var romcoms = [
{
"cat":"Rom-coms",
"ques":"Who stars as a television morning show producer named Becky, opposite Harrison Ford and Diane Keaton in 2010's Morning Glory?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
},
{
"cat":"Rom-coms",
"ques":"This 2001 film starring Renee Zellweger follows a year in the life of a British woman who is determined to improve herself while she looks for love.",
"answ":"BRIDGET JONES'S DIARY",
"answ3":"BRIDGET JONES' DIARY",
"answ2":"Bridget Jones's Diary.",
},
{
"cat":"Rom-coms",
"ques":"Adam Sandler plays Henry Roth, a veterinarian living in Hawaii in what 2000s rom-com?",
"answ":"50 FIRST DATES",
"answ3":"FIFTY FIRST DATES",
"answ2":"50 First Dates.",
},
{
"cat":"Rom-coms",
"ques":"What Oscar winning actress plays author Barbara Novak in the film Down with Love?",
"answ":"RENEE ZELLWEGER",
"answ2":"Renée Zellweger.",
},
{
"cat":"Rom-coms",
"ques":"Which actress stars in the rom-coms The Holiday, The Other Woman and Sex Tape?",
"answ":"CAMERON DIAZ",
"answ2":"Cameron Diaz.",
},
{
"cat":"Rom-coms",
"ques":"Who played the large-nosed Charlie in 1987's Roxanne?",
"answ":"STEVE MARTIN",
"answ2":"Steve Martin.",
},
{
"cat":"Rom-coms",
"ques":"Rosamund Pike plays Jane, Keira Knightley's sister, in what 2005 film?",
"answ":"PRIDE AND PREJUDICE",
"answ2":"Pride & Prejudice.",
},
{
"cat":"Rom-coms",
"ques":"Which actress stars in the rom-coms Killers, Life As We Know It and The Big Wedding?",
"answ":"KATHERINE HEIGL",
"answ2":"Katherine Heigl.",
},
{
"cat":"Rom-coms",
"ques":"This actress starred in the 90s romcoms French Kiss, IQ and Addicted To Love?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Rom-coms",
"ques":"Andy Tennant directed Salma Hayek and which Friends actor as Alex Whitman, in the 1997 rom-com Fools Rush In?",
"answ":"MATTHEW PERRY",
"answ2":"Matthew Perry.",
},
{
"cat":"Rom-coms",
"ques":"Who directed the rom-coms Say Anything, Elizabethtown and Aloha?",
"answ":"CAMERON CROWE",
"answ2":"Cameron Crowe.",
},
{
"cat":"Rom-coms",
"ques":"What 90s rom-com features supporting performances from Matt Dillon, Chris Elliot and Brett Favre?",
"answ":"THERE'S SOMETHING ABOUT MARY",
"answ2":"There's Something About Mary.",
},
{
"cat":"Rom-coms",
"ques":"In Sweet Home Alabama, who plays Reese Witherspoon's socialite fiance Andrew?",
"answ":"PATRICK DEMPSEY",
"answ2":"Patrick Dempsey.",
},
{
"cat":"Rom-coms",
"ques":"Which actress co-starred in the rom-coms Forgetting Sarah Marshall and Friends With Benefits?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
},
{
"cat":"Rom-coms",
"ques":"Which actress starred in the rom-coms Raising Helen, My Best Friend's Girl and Something Borrowed?",
"answ":"KATE HUDSON",
"answ2":"Kate Hudson.",
},
{
"cat":"Rom-coms",
"ques":"Which actress co-stars with Hugh Grant as the character of Lucy Kelson, in the 2002 rom-com Two Weeks Notice?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
},
{
"cat":"Rom-coms",
"ques":"What rom-com starring Seth Rogen has the tagline: 'Save The Due Date'?",
"answ":"KNOCKED UP",
"answ2":"Knocked Up.",
},
{
"cat":"Rom-coms",
"ques":"Which actress co-starred with Justin Timberlake in the rom-com Friends With Benefits, playing the character of Jamie?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
},
{
"cat":"Rom-coms",
"ques":"Emilia Clarke stars in the romantic comedy Last Christmas, who is her male co-star?",
"answ":"HENRY GOLDING",
"answ2":"Henry Golding.",
},
{
"cat":"Rom-coms",
"ques":"Who directed 2019's Last Christmas?",
"answ":"PAUL FEIG",
"answ2":"Paul Feig.",
},
{
"cat":"Rom-coms",
"ques":"Billy Wilder directed Tony Curtis and Jack Lemmon as crossdressing musicians in which 1959 romantic comedy?",
"answ":"SOME LIKE IT HOT",
"answ2":"Some Like It Hot.",
},
{
"cat":"Rom-coms",
"ques":"In 10 Things I Hate About You, Heath Ledger's character sings what song to Julia Stiles' character?",
"answ":"CAN'T TAKE MY EYES OFF YOU",
"answ2":"Can't Take My Eyes Off You.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Ryan Gosling's love interest Emily, in Crazy, Stupid, Love?",
"answ":"EMMA STONE",
"answ2":"Emma Stone.",
},
{
"cat":"Rom-coms",
"ques":"What 2019 rom-com fantasy was directed by Danny Boyle and starred Himesh Patel and Lily James?",
"answ":"YESTERDAY",
"answ2":"Yesterday.",
},
{
"cat":"Rom-coms",
"ques":"Which actor plays Pat Solitano Senior, father of Bradley Cooper's character in Silver Lining's Playbook?",
"answ":"ROBERT DE NIRO",
"answ3":"ROBERT DENIRO",
"answ2":"Robert De Niro.",
},
{
"cat":"Rom-coms",
"ques":"Andrew Lincoln holds up cards with love messages on them for what actress to read in Love Actually?",
"answ":"KEIRA KNIGHTLEY",
"answ2":"Keira Knightley.",
},
{
"cat":"Rom-coms",
"ques":"Jack Lemmon, Tony Curtis and Marilyn Monroe star in what famous 1959 rom-com?",
"answ":"SOME LIKE IT HOT",
"answ2":"Some Like It Hot.",
},
{
"cat":"Rom-coms",
"ques":"Martha Coolidge directed Nicolas Cage and Deborah Foreman in what 1983 teen romcom?",
"answ":"VALLEY GIRL",
"answ2":"Valley Girl.",
},
{
"cat":"Rom-coms",
"ques":"What is the title of the 2016 Bridget Jones sequel in which Bridget discovers that she is pregnant?",
"answ":"BRIDGET JONES'S BABY",
"answ3":"BRIDGET JONES' BABY",
"answ2":"Bridget Jones's Baby.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Julianne Potter, a 27-year-old food critic who realizes she's in love with her best friend Michael, in My Best Friend's Wedding?",
"answ":"JULIA ROBERTS",
"answ2":"Julia Roberts.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Tiffany Maxwell in Silver Linings Playbook?",
"answ":"JENNIFER LAWRENCE",
"answ2":"Jennifer Lawrence.",
},
{
"cat":"Rom-coms",
"ques":"What 2018 romantic comedy stars Constance Wu, Henry Golding and Awkwafina?",
"answ":"CRAZY RICH ASIANS",
"answ2":"Crazy Rich Asians.",
},
{
"cat":"Rom-coms",
"ques":"Which actress plays Paul Rudd's fiance in I Love You, Man?",
"answ":"RASHIDA JONES",
"answ2":"Rashida Jones.",
},
{
"cat":"Rom-coms",
"ques":"Hugh Jackman and Meg Ryan starred in what 2001 romantic comedy?",
"answ":"KATE AND LEOPOLD",
"answ2":"Kate & Leopold.",
},
{
"cat":"Rom-coms",
"ques":"Emma Stone starred as Olive Penderghast, a modern day Hester Prynne in this film inspired by The Scarlet Letter.",
"answ":"EASY A",
"answ2":"Easy A.",
},
{
"cat":"Rom-coms",
"ques":"This 2001 romantic comedy, about a dysfunctional Hollywood relationship, starred John Cusack, Catherine Zeta-Jones, Billy Crystal and Julia Roberts.",
"answ":"AMERICA'S SWEETHEARTS",
"answ2":"America's Sweethearts.",
},
{
"cat":"Rom-coms",
"ques":"Who plays the daughter of Ryan Reynold's character in Definitely, Maybe?",
"answ":"ABIGAIL BRESLIN",
"answ2":"Abigail Breslin.",
},
{
"cat":"Rom-coms",
"ques":"Natalie Portman starred opposite Ashton Kutcher in what 2011 romantic comedy?",
"answ":"NO STRINGS ATTACHED",
"answ2":"No Strings Attached.",
},
{
"cat":"Rom-coms",
"ques":"What 2012 rom-com stars Jason Segel and Emily Blunt as a couple struggling to get married?",
"answ":"THE FIVE YEAR ENGAGEMENT",
"answ3":"FIVE YEAR ENGAGEMENT",
"answ2":"The Five-Year Engagement.",
},
{
"cat":"Rom-coms",
"ques":"Who played wedding columnist Iris Simpkins, in The Holiday?",
"answ":"KATE WINSLET",
"answ2":"Kate Winslet.",
},
{
"cat":"Rom-coms",
"ques":"Name one of the two actresses in the 2003 rom-com Under the Tuscan Sun directed by Audrey Wells.",
"answ":"DIANE LANE",
"answ3":"SANDRA OH",
"answ2":"Diane Lane/Sandra Oh.",
},
{
"cat":"Rom-coms",
"ques":"What 2002 romantic comedy stars Jennifer Lopez and Ralph Fiennes?",
"answ":"MAID IN MANHATTAN",
"answ2":"Maid in Manhattan.",
},
{
"cat":"Rom-coms",
"ques":"Who played playboy Henry Roth in 50 First Dates?",
"answ":"ADAM SANDLER",
"answ2":"Adam Sandler.",
},
{
"cat":"Rom-coms",
"ques":"Vince Vaughn and Jennifer Aniston starred in this 2006 romantic comedy about the end of a relationship.",
"answ":"THE BREAK UP",
"answ3":"BREAK UP",
"answ2":"The Break-Up.",
},
{
"cat":"Rom-coms",
"ques":"Freddie Prinze Jr. and Rachael Leigh Cook starred in what 1999 rom-com?",
"answ":"SHE'S ALL THAT",
"answ2":"She's All That.",
},
{
"cat":"Rom-coms",
"ques":"Emma Stone and Ryan Gosling both starred in La La Land, in which rom-com did they made their first movie debut together?",
"answ":"CRAZY STUPID LOVE",
"answ2":"Crazy Stupid Love.",
},
{
"cat":"Rom-coms",
"ques":"Matthew McConaughey stars alongside Sarah Jessica Parker in what 2006 romantic comedy?",
"answ":"FAILURE TO LAUNCH",
"answ2":"Failure to Launch.",
},
{
"cat":"Rom-coms",
"ques":"In Notting Hill, what kind of shop did Hugh Grant's character own?",
"answ":"BOOK SHOP",
"answ3":"BOOK STORE",
"answ2":"Book shop.",
},
{
"cat":"Rom-coms",
"ques":"Who directed Bridesmaids?",
"answ":"PAUL FEIG",
"answ3":"PAUL FIEG",
"answ2":"Paul Feig.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Mikey's mother in Look Who's Talking?",
"answ":"KIRSTIE ALLEY",
"answ2":"Kirstie Alley.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Dr. Aaron Connors, Amy Schumer's co-lead in Trainwreck?",
"answ":"BILL HADER",
"answ2":"Bill Hader.",
},
{
"cat":"Rom-coms",
"ques":"What city is the setting for 2001's Amelie?",
"answ":"PARIS",
"answ2":"Paris.",
},
{
"cat":"Rom-coms",
"ques":"In The Devil Wears Prada, what star of TV's The Mentalist, plays Christian Thompson, a writer that Anne Hathaway's character sleeps with during her trip to Paris?",
"answ":"SIMON BAKER",
"answ2":"Simon Baker.",
},
{
"cat":"Rom-coms",
"ques":"Who plays the love interest to CIA agents and best friends Tom Hardy and Chris Pine in This Means War?",
"answ":"REESE WITHERSPOON",
"answ3":"REESE WITHERSPOONE",
"answ2":"Reese Witherspoon.",
},
{
"cat":"Rom-coms",
"ques":"Who does Sandra Bullock romance in The Proposal?",
"answ":"RYAN REYNOLDS",
"answ2":"Ryan Reynolds.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Jack Nicholson's co-lead, Erica, in Something's Gotta Give?",
"answ":"DIANE KEATON",
"answ2":"Diane Keaton.",
},
{
"cat":"Rom-coms",
"ques":"Who played Steve Carell's cheating wife in Crazy, Stupid, Love?",
"answ":"JULIANNE MOORE",
"answ3":"JULIANE MOORE",
"answ2":"Julianne Moore.",
},
{
"cat":"Rom-coms",
"ques":"Garry Marshall directed Valentine's Day, Mother's Day and what other film named after a holiday?",
"answ":"NEW YEAR'S EVE",
"answ2":"New Year's Eve.",
},
{
"cat":"Rom-coms",
"ques":"Josh Lucas plays Jake, a former flame to Reese Witherspoon in what movie?",
"answ":"SWEET HOME ALABAMA",
"answ2":"Sweet Home Alabama.",
},
{
"cat":"Rom-coms",
"ques":"Which actress plays the unfaithful girlfriend of Joseph Gordon-Levitt's character at the outset of 50/50?",
"answ":"BRYCE DALLAS HOWARD",
"answ2":"Bryce Dallas Howard.",
},
{
"cat":"Rom-coms",
"ques":"Who played Muriel Heslop in the film Muriel's Wedding?",
"answ":"TONI COLLETTE",
"answ3":"TONI COLETTE",
"answ2":"Toni Collette.",
},
{
"cat":"Rom-coms",
"ques":"Who played Rosalee Futch who wins a date with Tad in the film Win a Date with Tad Hamilton!?",
"answ":"KATE BOSWORTH",
"answ3":"CATE BOSWORTH",
"answ2":"Kate Bosworth.",
},
{
"cat":"Rom-coms",
"ques":"Who played Sarah Marshall in Forgetting Sarah Marshall?",
"answ":"KRISTEN BELL",
"answ2":"Kristen Bell.",
},
{
"cat":"Rom-coms",
"ques":"Who co-starred as the friend/love interest of Mila Kunis in 2011's Friends with Benefits?",
"answ":"JUSTIN TIMBERLAKE",
"answ2":"Justin Timberlake.",
},
{
"cat":"Rom-coms",
"ques":"Drew Barrymore plays Josie Geller, who gets the nickname Josie Grossy in what movie?",
"answ":"NEVER BEEN KISSED",
"answ2":"Never Been Kissed.",
},
{
"cat":"Rom-coms",
"ques":"What film had Daryl Hannah's character wooed by a big-nosed fire chief?",
"answ":"ROXANNE",
"answ2":"Roxanne.",
},
{
"cat":"Rom-coms",
"ques":"In Sweet Home Alabama, what does Jake sell in his shop?",
"answ":"GLASS",
"answ3":"GLASS SCULPTURES",
"answ2":"Glass.",
},
{
"cat":"Rom-coms",
"ques":"Who starred as the freshly dumped Hawaii-bound Peter Bretter in Forgetting Sarah Marshall?",
"answ":"JASON SEGEL",
"answ3":"JASON SIEGEL",
"answ2":"Jason Segel.",
},
{
"cat":"Rom-coms",
"ques":"On which holiday do Sam and Annie meet at the end of 1993's Sleepless in Seattle?",
"answ":"VALENTINE'S DAY",
"answ3":"VALENTINE DAY",
"answ2":"Valentine's Day.",
},
{
"cat":"Rom-coms",
"ques":"What office rom-com stars Melanie Griffith, Sigourney Weaver and Harrison Ford?",
"answ":"WORKING GIRL",
"answ2":"Working Girl.",
},
{
"cat":"Rom-coms",
"ques":"Who is Jennifer Lopez's co-star in Maid in Manhattan?",
"answ":"RALPH FIENNES",
"answ3":"RALPH FIENES",
"answ2":"Ralph Fiennes.",
},
{
"cat":"Rom-coms",
"ques":"Who played Cher Horowitz in the movie Clueless?",
"answ":"ALICIA SILVERSTONE",
"answ2":"Alicia Silverstone.",
},
{
"cat":"Rom-coms",
"ques":"What law school does Elle Woods attend in Legally Blonde?",
"answ":"HARVARD",
"answ3":"HARVARD LAW SCHOOL",
"answ2":"Harvard.",
},
{
"cat":"Rom-coms",
"ques":"What actress played Sarah Huttinger in 2005's Rumor Has It?",
"answ":"JENNIFER ANISTON",
"answ2":"Jennifer Aniston.",
},
{
"cat":"Rom-coms",
"ques":"What actor can be seen as Daniel Cleaver in Bridget Jones' Diary?",
"answ":"HUGH GRANT",
"answ2":"Hugh Grant.",
},
{
"cat":"Rom-coms",
"ques":"In It Could Happen to You, what actor plays the cop who wins the lottery opposite Bridget Fonda?",
"answ":"NICOLAS CAGE",
"answ3":"NIC CAGE",
"answ2":"Nicolas Cage.",
},
{
"cat":"Rom-coms",
"ques":"In the beginning of Sleepless in Seatle, Tom Hanks moved to Seattle from what city?",
"answ":"CHICAGO",
"answ2":"Chicago.",
},
{
"cat":"Rom-coms",
"ques":"What classic 1980s song do all of the characters dance to in 13 Going on 30?",
"answ":"THRILLER",
"answ2":"Thriller.",
},
{
"cat":"Rom-coms",
"ques":"Who played the role of Kimberly in 1997's My Best Friend's Wedding?",
"answ":"CAMERON DIAZ",
"answ2":"Cameron Diaz.",
},
{
"cat":"Rom-coms",
"ques":"Who plays Josie's older brother in Never Been Kissed?",
"answ":"DAVID ARQUETTE",
"answ2":"David Arquette.",
},
{
"cat":"Rom-coms",
"ques":"Which cast member meets and hooks Up with Marisa Tomei's character in Crazy Stupid Love?",
"answ":"STEVE CARELL",
"answ2":"Steve Carell.",
},
{
"cat":"Rom-coms",
"ques":"Which film sees Meg Ryan travel abroad to contront the less than faithful Timothy Hutton?",
"answ":"FRENCH KISS",
"answ2":"French Kiss.",
},
{
"cat":"Rom-coms",
"ques":"The tune Grow Old With You is performed during the climax of what movie?",
"answ":"THE WEDDING SINGER",
"answ2":"The Wedding Singer.",
},
{
"cat":"Rom-coms",
"ques":"You'll find boutique bookseller Kathleen Kelly and corporate chain Fox Books in what 1998 film?",
"answ":"YOU'VE GOT MAIL",
"answ2":"You've Got Mail.",
},
{
"cat":"Rom-coms",
"ques":"What film paired Gerard Butler and Jennifer Aniston as feuding exes?",
"answ":"THE BOUNTY HUNTER",
"answ3":"BOUNTY HUNTER",
"answ2":"The Bounty Hunter.",
},
{
"cat":"Rom-coms",
"ques":"In Bride Wars, Kate Hudson faces off against her best friend played by whom?",
"answ":"ANNE HATHAWAY",
"answ2":"Anne Hathaway.",
},
{
"cat":"Rom-coms",
"ques":"What film do Emma Stone and Ryan Gosling reenact in Crazy Stupid Love?",
"answ":"DIRTY DANCING",
"answ2":"Dirty Dancing.",
},
{
"cat":"Rom-coms",
"ques":"What Academy Award winning actor plays Annie Hall's brother in the film Annie Hall?",
"answ":"CHRISTOPHER WALKEN",
"answ2":"Christopher Walken.",
},
{
"cat":"Rom-coms",
"ques":"What is the subtitle of The Princess Diaries 2?",
"answ":"ROYAL ENGAGEMENT",
"answ2":"Royal Engagement.",
},
{
"cat":"Rom-coms",
"ques":"Who switches homes with Kate Winslet in The Holiday?",
"answ":"CAMERON DIAZ",
"answ2":"Cameron Diaz.",
},
{
"cat":"Rom-coms",
"ques":"Who played Tad Hamilton in Win a Date with Tad Hamilton!?",
"answ":"JOSH DUHAMEL",
"answ2":"Josh Duhamel.",
},
{
"cat":"Rom-coms",
"ques":"What 2001 rom-com stars Julia Roberts, John Cusack and Catherine Zeta-Jones?",
"answ":"AMERICA'S SWEETHEARTS",
"answ2":"America's Sweethearts.",
},
{
"cat":"Rom-coms",
"ques":"Who played Alicia Silverstone's ex-stepbrother Josh in Clueless?",
"answ":"PAUL RUDD",
"answ2":"Paul Rudd.",
},
{
"cat":"Rom-coms",
"ques":"Who plays the new cashier that Dane Cook and Dax Shepard are fighting over in Employee of the Month?",
"answ":"JESSICA SIMPSON",
"answ2":"Jessica Simpson.",
},
{
"cat":"Rom-coms",
"ques":"What actress plays the lead role in 27 Dresses?",
"answ":"KATHERINE HEIGL",
"answ2":"Katherine Heigl.",
},
{
"cat":"Rom-coms",
"ques":"In which film do you find Ryan Gosling professing his love to a mannequin?",
"answ":"LARS AND THE REAL GIRL",
"answ2":"Lars and the Real Girl.",
},
{
"cat":"Rom-coms",
"ques":"Who played the rock star in Forgetting Sarah Marshall?",
"answ":"RUSSELL BRAND",
"answ2":"Russell Brand.",
},
{
"cat":"Rom-coms",
"ques":"Who played Bridget in Bridget Jones' Diary?",
"answ":"RENEE ZELLWEGER",
"answ2":"Renée Zellweger.",
},
{
"cat":"Rom-coms",
"ques":"What actress played lead character Lelaina Pierce in Reality Bites?",
"answ":"WINONA RYDER",
"answ2":"Winona Ryder.",
},
{
"cat":"Rom-coms",
"ques":"Who played Harry in When Harry Met Sally...?",
"answ":"BILLY CRYSTAL",
"answ2":"Billy Crystal.",
},
{
"cat":"Rom-coms",
"ques":"Who played Sally in When Harry Met Sally...?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Rom-coms",
"ques":"What rom-com featured Will Smith and Eva Mendes?",
"answ":"HITCH",
"answ2":"Hitch.",
},
{
"cat":"Rom-coms",
"ques":"Which rom-com stars Heath Ledger and Julia Stiles?",
"answ":"10 THINGS I HATE ABOUT YOU",
"answ3":"TEN THINGS I HATE ABOUT YOU",
"answ2":"10 Things I Hate About You.",
},
{
"cat":"Rom-coms",
"ques":"In Rumor Has It, a woman learns her family may have been the inspiration for what classic book and film?",
"answ":"THE GRADUATE",
"answ2":"The Graduate.",
},
{
"cat":"Rom-coms",
"ques":"Who was John Cusack's love interest in Serendipity?",
"answ":"KATE BECKINSALE",
"answ3":"CATE BECKINSALE",
"answ2":"Kate Beckinsale.",
},
{
"cat":"Rom-coms",
"ques":"Who directed Valentine's Day and New Year's Eve?",
"answ":"GARRY MARSHALL",
"answ3":"GARY MARSHALL",
"answ2":"Garry Marshall.",
},
{
"cat":"Rom-coms",
"ques":"What actress played the lead in Someone like You?",
"answ":"ASHLEY JUDD",
"answ2":"Ashley Judd.",
},
{
"cat":"Rom-coms",
"ques":"Who played Kate in Kate & Leopold?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Rom-coms",
"ques":"Who played Leopold in Kate & Leopold?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
},
{
"cat":"Rom-coms",
"ques":"This actor starred in and directed Reality Bites.",
"answ":"BEN STILLER",
"answ2":"Ben Stiller.",
},
{
"cat":"Rom-coms",
"ques":"In what movie does Hugh Grant ask the object of his affection NOT to marry him?",
"answ":"FOUR WEDDINGS AND A FUNERAL",
"answ3":"4 WEDDINGS AND A FUNERAL",
"answ2":"Four Weddings and a Funeral.",
},
{
"cat":"Rom-coms",
"ques":"What famous comedian plays Tom Hanks' best friend in You've Got Mail?",
"answ":"DAVE CHAPPELLE",
"answ3":"DAVE CHAPELLE",
"answ2":"Dave Chappelle.",
},
{
"cat":"Rom-coms",
"ques":"Who played Drew Barrymore's steroid loving brother in 50 First Dates?",
"answ":"SEAN ASTIN",
"answ2":"Sean Astin.",
},
{
"cat":"Rom-coms",
"ques":"Matthew McConaughey stars alongside whom in How to Lose a Guy in 10 Days?",
"answ":"KATE HUDSON",
"answ2":"Kate Hudson.",
},
{
"cat":"Rom-coms",
"ques":"Before Jack Nicholson falls for Diane Keaton in Something's Gotta Give he's dating Keaton's daughter played by whom?",
"answ":"AMANDA PEET",
"answ2":"Amanda Peet.",
},
{
"cat":"Rom-coms",
"ques":"Name the film that starred Adam Sandler and Jennifer Aniston as his assistant posing as his ex-wife.",
"answ":"JUST GO WITH IT",
"answ2":"Just Go With It.",
},
{
"cat":"Rom-coms",
"ques":"Who plays the title role in the 2001 romantic comedy The Wedding Planner?",
"answ":"JENNIFER LOPEZ",
"answ2":"Jennifer Lopez.",
},
{
"cat":"Rom-coms",
"ques":"In Bridget Jones' Diary, Colin Firth and what other actor vie for Bridget's affection?",
"answ":"HUGH GRANT",
"answ2":"Hugh Grant.",
},
{
"cat":"Rom-coms",
"ques":"Which rom-com involves the New York Knicks, a magazine called Composure and a diamond ad campaign?",
"answ":"HOW TO LOSE A GUY IN 10 DAYS",
"answ3":"HOW TO LOSE A GUY IN TEN DAYS",
"answ2":"How to Lose a Guy in 10 Days.",
},
{
"cat":"Rom-coms",
"ques":"Of the movies Housesitter, Houseguest and Bringing Down the House, which one stars Sinbad?",
"answ":"HOUSEGUEST",
"answ2":"Houseguest.",
},
];
var r2Q12 = [
{
"cat":"Rom-coms",
"ques":"Who directed He's Just Not That Into You?",
"answ":"KEN KWAPIS",
"answ2":"Ken Kwapis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Hughes</button><button id=corop class=buttons003 onclick=qcor()>Ken Kwapis</button><button id=incop3 class=buttons003 onclick=qinc()>Dennis Dugan</button><button id=incop4 class=buttons003 onclick=qinc()>Peyton Reed</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Jerry Maguire is the sports agent for Rod Tidwell who plays for what NFL team?",
"answ":"ARIZONA CARDINALS",
"answ2":"Arizona Cardinals.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Los Angeles Rams</button><button id=corop class=buttons003 onclick=qcor()>Arizona Cardinals</button><button id=incop3 class=buttons003 onclick=qinc()>Denver Broncos</button><button id=incop4 class=buttons003 onclick=qinc()>Seattle Seahawks</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In The 40-Year-Old Virgin, what musician does Jane Lynch always have playing on the TVs at Smart Tech?",
"answ":"MICHAEL MCDONALD",
"answ2":"Michael McDonald.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kenny Rogers</button><button id=corop class=buttons003 onclick=qcor()>Michael McDonald</button><button id=incop3 class=buttons003 onclick=qinc()>Johnny Cash</button><button id=incop4 class=buttons003 onclick=qinc()>Willie Nelson</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played Jennifer Garner's flamboyant boss in 13 Going on 30?",
"answ":"ANDY SERKIS",
"answ2":"Andy Serkis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kevin Spacey</button><button id=corop class=buttons003 onclick=qcor()>Andy Serkis</button><button id=incop3 class=buttons003 onclick=qinc()>Benedict Cumberbatch</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Bateman</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What sport do Nina and George Banks play together the day before her wedding in 1991's Father of the Bride?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tennis</button><button id=incop2 class=buttons003 onclick=qinc()>Football</button><button id=incop3 class=buttons003 onclick=qinc()>Baseball</button><button id=corop class=buttons003 onclick=qcor()>Basketball</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What does Channing Tatum shove up his nose in She's the Man?",
"answ":"TAMPON",
"answ3":"A TAMPON",
"answ2":"Tampon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Beans</button><button id=incop2 class=buttons003 onclick=qinc()>LEGO brick</button><button id=incop3 class=buttons003 onclick=qinc()>Pencil</button><button id=corop class=buttons003 onclick=qcor()>Tampon</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What 1995 rom-com stars Hugh Grant and Julianne Moore?",
"answ":"NINE MONTHS",
"answ3":"9 MONTHS",
"answ2":"Nine Months.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nine Months</button><button id=incop2 class=buttons003 onclick=qinc()>Notting Hill</button><button id=incop3 class=buttons003 onclick=qinc()>Two Weeks Notice</button><button id=incop4 class=buttons003 onclick=qinc()>Mickey Blue Eyes</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Pretty Woman what is the rule Julia Roberts' character abides by?",
"answ":"NO KISSING ON THE MOUTH",
"answ3":"NO KISSES ON THE MOUTH",
"answ2":"No kissing on the mouth.",
"option":"<button id=corop class=buttons003 onclick=qcor()>No kissing on the mouth</button><button id=incop2 class=buttons003 onclick=qinc()>No last names</button><button id=incop3 class=buttons003 onclick=qinc()>No older men</button><button id=incop4 class=buttons003 onclick=qinc()>No sex on the first date</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Sam and Annie meet on Valentine's Day at the top of the Empire State Building in what romantic comedy?",
"answ":"SLEEPLESS IN SEATTLE",
"answ2":"Sleepless in Seattle.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sleepless in Seattle</button><button id=incop2 class=buttons003 onclick=qinc()>French Kiss</button><button id=incop3 class=buttons003 onclick=qinc()>You've Got Mail</button><button id=incop4 class=buttons003 onclick=qinc()>Addicted to Love</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"A journalist enrolls into her old high school as part of her research for a story in what rom-com?",
"answ":"NEVER BEEN KISSED",
"answ2":"Never Been Kissed.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Never Been Kissed</button><button id=incop2 class=buttons003 onclick=qinc()>You've Got Mail</button><button id=incop3 class=buttons003 onclick=qinc()>Legally Blonde</button><button id=incop4 class=buttons003 onclick=qinc()>How to Lose a Guy in 10 Days</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played the title role in the original Sabrina?",
"answ":"AUDREY HEPBURN",
"answ3":"AUDREY HEPBURNE",
"answ2":"Audrey Hepburn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Audrey Hepburn</button><button id=incop2 class=buttons003 onclick=qinc()>Katharine Hepburn</button><button id=incop3 class=buttons003 onclick=qinc()>Ingrid Bergman</button><button id=incop4 class=buttons003 onclick=qinc()>Joan Crawford</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who plays Amy Schumer's father in Trainwreck?",
"answ":"COLIN QUINN",
"answ3":"COLIN QUIN",
"answ2":"Colin Quinn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop2 class=buttons003 onclick=qinc()>J.K. Simmons</button><button id=incop3 class=buttons003 onclick=qinc()>Harvey Keitel</button><button id=corop class=buttons003 onclick=qcor()>Colin Quinn</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In which rom-com does Kate Beckinsale write her phone number in the novel Love in the Time of Cholera?",
"answ":"SERENDIPITY",
"answ2":"Serendipity.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Everybody's Fine</button><button id=incop2 class=buttons003 onclick=qinc()>Nothing but the Truth</button><button id=incop3 class=buttons003 onclick=qinc()>Me Before You</button><button id=corop class=buttons003 onclick=qcor()>Serendipity</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Jack Nicholson falls for Diane Keaton in this 2003 romantic comedy.",
"answ":"SOMETHING'S GOTTA GIVE",
"answ2":"Something's Gotta Give.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The First Wives Club</button><button id=incop2 class=buttons003 onclick=qinc()>Morning Glory</button><button id=incop3 class=buttons003 onclick=qinc()>Town & Country</button><button id=corop class=buttons003 onclick=qcor()>Something's Gotta Give</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Which sorority was Elle Woods from Legally Blonde president of?",
"answ":"DELTA NU",
"answ2":"Delta Nu.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Phi Lambda</button><button id=corop class=buttons003 onclick=qcor()>Delta Nu</button><button id=incop3 class=buttons003 onclick=qinc()>Kappa Kappa Delta</button><button id=incop4 class=buttons003 onclick=qinc()>Zeta Alpha Zeta</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In which movie does Hugh Grant declare love for Andie MacDowell?",
"answ":"FOUR WEDDINGS AND A FUNERAL",
"answ3":"4 WEDDINGS AND A FUNERAL",
"answ2":"Four Weddings and a Funeral.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Notting Hill</button><button id=corop class=buttons003 onclick=qcor()>Four Weddings and a Funeral</button><button id=incop3 class=buttons003 onclick=qinc()>Mickey Blue Eyes</button><button id=incop4 class=buttons003 onclick=qinc()>About a Boy</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Which color M&Ms are Mary's favorite in The Wedding Planner?",
"answ":"BROWN",
"answ2":"Brown.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blue</button><button id=corop class=buttons003 onclick=qcor()>Brown</button><button id=incop3 class=buttons003 onclick=qinc()>Yellow</button><button id=incop4 class=buttons003 onclick=qinc()>Orange</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who plays the older Jenna in the 2004 movie 13 Going on 30?",
"answ":"JENNIFER GARNER",
"answ2":"Jennifer Garner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anne Hathaway</button><button id=corop class=buttons003 onclick=qcor()>Jennifer Garner</button><button id=incop3 class=buttons003 onclick=qinc()>Katie Holmes</button><button id=incop4 class=buttons003 onclick=qinc()>Eva Green</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What city does Kat travel to, to be a maid of honor for her younger sister in The Wedding Date?",
"answ":"LONDON",
"answ2":"London.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paris</button><button id=incop2 class=buttons003 onclick=qinc()>New York</button><button id=incop3 class=buttons003 onclick=qinc()>Los Angeles</button><button id=corop class=buttons003 onclick=qcor()>London</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What character punches Joey in the face in 10 Things I Hate About You?",
"answ":"BIANCA",
"answ2":"Bianca.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cameron</button><button id=incop2 class=buttons003 onclick=qinc()>Patrick</button><button id=incop3 class=buttons003 onclick=qinc()>Kat</button><button id=corop class=buttons003 onclick=qcor()>Bianca</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What is Vivian's best friend's first name in Pretty Woman?",
"answ":"KIT",
"answ2":"Kit.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Karen</button><button id=incop2 class=buttons003 onclick=qinc()>Kat</button><button id=corop class=buttons003 onclick=qcor()>Kit</button><button id=incop4 class=buttons003 onclick=qinc()>Kath</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Aldous Snow moves in on Peter's actress ex-girlfriend in this 2008 film.",
"answ":"FORGETTING SARAH MARSHALL",
"answ3":"FORGETTING SARA MARSHALL",
"answ2":"Forgetting Sarah Marshall.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Get Him to the Greek</button><button id=incop2 class=buttons003 onclick=qinc()>Superbad</button><button id=corop class=buttons003 onclick=qcor()>Forgetting Sarah Marshall</button><button id=incop4 class=buttons003 onclick=qinc()>Knocked Up</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Freddie Prinze Jr. stars as big man on campus Zack Siler in what 90s rom-coms?",
"answ":"SHE'S ALL THAT",
"answ2":"She's All That.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Clueless</button><button id=incop2 class=buttons003 onclick=qinc()>10 Things I Hate About You</button><button id=corop class=buttons003 onclick=qcor()>She's All That</button><button id=incop4 class=buttons003 onclick=qinc()>Jawbreaker</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played Mike Chadway in The Ugly Truth?",
"answ":"GERARD BUTLER",
"answ2":"Gerard Butler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugh Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Adam Sandler</button><button id=corop class=buttons003 onclick=qcor()>Gerard Butler</button><button id=incop4 class=buttons003 onclick=qinc()>Channing Tatum</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In When Harry Met Sally, while driving to New York, Harry and Sally debate the ending of what classic film?",
"answ":"CASABLANCA",
"answ2":"Casablanca.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gone with the Wind</button><button id=incop2 class=buttons003 onclick=qinc()>It's A Wonderful Life</button><button id=corop class=buttons003 onclick=qcor()>Casablanca</button><button id=incop4 class=buttons003 onclick=qinc()>Citizen Kane</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What comedy starring Channing Tatum and Amanda Bynes is an adaptation of Shakespeare's Twelfth Night?",
"answ":"SHE'S THE MAN",
"answ2":"She's the Man.",
"option":"<button id=corop class=buttons003 onclick=qcor()>She's the Man</button><button id=incop2 class=buttons003 onclick=qinc()>What I Like About You</button><button id=incop3 class=buttons003 onclick=qinc()>Easy A</button><button id=incop4 class=buttons003 onclick=qinc()>Bend It Like Beckham</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Bridesmaids, after the engagement party Annie goes home an bakes what for herself?",
"answ":"A CUPCAKE",
"answ3":"CUPCAKE",
"answ2":"A cupcake.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A cookie</button><button id=incop2 class=buttons003 onclick=qinc()>A donut</button><button id=incop3 class=buttons003 onclick=qinc()>A cake</button><button id=corop class=buttons003 onclick=qcor()>A cupcake</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In 500 Days of Summer, what is Tom's favorite place in all of Los Angeles?",
"answ":"A PARK BENCH",
"answ3":"PARK BENCH",
"answ2":"A park bench.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A record store</button><button id=corop class=buttons003 onclick=qcor()>A park bench</button><button id=incop3 class=buttons003 onclick=qinc()>A movie theater</button><button id=incop4 class=buttons003 onclick=qinc()>A coffee shop</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Name the 90s rom-com that ends with Andie MacDowell telling Hugh Grant 'I do'?",
"answ":"FOUR WEDDINGS AND A FUNERAL",
"answ2":"Four Weddings and a Funeral.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Groundhog Day</button><button id=corop class=buttons003 onclick=qcor()>Four Weddings and a Funeral</button><button id=incop3 class=buttons003 onclick=qinc()>Four Rooms</button><button id=incop4 class=buttons003 onclick=qinc()>Multiplicity</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played matchmaker Emma Woodhouse in the 1996 film adaptation of Jane Austen's Emma?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emma Thompson</button><button id=incop2 class=buttons003 onclick=qinc()>Claire Danes</button><button id=corop class=buttons003 onclick=qcor()>Gwyneth Paltrow</button><button id=incop4 class=buttons003 onclick=qinc()>Kate Winslet</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In the movie I Love You Man, what did Peter and Sydney go out to eat on their first 'man-date'?",
"answ":"FISH TACOS",
"answ2":"Fish tacos.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Donuts</button><button id=incop2 class=buttons003 onclick=qinc()>Spaghetti tacos</button><button id=corop class=buttons003 onclick=qcor()>Fish tacos</button><button id=incop4 class=buttons003 onclick=qinc()>Pizza</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Love Actually, what popular TV actor plays Mark, the best man who was actually in love with Juliet, played by Keira Knightley?",
"answ":"ANDREW LINCOLN",
"answ2":"Andrew Lincoln.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Simon Baker</button><button id=incop2 class=buttons003 onclick=qinc()>Johnny Galecki</button><button id=corop class=buttons003 onclick=qcor()>Andrew Lincoln</button><button id=incop4 class=buttons003 onclick=qinc()>Michael C. Hall</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played 'bad boy' Patrick Verona in 10 Things I Hate About You?",
"answ":"HEATH LEDGER",
"answ2":"Heath Ledger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ashton Kutcher</button><button id=incop2 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=corop class=buttons003 onclick=qcor()>Heath Ledger</button><button id=incop4 class=buttons003 onclick=qinc()>Will Smith</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Ryan Reynolds tells his daughter the story of how he met her mother in what 2008 film?",
"answ":"DEFINITELY MAYBE",
"answ3":"DEFINITELY  MAYBE",
"answ2":"Definitely, Maybe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chaos Theory</button><button id=incop2 class=buttons003 onclick=qinc()>Fireflies in the Garden</button><button id=corop class=buttons003 onclick=qcor()>Definitely, Maybe</button><button id=incop4 class=buttons003 onclick=qinc()>Adventureland</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What was Amelie's occupation in the charming romantic comedy Amelie (2001)?",
"answ":"WAITRESS",
"answ2":"Waitress.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Market clerk</button><button id=incop2 class=buttons003 onclick=qinc()>Nanny</button><button id=incop3 class=buttons003 onclick=qinc()>Salon hairdresser</button><button id=corop class=buttons003 onclick=qcor()>Waitress</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In the rom-com/comedy Dave, who plays First Lady Ellen Mitchell?",
"answ":"SIGOURNEY WEAVER",
"answ2":"Sigourney Weaver.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emma Thompson</button><button id=incop2 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=incop3 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><button id=corop class=buttons003 onclick=qcor()>Sigourney Weaver</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In which film will you find Paul Rudd, a real estate agent, in search for a male best friend?",
"answ":"I LOVE YOU MAN",
"answ3":"I LOVE YOU  MAN",
"answ2":"I Love You, Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Knocked Up</button><button id=incop2 class=buttons003 onclick=qinc()>Forgetting Sarah Marshall</button><button id=incop3 class=buttons003 onclick=qinc()>Dinner for Schmucks</button><button id=corop class=buttons003 onclick=qcor()>I Love You, Man</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who plays reporter Kevin Doyle in 2008's 27 Dresses?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Matt Damon</button><button id=incop2 class=buttons003 onclick=qinc()>Dominic Monaghan</button><button id=incop3 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=corop class=buttons003 onclick=qcor()>James Marsden</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What film features original songs 'Brown Shoes', 'Girls' & 'Drive It Like You Stole It'?",
"answ":"SING STREET",
"answ2":"Sing Street.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mamma Mia! Here We Go Again</button><button id=incop2 class=buttons003 onclick=qinc()>Pitch Perfect</button><button id=incop3 class=buttons003 onclick=qinc()>School of Rock</button><button id=corop class=buttons003 onclick=qcor()>Sing Street</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Deborah Foreman played the title character in 1983's Valley Girl. Who played her punk-rocker love interest Randy?",
"answ":"NICOLAS CAGE",
"answ3":"NICHOLAS CAGE",
"answ2":"Nicolas Cage.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sean Penn</button><button id=corop class=buttons003 onclick=qcor()>Nicolas Cage</button><button id=incop3 class=buttons003 onclick=qinc()>Andrew Dice Clay</button><button id=incop4 class=buttons003 onclick=qinc()>Patrick Swayze</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Clueless, while being held at gunpoint, Cher refuses to lay on the ground because she doesn't want to ruin her dress by which important designer?",
"answ":"ALAIA",
"answ3":"ALAÏA",
"answ2":"Alaïa.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dior</button><button id=corop class=buttons003 onclick=qcor()>Alaïa</button><button id=incop3 class=buttons003 onclick=qinc()>Fiorucci</button><button id=incop4 class=buttons003 onclick=qinc()>Armani</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In the film Going The Distance, Drew Barrymore's character has the high score on what classic arcade game?",
"answ":"CENTIPEDE",
"answ2":"Centipede.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Centipede</button><button id=incop2 class=buttons003 onclick=qinc()>Asteroids</button><button id=incop3 class=buttons003 onclick=qinc()>Pac-Man</button><button id=incop4 class=buttons003 onclick=qinc()>Space Invaders</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Name the actress that played Emily's mother in The Big Sick.",
"answ":"HOLLY HUNTER",
"answ2":"Holly Hunter.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Holly Hunter</button><button id=incop2 class=buttons003 onclick=qinc()>Diane Lane</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=incop4 class=buttons003 onclick=qinc()>Kim Basinger</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played Andrew's mother, Grace Paxton in 2009's The Proposal?",
"answ":"MARY STEENBURGEN",
"answ2":"Mary Steenburgen.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mary Steenburgen</button><button id=incop2 class=buttons003 onclick=qinc()>Famke Janssen</button><button id=incop3 class=buttons003 onclick=qinc()>Helen Mirren</button><button id=incop4 class=buttons003 onclick=qinc()>Jane Seymour</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In 13 Going On 30, what color is the house that Matt and Jenna live in at the end of the film?",
"answ":"PINK",
"answ2":"Pink.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pink</button><button id=incop2 class=buttons003 onclick=qinc()>White</button><button id=incop3 class=buttons003 onclick=qinc()>Blue</button><button id=incop4 class=buttons003 onclick=qinc()>Brown</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Robin Williams is the reverend for John Krasinski and Mandy Moore's wedding in what film?",
"answ":"LICENSE TO WED",
"answ2":"License to Wed.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>It's Complicated</button><button id=incop2 class=buttons003 onclick=qinc()>The Holiday</button><button id=incop3 class=buttons003 onclick=qinc()>Smiley Face</button><button id=corop class=buttons003 onclick=qcor()>License to Wed</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Legally Blonde, the resume that Elle gives to Callahan is printed on pink paper. What else is it that, according to Elle, 'gives it a little something extra'?",
"answ":"IT'S SCENTED",
"answ3":"SCENTED",
"answ2":"It's scented.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>It's handwritten</button><button id=incop2 class=buttons003 onclick=qinc()>It's in French</button><button id=incop3 class=buttons003 onclick=qinc()>It contains pictures</button><button id=corop class=buttons003 onclick=qcor()>It's scented</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who plays Amy Schumer's sister in Trainwreck?",
"answ":"BRIE LARSON",
"answ2":"Brie Larson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kirsten Dunst</button><button id=incop2 class=buttons003 onclick=qinc()>Amy Adams</button><button id=incop3 class=buttons003 onclick=qinc()>Rebel Wilson</button><button id=corop class=buttons003 onclick=qcor()>Brie Larson</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Bridget Jones's Diary, Bridget is invited to what she thinks is a costume party. What does she dress up as?",
"answ":"PLAYBOY BUNNY",
"answ2":"Playboy Bunny.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nurse</button><button id=incop2 class=buttons003 onclick=qinc()>Clown</button><button id=incop3 class=buttons003 onclick=qinc()>Mummy</button><button id=corop class=buttons003 onclick=qcor()>Playboy Bunny</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Nick Cannon's Love Don't Cost a Thing is a remake of what 80s rom-com?",
"answ":"CAN'T BUY ME LOVE",
"answ2":"Can't Buy Me Love.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Splash</button><button id=incop2 class=buttons003 onclick=qinc()>Sixteen Candles</button><button id=incop3 class=buttons003 onclick=qinc()>Overboard</button><button id=corop class=buttons003 onclick=qcor()>Can't Buy Me Love</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Natalie Krinsky directed what 2020 rom-com about a young woman who starts a unique pop-up space after a break up?",
"answ":"THE BROKEN HEARTS GALLERY",
"answ3":"BROKEN HEARTS GALLERY",
"answ2":"The Broken Hearts Gallery.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Half Of It</button><button id=incop2 class=buttons003 onclick=qinc()>10 Things We Should Do Before We Break Up</button><button id=incop3 class=buttons003 onclick=qinc()>Break Up Story</button><button id=corop class=buttons003 onclick=qcor()>The Broken Hearts Gallery</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who played the female lead in The Beautician and the Beast?",
"answ":"FRAN DRESCHER",
"answ3":"FRAN DRESHER",
"answ2":"Fran Drescher.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pamela Reed</button><button id=incop2 class=buttons003 onclick=qinc()>Jennifer Lopez</button><button id=incop3 class=buttons003 onclick=qinc()>Diane Lane</button><button id=corop class=buttons003 onclick=qcor()>Fran Drescher</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Notting Hill, Will claims his wife left him for a man who looks like which Hollywood heavyweight actor?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>George Clooney</button><button id=incop2 class=buttons003 onclick=qinc()>Brad Pitt</button><button id=incop3 class=buttons003 onclick=qinc()>Denzel Washington</button><button id=corop class=buttons003 onclick=qcor()>Harrison Ford</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Legally Blonde who plays Brooke Windham, the murder defendant Elle befriends?",
"answ":"ALI LARTER",
"answ3":"ALIE LARTER",
"answ2":"Ali Larter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Linda Cardellini</button><button id=incop2 class=buttons003 onclick=qinc()>Kathryn Hahn</button><button id=incop3 class=buttons003 onclick=qinc()>Selma Blair</button><button id=corop class=buttons003 onclick=qcor()>Ali Larter</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"This comedic actress played Anita, Josie's promiscuous co-worker in 1999's Never Been Kissed.",
"answ":"MOLLY SHANNON",
"answ2":"Molly Shannon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Parker Posey</button><button id=incop2 class=buttons003 onclick=qinc()>Janeane Garofalo</button><button id=incop3 class=buttons003 onclick=qinc()>Joan Cusack</button><button id=corop class=buttons003 onclick=qcor()>Molly Shannon</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Daddy's Little Girls, Gabrielle Union plays a lawyer who falls in love with a single dad played by Idris Elba. What is his blue collar profession?",
"answ":"MECHANIC",
"answ2":"Mechanic.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bartender</button><button id=incop2 class=buttons003 onclick=qinc()>Police officer</button><button id=incop3 class=buttons003 onclick=qinc()>Train driver</button><button id=corop class=buttons003 onclick=qcor()>Mechanic</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Which actress plays Meg Ryan's best friend Marie in When Harry Met Sally?",
"answ":"CARRIE FISHER",
"answ2":"Carrie Fisher.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Laura Dern</button><button id=incop2 class=buttons003 onclick=qinc()>Pernilla August</button><button id=corop class=buttons003 onclick=qcor()>Carrie Fisher</button><button id=incop4 class=buttons003 onclick=qinc()>Caroline Blakiston</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who plays Walter, Annie's fiancé in Sleepless in Seattle?",
"answ":"BILL PULLMAN",
"answ2":"Bill Pullman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hanks</button><button id=incop2 class=buttons003 onclick=qinc()>Josh Brolin</button><button id=corop class=buttons003 onclick=qcor()>Bill Pullman</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Harris</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"What romantic comedy starring Meg Ryan revolves around a call-in radio show?",
"answ":"SLEEPLESS IN SEATTLE",
"answ2":"Sleepless in Seattle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Addicted to Love</button><button id=incop2 class=buttons003 onclick=qinc()>Prelude to a Kiss</button><button id=corop class=buttons003 onclick=qcor()>Sleepless in Seattle</button><button id=incop4 class=buttons003 onclick=qinc()>French Kiss</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"When Harry Met Sally predominantly takes place in what city?",
"answ":"NEW YORK CITY",
"answ3":"NEW YORK",
"answ2":"New York City.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>San Francisco</button><button id=incop2 class=buttons003 onclick=qinc()>Chicago</button><button id=incop3 class=buttons003 onclick=qinc()>Washington DC</button><button id=corop class=buttons003 onclick=qcor()>New York City</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Love & Other Drugs, Anne Hathaway's character is afflicted with what disease?",
"answ":"PARKINSON",
"answ3":"PARKINSON'S DISEASE",
"answ2":"Parkinson's disease.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Diabetes</button><button id=incop2 class=buttons003 onclick=qinc()>Huntington's disease</button><button id=incop3 class=buttons003 onclick=qinc()>Celiac disease</button><button id=corop class=buttons003 onclick=qcor()>Parkinson's disease</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"Who directed the 1989 rom-com Look Who's Talking?",
"answ":"AMY HECKERLING",
"answ2":"Amy Heckerling.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harold Ramis</button><button id=corop class=buttons003 onclick=qcor()>Amy Heckerling</button><button id=incop3 class=buttons003 onclick=qinc()>John Landis</button><button id=incop4 class=buttons003 onclick=qinc()>Frank Oz</button><br/>",
},
{
"cat":"Rom-coms",
"ques":"In Clueless, a beautiful woman is referred to as what?",
"answ":"BETTY",
"answ2":"Betty.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Babe</button><button id=corop class=buttons003 onclick=qcor()>Betty</button><button id=incop3 class=buttons003 onclick=qinc()>Kate</button><button id=incop4 class=buttons003 onclick=qinc()>Shelly</button><br/>",
},
];
romcoms = shuffle(romcoms);
r2Q12 = shuffle(r2Q12);