var biopics = [
{
"cat":"Biopics",
"ques":"Who played Ty Cobb in the 1994 baseball biopic Cobb?",
"answ":"TOMMY LEE JONES",
"answ2":"Tommy Lee Jones.",
},
{
"cat":"Biopics",
"ques":"Who played Queen Elizabeth in 2010's The King's Speech?",
"answ":"HELENA BONHAM CARTER",
"answ2":"Helena Bonham Carter.",
},
{
"cat":"Biopics",
"ques":"Which Oscar-nominated actor directed the 2000 biopic Pollock?",
"answ":"ED HARRIS",
"answ2":"Ed Harris.",
},
{
"cat":"Biopics",
"ques":"Which Oscar-nominated actor starred as the titular character in the 2000 biopic Pollock?",
"answ":"ED HARRIS",
"answ2":"Ed Harris.",
},
{
"cat":"Biopics",
"ques":"Which actor starred as veteran horse trainer Lucien Laurin in 2010's Secretariat?",
"answ":"JOHN MALKOVICH",
"answ2":"John Malkovich.",
},
{
"cat":"Biopics",
"ques":"Which actress starred as Penny Chenery, Secretariat's owner in 2010's Secretariat?",
"answ":"DIANE LANE",
"answ2":"Diane Lane.",
},
{
"cat":"Biopics",
"ques":"What 2020 biopic features supporting performances from Linda Cardellini, Kyle MacLachlan and Matt Dillon?",
"answ":"CAPONE",
"answ2":"Capone.",
},
{
"cat":"Biopics",
"ques":"Who plays car designer Carroll Shelby in the film Ford v. Ferrari?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
},
{
"cat":"Biopics",
"ques":"Who plays Branch Rickey alongside Chadwick Boseman's Jackie Robinson in 42?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Biopics",
"ques":"Jon S. Baird directed John C. Reilly in what 2010s biopic?",
"answ":"STAN AND OLLIE",
"answ2":"Stan & Ollie.",
},
{
"cat":"Biopics",
"ques":"Who directed the biographical spy thriller Snowden?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
},
{
"cat":"Biopics",
"ques":"What Hollywood screen legend played real-life characters such as Charles Lindbergh, Glenn Miller and Wyatt Earp?",
"answ":"JAMES STEWART",
"answ3":"JIMMY STEWART",
"answ2":"James Stewart.",
},
{
"cat":"Biopics",
"ques":"Who stars as businessman Ray Kroc in the film The Founder that portrays the story of the McDonalds fast-food restaurant chain?",
"answ":"MICHAEL KEATON",
"answ2":"Michael Keaton.",
},
{
"cat":"Biopics",
"ques":"Sean Penn, Josh Brolin and James Franco star in what 2008 biographical drama?",
"answ":"MILK",
"answ2":"Milk.",
},
{
"cat":"Biopics",
"ques":"Paul Dano and John Cusack co-star as famed musician Brian Wilson at different points of his life in what 2015 film?",
"answ":"LOVE AND MERCY",
"answ2":"Love & Mercy.",
},
{
"cat":"Biopics",
"ques":"David Oyelowo portrayed Martin Luther King in what historical drama?",
"answ":"SELMA",
"answ2":"Selma.",
},
{
"cat":"Biopics",
"ques":"Jay Roach directed Charlize Theron, Nicole Kidman and Margot Robbie in what 2019 biographical drama about scandals at Fox News?",
"answ":"BOMBSHELL",
"answ2":"Bombshell.",
},
{
"cat":"Biopics",
"ques":"Jay Roach directed Bryan Cranston in what 2015 biopic?",
"answ":"TRUMBO",
"answ2":"Trumbo.",
},
{
"cat":"Biopics",
"ques":"Who played Tonya Harding in the 2018 film I, Tonya?",
"answ":"MARGOT ROBBIE",
"answ2":"Margot Robbie.",
},
{
"cat":"Biopics",
"ques":"Bradley Cooper plays real-life Navy Seal Chris Kyle in which film?",
"answ":"AMERICAN SNIPER",
"answ2":"American Sniper.",
},
{
"cat":"Biopics",
"ques":"Who was nominated for an Academy Award for their role as Joe Gould in the film Cinderella Man?",
"answ":"PAUL GIAMATTI",
"answ2":"Paul Giamatti.",
},
{
"cat":"Biopics",
"ques":"Which 2016 film follows Katherine G. Johnson, Dorothy Vaughan and Mary Jackson and their struggles at NASA during the 1960s?",
"answ":"HIDDEN FIGURES",
"answ2":"Hidden Figures.",
},
{
"cat":"Biopics",
"ques":"Which actor won an Oscar for portraying Truman Capote in 2005's Capote?",
"answ":"PHILIP SEYMOUR HOFFMAN",
"answ3":"PHILLIP SEYMOUR HOFFMAN",
"answ2":"Philip Seymour Hoffman.",
},
{
"cat":"Biopics",
"ques":"In K-19: The Widowmaker, who stars as Captain Alexei Vostrikov, commander of the first Soviet ballistic missile nuclear submarine?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Biopics",
"ques":"Who plays EMI executive Ray Foster in Bohemian Rhapsody?",
"answ":"MIKE MYERS",
"answ3":"MIKE MEYERS",
"answ2":"Mike Myers.",
},
{
"cat":"Biopics",
"ques":"Who played the lead Idi Amin in 2006's The Last King of Scotland?",
"answ":"FOREST WHITAKER",
"answ2":"Forest Whitaker.",
},
{
"cat":"Biopics",
"ques":"What former Taxi co-star played Andy Kaufman's manager, George Shapiro, in Man on the Moon?",
"answ":"DANNY DEVITO",
"answ3":"DANNY DE VITO",
"answ2":"Danny DeVito.",
},
{
"cat":"Biopics",
"ques":"In Battle of the Sexes, what actor plays Billie Jean King's opponent Bobby Riggs?",
"answ":"STEVE CARELL",
"answ3":"STEVE CARRELL",
"answ2":"Steve Carell.",
},
{
"cat":"Biopics",
"ques":"What 1983 film tells the true story of the original Mercury 7 astronauts during the early days of the U.S. Space Program?",
"answ":"THE RIGHT STUFF",
"answ2":"The Right Stuff.",
},
{
"cat":"Biopics",
"ques":"Who played Johnny Cash's wife June in Walk the Line?",
"answ":"REESE WITHERSPOON",
"answ3":"REESE WITHERSPOONE",
"answ2":"Reese Witherspoon.",
},
{
"cat":"Biopics",
"ques":"Who played Jane Austen in 2007's Becoming Jane?",
"answ":"ANNE HATHAWAY",
"answ2":"Anne Hathaway.",
},
{
"cat":"Biopics",
"ques":"Which actress played Katherine Johnson alongside co-stars Octavia Spencer and Janelle Monae in Hidden Figures?",
"answ":"TARAJI P HENSON",
"answ3":"TARAJI HENSON",
"answ2":"Taraji P. Henson.",
},
{
"cat":"Biopics",
"ques":"Who played Eazy-E in Straight Outta Compton?",
"answ":"JASON MITCHELL",
"answ3":"JASON MITCHEL",
"answ2":"Jason Mitchell.",
},
{
"cat":"Biopics",
"ques":"Nelson Mandela is played by whom in the film Invictus?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Biopics",
"ques":"Who played Jim Morrison in 1991's biopic The Doors?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
},
];
var r2Q14 = [
{
"cat":"Biopics",
"ques":"What was the name of the film starring Emma Thompson about Mary Poppins?",
"answ":"SAVING MR BANKS",
"answ2":"Saving Mr. Banks.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Saving Mr. Banks</button><button id=incop2 class=buttons003 onclick=qinc()>The Founder</button><button id=incop3 class=buttons003 onclick=qinc()>October Sky</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Robin</button><br/>",
},
{
"cat":"Biopics",
"ques":"What was the name of the 2005 Johnny Cash biopic?",
"answ":"WALK THE LINE",
"answ2":"Walk the Line.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Pianist</button><button id=corop class=buttons003 onclick=qcor()>Walk the Line</button><button id=incop3 class=buttons003 onclick=qinc()>Straight Outta Compton</button><button id=incop4 class=buttons003 onclick=qinc()>Miracle</button><br/>",
},
{
"cat":"Biopics",
"ques":"In 2012's Lincoln, Daniel Day-Lewis portrayed the president who lobbied for Congress to pass the ____ Amendment?",
"answ":"THIRTEENTH",
"answ2":"Thirteenth Amendment.",
"answ3":"13TH",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Twelfth</button><button id=corop class=buttons003 onclick=qcor()>Thirteenth</button><button id=incop3 class=buttons003 onclick=qinc()>Fourteenth</button><button id=incop4 class=buttons003 onclick=qinc()>Sixteenth</button><br/>",
},
{
"cat":"Biopics",
"ques":"Which college does Big Mike choose to attend in 2009's The Blind Side?",
"answ":"OLE MISS",
"answ2":"Ole Miss/Mississippi.",
"answ3":"MISSISSIPPI",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harvard</button><button id=corop class=buttons003 onclick=qcor()>Ole Miss</button><button id=incop3 class=buttons003 onclick=qinc()>Yale</button><button id=incop4 class=buttons003 onclick=qinc()>Princeton</button><br/>",
},
{
"cat":"Biopics",
"ques":"What is the name of the boxing star whose life is put under scrutiny in 1980's Raging Bull?",
"answ":"JAKE LAMOTTA",
"answ2":"Jake LaMotta.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sugar Ray Robinson</button><button id=corop class=buttons003 onclick=qcor()>Jake LaMotta</button><button id=incop3 class=buttons003 onclick=qinc()>Rocky Marciano</button><button id=incop4 class=buttons003 onclick=qinc()>Reggie Johnson</button><br/>",
},
{
"cat":"Biopics",
"ques":"What is the name of the 1989 movie that tells the story of the tragic life of comedic actor John Belushi?",
"answ":"WIRED",
"answ2":"Wired.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Wired</button><button id=incop2 class=buttons003 onclick=qinc()>Bogie</button><button id=incop3 class=buttons003 onclick=qinc()>Private Parts</button><button id=incop4 class=buttons003 onclick=qinc()>Patch Adams</button><br/>",
},
{
"cat":"Biopics",
"ques":"Which country music singer did Sissy Spacek portray in 1980's Coal Miner's Daughter?",
"answ":"LORETTA LYNN",
"answ2":"Loretta Lynn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Loretta Lynn</button><button id=incop2 class=buttons003 onclick=qinc()>Tammy Wynette</button><button id=incop3 class=buttons003 onclick=qinc()>Dolly Parton</button><button id=incop4 class=buttons003 onclick=qinc()>Donna Fargo</button><br/>",
},
{
"cat":"Biopics",
"ques":"Composer Atticus Ross teamed up with what musician to do the score for David Fincher's The Social Network?",
"answ":"TRENT REZNOR",
"answ2":"Trent Reznor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Randy Newman</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Bolton</button><button id=corop class=buttons003 onclick=qcor()>Trent Reznor</button><button id=incop4 class=buttons003 onclick=qinc()>Eric Clapton</button><br/>",
},
{
"cat":"Biopics",
"ques":"Todd Haynes directed which biopic that featured several different actors portraying Bob Dylan throughout his life?",
"answ":"I'M NOT THERE",
"answ3":"I AM NOT THERE",
"answ2":"I'm Not There.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blowin' in the Wind</button><button id=incop2 class=buttons003 onclick=qinc()>The Times They Are a-Changin</button><button id=incop3 class=buttons003 onclick=qinc()>By Your Side</button><button id=corop class=buttons003 onclick=qcor()>I'm Not There</button><br/>",
},
{
"cat":"Biopics",
"ques":"Which actor/director was behind the camera for two famed biopics, Gandhi and Chaplin?",
"answ":"RICHARD ATTENBOROUGH",
"answ2":"Richard Attenborough.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Woody Allen</button><button id=incop2 class=buttons003 onclick=qinc()>Clint Eastwood</button><button id=incop3 class=buttons003 onclick=qinc()>Ron Howard</button><button id=corop class=buttons003 onclick=qcor()>Richard Attenborough</button><br/>",
},
{
"cat":"Biopics",
"ques":"Underground comic book writer Harvey Pekar is the subject of which biopic?",
"answ":"AMERICAN SPLENDOR",
"answ2":"American Splendor.",
"option":"<button id=corop class=buttons003 onclick=qcor()>American Splendor</button><button id=incop2 class=buttons003 onclick=qinc()>Alpha Dog</button><button id=incop3 class=buttons003 onclick=qinc()>Chopper</button><button id=incop4 class=buttons003 onclick=qinc()>Ip Man</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Charlie Chaplin in 1992's Chaplin?",
"answ":"ROBERT DOWNEY JR",
"answ2":"Robert Downey Jr.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Robert Downey Jr</button><button id=incop2 class=buttons003 onclick=qinc()>Bill Hader</button><button id=incop3 class=buttons003 onclick=qinc()>Jamie Bell</button><button id=incop4 class=buttons003 onclick=qinc()>Dan Aykroyd</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Selena's father Abraham Quintanilla in 1997's Selena?",
"answ":"EDWARD JAMES OLMOS",
"answ2":"Edward James Olmos.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Armand Assante</button><button id=incop2 class=buttons003 onclick=qinc()>Jimmy Smits</button><button id=incop3 class=buttons003 onclick=qinc()>Adolfo Martinez</button><button id=corop class=buttons003 onclick=qcor()>Edward James Olmos</button><br/>",
},
{
"cat":"Biopics",
"ques":"What is the name of the 2004 film starring Kevin Kline that follows the life of American songwriter Cole Porter?",
"answ":"DE LOVELY",
"answ2":"De-Lovely.",
"answ3":"DELOVELY",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Let's Misbehave</button><button id=incop2 class=buttons003 onclick=qinc()>Night and Day</button><button id=corop class=buttons003 onclick=qcor()>De-Lovely</button><button id=incop4 class=buttons003 onclick=qinc()>Anything Goes</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Jerry Lee Lewis' 13-year old cousin in 1989's Great Balls of Fire?",
"answ":"WINONA RYDER",
"answ2":"Winona Ryder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alyssa Milano</button><button id=corop class=buttons003 onclick=qcor()>Winona Ryder</button><button id=incop3 class=buttons003 onclick=qinc()>Amy Ryan</button><button id=incop4 class=buttons003 onclick=qinc()>Annabeth Gish</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Selena in the Selena biopic?",
"answ":"JENNIFER LOPEZ",
"answ2":"Jennifer Lopez.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eva Mendes</button><button id=incop2 class=buttons003 onclick=qinc()>Selma Hajek</button><button id=corop class=buttons003 onclick=qcor()>Jennifer Lopez</button><button id=incop4 class=buttons003 onclick=qinc()>Penélope Cruz</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played the lead character Christy Brown in the film My Left Foot?",
"answ":"DANIEL DAY LEWIS",
"answ2":"Daniel Day-Lewis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop2 class=buttons003 onclick=qinc()>Joaquin Phoenix</button><button id=corop class=buttons003 onclick=qcor()>Daniel Day-Lewis</button><button id=incop4 class=buttons003 onclick=qinc()>John Cusack</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who directed the 2005 biopic Capote?",
"answ":"BENNETT MILLER",
"answ3":"BENNET MILLER",
"answ2":"Bennett Miller.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Clint Eastwood</button><button id=incop2 class=buttons003 onclick=qinc()>Gus Van Sant</button><button id=corop class=buttons003 onclick=qcor()>Bennett Miller</button><button id=incop4 class=buttons003 onclick=qinc()>Ang Lee</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played the adult version of author Harvey Pekar in American Splendor?",
"answ":"PAUL GIAMATTI",
"answ2":"Paul Giamatti.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toby Jones</button><button id=incop2 class=buttons003 onclick=qinc()>Thomas Hayden Church</button><button id=corop class=buttons003 onclick=qcor()>Paul Giamatti</button><button id=incop4 class=buttons003 onclick=qinc()>John Goodman</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played the title character in 1992's Hoffa?",
"answ":"JACK NICHOLSON",
"answ2":"Jack Nicholson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jack Nicholson</button><button id=incop2 class=buttons003 onclick=qinc()>Danny DeVito</button><button id=incop3 class=buttons003 onclick=qinc()>Scott Glenn</button><button id=incop4 class=buttons003 onclick=qinc()>Ray Liotta</button><br/>",
},
{
"cat":"Biopics",
"ques":"What 2004 Oliver Stone film starring Colin Farrell depicts the life and times of a famed world leader?",
"answ":"ALEXANDER",
"answ2":"Alexander.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Seize the Day</button><button id=incop2 class=buttons003 onclick=qinc()>Troy</button><button id=incop3 class=buttons003 onclick=qinc()>Hannibal</button><button id=corop class=buttons003 onclick=qcor()>Alexander</button><br/>",
},
{
"cat":"Biopics",
"ques":"Which actor portrayed famous magician Harry Houdini in the biographical film Houdini?",
"answ":"TONY CURTIS",
"answ3":"ANTHONY CURTIS",
"answ2":"Tony Curtis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alec Guinness</button><button id=incop2 class=buttons003 onclick=qinc()>David Niven</button><button id=incop3 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=corop class=buttons003 onclick=qcor()>Tony Curtis</button><br/>",
},
{
"cat":"Biopics",
"ques":"In Moneyball, which team did the Oakland A's play in their attempt to win 20 consecutive games?",
"answ":"KANSAS CITY ROYALS",
"answ2":"Kansas City Royals.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Detroit Tigers</button><button id=incop2 class=buttons003 onclick=qinc()>Cleveland Indians</button><button id=incop3 class=buttons003 onclick=qinc()>Chicago White Sox</button><button id=corop class=buttons003 onclick=qcor()>Kansas City Royals</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played the role of Althea Flynt in The People vs Larry Flynt?",
"answ":"COURTNEY LOVE",
"answ2":"Courtney Love.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Elizabeth Berridge</button><button id=incop2 class=buttons003 onclick=qinc()>Louise Fletcher</button><button id=incop3 class=buttons003 onclick=qinc()>Natalie Portman</button><button id=corop class=buttons003 onclick=qcor()>Courtney Love</button><br/>",
},
{
"cat":"Biopics",
"ques":"Liam Neeson played this Irish patriot in Neil Jordan's 1996 film.",
"answ":"MICHAEL COLLINS",
"answ2":"Michael Collins.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry Boland</button><button id=incop2 class=buttons003 onclick=qinc()>Liam Tobin</button><button id=incop3 class=buttons003 onclick=qinc()>Rory O'Connor</button><button id=corop class=buttons003 onclick=qcor()>Michael Collins</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays Della Bea Robinson in Ray?",
"answ":"KERRY WASHINGTON",
"answ3":"CARRIE WASHINGTON",
"answ2":"Kerry Washington.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Viola Davis</button><button id=corop class=buttons003 onclick=qcor()>Kerry Washington</button><button id=incop3 class=buttons003 onclick=qinc()>Regina King</button><button id=incop4 class=buttons003 onclick=qinc()>Taraji P. Henson</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays Frida Kahlo's husband, Diego Rivera in the movie Frida?",
"answ":"ALFRED MOLINA",
"answ2":"Alfred Molina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Diego Luna</button><button id=corop class=buttons003 onclick=qcor()>Alfred Molina</button><button id=incop3 class=buttons003 onclick=qinc()>Edward Norton</button><button id=incop4 class=buttons003 onclick=qinc()>Javier Bardem</button><br/>",
},
{
"cat":"Biopics",
"ques":"Which media outlet did Steven Glass work for in 2003's Shattered Glass?",
"answ":"THE NEW REPUBLIC",
"answ3":"NEW REPUBLIC",
"answ2":"The New Republic.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>TIME Magazine</button><button id=corop class=buttons003 onclick=qcor()>The New York Daily News</button><button id=incop3 class=buttons003 onclick=qinc()>The New Republic</button><button id=incop4 class=buttons003 onclick=qinc()>The Washington Post</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played the title role in 1996's Evita?",
"answ":"MADONNA",
"answ2":"Madonna.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cher</button><button id=corop class=buttons003 onclick=qcor()>Madonna</button><button id=incop3 class=buttons003 onclick=qinc()>Jennifer Lopez</button><button id=incop4 class=buttons003 onclick=qinc()>Dolly Parton</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays the brilliant mathematician who studies under G.H. Hardy in 2016's The Man Who Knew Infinity?",
"answ":"DEV PATEL",
"answ2":"Dev Patel.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dev Patel</button><button id=incop2 class=buttons003 onclick=qinc()>Ethan Embry</button><button id=incop3 class=buttons003 onclick=qinc()>Tom Holland</button><button id=incop4 class=buttons003 onclick=qinc()>Asa Butterfield</button><br/>",
},
{
"cat":"Biopics",
"ques":"The 1993 film Shadowlands stars Anthony Hopkins as which famous author?",
"answ":"CS LEWIS",
"answ2":"C.S. Lewis",
"option":"<button id=corop class=buttons003 onclick=qcor()>C.S. Lewis</button><button id=incop2 class=buttons003 onclick=qinc()>Stephen King</button><button id=incop3 class=buttons003 onclick=qinc()>J.R.R. Tolkien</button><button id=incop4 class=buttons003 onclick=qinc()>Charles Dickens</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who directed the 1991 crime thriller Bugsy, starring Warren Beatty and Annette Bening?",
"answ":"BARRY LEVINSON",
"answ2":"Barry Levinson",
"option":"<button id=corop class=buttons003 onclick=qcor()>Barry Levinson</button><button id=incop2 class=buttons003 onclick=qinc()>Warren Beatty</button><button id=incop3 class=buttons003 onclick=qinc()>Stephen Frears</button><button id=incop4 class=buttons003 onclick=qinc()>Lisa Cholodenko</button><br/>",
},
{
"cat":"Biopics",
"ques":"Backbeat is a dramatic take on the early days of what famous band?",
"answ":"THE BEATLES",
"answ3":"BEATLES",
"answ2":"The Beatles",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Beatles</button><button id=incop2 class=buttons003 onclick=qinc()>The Rolling Stones</button><button id=incop3 class=buttons003 onclick=qinc()>Aerosmith</button><button id=incop4 class=buttons003 onclick=qinc()>The Beach Boys</button><br/>",
},
{
"cat":"Biopics",
"ques":"A man's coerced confession to an IRA bombing he did not commit results in his false inprisonment in what 90s biopic?",
"answ":"IN THE NAME OF THE FATHER",
"answ2":"In the Name of the Father.",
"option":"<button id=corop class=buttons003 onclick=qcor()>In the Name of the Father</button><button id=incop2 class=buttons003 onclick=qinc()>Runaway Jury</button><button id=incop3 class=buttons003 onclick=qinc()>The Rainmaker</button><button id=incop4 class=buttons003 onclick=qinc()>The Hurricane</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays John Merrick 'The Elephant Man' in 1980s The Elephant Man?",
"answ":"JOHN HURT",
"answ2":"John Hurt.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John Hurt</button><button id=incop2 class=buttons003 onclick=qinc()>Anthony Hopkins</button><button id=incop3 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=incop4 class=buttons003 onclick=qinc()>Al Pacino</button><br/>",
},
{
"cat":"Biopics",
"ques":"Tobey Maguire stars as prodigy Bobby Fischer in what movie?",
"answ":"PAWN SACRIFICE",
"answ2":"Pawn Sacrifice.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pawn Sacrifice</button><button id=incop2 class=buttons003 onclick=qinc()>Searching for Bobby Fischer</button><button id=incop3 class=buttons003 onclick=qinc()>Checkmate</button><button id=incop4 class=buttons003 onclick=qinc()>Mind Games</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who directed the 2014 biopic Mr Turner, starring Timothy Spall as the eccentric British painter J.M.W. Turner?",
"answ":"MIKE LEIGH",
"answ2":"Mike Leigh.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mike Leigh</button><button id=incop2 class=buttons003 onclick=qinc()>Viggo Mortensen</button><button id=incop3 class=buttons003 onclick=qinc()>Ava Duvernay</button><button id=incop4 class=buttons003 onclick=qinc()>Michelle McClaren</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played explorer Sir Walter Raleigh in the 2007 historical drama Elizabeth: The Golden Age?",
"answ":"CLIVE OWEN",
"answ2":"Clive Owen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Geoffrey Rush</button><button id=incop2 class=buttons003 onclick=qinc()>Eddie Redmayne</button><button id=corop class=buttons003 onclick=qcor()>Clive Owen</button><button id=incop4 class=buttons003 onclick=qinc()>Gerard Butler</button><br/>",
},
{
"cat":"Biopics",
"ques":"What historical figure is portrayed by Josh Lucas in J. Edgar?",
"answ":"CHARLES LINDBERGH",
"answ3":"CHARLES LINDBERG",
"answ2":"Charles Lindbergh.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>J. Edgar Hoover</button><button id=incop2 class=buttons003 onclick=qinc()>John F. Kennedy</button><button id=corop class=buttons003 onclick=qcor()>Charles Lindbergh</button><button id=incop4 class=buttons003 onclick=qinc()>Robert F. Kennedy</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who directed 127 Hours?",
"answ":"DANNY BOYLE",
"answ2":"Danny Boyle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Steven Soderbergh</button><button id=corop class=buttons003 onclick=qcor()>Danny Boyle</button><button id=incop3 class=buttons003 onclick=qinc()>Doug Liman</button><button id=incop4 class=buttons003 onclick=qinc()>Bennett Miller</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays Bradley Cooper's wife in American Sniper?",
"answ":"SIENNA MILLER",
"answ2":"Sienna Miller.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charlize Theron</button><button id=corop class=buttons003 onclick=qcor()>Sienna Miller</button><button id=incop3 class=buttons003 onclick=qinc()>Amber Heard</button><button id=incop4 class=buttons003 onclick=qinc()>Katherine Heigl</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays the frustrated new prime minister in The Queen?",
"answ":"MICHAEL SHEEN",
"answ2":"Michael Sheen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Cromwell</button><button id=corop class=buttons003 onclick=qcor()>Michael Sheen</button><button id=incop3 class=buttons003 onclick=qinc()>Stanley Tucci</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Arkin</button><br/>",
},
{
"cat":"Biopics",
"ques":"Chadwick Boseman occasionally breaks the fourth wall while starring in what biopic?",
"answ":"GET ON UP",
"answ2":"Get On Up.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Why Do Fools Fall in Love</button><button id=incop2 class=buttons003 onclick=qinc()>42</button><button id=corop class=buttons003 onclick=qcor()>Get On Up</button><button id=incop4 class=buttons003 onclick=qinc()>Talk To Me</button><br/>",
},
{
"cat":"Biopics",
"ques":"What actor played American entertainer, playwright and composer George M. Cohan in both Yankee Doodle Dandy and The Seven Little Foys?",
"answ":"JAMES CAGNEY",
"answ2":"James Cagney.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Robert Donat</button><button id=incop2 class=buttons003 onclick=qinc()>Orson Welles</button><button id=corop class=buttons003 onclick=qcor()>James Cagney</button><button id=incop4 class=buttons003 onclick=qinc()>Clark Gable</button><br/>",
},
{
"cat":"Biopics",
"ques":"In Men of Honor, Cuba Gooding suffers an injury on a ship and loses a part of his body. What part of his body does he lose?",
"answ":"LEG",
"answ3":"LEFT LEG",
"answ2":"Leg.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Arm</button><button id=incop2 class=buttons003 onclick=qinc()>Hand</button><button id=corop class=buttons003 onclick=qcor()>Leg</button><button id=incop4 class=buttons003 onclick=qinc()>Foot</button><br/>",
},
{
"cat":"Biopics",
"ques":"What is the nickname that Howard Stern hives Paul Giamatti in Private Parts?",
"answ":"PIG VOMIT",
"answ2":"Pig vomit.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fat ass</button><button id=corop class=buttons003 onclick=qcor()>Pig vomit</button><button id=incop3 class=buttons003 onclick=qinc()>Porker</button><button id=incop4 class=buttons003 onclick=qinc()>Pig nose</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays a LA journalist that befriends a homeless Juilliard-trained musician in The Soloist?",
"answ":"ROBERT DOWNEY JR",
"answ3":"ROBERT DOWNEY JUNIOR",
"answ2":"Robert Downey Jr.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jamie Foxx</button><button id=corop class=buttons003 onclick=qcor()>Robert Downey Jr.</button><button id=incop3 class=buttons003 onclick=qinc()>James Marsden</button><button id=incop4 class=buttons003 onclick=qinc()>Russell Crowe</button><br/>",
},
{
"cat":"Biopics",
"ques":"What actor plays bull rider Lane Frost in 8 Seconds?",
"answ":"LUKE PERRY",
"answ2":"Luke Perry.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bryan Cranston</button><button id=corop class=buttons003 onclick=qcor()>Luke Perry</button><button id=incop3 class=buttons003 onclick=qinc()>Owen Wilson</button><button id=incop4 class=buttons003 onclick=qinc()>Russell Crowe</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who wrote the screenplay for The Social Network?",
"answ":"AARON SORKIN",
"answ2":"Aaron Sorkin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>David Fincher</button><button id=corop class=buttons003 onclick=qcor()>Aaron Sorkin</button><button id=incop3 class=buttons003 onclick=qinc()>Chris Terrio</button><button id=incop4 class=buttons003 onclick=qinc()>Danny Boyle</button><br/>",
},
{
"cat":"Biopics",
"ques":"What 2000s biopic centers around the creation of Peter Pan?",
"answ":"FINDING NEVERLAND",
"answ2":"Finding Neverland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pan</button><button id=corop class=buttons003 onclick=qcor()>Finding Neverland</button><button id=incop3 class=buttons003 onclick=qinc()>Hook</button><button id=incop4 class=buttons003 onclick=qinc()>Saving Mr. Banks</button><br/>",
},
{
"cat":"Biopics",
"ques":"In The Imitation Game, what was the name that Alan Turing gave to his Enigma-breaking machine?",
"answ":"CHRISTOPHER",
"answ2":"Christopher.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Christopher</button><button id=incop2 class=buttons003 onclick=qinc()>Michael</button><button id=incop3 class=buttons003 onclick=qinc()>Daniel</button><button id=incop4 class=buttons003 onclick=qinc()>Thomas</button><br/>",
},
{
"cat":"Biopics",
"ques":"What 2016 biopic is about Army Medic Desmond T. Doss?",
"answ":"HACKSAW RIDGE",
"answ2":"Hacksaw Ridge.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hacksaw Ridge</button><button id=incop2 class=buttons003 onclick=qinc()>Allied</button><button id=incop3 class=buttons003 onclick=qinc()>13 Hours: The Secret Soldiers of Benghazi</button><button id=incop4 class=buttons003 onclick=qinc()>Free State of Jones</button><br/>",
},
{
"cat":"Biopics",
"ques":"What Harry Potter vet played Dennis Sciama, one of Stephen Hawking's professors and mentors in The Theory of Everything?",
"answ":"DAVID THEWLIS",
"answ2":"David Thewlis.",
"option":"<button id=corop class=buttons003 onclick=qcor()>David Thewlis</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Rickman</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Gambon</button><button id=incop4 class=buttons003 onclick=qinc()>Ralph Fiennes</button><br/>",
},
{
"cat":"Biopics",
"ques":"What MCU star has a small role as Oakland A's first baseman Scott Hatteberg in Moneyball?",
"answ":"CHRIS PRATT",
"answ2":"Chris Pratt.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Chris Pratt</button><button id=incop2 class=buttons003 onclick=qinc()>Chris Evans</button><button id=incop3 class=buttons003 onclick=qinc()>Sebastian Stan</button><button id=incop4 class=buttons003 onclick=qinc()>Anthony Mackie</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Queen's manager John Reid in Bohemian Rhapsody?",
"answ":"AIDAN GILLEN",
"answ3":"AIDEN GILLEN",
"answ2":"Aidan Gillen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Tudyk</button><button id=incop2 class=buttons003 onclick=qinc()>Mike Myers</button><button id=incop3 class=buttons003 onclick=qinc()>David Thewlis</button><button id=corop class=buttons003 onclick=qcor()>Aidan Gillen</button><br/>",
},
{
"cat":"Biopics",
"ques":"In A Beautiful Mind, what Ivy League school did John Nash attend?",
"answ":"PRINCETON",
"answ3":"PRINCETON UNIVERSITY",
"answ2":"Princeton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Yale</button><button id=corop class=buttons003 onclick=qcor()>Princeton</button><button id=incop3 class=buttons003 onclick=qinc()>Harvard</button><button id=incop4 class=buttons003 onclick=qinc()>Columbia</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who plays Russell Crowe's wife, Mae, in Cinderella Man?",
"answ":"RENEE ZELLWEGER",
"answ3":"RENÉE ZELLWEGER",
"answ2":"Renée Zellweger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rene Russo</button><button id=incop2 class=buttons003 onclick=qinc()>Connie Nielsen</button><button id=incop3 class=buttons003 onclick=qinc()>Kelly Lynch</button><button id=corop class=buttons003 onclick=qcor()>Renée Zellweger</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who does John Carroll Lynch play opposite Natalie Portman in Jackie?",
"answ":"LYNDON JOHNSON",
"answ3":"LYNDON B JOHNSON",
"answ2":"Lyndon B. Johnson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Robert F. Kennedy</button><button id=incop2 class=buttons003 onclick=qinc()>John F. Kennedy</button><button id=incop3 class=buttons003 onclick=qinc()>John F. Kennedy Jr.</button><button id=corop class=buttons003 onclick=qcor()>Lyndon B. Johnson</button><br/>",
},
{
"cat":"Biopics",
"ques":"In Finding Neverland, who plays troubled young Peter Llewelyn Davies, whom J.M. Barrie bases Peter Pan off of?",
"answ":"FREDDIE HIGHMORE",
"answ3":"FREDDY HIGHMORE",
"answ2":"Freddie Highmore.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Logan Lerman</button><button id=incop2 class=buttons003 onclick=qinc()>Dylan O'Brien</button><button id=incop3 class=buttons003 onclick=qinc()>Topher Grace</button><button id=corop class=buttons003 onclick=qcor()>Freddie Highmore</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who stars as Helen Gandy in J. Edgar?",
"answ":"NAOMI WATTS",
"answ3":"NAOMIE WATTS",
"answ2":"Naomi Watts.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nicole Kidman</button><button id=corop class=buttons003 onclick=qcor()>Naomi Watts</button><button id=incop3 class=buttons003 onclick=qinc()>Sienna Miller</button><button id=incop4 class=buttons003 onclick=qinc()>Rachel Weisz</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Abraham Lincoln's son Robert Todd Lincoln in 2012's Lincoln?",
"answ":"JOSEPH GORDON LEVITT",
"answ2":"Joseph Gordon-Levitt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hardy</button><button id=corop class=buttons003 onclick=qcor()>Joseph Gordon-Levitt</button><button id=incop3 class=buttons003 onclick=qinc()>Topher Grace</button><button id=incop4 class=buttons003 onclick=qinc()>Dylan O'Brien</button><br/>",
},
{
"cat":"Biopics",
"ques":"Kevin Kline portrayed what classic film star in the 2013 film The Last of Robin Hood?",
"answ":"ERROL FLYNN",
"answ2":"Errol Flynn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Orson Welles</button><button id=corop class=buttons003 onclick=qcor()>Errol Flynn</button><button id=incop3 class=buttons003 onclick=qinc()>Humphrey Bogart</button><button id=incop4 class=buttons003 onclick=qinc()>Peter O'Toole</button><br/>",
},
{
"cat":"Biopics",
"ques":"In Hidden Figures, which famous astronaut do the three main heroines help launch into space?",
"answ":"JOHN GLENN",
"answ2":"John Glenn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Buzz Aldrin</button><button id=corop class=buttons003 onclick=qcor()>John Glenn</button><button id=incop3 class=buttons003 onclick=qinc()>Alan Shepard</button><button id=incop4 class=buttons003 onclick=qinc()>Neil Armstrong</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who played Jane Hawking, wife to Stephen Hawking, in the 2014 film The Theory of Everything?",
"answ":"FELICITY JONES",
"answ2":"Felicity Jones.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alicia Vikander</button><button id=corop class=buttons003 onclick=qcor()>Felicity Jones</button><button id=incop3 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=incop4 class=buttons003 onclick=qinc()>Sienna Miller</button><br/>",
},
{
"cat":"Biopics",
"ques":"In what 2009 biographical film does Angela Bassett play Voletta Wallace?",
"answ":"NOTORIOUS",
"answ2":"Notorious.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Notorious</button><button id=incop2 class=buttons003 onclick=qinc()>All Eyez on Me</button><button id=incop3 class=buttons003 onclick=qinc()>Get on Up</button><button id=incop4 class=buttons003 onclick=qinc()>Straight Outta Compton</button><br/>",
},
{
"cat":"Biopics",
"ques":"In J. Edgar, who plays Clyde Tolson, the longtime companion of J. Edgar Hoover?",
"answ":"ARMIE HAMMER",
"answ2":"Armie Hammer.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Armie Hammer</button><button id=incop2 class=buttons003 onclick=qinc()>James Marsden</button><button id=incop3 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=incop4 class=buttons003 onclick=qinc()>Scott Eastwood</button><br/>",
},
{
"cat":"Biopics",
"ques":"In Richard Jewell, what is the name of the park where Richard notices a suspicious package that ends up detonating?",
"answ":"CENTENNIAL PARK",
"answ3":"CENTENIAL PARK",
"answ2":"Centennial Park.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fountain Ring Park</button><button id=corop class=buttons003 onclick=qcor()>Centennial Park</button><button id=incop3 class=buttons003 onclick=qinc()>Georgia Authority Park</button><button id=incop4 class=buttons003 onclick=qinc()>Atlanta Heritage Park</button><br/>",
},
{
"cat":"Biopics",
"ques":"Who directed 2001's Blow?",
"answ":"TED DEMME",
"answ2":"Ted Demme.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Martin Campbell</button><button id=corop class=buttons003 onclick=qcor()>Ted Demme</button><button id=incop3 class=buttons003 onclick=qinc()>Gary Ross</button><button id=incop4 class=buttons003 onclick=qinc()>Robert Schwentke</button><br/>",
},
];
biopics = shuffle(biopics);
r2Q14 = shuffle(r2Q14);