var comingofage = [
{
"cat":"Coming of Age",
"ques":"Who directed Stand By Me?",
"answ":"ROB REINER",
"answ2":"Rob Reiner.",
},
{
"cat":"Coming of Age",
"ques":"In what 1973 George Lucas film can you find the stars Ron Howard, Harrison Ford and Richard Dreyfuss?",
"answ":"AMERICAN GRAFFITI",
"answ3":"AMERICAN GRAFITI",
"answ2":"American Graffiti.",
},
{
"cat":"Coming of Age",
"ques":"What 1967 coming of age drama involves a love triangle between Katharine Ross, Anne Bancroft and Dustin Hoffman?",
"answ":"THE GRADUATE",
"answ2":"The Graduate.",
},
{
"cat":"Coming of Age",
"ques":"What MCU actor plays Brand, Mikey's older brother, in The Goonies?",
"answ":"JOSH BROLIN",
"answ2":"Josh Brolin.",
},
{
"cat":"Coming of Age",
"ques":"Who directed The Breakfast Club?",
"answ":"JOHN HUGHES",
"answ3":"JON HUGHES",
"answ2":"John Hughes.",
},
{
"cat":"Coming of Age",
"ques":"Who played 'Mouth' in The Goonies?",
"answ":"COREY FELDMAN",
"answ3":"CORY FELDMAN",
"answ2":"Corey Feldman.",
},
{
"cat":"Coming of Age",
"ques":"What 2018 coming-of-age film stars Nick Robinson, Jennifer Garner and Josh Duhamel?",
"answ":"LOVE SIMON",
"answ3":"LOVE  SIMON",
"answ2":"Love, Simon.",
},
{
"cat":"Coming of Age",
"ques":"Who played Sharon Norbury, the calculus teacher, in Mean Girls?",
"answ":"TINA FEY",
"answ3":"TINA FAY",
"answ2":"Tina Fey.",
},
{
"cat":"Coming of Age",
"ques":"What is the title of the 1979 sequel to American Graffiti?",
"answ":"MORE AMERICAN GRAFFITI",
"answ3":"MORE AMERICAN GRAFITI",
"answ2":"More American Graffiti.",
},
{
"cat":"Coming of Age",
"ques":"What Wes Anderson film follows young kids Sam Shakusky and Suzy Bishop, who fall in love in the 1960s?",
"answ":"MOONRISE KINGDOM",
"answ2":"Moonrise Kingdom.",
},
{
"cat":"Coming of Age",
"ques":"Bo Burnham wrote and directed this 2018 coming of age film.",
"answ":"EIGHT GRADE",
"answ2":"Eight Grade.",
},
{
"cat":"Coming of Age",
"ques":"In what coming of age film does Jesse Eisenberg play a character who works at an amusement park for the summer?",
"answ":"ADVENTURELAND",
"answ2":"Adventureland.",
},
{
"cat":"Coming of Age",
"ques":"What 2010 coming of age biopic stars Kristen Stewart and Dakota Fanning as 70s rockers Joan Jett and Cherie Currie?",
"answ":"THE RUNAWAYS",
"answ2":"The Runaways.",
},
{
"cat":"Coming of Age",
"ques":"Which DCEU actor plays a teen named Patrick in The Perks of Being a Wallflower?",
"answ":"EZRA MILLER",
"answ2":"Ezra Miller.",
},
{
"cat":"Coming of Age",
"ques":"What 2002 drama follows a young Maori girl trying to claim her place as chief amongst a strictly patriarchal New Zealand tribe?",
"answ":"WHALE RIDER",
"answ2":"Whale Rider.",
},
{
"cat":"Coming of Age",
"ques":"What 2005 coming of age film stars Amber Tamblyn, America Ferrera and Blake Lively?",
"answ":"THE SISTERHOOD OF THE TRAVELING PANTS",
"answ3":"SISTERHOOD OF THE TRAVELING PANTS",
"answ2":"The Sisterhood of the Traveling Pants.",
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls, which character said the quote: 'Stop trying to make fetch happen, it's not going to happen'?",
"answ":"REGINA",
"answ2":"Regina.",
},
{
"cat":"Coming of Age",
"ques":"Michael Caine and Robert Duvall play eccentric uncles to a boy named Walter in what film?",
"answ":"SECONDHAND LIONS",
"answ2":"Secondhand Lions.",
},
{
"cat":"Coming of Age",
"ques":"The Oscar-nominated Lady Bird takes place primarily in what California city?",
"answ":"SACRAMENTO",
"answ2":"Sacramento.",
},
{
"cat":"Coming of Age",
"ques":"Who played the dying girl in Me and Earl and the Dying Girl?",
"answ":"OLIVIA COOKE",
"answ3":"OLIVIA COOK",
"answ2":"Olivia Cooke.",
},
{
"cat":"Coming of Age",
"ques":"What nickname did the boys give to the large dog that lived next door to the ball field in The Sandlot?",
"answ":"THE BEAST",
"answ3":"BEAST",
"answ2":"The Beast.",
},
{
"cat":"Coming of Age",
"ques":"In Dazed and Confused, Pink and his friends try to get tickets for the concert of what rock band?",
"answ":"AEROSMITH",
"answ2":"Aerosmith.",
},
{
"cat":"Coming of Age",
"ques":"Who directed 1985's Explorers?",
"answ":"JOE DANTE",
"answ2":"Joe Dante.",
},
{
"cat":"Coming of Age",
"ques":"In Dazed and Confused, the senior guys ____ the incoming freshman boys.",
"answ":"PADDLE",
"answ3":"SPANK",
"answ2":"Paddle/spank.",
},
];
var r2Q15 = [
{
"cat":"Coming of Age",
"ques":"In the film Dazed and Confused, which president is set to have grown marihuana on his plantation?",
"answ":"GEORGE WASHINGTON",
"answ3":"WASHINGTON",
"answ2":"George Washington.",
"option":"<button id=corop class=buttons003 onclick=qcor()>George Washington</button><button id=incop2 class=buttons003 onclick=qinc()>Theodore Roosevelt</button><button id=incop3 class=buttons003 onclick=qinc()>Abraham Lincoln</button><button id=incop4 class=buttons003 onclick=qinc()>Thomas Jefferson</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls what breakfast food did Gretchen Wiener's father invent?",
"answ":"TOASTER STRUDEL",
"answ3":"TOASTER STRUDELS",
"answ2":"Toaster Strudel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pop-Tarts</button><button id=corop class=buttons003 onclick=qcor()>Toaster Strudel</button><button id=incop3 class=buttons003 onclick=qinc()>Eggo Waffles</button><button id=incop4 class=buttons003 onclick=qinc()>Breakfast Bowl</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What famous baseball player signed the ball that went over the fence in The Sandlot?",
"answ":"BABE RUTH",
"answ2":"Babe Ruth.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Barry Bonds</button><button id=incop2 class=buttons003 onclick=qinc()>Willie Mays</button><button id=corop class=buttons003 onclick=qcor()>Babe Ruth</button><button id=incop4 class=buttons003 onclick=qinc()>Ty Cobb</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What Lord of the Rings star made his film debut in The Goonies?",
"answ":"SEAN ASTIN",
"answ2":"Sean Astin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Elijah Wood</button><button id=incop2 class=buttons003 onclick=qinc()>Billy Boyd</button><button id=corop class=buttons003 onclick=qcor()>Sean Astin</button><button id=incop4 class=buttons003 onclick=qinc()>Dominic Monaghan</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What is the name of the high school football team that is the prime focus in Friday Night Lights?",
"answ":"PERMIAN PANTERS",
"answ3":"THE PERMIAN PANTERS",
"answ2":"Permian Panters.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>South Kingstown Rebels</button><button id=incop2 class=buttons003 onclick=qinc()>Compton Comets</button><button id=corop class=buttons003 onclick=qcor()>Permian Panters</button><button id=incop4 class=buttons003 onclick=qinc()>Toledo Rockets</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"The climax of Rebel Without a Cause starring James Dean takes place at which popular Hollywood landmark?",
"answ":"GRIFFITH OBSERVATORY",
"answ3":"THE GRIFFITH OBSERVATORY",
"answ2":"Griffith Observatory.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Griffith Observatory</button><button id=incop2 class=buttons003 onclick=qinc()>Dodger Stadium</button><button id=incop3 class=buttons003 onclick=qinc()>Greek Theatre</button><button id=incop4 class=buttons003 onclick=qinc()>Hollywood Bowl</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What famous director played Richard Dreyfuss's friend Steve in American Graffiti?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ron Howard</button><button id=incop2 class=buttons003 onclick=qinc()>Clint Eastwood</button><button id=incop3 class=buttons003 onclick=qinc()>Woody Allen</button><button id=incop4 class=buttons003 onclick=qinc()>Quentin Tarantino</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"At the end of Dead Poets Society the students show their support for mr. Keating by _____.",
"answ":"STANDING ON THEIR DESKS",
"answ3":"STANDING ON THEIR DESK",
"answ2":"Standing on their desks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Writing him letters</button><button id=incop2 class=buttons003 onclick=qinc()>Singing a song</button><button id=corop class=buttons003 onclick=qcor()>Standing on their desks</button><button id=incop4 class=buttons003 onclick=qinc()>Refusing to go to school</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Where do all of the students hang out in American Graffiti?",
"answ":"MEL'S DRIVE IN",
"answ3":"MELS DRIVE IN",
"answ2":"Mel's Drive-In.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>McDonalds</button><button id=incop2 class=buttons003 onclick=qinc()>KFC</button><button id=corop class=buttons003 onclick=qcor()>Mel's Drive-In</button><button id=incop4 class=buttons003 onclick=qinc()>Shopping Mall</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Perks of Being a Wallflower, what David Bowie song are the main characters listening to when they drive through the tunnel?",
"answ":"HEROES",
"answ2":"Heroes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Under Pressure</button><button id=incop2 class=buttons003 onclick=qinc()>Starman</button><button id=corop class=buttons003 onclick=qcor()>Heroes</button><button id=incop4 class=buttons003 onclick=qinc()>Rebel Rebel</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"According to the epilogue in Fast Times at Ridgemont High which celebrity does Spicoli save from drowning?",
"answ":"BROOKE SHIELDS",
"answ2":"Brooke Shields.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Farrah Fawcett</button><button id=corop class=buttons003 onclick=qcor()>Brooke Shields</button><button id=incop3 class=buttons003 onclick=qinc()>Jennifer Beals</button><button id=incop4 class=buttons003 onclick=qinc()>Olivia Newton-John</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What is the name of the main character, the boy, in Boyhood?",
"answ":"MASON",
"answ2":"Mason.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Elijah</button><button id=corop class=buttons003 onclick=qcor()>Mason</button><button id=incop3 class=buttons003 onclick=qinc()>Ricky</button><button id=incop4 class=buttons003 onclick=qinc()>John</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What song did Heath Ledger sing over the PA system to Julia Stiles during her soccer practice in 10 Things I Hate About You?",
"answ":"CAN'T TAKE MY EYES OFF YOU",
"answ2":"Can't Take My Eyes Off You.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Can't Take My Eyes Off You</button><button id=incop2 class=buttons003 onclick=qinc()>I Love You Always Forever</button><button id=incop3 class=buttons003 onclick=qinc()>I Will Always Love You</button><button id=incop4 class=buttons003 onclick=qinc()>Don't Go Away</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays shy 14-year-old Duncan in The Way Way Back?",
"answ":"LIAM JAMES",
"answ2":"Liam James.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Timothée Chalamet</button><button id=corop class=buttons003 onclick=qcor()>Liam James</button><button id=incop3 class=buttons003 onclick=qinc()>Brendan Meyer</button><button id=incop4 class=buttons003 onclick=qinc()>Hayden Christensen</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls, Lindsay Lohan's character joins a high school clique dubbed the ____.",
"answ":"PLASTICS",
"answ3":"THE PLASTICS",
"answ2":"Plastics.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wicked Stepdaughters</button><button id=incop2 class=buttons003 onclick=qinc()>Debs</button><button id=corop class=buttons003 onclick=qcor()>Plastics</button><button id=incop4 class=buttons003 onclick=qinc()>Cats</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What do Goonies never say?",
"answ":"DIE",
"answ2":"Die.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bye</button><button id=incop2 class=buttons003 onclick=qinc()>Loser</button><button id=corop class=buttons003 onclick=qcor()>Die</button><button id=incop4 class=buttons003 onclick=qinc()>Quit</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In The Perks of Being a Wallflower, what movie do the kids reenact live in the film?",
"answ":"THE ROCKY HORROR PICTURE SHOW",
"answ3":"ROCKY HORROR PICTURE SHOW",
"answ2":"The Rocky Horror Picture Show.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Titanic</button><button id=incop2 class=buttons003 onclick=qinc()>Psycho</button><button id=corop class=buttons003 onclick=qcor()>The Rocky Horror Picture Show</button><button id=incop4 class=buttons003 onclick=qinc()>One Flew Over the Cuckoo's Nest</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Say Anything, what does Lloyd say he wants to do for a career?",
"answ":"KICKBOXER",
"answ2":"Kickboxer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chef</button><button id=incop2 class=buttons003 onclick=qinc()>Radio DJ</button><button id=corop class=buttons003 onclick=qcor()>Kickboxer</button><button id=incop4 class=buttons003 onclick=qinc()>Bouncer</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who does Ferris pretend to be when he picks up Sloane from school in Ferris Bueller's Day Off?",
"answ":"HER FATHER",
"answ3":"HER DAD",
"answ2":"Her father.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Her brother</button><button id=corop class=buttons003 onclick=qcor()>Her father</button><button id=incop3 class=buttons003 onclick=qinc()>Her boyfriend</button><button id=incop4 class=buttons003 onclick=qinc()>Police agent</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What is used as a makeshift treehouse in 2012's Mud?",
"answ":"BOAT",
"answ3":"A BOAT",
"answ2":"a boat.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Boat</button><button id=incop2 class=buttons003 onclick=qinc()>Shipping container</button><button id=incop3 class=buttons003 onclick=qinc()>Tipi</button><button id=incop4 class=buttons003 onclick=qinc()>Cardboard Box</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Stand By Me, what is the name of the junkyard dog?",
"answ":"CHOPPER",
"answ2":"Chopper.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Chopper</button><button id=incop2 class=buttons003 onclick=qinc()>Sonny</button><button id=incop3 class=buttons003 onclick=qinc()>Gordie</button><button id=incop4 class=buttons003 onclick=qinc()>Tucker</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"The Way Way Back was written and directed by Nat Faxon and what other actor/director?",
"answ":"JIM RASH",
"answ2":"Jim Rash.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jim Rash</button><button id=incop2 class=buttons003 onclick=qinc()>Ben Stiller</button><button id=incop3 class=buttons003 onclick=qinc()>George Clooney</button><button id=incop4 class=buttons003 onclick=qinc()>Rob Reiner</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Sixteen Candles what is the nickname of Anthony Michael Hall's character?",
"answ":"FARMER TED",
"answ2":"Farmer Ted.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lumberjack</button><button id=incop2 class=buttons003 onclick=qinc()>Weasel</button><button id=incop3 class=buttons003 onclick=qinc()>Baker Boy</button><button id=corop class=buttons003 onclick=qcor()>Farmer Ted</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What performer with the surname Coppola had a cameo in Fast Times at Ridgemont High?",
"answ":"NICOLAS CAGE",
"answ3":"NIC CAGE",
"answ2":"Nicolas Cage.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Francis Ford Coppola</button><button id=incop2 class=buttons003 onclick=qinc()>August Coppola</button><button id=incop3 class=buttons003 onclick=qinc()>Sofia Coppola</button><button id=corop class=buttons003 onclick=qcor()>Nicolas Cage</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What does Claire give to Bender at the end of The Breakfast Club?",
"answ":"HER EARRING",
"answ3":"EARRING",
"answ2":"Her earring.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A book</button><button id=incop2 class=buttons003 onclick=qinc()>A pencil</button><button id=incop3 class=buttons003 onclick=qinc()>Her necklace</button><button id=corop class=buttons003 onclick=qcor()>Her earring</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In what school film does rebel John Bender describe his violent father?",
"answ":"THE BREAKFAST CLUB",
"answ3":"BREAKFAST CLUB",
"answ2":"The Breakfast Club.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Graduation</button><button id=incop2 class=buttons003 onclick=qinc()>Dazed and Confused</button><button id=incop3 class=buttons003 onclick=qinc()>Dead Poets Society</button><button id=corop class=buttons003 onclick=qcor()>The Breakfast Club</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In The Fault in Our Stars, Hazel and Gus travel to which European city?",
"answ":"AMSTERDAM",
"answ2":"Amsterdam.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paris</button><button id=incop2 class=buttons003 onclick=qinc()>Milan</button><button id=incop3 class=buttons003 onclick=qinc()>Berlin</button><button id=corop class=buttons003 onclick=qcor()>Amsterdam</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Pretty in Pink, which character lip-syncs to Otis Redding in the record store?",
"answ":"DUCKIE",
"answ3":"DUCKY",
"answ2":"Duckie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andie</button><button id=incop2 class=buttons003 onclick=qinc()>Jack</button><button id=incop3 class=buttons003 onclick=qinc()>Iona</button><button id=corop class=buttons003 onclick=qcor()>Duckie</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What SNL alumn appears in Adventureland as park manager Paulette?",
"answ":"KRISTEN WIIG",
"answ3":"KIRSTEN WIIG",
"answ2":"Kristen Wiig.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Maya Rudolph</button><button id=incop2 class=buttons003 onclick=qinc()>Tina Fey</button><button id=incop3 class=buttons003 onclick=qinc()>Amy Poehler</button><button id=corop class=buttons003 onclick=qcor()>Kristen Wiig</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What word of advice is whispered to Dustin Hoffman in 1967's The Graduate?",
"answ":"PLASTICS",
"answ2":"Plastics.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Plastics</button><button id=incop2 class=buttons003 onclick=qinc()>Sugar-free</button><button id=incop3 class=buttons003 onclick=qinc()>Computers</button><button id=incop4 class=buttons003 onclick=qinc()>Exercise</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays teenage Rolling Stone reporter William Miller in Almost Famous?",
"answ":"PATRICK FUGIT",
"answ2":"Patrick Fugit.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Patrick Fugit</button><button id=incop2 class=buttons003 onclick=qinc()>Billy Crudup</button><button id=incop3 class=buttons003 onclick=qinc()>Jason Lee</button><button id=incop4 class=buttons003 onclick=qinc()>Noah Wyle</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Jeff Daniels and Laura Linney play a couple separating in what 2005 dramedy?",
"answ":"THE SQUID AND THE WHALE",
"answ3":"SQUID AND THE WHALE",
"answ2":"The Squid and the Whale.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Squid and the Whale</button><button id=incop2 class=buttons003 onclick=qinc()>Imaginary Heroes</button><button id=incop3 class=buttons003 onclick=qinc()>Because of Winn-Dixie</button><button id=incop4 class=buttons003 onclick=qinc()>Kinsey</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"James Ponsoldt directed Miles Teller in which film?",
"answ":"THE SPECTACULAR NOW",
"answ3":"SPECTACULAR NOW",
"answ2":"The Spectacular Now.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>21 & Over</button><button id=incop2 class=buttons003 onclick=qinc()>Project X</button><button id=corop class=buttons003 onclick=qcor()>The Spectacular Now</button><button id=incop4 class=buttons003 onclick=qinc()>That Awkward Moment</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who played the character of Chris Chambers in the film Stand By Me?",
"answ":"RIVER PHOENIX",
"answ2":"River Phoenix.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jerry O'Connell</button><button id=incop2 class=buttons003 onclick=qinc()>John Cusack</button><button id=corop class=buttons003 onclick=qcor()>River Phoenix</button><button id=incop4 class=buttons003 onclick=qinc()>Corey Feldman</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who played Sloane Peterson in Ferris Bueller's Day Off?",
"answ":"MIA SARA",
"answ2":"Mia Sara.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jennifer Grey</button><button id=incop2 class=buttons003 onclick=qinc()>Lea Thompson</button><button id=corop class=buttons003 onclick=qcor()>Mia Sara</button><button id=incop4 class=buttons003 onclick=qinc()>Elisabeth Shue</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays Vada's father Harry Sultenfuss in 1991's My Girl?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jim Belushi</button><button id=incop2 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><button id=corop class=buttons003 onclick=qcor()>Dan Aykroyd</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Murray</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What is the last name of Cady, played by Lindsay Lohan, in Mean Girls?",
"answ":"HERON",
"answ2":"Heron.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Heron</button><button id=incop2 class=buttons003 onclick=qinc()>Weiners</button><button id=incop3 class=buttons003 onclick=qinc()>George</button><button id=incop4 class=buttons003 onclick=qinc()>Cassington</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who played opposite James Dean as Judy in Rebel Without a Cause?",
"answ":"NATALIE WOOD",
"answ2":"Natalie Wood.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Natalie Wood</button><button id=incop2 class=buttons003 onclick=qinc()>Julie Harris</button><button id=incop3 class=buttons003 onclick=qinc()>Elizabeth Taylor</button><button id=incop4 class=buttons003 onclick=qinc()>Donna Reed</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays the strict father Mr. Perry in Dead Poets Society?",
"answ":"KURTWOOD SMITH",
"answ2":"Kurtwood Smith.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kurtwood Smith</button><button id=incop2 class=buttons003 onclick=qinc()>Bryan Cranston</button><button id=incop3 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Harris</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What seminal drama marked the first movie for Ice Cube in an acting role?",
"answ":"BOYS N THE HOOD",
"answ3":"BOYZ N THE HOOD",
"answ2":"Boyz N the Hood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Juice</button><button id=corop class=buttons003 onclick=qcor()>Boyz N the Hood</button><button id=incop3 class=buttons003 onclick=qinc()>Menace II Society</button><button id=incop4 class=buttons003 onclick=qinc()>Straight Out of Compton</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Perks of Being a Wallflower, who played Charlie's English teacher and mentor, Mr. Anderson?",
"answ":"PAUL RUDD",
"answ2":"Paul Rudd.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dylan McDermott</button><button id=incop2 class=buttons003 onclick=qinc()>Tom Savini</button><button id=corop class=buttons003 onclick=qcor()>Paul Rudd</button><button id=incop4 class=buttons003 onclick=qinc()>Nicholas Braun</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In 1987's Adventures in Babysitting, who is credited as playing Thor?",
"answ":"VINCENT D'ONOFRIO",
"answ3":"VINCENT D'NOFRIO",
"answ2":"Vincent D'Onofrio.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bill Paxton</button><button id=incop2 class=buttons003 onclick=qinc()>Philip Seymour Hoffman</button><button id=corop class=buttons003 onclick=qcor()>Vincent D'Onofrio</button><button id=incop4 class=buttons003 onclick=qinc()>Bradley Whitford</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who directed Joseph Gordon-Levitt in 500 Days of Summer?",
"answ":"MARC WEBB",
"answ3":"MARK WEBB",
"answ2":"Marc Webb.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paul Feig</button><button id=incop2 class=buttons003 onclick=qinc()>Todd Phillips</button><button id=corop class=buttons003 onclick=qcor()>Marc Webb</button><button id=incop4 class=buttons003 onclick=qinc()>Judd Apatow</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What is Ferris Bueller's girlfriend's name?",
"answ":"SLOANE",
"answ2":"Sloane.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dina</button><button id=corop class=buttons003 onclick=qcor()>Sloane</button><button id=incop3 class=buttons003 onclick=qinc()>Gwynn</button><button id=incop4 class=buttons003 onclick=qinc()>Shaune</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Wet Hot American Summer, two camp councelors get married. Michael Ian Black played one of them. Who played the other?",
"answ":"BRADLEY COOPER",
"answ2":"Bradley Cooper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paul Rudd</button><button id=incop2 class=buttons003 onclick=qinc()>Janeane Garofalo</button><button id=incop3 class=buttons003 onclick=qinc()>Elizabeth Banks</button><button id=corop class=buttons003 onclick=qcor()>Bradley Cooper</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What was the only Oscar won by the 2014 coming of age drama Boyhood?",
"answ":"BEST SUPPORTING ACTRESS",
"answ3":"SUPPORTING ACTRESS",
"answ2":"Best Supporting Actress.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Actress</button><button id=incop2 class=buttons003 onclick=qinc()>Best Supporting Actor</button><button id=incop3 class=buttons003 onclick=qinc()>Best Actor</button><button id=corop class=buttons003 onclick=qcor()>Best Supporting Actress</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Ferris Bueller's Day Off, what hockey team's jersey does Cameron wear throughout the movie?",
"answ":"DETROIT RED WINGS",
"answ3":"RED WINGS",
"answ2":"Detroit Red Wings.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago Blackhawks</button><button id=incop2 class=buttons003 onclick=qinc()>Montreal Canadiens</button><button id=corop class=buttons003 onclick=qcor()>Detroit Red Wings</button><button id=incop4 class=buttons003 onclick=qinc()>Ottawa Senators</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who played Juno's stepmother in 2007's Juno?",
"answ":"ALLISON JANNEY",
"answ3":"ALISSON JANNEY",
"answ2":"Allison Janney.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jennifer Garner</button><button id=incop2 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=corop class=buttons003 onclick=qcor()>Allison Janney</button><button id=incop4 class=buttons003 onclick=qinc()>Maggie Gyllenhaal</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What color is John Milner's iconic 1932 Ford Coupe that he races in American Graffiti?",
"answ":"YELLOW",
"answ2":"Yellow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>White</button><button id=incop2 class=buttons003 onclick=qinc()>Red</button><button id=corop class=buttons003 onclick=qcor()>Yellow</button><button id=incop4 class=buttons003 onclick=qinc()>Black</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who directed 2017's Call Me By Your Name?",
"answ":"LUCA GUADAGNINO",
"answ3":"LUCA GUADAGINO",
"answ2":"Luca Guadagnino.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Greg Berlanti</button><button id=incop2 class=buttons003 onclick=qinc()>Saoirse Ronan</button><button id=corop class=buttons003 onclick=qcor()>Luca Guadagnino</button><button id=incop4 class=buttons003 onclick=qinc()>Barry Jenkins</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Love Simon, who plays Simon's father Jack?",
"answ":"JOSH DUHAMEL",
"answ2":"Josh Duhamel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jason Bateman</button><button id=incop2 class=buttons003 onclick=qinc()>Timothy Olyphant</button><button id=incop3 class=buttons003 onclick=qinc()>Rainn Wilson</button><button id=corop class=buttons003 onclick=qcor()>Josh Duhamel</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays the adult version of Haley Joel Osment's character in Secondhand Lions?",
"answ":"JOSH LUCAS",
"answ2":"Josh Lucas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=corop class=buttons003 onclick=qcor()>Josh Lucas</button><button id=incop3 class=buttons003 onclick=qinc()>Luke Wilson</button><button id=incop4 class=buttons003 onclick=qinc()>Viggo Mortensen</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Rob Reiner directed what 2010 movie about two 8th graders who start to have feelings for each other despite being total opposites?",
"answ":"FLIPPED",
"answ2":"Flipped.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Palo Alto</button><button id=incop2 class=buttons003 onclick=qinc()>Submarine</button><button id=corop class=buttons003 onclick=qcor()>Flipped</button><button id=incop4 class=buttons003 onclick=qinc()>The Runaways</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In Stand By Me, how does narrator Richard Dreyfuss say River Phoenix's character Chris died?",
"answ":"STABBED",
"answ3":"HE WAS STABBED",
"answ2":"Stabbed.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Stabbed</button><button id=incop2 class=buttons003 onclick=qinc()>Pushed in front of a train</button><button id=incop3 class=buttons003 onclick=qinc()>Heart attack</button><button id=incop4 class=buttons003 onclick=qinc()>Choked on a pretzel</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What coming of age movie is based on the life of Chazz Palminteri?",
"answ":"A BRONX TALE",
"answ3":"BRONX TALE",
"answ2":"A Bronx Tale.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A Bronx Tale</button><button id=incop2 class=buttons003 onclick=qinc()>Mad Love</button><button id=incop3 class=buttons003 onclick=qinc()>October Sky</button><button id=incop4 class=buttons003 onclick=qinc()>That Night</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Josh Hamilton plays father to Elsie Fisher in what coming of age film?",
"answ":"EIGHT GRADE",
"answ2":"Eight Grade.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Diary of a Teenage Girl</button><button id=incop2 class=buttons003 onclick=qinc()>The Miseducation of Cameron Poe</button><button id=corop class=buttons003 onclick=qcor()>Eight Grade</button><button id=incop4 class=buttons003 onclick=qinc()>Brooklyn</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"John and Joan Cusack star in what 1984 coming of age film?",
"answ":"SIXTEEN CANDLES",
"answ2":"Sixteen Candles.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pretty in Pink</button><button id=incop2 class=buttons003 onclick=qinc()>Footloose</button><button id=incop3 class=buttons003 onclick=qinc()>Say Anything</button><button id=corop class=buttons003 onclick=qcor()>Sixteen Candles</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who plays the difficult and wealthy boyfriend, Trent, of Duncan's mother in The Way, Way Back?",
"answ":"STEVE CARELL",
"answ2":"Steve Carell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jason Clarke</button><button id=incop2 class=buttons003 onclick=qinc()>Casey Affleck</button><button id=incop3 class=buttons003 onclick=qinc()>Colin Farrell</button><button id=corop class=buttons003 onclick=qcor()>Steve Carell</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Who stars as a charismatic teen genius named Chris Knight, in 1985's Real Genius?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christian Slater</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Biehn</button><button id=incop3 class=buttons003 onclick=qinc()>Brad Pitt</button><button id=corop class=buttons003 onclick=qcor()>Val Kilmer</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What school subject did Max Fischer say he 'saved' in Rushmore?",
"answ":"LATIN",
"answ2":"Latin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Math</button><button id=incop2 class=buttons003 onclick=qinc()>Spanish</button><button id=incop3 class=buttons003 onclick=qinc()>English</button><button id=corop class=buttons003 onclick=qcor()>Latin</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Which actress plays the title character in the teen comedy I Love You, Beth Cooper?",
"answ":"HAYDEN PANETTIERE",
"answ3":"HAYDEN PANETIERE",
"answ2":"Hayden Panettiere.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Megan Fox</button><button id=incop2 class=buttons003 onclick=qinc()>Blake Lively</button><button id=incop3 class=buttons003 onclick=qinc()>Hilary Duff</button><button id=corop class=buttons003 onclick=qcor()>Hayden Panettiere</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Boyhood takes place in what U.S. State?",
"answ":"TEXAS",
"answ2":"Texas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Florida</button><button id=incop2 class=buttons003 onclick=qinc()>South Carolina</button><button id=incop3 class=buttons003 onclick=qinc()>California</button><button id=corop class=buttons003 onclick=qcor()>Texas</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"In the 1992 movie School Ties, Matt Damon's character cheats on a final exam on what subject near the end of the movie?",
"answ":"HISTORY",
"answ2":"History.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chemistry</button><button id=incop2 class=buttons003 onclick=qinc()>French</button><button id=corop class=buttons003 onclick=qcor()>History</button><button id=incop4 class=buttons003 onclick=qinc()>Calculus</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What 2012 coming of age film stars Logan Lerman, Ezra Miller and Emma Watson?",
"answ":"THE PERKS OF BEING A WALLFLOWER",
"answ3":"PERKS OF BEING A WALLFLOWER",
"answ2":"The Perks of Being a Wallflower.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Perks of Being a Wallflower</button><button id=incop2 class=buttons003 onclick=qinc()>The Bling Ring</button><button id=incop3 class=buttons003 onclick=qinc()>Silver Linings Playbook</button><button id=incop4 class=buttons003 onclick=qinc()>Seeking a Friend for the End of the World</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"What 1983 Francis Ford Coppola film revolves around Oklahoma greasers played by young stars such as C. Thom Howell, Matt Dillon and Patrick Swayze?",
"answ":"THE OUTSIDERS",
"answ2":"The Outsiders.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Cotton Club</button><button id=corop class=buttons003 onclick=qcor()>The Outsiders</button><button id=incop3 class=buttons003 onclick=qinc()>Rumble Fish</button><button id=incop4 class=buttons003 onclick=qinc()>One from the Heart</button><br/>",
},
{
"cat":"Coming of Age",
"ques":"Which actor played Simon in 2018's Love, Simon?",
"answ":"NICK ROBINSON",
"answ2":"Nick Robinson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ansel Elgort</button><button id=corop class=buttons003 onclick=qcor()>Nick Robinson</button><button id=incop3 class=buttons003 onclick=qinc()>Taron Egerton</button><button id=incop4 class=buttons003 onclick=qinc()>Timothée Chalamet</button><br/>",
},
];
comingofage = shuffle(comingofage);
r2Q15 = shuffle(r2Q15);