var comingofage = [
{
"cat":"Coming of Age",
"ques":"Who directed Stand By Me?",
"answ":"ROB REINER",
"answ2":"Rob Reiner.",
},
{
"cat":"Coming of Age",
"ques":"Who directed 2000's Billy Elliot?",
"answ":"STEPHEN DALDRY",
"answ2":"Stephen Daldry.",
},
{
"cat":"Coming of Age",
"ques":"Who plays Hailee Steinfeld's brother in The Edge of Seventeen?",
"answ":"BLAKE JENNER",
"answ2":"Blake Jenner.",
},
{
"cat":"Coming of Age",
"ques":"Carey Mulligan stars as a teenage girl growing up in 1960s London who begins a relationship with an older man in what 2010 film?",
"answ":"AN EDUCATION",
"answ2":"An Education.",
},
{
"cat":"Coming of Age",
"ques":"In 1979's Breaking Away, four working class teens face off against snobby university students in what sport?",
"answ":"CYCLING",
"answ3":"COMPETITIVE CYCLING",
"answ2":"Cycling.",
},
{
"cat":"Coming of Age",
"ques":"In what 1973 George Lucas film can you find the stars Ron Howard, Harrison Ford and Richard Dreyfuss?",
"answ":"AMERICAN GRAFFITI",
"answ3":"AMERICAN GRAFITI",
"answ2":"American Graffiti.",
},
{
"cat":"Coming of Age",
"ques":"What 1967 coming of age drama involves a love triangle between Katharine Ross, Anne Bancroft and Dustin Hoffman?",
"answ":"THE GRADUATE",
"answ2":"The Graduate.",
},
{
"cat":"Coming of Age",
"ques":"What MCU actor plays Brand, Mikey's older brother, in The Goonies?",
"answ":"JOSH BROLIN",
"answ2":"Josh Brolin.",
},
{
"cat":"Coming of Age",
"ques":"Who directed The Breakfast Club?",
"answ":"JOHN HUGHES",
"answ3":"JON HUGHES",
"answ2":"John Hughes.",
},
{
"cat":"Coming of Age",
"ques":"Who played 'Mouth' in The Goonies?",
"answ":"COREY FELDMAN",
"answ3":"CORY FELDMAN",
"answ2":"Corey Feldman.",
},
{
"cat":"Coming of Age",
"ques":"What 2018 coming-of-age film stars Nick Robinson, Jennifer Garner and Josh Duhamel?",
"answ":"LOVE SIMON",
"answ3":"LOVE  SIMON",
"answ2":"Love, Simon.",
},
{
"cat":"Coming of Age",
"ques":"Who played Sharon Norbury, the calculus teacher, in Mean Girls?",
"answ":"TINA FEY",
"answ3":"TINA FAY",
"answ2":"Tina Fey.",
},
{
"cat":"Coming of Age",
"ques":"What is the title of the 1979 sequel to American Graffiti?",
"answ":"MORE AMERICAN GRAFFITI",
"answ3":"MORE AMERICAN GRAFITI",
"answ2":"More American Graffiti.",
},
{
"cat":"Coming of Age",
"ques":"What Wes Anderson film follows young kids Sam Shakusky and Suzy Bishop, who fall in love in the 1960s?",
"answ":"MOONRISE KINGDOM",
"answ2":"Moonrise Kingdom.",
},
{
"cat":"Coming of Age",
"ques":"Bo Burnham wrote and directed this 2018 coming of age film.",
"answ":"EIGHT GRADE",
"answ2":"Eight Grade.",
},
{
"cat":"Coming of Age",
"ques":"In what coming of age film does Jesse Eisenberg play a character who works at an amusement park for the summer?",
"answ":"ADVENTURELAND",
"answ2":"Adventureland.",
},
{
"cat":"Coming of Age",
"ques":"What 2010 coming of age biopic stars Kristen Stewart and Dakota Fanning as 70s rockers Joan Jett and Cherie Currie?",
"answ":"THE RUNAWAYS",
"answ2":"The Runaways.",
},
{
"cat":"Coming of Age",
"ques":"Which DCEU actor plays a teen named Patrick in The Perks of Being a Wallflower?",
"answ":"EZRA MILLER",
"answ2":"Ezra Miller.",
},
{
"cat":"Coming of Age",
"ques":"What 2002 drama follows a young Maori girl trying to claim her place as chief amongst a strictly patriarchal New Zealand tribe?",
"answ":"WHALE RIDER",
"answ2":"Whale Rider.",
},
{
"cat":"Coming of Age",
"ques":"What 2005 coming of age film stars Amber Tamblyn, America Ferrera and Blake Lively?",
"answ":"THE SISTERHOOD OF THE TRAVELING PANTS",
"answ3":"SISTERHOOD OF THE TRAVELING PANTS",
"answ2":"The Sisterhood of the Traveling Pants.",
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls, which character said the quote: 'Stop trying to make fetch happen, it's not going to happen'?",
"answ":"REGINA",
"answ2":"Regina.",
},
{
"cat":"Coming of Age",
"ques":"Michael Caine and Robert Duvall play eccentric uncles to a boy named Walter in what film?",
"answ":"SECONDHAND LIONS",
"answ2":"Secondhand Lions.",
},
{
"cat":"Coming of Age",
"ques":"The Oscar-nominated Lady Bird takes place primarily in what California city?",
"answ":"SACRAMENTO",
"answ2":"Sacramento.",
},
{
"cat":"Coming of Age",
"ques":"Who played the dying girl in Me and Earl and the Dying Girl?",
"answ":"OLIVIA COOKE",
"answ3":"OLIVIA COOK",
"answ2":"Olivia Cooke.",
},
{
"cat":"Coming of Age",
"ques":"What nickname did the boys give to the large dog that lived next door to the ball field in The Sandlot?",
"answ":"THE BEAST",
"answ3":"BEAST",
"answ2":"The Beast.",
},
{
"cat":"Coming of Age",
"ques":"In Dazed and Confused, Pink and his friends try to get tickets for the concert of what rock band?",
"answ":"AEROSMITH",
"answ2":"Aerosmith.",
},
{
"cat":"Coming of Age",
"ques":"Who directed 1985's Explorers?",
"answ":"JOE DANTE",
"answ2":"Joe Dante.",
},
{
"cat":"Coming of Age",
"ques":"In Dazed and Confused, the senior guys ____ the incoming freshman boys.",
"answ":"PADDLE",
"answ3":"SPANK",
"answ2":"Paddle/spank.",
},
];
var r2Q15 = [
{
"cat":"Coming of Age",
"ques":"In the film Dazed and Confused, which president is set to have grown marihuana on his plantation?",
"answ":"GEORGE WASHINGTON",
"answ3":"WASHINGTON",
"answ2":"George Washington.",
"option":["George Washington", "Theodore Roosevelt", "Abraham Lincoln", "Thomas Jefferson"],
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls what breakfast food did Gretchen Wiener's father invent?",
"answ":"TOASTER STRUDEL",
"answ3":"TOASTER STRUDELS",
"answ2":"Toaster Strudel.",
"option":["Toaster Strudel", "Pop-Tarts", "Eggo Waffles", "Breakfast Bowl"],
},
{
"cat":"Coming of Age",
"ques":"What famous baseball player signed the ball that went over the fence in The Sandlot?",
"answ":"BABE RUTH",
"answ2":"Babe Ruth.",
"option":["Babe Ruth", "Barry Bonds", "Willie Mays", "Ty Cobb"],
},
{
"cat":"Coming of Age",
"ques":"What Lord of the Rings star made his film debut in The Goonies?",
"answ":"SEAN ASTIN",
"answ2":"Sean Astin.",
"option":["Sean Astin", "Elijah Wood", "Billy Boyd", "Dominic Monaghan"],
},
{
"cat":"Coming of Age",
"ques":"What is the name of the high school football team that is the prime focus in Friday Night Lights?",
"answ":"PERMIAN PANTERS",
"answ3":"THE PERMIAN PANTERS",
"answ2":"Permian Panters.",
"option":["Permian Panters", "South Kingstown Rebels", "Compton Comets", "Toledo Rockets"],
},
{
"cat":"Coming of Age",
"ques":"The climax of Rebel Without a Cause starring James Dean takes place at which popular Hollywood landmark?",
"answ":"GRIFFITH OBSERVATORY",
"answ3":"THE GRIFFITH OBSERVATORY",
"answ2":"Griffith Observatory.",
"option":["Griffith Observatory", "Dodger Stadium", "Greek Theatre", "Hollywood Bowl"],
},
{
"cat":"Coming of Age",
"ques":"What famous director played Richard Dreyfuss's friend Steve in American Graffiti?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":["Ron Howard", "Clint Eastwood", "Woody Allen", "Quentin Tarantino"],
},
{
"cat":"Coming of Age",
"ques":"At the end of Dead Poets Society the students show their support for mr. Keating by _____.",
"answ":"STANDING ON THEIR DESKS",
"answ3":"GETTING ON THEIR DESK",
"answ2":"Standing on their desks.",
"option":["Standing on their desks", "Writing him letters", "Singing a song", "Refusing to go to school"],
},
{
"cat":"Coming of Age",
"ques":"Where do all of the students hang out in American Graffiti?",
"answ":"MEL'S DRIVE IN",
"answ3":"MELS DRIVE IN",
"answ2":"Mel's Drive-In.",
"option":["Mel's Drive-In", "McDonalds", "KFC", "Shopping Mall"],
},
{
"cat":"Coming of Age",
"ques":"In Perks of Being a Wallflower, what David Bowie song are the main characters listening to when they drive through the tunnel?",
"answ":"HEROES",
"answ2":"Heroes.",
"option":["Heroes", "Under Pressure", "Starman", "Rebel Rebel"],
},
{
"cat":"Coming of Age",
"ques":"According to the epilogue in Fast Times at Ridgemont High which celebrity does Spicoli save from drowning?",
"answ":"BROOKE SHIELDS",
"answ2":"Brooke Shields.",
"option":["Brooke Shields", "Farrah Fawcett", "Jennifer Beals", "Olivia Newton-John"],
},
{
"cat":"Coming of Age",
"ques":"What is the name of the main character, the boy, in Boyhood?",
"answ":"MASON",
"answ2":"Mason.",
"option":["Mason", "Elijah", "Ricky", "John"],
},
{
"cat":"Coming of Age",
"ques":"What song did Heath Ledger sing over the PA system to Julia Stiles during her soccer practice in 10 Things I Hate About You?",
"answ":"CAN'T TAKE MY EYES OFF YOU",
"answ2":"Can't Take My Eyes Off You.",
"option":["Can't Take My Eyes Off You", "I Love You Always Forever", "I Will Always Love You", "Don't Go Away"],
},
{
"cat":"Coming of Age",
"ques":"Who plays shy 14-year-old Duncan in The Way Way Back?",
"answ":"LIAM JAMES",
"answ2":"Liam James.",
"option":["Liam James", "Timothée Chalamet", "Brendan Meyer", "Hayden Christensen"],
},
{
"cat":"Coming of Age",
"ques":"In Mean Girls, Lindsay Lohan's character joins a high school clique dubbed the ____.",
"answ":"PLASTICS",
"answ3":"THE PLASTICS",
"answ2":"Plastics.",
"option":["Plastics", "Wicked Stepdaughters", "Debs", "Cats"],
},
{
"cat":"Coming of Age",
"ques":"What do Goonies never say?",
"answ":"DIE",
"answ2":"Die.",
"option":["Die", "Bye", "Loser", "Quit"],
},
{
"cat":"Coming of Age",
"ques":"In The Perks of Being a Wallflower, what movie do the kids reenact live in the film?",
"answ":"THE ROCKY HORROR PICTURE SHOW",
"answ3":"ROCKY HORROR PICTURE SHOW",
"answ2":"The Rocky Horror Picture Show.",
"option":["The Rocky Horror Picture Show", "Titanic", "Psycho", "One Flew Over the Cuckoo's Nest"],
},
{
"cat":"Coming of Age",
"ques":"In Say Anything, what does Lloyd say he wants to do for a career?",
"answ":"KICKBOXER",
"answ2":"Kickboxer.",
"option":["Kickboxer", "Chef", "Radio DJ", "Bouncer"],
},
{
"cat":"Coming of Age",
"ques":"Who does Ferris pretend to be when he picks up Sloane from school in Ferris Bueller's Day Off?",
"answ":"HER FATHER",
"answ3":"HER DAD",
"answ2":"Her father.",
"option":["Her father", "Her brother", "Her boyfriend", "Police agent"],
},
{
"cat":"Coming of Age",
"ques":"What is used as a makeshift treehouse in 2012's Mud?",
"answ":"BOAT",
"answ3":"A BOAT",
"answ2":"a boat.",
"option":["Boat", "Shipping container", "Tipi", "Cardboard Box"],
},
{
"cat":"Coming of Age",
"ques":"In Stand By Me, what is the name of the junkyard dog?",
"answ":"CHOPPER",
"answ2":"Chopper.",
"option":["Chopper", "Sonny", "Gordie", "Tucker"],
},
{
"cat":"Coming of Age",
"ques":"The Way Way Back was written and directed by Nat Faxon and what other actor/director?",
"answ":"JIM RASH",
"answ2":"Jim Rash.",
"option":["Jim Rash", "Ben Stiller", "George Clooney", "Rob Reiner"],
},
{
"cat":"Coming of Age",
"ques":"In Sixteen Candles what is the nickname of Anthony Michael Hall's character?",
"answ":"FARMER TED",
"answ2":"Farmer Ted.",
"option":["Farmer Ted", "Lumberjack", "Weasel", "Baker Boy"],
},
{
"cat":"Coming of Age",
"ques":"What performer with the surname Coppola had a cameo in Fast Times at Ridgemont High?",
"answ":"NICOLAS CAGE",
"answ3":"NIC CAGE",
"answ2":"Nicolas Cage.",
"option":["Nicolas Cage", "Francis Ford Coppola", "August Coppola", "Sofia Coppola"],
},
{
"cat":"Coming of Age",
"ques":"What does Claire give to Bender at the end of The Breakfast Club?",
"answ":"HER EARRING",
"answ3":"EARRING",
"answ2":"Her earring.",
"option":["Her earring", "A book", "A pencil", "Her necklace"],
},
{
"cat":"Coming of Age",
"ques":"In what school film does rebel John Bender describe his violent father?",
"answ":"THE BREAKFAST CLUB",
"answ3":"BREAKFAST CLUB",
"answ2":"The Breakfast Club.",
"option":["The Breakfast Club", "Graduation", "Dazed and Confused", "Dead Poets Society"],
},
{
"cat":"Coming of Age",
"ques":"In Pretty in Pink, which character lip-syncs to Otis Redding in the record store?",
"answ":"DUCKIE",
"answ3":"DUCKY",
"answ2":"Duckie.",
"option":["Duckie", "Andie", "Jack", "Iona"],
},
{
"cat":"Coming of Age",
"ques":"What SNL alumn appears in Adventureland as park manager Paulette?",
"answ":"KRISTEN WIIG",
"answ3":"KIRSTEN WIIG",
"answ2":"Kristen Wiig.",
"option":["Kristen Wiig", "Maya Rudolph", "Tina Fey", "Amy Poehler"],
},
{
"cat":"Coming of Age",
"ques":"What word of advice is whispered to Dustin Hoffman in 1967's The Graduate?",
"answ":"PLASTICS",
"answ2":"Plastics.",
"option":["Plastics", "Sugar-free", "Computers", "Exercise"],
},
{
"cat":"Coming of Age",
"ques":"Who plays teenage Rolling Stone reporter William Miller in Almost Famous?",
"answ":"PATRICK FUGIT",
"answ2":"Patrick Fugit.",
"option":["Patrick Fugit", "Billy Crudup", "Jason Lee", "Noah Wyle"],
},
{
"cat":"Coming of Age",
"ques":"Jeff Daniels and Laura Linney play a couple separating in what 2005 dramedy?",
"answ":"THE SQUID AND THE WHALE",
"answ3":"SQUID AND THE WHALE",
"answ2":"The Squid and the Whale.",
"option":["The Squid and the Whale", "Imaginary Heroes", "Because of Winn-Dixie", "Kinsey"],
},
{
"cat":"Coming of Age",
"ques":"James Ponsoldt directed Miles Teller in which film?",
"answ":"THE SPECTACULAR NOW",
"answ3":"SPECTACULAR NOW",
"answ2":"The Spectacular Now.",
"option":["The Spectacular Now", "21 & Over", "Project X", "That Awkward Moment"],
},
{
"cat":"Coming of Age",
"ques":"Who played the character of Chris Chambers in the film Stand By Me?",
"answ":"RIVER PHOENIX",
"answ2":"River Phoenix.",
"option":["River Phoenix", "Jerry O'Connell", "John Cusack", "Corey Feldman"],
},
{
"cat":"Coming of Age",
"ques":"Who played Sloane Peterson in Ferris Bueller's Day Off?",
"answ":"MIA SARA",
"answ2":"Mia Sara.",
"option":["Mia Sara", "Jennifer Grey", "Lea Thompson", "Elisabeth Shue"],
},
{
"cat":"Coming of Age",
"ques":"Who plays Vada's father Harry Sultenfuss in 1991's My Girl?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
"option":["Dan Aykroyd", "Jim Belushi", "Richard Dreyfuss", "Bill Murray"],
},
{
"cat":"Coming of Age",
"ques":"What is the last name of Cady, played by Lindsay Lohan, in Mean Girls?",
"answ":"HERON",
"answ2":"Heron.",
"option":["Heron", "Weiners", "George", "Cassington"],
},
{
"cat":"Coming of Age",
"ques":"Who played opposite James Dean as Judy in Rebel Without a Cause?",
"answ":"NATALIE WOOD",
"answ2":"Natalie Wood.",
"option":["Natalie Wood", "Julie Harris", "Elizabeth Taylor", "Donna Reed"],
},
{
"cat":"Coming of Age",
"ques":"Who plays the strict father Mr. Perry in Dead Poets Society?",
"answ":"KURTWOOD SMITH",
"answ2":"Kurtwood Smith.",
"option":["Kurtwood Smith", "Bryan Cranston", "Richard Dreyfuss", "Ed Harris"],
},
{
"cat":"Coming of Age",
"ques":"What seminal drama marked the first movie for Ice Cube in an acting role?",
"answ":"BOYS N THE HOOD",
"answ3":"BOYZ N THE HOOD",
"answ2":"Boyz N the Hood.",
"option":["Boyz N the Hood", "Juice", "Menace II Society", "Straight Out of Compton"],
},
{
"cat":"Coming of Age",
"ques":"In Perks of Being a Wallflower, who played Charlie's English teacher and mentor, Mr. Anderson?",
"answ":"PAUL RUDD",
"answ2":"Paul Rudd.",
"option":["Paul Rudd", "Dylan McDermott", "Tom Savini", "Nicholas Braun"],
},
{
"cat":"Coming of Age",
"ques":"In 1987's Adventures in Babysitting, who is credited as playing Thor?",
"answ":"VINCENT D'ONOFRIO",
"answ3":"VINCENT D'NOFRIO",
"answ2":"Vincent D'Onofrio.",
"option":["Vincent D'Onofrio", "Bill Paxton", "Philip Seymour Hoffman", "Bradley Whitford"],
},
{
"cat":"Coming of Age",
"ques":"Who directed Joseph Gordon-Levitt in 500 Days of Summer?",
"answ":"MARC WEBB",
"answ3":"MARK WEBB",
"answ2":"Marc Webb.",
"option":["Marc Webb", "Paul Feig", "Todd Phillips", "Judd Apatow"],
},
{
"cat":"Coming of Age",
"ques":"What is Ferris Bueller's girlfriend's name?",
"answ":"SLOANE",
"answ2":"Sloane.",
"option":["Sloane", "Dina", "Gwynn", "Shaune"],
},
{
"cat":"Coming of Age",
"ques":"In Wet Hot American Summer, two camp councelors get married. Michael Ian Black played one of them. Who played the other?",
"answ":"BRADLEY COOPER",
"answ2":"Bradley Cooper.",
"option":["Bradley Cooper", "Paul Rudd", "Janeane Garofalo", "Elizabeth Banks"],
},
{
"cat":"Coming of Age",
"ques":"What was the only Oscar won by the 2014 coming of age drama Boyhood?",
"answ":"BEST SUPPORTING ACTRESS",
"answ3":"SUPPORTING ACTRESS",
"answ2":"Best Supporting Actress.",
"option":["Best Supporting Actress", "Best Actress", "Best Supporting Actor", "Best Actor"],
},
{
"cat":"Coming of Age",
"ques":"In Ferris Bueller's Day Off, what hockey team's jersey does Cameron wear throughout the movie?",
"answ":"DETROIT RED WINGS",
"answ3":"RED WINGS",
"answ2":"Detroit Red Wings.",
"option":["Detroit Red Wings", "Chicago Blackhawks", "Montreal Canadiens", "Ottawa Senators"],
},
{
"cat":"Coming of Age",
"ques":"Who played Juno's stepmother in 2007's Juno?",
"answ":"ALLISON JANNEY",
"answ3":"ALISSON JANNEY",
"answ2":"Allison Janney.",
"option":["Allison Janney", "Jennifer Garner", "Emily Blunt", "Maggie Gyllenhaal"],
},
{
"cat":"Coming of Age",
"ques":"What color is John Milner's iconic 1932 Ford Coupe that he races in American Graffiti?",
"answ":"YELLOW",
"answ2":"Yellow.",
"option":["Yellow", "White", "Red", "Black"],
},
{
"cat":"Coming of Age",
"ques":"Who directed 2017's Call Me By Your Name?",
"answ":"LUCA GUADAGNINO",
"answ3":"LUCA GUADAGINO",
"answ2":"Luca Guadagnino.",
"option":["Luca Guadagnino", "Greg Berlanti", "Saoirse Ronan", "Barry Jenkins"],
},
{
"cat":"Coming of Age",
"ques":"In Love Simon, who plays Simon's father Jack?",
"answ":"JOSH DUHAMEL",
"answ2":"Josh Duhamel.",
"option":["Josh Duhamel", "Jason Bateman", "Timothy Olyphant", "Rainn Wilson"],
},
{
"cat":"Coming of Age",
"ques":"Who plays the adult version of Haley Joel Osment's character in Secondhand Lions?",
"answ":"JOSH LUCAS",
"answ2":"Josh Lucas.",
"option":["Josh Lucas", "Matthew McConaughey", "Luke Wilson", "Viggo Mortensen"],
},
{
"cat":"Coming of Age",
"ques":"Rob Reiner directed what 2010 movie about two 8th graders who start to have feelings for each other despite being total opposites?",
"answ":"FLIPPED",
"answ2":"Flipped.",
"option":["Flipped", "Palo Alto", "Submarine", "The Runaways"],
},
{
"cat":"Coming of Age",
"ques":"In Stand By Me, how does narrator Richard Dreyfuss say River Phoenix's character Chris died?",
"answ":"STABBED",
"answ3":"HE WAS STABBED",
"answ2":"Stabbed.",
"option":["Stabbed", "Pushed in front of a train", "Heart attack", "Choked on a pretzel"],
},
{
"cat":"Coming of Age",
"ques":"What coming of age movie is based on the life of Chazz Palminteri?",
"answ":"A BRONX TALE",
"answ3":"BRONX TALE",
"answ2":"A Bronx Tale.",
"option":["A Bronx Tale", "Mad Love", "October Sky", "That Night"],
},
{
"cat":"Coming of Age",
"ques":"Josh Hamilton plays father to Elsie Fisher in what coming of age film?",
"answ":"EIGHT GRADE",
"answ2":"Eight Grade.",
"option":["Eight Grade", "The Diary of a Teenage Girl", "The Miseducation of Cameron Poe", "Brooklyn"],
},
{
"cat":"Coming of Age",
"ques":"John and Joan Cusack star in what 1984 coming of age film?",
"answ":"SIXTEEN CANDLES",
"answ2":"Sixteen Candles.",
"option":["Sixteen Candles", "Pretty in Pink", "Footloose", "Say Anything"],
},
{
"cat":"Coming of Age",
"ques":"Who plays the difficult and wealthy boyfriend, Trent, of Duncan's mother in The Way, Way Back?",
"answ":"STEVE CARELL",
"answ2":"Steve Carell.",
"option":["Steve Carell", "Jason Clarke", "Casey Affleck", "Colin Farrell"],
},
{
"cat":"Coming of Age",
"ques":"Who stars as a charismatic teen genius named Chris Knight, in 1985's Real Genius?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
"option":["Val Kilmer", "Christian Slater", "Michael Biehn", "Brad Pitt"],
},
{
"cat":"Coming of Age",
"ques":"What school subject did Max Fischer say he 'saved' in Rushmore?",
"answ":"LATIN",
"answ2":"Latin.",
"option":["Latin", "Math", "Spanish", "English"],
},
{
"cat":"Coming of Age",
"ques":"Which actress plays the title character in the teen comedy I Love You, Beth Cooper?",
"answ":"HAYDEN PANETTIERE",
"answ3":"HAYDEN PANETIERE",
"answ2":"Hayden Panettiere.",
"option":["Hayden Panettiere", "Megan Fox", "Blake Lively", "Hilary Duff"],
},
{
"cat":"Coming of Age",
"ques":"Boyhood takes place in what U.S. State?",
"answ":"TEXAS",
"answ2":"Texas.",
"option":["Texas", "Florida", "South Carolina", "California"],
},
{
"cat":"Coming of Age",
"ques":"In the 1992 movie School Ties, Matt Damon's character cheats on a final exam on what subject near the end of the movie?",
"answ":"HISTORY",
"answ2":"History.",
"option":["History", "Chemistry", "French", "Calculus"],
},
{
"cat":"Coming of Age",
"ques":"What 2012 coming of age film stars Logan Lerman, Ezra Miller and Emma Watson?",
"answ":"THE PERKS OF BEING A WALLFLOWER",
"answ3":"PERKS OF BEING A WALLFLOWER",
"answ2":"The Perks of Being a Wallflower.",
"option":["The Perks of Being a Wallflower", "The Bling Ring", "Silver Linings Playbook", "Seeking a Friend for the End of the World"],
},
{
"cat":"Coming of Age",
"ques":"What 1983 Francis Ford Coppola film revolves around Oklahoma greasers played by young stars such as C. Thom Howell, Matt Dillon and Patrick Swayze?",
"answ":"THE OUTSIDERS",
"answ2":"The Outsiders.",
"option":["The Outsiders", "The Cotton Club", "Rumble Fish", "One from the Heart"],
},
{
"cat":"Coming of Age",
"ques":"Which actor played Simon in 2018's Love, Simon?",
"answ":"NICK ROBINSON",
"answ2":"Nick Robinson.",
"option":["Nick Robinson", "Ansel Elgort", "Taron Egerton", "Timothée Chalamet"],
},
];
comingofage = shuffle(comingofage);
r2Q15 = shuffle(r2Q15);