var disney = [
{
"cat":"Disney",
"ques":"What classic Disney animated film is known for the song 'Heigh Ho'?",
"answ":"SNOW WHITE AND THE SEVEN DWARFS",
"answ3":"SNOW WHITE",
"answ2":"Snow White and the Seven Dwarfs.",
},
{
"cat":"Disney",
"ques":"Which actress voiced the evil Mother Gothel in Tangled?",
"answ":"DONNA MURPHY",
"answ2":"Donna Murphy.",
},
{
"cat":"Disney",
"ques":"What 2000s animated film, was the second theatrically released installment in the Winnie the Pooh franchise?",
"answ":"THE TIGGER MOVIE",
"answ":"TIGGER MOVIE",
"answ2":"The Tigger Movie.",
},
{
"cat":"Disney",
"ques":"Glenn Close and Gérard Depardieu star in what 2000 live-action Disney sequel?",
"answ":"102 DALMATIANS",
"answ2":"102 Dalmatians.",
},
{
"cat":"Disney",
"ques":"Who stars as Cruella de Vil in the 2000 Disney film 102 Dalmatians?",
"answ":"GLENN CLOSE",
"answ2":"Glenn Close.",
},
{
"cat":"Disney",
"ques":"Who directed the films A Goofy Movie, Tarzan and 102 Dalmatians?",
"answ":"KEVIN LIMA",
"answ2":"Kevin Lima.",
},
{
"cat":"Disney",
"ques":"In Aladdin, what is the name of Jasmine's pet tiger?",
"answ":"RAJAH",
"answ3":"RAJA",
"answ2":"Rajah.",
},
{
"cat":"Disney",
"ques":"Donnie Yen and Jet Li appear in what 2020 live-action Disney film?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"Which actress stars as Maggie Peyton in 2005's Herbie Fully Loaded?",
"answ":"LINDSAY LOHAN",
"answ2":"Lindsay Lohan.",
},
{
"cat":"Disney",
"ques":"This Disney film features the line: 'Teenagers. They think they known everything. You give them an inch, they swim all over you.'?",
"answ":"THE LITTLE MERMAID",
"answ3":"LITTLE MERMAID",
"answ2":"The Little Mermaid.",
},
{
"cat":"Disney",
"ques":"In which 2018 Disney film will you find the hundred-acre woods and hear about creatures known as Heffalumps and Woozles?",
"answ":"CHRISTOPHER ROBIN",
"answ2":"Christopher Robin.",
},
{
"cat":"Disney",
"ques":"'Go the Distance' was nominated for Best Original Song for what 90s Disney film?",
"answ":"HERCULES",
"answ2":"Hercules.",
},
{
"cat":"Disney",
"ques":"What 1998 live-action Disney remake stars Lindsay Lohan, Dennis Quaid and Natasha Richardson?",
"answ":"THE PARENT TRAP",
"answ2":"The Parent Trap.",
},
{
"cat":"Disney",
"ques":"In The Many Adventures of Winne the Pooh, which character says: 'I'm so happy, I feel like bouncing.'?",
"answ":"TIGGER",
"answ2":"Tigger.",
},
{
"cat":"Disney",
"ques":"The song 'I'll Make a Man Out of You', is performed while young men are trained to be soldiers for war in what Disney film?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"What classic Disney film is a series of animated scenes set to famous classical music pieces, such as The Nutcracker Suite?",
"answ":"FANTASIA",
"answ2":"Fantasia.",
},
{
"cat":"Disney",
"ques":"This Academy Award winning actress played Lady Tremaine, the evil stepmother in Disney's live-action adaptation of Cinderella.",
"answ":"CATE BLANCHETT",
"answ3":"KATE BLANCHETT",
"answ2":"Cate Blanchett.",
},
{
"cat":"Disney",
"ques":"What Disney villain has blue flames for hair?",
"answ":"HADES",
"answ2":"Hades.",
},
{
"cat":"Disney",
"ques":"David Spade and John Goodman voice Kuzco and Pacha respectively in what Disney film?",
"answ":"THE EMPEROR'S NEW GROOVE",
"answ3":"EMPEROR'S NEW GROOVE",
"answ2":"The Emperor's New Groove.",
},
{
"cat":"Disney",
"ques":"Which SNL alum provides the voice of Kuzco in The Emperor's New Groove?",
"answ":"DAVID SPADE",
"answ2":"David Spade.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin who does Aladdin pretend to be to safe Jasmine from having her hand cut off by the merchant in the marketplace?",
"answ":"HER BROTHER",
"answ3":"BROTHER",
"answ2":"Her brother.",
},
{
"cat":"Disney",
"ques":"What Disney animated film series features two lead characters by the names of Bernard and Bianca?",
"answ":"THE RESCUERS",
"answ3":"RESCUERS",
"answ2":"The Rescuers.",
},
{
"cat":"Disney",
"ques":"What 2016 Disney remake stars Robert Redford and Bryce Dallas Howard?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
},
{
"cat":"Disney",
"ques":"What 1954 Disney film features Captain Nemo, and his ship, the Nautilus?",
"answ":"20000 LEAGUES UNDER THE SEA",
"answ3":"20 000 LEAGUES UNDER THE SEA",
"answ2":"20,000 Leagues Under the Sea.",
},
{
"cat":"Disney",
"ques":"In 1994's The Lion King, who voices adult Simba?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
},
{
"cat":"Disney",
"ques":"What Disney animated movie features the Billy Joel song 'Why Should I Worry'?",
"answ":"OLIVER AND COMPANY",
"answ2":"Oliver & Company.",
},
{
"cat":"Disney",
"ques":"Prince Philip is the prince from what Disney animated classic?",
"answ":"SLEEPING BEAUTY",
"answ2":"Sleeping Beauty.",
},
{
"cat":"Disney",
"ques":"What country does the Disney classic Beauty and the Beast take place in?",
"answ":"FRANCE",
"answ2":"France.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, what kind of animals are Ursula's pets?",
"answ":"EELS",
"answ3":"MORAY EELS",
"answ2":"Eels.",
},
{
"cat":"Disney",
"ques":"You'll find a demon-like villain named The Horned King in what Disney animated film?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"What was the name of the sequel to Disney's The Rescuers?",
"answ":"THE RESCUERS DOWN UNDER",
"answ3":"RESCUERS DOWN UNDER",
"answ2":"The Rescuers Down Under.",
},
{
"cat":"Disney",
"ques":"The world 'parley' is used in order to stop a fight and talk things out in what Disney adventure?",
"answ":"PIRATES OF THE CARIBBEAN",
"answ3":"PIRATES OF THE CARIBBEAN THE CURSE OF THE BLACK PEARL",
"answ2":"Pirates of the Caribbean: The Curse of the Black Pearl.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, for how many years does the Genie tell Aladdin he's been trapped in the lamp?",
"answ":"10 000",
"answ3":"10000",
"answ2":"10,000.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, what is the name of the flying carpet?",
"answ":"CARPET",
"answ2":"Carpet.",
},
{
"cat":"Disney",
"ques":"Who plays the singing prince in the live-action animation hybrid Enchanted?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
},
{
"cat":"Disney",
"ques":"Who voiced Scar in 1994's The Lion King?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
},
{
"cat":"Disney",
"ques":"In Disney's Robin Hood, what type of animal is Robin Hood?",
"answ":"FOX",
"answ2":"Fox.",
},
{
"cat":"Disney",
"ques":"Captain Hook has his hook on his ____ hand.",
"answ":"LEFT",
"answ3":"LEFT HAND",
"answ2":"His left hand.",
},
{
"cat":"Disney",
"ques":"Who voices the parrot Iago in 1992's Aladdin?",
"answ":"GILBERT GOTTFRIED",
"answ2":"Gilbert Gottfried.",
},
{
"cat":"Disney",
"ques":"What is the name of the walking talking clock in Disney's Beauty and the Beast?",
"answ":"COGSWORTH",
"answ2":"Cogsworth.",
},
{
"cat":"Disney",
"ques":"Tiana is the name of the lead character in what Disney film?",
"answ":"THE PRINCESS AND THE FROG",
"answ3":"PRINCESS AND THE FROG",
"answ2":"The Princess and the Frog.",
},
{
"cat":"Disney",
"ques":"Judge Frollo is the villain of which Disney film?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"Meeko and Flit are the names of two characters in what Disney film?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Disney",
"ques":"Which Disney film features a pig herder named Taran who must go on a quest to stop the evil Horned King?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"Who voices Esmeralda in Disney's The Hunchback of Notre Dame?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
},
{
"cat":"Disney",
"ques":"Mandy Moore and Zachary Levi provide voices in which Disney film?",
"answ":"TANGLED",
"answ2":"Tangled.",
},
{
"cat":"Disney",
"ques":"Herbie Rides Again was the sequel to what Disney classic?",
"answ":"THE LOVE BUG",
"answ2":"The Love Bug.",
},
{
"cat":"Disney",
"ques":"Mackenzie Foy plays the lead Clara Stahlbaum in what 2010s Disney live action film?",
"answ":"THE NUTCRACKER AND THE FOUR REALMS",
"answ3":"NUTCRACKER AND THE FOUR REALMS",
"answ2":"The Nutcracker and the Four Realms.",
},
];
var r2Q17 = [
{
"cat":"Disney",
"ques":"What Disney character has a best friend named Timothy Q. Mouse?",
"answ":"DUMBO",
"answ2":"Dumbo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pinocchio</button><button id=incop2 class=buttons003 onclick=qinc()>Merlin</button><button id=corop class=buttons003 onclick=qcor()>Dumbo</button><button id=incop4 class=buttons003 onclick=qinc()>Quasimodo</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the octopus-like villain in The Little Mermaid?",
"answ":"URSULA",
"answ2":"Ursula.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Angela</button><button id=incop2 class=buttons003 onclick=qinc()>Katherine</button><button id=corop class=buttons003 onclick=qcor()>Ursula</button><button id=incop4 class=buttons003 onclick=qinc()>Maleficent</button><br/>",
},
{
"cat":"Disney",
"ques":"In The Rescuers, what precious object is the Devil's Eye?",
"answ":"DIAMOND",
"answ2":"Diamond.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emerald</button><button id=incop2 class=buttons003 onclick=qinc()>Sapphire</button><button id=incop3 class=buttons003 onclick=qinc()>Ruby</button><button id=corop class=buttons003 onclick=qcor()>Diamond</button><br/>",
},
{
"cat":"Disney",
"ques":"What was the first full-length Disney movie to star Goofy as the title character?",
"answ":"A GOOFY MOVIE",
"answ3":"GOOFY MOVIE",
"answ2":"A Goofy Movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Goofy's Adventure</button><button id=incop2 class=buttons003 onclick=qinc()>Goofy The Movie</button><button id=incop3 class=buttons003 onclick=qinc()>The Adventures of Goofy</button><button id=corop class=buttons003 onclick=qcor()>A Goofy Movie</button><br/>",
},
{
"cat":"Disney",
"ques":"What actor is the voice of the satyr Phil in Hercules?",
"answ":"DANNY DEVITO",
"answ2":"Danny DeVito.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Adam Sandler</button><button id=corop class=buttons003 onclick=qcor()>Danny DeVito</button><button id=incop3 class=buttons003 onclick=qinc()>Eddie Murphy</button><button id=incop4 class=buttons003 onclick=qinc()>Samuel E. Wright</button><br/>",
},
{
"cat":"Disney",
"ques":"The character Thomas O'Malley is from what Disney animated classic?",
"answ":"THE ARISTOCATS",
"answ3":"ARISTOCATS",
"answ2":"The Aristocats.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Great Mouse Detective</button><button id=corop class=buttons003 onclick=qcor()>The Aristocats</button><button id=incop3 class=buttons003 onclick=qinc()>The Rescuers</button><button id=incop4 class=buttons003 onclick=qinc()>Oliver & Company</button><br/>",
},
{
"cat":"Disney",
"ques":"Who provided the voice of the villainous Hades in Disney's Hercules?",
"answ":"JAMES WOODS",
"answ2":"James Woods.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Martin Short</button><button id=corop class=buttons003 onclick=qcor()>James Woods</button><button id=incop3 class=buttons003 onclick=qinc()>Hugh Laurie</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Walken</button><br/>",
},
{
"cat":"Disney",
"ques":"Who plays the baseball agent who journeys to India to look for untapped baseball talent in Million Dollar Arm?",
"answ":"JON HAMM",
"answ2":"Jon Hamm.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jon Hamm</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=incop3 class=buttons003 onclick=qinc()>Aaron Eckhart</button><button id=incop4 class=buttons003 onclick=qinc()>Ryan Gosling</button><br/>",
},
{
"cat":"Disney",
"ques":"What kind of object was Dumbo told that it was magic and if he held it in his trunk he would be able to fly?",
"answ":"FEATHER",
"answ3":"A FEATHER",
"answ2":"Feather.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Branch</button><button id=incop2 class=buttons003 onclick=qinc()>Flower</button><button id=incop3 class=buttons003 onclick=qinc()>String</button><button id=corop class=buttons003 onclick=qcor()>Feather</button><br/>",
},
{
"cat":"Disney",
"ques":"Who plays D'Artagnan in 1993's The Three Musketeers?",
"answ":"CHRIS O'DONNELL",
"answ2":"Chris O'Donnell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charlie Sheen</button><button id=incop2 class=buttons003 onclick=qinc()>Oliver Platt</button><button id=corop class=buttons003 onclick=qcor()>Chris O'Donnell</button><button id=incop4 class=buttons003 onclick=qinc()>Kiefer Sutherland</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the youngest of the three Darling children in 1953's Peter Pan?",
"answ":"MICHAEL",
"answ2":"Michael.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charlie</button><button id=incop2 class=buttons003 onclick=qinc()>Oliver</button><button id=corop class=buttons003 onclick=qcor()>Michael</button><button id=incop4 class=buttons003 onclick=qinc()>Alfred</button><br/>",
},
{
"cat":"Disney",
"ques":"In 1950's Cinderella, one of the two mice is called Jaq. What is the other one called?",
"answ":"GUS",
"answ2":"Gus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joe</button><button id=incop2 class=buttons003 onclick=qinc()>Fred</button><button id=corop class=buttons003 onclick=qcor()>Gus</button><button id=incop4 class=buttons003 onclick=qinc()>Syl</button><br/>",
},
{
"cat":"Disney",
"ques":"What Disney film features the vultures Trigger and Nutsy?",
"answ":"ROBIN HOOD",
"answ2":"Robin Hood.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Robin Hood</button><button id=incop2 class=buttons003 onclick=qinc()>The Sword in the Stone</button><button id=incop3 class=buttons003 onclick=qinc()>The Black Cauldron</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella</button><br/>",
},
{
"cat":"Disney",
"ques":"What was Disney's first live-action science-fiction film?",
"answ":"20000 LEAGUES UNDER THE SEA",
"answ3":"20 000 LEAGUES UNDER THE SEA",
"answ2":"20,000 Leagues Under the Sea.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Black Hole</button><button id=incop2 class=buttons003 onclick=qinc()>Tron</button><button id=corop class=buttons003 onclick=qcor()>20,000 Leagues Under the Sea</button><button id=incop4 class=buttons003 onclick=qinc()>Moon Pilot</button><br/>",
},
{
"cat":"Disney",
"ques":"Who voiced Fear in 2015's Inside Out?",
"answ":"BILL HADER",
"answ2":"Bill Hader.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Justin Long</button><button id=incop2 class=buttons003 onclick=qinc()>Kyle MacLachlan</button><button id=incop3 class=buttons003 onclick=qinc()>Jesse Eisenberg</button><button id=corop class=buttons003 onclick=qcor()>Bill Hader</button><br/>",
},
{
"cat":"Disney",
"ques":"In Mary Poppins, what animal that also spoke was on the end of Mary Poppins' umbrella?",
"answ":"PARROT",
"answ3":"BIRD",
"answ2":"Parrot.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sheep</button><button id=incop2 class=buttons003 onclick=qinc()>Lion</button><button id=incop3 class=buttons003 onclick=qinc()>Dog</button><button id=corop class=buttons003 onclick=qcor()>Parrot</button><br/>",
},
{
"cat":"Disney",
"ques":"In what animated feature would you find a villain named Sykes?",
"answ":"OLIVER AND COMPANY",
"answ2":"Oliver & Company.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Home on the Range</button><button id=corop class=buttons003 onclick=qcor()>Oliver & Company</button><button id=incop3 class=buttons003 onclick=qinc()>Atlantis The Lost Empire</button><button id=incop4 class=buttons003 onclick=qinc()>Tarzan</button><br/>",
},
{
"cat":"Disney",
"ques":"What Firefly and Serenity star has provided their voice to Wreck-It Ralph, Frozen, Big Hero 6 and Zootopia?",
"answ":"ALAN TUDYK",
"answ3":"ALAN TUDIK",
"answ2":"Alan Tudyk.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nathan Fillion</button><button id=corop class=buttons003 onclick=qcor()>Alan Tudyk</button><button id=incop3 class=buttons003 onclick=qinc()>Gina Torres</button><button id=incop4 class=buttons003 onclick=qinc()>Adam Baldwin</button><br/>",
},
{
"cat":"Disney",
"ques":"In Disney's Bolt, who voiced the titular character?",
"answ":"JOHN TRAVOLTA",
"answ2":"John Travolta.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nicolas Cage</button><button id=corop class=buttons003 onclick=qcor()>John Travolta</button><button id=incop3 class=buttons003 onclick=qinc()>Ed Harris</button><button id=incop4 class=buttons003 onclick=qinc()>Alec Baldwin</button><br/>",
},
{
"cat":"Disney",
"ques":"In 1994's The Lion King, what is the name of the place that Simba is forbidden to go to?",
"answ":"THE ELEPHANT GRAVEYARD",
"answ3":"ELEPHANT GRAVEYARD",
"answ2":"The Elephant Graveyard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pride Rock</button><button id=incop2 class=buttons003 onclick=qinc()>The Oasis</button><button id=incop3 class=buttons003 onclick=qinc()>The Water Hole</button><button id=corop class=buttons003 onclick=qcor()>The Elephant Graveyard</button><br/>",
},
{
"cat":"Disney",
"ques":"You'll find the characters of Copper and Tod in this Disney animated film?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bambi</button><button id=incop2 class=buttons003 onclick=qinc()>Lady and the Tramp</button><button id=incop3 class=buttons003 onclick=qinc()>The Aristocats</button><button id=corop class=buttons003 onclick=qcor()>The Fox and the Hound</button><br/>",
},
{
"cat":"Disney",
"ques":"In Dinosaur, what is the name of the young Iguanodon who is adopted and raised by a family of lemurs?",
"answ":"ALADAR",
"answ2":"Aladar.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Plio</button><button id=incop2 class=buttons003 onclick=qinc()>ittlefoot</button><button id=incop3 class=buttons003 onclick=qinc()>Suri</button><button id=corop class=buttons003 onclick=qcor()>Aladar</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the prince's name in The Little Mermaid?",
"answ":"ERIC",
"answ3":"ERIK",
"answ2":"Eric.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charming</button><button id=incop2 class=buttons003 onclick=qinc()>Jonathan</button><button id=incop3 class=buttons003 onclick=qinc()>Philip</button><button id=corop class=buttons003 onclick=qcor()>Eric</button><br/>",
},
{
"cat":"Disney",
"ques":"Which 1970s Disney film is set at the Maine village of Passamaquoddy?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bedknobs and Broomsticks</button><button id=incop2 class=buttons003 onclick=qinc()>Candleshoe</button><button id=incop3 class=buttons003 onclick=qinc()>Pocahontas</button><button id=corop class=buttons003 onclick=qcor()>Pete's Dragon</button><br/>",
},
{
"cat":"Disney",
"ques":"In Aladdin, Jafar uses a golden what, to locate the cave that hides the magic lamp?",
"answ":"SCARAB",
"answ3":"GOLDEN SCARAB",
"answ2":"Scarab.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dagger</button><button id=incop2 class=buttons003 onclick=qinc()>Compass</button><button id=corop class=buttons003 onclick=qcor()>Scarab</button><button id=incop4 class=buttons003 onclick=qinc()>Arrow</button><br/>",
},
{
"cat":"Disney",
"ques":"Finish the quote from Frozen: 'Winter is a good time to stay in and cuddle, put me in Summer and I'll be a ____'",
"answ":"HAPPY SNOWMAN",
"answ3":"A HAPPY SNOWMAN",
"answ2":"Happy Snowman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sad Snowman</button><button id=incop2 class=buttons003 onclick=qinc()>Puddle</button><button id=corop class=buttons003 onclick=qcor()>Happy Snowman</button><button id=incop4 class=buttons003 onclick=qinc()>Melting Snowman</button><br/>",
},
{
"cat":"Disney",
"ques":"Who voices adventurer Jim Hawkins in 2002's Treasure Planet?",
"answ":"JOSEPH GORDON LEVITT",
"answ3":"JOSEPH GORDON LEVIT",
"answ2":"Joseph Gordon-Levitt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=incop2 class=buttons003 onclick=qinc()>Jonathan Taylor Thomas</button><button id=corop class=buttons003 onclick=qcor()>Joseph Gordon-Levitt</button><button id=incop4 class=buttons003 onclick=qinc()>Frankie Muniz</button><br/>",
},
{
"cat":"Disney",
"ques":"The term 'Twitterpated' is the word that described falling in love in what Disney animated classic?",
"answ":"BAMBI",
"answ2":"Bambi.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pocanhontas</button><button id=incop2 class=buttons003 onclick=qinc()>Dumbo</button><button id=corop class=buttons003 onclick=qcor()>Bambi</button><button id=incop4 class=buttons003 onclick=qinc()>The Fox and the Hound</button><br/>",
},
{
"cat":"Disney",
"ques":"According to a song from the film, which Disney character went from 'zero to hero'?",
"answ":"HERCULES",
"answ2":"Hercules.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pinocchio</button><button id=incop2 class=buttons003 onclick=qinc()>Dumbo</button><button id=corop class=buttons003 onclick=qcor()>Hercules</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella</button><br/>",
},
{
"cat":"Disney",
"ques":"What classic Disney character baked a gooseberry pie while singing 'Someday my prince will come'?",
"answ":"SNOWWHITE",
"answ3":"SNOW WHITE",
"answ2":"Snow White.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Belle</button><button id=incop2 class=buttons003 onclick=qinc()>Sleeping Beauty</button><button id=corop class=buttons003 onclick=qcor()>Snow White</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella</button><br/>",
},
{
"cat":"Disney",
"ques":"How many Disney films were made about a hockey team called The Mighty Ducks?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"Disney",
"ques":"What do Aladdin and his monkey steal from the marketplace when you're first introduced to them in 1992's Aladdin?",
"answ":"BREAD",
"answ3":"A BREAD",
"answ2":"Bread.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Apple</button><button id=incop2 class=buttons003 onclick=qinc()>Money</button><button id=corop class=buttons003 onclick=qcor()>Bread</button><button id=incop4 class=buttons003 onclick=qinc()>Fish</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the main villain in Disney's Mulan?",
"answ":"SHAN YU",
"answ2":"Shan Yu.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fa Zhou</button><button id=incop2 class=buttons003 onclick=qinc()>Shang</button><button id=incop3 class=buttons003 onclick=qinc()>Yao</button><button id=corop class=buttons003 onclick=qcor()>Shan Yu</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the Disney character known as 'the great mouse detective'?",
"answ":"BASIL",
"answ2":"Basil.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sherwin</button><button id=incop2 class=buttons003 onclick=qinc()>Dr. Dawson</button><button id=corop class=buttons003 onclick=qcor()>Basil</button><button id=incop4 class=buttons003 onclick=qinc()>Ratcliffe</button><br/>",
},
{
"cat":"Disney",
"ques":"Adriana Caselotti was 18 years old when she was asked to voice what famous Disney character?",
"answ":"SNOW WHITE",
"answ3":"SNOWWHITE",
"answ2":"Snow White.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sleeping Beauty</button><button id=incop2 class=buttons003 onclick=qinc()>Ariel</button><button id=corop class=buttons003 onclick=qcor()>Snow White</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella</button><br/>",
},
{
"cat":"Disney",
"ques":"In what 90s Disney animated film do you hear Disney tunes such as 'Stand Out', 'After Today' and 'I2I (Eye-2-Eye)'?",
"answ":"A GOOFY MOVIE",
"answ3":"GOOFY MOVIE",
"answ2":"A Goofy Movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Hunchback of Notre Dame</button><button id=incop2 class=buttons003 onclick=qinc()>The Rescuers Down Under</button><button id=corop class=buttons003 onclick=qcor()>A Goofy Movie</button><button id=incop4 class=buttons003 onclick=qinc()>Pocahontas</button><br/>",
},
{
"cat":"Disney",
"ques":"Who voices Jane Porter in 1999's Tarzan?",
"answ":"MINNIE DRIVER",
"answ2":"Minnie Driver.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Reese Witherspoon</button><button id=incop2 class=buttons003 onclick=qinc()>Sally Field</button><button id=corop class=buttons003 onclick=qcor()>Minnie Driver</button><button id=incop4 class=buttons003 onclick=qinc()>Joan Cusack</button><br/>",
},
{
"cat":"Disney",
"ques":"The Court of Miracles is the name of a secret hideout in what Disney animated film?",
"answ":"THE HUNCHBACK OF NOTRE DAM",
"answ3":"HUNCHBACK OF NOTRE DAM",
"answ2":"The Hunchback of Notre Dame.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pocahontas</button><button id=incop2 class=buttons003 onclick=qinc()>The Black Cauldron</button><button id=corop class=buttons003 onclick=qcor()>The Hunchback of Notre Dame</button><button id=incop4 class=buttons003 onclick=qinc()>The Sword in the Stone</button><br/>",
},
{
"cat":"Disney",
"ques":"The 'Unbirthday Song' can be found in what Disney film?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Peter Pan</button><button id=incop2 class=buttons003 onclick=qinc()>The Jungle Book</button><button id=corop class=buttons003 onclick=qcor()>Alice in Wonderland</button><button id=incop4 class=buttons003 onclick=qinc()>A Goofy Movie</button><br/>",
},
{
"cat":"Disney",
"ques":"Other than 'Mowgli', what do many of the characters in 1967's Disney's Jungle Book refer to him as?",
"answ":"MAN CUB",
"answ2":"Man Cub.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Baby Cub</button><button id=incop2 class=buttons003 onclick=qinc()>Man Child</button><button id=corop class=buttons003 onclick=qcor()>Man Cub</button><button id=incop4 class=buttons003 onclick=qinc()>Little One</button><br/>",
},
{
"cat":"Disney",
"ques":"Over what activity does Mr. Banks finally bond with his children in Mary Poppins?",
"answ":"FLYING A KITE",
"answ3":"KITE FLYING",
"answ2":"Flying a kite.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soccer</button><button id=incop2 class=buttons003 onclick=qinc()>Baseball</button><button id=corop class=buttons003 onclick=qcor()>Flying a kite</button><button id=incop4 class=buttons003 onclick=qinc()>Playing chess</button><br/>",
},
{
"cat":"Disney",
"ques":"This musical tribute to the world of Uncle Remus co-starred Oscar-winner Hattie McDaniel in what controversial Disney film?",
"answ":"SONG OF THE SOUTH",
"answ2":"Song of the South.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Melody Time</button><button id=incop2 class=buttons003 onclick=qinc()>The Reluctant Dragon</button><button id=corop class=buttons003 onclick=qcor()>Song of the South</button><button id=incop4 class=buttons003 onclick=qinc()>The Vanishing Prairie</button><br/>",
},
{
"cat":"Disney",
"ques":"You'll find the main characters by the name of Meg and Phil in what Disney animated film?",
"answ":"HERCULES",
"answ2":"Hercules.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hercules</button><button id=incop2 class=buttons003 onclick=qinc()>Big Hero 6</button><button id=incop3 class=buttons003 onclick=qinc()>The Hunchback of Notre Dame</button><button id=incop4 class=buttons003 onclick=qinc()>Wreck-It Ralph</button><br/>",
},
{
"cat":"Disney",
"ques":"Who stars as a busy realtor whose family is invited to a mysterious manor in 2003's Haunted Mansion?",
"answ":"EDDIE MURPHY",
"answ2":"Eddie Murphy.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Eddie Murphy</button><button id=incop2 class=buttons003 onclick=qinc()>Jack Black</button><button id=incop3 class=buttons003 onclick=qinc()>Brendan Fraser</button><button id=incop4 class=buttons003 onclick=qinc()>Robin Williams</button><br/>",
},
{
"cat":"Disney",
"ques":"What classic Disney movie stars Fred MacMurray, introduced a substance called 'Flubber' and features a flying Model T?",
"answ":"THE ABSENT MINDED PROFESSOR",
"answ3":"ABSENT MINDED PROFESSOR",
"answ2":"The Absent-Minded Professor.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Absent-Minded Professor</button><button id=incop2 class=buttons003 onclick=qinc()>Big Red</button><button id=incop3 class=buttons003 onclick=qinc()>The Barefoot Executive</button><button id=incop4 class=buttons003 onclick=qinc()>Gus</button><br/>",
},
{
"cat":"Disney",
"ques":"In Tangled, what symbol decorates the lanterns released by Rapunzel's parents?",
"answ":"SUN",
"answ3":"A SUN",
"answ2":"A sun.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>An angel</button><button id=incop2 class=buttons003 onclick=qinc()>A flower</button><button id=corop class=buttons003 onclick=qcor()>A sun</button><button id=incop4 class=buttons003 onclick=qinc()>A moon</button><br/>",
},
{
"cat":"Disney",
"ques":"Who voices social worker Cobra Bubbles in Lilo and Stitch?",
"answ":"VING RHAMES",
"answ2":"Ving Rhames.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Clarke Duncan</button><button id=corop class=buttons003 onclick=qcor()>Ving Rhames</button><button id=incop3 class=buttons003 onclick=qinc()>Tommy Lister</button><button id=incop4 class=buttons003 onclick=qinc()>Billy Dee Williams</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the evil marionette master who kidnaps Pinocchio to star in his shows?",
"answ":"STROMBOLI",
"answ2":"Stromboli.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gideon</button><button id=incop2 class=buttons003 onclick=qinc()>Figaro</button><button id=incop3 class=buttons003 onclick=qinc()>Lampwick</button><button id=corop class=buttons003 onclick=qcor()>Stromboli</button><br/>",
},
{
"cat":"Disney",
"ques":"In The Emperor's New Groove, Yzma's bumbling right-hand man, Kronk, gets information about Kuzco's whereabouts by talking to what woodland creature?",
"answ":"SQUIRREL",
"answ3":"SQUIREL",
"answ2":"Squirrel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chipmunk</button><button id=incop2 class=buttons003 onclick=qinc()>Rabbit</button><button id=incop3 class=buttons003 onclick=qinc()>Weasel</button><button id=corop class=buttons003 onclick=qcor()>Squirrel</button><br/>",
},
{
"cat":"Disney",
"ques":"Who was the lead and played both characters Susan Evers/Sharon McKendrick in 1961's Parent Trap?",
"answ":"HAYLEY MILLS",
"answ3":"HAILEE MILLS",
"answ2":"Hayley Mills.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nancy Kwan</button><button id=incop2 class=buttons003 onclick=qinc()>Ina Balin</button><button id=incop3 class=buttons003 onclick=qinc()>Jane Fonda</button><button id=corop class=buttons003 onclick=qcor()>Hayley Mills</button><br/>",
},
{
"cat":"Disney",
"ques":"In the Pirates of the Caribbean franchise, before joining a life of piracy, Will Turner was an apprentice in what profession?",
"answ":"BLACKSMITH",
"answ3":"SMITH",
"answ2":"Blacksmith.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Butcher</button><button id=incop2 class=buttons003 onclick=qinc()>Baker</button><button id=incop3 class=buttons003 onclick=qinc()>Carpenter</button><button id=corop class=buttons003 onclick=qcor()>Blacksmith</button><br/>",
},
{
"cat":"Disney",
"ques":"In Big Hero 6, what comedic actor provides the voice for uber comic book fan and professional slacker, Fred?",
"answ":"TJ MILLER",
"answ3":"T J MILLER",
"answ2":"T.J. Miller.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Franco</button><button id=incop2 class=buttons003 onclick=qinc()>Seth Rogen</button><button id=incop3 class=buttons003 onclick=qinc()>Jason Segel</button><button id=corop class=buttons003 onclick=qcor()>T.J. Miller</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of Goofy's son in A Goofy Movie?",
"answ":"MAX",
"answ2":"Max.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>PJ</button><button id=corop class=buttons003 onclick=qcor()>Max</button><button id=incop3 class=buttons003 onclick=qinc()>Bobby</button><button id=incop4 class=buttons003 onclick=qinc()>Wally</button><br/>",
},
{
"cat":"Disney",
"ques":"In Mary Poppins Returns, who plays Wilkins and also voices Wolf?",
"answ":"COLIN FIRTH",
"answ3":"COLLIN FIRTH",
"answ2":"Colin Firth.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Colin Firth</button><button id=incop2 class=buttons003 onclick=qinc()>Lin Manuel-Miranda</button><button id=incop3 class=buttons003 onclick=qinc()>David Warner</button><button id=incop4 class=buttons003 onclick=qinc()>Jim Norton</button><br/>",
},
{
"cat":"Disney",
"ques":"Which Disney princess comes from Andalasia?",
"answ":"GISELLE",
"answ3":"PRINCESS GISELLE",
"answ2":"Giselle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rapunzel</button><button id=incop2 class=buttons003 onclick=qinc()>Aurora</button><button id=incop3 class=buttons003 onclick=qinc()>Belle</button><button id=corop class=buttons003 onclick=qcor()>Giselle</button><br/>",
},
{
"cat":"Disney",
"ques":"What Disney animated film features the song Following The Leader?",
"answ":"PETER PAN",
"answ2":"Peter Pan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Beauty & the Beast</button><button id=incop2 class=buttons003 onclick=qinc()>Pocahontas</button><button id=incop3 class=buttons003 onclick=qinc()>Mulan</button><button id=corop class=buttons003 onclick=qcor()>Peter Pan</button><br/>",
},
{
"cat":"Disney",
"ques":"What 90s film was Disney's live-action remake of one of its earlier animated feature films and starred Cary Elwes, Lena Headey and Sam Neill?",
"answ":"RUDYARD KIPLING'S THE JUNGLE BOOK",
"answ3":"THE JUNGLE BOOK",
"answ2":"Rudyard Kipling's The Jungle Book.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alice in Wonderland</button><button id=corop class=buttons003 onclick=qcor()>Rudyard Kipling's The Jungle Book</button><button id=incop3 class=buttons003 onclick=qinc()>101 Dalmatians</button><button id=incop4 class=buttons003 onclick=qinc()>The Sorcerer's Apprentice</button><br/>",
},
{
"cat":"Disney",
"ques":"Which animated film includes the song The Best of Friends?",
"answ":"FOX AND THE HOUND",
"answ3":"THE FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Fox and the Hound</button><button id=incop2 class=buttons003 onclick=qinc()>Oliver and Company</button><button id=incop3 class=buttons003 onclick=qinc()>Tarzan</button><button id=incop4 class=buttons003 onclick=qinc()>Lilo & Stitch</button><br/>",
},
{
"cat":"Disney",
"ques":"In Lilo & Stitch, what is the word that means family?",
"answ":"OHANA",
"answ2":"Ohana.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ohana</button><button id=incop2 class=buttons003 onclick=qinc()>Aloha</button><button id=incop3 class=buttons003 onclick=qinc()>Mahalo</button><button id=incop4 class=buttons003 onclick=qinc()>Kahuna</button><br/>",
},
{
"cat":"Disney",
"ques":"In 101 Dalmatians, dog owners Roger and Anita reside in what city?",
"answ":"LONDON",
"answ2":"London.",
"option":"<button id=corop class=buttons003 onclick=qcor()>London</button><button id=incop2 class=buttons003 onclick=qinc()>Paris</button><button id=incop3 class=buttons003 onclick=qinc()>New York City</button><button id=incop4 class=buttons003 onclick=qinc()>Dublin</button><br/>",
},
{
"cat":"Disney",
"ques":"What was the name of the villain in the 1985 animated film The Black Cauldron?",
"answ":"HORNED KING",
"answ2":"Horned King.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Horned King</button><button id=incop2 class=buttons003 onclick=qinc()>Black King</button><button id=incop3 class=buttons003 onclick=qinc()>Cursed King</button><button id=incop4 class=buttons003 onclick=qinc()>Evil King</button><br/>",
},
{
"cat":"Disney",
"ques":"Who provides the speaking voice for Captain Li Shang in Disney's Mulan?",
"answ":"BD WONG",
"answ2":"BD Wong.",
"option":"<button id=corop class=buttons003 onclick=qcor()>BD Wong</button><button id=incop2 class=buttons003 onclick=qinc()>Ken Watanabe</button><button id=incop3 class=buttons003 onclick=qinc()>Jerry Tondo</button><button id=incop4 class=buttons003 onclick=qinc()>Harvey Fierstein</button><br/>",
},
{
"cat":"Disney",
"ques":"Edgar is the name of the villainous butler in what Disney animated film?",
"answ":"THE ARISTOCATS",
"answ3":"ARISTOCATS",
"answ2":"The Aristocats.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Aristocats</button><button id=incop2 class=buttons003 onclick=qinc()>The Fox and the Hound</button><button id=incop3 class=buttons003 onclick=qinc()>Oliver & Company</button><button id=incop4 class=buttons003 onclick=qinc()>Lady and the Tramp</button><br/>",
},
{
"cat":"Disney",
"ques":"What is the name of the speaking tree that serves as Pocanhontas' guide in the film Pocahontas?",
"answ":"GRANDMOTHER WILLOW",
"answ2":"Grandmother Willow.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Grandmother Willow</button><button id=incop2 class=buttons003 onclick=qinc()>Mother Tree</button><button id=incop3 class=buttons003 onclick=qinc()>Powhatan Willow</button><button id=incop4 class=buttons003 onclick=qinc()>Nakoma Tree</button><br/>",
},
{
"cat":"Disney",
"ques":"What 1980s Disney animated film stars the voice talents of Kurt Russell and Mickey Rooney?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Rescuers</button><button id=incop2 class=buttons003 onclick=qinc()>Oliver & Company</button><button id=incop3 class=buttons003 onclick=qinc()>The Great Mouse Detective</button><button id=corop class=buttons003 onclick=qcor()>The Fox and the Hound</button><br/>",
},
{
"cat":"Disney",
"ques":"Dwayne Johnson's character has what profession, which propels him into an adventure, in the Disney film Race to Witch Mountain?",
"answ":"TAXI DRIVER",
"answ3":"CAB DRIVER",
"answ2":"Taxi driver.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Firefighter</button><button id=incop2 class=buttons003 onclick=qinc()>Construction worker</button><button id=incop3 class=buttons003 onclick=qinc()>Pilot</button><button id=corop class=buttons003 onclick=qcor()>Taxi driver</button><br/>",
},
{
"cat":"Disney",
"ques":"Who plays real life composer Richard Sherman in 2013's Saving Mr. Banks?",
"answ":"JASON SCHWARTZMAN",
"answ2":"Jason Schwartzman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>B.J. Novak</button><button id=incop2 class=buttons003 onclick=qinc()>Colin Farrell</button><button id=incop3 class=buttons003 onclick=qinc()>Bradley Whitford</button><button id=corop class=buttons003 onclick=qcor()>Jason Schwartzman</button><br/>",
},
{
"cat":"Disney",
"ques":"In Tangled, after being denied permission to leaver her tower, what does Rapunzel ask her mother to get her for her 18th birthday?",
"answ":"PAINT",
"answ2":"Paint.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hairbrush</button><button id=corop class=buttons003 onclick=qcor()>Paint</button><button id=incop3 class=buttons003 onclick=qinc()>Gold Thread</button><button id=incop4 class=buttons003 onclick=qinc()>Lantern</button><br/>",
},
{
"cat":"Disney",
"ques":"Who plays the lead role of Christopher Robin in 2018's Christopher Robin?",
"answ":"EWAN MCGREGOR",
"answ2":"Ewan McGregor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugh Grant</button><button id=corop class=buttons003 onclick=qcor()>Ewan McGregor</button><button id=incop3 class=buttons003 onclick=qinc()>Colin Firth</button><button id=incop4 class=buttons003 onclick=qinc()>Colin Farrell</button><br/>",
},
{
"cat":"Disney",
"ques":"In 1955's Lady and the Tramp, what is the name of the restaurant where they eat the spaghetti?",
"answ":"TONY'S",
"answ2":"Tony's.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Belle Noche</button><button id=incop2 class=buttons003 onclick=qinc()>Vicuzzis's</button><button id=incop3 class=buttons003 onclick=qinc()>Alfredo's</button><button id=corop class=buttons003 onclick=qcor()>Tony's</button><br/>",
},
{
"cat":"Disney",
"ques":"In Zootopia, what is the name of the shrew who is the most feared mob boss in Tundratown?",
"answ":"MR BIG",
"answ3":"MISTER BIG",
"answ2":"Mr. Big.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tony Shrewmoni</button><button id=incop2 class=buttons003 onclick=qinc()>Mr. Shrewlington</button><button id=incop3 class=buttons003 onclick=qinc()>Don Shrewleone</button><button id=corop class=buttons003 onclick=qcor()>Mr. Big</button><br/>",
},
];
disney = shuffle(disney);
r2Q17 = shuffle(r2Q17);