var disney = [
{
"cat":"Disney",
"ques":"In Disney's Pinocchio, what was the name of the place that all of the boys were taken to for vacation?",
"answ":"PLEASURE ISLAND",
"answ2":"Pleasure Island.",
},
{
"cat":"Disney",
"ques":"What year saw the release of Disney's Hercules?",
"answ":"1997",
"answ2":"1997.",
},
{
"cat":"Disney",
"ques":"Who voiced Zeus in Disney's Hercules?",
"answ":"RIP TORN",
"answ2":"Rip Torn.",
},
{
"cat":"Disney",
"ques":"What year saw the release of Disney's The Rescuers?",
"answ":"1977",
"answ2":"1977.",
},
{
"cat":"Disney",
"ques":"What was the name of the male mouse protagonist in Disney's The Rescuers films?",
"answ":"BERNARD",
"answ2":"Bernard.",
},
{
"cat":"Disney",
"ques":"What was the name of the female owner of Lady Disney's Lady and the Tramp?",
"answ":"DARLING",
"answ2":"Darling.",
},
{
"cat":"Disney",
"ques":"What year saw the release of Disney's The Aristocats?",
"answ":"1970",
"answ2":"1970.",
},
{
"cat":"Disney",
"ques":"What year saw the release of the Disney animated classic Peter Pan?",
"answ":"1953",
"answ2":"1953.",
},
{
"cat":"Disney",
"ques":"What Oscar winning actor voiced the poacher McLeach in Disney's The Rescuers Down Under?",
"answ":"GEORGE C SCOTT",
"answ2":"George C. Scott.",
},
{
"cat":"Disney",
"ques":"Who voiced the albatross Wilbur in Disney's The Rescuers Down Under?",
"answ":"JOHN CANDY",
"answ2":"John Candy.",
},
{
"cat":"Disney",
"ques":"What is the name of the streetwise dog that befriends Oliver in Disney's Oliver & Company?",
"answ":"DODGER",
"answ2":"Dodger.",
},
{
"cat":"Disney",
"ques":"What horror legend voices the villainous Ratigan in Disney's The Great Mouse Detective?",
"answ":"VINCENT PRICE",
"answ2":"Vincent Price.",
},
{
"cat":"Disney",
"ques":"What is the name of the villain in Disney's The Great Mouse Detective?",
"answ":"RATIGAN",
"answ2":"Ratigan.",
},
{
"cat":"Disney",
"ques":"Who voiced Oliver in Disney's Oliver & Company?",
"answ":"JOEY LAWRENCE",
"answ2":"Joey Lawrence.",
},
{
"cat":"Disney",
"ques":"Who voiced Tito the chihuahua in Disney's Oliver & Company?",
"answ":"CHEECH MARIN",
"answ2":"Cheech Marin.",
},
{
"cat":"Disney",
"ques":"Who voiced the villainous Sykes in Disney's Oliver & Company?",
"answ":"ROBERT LOGGIA",
"answ2":"Robert Loggia.",
},
{
"cat":"Disney",
"ques":"Trusty and Jock are two dogs that you'll find in what Disney Classic?",
"answ":"LADY AND THE TRAMP",
"answ2":"Lady and the Tramp.",
},
{
"cat":"Disney",
"ques":"What animal does Tramp save the baby from in Disney's Lady and the Tramp?",
"answ":"RAT",
"answ2":"Rat.",
},
{
"cat":"Disney",
"ques":"What is the name of the cat who gets abducted along with her kittens in Disney's The Aristocats?",
"answ":"DUCHESS",
"answ2":"Duchess.",
},
{
"cat":"Disney",
"ques":"What year was Disney's original Lady and the Tramp released?",
"answ":"1955",
"answ2":"1955.",
},
{
"cat":"Disney",
"ques":"What kind of animal did Robin Hood disguise himself as during the archery tournament in Disney's Robin Hood?",
"answ":"STORK",
"answ2":"Stork.",
},
{
"cat":"Disney",
"ques":"What kind of animal was the Sheriff of Nottingham in Disney's Robin Hood?",
"answ":"WOLF",
"answ2":"Wolf.",
},
{
"cat":"Disney",
"ques":"What kind of animal was Friar Tuck in Disney's Robin Hood?",
"answ":"BADGER",
"answ2":"Badger.",
},
{
"cat":"Disney",
"ques":"What Oscar winning actor voiced Prince John in Disney's Robin Hood?",
"answ":"PETER USTINOV",
"answ2":"Peter Ustinov.",
},
{
"cat":"Disney",
"ques":"What was the name of Prince John's snake advisor in Disney's Robin Hood?",
"answ":"SIR HISS",
"answ3":"HISS",
"answ2":"Sir Hiss.",
},
{
"cat":"Disney",
"ques":"What year saw the release of Disney's The Sword in the Stone?",
"answ":"1963",
"answ2":"1963.",
},
{
"cat":"Disney",
"ques":"What year was Disney's Robin Hood released?",
"answ":"1973",
"answ2":"1973.",
},
{
"cat":"Disney",
"ques":"By what name did those in the castle often call Arthur in Disney's The Sword in the Stone?",
"answ":"WART",
"answ2":"Wart.",
},
{
"cat":"Disney",
"ques":"What was the name of the owl in Disney's The Sword in the Stone?",
"answ":"ARCHIMEDES",
"answ2":"Archimedes.",
},
{
"cat":"Disney",
"ques":"What was the name of the albatross in Disney's The Rescuers Down Under?",
"answ":"WILBUR",
"answ2":"Wilbur.",
},
{
"cat":"Disney",
"ques":"What kind of bird did the mice fly on in both Rescuers films?",
"answ":"ALBATROSS",
"answ2":"Albatross.",
},
{
"cat":"Disney",
"ques":"What is the name of the young orphan girl that is held captive in Disney's The Rescuers?",
"answ":"PENNY",
"answ2":"Penny.",
},
{
"cat":"Disney",
"ques":"What was the name of the villain in Disney's The Rescuers?",
"answ":"MADAME MEDUSA",
"answ2":"Madame Medusa.",
},
{
"cat":"Disney",
"ques":"What did Madame Medusa have as pets in Disney's The Rescuers?",
"answ":"CROCODILES",
"answ2":"Crocodiles.",
},
{
"cat":"Disney",
"ques":"Brutus and Nero were the names of two crocodiles in what Disney Classic?",
"answ":"THE RESCUERS",
"answ2":"The Rescuers.",
},
{
"cat":"Disney",
"ques":"What was the name of the female mouse protagonist in Disney's The Rescuers films?",
"answ":"BIANCA",
"answ2":"Bianca.",
},
{
"cat":"Disney",
"ques":"Who voiced Bernard in Disney's The Rescuers films?",
"answ":"BOB NEWHART",
"answ2":"Bob Newhart.",
},
{
"cat":"Disney",
"ques":"Who voiced Miss Bianca in Disney's The Rescuers films?",
"answ":"EVA GABOR",
"answ2":"Eva Gabor.",
},
{
"cat":"Disney",
"ques":"What was the name of the hunter's veteran hunting dog in Disney's The Fox and the Hound?",
"answ":"CHIEF",
"answ2":"Chief.",
},
{
"cat":"Disney",
"ques":"You'll find two friends that are birds by the name of Dinky and Boomer in what animated Disney classic?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
},
{
"cat":"Disney",
"ques":"What late night talk show personality voiced Hermes, the Messenger God in Disney's Hercules?",
"answ":"PAUL SHAFFER",
"answ2":"Paul Shaffer.",
},
{
"cat":"Disney",
"ques":"What child actor voiced young Copper in Disney's The Fox and the Hound?",
"answ":"COREY FELDMAN",
"answ2":"Corey Feldman.",
},
{
"cat":"Disney",
"ques":"Who voiced adult Copper in Disney's The Fox and the Hound?",
"answ":"KURT RUSSELL",
"answ2":"Kurt Russell.",
},
{
"cat":"Disney",
"ques":"Who voiced adult Tod in Disney's The Fox and the Found?",
"answ":"MICKEY ROONEY",
"answ2":"Mickey Rooney.",
},
{
"cat":"Disney",
"ques":"Who voiced adult Hercules in Disney's Hercules?",
"answ":"TATE DONOVAN",
"answ2":"Tate Donovan.",
},
{
"cat":"Disney",
"ques":"In Disney's Hercules one of Hades' minions is named Pain. What is the name of the other one?",
"answ":"PANIC",
"answ2":"Panic.",
},
{
"cat":"Disney",
"ques":"What is the name of Hercules' love interest in Disney's Hercules?",
"answ":"MEG",
"answ2":"Meg.",
},
{
"cat":"Disney",
"ques":"In Disney's Hercules one of Hades' minions is named Panic. What is the name of the other one?",
"answ":"PAIN",
"answ2":"Pain.",
},
{
"cat":"Disney",
"ques":"Which classic Disney movie features a character baking a pie while singing 'Someday My Prince Will Come'?",
"answ":"SNOW WHITE AND THE SEVEN DWARFS",
"answ3":"SNOW WHITE",
"answ2":"Snow White and the Seven Dwarfs.",
},
{
"cat":"Disney",
"ques":"Which Disney film was the first animated movie to be nominated for a Best Picture Oscar, losing to Silence of the Lambs?",
"answ":"BEAUTY AND THE BEAST",
"answ2":"Beauty and the Beast.",
},
{
"cat":"Disney",
"ques":"During WWII in England, apprentice witch Angela Lansbury practices her craft on some children as well as thwarting a Nazi invasion in what film?",
"answ":"BEDKNOBS AND BROOMSTICKS",
"answ2":"Bedknobs and Broomsticks.",
},
{
"cat":"Disney",
"ques":"What classic Disney animated film is known for the song 'Heigh Ho'?",
"answ":"SNOW WHITE AND THE SEVEN DWARFS",
"answ3":"SNOW WHITE",
"answ2":"Snow White and the Seven Dwarfs.",
},
{
"cat":"Disney",
"ques":"Which actress voiced the evil Mother Gothel in Tangled?",
"answ":"DONNA MURPHY",
"answ2":"Donna Murphy.",
},
{
"cat":"Disney",
"ques":"What 2000s animated film, was the second theatrically released installment in the Winnie the Pooh franchise?",
"answ":"THE TIGGER MOVIE",
"answ3":"TIGGER MOVIE",
"answ2":"The Tigger Movie.",
},
{
"cat":"Disney",
"ques":"Glenn Close and Gérard Depardieu star in what 2000 live-action Disney sequel?",
"answ":"102 DALMATIANS",
"answ2":"102 Dalmatians.",
},
{
"cat":"Disney",
"ques":"Who stars as Cruella de Vil in the 2000 Disney film 102 Dalmatians?",
"answ":"GLENN CLOSE",
"answ2":"Glenn Close.",
},
{
"cat":"Disney",
"ques":"Who directed the films A Goofy Movie, Tarzan and 102 Dalmatians?",
"answ":"KEVIN LIMA",
"answ2":"Kevin Lima.",
},
{
"cat":"Disney",
"ques":"In Aladdin, what is the name of Jasmine's pet tiger?",
"answ":"RAJAH",
"answ3":"RAJA",
"answ2":"Rajah.",
},
{
"cat":"Disney",
"ques":"Donnie Yen and Jet Li appear in what 2020 live-action Disney film?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"Which actress stars as Maggie Peyton in 2005's Herbie Fully Loaded?",
"answ":"LINDSAY LOHAN",
"answ2":"Lindsay Lohan.",
},
{
"cat":"Disney",
"ques":"This Disney film features the line: 'Teenagers. They think they known everything. You give them an inch, they swim all over you.'?",
"answ":"THE LITTLE MERMAID",
"answ3":"LITTLE MERMAID",
"answ2":"The Little Mermaid.",
},
{
"cat":"Disney",
"ques":"In which 2018 Disney film will you find the hundred-acre woods and hear about creatures known as Heffalumps and Woozles?",
"answ":"CHRISTOPHER ROBIN",
"answ2":"Christopher Robin.",
},
{
"cat":"Disney",
"ques":"'Go the Distance' was nominated for Best Original Song for what 90s Disney film?",
"answ":"HERCULES",
"answ2":"Hercules.",
},
{
"cat":"Disney",
"ques":"What 1998 live-action Disney remake stars Lindsay Lohan, Dennis Quaid and Natasha Richardson?",
"answ":"THE PARENT TRAP",
"answ2":"The Parent Trap.",
},
{
"cat":"Disney",
"ques":"In The Many Adventures of Winne the Pooh, which character says: 'I'm so happy, I feel like bouncing.'?",
"answ":"TIGGER",
"answ2":"Tigger.",
},
{
"cat":"Disney",
"ques":"The song 'I'll Make a Man Out of You', is performed while young men are trained to be soldiers for war in what Disney film?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"What classic Disney film is a series of animated scenes set to famous classical music pieces, such as The Nutcracker Suite?",
"answ":"FANTASIA",
"answ2":"Fantasia.",
},
{
"cat":"Disney",
"ques":"This Academy Award winning actress played Lady Tremaine, the evil stepmother in Disney's live-action adaptation of Cinderella.",
"answ":"CATE BLANCHETT",
"answ3":"KATE BLANCHETT",
"answ2":"Cate Blanchett.",
},
{
"cat":"Disney",
"ques":"What Disney villain has blue flames for hair?",
"answ":"HADES",
"answ2":"Hades.",
},
{
"cat":"Disney",
"ques":"David Spade and John Goodman voice Kuzco and Pacha respectively in what Disney film?",
"answ":"THE EMPEROR'S NEW GROOVE",
"answ3":"EMPEROR'S NEW GROOVE",
"answ2":"The Emperor's New Groove.",
},
{
"cat":"Disney",
"ques":"Which SNL alum provides the voice of Kuzco in The Emperor's New Groove?",
"answ":"DAVID SPADE",
"answ2":"David Spade.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin who does Aladdin pretend to be to safe Jasmine from having her hand cut off by the merchant in the marketplace?",
"answ":"HER BROTHER",
"answ3":"BROTHER",
"answ2":"Her brother.",
},
{
"cat":"Disney",
"ques":"What Disney animated film series features two lead characters by the names of Bernard and Bianca?",
"answ":"THE RESCUERS",
"answ3":"RESCUERS",
"answ2":"The Rescuers.",
},
{
"cat":"Disney",
"ques":"What 2016 Disney remake stars Robert Redford and Bryce Dallas Howard?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
},
{
"cat":"Disney",
"ques":"What 1954 Disney film features Captain Nemo, and his ship, the Nautilus?",
"answ":"20000 LEAGUES UNDER THE SEA",
"answ3":"20 000 LEAGUES UNDER THE SEA",
"answ2":"20,000 Leagues Under the Sea.",
},
{
"cat":"Disney",
"ques":"In 1994's The Lion King, who voices adult Simba?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
},
{
"cat":"Disney",
"ques":"What Disney animated movie features the Billy Joel song 'Why Should I Worry'?",
"answ":"OLIVER AND COMPANY",
"answ2":"Oliver & Company.",
},
{
"cat":"Disney",
"ques":"Prince Philip is the prince from what Disney animated classic?",
"answ":"SLEEPING BEAUTY",
"answ2":"Sleeping Beauty.",
},
{
"cat":"Disney",
"ques":"What country does the Disney classic Beauty and the Beast take place in?",
"answ":"FRANCE",
"answ2":"France.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, what kind of animals are Ursula's pets?",
"answ":"EELS",
"answ3":"MORAY EELS",
"answ2":"Eels.",
},
{
"cat":"Disney",
"ques":"You'll find a demon-like villain named The Horned King in what Disney animated film?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"What was the name of the sequel to Disney's The Rescuers?",
"answ":"THE RESCUERS DOWN UNDER",
"answ3":"RESCUERS DOWN UNDER",
"answ2":"The Rescuers Down Under.",
},
{
"cat":"Disney",
"ques":"The world 'parley' is used in order to stop a fight and talk things out in what Disney adventure?",
"answ":"PIRATES OF THE CARIBBEAN",
"answ3":"PIRATES OF THE CARIBBEAN THE CURSE OF THE BLACK PEARL",
"answ2":"Pirates of the Caribbean: The Curse of the Black Pearl.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, for how many years does the Genie tell Aladdin he's been trapped in the lamp?",
"answ":"10 000",
"answ3":"10000",
"answ2":"10,000.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, what is the name of the flying carpet?",
"answ":"CARPET",
"answ2":"Carpet.",
},
{
"cat":"Disney",
"ques":"Who plays the singing prince in the live-action animation hybrid Enchanted?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
},
{
"cat":"Disney",
"ques":"Who voiced Scar in 1994's The Lion King?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
},
{
"cat":"Disney",
"ques":"In Disney's Robin Hood, what type of animal is Robin Hood?",
"answ":"FOX",
"answ2":"Fox.",
},
{
"cat":"Disney",
"ques":"Captain Hook has his hook on his ____ hand.",
"answ":"LEFT",
"answ3":"LEFT HAND",
"answ2":"His left hand.",
},
{
"cat":"Disney",
"ques":"Who voices the parrot Iago in 1992's Aladdin?",
"answ":"GILBERT GOTTFRIED",
"answ2":"Gilbert Gottfried.",
},
{
"cat":"Disney",
"ques":"What is the name of the walking talking clock in Disney's Beauty and the Beast?",
"answ":"COGSWORTH",
"answ2":"Cogsworth.",
},
{
"cat":"Disney",
"ques":"Tiana is the name of the lead character in what Disney film?",
"answ":"THE PRINCESS AND THE FROG",
"answ3":"PRINCESS AND THE FROG",
"answ2":"The Princess and the Frog.",
},
{
"cat":"Disney",
"ques":"Judge Frollo is the villain of which Disney film?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"Meeko and Flit are the names of two characters in what Disney film?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Disney",
"ques":"Which Disney film features a pig herder named Taran who must go on a quest to stop the evil Horned King?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"Who voices Esmeralda in Disney's The Hunchback of Notre Dame?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
},
{
"cat":"Disney",
"ques":"Mandy Moore and Zachary Levi provide voices in which Disney film?",
"answ":"TANGLED",
"answ2":"Tangled.",
},
{
"cat":"Disney",
"ques":"Herbie Rides Again was the sequel to what Disney classic?",
"answ":"THE LOVE BUG",
"answ2":"The Love Bug.",
},
{
"cat":"Disney",
"ques":"Mackenzie Foy plays the lead Clara Stahlbaum in what 2010s Disney live action film?",
"answ":"THE NUTCRACKER AND THE FOUR REALMS",
"answ3":"NUTCRACKER AND THE FOUR REALMS",
"answ2":"The Nutcracker and the Four Realms.",
},
];
var r2Q17 = [
{
"cat":"Disney",
"ques":"What Disney character has a best friend named Timothy Q. Mouse?",
"answ":"DUMBO",
"answ2":"Dumbo.",
"option":["Dumbo", "Pinocchio", "Merlin", "Quasimodo"],
},
{
"cat":"Disney",
"ques":"What is the name of the octopus-like villain in The Little Mermaid?",
"answ":"URSULA",
"answ2":"Ursula.",
"option":["Ursula", "Angela", "Katherine", "Maleficent"],
},
{
"cat":"Disney",
"ques":"In The Rescuers, what precious object is the Devil's Eye?",
"answ":"DIAMOND",
"answ2":"Diamond.",
"option":["Diamond", "Emerald", "Sapphire", "Ruby"],
},
{
"cat":"Disney",
"ques":"What was the first full-length Disney movie to star Goofy as the title character?",
"answ":"A GOOFY MOVIE",
"answ3":"GOOFY MOVIE",
"answ2":"A Goofy Movie.",
"option":["A Goofy Movie", "Goofy's Adventure", "Goofy The Movie", "The Adventures of Goofy"],
},
{
"cat":"Disney",
"ques":"What actor is the voice of the satyr Phil in Hercules?",
"answ":"DANNY DEVITO",
"answ2":"Danny DeVito.",
"option":["Danny DeVito", "Adam Sandler", "Eddie Murphy", "Samuel E. Wright"],
},
{
"cat":"Disney",
"ques":"The character Thomas O'Malley is from what Disney animated classic?",
"answ":"THE ARISTOCATS",
"answ3":"ARISTOCATS",
"answ2":"The Aristocats.",
"option":["The Aristocats", "The Great Mouse Detective", "The Rescuers", "Oliver & Company"],
},
{
"cat":"Disney",
"ques":"Who provided the voice of the villainous Hades in Disney's Hercules?",
"answ":"JAMES WOODS",
"answ2":"James Woods.",
"option":["James Woods", "Martin Short", "Hugh Laurie", "Christopher Walken"],
},
{
"cat":"Disney",
"ques":"Who plays the baseball agent who journeys to India to look for untapped baseball talent in Million Dollar Arm?",
"answ":"JON HAMM",
"answ2":"Jon Hamm.",
"option":["Jon Hamm", "Michael Keaton", "Aaron Eckhart", "Ryan Gosling"],
},
{
"cat":"Disney",
"ques":"What kind of object was Dumbo told that it was magic and if he held it in his trunk he would be able to fly?",
"answ":"FEATHER",
"answ3":"A FEATHER",
"answ2":"Feather.",
"option":["Feather", "Branch", "Flower", "String"],
},
{
"cat":"Disney",
"ques":"Who plays D'Artagnan in 1993's The Three Musketeers?",
"answ":"CHRIS O'DONNELL",
"answ2":"Chris O'Donnell.",
"option":["Chris O'Donnell", "Charlie Sheen", "Oliver Platt", "Kiefer Sutherland"],
},
{
"cat":"Disney",
"ques":"What is the name of the youngest of the three Darling children in 1953's Peter Pan?",
"answ":"MICHAEL",
"answ2":"Michael.",
"option":["Michael", "Charlie", "Oliver", "Alfred"],
},
{
"cat":"Disney",
"ques":"In 1950's Cinderella, one of the two mice is called Jaq. What is the other one called?",
"answ":"GUS",
"answ2":"Gus.",
"option":["Gus", "Joe", "Fred", "Syl"],
},
{
"cat":"Disney",
"ques":"What Disney film features the vultures Trigger and Nutsy?",
"answ":"ROBIN HOOD",
"answ2":"Robin Hood.",
"option":["Robin Hood", "The Sword in the Stone", "The Black Cauldron", "Cinderella"],
},
{
"cat":"Disney",
"ques":"What was Disney's first live-action science-fiction film?",
"answ":"20000 LEAGUES UNDER THE SEA",
"answ3":"20 000 LEAGUES UNDER THE SEA",
"answ2":"20,000 Leagues Under the Sea.",
"option":["20,000 Leagues Under the Sea", "The Black Hole", "Tron", "Moon Pilot"],
},
{
"cat":"Disney",
"ques":"Who voiced Fear in 2015's Inside Out?",
"answ":"BILL HADER",
"answ2":"Bill Hader.",
"option":["Bill Hader", "Justin Long", "Kyle MacLachlan", "Jesse Eisenberg"],
},
{
"cat":"Disney",
"ques":"In Mary Poppins, what animal that also spoke was on the end of Mary Poppins' umbrella?",
"answ":"PARROT",
"answ3":"BIRD",
"answ2":"Parrot.",
"option":["Parrot", "Sheep", "Lion", "Dog"],
},
{
"cat":"Disney",
"ques":"In what animated feature would you find a villain named Sykes?",
"answ":"OLIVER AND COMPANY",
"answ2":"Oliver & Company.",
"option":["Oliver & Company", "Home on the Range", "Atlantis The Lost Empire", "Tarzan"],
},
{
"cat":"Disney",
"ques":"What Firefly and Serenity star has provided their voice to Wreck-It Ralph, Frozen, Big Hero 6 and Zootopia?",
"answ":"ALAN TUDYK",
"answ3":"ALAN TUDIK",
"answ2":"Alan Tudyk.",
"option":["Alan Tudyk", "Nathan Fillion", "Gina Torres", "Adam Baldwin"],
},
{
"cat":"Disney",
"ques":"In Disney's Bolt, who voiced the titular character?",
"answ":"JOHN TRAVOLTA",
"answ2":"John Travolta.",
"option":["John Travolta", "Nicolas Cage", "Ed Harris", "Alec Baldwin"],
},
{
"cat":"Disney",
"ques":"In 1994's The Lion King, what is the name of the place that Simba is forbidden to go to?",
"answ":"THE ELEPHANT GRAVEYARD",
"answ3":"ELEPHANT GRAVEYARD",
"answ2":"The Elephant Graveyard.",
"option":["The Elephant Graveyard", "Pride Rock", "The Oasis", "The Water Hole"],
},
{
"cat":"Disney",
"ques":"You'll find the characters of Copper and Tod in this Disney animated film?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":["The Fox and the Hound", "Bambi", "Lady and the Tramp", "The Aristocats"],
},
{
"cat":"Disney",
"ques":"In Dinosaur, what is the name of the young Iguanodon who is adopted and raised by a family of lemurs?",
"answ":"ALADAR",
"answ2":"Aladar.",
"option":["Aladar", "Plio", "ittlefoot", "Suri"],
},
{
"cat":"Disney",
"ques":"What is the prince's name in The Little Mermaid?",
"answ":"ERIC",
"answ3":"ERIK",
"answ2":"Eric.",
"option":["Eric", "Charming", "Jonathan", "Philip"],
},
{
"cat":"Disney",
"ques":"Which 1970s Disney film is set at the Maine village of Passamaquoddy?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
"option":["Pete's Dragon", "Bedknobs and Broomsticks", "Candleshoe", "Pocahontas"],
},
{
"cat":"Disney",
"ques":"In Aladdin, Jafar uses a golden what, to locate the cave that hides the magic lamp?",
"answ":"SCARAB",
"answ3":"GOLDEN SCARAB",
"answ2":"Scarab.",
"option":["Scarab", "Dagger", "Compass", "Arrow"],
},
{
"cat":"Disney",
"ques":"Finish the quote from Frozen: 'Winter is a good time to stay in and cuddle, put me in Summer and I'll be a ____'",
"answ":"HAPPY SNOWMAN",
"answ3":"A HAPPY SNOWMAN",
"answ2":"Happy Snowman.",
"option":["Happy Snowman", "Sad Snowman", "Puddle", "Melting Snowman"],
},
{
"cat":"Disney",
"ques":"Who voices adventurer Jim Hawkins in 2002's Treasure Planet?",
"answ":"JOSEPH GORDON LEVITT",
"answ3":"JOSEPH GORDON LEVIT",
"answ2":"Joseph Gordon-Levitt.",
"option":["Joseph Gordon-Levitt", "Ryan Gosling", "Jonathan Taylor Thomas", "Frankie Muniz"],
},
{
"cat":"Disney",
"ques":"Which 1977 live-action Disney film was directed by Don Chaffey and starred Sean Marshall?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
"option":["Pete's Dragon", "The Phantom Tollbooth", "The Hobbit", "One of Our Dinosaurs is Missing"],
},
{
"cat":"Disney",
"ques":"The term 'Twitterpated' is the word that described falling in love in what Disney animated classic?",
"answ":"BAMBI",
"answ2":"Bambi.",
"option":["Bambi", "Pocanhontas", "Dumbo", "The Fox and the Hound"],
},
{
"cat":"Disney",
"ques":"According to a song from the film, which Disney character went from 'zero to hero'?",
"answ":"HERCULES",
"answ2":"Hercules.",
"option":["Hercules", "Pinocchio", "Dumbo", "Cinderella"],
},
{
"cat":"Disney",
"ques":"What classic Disney character baked a gooseberry pie while singing 'Someday my prince will come'?",
"answ":"SNOWWHITE",
"answ3":"SNOW WHITE",
"answ2":"Snow White.",
"option":["Snow White", "Belle", "Sleeping Beauty", "Cinderella"],
},
{
"cat":"Disney",
"ques":"How many Disney films were made about a hockey team called The Mighty Ducks?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "1", "4"],
},
{
"cat":"Disney",
"ques":"What do Aladdin and his monkey steal from the marketplace when you're first introduced to them in 1992's Aladdin?",
"answ":"BREAD",
"answ3":"A BREAD",
"answ2":"Bread.",
"option":["Bread", "Apple", "Money", "Fish"],
},
{
"cat":"Disney",
"ques":"What is the name of the main villain in Disney's Mulan?",
"answ":"SHAN YU",
"answ2":"Shan Yu.",
"option":["Shan Yu", "Fa Zhou", "Shang", "Yao"],
},
{
"cat":"Disney",
"ques":"What is the name of the Disney character known as 'the great mouse detective'?",
"answ":"BASIL",
"answ2":"Basil.",
"option":["Basil", "Sherwin", "Dr. Dawson", "Ratcliffe"],
},
{
"cat":"Disney",
"ques":"Adriana Caselotti was 18 years old when she was asked to voice what famous Disney character?",
"answ":"SNOW WHITE",
"answ3":"SNOWWHITE",
"answ2":"Snow White.",
"option":["Snow White", "Sleeping Beauty", "Ariel", "Cinderella"],
},
{
"cat":"Disney",
"ques":"In what 90s Disney animated film do you hear Disney tunes such as 'Stand Out', 'After Today' and 'I2I (Eye-2-Eye)'?",
"answ":"A GOOFY MOVIE",
"answ3":"GOOFY MOVIE",
"answ2":"A Goofy Movie.",
"option":["A Goofy Movie", "The Hunchback of Notre Dame", "The Rescuers Down Under", "Pocahontas"],
},
{
"cat":"Disney",
"ques":"Who voices Jane Porter in 1999's Tarzan?",
"answ":"MINNIE DRIVER",
"answ2":"Minnie Driver.",
"option":["Minnie Driver", "Reese Witherspoon", "Sally Field", "Joan Cusack"],
},
{
"cat":"Disney",
"ques":"The Court of Miracles is the name of a secret hideout in what Disney animated film?",
"answ":"THE HUNCHBACK OF NOTRE DAM",
"answ3":"HUNCHBACK OF NOTRE DAM",
"answ2":"The Hunchback of Notre Dame.",
"option":["The Hunchback of Notre Dame", "Pocahontas", "The Black Cauldron", "The Sword in the Stone"],
},
{
"cat":"Disney",
"ques":"The 'Unbirthday Song' can be found in what Disney film?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
"option":["Alice in Wonderland", "Peter Pan", "The Jungle Book", "A Goofy Movie"],
},
{
"cat":"Disney",
"ques":"Other than 'Mowgli', what do many of the characters in 1967's Disney's Jungle Book refer to him as?",
"answ":"MAN CUB",
"answ2":"Man Cub.",
"option":["Man Cub", "Baby Cub", "Man Child", "Little One"],
},
{
"cat":"Disney",
"ques":"Over what activity does Mr. Banks finally bond with his children in Mary Poppins?",
"answ":"FLYING A KITE",
"answ3":"KITE FLYING",
"answ2":"Flying a kite.",
"option":["Flying a kite", "Soccer", "Baseball", "Playing chess"],
},
{
"cat":"Disney",
"ques":"This musical tribute to the world of Uncle Remus co-starred Oscar-winner Hattie McDaniel in what controversial Disney film?",
"answ":"SONG OF THE SOUTH",
"answ2":"Song of the South.",
"option":["Song of the South", "Melody Time", "The Reluctant Dragon", "The Vanishing Prairie"],
},
{
"cat":"Disney",
"ques":"You'll find the main characters by the name of Meg and Phil in what Disney animated film?",
"answ":"HERCULES",
"answ2":"Hercules.",
"option":["Hercules", "Big Hero 6", "The Hunchback of Notre Dame", "Wreck-It Ralph"],
},
{
"cat":"Disney",
"ques":"Who stars as a busy realtor whose family is invited to a mysterious manor in 2003's Haunted Mansion?",
"answ":"EDDIE MURPHY",
"answ2":"Eddie Murphy.",
"option":["Eddie Murphy", "Jack Black", "Brendan Fraser", "Robin Williams"],
},
{
"cat":"Disney",
"ques":"What classic Disney movie stars Fred MacMurray, introduced a substance called 'Flubber' and features a flying Model T?",
"answ":"THE ABSENT MINDED PROFESSOR",
"answ3":"ABSENT MINDED PROFESSOR",
"answ2":"The Absent-Minded Professor.",
"option":["The Absent-Minded Professor", "Big Red", "The Barefoot Executive", "Gus"],
},
{
"cat":"Disney",
"ques":"In Tangled, what symbol decorates the lanterns released by Rapunzel's parents?",
"answ":"SUN",
"answ3":"A SUN",
"answ2":"A sun.",
"option":["A sun", "An angel", "A flower", "A moon"],
},
{
"cat":"Disney",
"ques":"Who voices social worker Cobra Bubbles in Lilo and Stitch?",
"answ":"VING RHAMES",
"answ2":"Ving Rhames.",
"option":["Ving Rhames", "Michael Clarke Duncan", "Tommy Lister", "Billy Dee Williams"],
},
{
"cat":"Disney",
"ques":"What is the name of the evil marionette master who kidnaps Pinocchio to star in his shows?",
"answ":"STROMBOLI",
"answ2":"Stromboli.",
"option":["Stromboli", "Gideon", "Figaro", "Lampwick"],
},
{
"cat":"Disney",
"ques":"In The Emperor's New Groove, Yzma's bumbling right-hand man, Kronk, gets information about Kuzco's whereabouts by talking to what woodland creature?",
"answ":"SQUIRREL",
"answ3":"SQUIREL",
"answ2":"Squirrel.",
"option":["Squirrel", "Chipmunk", "Rabbit", "Weasel"],
},
{
"cat":"Disney",
"ques":"Who was the lead and played both characters Susan Evers/Sharon McKendrick in 1961's Parent Trap?",
"answ":"HAYLEY MILLS",
"answ3":"HAILEE MILLS",
"answ2":"Hayley Mills.",
"option":["Hayley Mills", "Nancy Kwan", "Ina Balin", "Jane Fonda"],
},
{
"cat":"Disney",
"ques":"In the Pirates of the Caribbean franchise, before joining a life of piracy, Will Turner was an apprentice in what profession?",
"answ":"BLACKSMITH",
"answ3":"SMITH",
"answ2":"Blacksmith.",
"option":["Blacksmith", "Butcher", "Baker", "Carpenter"],
},
{
"cat":"Disney",
"ques":"In Big Hero 6, what comedic actor provides the voice for uber comic book fan and professional slacker, Fred?",
"answ":"TJ MILLER",
"answ3":"T J MILLER",
"answ2":"T.J. Miller.",
"option":["T.J. Miller", "James Franco", "Seth Rogen", "Jason Segel"],
},
{
"cat":"Disney",
"ques":"What is the name of Goofy's son in A Goofy Movie?",
"answ":"MAX",
"answ2":"Max.",
"option":["Max", "PJ", "Bobby", "Wally"],
},
{
"cat":"Disney",
"ques":"In Mary Poppins Returns, who plays Wilkins and also voices Wolf?",
"answ":"COLIN FIRTH",
"answ3":"COLLIN FIRTH",
"answ2":"Colin Firth.",
"option":["Colin Firth", "Lin Manuel-Miranda", "David Warner", "Jim Norton"],
},
{
"cat":"Disney",
"ques":"Which Disney princess comes from Andalasia?",
"answ":"GISELLE",
"answ3":"PRINCESS GISELLE",
"answ2":"Giselle.",
"option":["Giselle", "Rapunzel", "Aurora", "Belle"],
},
{
"cat":"Disney",
"ques":"What Disney animated film features the song Following The Leader?",
"answ":"PETER PAN",
"answ2":"Peter Pan.",
"option":["Peter Pan", "Beauty & the Beast", "Pocahontas", "Mulan"],
},
{
"cat":"Disney",
"ques":"What 90s film was Disney's live-action remake of one of its earlier animated feature films and starred Cary Elwes, Lena Headey and Sam Neill?",
"answ":"RUDYARD KIPLING'S THE JUNGLE BOOK",
"answ3":"THE JUNGLE BOOK",
"answ2":"Rudyard Kipling's The Jungle Book.",
"option":["Rudyard Kipling's The Jungle Book", "Alice in Wonderland", "101 Dalmatians", "The Sorcerer's Apprentice"],
},
{
"cat":"Disney",
"ques":"Which animated film includes the song The Best of Friends?",
"answ":"FOX AND THE HOUND",
"answ3":"THE FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":["The Fox and the Hound", "Oliver and Company", "Tarzan", "Lilo & Stitch"],
},
{
"cat":"Disney",
"ques":"In Lilo & Stitch, what is the word that means family?",
"answ":"OHANA",
"answ2":"Ohana.",
"option":["Ohana", "Aloha", "Mahalo", "Kahuna"],
},
{
"cat":"Disney",
"ques":"In 101 Dalmatians, dog owners Roger and Anita reside in what city?",
"answ":"LONDON",
"answ2":"London.",
"option":["London", "Paris", "New York City", "Dublin"],
},
{
"cat":"Disney",
"ques":"What was the name of the villain in the 1985 animated film The Black Cauldron?",
"answ":"HORNED KING",
"answ2":"Horned King.",
"option":["Horned King", "Black King", "Cursed King", "Evil King"],
},
{
"cat":"Disney",
"ques":"Who provides the speaking voice for Captain Li Shang in Disney's Mulan?",
"answ":"BD WONG",
"answ2":"BD Wong.",
"option":["BD Wong", "Ken Watanabe", "Jerry Tondo", "Harvey Fierstein"],
},
{
"cat":"Disney",
"ques":"Edgar is the name of the villainous butler in what Disney animated film?",
"answ":"THE ARISTOCATS",
"answ3":"ARISTOCATS",
"answ2":"The Aristocats.",
"option":["The Aristocats", "The Fox and the Hound", "Oliver & Company", "Lady and the Tramp"],
},
{
"cat":"Disney",
"ques":"What is the name of the speaking tree that serves as Pocanhontas' guide in the film Pocahontas?",
"answ":"GRANDMOTHER WILLOW",
"answ2":"Grandmother Willow.",
"option":["Grandmother Willow", "Mother Tree", "Powhatan Willow", "Nakoma Tree"],
},
{
"cat":"Disney",
"ques":"What 1980s Disney animated film stars the voice talents of Kurt Russell and Mickey Rooney?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":["The Fox and the Hound", "The Rescuers", "Oliver & Company", "The Great Mouse Detective"],
},
{
"cat":"Disney",
"ques":"Dwayne Johnson's character has what profession, which propels him into an adventure, in the Disney film Race to Witch Mountain?",
"answ":"TAXI DRIVER",
"answ3":"CAB DRIVER",
"answ2":"Taxi driver.",
"option":["Taxi driver", "Firefighter", "Construction worker", "Pilot"],
},
{
"cat":"Disney",
"ques":"Who plays real life composer Richard Sherman in 2013's Saving Mr. Banks?",
"answ":"JASON SCHWARTZMAN",
"answ2":"Jason Schwartzman.",
"option":["Jason Schwartzman", "B.J. Novak", "Colin Farrell", "Bradley Whitford"],
},
{
"cat":"Disney",
"ques":"In Tangled, after being denied permission to leaver her tower, what does Rapunzel ask her mother to get her for her 18th birthday?",
"answ":"PAINT",
"answ2":"Paint.",
"option":["Paint", "Hairbrush", "Gold Thread", "Lantern"],
},
{
"cat":"Disney",
"ques":"Who plays the lead role of Christopher Robin in 2018's Christopher Robin?",
"answ":"EWAN MCGREGOR",
"answ2":"Ewan McGregor.",
"option":["Ewan McGregor", "Hugh Grant", "Colin Firth", "Colin Farrell"],
},
{
"cat":"Disney",
"ques":"In 1955's Lady and the Tramp, what is the name of the restaurant where they eat the spaghetti?",
"answ":"TONY'S",
"answ2":"Tony's.",
"option":["Tony's", "Belle Noche", "Vicuzzis's", "Alfredo's"],
},
{
"cat":"Disney",
"ques":"In Zootopia, what is the name of the shrew who is the most feared mob boss in Tundratown?",
"answ":"MR BIG",
"answ3":"MISTER BIG",
"answ2":"Mr. Big.",
"option":["Mr. Big", "Tony Shrewmoni", "Mr. Shrewlington", "Don Shrewleone"],
},

{
"cat":"Disney",
"ques":"In Snow White & The Seven Dwarfs, what type of pie was Snow White baking when she was singing 'Someday My Prince Will Come'?",
"answ":"GOOSEBERRY PIE",
"answ3":"GOOSEBERRY",
"answ2":"Gooseberry Pie.",
"option":["Gooseberry Pie", "Blueberry Pie", "Apple Pie", "Hornazo pie"],
},
{
"cat":"Disney",
"ques":"Who voiced young Hercules in Disney's Hercules?",
"answ":"JOSH KEATON",
"answ2":"Josh Keaton.",
"option":["Josh Keaton", "Cary Elwes", "Andrew Lawrence", "Fred Savage"],
},
{
"cat":"Disney",
"ques":"What was the name of the motherly Owl in Disney's The Fox and the Hound?",
"answ":"BIG MAMA",
"answ2":"Big Mama.",
"option":["Big Mama", "Archimedes", "Friend Owl", "Tweed"],
},
{
"cat":"Disney",
"ques":"What was the name of the antagonistic hunter in Disney's The Fox and the Hound?",
"answ":"AMOS SLADE",
"answ3":"AMOS",
"answ2":"Amos Slade.",
"option":["Amos Slade", "Claude Frollo", "Slade Wilson", "Bernard Bridger"],
},
{
"cat":"Disney",
"ques":"What was the name of the female fox that Tod befriends in Disney's The Fox and the Hound?",
"answ":"VIXEY",
"answ2":"Vixey.",
"option":["Vixey", "Lexie", "Trixie", "Sandy"],
},
{
"cat":"Disney",
"ques":"Who voiced the female fox that Tod befriends in in Disney's The Fox and the Hound?",
"answ":"SANDY DUNCAN",
"answ2":"Sandy Duncan.",
"option":["Sandy Duncan", "Jodie Foster", "Florence Henderson", "Kim Cattrall"],
},
{
"cat":"Disney",
"ques":"What was the name of the woman who cared for Tod in Disney's The Fox and the Hound?",
"answ":"WIDOW TWEED",
"answ3":"TWEED",
"answ2":"Widow Tweed.",
"option":["Widow Tweed", "Ms. Helen", "Big Mama", "Old Nan"],
},
{
"cat":"Disney",
"ques":"Who voiced Meg in Disney's Hercules?",
"answ":"SUSAN EGAN",
"answ2":"Susan Egan.",
"option":["Susan Egan", "Emma Thompson", "Jodie Benson", "Charlize Theron"],
},
{
"cat":"Disney",
"ques":"What actor, with a unique voice of their own, lent it to Pain in Disney's Hercules?",
"answ":"BOBCAT GOLDTHWAIT",
"answ2":"Bobcat Goldthwait.",
"option":["Bobcat Goldthwait", "Ray Romano", "Dana Carvey", "Tim Curry"],
},
{
"cat":"Disney",
"ques":"What was the name of the albatross in Disney's The Rescuers?",
"answ":"ORVILLE",
"answ2":"Orville.",
"option":["Orville", "Bernard", "Wilbur", "Albus"],
},
{
"cat":"Disney",
"ques":"What is the name of the place where the young girl is being held captive in Disney's The Rescuers?",
"answ":"DEVIL'S BAYOU",
"answ2":"Devil's Bayou.",
"option":["Devil's Bayou", "Devil's Lake", "Devil's Eye", "Devil's Cove"],
},
{
"cat":"Disney",
"ques":"What is the name of the organization dedicated to helping abduction victims in Disney's The Rescuers?",
"answ":"RESCUE AID SOCIETY",
"answ2":"Rescue Aid Society.",
"option":["Rescue Aid Society", "Search and Rescue", "Lost and Found", "Rescue Aid Association"],
},
{
"cat":"Disney",
"ques":"At the end of Disney's The Sword in the Stone what tropical location did Merlin return from?",
"answ":"BERMUDA",
"answ2":"Bermuda.",
"option":["Bermuda", "Costa Rica", "Bahamas", "Jamaica"],
},
{
"cat":"Disney",
"ques":"What was the name of the witch that Merlin battled in Disney's The Sword in the Stone?",
"answ":"MADAM MIM",
"answ2":"Madam Mim.",
"option":["Madam Mim", "Ursula", "Madame Medusa", "Winifred"],
},
{
"cat":"Disney",
"ques":"What was the name of the ruler of the King's Castle and Arthur's foster father in Disney's The Sword in the Stone?",
"answ":"SIR ECTOR",
"answ3":"ECTOR",
"answ2":"Sir Ector.",
"option":["Sir Ector", "Lancelot", "Sir Kay", "Percival"],
},
{
"cat":"Disney",
"ques":"What was the name of Arthur's foster brother in Disney's The Sword in the Stone?",
"answ":"SIR KAY",
"answ3":"KAY",
"answ2":"Sir Kay.",
"option":["Sir Kay", "Percival", "Sir Ector", "Lancelot"],
},
{
"cat":"Disney",
"ques":"What was the name of the minstrel rooster in Disney's Robin Hood?",
"answ":"ALLAN A DALE",
"answ2":"Allan-a-Dale.",
"option":["Allan-a-Dale", "Gilbert Whitehand", "Will Scarlet", "Will Stutely"],
},
{
"cat":"Disney",
"ques":"What singer-songwriter voiced The Rooster in Disney's Robin Hood?",
"answ":"ROGER MILLER",
"answ2":"Roger Miller.",
"option":["Roger Miller", "Kris Kristofferson", "Glenn Campbell", "Dean Martin"],
},
{
"cat":"Disney",
"ques":"Who voiced the Classic Disney characters Baloo, Little John and Thomas O'Malley?",
"answ":"PHIL HARRIS",
"answ2":"Phil Harris.",
"option":["Phil Harris", "Sterling Holloway", "Sebastian Cabot", "John Fiedler"],
},
{
"cat":"Disney",
"ques":"What actor, who appeared in numerous westerns, voiced Friar Tuck in Disney's Robin Hood?",
"answ":"ANDY DEVINE",
"answ2":"Andy Devine.",
"option":["Andy Devine", "John Fiedler", "Dean Martin", "Gary Cooper"],
},
{
"cat":"Disney",
"ques":"What was the name of Maid Marian's friend in Disney's Robin Hood?",
"answ":"LADY KLUCK",
"answ3":"KLUCK",
"answ2":"Lady Kluck.",
"option":["Lady Kluck", "Lady Beaks", "Lady Chick", "Lady Feathers"],
},
{
"cat":"Disney",
"ques":"What was the name of the crossbow wielding vulture in Disney's Robin Hood?",
"answ":"TRIGGER",
"answ2":"Trigger.",
"option":["Trigger", "Shooter", "Nutsy", "Lucky"],
},
{
"cat":"Disney",
"ques":"What was the name of the dopey vulture henchman in Disney's Robin Hood?",
"answ":"NUTSY",
"answ2":"Nutsy.",
"option":["Nutsy", "Happy", "Trigger", "Lucky"],
},
{
"cat":"Disney",
"ques":"Who pretends to be the Duke of Chutney in Disney's Robin Hood?",
"answ":"LITTLE JOHN",
"answ2":"Little John.",
"option":["Little John", "Little John", "Robin Hood", "Will Scarlet"],
},
{
"cat":"Disney",
"ques":"What is name of the song everyone is singing that is mocking Prince John in Disney's Robin Hood?",
"answ":"THE PHONY KING OF ENGLAND",
"answ3":"PHONY KING OF ENGLAND",
"answ2":"Phony King of England.",
"option":["Phony King of England", "Oo-De-Lally", "Not in Nottingham", "Whistle Stop"],
},
{
"cat":"Disney",
"ques":"What is name of the young turtle that is friends with the rabbit children in Disney's Robin Hood?",
"answ":"TOBY",
"answ2":"Toby.",
"option":["Toby", "Archie", "Jordy", "Tort"],
},
{
"cat":"Disney",
"ques":"What is the name of young male rabbit that idolized Robin Hood in Disney's Robin Hood?",
"answ":"SKIPPY",
"answ2":"Skippy.",
"option":["Skippy", "Fuzz", "Hoppy", "Hopps"],
},
{
"cat":"Disney",
"ques":"What kind of animal is the priest in Disney's Robin Hood?",
"answ":"MOUSE",
"answ2":"Mouse.",
"option":["Mouse", "Bear", "Badger", "Dog"],
},
{
"cat":"Disney",
"ques":"What was the name of the male owner of Lady in Disney's Lady and the Tramp?",
"answ":"JIM DEAR",
"answ3":"JIM",
"answ2":"Jim Dear.",
"option":["Jim", "George", "Toby", "Daniel"],
},
{
"cat":"Disney",
"ques":"Who voiced Duchess in Disney's The Aristocats?",
"answ":"EVA GABOR",
"answ2":"Eva Gabor.",
"option":["Eva Gabor", "Jane Fonda", "Zsa Zsa Gabor", "Ursula Andress"],
},
{
"cat":"Disney",
"ques":"What is the name of the jealous butler in Disney's The Aristocats?",
"answ":"EDGAR",
"answ2":"Edgar.",
"option":["Edgar", "Alistair", "Toby", "Thomas"],
},
{
"cat":"Disney",
"ques":"What is the name of young girl who adopts Oliver in Disney's Oliver & Company?",
"answ":"JENNY",
"answ2":"Jenny.",
"option":["Jenny", "Oliva", "Penny", "Michelle"],
},
{
"cat":"Disney",
"ques":"What is the name of the prize-winning poodle the lives in the home that adopts Oliver in Disney's Oliver & Company?",
"answ":"GEORGETTE",
"answ2":"Georgette.",
"option":["Georgette", "Oliva", "Bette", "Cocoa"],
},
{
"cat":"Disney",
"ques":"Who voices the poodle Georgette in Disney's Oliver & Company?",
"answ":"BETTE MIDLER",
"answ2":"Bette Midler.",
"option":["Bette Midler", "Meryl Streep", "Reba McEntire", "Barbra Streisand"],
},
{
"cat":"Disney",
"ques":"What is name of the bat henchman in Disney's The Great Mouse Detective?",
"answ":"FIDGET",
"answ2":"Fidget.",
"option":["Fidget", "Wingnut", "Figwit", "Batty"],
},
{
"cat":"Disney",
"ques":"What is the name of the Doctor that assists Basil in his investigation in Disney's The Great Mouse Detective?",
"answ":"DR DAWSON",
"answ3":"DAWSON",
"answ2":"Dr. Dawson.",
"option":["Dr. Dawson", "Dr. Nelson", "Dr. Watson", "Dr. Mason"],
},
{
"cat":"Disney",
"ques":"What is the name of the girl who seeks out Basil's help in Disney's The Great Mouse Detective?",
"answ":"OLIVIA",
"answ2":"Olivia.",
"option":["Olivia", "Jenny", "Penny", "Chelsea"],
},
{
"cat":"Disney",
"ques":"What is the name of Sherlock's dog that Basil often goes to for help when tracking down a suspect in Disney's The Great Mouse Detective?",
"answ":"TOBY",
"answ2":"Toby.",
"option":["Toby", "Spot", "Max", "Lucky"],
},
{
"cat":"Disney",
"ques":"What is the name of Ratigan's pet cat that he uses to dispose of traitors in Disney's The Great Mouse Detective?",
"answ":"FELICIA",
"answ2":"Felicia.",
"option":["Felicia", "Felicity", "Olivia", "Duchess"],
},
{
"cat":"Disney",
"ques":"What is the name of the debonair kangaroo mouse in Disney's The Rescuers Down Under?",
"answ":"JAKE",
"answ2":"Jake.",
"option":["Jake", "Billy", "Mike", "Nick"],
},
{
"cat":"Disney",
"ques":"What is the name of the poacher in Disney's The Rescuers Down Under?",
"answ":"MCLEACH",
"answ3":"PERCIVAL C MCLEACH",
"answ2":"McLeach.",
"option":["McLeach", "Alameda Slim", "Gaston", "Clayton"],
},
{
"cat":"Disney",
"ques":"What is the name of McLeach's pet goanna in Disney's The Rescuers Down Under?",
"answ":"JOANNA",
"answ2":"Joanna.",
"option":["Joanna", "Gia", "Medusa", "Jana"],
},
{
"cat":"Disney",
"ques":"What is the name of the boy who was taken prisoner by the poacher in Disney's The Rescuers Down Under?",
"answ":"CODY",
"answ2":"Cody.",
"option":["Cody", "Chris", "Mark", "Tim"],
},
];
disney = shuffle(disney);
r2Q17 = shuffle(r2Q17);