var twopointer = [
{
"cat":"Mystery",
"ques":"In what comedic mystery film does Tim Curry say the line: 'We're trying to find out who killed him, and where, and with what'?",
"answ":"CLUE",
"answ2":"Clue.",
},
{
"cat":"Wizarding World",
"ques":"At the end of Harry Potter and the Deathly Hallows Part 1, which character kills Dobby the House Elf?",
"answ":"BELLATRIX LESTRANGE",
"answ2":"Bellatrix Lestrange.",
},
{
"cat":"Star Trek",
"ques":"Which Star Trek film features Patrick Stewart, Jonathan Frakes, F. Murray Abraham and Donna Murphy?",
"answ":"STAR TREK INSURRECTION",
"answ2":"Star Trek: Insurrection.",
},
{
"cat":"Nicolas Cage",
"ques":"What 2003 drama about a young male street hustler, is the only film that Nicolas Cage directed?",
"answ":"SONNY",
"answ2":"Sonny.",
},
{
"cat":"Martial Arts",
"ques":"Who starred in 1985's The Protector, as well as the 2000s films The Medallion and The Forbidden Kingdom?",
"answ":"JACKIE CHAN",
"answ2":"Jackie Chan.",
},
{
"cat":"Stephen King",
"ques":"What is the profession of the protagonist Paul Sheldon in 1990's Misery?",
"answ":"NOVELIST",
"answ3":"WRITER",
"answ2":"Novelist/Writer.",
},
{
"cat":"Reese Witherspoon",
"ques":"Reese Witherspoon plays Deputy District attorney Penny Kimball in what 2014 Paul Thomas Anderson film?",
"answ":"INHERENT VICE",
"answ2":"Inherent Vice.",
},
{
"cat":"Reese Witherspoon",
"ques":"Which actress plays the title character, opposite Reese Witherspoon, in the 2006 romantic fantasy Penelope?",
"answ":"CHRISTINA RICCI",
"answ2":"Christina Ricci .",
},
{
"cat":"Matt & Ben",
"ques":"Before playing Batman, Ben Affleck had portrayed what other comic books superhero?",
"answ":"DAREDEVIL",
"answ2":"Daredevil.",
},
{
"cat":"Matt & Ben",
"ques":"Which actress co-stars with Matt Damon in the film We Bought A Zoo as the lead zookeeper Kelly Foster?",
"answ":"SCARLETT JOHANSSON",
"answ2":"Scarlett Johansson.",
},
{
"cat":"Matt & Ben",
"ques":"How many Oscars has Matt Damon won?",
"answ":"1",
"answ3":"ONE",
"answ2":"1.",
},
{
"cat":"Sean Connery",
"ques":"Sean Connery plays the immortal character Juan Sánchez-Villalobos Ramírez in what 80s film?",
"answ":"HIGHLANDER",
"answ2":"Highlander.",
},
{
"cat":"Sean Connery",
"ques":"Who directed Sean Connery in the films The Hill, The Anderson Tapes and Family Business?",
"answ":"SIDNEY LUMET",
"answ2":"Sidney Lumet.",
},
{
"cat":"Sean Connery",
"ques":"Sean Connery appears in which 80s film from director Terry Gilliam?",
"answ":"TIME BANDITS",
"answ2":"Time Bandits.",
},
{
"cat":"Sean Connery",
"ques":"Sean Connery appears opposite Andy Garcia, Billy Drago and Patricia Clarkson in what action-thriller?",
"answ":"THE UNTOUCHABLES",
"answ2":"The Untouchables.",
},
{
"cat":"Sean Connery",
"ques":"Who directed the 2000 drama Finding Forrester?",
"answ":"GUS VAN SANT",
"answ2":"Gus Van Sant.",
},
{
"cat":"Sean Connery",
"ques":"Which actor plays Adso, the teenage apprentice of Sean Connery's character in 1986's The Name Of The Rose?",
"answ":"CHRISTIAN SLATER",
"answ2":"Christian Slater.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris plays Detective Sergeant Remy Bressant in what 2007 crime thriller?",
"answ":"GONE BABY GONE",
"answ2":"Gone Baby Gone.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris received a Best Supporting Actor nomination for which film in which he co-starred with Meryl Streep and Nicole Kidman?",
"answ":"THE HOURS",
"answ2":"The Hours.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris is heard as the voice of Mission Control in what 2013 sci-fi film?",
"answ":"GRAVITY",
"answ2":"Gravity.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris co-stars with Julia Roberts in what 1990s tearjerker?",
"answ":"STEPMOM",
"answ2":"Stepmom.",
},
{
"cat":"Ed Harris",
"ques":"John Schlesinger directed Ed Harris and Sally Field in what 1996 thriller?",
"answ":"EYE FOR AN EYE",
"answ2":"Eye for an Eye.",
},
{
"cat":"Remakes & Reboots",
"ques":"Which actor appeared in the 2000s remakes Planet Of The Apes, The Italian Job and The Departed?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
},
{
"cat":"Wizarding World",
"ques":"Peter Pettigrew can transform himself into what kind of animal?",
"answ":"RAT",
"answ2":"Rat.",
},
{
"cat":"Martial Arts",
"ques":"Who plays the lead role of taxi driver Jimmy Tong in the 2002 film The Tuxedo?",
"answ":"JACKIE CHAN",
"answ2":"Jackie Chan.",
},
{
"cat":"Lucasfilm",
"ques":"Who was a scriptwriter on Raiders of the Lost Ark, The Empire Strikes Back and Solo: A Star Wars Story?",
"answ":"LAWRENCE KASDAN",
"answ2":"Lawrence Kasdan.",
},
{
"cat":"Lucasfilm",
"ques":"Which Oscar winner plays Major Emanuel Stance, who commands African-American fighter pilots during World War II, in the film Red Tails?",
"answ":"CUBA GOODING JR",
"answ2":"Cuba Gooding Jr.",
},
{
"cat":"Lucasfilm",
"ques":"Bill L. Norton directed what 1979 film for Lucasfilm that featured Cindy Williams, Scott Glenn and Harrison Ford?",
"answ":"MORE AMERICAN GRAFFITI",
"answ2":"More American Graffiti.",
},
{
"cat":"Lucasfilm",
"ques":"What 1988 biopic was the only Lucasfilm production that was directed by Francis Ford Coppola?",
"answ":"TUCKER THE MAN AND HIS DREAM",
"answ2":"Tucker: The Man and His Dream.",
},
{
"cat":"Star Trek",
"ques":"Who directed 2016's Star Trek Beyond?",
"answ":"JUSTIN LIN",
"answ2":"Justin Lin.",
},
{
"cat":"Star Trek",
"ques":"Which Star Trek film has the tagline: 'Two Captains. One Destiny.'?",
"answ":"STAR TREK GENERATIONS",
"answ2":"Star Trek Generations.",
},
{
"cat":"Star Trek",
"ques":"Brent Spiner plays two androids, Data and B-4 in which Star Trek film?",
"answ":"STAR TREK NEMESIS",
"answ2":"Star Trek Nemesis.",
},
{
"cat":"John Hughes",
"ques":"Which John Hughes film has the line: 'Life moves pretty fast, if you don't stop and look around once in a while, you could miss it'?",
"answ":"FERRIS BUELLER'S DAY OFF",
"answ3":"FERRIS BUELLERS DAY OFF",
"answ2":"Ferris Bueller's Day Off.",
},
{
"cat":"Charlize Theron",
"ques":"Who plays Charlize Theron's husband in the sci-fi drama The Astronaut's Wife?",
"answ":"JOHNNY DEPP",
"answ2":"Johnny Depp.",
},
{
"cat":"Charlize Theron",
"ques":"In A Million Ways to Die in the West, who plays the main villain, the notorious outlaw Clint Leatherwood?",
"answ":"LIAM NEESON",
"answ2":"Liam Neeson.",
},
{
"cat":"Charlize Theron",
"ques":"Who directed 2017's The Fate of the Furious?",
"answ":"F GARY GRAY",
"answ2":"F. Gary Gray.",
},
{
"cat":"Charlize Theron",
"ques":"What 2018 action comedy stars Charlize Theron, Joel Edgerton and David Oyelowo?",
"answ":"GRINGO",
"answ2":"Gringo.",
},
{
"cat":"Paul Newman",
"ques":"Paul Newman provides the voice of Doc Hudson in which animated film?",
"answ":"CARS",
"answ2":"Cars.",
},
{
"cat":"Paul Newman",
"ques":"Which famous actress plays the character Maggie, opposite Paul Newman, in the 1958 classic Cat On A Hot Tin Roof?",
"answ":"ELIZABETH TAYLOR",
"answ2":"Elizabeth Taylor.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"What courtroom drama is known for the line: 'You can't handle the truth'?",
"answ":"A FEW GOOD MEN",
"answ2":"A Few Good Men.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"Who directed John Grisham's 1995 adaptation of The Rainmaker?",
"answ":"FRANCIS FORD COPPOLA",
"answ2":"Francis Ford Coppola.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"In Kramer vs Kramer, Dustin Hoffman plays Ted Kramer. Who plays Joanna Kramer?",
"answ":"MERYL STREEP",
"answ2":"Meryl Streep.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"Which 1957 Billy Wilder courtroom drama was based on a story by Agatha Christie?",
"answ":"WITNESS FOR THE PROSECUTION",
"answ2":"Witness for the Prosecution.",
},
{
"cat":"Robert De Niro",
"ques":"Which comedic actor plays a gangster named Frank Milo, opposite Robert De Niro in 1993's Mad Dog and Glory?",
"answ":"BILL MURRAY",
"answ2":"Bill Murray.",
},
{
"cat":"Robert De Niro",
"ques":"Who directed Robert De Niro in the 2001 heist film The Score?",
"answ":"FRANK OZ",
"answ2":"Frank Oz.",
},
{
"cat":"Robert De Niro",
"ques":"What is the profession of Robert De Niro's character Jack Walsh in the action-comedy Midnight Run?",
"answ":"BOUNTY HUNTER",
"answ2":"Bounty Hunter.",
},
{
"cat":"Robert De Niro",
"ques":"Who directed the 1990 drama Awakenings starring Robert De Niro and Robin Williams?",
"answ":"PENNY MARSHALL",
"answ2":"Penny Marshall.",
},
{
"cat":"Robert Redford",
"ques":"In what comic book movie does Robert Redford first play the character Alexander Pierce?",
"answ":"CAPTAIN AMERICA THE WINTER SOLDIER",
"answ3":"THE WINTER SOLDIER",
"answ2":"Captain America: The Winter Soldier.",
},
{
"cat":"Robert Redford",
"ques":"Which actress stars as Grace, the daughter of Robert Redford's character in 2016's Pete's Dragon?",
"answ":"BRYCE DALLAS HOWARD",
"answ2":"Bryce Dallas Howard.",
},
{
"cat":"Robert Redford",
"ques":"In what 2000s drama does Robert Redford play a court-martialed General who rallies other inmates against a corrupt warden?",
"answ":"THE LAST CASTLE",
"answ3":"LAST CASTLE",
"answ2":"The Last Castle.",
},
{
"cat":"Robert Redford",
"ques":"Robert Redford made his directorial debut with what 1980 family drama, which won the Best Picture Oscar?",
"answ":"ORDINARY PEOPLE",
"answ2":"Ordinary People.",
},
{
"cat":"Anne Hathaway",
"ques":"In what 2004 fantasy rom-com does Anne Hathaway play Ella of Frell?",
"answ":"ELLA ENCHANTED",
"answ2":"Ella Enchanted.",
},
{
"cat":"Anne Hathaway",
"ques":"What 2005 film marks the first time Anne Hathaway lent her voice to an American animated film?",
"answ":"HOODWINKED",
"answ2":"Hoodwinked.",
},
{
"cat":"Anne Hathaway",
"ques":"Anne Hathaway plays Agent 99 in what 2008 action spy comedy?",
"answ":"GET SMART",
"answ2":"Get Smart.",
},
{
"cat":"Anne Hathaway",
"ques":"Which actress co-stars as Anne Hathaway's best friend in the comedy Bride Wars?",
"answ":"KATE HUDSON",
"answ2":"Kate Hudson.",
},
{
"cat":"Amy Adams",
"ques":"Who plays Amy Adams' sister in the 2008 dramedy Sunshine Cleaning?",
"answ":"EMILY BLUNT",
"answ2":"Emily Blunt.",
},
{
"cat":"Amy Adams",
"ques":"Amy Adams received her first Oscar nomination for what 2000s film?",
"answ":"JUNEBUG",
"answ2":"Junebug.",
},
{
"cat":"Amy Adams",
"ques":"Which Walking Dead actor plays Al Capone in Night at the Museum: Battle of the Smithsonian?",
"answ":"JON BERNTHAL",
"answ3":"JOHN BERNTHAL",
"answ2":"Jon Bernthal.",
},
{
"cat":"Mystery",
"ques":"Jared Harris plays the literary criminal Professor Moriarty in what 2011 mystery movie-sequel?",
"answ":"SHERLOCK HOLMES A GAME OF SHADOWS",
"answ3":"SHERLOCK HOLMES GAME OF SHADOWS",
"answ2":"Sherlock Holmes: A Game of Shadows.",
},
{
"cat":"Jodie Foster",
"ques":"Jodie Foster plays card-playing con artist Mrs. Annabelle Bransford in what 1994 western?",
"answ":"MAVERICK",
"answ2":"Maverick.",
},
{
"cat":"Jodie Foster",
"ques":"Jodie foster plays a character called the Nurse, who runs a secret emergency room for criminals in what 2018 film?",
"answ":"HOTEL ARTEMIS",
"answ2":"Hotel Artemis.",
},
{
"cat":"Jodie Foster",
"ques":"This Neill Blomkamp film starred Jodie Foster and Matt Damon?",
"answ":"ELYSIUM",
"answ2":"Elysium.",
},
{
"cat":"Stephen King",
"ques":"What is the name of the titular killer St. Bernard in the 1983 movie based on a novel by Stephen King?",
"answ":"CUJO",
"answ2":"Cujo.",
},
{
"cat":"Reese Witherspoon",
"ques":"Reese Witherspoon won an Oscar for what 2005 biopic?",
"answ":"WALK THE LINE",
"answ2":"Walk the Line.",
},
{
"cat":"Reese Witherspoon",
"ques":"Who plays Jake, the estranged husband of Reese Witherspoon's character in the rom-com Sweet Home Alabama?",
"answ":"JOSH LUCAS",
"answ2":"Josh Lucas.",
},
{
"cat":"Reese Witherspoon",
"ques":"Which actor plays Brad, the male lead in the comedy Four Christmases?",
"answ":"VINCE VAUGHN",
"answ2":"Vince Vaughn.",
},
{
"cat":"Star Trek",
"ques":"What is the name of the third Star Trek film to star the cast of Star Trek: The Next Generation?",
"answ":"STAR TREK INSURRECTION",
"answ3":"INSURRECTION",
"answ2":"Star Trek: Insurrection.",
},
{
"cat":"Star Trek",
"ques":"Who played Dr. McCoy in Star Trek: The Motion Picture?",
"answ":"DEFOREST KELLEY",
"answ3":"DEFORREST KELLEY",
"answ2":"DeForest Kelley.",
},
{
"cat":"Star Trek",
"ques":"In 2009's Star Trek, who is Captain of the Enterprise when it first sets off into space?",
"answ":"CHRISTOPHER PIKE",
"answ3":"PIKE",
"answ2":"Christopher Pike.",
},
{
"cat":"Star Trek",
"ques":"What song did Jaylah use to jam and disorient the swarm ships in Star Trek Beyond at the end of the film?",
"answ":"SABOTAGE",
"answ2":"Sabotage.",
},
{
"cat":"Harrison Ford",
"ques":"In The Call of the Wild, what is the name of the gentle St. Bernard mix dog that the film revolves around?",
"answ":"BUCK",
"answ2":"Buck.",
},
{
"cat":"Harrison Ford",
"ques":"What Oscar nominated actress plays Sarah Turner, Ford's wife in the 1991 film Regarding Henry?",
"answ":"ANNETTE BENING",
"answ3":"ANNETTE BENNING",
"answ2":"Annette Bening.",
},
{
"cat":"Sean Connery",
"ques":"Sean Connery won an Oscar for portraying the character Jimmy Malone in what film?",
"answ":"THE UNTOUCHABLES",
"answ2":"The Untouchables.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris plays the character Christof, in what 90s film that stars Jim Carrey?",
"answ":"THE TRUMAN SHOW",
"answ3":"TRUMAN SHOW",
"answ2":"The Truman Show.",
},
{
"cat":"Ed Harris",
"ques":"Which actress won an Oscar for the films Pollock, which Ed Harris starred in and directed?",
"answ":"MARCIA GAY HARDEN",
"answ2":"Marcia Gay Harden.",
},
{
"cat":"Ed Harris",
"ques":"Which Oscar winning actor played the villainous rancher Randall Bragg in the western Appaloosa?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
},
{
"cat":"Ed Harris",
"ques":"Ed Harris played which famous real-life astronaut in 1983's The Right Stuff?",
"answ":"JOHN GLENN",
"answ2":"John Glenn.",
},
{
"cat":"Francis Ford Coppola",
"ques":"Who plays the title character in 1986's Peggy Sue Got Married?",
"answ":"KATHLEEN TURNER",
"answ2":"Kathleen Turner.",
},
{
"cat":"Francis Ford Coppola",
"ques":"Francis Ford Coppola directed what 90s legal thriller based on a John Grisham novel which stars Matt Damon?",
"answ":"THE RAINMAKER",
"answ2":"The Rainmaker.",
},
{
"cat":"Francis Ford Coppola",
"ques":"Who plays the main female character Mina Harker in Bram Stoker's Dracula?",
"answ":"WINONA RYDER",
"answ2":"Winona Ryder.",
},
{
"cat":"Francis Ford Coppola",
"ques":"Which actor plays a character only known as The Motorcycle Boy in 1983's Rumble Fish?",
"answ":"MICKEY ROURKE",
"answ2":"Mickey Rourke.",
},
{
"cat":"Francis Ford Coppola",
"ques":"Laurence Fishburne had an early role as Tyrone 'Clean' Miller in which 1970s Coppola film?",
"answ":"APOCALYPSE NOW",
"answ2":"Apocalypse Now.",
},
{
"cat":"Frank Capra",
"ques":"Which legendary crooner stars in the 1959 Frank Capra comedy A Hole In The Head?",
"answ":"FRANK SINATRA",
"answ2":"Frank Sinatra.",
},
{
"cat":"Frank Capra",
"ques":"Which Frank Capra film follows a naive man who is appointed to the U.S. Senate and soon collides with political corruption?",
"answ":"MR SMITH GOES TO WASHINGTON",
"answ2":"Mr. Smith Goes To Washington.",
},
{
"cat":"Frank Capra",
"ques":"Which famous crooner stars as the character Dan Brooks in the 1950 comedy Riding High?",
"answ":"BING CROSBY",
"answ2":"Bing Crosby.",
},
{
"cat":"Frank Capra",
"ques":"Which famous actor starred as a wealthy young man named Tony Kirby in 1938's You Can't Take It With You?",
"answ":"JAMES STEWART",
"answ3":"JIMMY STEWART",
"answ2":"James Stewart.",
},
{
"cat":"Frank Capra",
"ques":"What famously blonde actress starred as the character Ann in the 1931 Frank Capra film Platinum Blonde?",
"answ":"JEAN HARLOW",
"answ2":"Jean Harlow.",
},
{
"cat":"Frank Capra",
"ques":"Which 1934 Frank Capra film won 5 Oscars, including Best Picture, Best Director, Best Actor and Best Actress?",
"answ":"IT HAPPENED ONE NIGHT",
"answ2":"It Happened One Night.",
},
{
"cat":"Frank Capra",
"ques":"Frank Capra received his first Best Director nomination for what comedic film which was released in 1933?",
"answ":"LADY FOR A DAY",
"answ2":"Lady For A Day.",
},
{
"cat":"Frank Capra",
"ques":"In which Frank Capra drama does Ronald Colman star as a diplomat who discovers the enchanted city of Shangri-La after a plane crash?",
"answ":"LOST HORIZON",
"answ2":"Lost Horizon.",
},
{
"cat":"Martial Arts",
"ques":"What Hong Kong filmmaker made his American directorial debut with the 1993 film Hard Target?",
"answ":"JOHN WOO",
"answ2":"John Woo.",
},
{
"cat":"Martial Arts",
"ques":"Who plays Detective James Carter, a fast talking street-smart LAPD Detective in the Rush Hour trilogy?",
"answ":"CHRIS TUCKER",
"answ2":"Chris Tucker.",
},
{
"cat":"Mystery",
"ques":"Casey Affleck and Michelle Monaghan play a couple who are professional private detectives in what 2007 film?",
"answ":"GONE BABY GONE",
"answ2":"Gone Baby Gone.",
},
{
"cat":"Matt & Ben",
"ques":"Matt Damon received his first acting Oscar nomination for which film?",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
},
{
"cat":"Martial Arts",
"ques":"Who plays the character Tang Lung in 1972's The Way Of The Dragon?",
"answ":"BRUCE LEE",
"answ2":"Bruce Lee.",
},
{
"cat":"Martial Arts",
"ques":"Who plays the lead role of Ting in Ong-Bak: The Thai Warrior?",
"answ":"TONY JAA",
"answ2":"Tony Jaa.",
},
{
"cat":"Martial Arts",
"ques":"Which Oscar winning actress plays the lead role of Julie Pierce in The Next Karate Kid?",
"answ":"HILARY SWANK",
"answ2":"Hilary Swank.",
},
{
"cat":"Martial Arts",
"ques":"What 1974 film starred Sonny Chiba as Terry, a mercenary karate master and was the first film in a popular franchise?",
"answ":"THE STREET FIGHTER",
"answ3":"STREET FIGHTER",
"answ2":"The Street Fighter.",
},
{
"cat":"Martial Arts",
"ques":"Which 2000s movie franchise has a main character named Chon Wang?",
"answ":"SHANGHAI NOON",
"answ2":"Shanghai Noon.",
},
{
"cat":"Mel Brooks",
"ques":"Who plays Mel Brooks' biggest rival, Vance Crasswell, in Life Stinks?",
"answ":"JEFFREY TAMBOR",
"answ2":"Jeffrey Tambor.",
},
{
"cat":"Mel Brooks",
"ques":"Who directed Mel Brooks and Anne Bancroft in To Be Or Not To Be?",
"answ":"ALAN JOHNSON",
"answ2":"Alan Johnson.",
},
{
"cat":"Mel Brooks",
"ques":"Mel Brooks makes a voice appearance in what Pixar film as a character named Melephant Brooks?",
"answ":"TOY STORY 4",
"answ2":"Toy Story 4.",
},
{
"cat":"Mel Brooks",
"ques":"Who has a cameo as the musical director Buddy Bizarre in 1974's Blazing Saddles?",
"answ":"DOM DELUISE",
"answ2":"Dom DeLuise.",
},
{
"cat":"Mel Brooks",
"ques":"Who plays Marty Eggs, one of Mel Funn's sidekicks who pitches the first silent film in 40 years to a Hollywood studio head in Silent Movie?",
"answ":"MARTY FELDMAN",
"answ2":"Marty Feldman.",
},
{
"cat":"Mel Brooks",
"ques":"Who plays the role of S.S. Colonel Erhardt in 1983's To Be Or Not To Be?",
"answ":"CHARLES DURNING",
"answ2":"Charles Durning.",
},
{
"cat":"Stephen King",
"ques":"Who plays the role of Selena St. George as an adult in the film Dolores Claiborne?",
"answ":"JENNIFER JASON LEIGH",
"answ2":"Jennifer Jason Leigh.",
},
{
"cat":"Tyler Perry",
"ques":"Tyler Perry plays lawyer Tanner Bolt in what 2014 thriller?",
"answ":"GONE GIRL",
"answ2":"Gone Girl.",
},
{
"cat":"James Stewart",
"ques":"The 1938 Best Picture winner You Can't Take It With You was James Stewart's first collaboration with what famous director?",
"answ":"FRANK CAPRA",
"answ2":"Frank Capra.",
},
{
"cat":"James Stewart",
"ques":"Which actress starred as a witch opposite James Stewart in the 1958 rom-com Bell, Book and Candle?",
"answ":"KIM NOVAK",
"answ2":"Kim Novak.",
},
{
"cat":"James Stewart",
"ques":"In what 1950 western does James Stewart play Lin McAdam, a cowboy whose obsession with a stolen rifle leads to a bullet-ridden odyssey?",
"answ":"WINCHESTER 73",
"answ3":"WINCHESTER '73",
"answ2":"Winchester '73.",
},
{
"cat":"James Stewart",
"ques":"What is the profession of James Stewart's character Paul Biegler in the 1959 crime drama Anatomy Of A Murder?",
"answ":"LAWYER",
"answ2":"Lawyer.",
},
{
"cat":"Kurt Russell",
"ques":"In what 90s western does Kurt Russell say: 'You tell 'em I'm coming... and hell's coming with me, you hear. Hell's coming with me!'?",
"answ":"TOMBSTONE",
"answ2":"Tombstone.",
},
{
"cat":"Judd Apatow",
"ques":"Which actress plays Margie, the mother of Pete Davidson's character in The King Of Staten Island?",
"answ":"MARISA TOMEI",
"answ2":"Marisa Tomei.",
},
{
"cat":"Remakes & Reboots",
"ques":"What 2000 crime film starred Sylvester Stallone, and was a remake of a 1971 Michael Caine film?",
"answ":"GET CARTER",
"answ2":"Get Carter.",
},
{
"cat":"SNL Movies",
"ques":"Which comedian plays a version of herself in the 1994 film It's Pat?",
"answ":"KATHY GRIFFIN",
"answ3":"CATHY GRIFFIN",
"answ2":"Kathy Griffin.",
},
{
"cat":"SNL Movies",
"ques":"In Coneheads, which actress plays Prymaat Conehead who is married to Beldar?",
"answ":"JANE CURTIN",
"answ2":"Jane Curtin.",
},
{
"cat":"SNL Movies",
"ques":"In Wayne's World, Wayne and Garth host a public access show that is on what number tv channel?",
"answ":"10",
"answ3":"CHANNEL 10",
"answ2":"10.",
},
{
"cat":"SNL Movies",
"ques":"In Stuart Saves His Family, Stuart Smalley had been hit by a car as a child, while his family was trying to take a photo in front of what famous landmark?",
"answ":"HOLLYWOOD SIGN",
"answ3":"THE HOLLYWOOD SIGN",
"answ2":"Hollywood Sign.",
},
{
"cat":"Stephen King",
"ques":"What film based on a Stephen King novel features performances by Nancy Allen, Piper Laurie and John Travolta?",
"answ":"CARRIE",
"answ2":"Carrie.",
},
{
"cat":"Teenage Mutant Ninja Turtles",
"ques":"How many total Teenage Mutant Ninja Turtles films have been released to date?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
},
{
"cat":"Halle Berry",
"ques":"Halle Berry plays the character Sofia Al-Azwar in what action movie franchise?",
"answ":"JOHN WICK",
"answ3":"JOHN WICK CHAPTER 3 PARABELLUM",
"answ2":"John Wick.",
},
{
"cat":"Halle Berry",
"ques":"Halle Berry plays the character Miss Stone in what live-action 1994 family film based on a TV cartoon?",
"answ":"THE FLINTSTONES",
"answ2":"The Flintstones.",
},
{
"cat":"Halle Berry",
"ques":"Halle Berry made her movie debut in which film from director Spike Lee?",
"answ":"JUNGLE FEVER",
"answ2":"Jungle Fever.",
},
{
"cat":"Halle Berry",
"ques":"What is the first name of Halle Berry's character in the film Catwoman?",
"answ":"PATIENCE",
"answ2":"Patience.",
},
{
"cat":"John Hughes",
"ques":"What 1984 teen comedy marked John Hughes directorial debut?",
"answ":"SIXTEEN CANDLES",
"answ2":"Sixteen Candles.",
},
{
"cat":"Jim Carrey",
"ques":"In what film does Jim Carrey play the character Joel Barrish, a man dealing with a painful breakup?",
"answ":"ETERNAL SUNSHINE OF THE SPOTLESS MIND",
"answ2":"Eternal Sunshine of the Spotless Mind.",
},
{
"cat":"Kevin Hart",
"ques":"Which actress plays Kevin Hart's love interest Joan in the 2014 rom-com About Last Night?",
"answ":"REGINA HALL",
"answ2":"Regina Hall.",
},
{
"cat":"Kevin Hart",
"ques":"Kevin Hart has a cameo as an air marshall in what film in the Fast and Furious franchise?",
"answ":"HOBBS AND SHAW",
"answ2":"Hobbs & Shaw.",
},
{
"cat":"Kevin Hart",
"ques":"Who directed the 2017 film The Upside?",
"answ":"NEIL BURGER",
"answ2":"Neil Burger.",
},
{
"cat":"Modern Classics",
"ques":"Who plays Sergeant Mike Horvath, who answers directly to Tom Hanks' character on their mission to find Ryan in Saving Private Ryan?",
"answ":"TOM SIZEMORE",
"answ2":"Tom Sizemore.",
},
{
"cat":"Martial Arts",
"ques":"Who stars as FBI agent John Crawford, opposite Jet Li in the 2007 film War?",
"answ":"JASON STATHAM",
"answ2":"Jason Statham.",
},
{
"cat":"Martial Arts",
"ques":"What 2000s martial arts epic involves a sword called the 'Green Destiny'?",
"answ":"CROUCHING TIGER HIDDEN DRAGON",
"answ2":"Crouching Tiger, Hidden Dragon.",
},
{
"cat":"Martial Arts",
"ques":"Who starred in and directed the 2005 martial arts comedy Kung Fu Hustle?",
"answ":"STEPHEN CHOW",
"answ2":"Stephen Chow.",
},
{
"cat":"Martial Arts",
"ques":"Who starred as himself in hte 1992 martial arts family film Sidekicks?",
"answ":"CHUCK NORRIS",
"answ2":"Chuck Norris.",
},
{
"cat":"Wizarding World",
"ques":"What enchanted instrument puts the terrifying three-headed dog to sleep in Harry Potter and the Philosopher's Stone?",
"answ":"HARP",
"answ3":"A HARP",
"answ2":"Harp.",
},
{
"cat":"Wizarding World",
"ques":"Who took on the post of Potions Master at Hogwarts in The Half-Blood Prince?",
"answ":"PROFESSOR SLUGHORN",
"answ3":"HORACE SLUGHORN",
"answ2":"Professor Slughorn.",
},
{
"cat":"Wizarding World",
"ques":"Who plays Professor Lupin in the Harry Potter series?",
"answ":"DAVID THEWLIS",
"answ2":"David Thewlis.",
},
{
"cat":"Wizarding World",
"ques":"Who directed Harry Potter and the Goblet of Fire?",
"answ":"MIKE NEWELL",
"answ2":"Mike Newell.",
},
{
"cat":"Eddie Murphy",
"ques":"What 90s Eddie Murphy film featuring Martin Lawrence has the tagline: 'A player who's about to be played'?",
"answ":"BOOMERANG",
"answ2":"Boomerang.",
},
{
"cat":"Eddie Murphy",
"ques":"Who plays the lead role of Josh Kovaks alongside Eddie Murphy and Matthew Broderick in the film Tower Heist?",
"answ":"BEN STILLER",
"answ2":"Ben Stiller.",
},
{
"cat":"Remakes & Reboots",
"ques":"What 2014 remake of a 1980s romance movie stars Gabriella Wilde, Alex Pettyfer and Bruce Greenwood?",
"answ":"ENDLESS LOVE",
"answ2":"Endless Love.",
},
{
"cat":"Matt & Ben",
"ques":"Who directed The Bourne Ultimatum?",
"answ":"PAUL GREENGRASS",
"answ2":"Paul Greengrass.",
},
{
"cat":"Matt & Ben",
"ques":"In Stuck On You, conjoined twins Bob and Walt run what type of establishment?",
"answ":"RESTAURANT",
"answ2":"Restaurant.",
},
{
"cat":"Matt & Ben",
"ques":"Which actress plays Ben Affleck's love interest in the drama Bounce?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
},
{
"cat":"Matt & Ben",
"ques":"Which actor plays mathematics professor Gerald Lambeau in Good Will Hunting?",
"answ":"STELLAN SKARSGARD",
"answ2":"Stellan Skarsgard.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"Which Oscar winning actor co-stars with Ryan Gosling in 2007's Fracture?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"Jeremy Irons won a Best Actor Oscar for playing real-life murder defendant Claus Von Bulow in what film?",
"answ":"REVERSAL OF FORTUNE",
"answ2":"Reversal of Fortune.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"Who directed 1993's The Firm?",
"answ":"SYDNEY POLLACK",
"answ3":"SIDNEY POLLACK",
"answ2":"Sydney Pollack.",
},
{
"cat":"Courtroom Dramas/Legal Thrillers",
"ques":"In what classic film does Henry Fonda play Abraham Lincoln when he was a trial lawyer, prior to taking up politics?",
"answ":"YOUNG MR LINCOLN",
"answ2":"Young Mr. Lincoln.",
},
{
"cat":"Nora Ephron",
"ques":"Who plays Manhattan food writer Rachel Samstat in the Nora Ephron penned film Heartburn?",
"answ":"MERYL STREEP",
"answ2":"Meryl Streep.",
},
{
"cat":"Nora Ephron",
"ques":"Nora Ephron made her directorial debut with what 1992 film?",
"answ":"THIS IS MY LIFE",
"answ2":"This Is My Life.",
},
{
"cat":"Nora Ephron",
"ques":"Which actress appeared in When Harry Met Sally and Hanging Up?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Whoopi Goldberg",
"ques":"Whoopi Goldberg had her first comedic leading role in what 1986 Penny Marshall film?",
"answ":"JUMPIN' JACK FLASH",
"answ3":"JUMPING JACK FLASH",
"answ2":"Jumpin' Jack Flash.",
},
{
"cat":"Whoopi Goldberg",
"ques":"In the 1996 film Eddie, Whoopi Goldberg plays a fan who becomes a coach of what professional sport?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
},
{
"cat":"Whoopi Goldberg",
"ques":"Who stars with Whoopi Goldberg in the 1996 courtroom drama Ghosts of Mississippi as real-life D.A. Bobby DeLaughter?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
},
{
"cat":"Brad Pitt",
"ques":"Who directed Brad Pitt in 2011's Moneyball?",
"answ":"BENNETT MILLER",
"answ2":"Bennett Miller.",
},
{
"cat":"Sigourney Weaver",
"ques":"Sigourney Weaver plays Louise Walker, a warden at the juvenile detention center Camp Green Lake in what 2003 film?",
"answ":"HOLES",
"answ2":"Holes.",
},
{
"cat":"Sigourney Weaver",
"ques":"Sigourney Weaver starred in Aliens and what other film from director James Cameron?",
"answ":"AVATAR",
"answ2":"Avatar.",
},
{
"cat":"Sigourney Weaver",
"ques":"Who co-stars with Sigourney Weaver as the title character in the 1993 comedy Dave?",
"answ":"KEVIN KLINE",
"answ2":"Kevin Kline.",
},
{
"cat":"Sigourney Weaver",
"ques":"What 1981 political thriller stars William Hurt, Sigourney Weaver and Christopher Plummer?",
"answ":"EYEWITNESS",
"answ3":"EYE WITNESS",
"answ2":"Eyewitness.",
},
{
"cat":"Mystery",
"ques":"Which Oscar winning actor plays the marble-mouthed criminal Freddie Fenster in The Usual Susppects?",
"answ":"BENICIO DEL TORO",
"answ2":"Benicio Del Toro.",
},
{
"cat":"Mystery",
"ques":"Who directed the 2019 film Knives Out?",
"answ":"RIAN JOHNSON",
"answ2":"Rian Johnson.",
},
{
"cat":"Mystery",
"ques":"What 1985 film from director Barry Levinson tells how the famous characters Sherlock Holmes and Dr. Watson first met?",
"answ":"YOUNG SHERLOCK HOLMES",
"answ2":"Young Sherlock Holmes.",
},
{
"cat":"Mystery",
"ques":"Which actress plays Emily, a wealthy young mother who mysteriously disappears in the 2018 film A Simple Favor?",
"answ":"BLAKE LIVELY",
"answ2":"Blake Lively.",
},
{
"cat":"Oprah Winfrey",
"ques":"Oprah Winfrey appeared in which film from director Steven Spielberg?",
"answ":"THE COLOR PURPLE",
"answ3":"COLOR PURPLE",
"answ2":"The Color Purple.",
},
{
"cat":"Oprah Winfrey",
"ques":"Who directed Oprah in the film Selma?",
"answ":"AVA DUVERNAY",
"answ2":"Ava DuVernay.",
},
{
"cat":"Oprah Winfrey",
"ques":"Oprah Winfey appears in what 1986 film from director Jerrold Freedman, which also stars Matt Dillon and Victor Love?",
"answ":"NATIVE SON",
"answ2":"Native Son.",
},
{
"cat":"Oprah Winfrey",
"ques":"Which comedic actress plays the character Mrs. Who, in the film A Wrinkle in Time?",
"answ":"MINDY KALING",
"answ2":"Mindy Kaling.",
},
{
"cat":"Superman",
"ques":"To date, how many times has Henry Cavill played Superman?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Superman",
"ques":"In Superman II, there is a hostage situation involving terrorists taking over what landmark?",
"answ":"EIFFEL TOWER",
"answ3":"THE EIFFEL TOWER",
"answ2":"The Eiffel Tower.",
},
{
"cat":"Superman",
"ques":"What is the name of Lex Luthor's company in Batman v. Superman?",
"answ":"LEXCORP",
"answ2":"LexCorp.",
},
{
"cat":"Superman",
"ques":"Who was credited as Superman's father Jor-El in Superman Returns?",
"answ":"MARLON BRANDO",
"answ2":"Marlon Brando.",
},
{
"cat":"Tyler Perry",
"ques":"Tyler Perry appears as politician, diplomat and general Colin Powell in what film?",
"answ":"VICE",
"answ2":"Vice.",
},
{
"cat":"Tyler Perry",
"ques":"Which Tyler Perry film has the tagline: 'Trick or Treat Fools'?",
"answ":"BOO! A MADEA HALLOWEEN",
"answ3":"BOO A MADEA HALLOWEEN",
"answ2":"Boo! A Madea Halloween.",
},
{
"cat":"Tyler Perry",
"ques":"Many of the films directed by Tyler Perry, including Meet The Browns, take place in what southern U.S. state?",
"answ":"GEORGIA",
"answ2":"Georgia.",
},
{
"cat":"Tyler Perry",
"ques":"Who plays the sadistic killer Picasso in the film Alex Cross?",
"answ":"MATTHEW FOX",
"answ2":"Matthew Fox.",
},
{
"cat":"Robert De Niro",
"ques":"Robert De Niro was first nominated for a Best Leading Actor Oscar for which Martin Scorsese film?",
"answ":"TAXI DRIVER",
"answ2":"Taxi Driver.",
},
{
"cat":"Robert De Niro",
"ques":"In which film does Robert De Niro plays Harry Tuttle, a terrorist who is trying to take down an oppressive government system?",
"answ":"BRAZIL",
"answ2":"Brazil.",
},
{
"cat":"Robert De Niro",
"ques":"Who directed Robert De Niro in the 1994 horror adaptation Mary Shelley's Frankenstein?",
"answ":"KENNETH BRANAGH",
"answ3":"KENNETH BRANAUGH",
"answ2":"Kenneth Branagh.",
},
{
"cat":"Robert De Niro",
"ques":"In which film does Robert De Niro say the line: 'Never rat on your friends and always keep your mouth shut'?",
"answ":"GOODFELLAS",
"answ2":"Goodfellas.",
},
{
"cat":"Leonardo DiCaprio",
"ques":"For what film did Leonardo DiCaprio receive his first acting Oscar nomination?",
"answ":"WHAT'S EATING GILBERT GRAPE",
"answ2":"What's Eating Gilbert Grape.",
},
{
"cat":"Emily Blunt",
"ques":"Emily Blunt co-stars with Joseph Gordon-Levitt in what film from director Rian Johnson?",
"answ":"LOOPER",
"answ2":"Looper.",
},
{
"cat":"Emily Blunt",
"ques":"Emily Blunt plays the female lead in what movie, which is a reboot of a Universal Monster property?",
"answ":"THE WOLFMAN",
"answ3":"THE WOLF MAN",
"answ2":"The Wolfman.",
},
{
"cat":"Emily Blunt",
"ques":"Emily Blunt has a cameo as Miss Piggy's assistant in which film that stars The Muppets?",
"answ":"THE MUPPETS",
"answ2":"The Muppets.",
},
{
"cat":"Emily Blunt",
"ques":"Emily Blunt's character works for what government agency at the beginning of Sicario, before being enlisted to a special ops task force?",
"answ":"FBI",
"answ2":"FBI.",
},
{
"cat":"Paul Thomas Anderson",
"ques":"Who plays adult actress Amber Waves in Boogie Nights?",
"answ":"JULIANNE MOORE",
"answ2":"Julianne Moore.",
},
{
"cat":"Keanu Reeves",
"ques":"What is the title of the 2020 entry in the Bill and Ted franchise?",
"answ":"BILL AND TED FACE THE MUSIC",
"answ3":"FACE THE MUSIC",
"answ2":"Bill & Ted Face the Music.",
},
{
"cat":"Paul Thomas Anderson",
"ques":"You'll find the characters of Reynolds and Cyril Woodcock in which Paul Thomas Anderson film?",
"answ":"PHANTOM THREAD",
"answ2":"Phantom Thread.",
},
{
"cat":"Paul Thomas Anderson",
"ques":"Freddie Quell is the main character in which Paul Thomas Anderson film?",
"answ":"THE MASTER",
"answ2":"The Master.",
},
{
"cat":"Frances McDormand",
"ques":"Frances McDormand received a Best Supporting Actress nomination for what 2000 film from director Cameron Crowe?",
"answ":"ALMOST FAMOUS",
"answ2":"Almost Famous.",
},
{
"cat":"Frances McDormand",
"ques":"Frances McDormand plays the mother of Suzy Bishop, a teen girl who goes on the run in what film?",
"answ":"MOONRISE KINGDOM",
"answ2":"Moonrise Kingdom.",
},
{
"cat":"Frances McDormand",
"ques":"Frances McDormand won the Best Actress Oscar twice, one for 3 Billboards Outside Ebbing Missiouri, and which other film?",
"answ":"FARGO",
"answ2":"Fargo.",
},
{
"cat":"Frances McDormand",
"ques":"Frances McDormand has a supporting role as the character Zoe in what rom-com that stars Jack Nicholson and Diane Keaton?",
"answ":"SOMETHING'S GOTTA GIVE",
"answ3":"SOMETHINGS GOTTA GIVE",
"answ2":"Something's Gotta Give.",
},
{
"cat":"Planet of the Apes",
"ques":"Who plays Charles Rodman, Will's Alzheimer-afflicted father in Rise of the Planet of the Apes?",
"answ":"JOHN LITHGOW",
"answ2":"John Lithgow.",
},
{
"cat":"Judd Apatow",
"ques":"Paul Rudd and Leslie Mann star in what 2012 Judd Apatow comedy?",
"answ":"THIS IS 40",
"answ3":"THIS IS FORTY",
"answ2":"This Is 40.",
},
{
"cat":"Planet of the Apes",
"ques":"Who plays Malcolm, the leader of a small group that forms a strong bond with Caesar in Dawn of the Planet of the Apes?",
"answ":"JASON CLARKE",
"answ3":"JASON CLARK",
"answ2":"Jason Clarke.",
},
{
"cat":"Planet of the Apes",
"ques":"What is the title of the fifth film in the original Planet of the Apes series?",
"answ":"BATTLE FOR THE PLANET OF THE APES",
"answ2":"Battle for the Planet of the Apes.",
},
{
"cat":"Mystery",
"ques":"Which Oscar winning actor plays Harlan Thrombey, patriarch of a dysfunctional upper class family in the film Knives Out?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
},
{
"cat":"Mystery",
"ques":"Ryan Gosling plays private detective Holland March in what 2016 film from director Shane Black?",
"answ":"THE NICE GUYS",
"answ3":"NICE GUYS",
"answ2":"The Nice Guys.",
},
{
"cat":"Mystery",
"ques":"Which actor plays Dr. John Watson in the 2009 film Sherlock Holmes?",
"answ":"JUDE LAW",
"answ2":"Jude Law.",
},
{
"cat":"Mystery",
"ques":"Which actor plays the character Professor Plum in the 1985 board-game adaptation Clue?",
"answ":"CHRISTOPHER LLOYD",
"answ3":"CHRISTOPHER LOYD",
"answ2":"Christopher Lloyd.",
},
{
"cat":"Mystery",
"ques":"Which actress stars as the character Caroline Hubbard in 2017's Murder on the Orient Express?",
"answ":"MICHELLE PFEIFFER",
"answ2":"Michelle Pfeiffer.",
},
{
"cat":"Mystery",
"ques":"Who played the character Sam Spade in the 1941 film The Maltese Falcon?",
"answ":"HUMPHREY BOGART",
"answ2":"Humphrey Bogart.",
},
{
"cat":"Mystery",
"ques":"Who plays the titular teenage detective in the 2007 family film Nancy Drew?",
"answ":"EMMA ROBERTS",
"answ2":"Emma Roberts.",
},
{
"cat":"Mystery",
"ques":"What mystery movie franchise features the characters Nick and Nora Charles?",
"answ":"THE THIN MAN",
"answ3":"THIN MAN",
"answ2":"The Thin Man.",
},
{
"cat":"Matt & Ben",
"ques":"Who directed Ben Affleck in The Accountant and The Way Back?",
"answ":"GAVIN O'CONNOR",
"answ3":"GAVIN O CONNOR",
"answ2":"Gavin O'Connor.",
},
{
"cat":"Stephen King",
"ques":"What 1989 adaptation of a Stephen King novel has the tagline: 'Sometimes dead is better.'?",
"answ":"PET SEMATARY",
"answ3":"PET SEMETARY",
"answ2":"Pet Sematary.",
},
{
"cat":"Stephen King",
"ques":"Which Stephen King adaptation features supporting performances from the actors Danny Lloyd, Barry Nelson and Tony Burton?",
"answ":"THE SHINING",
"answ2":"The Shining.",
},
{
"cat":"Stephen King",
"ques":"Who stars as a young girl with pyro-kinetic powers in 1984's Firestarter?",
"answ":"DREW BARRYMORE",
"answ2":"Drew Barrymore.",
},
{
"cat":"Stephen King",
"ques":"What famous horror director helmed the 1993 Stephen King adaptation The Dark Half?",
"answ":"GEORGE A ROMERO",
"answ3":"GEORGE ROMERO",
"answ2":"George A. Romero.",
},
{
"cat":"Stephen King",
"ques":"Who plays Jud Crandall, neighbor of the Creed family, in 1989's Pet Sematary?",
"answ":"FRED GWYNNE",
"answ3":"FRED GWYNE",
"answ2":"Fred Gwynne.",
},
{
"cat":"Stephen King",
"ques":"Which Stephen King adaptation has a scene in which a boy is mocked for listening to 'New Kids On The Block' on his walkman?",
"answ":"IT",
"answ3":"IT CHAPTER ONE",
"answ2":"It (2017).",
},
{
"cat":"Remakes & Reboots",
"ques":"What is the title of the 2020 animated reboot of the Scooby-Doo franchise?",
"answ":"SCOOB!",
"answ3":"SCOOB",
"answ2":"Scoob!.",
},
{
"cat":"Mystery",
"ques":"Which Academy Award winning actress plays airplane engineer Kyle Pratt, whose daughter goes missing aboard a flight in Flightplan?",
"answ":"JODIE FOSTER",
"answ2":"Jodie Foster.",
},
{
"cat":"Mystery",
"ques":"Shane Black directed what 2000s murder mystery that involves a private eye, a struggling actress and a thief masquerading as an actor?",
"answ":"KISS KISS BANG BANG",
"answ2":"Kiss Kiss Bang Bang.",
},
{
"cat":"Mystery",
"ques":"What is the title of the 2009 sequel to The Da Vinci Code?",
"answ":"ANGELS AND DEMONS",
"answ2":"Angels & Demons.",
},
{
"cat":"Brad Pitt",
"ques":"Brad Pitt received his first Oscar nomination for what Terry Gilliam sci-fi film?",
"answ":"TWELVE MONKEYS",
"answ3":"12 MONKEYS",
"answ2":"Twelve Monkeys.",
},
{
"cat":"Stephen King",
"ques":"What Stephen King adaptation had a 90s sequel with the subtitle The Rage?",
"answ":"CARRIE",
"answ2":"Carrie.",
},
{
"cat":"Modern Classics",
"ques":"Who directed Jim Carrey in 1998's The Truman Show?",
"answ":"PETER WEIR",
"answ2":"Peter Weir.",
},
{
"cat":"Leonardo DiCaprio",
"ques":"Jeffrey Donavan plays Robert F. Kennedy in what 2010s DiCaprio film?",
"answ":"J EDGAR",
"answ2":"J. Edgar.",
},
{
"cat":"Wrestlers in Film",
"ques":"John Cena appears in which film in the Transformers franchise?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Wrestlers in Film",
"ques":"What is the name of the wrestler played by Randy Savage in 2002's Spider-Man?",
"answ":"BONESAW",
"answ3":"BONESAW MCGRAW",
"answ2":"Bonesaw.",
},
{
"cat":"Wrestlers in Film",
"ques":"In which 1991 film does Hulk Hogan play an interstellar hero from a distant world who visits Earth?",
"answ":"SUBURBAN COMMANDO",
"answ2":"Suburban Commando.",
},
{
"cat":"Wrestlers in Film",
"ques":"Who stars as convict Jack Conrad in the 2007 action thriller The Condemned?",
"answ":"STEVE AUSTIN",
"answ2":"Steve Austin.",
},
{
"cat":"James Stewart",
"ques":"James Stewart provides the voice of the character Sheriff Wylie Burp in what 90s animated film?",
"answ":"AN AMERICAN TAIL FIEVEL GOES WEST",
"answ3":"AN AMERICAN TAIL 2",
"answ2":"An American Tail: Fievel Goes Wes.",
},
{
"cat":"James Stewart",
"ques":"Who directed James Stewart in the films Rope and The Man Who Knew To Much?",
"answ":"ALFRED HITCHCOCK",
"answ2":"Alfred Hitchcock.",
},
{
"cat":"James Stewart",
"ques":"In the film Harvey, James Stewart's character has an invisible best friend in the titular Harvey, who is what kind of animal?",
"answ":"RABBIT",
"answ2":"Rabbit.",
},
{
"cat":"James Stewart",
"ques":"Which legendary actor co-starred with James Stewart in the westerns The Man Who Shot Liberty Valance and The Shootist?",
"answ":"JOHN WAYNE",
"answ2":"John Wayne.",
},
{
"cat":"Remakes & Reboots",
"ques":"Craig Gillespie directed what 2011 horror remake featuring Imogen Poots and Toni Collette?",
"answ":"FRIGHT NIGHT",
"answ2":"Fright Night.",
},
{
"cat":"Jennifer Lopez",
"ques":"Which actor co-starred with Jennifer Lopez in the films Gigli and Jersey Girl?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
},
{
"cat":"Viola Davis",
"ques":"Viola Davis was nominated for her first acting Oscar for what film?",
"answ":"DOUBT",
"answ2":"Doubt.",
},
{
"cat":"Viola Davis",
"ques":"Viola Davis plays Della Shiraz, the best friend of Julia Roberts' character in what film?",
"answ":"EAT PRAY LOVE",
"answ2":"Eat Pray Love.",
},
{
"cat":"Viola Davis",
"ques":"Viola Davis has been directed by Tyler Perry in one film starring his character Madea. What film was this?",
"answ":"MADEA GOES TO JAIL",
"answ2":"Madea Goes To Jail.",
},
{
"cat":"Viola Davis",
"ques":"Viola Davis plays Major Gwen Anderson who prepares her Battle School students for a possible alien invasion in what film?",
"answ":"ENDER'S GAME",
"answ3":"ENDERS GAME",
"answ2":"Ender's Game.",
},
];
twopointer = shuffle(twopointer);