var seventies = [
{
"cat":"70s",
"ques":"Who stars as Arthur Kirkland, a lawyer who is forced to defend a judge in 1979's ...And Justice For All?",
"answ":"AL PACINO",
"answ2":"Al Pacino.",
},
{
"cat":"70s",
"ques":"What was the first collaboration between director George Lucas and actor Harrison Ford?",
"answ":"AMERICAN GRAFFITI",
"answ2":"American Graffiti.",
},
{
"cat":"70s",
"ques":"Donald Sutherland played Hawkeye Pierce in what 1970 comedy?",
"answ":"MASH",
"answ3":"M*A*S*H",
"answ2":"M*A*S*H.",
},
{
"cat":"70s",
"ques":"Blake Edwards directed who as the wacky inspector Clouseau in the 1970s films The Return of the Pink Panther and The Pink Panther Strikes Again?",
"answ":"PETER SELLERS",
"answ2":"Peter Sellers.",
},
{
"cat":"70s",
"ques":"This classic Robert Altman film follows a unit of medical personnel during the Korean War.",
"answ":"MASH",
"answ3":"M*A*S*H",
"answ2":"M*A*S*H.",
},
{
"cat":"70s",
"ques":"What 70s musical includes songs such as 'Summer Nights', 'You're the One That I Want' and 'Beauty School Dropout'?",
"answ":"GREASE",
"answ2":"Grease.",
},
{
"cat":"70s",
"ques":"What rocker starred as an alien searching for water to save his planet in The Man Who Fell to Earth?",
"answ":"DAVID BOWIE",
"answ2":"David Bowie.",
},
{
"cat":"70s",
"ques":"What 1970s classic drama has performances by Robert Duvall, Ned Beatty, Faye Dunaway and William Holden?",
"answ":"NETWORK",
"answ2":"Network.",
},
{
"cat":"70s",
"ques":"Clint Eastwood plays Frank Morris, a prisoner with an exceptional IQ in what 1979 biographical film?",
"answ":"ESCAPE FROM ALCATRAZ",
"answ2":"Escape from Alcatraz.",
},
{
"cat":"70s",
"ques":"What is the name of the crime family that is central to the film The Godfather?",
"answ":"CORLEONE FAMILY",
"answ3":"CORLEONE",
"answ2":"Corleone family.",
},
{
"cat":"70s",
"ques":"What 1970s comedy includes the characters Bo Danville, Cledus Snow and Sheriff Buford T. Justice?",
"answ":"SMOKEY AND THE BANDIT",
"answ2":"Smokey and the Bandit.",
},
{
"cat":"70s",
"ques":"Terrence Malick wrote and directed what 1973 crime drama?",
"answ":"BADLANDS",
"answ2":"Badlands.",
},
{
"cat":"70s",
"ques":"Which actor makes a silent cameo as a priest at the beginning of 1978's Invasion of the Body Snatchers?",
"answ":"ROBERT DUVALL",
"answ2":"Robert Duvall.",
},
{
"cat":"70s",
"ques":"1971's The French Connection follows a pair of narcotics cops investigating a smuggling ring in what U.S. city?",
"answ":"NEW YORK",
"answ3":"NEW YORK CITY",
"answ2":"New York.",
},
{
"cat":"70s",
"ques":"Who played Sonny Wortzik in the 1975 drama Dog Day Afternoon?",
"answ":"AL PACINO",
"answ2":"Al Pacino.",
},
{
"cat":"70s",
"ques":"Which band sang the song Staying Alive for the opening of Saturday Night Fever?",
"answ":"BEE GEES",
"answ3":"THE BEE GEES",
"answ2":"Bee Gees.",
},
{
"cat":"70s",
"ques":"What 1973 film stars Bruce Lee as a martial artist recruited to spy on a drug lord during a deadly fighting tournament?",
"answ":"ENTER THE DRAGON",
"answ2":"Enter the Dragon.",
},
{
"cat":"70s",
"ques":"What was the name of Luke's aunt in Star Wars: A New Hope?",
"answ":"BERU",
"answ2":"Beru.",
},
{
"cat":"70s",
"ques":"Who directed the Al Pacino film Dog Day Afternoon?",
"answ":"SIDNEY LUMET",
"answ2":"Sidney Lumet.",
},
{
"cat":"70s",
"ques":"What is the name of the strong but dim-witted henchman sent to kill the sheriff in Blazing Saddles?",
"answ":"MONGO",
"answ2":"Mongo.",
},
{
"cat":"70s",
"ques":"Who played Carl Bernstein in All the President's Men?",
"answ":"DUSTIN HOFFMAN",
"answ3":"DUSTIN HOFMAN",
"answ2":"Dustin Hoffman.",
},
{
"cat":"70s",
"ques":"Who played the title character in 1977's Annie Hall?",
"answ":"DIANE KEATON",
"answ2":"Diane Keaton.",
},
{
"cat":"70s",
"ques":"Who played the lead role of Jack Prescott in the 1976 remake of King Kong?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"70s",
"ques":"Who stars as the architect turned vigilante Paul Kersey in 1974's Death Wish?",
"answ":"CHARLES BRONSON",
"answ2":"Charles Bronson.",
},
{
"cat":"70s",
"ques":"Who played legendary comedian Lenny Bruce in the 1974 film Lenny?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
},
];
var r2Q21 = [
{
"cat":"70s",
"ques":"What Dirty Harry movie features the serial killer Scorpio?",
"answ":"DIRTY HARRY",
"answ2":"Dirty Harry.",
"option":["Dirty Harry", "Magnum Force", "Sudden Impact", "The Enforcer"],
},
{
"cat":"70s",
"ques":"What was the name of the sequel to 1973's Westworld?",
"answ":"FUTUREWORLD",
"answ2":"Futureworld.",
"option":["Futureworld", "Westworld 2000", "Beyond Westworld", "Westworld II"],
},
{
"cat":"70s",
"ques":"In Taxi Driver, De Niro's character takes his love interest on a date to see a ____ movie.",
"answ":"PORNO",
"answ3":"PORNOGRAPHIC",
"answ2":"Pornographic movie.",
"option":["Pornographic movie", "German movie", "Silent movie", "Horror movie"],
},
{
"cat":"70s",
"ques":"How many Golden Tickets did candy-maker Willy Wonka hide in his famous Wonka Bars?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
"option":["5", "7", "4", "6"],
},
{
"cat":"70s",
"ques":"Who plays the male lead Oliver, in the 1970 romance film, Love Story?",
"answ":"RYAN O'NEAL",
"answ2":"Ryan O'Neal.",
"option":["Ryan O'Neal", "Warren Beatty", "Dustin Hoffman", "Robert Redford"],
},
{
"cat":"70s",
"ques":"In Grease, where is Sandy originally from?",
"answ":"AUSTRALIA",
"answ2":"Australia.",
"option":["Australia", "London", "Paris", "Los Angeles"],
},
{
"cat":"70s",
"ques":"In what movie do sweethearts Brad and Janet discover the eerie mansion of Dr. Frank-N-Furter?",
"answ":"THE ROCKY HORROR PICTURE SHOW",
"answ3":"ROCKY HORROR PICTURE SHOW",
"answ2":"The Rocky Horror Picture Show.",
"option":["The Rocky Horror Picture Show", "Attack of the Killer Tomatoes", "Son of Dracula", "Young Frankenstein"],
},
{
"cat":"70s",
"ques":"What was the name of the dog in Smokey and the Bandit?",
"answ":"FRED",
"answ2":"Fred.",
"option":["Fred", "Duke", "Sam", "Frank"],
},
{
"cat":"70s",
"ques":"What newspaper did Woodward and Bernstein work for in All the President's Men?",
"answ":"THE WASHINGTON POST",
"answ3":"WASHINGTON POST",
"answ2":"The Washington Post.",
"option":["The Washington Post", "The New York Times", "The Boston Globe", "The Wall Street Journal"],
},
{
"cat":"70s",
"ques":"What 70s film was Sean Connery's final performance of Bond for Eon Productions?",
"answ":"DIAMONDS ARE FOREVER",
"answ2":"Diamonds Are Forever.",
"option":["Diamonds Are Forever", "The Spy Who Loved Me", "The Man With the Golden Gun", "You Only Live Twice"],
},
{
"cat":"70s",
"ques":"What 1974 comedy features Kenneth Mars, Marty Feldman and Madeline Kahn?",
"answ":"YOUNG FRANKENSTEIN",
"answ2":"Young Frankenstein.",
"option":["Young Frankenstein", "Blazing Saddles", "The Longest Yard", "Uptown Saturday Night"],
},
{
"cat":"70s",
"ques":"What 1971 film's protagonist is a half-caucasian half-American Navajo Indian, a Vietnam War vet and a hapkido master?",
"answ":"BILLY JACK",
"answ2":"Billy Jack.",
"option":["Billy Jack", "Benjamin L. Willard", "Travis Bickle", "Randle Patrick McMurphy"],
},
{
"cat":"70s",
"ques":"What 70s thriller directed by John Schlesinger starred Roy Scheider, Laurence Olivier and William Devane?",
"answ":"MARATHON MAN",
"answ2":"Marathon Man.",
"option":["Marathon Man", "The Day of the Locust", "Airport", "Yanks"],
},
{
"cat":"70s",
"ques":"Who played Sonny's bank robbing partner Sal in 1975's Dog Day Afternoon?",
"answ":"JOHN CAZALE",
"answ2":"John Cazale.",
"option":["John Cazale", "Al Pacino", "Lance Henriksen", "Robert De Niro"],
},
{
"cat":"70s",
"ques":"What 1977 movie tells the story of the World War II military operation entitled Operation Market Garden?",
"answ":"A BRIDGE TOO FAR",
"answ2":"A Bridge Too Far.",
"option":["A Bridge Too Far", "The Bridge on the River Kwai", "The Bridge at Remagen", "The Longest Day"],
},
{
"cat":"70s",
"ques":"Who plays the blind monk in Young Frankenstein?",
"answ":"GENE HACKMAN",
"answ2":"Gene Hackman.",
"option":["Gene Hackman", "Gene Wilder", "Mel Brooks", "Peter Boyle"],
},
{
"cat":"70s",
"ques":"Who played King Arthur in the 1975 film Monty Python and the Holy Grail?",
"answ":"GRAHAM CHAPMAN",
"answ2":"Graham Chapman.",
"option":["Graham Chapman", "John Cleese", "Terry Gilliam", "Eric Idle"],
},
{
"cat":"70s",
"ques":"Who played the character of Katie opposite Robert Redford in 1973's The Way We Were?",
"answ":"BARBRA STREISAND",
"answ3":"BARBARA STREISAND",
"answ2":"Barba Streisand.",
"option":["Barbra Streisand", "Florence Henderson", "Lynda Carter", "Diane Keaton"],
},
{
"cat":"70s",
"ques":"In what 70s comedy will you find a trucker named Philo Beddoe roaming the American West in search for a lost love?",
"answ":"EVERY WHICH WAY BUT LOSE",
"answ3":"EVERY WHICH WAY BUT LOOSE",
"answ2":"Every Which Way But Loose.",
"option":["Every Which Way But Loose", "Breaking Away", "The Heartbreak Kid", "The Frisco Kid"],
},
{
"cat":"70s",
"ques":"What film director played the role of Noah Cross in Chinatown?",
"answ":"JOHN HUSTON",
"answ3":"JOHN HOUSTON",
"answ2":"John Huston.",
"option":["John Huston", "Orson Welles", "Billy Wilder", "Roman Polanski"],
},
{
"cat":"70s",
"ques":"What was the name of the psychotic serial killer in Dirty Harry?",
"answ":"SCORPIO",
"answ2":"Scorpio.",
"option":["Scorpio", "Pyro", "Ajax", "Roman"],
},
{
"cat":"70s",
"ques":"In Blazing Saddles, what seems to be the last name of everybody in the town of Rock Ridge?",
"answ":"JOHNSON",
"answ2":"Johnson.",
"option":["Johnson", "Smith", "Taylor", "Baker"],
},
{
"cat":"70s",
"ques":"What film stars James Brolin, Sam Waterston and O.J. Simpson as 3 astronauts who are forced to fake a Mars landing?",
"answ":"CAPRICORN ONE",
"answ2":"Capricorn One.",
"option":["Capricorn One", "Mission to Mars", "Deep Dark Secrets", "Fantastic Voyage"],
},
{
"cat":"70s",
"ques":"Who played the title character in 1971's Shaft?",
"answ":"RICHARD ROUNDTREE",
"answ2":"Richard Roundtree.",
"option":["Richard Roundtree", "Samuel L. Jackson", "Morgan Freeman", "Sidney Poitier"],
},
{
"cat":"70s",
"ques":"Who played treasure-hunter Romer Treece in 1977's The Deep?",
"answ":"ROBERT SHAW",
"answ2":"Robert Shaw.",
"option":["Robert Shaw", "Richard Dreyfuss", "Nick Nolte", "Dustin Hoffman"],
},
{
"cat":"70s",
"ques":"Who directed the 1970s horror classic Suspiria?",
"answ":"DARIO ARGENTO",
"answ2":"Dario Argento.",
"option":["Dario Argento", "John Carpenter", "Wes Craven", "William Friedkin"],
},
{
"cat":"70s",
"ques":"In what 70s sci-fi film does Bruce Dern star as ecologist Freeman Lowell?",
"answ":"SILENT RUNNING",
"answ2":"Silent Running.",
"option":["Silent Running", "Time After Time", "The Omega Man", "Solaris"],
},
{
"cat":"70s",
"ques":"Who played the robot gunslinger in 1973's Westworld?",
"answ":"YUL BRYNNER",
"answ3":"YUL BRINNER",
"answ2":"Yul Brynner.",
"option":["Yul Brynner", "Charles Bronson", "Robert Vaughn", "James Coburn"],
},
{
"cat":"70s",
"ques":"In 1975's The Man Who Would Be King, what song does Sean Connery's character sing before he tumbles to his death?",
"answ":"THE SON OF GOD GOES FORTH TO WAR",
"answ3":"THE MINSTREL BOY",
"answ2":"The Minstrel Boy/The Son of God Goes Forth to War.",
"option":["The Minstrel Boy", "God Save the Queen", "Danny Boy", "Scarborough Fair"],
},
{
"cat":"70s",
"ques":"What was the final movie in The Planet of the Apes series to be released in the 1970s?",
"answ":"BATTLE FOR THE PLANET OF THE APES",
"answ2":"Battle for the Planet of the Apes.",
"option":["Battle for the Planet of the Apes", "Conquest of the Planet of the Apes", "Escape from the Planet of the Apes", "Beneath the Planet of the Apes"],
},
{
"cat":"70s",
"ques":"Who stars as a critic obsessed with Casablanca in Herbert Ross' Play It Again, Sam?",
"answ":"WOODY ALLEN",
"answ3":"WOODY ALLAN",
"answ2":"Woody Allen.",
"option":["Woody Allen", "Jack Nicholson", "Dustin Hoffman", "Robert De Niro"],
},
{
"cat":"70s",
"ques":"In Deliverance, who plays Lewis who suffers a bad leg break?",
"answ":"BURT REYNOLDS",
"answ2":"Burt Reynolds.",
"option":["Burt Reynolds", "Ronny Cox", "Jon Voight", "Ned Beatty"],
},
{
"cat":"70s",
"ques":"In Smokey and the Bandit, what country western music star plays the Bandit's 'good buddy' Cledus 'Snowman' Snow?",
"answ":"JERRY REED",
"answ2":"Jerry Reed.",
"option":["Jerry Reed", "Willie Nelson", "Kenny Rogers", "Kris Kristofferson"],
},
{
"cat":"70s",
"ques":"In Young Frankenstein, who plays the lovely young assistant Inga?",
"answ":"TERI GARR",
"answ2":"Teri Garr.",
"option":["Teri Garr", "Jane Fonda", "Liza Minnelli", "Vanessa Redgrave"],
},
{
"cat":"70s",
"ques":"What island/beach do the attacks in Jaws take place?",
"answ":"AMITY ISLAND",
"answ3":"AMITY",
"answ2":"Amity Island.",
"option":["Amity Island", "Chappaquiddick Island", "Castle Island", "Langlee Island"],
},
{
"cat":"70s",
"ques":"Who plays the lead role of Jonathan E. in the 1975 movie Rollerball?",
"answ":"JAMES CAAN",
"answ2":"James Caan.",
"option":["James Caan", "John Houseman", "Burt Young", "Billy Dee Williams"],
},
{
"cat":"70s",
"ques":"In The Way of the Dragon (also referred to as Return of the Dragon), Bruce Lee fought Chuck Norris at which historical monument?",
"answ":"COLOSSEUM",
"answ3":"COLOSEUM",
"answ2":"Colosseum.",
"option":["Colosseum", "Parthenon", "Great Wall", "Forbidden City"],
},
{
"cat":"70s",
"ques":"Who directed Network?",
"answ":"SIDNEY LUMET",
"answ2":"Sidney Lumet.",
"option":["Sidney Lumet", "Robert Altman", "Mike Nichols", "Alan J. Pakula"],
},
{
"cat":"70s",
"ques":"Who played Jane in the 1977 version of Fun with Dick and Jane?",
"answ":"JANE FONDA",
"answ2":"Jane Fonda.",
"option":["Jane Fonda", "Cybill Shepherd", "Faye Dunaway", "Michelle Pfeiffer"],
},
{
"cat":"70s",
"ques":"Whose birthday is being celebrated at the end of The Godfather Part 2?",
"answ":"VITO",
"answ3":"VITO CORLEONE",
"answ2":"Vito.",
"option":["Vito", "Michael", "Connie", "Sonny"],
},
{
"cat":"70s",
"ques":"What European country did Serpico move to after retiring from the police force?",
"answ":"SWITZERLAND",
"answ2":"Switzerland.",
"option":["Switzerland", "Germany", "Greece", "Denmark"],
},
{
"cat":"70s",
"ques":"Who plays Rudyard Kipling in the 1975 adventure film The Man Who Would Be King?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
"option":["Christopher Plummer", "Sean Connery", "Michael Caine", "Jack Nicholson"],
},
{
"cat":"70s",
"ques":"The irreverent adventures of Hawkeye Pierce and Trapper John can be found in what Robert Altman film?",
"answ":"M*A*S*H",
"answ3":"MASH",
"answ2":"MASH.",
"option":["MASH", "Nashville", "The Long Goodbye", "Thieves Like Us"],
},
{
"cat":"70s",
"ques":"Who plays Annie's troubled brother Duane in Annie Hall?",
"answ":"CHRISTOPHER WALKEN",
"answ2":"Christopher Walken.",
"option":["Christopher Walken", "Jeff Daniels", "Alan Alda", "Bill Murray"],
},
{
"cat":"70s",
"ques":"Who played the role of the shy teenage girl named Holly in Terrence Malick's Badlands?",
"answ":"SISSY SPACEK",
"answ2":"Sissy Spacek.",
"option":["Sissy Spacek", "Jodie Foster", "Sally Field", "Cybill Shepherd"],
},
{
"cat":"70s",
"ques":"What 1971 film marked the directorial debut of George Lucas?",
"answ":"THX 1138",
"answ2":"THX 1138.",
"option":["THX 1138", "Star Wars", "American Graffiti", "Kagemusha"],
},
{
"cat":"70s",
"ques":"In All the President's Men, where did Bob Woodward have all of his secret meetings with Deep Throat?",
"answ":"PARKING GARAGE",
"answ3":"IN A PARKING GARAGE",
"answ2":"Parking garage.",
"option":["Parking garage", "Restaurant", "Movie theater", "Gas station"],
},
{
"cat":"70s",
"ques":"Who starred as hitman Arthur Bishop in the original 1972 film The Mechanic?",
"answ":"CHARLES BRONSON",
"answ2":"Charles Bronson.",
"option":["Charles Bronson", "Lee Marvin", "Ernest Borgnine", "Clint Eastwood"],
},
{
"cat":"70s",
"ques":"Who played Detective Hercule Poirot in the 1974 version of Murder on the Orient Express?",
"answ":"ALBERT FINNEY",
"answ2":"Albert Finney.",
"option":["Albert Finney", "Peter Ustinov", "Ian Holm", "Alec Guinness"],
},
{
"cat":"70s",
"ques":"In the 1975 cult classic Death Race 2000, the lead character is named after what Universal horror monster?",
"answ":"FRANKENSTEIN",
"answ3":"FRANKENSTEIN'S MONSTER",
"answ2":"Frankenstein.",
"option":["Frankenstein", "Mummy", "Dracula", "Wolf man"],
},
{
"cat":"70s",
"ques":"Who played the titular character in 1977's MacArthur?",
"answ":"GREGORY PECK",
"answ2":"Gregory Peck.",
"option":["Gregory Peck", "David Warner", "Charles Bronson", "Laurence Olivier"],
},
{
"cat":"70s",
"ques":"In 1976's Taxi Driver, what name does Travis tell the Secret Service agent his name is?",
"answ":"HENRY",
"answ3":"HENRY KRINKLE",
"answ2":"Henry Krinkle.",
"option":["Henry Krinkle", "Lennie Briscoe", "Mac Gargan", "Mike Haggar"],
},
{
"cat":"70s",
"ques":"What is the name of the fighter that Rocky fights in the very first fight in the original Rocky film?",
"answ":"SPIDER RICO",
"answ2":"Spider Rico.",
"option":["Spider Rico", "Mickey Goldmill", "Mason Dixon", "Union Cane"],
},
{
"cat":"70s",
"ques":"Who plays the role of Victoria Brisbane in 1977's High Anxiety?",
"answ":"MADELINE KAHN",
"answ2":"Madeline Kahn.",
"option":["Madeline Kahn", "Diane Keaton", "Ellen Burstyn", "Faye Dunaway"],
},
{
"cat":"70s",
"ques":"Who plays Ostap Bender, a homeless con-artist in 1970's The Twelve Chairs?",
"answ":"FRANK LANGELLA",
"answ2":"Frank Langella.",
"option":["Frank Langella", "Donald Pleasence", "Robert Mitchum", "Christopher Lee"],
},
{
"cat":"70s",
"ques":"Which famous comedic actor played Doctor Ross in Woody Allen's cult hit Everything You Always Wanted To Know About Sex?",
"answ":"GENE WILDER",
"answ2":"Gene Wilder.",
"option":["Gene Wilder", "Walter Matthau", "Peter Sellars", "Jerry Lewis"],
},
{
"cat":"70s",
"ques":"Who directed 1971's Dirty Harry?",
"answ":"DON SIEGEL",
"answ3":"DON SEGEL",
"answ2":"Don Siegel.",
"option":["Don Siegel", "Clint Eastwood", "Ted Post", "James Fargo"],
},
{
"cat":"70s",
"ques":"In Monty Python and the Holy Grail, what does the French taunter say 'your mother smells' like?",
"answ":"ELDERBERRIES",
"answ2":"Elderberries.",
"option":["Elderberries", "Strawberries", "Blueberries", "Apples"],
},
{
"cat":"70s",
"ques":"Jack Nicholson played a therapist in what 1975 musical based on music by The Who?",
"answ":"TOMMY",
"answ2":"Tommy.",
"option":["Tommy", "Imagine", "Veronica", "Marco"],
},
{
"cat":"70s",
"ques":"What 1978 movie stars Richard Gere as a farm worker involved in a romantic triangle during the 1910s?",
"answ":"DAYS OF HEAVEN",
"answ2":"Days of Heaven.",
"option":["Days of Heaven", "Badlands", "Bound for Glory", "Gates of Heaven"],
},
{
"cat":"70s",
"ques":"The 1971 coming-of-age drama The Last Picture Show takes place in what U.S. state during the 1950s?",
"answ":"TEXAS",
"answ2":"Texas.",
"option":["Texas", "California", "Kansas", "Kentucky"],
},
{
"cat":"70s",
"ques":"Which actress won Oscars for her performances in the 70s films Women in Love and A Touch of Class?",
"answ":"GLENDA JACKSON",
"answ2":"Glenda Jackson.",
"option":["Glenda Jackson", "Jill Clayburgh", "Maggie Smith", "Ellen Burstyn"],
},
];
seventies = shuffle(seventies);
r2Q21 = shuffle(r2Q21);