var seventies = [
{
"cat":"70s",
"ques":"What rocker starred as an alien searching for water to save his planet in The Man Who Fell to Earth?",
"answ":"DAVID BOWIE",
"answ2":"David Bowie.",
},
{
"cat":"70s",
"ques":"Clint Eastwood plays Frank Morris, a prisoner with an exceptional IQ in what 1979 biographical film?",
"answ":"ESCAPE FROM ALCATRAZ",
"answ2":"Escape from Alcatraz.",
},
{
"cat":"70s",
"ques":"What is the name of the crime family that is central to the film The Godfather?",
"answ":"CORLEONE FAMILY",
"answ3":"CORLEONE",
"answ2":"Corleone family.",
},
{
"cat":"70s",
"ques":"What 1970s comedy includes the characters Bo Danville, Cledus Snow and Sheriff Buford T. Justice?",
"answ":"SMOKEY AND THE BANDIT",
"answ2":"Smokey and the Bandit.",
},
{
"cat":"70s",
"ques":"Terrence Malick wrote and directed what 1973 crime drama?",
"answ":"BADLANDS",
"answ2":"Badlands.",
},
{
"cat":"70s",
"ques":"Which actor makes a silent cameo as a priest at the beginning of 1978's Invasion of the Body Snatchers?",
"answ":"ROBERT DUVALL",
"answ2":"Robert Duvall.",
},
{
"cat":"70s",
"ques":"1971's The French Connection follows a pair of narcotics cops investigating a smuggling ring in what U.S. city?",
"answ":"NEW YORK",
"answ3":"NEW YORK CITY",
"answ2":"New York.",
},
{
"cat":"70s",
"ques":"Who played Sonny Wortzik in the 1975 drama Dog Day Afternoon?",
"answ":"AL PACINO",
"answ2":"Al Pacino.",
},
{
"cat":"70s",
"ques":"Which band sang the song Staying Alive for the opening of Saturday Night Fever?",
"answ":"BEE GEES",
"answ3":"THE BEE GEES",
"answ2":"Bee Gees.",
},
{
"cat":"70s",
"ques":"What 1973 film stars Bruce Lee as a martial artist recruited to spy on a drug lord during a deadly fighting tournament?",
"answ":"ENTER THE DRAGON",
"answ2":"Enter the Dragon.",
},
{
"cat":"70s",
"ques":"What was the name of Luke's aunt in Star Wars: A New Hope?",
"answ":"BERU",
"answ2":"Beru.",
},
{
"cat":"70s",
"ques":"Who directed the Al Pacino film Dog Day Afternoon?",
"answ":"SIDNEY LUMET",
"answ2":"Sidney Lumet.",
},
{
"cat":"70s",
"ques":"What is the name of the strong but dim-witted henchman sent to kill the sheriff in Blazing Saddles?",
"answ":"MONGO",
"answ2":"Mongo.",
},
{
"cat":"70s",
"ques":"Who played Carl Bernstein in All the President's Men?",
"answ":"DUSTIN HOFFMAN",
"answ3":"DUSTIN HOFMAN",
"answ2":"Dustin Hoffman.",
},
{
"cat":"70s",
"ques":"Who played the title character in 1977's Annie Hall?",
"answ":"DIANE KEATON",
"answ2":"Diane Keaton.",
},
{
"cat":"70s",
"ques":"Who played the lead role of Jack Prescott in the 1976 remake of King Kong?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"70s",
"ques":"Who stars as the architect turned vigilante Paul Kersey in 1974's Death Wish?",
"answ":"CHARLES BRONSON",
"answ2":"Charles Bronson.",
},
{
"cat":"70s",
"ques":"Who played legendary comedian Lenny Bruce in the 1974 film Lenny?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
},
];
var r2Q21 = [
{
"cat":"70s",
"ques":"What Dirty Harry movie features the serial killer Scorpio?",
"answ":"DIRTY HARRY",
"answ2":"Dirty Harry.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Magnum Force</button><button id=incop2 class=buttons003 onclick=qinc()>Sudden Impact</button><button id=incop3 class=buttons003 onclick=qinc()>The Enforcer</button><button id=corop class=buttons003 onclick=qcor()>Dirty Harry</button><br/>",
},
{
"cat":"70s",
"ques":"What was the name of the sequel to 1973's Westworld?",
"answ":"FUTUREWORLD",
"answ2":"Futureworld.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Westworld 2000</button><button id=incop2 class=buttons003 onclick=qinc()>Beyond Westworld</button><button id=incop3 class=buttons003 onclick=qinc()>Westworld II</button><button id=corop class=buttons003 onclick=qcor()>Futureworld</button><br/>",
},
{
"cat":"70s",
"ques":"In Taxi Driver, De Niro's character takes his love interest on a date to see a ____ movie.",
"answ":"PORNO",
"answ3":"PORNOGRAPHIC",
"answ2":"Pornographic movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>German movie</button><button id=incop2 class=buttons003 onclick=qinc()>Silent movie</button><button id=incop3 class=buttons003 onclick=qinc()>Horror movie</button><button id=corop class=buttons003 onclick=qcor()>Pornographic movie</button><br/>",
},
{
"cat":"70s",
"ques":"How many Golden Tickets did candy-maker Willy Wonka hide in his famous Wonka Bars?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>4</button><button id=incop2 class=buttons003 onclick=qinc()>7</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"70s",
"ques":"In Grease, where is Sandy originally from?",
"answ":"AUSTRALIA",
"answ2":"Australia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>London</button><button id=incop2 class=buttons003 onclick=qinc()>Paris</button><button id=incop3 class=buttons003 onclick=qinc()>Los Angeles</button><button id=corop class=buttons003 onclick=qcor()>Australia</button><br/>",
},
{
"cat":"70s",
"ques":"In what movie do sweethearts Brad and Janet discover the eerie mansion of Dr. Frank-N-Furter?",
"answ":"THE ROCKY HORROR PICTURE SHOW",
"answ3":"ROCKY HORROR PICTURE SHOW",
"answ2":"The Rocky Horror Picture Show.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Attack of the Killer Tomatoes</button><button id=incop2 class=buttons003 onclick=qinc()>Son of Dracula</button><button id=incop3 class=buttons003 onclick=qinc()>Young Frankenstein</button><button id=corop class=buttons003 onclick=qcor()>The Rocky Horror Picture Show</button><br/>",
},
{
"cat":"70s",
"ques":"What was the name of the dog in Smokey and the Bandit?",
"answ":"FRED",
"answ2":"Fred.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Fred</button><button id=incop2 class=buttons003 onclick=qinc()>Duke</button><button id=incop3 class=buttons003 onclick=qinc()>Sam</button><button id=incop4 class=buttons003 onclick=qinc()>Frank</button><br/>",
},
{
"cat":"70s",
"ques":"What newspaper did Woodward and Bernstein work for in All the President's Men?",
"answ":"THE WASHINGTON POST",
"answ3":"WASHINGTON POST",
"answ2":"The Washington Post.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Washington Post</button><button id=incop2 class=buttons003 onclick=qinc()>The New York Times</button><button id=incop3 class=buttons003 onclick=qinc()>The Boston Globe</button><button id=incop4 class=buttons003 onclick=qinc()>The Wall Street Journal</button><br/>",
},
{
"cat":"70s",
"ques":"What 70s film was Sean Connery's final performance of Bond for Eon Productions?",
"answ":"DIAMONDS ARE FOREVER",
"answ2":"Diamonds Are Forever.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Diamonds Are Forever</button><button id=incop2 class=buttons003 onclick=qinc()>The Spy Who Loved Me</button><button id=incop3 class=buttons003 onclick=qinc()>The Man With the Golden Gun</button><button id=incop4 class=buttons003 onclick=qinc()>You Only Live Twice</button><br/>",
},
{
"cat":"70s",
"ques":"What 1974 comedy features Kenneth Mars, Marty Feldman and Madeline Kahn?",
"answ":"YOUNG FRANKENSTEIN",
"answ2":"Young Frankenstein.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blazing Saddles</button><button id=corop class=buttons003 onclick=qcor()>Young Frankenstein</button><button id=incop3 class=buttons003 onclick=qinc()>The Longest Yard</button><button id=incop4 class=buttons003 onclick=qinc()>Uptown Saturday Night</button><br/>",
},
{
"cat":"70s",
"ques":"What 1971 film's protagonist is a half-caucasian half-American Navajo Indian, a Vietnam War vet and a hapkido master?",
"answ":"BILLY JACK",
"answ2":"Billy Jack.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Benjamin L. Willard</button><button id=corop class=buttons003 onclick=qcor()>Billy Jack</button><button id=incop3 class=buttons003 onclick=qinc()>Travis Bickle</button><button id=incop4 class=buttons003 onclick=qinc()>Randle Patrick McMurphy</button><br/>",
},
{
"cat":"70s",
"ques":"What 70s thriller directed by John Schlesinger starred Roy Scheider, Laurence Olivier and William Devane?",
"answ":"MARATHON MAN",
"answ2":"Marathon Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Day of the Locust</button><button id=corop class=buttons003 onclick=qcor()>Marathon Man</button><button id=incop3 class=buttons003 onclick=qinc()>Airport</button><button id=incop4 class=buttons003 onclick=qinc()>Yanks</button><br/>",
},
{
"cat":"70s",
"ques":"Who played Sonny's bank robbing partner Sal in 1975's Dog Day Afternoon?",
"answ":"JOHN CAZALE",
"answ2":"John Cazale.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Al Pacino</button><button id=corop class=buttons003 onclick=qcor()>John Cazale</button><button id=incop3 class=buttons003 onclick=qinc()>Lance Henriksen</button><button id=incop4 class=buttons003 onclick=qinc()>Robert De Niro</button><br/>",
},
{
"cat":"70s",
"ques":"What 1977 movie tells the story of the World War II military operation entitled Operation Market Garden?",
"answ":"A BRIDGE TOO FAR",
"answ2":"A Bridge Too Far.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A Bridge Too Far</button><button id=incop2 class=buttons003 onclick=qinc()>The Bridge on the River Kwai</button><button id=incop3 class=buttons003 onclick=qinc()>The Bridge at Remagen</button><button id=incop4 class=buttons003 onclick=qinc()>The Longest Day</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays the blind monk in Young Frankenstein?",
"answ":"GENE HACKMAN",
"answ2":"Gene Hackman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gene Wilder</button><button id=incop2 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=incop3 class=buttons003 onclick=qinc()>Peter Boyle</button><button id=corop class=buttons003 onclick=qcor()>Gene Hackman</button><br/>",
},
{
"cat":"70s",
"ques":"Who played King Arthur in the 1975 film Monty Python and the Holy Grail?",
"answ":"GRAHAM CHAPMAN",
"answ2":"Graham Chapman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Cleese</button><button id=incop2 class=buttons003 onclick=qinc()>Terry Gilliam</button><button id=incop3 class=buttons003 onclick=qinc()>Eric Idle</button><button id=corop class=buttons003 onclick=qcor()>Graham Chapman</button><br/>",
},
{
"cat":"70s",
"ques":"Who played the character of Katie opposite Robert Redford in 1973's The Way We Were?",
"answ":"BARBRA STREISAND",
"answ3":"BARBARA STREISAND",
"answ2":"Barba Streisand.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Florence Henderson</button><button id=incop2 class=buttons003 onclick=qinc()>Lynda Carter</button><button id=incop3 class=buttons003 onclick=qinc()>Diane Keaton</button><button id=corop class=buttons003 onclick=qcor()>Barbra Streisand</button><br/>",
},
{
"cat":"70s",
"ques":"In what 70s comedy will you find a trucker named Philo Beddoe roaming the American West in search for a lost love?",
"answ":"EVERY WHICH WAY BUT LOSE",
"answ3":"EVERY WHICH WAY BUT LOOSE",
"answ2":"Every Which Way But Loose.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Every Which Way But Loose</button><button id=incop2 class=buttons003 onclick=qinc()>Breaking Away</button><button id=incop3 class=buttons003 onclick=qinc()>The Heartbreak Kid</button><button id=incop4 class=buttons003 onclick=qinc()>The Frisco Kid</button><br/>",
},
{
"cat":"70s",
"ques":"What film director played the role of Noah Cross in Chinatown?",
"answ":"JOHN HUSTON",
"answ3":"JOHN HOUSTON",
"answ2":"John Huston.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Orson Welles</button><button id=corop class=buttons003 onclick=qcor()>John Huston</button><button id=incop3 class=buttons003 onclick=qinc()>Billy Wilder</button><button id=incop4 class=buttons003 onclick=qinc()>Roman Polanski</button><br/>",
},
{
"cat":"70s",
"ques":"What was the name of the psychotic serial killer in Dirty Harry?",
"answ":"SCORPIO",
"answ2":"Scorpio.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pyro</button><button id=corop class=buttons003 onclick=qcor()>Scorpio</button><button id=incop3 class=buttons003 onclick=qinc()>Ajax</button><button id=incop4 class=buttons003 onclick=qinc()>Roman</button><br/>",
},
{
"cat":"70s",
"ques":"In Blazing Saddles, what seems to be the last name of everybody in the town of Rock Ridge?",
"answ":"JOHNSON",
"answ2":"Johnson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Smith</button><button id=corop class=buttons003 onclick=qcor()>Johnson</button><button id=incop3 class=buttons003 onclick=qinc()>Taylor</button><button id=incop4 class=buttons003 onclick=qinc()>Baker</button><br/>",
},
{
"cat":"70s",
"ques":"What film stars James Brolin, Sam Waterston and O.J. Simpson as 3 astronauts who are forced to fake a Mars landing?",
"answ":"CAPRICORN ONE",
"answ2":"Capricorn One.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mission to Mars</button><button id=corop class=buttons003 onclick=qcor()>Capricorn One</button><button id=incop3 class=buttons003 onclick=qinc()>Deep Dark Secrets</button><button id=incop4 class=buttons003 onclick=qinc()>Fantastic Voyage</button><br/>",
},
{
"cat":"70s",
"ques":"Who played the title character in 1971's Shaft?",
"answ":"RICHARD ROUNDTREE",
"answ2":"Richard Roundtree.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Samuel L. Jackson</button><button id=corop class=buttons003 onclick=qcor()>Richard Roundtree</button><button id=incop3 class=buttons003 onclick=qinc()>Deep Dark Secrets</button><button id=incop4 class=buttons003 onclick=qinc()>Fantastic Voyage</button><br/>",
},
{
"cat":"70s",
"ques":"Who played treasure-hunter Romer Treece in 1977's The Deep?",
"answ":"ROBERT SHAW",
"answ2":"Robert Shaw.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><button id=corop class=buttons003 onclick=qcor()>Robert Shaw</button><button id=incop3 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop4 class=buttons003 onclick=qinc()>Dustin Hoffman</button><br/>",
},
{
"cat":"70s",
"ques":"Who directed the 1970s horror classic Suspiria?",
"answ":"DARIO ARGENTO",
"answ2":"Dario Argento.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Carpenter</button><button id=corop class=buttons003 onclick=qcor()>Dario Argento</button><button id=incop3 class=buttons003 onclick=qinc()>Wes Craven</button><button id=incop4 class=buttons003 onclick=qinc()>William Friedkin</button><br/>",
},
{
"cat":"70s",
"ques":"In what 70s sci-fi film does Bruce Dern star as ecologist Freeman Lowell?",
"answ":"SILENT RUNNING",
"answ2":"Silent Running.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Time After Time</button><button id=corop class=buttons003 onclick=qcor()>Silent Running</button><button id=incop3 class=buttons003 onclick=qinc()>The Omega Man</button><button id=incop4 class=buttons003 onclick=qinc()>Solaris</button><br/>",
},
{
"cat":"70s",
"ques":"Who played the robot gunslinger in 1973's Westworld?",
"answ":"YUL BRYNNER",
"answ3":"YUL BRINNER",
"answ2":"Yul Brynner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charles Bronson</button><button id=corop class=buttons003 onclick=qcor()>Yul Brynner</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Vaughn</button><button id=incop4 class=buttons003 onclick=qinc()>James Coburn</button><br/>",
},
{
"cat":"70s",
"ques":"In 1975's The Man Who Would Be King, what song does Sean Connery's character sing before he tumbles to his death?",
"answ":"MINSTREL BOY",
"answ3":"THE MINSTREL BOY",
"answ2":"The Minstrel Boy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>God Save the Queen</button><button id=incop2 class=buttons003 onclick=qinc()>Danny Boy</button><button id=incop3 class=buttons003 onclick=qinc()>Scarborough Fair</button><button id=corop class=buttons003 onclick=qcor()>The Minstrel Boy</button><br/>",
},
{
"cat":"70s",
"ques":"What was the final movie in The Planet of the Apes series to be released in the 1970s?",
"answ":"BATTLE FOR THE PLANET OF THE APES",
"answ2":"Battle for the Planet of the Apes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Conquest of the Planet of the Apes</button><button id=incop2 class=buttons003 onclick=qinc()>Escape from the Planet of the Apes</button><button id=incop3 class=buttons003 onclick=qinc()>Beneath the Planet of the Apes</button><button id=corop class=buttons003 onclick=qcor()>Battle for the Planet of the Apes</button><br/>",
},
{
"cat":"70s",
"ques":"Who stars as a critic obsessed with Casablanca in Herbert Ross' Play It Again, Sam?",
"answ":"WOODY ALLEN",
"answ3":"WOODY ALLAN",
"answ2":"Woody Allen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=incop2 class=buttons003 onclick=qinc()>Dustin Hoffman</button><button id=incop3 class=buttons003 onclick=qinc()>Robert De Niro</button><button id=corop class=buttons003 onclick=qcor()>Woody Allen</button><br/>",
},
{
"cat":"70s",
"ques":"In Deliverance, who plays Lewis who suffers a bad leg break?",
"answ":"BURT REYNOLDS",
"answ2":"Burt Reynolds.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ronny Cox</button><button id=incop2 class=buttons003 onclick=qinc()>Jon Voight</button><button id=incop3 class=buttons003 onclick=qinc()>Ned Beatty</button><button id=corop class=buttons003 onclick=qcor()>Burt Reynolds</button><br/>",
},
{
"cat":"70s",
"ques":"In Smokey and the Bandit, what country western music star plays the Bandit's 'good buddy' Cledus 'Snowman' Snow?",
"answ":"JERRY REED",
"answ2":"Jerry Reed.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Willie Nelson</button><button id=corop class=buttons003 onclick=qcor()>Jerry Reed</button><button id=incop3 class=buttons003 onclick=qinc()>Kenny Rogers</button><button id=incop4 class=buttons003 onclick=qinc()>Kris Kristofferson</button><br/>",
},
{
"cat":"70s",
"ques":"In Young Frankenstein, who plays the lovely young assistant Inga?",
"answ":"TERI GARR",
"answ2":"Teri Garr.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jane Fonda</button><button id=corop class=buttons003 onclick=qcor()>Teri Garr</button><button id=incop3 class=buttons003 onclick=qinc()>Liza Minnelli</button><button id=incop4 class=buttons003 onclick=qinc()>Vanessa Redgrave</button><br/>",
},
{
"cat":"70s",
"ques":"What island/beach do the attacks in Jaws take place?",
"answ":"AMITY ISLAND",
"answ3":"AMITY",
"answ2":"Amity Island.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chappaquiddick Island</button><button id=corop class=buttons003 onclick=qcor()>Amity Island</button><button id=incop3 class=buttons003 onclick=qinc()>Castle Island</button><button id=incop4 class=buttons003 onclick=qinc()>Langlee Island</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays the lead role of Jonathan E. in the 1975 movie Rollerball?",
"answ":"JAMES CAAN",
"answ2":"James Caan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Houseman</button><button id=corop class=buttons003 onclick=qcor()>James Caan</button><button id=incop3 class=buttons003 onclick=qinc()>Burt Young</button><button id=incop4 class=buttons003 onclick=qinc()>Billy Dee Williams</button><br/>",
},
{
"cat":"70s",
"ques":"In The Way of the Dragon (also referred to as Return of the Dragon), Bruce Lee fought Chuck Norris at which historical monument?",
"answ":"COLOSSEUM",
"answ3":"COLOSEUM",
"answ2":"Colosseum.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Colosseum</button><button id=incop2 class=buttons003 onclick=qinc()>Parthenon</button><button id=incop3 class=buttons003 onclick=qinc()>Great Wall</button><button id=incop4 class=buttons003 onclick=qinc()>Forbidden City</button><br/>",
},
{
"cat":"70s",
"ques":"Who directed Network?",
"answ":"SIDNEY LUMET",
"answ2":"Sidney Lumet.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sidney Lumet</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Altman</button><button id=incop3 class=buttons003 onclick=qinc()>Mike Nichols</button><button id=incop4 class=buttons003 onclick=qinc()>Alan J. Pakula</button><br/>",
},
{
"cat":"70s",
"ques":"Who played Jane in the 1977 version of Fun with Dick and Jane?",
"answ":"JANE FONDA",
"answ2":"Jane Fonda.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jane Fonda</button><button id=incop2 class=buttons003 onclick=qinc()>Cybill Shepherd</button><button id=incop3 class=buttons003 onclick=qinc()>Faye Dunaway</button><button id=incop4 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><br/>",
},
{
"cat":"70s",
"ques":"Whose birthday is being celebrated at the end of The Godfather Part 2?",
"answ":"VITO",
"answ3":"VITO CORLEONE",
"answ2":"Vito.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael</button><button id=incop2 class=buttons003 onclick=qinc()>Connie</button><button id=incop3 class=buttons003 onclick=qinc()>Sonny</button><button id=corop class=buttons003 onclick=qcor()>Vito</button><br/>",
},
{
"cat":"70s",
"ques":"What European country did Serpico move to after retiring from the police force?",
"answ":"SWITZERLAND",
"answ2":"Switzerland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Germany</button><button id=corop class=buttons003 onclick=qcor()>Switzerland</button><button id=incop3 class=buttons003 onclick=qinc()>Greece</button><button id=incop4 class=buttons003 onclick=qinc()>Denmark</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays Rudyard Kipling in the 1975 adventure film The Man Who Would Be King?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Christopher Plummer</button><button id=incop2 class=buttons003 onclick=qinc()>Sean Connery</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Caine</button><button id=incop4 class=buttons003 onclick=qinc()>Jack Nicholson</button><br/>",
},
{
"cat":"70s",
"ques":"The irreverent adventures of Hawkeye Pierce and Trapper John can be found in what Robert Altman film?",
"answ":"M*A*S*H",
"answ3":"MASH",
"answ2":"MASH.",
"option":"<button id=corop class=buttons003 onclick=qcor()>MASH</button><button id=incop2 class=buttons003 onclick=qinc()>Nashville</button><button id=incop3 class=buttons003 onclick=qinc()>The Long Goodbye</button><button id=incop4 class=buttons003 onclick=qinc()>Thieves Like Us</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays Annie's troubled brother Duane in Annie Hall?",
"answ":"CHRISTOPHER WALKEN",
"answ2":"Christopher Walken.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeff Daniels</button><button id=corop class=buttons003 onclick=qcor()>Christopher Walken</button><button id=incop3 class=buttons003 onclick=qinc()>Alan Alda</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Murray</button><br/>",
},
{
"cat":"70s",
"ques":"Who played the role of the shy teenage girl named Holly in Terrence Malick's Badlands?",
"answ":"SISSY SPACEK",
"answ2":"Sissy Spacek.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sissy Spacek</button><button id=incop2 class=buttons003 onclick=qinc()>Jodie Foster</button><button id=incop3 class=buttons003 onclick=qinc()>Sally Field</button><button id=incop4 class=buttons003 onclick=qinc()>Cybill Shepherd</button><br/>",
},
{
"cat":"70s",
"ques":"What 1971 film marked the directorial debut of George Lucas?",
"answ":"THX 1138",
"answ2":"THX 1138.",
"option":"<button id=corop class=buttons003 onclick=qcor()>THX 1138</button><button id=incop2 class=buttons003 onclick=qinc()>Star Wars</button><button id=incop3 class=buttons003 onclick=qinc()>American Graffiti</button><button id=incop4 class=buttons003 onclick=qinc()>Kagemusha</button><br/>",
},
{
"cat":"70s",
"ques":"In All the President's Men, where did Bob Woodward have all of his secret meetings with Deep Throat?",
"answ":"PARKING GARAGE",
"answ3":"IN A PARKING GARAGE",
"answ2":"Parking garage.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Parking garage</button><button id=incop2 class=buttons003 onclick=qinc()>Restaurant</button><button id=incop3 class=buttons003 onclick=qinc()>Movie theater</button><button id=incop4 class=buttons003 onclick=qinc()>Gas station</button><br/>",
},
{
"cat":"70s",
"ques":"Who starred as hitman Arthur Bishop in the original 1972 film The Mechanic?",
"answ":"CHARLES BRONSON",
"answ2":"Charles Bronson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Charles Bronson</button><button id=incop2 class=buttons003 onclick=qinc()>Lee Marvin</button><button id=incop3 class=buttons003 onclick=qinc()>Ernest Borgnine</button><button id=incop4 class=buttons003 onclick=qinc()>Clint Eastwood</button><br/>",
},
{
"cat":"70s",
"ques":"Who played Detective Hercule Poirot in the 1974 version of Murder on the Orient Express?",
"answ":"ALBERT FINNEY",
"answ2":"Albert Finney.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Albert Finney</button><button id=incop2 class=buttons003 onclick=qinc()>Peter Ustinov</button><button id=incop3 class=buttons003 onclick=qinc()>Ian Holm</button><button id=incop4 class=buttons003 onclick=qinc()>Alec Guinness</button><br/>",
},
{
"cat":"70s",
"ques":"In the 1975 cult classic Death Race 2000, the lead character is named after what Universal horror monster?",
"answ":"FRANKENSTEIN",
"answ3":"FRANKENSTEIN'S MONSTER",
"answ2":"Frankenstein.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Frankenstein</button><button id=incop2 class=buttons003 onclick=qinc()>Mummy</button><button id=incop3 class=buttons003 onclick=qinc()>Dracula</button><button id=incop4 class=buttons003 onclick=qinc()>Wolf man</button><br/>",
},
{
"cat":"70s",
"ques":"Who played the titular character in 1977's MacArthur?",
"answ":"GREGORY PECK",
"answ2":"Gregory Peck.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gregory Peck</button><button id=incop2 class=buttons003 onclick=qinc()>David Warner</button><button id=incop3 class=buttons003 onclick=qinc()>Charles Bronson</button><button id=incop4 class=buttons003 onclick=qinc()>Laurence Olivier</button><br/>",
},
{
"cat":"70s",
"ques":"In 1976's Taxi Driver, what name does Travis tell the Secret Service agent his name is?",
"answ":"HENRY",
"answ3":"HENRY KRINKLE",
"answ2":"Henry Krinkle.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Henry Krinkle</button><button id=incop2 class=buttons003 onclick=qinc()>Lennie Briscoe</button><button id=incop3 class=buttons003 onclick=qinc()>Mac Gargan</button><button id=incop4 class=buttons003 onclick=qinc()>Mike Haggar</button><br/>",
},
{
"cat":"70s",
"ques":"What is the name of the fighter that Rocky fights in the very first fight in the original Rocky film?",
"answ":"SPIDER RICO",
"answ2":"Spider Rico.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mickey Goldmill</button><button id=corop class=buttons003 onclick=qcor()>Spider Rico</button><button id=incop3 class=buttons003 onclick=qinc()>Mason Dixon</button><button id=incop4 class=buttons003 onclick=qinc()>Union Cane</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays the role of Victoria Brisbane in 1977's High Anxiety?",
"answ":"MADELINE KAHN",
"answ2":"Madeline Kahn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Diane Keaton</button><button id=corop class=buttons003 onclick=qcor()>Madeline Kahn</button><button id=incop3 class=buttons003 onclick=qinc()>Ellen Burstyn</button><button id=incop4 class=buttons003 onclick=qinc()>Faye Dunaway</button><br/>",
},
{
"cat":"70s",
"ques":"Who plays Ostap Bender, a homeless con-artist in 1970's The Twelve Chairs?",
"answ":"FRANK LANGELLA",
"answ2":"Frank Langella.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Donald Pleasence</button><button id=corop class=buttons003 onclick=qcor()>Frank Langella</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Mitchum</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Lee</button><br/>",
},
{
"cat":"70s",
"ques":"Which famous comedic actor played Doctor Ross in Woody Allen's cult hit Everything You Always Wanted To Know About Sex?",
"answ":"GENE WILDER",
"answ2":"Gene Wilder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Walter Matthau</button><button id=incop2 class=buttons003 onclick=qinc()>Peter Sellars</button><button id=incop3 class=buttons003 onclick=qinc()>Jerry Lewis</button><button id=corop class=buttons003 onclick=qcor()>Gene Wilder</button><br/>",
},
{
"cat":"70s",
"ques":"Who directed 1971's Dirty Harry?",
"answ":"DON SIEGEL",
"answ3":"DON SEGEL",
"answ2":"Don Siegel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Clint Eastwood</button><button id=corop class=buttons003 onclick=qcor()>Don Siegel</button><button id=incop3 class=buttons003 onclick=qinc()>Ted Post</button><button id=incop4 class=buttons003 onclick=qinc()>James Fargo</button><br/>",
},
{
"cat":"70s",
"ques":"In Monty Python and the Holy Grail, what does the French taunter say 'your mother smells' like?",
"answ":"ELDERBERRIES",
"answ2":"Elderberries.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Strawberries</button><button id=corop class=buttons003 onclick=qcor()>Elderberries</button><button id=incop3 class=buttons003 onclick=qinc()>Blueberries</button><button id=incop4 class=buttons003 onclick=qinc()>Apples</button><br/>",
},
{
"cat":"70s",
"ques":"Jack Nicholson played a therapist in what 1975 musical based on music by The Who?",
"answ":"TOMMY",
"answ2":"Tommy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Imagine</button><button id=corop class=buttons003 onclick=qcor()>Tommy</button><button id=incop3 class=buttons003 onclick=qinc()>Veronica</button><button id=incop4 class=buttons003 onclick=qinc()>Marco</button><br/>",
},
];
seventies = shuffle(seventies);
r2Q21 = shuffle(r2Q21);