var moviereleasedates = [
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of William Friedkin's classic The French Connection?",
"answ":"1971",
"answ2":"1971.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was the remake of The Wicker Man starring Nicolas Cage released?",
"answ":"2006",
"answ2":"2006.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the original Dawn of the Dead?",
"answ":"1978",
"answ2":"1978.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Rosemary's Baby released?",
"answ":"1968",
"answ2":"1968.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Scary Movie 2?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was It Follows released in theaters?",
"answ":"2015",
"answ2":"2015.",
},
{
"cat":"Movie Release Dates",
"ques":"In which year was David Lynch's Eraserhead released?",
"answ":"1977",
"answ2":"1977.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was Zack Snyder's remake of Dawn of the Dead released?",
"answ":"2004",
"answ2":"2004.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was original Fright Night released?",
"answ":"1985",
"answ2":"1985.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was the remake of Poltergeist starring Sam Rockwell released?",
"answ":"2015",
"answ2":"2015.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was The Conjuring released?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Cabin in the Woods released?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Training Day?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Terminator 2: Judgement Day released?",
"answ":"1991",
"answ2":"1991.",
},
{
"cat":"Movie Release Dates",
"ques":"The sports classic Rocky came out in what year?",
"answ":"1976",
"answ2":"1976.",
},
{
"cat":"Movie Release Dates",
"ques":"Schindler's List was released in what year?",
"answ":"1993",
"answ2":"1993.",
},
{
"cat":"Movie Release Dates",
"ques":"Happy Death Day was released in what year?",
"answ":"2017",
"answ2":"2017.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year did G.I. Joe: Retaliation come out?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of True Lies?",
"answ":"1994",
"answ2":"1994.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the films Glory, Tim Burton's Batman and Born on the Fourth of July?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Movie Release Dates",
"ques":"Fatal Attraction, Evil Dead II and Good Morning, Vietnam! were all released in what year?",
"answ":"1987",
"answ2":"1987.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Warrior and Tinker Tailor Soldier Spy?",
"answ":"2011",
"answ2":"2011.",
},
{
"cat":"Movie Release Dates",
"ques":"2009 saw the release of what Quentin Tarantino film?",
"answ":"INGLOURIOUS BASTERDS",
"answ3":"INGLORIOUS BASTERDS",
"answ2":"Inglourious Basterds.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Braveheart, Heat and Se7en?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Movie Release Dates",
"ques":"Good Night and Good Luck, Munich and Brokeback Mountain all came out in what year?",
"answ":"2005",
"answ2":"2005.",
},
{
"cat":"Movie Release Dates",
"ques":"Harry Potter and the Goblet of Fire was released in what year?",
"answ":"2005",
"answ2":"2005.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Back to the Future Part 2?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Home Alone 2: Lost in New York released?",
"answ":"1992",
"answ2":"1992.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Pixar's Wall-E?",
"answ":"2008",
"answ2":"2008.",
},
{
"cat":"Movie Release Dates",
"ques":"Gangs of New York, Road to Perdition and Men in Black 2 all came out in what year?",
"answ":"2002",
"answ2":"2002.",
},
{
"cat":"Movie Release Dates",
"ques":"Harry Potter and the Chamber of Secrets was released in what year?",
"answ":"2002",
"answ2":"2002.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was Die Hard released?",
"answ":"1988",
"answ2":"1988.",
},
{
"cat":"Movie Release Dates",
"ques":"Both Kramer vs Kramer and Manhattan were released in what year?",
"answ":"1979",
"answ2":"1979.",
},
{
"cat":"Movie Release Dates",
"ques":"Paul Newman first appeared as Fast Eddie Felson in The Hustler released in what year?",
"answ":"1961",
"answ2":"1961.",
},
{
"cat":"Movie Release Dates",
"ques":"The world first met the Minions in Despicable Me released in what year?",
"answ":"2010",
"answ2":"2010.",
},
{
"cat":"Movie Release Dates",
"ques":"Which romance film was released first: The Wedding Planner, 500 Days of Summer or Sweet Home Alabama?",
"answ":"THE WEDDING PLANNER",
"answ3":"WEDDING PLANNER",
"answ2":"The Wedding Planner.",
},
{
"cat":"Movie Release Dates",
"ques":"Mighty Morpin' Power Rangers: The Movie was released into theaters in what year?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Movie Release Dates",
"ques":"George Miller's The Road Warrior was released in what year?",
"answ":"1981",
"answ2":"1981.",
},
{
"cat":"Movie Release Dates",
"ques":"What year did The Wrestler come out?",
"answ":"2008",
"answ2":"2008.",
},
{
"cat":"Movie Release Dates",
"ques":"Which Sylvester Stallone film was released first: Rambo First Blood Part 2 or Rocky IV?",
"answ":"RAMBO FIRST BLOOD PART 2",
"answ3":"FIRST BLOOD PART 2",
"answ2":"Rambo First Blood Part 2.",
},
{
"cat":"Movie Release Dates",
"ques":"The original Tremors starring Fred Ward and Kevin Bacon was released in what year?",
"answ":"1990",
"answ2":"1990.",
},
{
"cat":"Movie Release Dates",
"ques":"DreamWorks' Kung Fu Panda was released in what year?",
"answ":"2008",
"answ2":"2008.",
},
{
"cat":"Movie Release Dates",
"ques":"Star Trek Insurrection was released in what year?",
"answ":"1998",
"answ2":"1998.",
},
{
"cat":"Movie Release Dates",
"ques":"Will Smith and Martin Lawrence first teamed up in the classic action comedy Bad Boys in what year?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Movie Release Dates",
"ques":"Alfonso Cuaron's sci-fi drama Children of Men was released in what year?",
"answ":"2006",
"answ2":"2006.",
},
{
"cat":"Movie Release Dates",
"ques":"Billy Wilder wrote and directed The Spirit of St. Louis, Love in the Afternoon, and Witness for the Prosecution in what very busy year?",
"answ":"1957",
"answ2":"1957.",
},
{
"cat":"Movie Release Dates",
"ques":"Pixar's Cars was released in what year?",
"answ":"2006",
"answ2":"2006.",
},
{
"cat":"Movie Release Dates",
"ques":"Pretty Woman starring Julia Roberts was released in what year?",
"answ":"1990",
"answ2":"1990.",
},
{
"cat":"Movie Release Dates",
"ques":"Steven Spielberg's War Horse and The Adventures of Tin Tin were both released in what year?",
"answ":"2011",
"answ2":"2011.",
},
{
"cat":"Movie Release Dates",
"ques":"Gretchen Wieners tried to make 'fetch' happen in Mean Girls which hit theaters in what year?",
"answ":"2004",
"answ2":"2004.",
},
{
"cat":"Movie Release Dates",
"ques":"Which Denzel Washington film was released first: Remember the Titans, Man on Fire or The Hurricane?",
"answ":"THE HURRICANE",
"answ2":"The Hurricane.",
},
{
"cat":"Movie Release Dates",
"ques":"The Schwarzenegger comedy Twins was released in what year?",
"answ":"1988",
"answ2":"1988.",
},
{
"cat":"Movie Release Dates",
"ques":"Which of these 90s action movies came out first: The Rock, GoldenEye or Timecop?",
"answ":"TIMECOP",
"answ2":"Timecop.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the fantasy buddy comic film R.I.P.D.?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Movie Release Dates",
"ques":"Which came out first: 48 Hrs or Beverly Hills Cop?",
"answ":"48 HRS",
"answ3":"48 HOURS",
"answ2":"48 Hrs.",
},
{
"cat":"Movie Release Dates",
"ques":"Disney's A Goofy Movie and Pocahontas were both released in what year?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Movie Release Dates",
"ques":"Sylvester Stallone's disaster film Daylight was released in what year?",
"answ":"1996",
"answ2":"1996.",
},
{
"cat":"Movie Release Dates",
"ques":"Which of these 3 Mel Brooks films were released first: Young Frankenstein, High Anxiety or Blazing Saddles?",
"answ":"BLAZING SADDLES",
"answ2":"Blazing Saddles.",
},
{
"cat":"Movie Release Dates",
"ques":"The Hunger Games went from book to the big screen in what year?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was the classic Citizen Kane released?",
"answ":"1941",
"answ2":"1941.",
},
{
"cat":"Movie Release Dates",
"ques":"Adam Sandler starred in both The Wedding Singer and The Waterboy in what year?",
"answ":"1998",
"answ2":"1998.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Dumb and Dumber?",
"answ":"1994",
"answ2":"1994.",
},
{
"cat":"Movie Release Dates",
"ques":"Independence Day had Will Smith and Jeff Goldblum save the world in what year?",
"answ":"1996",
"answ2":"1996.",
},
{
"cat":"Movie Release Dates",
"ques":"Of the following 3 Jim Carrey films, which came out last: The Mask, Dumb & Dumber or Ace Ventura: Pet Detective?",
"answ":"DUMB AND DUMBER",
"answ2":"Dumb & Dumber.",
},
{
"cat":"Movie Release Dates",
"ques":"The Lord of the Rings: The Fellowship of the Ring was released in what year?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Movie Release Dates",
"ques":"Spike Jonze's sci-fi romance, Her, was released in what year?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Movie Release Dates",
"ques":"Tim Burton's Beetlejuice was released in what year?",
"answ":"1988",
"answ2":"1988.",
},
{
"cat":"Movie Release Dates",
"ques":"Eternal Sunshine of the Spotless Mind and Finding Neverland were both released in what year?",
"answ":"2004",
"answ2":"2004.",
},
{
"cat":"Movie Release Dates",
"ques":"Tobe Hooper's original Texas Chainsaw Massacre was released in what year?",
"answ":"1974",
"answ2":"1974.",
},
{
"cat":"Movie Release Dates",
"ques":"Which 1 of these 4 films were NOT released in the same year: Spider-Man, School of Rock, The Ring or Ice Age?",
"answ":"SCHOOL OF ROCK",
"answ2":"School of Rock.",
},
{
"cat":"Movie Release Dates",
"ques":"Disney's feel-good sports biopic Cool Runnings was released in what year?",
"answ":"1993",
"answ2":"1993.",
},
{
"cat":"Movie Release Dates",
"ques":"George Miller's dystopian action classic Mad Max was released in what year?",
"answ":"1979",
"answ2":"1979.",
},
{
"cat":"Movie Release Dates",
"ques":"Jamie Foxx received Oscar nominations for his performances in both Ray and Collateral which were released in what year?",
"answ":"2004",
"answ2":"2004.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of these classic monster movies: Frankenstein, Dracula, and Dr. Jekyll and Mr. Hyde?",
"answ":"1931",
"answ2":"1931.",
},
{
"cat":"Movie Release Dates",
"ques":"Which of these 80s comedies were released first: Weird Science, Big or Planes, Train and Automobiles?",
"answ":"WEIRD SCIENCE",
"answ2":"Weird Science.",
},
{
"cat":"Movie Release Dates",
"ques":"The sci-fi thriller Twelve Monkeys was released in what year?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Movie Release Dates",
"ques":"The 40 Year-Old Virgin was released in what year?",
"answ":"2005",
"answ2":"2005.",
},
{
"cat":"Movie Release Dates",
"ques":"What year was Superman Returns released?",
"answ":"2006",
"answ2":"2006.",
},
{
"cat":"Movie Release Dates",
"ques":"In which year was the John Carpenter classic Halloween released?",
"answ":"1978",
"answ2":"1978.",
},
{
"cat":"Movie Release Dates",
"ques":"The sports classics Major League and Field of Dreams were both released in what year?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Movie Release Dates",
"ques":"The modern comedy classic The Hangover exploded into theaters in what year?",
"answ":"2009",
"answ2":"2009.",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Robin Williams film Patch Adams?",
"answ":"1998",
"answ2":"1998.",
},
{
"cat":"Movie Release Dates",
"ques":"The sci-fi classics Blade Runner and Star Trek II: The Wrath of Khan were released in what year?",
"answ":"1982",
"answ2":"1982.",
},
{
"cat":"Movie Release Dates",
"ques":"Quentin Tarantino's raw western Django Unchained was released in what year?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Movie Release Dates",
"ques":"The horror classic Evil Dead II was released in what year?",
"answ":"1987",
"answ2":"1987.",
},
{
"cat":"Movie Release Dates",
"ques":"Modern pulp adventure film The Mummy, with Brendan Fraser, hit theaters in what year?",
"answ":"1999",
"answ2":"1999.",
},
{
"cat":"Movie Release Dates",
"ques":"The Spielberg classic Close Encounters of the Third Kind was released in what year?",
"answ":"1977",
"answ2":"1977.",
},
{
"cat":"Movie Release Dates",
"ques":"Which 1 of these 4 films were NOT released in the same year: Red Dawn, Amadeus, Witness or Footloose?",
"answ":"WITNESS",
"answ2":"Witness.",
},
{
"cat":"Movie Release Dates",
"ques":"The Three Musketeers film starring Charlie Sheen, Chris O'Donnell, Oliver Platt and Kiefer Sutherland was released in what year?",
"answ":"1993",
"answ2":"1993.",
},
{
"cat":"Movie Release Dates",
"ques":"X-Men First Class was released in what year?",
"answ":"2011",
"answ2":"2011.",
},
{
"cat":"Movie Release Dates",
"ques":"The Fox and the Hound, Stripes and Escape from New York were all released in what year?",
"answ":"1981",
"answ2":"1981.",
},
{
"cat":"Movie Release Dates",
"ques":"In what year were both Matrix Reloaded and Matrix Revolutions released?",
"answ":"2003",
"answ2":"2003.",
},
{
"cat":"Movie Release Dates",
"ques":"Star Wars: The Phantom Menace was released in what year?",
"answ":"1999",
"answ2":"1999.",
},
{
"cat":"Movie Release Dates",
"ques":"Marty McFly and Doc Brown head to the wild west in Back to the Future Part III released in what year?",
"answ":"1990",
"answ2":"1990.",
},
{
"cat":"Movie Release Dates",
"ques":"The Disney animated films Bambi and Saludos Amigos were both released in what year?",
"answ":"1942",
"answ2":"1942.",
},
{
"cat":"Movie Release Dates",
"ques":"Other than 2016, what year features films from the following franchises: Harry Potter, Batman & Star Wars?",
"answ":"2005",
"answ2":"2005.",
},
{
"cat":"Movie Release Dates",
"ques":"David Fincher's The Game was released in what year?",
"answ":"1997",
"answ2":"1997.",
},
{
"cat":"Movie Release Dates",
"ques":"The Harry Potter series first debuted on the big screen with Harry Potter and the Sorcerer's Stone in what year?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Movie Release Dates",
"ques":"The Disney animated classics Cinderella, Peter Pan and Sleeping Beauty were all released in what decade?",
"answ":"1950S",
"answ3":"50S",
"answ2":"1950s.",
},
{
"cat":"Movie Release Dates",
"ques":"John Woo's sci-fi action film Face/Off was released in what year?",
"answ":"1997",
"answ2":"1997.",
},
{
"cat":"Movie Release Dates",
"ques":"The horror classic Scream hit theaters in what year?",
"answ":"1996",
"answ2":"1996.",
},
{
"cat":"Movie Release Dates",
"ques":"What year revelled in the Christmas spirit with the release of Love Actually, Bad Santa and Elf?",
"answ":"2003",
"answ2":"2003.",
},
];
var r2Q22 = [
{
"cat":"Movie Release Dates",
"ques":"What year was Braveheart released?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1999</button><button id=incop3 class=buttons003 onclick=qinc()>1994</button><button id=corop class=buttons003 onclick=qcor()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did the first Alvin and the Chipmunks movie come out?",
"answ":"2007",
"answ2":"2007.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2006</button><button id=corop class=buttons003 onclick=qcor()>2007</button><button id=incop4 class=buttons003 onclick=qinc()>2012</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did Goodfellas come out?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1989</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop3 class=buttons003 onclick=qinc()>1995</button><button id=incop4 class=buttons003 onclick=qinc()>1997</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did the Val Kilmer comedy Top Secret! come out?",
"answ":"1984",
"answ2":"1984.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1980</button><button id=corop class=buttons003 onclick=qcor()>1984</button><button id=incop3 class=buttons003 onclick=qinc()>1985</button><button id=incop4 class=buttons003 onclick=qinc()>1987</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did the classic horror film The Exorcist come out?",
"answ":"1973",
"answ2":"1973.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1971</button><button id=corop class=buttons003 onclick=qcor()>1973</button><button id=incop3 class=buttons003 onclick=qinc()>1974</button><button id=incop4 class=buttons003 onclick=qinc()>1977</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year was the Bond film Casino Royale starring Daniel Craig released?",
"answ":"2006",
"answ2":"2006.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2006</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2005</button><button id=incop4 class=buttons003 onclick=qinc()>2007</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Taxi Driver released?",
"answ":"1976",
"answ2":"1976.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1976</button><button id=incop2 class=buttons003 onclick=qinc()>1974</button><button id=incop3 class=buttons003 onclick=qinc()>1977</button><button id=incop4 class=buttons003 onclick=qinc()>1979</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year did Toy Story 2 come out?",
"answ":"1999",
"answ2":"1999.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1999</button><button id=incop2 class=buttons003 onclick=qinc()>2000</button><button id=incop3 class=buttons003 onclick=qinc()>2001</button><button id=incop4 class=buttons003 onclick=qinc()>2002</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the original Planet of the Apes starring Charlton Heston?",
"answ":"1968",
"answ2":"1968.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1968</button><button id=incop2 class=buttons003 onclick=qinc()>1967</button><button id=incop3 class=buttons003 onclick=qinc()>1966</button><button id=incop4 class=buttons003 onclick=qinc()>1969</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Lord of the Rings: The Return of the King was released in what year?",
"answ":"2003",
"answ2":"2003.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2001</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2002</button><button id=corop class=buttons003 onclick=qcor()>2003</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The sci-fi classic Metropolis was released in which year?",
"answ":"1927",
"answ2":"1927.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1929</button><button id=incop2 class=buttons003 onclick=qinc()>1935</button><button id=incop3 class=buttons003 onclick=qinc()>1938</button><button id=corop class=buttons003 onclick=qcor()>1927</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of John Ford's classic western The Searchers?",
"answ":"1956",
"answ2":"1956.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1952</button><button id=incop2 class=buttons003 onclick=qinc()>1954</button><button id=incop3 class=buttons003 onclick=qinc()>1955</button><button id=corop class=buttons003 onclick=qcor()>1956</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Rain Man was released in which year?",
"answ":"1988",
"answ2":"1988.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1991</button><button id=incop2 class=buttons003 onclick=qinc()>1985</button><button id=incop3 class=buttons003 onclick=qinc()>1990</button><button id=corop class=buttons003 onclick=qcor()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the coming-of-age classic Sixteen Candles?",
"answ":"1984",
"answ2":"1984.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1984</button><button id=incop2 class=buttons003 onclick=qinc()>1985</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=incop4 class=buttons003 onclick=qinc()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Eternal Sunshine of the Spotless Mind released?",
"answ":"2004",
"answ2":"2004.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2004</button><button id=incop2 class=buttons003 onclick=qinc()>2000</button><button id=incop3 class=buttons003 onclick=qinc()>2002</button><button id=incop4 class=buttons003 onclick=qinc()>2003</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Godfather Part II released?",
"answ":"1974",
"answ2":"1974.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1974</button><button id=incop2 class=buttons003 onclick=qinc()>1976</button><button id=incop3 class=buttons003 onclick=qinc()>1973</button><button id=incop4 class=buttons003 onclick=qinc()>1972</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Home Alone released?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1991</button><button id=incop2 class=buttons003 onclick=qinc()>1992</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop4 class=buttons003 onclick=qinc()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Lego Movie released?",
"answ":"2014",
"answ2":"2014.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2015</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=corop class=buttons003 onclick=qcor()>2014</button><button id=incop4 class=buttons003 onclick=qinc()>2012</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Kevin Spacey crime drama L.A. Confidential?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1993</button><button id=incop2 class=buttons003 onclick=qinc()>1998</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Stanley Kubrick's war opus Full Metal Jacket came out in which year?",
"answ":"1987",
"answ2":"1987.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1983</button><button id=incop2 class=buttons003 onclick=qinc()>1988</button><button id=corop class=buttons003 onclick=qcor()>1987</button><button id=incop4 class=buttons003 onclick=qinc()>1985</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Disney's second animated feature, Pinocchio?",
"answ":"1940",
"answ2":"1940.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1938</button><button id=incop2 class=buttons003 onclick=qinc()>1939</button><button id=corop class=buttons003 onclick=qcor()>1940</button><button id=incop4 class=buttons003 onclick=qinc()>1941</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year did the coming-of-age movie St. Elmo's Fire hit theaters?",
"answ":"1985",
"answ2":"1985.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1986</button><button id=incop2 class=buttons003 onclick=qinc()>1984</button><button id=corop class=buttons003 onclick=qcor()>1985</button><button id=incop4 class=buttons003 onclick=qinc()>1983</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Hook, Sleeping with the Enemy and The Addams Family were released in what year?",
"answ":"1991",
"answ2":"1991.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1994</button><button id=incop3 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1991</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Pixar classic Finding Nemo was released in what year?",
"answ":"2003",
"answ2":"2003.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2000</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=corop class=buttons003 onclick=qcor()>2003</button><button id=incop4 class=buttons003 onclick=qinc()>2001</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Batman Forever starring Val Kilmer as Bruce Wayne was released in what year?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1992</button><button id=incop2 class=buttons003 onclick=qinc()>1993</button><button id=incop3 class=buttons003 onclick=qinc()>1994</button><button id=corop class=buttons003 onclick=qcor()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Carrie and All the President's Men were both released in what year?",
"answ":"1976",
"answ2":"1976.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1972</button><button id=incop2 class=buttons003 onclick=qinc()>1973</button><button id=incop3 class=buttons003 onclick=qinc()>1974</button><button id=corop class=buttons003 onclick=qcor()>1976</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the hit comedy Bridesmaids?",
"answ":"2011",
"answ2":"2011.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2012</button><button id=incop2 class=buttons003 onclick=qinc()>2008</button><button id=incop3 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2011</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Singin' in the Rain was released in what year?",
"answ":"1952",
"answ2":"1952.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1951</button><button id=incop2 class=buttons003 onclick=qinc()>1953</button><button id=incop3 class=buttons003 onclick=qinc()>1956</button><button id=corop class=buttons003 onclick=qcor()>1952</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year was the sci-fi action film Aliens released?",
"answ":"1986",
"answ2":"1986.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1983</button><button id=incop2 class=buttons003 onclick=qinc()>1984</button><button id=incop3 class=buttons003 onclick=qinc()>1985</button><button id=corop class=buttons003 onclick=qcor()>1986</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did Lord of the Rings: The Two Towers come out?",
"answ":"2002",
"answ2":"2002.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2000</button><button id=incop2 class=buttons003 onclick=qinc()>2003</button><button id=incop3 class=buttons003 onclick=qinc()>2001</button><button id=corop class=buttons003 onclick=qcor()>2002</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Robin Williams gave life to the Genie in Disney's Aladdin in what year?",
"answ":"1992",
"answ2":"1992.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1993</button><button id=incop3 class=buttons003 onclick=qinc()>1991</button><button id=corop class=buttons003 onclick=qcor()>1992</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Notting Hill, She's All That and Never Been Kissed were released in what year?",
"answ":"1999",
"answ2":"1999.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1996</button><button id=incop2 class=buttons003 onclick=qinc()>1997</button><button id=incop3 class=buttons003 onclick=qinc()>1998</button><button id=corop class=buttons003 onclick=qcor()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The sword and sorcery film The Beastmaster was released in what year?",
"answ":"1982",
"answ2":"1982.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1981</button><button id=corop class=buttons003 onclick=qcor()>1982</button><button id=incop3 class=buttons003 onclick=qinc()>1983</button><button id=incop4 class=buttons003 onclick=qinc()>1987</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Scorsese's early triumph Mean Streets was released in what year?",
"answ":"1973",
"answ2":"1973.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1971</button><button id=corop class=buttons003 onclick=qcor()>1973</button><button id=incop3 class=buttons003 onclick=qinc()>1974</button><button id=incop4 class=buttons003 onclick=qinc()>1977</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Edgar Wright's Shaun of the Dead was released in what year?",
"answ":"2004",
"answ2":"2004.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2003</button><button id=corop class=buttons003 onclick=qcor()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2005</button><button id=incop4 class=buttons003 onclick=qinc()>2006</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Fifth Element, Con Air and Batman & Robin were all released in what year?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop3 class=buttons003 onclick=qinc()>1998</button><button id=incop4 class=buttons003 onclick=qinc()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The original Ghostbusters was released in what year?",
"answ":"1984",
"answ2":"1984.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1984</button><button id=incop2 class=buttons003 onclick=qinc()>1987</button><button id=incop3 class=buttons003 onclick=qinc()>1988</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Toy Story 3?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2008</button><button id=corop class=buttons003 onclick=qcor()>2010</button><button id=incop3 class=buttons003 onclick=qinc()>2012</button><button id=incop4 class=buttons003 onclick=qinc()>2013</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Sean Penn thriller Mystic River was released in what year?",
"answ":"2003",
"answ2":"2003.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2002</button><button id=corop class=buttons003 onclick=qcor()>2003</button><button id=incop3 class=buttons003 onclick=qinc()>2004</button><button id=incop4 class=buttons003 onclick=qinc()>2005</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Road House, Field of Dreams and Ghostbusters II share what release year?",
"answ":"1989",
"answ2":"1989.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1987</button><button id=corop class=buttons003 onclick=qcor()>1989</button><button id=incop3 class=buttons003 onclick=qinc()>1990</button><button id=incop4 class=buttons003 onclick=qinc()>1992</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Amazing Spider-Man released?",
"answ":"2012",
"answ2":"2012.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2011</button><button id=corop class=buttons003 onclick=qcor()>2012</button><button id=incop3 class=buttons003 onclick=qinc()>2013</button><button id=incop4 class=buttons003 onclick=qinc()>2014</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Tarantino's Inglourious Basterds was released in what year?",
"answ":"2009",
"answ2":"2009.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2007</button><button id=corop class=buttons003 onclick=qcor()>2009</button><button id=incop3 class=buttons003 onclick=qinc()>2011</button><button id=incop4 class=buttons003 onclick=qinc()>2012</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Bram Stoker's Dracula was released in what year?",
"answ":"1992",
"answ2":"1992.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1991</button><button id=corop class=buttons003 onclick=qcor()>1992</button><button id=incop4 class=buttons003 onclick=qinc()>1993</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the war drama G.I. Jane?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1993</button><button id=incop2 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Rain Man, Coming To America and Bull Durham were all released in what year?",
"answ":"1988",
"answ2":"1988.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1986</button><button id=incop2 class=buttons003 onclick=qinc()>1987</button><button id=corop class=buttons003 onclick=qcor()>1988</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year was the Oscar nominated film The Kids Are All Right released?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2008</button><button id=incop2 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2010</button><button id=incop4 class=buttons003 onclick=qinc()>2011</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the first How to Train Your Dragon?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2008</button><button id=incop2 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2010</button><button id=incop4 class=buttons003 onclick=qinc()>2011</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Bill & Ted's Excellent Adventure was released in what year?",
"answ":"1989",
"answ2":"1989.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1987</button><button id=incop2 class=buttons003 onclick=qinc()>1988</button><button id=corop class=buttons003 onclick=qcor()>1989</button><button id=incop4 class=buttons003 onclick=qinc()>1990</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Forrest Gump was released in what year?",
"answ":"1994",
"answ2":"1994.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1992</button><button id=incop2 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1994</button><button id=incop4 class=buttons003 onclick=qinc()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Die Hard 2 was released in what year?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1992</button><button id=incop2 class=buttons003 onclick=qinc()>1991</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was V for Vendetta released?",
"answ":"2006",
"answ2":"2006.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2003</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2005</button><button id=corop class=buttons003 onclick=qcor()>2006</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the John Hughes classic The Breakfast Club?",
"answ":"1985",
"answ2":"1985.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1982</button><button id=incop2 class=buttons003 onclick=qinc()>1983</button><button id=corop class=buttons003 onclick=qcor()>1985</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Dallas Buyers Club was released in what year?",
"answ":"2013",
"answ2":"2013.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2010</button><button id=incop2 class=buttons003 onclick=qinc()>2011</button><button id=corop class=buttons003 onclick=qcor()>2013</button><button id=incop4 class=buttons003 onclick=qinc()>2015</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Clueless?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1993</button><button id=incop2 class=buttons003 onclick=qinc()>1994</button><button id=corop class=buttons003 onclick=qcor()>1995</button><button id=incop4 class=buttons003 onclick=qinc()>1996</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"John Carpenter's Big Trouble in Little China punched its way to theaters in what year?",
"answ":"1986",
"answ2":"1986.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1984</button><button id=corop class=buttons003 onclick=qcor()>1986</button><button id=incop3 class=buttons003 onclick=qinc()>1988</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Jim Carrey played Truman Burbank in The Truman Show, released in what year?",
"answ":"1998",
"answ2":"1998.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1997</button><button id=corop class=buttons003 onclick=qcor()>1998</button><button id=incop3 class=buttons003 onclick=qinc()>1999</button><button id=incop4 class=buttons003 onclick=qinc()>2000</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The war drama The Thin Red Line was released in what year?",
"answ":"1998",
"answ2":"1998.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1997</button><button id=corop class=buttons003 onclick=qcor()>1998</button><button id=incop3 class=buttons003 onclick=qinc()>1999</button><button id=incop4 class=buttons003 onclick=qinc()>2000</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Apollo 13 released?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1994</button><button id=corop class=buttons003 onclick=qcor()>1995</button><button id=incop3 class=buttons003 onclick=qinc()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Tim Burton's Sweeney Todd: The Demon Barber of Fleet Street was released in what year?",
"answ":"2007",
"answ2":"2007.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2006</button><button id=corop class=buttons003 onclick=qcor()>2007</button><button id=incop3 class=buttons003 onclick=qinc()>2008</button><button id=incop4 class=buttons003 onclick=qinc()>2009</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Sam Raimi's horror classic The Evil Dead creeped onto the silver screen in what year?",
"answ":"1981",
"answ2":"1981.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1980</button><button id=corop class=buttons003 onclick=qcor()>1981</button><button id=incop3 class=buttons003 onclick=qinc()>1983</button><button id=incop4 class=buttons003 onclick=qinc()>1985</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Clint Eastwood classic Dirty Harry was released in what year?",
"answ":"1971",
"answ2":"1971.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1970</button><button id=corop class=buttons003 onclick=qcor()>1971</button><button id=incop3 class=buttons003 onclick=qinc()>1973</button><button id=incop4 class=buttons003 onclick=qinc()>1975</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did the comedy Three Man and a Baby come out?",
"answ":"1987",
"answ2":"1987.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1983</button><button id=incop2 class=buttons003 onclick=qinc()>1985</button><button id=corop class=buttons003 onclick=qcor()>1987</button><button id=incop4 class=buttons003 onclick=qinc()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"We saw Carl Fredricksen attach a bunch of balloons to his house and fly away in Up in what year?",
"answ":"2009",
"answ2":"2009.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2008</button><button id=corop class=buttons003 onclick=qcor()>2009</button><button id=incop4 class=buttons003 onclick=qinc()>2010</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Vince Vaughn comedy Old School was released in what year?",
"answ":"2003",
"answ2":"2003.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2001</button><button id=corop class=buttons003 onclick=qcor()>2003</button><button id=incop3 class=buttons003 onclick=qinc()>2004</button><button id=incop4 class=buttons003 onclick=qinc()>2006</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Julia Roberts films My Best Friend's Wedding and Conspiracy Theory?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1995</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop3 class=buttons003 onclick=qinc()>1998</button><button id=incop4 class=buttons003 onclick=qinc()>2000</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Christopher Nolan's Inception entered our dreams and theaters in the summer of what year?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2010</button><button id=incop3 class=buttons003 onclick=qinc()>2011</button><button id=incop4 class=buttons003 onclick=qinc()>2012</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Tim Burton's Sleepy Hollow was released in what year?",
"answ":"1999",
"answ2":"1999.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1995</button><button id=incop2 class=buttons003 onclick=qinc()>1996</button><button id=incop3 class=buttons003 onclick=qinc()>1998</button><button id=corop class=buttons003 onclick=qcor()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Annie Hall released?",
"answ":"1977",
"answ2":"1977.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1972</button><button id=incop2 class=buttons003 onclick=qinc()>1974</button><button id=incop3 class=buttons003 onclick=qinc()>1975</button><button id=corop class=buttons003 onclick=qcor()>1977</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Terminator 3: Rise of the Machines?",
"answ":"2003",
"answ2":"2003.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2001</button><button id=incop2 class=buttons003 onclick=qinc()>2002</button><button id=corop class=buttons003 onclick=qcor()>2003</button><button id=incop4 class=buttons003 onclick=qinc()>2004</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Will Smith film Hancock?",
"answ":"2008",
"answ2":"2008.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2007</button><button id=corop class=buttons003 onclick=qcor()>2008</button><button id=incop4 class=buttons003 onclick=qinc()>2009</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Richard Linklater's Dazed and Confused was released in what year?",
"answ":"1993",
"answ2":"1993.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1991</button><button id=corop class=buttons003 onclick=qcor()>1993</button><button id=incop4 class=buttons003 onclick=qinc()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The war comedy M.A.S.H. was released in what year?",
"answ":"1970",
"answ2":"1970.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1970</button><button id=incop2 class=buttons003 onclick=qinc()>1971</button><button id=incop3 class=buttons003 onclick=qinc()>1973</button><button id=incop4 class=buttons003 onclick=qinc()>1975</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"White House Down and Olympus Has Fallen were released in what year?",
"answ":"2013",
"answ2":"2013.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2010</button><button id=incop2 class=buttons003 onclick=qinc()>2011</button><button id=corop class=buttons003 onclick=qcor()>2013</button><button id=incop4 class=buttons003 onclick=qinc()>2015</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Liar Liar and Austin Powers International Man of Mystery?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1995</button><button id=incop2 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1998</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Mel Gibson and Helen Hunt film What Women Want?",
"answ":"2000",
"answ2":"2000.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1998</button><button id=incop2 class=buttons003 onclick=qinc()>1999</button><button id=corop class=buttons003 onclick=qcor()>2000</button><button id=incop4 class=buttons003 onclick=qinc()>2002</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the original Disney's The Jungle Book?",
"answ":"1967",
"answ2":"1967.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1966</button><button id=incop2 class=buttons003 onclick=qinc()>1968</button><button id=corop class=buttons003 onclick=qcor()>1967</button><button id=incop4 class=buttons003 onclick=qinc()>1969</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year was Caddyshack released?",
"answ":"1980",
"answ2":"1980.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1977</button><button id=incop2 class=buttons003 onclick=qinc()>1978</button><button id=corop class=buttons003 onclick=qcor()>1980</button><button id=incop4 class=buttons003 onclick=qinc()>1981</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Godfather Part III released?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1987</button><button id=incop2 class=buttons003 onclick=qinc()>1989</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop4 class=buttons003 onclick=qinc()>1991</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was the first Harry Potter movie released?",
"answ":"2001",
"answ2":"2001.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2004</button><button id=incop2 class=buttons003 onclick=qinc()>2003</button><button id=incop3 class=buttons003 onclick=qinc()>2002</button><button id=corop class=buttons003 onclick=qcor()>2001</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was the iconic Pulp Fiction released?",
"answ":"1994",
"answ2":"1994.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1991</button><button id=incop3 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1994</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Spider-Man 2?",
"answ":"2004",
"answ2":"2004.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2000</button><button id=incop2 class=buttons003 onclick=qinc()>2001</button><button id=incop3 class=buttons003 onclick=qinc()>2003</button><button id=corop class=buttons003 onclick=qcor()>2004</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the first Toy Story movie?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1992</button><button id=incop2 class=buttons003 onclick=qinc()>1993</button><button id=incop3 class=buttons003 onclick=qinc()>1994</button><button id=corop class=buttons003 onclick=qcor()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the Hitchcock classic Psycho?",
"answ":"1960",
"answ2":"1960.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1963</button><button id=incop2 class=buttons003 onclick=qinc()>1955</button><button id=incop3 class=buttons003 onclick=qinc()>1958</button><button id=corop class=buttons003 onclick=qcor()>1960</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Name the year the following movies were released: Ordinary People, Stir Crazy, The Blues Brothers.",
"answ":"1980",
"answ2":"1980.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1975</button><button id=incop2 class=buttons003 onclick=qinc()>1977</button><button id=incop3 class=buttons003 onclick=qinc()>1978</button><button id=corop class=buttons003 onclick=qcor()>1980</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the first Friday the 13th film?",
"answ":"1980",
"answ2":"1980.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1975</button><button id=incop2 class=buttons003 onclick=qinc()>1977</button><button id=incop3 class=buttons003 onclick=qinc()>1978</button><button id=corop class=buttons003 onclick=qcor()>1980</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Batman & Robin was released in what year?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1994</button><button id=incop2 class=buttons003 onclick=qinc()>1995</button><button id=incop3 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1997</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the animated films The Road to El Dorado, Chicken Run and Titan A.E.?",
"answ":"2000",
"answ2":"2000.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2004</button><button id=incop2 class=buttons003 onclick=qinc()>2002</button><button id=incop3 class=buttons003 onclick=qinc()>1999</button><button id=corop class=buttons003 onclick=qcor()>2000</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Fantastic Beasts and Where to Find Them was released in what year?",
"answ":"2016",
"answ2":"2016.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2013</button><button id=incop2 class=buttons003 onclick=qinc()>2014</button><button id=incop3 class=buttons003 onclick=qinc()>2015</button><button id=corop class=buttons003 onclick=qcor()>2016</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Jackie Chan and Chris Tucker first joined forces in Rush Hour which was released in what year?",
"answ":"1998",
"answ2":"1998.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1998</button><button id=incop3 class=buttons003 onclick=qinc()>1999</button><button id=incop4 class=buttons003 onclick=qinc()>2000</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Crocodile Dundee was released in what year?",
"answ":"1986",
"answ2":"1986.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1984</button><button id=corop class=buttons003 onclick=qcor()>1986</button><button id=incop3 class=buttons003 onclick=qinc()>1988</button><button id=incop4 class=buttons003 onclick=qinc()>1990</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Oliver Stone's historical drama, JFK, was released in what year?",
"answ":"1991",
"answ2":"1991.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=corop class=buttons003 onclick=qcor()>1991</button><button id=incop3 class=buttons003 onclick=qinc()>1992</button><button id=incop4 class=buttons003 onclick=qinc()>1993</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Indiana Jones and the Temple of Doom, Splash and Romancing the Stone were all released in what year?",
"answ":"1984",
"answ2":"1984.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1982</button><button id=corop class=buttons003 onclick=qcor()>1984</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=incop4 class=buttons003 onclick=qinc()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Pee-wee's Big Adventure was released in what year?",
"answ":"1985",
"answ2":"1985.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1983</button><button id=corop class=buttons003 onclick=qcor()>1985</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=incop4 class=buttons003 onclick=qinc()>1988</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Paul Verhoeven's action sci-fi thriller, Total Recall, was released in what year?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1988</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop3 class=buttons003 onclick=qinc()>1992</button><button id=incop4 class=buttons003 onclick=qinc()>1994</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The first Mission Impossible film came out in what year?",
"answ":"1996",
"answ2":"1996.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1995</button><button id=corop class=buttons003 onclick=qcor()>1996</button><button id=incop3 class=buttons003 onclick=qinc()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1998</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Double Dragon and Street Fighter both came out in what year?",
"answ":"1994",
"answ2":"1994.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1994</button><button id=incop3 class=buttons003 onclick=qinc()>1996</button><button id=incop4 class=buttons003 onclick=qinc()>1997</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Spider-Man 3 was released in what year?",
"answ":"2007",
"answ2":"2007.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=corop class=buttons003 onclick=qcor()>2007</button><button id=incop3 class=buttons003 onclick=qinc()>2008</button><button id=incop4 class=buttons003 onclick=qinc()>2009</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The first Iron Man was released in what year?",
"answ":"2008",
"answ2":"2008.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2007</button><button id=corop class=buttons003 onclick=qcor()>2008</button><button id=incop4 class=buttons003 onclick=qinc()>2009</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of the family classic Honey, I Shrunk the Kids?",
"answ":"1989",
"answ2":"1989.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1986</button><button id=incop2 class=buttons003 onclick=qinc()>1988</button><button id=corop class=buttons003 onclick=qcor()>1989</button><button id=incop4 class=buttons003 onclick=qinc()>1990</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"John Carpenter's The Thing was released on the same day as what other legendary sci-fi film?",
"answ":"BLADE RUNNER",
"answ2":"Blade Runner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>E.T. The Extra-Terrestrial</button><button id=incop2 class=buttons003 onclick=qinc()>Tron</button><button id=corop class=buttons003 onclick=qcor()>Blade Runner</button><button id=incop4 class=buttons003 onclick=qinc()>Star Wars</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Harry Potter and the Prisoner of Azkaban was released in what year?",
"answ":"2004",
"answ2":"2004.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2002</button><button id=corop class=buttons003 onclick=qcor()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2003</button><button id=incop4 class=buttons003 onclick=qinc()>2005</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Kevin Costner 'danced' with the wolves in Dances with Wolves which was released in what year?",
"answ":"1990",
"answ2":"1990.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1988</button><button id=incop2 class=buttons003 onclick=qinc()>1989</button><button id=corop class=buttons003 onclick=qcor()>1990</button><button id=incop4 class=buttons003 onclick=qinc()>1992</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The King's Speech was released in what year?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2007</button><button id=incop2 class=buttons003 onclick=qinc()>2008</button><button id=incop3 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2010</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The very first RoboCop starring Peter Weller was released in what year?",
"answ":"1987",
"answ2":"1987.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1981</button><button id=incop2 class=buttons003 onclick=qinc()>1983</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=corop class=buttons003 onclick=qcor()>1987</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Lethal Weapon 2 was released in what year?",
"answ":"1989",
"answ2":"1989.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1984</button><button id=incop2 class=buttons003 onclick=qinc()>1985</button><button id=incop3 class=buttons003 onclick=qinc()>1987</button><button id=corop class=buttons003 onclick=qcor()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was the James Dean classic Rebel Without a Cause released?",
"answ":"1955",
"answ2":"1955.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1950</button><button id=incop2 class=buttons003 onclick=qinc()>1952</button><button id=incop3 class=buttons003 onclick=qinc()>1953</button><button id=corop class=buttons003 onclick=qcor()>1955</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Sandra Bullock film While You Were Sleeping was released in what year?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1990</button><button id=incop2 class=buttons003 onclick=qinc()>1992</button><button id=incop3 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1995</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Daniel Day-Lewis 'drank' your milkshake in There Will Be Blood which was released in what year?",
"answ":"2007",
"answ2":"2007.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2004</button><button id=incop2 class=buttons003 onclick=qinc()>2005</button><button id=incop3 class=buttons003 onclick=qinc()>2006</button><button id=corop class=buttons003 onclick=qcor()>2007</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"10 Things I Hate About You was released in what year?",
"answ":"1999",
"answ2":"1999.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1994</button><button id=incop2 class=buttons003 onclick=qinc()>1996</button><button id=incop3 class=buttons003 onclick=qinc()>1997</button><button id=corop class=buttons003 onclick=qcor()>1999</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year did Slumdog Millionaire come out?",
"answ":"2008",
"answ2":"2008.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2006</button><button id=incop3 class=buttons003 onclick=qinc()>2007</button><button id=corop class=buttons003 onclick=qcor()>2008</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Robert Redford and Paul Newman teamed up in The Sting, which was released in what year?",
"answ":"1973",
"answ2":"1973.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1968</button><button id=incop2 class=buttons003 onclick=qinc()>1969</button><button id=incop3 class=buttons003 onclick=qinc()>1971</button><button id=corop class=buttons003 onclick=qcor()>1973</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Speed, starring Keanu Reeves?",
"answ":"1994",
"answ2":"1994.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1991</button><button id=incop2 class=buttons003 onclick=qinc()>1992</button><button id=incop3 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1994</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of The Day After Tomorrow?",
"answ":"2004",
"answ2":"2004.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2000</button><button id=incop2 class=buttons003 onclick=qinc()>2002</button><button id=incop3 class=buttons003 onclick=qinc()>2003</button><button id=corop class=buttons003 onclick=qcor()>2004</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Shutter Island released?",
"answ":"2010",
"answ2":"2010.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2006</button><button id=incop2 class=buttons003 onclick=qinc()>2008</button><button id=incop3 class=buttons003 onclick=qinc()>2009</button><button id=corop class=buttons003 onclick=qcor()>2010</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Top Gun was released in what year?",
"answ":"1986",
"answ2":"1986.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1983</button><button id=incop2 class=buttons003 onclick=qinc()>1984</button><button id=incop3 class=buttons003 onclick=qinc()>1985</button><button id=corop class=buttons003 onclick=qcor()>1986</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Trouble with the Curve released?",
"answ":"2012",
"answ2":"2012.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2012</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=incop3 class=buttons003 onclick=qinc()>2014</button><button id=incop4 class=buttons003 onclick=qinc()>2016</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw Boris Karloff debut as Frankenstein, and Bela Lugosi debut as Dracula in their respective movies?",
"answ":"1931",
"answ2":"1931.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1939</button><button id=incop2 class=buttons003 onclick=qinc()>1932</button><button id=incop3 class=buttons003 onclick=qinc()>1934</button><button id=corop class=buttons003 onclick=qcor()>1931</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Fast Times at Ridgemont High was released in what year?",
"answ":"1982",
"answ2":"1982.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1989</button><button id=incop2 class=buttons003 onclick=qinc()>1983</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=corop class=buttons003 onclick=qcor()>1982</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Basic Instinct, The Crying Game, and Alien 3 all came out in what year?",
"answ":"1992",
"answ2":"1992.",
"option":"<button id=corop class=buttons003 onclick=qcor()>1992</button><button id=incop2 class=buttons003 onclick=qinc()>1990</button><button id=incop3 class=buttons003 onclick=qinc()>1994</button><button id=incop4 class=buttons003 onclick=qinc()>1996</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year did the very first movie in the Fast and Furious franchise start off this successful franchise?",
"answ":"2001",
"answ2":"2001.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2001</button><button id=incop2 class=buttons003 onclick=qinc()>2000</button><button id=incop3 class=buttons003 onclick=qinc()>2004</button><button id=incop4 class=buttons003 onclick=qinc()>2003</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"The Michael Douglas film The American President was released in what year?",
"answ":"1995",
"answ2":"1995.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1995</button><button id=incop3 class=buttons003 onclick=qinc()>1993</button><button id=incop4 class=buttons003 onclick=qinc()>1998</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was DiCaprio's J. Edgar film released?",
"answ":"2011",
"answ2":"2011.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2011</button><button id=incop2 class=buttons003 onclick=qinc()>2009</button><button id=incop3 class=buttons003 onclick=qinc()>2008</button><button id=incop4 class=buttons003 onclick=qinc()>2013</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was The Wolf of Wall Street released?",
"answ":"2013",
"answ2":"2013.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2013</button><button id=incop2 class=buttons003 onclick=qinc()>2014</button><button id=incop3 class=buttons003 onclick=qinc()>2015</button><button id=incop4 class=buttons003 onclick=qinc()>2016</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Willow was released in what year?",
"answ":"1988",
"answ2":"1988.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1984</button><button id=incop2 class=buttons003 onclick=qinc()>1986</button><button id=corop class=buttons003 onclick=qcor()>1988</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of Nightcrawler, starring Jake Gyllenhaal?",
"answ":"2014",
"answ2":"2014.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2013</button><button id=corop class=buttons003 onclick=qcor()>2014</button><button id=incop3 class=buttons003 onclick=qinc()>2015</button><button id=incop4 class=buttons003 onclick=qinc()>2016</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year did Wes Craven return to the Nightmare franchise with Wes Craven's New Nightmare?",
"answ":"1994",
"answ2":"1994.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1993</button><button id=corop class=buttons003 onclick=qcor()>1994</button><button id=incop3 class=buttons003 onclick=qinc()>1995</button><button id=incop4 class=buttons003 onclick=qinc()>1996</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Iron Man 3 released?",
"answ":"2013",
"answ2":"2013.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2011</button><button id=incop2 class=buttons003 onclick=qinc()>2012</button><button id=corop class=buttons003 onclick=qcor()>2013</button><button id=incop4 class=buttons003 onclick=qinc()>2014</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"In what year was Best Picture Winner No Country For Old Men released?",
"answ":"2007",
"answ2":"2007.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2005</button><button id=incop2 class=buttons003 onclick=qinc()>2006</button><button id=corop class=buttons003 onclick=qcor()>2007</button><button id=incop4 class=buttons003 onclick=qinc()>2008</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Gareth Edwards directed the monster film Godzilla that came out in what year?",
"answ":"2014",
"answ2":"2014.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2012</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=corop class=buttons003 onclick=qcor()>2014</button><button id=incop4 class=buttons003 onclick=qinc()>2015</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"What year saw the release of La La Land?",
"answ":"2016",
"answ2":"2016.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2014</button><button id=incop2 class=buttons003 onclick=qinc()>2015</button><button id=corop class=buttons003 onclick=qcor()>2016</button><button id=incop4 class=buttons003 onclick=qinc()>2017</button><br/>",
},
{
"cat":"Movie Release Dates",
"ques":"Weird Science was released in what year?",
"answ":"1985",
"answ2":"1985.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1982</button><button id=incop2 class=buttons003 onclick=qinc()>1984</button><button id=corop class=buttons003 onclick=qcor()>1985</button><button id=incop4 class=buttons003 onclick=qinc()>1987</button><br/>",
},
];
moviereleasedates = shuffle(moviereleasedates);
r2Q22 = shuffle(r2Q22);