var moviequotes = [
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'By Grapthar's hammer, you shall be avenged!'",
"answ":"GALAXY QUEST",
"answ2":"Galaxy Quest.",
},
{
"cat":"Movie Quotes",
"ques":"From which movie is this quote: 'There's nothing stronger than the heart of a volunteer'?",
"answ":"PEARL HARBOR",
"answ2":"Pearl Harbor.",
},
{
"cat":"Movie Quotes",
"ques":"From which movie is this quote: 'They may take away our lives, but they'll never take our freedom!'?",
"answ":"BRAVEHEART",
"answ2":"Braveheart.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: '$10,000 dollars for me by myself. For that, you get the head, the tail - the whole damn thing.'",
"answ":"JAWS",
"answ2":"Jaws.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'He's not the Messiah. He's a very naughty boy!'",
"answ":"MONTY PYTHON'S LIFE OF BRIAN",
"answ3":"LIFE OF BRIAN",
"answ2":"Monty Python's Life of Brian.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Let's go to the Winchester, have a pint and wait for this to all blow over'",
"answ":"SHAUN OF THE DEAD",
"answ2":"Shaun of the Dead.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Man who catch fly with chopstick accomplish anything.'",
"answ":"THE KARATE KID",
"answ2":"The Karate Kid.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Oh my gosh, look at that fluffy unicorn! He's so fluffy, I'm gonna die!'",
"answ":"DESPICABLE ME",
"answ2":"Despicable Me.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I don't understand. All my life I've been waiting for someone and when I find her, she's ... she's a fish.'",
"answ":"SPLASH",
"answ2":"Splash.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Are you not entertained! Are you not entertained! Is this not why you are here!'",
"answ":"GLADIATOR",
"answ2":"Gladiator.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I'm just one stomach flu away from my goal weight.'",
"answ":"THE DEVIL WEARS PRADA",
"answ2":"The Devil Wears Prada.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Sunnyside is a place of ruin and despair, ruled by an evil bear who smells of strawberries!'",
"answ":"TOY STORY 3",
"answ2":"Toy Story 3.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'But I'm funny how?, I mean, funny like I'm a clown?, I amuse you?'",
"answ":"GOODFELLAS",
"answ2":"GoodFellas.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I'm your number one fan. There's nothing to worry about. You're gonna be just fine. I'll take good care of you. I'm your number one fan.'",
"answ":"MISERY",
"answ2":"Misery.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'That's what's great about the outdoors, you know. It's one giant toilet.'",
"answ":"THE BIG CHILL",
"answ2":"The Big Chill.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'It's 106 miles to Chicago, we got a full tank of gas, half a pack of cigarettes, it's dark, and we're wearing sunglasses.'",
"answ":"THE BLUES BROTHERS",
"answ2":"The Blues Brothers.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Excuse me, is that your nose, or did a bus park on your face?'",
"answ":"ROXANNE",
"answ2":"Roxanne.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'So tell me, Eddie, is that a rabbit in your pocket, or are you just happy to see me?'",
"answ":"WHO FRAMED ROGER RABBIT",
"answ2":"Who Framed Roger Rabbit.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'On second thought, let's not go to Camelot. It is a silly place.'",
"answ":"MONTY PYTHON AND THE HOLY GRAIL",
"answ2":"Monty Python and the Holy Grail.",
},
{
"cat":"Movie Quotes",
"ques":"What Oscar-winning blockbuster has the line: 'I figure life's a gift and I don't intend on wasting it. You don't know what hand you're gonna get dealt next.'?",
"answ":"TITANIC",
"answ2":"Titanic.",
},
{
"cat":"Movie Quotes",
"ques":"Which Disney animated film has the line: 'I tried to run away and be a good guy. But I'm not! I'm just a bad guy.'?",
"answ":"WRECK IT RALPH",
"answ2":"Wreck-It-Ralph.",
},
{
"cat":"Movie Quotes",
"ques":"What 90s film is known for the line 'Just when I think you couldn't possibly be any dumber, you go and do something like this and totally redeem yourself!'?",
"answ":"DUMB AND DUMBER",
"answ2":"Dumb and Dumber.",
},
{
"cat":"Movie Quotes",
"ques":"'I don't want to come off as arrogant here, but I'm the greatest botanist on this planet' is said by Matt Damon in what film?",
"answ":"THE MARTIAN",
"answ2":"The Martian.",
},
{
"cat":"Movie Quotes",
"ques":"The famously ad-libbed line: 'I'm walking here! I'm walking here!' is from what 1969 movie?",
"answ":"MIDNIGHT COWBOY",
"answ2":"Midnight Cowboy.",
},
{
"cat":"Movie Quotes",
"ques":"Which 2017 horror film features the line: 'By the way, I would have voted for Obama a third term, if I could.'?",
"answ":"GET OUT",
"answ2":"Get Out.",
},
{
"cat":"Movie Quotes",
"ques":"What 90s historical epic is known for the line: 'They may take our lives, but they'll never take our freedom'?",
"answ":"BRAVEHEART",
"answ2":"Braveheart.",
},
{
"cat":"Movie Quotes",
"ques":"What film from director Oliver Stone has the following line: 'Life all comes down to a few moments. This is one of them.'?",
"answ":"WALL STREET",
"answ2":"Wall Street.",
},
{
"cat":"Movie Quotes",
"ques":"In what 90s film does Tom Cruise say the line: 'Help me help you'?",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
},
{
"cat":"Movie Quotes",
"ques":"What classic film coined the line: 'There's no place like home'?",
"answ":"THE WIZARD OF OZ",
"answ3":"WIZARD OF OZ",
"answ2":"The Wizard of Oz.",
},
{
"cat":"Movie Quotes",
"ques":"What 1933 classic adventure film coined the line 'It wasn't the airplanes. It was Beauty killed the Beast'?",
"answ":"KING KONG",
"answ2":"King Kong.",
},
{
"cat":"Movie Quotes",
"ques":"In what 1993 thriller will you find the quote: 'Well, think me up a cup of coffee and a chocolate doughnut with some of those little sprinkles on top, while you're thinking'?",
"answ":"THE FUGITIVE",
"answ2":"The Fugitive.",
},
{
"cat":"Movie Quotes",
"ques":"Which Quentin Tarantino film has the line: 'Anybody accidentally kills anybody in a fight, they go to jail. It's called manslaughter.'",
"answ":"ONCE UPON A TIME IN HOLLYWOOD",
"answ2":"Once Upon a Time in Hollywood.",
},
{
"cat":"Movie Quotes",
"ques":"What 90s film has the line: 'Hope is a good thing, maybe the best of things, and no good thing ever dies.'",
"answ":"THE SHAWSHANK REDEMPTION",
"answ3":"SHAWSHANK REDEMPTION",
"answ2":"The Shawshank Redemption.",
},
{
"cat":"Movie Quotes",
"ques":"What 2010 action movie, based on a TV show, features the famous line: 'I love it when a plan comes together'?",
"answ":"THE A TEAM",
"answ3":"A TEAM",
"answ2":"The A-Team.",
},
{
"cat":"Movie Quotes",
"ques":"What crime film has the line: 'The greatest trick the devil ever pulled was convincing the world he did not exist'",
"answ":"THE USUAL SUSPECTS",
"answ3":"USUAL SUSPECTS",
"answ2":"The Usual Suspects.",
},
{
"cat":"Movie Quotes",
"ques":"What classic monster movie originated the line: 'It's Alive! It's Alive!'",
"answ":"FRANKENSTEIN",
"answ2":"Frankenstein.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Tower, this is Ghost Rider requesting a flyby.'",
"answ":"TOP GUN",
"answ2":"Top Gun.",
},
{
"cat":"Movie Quotes",
"ques":"In what 1983 film will you hear a criminal say 'The world is yours!'",
"answ":"SCARFACE",
"answ2":"Scarface.",
},
{
"cat":"Movie Quotes",
"ques":"What 80s film is known for the line: 'Nobody puts Baby in a corner'?",
"answ":"DIRTY DANCING",
"answ2":"Dirty Dancing.",
},
{
"cat":"Movie Quotes",
"ques":"What 80s action film is known for the line: 'Come out to the coast, we'll together, have a few laughs...'",
"answ":"DIE HARD",
"answ2":"Die Hard.",
},
{
"cat":"Movie Quotes",
"ques":"What 1980s film features the line: 'Are you trying to tell me my mother has got the hots for me?'",
"answ":"BACK TO THE FUTURE",
"answ2":"Back to the Future.",
},
{
"cat":"Movie Quotes",
"ques":"In what 1987 sci-fi film will you find the quote: 'Dead or alive, you're coming with me'",
"answ":"ROBOCOP",
"answ2":"RoboCop.",
},
{
"cat":"Movie Quotes",
"ques":"In what film will you hear Daniel Day-Lewis famously say: 'I drink your milkshake!'",
"answ":"THERE WILL BE BLOOD",
"answ2":"There Will Be Blood.",
},
{
"cat":"Movie Quotes",
"ques":"Which Disney animated classic is known for the line: 'Always let your conscience be your guide?'",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Movie Quotes",
"ques":"What 90s film has the line: 'I guess it comes down to a simple choice, really. Get busy living, or get busy dying.'",
"answ":"THE SHAWSHANK REDEMPTION",
"answ3":"SHAWSHANK REDEMPTION",
"answ2":"The Shawshank Redemption.",
},
{
"cat":"Movie Quotes",
"ques":"What 2004 sports movie has the quote: 'Nobody makes me bleed my own blood!.... Nobody!'",
"answ":"DODGEBALL",
"answ3":"DODGEBALL A TRUE UNDERDOG STORY",
"answ2":"Dodgeball.",
},
{
"cat":"Movie Quotes",
"ques":"What family film has the line 'Keep the change, you filthy animal.'",
"answ":"HOME ALONE",
"answ2":"Home Alone.",
},
{
"cat":"Movie Quotes",
"ques":"What film features the immortal lines: 'Surely you can't be serious.' 'I am serious...and don't call me Shirley'?",
"answ":"AIRPLANE",
"answ2":"Airplane!.",
},
{
"cat":"Movie Quotes",
"ques":"Which 80s movie features the quote: 'We've got a hundred six miles to Chicago, we've got a full tank of gas, half a pack of cigarettes, it's dark, and we're wearing sunglasses.'",
"answ":"THE BLUES BROTHERS",
"answ3":"BLUES BROTHERS",
"answ2":"The Blues Brothers.",
},
{
"cat":"Movie Quotes",
"ques":"What iconic villain says: 'I find your lack of faith disturbing'",
"answ":"DARTH VADER",
"answ2":"Darth Vader.",
},
{
"cat":"Movie Quotes",
"ques":"In what classic film will you hear the quote: 'Here's looking at you, kid.'",
"answ":"CASABLANCA",
"answ2":"Casablanca.",
},
{
"cat":"Movie Quotes",
"ques":"What Tarantino film finds a character stating: 'Gentlemen, you had my curiosity, now you have my attention.'",
"answ":"DJANGO UNCHAINED",
"answ2":"Django Unchained.",
},
{
"cat":"Movie Quotes",
"ques":"In what film does Daniel-Day Lewis say: 'You stay alive, no matter what occurs! I will find you! No matter how long it takes, no matter how far. I will find you!'",
"answ":"LAST OF THE MOHICANS",
"answ3":"THE LAST OF THE MOHICANS",
"answ2":"The Last of the Mohicans.",
},
{
"cat":"Movie Quotes",
"ques":"Name the sci-fi comedy that features quote: 'I want the people to know that they still have 2 out of 3 branches of the government working for them, and that ain't bad.'",
"answ":"MARS ATTACKS",
"answ2":"Mars Attacks!.",
},
{
"cat":"Movie Quotes",
"ques":"The quote: 'You mean you have to use your hands? That's like a baby's toy' is featured in which time travel film?",
"answ":"BACK TO THE FUTURE PART II",
"answ3":"BACK TO THE FUTURE PART 2",
"answ2":"Back to the Future Part II.",
},
{
"cat":"Movie Quotes",
"ques":"Finish the quote from Terminator 2: 'I need your clothes, your boots, and your ____'",
"answ":"MOTORCYCLE",
"answ2":"Motorcycle.",
},
{
"cat":"Movie Quotes",
"ques":"In what 90s horror film will you hear the quote: 'Do you like scary movies?'?",
"answ":"SCREAM",
"answ2":"Scream.",
},
{
"cat":"Movie Quotes",
"ques":"In what 80s movie will you hear the quote: 'If it bleeds, we can kill it.'",
"answ":"PREDATOR",
"answ2":"Predator.",
},
{
"cat":"Movie Quotes",
"ques":"What 2004 comedy features the line: 'It's terrible. She has beautiful eyes, and her hair smells like cinnamon.'?",
"answ":"ANCHORMAN THE LEGEND OF RON BURGUNDY",
"answ3":"ANCHORMAN",
"answ2":"Anchorman The Legend of Ron Burgundy.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Greed, for a lack of a better word, is good.'",
"answ":"WALL STREET",
"answ2":"Wall Street.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie that begins with the narrative line: 'I was 12 going on 13 the first time I saw a dead human being.'",
"answ":"STAND BY ME",
"answ2":"Stand by Me.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'Roads? Where we're going we don't need roads.'",
"answ":"BACK TO THE FUTURE",
"answ2":"Back to the Future.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'I coulda been a contender. I coulda been somebody, instead of a bum, which is what I am.'",
"answ":"ON THE WATERFRONT",
"answ2":"On the Waterfront.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie in which an imaginary Elvis proclaims: 'I like you Clarence. Always have, always will.'",
"answ":"TRUE ROMANCE",
"answ2":"True Romance.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'I honestly think you ought to sit down calmly, take a stress pill and think things over.'",
"answ":"2001 A SPACE ODYSSEY",
"answ3":"2001 A SPACE ODYSEY",
"answ2":"2001: A Space Odyssey.",
},
{
"cat":"Movie Quotes",
"ques":"Finish the quote: 'I have come here to chew ___ and kick ass, and I'm all out of ____'",
"answ":"BUBBLEGUM",
"answ2":"Bubblegum.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Give me that baby you warthog from hell!'",
"answ":"RAISING ARIZONA",
"answ2":"Raising Arizona.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Wise men say forgiveness is divine, but never pay full price for late pizza.'",
"answ":"TEENAGE MUTANT NINJA TURTLES",
"answ2":"Teenage Mutant Ninja Turtles.",
},
{
"cat":"Movie Quotes",
"ques":"What movie character said: 'When Mr. Bigglesworth gets upset people die.'",
"answ":"DR EVIL",
"answ2":"Dr. Evil.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'I'm not bad. I'm just drawn that way.'",
"answ":"WHO FRAMED ROGER RABBIT",
"answ2":"Who Framed Roger Rabbit.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'Fat, drunk and stupid is no way to go through life son.'",
"answ":"ANIMAL HOUSE",
"answ2":"Animal House.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'That's a real badge, I'm a real cop, and this is a real gun.'",
"answ":"LETHAL WEAPON",
"answ2":"Lethal Weapon.",
},
{
"cat":"Movie Quotes",
"ques":"The famous line 'Snap out of it!' is from what movie?",
"answ":"MOONSTRUCK",
"answ2":"Moonstruck.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'This is not 'Nam, this is bowling. There are rules.'",
"answ":"THE BIG LEBOWSKI",
"answ3":"BIG LEBOWSKI",
"answ2":"The Big Lebowski.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'They call me Mr. Tibbs.'",
"answ":"IN THE HEAT OF THE NIGHT",
"answ2":"In the Heat of the Night.",
},
{
"cat":"Movie Quotes",
"ques":"Which comedy features the quote: 'I have nipples Greg, could you milk me?'",
"answ":"MEET THE PARENTS",
"answ2":"Meet the Parents.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I collect spores, molds and fungus.'",
"answ":"GHOSTBUSTERS",
"answ2":"Ghostbusters.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'And I guess that was your accomplice in the woodchipper.'",
"answ":"FARGO",
"answ2":"Fargo.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'You seem a decent fellow, I hate to kill you. You seem a decent fellow, I hate to die.'",
"answ":"THE PRINCESS BRIDE",
"answ3":"PRINCESS BRIDE",
"answ2":"The Princess Bride.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'There's an awful lot you can tell about a person by their shoes.'",
"answ":"FORREST GUMP",
"answ2":"Forrest Gump.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Do you have a bra to match this? Preferably something leather, rubber or barbed wire.'",
"answ":"WEIRD SCIENCE",
"answ2":"Weird Science.",
},
{
"cat":"Movie Quotes",
"ques":"Finish this quote: 'You hear me talking ____ boy. I ain't through with you by a damn sight. I'ma get medieval on your ass.'",
"answ":"HILLBILLY",
"answ2":"Hillbilly.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'It seems to be the only thing you learned is that Caesar is a salad dressing dude.'",
"answ":"BILL AND TED'S EXCELLENT ADVENTURE",
"answ2":"Bill & Ted's Excellent Adventure.",
},
{
"cat":"Movie Quotes",
"ques":"Finish this quote: 'Of all the ____ in all the towns in all the world, she walks into mine.'",
"answ":"GIN JOINTS",
"answ2":"Gin joints.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I was born a poor black child.'",
"answ":"THE JERK",
"answ2":"The Jerk.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'I came across time for you Sarah, I love you, I always have.'",
"answ":"THE TERMINATOR",
"answ3":"TERMINATOR",
"answ2":"The Terminator.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'This'll be fun. We can stay up late swapping manly stories and in the morning I'm making waffles.'",
"answ":"SHREK",
"answ2":"Shrek.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'We've come for your daughter Chuck.'",
"answ":"BEETLEJUICE",
"answ2":"Beetlejuice.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'Gentlemen, you can't fight in here. This is the war room.'",
"answ":"DR STRANGELOVE",
"answ3":"DR STRANGELOVE OR HOW I LEARNED TO STOP WORRYING AND LOVE THE BOMB",
"answ2":"Dr. Strangelove.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'Did you know that bees and dogs can smell fear?'",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'We got cocaine and coffee here. We're gonna get wired and have a big party.'",
"answ":"BEVERLY HILLS COP",
"answ2":"Beverly Hills Cop.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'Yes they deserve to die and I hope they burn in hell!'",
"answ":"A TIME TO KILL",
"answ2":"A Time to Kill.",
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'The list is an absolute good. The list is life. all around its margins lies the gulf.'",
"answ":"SCHINDLER'S LIST",
"answ3":"SCHINDLERS LIST",
"answ2":"Schindler's List.",
},
];
var r2Q23 = [
{
"cat":"Movie Quotes",
"ques":"In Mean Girls, Regina says to Gretchen: 'Stop trying to make ____ happen, it's not gonna happen.'",
"answ":"FETCH",
"answ2":"Fetch.",
"option":["Fetch", "YOLO", "Fudge", "Toast"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie based on a graphic novel: 'An old man dies, a little girl lives. Fair trade.'",
"answ":"SIN CITY",
"answ2":"Sin City.",
"option":["Sin City", "The Witcher", "Watchmen", "Kingsman The Secret Service"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'As long as you can still grab a breath, you fight. You breathe...keep breathing.'",
"answ":"THE REVENANT",
"answ3":"REVENANT",
"answ2":"The Revenant.",
"option":["The Revenant", "Titanic", "The Man in the Iron Mask", "Blood Diamond"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I get to live the rest of my life like a schnook.'",
"answ":"GOODFELLAS",
"answ2":"Goodfellas.",
"option":["Goodfellas", "Casino", "The Godfather", "The Departed"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Good morning, and in case I don't see you: Good afternoon, good evening, and good night.'",
"answ":"THE TRUMAN SHOW",
"answ3":"TRUMAN SHOW",
"answ2":"The Truman Show.",
"option":["The Truman Show", "Dumb and Dumber", "Anchorman: The Legend of Ron Burgundy", "DodgeBall: A True Underdog Story"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'I'm having an old friend for diner.'",
"answ":"THE SILENCE OF THE LAMBS",
"answ3":"SILENCE OF THE LAMBS",
"answ2":"The Silence of the Lambs.",
"option":["The Silence of the Lambs", "A Nightmare on Elm Street", "Se7en", "The Bone Collector"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie featuring the quote: 'I'll have what she's having.'",
"answ":"WHEN HARRY MET SALLY",
"answ2":"When Harry Met Sally...",
"option":["When Harry Met Sally...", "Notting Hill", "You've Got Mail", "The Princess Bride"],
},
{
"cat":"Movie Quotes",
"ques":"Which war movie features the quote: 'You're so ugly, you could be a modern art masterpiece.'?",
"answ":"FULL METAL JACKET",
"answ2":"Full Metal Jacket.",
"option":["Full Metal Jacket", "MASH", "Saving Private Ryan", "Airplane!"],
},
{
"cat":"Movie Quotes",
"ques":"From what Oscar-winning screenplay is the quote: 'I'm already pregnant so what other shenanigans could I get into?'",
"answ":"JUNO",
"answ2":"Juno.",
"option":["Juno", "Midnight in Paris", "Little Miss Sunshine", "Talk to Her"],
},
{
"cat":"Movie Quotes",
"ques":"In what Heath Ledger movie can you hear the line: 'The Pope may be French, but Jesus is English.'?",
"answ":"A KNIGHT'S TALE",
"answ2":"A Knight's Tale.",
"option":["A Knight's Tale", "Brokeback Mountain", "10 Things I Hate About You", "The Brothers Grimm"],
},
{
"cat":"Movie Quotes",
"ques":"Name the 1982 drama featuring the quote: 'I got nowhere else to go.'",
"answ":"AN OFFICER AND A GENTLEMAN",
"answ3":"OFFICER AND A GENTLEMAN",
"answ2":"An Officer and a Gentleman.",
"option":["An Officer and a Gentleman", "Sophie's Choice", "Missing", "The Verdict"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'There are no two words in the English language more harmful than good job.'",
"answ":"WHIPLASH",
"answ2":"Whiplash.",
"option":["Whiplash", "The Post", "Spotlight", "Birdman"],
},
{
"cat":"Movie Quotes",
"ques":"Which actor had the famous line from In the Heat of the Night: 'They call me Mr. Tibbs.'",
"answ":"SIDNEY POITIER",
"answ2":"Sidney Poitier.",
"option":["Sidney Poitier", "Lee Grant", "Rod Steiger", "James Patterson"],
},
{
"cat":"Movie Quotes",
"ques":"Which movie saw Sean Connery utter the famous line: 'You're the man now, dog.'",
"answ":"FINDING FORRESTER",
"answ2":"Finding Forrester.",
"option":["Finding Forrester", "Highlander", "A Bridge Too Far", "The Name of the Rose"],
},
{
"cat":"Movie Quotes",
"ques":"Finish this quote: 'I can't believe I gave my panties to a ____'",
"answ":"GEEK",
"answ2":"Geek.",
"option":["Geek", "Nerd", "Murderer", "Child"],
},
{
"cat":"Movie Quotes",
"ques":"Finish the quote: 'Take your ____ paws off me, you damn dirty ape!'",
"answ":"STINKING",
"answ2":"Stinking.",
"option":["Stinking", "Dirty", "Hairy", "Little"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'What we've got here is failure to communicate.'",
"answ":"COOL HAND LUKE",
"answ2":"Cool Hand Luke.",
"option":["Cool Hand Luke", "Airplane!", "The Shawkshank Redemption", "M*A*S*H"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1968 film would you hear the quote 'Open the pod bay doors, please, HAL'?",
"answ":"2001 A SPACE ODYSSEY",
"answ3":"2001 A SPACE ODDYSEY",
"answ2":"2001 A Space Odyssey.",
"option":["2001 A Space Odyssey", "Alien", "Planet of the Apes", "War of the Worlds"],
},
{
"cat":"Movie Quotes",
"ques":"Finish this quote from 1993's Tombstone. 'I'm your ____'",
"answ":"HUCKLEBERRY",
"answ2":"Huckleberry.",
"option":["Huckleberry", "Friend", "Man", "Guy"],
},
{
"cat":"Movie Quotes",
"ques":"Which famous movie character said the line: 'A boy's best friend is his mother.'",
"answ":"NORMAN BATES",
"answ2":"Norman Bates.",
"option":["Norman Bates", "Hannibal Lecter", "Freddy Krueger", "John Connor"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Throw that shit again, Meat. Throw that weak-ass shit again.'",
"answ":"BULL DURHAM",
"answ2":"Bull Durham.",
"option":["Bull Durham", "Million Dollar Arm", "The Rookie", "The Sandlot"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'You're a funny guy Sully, I like you. That's why I'm gonna kill you last.'",
"answ":"COMMANDO",
"answ2":"Commando.",
"option":["Commando", "Predator", "Last Action Hero", "The Terminator"],
},
{
"cat":"Movie Quotes",
"ques":"What classic actor uttered this famous line from White Heat: 'Made it Ma. Top of the world!'",
"answ":"JAMES CAGNEY",
"answ2":"James Cagney.",
"option":["James Cagney", "James Stewart", "Humphrey Bogart", "Orson Welles"],
},
{
"cat":"Movie Quotes",
"ques":"'I'm kind of a big deal' can be heard in what 2004 comedy?",
"answ":"ANCHORMAN",
"answ3":"ANCHORMAN THE LEGEND OF RON BURGUNDY",
"answ2":"Anchorman: The Legend of Ron Burgundy.",
"option":["Anchorman: The Legend of Ron Burgundy", "Win a Date With Tad Hamilton", "50 First Dates", "Kung Fu Hustle"],
},
{
"cat":"Movie Quotes",
"ques":"What actor said: 'That's what I love about these high school girls man. I get older, they stay the same age.'?",
"answ":"MATTHEW MCCONAUGHEY",
"answ2":"Matthew McConaughey.",
"option":["Matthew McConaughey", "Rob Lowe", "Seann William Scott", "Jason Biggs"],
},
{
"cat":"Movie Quotes",
"ques":"In what beloved animated film will you hear the quote: 'This isn't flying, it's falling with style!'",
"answ":"TOY STORY",
"answ2":"Toy Story.",
"option":["Toy Story", "A Bug's Life", "The Incredibles", "Shrek"],
},
{
"cat":"Movie Quotes",
"ques":"In what 2000s film do you hear the quote: 'I am a golden god!'",
"answ":"ALMOST FAMOUS",
"answ2":"Almost Famous.",
"option":["Almost Famous", "Anchorman: The Legend of Ron Burgundy", "Zoolander", "The Dictator"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie: 'I fart in your general direction. Your mother was a hamster and your father smelt of elderberries.'",
"answ":"MONTY PYTHON AND THE HOLY GRAIL",
"answ2":"Monty Pyton and the Holy Grail.",
"option":["Monty Pyton and the Holy Grail", "Blazing Saddles", "Airplane!", "Monty Python's Life of Brian"],
},
{
"cat":"Movie Quotes",
"ques":"What classic comedy had the final line: 'But you don't understand Osgood. I'm a man! Well, nobody's perfect.'",
"answ":"SOME LIKE IT HOT",
"answ2":"Some Like It Hot.",
"option":["Some Like It Hot", "His Girl Friday", "Bringing Up Baby", "The Producers"],
},
{
"cat":"Movie Quotes",
"ques":"What chilling 1981 movie features the line: 'No wire hangers ever!'",
"answ":"MOMMIE DEAREST",
"answ3":"MOMMY DEAREST",
"answ2":"Mommie Dearest.",
"option":["Mommie Dearest", "An American Werewolf in London", "Blow Out", "The Evil Dead"],
},
{
"cat":"Movie Quotes",
"ques":"Finish the quote from The Godfather: 'Leave the gun, take the ____'",
"answ":"CANNOLI",
"answ3":"CANOLI",
"answ2":"Cannoli.",
"option":["Cannoli", "Knife", "Beans", "Banana"],
},
{
"cat":"Movie Quotes",
"ques":"What classic horror movie ends with this final line of dialogue: 'Why, she wouldn't even harm a fly'?",
"answ":"PSYCHO",
"answ2":"Psycho.",
"option":["Psycho", "The Shining", "Halloween", "Friday the 13th"],
},
{
"cat":"Movie Quotes",
"ques":"'I offered you a chance to be a cop and you blew it' is a line from which 1997 crime film?",
"answ":"COP LAND",
"answ2":"Cop Land.",
"option":["Cop Land", "Face/Off", "L.A. Confidential", "Jackie Brown"],
},
{
"cat":"Movie Quotes",
"ques":"In what 90s comedy will you hear the quote: 'You ain't cool unless you pee your pants'?",
"answ":"BILLY MADISON",
"answ3":"BILLY MADDISON",
"answ2":"Billy Madison.",
"option":["Billy Madison", "Happy Gilmore", "Dumb and Dumber", "American Pie"],
},
{
"cat":"Movie Quotes",
"ques":"What 90s film's last lines are: 'And like that. Poof. He's gone.'",
"answ":"THE USUAL SUSPECTS",
"answ3":"USUAL SUSPECTS",
"answ2":"The Usual Suspects.",
"option":["The Usual Suspects", "The Silence of the Lambs", "The Shawshank Redemption", "Fargo"],
},
{
"cat":"Movie Quotes",
"ques":"Name the 2010 thriller from the quote: 'I gotta get off this rock, Chuck. Get back to the mainland. Whatever the hell's going on here, it's bad.'",
"answ":"SHUTTER ISLAND",
"answ2":"Shutter Island.",
"option":["Shutter Island", "True Grit", "The American", "Green Zone"],
},
{
"cat":"Movie Quotes",
"ques":"What movie contains the quote: 'Define irony. A bunch of idiots dancing on a plane to a song made famous by a band that died in a plane crash.'",
"answ":"CON AIR",
"answ2":"Con Air.",
"option":["Con Air", "The Rock", "Bad Boys", "The Fugitive"],
},
{
"cat":"Movie Quotes",
"ques":"Name the Will Ferrell comedy from the quote: 'You have the voice of an angel. Your voice is like a combination of Fergie and Jesus.'",
"answ":"STEP BROTHERS",
"answ2":"Step Brothers.",
"option":["Step Brothers", "Semi-Pro", "Blades of Glory", "Talladega Nights: The Ballad of Ricky Bobby"],
},
{
"cat":"Movie Quotes",
"ques":"Which horror classic features the line: 'They're coming to get you, Barbara!'",
"answ":"NIGHT OF THE LIVING DEAD",
"answ3":"THE NIGHT OF THE LIVING DEAD",
"answ2":"Night of the Living Dead.",
"option":["Night of the Living Dead", "Halloween", "Friday the 13th", "Psycho"],
},
{
"cat":"Movie Quotes",
"ques":"'Next time you have a chance to kill someone, don't hesitate' is a line from which action favorite?",
"answ":"DIE HARD",
"answ2":"Die Hard.",
"option":["Die Hard", "Commando", "John Wick", "The Terminator"],
},
{
"cat":"Movie Quotes",
"ques":"In Apocalypse Now, Kurtz tells Willard that he is an 'errand boy' sent by whom to collect the bill?",
"answ":"GROCERY CLERKS",
"answ2":"Grocery clerks.",
"option":["Grocery clerks", "The gas company", "The dress shop", "Thugs"],
},
{
"cat":"Movie Quotes",
"ques":"Which 90s Tom Clancy adaptation contains the quote: 'Hey Ryan, be careful what you shoot at. Some things in here don't react too well to bullets.'",
"answ":"THE HUNT FOR RED OCTOBER",
"answ3":"HUNT FOR RED OCTOBER",
"answ2":"The Hunt for Red October.",
"option":["The Hunt for Red October", "Clear and Present Danger", "Patriot Games", "NetForce"],
},
{
"cat":"Movie Quotes",
"ques":"Which 90s crime film features the line: 'You shoot me in a dream, you better wake up and apologize'",
"answ":"RESERVOIR DOGS",
"answ2":"Reservoir Dogs.",
"option":["Reservoir Dogs", "Goodfellas", "The Usual Suspects", "Primal Fear"],
},
{
"cat":"Movie Quotes",
"ques":"In what Ben Affleck film will you hear the quote: 'No matter how much you change, you still have to pay the price for the things you've done'",
"answ":"THE TOWN",
"answ2":"The Town.",
"option":["The Town", "Good Will Hunting", "The Accountant", "Gone Baby Gone"],
},
{
"cat":"Movie Quotes",
"ques":"In what classic holiday film will you find the quote: 'No man is a failure who has friends.'",
"answ":"IT'S A WONDERFUL LIFE",
"answ2":"It's a Wonderful Life.",
"option":["It's a Wonderful Life", "Home Alone", "Scrooged", "Elf"],
},
{
"cat":"Movie Quotes",
"ques":"'I believe in America' is the opening line to what crime classic?",
"answ":"THE GODFATHER",
"answ2":"The Godfather.",
"option":["The Godfather", "Goodfellas", "Scarface", "Reservoir Dogs"],
},
{
"cat":"Movie Quotes",
"ques":"In what film does Clint Eastwood say: 'You see, in this world there are two kinds of people my friend. Those with loaded guns, and those who dig. You dig.'",
"answ":"THE GOOD  THE BAD AND THE UGLY",
"answ3":"THE GOOD THE BAD AND THE UGLY",
"answ2":"The Good, The Bad and the Ugly.",
"option":["The Good, The Bad and the Ugly", "A Fistful of Dollars", "High Plains Drifter", "Unforgiven"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1933 film would you hear the quote: 'Sawyer, you're going out a youngster, but you've got to come back a star!'?",
"answ":"42ND STREET",
"answ2":"42nd Street.",
"option":["42nd Street", "Little Women", "She Done Him Wrong", "Dinner at Eight"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1992 film would you hear the quote: 'There's no crying in baseball!'?",
"answ":"A LEAGUE OF THEIR OWN",
"answ2":"A League of Their Own.",
"option":["A League of Their Own", "Sons Of The Desert", "Soylent Green", "A Streetcar Named Desire"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1951 film would you hear the quote: 'I have always depended on the kindness of strangers.'?",
"answ":"A STREETCAR NAMED DESIRE",
"answ2":"A Streetcar Named Desire.",
"option":["A Streetcar Named Desire", "Casablanca", "The Silence of the Lambs", "The Treasure of the Sierra Madre"],
},
{
"cat":"Movie Quotes",
"ques":"In what comedy can you hear quote: 'What was it we had for dinner tonight? Well, we had a choice of steak or fish. Yes, yes, I remember, I had lasagna.'",
"answ":"AIRPLANE",
"answ2":"Airplane.",
"option":["Airplane", "Top Secret", "Hot Shots", "Caddyshack"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1950 film would you hear the quote: 'Fasten your seatbelts. It's going to be a bumpy night.'?",
"answ":"ALL ABOUT EVE",
"answ2":"All About Eve.",
"option":["All About Eve", "Soylent Green", "Jerry Maguire", "The Wizard of Oz"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1930 film would you hear the quote: 'One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.'?",
"answ":"ANIMAL CRACKERS",
"answ2":"Animal Crackers.",
"option":["Animal Crackers", "Apocalypse Now", "It's a Wonderful Life", "The Wizard of Oz"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1979 film would you hear the quote: 'I love the smell of napalm in the morning.'?",
"answ":"APOCALYPSE NOW",
"answ2":"Apocalypse Now.",
"option":["Apocalypse Now", "Patton", "The Deer Hunter", "Midway"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1995 film would you hear the quote: 'Houston, we have a problem.'?",
"answ":"APOLLO 13",
"answ2":"Apollo 13.",
"option":["Apollo 13", "Lost in Space", "Species", "Trapped in Space"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1958 film would you hear the quote: 'Life is a banquet, and most poor suckers are starving to death!'?",
"answ":"AUNTIE MAME",
"answ2":"Auntie Mame.",
"option":["Auntie Mame", "Casablanca", "The Wizard of Oz", "Shane"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1967 film would you hear the quote: 'We rob banks.'?",
"answ":"BONNIE AND CLYDE",
"answ2":"Bonnie and Clyde.",
"option":["Bonnie and Clyde", "Goldfinger", "Shampoo", "Love Story"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1942 film would you hear the quote:'Louis, I think this is the beginning of a beautiful friendship.'?",
"answ":"CASABLANCA",
"answ2":"Casablanca.",
"option":["Casablanca", "The Silence of the Lambs", "Funny Girl", "Dr. Strangelove"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1942 film would you hear the quote: 'Round up the usual suspects.'?",
"answ":"CASABLANCA",
"answ2":"Casablanca.",
"option":["Casablanca", "Auntie Mame", "A Streetcar Named Desire", "The Sixth Sense"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1942 film would you hear the quote: 'We'll always have Paris.'?",
"answ":"CASABLANCA",
"answ2":"Casablanca.",
"option":["Casablanca", "Gone with the Wind", "A Streetcar Named Desire", "Knute Rockne All American"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1989 film would you hear the quote:'Carpe diem. Seize the day, boys. Make your lives extraordinary.'?",
"answ":"DEAD POETS SOCIETY",
"answ2":"Dead Poets Society.",
"option":["Dead Poets Society", "Gone with the Wind", "The Graduate", "Dirty Dancing"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1971 film would you hear the quote: 'You've got to ask yourself one question: Do I feel lucky? Well, do ya, punk?'",
"answ":"DIRTY HARRY",
"answ2":"Dirty Harry.",
"option":["Dirty Harry", "The Enforcer", "Magnum Force", "Sudden Impact"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1975 film would you hear the quote: 'Attica! Attica!'?",
"answ":"DOG DAY AFTERNOON",
"answ2":"Dog Day Afternoon.",
"option":["Dog Day Afternoon", "The Naughty Nineties", "The Pride Of The Yankees", "To Have And Have Not"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1989 film would you hear the quote: 'If you build it, he will come.'?",
"answ":"FIELD OF DREAMS",
"answ2":"Field of Dreams.",
"option":["Field of Dreams", "The Terminator", "Short Circuit", "Tron"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1994 film would you hear the quote: 'My mama always said life was like a box of chocolates.'?",
"answ":"FORREST GUMP",
"answ2":"Forrest Gump.",
"option":["Forrest Gump", "Taxi Driver", "Star Wars", "2001 A Space Odyssey"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1964 spy film would you hear the the lead ask for 'A martini. Shaken, not stirred.'?",
"answ":"GOLDFINGER",
"answ2":"Goldfinger.",
"option":["Goldfinger", "Thunderball", "Dr. No", "You Only Live Twice"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1939 film would you hear the quote: 'Frankly, my dear, I don't give a damn.'?",
"answ":"GONE WITH THE WIND",
"answ2":"Gone with the Wind.",
"option":["Gone with the Wind", "The Wizard of Oz", "The Naughty Nineties", "She Done Him Wrong"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1939 film would you hear the quote: 'After all, tomorrow is another day!'?",
"answ":"GONE WITH THE WIND",
"answ2":"Gone with the Wind.",
"option":["Gone with the Wind", "She Done Him Wrong", "The Wizard of Oz", "King Kong"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1939 film would you hear the quote: 'As God is my witness, I'll never be hungry again.'?",
"answ":"GONE WITH THE WIND",
"answ2":"Gone with the Wind.",
"option":["Gone with the Wind", "Jaws", "King Kong", "The Terminator"],
},
{
"cat":"Movie Quotes",
"ques":"In what 1997 movie can you find the quote: 'Do you buy all these books retail or do you send away for, like, a shrink kit that comes with all these volumes included?'",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
"option":["Good Will Hunting", "Awakenings", "In 'n' Out", "Analyze This"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1975 film would you hear the quote: 'You're gonna need a bigger boat.'?",
"answ":"JAWS",
"answ2":"Jaws.",
"option":["Jaws", "All About Eve", "The Terminator", "The Graduate"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1996 film would you hear the quote: 'Show me the money!'?",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
"option":["Jerry Maguire", "The Cable Guy", "Mars Attacks", "Space Jam"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1996 film would you hear the quote: 'You had me at hello'?",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
"option":["Jerry Maguire", "The Pride Of The Yankees", "Sunset Blvd.", "Network"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1970 film would you hear the quote: 'Love means never having to say you're sorry.'?",
"answ":"LOVE STORY",
"answ2":"Love Story.",
"option":["Love Story", "Funny Girl", "Rocky", "Cool Hand Luke"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1976 film would you hear the quote: 'I'm as mad as hell, and I'm not going to take this anymore!'?",
"answ":"NETWORK",
"answ2":"Network.",
"option":["Network", "Mommie Dearest", "All About Eve", "Annie Hall"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1983 film would you hear the quote: 'Say hello to my little friend!'?",
"answ":"SCARFACE",
"answ2":"Scarface.",
"option":["Scarface", "The Graduate", "Little Caesar", "Casablanca"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1950 film would you hear the quote: 'All right, Mr. DeMille, I'm ready for my close-up.'?",
"answ":"SUNSET BOULEVARD",
"answ2":"Sunset Boulevard.",
"option":["Sunset Boulevard", "A Few Good Men", "A Streetcar Named Desire", "The Sixth Sense"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1950 film would you hear the quote: 'I am big! It's the pictures that got small.'?",
"answ":"SUNSET BOULEVARD",
"answ2":"Sunset Boulevard.",
"option":["Sunset Boulevard", "Gone with the Wind", "White Heat", "Network"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1976 film would you hear the quote: 'You talking to me?'",
"answ":"TAXI DRIVER",
"answ2":"Taxi Driver.",
"option":["Taxi Driver", "Dirty Harry", "Wall Street", "ET the Extra-Terrestrial"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1991 film would you hear the quote: 'Hasta la vista, baby.'?",
"answ":"TERMINATOR 2",
"answ3":"TERMINATOR 2 JUDGEMENT DAY",
"answ2":"Terminator 2.",
"option":["Terminator 2: Judgment Day", "Poltergeist", "Chinatown", "The Wizard of Oz"],
},
{
"cat":"Movie Quotes",
"ques":"What film features the quote: 'This is not 'Nam. This is bowling. There are rules.'",
"answ":"THE BIG LEBOWSKI",
"answ2":"The Big Lebowski.",
"option":["The Big Lebowski", "Grease 2", "Kingpin", "Buffalo '66"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1972 film would you hear the quote: 'I'm gonna make him an offer he can't refuse.'?",
"answ":"THE GODFATHER",
"answ2":"The Godfather.",
"option":["The Godfather", "Dirty Harry", "ET the Extra-Terrestrial", "All About Eve"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1974 film would you hear the quote: 'Keep your friends close, but your enemies closer.'?",
"answ":"THE GODFATHER PART II",
"answ3":"GODFATHER PART II",
"answ2":"The Godfather Part II.",
"option":["The Godfather Part II", "Network", "Terminator 2", "Dr. Strangelove"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1967 film would you hear the quote: 'Mrs. Robinson, you're trying to seduce me. Aren't you?'",
"answ":"THE GRADUATE",
"answ2":"The Graduate.",
"option":["The Graduate", "The Wizard of Oz", "Marathon Man", "Soylent Green"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1941 film would you hear the quote: 'The stuff that dreams are made of.'?",
"answ":"THE MALTESE FALCON",
"answ2":"The Maltese Falcon.",
"option":["The Maltese Falcon", "Dracula", "Wall Street", "Marathon Man"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1980 film would you hear the quote: 'Here's Johnny!'?",
"answ":"THE SHINING",
"answ2":"The Shining.",
"option":["The Shining", "Chinatown", "Dracula", "A League of Their Own"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1991 film would you hear the quote: 'I ate his liver with some fava beans and a nice Chianti.'?",
"answ":"THE SILENCE OF THE LAMBS",
"answ3":"SILENCE OF THE LAMBS",
"answ2":"The Silence of the Lambs.",
"option":["The Silence of the Lambs", "Goldfinger", "The Jazz Singer", "Casablanca"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1999 film would you hear the quote: 'I see dead people.'?",
"answ":"THE SIXTH SENSE",
"answ3":"SIXTH SENSE",
"answ2":"The Sixth Sense.",
"option":["The Sixth Sense", "The Maltese Falcon", "Planet of the Apes", "National Lampoon's Animal House"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1984 film would you hear the quote: 'I'll be back.'?",
"answ":"THE TERMINATOR",
"answ2":"The Terminator.",
"option":["The Terminator", "Beverly Hills Cop", "Apocalypse Now", "Ghostbusters"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1939 film would you hear the quote: 'Toto, I've a feeling we're not in Kansas anymore.'?",
"answ":"THE WIZARD OF OZ",
"answ2":"The Wizard of Oz.",
"option":["The Wizard of Oz", "When Harry Met Sally", "The Graduate", "Casablanca"],
},
{
"cat":"Movie Quotes",
"ques":"Which drama features the quote: 'Look, you shoot up a guy's head with his pants down, believe me, Texas is not the place you want to get caught.'",
"answ":"THELMA AND LOUISE",
"answ2":"Thelma & Louise.",
"option":["Thelma & Louise", "The Three Burials of Melquiades Estrada", "No Country for Old Men", "Lone Star"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1997 film would you hear the quote: 'I'm the king of the world!'?",
"answ":"TITANIC",
"answ2":"Titanic.",
"option":["Titanic", "Con Air", "Love Story", "Starship Troopers"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1986 film would you hear the quote: 'I feel the need - the need for speed!'?",
"answ":"TOP GUN",
"answ2":"Top Gun.",
"option":["Top Gun", "Jerry Maguire", "Soylent Green", "Shane"],
},
{
"cat":"Movie Quotes",
"ques":"In which 1939 film would you hear the quote: 'I'll get you, my pretty, and your little dog, too!'?",
"answ":"THE WIZARD OF OZ",
"answ2":"The Wizard of Oz.",
"option":["The Wizard of Oz", "Wuthering Heights", "Stagecoach", "Gone with the Wind"],
},
{
"cat":"Movie Quotes",
"ques":"Finish the movie quote: 'You know, I have one simple request. And that is to have sharks with frickin' _______ attached to their heads!",
"answ":"LASER BEAMS",
"answ2":"Laser Beams.",
"option":["Laser Beams", "Machine Guns", "Ray Guns", "Samurai Swords"],
},
{
"cat":"Movie Quotes",
"ques":"Name the 1958 movie in which Paul Newman warns Elizabeth Taylor: 'Careful, Maggie, your claws are showing.'",
"answ":"CAT ON A HOT TIN ROOF",
"answ2":"Cat on a Hot Tin Roof.",
"option":["Cat on a Hot Tin Roof", "Cool Hand Luke", "The Hustler", "The Long, Hot Summer"],
},
{
"cat":"Movie Quotes",
"ques":"Name the 1962 epic in which the lead character pleads: 'I pray that I may never see the desert again. Hear me, God.'",
"answ":"LAWRENCE OF ARABIA",
"answ2":"Lawrence of Arabia.",
"option":["Lawrence of Arabia", "How the West was Won", "Cleopatra", "Spartacus"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie from the quote: 'Well hello, Mr. Fancypants. Well, I've got news for you pal, you ain't leading but two things right now: Jack and shit... and Jack left town.'",
"answ":"ARMY OF DARKNESS",
"answ2":"Army of Darkness.",
"option":["Army of Darkness", "Planes, Trains and Automobiles", "Dude, Where's My Car?", "Smokey and the Bandit"],
},
{
"cat":"Movie Quotes",
"ques":"Name the movie featuring the quote: 'You won't answer my calls, you change your number...I'm not gonna be ignored, Dan.'",
"answ":"FATAL ATTRACTION",
"answ2":"Fatal Attraction.",
"option":["Fatal Attraction", "Body Heat", "Basic Instinct", "Blue Velvet"],
},
];
moviequotes = shuffle(moviequotes);
r2Q23 = shuffle(r2Q23);