var r2Q24 = [
{
"cat":"Movie Taglines",
"ques":"Which Robin Williams film has the tagline: 'Laughter is contagious'?",
"answ":"PATCH ADAMS",
"answ2":"Patch Adams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Birdcage</button><button id=incop2 class=buttons003 onclick=qinc()>Flubber</button><button id=incop3 class=buttons003 onclick=qinc()>Shakes the Clown</button><button id=corop class=buttons003 onclick=qcor()>Patch Adams</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 2015 film with the tagline: 'Bring Him Home'?",
"answ":"THE MARTIAN",
"answ2":"The Martian.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Revenant</button><button id=incop2 class=buttons003 onclick=qinc()>Bridge of Spies</button><button id=incop3 class=buttons003 onclick=qinc()>San Andreas</button><button id=corop class=buttons003 onclick=qcor()>The Martian</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which comedy film had the tagline: 'The longer you wait the harder it gets.'?",
"answ":"THE 40 YEAR OLD VIRGIN",
"answ3":"40 YEAR OLD VIRGIN",
"answ2":"The 40-Year-Old Virgin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>American Pie</button><button id=incop2 class=buttons003 onclick=qinc()>Knocked Up</button><button id=incop3 class=buttons003 onclick=qinc()>This Is 40</button><button id=corop class=buttons003 onclick=qcor()>The 40-Year-Old Virgin</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What animated film has the tagline: 'An unforgettable adventure she probably won't remember'?",
"answ":"FINDING DORY",
"answ2":"Finding Dory.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Coraline</button><button id=incop2 class=buttons003 onclick=qinc()>Frozen</button><button id=incop3 class=buttons003 onclick=qinc()>Chicken Run</button><button id=corop class=buttons003 onclick=qcor()>Finding Dory</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 2004 comedy with the tagline: 'In search of wine. In search of women. In search of themselves.'",
"answ":"SIDEWAYS",
"answ2":"Sideways.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chasing Liberty</button><button id=incop2 class=buttons003 onclick=qinc()>The Perfect Score</button><button id=incop3 class=buttons003 onclick=qinc()>The Ladykillers</button><button id=corop class=buttons003 onclick=qcor()>Sideways</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1999 horror film had the tagline: 'Heads will roll.'?",
"answ":"SLEEPY HOLLOW",
"answ2":"Sleepy Hollow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lake Placid</button><button id=incop2 class=buttons003 onclick=qinc()>The Haunting</button><button id=incop3 class=buttons003 onclick=qinc()>End of Days</button><button id=corop class=buttons003 onclick=qcor()>Sleepy Hollow</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What Spielberg movie had the following tagline: 'The true story of a real fake.'?",
"answ":"CATCH ME IF YOU CAN",
"answ2":"Catch Me If You Can.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Catch Me If You Can</button><button id=incop2 class=buttons003 onclick=qinc()>Bridge of Spies</button><button id=incop3 class=buttons003 onclick=qinc()>The Terminal</button><button id=incop4 class=buttons003 onclick=qinc()>The BFG</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1998 comedy had the following tagline: 'Love is in the hair.'?",
"answ":"THERE'S SOMETHING ABOUT MARY",
"answ3":"THERE IS SOMETHING ABOUT MARY",
"answ2":"There's Something About Mary.",
"option":"<button id=corop class=buttons003 onclick=qcor()>There's Something About Mary</button><button id=incop2 class=buttons003 onclick=qinc()>Ever After</button><button id=incop3 class=buttons003 onclick=qinc()>The Wedding Singer</button><button id=incop4 class=buttons003 onclick=qinc()>Dirty Work</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 2000s sci-fi horror film had the tagline: 'The last man on Earth is not alone.'?",
"answ":"I AM LEGEND",
"answ2":"I Am Legend.",
"option":"<button id=corop class=buttons003 onclick=qcor()>I Am Legend</button><button id=incop2 class=buttons003 onclick=qinc()>Oblivion</button><button id=incop3 class=buttons003 onclick=qinc()>I Robot</button><button id=incop4 class=buttons003 onclick=qinc()>The Happening</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What Tarantino movie had the tagline: 'Life, liberty and the pursuit of vengeance'?",
"answ":"DJANGO UNCHAINED",
"answ2":"Django Unchained.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Django Unchained</button><button id=incop2 class=buttons003 onclick=qinc()>Reservoir Dogs</button><button id=incop3 class=buttons003 onclick=qinc()>Once Upon a Time in Hollywood</button><button id=incop4 class=buttons003 onclick=qinc()>Pulp Fiction</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What Best Picture nominee had the tagline: 'She brought a small town to its feet and a huge corporation to its knees.'?",
"answ":"ERIN BROCKOVICH",
"answ2":"Erin Brockovich.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Erin Brockovich</button><button id=incop2 class=buttons003 onclick=qinc()>Silver Linings Playbook</button><button id=incop3 class=buttons003 onclick=qinc()>The Reader</button><button id=incop4 class=buttons003 onclick=qinc()>The Queen</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What sci-fi mashup had the tagline: 'Whoever wins, we lose.'?",
"answ":"ALIEN VERSUS PREDATOR",
"answ3":"ALIEN VS PREDATOR",
"answ2":"Alien vs. Predator.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alien vs. Predator</button><button id=incop2 class=buttons003 onclick=qinc()>Godzilla vs. Kong</button><button id=incop3 class=buttons003 onclick=qinc()>Eagle vs. Shark</button><button id=incop4 class=buttons003 onclick=qinc()>Freddy vs. Jason</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1998 film had the tagline: 'On the air. Unaware.'?",
"answ":"TRUMAN SHOW",
"answ3":"THE TRUMAN SHOW",
"answ2":"The Truman Show.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Truman Show</button><button id=incop2 class=buttons003 onclick=qinc()>EDTv</button><button id=incop3 class=buttons003 onclick=qinc()>Brazil</button><button id=incop4 class=buttons003 onclick=qinc()>eXistenZ</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1990s movie had the tagline: 'His life was in their hands. Now her toe is in the mail.'",
"answ":"THE BIG LEBOWSKI",
"answ3":"BIG LEBOWSKI",
"answ2":"The Big Lebowski.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Big Lebowski</button><button id=incop2 class=buttons003 onclick=qinc()>The Hudsucker Proxy</button><button id=incop3 class=buttons003 onclick=qinc()>Fargo</button><button id=incop4 class=buttons003 onclick=qinc()>	The Ladykillers</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 2004 drama had the tagline: 'Would you erase me'?",
"answ":"ETERNAL SUNSHINE OF THE SPOTLESS MIND",
"answ2":"Eternal Sunshine of the Spotless Mind.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Eternal Sunshine of the Spotless Mind</button><button id=incop2 class=buttons003 onclick=qinc()>The Notebook</button><button id=incop3 class=buttons003 onclick=qinc()>The Manchurian Candidate</button><button id=incop4 class=buttons003 onclick=qinc()>Closer</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which comedy film had the tagline: 'Trapped in time. Surrounded by evil. Low on gas.'?",
"answ":"ARMY OF DARKNESS",
"answ2":"Army of Darkness.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Army of Darkness</button><button id=incop2 class=buttons003 onclick=qinc()>Edge of Tomorrow</button><button id=incop3 class=buttons003 onclick=qinc()>Hot Tub Time Machine</button><button id=incop4 class=buttons003 onclick=qinc()>Palm Springs</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1997 film with the tagline: 'Even a hitman deserves a second shot'?",
"answ":"GROSSE POINTE BLANK",
"answ2":"Grosse Pointe Blank.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Face/Off</button><button id=incop2 class=buttons003 onclick=qinc()>The Peacemaker</button><button id=incop3 class=buttons003 onclick=qinc()>Drive</button><button id=corop class=buttons003 onclick=qcor()>Grosse Pointe Blank</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 80s film with the tagline: 'Man is the warmest placed to hide'?",
"answ":"THE THING",
"answ2":"The Thing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Invasion of the Body Snatchers</button><button id=incop2 class=buttons003 onclick=qinc()>Alien</button><button id=incop3 class=buttons003 onclick=qinc()>They Live</button><button id=corop class=buttons003 onclick=qcor()>The Thing</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the film with the tagline: 'Reality is a thing of the past'?",
"answ":"THE MATRIX",
"answ3":"MATRIX",
"answ2":"The Matrix.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Interstellar</button><button id=incop2 class=buttons003 onclick=qinc()>Inception</button><button id=incop3 class=buttons003 onclick=qinc()>Existenz</button><button id=corop class=buttons003 onclick=qcor()>The Matrix</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1994 film with the tagline: 'Fifty million people watching, but no one saw a thing'?",
"answ":"QUIZ SHOW",
"answ2":"Quiz Show.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Quiz Show</button><button id=incop2 class=buttons003 onclick=qinc()>True Lies</button><button id=incop3 class=buttons003 onclick=qinc()>Clear and Present Danger</button><button id=incop4 class=buttons003 onclick=qinc()>Maverick</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 2005 film with the tagline: 'Love is a force of nature'?",
"answ":"BROKEBACK MOUNTAIN",
"answ2":"Brokeback Mountain.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Brokeback Mountain</button><button id=incop2 class=buttons003 onclick=qinc()>Pride & Prejudice</button><button id=incop3 class=buttons003 onclick=qinc()>Hitch</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella Man</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the film with the tagline: 'One man's struggle to take it easy'?",
"answ":"FERRIS BUELLER'S DAY OFF",
"answ3":"FERRIS BUELLERS DAY OFF",
"answ2":"Ferris Bueller's Day Off.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ferris Bueller's Day Off</button><button id=incop2 class=buttons003 onclick=qinc()>Slackers</button><button id=incop3 class=buttons003 onclick=qinc()>Napoleon Dynamite</button><button id=incop4 class=buttons003 onclick=qinc()>Get a Job</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 80s film had the tagline: 'A lively comedy about a guy who isn't'?",
"answ":"WEEKEND AT BERNIE'S",
"answ3":"WEEKEND AT BERNIES",
"answ2":"Weekend at Bernie's.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lars and the Real Girl</button><button id=corop class=buttons003 onclick=qcor()>Weekend at Bernie's</button><button id=incop3 class=buttons003 onclick=qinc()>Lucky Numbers</button><button id=incop4 class=buttons003 onclick=qinc()>Napoleon Dynamite</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the film with the tagline: 'Protecting the Earth from the scum of the universe'?",
"answ":"MEN IN BLACK",
"answ2":"Men in Black.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jupiter Ascending</button><button id=corop class=buttons003 onclick=qcor()>Men in Black</button><button id=incop3 class=buttons003 onclick=qinc()>R.I.P.D</button><button id=incop4 class=buttons003 onclick=qinc()>Evolution</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1999 film with the tagline: 'There's something about your first piece'?",
"answ":"AMERICAN PIE",
"answ2":"American Pie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Accepted</button><button id=incop2 class=buttons003 onclick=qinc()>The 40-Year Old Virgin</button><button id=corop class=buttons003 onclick=qcor()>American Pie</button><button id=incop4 class=buttons003 onclick=qinc()>Superbad</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1998 film with the tagline: 'Size does matter'?",
"answ":"GODZILLA",
"answ2":"Godzilla.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rampage</button><button id=incop2 class=buttons003 onclick=qinc()>King Kong</button><button id=corop class=buttons003 onclick=qcor()>Godzilla</button><button id=incop4 class=buttons003 onclick=qinc()>Gulliver's Travels</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the movie that carried the tagline: 'Vampires. Not interviews.'?",
"answ":"FROM DUSK TILL DAWN",
"answ2":"From Dusk till Dawn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>From Dusk Till Dawn</button><button id=incop2 class=buttons003 onclick=qinc()>Twilight</button><button id=incop3 class=buttons003 onclick=qinc()>30 Days of Night</button><button id=incop4 class=buttons003 onclick=qinc()>Fright Night</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1999 film had the tagline: 'The show has been cancelled, but the adventure is just beginning'?",
"answ":"GALAXY QUEST",
"answ2":"Galaxy Quest.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Galaxy Quest</button><button id=incop2 class=buttons003 onclick=qinc()>The Truman Show</button><button id=incop3 class=buttons003 onclick=qinc()>EDtv</button><button id=incop4 class=buttons003 onclick=qinc()>South Park: Bigger, Longer & Uncut</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 80s film had the tagline: 'The thing that won't die, in the nightmare that won't end'?",
"answ":"THE TERMINATOR",
"answ3":"TERMINATOR",
"answ2":"The Terminator.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alien</button><button id=incop2 class=buttons003 onclick=qinc()>Friday the 13th</button><button id=corop class=buttons003 onclick=qcor()>The Terminator</button><button id=incop4 class=buttons003 onclick=qinc()>The Thing</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What stop-motion animated film had the tagline: 'Escape or die frying'?",
"answ":"CHICKEN RUN",
"answ2":"Chicken Run.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shaun the Sheep</button><button id=incop2 class=buttons003 onclick=qinc()>Mary and Wax</button><button id=corop class=buttons003 onclick=qcor()>Chicken Run</button><button id=incop4 class=buttons003 onclick=qinc()>Wallace & Gromitt The Curse of the Were-Rabbit</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What Brad Pitt movie asks the question 'Are you in or out'?",
"answ":"OCEAN'S ELEVEN",
"answ3":"OCEAN'S 11",
"answ2":"Ocean's Eleven.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Seven</button><button id=incop2 class=buttons003 onclick=qinc()>Fight Club</button><button id=corop class=buttons003 onclick=qcor()>Ocean's Eleven</button><button id=incop4 class=buttons003 onclick=qinc()>Ad Astra</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What Russell Crowe film had the tagline: 'One man's extraordinary fight to save the family he loved'?",
"answ":"CINDERELLA MAN",
"answ2":"Cinderella Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gladiator</button><button id=incop2 class=buttons003 onclick=qinc()>American Gangster</button><button id=corop class=buttons003 onclick=qcor()>Cinderella Man</button><button id=incop4 class=buttons003 onclick=qinc()>Robin Hood</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which 2003 comedy had the tagline: 'All the fun of college, none of the education'?",
"answ":"OLD SCHOOL",
"answ2":"Old School.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>School of Rock</button><button id=incop2 class=buttons003 onclick=qinc()>Accepted</button><button id=corop class=buttons003 onclick=qcor()>Old School</button><button id=incop4 class=buttons003 onclick=qinc()>Slackers</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 2000 Jim Carrey comedy had the tagline 'From gentle to mental'?",
"answ":"ME MYSELF AND IRENE",
"answ3":"ME  MYSELF AND IRENE",
"answ2":"Me, Myself & Irene.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Mask</button><button id=incop2 class=buttons003 onclick=qinc()>The Cable Guy</button><button id=corop class=buttons003 onclick=qcor()>Me, Myself & Irene</button><button id=incop4 class=buttons003 onclick=qinc()>The Majestic</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which 90s comedy had the tagline: 'Cocktails first. Questions later'?",
"answ":"SWINGERS",
"answ2":"Swingers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Half Baked</button><button id=incop2 class=buttons003 onclick=qinc()>Clueless</button><button id=corop class=buttons003 onclick=qcor()>Swingers</button><button id=incop4 class=buttons003 onclick=qinc()>Hot Shots!</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"'Oh, yes. There will be blood' is the tagline for a film in which horror franchise?",
"answ":"SAW",
"answ2":"Saw.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Halloween</button><button id=incop2 class=buttons003 onclick=qinc()>Friday the 13th</button><button id=corop class=buttons003 onclick=qcor()>Saw</button><button id=incop4 class=buttons003 onclick=qinc()>Texas Chainsaw Massacre</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 90s comedy had the tagline: 'If at first you don't succeed, lower your standards'?",
"answ":"TOMMY BOY",
"answ2":"Tommy Boy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dumb and Dumber</button><button id=incop2 class=buttons003 onclick=qinc()>There's Something About Mary</button><button id=corop class=buttons003 onclick=qcor()>Tommy Boy</button><button id=incop4 class=buttons003 onclick=qinc()>Wayne's World</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which Christina Ricci movie had the tagline: 'Get an afterlife'?",
"answ":"CASPER",
"answ2":"Casper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Addams Family Values</button><button id=incop2 class=buttons003 onclick=qinc()>I Woke Up Early The Day I Died</button><button id=corop class=buttons003 onclick=qcor()>Casper</button><button id=incop4 class=buttons003 onclick=qinc()>Sleepy Hollow</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which Stallone movie had the tagline: 'They went in alone. The only way out is together'?",
"answ":"DAYLIGHT",
"answ2":"Daylight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Judge Dredd</button><button id=incop2 class=buttons003 onclick=qinc()>Cobra</button><button id=incop3 class=buttons003 onclick=qinc()>The Expendables</button><button id=corop class=buttons003 onclick=qcor()>Daylight</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What movie had the tagline: 'Heroes. Giants. Villains. Wizards. True Love'?",
"answ":"THE PRINCESS BRIDE",
"answ3":"PRINCESS BRIDE",
"answ2":"The Princess Bride.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Stardust</button><button id=incop2 class=buttons003 onclick=qinc()>Bridge to Terabithia</button><button id=incop3 class=buttons003 onclick=qinc()>The NeverEnding Story</button><button id=corop class=buttons003 onclick=qcor()>The Princess Bride</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which 2005 comedy film had the tagline: 'Cousins. Outlaws. Thrillbillies'?",
"answ":"THE DUKES OF HAZZARD",
"answ3":"DUKES OF HAZZARD",
"answ2":"The Dukes of Hazzard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guess Who</button><button id=incop2 class=buttons003 onclick=qinc()>Keeping Mum</button><button id=incop3 class=buttons003 onclick=qinc()>The Ringer</button><button id=corop class=buttons003 onclick=qcor()>The Dukes of Hazzard</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What cult classic had the tagline: 'Just because they serve you, doesn't mean they like you'?",
"answ":"CLERKS",
"answ2":"Clerks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Slammin' Salmon</button><button id=incop2 class=buttons003 onclick=qinc()>Mallrats</button><button id=incop3 class=buttons003 onclick=qinc()>Waiting...</button><button id=corop class=buttons003 onclick=qcor()>Clerks</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What disaster film had the tagline: 'Earth. It was fun while it lasted'?",
"answ":"ARMAGEDDON",
"answ3":"ARMEGEDDON",
"answ2":"Armageddon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Deep Impact</button><button id=incop2 class=buttons003 onclick=qinc()>The Day After Tomorrow</button><button id=incop3 class=buttons003 onclick=qinc()>After Earth</button><button id=corop class=buttons003 onclick=qcor()>Armageddon</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"'Every man dies, not every man really lives' is the tagline of which film?",
"answ":"BRAVEHEART",
"answ2":"Braveheart.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Troy</button><button id=incop2 class=buttons003 onclick=qinc()>300</button><button id=incop3 class=buttons003 onclick=qinc()>The Patriot</button><button id=corop class=buttons003 onclick=qcor()>Braveheart</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1990 film with the tagline: 'Eight legs, two fangs and an attitude'?",
"answ":"ARACHNOPHOBIA",
"answ2":"Arachnophobia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eight Legged Freaks</button><button id=incop2 class=buttons003 onclick=qinc()>Webs</button><button id=incop3 class=buttons003 onclick=qinc()>Spider</button><button id=corop class=buttons003 onclick=qcor()>Arachnophobia</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Name the 1992 film with the tagline: 'The bitch is back'?",
"answ":"ALIEN 3",
"answ3":"ALIEN III",
"answ2":"Alien 3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Predator II</button><button id=incop2 class=buttons003 onclick=qinc()>Death Becomes Her</button><button id=incop3 class=buttons003 onclick=qinc()>Sleepwalkers</button><button id=corop class=buttons003 onclick=qcor()>Alien 3</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Released in 2013, what cop comedy had the tagline: 'Good cop, mad cop.'?",
"answ":"THE HEAT",
"answ2":"The Heat.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Heat</button><button id=incop2 class=buttons003 onclick=qinc()>Hot Pursuit</button><button id=incop3 class=buttons003 onclick=qinc()>21 Jump Street</button><button id=incop4 class=buttons003 onclick=qinc()>Ride Along</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What action comedy features the tagline: 'When he said I do, he never said what he did'?",
"answ":"TRUE LIES",
"answ2":"True Lies.",
"option":"<button id=corop class=buttons003 onclick=qcor()>True Lies</button><button id=incop2 class=buttons003 onclick=qinc()>Knight and Day</button><button id=incop3 class=buttons003 onclick=qinc()>Mr. & Mrs. Smith</button><button id=incop4 class=buttons003 onclick=qinc()>Killers</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"Which 2012 crime drama has the tagline: 'A totally twisted deep-fried Texas redneck trailer park murder story'?",
"answ":"KILLER JOE",
"answ2":"Killer Joe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Iceman</button><button id=incop2 class=buttons003 onclick=qinc()>The Park Beyond the Pines</button><button id=corop class=buttons003 onclick=qcor()>Killer Joe</button><button id=incop4 class=buttons003 onclick=qinc()>Lawless</button><br/>",
},
{
"cat":"Movie Taglines",
"ques":"What 1986 horror comedy had the tagline: 'Ding dong. You're dead.'",
"answ":"HOUSE",
"answ2":"House.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Children of the Corn</button><button id=incop2 class=buttons003 onclick=qinc()>Gremlins</button><button id=corop class=buttons003 onclick=qcor()>House</button><button id=incop4 class=buttons003 onclick=qinc()>Wrong Turn</button><br/>",
},
];
r2Q24 = shuffle(r2Q24);