var romance = [
{
"cat":"Romance",
"ques":"Which actor plays the leading role in Definitely Maybe?",
"answ":"RYAN REYNOLDS",
"answ2":"Ryan Reynolds.",
},
{
"cat":"Romance",
"ques":"Domhnall Gleeson and Rachel McAdams star in the time travel romantic dramedy titled what?",
"answ":"ABOUT TIME",
"answ2":"About Time.",
},
{
"cat":"Romance",
"ques":"What actress does Adam Sandler need to convince to fall in love with him every day in 50 First Dates?",
"answ":"DREW BARRYMORE",
"answ2":"Drew Barrymore.",
},
{
"cat":"Romance",
"ques":"Which actor plays the lead of Augustus Waters in The Fault in Our Stars?",
"answ":"ANSEL ELGORT",
"answ2":"Ansel Elgort.",
},
{
"cat":"Romance",
"ques":"Who plays wealthy businessman Edward Lewis in 1990's Pretty Woman?",
"answ":"RICHARD GERE",
"answ2":"Richard Gere.",
},
{
"cat":"Romance",
"ques":"Who stars as Kevin Costner's co-lead in 1996's Tin Cup?",
"answ":"RENE RUSSO",
"answ2":"Rene Russo.",
},
{
"cat":"Romance",
"ques":"Who is the male lead in 2011's Midnight in Paris?",
"answ":"OWEN WILSON",
"answ2":"Owen Wilson.",
},
{
"cat":"Romance",
"ques":"Who directed Ewan McGregor and Nicole Kidman in Moulin Rouge?",
"answ":"BAZ LUHRMANN",
"answ3":"BAZ LURMANN",
"answ2":"Baz Luhrmann.",
},
{
"cat":"Romance",
"ques":"Drew Barrymore and Adam Sandler star in what 1980s set romantic comedy?",
"answ":"THE WEDDING SINGER",
"answ3":"WEDDING SINGER",
"answ2":"The Wedding Singer.",
},
{
"cat":"Romance",
"ques":"In The American President, who plays Washington lobbyist Sydney Ellen Wade?",
"answ":"ANNETTE BENNING",
"answ3":"ANNETTE BENING",
"answ2":"Annette Bening.",
},
{
"cat":"Romance",
"ques":"Who directed Safety Not Guaranteed?",
"answ":"COLIN TREVORROW",
"answ3":"COLIN TREVOROW",
"answ2":"Colin Trevorrow.",
},
{
"cat":"Romance",
"ques":"Jennifer Connelly plays Bradley Cooper's character's wife in this 2009 romance film.",
"answ":"HE'S JUST NOT THAT INTO YOU",
"answ2":"He's Just Not That Into You.",
},
{
"cat":"Romance",
"ques":"Who directed If Beale Street Could Talk?",
"answ":"BARRY JENKINS",
"answ2":"Barry Jenkins.",
},
{
"cat":"Romance",
"ques":"A Pakistani funny man falls for an American graduate student at one of his comedy shows. He soon becomes worried about what his traditional parents will think of her. Name the film.",
"answ":"THE BIG SICK",
"answ3":"BIG SICK",
"answ2":"The Big Sick.",
},
{
"cat":"Romance",
"ques":"What funnyman took a dramatic turn as troubled salesman Barry Egan in Punch Drunk Love?",
"answ":"ADAM SANDLER",
"answ2":"Adam Sandler.",
},
{
"cat":"Romance",
"ques":"In Roman Holiday, who plays American reporter Joe Bradley who tries to get a scoop on Princess Ann, but instead falls in love?",
"answ":"GREGORY PECK",
"answ2":"Gregory Peck.",
},
{
"cat":"Romance",
"ques":"What film stars Kate Beckinsale and John Cusack as two strangers who instantly fall in love and then spend years waiting for fate to bring them together again?",
"answ":"SERENDIPITY",
"answ2":"Serendipity.",
},
{
"cat":"Romance",
"ques":"In what romantic drama does Mel Gibson play a pilot from the 1930s who's cryogenically frozen and awakens in 1992?",
"answ":"FOREVER YOUNG",
"answ2":"Forever Young.",
},
{
"cat":"Romance",
"ques":"Who plays business focused Linus Larrabe in 1995's Sabrina?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Romance",
"ques":"Who directed 1970's Love Story?",
"answ":"ARTHUR HILLER",
"answ2":"Arthur Hiller.",
},
{
"cat":"Romance",
"ques":"What is the name of the song that Ingrid Bergman asked Sam to play in 1942's Casablanca?",
"answ":"AS TIME GOES BY",
"answ2":"As Time Goes By.",
},
{
"cat":"Romance",
"ques":"Who plays Emmeline Lestrange in The Blue Lagoon?",
"answ":"BROOKE SHIELDS",
"answ2":"Brooke Shields.",
},
];
var r2Q25 = [
{
"cat":"Romance",
"ques":"In Sideways, what do Paul Giamatti and Thomas Haden Church plan to do on their trip before getting involved with Sandra Oh and Virginia Madsen?",
"answ":"WINE TASTING",
"answ3":"GO WINE TASTING",
"answ2":"Wine tasting.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Wine tasting</button><button id=incop2 class=buttons003 onclick=qinc()>Fishing</button><button id=incop3 class=buttons003 onclick=qinc()>Research for a manuscript</button><button id=incop4 class=buttons003 onclick=qinc()>Golf tournament</button><br/>",
},
{
"cat":"Romance",
"ques":"Who played Juliet opposite Leonardo DiCaprio in 1996's Romeo + Juliet?",
"answ":"CLAIRE DANES",
"answ2":"Claire Danes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Selma Blair</button><button id=corop class=buttons003 onclick=qcor()>Claire Danes</button><button id=incop3 class=buttons003 onclick=qinc()>Sienna Miller</button><button id=incop4 class=buttons003 onclick=qinc()>Anne Hathaway</button><br/>",
},
{
"cat":"Romance",
"ques":"In the 1980 romantic fantasy Somewhere in Time, who co-starred alongside Christopher Reeve?",
"answ":"JANE SEYMOUR",
"answ2":"Jane Seymour.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jane Seymour</button><button id=incop2 class=buttons003 onclick=qinc()>Margot Kidder</button><button id=incop3 class=buttons003 onclick=qinc()>Julie Andrews</button><button id=incop4 class=buttons003 onclick=qinc()>Judi Dench</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays Barbra Streisand's love interest in 1996's The Mirror Has Two Faces?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Daniel Day-Lewis</button><button id=incop2 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop3 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop4 class=buttons003 onclick=qinc()>Robert Duvall</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays stubborn landlord Armande Voizin in the 2000 romance Chocolat?",
"answ":"JUDI DENCH",
"answ2":"Judi Dench.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Maggie Smith</button><button id=incop2 class=buttons003 onclick=qinc()>Gérard Depardieu</button><button id=corop class=buttons003 onclick=qcor()>Judi Dench</button><button id=incop4 class=buttons003 onclick=qinc()>Javier Bardem</button><br/>",
},
{
"cat":"Romance",
"ques":"Where do Cher and Nicolas Cage go for their first date in Moonstruck?",
"answ":"OPERA",
"answ3":"THE OPERA",
"answ2":"The opera.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A park</button><button id=incop2 class=buttons003 onclick=qinc()>The beach</button><button id=corop class=buttons003 onclick=qcor()>The opera</button><button id=incop4 class=buttons003 onclick=qinc()>A movie theater</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays playwright Richard Collier in Somewhere in Time?",
"answ":"CHRISTOPHER REEVE",
"answ2":"Christopher Reeve.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=incop2 class=buttons003 onclick=qinc()>Donald Sutherland</button><button id=corop class=buttons003 onclick=qcor()>Christopher Reeve</button><button id=incop4 class=buttons003 onclick=qinc()>Richard Gere</button><br/>",
},
{
"cat":"Romance",
"ques":"Where does Barbra Streisand first meet Robert Redford in 1973's The Way We Were?",
"answ":"COLLEGE",
"answ2":"College.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Restaurant</button><button id=incop2 class=buttons003 onclick=qinc()>Swimming Pool</button><button id=corop class=buttons003 onclick=qcor()>College</button><button id=incop4 class=buttons003 onclick=qinc()>Summer Camp</button><br/>",
},
{
"cat":"Romance",
"ques":"Who played the lead character Sonora Webster in Wild Hearts Can't Be Broken?",
"answ":"GABRIELLE ANWAR",
"answ2":"Gabrielle Anwar.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Katie Holmes</button><button id=incop2 class=buttons003 onclick=qinc()>Rebecca De Mornay</button><button id=corop class=buttons003 onclick=qcor()>Gabrielle Anwar</button><button id=incop4 class=buttons003 onclick=qinc()>Hope Davis</button><br/>",
},
{
"cat":"Romance",
"ques":"What was the name of Romeo's girlfriend before he met Juliet in 1996's Romeo + Juliet?",
"answ":"ROSALINE",
"answ2":"Rosaline.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rosaline</button><button id=incop2 class=buttons003 onclick=qinc()>Caroline</button><button id=incop3 class=buttons003 onclick=qinc()>Victoria</button><button id=incop4 class=buttons003 onclick=qinc()>Maria</button><br/>",
},
{
"cat":"Romance",
"ques":"What do Jack and Rose repeatedly say to each other throughout Titanic?",
"answ":"YOU JUMP I JUMP",
"answ2":"You jump I jump.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Always</button><button id=corop class=buttons003 onclick=qcor()>You Jump I Jump</button><button id=incop3 class=buttons003 onclick=qinc()>I'm Flying</button><button id=incop4 class=buttons003 onclick=qinc()>Make It Happen</button><br/>",
},
{
"cat":"Romance",
"ques":"In The Notebook who plays Lon Hammond, the lawyer with whom Rachel McAdams's character gets engaged?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=corop class=buttons003 onclick=qcor()>James Marsden</button><button id=incop3 class=buttons003 onclick=qinc()>Kevin Connolly</button><button id=incop4 class=buttons003 onclick=qinc()>James McAvoy</button><br/>",
},
{
"cat":"Romance",
"ques":"In 500 Days of Summer, Tom studied to be a(n) ____.",
"answ":"ARCHITECT",
"answ2":"Architect.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Doctor</button><button id=incop2 class=buttons003 onclick=qinc()>Mechanic</button><button id=corop class=buttons003 onclick=qcor()>Architect</button><button id=incop4 class=buttons003 onclick=qinc()>English Teacher</button><br/>",
},
{
"cat":"Romance",
"ques":"What is the occupation of Rachel McAdams's character in Morning Glory?",
"answ":"TELEVISION PRODUCER",
"answ3":"TV PRODUCER",
"answ2":"Television Producer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Baker</button><button id=incop2 class=buttons003 onclick=qinc()>Wine Rep</button><button id=corop class=buttons003 onclick=qcor()>Television Producer</button><button id=incop4 class=buttons003 onclick=qinc()>Barista</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays Woody Allen's school-aged girlfriend in 1979's Manhattan?",
"answ":"MARIEL HEMINGWAY",
"answ2":"Mariel Hemingway.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Uma Thurman</button><button id=incop2 class=buttons003 onclick=qinc()>Mira Sorvino</button><button id=corop class=buttons003 onclick=qcor()>Diane Keaton</button><button id=incop4 class=buttons003 onclick=qinc()>Mariel Hemingway</button><br/>",
},
{
"cat":"Romance",
"ques":"What singer stars in the 1980 remake of The Jazz Singer?",
"answ":"NEIL DIAMOND",
"answ2":"Neil Diamond.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kenny Rogers</button><button id=corop class=buttons003 onclick=qcor()>Neil Diamond</button><button id=incop3 class=buttons003 onclick=qinc()>Kris Kristofferson</button><button id=incop4 class=buttons003 onclick=qinc()>Neil Sedaka</button><br/>",
},
{
"cat":"Romance",
"ques":"In An Officer and a Gentleman, who played the drill instructor Sergeant Emil Foley?",
"answ":"LOUIS GOSSETT JR",
"answ3":"LOUIS GOSSET JR",
"answ2":"Louis Gossett Jr.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>David Caruso</button><button id=corop class=buttons003 onclick=qcor()>Louis Gossett Jr</button><button id=incop3 class=buttons003 onclick=qinc()>Richard Gere</button><button id=incop4 class=buttons003 onclick=qinc()>Jeroen Krabbé</button><br/>",
},
{
"cat":"Romance",
"ques":"Who stars opposite Humphrey Bogart in the 1942 romantic classic Casablanca?",
"answ":"INGRID BERGMAN",
"answ2":"Ingrid Bergman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Katharine Hepburn</button><button id=corop class=buttons003 onclick=qcor()>Ingrid Bergman</button><button id=incop3 class=buttons003 onclick=qinc()>Bette Davis</button><button id=incop4 class=buttons003 onclick=qinc()>Greer Garson</button><br/>",
},
{
"cat":"Romance",
"ques":"What state does Leonardo DiCaprio say he's from in Titanic?",
"answ":"WISCONSIN",
"answ2":"Wisconsin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Florida</button><button id=corop class=buttons003 onclick=qcor()>Wisconsin</button><button id=incop3 class=buttons003 onclick=qinc()>Minnesota</button><br /><button id=incop4 class=buttons003 onclick=qinc()>California</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays Will Shakespeare in Shakespeare in Love?",
"answ":"JOSEPH FIENNES",
"answ2":"Joseph Fiennes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Colin Firth</button><button id=corop class=buttons003 onclick=qcor()>Joseph Fiennes</button><button id=incop3 class=buttons003 onclick=qinc()>Ben Affleck</button><button id=incop4 class=buttons003 onclick=qinc()>Leonardo DiCaprio</button><br/>",
},
{
"cat":"Romance",
"ques":"In 500 Days of Summer, which member of the Beatles does Summer say is the best?",
"answ":"RINGO STARR",
"answ3":"RINGO",
"answ2":"Ringo Starr.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Lennon</button><button id=incop2 class=buttons003 onclick=qinc()>Paul McCartney</button><button id=incop3 class=buttons003 onclick=qinc()>George Harrison</button><button id=corop class=buttons003 onclick=qcor()>Ringo Starr</button><br/>",
},
{
"cat":"Romance",
"ques":"What is the subject of Bill Murray's play in 1982's Tootsie?",
"answ":"THE LOVE CANAL",
"answ3":"LOVE CANAL",
"answ2":"The Love Canal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Dust Bowl</button><button id=incop2 class=buttons003 onclick=qinc()>The Great Depression</button><button id=corop class=buttons003 onclick=qcor()>The Love Canal</button><button id=incop4 class=buttons003 onclick=qinc()>Three Mile Island</button><br/>",
},
{
"cat":"Romance",
"ques":"What actor plays Jack Trainor, the man Melanie Griffith and Sigourney Weaver fight over in Working Girl?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alec Baldwin</button><button id=incop2 class=buttons003 onclick=qinc()>Dennis Quaid</button><button id=incop3 class=buttons003 onclick=qinc()>Bruce Willis</button><button id=corop class=buttons003 onclick=qcor()>Harrison Ford</button><br/>",
},
{
"cat":"Romance",
"ques":"Where did Clementine tell Joel to meet her after his memory got erased in Eternal Sunshine of the Spotless Mind?",
"answ":"MONTAUK",
"answ2":"Montauk.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Queens</button><button id=incop2 class=buttons003 onclick=qinc()>Deli</button><button id=incop3 class=buttons003 onclick=qinc()>Train Station</button><button id=corop class=buttons003 onclick=qcor()>Montauk</button><br/>",
},
{
"cat":"Romance",
"ques":"Who played classical music student Jenny in 1970's Love Story?",
"answ":"ALI MACGRAW",
"answ3":"ALI MCGRAW",
"answ2":"Ali MacGraw.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jane Fonda</button><button id=incop2 class=buttons003 onclick=qinc()>Barbra Streisand</button><button id=incop3 class=buttons003 onclick=qinc()>Katharine Hepburn</button><button id=corop class=buttons003 onclick=qcor()>Ali MacGraw</button><br/>",
},
{
"cat":"Romance",
"ques":"What was the first name of Timothée Chalamet's character in Call Me By Your Name?",
"answ":"ELIO",
"answ2":"Elio.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mounir</button><button id=incop2 class=buttons003 onclick=qinc()>Isaac</button><button id=incop3 class=buttons003 onclick=qinc()>Gio</button><button id=corop class=buttons003 onclick=qcor()>Elio</button><br/>",
},
{
"cat":"Romance",
"ques":"What MCU actor directed the 2014 romantic drama Before We Go?",
"answ":"CHRIS EVANS",
"answ2":"Chris Evans.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Don Cheadle</button><button id=corop class=buttons003 onclick=qcor()>Chris Evans</button><button id=incop3 class=buttons003 onclick=qinc()>Jon Favreau</button><button id=incop4 class=buttons003 onclick=qinc()>Jeremy Renner</button><br/>",
},
{
"cat":"Romance",
"ques":"Who played Jim Carrey's girlfriend Clementine in Eternal Sunshine of the Spotless Mind?",
"answ":"KATE WINSLET",
"answ2":"Kate Winslet.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rooney Mara</button><button id=corop class=buttons003 onclick=qcor()>Kate Winslet</button><button id=incop3 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=incop4 class=buttons003 onclick=qinc()>Cate Blanchett</button><br/>",
},
{
"cat":"Romance",
"ques":"Who played the titular character in 2015's Carol?",
"answ":"CATE BLANCHETT",
"answ3":"CATE BLANCHET",
"answ2":"Cate Blanchett.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Chastain</button><button id=corop class=buttons003 onclick=qcor()>Cate Blanchett</button><button id=incop3 class=buttons003 onclick=qinc()>Rachel McAdams</button><button id=incop4 class=buttons003 onclick=qinc()>Brie Larson</button><br/>",
},
{
"cat":"Romance",
"ques":"Keira Knightley starred in which feature adapted from a Jane Austen novel?",
"answ":"PRIDE AND PREJUDICE",
"answ2":"Pride & Prejudice.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sense and Sensibility</button><button id=corop class=buttons003 onclick=qcor()>Pride & Prejudice</button><button id=incop3 class=buttons003 onclick=qinc()>Emma</button><button id=incop4 class=buttons003 onclick=qinc()>Persuasion</button><br/>",
},
{
"cat":"Romance",
"ques":"In what film do Ashton Kutcher and Amanda Peet slowly fall in love over the course of seven years?",
"answ":"A LOT LIKE LOVE",
"answ2":"A Lot Like Love.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>No Strings Attached</button><button id=corop class=buttons003 onclick=qcor()>A Lot Like Love</button><button id=incop3 class=buttons003 onclick=qinc()>Griffin & Phoenix</button><button id=incop4 class=buttons003 onclick=qinc()>Please Give</button><br/>",
},
{
"cat":"Romance",
"ques":"Where do Landon and Jamie share their first kiss in A Walk To Remember?",
"answ":"DURING THE SCHOOL PLAY",
"answ3":"SCHOOL PLAY",
"answ2":"During the school play.",
"option":"<button id=corop class=buttons003 onclick=qcor()>During the school play</button><button id=incop2 class=buttons003 onclick=qinc()>Walking home from school</button><button id=incop3 class=buttons003 onclick=qinc()>At their senior prom</button><button id=incop4 class=buttons003 onclick=qinc()>Outside an observatory</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays David and Gillian's daughter, Rachel, in To Gillian on Her 37th Birthday?",
"answ":"CLAIRE DANES",
"answ2":"Claire Danes.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Claire Danes</button><button id=incop2 class=buttons003 onclick=qinc()>Kristanna Loken</button><button id=incop3 class=buttons003 onclick=qinc()>Brie Larson</button><button id=incop4 class=buttons003 onclick=qinc()>Neve Campbell</button><br/>",
},
{
"cat":"Romance",
"ques":"Water For Elephants features Reese Witherspoon and what other Oscar-winning actor?",
"answ":"CHRISTOPH WALTZ",
"answ3":"KRISTOF WALTZ",
"answ2":"Christoph Waltz.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Adrien Brody</button><button id=incop2 class=buttons003 onclick=qinc()>Colin Firth</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Caine</button><button id=corop class=buttons003 onclick=qcor()>Christoph Waltz</button><br/>",
},
{
"cat":"Romance",
"ques":"What actor appeared in both Valentine's Day and Silver Linings Playbook?",
"answ":"BRADLEY COOPER",
"answ2":"Bradley Cooper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Topher Grace</button><button id=incop2 class=buttons003 onclick=qinc()>Colin Firth</button><button id=incop3 class=buttons003 onclick=qinc()>Robert De Niro</button><button id=corop class=buttons003 onclick=qcor()>Bradley Cooper</button><br/>",
},
{
"cat":"Romance",
"ques":"Who directed the 1985 brat pack film St. Elmo's Fire?",
"answ":"JOEL SCHUMACHER",
"answ2":"Joel Schumacher.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rob Reiner</button><button id=incop2 class=buttons003 onclick=qinc()>John Hughes</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Zemeckis</button><button id=corop class=buttons003 onclick=qcor()>Joel Schumacher</button><br/>",
},
{
"cat":"Romance",
"ques":"What does Claire Danes sell in the 2005 romantic drama Shopgirl?",
"answ":"GLOVES",
"answ2":"Gloves.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Books</button><button id=incop2 class=buttons003 onclick=qinc()>Jewelry</button><button id=incop3 class=buttons003 onclick=qinc()>Cheese</button><button id=corop class=buttons003 onclick=qcor()>Gloves</button><br/>",
},
{
"cat":"Romance",
"ques":"In what movie does Richard Gere play a lawyer who takes up dancing?",
"answ":"SHALL WE DANCE?",
"answ3":"SHALL WE DANCE",
"answ2":"Shall We Dance?.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Save The Last Dance</button><button id=incop2 class=buttons003 onclick=qinc()>Dance With Me</button><button id=incop3 class=buttons003 onclick=qinc()>Let's Dance</button><button id=corop class=buttons003 onclick=qcor()>Shall We Dance?</button><br/>",
},
{
"cat":"Romance",
"ques":"In what movie does Johnny Depp make dinner rolls 'dance' on a restaurant counter?",
"answ":"BENNY AND JOON",
"answ2":"Benny & Joon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Arizona Dream</button><button id=incop2 class=buttons003 onclick=qinc()>Chocolat</button><button id=incop3 class=buttons003 onclick=qinc()>Don Juan DeMarco</button><button id=corop class=buttons003 onclick=qcor()>Benny & Joon</button><br/>",
},
{
"cat":"Romance",
"ques":"In what month do Tom and Summer meet in 500 Days of Summer?",
"answ":"JANUARY",
"answ2":"January.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>May</button><button id=incop2 class=buttons003 onclick=qinc()>July</button><button id=incop3 class=buttons003 onclick=qinc()>December</button><button id=corop class=buttons003 onclick=qcor()>January</button><br/>",
},
{
"cat":"Romance",
"ques":"Alan Alda wrote, directed and starred in which 90s wedding movie starring himself and Molly Ringwald?",
"answ":"BETSY'S WEDDING",
"answ2":"Betsy's Wedding.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>American Wedding</button><button id=incop2 class=buttons003 onclick=qinc()>Muriel's Wedding</button><button id=incop3 class=buttons003 onclick=qinc()>Monsoon Wedding</button><button id=corop class=buttons003 onclick=qcor()>Betsy's Wedding</button><br/>",
},
{
"cat":"Romance",
"ques":"Who stars alongside Domhnall Gleeson as the girl who he travels through time over and over again to woo in About Time?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Alba</button><button id=incop2 class=buttons003 onclick=qinc()>Emma Stone</button><button id=incop3 class=buttons003 onclick=qinc()>Amanda Seyfried</button><button id=corop class=buttons003 onclick=qcor()>Rachel McAdams</button><br/>",
},
{
"cat":"Romance",
"ques":"Who plays bad boy Patrick Verona, who is hired to go on a date with Kat Stratford in 1999's 10 Things I Hate About You?",
"answ":"HEATH LEDGER",
"answ2":"Heath Ledger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tobey Maguire</button><button id=incop2 class=buttons003 onclick=qinc()>Paul Bettany</button><button id=incop3 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=corop class=buttons003 onclick=qcor()>Heath Ledger</button><br/>",
},
{
"cat":"Romance",
"ques":"In The Great Gatsby, what does Gatsby stare at every night to remind himself of how close Daisy is?",
"answ":"THE GREEN LIGHT",
"answ3":"GREEN LIGHT",
"answ2":"The Green Light.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Lighthouse</button><button id=incop2 class=buttons003 onclick=qinc()>The Mirror</button><button id=incop3 class=buttons003 onclick=qinc()>Her picture</button><button id=corop class=buttons003 onclick=qcor()>The Green Light</button><br/>",
},
{
"cat":"Romance",
"ques":"Spencer Tracy and Katharine Hepburn play married lawyers at odds in the courtroom in what film?",
"answ":"ADAM'S RIB",
"answ3":"ADAMS RIB",
"answ2":"Adam's Rib.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>State of the Union</button><button id=incop2 class=buttons003 onclick=qinc()>Desk Set</button><button id=corop class=buttons003 onclick=qcor()>Adam's Rib</button><button id=incop4 class=buttons003 onclick=qinc()>Woman of the Year</button><br/>",
},
{
"cat":"Romance",
"ques":"What country music artist plays Brad's brother, Dallas, in Four Christmases?",
"answ":"TIM MCGRAW",
"answ2":"Tim McGraw.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tim McGraw</button><button id=incop2 class=buttons003 onclick=qinc()>Garth Brooks</button><button id=incop3 class=buttons003 onclick=qinc()>Keith Urban</button><button id=incop4 class=buttons003 onclick=qinc()>Brad Paisley</button><br/>",
},
{
"cat":"Romance",
"ques":"Richard Gere is training to become an officer in what military branch in 1982's An Officer and a Gentleman?",
"answ":"NAVY",
"answ3":"US NAVY",
"answ2":"Navy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Army</button><button id=incop2 class=buttons003 onclick=qinc()>Air Force</button><button id=corop class=buttons003 onclick=qcor()>Navy</button><button id=incop4 class=buttons003 onclick=qinc()>Woman of the Year</button><br/>",
},
{
"cat":"Romance",
"ques":"In Punch Drunk Love, Philip Seymour Hoffman plays a shady character who owns a store that sells what?",
"answ":"MATTRESSES",
"answ3":"MATRESSES",
"answ2":"Mattresses.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mattresses</button><button id=incop2 class=buttons003 onclick=qinc()>Womens Clothing</button><button id=incop3 class=buttons003 onclick=qinc()>Coffins</button><button id=incop4 class=buttons003 onclick=qinc()>Guns</button><br/>",
},
{
"cat":"Romance",
"ques":"Which actor plays an angel who falls in love with Meg Ryan's character in City of Angels?",
"answ":"NICOLAS CAGE",
"answ3":"NICHOLAS CAGE",
"answ2":"Nicolas Cage.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nicolas Cage</button><button id=incop2 class=buttons003 onclick=qinc()>John Travolta</button><button id=incop3 class=buttons003 onclick=qinc()>John Cusack</button><button id=incop4 class=buttons003 onclick=qinc()>Russell Crowe</button><br/>",
},
{
"cat":"Romance",
"ques":"What famous singer stars as the character Savannah Jackson opposite Angela Bassett in 1995's Waiting To Exhale?",
"answ":"WHITNEY HOUSTON",
"answ3":"WITNEY HOUSTON",
"answ2":"Whitney Houston.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Whitney Houston</button><button id=incop2 class=buttons003 onclick=qinc()>Madonna</button><button id=incop3 class=buttons003 onclick=qinc()>Jennifer Lopez</button><button id=incop4 class=buttons003 onclick=qinc()>Christina Aguilera</button><br/>",
},
];
romance = shuffle(romance);
r2Q25 = shuffle(r2Q25);