var pixar = [
{
"cat":"Pixar",
"ques":"What is the name of the robot that Wall-E falls for and chases across the galaxy?",
"answ":"EVE",
"answ2":"EVE.",
},
{
"cat":"Pixar",
"ques":"In Cars, who wins the tiebreaker race in LA at the end of the film?",
"answ":"CHICK HICKS",
"answ2":"Chick Hicks.",
},
{
"cat":"Pixar",
"ques":"In Toy Story 3, a toy of what kind of animal is in charge of watching the security cameras at night?",
"answ":"MONKEY",
"answ2":"Monkey.",
},
{
"cat":"Pixar",
"ques":"What is the name of the supervillain in The Incredibles?",
"answ":"SYNDROME",
"answ2":"Syndrome.",
},
{
"cat":"Pixar",
"ques":"At the end of Toy Story, what gift does Andy get for Christmas?",
"answ":"PUPPY",
"answ3":"DOG",
"answ2":"Puppy/Dog.",
},
{
"cat":"Pixar",
"ques":"Who composed the score for Up?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Pixar",
"ques":"What was Pixar's third theatrically released film that was released in 1999?",
"answ":"TOY STORY 2",
"answ2":"Toy Story 2.",
},
{
"cat":"Pixar",
"ques":"What is the first and last name of the one-eyed green monster voiced by Billy Crystal in Monster's, Inc?",
"answ":"MIKE WAZOWSKI",
"answ2":"Mike Wazowski.",
},
{
"cat":"Pixar",
"ques":"Toy Story was the first film released by Pixar, which 1998 film was the second?",
"answ":"A BUG'S LIFE",
"answ2":"A Bug's Life.",
},
{
"cat":"Pixar",
"ques":"In Coco, what is the name of the famous song that Ernesto De La Cruz stole from Hector?",
"answ":"REMEMBER ME",
"answ2":"Remember Me.",
},
{
"cat":"Pixar",
"ques":"Emperor Zurg is the arch nemesis of which Pixar character?",
"answ":"BUZZ LIGHTYEAR",
"answ2":"Buzz Lightyear.",
},
{
"cat":"Pixar",
"ques":"What relation does Coco have to Miguel in Coco?",
"answ":"GREAT GRANDMOTHER",
"answ2":"Great-grandmother.",
},
{
"cat":"Pixar",
"ques":"Who voices the character of The Underminer in The Incredibles and The Incredibles 2?",
"answ":"JOHN RATZENBERGER",
"answ2":"John Ratzenberger.",
},
{
"cat":"Pixar",
"ques":"In what Pixar film does Sigourney Weaver provide the voice of a character called Ship's Computer?",
"answ":"WALL E",
"answ2":"WALL-E.",
},
{
"cat":"Pixar",
"ques":"What storybook character has the affection of Woody in Toy Story?",
"answ":"BO PEEP",
"answ2":"Bo Peep.",
},
{
"cat":"Pixar",
"ques":"Released in 2007, what was the eight Pixar film?",
"answ":"RATATOUILLE",
"answ3":"RATATOUILE",
"answ2":"Ratatouille.",
},
{
"cat":"Pixar",
"ques":"In A Bug's Life, what is the actual occupation of the fake warriors that Flick hires?",
"answ":"CIRCUS PERFORMERS",
"answ3":"CIRCUS ARTISTS",
"answ2":"Circus performers.",
},
{
"cat":"Pixar",
"ques":"Who voices regal blue tang Dory, in Finding Nemo and Finding Dory?",
"answ":"ELLEN DEGENERES",
"answ2":"Ellen DeGeneres.",
},
{
"cat":"Pixar",
"ques":"What is the first name of the speedster son in The Incredibles?",
"answ":"DASH",
"answ3":"DASHIELL",
"answ2":"Dash.",
},
{
"cat":"Pixar",
"ques":"Carl Fredricksen is a character in what Pixar film?",
"answ":"UP",
"answ2":"Up.",
},
{
"cat":"Pixar",
"ques":"Who directed Ratatouille?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"Pixar",
"ques":"Who provided the voice of Edna Mode in The Incredibles?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"Pixar",
"ques":"Who directed Toy Story 2?",
"answ":"JOHN LASSETER",
"answ2":"John Lasseter.",
},
{
"cat":"Pixar",
"ques":"Who directed Monsters, Inc?",
"answ":"PETE DOCTER",
"answ3":"PETER DOCTER",
"answ2":"Pete Docter.",
},
{
"cat":"Pixar",
"ques":"Who provides the bubbly voice of Joy in Inside Out?",
"answ":"AMY POEHLER",
"answ2":"Amy Poehler.",
},
];
var r2Q28 = [
{
"cat":"Pixar",
"ques":"In Finding Nemo what was the pelican's name who befriended Nemo and assisted Marlin and Dory?",
"answ":"NIGEL",
"answ2":"Nigel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>William</button><button id=corop class=buttons003 onclick=qcor()>Nigel</button><button id=incop3 class=buttons003 onclick=qinc()>Oliver</button><button id=incop4 class=buttons003 onclick=qinc()>Frederick</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Up what was the name of Carl Fredricksen's wife?",
"answ":"ELLIE",
"answ3":"ELLY",
"answ2":"Ellie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sally</button><button id=incop2 class=buttons003 onclick=qinc()>Elise</button><button id=incop3 class=buttons003 onclick=qinc()>Kathy</button><button id=corop class=buttons003 onclick=qcor()>Ellie</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who provides the voice of Lotso the evil bear in Toy Story 3?",
"answ":"NED BEATTY",
"answ2":"Ned Beatty.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blake Clark</button><button id=incop2 class=buttons003 onclick=qinc()>Timothy Dalton</button><button id=incop3 class=buttons003 onclick=qinc()>Tim Allen</button><button id=corop class=buttons003 onclick=qcor()>Ned Beatty</button><br/>",
},
{
"cat":"Pixar",
"ques":"What was the first Pixar film to win Best Animated Feature at the Academy Awards?",
"answ":"FINDING NEMO",
"answ2":"Finding Nemo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toy Story</button><button id=incop2 class=buttons003 onclick=qinc()>Monsters, Inc.</button><button id=corop class=buttons003 onclick=qcor()>Finding Nemo</button><button id=incop4 class=buttons003 onclick=qinc()>The Incredibles</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced Hamm in the Toy Story films?",
"answ":"JOHN RATZENBERGER",
"answ2":"John Ratzenberger.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John Ratzenberger</button><button id=incop2 class=buttons003 onclick=qinc()>Kelsey Grammer</button><button id=incop3 class=buttons003 onclick=qinc()>Don Rickles</button><button id=incop4 class=buttons003 onclick=qinc()>Jim Varney</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of the bullying kid in Toy Story?",
"answ":"SID",
"answ2":"Sid.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sid</button><button id=incop2 class=buttons003 onclick=qinc()>Gus</button><button id=incop3 class=buttons003 onclick=qinc()>Dylan</button><button id=incop4 class=buttons003 onclick=qinc()>Andy</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Wall-E what does the E in Wally's name stand for?",
"answ":"EARTH CLASS",
"answ2":"Earth-Class.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Earth-Class</button><button id=incop2 class=buttons003 onclick=qinc()>Earth-Bot</button><button id=incop3 class=buttons003 onclick=qinc()>Earth-Cruiser</button><button id=incop4 class=buttons003 onclick=qinc()>Earth-Cleaner</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Toy Story 2, what animal is the mascot for Al's Toy Barn?",
"answ":"CHICKEN",
"answ2":"Chicken.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pig</button><button id=corop class=buttons003 onclick=qcor()>Chicken</button><button id=incop3 class=buttons003 onclick=qinc()>Cow</button><button id=incop4 class=buttons003 onclick=qinc()>Goat</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced cranky old man Carl Fredricksen in Up?",
"answ":"ED ASNER",
"answ2":"Ed Asner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=corop class=buttons003 onclick=qcor()>Ed Asner</button><button id=incop3 class=buttons003 onclick=qinc()>John Ratzenberger</button><button id=incop4 class=buttons003 onclick=qinc()>Don Rickles</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Cars, what racing trophy does Lighning McQueen want to win?",
"answ":"PISTON CUP",
"answ2":"Piston Cup.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Piston Cup</button><button id=incop2 class=buttons003 onclick=qinc()>Charlotte Cup</button><button id=incop3 class=buttons003 onclick=qinc()>Skyrocket Cup</button><button id=incop4 class=buttons003 onclick=qinc()>Diamond Cup</button><br/>",
},
{
"cat":"Pixar",
"ques":"Remy the rat helps a young man named what in Ratatouille?",
"answ":"ALFREDO",
"answ3":"ALFREDO LINGUINI",
"answ2":"Alfredo Linguini.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mario</button><button id=incop2 class=buttons003 onclick=qinc()>Gusteau</button><button id=incop3 class=buttons003 onclick=qinc()>Horst</button><button id=corop class=buttons003 onclick=qcor()>Linguini</button><br/>",
},
{
"cat":"Pixar",
"ques":"What kind of candy distracts Heimlich the caterpillar during his circus performance in A Bug's Life?",
"answ":"CANDY CORN",
"answ3":"CANDY CORNS",
"answ2":"Candy Corn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Twizzlers</button><button id=corop class=buttons003 onclick=qcor()>Candy Corn</button><button id=incop3 class=buttons003 onclick=qinc()>Life Savers</button><button id=incop4 class=buttons003 onclick=qinc()>Jolly Ranchers</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced Slinky Dog in 1995's Toy Story?",
"answ":"JIM VARNEY",
"answ2":"Jim Varney.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jim Varney</button><button id=incop2 class=buttons003 onclick=qinc()>John Ratzenberger</button><button id=incop3 class=buttons003 onclick=qinc()>Don Rickles</button><button id=incop4 class=buttons003 onclick=qinc()>Wallace Shawn</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who provided the 'voice' of WALL-E?",
"answ":"BEN BURTT",
"answ3":"BEN BURT",
"answ2":"Ben Burtt.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ben Burtt</button><button id=incop2 class=buttons003 onclick=qinc()>Brad Bird</button><button id=incop3 class=buttons003 onclick=qinc()>Jeff Garlin</button><button id=incop4 class=buttons003 onclick=qinc()>Fred Willard</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name given to the bird-like creature in Up?",
"answ":"KEVIN",
"answ2":"Kevin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kevin</button><button id=incop2 class=buttons003 onclick=qinc()>Adam</button><button id=incop3 class=buttons003 onclick=qinc()>Harry</button><button id=incop4 class=buttons003 onclick=qinc()>Chris</button><br/>",
},
{
"cat":"Pixar",
"ques":"What does the Abominable Snowman make for Mike & Sully after they have been banished in Monsters, Inc?",
"answ":"SNOW CONES",
"answ3":"SNOWCONES",
"answ2":"Snow cones.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Snow cones</button><button id=incop2 class=buttons003 onclick=qinc()>Reindeer soup</button><button id=incop3 class=buttons003 onclick=qinc()>Snow pie</button><button id=incop4 class=buttons003 onclick=qinc()>Squirrel steak</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced Sally the Porsche in the Pixar films Cars, Cars 2 and Cars 3?",
"answ":"BONNIE HUNT",
"answ2":"Bonnie Hunt.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Bonnie Hunt</button><button id=incop2 class=buttons003 onclick=qinc()>Jenifer Lewis</button><button id=incop3 class=buttons003 onclick=qinc()>Tilda Swinton</button><button id=incop4 class=buttons003 onclick=qinc()>Joan Cusack</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Wall-E, the lonely robots watches a clip of the song 'It Only Takes A Moment' from what classic musical?",
"answ":"HELLO DOLLY",
"answ3":"HELLO  DOLLY",
"answ2":"Hello, Dolly!.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hello, Dolly!</button><button id=incop2 class=buttons003 onclick=qinc()>The Sound of Music</button><button id=incop3 class=buttons003 onclick=qinc()>West Side Story</button><button id=incop4 class=buttons003 onclick=qinc()>My Fair Lady</button><br/>",
},
{
"cat":"Pixar",
"ques":"In The Incredibles, Mr. Incredibles hides behind the skeleton of what former superhero to avoid detection?",
"answ":"GAZERBEAM",
"answ2":"Gazerbeam.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blazestone</button><button id=incop2 class=buttons003 onclick=qinc()>Downburst</button><button id=incop3 class=buttons003 onclick=qinc()>Appogee</button><button id=corop class=buttons003 onclick=qcor()>Gazerbeam</button><br/>",
},
{
"cat":"Pixar",
"ques":"Name the Pixar movie: 'Authority should derive from consent of the governed, not from the threat of force'",
"answ":"TOY STORY 3",
"answ2":"Toy Story 3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Monsters, Inc</button><button id=incop2 class=buttons003 onclick=qinc()>Cars 2</button><button id=incop3 class=buttons003 onclick=qinc()>Finding Nemo</button><button id=corop class=buttons003 onclick=qcor()>Toy Story 3</button><br/>",
},
{
"cat":"Pixar",
"ques":"What was the Doberman Pincher leader's name in Up?",
"answ":"ALPHA",
"answ2":"Alpha.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alpha</button><button id=incop2 class=buttons003 onclick=qinc()>Razor</button><button id=incop3 class=buttons003 onclick=qinc()>Number 1</button><button id=incop4 class=buttons003 onclick=qinc()>Jacque</button><br/>",
},
{
"cat":"Pixar",
"ques":"What sitcom actor voices Molt, Hopper's dim-witted brother in A Bug's Life and Bing Bong in Inside Out?",
"answ":"RICHARD KIND",
"answ2":"Richard Kind.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paul Reiser</button><button id=corop class=buttons003 onclick=qcor()>Richard Kind</button><button id=incop3 class=buttons003 onclick=qinc()>Barry Bostwick</button><button id=incop4 class=buttons003 onclick=qinc()>Patrick Warburton</button><br/>",
},
{
"cat":"Pixar",
"ques":"What kind of dinosaurs were the cattle rustlers in The Good Dinosaur?",
"answ":"VELOCIRAPTOR",
"answ3":"VELOCIRAPTORS",
"answ2":"Velociraptor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dilophosaurus</button><button id=incop2 class=buttons003 onclick=qinc()>Tyrannosaurus</button><button id=incop3 class=buttons003 onclick=qinc()>Triceratops</button><button id=corop class=buttons003 onclick=qcor()>Velociraptor</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voices prospector Stinky Pete in Toy Stoy 2?",
"answ":"KELSEY GRAMMER",
"answ2":"Kelsey Grammer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>R. Lee Ermey</button><button id=incop2 class=buttons003 onclick=qinc()>Jonathan Harris</button><button id=incop3 class=buttons003 onclick=qinc()>Wayne Knight</button><button id=corop class=buttons003 onclick=qcor()>Kelsey Grammer</button><br/>",
},
{
"cat":"Pixar",
"ques":"What animal distracts the dog in Up?",
"answ":"SQUIRREL",
"answ2":"Squirrel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cat</button><button id=incop2 class=buttons003 onclick=qinc()>Rat</button><button id=incop3 class=buttons003 onclick=qinc()>Hedgehog</button><button id=corop class=buttons003 onclick=qcor()>Squirrel</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who directed Toy Story 4?",
"answ":"JOSH COOLEY",
"answ2":"Josh Cooley.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andrew Stanton</button><button id=incop2 class=buttons003 onclick=qinc()>Lee Unkrich</button><button id=incop3 class=buttons003 onclick=qinc()>John Lasseter</button><button id=corop class=buttons003 onclick=qcor()>Josh Cooley</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced Forky in Toy Story 4?",
"answ":"TONY HALE",
"answ2":"Tony Hale.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bill Hader</button><button id=incop2 class=buttons003 onclick=qinc()>Jay Hernandez</button><button id=incop3 class=buttons003 onclick=qinc()>John C. Reilly</button><button id=corop class=buttons003 onclick=qcor()>Tony Hale</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of the villain that uses TV's to hypnotize people in The Incredibles 2?",
"answ":"SCREENSLAVER",
"answ3":"THE SCREENSLAVER",
"answ2":"Screenslaver.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Underminder</button><button id=incop2 class=buttons003 onclick=qinc()>Syndrome</button><button id=incop3 class=buttons003 onclick=qinc()>Mezmerella</button><button id=corop class=buttons003 onclick=qcor()>Screenslaver</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of 12-year old boy that dreams of becoming a musician in Coco?",
"answ":"MIGUEL",
"answ2":"Miguel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Felipe</button><button id=incop2 class=buttons003 onclick=qinc()>Oscar</button><button id=incop3 class=buttons003 onclick=qinc()>Carlos</button><button id=corop class=buttons003 onclick=qcor()>Miguel</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Inside Out, what veggie does Riley hate?",
"answ":"BROCCOLI",
"answ3":"BROCOLI",
"answ2":"Broccoli.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Carrots</button><button id=incop2 class=buttons003 onclick=qinc()>Tomatoes</button><button id=incop3 class=buttons003 onclick=qinc()>Lettuce</button><button id=corop class=buttons003 onclick=qcor()>Broccoli</button><br/>",
},
{
"cat":"Pixar",
"ques":"Buck and Libby are the siblings of what Pixar character?",
"answ":"ARLO",
"answ3":"THE GOOD DINOSAUR",
"answ2":"Arlo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mike Wazowski</button><button id=incop2 class=buttons003 onclick=qinc()>Remy</button><button id=incop3 class=buttons003 onclick=qinc()>Flik</button><button id=corop class=buttons003 onclick=qcor()>Arlo</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of Woody's trusty steed that he first meets in Toy Story 2?",
"answ":"BULLSEYE",
"answ2":"Bullseye.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bucky</button><button id=incop2 class=buttons003 onclick=qinc()>Cisco</button><button id=incop3 class=buttons003 onclick=qinc()>Copper</button><button id=corop class=buttons003 onclick=qcor()>Bullseye</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voiced Charlie, Dory's father in Finding Dory?",
"answ":"EUGENE LEVY",
"answ3":"EUGENE LEVI",
"answ2":"Eugene Levy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ed O'Neill</button><button id=incop2 class=buttons003 onclick=qinc()>Chevy Chase</button><button id=corop class=buttons003 onclick=qcor()>Eugene Levy</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Hader</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of the daughter that can turn invisible in The Incredibles?",
"answ":"VIOLET",
"answ2":"Violet.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Samantha</button><button id=incop2 class=buttons003 onclick=qinc()>Amber</button><button id=corop class=buttons003 onclick=qcor()>Violet</button><button id=incop4 class=buttons003 onclick=qinc()>Susan</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the number of Lightning McQueen's car in Cars?",
"answ":"95",
"answ2":"95.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=incop2 class=buttons003 onclick=qinc()>24</button><button id=incop3 class=buttons003 onclick=qinc()>55</button><button id=corop class=buttons003 onclick=qcor()>95</button><br/>",
},
{
"cat":"Pixar",
"ques":"From what state did Riley and her family move from in Inside Out?",
"answ":"MINNESOTA",
"answ2":"Minnesota.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Minnesota</button><button id=incop2 class=buttons003 onclick=qinc()>Michigan</button><button id=incop3 class=buttons003 onclick=qinc()>Wisconsin</button><button id=incop4 class=buttons003 onclick=qinc()>Iowa</button><br/>",
},
{
"cat":"Pixar",
"ques":"What Pixar film was the first to receive a PG-rating in the US?",
"answ":"THE INCREDIBLES",
"answ3":"INCREDIBLES",
"answ2":"The Incredibles.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cars</button><button id=corop class=buttons003 onclick=qcor()>The Incredibles</button><button id=incop3 class=buttons003 onclick=qinc()>Monsters, Inc</button><button id=incop4 class=buttons003 onclick=qinc()>WALL-E</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Toy Story 2 we finally meet Buzz's archrival, an evil emperor, space villain that goes by what name?",
"answ":"ZURG",
"answ2":"Zurg.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scud</button><button id=corop class=buttons003 onclick=qcor()>Zurg</button><button id=incop3 class=buttons003 onclick=qinc()>Mor'du</button><button id=incop4 class=buttons003 onclick=qinc()>Skurge</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Finding Nemo, what does Dory name the baby jellyfish she finds?",
"answ":"SQUASHY",
"answ3":"SQUASHIE",
"answ2":"Squashy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Squishy</button><button id=corop class=buttons003 onclick=qcor()>Squashy</button><button id=incop3 class=buttons003 onclick=qinc()>Jiggly</button><button id=incop4 class=buttons003 onclick=qinc()>Phil</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of Sid's dog that terrorizes Woody and Buzz in the original Toy Story?",
"answ":"SCUD",
"answ2":"Scud.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Scud</button><button id=incop2 class=buttons003 onclick=qinc()>Spud</button><button id=incop3 class=buttons003 onclick=qinc()>Rover</button><button id=incop4 class=buttons003 onclick=qinc()>Spike</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voices the octopus Hank in Finding Dory?",
"answ":"ED O'NEILL",
"answ3":"ED O'NEIL",
"answ2":"Ed O'Neill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ty Burrell</button><button id=incop2 class=buttons003 onclick=qinc()>Eugene Levy</button><button id=corop class=buttons003 onclick=qcor()>Ed O'Neill</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Hader</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of the mega-corporation in Wall-E?",
"answ":"BUY N LARGE",
"answ3":"BUY AND LARGE",
"answ2":"Buy n Large.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dinoco</button><button id=incop2 class=buttons003 onclick=qinc()>Pizza Planet</button><button id=corop class=buttons003 onclick=qcor()>Buy n Large</button><button id=incop4 class=buttons003 onclick=qinc()>Acme Corporation</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Inside Out, what kind of product had a jingle that kept being played, annoying all of the emotions?",
"answ":"GUM",
"answ2":"Gum.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soda</button><button id=corop class=buttons003 onclick=qcor()>Gum</button><button id=incop3 class=buttons003 onclick=qinc()>Ice Cream</button><button id=incop4 class=buttons003 onclick=qinc()>Toy Store</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Brave, who voices Merida's mother, Queen Elinor?",
"answ":"EMMA THOMPSON",
"answ2":"Emma Thompson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=incop2 class=buttons003 onclick=qinc()>Kate Winslet</button><button id=corop class=buttons003 onclick=qcor()>Emma Thompson</button><button id=incop4 class=buttons003 onclick=qinc()>Carey Mulligan</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who is playing the Buzz Lightyear video game at the very beginning of Toy Story 2?",
"answ":"REX",
"answ2":"Rex.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Woody</button><button id=incop2 class=buttons003 onclick=qinc()>Hamm</button><button id=corop class=buttons003 onclick=qcor()>Rex</button><button id=incop4 class=buttons003 onclick=qinc()>Slinky Dog</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Inside Out, what was the occupation of the hunky man that the mom daydreamed about off and on throughout the movie?",
"answ":"HELICOPTER PILOT",
"answ3":"PILOT",
"answ2":"Helicopter pilot.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Helicoper pilot</button><button id=incop2 class=buttons003 onclick=qinc()>Surgeon</button><button id=incop3 class=buttons003 onclick=qinc()>Lawyer</button><button id=incop4 class=buttons003 onclick=qinc()>Lifeguard</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voices Slim, a walking stick in A Bug's Life?",
"answ":"DAVID HYDE PIERCE",
"answ2":"David Hyde Pierce.",
"option":"<button id=corop class=buttons003 onclick=qcor()>David Hyde Pierce</button><button id=incop2 class=buttons003 onclick=qinc()>Richard Kind</button><button id=incop3 class=buttons003 onclick=qinc()>Dave Foley</button><button id=incop4 class=buttons003 onclick=qinc()>Kevin Spacey</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Coco, what is the name of the down-on-his-luck skeleton who offers to help Miguel reach Ernesto de la Cruz?",
"answ":"HECTOR",
"answ2":"Hector.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hector</button><button id=incop2 class=buttons003 onclick=qinc()>Leon</button><button id=incop3 class=buttons003 onclick=qinc()>Julio</button><button id=incop4 class=buttons003 onclick=qinc()>Emilio</button><br/>",
},
{
"cat":"Pixar",
"ques":"What was the name of the human boy in The Good Dinosaur?",
"answ":"SPOT",
"answ2":"Spot.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Spot</button><button id=incop2 class=buttons003 onclick=qinc()>Rex</button><button id=incop3 class=buttons003 onclick=qinc()>Spike</button><button id=incop4 class=buttons003 onclick=qinc()>Stinky</button><br/>",
},
{
"cat":"Pixar",
"ques":"In The Incredibles, hero costume designer Edna Mode never includes what in her costume designs?",
"answ":"CAPE",
"answ3":"CAPES",
"answ2":"Capes.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Capes</button><button id=incop2 class=buttons003 onclick=qinc()>Purple</button><button id=incop3 class=buttons003 onclick=qinc()>Buttons</button><button id=incop4 class=buttons003 onclick=qinc()>Zippers</button><br/>",
},
{
"cat":"Pixar",
"ques":"What was the name of the fraternity of misfits that Mike joins in Monsters University?",
"answ":"OOZMA KAPPA",
"answ2":"Oozma Kappa.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Roar Omega Roar</button><button id=corop class=buttons003 onclick=qcor()>Oozma Kappa</button><button id=incop3 class=buttons003 onclick=qinc()>Omega Howl</button><button id=incop4 class=buttons003 onclick=qinc()>Lambda Lambda Lambda</button><br/>",
},
{
"cat":"Pixar",
"ques":"Lloyd Cher replaced which legendary comedian as Fillmore in Cars 2?",
"answ":"GEORGE CARLIN",
"answ2":"George Carlin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Woody Allen</button><button id=corop class=buttons003 onclick=qcor()>George Carlin</button><button id=incop3 class=buttons003 onclick=qinc()>Dom Deluise</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Rickman</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Finding Nemo, what nickname was Nemo given in the fishtank at the dentist office?",
"answ":"SHARKBAIT",
"answ2":"Sharkbait.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scuttlebutt</button><button id=incop2 class=buttons003 onclick=qinc()>Flipper</button><button id=incop3 class=buttons003 onclick=qinc()>Stripes</button><button id=corop class=buttons003 onclick=qcor()>Sharkbait</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Incredibles 2, who voices Winston Deavor, a superhero fan who wants to bring superheroes through revamping the public's perception?",
"answ":"BOB ODENKIRK",
"answ2":"Bob Odenkirk.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Will Arnett</button><button id=incop2 class=buttons003 onclick=qinc()>Dustin Hoffman</button><button id=corop class=buttons003 onclick=qcor()>Bob Odenkirk</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Helms</button><br/>",
},
{
"cat":"Pixar",
"ques":"What was the first Pixar movie to be nominated for Best Picture at the Oscars?",
"answ":"UP",
"answ2":"Up.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toy Story</button><button id=incop2 class=buttons003 onclick=qinc()>Finding Nemo</button><button id=corop class=buttons003 onclick=qcor()>Up</button><button id=incop4 class=buttons003 onclick=qinc()>Ratatouille</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Brave, what is the name of the monstrous bear that was the prince from old legends?",
"answ":"MORDU",
"answ3":"MOR'DU",
"answ2":"Mor'du.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mor'du</button><button id=incop2 class=buttons003 onclick=qinc()>Grey</button><button id=incop3 class=buttons003 onclick=qinc()>Mordred</button><button id=incop4 class=buttons003 onclick=qinc()>Kurgan</button><br/>",
},
{
"cat":"Pixar",
"ques":"In The Incredibles, after the public turns on superheroes, the government initiates which program to force heroes to permanently keep their secret identities?",
"answ":"SUPERHERO RELOCATION PROGRAM",
"answ3":"THE SUPERHERO RELOCATION PROGRAM",
"answ2":"Superhero Relocation Program.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Identity Change Program</button><button id=incop2 class=buttons003 onclick=qinc()>Superhero Eraser Program</button><button id=incop3 class=buttons003 onclick=qinc()>Identity Permanence Program</button><button id=corop class=buttons003 onclick=qcor()>Superhero Relocation Program</button><br/>",
},
{
"cat":"Pixar",
"ques":"What is the name of the giant ship that humans now live on in Wall-E?",
"answ":"AXIOM",
"answ3":"THE AXIOM",
"answ2":"The Axiom.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Ark</button><button id=corop class=buttons003 onclick=qcor()>The Axiom</button><button id=incop3 class=buttons003 onclick=qinc()>The Aries</button><button id=incop4 class=buttons003 onclick=qinc()>The Argo</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Monsters Inc, what do monsters discover is more powerful than children's screams?",
"answ":"LAUGHTER",
"answ3":"LAUGHING",
"answ2":"Laughter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Love</button><button id=corop class=buttons003 onclick=qcor()>Laughter</button><button id=incop3 class=buttons003 onclick=qinc()>Tears</button><button id=incop4 class=buttons003 onclick=qinc()>Kindness</button><br/>",
},
{
"cat":"Pixar",
"ques":"The characters Jessie the Cowgirl and Bullseye the Horse are introduced in which film in the Toy Story franchise?",
"answ":"TOY STORY 2",
"answ3":"TOY STORY II",
"answ2":"Toy Story 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toy Story</button><button id=corop class=buttons003 onclick=qcor()>Toy Story 2</button><button id=incop3 class=buttons003 onclick=qinc()>Toy Story 3</button><button id=incop4 class=buttons003 onclick=qinc()>Toy Story 4</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voices Remy's father, Django, in Ratatouille?",
"answ":"BRIAN DENNEHY",
"answ3":"BRYAN DENNEHY",
"answ2":"Brian Dennehy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ian Holm</button><button id=incop2 class=buttons003 onclick=qinc()>Brad Garrett</button><button id=corop class=buttons003 onclick=qcor()>Brian Dennehy</button><button id=incop4 class=buttons003 onclick=qinc()>James Remar</button><br/>",
},
{
"cat":"Pixar",
"ques":"What type of animals are Fluke and Rudder, voiced by Idris Elba and Dominic West, in Finding Dory?",
"answ":"SEA LIONS",
"answ3":"SEA LION",
"answ2":"Sea lions.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sharks</button><button id=incop2 class=buttons003 onclick=qinc()>Sea turtles</button><button id=corop class=buttons003 onclick=qcor()>Sea lions</button><button id=incop4 class=buttons003 onclick=qinc()>Pelicans</button><br/>",
},
{
"cat":"Pixar",
"ques":"Which character in The Incredibles tell Mr. Incredible: 'My God, you've gotten fat'?",
"answ":"ETNA MODE",
"answ3":"EDNA MODE",
"answ2":"Etna Mode.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mirage</button><button id=incop2 class=buttons003 onclick=qinc()>Syndrome</button><button id=corop class=buttons003 onclick=qcor()>Etna Mode</button><button id=incop4 class=buttons003 onclick=qinc()>Frozone</button><br/>",
},
{
"cat":"Pixar",
"ques":"Who voices Jackson Storm, McQueen's new racing rival, in Cars 3?",
"answ":"ARMIE HAMMER",
"answ2":"Armie Hammer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=incop2 class=buttons003 onclick=qinc()>Nathan Fillion</button><button id=corop class=buttons003 onclick=qcor()>Armie Hammer</button><button id=incop4 class=buttons003 onclick=qinc()>Chris Cooper</button><br/>",
},
{
"cat":"Pixar",
"ques":"In The Incredibles, Bob Parr's boss mentions that a company is like an enormous what?",
"answ":"CLOCK",
"answ2":"Clock.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Assembly Line</button><button id=corop class=buttons003 onclick=qcor()>Clock</button><button id=incop3 class=buttons003 onclick=qinc()>Engine</button><button id=incop4 class=buttons003 onclick=qinc()>Piano</button><br/>",
},
{
"cat":"Pixar",
"ques":"Which Pixar film involves a young boy named Russell, who is a wilderness scout trying to earn an 'assisting the elderly' badge?",
"answ":"UP",
"answ2":"Up.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Inside Out</button><button id=corop class=buttons003 onclick=qcor()>Up</button><button id=incop3 class=buttons003 onclick=qinc()>Coco</button><button id=incop4 class=buttons003 onclick=qinc()>Toy Story 3</button><br/>",
},
{
"cat":"Pixar",
"ques":"Willem Dafoe voices the character of Gill in what 2003 Pixar film?",
"answ":"FINDING NEMO",
"answ2":"Finding Nemo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ratatouille</button><button id=corop class=buttons003 onclick=qcor()>Finding Nemo</button><button id=incop3 class=buttons003 onclick=qinc()>Cars</button><button id=incop4 class=buttons003 onclick=qinc()>Toy Story 2</button><br/>",
},
{
"cat":"Pixar",
"ques":"Randy Newman performs the song 'The Time Of Your Life' in what 90s Pixar film?",
"answ":"A BUG'S LIFE",
"answ3":"A BUGS LIFE",
"answ2":"A Bug's Life.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toy Story</button><button id=corop class=buttons003 onclick=qcor()>A Bug's Life</button><button id=incop3 class=buttons003 onclick=qinc()>Toy Story 2</button><button id=incop4 class=buttons003 onclick=qinc()>Finding Nemo</button><br/>",
},
{
"cat":"Pixar",
"ques":"In Wall-E, what discarded object does the title character show to the unimpressed sleek robot Eve?",
"answ":"RUBIK'S CUBE",
"answ3":"RUBIK CUBE",
"answ2":"Rubik's Cube.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tonka Toy</button><button id=corop class=buttons003 onclick=qcor()>Rubik's Cube</button><button id=incop3 class=buttons003 onclick=qinc()>Magic 8-Ball</button><button id=incop4 class=buttons003 onclick=qinc()>Etch-a-Sketch</button><br/>",
},
];
pixar = shuffle(pixar);
r2Q28 = shuffle(r2Q28);