var sports = [
{
"cat":"Sports",
"ques":"Who stars in and produced the 2012 baseball movie Trouble with the Curve?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
},
{
"cat":"Sports",
"ques":"The films Seabiscuit and Secretariat both depict what sport?",
"answ":"HORSE RACING",
"answ2":"Horse racing.",
},
{
"cat":"Sports",
"ques":"The formidable boxing villain Ivan Drago first appeared in what 1985 boxing film?",
"answ":"ROCKY IV",
"answ3":"ROCKY 4",
"answ2":"Rocky IV.",
},
{
"cat":"Sports",
"ques":"Which baseball film features such actors as Robert Duvall, Wilford Brimley and Michael Madsen?",
"answ":"THE NATURAL",
"answ2":"The Natural.",
},
{
"cat":"Sports",
"ques":"What basketball legend portrays a ballplayer named Neon in 1994's Blue Chips?",
"answ":"SHAQUILLE O'NEAL",
"answ3":"SHAQ",
"answ2":"Shaquille O'Neal.",
},
{
"cat":"Sports",
"ques":"What kind of animal is Bill Murray's Carl Spackler going to war with in 1980's Caddyshack?",
"answ":"GOPHER",
"answ2":"Gopher.",
},
{
"cat":"Sports",
"ques":"Who plays the fearsome boxer Clubber Lang in the Rocky franchise?",
"answ":"MISTER T",
"answ3":"MR T",
"answ2":"Mr. T.",
},
{
"cat":"Sports",
"ques":"Ray Liotta plays Shoeless Joe Jackson and James Earl Jones plays Terance Mann in what 1989 baseball drama?",
"answ":"FIELD OF DREAMS",
"answ2":"Field of Dreams.",
},
{
"cat":"Sports",
"ques":"In Trouble With The Curve, who plays former player and now scout Johnny 'The Flame' Flanagan?",
"answ":"JUSTIN TIMBERLAKE",
"answ2":"Justin Timberlake.",
},
{
"cat":"Sports",
"ques":"What is the title of the 6th film in the Rocky franchise, released in 2006?",
"answ":"ROCKY BALBOA",
"answ2":"Rocky Balboa.",
},
{
"cat":"Sports",
"ques":"Michael B. Jordan and Sylvester Stallone star in what 2018 boxing film from director Steven Caple Jr.?",
"answ":"CREED II",
"answ3":"CREED 2",
"answ2":"Creed II.",
},
{
"cat":"Sports",
"ques":"Who stars as an underachieving gambler who ends up coaching a little league team in 2001's Hardball?",
"answ":"KEANU REEVES",
"answ2":"Keanu Reeves.",
},
{
"cat":"Sports",
"ques":"The 2015 sports film MacFarland, USA primarily revolves around which sport?",
"answ":"RUNNING",
"answ3":"CROSS COUNTRY RUNNING",
"answ2":"Running/Cross country running.",
},
{
"cat":"Sports",
"ques":"Jackie Moon is the owner, head coach, power forward, and pre-game announcer for the Flint Tropics in what comedy?",
"answ":"SEMI PRO",
"answ2":"Semi-Pro.",
},
{
"cat":"Sports",
"ques":"Which actress plays Maureen Hope, the wife to Billy Hope that is tragically killed, in the film Southpaw?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
},
{
"cat":"Sports",
"ques":"Mike Ditka plays himself while helping Will Ferrell's character in what soccer film?",
"answ":"KICKING AND SCREAMING",
"answ2":"Kicking and Screaming.",
},
{
"cat":"Sports",
"ques":"In Bloodsport, how long does the legendary martial arts tournament last that is held in Hong Kong?",
"answ":"3 DAYS",
"answ3":"THREE DAYS",
"answ2":"Three days.",
},
{
"cat":"Sports",
"ques":"Which actor plays basketball coach Jack Cunningham in the 2020 film The Way Back?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
},
{
"cat":"Sports",
"ques":"Who plays hockey coach Gordon Bombay in The Mighty Ducks?",
"answ":"EMILIO ESTEVEZ",
"answ2":"Emilio Estevez.",
},
{
"cat":"Sports",
"ques":"Mark Wahlberg's character plays what sport in 2006's Invincible?",
"answ":"AMERICAN FOOTBALL",
"answ3":"FOOTBALL",
"answ2":"American football.",
},
{
"cat":"Sports",
"ques":"Who plays Drew Barrymore's co-lead in Fever Pitch?",
"answ":"JIMMY FALLON",
"answ2":"Jimmy Fallon.",
},
{
"cat":"Sports",
"ques":"What Friends actor starred in the 1996 comedy Ed, playing a baseball pitcher who has a chimpanzee as a roommate and a teammate?",
"answ":"MATT LEBLANC",
"answ3":"MATT LABLANC",
"answ2":"Matt LeBlanc.",
},
{
"cat":"Sports",
"ques":"Who does Rocky fight in the climactic boxing match in Rocky II?",
"answ":"APOLLO CREED",
"answ2":"Apollo Creed.",
},
{
"cat":"Sports",
"ques":"Who plays the famously hot-headed tennis player John McEnroe in 2017's Borg vs. McEnroe?",
"answ":"SHIA LABEOUF",
"answ3":"SHIA LEBEOUF",
"answ2":"Shia LaBeouf.",
},
{
"cat":"Sports",
"ques":"Who directed Chris Hemsworth in the 2013 race car film Rush?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
},
{
"cat":"Sports",
"ques":"Harrison Ford stars as Branch Rickey alongside Chadwick Boseman in what film?",
"answ":"42",
"answ2":"42.",
},
{
"cat":"Sports",
"ques":"Which team is Jimmy Fallon a fan of in the film Fever Pitch?",
"answ":"BOSTON RED SOX",
"answ3":"RED SOX",
"answ2":"Boston Red Sox.",
},
{
"cat":"Sports",
"ques":"Who played Willie Mays Hayes in Major League?",
"answ":"WESLEY SNIPES",
"answ2":"Wesley Snipes.",
},
{
"cat":"Sports",
"ques":"In White Men Can't Jump, Rosie Perez's character, Gloria, is studying to compete on what game show?",
"answ":"JEOPARDY",
"answ2":"Jeopardy.",
},
{
"cat":"Sports",
"ques":"What is Benny Rodriguez's baseball nickname in The Sandlot?",
"answ":"THE JET",
"answ3":"JET",
"answ2":"The Jet.",
},
{
"cat":"Sports",
"ques":"What movie starred Tom Hardy and Joel Edgerton as brothers competing in a mixed martial arts tournament?",
"answ":"WARRIOR",
"answ2":"Warrior.",
},
{
"cat":"Sports",
"ques":"Who played quarterback Paul Crewe in the original The Longest Yard?",
"answ":"BURT REYNOLDS",
"answ2":"Burt Reynolds.",
},
{
"cat":"Sports",
"ques":"In what city does Fever Pitch take place?",
"answ":"BOSTON",
"answ2":"Boston.",
},
{
"cat":"Sports",
"ques":"In The Mighty Ducks, what was the name of the hockey coach that coached the Ducks?",
"answ":"GORDON BOMBAY",
"answ2":"Gordon Bombay.",
},
{
"cat":"Sports",
"ques":"Who directed Space Jam?",
"answ":"JOE PYTKA",
"answ2":"Joe Pytka.",
},
{
"cat":"Sports",
"ques":"What was the last name of Randy The Ram in The Wrestler?",
"answ":"ROBINSON",
"answ2":"Robinson.",
},
{
"cat":"Sports",
"ques":"What is the name of the team coached by Nick Nolte in Blue Chips?",
"answ":"WESTERN UNIVERSITY DOLPHINS",
"answ2":"Western University Dolphins.",
},
{
"cat":"Sports",
"ques":"Who do the Indians play in the one-game playoff and the end of Major League?",
"answ":"YANKEES",
"answ3":"NEW YORK YANKEES",
"answ2":"Yankees.",
},
{
"cat":"Sports",
"ques":"What actor received a Best Supporting Actor nomination for playing Howard Cosell in 2001's Ali?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
},
{
"cat":"Sports",
"ques":"Which hockey movie follows the exploits of the Charlestown Chiefs?",
"answ":"SLAP SHOT",
"answ2":"Slap Shot.",
},
{
"cat":"Sports",
"ques":"Which real life boxer played Tommy Gunn in Rocky V?",
"answ":"TOMMY MORRISON",
"answ2":"Tommy Morrison.",
},
{
"cat":"Sports",
"ques":"Wilford Brimley played manager Pop Fisher in which baseball flick?",
"answ":"THE NATURAL",
"answ2":"The Natural.",
},
];
var r2Q30 = [
{
"cat":"Sports",
"ques":"'Au revoir, gopher' is a line from what golf movie?",
"answ":"CADDYSHACK",
"answ2":"Caddyshack.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Happy Gilmore</button><button id=corop class=buttons003 onclick=qcor()>Caddyshack</button><button id=incop3 class=buttons003 onclick=qinc()>Who's Your Caddy?</button><button id=incop4 class=buttons003 onclick=qinc()>The Caddy</button><br/>",
},
{
"cat":"Sports",
"ques":"What noted athlete appears in There's Something About Mary?",
"answ":"BRETT FAVRE",
"answ2":"Brett Favre.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Brady</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Jordan</button><button id=corop class=buttons003 onclick=qcor()>Brett Favre</button><button id=incop4 class=buttons003 onclick=qinc()>Terry Bradshaw</button><br/>",
},
{
"cat":"Sports",
"ques":"In Little Big League 12-year old Billy Heywood becomes owner and manager of what major league baseball team?",
"answ":"MINNESOTA TWINS",
"answ2":"Minnesota Twins.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago Cubs</button><button id=incop2 class=buttons003 onclick=qinc()>Seattle Mariners</button><button id=corop class=buttons003 onclick=qcor()>Minnesota Twins</button><button id=incop4 class=buttons003 onclick=qinc()>Detroit Tigers</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played legendary hockey coach Herb Brooks in Miracle?",
"answ":"KURT RUSSELL",
"answ2":"Kurt Russell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kurt Russell</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=incop4 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><br/>",
},
{
"cat":"Sports",
"ques":"The 2002 film Blue Crush features which sport?",
"answ":"SURFING",
"answ2":"Surfing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Swimming</button><button id=corop class=buttons003 onclick=qcor()>Surfing</button><button id=incop3 class=buttons003 onclick=qinc()>Water polo</button><button id=incop4 class=buttons003 onclick=qinc()>Rowing</button><br/>",
},
{
"cat":"Sports",
"ques":"You'll find characters named Sidney Deane and Billy Hoyle in which basketball film?",
"answ":"WHITE MEN CAN'T JUMP",
"answ2":"White Men Can't Jump.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Semi-Pro</button><button id=incop2 class=buttons003 onclick=qinc()>Crossover</button><button id=corop class=buttons003 onclick=qcor()>White Men Can't Jump</button><button id=incop4 class=buttons003 onclick=qinc()>Coach Carter</button><br/>",
},
{
"cat":"Sports",
"ques":"What baseball movie is based on the novel Shoeless Joe?",
"answ":"FIELD OF DREAMS",
"answ2":"Field of Dreams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Natural</button><button id=incop2 class=buttons003 onclick=qinc()>Million Dollar Arm</button><button id=corop class=buttons003 onclick=qcor()>Field of Dreams</button><button id=incop4 class=buttons003 onclick=qinc()>The Babe</button><br/>",
},
{
"cat":"Sports",
"ques":"Which baseball player was a hypnotized assassin in the Naked Gun?",
"answ":"REGGIE JACKSON",
"answ2":"Reggie Jackson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jay Johnstone</button><button id=incop2 class=buttons003 onclick=qinc()>Burt Hooton</button><button id=incop3 class=buttons003 onclick=qinc()>Graig Nettles</button><button id=corop class=buttons003 onclick=qcor()>Reggie Jackson</button><br/>",
},
{
"cat":"Sports",
"ques":"What activity is the focus of the film Iron Monkey?",
"answ":"MARTIAL ARTS",
"answ2":"Martial arts.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Competitive cooking</button><button id=incop2 class=buttons003 onclick=qinc()>Marathan running</button><button id=incop3 class=buttons003 onclick=qinc()>Sculpting</button><button id=corop class=buttons003 onclick=qcor()>Martial arts</button><br/>",
},
{
"cat":"Sports",
"ques":"In Days of Thunder what soda was Cole Trickle's car sponsored by in the final race at Daytona?",
"answ":"MELLO YELLO",
"answ2":"Mello Yello.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bubble Up</button><button id=corop class=buttons003 onclick=qcor()>Mello Yello</button><button id=incop3 class=buttons003 onclick=qinc()>Mountain Dew</button><button id=incop4 class=buttons003 onclick=qinc()>Fanta</button><br/>",
},
{
"cat":"Sports",
"ques":"Who directed Friday Night Lights?",
"answ":"PETER BERG",
"answ2":"Peter Berg.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Lee Hancock</button><button id=corop class=buttons003 onclick=qcor()>Peter Berg</button><button id=incop3 class=buttons003 onclick=qinc()>John Gatins</button><button id=incop4 class=buttons003 onclick=qinc()>Thomas Carter</button><br/>",
},
{
"cat":"Sports",
"ques":"What do they call the road where the final rollerblade race takes place at the end of the film Airborne?",
"answ":"DEVIL'S BACKBONE",
"answ3":"DEVILS BACKBONE",
"answ2":"Devil's Backbone.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Devil's Reach</button><button id=incop2 class=buttons003 onclick=qinc()>Devil's Runway</button><button id=incop3 class=buttons003 onclick=qinc()>Devil's Highway</button><button id=corop class=buttons003 onclick=qcor()>Devil's Backbone</button><br/>",
},
{
"cat":"Sports",
"ques":"Which baseball film ends with a spectacular home run that shatters the lights?",
"answ":"THE NATURAL",
"answ2":"The Natural.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Natural</button><button id=incop2 class=buttons003 onclick=qinc()>Major League</button><button id=incop3 class=buttons003 onclick=qinc()>Cobb</button><button id=incop4 class=buttons003 onclick=qinc()>The Rookie</button><br/>",
},
{
"cat":"Sports",
"ques":"Which comedy stars Rip Torn as a coach who throws wrenches at his players?",
"answ":"DODGEBALL",
"answ3":"DODGEBALL A TRUE UNDERDOG STORY",
"answ2":"DodgeBall: A True Underdog Story.",
"option":"<button id=corop class=buttons003 onclick=qcor()>DodgeBall</button><button id=incop2 class=buttons003 onclick=qinc()>Blades of Glory</button><button id=incop3 class=buttons003 onclick=qinc()>Semi-Pro</button><button id=incop4 class=buttons003 onclick=qinc()>The Game Plan</button><br/>",
},
{
"cat":"Sports",
"ques":"Seabiscuit's match of the century pits which horse against Seabiscuit?",
"answ":"WAR ADMIRAL",
"answ2":"War Admiral.",
"option":"<button id=corop class=buttons003 onclick=qcor()>War Admiral</button><button id=incop2 class=buttons003 onclick=qinc()>Secretariat</button><button id=incop3 class=buttons003 onclick=qinc()>Whirlaway</button><button id=incop4 class=buttons003 onclick=qinc()>Citation</button><br/>",
},
{
"cat":"Sports",
"ques":"What profession is Dennis Quaid's character in before he tries out for Major League Baseball in The Rookie?",
"answ":"HIGH SCHOOL TEACHER",
"answ3":"TEACHER",
"answ2":"High school teacher.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Auto mechanic</button><button id=incop2 class=buttons003 onclick=qinc()>Carpenter</button><button id=incop3 class=buttons003 onclick=qinc()>Janitor</button><button id=corop class=buttons003 onclick=qcor()>High school teacher</button><br/>",
},
{
"cat":"Sports",
"ques":"What sports film sees Kevin Costner play a character named Roy McAvoy?",
"answ":"TIN CUP",
"answ2":"Tin Cup.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Field of Dreams</button><button id=incop2 class=buttons003 onclick=qinc()>Bull Durham</button><button id=incop3 class=buttons003 onclick=qinc()>Draft Day</button><button id=corop class=buttons003 onclick=qcor()>Tin Cup</button><br/>",
},
{
"cat":"Sports",
"ques":"Who directed the classic sport films Bull Durham and White Men Can't Jump?",
"answ":"RON SHELTON",
"answ2":"Ron Shelton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Phil Alden Robinson</button><button id=incop2 class=buttons003 onclick=qinc()>Andrew Davis</button><button id=incop3 class=buttons003 onclick=qinc()>Thomas Carter</button><button id=corop class=buttons003 onclick=qcor()>Ron Shelton</button><br/>",
},
{
"cat":"Sports",
"ques":"Two NBA all-stars starred in Blue Chips, Penny Hardaway and ____.",
"answ":"SHAQUILLE O'NEAL",
"answ3":"SHAQ",
"answ2":"Shaquille O'Neal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Magic Johnson</button><button id=incop2 class=buttons003 onclick=qinc()>Kareem Abdul-Jabbar</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Jordan</button><button id=corop class=buttons003 onclick=qcor()>Shaquille O'Neal</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the name of the quiet sharpshooting high school star on the basketball team in Hoosiers?",
"answ":"JIMMY CHITWOOD",
"answ2":"Jimmy Chitwood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Johnny Summers</button><button id=incop2 class=buttons003 onclick=qinc()>James Walker</button><button id=incop3 class=buttons003 onclick=qinc()>Ollie Fleener</button><button id=corop class=buttons003 onclick=qcor()>Jimmy Chitwood</button><br/>",
},
{
"cat":"Sports",
"ques":"In Rookie of the Year, Henry Rowengartner is a fan of which Major League Baseball team?",
"answ":"CHICAGO CUBS",
"answ2":"Chicago Cubs.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>San Francisco Giants</button><button id=incop2 class=buttons003 onclick=qinc()>Los Angeles Dodgers</button><button id=incop3 class=buttons003 onclick=qinc()>New York Yankees</button><button id=corop class=buttons003 onclick=qcor()>Chicago Cubs</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League, what is the name of the coach of the Indians?",
"answ":"LOU BROWN",
"answ2":"Lou Brown.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jake Taylor</button><button id=incop2 class=buttons003 onclick=qinc()>Jeremy Keltner</button><button id=incop3 class=buttons003 onclick=qinc()>Pedro Cerrano</button><button id=corop class=buttons003 onclick=qcor()>Lou Brown</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played Shoeless Joe Jackson in Field of Dreams?",
"answ":"RAY LIOTTA",
"answ2":"Ray Liotta.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=corop class=buttons003 onclick=qcor()>Ray Liotta</button><button id=incop3 class=buttons003 onclick=qinc()>Christian Bale</button><button id=incop4 class=buttons003 onclick=qinc()>John Travolta</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League, where does Cleveland Indians owner Rachel Phelps want to move the team?",
"answ":"MIAMI",
"answ2":"Miami.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Los Angeles</button><button id=incop2 class=buttons003 onclick=qinc()>New York</button><button id=incop3 class=buttons003 onclick=qinc()>San Francisco</button><button id=corop class=buttons003 onclick=qcor()>Miami</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays the teacher that Gene Hackman eventually becomes close with in Hoosiers?",
"answ":"BARBARA HERSHEY",
"answ3":"BARBARA HERSEY",
"answ2":"Barbara Hershey.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Barbara Hershey</button><button id=incop2 class=buttons003 onclick=qinc()>Karen Allen</button><button id=incop3 class=buttons003 onclick=qinc()>Sigourney Weaver</button><button id=incop4 class=buttons003 onclick=qinc()>Dee Wallace</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays the graduate student D-Bob that befriends Rudy in 1993's Rudy?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jon Favreau</button><button id=incop2 class=buttons003 onclick=qinc()>Vince Vaughn</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Downey Jr.</button><button id=incop4 class=buttons003 onclick=qinc()>Jeremy Piven</button><br/>",
},
{
"cat":"Sports",
"ques":"At the end of Moneyball, Brad Pitt turns down the lucrative offer to become the general manager for what Major League team?",
"answ":"BOSTON RED SOX",
"answ3":"RED SOX",
"answ2":"Boston Red Sox.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Boston Red Sox</button><button id=incop2 class=buttons003 onclick=qinc()>Minnesota Twins</button><button id=incop3 class=buttons003 onclick=qinc()>Los Angeles Dodgers</button><button id=incop4 class=buttons003 onclick=qinc()>New York Yankees</button><br/>",
},
{
"cat":"Sports",
"ques":"What film sees Kenny Rogers as a race car driver who takes in orphan children to be his pit crew?",
"answ":"SIX PACK",
"answ2":"Six Pack.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Grand Prix</button><button id=corop class=buttons003 onclick=qcor()>Six Pack</button><button id=incop3 class=buttons003 onclick=qinc()>Speed Racer</button><button id=incop4 class=buttons003 onclick=qinc()>Talladega Nights: The Ballad of Ricky Bobby</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played scout Ernie Capadino in A League of Their Own?",
"answ":"JON LOVITZ",
"answ3":"JON LOVITS",
"answ2":"Jon Lovitz.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hanks</button><button id=corop class=buttons003 onclick=qcor()>Jon Lovitz</button><button id=incop3 class=buttons003 onclick=qinc()>John Cusack</button><button id=incop4 class=buttons003 onclick=qinc()>Joe Pesci</button><br/>",
},
{
"cat":"Sports",
"ques":"In the movie Eddie, Whoopi Goldberg is a fan who wins a contest to become the coach of what NBA team?",
"answ":"NEW YORK KNICKS",
"answ3":"THE KNICKS",
"answ2":"New York Knicks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago Bulls</button><button id=corop class=buttons003 onclick=qcor()>New York Knicks</button><button id=incop3 class=buttons003 onclick=qinc()>Toronto Raptors</button><button id=incop4 class=buttons003 onclick=qinc()>Cleveland Cavaliers</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the name of the sports comedy about a college football team starring Scott Bakula, Sinbad and Jason Bateman?",
"answ":"NECESSARY ROUGHNESS",
"answ2":"Necessary Roughness.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>North Dallas 40</button><button id=corop class=buttons003 onclick=qcor()>Necessary Roughness</button><button id=incop3 class=buttons003 onclick=qinc()>Friday Night Fights</button><button id=incop4 class=buttons003 onclick=qinc()>The Benchwarmers</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played assistant coach Red Dawson in 2006's We Are Marshall?",
"answ":"MATTHEW FOX",
"answ2":"Matthew Fox.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anthony Mackie</button><button id=corop class=buttons003 onclick=qcor()>Matthew Fox</button><button id=incop3 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop4 class=buttons003 onclick=qinc()>Ian McShane</button><br/>",
},
{
"cat":"Sports",
"ques":"What high school subject did Joel Edgerton's character teach in 2011's Warrior?",
"answ":"PHYSICS",
"answ2":"Physics.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Physics</button><button id=incop2 class=buttons003 onclick=qinc()>Chemistry</button><button id=incop3 class=buttons003 onclick=qinc()>Economics</button><button id=incop4 class=buttons003 onclick=qinc()>Calculus</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League, what was Rachel Phelp's profession prior to inheriting ownership of the Cleveland Indians?",
"answ":"SHOWGIRL",
"answ2":"Showgirl.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Teacher</button><button id=incop2 class=buttons003 onclick=qinc()>Escort</button><button id=corop class=buttons003 onclick=qcor()>Showgirl</button><button id=incop4 class=buttons003 onclick=qinc()>Bartender</button><br/>",
},
{
"cat":"Sports",
"ques":"What 'Talladega Nights' actor also starred in 1990's Days of Thunder?",
"answ":"JOHN C REILLY",
"answ2":"John C. Reilly.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Will Ferrell</button><button id=incop2 class=buttons003 onclick=qinc()>Sacha Baron Cohen</button><button id=corop class=buttons003 onclick=qcor()>John C. Reilly</button><button id=incop4 class=buttons003 onclick=qinc()>Gary Cole</button><br/>",
},
{
"cat":"Sports",
"ques":"Jackie Gleason played Paul Newman's rival in which 1960's film?",
"answ":"THE HUSTLER",
"answ2":"The Hustler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Requiem for a Heavyweight</button><button id=incop2 class=buttons003 onclick=qinc()>Skidoo</button><button id=corop class=buttons003 onclick=qcor()>The Hustler</button><button id=incop4 class=buttons003 onclick=qinc()>Grand Prix</button><br/>",
},
{
"cat":"Sports",
"ques":"What major golf tournament is the site of the climax for Tin Cup?",
"answ":"US OPEN",
"answ3":"THE US OPEN",
"answ2":"U.S. Open.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Masters</button><button id=incop2 class=buttons003 onclick=qinc()>British Open</button><button id=corop class=buttons003 onclick=qcor()>U.S. Open</button><button id=incop4 class=buttons003 onclick=qinc()>PGA Championship</button><br/>",
},
{
"cat":"Sports",
"ques":"North Dallas Forty stars what actor as pro wide receiver Phil Elliot?",
"answ":"NICK NOLTE",
"answ2":"Nick Nolte.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paul Newman</button><button id=corop class=buttons003 onclick=qcor()>Nick Nolte</button><button id=incop3 class=buttons003 onclick=qinc()>Warren Beatty</button><button id=incop4 class=buttons003 onclick=qinc()>Marlon Brando</button><br/>",
},
{
"cat":"Sports",
"ques":"What sport is the focus of the film Blades of Glory?",
"answ":"FIGURE SKATING",
"answ2":"Figure Skating.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ice hockey</button><button id=corop class=buttons003 onclick=qcor()>Figure skating</button><button id=incop3 class=buttons003 onclick=qinc()>Curling</button><button id=incop4 class=buttons003 onclick=qinc()>Speed skating</button><br/>",
},
{
"cat":"Sports",
"ques":"In Rocky II, what product does Rocky promote for his first TV commercial?",
"answ":"AFTERSHAVE",
"answ3":"BEAST AFTERSHAVE",
"answ2":"Aftershave.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Energy drink</button><button id=corop class=buttons003 onclick=qcor()>Aftershave</button><button id=incop3 class=buttons003 onclick=qinc()>Liquor</button><button id=incop4 class=buttons003 onclick=qinc()>Candybar</button><br/>",
},
{
"cat":"Sports",
"ques":"Which boxing match is spotlighted in the 1996 documentary When We Were Kings?",
"answ":"FOREMAN VS ALI",
"answ3":"RUMBLE IN THE JUNGLE",
"answ2":"Rumble in the Jungle (Foreman vs Ali).",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Thrilla in Manila</button><button id=corop class=buttons003 onclick=qcor()>Rumble in the Jungle</button><button id=incop3 class=buttons003 onclick=qinc()>Drama in Bahama</button><button id=incop4 class=buttons003 onclick=qinc()>Fight of the Century</button><br/>",
},
{
"cat":"Sports",
"ques":"At the climactic bout in Rocky Balboa, which real-life boxer taunts the champ at ringside?",
"answ":"MIKE TYSON",
"answ2":"Mike Tyson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jesse Ferguson</button><button id=corop class=buttons003 onclick=qcor()>Mike Tyson</button><button id=incop3 class=buttons003 onclick=qinc()>Marvis Frazier</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Spinks</button><br/>",
},
{
"cat":"Sports",
"ques":"In Invictus, which team does South Africa beat in the cup final?",
"answ":"NEW ZEALAND",
"answ2":"New Zealand.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>England</button><button id=incop2 class=buttons003 onclick=qinc()>France</button><button id=corop class=buttons003 onclick=qcor()>New Zealand</button><button id=incop4 class=buttons003 onclick=qinc()>Australia</button><br/>",
},
{
"cat":"Sports",
"ques":"The 1995 family film The Big Green centers around what sport?",
"answ":"SOCCER",
"answ2":"Soccer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Football</button><button id=corop class=buttons003 onclick=qcor()>Soccer</button><button id=incop3 class=buttons003 onclick=qinc()>Field Hockey</button><button id=incop4 class=buttons003 onclick=qinc()>Baseball</button><br/>",
},
{
"cat":"Sports",
"ques":"In Days of Thunder, what is the name of Cole Trickle's teammate/rival played by Cary Elwes?",
"answ":"RUSS",
"answ3":"RUSS WHEELER",
"answ2":"Russ Wheeler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rick Wilson</button><button id=incop2 class=buttons003 onclick=qinc()>Randy Warden</button><button id=corop class=buttons003 onclick=qcor()>Russ Wheeler</button><button id=incop4 class=buttons003 onclick=qinc()>Rowdy Burns</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the subject of director Stacy Peralta's documentary Riding Giants?",
"answ":"SURFING",
"answ2":"Surfing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Auto racing</button><button id=incop2 class=buttons003 onclick=qinc()>Horse racing</button><button id=corop class=buttons003 onclick=qcor()>Surfing</button><button id=incop4 class=buttons003 onclick=qinc()>Sailing</button><br/>",
},
{
"cat":"Sports",
"ques":"What was the nickname given to the quarterback who moved in from California in Remember the Titans?",
"answ":"SUNSHINE",
"answ2":"Sunshine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rev</button><button id=incop2 class=buttons003 onclick=qinc()>Wildcat</button><button id=incop3 class=buttons003 onclick=qinc()>Mox</button><button id=corop class=buttons003 onclick=qcor()>Sunshine</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played Reggie Dunlop, the coach of the Charlestown Chiefs in the hockey flick Slap Shot?",
"answ":"PAUL NEWMAN",
"answ2":"Paul Newman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Robert Redford</button><button id=incop2 class=buttons003 onclick=qinc()>George Kennedy</button><button id=incop3 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=corop class=buttons003 onclick=qcor()>Paul Newman</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played the AFFA Football Commissioner in the sports drama Any Given Sunday?",
"answ":"CHARLTON HESTON",
"answ2":"Charlton Heston.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=corop class=buttons003 onclick=qcor()>Charlton Heston</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Duvall</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Harris</button><br/>",
},
{
"cat":"Sports",
"ques":"What country did Eddie Edwards compete for in the Winter Olympics in Eddie the Eagle?",
"answ":"GREAT BRITAIN",
"answ3":"UNITED KINGDOM",
"answ2":"Great Britain.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Canada</button><button id=corop class=buttons003 onclick=qcor()>Great Britain</button><button id=incop3 class=buttons003 onclick=qinc()>France</button><button id=incop4 class=buttons003 onclick=qinc()>Germany</button><br/>",
},
{
"cat":"Sports",
"ques":"In the movie Dodgeball, the championship match was broadcast on what fictional TV network?",
"answ":"ESPN8 THE OCHO",
"answ3":"THE OCHO",
"answ2":"ESPN8: The Ocho.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>ESPN9: The Dodger</button><button id=corop class=buttons003 onclick=qcor()>ESPN8: The Ocho</button><button id=incop3 class=buttons003 onclick=qinc()>ESPN6: El Loco</button><button id=incop4 class=buttons003 onclick=qinc()>ESPN5: The OG</button><br/>",
},
{
"cat":"Sports",
"ques":"Who directed 2010's The Fighter?",
"answ":"DAVID O RUSSELL",
"answ2":"David O. Russell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>David O. Russell</button><button id=incop2 class=buttons003 onclick=qinc()>Gavin O'Connor</button><button id=incop3 class=buttons003 onclick=qinc()>Darren Aronofsky</button><button id=incop4 class=buttons003 onclick=qinc()>Ryan Coogler</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays Brooklyn Dodgers team execute Branch Rickey in 42?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Harrison Ford</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop3 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Douglas</button><br/>",
},
{
"cat":"Sports",
"ques":"In 2004's Miracle, which European country did Team USA compete against in the Oslo exhibition game?",
"answ":"NORWAY",
"answ2":"Norway.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Norway</button><button id=incop2 class=buttons003 onclick=qinc()>Denmark</button><button id=incop3 class=buttons003 onclick=qinc()>Finland</button><button id=incop4 class=buttons003 onclick=qinc()>Sweden</button><br/>",
},
{
"cat":"Sports",
"ques":"How many rounds did the final fight between Rocky and Clubber Lang last in Rocky 3?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played the coach in Ladybugs?",
"answ":"RODNEY DANGERFIELD",
"answ2":"Rodney Dangerfield.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rodney Dangerfield</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop3 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=incop4 class=buttons003 onclick=qinc()>Dustin Hoffman</button><br/>",
},
{
"cat":"Sports",
"ques":"What classic film star made his final performance in Field of Dreams as Archibald 'Moonlight' Graham?",
"answ":"BURT LANCASTER",
"answ2":"Burt Lancaster.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Burt Lancaster</button><button id=incop2 class=buttons003 onclick=qinc()>James Stewart</button><button id=incop3 class=buttons003 onclick=qinc()>Kirk Douglas</button><button id=incop4 class=buttons003 onclick=qinc()>Tony Curtis</button><br/>",
},
{
"cat":"Sports",
"ques":"What film follows the perfect game performance of an aging baseball star in what could be his final professional game?",
"answ":"FOR LOVE OF THE GAME",
"answ2":"For Love of the Game.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Field of Dreams</button><button id=corop class=buttons003 onclick=qcor()>For Love of the Game</button><button id=incop3 class=buttons003 onclick=qinc()>Bull Durham</button><button id=incop4 class=buttons003 onclick=qinc()>The Final Season</button><br/>",
},
{
"cat":"Sports",
"ques":"Against which team did Notre Dame's Daniel 'Rudy' Ruettiger get a sack against in Rudy?",
"answ":"GEORGIA TECH",
"answ2":"Georgia Tech.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Army</button><button id=incop2 class=buttons003 onclick=qinc()>Pitt</button><button id=incop3 class=buttons003 onclick=qinc()>Miami</button><button id=corop class=buttons003 onclick=qcor()>Georgia Tech</button><br/>",
},
{
"cat":"Sports",
"ques":"In Rookie of the Year, what team were the Chicago Cubs playing against in the final game of the regular season?",
"answ":"NEW YORK METS",
"answ2":"New York Mets.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Minnesota Twins</button><button id=incop2 class=buttons003 onclick=qinc()>Pittsburgh Pirates</button><button id=incop3 class=buttons003 onclick=qinc()>Cincinnati Reds</button><button id=corop class=buttons003 onclick=qcor()>New York Mets</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays Charles S. Howard, the owner of Seabiscuit in Seabiscuit?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jeff Bridges</button><button id=incop2 class=buttons003 onclick=qinc()>Chris Cooper</button><button id=incop3 class=buttons003 onclick=qinc()>Tobey Maguire</button><button id=incop4 class=buttons003 onclick=qinc()>Tom Hanks</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League II, the ALCS puts the Cleveland Indians against which American League Central team?",
"answ":"CHICAGO WHITE SOX",
"answ2":"Chicago White Sox.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Chicago White Sox</button><button id=incop2 class=buttons003 onclick=qinc()>Detroit Tigers</button><button id=incop3 class=buttons003 onclick=qinc()>Kansas City Royals</button><button id=incop4 class=buttons003 onclick=qinc()>Minnesota Twins</button><br/>",
},
{
"cat":"Sports",
"ques":"Who directed 2015's Southpaw?",
"answ":"ANTOINE FUQUA",
"answ3":"ANTON FUQUA",
"answ2":"Antoine Fuqua.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Antoine Fuqua</button><button id=incop2 class=buttons003 onclick=qinc()>Ryan Coogler</button><button id=incop3 class=buttons003 onclick=qinc()>Ron Howard</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Landesman</button><br/>",
},
{
"cat":"Sports",
"ques":"What was the name of the prison football team in 1974's and 2005's The Longest Yard?",
"answ":"MEAN MACHINE",
"answ2":"Mean Machine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wrecking Crew</button><button id=incop2 class=buttons003 onclick=qinc()>Bar Breakers</button><button id=corop class=buttons003 onclick=qcor()>Mean Machine</button><button id=incop4 class=buttons003 onclick=qinc()>Gridiron Gang</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played Will Ferrell & John Heder's ice-skating coach in Blades of Glory?",
"answ":"CRAIG T NELSON",
"answ2":"Craig T. Nelson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>William Fichtner</button><button id=incop2 class=buttons003 onclick=qinc()>Nick Swardson</button><button id=corop class=buttons003 onclick=qcor()>Craig T. Nelson</button><button id=incop4 class=buttons003 onclick=qinc()>William H. Macy</button><br/>",
},
{
"cat":"Sports",
"ques":"What's the name of the Miami Dolphins mascot stolen in Ace Ventura Pet Detective?",
"answ":"SNOWFLAKE",
"answ3":"SNOW FLAKE",
"answ2":"Snowflake.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Willy</button><button id=incop2 class=buttons003 onclick=qinc()>Finkle</button><button id=corop class=buttons003 onclick=qcor()>Snowflake</button><button id=incop4 class=buttons003 onclick=qinc()>Flipper</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays retired baseball player Stan Ross who must return to the big league in Mr. 3000?",
"answ":"BERNIE MAC",
"answ2":"Bernie Mac.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Martin Lawrence</button><button id=incop2 class=buttons003 onclick=qinc()>Wesley Snipes</button><button id=corop class=buttons003 onclick=qcor()>Bernie Mac</button><button id=incop4 class=buttons003 onclick=qinc()>Michael B. Jordan</button><br/>",
},
{
"cat":"Sports",
"ques":"The basketball drama Hoosiers was released in what year?",
"answ":"1986",
"answ2":"1986.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1984</button><button id=incop2 class=buttons003 onclick=qinc()>1985</button><button id=corop class=buttons003 onclick=qcor()>1986</button><button id=incop4 class=buttons003 onclick=qinc()>1987</button><br/>",
},
{
"cat":"Sports",
"ques":"What famous actor played cornerback Alan Bosley in Remember the Titans?",
"answ":"RYAN GOSLING",
"answ2":"Ryan Gosling.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wood Harris</button><button id=incop2 class=buttons003 onclick=qinc()>Justin Timberlake</button><button id=corop class=buttons003 onclick=qcor()>Ryan Gosling</button><button id=incop4 class=buttons003 onclick=qinc()>Topher Grace</button><br/>",
},
{
"cat":"Sports",
"ques":"Lil Bow Wow plays a 14 year old orphan who becomes a NBA superstar after trying on unique sneakers in what 2002 film?",
"answ":"LIKE MIKE",
"answ2":"Like Mike.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Space Jam</button><button id=incop2 class=buttons003 onclick=qinc()>Celtic Pride</button><button id=corop class=buttons003 onclick=qcor()>Like Mike</button><button id=incop4 class=buttons003 onclick=qinc()>Thunderstruck</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays the basketball coach Don Haskins in the film Glory Road?",
"answ":"JOSH LUCAS",
"answ2":"Josh Lucas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop2 class=buttons003 onclick=qinc()>Jon Voight</button><button id=corop class=buttons003 onclick=qcor()>Josh Lucas</button><button id=incop4 class=buttons003 onclick=qinc()>Rip Torn</button><br/>",
},
{
"cat":"Sports",
"ques":"Macushla, which is Gaelic for 'my darling' or 'my blood' was embroidered on a boxin robe of the main character in what film?",
"answ":"MILLION DOLLAR BABY",
"answ2":"Million Dollar Baby.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Creed</button><button id=incop2 class=buttons003 onclick=qinc()>Rocky III</button><button id=corop class=buttons003 onclick=qcor()>Million Dollar Baby</button><button id=incop4 class=buttons003 onclick=qinc()>Southpaw</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played washed up golf pro Roy McAvoy in Tin Cup?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cuba Gooding Jr.</button><button id=incop2 class=buttons003 onclick=qinc()>Don Johnson</button><button id=corop class=buttons003 onclick=qcor()>Kevin Costner</button><button id=incop4 class=buttons003 onclick=qinc()>Jon Hamm</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League, what is the result of the at-bat when Jake Taylor mimics Babe Ruth's famous 'called shot'?",
"answ":"BUNT",
"answ3":"A BUNT",
"answ2":"Bunt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Home Run</button><button id=incop2 class=buttons003 onclick=qinc()>Strike Out</button><button id=corop class=buttons003 onclick=qcor()>Bunt</button><button id=incop4 class=buttons003 onclick=qinc()>Foul ball</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays head football coach Harold Jones in the 2003 sports drama Radio?",
"answ":"ED HARRIS",
"answ2":"Ed Harris.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Cooper</button><button id=incop2 class=buttons003 onclick=qinc()>Ed O'Neill</button><button id=incop3 class=buttons003 onclick=qinc()>John Goodman</button><button id=corop class=buttons003 onclick=qcor()>Ed Harris</button><br/>",
},
{
"cat":"Sports",
"ques":"Keanu Reeves played two quarterbacks in two unrelated movies, that went to the same college. What university did he play for?",
"answ":"OHIO STATE",
"answ3":"OHIO STATE UNIVERSITY",
"answ2":"Ohio State.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miami</button><button id=incop2 class=buttons003 onclick=qinc()>Penn State</button><button id=incop3 class=buttons003 onclick=qinc()>Virginia Tech</button><button id=corop class=buttons003 onclick=qcor()>Ohio State</button><br/>",
},
{
"cat":"Sports",
"ques":"What 2001 baseball film stars Freddie Prinze Jr. and Jessica Biel?",
"answ":"SUMMER CATCH",
"answ2":"Summer Catch.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Everyone's Hero</button><button id=incop2 class=buttons003 onclick=qinc()>Hustle</button><button id=incop3 class=buttons003 onclick=qinc()>The Outfield</button><button id=corop class=buttons003 onclick=qcor()>Summer Catch</button><br/>",
},
{
"cat":"Sports",
"ques":"In the pro shop in Caddyshack, Rodney Dangerfield says: 'You buy a hat like this, I'll bet you get a free _____'?",
"answ":"BOWL OF SOUP",
"answ2":"Bowl of soup.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Box of tees</button><button id=corop class=buttons003 onclick=qcor()>Bowl of soup</button><button id=incop3 class=buttons003 onclick=qinc()>Golf lesson</button><button id=incop4 class=buttons003 onclick=qinc()>Club Sandwich</button><br/>",
},
{
"cat":"Sports",
"ques":"In Hoosiers, who plays Shooter, the assistant coach struggling with alcoholism?",
"answ":"DENNIS HOPPER",
"answ2":"Dennis Hopper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=corop class=buttons003 onclick=qcor()>Dennis Hopper</button><button id=incop3 class=buttons003 onclick=qinc()>Kyle MacLachlan</button><button id=incop4 class=buttons003 onclick=qinc()>Eric Roberts</button><br/>",
},
{
"cat":"Sports",
"ques":"Before playing Foggy Nelson in Marvel's Daredevil, Elden Henson player enforcer Fulton Reed in what hockey film?",
"answ":"THE MIGHTY DUCKS",
"answ3":"MIGHTY DUCKS",
"answ2":"The Mighty Ducks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mystery, Alaska</button><button id=incop2 class=buttons003 onclick=qinc()>Miracle</button><button id=incop3 class=buttons003 onclick=qinc()>Goon</button><button id=corop class=buttons003 onclick=qcor()>The Mighty Ducks</button><br/>",
},
{
"cat":"Sports",
"ques":"In 2004's Friday Night Lights, what musician plays an abusive and alcoholic father who lives in the glory days of his past football career?",
"answ":"TIM MCGRAW",
"answ2":"Tim McGraw.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Elton John</button><button id=incop2 class=buttons003 onclick=qinc()>David Bowie</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Bolton</button><button id=corop class=buttons003 onclick=qcor()>Tim McGraw</button><br/>",
},
{
"cat":"Sports",
"ques":"What WWE legend portrayed Patricia Clarkson's oldest son in 2010's sports drama Legendary?",
"answ":"JOHN CENA",
"answ2":"John Cena.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Big Show</button><button id=incop2 class=buttons003 onclick=qinc()>Dwayne Johnson</button><button id=incop3 class=buttons003 onclick=qinc()>Chris Jericho</button><button id=corop class=buttons003 onclick=qcor()>John Cena</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the name of Ivan Drago's son in Creed II?",
"answ":"VIKTOR",
"answ3":"VICTOR",
"answ2":"Viktor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anatoly</button><button id=incop2 class=buttons003 onclick=qinc()>Vladimir</button><button id=corop class=buttons003 onclick=qcor()>Viktor</button><button id=incop4 class=buttons003 onclick=qinc()>Boris</button><br/>",
},
{
"cat":"Sports",
"ques":"What actor portrayed Ricky Bobby's father in Talladega Nights: The Ballad of Ricky Bobby?",
"answ":"GARY COLE",
"answ2":"Gary Cole.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Arkin</button><button id=incop2 class=buttons003 onclick=qinc()>Dustin Hoffman</button><button id=corop class=buttons003 onclick=qcor()>Gary Cole</button><button id=incop4 class=buttons003 onclick=qinc()>Rip Torn</button><br/>",
},
{
"cat":"Sports",
"ques":"What sports film stars Omar Epps, Sanaa Lathan, Dennis Haysbert and Alfre Woodard?",
"answ":"LOVE AND BASKETBALL",
"answ2":"Love & Basketball.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Coach Carter</button><button id=incop2 class=buttons003 onclick=qinc()>Streetballers</button><button id=corop class=buttons003 onclick=qcor()>Love & Basketball</button><button id=incop4 class=buttons003 onclick=qinc()>Friday Night Lights</button><br/>",
},
{
"cat":"Sports",
"ques":"What National League Central MLB team did Bernie Mac play for in Mr. 3000?",
"answ":"MILWAUKEE BREWERS",
"answ2":"Milwaukee Brewers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Milwaukee Brewers</button><button id=incop2 class=buttons003 onclick=qinc()>Pittsburgh Pirates</button><button id=incop3 class=buttons003 onclick=qinc()>St. Louis Cardinals</button><button id=incop4 class=buttons003 onclick=qinc()>Chicago Cubs</button><br/>",
},
{
"cat":"Sports",
"ques":"What real-life ice skating star has a cameo appearance in Ice Princess?",
"answ":"MICHELLE KWAN",
"answ2":"Michelle Kwan.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michelle Kwan</button><button id=incop2 class=buttons003 onclick=qinc()>Nancy Kerrigan</button><button id=incop3 class=buttons003 onclick=qinc()>Sarah Hughes</button><button id=incop4 class=buttons003 onclick=qinc()>Kristi Yamaguchi</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the name of the country club in Caddyshack?",
"answ":"BUSHWOOD",
"answ3":"BUSHWOOD COUNTRY CLUB",
"answ2":"Bushwood.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Bushwood</button><button id=incop2 class=buttons003 onclick=qinc()>Indian Hill</button><button id=incop3 class=buttons003 onclick=qinc()>Oakmont</button><button id=incop4 class=buttons003 onclick=qinc()>Pitt Meadows</button><br/>",
},
{
"cat":"Sports",
"ques":"Who played the title role in 1979's boxing drama The Champ?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jon Voight</button><button id=incop2 class=buttons003 onclick=qinc()>Sylvester Stallone</button><button id=incop3 class=buttons003 onclick=qinc()>Chuck Norris</button><button id=incop4 class=buttons003 onclick=qinc()>Dustin Hoffman</button><br/>",
},
{
"cat":"Sports",
"ques":"In Major League, Indians radio announcer Harry Doyle is played by what real life baseball broadcaster?",
"answ":"BOB UECKER",
"answ3":"BOB UCKER",
"answ2":"Bob Uecker.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry Caray</button><button id=incop2 class=buttons003 onclick=qinc()>Jack Buck</button><button id=incop3 class=buttons003 onclick=qinc()>Vin Scully</button><button id=corop class=buttons003 onclick=qcor()>Bob Uecker</button><br/>",
},
{
"cat":"Sports",
"ques":"Samuel L. Jackson's Ken Carter coaches what high school sport in Coach Carter?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ice hockey</button><button id=incop2 class=buttons003 onclick=qinc()>American football</button><button id=incop3 class=buttons003 onclick=qinc()>Baseball</button><button id=corop class=buttons003 onclick=qcor()>Basketball</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays Quincy's father, Zeke, in Love & Basketball?",
"answ":"DENNIS HAYSBERT",
"answ3":"DENNIS HAYBERT",
"answ2":"Dennis Haysbert.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dennis Haysbert</button><button id=incop2 class=buttons003 onclick=qinc()>Keith David</button><button id=incop3 class=buttons003 onclick=qinc()>Taye Diggs</button><button id=incop4 class=buttons003 onclick=qinc()>Forest Whitaker</button><br/>",
},
{
"cat":"Sports",
"ques":"What 2001 sports romance stars Freddie Prinze Jr. as an aspiring pitcher in the Cape Cod baseball league?",
"answ":"SUMMER CATCH",
"answ2":"Summer Catch.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Summer Catch</button><button id=incop2 class=buttons003 onclick=qinc()>Angels in the Outfield</button><button id=incop3 class=buttons003 onclick=qinc()>Mickey</button><button id=incop4 class=buttons003 onclick=qinc()>Everyone's Hero</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays Paddy Conlon, the father of Tom Hardy and Joel Edgerton's characters in Warrior?",
"answ":"NICK NOLTE",
"answ2":"Nick Nolte.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nick Nolte</button><button id=incop2 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop3 class=buttons003 onclick=qinc()>Donald Sutherland</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Plummer</button><br/>",
},
{
"cat":"Sports",
"ques":"Who directed A League of Their Own?",
"answ":"PENNY MARSHALL",
"answ2":"Penny Marshall.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Penny Marshall</button><button id=incop2 class=buttons003 onclick=qinc()>David S. Ward</button><button id=incop3 class=buttons003 onclick=qinc()>Stephen Herek</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Reitman</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays veteran player Ross 'The Boss' in the 2011 hockey comedy Goon?",
"answ":"LIEV SCHREIBER",
"answ2":"Liev Schreiber.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Liev Schreiber</button><button id=incop2 class=buttons003 onclick=qinc()>Seann William Scott</button><button id=incop3 class=buttons003 onclick=qinc()>Vinnie Jones</button><button id=incop4 class=buttons003 onclick=qinc()>Chiwetel Ejiofor</button><br/>",
},
{
"cat":"Sports",
"ques":"Meg Ryan plays a promoter of what sport in the film Against The Ropes?",
"answ":"BOXING",
"answ2":"Boxing.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Boxing</button><button id=incop2 class=buttons003 onclick=qinc()>Wrestling</button><button id=incop3 class=buttons003 onclick=qinc()>Mixed Martial Arts</button><button id=incop4 class=buttons003 onclick=qinc()>Kick boxing</button><br/>",
},
{
"cat":"Sports",
"ques":"Which actor stars as the jockey Red Pollard in Seabiscuit?",
"answ":"TOBEY MAGUIRE",
"answ2":"Tobey Maguire.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tobey Maguire</button><button id=incop2 class=buttons003 onclick=qinc()>Ethan Hawke</button><button id=incop3 class=buttons003 onclick=qinc()>Jake Gyllenhaal</button><button id=incop4 class=buttons003 onclick=qinc()>James Franco</button><br/>",
},
{
"cat":"Sports",
"ques":"What is the name of the 2008 film about elite running back Ernie Davis who played football for Syracuse University?",
"answ":"THE EXPRESS",
"answ2":"The Express.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Draft Day</button><button id=corop class=buttons003 onclick=qcor()>The Express</button><button id=incop3 class=buttons003 onclick=qinc()>When the Game Stands Tall</button><button id=incop4 class=buttons003 onclick=qinc()>The Blind Side</button><br/>",
},
{
"cat":"Sports",
"ques":"You'll find the fictional football team of the Washington Sentinels in what 2000 film?",
"answ":"THE REPLACEMENTS",
"answ2":"The Replacements.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Invincible</button><button id=corop class=buttons003 onclick=qcor()>The Replacements</button><button id=incop3 class=buttons003 onclick=qinc()>The Sandlot</button><button id=incop4 class=buttons003 onclick=qinc()>Undisputed</button><br/>",
},
{
"cat":"Sports",
"ques":"What team did Billy Bean manage in 2011's Moneyball?",
"answ":"OAKLAND A'S",
"answ3":"OAKLAND ATHLETICS",
"answ2":"Oakland Athletics/Oakland A's.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tampa Bay Rays</button><button id=corop class=buttons003 onclick=qcor()>Oakland Athletics</button><button id=incop3 class=buttons003 onclick=qinc()>Chicago Cubs‎</button><button id=incop4 class=buttons003 onclick=qinc()>Houston Astros‎</button><br/>",
},
{
"cat":"Sports",
"ques":"In what football drama do actors Lucas Black, Garrett Hedlund and Derek Luke have supporting roles?",
"answ":"FRIDAY NIGHT LIGHTS",
"answ2":"Friday Night Lights.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Blind Side</button><button id=corop class=buttons003 onclick=qcor()>Friday Night Lights</button><button id=incop3 class=buttons003 onclick=qinc()>The Replacements‎</button><button id=incop4 class=buttons003 onclick=qinc()>Invincible‎</button><br/>",
},
{
"cat":"Sports",
"ques":"In Nacho Libre, what is the name of the wrestler Nacho looks up to above all others?",
"answ":"RAMSES",
"answ2":"Ramses.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ramses</button><button id=incop2 class=buttons003 onclick=qinc()>Chevy</button><button id=incop3 class=buttons003 onclick=qinc()>Silencio‎</button><button id=incop4 class=buttons003 onclick=qinc()>Emperor‎</button><br/>",
},
{
"cat":"Sports",
"ques":"You'll find a character that goes by the nickname All the Way Mae in what film?",
"answ":"A LEAGUE OF THEIR OWN",
"answ2":"A League of Their Own.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A League of Their Own</button><button id=incop2 class=buttons003 onclick=qinc()>Moneyball</button><button id=incop3 class=buttons003 onclick=qinc()>The Mighty Ducks</button><button id=incop4 class=buttons003 onclick=qinc()>Jerry Maguire‎</button><br/>",
},
{
"cat":"Sports",
"ques":"You'll find the first female ice skater to complete two triple-axel jumps in competition in which film?",
"answ":"I TONYA",
"answ2":"I Tonya.",
"option":"<button id=corop class=buttons003 onclick=qcor()>I Tonya</button><button id=incop2 class=buttons003 onclick=qinc()>The Cutting Edge</button><button id=incop3 class=buttons003 onclick=qinc()>Ice Princess</button><button id=incop4 class=buttons003 onclick=qinc()>Blades of Glory</button><br/>",
},
{
"cat":"Sports",
"ques":"Who plays Assistant General Manager and Assistant Coach Craig Patrick in 2004's Miracle?",
"answ":"NOAH EMMERICH",
"answ2":"Noah Emmerich.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Noah Emmerich</button><button id=incop2 class=buttons003 onclick=qinc()>Ron Howard</button><button id=incop3 class=buttons003 onclick=qinc()>David Tennant</button><button id=incop4 class=buttons003 onclick=qinc()>Kevin Costner</button><br/>",
},
{
"cat":"Sports",
"ques":"Which actress plays supermodel Suzy Miller, that ends up marrying and divorcing James Hunt, in the film Rush?",
"answ":"OLIVIA WILDE",
"answ2":"Olivia Wilde.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Olivia Wilde</button><button id=incop2 class=buttons003 onclick=qinc()>Jennifer Garner</button><button id=incop3 class=buttons003 onclick=qinc()>Megan Fox</button><button id=incop4 class=buttons003 onclick=qinc()>Margot Robbie</button><br/>",
},
{
"cat":"Sports",
"ques":"In Fighting with My Family, Zak and Saraya Knight meet what famous wrestler before a Smackdown event that gives them helpful advice?",
"answ":"DWAYNE JOHNSON",
"answ3":"THE ROCK",
"answ2":"Dwayne Johnson/The Rock.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dwayne Johnson</button><button id=incop2 class=buttons003 onclick=qinc()>John Cena</button><button id=incop3 class=buttons003 onclick=qinc()>Steve Austin</button><button id=incop4 class=buttons003 onclick=qinc()>Hulk Hogan</button><br/>",
},
];
sports = shuffle(sports);
r2Q30 = shuffle(r2Q30);