var r2Q31 = [
{
"cat":"Sandra Bullock",
"ques":"What country is Sandra Bullock from in The Proposal?",
"answ":"CANADA",
"answ2":"Canada.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>England</button><button id=incop2 class=buttons003 onclick=qinc()>Ireland</button><button id=corop class=buttons003 onclick=qcor()>Canada</button><button id=incop4 class=buttons003 onclick=qinc()>Australia</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In which film do Sandra Bullock and Nicole Kidman play sister witches?",
"answ":"PRACTICAL MAGIC",
"answ2":"Practical Magic.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Witches of Eastwick</button><button id=incop2 class=buttons003 onclick=qinc()>Beautiful Creatures</button><button id=corop class=buttons003 onclick=qcor()>Practical Magic</button><button id=incop4 class=buttons003 onclick=qinc()>The Witches</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"The contestant from which state won the Miss United States pageant in Miss Congeniality?",
"answ":"RHODE ISLAND",
"answ2":"Rhode Island.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kansas</button><button id=incop2 class=buttons003 onclick=qinc()>Montana</button><button id=corop class=buttons003 onclick=qcor()>Rhode Island</button><button id=incop4 class=buttons003 onclick=qinc()>Texas</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what city does the majority of The Heat take place?",
"answ":"BOSTON",
"answ2":"Boston.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Philadelphia</button><button id=incop2 class=buttons003 onclick=qinc()>Miami</button><button id=corop class=buttons003 onclick=qcor()>Boston</button><button id=incop4 class=buttons003 onclick=qinc()>Detroit</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays Sandra Bullock's boyfriend Jasper in the film 28 Days?",
"answ":"DOMINIC WEST",
"answ2":"Dominic West.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kevin Bacon</button><button id=incop2 class=buttons003 onclick=qinc()>James Marsden</button><button id=corop class=buttons003 onclick=qcor()>Dominic West</button><button id=incop4 class=buttons003 onclick=qinc()>Benjamin Bratt</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock stars opposite Liam Neeson and Oliver Platt in what 2000 film?",
"answ":"GUN SHY",
"answ2":"Gun Shy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Forces of Nature</button><button id=incop2 class=buttons003 onclick=qinc()>28 Days</button><button id=corop class=buttons003 onclick=qcor()>Gun Shy</button><button id=incop4 class=buttons003 onclick=qinc()>Miss Congeniality</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Which Oscar winning actress plays Sandra Bullock's sister in the 1998 film Practical Magic?",
"answ":"NICOLE KIDMAN",
"answ2":"Nicole Kidman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Julianne Moore</button><button id=incop2 class=buttons003 onclick=qinc()>Renee Zellweger</button><button id=corop class=buttons003 onclick=qcor()>Nicole Kidman</button><button id=incop4 class=buttons003 onclick=qinc()>Meryl Streep</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock plays the character of Gracie Hart in what 2000 film?",
"answ":"MISS CONGENIALITY",
"answ2":"Miss Congeniality.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Murder by Numbers</button><button id=incop2 class=buttons003 onclick=qinc()>The Lake House</button><button id=corop class=buttons003 onclick=qcor()>Miss Congeniality</button><button id=incop4 class=buttons003 onclick=qinc()>Gun Shy</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock played a computer programmer who had her identity stolen by a rogue government agency in what 1995 film?",
"answ":"THE NET",
"answ2":"The Net.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Demolition Man</button><button id=incop2 class=buttons003 onclick=qinc()>A Time to Kill</button><button id=corop class=buttons003 onclick=qcor()>The Net</button><button id=incop4 class=buttons003 onclick=qinc()>Hackers</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who is Sandra Bullock's co-lead in Forces of Nature?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ben Stiller</button><button id=incop2 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=corop class=buttons003 onclick=qcor()>Ben Affleck</button><button id=incop4 class=buttons003 onclick=qinc()>Keanu Reeves</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What state does Sandra Bullock represent in Miss Congeniality?",
"answ":"NEW JERSEY",
"answ2":"New Jersey.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Texas</button><button id=corop class=buttons003 onclick=qcor()>New Jersey</button><button id=incop3 class=buttons003 onclick=qinc()>Florida</button><button id=incop4 class=buttons003 onclick=qinc()>California</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what film is Bullock's boss played by Hugh Grant?",
"answ":"TWO WEEKS NOTICE",
"answ2":"Two Weeks Notice.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Heat</button><button id=corop class=buttons003 onclick=qcor()>Two Weeks Notice</button><button id=incop3 class=buttons003 onclick=qinc()>The Proposal</button><button id=incop4 class=buttons003 onclick=qinc()>Murder by Numbers</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Which film stars Matt Dillon, Don Cheadle and Sandra Bullock?",
"answ":"CRASH",
"answ2":"Crash.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Crash</button><button id=incop2 class=buttons003 onclick=qinc()>Babel</button><button id=incop3 class=buttons003 onclick=qinc()>Mulholland Drive</button><button id=incop4 class=buttons003 onclick=qinc()>Love Actually</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What must Sandra Bullock do in 28 Days?",
"answ":"SPEND TIME IN REHAB",
"answ3":"GO TO REHAB",
"answ2":"Spend time in rehab.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Graduate college</button><button id=incop2 class=buttons003 onclick=qinc()>Join the army</button><button id=corop class=buttons003 onclick=qcor()>Spend time in rehab</button><button id=incop4 class=buttons003 onclick=qinc()>Get married</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What country music star plays Bullock's husband in The Blind Side?",
"answ":"TIM MCGRAW",
"answ2":"Tim McGraw.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tim McGraw</button><button id=incop2 class=buttons003 onclick=qinc()>Garth Brooks</button><button id=incop3 class=buttons003 onclick=qinc()>Keith Urban</button><button id=incop4 class=buttons003 onclick=qinc()>Brad Paisley</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In which movie does Sandra Bullock play a subway tollbooth operator?",
"answ":"WHILE YOU WERE SLEEPING",
"answ2":"While You Were Sleeping.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miss Congeniality</button><button id=corop class=buttons003 onclick=qcor()>While You Were Sleeping</button><button id=incop3 class=buttons003 onclick=qinc()>The Net</button><button id=incop4 class=buttons003 onclick=qinc()>Infamous</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"The night before Bullock won an Oscar for Best Actress in The Blind Side she won a Razzie for her role in which film?",
"answ":"ALL ABOUT STEVE",
"answ2":"All About Steve.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Premonition</button><button id=incop2 class=buttons003 onclick=qinc()>Infamous</button><button id=incop3 class=buttons003 onclick=qinc()>Miss Congeniality 2</button><button id=corop class=buttons003 onclick=qcor()>All About Steve</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what film does Bullock play Kiefer Sutherland's girlfriend who is abducted by Jeff Bridges?",
"answ":"THE VANISHING",
"answ2":"The Vanishing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>While You Were Sleeping</button><button id=incop2 class=buttons003 onclick=qinc()>The Net</button><button id=incop3 class=buttons003 onclick=qinc()>A Time to Kill</button><button id=corop class=buttons003 onclick=qcor()>The Vanishing</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what film does Bullock play a legal researcher for Matthew McConaughey?",
"answ":"A TIME TO KILL",
"answ2":"A Time to Kill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hope Floats</button><button id=incop2 class=buttons003 onclick=qinc()>Two Weeks Notice</button><button id=incop3 class=buttons003 onclick=qinc()>Two If by Sea</button><button id=corop class=buttons003 onclick=qcor()>A Time to Kill</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra's identity was erased in which movie?",
"answ":"THE NET",
"answ2":"The Net.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Net</button><button id=incop2 class=buttons003 onclick=qinc()>Demolition Man</button><button id=incop3 class=buttons003 onclick=qinc()>Premonition</button><button id=incop4 class=buttons003 onclick=qinc()>A Time to Kill</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who provides the voice of Mission Control in Gravity?",
"answ":"ED HARRIS",
"answ2":"Ed Harris.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hanks</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Bacon</button><button id=incop3 class=buttons003 onclick=qinc()>Gary Sinise</button><button id=corop class=buttons003 onclick=qcor()>Ed Harris</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who stars opposite Sandra Bullock in Forces of Nature?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ben Affleck</button><button id=incop2 class=buttons003 onclick=qinc()>Matt Damon</button><button id=incop3 class=buttons003 onclick=qinc()>Keanu Reeves</button><button id=incop4 class=buttons003 onclick=qinc()>Neil Patrick Harris</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who played scientist Paul, who falls in love with Sandra in Love Potion No.9?",
"answ":"TATE DONOVAN",
"answ2":"Tate Donovan.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tate Donovan</button><button id=incop2 class=buttons003 onclick=qinc()>Rob Lowe</button><button id=incop3 class=buttons003 onclick=qinc()>Hugh Grant</button><button id=incop4 class=buttons003 onclick=qinc()>Ben Affleck</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what film does Sandra Bullock romance Chris O'Donnell during World War I?",
"answ":"IN LOVE AND WAR",
"answ2":"In Love and War.",
"option":"<button id=corop class=buttons003 onclick=qcor()>In Love and War</button><button id=incop2 class=buttons003 onclick=qinc()>Wrestling Ernest Hemingway</button><button id=incop3 class=buttons003 onclick=qinc()>In Good Company</button><button id=incop4 class=buttons003 onclick=qinc()>All Quiet on the Western Front</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what film does Bullock play a homicide detective hunting down Ryan Gosling and Michael Pitt?",
"answ":"MURDER BY NUMBERS",
"answ2":"Murder By Numbers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A Time To Kill</button><button id=corop class=buttons003 onclick=qcor()>Murder By Numbers</button><button id=incop3 class=buttons003 onclick=qinc()>Gun Shy</button><button id=incop4 class=buttons003 onclick=qinc()>Two If By Sea</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Comedian Adam Ray plays the bad guy in what buddy cop movie starring Sandra Bullock?",
"answ":"THE HEAT",
"answ2":"The Heat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miss Congeniality</button><button id=corop class=buttons003 onclick=qcor()>The Heat</button><button id=incop3 class=buttons003 onclick=qinc()>Get Smart</button><button id=incop4 class=buttons003 onclick=qinc()>Murder by Numbers</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays Bullock's father in the Divine Secrets of the Ya-Ya Sisterhood?",
"answ":"JAMES GARNER",
"answ2":"James Garner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=corop class=buttons003 onclick=qcor()>James Garner</button><button id=incop3 class=buttons003 onclick=qinc()>Dustin Hoffman</button><button id=incop4 class=buttons003 onclick=qinc()>Donald Sutherland</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What is Sandra's talent, that she performs during the talent portion of the Miss USA pageant in Miss Congeniality?",
"answ":"PLAYING WINE GLASSES",
"answ3":"PLAYING GLASS HARP",
"answ2":"Playing glass harp.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Juggling</button><button id=corop class=buttons003 onclick=qcor()>Playing glass harp</button><button id=incop3 class=buttons003 onclick=qinc()>Riding unicycle</button><button id=incop4 class=buttons003 onclick=qinc()>Knife throwing</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What is is the profession of Sandra Bullock's character Angela Bennett in 1995's The Net?",
"answ":"SOFTWARE ENGINEER",
"answ3":"COMPUTER PROGRAMMER",
"answ2":"Software engineer/Computer programmer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Teacher</button><button id=incop2 class=buttons003 onclick=qinc()>Lawyer</button><button id=incop3 class=buttons003 onclick=qinc()>Hair stylist</button><button id=corop class=buttons003 onclick=qcor()>Software engineer</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays the villainous John Geiger in Speed 2: Cruise Control?",
"answ":"WILLEM DAFOE",
"answ3":"WILLEM DEFOE",
"answ2":"Willem Dafoe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harvey Keitel</button><button id=incop2 class=buttons003 onclick=qinc()>James Woods</button><button id=incop3 class=buttons003 onclick=qinc()>Ed Harris</button><button id=corop class=buttons003 onclick=qcor()>Willem Dafoe</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who directed The Heat starring Sandra Bullock and Melissa McCarthy?",
"answ":"PAUL FEIG",
"answ3":"PAUL FIEG",
"answ2":"Paul Feig.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ben Falcone</button><button id=incop2 class=buttons003 onclick=qinc()>Greg Berlanti</button><button id=incop3 class=buttons003 onclick=qinc()>Seth Gordon</button><button id=corop class=buttons003 onclick=qcor()>Paul Feig</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock plays a futuristic cop obsessed with 90's culture in what film?",
"answ":"DEMOLITION MAN",
"answ2":"Demolition Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Total Recall</button><button id=incop2 class=buttons003 onclick=qinc()>Minority Report</button><button id=incop3 class=buttons003 onclick=qinc()>Judge Dredd</button><button id=corop class=buttons003 onclick=qcor()>Demolition Man</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What is the first and last name of Sandra Bullock's character in Oceans 8?",
"answ":"DEBBIE OCEAN",
"answ3":"DEBORAH OCEAN",
"answ2":"Debbie Ocean.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Ocean</button><button id=incop2 class=buttons003 onclick=qinc()>Jane Ocean</button><button id=incop3 class=buttons003 onclick=qinc()>Tess Ocean</button><button id=corop class=buttons003 onclick=qcor()>Debbie Ocean</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who directed Sandra Bullock in While You Were Sleeping?",
"answ":"JOHN TURTELTAUB",
"answ2":"John Turteltaub.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joel Schumacher</button><button id=incop2 class=buttons003 onclick=qinc()>Irwin Winkler</button><button id=incop3 class=buttons003 onclick=qinc()>Marco Brambilla</button><button id=corop class=buttons003 onclick=qcor()>John Turteltaub</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who directed Gravity?",
"answ":"ALFONSO CUARON",
"answ2":"Alfonso Cuaron.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sam Mendes</button><button id=incop2 class=buttons003 onclick=qinc()>Alejandro González Iñárritu</button><button id=incop3 class=buttons003 onclick=qinc()>Denis Villeneuve</button><button id=corop class=buttons003 onclick=qcor()>Alfonso Cuaron</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock voiced a character in which 1998 animated film?",
"answ":"THE PRINCE OF EGYPT",
"answ3":"PRINCE OF EGYPT",
"answ2":"The Prince of Egypt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anastasia</button><button id=incop2 class=buttons003 onclick=qinc()>Mulan</button><button id=incop3 class=buttons003 onclick=qinc()>Antz</button><button id=corop class=buttons003 onclick=qcor()>The Prince of Egypt</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"A Time to Kill is based on a novel from what writer?",
"answ":"JOHN GRISHAM",
"answ2":"John Grisham.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dan Brown</button><button id=corop class=buttons003 onclick=qcor()>John Grisham</button><button id=incop3 class=buttons003 onclick=qinc()>Stephen King</button><button id=incop4 class=buttons003 onclick=qinc()>David Baldacci</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who played Sandra Bullock's husband in Crash?",
"answ":"BRENDAN FRASER",
"answ2":"Brendan Fraser.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=corop class=buttons003 onclick=qcor()>Brendan Fraser</button><button id=incop3 class=buttons003 onclick=qinc()>Matt Dillon</button><button id=incop4 class=buttons003 onclick=qinc()>Keanu Reeves</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who played Sandra Bullock's sister in Bird Box?",
"answ":"SARAH PAULSON",
"answ2":"Sarah Paulson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Chastain</button><button id=corop class=buttons003 onclick=qcor()>Sarah Paulson</button><button id=incop3 class=buttons003 onclick=qinc()>Marisa Tomei</button><button id=incop4 class=buttons003 onclick=qinc()>Bryce Dallas Howard</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays Bullock's former high school classmate and love interest Justin in Hope Floats?",
"answ":"HARRY CONNICK JR",
"answ3":"HARRY CONNICK JUNIOR",
"answ2":"Harry Connick Jr.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Keanu Reeves</button><button id=corop class=buttons003 onclick=qcor()>Harry Connick Jr.</button><button id=incop3 class=buttons003 onclick=qinc()>Edward Norton</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Zahn</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In The Prince of Egypt, Sandra Bullock plays Miriam, Moses' biological sister. Who voiced Moses?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeff Goldblum</button><button id=corop class=buttons003 onclick=qcor()>Val Kilmer</button><button id=incop3 class=buttons003 onclick=qinc()>Ralph Fiennes</button><button id=incop4 class=buttons003 onclick=qinc()>Christian Bale</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays Ryan Reynold's grandmother, Annie, in The Proposal?",
"answ":"BETTY WHITE",
"answ2":"Betty White.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Barbara Walters</button><button id=corop class=buttons003 onclick=qcor()>Betty White</button><button id=incop3 class=buttons003 onclick=qinc()>Angela Lansbury</button><button id=incop4 class=buttons003 onclick=qinc()>Beverly Cleary</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays the older version of Sandra Bullock's mother in Divine Secrets of the Ya-Ya Sisterhood?",
"answ":"ELLEN BURSTYN",
"answ2":"Ellen Burstyn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Barbra Streisand</button><button id=incop2 class=buttons003 onclick=qinc()>Betty White</button><button id=incop3 class=buttons003 onclick=qinc()>Angela Lansbury</button><button id=corop class=buttons003 onclick=qcor()>Ellen Burstyn</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who played Gracie's beauty pageant coach Victor Melling in Miss Congeniality?",
"answ":"MICHAEL CAINE",
"answ3":"MICHAEL CAIN",
"answ2":"Michael Caine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=corop class=buttons003 onclick=qcor()>Michael Caine</button><button id=incop3 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=incop4 class=buttons003 onclick=qinc()>J.K. Simmons</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Sandra Bullock stars alongside Matthew McConaughey and Samuel L. Jackson in what 1996 crime thriller?",
"answ":"A TIME TO KILL",
"answ2":"A Time to Kill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Client</button><button id=corop class=buttons003 onclick=qcor()>A Time to Kill</button><button id=incop3 class=buttons003 onclick=qinc()>The Firm</button><button id=incop4 class=buttons003 onclick=qinc()>The Pelican Brief</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays Sandra Bullock's husband who was killed in a car accident in the mystery film Premonition?",
"answ":"JULIAN MCMAHON",
"answ2":"Julian McMahon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jake Weber</button><button id=corop class=buttons003 onclick=qcor()>Julian McMahon</button><button id=incop3 class=buttons003 onclick=qinc()>Simon Baker</button><button id=incop4 class=buttons003 onclick=qinc()>Eric Bana</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"What 1996 rom-com stars Sandra Bullock and Denis Leary as a thieving couple who run into relationship issues when they try to sell a stolen painting?",
"answ":"TWO IF BY SEA",
"answ2":"Two If by Sea.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Who Do I Gotta Kill?</button><button id=corop class=buttons003 onclick=qcor()>Two If by Sea</button><button id=incop3 class=buttons003 onclick=qinc()>Hope Floats</button><button id=incop4 class=buttons003 onclick=qinc()>Forces of Nature</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In the film While You Were Sleeping, what is Sandra Bullock's character's job?",
"answ":"TOKEN COLLECTOR",
"answ2":"Token collector.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nurse</button><button id=incop2 class=buttons003 onclick=qinc()>Businesswoman</button><button id=incop3 class=buttons003 onclick=qinc()>Reporter</button><button id=corop class=buttons003 onclick=qcor()>Token collector</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who plays snobby socialite Daphne Kluger, who wears the valuable Toussaint diamond necklace during the heist in Ocean's Eight?",
"answ":"ANNE HATHAWAY",
"answ2":"Anne Hathaway.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rachel McAdams</button><button id=incop2 class=buttons003 onclick=qinc()>Kate Beckinsale</button><button id=incop3 class=buttons003 onclick=qinc()>Jessica Biel</button><button id=corop class=buttons003 onclick=qcor()>Anne Hathaway</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"Who directed Speed?",
"answ":"JAN DE BONT",
"answ2":"Jan de Bont.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Renny Harlin</button><button id=corop class=buttons003 onclick=qcor()>Jan de Bont</button><button id=incop3 class=buttons003 onclick=qinc()>Wolfgang Petersen</button><button id=incop4 class=buttons003 onclick=qinc()>John McTiernan</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In what 90s action film did Sandra Bullock play a by-the-book cop named Lenina Huxley?",
"answ":"DEMOLITION MAN",
"answ2":"Demolition Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Net</button><button id=corop class=buttons003 onclick=qcor()>Demolition Man</button><button id=incop3 class=buttons003 onclick=qinc()>Forces of Nature</button><button id=incop4 class=buttons003 onclick=qinc()>While You Were Sleeping</button><br/>",
},
{
"cat":"Sandra Bullock",
"ques":"In Gravity, what is the name of the space shuttle?",
"answ":"EXPLORER",
"answ3":"THE EXPLORER",
"answ2":"Explorer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Moonraker</button><button id=corop class=buttons003 onclick=qcor()>Explorer</button><button id=incop3 class=buttons003 onclick=qinc()>Intrepid</button><button id=incop4 class=buttons003 onclick=qinc()>Nostromo</button><br/>",
},
];
r2Q31 = shuffle(r2Q31);