var thrillers = [
{
"cat":"Thrillers",
"ques":"Who plays the computer hacker Lisbeth Salander in David Fincher's The Girl with the Dragon Tattoo?",
"answ":"ROONEY MARA",
"answ2":"Rooney Mara.",
},
{
"cat":"Thrillers",
"ques":"Hilary Swank stars as Detective Val Quinlan in what 2020 thriller?",
"answ":"FATALE",
"answ2":"Fatale.",
},
{
"cat":"Thrillers",
"ques":"Who starred as Ava Faulkner in 2020's Ava?",
"answ":"JESSICA CHASTAIN",
"answ2":"Jessica Chastain.",
},
{
"cat":"Thrillers",
"ques":"Jessica Chastain, John Malkovich and Colin Farrell appear in what 2020 action thriller?",
"answ":"AVA",
"answ2":"Ava.",
},
{
"cat":"Thrillers",
"ques":"Who starred as Jean Seberg in the 2019 film Seberg?",
"answ":"KRISTEN STEWART",
"answ2":"Kristen Stewart.",
},
{
"cat":"Thrillers",
"ques":"Kristen Stewart, Zazie Beetz, Anthony Mackie and Vince Vaughn appear in what 2019 political thriller?",
"answ":"SEBERG",
"answ2":"Seberg.",
},
{
"cat":"Thrillers",
"ques":"David Ayer directed Shia LaBeouf and George Lopez in what 2020 action thriller?",
"answ":"THE TAX COLLECTOR",
"answ2":"The Tax Collector.",
},
{
"cat":"Thrillers",
"ques":"Who starred as the titular character in 2020's Becky?",
"answ":"LULU WILSON",
"answ2":"Lulu Wilson.",
},
{
"cat":"Thrillers",
"ques":"In 2020's Becky, which actor starred as an escaped convict and Neo-Nazi named Dominick?",
"answ":"KEVIN JAMES",
"answ2":"Kevin James.",
},
{
"cat":"Thrillers",
"ques":"A grieving woman sets out for revenge after discovering that the plane crash that killed her family was a terrorist attack in what 2020 film?",
"answ":"THE RHYTHM SECTION",
"answ2":"The Rhythm Section.",
},
{
"cat":"Thrillers",
"ques":"Who stars as Stephanie Patrick, a woman who lost her entire family in a plane crash in 2020's The Rhythm Section?",
"answ":"BLAKE LIVELY",
"answ2":"Blake Lively.",
},
{
"cat":"Thrillers",
"ques":"While visiting Egypt, an American journalist is kidnapped by members of the Iranian regime in what 2020 film?",
"answ":"INFIDEL",
"answ2":"Infidel.",
},
{
"cat":"Thrillers",
"ques":"A young woman is terrorized by a seemingly mentally ill stranger following a road rage incident in what 2020 film?",
"answ":"UNHINGED",
"answ2":"Unhinged.",
},
{
"cat":"Thrillers",
"ques":"Which actor portrays the titular character in 2010's The Ghost Writer?",
"answ":"EWAN MCGREGOR",
"answ2":"Ewan McGregor.",
},
{
"cat":"Thrillers",
"ques":"Which James Bond actor stars as former British Prime Minister Adam Lang in 2010's The Ghost Writer?",
"answ":"PIERCE BROSNAN",
"answ2":"Pierce Brosnan.",
},
{
"cat":"Thrillers",
"ques":"Ewan McGregor, Pierce Brosnan, James Belushi and Kim Catrall appear in what thriller directed by Roman Polanski?",
"answ":"THE GHOST WRITER",
"answ2":"The Ghost Writer.",
},
{
"cat":"Thrillers",
"ques":"Russell Crowe and Elizabeth Banks star in what 2010 film about a married couple whose life is turned upside down when the wife is accused of a murder?",
"answ":"THE NEXT THREE DAYS",
"answ2":"The Next Three Days.",
},
{
"cat":"Thrillers",
"ques":"Sam Worthington and Jessica Chastain star as Mossad agents in what 2010 thiller?",
"answ":"THE DEBT",
"answ2":"The Debt.",
},
{
"cat":"Thrillers",
"ques":"Mel Gibson plays a homicide detective whose daughter is murdered in what 2010 film?",
"answ":"EDGE OF DARKNESS",
"answ2":"Edge of Darkness.",
},
{
"cat":"Thrillers",
"ques":"Who plays Boston homicide detective Thomas Craven in 2010's Edge of Darkness?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Thrillers",
"ques":"Idris Elba, Paul Walker and Matt Dillon star in what 2010 action thriller about a group of professional bank robbers?",
"answ":"TAKERS",
"answ3":"BONE DEEP",
"answ2":"Taker/Bone Deep.",
},
{
"cat":"Thrillers",
"ques":"James Marsden, Lena Headey, Norman Reedus, and Kate Hudson star in what 2000 teen psychological thriller?",
"answ":"GOSSIP",
"answ2":"Gossip.",
},
{
"cat":"Thrillers",
"ques":"Who directed the 2000 thriller The Skulls, starring Paul Walker and Joshua Jackson?",
"answ":"ROB COHEN",
"answ2":"Rob Cohen.",
},
{
"cat":"Thrillers",
"ques":"Which Fast and Furious actor starred as boxing prodigy Caleb Mandrake in 2000's The Skulls?",
"answ":"PAUL WALKER",
"answ2":"Paul Walker.",
},
{
"cat":"Thrillers",
"ques":"Russell Crowe and Meg Ryan star in what 2000 action thriller directed by Taylor Hackford?",
"answ":"PROOF OF LIFE",
"answ2":"Proof of Life.",
},
{
"cat":"Thrillers",
"ques":"Chris O'Donnell, Bill Paxton and Robin Tunney appear in what 2000s survival thriller?",
"answ":"VERTICAL LIMIT",
"answ2":"Vertical Limit.",
},
{
"cat":"Thrillers",
"ques":"Who plays Annabelle 'Annie' Wilson, a fortune teller with extrasensory perception, in Sam Raimi's The Gift?",
"answ":"CATE BLANCHETT",
"answ2":"Cate Blanchett.",
},
{
"cat":"Thrillers",
"ques":"Who plays the role of Dr. Norman Spencer in What Lies Beneath?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Thrillers",
"ques":"Guy Pearce stars alongside Carrie-Anne Moss and Joe Pantoliano in what 2000 psychological thriller?",
"answ":"MEMENTO",
"answ2":"Memento.",
},
{
"cat":"Thrillers",
"ques":"Who plays the idealistic FBI agent Kate Macer in 2015's Sicario?",
"answ":"EMILY BLUNT",
"answ2":"Emily Blunt.",
},
{
"cat":"Thrillers",
"ques":"Who wrote and directed Promising Young Woman?",
"answ":"EMERALD FENNELL",
"answ3":"EMERALD FENELL",
"answ2":"Emerald Fennell.",
},
{
"cat":"Thrillers",
"ques":"Which actress stars as the main character Cassandra 'Cassie' Thomas in the film Promising Young Woman?",
"answ":"CAREY MULLIGAN",
"answ2":"Carey Mulligan.",
},
{
"cat":"Thrillers",
"ques":"Which actress plays Dr. Ellie Staple in 2019's Glass?",
"answ":"SARAH PAULSON",
"answ2":"Sarah Paulson.",
},
{
"cat":"Thrillers",
"ques":"Which actress stars as an art gallery owner named Susan Morrow in the 2016 film Nocturnal Animals?",
"answ":"AMY ADAMS",
"answ2":"Amy Adams.",
},
{
"cat":"Thrillers",
"ques":"Which famous musical artist plays a drug addict named Spoon in the 1997 comedy-crime film Gridlock'd?",
"answ":"TUPAC SHAKUR",
"answ3":"TUPAC",
"answ2":"Tupac Shakur.",
},
{
"cat":"Thrillers",
"ques":"What classic 50s thriller features characters that are referred to as Miss Lonelyhearts, Miss Torso and Miss Hearing Aid?",
"answ":"REAR WINDOW",
"answ2":"Rear Window.",
},
{
"cat":"Thrillers",
"ques":"David Dunn is a man who is the only survivor of a train accident in what 2000 thriller?",
"answ":"UNBREAKABLE",
"answ2":"Unbreakable.",
},
{
"cat":"Thrillers",
"ques":"What Academy Award winning actor plays the lead role of lawyer Michael 'Mickey' Haller in The Lincoln Lawyer?",
"answ":"MATTHEW MCCONAUGHEY",
"answ2":"Matthew McConaughey.",
},
{
"cat":"Thrillers",
"ques":"What 2016 thriller follows a rock band called the 'Ain't Rights', who become witnesses to a murder at a club run by Neo-Nazis?",
"answ":"GREEN ROOM",
"answ2":"Green Room.",
},
{
"cat":"Thrillers",
"ques":"Which actor stars in the thrillers Nick Of Time, The Ninth Gate and From Hell?",
"answ":"JOHNNY DEPP",
"answ2":"Johnny Depp.",
},
{
"cat":"Thrillers",
"ques":"Who plays the female lead Lisa Reisert, in 2005's Red Eye?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
},
{
"cat":"Thrillers",
"ques":"Taylor Hackford directed Keanu Reeves and Al Pacino in what 1997 thriller?",
"answ":"THE DEVIL'S ADVOCATE",
"answ3":"DEVIL'S ADVOCATE",
"answ2":"The Devil's Advocate.",
},
{
"cat":"Thrillers",
"ques":"Which famous actress who is also a popstar stars in the 2015 thriller The Boy Next Door?",
"answ":"JENNIFER LOPEZ",
"answ2":"Jennifer Lopez.",
},
{
"cat":"Thrillers",
"ques":"Who plays Kevin Wendell Crumb in 2017's Split?",
"answ":"JAMES MCAVOY",
"answ2":"James McAvoy.",
},
{
"cat":"Thrillers",
"ques":"What 2014 thriller was directed by Dan Gilroy, about an ambitious sociopath named Lou Bloom?",
"answ":"NIGHTCRAWLER",
"answ2":"Nightcrawler.",
},
{
"cat":"Thrillers",
"ques":"Which thriller from director Martin Scorsese follows a U.S. Marshal whose investigation leads him to a hospital for the criminally insane?",
"answ":"SHUTTER ISLAND",
"answ2":"Shutter Island.",
},
{
"cat":"Thrillers",
"ques":"Which actor stars in a dual role, in the psychological thriller Enemy?",
"answ":"JAKE GYLLENHAAL",
"answ3":"JAKE GYLLANHAAL",
"answ2":"Jake Gyllenhaal.",
},
{
"cat":"Thrillers",
"ques":"Who stars as Hanna in the 2011 thriller Hanna?",
"answ":"SAOIRSE RONAN",
"answ2":"Saoirse Ronan.",
},
{
"cat":"Thrillers",
"ques":"In what Hitchcock-inspired thriller does Shia LaBeouf play a teenager under house arrest who suspects his neighbor of murder?",
"answ":"DISTURBIA",
"answ2":"Disturbia.",
},
{
"cat":"Thrillers",
"ques":"Who plays Lisbeth Salander in 2018's The Girl In The Spider Web?",
"answ":"CLAIRE FOY",
"answ2":"Claire Foy.",
},
{
"cat":"Thrillers",
"ques":"Who stars as Nick Dunne in Gone Girl?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
},
{
"cat":"Thrillers",
"ques":"Who starred as lawyer and adulterer Dan Gallagher, in Fatal Attraction?",
"answ":"MICHAEL DOUGLAS",
"answ2":"Michael Douglas.",
},
{
"cat":"Thrillers",
"ques":"Which MCU actor plays a tracker who aids with a murder investigation in 2017's Wind River?",
"answ":"JEREMY RENNER",
"answ2":"Jeremy Renner.",
},
{
"cat":"Thrillers",
"ques":"Who plays reporter Mikael Blomkvist in 2011's The Girl with the Dragon Tattoo?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
},
{
"cat":"Thrillers",
"ques":"This actor starred as the lead in Christopher Nolan's Memento.",
"answ":"GUY PEARCE",
"answ2":"Guy Pearce.",
},
{
"cat":"Thrillers",
"ques":"Who plays the character of Keller Dover, a man whose daughter goes missing, in 2013's Prisoners?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
},
{
"cat":"Thrillers",
"ques":"Who played Simon Callem, the protagonist, in 2015's The Gift?",
"answ":"JASON BATEMAN",
"answ2":"Jason Bateman.",
},
{
"cat":"Thrillers",
"ques":"Which David Fincher-directed thriller involves a main character who has the nickname 'Amazing Amy'?",
"answ":"GONE GIRL",
"answ2":"Gone Girl.",
},
{
"cat":"Thrillers",
"ques":"Richard Kelly directed Jake Gyllenhaal in what 2000's thriller?",
"answ":"DONNIE DARKO",
"answ2":"Donnie Darko.",
},
{
"cat":"Thrillers",
"ques":"Who directed the 2018 crime thriller The Mule?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
},
{
"cat":"Thrillers",
"ques":"Which actress stars as a surfer named Nancy in the shark-themed thriller The Shallows?",
"answ":"BLAKE LIVELY",
"answ2":"Blake Lively.",
},
{
"cat":"Thrillers",
"ques":"Christian Bale is a factory worker who suffers from severe insomnia in what psychological thriller?",
"answ":"THE MACHINIST",
"answ2":"The Machinist.",
},
{
"cat":"Thrillers",
"ques":"Which actor plays the title character in the 2012 thriller Alex Cross?",
"answ":"TYLER PERRY",
"answ2":"Tyler Perry.",
},
{
"cat":"Thrillers",
"ques":"Who starred as the unhinged Alexandra 'Alex' Forrest in Fatal Attraction?",
"answ":"GLENN CLOSE",
"answ2":"Glenn Close.",
},
{
"cat":"Thrillers",
"ques":"Which actor plays a veteran detective named Somerset in Se7en?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Thrillers",
"ques":"Who directed Gone Girl?",
"answ":"DAVID FINCHER",
"answ2":"David Fincher.",
},
{
"cat":"Thrillers",
"ques":"In Unbreakable, what is David Dunn afraid of? What is his weakness?",
"answ":"WATER",
"answ2":"Water.",
},
{
"cat":"Thrillers",
"ques":"Who played ballerina Elizabeth 'Beth' MacIntyre/The Dying Swan in Black Swan?",
"answ":"WINONA RYDER",
"answ2":"Winona Ryder.",
},
{
"cat":"Thrillers",
"ques":"Both starring Morgan Freeman, which psychological thriller is the sequel to the 1997 film Kiss the Girls?",
"answ":"ALONG CAME A SPIDER",
"answ2":"Along Came a Spider.",
},
{
"cat":"Thrillers",
"ques":"What 1962 thriller starring Frank Sinatra and Angela Lansbury follows a prisoner of war who is brainwashed into becoming an assassin for a Communist conspiracy?",
"answ":"THE MANCHURIAN CANDIDATE",
"answ3":"MANCHURIAN CANDIDATE",
"answ2":"The Manchurian Candidate.",
},
{
"cat":"Thrillers",
"ques":"Who starred as rival stringer, Joe Loder, in Nightcrawler?",
"answ":"BILL PAXTON",
"answ2":"Bill Paxton.",
},
{
"cat":"Thrillers",
"ques":"What 1998 thriller stars Michael Douglas as a wealthy Wall Street speculator who plots to have his wife killed after discovering she had an affair?",
"answ":"A PERFECT MURDER",
"answ3":"PERFECT MURDER",
"answ2":"A Perfect Murder.",
},
{
"cat":"Thrillers",
"ques":"What 1993 movie stars Michael Douglas as a divorced engineer trekking through Los Angeles to get his daughter's birthday party?",
"answ":"FALLING DOWN",
"answ2":"Falling Down.",
},
{
"cat":"Thrillers",
"ques":"Rosamund Pike and Ben Affleck starred in this 2014 David Fincher psychological thriller.",
"answ":"GONE GIRL",
"answ2":"Gone Girl.",
},
{
"cat":"Thrillers",
"ques":"David Fincher directed this 2002 thriller starring Jodie Foster and Kristen Stewart.",
"answ":"PANIC ROOM",
"answ2":"Panic Room.",
},
{
"cat":"Thrillers",
"ques":"What 1972 thriller is famous for its 'Dueling Banjos' scene?",
"answ":"DELIVERANCE",
"answ2":"Deliverance.",
},
{
"cat":"Thrillers",
"ques":"What was the name of the sequel to The Fugitive?",
"answ":"US MARSHALS",
"answ2":"U.S. Marshals.",
},
{
"cat":"Thrillers",
"ques":"Hugh Jackman plays a father looking for his missing daughter in Prisoners. Who plays his friend Franklin?",
"answ":"TERRENCE HOWARD",
"answ3":"TERRANCE HOWARD",
"answ2":"Terrence Howard.",
},
{
"cat":"Thrillers",
"ques":"What 2003 legal thriller based on a John Grisham novel stars John Cusack and Gene Hackman?",
"answ":"RUNAWAY JURY",
"answ2":"Runaway Jury.",
},
{
"cat":"Thrillers",
"ques":"Who played Suzie Toller in the 1998 thriller Wild Things, along with Denise Richards and Matt Dillon?",
"answ":"NEVE CAMPBELL",
"answ3":"NEVE CAMPBEL",
"answ2":"Neve Campbell.",
},
{
"cat":"Thrillers",
"ques":"Who starred as the male lead in the 2005 supernatural-thriller White Noise?",
"answ":"MICHAEL KEATON",
"answ2":"Michael Keaton.",
},
{
"cat":"Thrillers",
"ques":"How much is the ransom demand in 1996's Ransom?",
"answ":"2 MILLION",
"answ3":"2 000 000",
"answ2":"2 million dollars.",
},
];
var r2Q32 = [
{
"cat":"Thrillers",
"ques":"In what city do Jim Garrison and his family reside in JFK?",
"answ":"NEW ORLEANS",
"answ2":"New Orleans.",
"option":["New Orleans", "Boston", "New York", "Chicago"],
},
{
"cat":"Thrillers",
"ques":"In what film does Brad Pitt play an IRA terrorist that is hiding out in the home of a New York cop?",
"answ":"THE DEVIL'S OWN",
"answ3":"DEVIL'S OWN",
"answ2":"The Devil's Own.",
"option":["The Devil's Own", "Sleepers", "The Fugitive", "Spy Game"],
},
{
"cat":"Thrillers",
"ques":"In Witness, the Amish boy witnesses the murder in a ____",
"answ":"BATHROOM",
"answ3":"BATHROOM OF A TRAIN STATION",
"answ2":"A bathroom of a train station.",
"option":["Bathroom of a train station", "Parking lot", "Shopping mall", "Church"],
},

{
"cat":"Thrillers",
"ques":"Who played Mel Gibson's wife in Ransom?",
"answ":"RENE RUSSO",
"answ3":"RENEE RUSSO",
"answ2":"Rene Russo.",
"option":["Rene Russo", "Helena Bonham Carter", "Jodie Foster", "Sharon Stone"],
},
{
"cat":"Thrillers",
"ques":"Who plays the detective with whom Meg Ryan has an affair in 2003's In the Cut?",
"answ":"MARK RUFFALO",
"answ2":"Mark Ruffalo.",
"option":["Mark Ruffalo", "Tom Hanks", "Russell Crowe", "Jeff Bridges"],
},
{
"cat":"Thrillers",
"ques":"What was the unique characteristic of the killer in The Fugitive?",
"answ":"ONE ARM",
"answ3":"HE HAD ONE ARM",
"answ2":"He had one arm.",
"option":["He had one arm", "He was deaf", "He was mute", "He had one ear"],
},
{
"cat":"Thrillers",
"ques":"What is Sharon Stone's profession in the 1992 thriller Basic Instinct?",
"answ":"WRITER",
"answ3":"CRIME NOVELIST",
"answ2":"Crime Novelist/Writer.",
"option":["Crime Novelist", "Detective", "Painter", "Lawyer"],
},
{
"cat":"Thrillers",
"ques":"Which 1981 thriller stars John Travolta as a sound technician who secretly records a political assassination?",
"answ":"BLOW OUT",
"answ2":"Blow Out.",
"option":["Blow Out", "Body Heat", "Nighthawks", "Death Hunt"],
},
{
"cat":"Thrillers",
"ques":"Who directed 1995's thriller Outbreak?",
"answ":"WOLFGANG PETERSEN",
"answ2":"Wolfgang Petersen.",
"option":["Wolfgang Petersen", "Jan de Bont", "Kevin Reynolds", "Ron Howard"],
},
{
"cat":"Thrillers",
"ques":"Who plays FBI agent Jennifer Marsh who investigates a serial killer in the 2008 thriller Untraceable?",
"answ":"DIANE LANE",
"answ2":"Diane Lane.",
"option":["Diane Lane", "Hilary Swank", "Marisa Tomei", "Rene Russo"],
},
{
"cat":"Thrillers",
"ques":"What actor plays Detective McFee, who takes part in killing the man in the bathroom in Witness?",
"answ":"DANNY GLOVER",
"answ2":"Danny Glover.",
"option":["Danny Glover", "Viggo Mortensen", "Harisson Ford", "Ed Harris"],
},
{
"cat":"Thrillers",
"ques":"You'll find Mort Rainey, a depressed author suffering from writer's block in what 2004 psychological thriller?",
"answ":"SECRET WINDOW",
"answ2":"Secret Window.",
"option":["Secret Window", "Ghost Town", "Stir of Echoes", "The Paper"],
},
{
"cat":"Thrillers",
"ques":"Who played Brad Pitt's wife Tracy in Se7en?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
"option":["Gwyneth Paltrow", "Julianne Moore", "Evangeline Lilly", "Liv Tyler"],
},
{
"cat":"Thrillers",
"ques":"Who plays Jodie Foster's 11-year old daughter in Panic Room?",
"answ":"KRISTEN STEWART",
"answ3":"KIRSTEN STEWART",
"answ2":"Kristen Stewart.",
"option":["Kristen Stewart", "Selena Gomez", "Dakota Fanning", "Chloë Grace Moretz"],
},
{
"cat":"Thrillers",
"ques":"Bridget Fonda gets creeped out by a terrorizing roommate Jennifer Jason Leigh in what 1992 thriller?",
"answ":"SINGLE WHITE FEMALE",
"answ2":"Single White Female.",
"option":["Single White Female", "The Crying Game", "The Hand that Rocks the Cradle", "Jennifer 8"],
},
{
"cat":"Thrillers",
"ques":"Which legendary actor played John Ferguson in Hitchcock's Vertigo?",
"answ":"JAMES STEWART",
"answ3":"JIMMY STEWART",
"answ2":"James Stewart.",
"option":["James Stewart", "Kirk Douglas", "John Wayne", "Ray Milland"],
},
{
"cat":"Thrillers",
"ques":"What is the name of the second installment in the Robert Langdon trilogy, based on the novels by Dan Brown?",
"answ":"ANGELS AND DEMONS",
"answ2":"Angels & Demons.",
"option":["Angels & Demons", "The Da Vinci Code", "Inferno", "Kiss the Girls"],
},
{
"cat":"Thrillers",
"ques":"What actress starred opposite Alec Baldwin in the 1996 legal thriller The Juror?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
"option":["Demi Moore", "Michelle Pfeiffer", "Kim Basinger", "Meg Ryan"],
},
{
"cat":"Thrillers",
"ques":"Which famous actor played the lead in 1972's The Getaway?",
"answ":"STEVE MCQUEEN",
"answ2":"Steve McQueen.",
"option":["Steve McQueen", "Charles Bronson", "James Stewart", "Robert Vaughn"],
},
{
"cat":"Thrillers",
"ques":"What is the profession of Tom Cruise's character in 2004's Collateral?",
"answ":"HITMAN",
"answ3":"ASSASSIN",
"answ2":"Hitman/Assassin.",
"option":["Hitman", "Banker", "Taxi Driver", "Lawyer"],
},
{
"cat":"Thrillers",
"ques":"The character of Hannibal Lecter has appeared in how many theatrically released films?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":["5", "4", "3", "6"],
},
{
"cat":"Thrillers",
"ques":"What actress & music star is featured opposite Sean Penn in 1997's thriller U-Turn?",
"answ":"JENNIFER LOPEZ",
"answ2":"Jennifer Lopez.",
"option":["Jennifer Lopez", "Whitney Houston", "Madonna", "Cher"],
},
{
"cat":"Thrillers",
"ques":"Who played magician Robert Angier, whose wife drowns during a water tank trick in The Prestige?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
"option":["Hugh Jackman", "Christian Bale", "Michael Caine", "Benicio Del Toro"],
},
{
"cat":"Thrillers",
"ques":"Who played the role of Conrad van Orton in 1997's The Game?",
"answ":"SEAN PENN",
"answ2":"Sean Penn.",
"option":["Sean Penn", "Jude Law", "Guy Pierce", "Matthew Broderick"],
},
{
"cat":"Thrillers",
"ques":"In Phone Booth, who plays the mysterious caller who has a sniper rifle aimed at Colin Farrell?",
"answ":"KIEFER SUTHERLAND",
"answ2":"Kiefer Sutherland.",
"option":["Kiefer Sutherland", "Frank Grillo", "Jude Law", "Jim Caviezel"],
},
{
"cat":"Thrillers",
"ques":"Who played former fireman Darren McCord in Sudden Death?",
"answ":"JEAN CLAUDE VAN DAMME",
"answ2":"Jeane-Claude Van Damme.",
"option":["Jeane-Claude Van Damme", "Chuck Norris", "Steven Seagal", "Bruce Willis"],
},
{
"cat":"Thrillers",
"ques":"Joshua Jackson and Paul Walker both starred in this film about a secret society of the same name.",
"answ":"THE SKULLS",
"answ2":"The Skulls.",
"option":["The Skulls", "The Company", "The Overlords", "The Society"],
},
{
"cat":"Thrillers",
"ques":"Who played Bob Woodward in All the President's Men?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
"option":["Robert Redford", "Dustin Hoffman", "Micheael Douglas", "Jack Nicholson"],
},
{
"cat":"Thrillers",
"ques":"Harry Connick Jr. plays a deranged killer in what 1995 thriller?",
"answ":"COPYCAT",
"answ2":"Copcat.",
"option":["Copcat", "Heat", "Seven", "The Usual Suspects"],
},
{
"cat":"Thrillers",
"ques":"Who played the villain in Se7en?",
"answ":"KEVIN SPACEY",
"answ2":"Kevin Spacey.",
"option":["Kevin Spacey", "Morgan Freeman", "Christopher Walken", "Dennis Hopper"],
},
{
"cat":"Thrillers",
"ques":"Which thriller has an ensemble cast including John Cusack as a limo driver and Amanda Peet as a Vegas prostitute?",
"answ":"IDENTITY",
"answ2":"Identity.",
"option":["Identity", "L.A. Confidential", "Heat", "Blow Out"],
},
{
"cat":"Thrillers",
"ques":"In Gone Girl, who plays the wealthy ex-boyfriend of Rosamund Pike's character?",
"answ":"NEIL PATRICK HARRIS",
"answ2":"Neil Patrick Harris.",
"option":["Neil Patrick Harris", "Ryan Gosling", "James Marsden", "Nicholas Hoult"],
},
{
"cat":"Thrillers",
"ques":"In Split, what was the nickname for the cannibalistic personality taken by James McAvoy's character at the climax of the movie?",
"answ":"THE BEAST",
"answ3":"BEAST",
"answ2":"The Beast.",
"option":["The Beast", "The Goliath", "The Eater", "The Hunger"],
},
{
"cat":"Thrillers",
"ques":"F. Gary Gray directed what 2009 crime thriller starring Gerard Butler and Jamie Foxx?",
"answ":"LAW ABIDING CITIZEN",
"answ2":"Law Abiding Citizen.",
"option":["Law Abiding Citizen", "The Sea of Trees", "A Man Apart", "The Italian Job"],
},
{
"cat":"Thrillers",
"ques":"In what thriller will you find a serial killer with the nickname 'Buffalo Bill'?",
"answ":"THE SILENCE OF THE LAMBS",
"answ3":"SILENCE OF THE LAMBS",
"answ2":"The Silence of the Lambs.",
"option":["The Silence of the Lambs", "The Bone Collector", "Saw", "Zodiac"],
},
{
"cat":"Thrillers",
"ques":"Who played Tim Robbins' deceased son in Jacob's Ladder?",
"answ":"MACALAY CULKIN",
"answ3":"MACAULAY CULKIN",
"answ2":"Macaulay Culkin.",
"option":["Macaulay Culkin", "Haley Joel Osment", "Jake Lloyd", "Spencer Treat Clark"],
},
{
"cat":"Thrillers",
"ques":"In the 1989 thriller Dead Calm, how does John and Rae Ingram's son die in the opening scene?",
"answ":"CAR ACCIDENT",
"answ2":"Car accident.",
"option":["Car accident", "Drowned", "Allergic reaction", "Cancer"],
},
{
"cat":"Thrillers",
"ques":"Johnny Depp plays a rare book dealer who while seeking out the last two copies of a demon text, gets drawn into a supernatural conspiracy in what film?",
"answ":"THE NINTH GATE",
"answ3":"THE 9TH GATE",
"answ2":"The Ninth Gate.",
"option":["The Ninth Gate", "Dead Man", "From Hell", "Secret Window"],
},
{
"cat":"Thrillers",
"ques":"Who plays the villainous Ray Marcus, leader of the murderous rednecks in Nocturnal Animals?",
"answ":"AARON TAYLOR JOHNSON",
"answ3":"ARON TAYLOR JOHNSON",
"answ2":"Aaron Taylor-Johnson.",
"option":["Aaron Taylor-Johnson", "Adrien Brody", "Adam Driver", "Ryan Gosling"],
},
{
"cat":"Thrillers",
"ques":"What Lord of the Rings actor stars as the pilot trying to solve the mystery of the missing girl in 2005's Flightplan?",
"answ":"SEAN BEAN",
"answ2":"Sean Bean.",
"option":["Sean Bean", "Ian McKellen", "Orlando Bloom", "Karl Urban"],
},
{
"cat":"Thrillers",
"ques":"Who plays suspected kidnapper Alex Jones in Denis Villeneuve's Prisoners?",
"answ":"PAUL DANO",
"answ2":"Paul Dano.",
"option":["Paul Dano", "Jesse Eisenberg", "Justin Long", "Jake Gyllenhaal"],
},
{
"cat":"Thrillers",
"ques":"Which actor plays the character of Leo Barnes, in both The Purge: Anarchy and The Purge: Election Year?",
"answ":"FRANK GRILLO",
"answ2":"Frank Grillo.",
"option":["Frank Grillo", "Clive Owen", "Jim Caviezel", "Jason Clarke"],
},
{
"cat":"Thrillers",
"ques":"Which character actor played Stanley, father of Carey Mulligan's character in Promising Young Woman?",
"answ":"CLANCY BROWN",
"answ2":"Clancy Brown.",
"option":["Clancy Brown", "Oliver Platt", "Bruce Greenwood", "Peter Stormare"],
},
{
"cat":"Thrillers",
"ques":"Who plays David Dunn's wife Audrey in the 2000 superhero thriller Unbreakable?",
"answ":"ROBIN WRIGHT",
"answ2":"Robin Wright.",
"option":["Robin Wright", "Mary Steenburgen", "Ashley Judd", "Demi Moore"],
},
{
"cat":"Thrillers",
"ques":"Who plays U.S. Marshall Samuel Gerard, hunting Harrison Ford's Richard Kimble, in 1993's The Fugitive?",
"answ":"TOMMY LEE JONES",
"answ2":"Tommy Lee Jones.",
"option":["Tommy Lee Jones", "Nick Nolte", "Morgan Freeman", "Ed Harris"],
},
{
"cat":"Thrillers",
"ques":"Which Black Panther actor plays Reggie Wayne, Kate's partner, in the crime thriller Sicario?",
"answ":"DANIEL KALUUYA",
"answ3":"DANIEL KALUYA",
"answ2":"Daniel Kaluuya.",
"option":["Daniel Kaluuya", "Chadwick Boseman", "Michael B. Jordan", "Winston Duke"],
},
{
"cat":"Thrillers",
"ques":"This actor stars alongisde Hugh Jackman as Detective Loki in Prisoners.",
"answ":"JAKE GYLLENHAAL",
"answ2":"Jake Gyllenhaal.",
"option":["Jake Gyllenhaal", "Christian Bale", "James Marsden", "Mark Ruffalo"],
},
{
"cat":"Thrillers",
"ques":"In David Fincher's Se7en, who plays the police captain?",
"answ":"R LEE ERMEY",
"answ3":"RONALD LEE ERMEY",
"answ2":"R. Lee Ermey.",
"option":["R. Lee Ermey", "Richard Roundtree", "Richard Schiff", "Mark Boone Junior"],
},
{
"cat":"Thrillers",
"ques":"In Panic Room, what health condition does Kristen Stewart's Sarah have that causes complications during the home invasion?",
"answ":"DIABETES",
"answ3":"DIABETES MELLITUS",
"answ2":"Diabetes.",
"option":["Diabetes", "Asthma", "Epilepsy", "Congenital Heart Disease"],
},
{
"cat":"Thrillers",
"ques":"The first victim that Somerset and Mills encounter in Se7en was 'guilty' of which sin?",
"answ":"GLUTTONY",
"answ2":"Gluttony.",
"option":["Gluttony", "Lust", "Greed", "Sloth"],
},
{
"cat":"Thrillers",
"ques":"Who plays Jim Hudson, the man who wins the bid to live in Chris' body, in Get Out?",
"answ":"STEPHEN ROOT",
"answ2":"Stephen Root.",
"option":["Stephen Root", "Oliver Platt", "Sam Neill", "Bradley Whitford"],
},
{
"cat":"Thrillers",
"ques":"William Hurt plays Kevin Costner's alter ego in what psychological thriller?",
"answ":"MR BROOKS",
"answ2":"Mr. Brooks.",
"option":["Mr. Brooks", "Perfect World", "Dragonfly", "3 Days To Kill"],
},
{
"cat":"Thrillers",
"ques":"Who plays Clyde Alexander Shelton, a man on a mission to avenge his wife and daughter, in 2009's Law Abiding Citizen?",
"answ":"GERARD BUTLER",
"answ2":"Gerard Butler.",
"option":["Gerard Butler", "Jamie Foxx", "Liam Neeson", "Frank Grillo"],
},
{
"cat":"Thrillers",
"ques":"David Lynch directed Naomi Watts and Justin Theroux in this 2001 neo-noir thriller.",
"answ":"MULHOLLAND DRIVE",
"answ2":"Mulholland Drive.",
"option":["Mulholland Drive", "Lost Highway", "The Man Who Wasn't There", "The Deep End"],
},
{
"cat":"Thrillers",
"ques":"In 1995's Se7en, Detective Mills commits the last of the 7 Deadly Sins at the end of the film, what is that sin?",
"answ":"WRATH",
"answ2":"Wrath.",
"option":["Wrath", "Pride", "Lust", "Greed"],
},
{
"cat":"Thrillers",
"ques":"Which DCEU actor has the role of George, a senior CIA supervisor in Zero Dark Thirty?",
"answ":"MARK STRONG",
"answ2":"Mark Strong.",
"option":["Mark Strong", "J.K. Simmons", "Harry Lenix", "Jai Courtney"],
},
{
"cat":"Thrillers",
"ques":"Which actress stars as the adult version of Melinda Gayle in the 2018 Tyler Perry film Acrimony, a thriller about a wronged wife?",
"answ":"TARAJI P HENSON",
"answ2":"Taraji P. Henson.",
"option":["Taraji P. Henson", "Janelle Monáe", "Octavia Spencer", "Angela Bassett"],
},
{
"cat":"Thrillers",
"ques":"In Firewall, which actor stars as Bill Cox, a businessman that holds Harrison Ford's character and his family hostage?",
"answ":"PAUL BETTANY",
"answ2":"Paul Bettany.",
"option":["Paul Bettany", "Gary Oldman", "Neil Patrick Harris", "Eric Bana"],
},
{
"cat":"Thrillers",
"ques":"What MCU actor co-stars with Viola Davis in the thriller Blackhat as the character Nicholas Hathaway?",
"answ":"CHRIS HEMSWORTH",
"answ2":"Chris Hemsworth.",
"option":["Chris Hemsworth", "Jeremy Renner", "Robert Downey Jr.", "Chris Evans"],
},
{
"cat":"Thrillers",
"ques":"Zero Dark Thirty follows the real-life mission to kill whom?",
"answ":"OSAMA BIN LADEN",
"answ2":"Osama bin Laden.",
"option":["Osama bin Laden", "Saddam Hussein", "Adolf Hitler", "Joseph Stalin"],
},
{
"cat":"Thrillers",
"ques":"Who stars as Detective Keith Frazier in Inside Man?",
"answ":"DENZEL WASHINGTON",
"answ2":"Denzel Washington.",
"option":["Denzel Washington", "Chiwetel Ejiofor", "Idris Elba", "Will Smith"],
},
{
"cat":"Thrillers",
"ques":"Spike Lee directed what 2013 thriller starring Josh Brolin?",
"answ":"OLDBOY",
"answ2":"Oldboy.",
"option":["Oldboy", "Inside Man", "Prisoners", "Homefront"],
},
{
"cat":"Thrillers",
"ques":"Who wrote and directed the 90s thriller The Crying Game starring Stephen Rea?",
"answ":"NEIL JORDAN",
"answ2":"Neil Jordan.",
"option":["Neil Jordan", "Stephen Frears", "Stephen Dalrdy", "Peter Cattaneo"],
},
];
thrillers = shuffle(thrillers);
r2Q32 = shuffle(r2Q32);