var scoressoundtracks = [
{
"cat":"Scores & Soundtracks",
"ques":"Blue Öyster Cult, Cheap Trick, Black Sabbath and Sammy Hagar lent music to this 1981 animated epic.",
"answ":"HEAVY METAL",
"answ2":"Heavy Metal.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What legendary western film composer composed the following 80s movies: The Mission, The Untouchables and Cinema Paradiso?",
"answ":"ENNIO MORRICONE",
"answ2":"Ennio Morricone.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The song 'Beat It' by Michael Jackson can be heard playing in the Cafe 80s in what 1989 sci-fi comedy?",
"answ":"BACK TO THE FUTURE PART II",
"answ3":"BACK TO THE FUTURE PART 2",
"answ2":"Back to the Future Part II.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for the films The Land Before Time and Willow?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for Gremlins and Poltergeist?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for the 2019 films Dumbo and Men In Black: International?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which 1980s film famously features the song 'Oh Yeah' performed by the band Yello?",
"answ":"FERRIS BUELLER'S DAY OFF",
"answ2":"Ferris Bueller's Day Off.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In what MCU sequel is the song 'Brandy' played multiple times?",
"answ":"GUARDIANS OF THE GALAXY VOL 2",
"answ3":"GUARDIANS OF THE GALAXY 2",
"answ2":"Guardians of the Galaxy Vol 2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Disney live action film features the songs 'Ever Ever After', 'So Close' and 'True Love's Kiss'",
"answ":"ENCHANTED",
"answ2":"Enchanted.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which composer wrote the music for all 3 The Lord of the Rings films?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Lion King and Interstellar?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Oscar-winning composer did the music for 1978's Superman: The Movie?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the first three Harry Potter films?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who provided the score for the films A Beautiful Mind and Braveheart?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which rap/hip hop artist had his songs featured in The Amazing Spider Man 2, Divergent and Black Panther?",
"answ":"KENDRICK LAMAR",
"answ2":"Kendrick Lamar.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who sings the iconic song 'You've Got a Friend In Me' in the original Toy Story?",
"answ":"RANDY NEWMAN",
"answ2":"Randy Newman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Salma Hayek dances to the song After Dark in what 90s movie?",
"answ":"FROM DUSK TILL DAWN",
"answ2":"From Dusk Till Dawn.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2017's The Shape of Water?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Rogue One: A Star Wars Story?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who sang the theme song to the 1980 hit comedy Nine to Five?",
"answ":"DOLLY PARTON",
"answ2":"Dolly Parton.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Incredibles?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The song Raindrops Keep Fallin' on My Head was written for what classic film?",
"answ":"BUTCH CASSIDY AND THE SUNDANCE KID",
"answ2":"Butch Cassidy and the Sundance Kid.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Rocky composer Bill Conti won an Oscar in 1983 for scoring this inspirational true story.",
"answ":"THE RIGHT STUFF",
"answ2":"The Right Stuff.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer of Star Trek: The Motion Picture?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What is the name of the song the crew listens to before landing in the jungle in Predator?",
"answ":"LONG TALL SALLY",
"answ2":"Long Tall Sally.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which movie's soundtrack features a tune by it's own fictional band The Soggy Bottom Boys?",
"answ":"O BROTHER WHERE ART THOU",
"answ3":"O BROTHER WHERE ARE THOU",
"answ2":"O Brother, Where Art Thou?",
},
];
var r2Q33 = [
{
"cat":"Scores & Soundtracks",
"ques":"Kenny Loggins recorded 'Danger Zone' and what other song for Top Gun?",
"answ":"PLAYING WITH THE BOYS",
"answ2":"Playing with the Boys.",
"option":["Playing with the Boys", "I'm Alright", "Conviction of the Heart", "Forever"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Name the composer of the classic score from Rudy.",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "James Horner", "John Williams", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What band is responsible for the Rocky classic Eye of the Tiger?",
"answ":"SURVIVOR",
"answ2":"Survivor.",
"option":["Survivor", "Europe", "The Rolling Stones", "Oasis"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The Guns N' Roses song 'You Could Be Mine' is featured in what classic from the 90s?",
"answ":"TERMINATOR 2 JUDGMENT DAY",
"answ3":"TERMINATOR 2",
"answ2":"Terminator 2: Judgment Day.",
"option":["Terminator 2: Judgment Day", "Jurassic Park", "The Matrix", "Total Recall"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for Pixar's Up?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "James Horner", "Alan Silvestri", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for 2012's The Avengers?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Hans Zimmer", "James Horner", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for Interstellar?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "James Horner", "Alan Silvestri", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Up Where We Belong was a smash hit used in what 1982 film?",
"answ":"AN OFFICER AND A GENTLEMAN",
"answ2":"An Officer and a Gentleman.",
"option":["An Officer and a Gentleman", "Gandhi", "Sophie's Choice", "One from the Heart"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for 1984's The Terminator?",
"answ":"BRAD FIEDEL",
"answ2":"Brad Fiedel.",
"option":["Brad Fiedel", "John Williams", "Alan Silvestri", "Jack Nitzsche"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for 2009's Avatar?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Danny Elfman", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which song greets Bill Murray each morning in Groundhog Day?",
"answ":"I GOT YOU BABE",
"answ2":"I Got You Babe.",
"option":["I Got You Babe", "A Thousand Miles", "Lovely Day", "I Smile"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Say Anything, which song does Lloyd play on his boombox outside Diane's window?",
"answ":"IN YOUR EYES",
"answ2":"In Your Eyes.",
"option":["In Your Eyes", "Good Vibrations", "The Book of Love", "Come Together"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who recorded the theme from the 1971 movie Shaft?",
"answ":"ISAAC HAYES",
"answ2":"Isaac Hayes.",
"option":["Isaac Hayes", "Marvin Gaye", "Michael Jackson", "Stevie Wonder"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor, Rise of the Planet of the Apes and Brave?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":["Patrick Doyle", "Brian Tyler", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for 1987's Predator?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Jerry Goldsmith", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays during Jennifer Beal's training montage in Flashdance?",
"answ":"MANIAC",
"answ2":"Maniac.",
"option":["Maniac", "Never", "Fame", "Stay"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the new music for 2006's Superman Returns?",
"answ":"JOHN OTTMAN",
"answ3":"JOHN OTMAN",
"answ2":"John Ottman.",
"option":["John Ottman", "Alan Silvestri", "James Horner", "Patrick Doyle"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which 90s film had a soundtrack featuring 'Burn' by The Cure and 'Big Empty' by Stone Temple Pilots?",
"answ":"THE CROW",
"answ2":"The Crow.",
"option":["The Crow", "Reality Bites", "Mystery Men", "The Mask"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Gremlins?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Jack Nitzsche", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Hans Zimmer won his only Academy Award for Best Original Score for which film?",
"answ":"THE LION KING",
"answ3":"LION KING",
"answ2":"The Lion King.",
"option":["The Lion King", "Dunkirk", "Interstellar", "Inception"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What hit song was written and performed by R. Kelly for Space Jam?",
"answ":"I BELIEVE I CAN FLY",
"answ2":"I Believe I Can Fly.",
"option":["I Believe I Can Fly", "Bump n' Grind", "Your Body's Callin'", "The World's Greatest"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1960's The Magnificent Seven?",
"answ":"ELMER BERNSTEIN",
"answ2":"Elmer Bernstein.",
"option":["Elmer Bernstein", "Ernest Gold", "Henry Mancini", "Alex North"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What group recorded 'Don't You Forget About Me' for The Breakfast Club?",
"answ":"SIMPLE MINDS",
"answ2":"Simple Minds.",
"option":["Simple Minds", "N'Sync", "Backstreet Boys", "Take That"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Road to Perdition, Finding Nemo and Skyfall?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Patrick Doyle", "Alan Silverstri", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Lethal Weapon, Die Hard and License to Kill?",
"answ":"MICHAEL KAMEN",
"answ2":"Michael Kamen.",
"option":["Michael Kamen", "Dave Grusin", "Randy Newman", "Quincy Jones"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Guardians of the Galaxy Vol. 2, what song did Ego say was about himself and Peter's mother?",
"answ":"BRANDY",
"answ2":"Brandy.",
"option":["Brandy", "Fox On The Run", "The Chain", "Jolene"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Besides the first two Terminator films, what other James Cameron movie had it's score composed by Brad Fiedel?",
"answ":"TRUE LIES",
"answ2":"True Lies.",
"option":["True Lies", "The Abyss", "Aliens", "Avatar"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Lisa Loeb's Gen-X hit 'Stay' plays over the closing credits of what Winona Ryder movie?",
"answ":"REALITY BITES",
"answ2":"Reality Bites.",
"option":["Reality Bites", "Heathers", "Girl, Interrupted", "Mermaids"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Sam Raimi's 2001 hit Spider-Man?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Alan Silvestri", "Brian Tyler", "Henry Jackman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Back to the Future?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Danny Elfman", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was credited as composing the score for 1982's The Thing?",
"answ":"ENNIO MORRICONE",
"answ3":"ENNIO MORICONE",
"answ2":"Ennio Morricone.",
"option":["Ennio Morricone", "John Carpenter", "John Williams", "Alan Howarth"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What famed composer was nominated at the Oscars for Best Original Score for both Little Women and The Shawkshank Redemption?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "James Horner", "Jerry Goldsmith", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2004's Troy?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Hans Zimmer", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for James Cameron's The Abyss?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Howard Shore", "Ennio Morricone", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1984's The Karate Kid?",
"answ":"BILL CONTI",
"answ2":"Bill Conti.",
"option":["Bill Conti", "John Williams", "Alan Silvestri", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1989's Glory?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Hans Zimmer", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1979's Alien?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The Hateful Eight features a track called 'Beastiality', an unused piece of music from which 1982 horror film?",
"answ":"THE THING",
"answ2":"The Thing.",
"option":["The Thing", "Aliens", "The Shining", "A Nightmare on Elm Street"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Titanic?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Michael Giacchino", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What Lord of the Rings actor wrote and performed the song 'The Last Goodbye' for the soundtrack of The Hobbit: Battle of the Five Armies?",
"answ":"BILLY BOYD",
"answ2":"Billy Boyd.",
"option":["Billy Boyd", "Elijah Wood", "Sean Astin", "Dominic Monaghan"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What musical artist created the soundtrack for Disney's Tarzan in 1999?",
"answ":"PHIL COLLINS",
"answ2":"Phil Collins.",
"option":["Phil Collins", "Elton John", "Randy Newman", "David Bowie"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which legendary composer is well-known for scores ranging from Citizen Kane to Psycho to Taxi Driver?",
"answ":"BERNARD HERRMANN",
"answ3":"BERNARD HERMANN",
"answ2":"Bernard Herrmann.",
"option":["Bernard Herrmann", "Ennio Morricone", "John Wiliams", "John Barry"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2009's Sherlock Holmes?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Michael Giacchino", "Alexandre Desplat", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"'Raindrops Keep Fallin' on My Head' was famously written for what classic film?",
"answ":"BUTCH CASSIDY AND THE SUNDANCE KID",
"answ2":"Butch Cassidy and the Sundance Kid.",
"option":["Butch Cassidy and the Sundance Kid", "Vertigo", "Psycho", "Citizen Kane"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for The Hunger Games?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":["James Newton Howard", "Danny Elfman", "John Carpenter", "Henry Jackman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Apollo 13?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "Ennio Morricone", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What 90s boy band performed the song 'True to Your Heart' alongside Stevie Wonder in Disney's Mulan?",
"answ":"98 DEGREES",
"answ2":"98 Degrees.",
"option":["98 Degrees", "Dream Street", "B2K", "Take That"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Scorsese films: The Aviator, The Departed ang Hugo?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "Thomas Newman", "James Horner", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1990's Total Recall?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Thomas Newman", "Alan Silvestri", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performed Back in Time from Back to the Future?",
"answ":"HUEY LEWIS",
"answ3":"HUEY LEWIS AND THE NEWS",
"answ2":"Huey Lewis and the News.",
"option":["Huey Lewis and the News", "Eric Clapton", "Etta James", "Marvin Berry & The Starlighters"],
},
{
"cat":"Scores & Soundtracks",
"ques":"For what film did Italian composer Ennio Morricone win his first Oscar for Best Original Score?",
"answ":"THE HATEFUL EIGHT",
"answ3":"HATEFUL EIGHT",
"answ2":"The Hateful Eight.",
"option":["The Hateful Eight", "The Mission", "The Good the Bad and the Ugly", "Once Upon a Time in the West"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score to Pixar's WALL-E?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Alan Silvestri", "Howard Shore", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Baby Driver, Baby's 'killer track' is from what 1970s rock band?",
"answ":"QUEEN",
"answ2":"Queen.",
"option":["Queen", "The Who", "The Rolling Stones", "Pink Floyd"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The scores from The Terminator, Fright Night and True Lies were all composed by whom?",
"answ":"BRAD FIEDEL",
"answ2":"Brad Fiedel.",
"option":["Brad Fiedel", "James Newton Howard", "John Williams", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who wrote the soundtrack for Escape from New York?",
"answ":"JOHN CARPENTER",
"answ2":"John Carpenter.",
"option":["John Carpenter", "Jerry Goldsmith", "Basil Poledouris", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Goodfellas, what song plays during the iconic long tracking shot of Henry and Karen entering the Copacabana?",
"answ":"THEN HE KISSED ME",
"answ2":"Then He Kissed Me.",
"option":["Then He Kissed Me", "Rag to Riches", "Baby, I Love You", "Layla"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the J.J. Abrams directed Super 8?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Trevor Rabin", "Alan Silvestri", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which actress sings Can't Take My Eyes Off of You to Jesus on a cross for her pageant talent in Drop Dead Gorgeous?",
"answ":"DENISE RICHARDS",
"answ2":"Denise Richards.",
"option":["Denise Richards", "Kirsten Dunst", "Amy Adams", "Brittany Murphy"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Amazing Spider-Man 2?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Howard Shore", "Alan Silvestri", "Junkie XL"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Aerosmith, Alice Cooper, ZZ Top and Ted Nugent all provide songs for what 1993 comedy?",
"answ":"DAZED AND CONFUSED",
"answ2":"Dazed and Confused.",
"option":["Dazed and Confused", "Hot Shots! Part Deux", "Wayne's World 2", "Groundhog Day"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Commando?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Jerry Goldsmith", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Zero Dark Thirty?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "Michael Giacchino", "Danny Elfman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Eye of the Tiger first appeared in which Rocky film?",
"answ":"ROCKY 3",
"answ3":"ROCKY III",
"answ2":"Rocky 3.",
"option":["Rocky 3", "Rocky", "Rocky 2", "Rocky 4"],
},
{
"cat":"Scores & Soundtracks",
"ques":"M.I.A.'s song Paper Planes appears in what Danny Boyle film?",
"answ":"SLUMDOG MILLIONAIRE",
"answ2":"Slumdog Millionaire.",
"option":["Slumdog Millionaire", "Trainspotting", "Sunshine", "127 Hours"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Lesley Barber composed the score to what 2016 film that was later nominated for a Best Picture Oscar?",
"answ":"MANCHESTER BY THE SEA",
"answ2":"Manchester By The Sea.",
"option":["Manchester By The Sea", "Lion", "Hidden Figures", "Hacksaw Ridge"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Coen Brothers film is known for the song 'I Am a Man of Constant Sorrow'?",
"answ":"O BROTHER WHERE ART THOU",
"answ2":"O Brother, Where Art Thou?.",
"option":["O Brother, Where Art Thou?", "Fargo", "True Grit", "The Ladykillers"],
},
];
scoressoundtracks = shuffle(scoressoundtracks);
r2Q33 = shuffle(r2Q33);