var scoressoundtracks = [
{
"cat":"Scores & Soundtracks",
"ques":"Blue Öyster Cult, Cheap Trick, Black Sabbath and Sammy Hagar lent music to this 1981 animated epic.",
"answ":"HEAVY METAL",
"answ2":"Heavy Metal.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Jerry Goldsmith received a Best Original Score Oscar nomination for which 1979 epic sci-fi film?",
"answ":"STAR TREK THE MOTION PICTURE",
"answ2":"Star Trek: The Motion Picture.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The 2007 musical Across the Universe features songs originally performed by what band?",
"answ":"THE BEATLES",
"answ3":"BEATLES",
"answ2":"The Beatles.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Prince won an Oscar for Best Original Song Score for what 1984 film which included such hits as 'Let's Go Crazy' and 'When Doves Cry'?",
"answ":"PURPLE RAIN",
"answ2":"Purple Rain.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What 1995 comic book film skyrocketed Seal's 'Kiss From a Rose' into popularity?",
"answ":"BATMAN FOREVER",
"answ2":"Batman Forever.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The BFG, Lincoln and 2013's The Book Thief?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Adventures of Tintin?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Schindler's List?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Indiana Jones and the Temple of Doom and Indiana Jones and the Last Crusade?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Accidental Tourist, Empire of the Sun and The Witches of Eastwick?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Close Encounters of the Third Kind?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Jaws?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Blade Runner 2049?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Kung Fu Panda trilogy?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1968's Planet of the Apes?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for U.S. Marshals and Air Force One?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Saving Mr. Banks, Erin Brockovich and American Beauty?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ratatouille?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for John Carter, Tomorrowland and Jupiter Ascending?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Mission: Impossible III and Mission: Impossible - Ghost Protocol?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Dawn of the Planet of the Apes and War for the Planet of the Apes?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Zootopia and Inside Out?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the films Fantastic Mr. Fox, The Ides of March and Moonrise Kingdom?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Capricorn One, Logan's Run and Chinatown?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Innerspace, Basic Instinct and Hoosiers?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for First Blood and Rambo: First Blood Part II?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for A Fistful of Dollars and For a Few Dollars More?",
"answ":"ENNIO MORRICONE",
"answ2":"Ennio Morricone.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1996's Mission: Impossible?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1999's Sleepy Hollow?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2001's Planet of the Apes?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2010's Alice in Wonderland?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Girl on the Train, Silver Linings Playbook and American Hustle?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Fifty Shades of Grey and Fifty Shades Darker?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for for Michael Bay's The Rock?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Gladiator?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Pirates of the Caribbean: On Stranger Tides and Pirates of the Caribbean: At World's End?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the animated films Madagascar, Rango and Megamind?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Dunkirk?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Hidden Figures, 12 Years a Slave and Chappie?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Se7en?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for all three The Hobbit films?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Aliens, Red Heat and Cocoon?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the spy films Patriot Games and Clear and Present Danger?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1998's The Mask of Zorro and 2005's The Legend of Zorro?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the 2016 remake of The Magnificent Seven?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for E.T. the Extra-Terrestrial?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Raiders of the Lost Ark?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for JFK?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Hook?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Jurassic Park and The Lost World: Jurassic Park?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Home Alone and Home Alone 2: Lost in New York?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Saving Private Ryan?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Sleepers, Seven Years in Tibet and Amistad?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2005's War of the Worlds?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for A.I. Artificial Intelligence?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Indiana Jones and the Kingdom of the Crystal Skull?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2005's Munich?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What legendary western film composer composed the following 80s movies: The Mission, The Untouchables and Cinema Paradiso?",
"answ":"ENNIO MORRICONE",
"answ2":"Ennio Morricone.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The song 'Beat It' by Michael Jackson can be heard playing in the Cafe 80s in what 1989 sci-fi comedy?",
"answ":"BACK TO THE FUTURE PART II",
"answ3":"BACK TO THE FUTURE PART 2",
"answ2":"Back to the Future Part II.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for the films The Land Before Time and Willow?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for the 2019 films Dumbo and Men In Black: International?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which 1980s film famously features the song 'Oh Yeah' performed by the band Yello?",
"answ":"FERRIS BUELLER'S DAY OFF",
"answ2":"Ferris Bueller's Day Off.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In what MCU sequel is the song 'Brandy' played multiple times?",
"answ":"GUARDIANS OF THE GALAXY VOL 2",
"answ3":"GUARDIANS OF THE GALAXY 2",
"answ2":"Guardians of the Galaxy Vol 2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Disney live action film features the songs 'Ever Ever After', 'So Close' and 'True Love's Kiss'",
"answ":"ENCHANTED",
"answ2":"Enchanted.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which composer wrote the music for all 3 The Lord of the Rings films?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1994's The Lion King?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Oscar-winning composer did the music for 1978's Superman: The Movie?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the first three Harry Potter films?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who provided the score for the films A Beautiful Mind and Braveheart?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which rap/hip hop artist had his songs featured in The Amazing Spider Man 2, Divergent and Black Panther?",
"answ":"KENDRICK LAMAR",
"answ2":"Kendrick Lamar.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who sings the iconic song 'You've Got a Friend In Me' in the original Toy Story?",
"answ":"RANDY NEWMAN",
"answ2":"Randy Newman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Salma Hayek dances to the song After Dark in what 90s movie?",
"answ":"FROM DUSK TILL DAWN",
"answ2":"From Dusk Till Dawn.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2017's The Shape of Water?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Rogue One: A Star Wars Story?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who sang the theme song to the 1980 hit comedy Nine to Five?",
"answ":"DOLLY PARTON",
"answ2":"Dolly Parton.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Incredibles?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The song Raindrops Keep Fallin' on My Head was written for what classic film?",
"answ":"BUTCH CASSIDY AND THE SUNDANCE KID",
"answ2":"Butch Cassidy and the Sundance Kid.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Rocky composer Bill Conti won an Oscar in 1983 for scoring this inspirational true story.",
"answ":"THE RIGHT STUFF",
"answ2":"The Right Stuff.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer of Star Trek: The Motion Picture?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What is the name of the song the crew listens to before landing in the jungle in Predator?",
"answ":"LONG TALL SALLY",
"answ2":"Long Tall Sally.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which movie's soundtrack features a tune by it's own fictional band The Soggy Bottom Boys?",
"answ":"O BROTHER WHERE ART THOU",
"answ3":"O BROTHER WHERE ARE THOU",
"answ2":"O Brother, Where Art Thou?",
},
];
var r2Q33 = [
{
"cat":"Scores & Soundtracks",
"ques":"Kenny Loggins recorded 'Danger Zone' and what other song for Top Gun?",
"answ":"PLAYING WITH THE BOYS",
"answ2":"Playing with the Boys.",
"option":["Playing with the Boys", "I'm Alright", "Conviction of the Heart", "Forever"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Name the composer of the classic score from Rudy.",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "James Horner", "John Williams", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What band is responsible for the Rocky classic Eye of the Tiger?",
"answ":"SURVIVOR",
"answ2":"Survivor.",
"option":["Survivor", "Europe", "The Rolling Stones", "Oasis"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The Guns N' Roses song 'You Could Be Mine' is featured in what classic from the 90s?",
"answ":"TERMINATOR 2 JUDGMENT DAY",
"answ3":"TERMINATOR 2",
"answ2":"Terminator 2: Judgment Day.",
"option":["Terminator 2: Judgment Day", "Jurassic Park", "The Matrix", "Total Recall"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for Pixar's Up?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "James Horner", "Alan Silvestri", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for 2012's The Avengers?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Hans Zimmer", "James Horner", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for Interstellar?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "James Horner", "Alan Silvestri", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Up Where We Belong was a smash hit used in what 1982 film?",
"answ":"AN OFFICER AND A GENTLEMAN",
"answ2":"An Officer and a Gentleman.",
"option":["An Officer and a Gentleman", "Gandhi", "Sophie's Choice", "One from the Heart"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for 1984's The Terminator?",
"answ":"BRAD FIEDEL",
"answ2":"Brad Fiedel.",
"option":["Brad Fiedel", "John Williams", "Alan Silvestri", "Jack Nitzsche"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was the composer for 2009's Avatar?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Danny Elfman", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which song greets Bill Murray each morning in Groundhog Day?",
"answ":"I GOT YOU BABE",
"answ2":"I Got You Babe.",
"option":["I Got You Babe", "A Thousand Miles", "Lovely Day", "I Smile"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Say Anything, which song does Lloyd play on his boombox outside Diane's window?",
"answ":"IN YOUR EYES",
"answ2":"In Your Eyes.",
"option":["In Your Eyes", "Good Vibrations", "The Book of Love", "Come Together"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who recorded the theme from the 1971 movie Shaft?",
"answ":"ISAAC HAYES",
"answ2":"Isaac Hayes.",
"option":["Isaac Hayes", "Marvin Gaye", "Michael Jackson", "Stevie Wonder"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor, Rise of the Planet of the Apes and Brave?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":["Patrick Doyle", "Brian Tyler", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for 1987's Predator?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Jerry Goldsmith", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays during Jennifer Beal's training montage in Flashdance?",
"answ":"MANIAC",
"answ2":"Maniac.",
"option":["Maniac", "Never", "Fame", "Stay"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the new music for 2006's Superman Returns?",
"answ":"JOHN OTTMAN",
"answ3":"JOHN OTMAN",
"answ2":"John Ottman.",
"option":["John Ottman", "Alan Silvestri", "James Horner", "Patrick Doyle"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which 90s film had a soundtrack featuring 'Burn' by The Cure and 'Big Empty' by Stone Temple Pilots?",
"answ":"THE CROW",
"answ2":"The Crow.",
"option":["The Crow", "Reality Bites", "Mystery Men", "The Mask"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Gremlins?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Jack Nitzsche", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Hans Zimmer won his only Academy Award for Best Original Score for which film?",
"answ":"THE LION KING",
"answ3":"LION KING",
"answ2":"The Lion King.",
"option":["The Lion King", "Dunkirk", "Interstellar", "Inception"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What hit song was written and performed by R. Kelly for Space Jam?",
"answ":"I BELIEVE I CAN FLY",
"answ2":"I Believe I Can Fly.",
"option":["I Believe I Can Fly", "Bump n' Grind", "Your Body's Callin'", "The World's Greatest"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1960's The Magnificent Seven?",
"answ":"ELMER BERNSTEIN",
"answ2":"Elmer Bernstein.",
"option":["Elmer Bernstein", "Ernest Gold", "Henry Mancini", "Alex North"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What group recorded 'Don't You Forget About Me' for The Breakfast Club?",
"answ":"SIMPLE MINDS",
"answ2":"Simple Minds.",
"option":["Simple Minds", "N'Sync", "Backstreet Boys", "Take That"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Road to Perdition, Finding Nemo and Skyfall?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Patrick Doyle", "Alan Silverstri", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Lethal Weapon, Die Hard and License to Kill?",
"answ":"MICHAEL KAMEN",
"answ2":"Michael Kamen.",
"option":["Michael Kamen", "Dave Grusin", "Randy Newman", "Quincy Jones"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Guardians of the Galaxy Vol. 2, what song did Ego say was about himself and Peter's mother?",
"answ":"BRANDY",
"answ2":"Brandy.",
"option":["Brandy", "Fox On The Run", "The Chain", "Jolene"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Besides the first two Terminator films, what other James Cameron movie had it's score composed by Brad Fiedel?",
"answ":"TRUE LIES",
"answ2":"True Lies.",
"option":["True Lies", "The Abyss", "Aliens", "Avatar"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Lisa Loeb's Gen-X hit 'Stay' plays over the closing credits of what Winona Ryder movie?",
"answ":"REALITY BITES",
"answ2":"Reality Bites.",
"option":["Reality Bites", "Heathers", "Girl, Interrupted", "Mermaids"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Sam Raimi's 2001 hit Spider-Man?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Alan Silvestri", "Brian Tyler", "Henry Jackman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Back to the Future?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Danny Elfman", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who was credited as composing the score for 1982's The Thing?",
"answ":"ENNIO MORRICONE",
"answ3":"ENNIO MORICONE",
"answ2":"Ennio Morricone.",
"option":["Ennio Morricone", "John Carpenter", "John Williams", "Alan Howarth"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What famed composer was nominated at the Oscars for Best Original Score for both Little Women and The Shawkshank Redemption?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "James Horner", "Jerry Goldsmith", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2004's Troy?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Hans Zimmer", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for James Cameron's The Abyss?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Howard Shore", "Ennio Morricone", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1984's The Karate Kid?",
"answ":"BILL CONTI",
"answ2":"Bill Conti.",
"option":["Bill Conti", "John Williams", "Alan Silvestri", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1989's Glory?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Hans Zimmer", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1979's Alien?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The Hateful Eight features a track called 'Beastiality', an unused piece of music from which 1982 horror film?",
"answ":"THE THING",
"answ2":"The Thing.",
"option":["The Thing", "Aliens", "The Shining", "A Nightmare on Elm Street"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Titanic?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Michael Giacchino", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What Lord of the Rings actor wrote and performed the song 'The Last Goodbye' for the soundtrack of The Hobbit: Battle of the Five Armies?",
"answ":"BILLY BOYD",
"answ2":"Billy Boyd.",
"option":["Billy Boyd", "Elijah Wood", "Sean Astin", "Dominic Monaghan"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What musical artist created the soundtrack for Disney's Tarzan in 1999?",
"answ":"PHIL COLLINS",
"answ2":"Phil Collins.",
"option":["Phil Collins", "Elton John", "Randy Newman", "David Bowie"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which legendary composer is well-known for scores ranging from Citizen Kane to Psycho to Taxi Driver?",
"answ":"BERNARD HERRMANN",
"answ3":"BERNARD HERMANN",
"answ2":"Bernard Herrmann.",
"option":["Bernard Herrmann", "Ennio Morricone", "John Wiliams", "John Barry"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2009's Sherlock Holmes?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Michael Giacchino", "Alexandre Desplat", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"'Raindrops Keep Fallin' on My Head' was famously written for what classic film?",
"answ":"BUTCH CASSIDY AND THE SUNDANCE KID",
"answ2":"Butch Cassidy and the Sundance Kid.",
"option":["Butch Cassidy and the Sundance Kid", "Vertigo", "Psycho", "Citizen Kane"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the music for The Hunger Games?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":["James Newton Howard", "Danny Elfman", "John Carpenter", "Henry Jackman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Apollo 13?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "Ennio Morricone", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What 90s boy band performed the song 'True to Your Heart' alongside Stevie Wonder in Disney's Mulan?",
"answ":"98 DEGREES",
"answ2":"98 Degrees.",
"option":["98 Degrees", "Dream Street", "B2K", "Take That"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Scorsese films: The Aviator, The Departed ang Hugo?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "Thomas Newman", "James Horner", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1990's Total Recall?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Thomas Newman", "Alan Silvestri", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performed Back in Time from Back to the Future?",
"answ":"HUEY LEWIS",
"answ3":"HUEY LEWIS AND THE NEWS",
"answ2":"Huey Lewis and the News.",
"option":["Huey Lewis and the News", "Eric Clapton", "Etta James", "Marvin Berry & The Starlighters"],
},
{
"cat":"Scores & Soundtracks",
"ques":"For what film did Italian composer Ennio Morricone win his first Oscar for Best Original Score?",
"answ":"THE HATEFUL EIGHT",
"answ3":"HATEFUL EIGHT",
"answ2":"The Hateful Eight.",
"option":["The Hateful Eight", "The Mission", "The Good the Bad and the Ugly", "Once Upon a Time in the West"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score to Pixar's WALL-E?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Alan Silvestri", "Howard Shore", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Baby Driver, Baby's 'killer track' is from what 1970s rock band?",
"answ":"QUEEN",
"answ2":"Queen.",
"option":["Queen", "The Who", "The Rolling Stones", "Pink Floyd"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The scores from The Terminator, Fright Night and True Lies were all composed by whom?",
"answ":"BRAD FIEDEL",
"answ2":"Brad Fiedel.",
"option":["Brad Fiedel", "James Newton Howard", "John Williams", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who wrote the soundtrack for Escape from New York?",
"answ":"JOHN CARPENTER",
"answ2":"John Carpenter.",
"option":["John Carpenter", "Jerry Goldsmith", "Basil Poledouris", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Goodfellas, what song plays during the iconic long tracking shot of Henry and Karen entering the Copacabana?",
"answ":"THEN HE KISSED ME",
"answ2":"Then He Kissed Me.",
"option":["Then He Kissed Me", "Rag to Riches", "Baby, I Love You", "Layla"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the J.J. Abrams directed Super 8?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Trevor Rabin", "Alan Silvestri", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which actress sings Can't Take My Eyes Off of You to Jesus on a cross for her pageant talent in Drop Dead Gorgeous?",
"answ":"DENISE RICHARDS",
"answ2":"Denise Richards.",
"option":["Denise Richards", "Kirsten Dunst", "Amy Adams", "Brittany Murphy"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Amazing Spider-Man 2?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Howard Shore", "Alan Silvestri", "Junkie XL"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Aerosmith, Alice Cooper, ZZ Top and Ted Nugent all provide songs for what 1993 comedy?",
"answ":"DAZED AND CONFUSED",
"answ2":"Dazed and Confused.",
"option":["Dazed and Confused", "Hot Shots! Part Deux", "Wayne's World 2", "Groundhog Day"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Commando?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Howard Shore", "Jerry Goldsmith", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Zero Dark Thirty?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "Michael Giacchino", "Danny Elfman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Eye of the Tiger first appeared in which Rocky film?",
"answ":"ROCKY 3",
"answ3":"ROCKY III",
"answ2":"Rocky 3.",
"option":["Rocky 3", "Rocky", "Rocky 2", "Rocky 4"],
},
{
"cat":"Scores & Soundtracks",
"ques":"M.I.A.'s song Paper Planes appears in what Danny Boyle film?",
"answ":"SLUMDOG MILLIONAIRE",
"answ2":"Slumdog Millionaire.",
"option":["Slumdog Millionaire", "Trainspotting", "Sunshine", "127 Hours"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Lesley Barber composed the score to what 2016 film that was later nominated for a Best Picture Oscar?",
"answ":"MANCHESTER BY THE SEA",
"answ2":"Manchester By The Sea.",
"option":["Manchester By The Sea", "Lion", "Hidden Figures", "Hacksaw Ridge"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Coen Brothers film is known for the song 'I Am a Man of Constant Sorrow'?",
"answ":"O BROTHER WHERE ART THOU",
"answ2":"O Brother, Where Art Thou?.",
"option":["O Brother, Where Art Thou?", "Fargo", "True Grit", "The Ladykillers"],
},

{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Memoirs of a Geisha?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Ennio Morricone", "James Horner", "Bernard Herrmann"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1999's Angela's Ashes and 1998's Stepmom?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Howard Shore", "James Horner", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1997's Rosewood?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Howard Shore", "Danny Elfman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for the 1995 films Nixon and Sabrina?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Howard Shore", "Danny Elfman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Far and Away?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Hans Zimmer", "Howard Shore", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1989's Always?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Ennio Morricone", "Hans Zimmer", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Jaws 2?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Hans Zimmer", "Howard Shore", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Towering Inferno, The Sugarland Express and 1941?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Ennio Morricone", "Howard Shore", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Southpaw and 2010's The Karate Kid?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "John Williams", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Spiderwick Chronicles?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "Howard Shore", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Apocalypto, Radio, Windtalkers and House of Sand and Fog?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "Howard Shore", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Perfect Storm, Deep Impact and Enemy at the Gates?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Bicentennial Man, Mighty Joe Young and The Devil's Own?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1996's Ranson?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Ennio Morricone", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the 1995's Casper and 1994's The Pagemaster?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Ennio Morricone", "John Williams", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Pelican Brief?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Howard Shore", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the animated films Balto and We're Back! A Dinosaur Story?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Howard Shore", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Rocketeer?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "John Williams", "Howard Shore", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Honey, I Shrunk the Kids?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "John Williams", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Jumanji, Field of Dreams and Legends of the Fall?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "John Williams", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for An American Tail?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "John Williams", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 48 Hrs.?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Hans Zimmer", "Jerry Goldsmith", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Oscar winning film Spotlight?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "Hans Zimmer", "James Horner", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Twilight Saga: Eclipse?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "Alan Silvestri", "James Horner", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Panic Room, A History of Violence and High Fidelity?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "John Williams", "James Horner", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1997's Cop Land?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "John Williams", "Hans Zimmer", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Mrs. Doubtfire?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "John Williams", "Hans Zimmer", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ron Howard's Rush?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Howard Shore", "Thomas Newman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2013's The Lone Ranger?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Howard Shore", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Holiday, Invincible and Frost/Nixon?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Thomas Newman", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Pirates of the Caribbean: Dead Man's Chest?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Danny Elfman", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Black Hawk Down, Pearl Harbor and 2004's King Arthur?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Danny Elfman", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Mission: Impossible II?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "Jerry Goldsmith", "Thomas Newman", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Road to El Dorado, The Thin Red Line and Hannibal?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "John Williams", "Thomas Newman", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Prince of Egypt?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "John Williams", "Thomas Newman", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for True Romance, The Preacher's Wife and Crimson Tide?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "John Williams", "Danny Elfman", "Thomas Newman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for A League of Their Own, Thelma & Louise and Muppet Treasure Island?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
"option":["Hans Zimmer", "John Williams", "Danny Elfman", "Thomas Newman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Goosebumps?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "John Williams", "Thomas Newman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Oz the Great and Powerful?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "John Williams", "Hans Zimmer", "Thomas Newman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Real Steel?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Hans Zimmer", "Thomas Newman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Terminator Salvation?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Christopher Young", "Thomas Newman", "Bernard Herrmann"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2007's The Kingdom?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Christopher Young", "Thomas Newman", "Bernard Herrmann"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the animated films Meet the Robinsons and Mr. Peabody & Sherman?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Michael Giacchino", "Thomas Newman", "Bernard Herrmann"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2006's Charlotte's Web?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Michael Giacchino", "Thomas Newman", "Bernard Herrmann"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Red Dragon?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "John Williams", "Hans Zimmer", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spy Kids?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "John Williams", "Hans Zimmer", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Good Will Hunting?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Alan Silvestri", "John Williams", "Thomas Newman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1994's Black Beauty?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Alan Silvestri", "Hans Zimmer", "Christopher Young"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Midnight Run?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Alan Silvestri", "Ennio Morricone", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1962's Cape Fear?",
"answ":"BERNARD HERRMANN",
"answ2":"Bernard Herrmann.",
"option":["Bernard Herrmann", "Jerry Goldsmith", "Ennio Morricone", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Finding Dory?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Michael Giacchino", "Jerry Goldsmith", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spectre?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Michael Giacchino", "Jerry Goldsmith", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Iron Lady, The Help and The Adjustment Bureau?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Hans Zimmer", "Jerry Goldsmith", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Phenomenon, The Horse Whisperer and Meet Joe Black?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Hans Zimmer", "Jerry Goldsmith", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1987's The Lost Boys?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
"option":["Thomas Newman", "Hans Zimmer", "Jerry Goldsmith", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Looney Tunes: Back in Action?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Hans Zimmer", "Thomas Newman", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Sum of All Fears?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Hans Zimmer", "Thomas Newman", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Hollow Man, The 13th Warrior and 1999's The Mummy?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Hans Zimmer", "Thomas Newman", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1998's Small Soldiers?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Christopher Young", "Thomas Newman", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1998's Mulan?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Christopher Young", "Thomas Newman", "Alexandre Desplat"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Ghost and the Darkness?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the films Congo, First Knight and The River Wild?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the 1994 western Bad Girls?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Dennis the Menace?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alan Silvestri", "Thomas Newman", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1992's Forever Young?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alan Silvestri", "Thomas Newman", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Gremlins 2: The New Batch?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alan Silvestri", "Thomas Newman", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Rambo III?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Howard Shore", "Thomas Newman", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Secret of NIMH?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Sand Pebbles?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "Alexandre Desplat", "Thomas Newman", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Golden Compass?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Curious Case of Benjamin Button?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Twilight Saga: New Moon?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The King's Speech?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Argo and The Imitation Game?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the 2012 animated film Rise of the Guardians?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2014's Godzilla?",
"answ":"ALEXANDRE DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "John Williams", "Michael Giacchino", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Jurassic World?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "Alexandre Desplat", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Which movie soundtrack includes the song 'I Just Can't Wait to Be King'?",
"answ2":"The Lion King.",
"answ":"THE LION KING",
"option":["The Lion King","Aladdin","Cinderella","Bambi"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In 2001: A Space Odyssey, what song did supercomputer HAL-9000 sing as he was being deactivated?",    
"answ":"DAISY BELL",
"answ2":"Daisy Bell.",
"option":["Daisy Bell","Danny Boy","Rock-a-Bye, Baby","East Side, West Side"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2009's Land of the Lost?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "Alexandre Desplat", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Speed Racer?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "Alexandre Desplat", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2005's Sky High?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "John Williams", "Alexandre Desplat", "Howard Shore"],
},
];
scoressoundtracks = shuffle(scoressoundtracks);
r2Q33 = shuffle(r2Q33);