var tomhanks = [
{
"cat":"Tom Hanks",
"ques":"Tom Hanks directed two feature films. Name one of them.",
"answ":"LARRY CROWNE",
"answ3":"THAT THING YOU DO",
"answ2":"Larry Crowne/That Thing You Do!.",
},
{
"cat":"Tom Hanks",
"ques":"Which Oscar-winning actress plays Tom Hanks' girlfriend Kelly in Cast Away?",
"answ":"HELEN HUNT",
"answ2":"Helen Hunt.",
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks starred in, directed and wrote what 1996 film that also has Tom Everett Scott, Liv Tyler and Steve Zahn?",
"answ":"THAT THING YOU DO",
"answ2":"That Thing You Do.",
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks stars alongside John Boyega and Emma Watson in what film?",
"answ":"THE CIRCLE",
"answ2":"The Circle.",
},
{
"cat":"Tom Hanks",
"ques":"What 1984 comedy marked the first collaboration between Tom Hanks and director Ron Howard?",
"answ":"SPLASH",
"answ2":"Splash.",
},
{
"cat":"Tom Hanks",
"ques":"What was the first film that Tom Hanks appeared in as Robert Langdon?",
"answ":"THE DA VINCI CODE",
"answ3":"DA VINCI CODE",
"answ2":"The Da Vinci Code.",
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks and Meg Ryan star in what romantic comedy released in 1990?",
"answ":"JOE VERSUS THE VOLCANO",
"answ2":"Joe Versus the Volcano.",
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks portrayed Harvard symbologist Robert Langdon in how many films?",
"answ":"THREE",
"answ3":"3",
"answ2":"3.",
},
{
"cat":"Tom Hanks",
"ques":"In Cast Away, what is on the FedEx box that Tom Hanks never opens?",
"answ":"PAIR OF WINGS",
"answ3":"WINGS",
"answ2":"Pair of wings.",
},
{
"cat":"Tom Hanks",
"ques":"Who directed Cast Away?",
"answ":"ROBERT ZEMECKIS",
"answ2":"Robert Zemeckis.",
},
{
"cat":"Tom Hanks",
"ques":"Outside of the Robert Langdon films, Tom Hanks has played the same character more than once in one other franchise. What franchise is that?",
"answ":"TOY STORY",
"answ2":"Toy Story.",
},
{
"cat":"Tom Hanks",
"ques":"Who played Tom Hanks' love interest in You've Got Mail?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Tom Hanks",
"ques":"Who directed Tom Hanks in Big?",
"answ":"PENNY MARSHALL",
"answ2":"Penny Marshall.",
},
{
"cat":"Tom Hanks",
"ques":"Amongst other roles Tom played a doctor, a hotel manager and a ruthless author in which 2012 film?",
"answ":"CLOUD ATLAS",
"answ2":"Cloud Atlas.",
},
{
"cat":"Tom Hanks",
"ques":"What was the first movie for which Tom Hanks won an Academy Award for acting?",
"answ":"PHILADELPHIA",
"answ2":"Philadelphia.",
},
];
var r2Q34 = [
{
"cat":"Tom Hanks",
"ques":"In what year did Tom Hanks star in The Terminal, The Ladykillers and The Polar Express?",
"answ":"2004",
"answ2":"2004.",
"option":["2004", "2002", "2003", "2001"],
},
{
"cat":"Tom Hanks",
"ques":"Who stars alongside Tom Hanks as gifted inmate John Coffey in The Green Mile?",
"answ":"MICHAEL CLARKE DUNCAN",
"answ3":"MICHAEL CLARK DUNCAN",
"answ2":"Michael Clarke Duncan.",
"option":["Michael Clarke Duncan", "Laurence Fishburne", "Morgan Freeman", "Ving Rhames"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks starred alongside Halle Berry, Jim Broadbent and Hugo Weaving in what film?",
"answ":"CLOUD ATLAS",
"answ2":"Cloud Atlas.",
"option":["Cloud Atlas", "The Ladykillers", "The Da Vinci Code", "Charlie Wilson's War"],
},
{
"cat":"Tom Hanks",
"ques":"What company did Tom Hanks' character Chuck Noland work for in Cast Away?",
"answ":"FEDEX",
"answ2":"FedEx.",
"option":["FedEx", "Amazon", "UPS", "DHL"],
},
{
"cat":"Tom Hanks",
"ques":"In which film does Tom Hanks play the character Jimmy Dugan?",
"answ":"A LEAGUE OF THEIR OWN",
"answ2":"A League of Their Own.",
"option":["A League of Their Own", "You've Got Mail", "Cloud Atlas", "Bridge of Spies"],
},
{
"cat":"Tom Hanks",
"ques":"What was the name of the mouse in The Green Mile?",
"answ":"MR JINGLES",
"answ3":"MISTER JINGLES",
"answ2":"Mr. Jingles.",
"option":["Mr. Jingles", "Milfred", "Timothy", "Mr. Hankey"],
},
{
"cat":"Tom Hanks",
"ques":"Name the first film that featured Tom Hanks and Meg Ryan in leading roles.",
"answ":"JOE VERSUS THE VOLCANO",
"answ2":"Joe Versus the Volcano.",
"option":["Joe Versus the Volcano", "You've Got Mail", "Sleepless in Seattle", "The Money Pit"],
},
{
"cat":"Tom Hanks",
"ques":"Who plays the scientist who proves Madison is a mermaid by splashing her with water in Splash?",
"answ":"EUGENE LEVY",
"answ3":"EUGENE LEVI",
"answ2":"Eugene Levy.",
"option":["Eugene Levy", "Tom Hanks", "John Candy", "Kevin Bacon"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed Tom Hanks in the 1980's comedy Splash?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":["Ron Howard", "Robert Zemeckis", "Richard Benjamin", "Penny Marshall"],
},
{
"cat":"Tom Hanks",
"ques":"What was the first film that Tom Hanks directed?",
"answ":"THAT THING YOU DO",
"answ2":"That Thing You Do.",
"option":["That Thing You Do", "Larry Crowne", "You've Got Mail", "The Great Buck Howard"],
},
{
"cat":"Tom Hanks",
"ques":"For what film did Tom Hanks receive his second Best Actor Oscar win?",
"answ":"FORREST GUMP",
"answ2":"Forrest Gump.",
"option":["Forrest Gump", "Philadelphia", "Saving Private Ryan", "Cast Away"],
},
{
"cat":"Tom Hanks",
"ques":"What is the last name of Tom Hanks dentist in Cast Away?",
"answ":"SPALDING",
"answ2":"Spalding.",
"option":["Spalding", "Wilson", "Vault", "Smith"],
},
{
"cat":"Tom Hanks",
"ques":"What is Tom Hanks character's job in Road to Perdition?",
"answ":"HITMAN",
"answ3":"ASSASSIN",
"answ2":"Hitman/Assassin.",
"option":["Hitman", "Weatherman", "Teacher", "Baker"],
},
{
"cat":"Tom Hanks",
"ques":"What is the name of the toy company where Tom Hanks works for in Big?",
"answ":"MACMILLEN",
"answ3":"MCMILLEN",
"answ2":"MacMillen.",
"option":["MacMillen", "Wonderworld", "Zoltars", "Thompson"],
},
{
"cat":"Tom Hanks",
"ques":"Who played the father of author P.L. Travers in Saving Mr. Banks?",
"answ":"COLUB FARRELL",
"answ2":"Colin Farrell.",
"option":["Colin Farrell", "Bradley Whitford", "Paul Giamatti", "B. J. Novak"],
},
{
"cat":"Tom Hanks",
"ques":"Which actress played Jim Lovell's wife Marilyn in Apollo 13?",
"answ":"KATHLEEN QUINLAN",
"answ2":"Kathleen Quinlan.",
"option":["Kathleen Quinlan", "Amy Madigan", "Annette Bening", "Rita Wilson"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed Tom Hanks in the 1990 film The Bonfire Of The Vanities?",
"answ":"BRIAN DE PALMA",
"answ2":"Brian De Palma.",
"option":["Brian De Palma", "Ron Howard", "Roger Spottiswoode", "Richard Donner"],
},
{
"cat":"Tom Hanks",
"ques":"In what movie did Carrie Fisher play Tom Hanks' wife?",
"answ":"THE BURBS",
"answ3":"THE 'BURBS",
"answ2":"The 'Burbs.",
"option":["The 'Burbs", "The Man with One Red Shoe", "The Green Mile", "The Bonfire of the Vanities"],
},
{
"cat":"Tom Hanks",
"ques":"In what film does Tom Hanks yell 'You are a child's plaything!'?",
"answ":"TOY STORY",
"answ2":"Toy Story.",
"option":["Toy Story", "Cars", "The Polar Express", "Toy Story 2"],
},
{
"cat":"Tom Hanks",
"ques":"Forrest keens a copy of what children's book in his briefcase in the film Forrest Gump?",
"answ":"CURIOUS GEORGE",
"answ2":"Curious George.",
"option":["Curious George", "Goodnight Moon", "Where the Wild Things Are", "Berenstain Bears"],
},
{
"cat":"Tom Hanks",
"ques":"What 90s Elijah Wood film saw Tom Hanks serve as the film's narrator?",
"answ":"RADIO FLYER",
"answ2":"Radio Flyer.",
"option":["Radio Flyer", "Paradise", "Avalon", "Forever Young"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks plays a detective in this 1987 film based on a TV series of the same name.",
"answ":"DRAGNET",
"answ2":"Dragnet.",
"option":["Dragnet", "Turner & Hooch", "Punchline", "The 'Burbs"],
},
{
"cat":"Tom Hanks",
"ques":"What subject did Tom Hanks's character teach before the war in Saving Private Ryan?",
"answ":"ENGLISH",
"answ2":"English.",
"option":["English", "Science", "Math", "History"],
},
{
"cat":"Tom Hanks",
"ques":"Forrest Gump played football at what university?",
"answ":"ALABAMA",
"answ2":"Alabama.",
"option":["Alabama", "Florida", "Tennessee", "Auburn"],
},
{
"cat":"Tom Hanks",
"ques":"In Saving Mr. Banks, Tom Hanks played what famous figure?",
"answ":"WALT DISNEY",
"answ2":"Walt Disney.",
"option":["Walt Disney", "Alfred Hitchcock", "Fred Rogers", "Dick Van Dyke"],
},
{
"cat":"Tom Hanks",
"ques":"Who plays Tom Hanks's wife in the comedy The 'Burbs?",
"answ":"CARRIE FISHER",
"answ3":"CARRY FISHER",
"answ2":"Carrie Fisher.",
"option":["Carrie Fisher", "Shelley Long", "Elizabeth Perkins", "Meg Ryan"],
},
{
"cat":"Tom Hanks",
"ques":"How many times has Tom Hanks been nominated for an Acting Oscar?",
"answ":"SIX",
"answ3":"6",
"answ2":"6.",
"option":["6", "5", "4", "3"],
},
{
"cat":"Tom Hanks",
"ques":"In Sleepless in Seattle, what film did Tom Hanks say scared every man in America?",
"answ":"FATAL ATTRACTION",
"answ2":"Fatal Attraction.",
"option":["Fatal Attraction", "Whatever happened to Baby Jane?", "Basic Instinct", "Body Heat"],
},
{
"cat":"Tom Hanks",
"ques":"Sally Field co-starred with Tom Hanks in Forrest Gump. They also shared the screen in what 80s comedy?",
"answ":"PUNCHLINE",
"answ2":"Punchline.",
"option":["Punchline", "Bonfire of the Vanities", "From Earth to the Moon", "The Burbs"],
},
{
"cat":"Tom Hanks",
"ques":"Apollo 13 was released in what year?",
"answ":"1995",
"answ2":"1995.",
"option":["1995", "1993", "1994", "1996"],
},
{
"cat":"Tom Hanks",
"ques":"What movie did Lori Singer co-star with Tom Hanks?",
"answ":"THE MAN WITH ONE RED SHOE",
"answ3":"MAN WITH ONE RED SHOE",
"answ2":"The Man with One Red Shoe.",
"option":["The Man with One Red Shoe", "Splash", "Big", "Radio Flyer"],
},
{
"cat":"Tom Hanks",
"ques":"In That Thing You Do, Mr. White worked for what record label?",
"answ":"PLAY TONE",
"answ3":"PLAYTONE",
"answ2":"Play-Tone.",
"option":["Play-Tone", "A&G", "StarMaker", "Sunset 45"],
},
{
"cat":"Tom Hanks",
"ques":"In which movie did Bruce Willis co-star with Tom Hanks?",
"answ":"BONFIRE OF THE VANITIES",
"answ2":"Bonfire of the Vanities.",
"option":["Bonfire of the Vanities", "Saving Private Ryan", "Nothing in Common", "The Green Mile"],
},
{
"cat":"Tom Hanks",
"ques":"Jim Belushi co-starred with Tom Hanks in which movie?",
"answ":"THE MAN WITH ONE RED SHOE",
"answ3":"MAN WITH ONE RED SHOE",
"answ2":"The Man with One Red Shoe.",
"option":["The Man with One Red Shoe", "Dragnet", "Bachelor Party", "Punchline"],
},
{
"cat":"Tom Hanks",
"ques":"Who played Miguel Alvarez in Philadelphia?",
"answ":"ANTONIO BANDERAS",
"answ2":"Antonio Banderas.",
"option":["Antonio Banderas", "Michael Peña", "Andy Garcia", "Emilio Estevez"],
},
{
"cat":"Tom Hanks",
"ques":"Emma Watson co-starred with Tom Hanks in which movie?",
"answ":"THE CIRCLE",
"answ2":"The Circle.",
"option":["The Circle", "Sully", "A Hologram for the King", "The Post"],
},
{
"cat":"Tom Hanks",
"ques":"Who played, Pamela Travers, the author of Mary Poppins, in Saving Mr. Banks?",
"answ":"EMMA THOMPSON",
"answ2":"Emma Thompson.",
"option":["Emma Thompson", "Meryl Streep", "Judi Dench", "Kate Winslet"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed 2016's Inferno?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":["Ron Howard", "James Ponsoldt", "Paul Greengrass", "Sam Mendes"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks had a small voice role in what 2006 Pixar movie?",
"answ":"CARS",
"answ2":"Cars.",
"option":["Cars", "Ratatouille", "WALL-E", "The Incredibles"],
},
{
"cat":"Tom Hanks",
"ques":"What famous child actor played Forrest Gump's son in 1994's Forrest Gump?",
"answ":"HALEY JOEL OSMENT",
"answ2":"Haley Joel Osment.",
"option":["Haley Joel Osment", "Macaulay Culkin", "Jake Lloyd", "Edward Furlong"],
},
{
"cat":"Tom Hanks",
"ques":"What was the first movie to pair Tom Hanks and Sally Field as co-stars?",
"answ":"PUNCHLINE",
"answ3":"PUNCH LINE",
"answ2":"Punchline.",
"option":["Punchline", "Montana", "New Mexico", "Oregon"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks and Aaron Eckhart star together in what 2016 Clint Eastwood film?",
"answ":"SULLY",
"answ2":"Sully.",
"option":["Sully", "American Sniper", "The 15:17 to Paris", "The Mule"],
},
{
"cat":"Tom Hanks",
"ques":"Which actress starred opposite Tom Hanks in The Money Pit?",
"answ":"SHELLEY LONG",
"answ3":"SHELLY LONG",
"answ2":"Shelley Long.",
"option":["Shelley Long", "Rita Wilson", "Meg Ryan", "Kim Basinger"],
},
{
"cat":"Tom Hanks",
"ques":"In what Hanks film will you see him dealing with neighbors with the last name Klopek?",
"answ":"THE BURBS",
"answ3":"THE 'BURBS",
"answ2":"The 'Burbs.",
"option":["The 'Burbs", "The Money Pit", "Philadelphia", "The Man with One Red Shoe"],
},
{
"cat":"Tom Hanks",
"ques":"Who played the foul-mouthed, hot-headed janitor Gawain MacSam in 2004's The Ladykillers?",
"answ":"MARLON WAYANS",
"answ2":"Marlon Wayans.",
"option":["Marlon Wayans", "J.K. Simmons", "Damon Wayans", "George Wallace"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks plays the character of John Miller in what 90s film?",
"answ":"SAVING PRIVATE RYAN",
"answ2":"Saving Private Ryan.",
"option":["Saving Private Ryan", "Apollo 13", "Sleepless in Seattle", "The Green Mile"],
},
{
"cat":"Tom Hanks",
"ques":"Who played Bishop Aringarosa in The Da Vinci Code?",
"answ":"ALFRED MOLINA",
"answ2":"Alfred Molina.",
"option":["Alfred Molina", "Ian McKellen", "Paul Bettany", "Ewan McGregor"],
},
{
"cat":"Tom Hanks",
"ques":"Other than That Thing You Do, what movie has Steve Zahn co-starred in with Tom Hanks?",
"answ":"YOU'VE GOT MAIL",
"answ2":"You've Got Mail.",
"option":["You've Got Mail", "Sleepless in Seattle", "Catch Me If You Can", "Big"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed Tom Hanks in The Terminal?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
"option":["Steven Spielberg", "Robert Zemeckis", "John Landis", "Harold Ramis"],
},
{
"cat":"Tom Hanks",
"ques":"In what 2014 film does Tom Hanks play a real-life airline pilot who makes a miracle landing on the Hudson river?",
"answ":"SULLY",
"answ2":"Sully.",
"option":["Sully", "Larry Crowne", "Ithaca", "Flight"],
},
{
"cat":"Tom Hanks",
"ques":"What is the profession of Tom Hanks' character in 1993's Philadelphia?",
"answ":"LAWYER",
"answ2":"Lawyer.",
"option":["Lawyer", "Doctor", "Accountant", "Architect"],
},
{
"cat":"Tom Hanks",
"ques":"Who plays Frank Navasky, a newspaper writer for The New York Observer, in You've Got Mail?",
"answ":"GREG KINNEAR",
"answ3":"GREG KINEAR",
"answ2":"Greg Kinnear.",
"option":["Greg Kinnear", "Steve Zahn", "Bill Pullman", "Billy Crystal"],
},
{
"cat":"Tom Hanks",
"ques":"Frank Darabont directed Tom Hanks in which 1999 drama?",
"answ":"THE GREEN MILE",
"answ3":"GREEN MILE",
"answ2":"The Green Mile.",
"option":["The Green Mile", "Cast Away", "You've Got Mail", "Apollo 13"],
},
{
"cat":"Tom Hanks",
"ques":"In the 2016 film A Hologram for the King, Tom Hanks goes to which country to sell holographic communications technology?",
"answ":"SAUDI ARABIA",
"answ2":"Saudi Arabia.",
"option":["Saudi Arabia", "Norway", "Spain", "Qatar"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed Tom Hanks in the 2017 techno thriller The Circle?",
"answ":"JAMES PONSOLDT",
"answ3":"JAMES PONSOLD",
"answ2":"James Ponsoldt.",
"option":["James Ponsoldt", "Tom Hanks", "Tom Tykwer", "Marc Webb"],
},
{
"cat":"Tom Hanks",
"ques":"Captain Phillips starring Tom Hanks was released in what year?",
"answ":"2013",
"answ2":"2013.",
"option":["2013", "2015", "2010", "2012"],
},
{
"cat":"Tom Hanks",
"ques":"Who directed Charlie Wilson's War starring Tom Hanks?",
"answ":"MIKE NICHOLS",
"answ2":"Mike Nichols.",
"option":["Mike Nichols", "Ron Howard", "Tom Hanks", "Michael Mann"],
},
{
"cat":"Tom Hanks",
"ques":"What was the name of the real life astronaut played by Tom Hanks in the 1995 film Apollo 13?",
"answ":"JIM LOVELL",
"answ2":"Jim Lovell.",
"option":["Jim Lovell", "Fred Haise", "Jack Swigert", "Ken Mattingly"],
},
{
"cat":"Tom Hanks",
"ques":"In You've Got Mail, Meg Ryan claims she's read which book 'about 100 times'?",
"answ":"PRIDE AND PREJUDICE",
"answ2":"Pride and Prejudice.",
"option":["Pride and Prejudice", "Gone with the Wind", "The Princess Bride", "The Notebook"],
},
{
"cat":"Tom Hanks",
"ques":"Who played the photography-obsessed assassin hunting Tom Hanks in the 2002 film Road to Perdition?",
"answ":"JUDE LAW",
"answ2":"Jude Law.",
"option":["Jude Law", "Daniel Craig", "Michael Fassbender", "Jake Gyllenhaal"],
},
{
"cat":"Tom Hanks",
"ques":"Which actor played Tom Hanks' son in the 2008 film The Great Buck Howard?",
"answ":"COLIN HANKS",
"answ2":"Colin Hanks.",
"option":["Colin Hanks", "Anton Yelchin", "Zac Efron", "Heath Ledger"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks made his feature film debut in which 1980 horror movie?",
"answ":"HE KNOWS YOU'RE ALONE",
"answ2":"He Knows You're Alone.",
"option":["He Knows You're Alone", "The Fog", "Friday the 13th", "Humanoids from the Deep"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks plays scheming Professor Goldthwaite Higginson Dorr in which 2004 film?",
"answ":"THE LADYKILLERS",
"answ2":"The Ladykillers.",
"option":["The Ladykillers", "Cloud Atlas", "Lemony Snicket's A Series of Unfortunate Events", "I Heart Huckabees"],
},
{
"cat":"Tom Hanks",
"ques":"What was the name of the character played by Tom Hanks in the 2006 film The Da Vinci Code?",
"answ":"ROBERT LANGDON",
"answ2":"Robert Langdon.",
"option":["Robert Langdon", "Chuck Noland", "Jim Lovell", "Joe"],
},
{
"cat":"Tom Hanks",
"ques":"In the 1993 film Sleepless in Seattle, Tom Hanks gets very emotional while describing which classic war movie?",
"answ":"THE DIRTY DOZEN",
"answ3":"DIRTY DOZEN",
"answ2":"The Dirty Dozen.",
"option":["The Dirty Dozen", "All Quiet on the Western Front", "Hell is for Heroes", "The Longest Day"],
},
{
"cat":"Tom Hanks",
"ques":"In which film does Tom Hanks play a Wall Street trader who gets involved in a hit-and-run accident?",
"answ":"THE BONFIRE OF THE VANITIES",
"answ3":"BONFIRE OF THE VANITIES",
"answ2":"The Bonfire of the Vanities.",
"option":["The Bonfire of the Vanities", "Changing Lanes", "Volunteers", "Nothing in Common"],
},
{
"cat":"Tom Hanks",
"ques":"What was Tom Hanks studying in college before he decided to become a stand-up comedian in the 1988 film Punchline?",
"answ":"MEDICINE",
"answ2":"Medicine.",
"option":["Medicine", "Philosophy", "Architecture", "Accounting"],
},
{
"cat":"Tom Hanks",
"ques":"In which 1987 comedy does Tom Hanks raid a milk factory, fight a giant snake and torture someone with a drawer?",
"answ":"DRAGNET",
"answ2":"Dragnet.",
"option":["Dragnet", "Volunteers", "Outrageous Fortune", "Bachelor Party"],
},
{
"cat":"Tom Hanks",
"ques":"Which actress plays Tom Hanks' widow in the 2011 film Extremely Loud & Incredibly Close?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
"option":["Sandra Bullock", "Viola Davis", "Meryl Streep", "Diane Lane"],
},
{
"cat":"Tom Hanks",
"ques":"Tom Hanks plays a traveler by the name of Viktor Navorski in what 2004 film?",
"answ":"THE TERMINAL",
"answ2":"The Terminal.",
"option":["The Terminal", "The Ladykillers", "Catch Me if You Can", "Cast Away"],
},
{
"cat":"Tom Hanks",
"ques":"Who plays alcoholic journalist Peter Farrow in The Bonfire of the Vanities?",
"answ":"BRUCE WILLIS",
"answ2":"Bruce Willis.",
"option":["Bruce Willis", "Morgan Freeman", "Jim Belushi", "Dan Aykroyd"],
},
];
tomhanks = shuffle(tomhanks);
r2Q34 = shuffle(r2Q34);