var war = [
{
"cat":"War",
"ques":"Name one of the two major films released in 1998 that competed against each other at the Oscars for Best Picture?",
"answ":"THE THIN RED LINE",
"answ3":"SAVING PRIVATE RYAN",
"answ2":"The Thin Red Line/Saving Private Ryan.",
},
{
"cat":"War",
"ques":"Who directed the Mark Wahlberg war film Lone Survivor?",
"answ":"PETER BERG",
"answ2":"Peter Berg.",
},
{
"cat":"War",
"ques":"Who directed the 1987 film Empire of the Sun?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"War",
"ques":"Who starred as Jed in the 1984 war film Red Dawn?",
"answ":"PATRICK SWAYZE",
"answ2":"Patrick Swayze.",
},
{
"cat":"War",
"ques":"What 2001 war film features a huge ensemble cast including Ewan McGregor, Eric Bana, Orlando Bloom and Josh Hartnett?",
"answ":"BLACK HAWK DOWN",
"answ2":"Black Hawk Down.",
},
{
"cat":"War",
"ques":"Who directed The Thin Red Line?",
"answ":"TERRENCE MALICK",
"answ2":"Terrence Malick.",
},
{
"cat":"War",
"ques":"Who plays Colonel Nicholson in the war film The Bridge On the River Kwai?",
"answ":"ALEC GUINNESS",
"answ2":"Alec Guinness.",
},
{
"cat":"War",
"ques":"Which famous singer played the soldier Alex in Dunkirk?",
"answ":"HARRY STYLES",
"answ2":"Harry Styles.",
},
{
"cat":"War",
"ques":"Charlie Sheen, Willem Dafoe and Forest Whitaker star together in what 1986 war film?",
"answ":"PLATOON",
"answ2":"Platoon.",
},
{
"cat":"War",
"ques":"What film adapted from a Mark Bowden book depicted the Battle of Mogadishu?",
"answ":"BLACK HAWK DOWN",
"answ2":"Black Hawk Down.",
},
{
"cat":"War",
"ques":"Who played the lead in American Sniper?",
"answ":"BRADLEY COOPER",
"answ2":"Bradley Cooper.",
},
{
"cat":"War",
"ques":"Who directed Platoon?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
},
{
"cat":"War",
"ques":"Denzel Washington won a Best Supporting Actor Oscar in 1989 for his role in what war movie?",
"answ":"GLORY",
"answ2":"Glory.",
},
{
"cat":"War",
"ques":"Alec Guiness and William Holden star in what film about POW's forced to build a bridge in Burma?",
"answ":"THE BRIDGE ON THE RIVER KWAI",
"answ3":"BRIDGE ON THE RIVER KWAI",
"answ2":"The Bridge on the River Kwai.",
},
{
"cat":"War",
"ques":"Who played Colonel Claus von Stauffenberg in Valkyrie?",
"answ":"TOM CRUISE",
"answ2":"Tom Cruise.",
},
{
"cat":"War",
"ques":"Who directed Tom Cruise in the war thriller Valkyrie?",
"answ":"BRYAN SINGER",
"answ2":"Bryan Singer.",
},
{
"cat":"War",
"ques":"In which war do the events of the film Fury take place?",
"answ":"WORLD WAR II",
"answ3":"WORLD WAR 2",
"answ2":"World War II.",
},
{
"cat":"War",
"ques":"Which Terrence Malick film was released the same year as Saving Private Ryan and also centered around World War II?",
"answ":"THE THIN RED LINE",
"answ3":"THIN RED LINE",
"answ2":"The Thin Red Line.",
},
{
"cat":"War",
"ques":"The Great Escape takes place during which war?",
"answ":"WORLD WAR II",
"answ3":"WORLD WAR 2",
"answ2":"World War II.",
},
];
var r2Q35 = [
{
"cat":"War",
"ques":"During which war do the events of 2007's Rescue Dawn, starring Christian Bale, take place?",
"answ":"VIETNAM WAR",
"answ3":"VIETNAM",
"answ2":"Vietnam War.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Vietnam War</button><button id=incop2 class=buttons003 onclick=qinc()>World War I</button><button id=incop3 class=buttons003 onclick=qinc()>World War II</button><button id=incop4 class=buttons003 onclick=qinc()>Gulf War</button><br/>",
},
{
"cat":"War",
"ques":"Sebastian Stan, Christopher Plummer, Ed Harris, Samuel L. Jackson and Peter Fonda appear in what 2020 war drama?",
"answ":"THE LAST FULL MEASURE",
"answ2":"The Last Full Measure.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Last Full Measure</button><button id=incop2 class=buttons003 onclick=qinc()>Greyhound</button><button id=incop3 class=buttons003 onclick=qinc()>Da 5 Bloods</button><button id=incop4 class=buttons003 onclick=qinc()>The Outpost</button><br/>",
},
{
"cat":"War",
"ques":"Who played former Olympian Louie Zamperini in 2014's Unbroken?",
"answ":"JACK O'CONNELL",
"answ2":"Jack O'Connell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jack O'Connell</button><button id=incop2 class=buttons003 onclick=qinc()>Domhnall Gleeson</button><button id=incop3 class=buttons003 onclick=qinc()>Garrett Hedlund</button><button id=incop4 class=buttons003 onclick=qinc()>Jai Courtney</button><br/>",
},
{
"cat":"War",
"ques":"Joel Schumacher directed what 2000 war drama starring Colin Farrell, Clifton Collins Jr. and Michael Shannon?",
"answ":"TIGERLAND",
"answ2":"Tigerland.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tigerland</button><button id=incop2 class=buttons003 onclick=qinc()>Black Hawk Down</button><button id=incop3 class=buttons003 onclick=qinc()>Windtalkers</button><button id=incop4 class=buttons003 onclick=qinc()>Flags of Our Fathers</button><br/>",
},
{
"cat":"War",
"ques":"Joel Schumacher's Tigerland is set during which war?",
"answ":"VIETNAM WAR",
"answ2":"Vietnam War.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Vietnam War</button><button id=incop2 class=buttons003 onclick=qinc()>Korean War</button><button id=incop3 class=buttons003 onclick=qinc()>World War II</button><button id=incop4 class=buttons003 onclick=qinc()>Iraq War</button><br/>",
},
{
"cat":"War",
"ques":"In The Patriot, which actress plays Mel Gibson's sister-in-law and later wife?",
"answ":"JOELY RICHARDSON",
"answ2":"Joely Richardson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Joely Richardson</button><button id=incop2 class=buttons003 onclick=qinc()>Ashley Judd</button><button id=incop3 class=buttons003 onclick=qinc()>Marisa Tomei</button><button id=incop4 class=buttons003 onclick=qinc()>Kim Basinger</button><br/>",
},
{
"cat":"War",
"ques":"Who directed the war film 13 Hours: The Secret Soldiers of Benghazi?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael Bay</button><button id=incop2 class=buttons003 onclick=qinc()>Sam Mendes</button><button id=incop3 class=buttons003 onclick=qinc()>Oliver Stone</button><button id=incop4 class=buttons003 onclick=qinc()>Terrence Malick</button><br/>",
},
{
"cat":"War",
"ques":"Who directed The Great Escape?",
"answ":"JOHN STURGES",
"answ2":"John Sturges.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John Sturges</button><button id=incop2 class=buttons003 onclick=qinc()>Stanley Kubrick</button><button id=incop3 class=buttons003 onclick=qinc()>Sam Peckinpah</button><button id=incop4 class=buttons003 onclick=qinc()>Alfred Hitchcock</button><br/>",
},
{
"cat":"War",
"ques":"Nicole Kidman and Hugh Jackman co-star in what 2008 war drama?",
"answ":"AUSTRALIA",
"answ2":"Australia.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Australia</button><button id=incop2 class=buttons003 onclick=qinc()>The Edge of Love</button><button id=incop3 class=buttons003 onclick=qinc()>The Hurt Locker</button><button id=incop4 class=buttons003 onclick=qinc()>The Boy in the Striped Pajamas</button><br/>",
},
{
"cat":"War",
"ques":"What Oscar winning actor stars as U.S Navy Commander Ernest Krause in the 2020 war film Greyhound?",
"answ":"TOM HANKS",
"answ2":"Tom Hanks.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tom Hanks</button><button id=incop2 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=incop3 class=buttons003 onclick=qinc()>Russell Crowe</button><button id=incop4 class=buttons003 onclick=qinc()>Geoffrey Rush</button><br/>",
},
{
"cat":"War",
"ques":"Alan Turing is the main character of what film set in World War II?",
"answ":"THE IMITATION GAME",
"answ2":"The Imitation Game.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Saving Private Ryan</button><button id=incop2 class=buttons003 onclick=qinc()>Fury</button><button id=incop3 class=buttons003 onclick=qinc()>Inglourious Basterds</button><button id=corop class=buttons003 onclick=qcor()>The Imitation Game</button><br/>",
},
{
"cat":"War",
"ques":"What was Chris Kyle's career before he decided to go to war in American Sniper?",
"answ":"RODEO RIDER",
"answ2":"Rodeo Rider.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rodeo Rider</button><button id=incop2 class=buttons003 onclick=qinc()>Horse Trainer</button><button id=incop3 class=buttons003 onclick=qinc()>Professional Gambler</button><button id=incop4 class=buttons003 onclick=qinc()>Ranch Foreman</button><br/>",
},
{
"cat":"War",
"ques":"In the movie Fury what is the nickname given to the newest member of the tanks crew Norman?",
"answ":"MACHINE",
"answ2":"Machine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gordo</button><button id=corop class=buttons003 onclick=qcor()>Machine</button><button id=incop3 class=buttons003 onclick=qinc()>Red</button><button id=incop4 class=buttons003 onclick=qinc()>Normie</button><br/>",
},
{
"cat":"War",
"ques":"Robin William plays which real-life disc jockey in Good Morning Vietnam?",
"answ":"ADRIAN CRONAUER",
"answ3":"ADRIAN KRONAUER",
"answ2":"Adrian Cronauer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Edward Garlick</button><button id=corop class=buttons003 onclick=qcor()>Adrian Cronauer</button><button id=incop3 class=buttons003 onclick=qinc()>Eddie Kirk</button><button id=incop4 class=buttons003 onclick=qinc()>Phil McPherson</button><br/>",
},
{
"cat":"War",
"ques":"Oliver Stone won an Academy Award for directing what 1986 war movie?",
"answ":"PLATOON",
"answ2":"Platoon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Salvador</button><button id=incop2 class=buttons003 onclick=qinc()>Heaven & Earth</button><button id=incop3 class=buttons003 onclick=qinc()>Born on the Fourth of July</button><button id=corop class=buttons003 onclick=qcor()>Platoon</button><br/>",
},
{
"cat":"War",
"ques":"Which 1978 war movie starred Robert De Niro, Christopher Walken and John Savage?",
"answ":"THE DEER HUNTER",
"answ3":"DEER HUNTER",
"answ2":"The Deer Hunter.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Deer Hunter</button><button id=incop2 class=buttons003 onclick=qinc()>Platoon</button><button id=incop3 class=buttons003 onclick=qinc()>Full Metal Jacket</button><button id=incop4 class=buttons003 onclick=qinc()>Apocalypse Now</button><br/>",
},
{
"cat":"War",
"ques":"All Quiet on the Western Front was set in which war?",
"answ":"WORLD WAR I",
"answ2":"World War I.",
"option":"<button id=corop class=buttons003 onclick=qcor()>World War I</button><button id=incop2 class=buttons003 onclick=qinc()>World War II</button><button id=incop3 class=buttons003 onclick=qinc()>Vietnam War</button><button id=incop4 class=buttons003 onclick=qinc()>Civil War</button><br/>",
},
{
"cat":"War",
"ques":"What actor portrays a photographer in Apocalypse Now?",
"answ":"DENNIS HOPPER",
"answ2":"Dennis Hopper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tommy Lee Jones</button><button id=incop2 class=buttons003 onclick=qinc()>John Malkovich</button><button id=corop class=buttons003 onclick=qcor()>Dennis Hopper</button><button id=incop4 class=buttons003 onclick=qinc()>Harry Dean Stanton</button><br/>",
},
{
"cat":"War",
"ques":"How many of Private Ryan's brothers were killed in Saving Private Ryan?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>5</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"War",
"ques":"Who played Mel Gibson's eldest son in The Patriot?",
"answ":"HEATH LEDGER",
"answ2":"Heath Ledger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alexander Skarsgard</button><button id=incop2 class=buttons003 onclick=qinc()>Orlando Bloom</button><button id=corop class=buttons003 onclick=qcor()>Heath Ledger</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Cavill</button><br/>",
},
{
"cat":"War",
"ques":"Who directed Paths of Glory?",
"answ":"STANLEY KUBRICK",
"answ2":"Stanley Kubrick.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Francis Coppola</button><button id=incop2 class=buttons003 onclick=qinc()>Oliver Stone</button><button id=corop class=buttons003 onclick=qcor()>Stanley Kubrick</button><button id=incop4 class=buttons003 onclick=qinc()>Sam Peckinpah</button><br/>",
},
{
"cat":"War",
"ques":"Major Major is a character in what 1970 war film?",
"answ":"CATCH 22",
"answ2":"Catch-22.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Catch-22</button><button id=incop2 class=buttons003 onclick=qinc()>Full Metal Jacket</button><button id=incop3 class=buttons003 onclick=qinc()>Patton</button><button id=incop4 class=buttons003 onclick=qinc()>Escape to Athena</button><br/>",
},
{
"cat":"War",
"ques":"What is the first film in Oliver Stone's Vietnam trilogy?",
"answ":"PLATOON",
"answ2":"Platoon.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Platoon</button><button id=incop2 class=buttons003 onclick=qinc()>Heaven & Earth</button><button id=incop3 class=buttons003 onclick=qinc()>Born on the Fourth of July</button><button id=incop4 class=buttons003 onclick=qinc()>Full Metal Jacket</button><br/>",
},
{
"cat":"War",
"ques":"Who played Colonel William Tavington in The Patriot?",
"answ":"JASON ISAACS",
"answ2":"Jason Isaacs.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tim Robbins</button><button id=incop2 class=buttons003 onclick=qinc()>Jason Isaacs</button><button id=incop3 class=buttons003 onclick=qinc()>Sean Penn</button><button id=incop4 class=buttons003 onclick=qinc()>Adrien Brody</button><br/>",
},
{
"cat":"War",
"ques":"In what war movie does Robert De Niro plays Russian roulette?",
"answ":"THE DEER HUNTER",
"answ2":"The Deer Hunter.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Deer Hunter</button><button id=incop2 class=buttons003 onclick=qinc()>Apocalypse Now</button><button id=incop3 class=buttons003 onclick=qinc()>Platoon</button><button id=incop4 class=buttons003 onclick=qinc()>Full Metal Jacket</button><br/>",
},
{
"cat":"War",
"ques":"Which war is the backdrop for the 2004 remake of The Manchurian Candidate?",
"answ":"GULF WAR",
"answ3":"THE GULF WAR",
"answ2":"Gulf War.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gulf War</button><button id=incop2 class=buttons003 onclick=qinc()>Korean War</button><button id=incop3 class=buttons003 onclick=qinc()>Vietnam War</button><button id=incop4 class=buttons003 onclick=qinc()>World War II</button><br/>",
},
{
"cat":"War",
"ques":"What did Mel Gibson melt down to make more bullets in The Patriot?",
"answ":"TOY SOLDIERS",
"answ3":"TIN SOLDIERS",
"answ2":"Toy Soldiers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Toy Soldiers</button><button id=incop2 class=buttons003 onclick=qinc()>Jewelry</button><button id=incop3 class=buttons003 onclick=qinc()>Coins</button><button id=incop4 class=buttons003 onclick=qinc()>Knives</button><br/>",
},
{
"cat":"War",
"ques":"Who directed the 2005 war drama Jarhead?",
"answ":"SAM MENDES",
"answ2":"Sam Mendes.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sam Mendes</button><button id=incop2 class=buttons003 onclick=qinc()>Joe Wright</button><button id=incop3 class=buttons003 onclick=qinc()>Terrence Malick</button><button id=incop4 class=buttons003 onclick=qinc()>Jonathan Mostow</button><br/>",
},
{
"cat":"War",
"ques":"Anthony Mackie co-starred as a member of a bomb disposal unit in what 2009 film?",
"answ":"THE HURT LOCKER",
"answ2":"The Hurt Locker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Hurt Locker</button><button id=incop2 class=buttons003 onclick=qinc()>The Kingdom</button><button id=incop3 class=buttons003 onclick=qinc()>Defiance</button><button id=incop4 class=buttons003 onclick=qinc()>The Messenger</button><br/>",
},
{
"cat":"War",
"ques":"Martin Sheen played Lieutenant Dobbs and Alan Arkin was Captain Yossarian in which 1970 war film?",
"answ":"CATCH 22",
"answ2":"Catch-22.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Catch-22</button><button id=incop2 class=buttons003 onclick=qinc()>MASH</button><button id=incop3 class=buttons003 onclick=qinc()>Tora! Tora! Tora!</button><button id=incop4 class=buttons003 onclick=qinc()>Kelly's Heroes</button><br/>",
},
{
"cat":"War",
"ques":"1989's Glory takes place during which war?",
"answ":"CIVIL WAR",
"answ3":"AMERICAN CIVIL WAR",
"answ2":"American Civil War.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gulf War</button><button id=incop2 class=buttons003 onclick=qinc()>World War I</button><button id=corop class=buttons003 onclick=qcor()>American Civil War</button><button id=incop4 class=buttons003 onclick=qinc()>World War II</button><br/>",
},
{
"cat":"War",
"ques":"Who directed Good Morning Vietnam?",
"answ":"BARRY LEVINSON",
"answ2":"Barry Levinson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Oliver Stone</button><button id=incop2 class=buttons003 onclick=qinc()>Sam Mendes</button><button id=corop class=buttons003 onclick=qcor()>Barry Levinson</button><button id=incop4 class=buttons003 onclick=qinc()>Stanley Kubrick</button><br/>",
},
{
"cat":"War",
"ques":"Who plays Major John Reisman, leader of 1967's The Dirty Dozen?",
"answ":"LEE MARVIN",
"answ2":"Lee Marvin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jim Brown</button><button id=incop2 class=buttons003 onclick=qinc()>Charles Bronson</button><button id=corop class=buttons003 onclick=qcor()>Lee Marvin</button><button id=incop4 class=buttons003 onclick=qinc()>Richard Jaeckel</button><br/>",
},
{
"cat":"War",
"ques":"Who composed the score for War Horse?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Howard Shore</button><button id=corop class=buttons003 onclick=qcor()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Danny Elfman</button><br/>",
},
{
"cat":"War",
"ques":"The majority of the film We Were Soldiers starring Mel Gibson takes place during which war?",
"answ":"VIETNAM WAR",
"answ2":"Vietnam War.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>World War II</button><button id=incop2 class=buttons003 onclick=qinc()>World War I</button><button id=corop class=buttons003 onclick=qcor()>Vietnam War</button><button id=incop4 class=buttons003 onclick=qinc()>Gulf War</button><br/>",
},
{
"cat":"War",
"ques":"Don Rickles plays staff sergeant Crapgame in what war film?",
"answ":"KELLY'S HEROES",
"answ2":"Kelly's Heroes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>MASH</button><button id=corop class=buttons003 onclick=qcor()>Kelly's Heroes</button><button id=incop3 class=buttons003 onclick=qinc()>Full Metal Jacket</button><button id=incop4 class=buttons003 onclick=qinc()>Apocalypse Now</button><br/>",
},
{
"cat":"War",
"ques":"What war film features Ty Burrell, Tom Hardy, Eric Bana and Nikolaj Coster-Waldau?",
"answ":"BLACK HAWK DOWN",
"answ2":"Black Hawk Down.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lone Survivor</button><button id=incop2 class=buttons003 onclick=qinc()>Pearl Harbor</button><button id=corop class=buttons003 onclick=qcor()>Black Hawk Down</button><button id=incop4 class=buttons003 onclick=qinc()>Hacksaw Ridge</button><br/>",
},
{
"cat":"War",
"ques":"Tom Cruise's character Nathan Algren in The Last Samurai is a veteran of what war?",
"answ":"CIVIL WAR",
"answ3":"AMERICAN CIVIL WAR",
"answ2":"The American Civil War.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>World War I</button><button id=incop2 class=buttons003 onclick=qinc()>Spanish Civil War</button><button id=corop class=buttons003 onclick=qcor()>American Civil War</button><button id=incop4 class=buttons003 onclick=qinc()>American Revolutionary War</button><br/>",
},
{
"cat":"War",
"ques":"In Jarhead, who played the lead, Anthony Swofford, a sniper in the U.S. Marine Corps?",
"answ":"JAKE GYLLENHAAL",
"answ3":"JAKE GYLENHAAL",
"answ2":"Jake Gyllenhaal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Henry Cavill</button><button id=incop2 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=corop class=buttons003 onclick=qcor()>Jake Gyllenhaal</button><button id=incop4 class=buttons003 onclick=qinc()>Bradley Cooper</button><br/>",
},
{
"cat":"War",
"ques":"Who plays the character nicknamed 'Bible' in David Ayer's Fury?",
"answ":"SHIA LABEOUF",
"answ3":"SHIA LABOEUF",
"answ2":"Shia LaBeouf.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brad Pitt</button><button id=incop2 class=buttons003 onclick=qinc()>Jon Bernthal</button><button id=corop class=buttons003 onclick=qcor()>Shia LaBeouf</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Isaacs</button><br/>",
},
{
"cat":"War",
"ques":"Who played the driver of the tank, Gordo, in Fury?",
"answ":"MICHAEL PENA",
"answ2":"Michael Pena.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael Pena</button><button id=incop2 class=buttons003 onclick=qinc()>Jon Bernthal</button><button id=incop3 class=buttons003 onclick=qinc()>Shia LaBeouf</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Isaacs</button><br/>",
},
{
"cat":"War",
"ques":"Which war film starred Ryan Philippe as a soldier who had thought he served his last tour in Iraq?",
"answ":"STOPP LOSS",
"answ2":"Stop-Loss.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Stop-Loss</button><button id=incop2 class=buttons003 onclick=qinc()>Setup</button><button id=incop3 class=buttons003 onclick=qinc()>Jarhead</button><button id=incop4 class=buttons003 onclick=qinc()>Black Hawk Down</button><br/>",
},
{
"cat":"War",
"ques":"In Michael Bay's Pearl Harbor, who plays President Franklin D. Roosevelt?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jon Voight</button><button id=incop2 class=buttons003 onclick=qinc()>James Woods</button><button id=incop3 class=buttons003 onclick=qinc()>Donald Sutherland</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Plummer</button><br/>",
},
{
"cat":"War",
"ques":"Who plays Andrew Garfield's father in Hacksaw Ridge?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hugo Weaving</button><button id=incop2 class=buttons003 onclick=qinc()>Guy Pearce</button><button id=incop3 class=buttons003 onclick=qinc()>Gary Oldman</button><button id=incop4 class=buttons003 onclick=qinc()>Kenneth Branagh</button><br/>",
},
{
"cat":"War",
"ques":"In The Railway Man, who stars as a former British soldier tortured by the memory of his time as a Japanese prisoner of war during World War II?",
"answ":"COLIN FIRTH",
"answ2":"Colin Firth.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christian Bale</button><button id=incop2 class=buttons003 onclick=qinc()>Hugh Laurie</button><button id=corop class=buttons003 onclick=qcor()>Colin Firth</button><button id=incop4 class=buttons003 onclick=qinc()>Sean Bean</button><br/>",
},
{
"cat":"War",
"ques":"Meg Ryan plays a Captain in the US Army in Courage Under Fire, which is set during which war?",
"answ":"THE GULF WAR",
"answ3":"GULF WAR",
"answ2":"The Gulf War.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>World War II</button><button id=incop2 class=buttons003 onclick=qinc()>Korean War</button><button id=incop3 class=buttons003 onclick=qinc()>Vietnam War</button><button id=corop class=buttons003 onclick=qcor()>Gulf War</button><br/>",
},
{
"cat":"War",
"ques":"What is the military rank of Jeremy Renner's character in The Hurt Locker?",
"answ":"SERGEANT",
"answ3":"SERGEANT FIRST CLASS",
"answ2":"Sergeant First Class.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Captain</button><button id=incop2 class=buttons003 onclick=qinc()>Major General</button><button id=incop3 class=buttons003 onclick=qinc()>Lieutenant Colonel</button><button id=corop class=buttons003 onclick=qcor()>Sergeant First Class</button><br/>",
},
{
"cat":"War",
"ques":"What classic war film won seven Oscars including Best Actor, Best Original Screenplay and Best Director?",
"answ":"PATTON",
"answ2":"Patton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>All Quiet on the Western Front</button><button id=incop2 class=buttons003 onclick=qinc()>Sands of Iwo Jima</button><button id=incop3 class=buttons003 onclick=qinc()>Where Eagles Dare</button><button id=corop class=buttons003 onclick=qcor()>Patton</button><br/>",
},
{
"cat":"War",
"ques":"The 2006 movie Flyboys follows the escapades of volunteer American aviators during which war?",
"answ":"WORLD WAR I",
"answ2":"World War I.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Iraq War</button><button id=incop2 class=buttons003 onclick=qinc()>Vietnam War</button><button id=incop3 class=buttons003 onclick=qinc()>World War II</button><button id=corop class=buttons003 onclick=qcor()>World War I</button><br/>",
},
{
"cat":"War",
"ques":"Who directed Black Hawk Down?",
"answ":"RIDLEY SCOTT",
"answ2":"Ridley Scott.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Terrence Malick</button><button id=incop2 class=buttons003 onclick=qinc()>Tony Scott</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Zemeckis</button><button id=corop class=buttons003 onclick=qcor()>Ridley Scott</button><br/>",
},
{
"cat":"War",
"ques":"What is the military rank of Tom Hanks' character in the war film Greyhound?",
"answ":"COMMANDER",
"answ2":"Commander.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>General</button><button id=incop2 class=buttons003 onclick=qinc()>Lieutenant</button><button id=incop3 class=buttons003 onclick=qinc()>Major</button><button id=corop class=buttons003 onclick=qcor()>Commander</button><br/>",
},
];
war = shuffle(war);
r2Q35 = shuffle(r2Q35);