var tens = [
{
"cat":"2010s",
"ques":"Who directed Saoirse Ronan and Cate Blanchett in 2011's Hanna?",
"answ":"JOE WRIGHT",
"answ2":"Joe Wright.",
},
{
"cat":"2010s",
"ques":"Catherine Keener and Oliver Platt play a married couple who butt heads with the granddaughters of an elderly woman who lives in the apartment they own in what 2010 film?",
"answ":"PLEASE GIVE",
"answ2":"Please Give.",
},
{
"cat":"2010s",
"ques":"Antonio Banderas, Josh Brolin, Anthony Hopkins and Naomi Watts appear in what 2010 film directed by Woody Allen?",
"answ":"YOU WILL MEET A TALL DARK STRANGER",
"answ2":"You Will Meet a Tall Dark Stranger.",
},
{
"cat":"2010s",
"ques":"A group of Siberian gulag escapees travel four thousand miles by foot to freedom in what 2010 film directed by Peter Weir?",
"answ":"THE WAY BACK",
"answ2":"The Way Back.",
},
{
"cat":"2010s",
"ques":"Which actor stars as the titular character in 2010's Cyrus?",
"answ":"JONAH HILL",
"answ2":"Jonah Hill.",
},
{
"cat":"2010s",
"ques":"Which 2010 film features the vocal talents of Owen Wilson, Fergie, Kiefer Sutherland, Damon Wayans Jr. and Sam Elliott?",
"answ":"MARMADUKE",
"answ2":"Marmaduke.",
},
{
"cat":"2010s",
"ques":"Ashton Kutcher and Katherine Heigl play a married couple on the run from assassins in what 2010s film?",
"answ":"KILLERS",
"answ2":"Killers.",
},
{
"cat":"2010s",
"ques":"Which MCU actor stars as the fallen Archangel Michael in 2010's Legion?",
"answ":"PAUL BETTANY",
"answ2":"Paul Bettany.",
},
{
"cat":"2010s",
"ques":"Shia LaBeouf, Josh Brolin, Susan Sarandon and Michael Douglas appear in what 2010 sequel?",
"answ":"WALL STREET MONEY NEVER SLEEPS",
"answ3":"WALL STREET 2",
"answ2":"Wall Street: Money Never Sleeps.",
},
{
"cat":"2010s",
"ques":"Who starred as mathematics teacher Frank Tupelo in 2010's The Tourist?",
"answ":"JOHNNY DEPP",
"answ2":"Johnny Depp.",
},
{
"cat":"2010s",
"ques":"Which actress played Johnny Depp's love interest in 2010's The Tourist?",
"answ":"ANGELINA JOLIE",
"answ2":"Angelina Jolie.",
},
{
"cat":"2010s",
"ques":"Ben Stiller, Robert De Niro, Kevin Hart and Jessica Alba appear in what 2010s comedy?",
"answ":"LITTLE FOCKERS",
"answ2":"Little Fockers.",
},
{
"cat":"2010s",
"ques":"Which actor stars in the following 2010s films: The Eagle, The Vow and Foxcatcher?",
"answ":"CHANNING TATUM",
"answ2":"Channing Tatum.",
},
{
"cat":"2010s",
"ques":"Which actor starred in the 2010s action films Homefront and Wild Card?",
"answ":"JASON STATHAM",
"answ2":"Jason Statham.",
},
{
"cat":"2010s",
"ques":"Who directed 2018's Death Wish?",
"answ":"ELI ROTH",
"answ2":"Eli Roth.",
},
{
"cat":"2010s",
"ques":"Who plays Kyle Reese in Terminator: Genisys?",
"answ":"JAI COURTNEY",
"answ2":"Jai Courtney.",
},
{
"cat":"2010s",
"ques":"Spike Jonze directed Joaquin Phoenix in what film about falling in love with an AI system?",
"answ":"HER",
"answ2":"Her.",
},
{
"cat":"2010s",
"ques":"Which actor plays Standard Gabriel, who is released from prison and is married to Carey Mulligan's Irene in 2011's Drive?",
"answ":"OSCAR ISAAC",
"answ2":"Oscar Isaac.",
},
{
"cat":"2010s",
"ques":"Who directed the 2016 film Miss Peregrine's Home For Peculiar Children?",
"answ":"TIM BURTON",
"answ2":"Tim Burton.",
},
{
"cat":"2010s",
"ques":"What actor co-starred alongside Jaden Smith as Mr. Han in 2010's The Karate Kid?",
"answ":"JACKIE CHAN",
"answ2":"Jackie Chan.",
},
{
"cat":"2010s",
"ques":"What Oscar winning actor plays the lead role in the psychological thriller You Were Nevery Really Here?",
"answ":"JOAQUIN PHOENIX",
"answ2":"Joaquin Phoenix.",
},
{
"cat":"2010s",
"ques":"Which Marvel actor stars as the character Tommy, opposite Carey Mulligan and Keira Knightley in 2010's Never Let Me Go?",
"answ":"ANDREW GARFIELD",
"answ2":"Andrew Garfield.",
},
{
"cat":"2010s",
"ques":"Which TV actress plays paramedic Anya Thorensen in 2018's Annihilation?",
"answ":"GINA RODRIGUEZ",
"answ3":"GINA RODRIGUES",
"answ2":"Gina Rodriguez.",
},
{
"cat":"2010s",
"ques":"Amandla Stenberg plays Starr Carter who witnesses her friend Khalil's murder when they are pulled over in what 2018 film?",
"answ":"THE HATE U GIVE",
"answ3":"THE HATE YOU GIVE",
"answ2":"The Hate U Give.",
},
{
"cat":"2010s",
"ques":"This 2014 ensemble film stars Ralph Fiennes as a concierge who must prove his innocence when he is framed for murder.",
"answ":"THE GRAND BUDAPEST HOTEL",
"answ3":"GRAND BUDAPEST HOTEL",
"answ2":"The Grand Budapest Hotel.",
},
{
"cat":"2010s",
"ques":"In Hail, Caesar!, what Star Wars actor plays Hobie Doyle, a young actor known for singing cowboy roles?",
"answ":"ALDEN EHRENREICH",
"answ3":"ALDEN ERENREICH",
"answ2":"Alden Ehrenreich.",
},
{
"cat":"2010s",
"ques":"Who directed 2015's Tomorrowland?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"2010s",
"ques":"Who plays the main love interest Theodore 'Laurie' Laurence in 2019's Little Women?",
"answ":"TIMOTHEE CHALAMET",
"answ3":"TIMOTHY CHALAMET",
"answ2":"Timothée Chalamet.",
},
{
"cat":"2010s",
"ques":"What Oscar winning actor co-stars with Alan Arkin and Michael Caine as Willie in the 2017 heist comedy Going In Style?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"2010s",
"ques":"What 2019 movie was directed by Roland Emmerich, stars Ed Skrein and depicts a famous World War 2 battle?",
"answ":"MIDWAY",
"answ2":"Midway.",
},
{
"cat":"2010s",
"ques":"Who played James Franco's father in 2011's Rise of the Planet of the Apes?",
"answ":"JOHN LITHGOW",
"answ3":"JOHN LITGOW",
"answ2":"John Lithgow.",
},
{
"cat":"2010s",
"ques":"What is the subtitle of the fifth film in the Rambo series, released in 2019?",
"answ":"LAST BLOOD",
"answ2":"Last Blood.",
},
{
"cat":"2010s",
"ques":"Anton Yelchin and Imogen Poots star in what 2016 thriller about a punk rock band who are attacked by neo-Nazis?",
"answ":"GREEN ROOM",
"answ2":"Green Room.",
},
{
"cat":"2010s",
"ques":"The characters of Kevin Wendell Crumb and David Dunn are brought together in a mental institution in what 2019 film?",
"answ":"GLASS",
"answ2":"Glass.",
},
{
"cat":"2010s",
"ques":"Who plays the main lead, Roy McBride, in the sci-fi film Ad Astra?",
"answ":"BRAD PITT",
"answ2":"Brad Pitt.",
},
{
"cat":"2010s",
"ques":"Who stars as a Chinese-American woman who learns that her grandmother has cancer in The Farewell?",
"answ":"AWKWAFINA",
"answ3":"AKWAFINA",
"answ2":"Awkwafina.",
},
{
"cat":"2010s",
"ques":"What 2019 horror film stars James McAvoy, Jessica Chastain, Bill Hader and Bill Skarsgard?",
"answ":"IT CHAPTER 2",
"answ3":"IT 2",
"answ2":"It Chapter 2.",
},
{
"cat":"2010s",
"ques":"What 2017 movie reboot of a popular TV show co-stars Elizabeth Banks and Bryan Cranston?",
"answ":"POWER RANGERS",
"answ2":"Power Rangers.",
},
{
"cat":"2010s",
"ques":"Which action star plays US Marine Ray Garrison in the film Bloodshot?",
"answ":"VIN DIESEL",
"answ2":"Vin Diesel.",
},
{
"cat":"2010s",
"ques":"What is the subtitle of the third John Wick film?",
"answ":"PARABELLUM",
"answ2":"Parabellum.",
},
{
"cat":"2010s",
"ques":"Jake Gyllenhaal plays a championship boxer in this 2015 film.",
"answ":"SOUTHPAW",
"answ2":"Southpaw.",
},
{
"cat":"2010s",
"ques":"Which actress starred in the 2019 films Fighting With My Family and Midsommer?",
"answ":"FLORENCE PUGH",
"answ3":"FLORENCE PUH",
"answ2":"Florence Pugh.",
},
{
"cat":"2010s",
"ques":"Which Oscar winning actress plays the main lead in 2019's Ma?",
"answ":"OCTAVIA SPENCER",
"answ2":"Octavia Spencer.",
},
{
"cat":"2010s",
"ques":"What 2019 horror film stars Elizabeth Banks and was produced by James Gunn?",
"answ":"BRIGHTBURN",
"answ2":"Brightburn.",
},
{
"cat":"2010s",
"ques":"Who plays Neil Armstrong in First Man?",
"answ":"RYAN GOSLING",
"answ2":"Ryan Gosling.",
},
{
"cat":"2010s",
"ques":"Name either the male or the female lead of the 2019 romantic comedy Isn't It Romantic.",
"answ":"REBEL WILSON",
"answ3":"LIAM HEMSWORTH",
"answ2":"Rebel Wilson/Liam Hemsworth.",
},
{
"cat":"2010s",
"ques":"In Welcome to Marwen, who stars as Mark Hogancamp, the man who uses modified dolls to create a fantasy world?",
"answ":"STEVE CARELL",
"answ3":"STEVE CARRELL",
"answ2":"Steve Carell.",
},
{
"cat":"2010s",
"ques":"Who played Leta Lestrange, Newt's former love in Fantastic Beasts: The Crimes of Grindelwald?",
"answ":"ZOE KRAVITZ",
"answ3":"ZOË KRAVITZ",
"answ2":"Zoe Kravitz.",
},
{
"cat":"2010s",
"ques":"Who provides the voice of the title character in Detective Pikachu?",
"answ":"RYAN REYNOLDS",
"answ2":"Ryan Reynolds.",
},
{
"cat":"2010s",
"ques":"Will Ferrell and Mark Wahlberg star as Detectives Gamble and Hoitz in what 2010 buddy cop film?",
"answ":"THE OTHER GUYS",
"answ2":"The Other Guys.",
},
{
"cat":"2010s",
"ques":"Who plays Apple creator Steve Jobs in 2015's Steve Jobs?",
"answ":"MICHAEL FASSBENDER",
"answ2":"Michael Fassbender.",
},
{
"cat":"2010s",
"ques":"Which actor plays Dell Scott, a man who cares for a quadriplegic named Phillip, in The Upside?",
"answ":"KEVIN HART",
"answ2":"Kevin Hart.",
},
{
"cat":"2010s",
"ques":"Who plays Donald Rumsfeld in Vice?",
"answ":"STEVE CARELL",
"answ3":"STEVE CARRELL",
"answ2":"Steve Carell.",
},
{
"cat":"2010s",
"ques":"Who plays Lady Sarah in The Favourite?",
"answ":"RACHEL WEISZ",
"answ2":"Rachel Weisz.",
},
{
"cat":"2010s",
"ques":"Who directed the film Fantastic Beasts: The Crimes of Grindelwald?",
"answ":"DAVID YATES",
"answ2":"David Yates.",
},
{
"cat":"2010s",
"ques":"What actress voices Queen Watevra Wa'Nabi in The LEGO Movie 2: The Second Part?",
"answ":"TIFFANY HADDISH",
"answ2":"Tiffany Haddish.",
},
{
"cat":"2010s",
"ques":"In Fighting with My Family, what actor, often seen in comedic roles, plays WWE trainer Hutch Morgan, who was in charge of selecting candidates?",
"answ":"VINCE VAUGHN",
"answ2":"Vince Vaughn.",
},
{
"cat":"2010s",
"ques":"Which actress co-stars as a character named Detroit in 2018's Sorry To Bother You?",
"answ":"TESSA THOMPSON",
"answ3":"TESSA THOMSON",
"answ2":"Tessa Thompson.",
},
{
"cat":"2010s",
"ques":"In La La Land, who plays Bill, the owner of the restaurant who fires Sebastian for playing jazz music instead of the traditional Christmas setlist?",
"answ":"JK SIMMONS",
"answ3":"J K SIMMONS",
"answ2":"J.K. Simmons.",
},
{
"cat":"2010s",
"ques":"Which 2018 comedy stars Ed Helms, Jon Hamm and Jeremy Renner?",
"answ":"TAG",
"answ2":"Tag.",
},
{
"cat":"2010s",
"ques":"What is Leonardo DiCaprio's wife's totem in the film Inception?",
"answ":"TOP",
"answ3":"SPINNING TOP",
"answ2":"Spinning top.",
},
{
"cat":"2010s",
"ques":"In what 2018 film do Blake Lively and Henry Golding play husband and wife?",
"answ":"A SIMPLE FAVOR",
"answ2":"A Simple Favor.",
},
{
"cat":"2010s",
"ques":"Who directed 2018's First Man?",
"answ":"DAMIEN CHAZELLE",
"answ3":"DAMIAN CHAZELLE",
"answ2":"Damien Chazelle.",
},
{
"cat":"2010s",
"ques":"In 2018's Searching, who plays David Kim who is searching for his missing daughter?",
"answ":"JOHN CHO",
"answ2":"John Cho.",
},
{
"cat":"2010s",
"ques":"Who plays charismatic cult leader Billy Lee in Bad Times at the El Royale?",
"answ":"CHRIS HEMSWORTH",
"answ2":"Chris Hemsworth.",
},
{
"cat":"2010s",
"ques":"A zombie boy forms a relationship with a living girl in what 2013 film?",
"answ":"WARM BODIES",
"answ2":"Warm Bodies.",
},
{
"cat":"2010s",
"ques":"In BlacKkKlansman, who plays David Duke?",
"answ":"TOPHER GRACE",
"answ2":"Topher Grace.",
},
{
"cat":"2010s",
"ques":"Who plays Agent Burns in Bumblebee?",
"answ":"JOHN CENA",
"answ2":"John Cena.",
},
{
"cat":"2010s",
"ques":"After a long absence from movies, Cher appeared in which 2010 movie starring alongside Christina Aguilera?",
"answ":"BURLESQUE",
"answ2":"Burlesque.",
},
{
"cat":"2010s",
"ques":"What musician was kidnapped by the villainous Poppy in Kingsman: The Golden Circle?",
"answ":"ELTON JOHN",
"answ2":"Elton John.",
},
{
"cat":"2010s",
"ques":"In 2018's Rampage, what is the name of the rare albino gorilla that befriends Davis?",
"answ":"GEORGE",
"answ2":"George.",
},
{
"cat":"2010s",
"ques":"What 2016 film stars Jeff Bridges, Chris Pine and Ben Foster?",
"answ":"HELL OR HIGH WATER",
"answ2":"Hell or High Water.",
},
{
"cat":"2010s",
"ques":"Who directed 2016's Don't Breathe?",
"answ":"FEDE ALVAREZ",
"answ2":"Fede Alvarez.",
},
{
"cat":"2010s",
"ques":"Charlize Theron stars alongside Seth MacFarlane in what comedy?",
"answ":"A MILLION WAYS TO DIE IN THE WEST",
"answ2":"A Million Ways to Die in the West.",
},
{
"cat":"2010s",
"ques":"Who played the American agent Ginger in Kingsman: The Golden Circle?",
"answ":"HALLE BARRY",
"answ3":"HALLE BERRY",
"answ2":"Halle Berry.",
},
{
"cat":"2010s",
"ques":"Jonah Hill and Miles Teller star in what Todd Phillips film about gun runners?",
"answ":"WAR DOGS",
"answ3":"WARDOGS",
"answ2":"War Dogs.",
},
{
"cat":"2010s",
"ques":"Who directed the 2014 mockumentary horror comedy What We Do in the Shadows?",
"answ":"TAIKA WAITITI",
"answ2":"Taika Waititi.",
},
{
"cat":"2010s",
"ques":"Who voices Brenda the Bun in Sausage Party?",
"answ":"KRISTEN WIIG",
"answ3":"KRISTEN WIG",
"answ2":"Kristen Wiig.",
},
{
"cat":"2010s",
"ques":"Who stars opposite Natalie Portman in the 2011 rom-com No Strings Attached?",
"answ":"ASHTON KUTCHER",
"answ2":"Ashton Kutcher.",
},
{
"cat":"2010s",
"ques":"Name the actor that played Louis Bloom in 2014's Nightcrawler?",
"answ":"JAKE GYLLENHAAL",
"answ2":"Jake Gyllenhaal.",
},
{
"cat":"2010s",
"ques":"In what 2016 film will you find Emma Roberts and Dave Franco playing an online game in which 'Watchers' dare 'Players' to complete increasingly dangerous tasks for money?",
"answ":"NERVE",
"answ2":"Nerve.",
},
{
"cat":"2010s",
"ques":"Who plays young Elio in Call Me By Your Name?",
"answ":"TIMOTHEE CHALAMET",
"answ3":"TIMOTHY CHALAMET",
"answ2":"Timothée Chalamet.",
},
{
"cat":"2010s",
"ques":"In what movie does Owen Wilson play the father to Auggie, the main protagonist of the movie?",
"answ":"WONDER",
"answ2":"Wonder.",
},
{
"cat":"2010s",
"ques":"Who plays a Statesman agent by the name of Tequila in Kingsman: The Golden Circle?",
"answ":"CHANNING TATUM",
"answ2":"Channing Tatum.",
},
{
"cat":"2010s",
"ques":"What 2015 movie stars Jason Bateman and Rebecca Hall as a married couple that is met by Joel Edgerton, who was a former childhood friend?",
"answ":"THE GIFT",
"answ2":"The Gift.",
},
{
"cat":"2010s",
"ques":"Who plays Greg Sestero in The Disaster Artist?",
"answ":"DAVE FRANCO",
"answ2":"Dave Franco.",
},
{
"cat":"2010s",
"ques":"What actress played Rachel Watson, a woman who becomes obsessed with her neighbors in 2016's The Girl On The Train?",
"answ":"EMILY BLUNT",
"answ2":"Emily Blunt.",
},
{
"cat":"2010s",
"ques":"What actor played down-on-his-luck private eye, Holland March in 2016's The Nice Guys?",
"answ":"RYAN GOSLING",
"answ2":"Ryan Gosling.",
},
{
"cat":"2010s",
"ques":"What 2015 sci-fi film starred George Clooney, Hugh Laurie and Britt Robertson?",
"answ":"TOMORROWLAND",
"answ2":"Tomorowland.",
},
{
"cat":"2010s",
"ques":"Who played Jane Porter Clayton in 2016's The Legend of Tarzan?",
"answ":"MARGOT ROBBIE",
"answ2":"Margot Robbie.",
},
{
"cat":"2010s",
"ques":"Who voiced the 'The Boss Baby' in The Boss Baby?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
},
{
"cat":"2010s",
"ques":"In 2017's Split, how many girls are kidnapped at the beginning of the film?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"2010s",
"ques":"What 2015 fantasy stars Hugh Jackman and is directed by Joe Wright?",
"answ":"PAN",
"answ2":"Pan.",
},
{
"cat":"2010s",
"ques":"Who plays Ryan Gosling's superior Lt. Joshi in Blade Runner 2049?",
"answ":"ROBIN WRIGHT",
"answ2":"Robin Wright.",
},
{
"cat":"2010s",
"ques":"Who played Valerie aka Red Riding Hood in 2011's Red Riding Hood?",
"answ":"AMANDA SEYFRIED",
"answ2":"Amanda Seyfried.",
},
{
"cat":"2010s",
"ques":"Who directed the 2019 'live-action' The Lion King remake?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
},
{
"cat":"2010s",
"ques":"Who voiced Alpha-5 in 2017's Power Rangers?",
"answ":"BILL HADER",
"answ2":"Bill Hader.",
},
{
"cat":"2010s",
"ques":"Who played The Green Hornet in 2011's The Green Hornet?",
"answ":"SETH ROGEN",
"answ3":"SETH ROGAN",
"answ2":"Seth Rogen.",
},
{
"cat":"2010s",
"ques":"Who plays morning news director Nina Romina in the 2014 crime drama Nightcrawler?",
"answ":"RENE RUSSO",
"answ3":"RENEE RUSSO",
"answ2":"Rene Russo.",
},
{
"cat":"2010s",
"ques":"Kristen Bell, Kathryn Hahn and what other actress star in Bad Moms and Bad Moms Christmas?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
},
{
"cat":"2010s",
"ques":"In which midwestern US city is the 2016 horror thriller Don't Breathe set?",
"answ":"DETROIT",
"answ2":"Detroit.",
},
{
"cat":"2010s",
"ques":"Who plays Colonel Weber in 2016's Arrival?",
"answ":"FOREST WHITAKER",
"answ3":"FORREST WHITAKER",
"answ2":"Forest Whitaker.",
},
{
"cat":"2010s",
"ques":"Who directed the heist comedy Logan Lucky?",
"answ":"STEVEN SODERBERGH",
"answ3":"STEVEN SODERBERG",
"answ2":"Steven Soderbergh.",
},
{
"cat":"2010s",
"ques":"What 2011 movie stars Jake Gyllenhaal who is repeatedly sent in an alternative reality to find a train bomber?",
"answ":"SOURCE CODE",
"answ2":"Source Code.",
},
{
"cat":"2010s",
"ques":"Who directed 2016's war film 13 Hours?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
},
{
"cat":"2010s",
"ques":"Who stars as Darius, a college graduate who lives at home with her widowed father in 2012's Safety Not Guaranteed?",
"answ":"AUBREY PLAZA",
"answ2":"Aubrey Plaza.",
},
{
"cat":"2010s",
"ques":"Who played Mark Wahlberg's girlfriend Lori in Ted?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
},
{
"cat":"2010s",
"ques":"Who plays twins Cameron and Tyler Winklevoss in The Social Network?",
"answ":"ARMIE HAMMER",
"answ2":"Armie Hammer.",
},
{
"cat":"2010s",
"ques":"Who wrote and directed Midnight Special?",
"answ":"JEFF NICHOLS",
"answ2":"Jeff Nichols.",
},
{
"cat":"2010s",
"ques":"Who plays a younger version of Agent K in Men in Black 3?",
"answ":"JOSH BROLIN",
"answ2":"Josh Brolin.",
},
{
"cat":"2010s",
"ques":"Andrew Garfield and what other actor play Jesuit priests looking for Liam Neeson in 2016's Silence?",
"answ":"ADAM DRIVER",
"answ2":"Adam Driver.",
},
{
"cat":"2010s",
"ques":"Name the 2012 animated film with the following characters: Merida, Lord Macintosh and Elinor.",
"answ":"BRAVE",
"answ2":"Brave.",
},
{
"cat":"2010s",
"ques":"In John Wick, what make of Ford car was stolen from John at the beginning of the film?",
"answ":"MUSTANG",
"answ3":"SHELBY",
"answ2":"Mustang/Shelby.",
},
{
"cat":"2010s",
"ques":"Who played Mason's biological father in Boyhood?",
"answ":"ETHAN HAWKE",
"answ3":"ETHAN HAWK",
"answ2":"Ethan Hawke.",
},
{
"cat":"2010s",
"ques":"What is the name of the idyllic place that Furiosa is taking Immortan Joe's wives in Mad Max Fury Road?",
"answ":"THE GREEN PLACE",
"answ3":"GREEN PLACE",
"answ2":"The Green Place.",
},
{
"cat":"2010s",
"ques":"Who plays the fiancee to Owen Wilson's struggling author in Midnight in Paris?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
},
{
"cat":"2010s",
"ques":"Who played the lead role of Nadine in the 2016 film Edge of Seventeen?",
"answ":"HAILEE STEINFELD",
"answ3":"HAILEY STEINFELD",
"answ2":"Hailee Steinfeld.",
},
{
"cat":"2010s",
"ques":"Who played Sarah Connor in Terminator Genisys?",
"answ":"EMILIA CLARKE",
"answ3":"EMILIA CLARK",
"answ2":"Emilia Clarke.",
},
{
"cat":"2010s",
"ques":"What 2012 war film was notable for using active duty U.S. Navy SEALS in its cast?",
"answ":"ACT OF VALOR",
"answ2":"Act of Valor.",
},
{
"cat":"2010s",
"ques":"Robert Pattinson joins the circus and romances Reese Witherspoon in what 2011 period piece?",
"answ":"WATER FOR ELEPHANTS",
"answ2":"Water for Elephants.",
},
{
"cat":"2010s",
"ques":"Name the comedic actor who stars as Tennessee in the 2017 thriller Alien Covenant.",
"answ":"DANNY MCBRIDE",
"answ2":"Danny McBride.",
},
{
"cat":"2010s",
"ques":"Natalie Portman, James Franco and Danny McBride star in what 2011 fantasy comedy?",
"answ":"YOUR HIGHNESS",
"answ2":"Your Highness.",
},
{
"cat":"2010s",
"ques":"Who starred as the enforcer Doug 'The Thug' Glatt in the hockey film Goon?",
"answ":"SEAN WILLIAM SCOTT",
"answ3":"SEANN WILLIAM SCOTT",
"answ2":"Seann William Scott.",
},
{
"cat":"2010s",
"ques":"Who directed Chronicle?",
"answ":"JOSH TRANK",
"answ2":"Josh Trank.",
},
{
"cat":"2010s",
"ques":"Sharlto Copley played which character in 2010's The A-Team?",
"answ":"MURDOCK",
"answ3":"HOWLING MAD MURDOCK",
"answ2":"Murdock.",
},
{
"cat":"2010s",
"ques":"In Sicario, who oversees the special joint task force that Emily Blunt is recruited for?",
"answ":"JOSH BROLIN",
"answ2":"Josh Brolin.",
},
{
"cat":"2010s",
"ques":"What popular TV actress plays Jon Favreau's estranged wife in Chef?",
"answ":"SOFIA VERGARA",
"answ2":"Sofía Vergara.",
},
{
"cat":"2010s",
"ques":"Who played FBI Special Agent Richard DesLauriers in 2016's Patriots Day?",
"answ":"KEVIN BACON",
"answ2":"Kevin Bacon.",
},
{
"cat":"2010s",
"ques":"In 21 Jump Street, who plays Deputy Chief Hardy who reassigns Schmidt and Jenko to Jump Street?",
"answ":"NICK OFFERMAN",
"answ2":"Nick Offerman.",
},
{
"cat":"2010s",
"ques":"Who played Dr. Martin Heiss, a paranormal debunker in 2016's Ghostbusters?",
"answ":"BILL MURRAY",
"answ2":"Bill Murray.",
},
{
"cat":"2010s",
"ques":"Who played Eddie's ski-jumping coach in Eddie the Eagle?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
},
{
"cat":"2010s",
"ques":"In 2016's The Edge of Seventeen, Nadine forms a special bond with one of her teachers Mr Bruner. Who plays Mr Bruner?",
"answ":"WOODY HARRELSON",
"answ2":"Woody Harrelson.",
},
{
"cat":"2010s",
"ques":"Who directed the 2011 sci-wi western Cowboys & Aliens?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
},
{
"cat":"2010s",
"ques":"Who played Michael Keaton's best friend and lawyer Jake in Birdman?",
"answ":"ZACH GALIFIANAKIS",
"answ3":"ZACH GALIFINAKIS",
"answ2":"Zach Galifianakis.",
},
{
"cat":"2010s",
"ques":"What 2015 comedy is based on a popular series of childrens books and stars Jack Black?",
"answ":"GOOSEBUMPS",
"answ2":"Goosebumps.",
},
{
"cat":"2010s",
"ques":"What 2015 crime drama was directed by Denis Villeneuve and starred Emily Blunt?",
"answ":"SICARIO",
"answ2":"Sicario.",
},
{
"cat":"2010s",
"ques":"Which 2010 film was based on a Hanna-Barbera series and featured the voice talents of Dan Aykroyd and Justin Timberlake?",
"answ":"YOGI BEAR",
"answ2":"Yogi Bear.",
},
{
"cat":"2010s",
"ques":"Who played R.L. Stine in Goosebumps?",
"answ":"JACK BLACK",
"answ2":"Jack Black.",
},
{
"cat":"2010s",
"ques":"What 2014 comedy stars Seth Rogen and James Franco as journalists recruited to assassinate Kim Jong-un?",
"answ":"THE INTERVIEW",
"answ2":"The Interview.",
},
{
"cat":"2010s",
"ques":"In Baby Driver, who played Baby's love interest Debora?",
"answ":"LILY JAMES",
"answ3":"LILY THOMSON",
"answ2":"Lily James.",
},
{
"cat":"2010s",
"ques":"What 2013 movie starred Jennifer Lawrence and Bradley Cooper?",
"answ":"AMERICAN HUSTLE",
"answ2":"American Hustle.",
},
{
"cat":"2010s",
"ques":"In Sherlock Holmes: A Game of Shadows, Mycroft is the ____ of Sherlock Holmes.",
"answ":"BROTHER",
"answ2":"Brother.",
},
{
"cat":"2010s",
"ques":"Jon Hamm and Kristen Wiig are in bed together at the beginning of what 2012 comedy?",
"answ":"BRIDESMAIDS",
"answ3":"BRIDEMAIDS",
"answ2":"Bridesmaids.",
},
{
"cat":"2010s",
"ques":"Who played Percy Jackson in the Percy Jackson films?",
"answ":"LOGAN LERMAN",
"answ2":"Logan Lerman.",
},
{
"cat":"2010s",
"ques":"What was the nickname of the aliens in Arrival?",
"answ":"ABOTT AND COSTELLO",
"answ3":"COSTELLO AND ABOTT",
"answ2":"Abott and Costello.",
},
{
"cat":"2010s",
"ques":"What traditionally comedic actor portrayed Steve Wozniak in 2015's Steve Jobs?",
"answ":"SETH ROGEN",
"answ3":"SETH ROGAN",
"answ2":"Seth Rogen.",
},
{
"cat":"2010s",
"ques":"Who played Ice Cube in the movie Straight Outta Compton?",
"answ":"O'SHEA JACKSON JR",
"answ3":"OMG",
"answ2":"O'Shea Jackson Jr/OMG.",
},
{
"cat":"2010s",
"ques":"What Star Wars star played Moses in the 2011 sci-fi film Attack the Block?",
"answ":"JOHN BOYEGA",
"answ2":"John Boyega.",
},
{
"cat":"2010s",
"ques":"Which 1982 horror movie received a remake in 2015?",
"answ":"POLTERGEIST",
"answ2":"Poltergeist.",
},
{
"cat":"2010s",
"ques":"Who portrayed King George VI in the Oscar-winning movie The King's Speech?",
"answ":"COLIN FIRTH",
"answ2":"Colin Firth.",
},
{
"cat":"2010s",
"ques":"What 2016 Richard Linklater film did he call 'the spiritual sequel' to Dazed and Confused?",
"answ":"EVERYBODY WANTS SOME",
"answ2":"Everybody Wants Some!!.",
},
{
"cat":"2010s",
"ques":"What former Punk'd star directed and starred in the 2017 action comedy CHiPs?",
"answ":"DAX SHEPARD",
"answ3":"DAX SHEPHERD",
"answ2":"Dax Shepard.",
},
{
"cat":"2010s",
"ques":"What actor played a corpse opposite Paul Dano's stranded character in Swiss Army Man?",
"answ":"DANIEL RADCLIFFE",
"answ3":"DANIEL RADCLIF",
"answ2":"Daniel Radcliffe.",
},
{
"cat":"2010s",
"ques":"In The Grand Budapest Hotel, Tony Revolori plays the lobby boy. What was his name?",
"answ":"ZERO",
"answ3":"ZERO MOUSTAFA",
"answ2":"Zero Moustafa.",
},
{
"cat":"2010s",
"ques":"Who played Michael Shannon's best friend Lucas in 2016's Midnight Special?",
"answ":"JOEL EDGERTON",
"answ3":"JOEL EDGARTON",
"answ2":"Joel Edgerton.",
},
{
"cat":"2010s",
"ques":"Who played the villainous Rita Repulsa in 2017's Power Rangers?",
"answ":"ELIZABETH BANKS",
"answ3":"ELISABETH BANKS",
"answ2":"Elizabeth Banks.",
},
{
"cat":"2010s",
"ques":"Who played the title character in 2017's King Arthur Legend of the Sword?",
"answ":"CHARLIE HUNNAM",
"answ2":"Charlie Hunnam.",
},
{
"cat":"2010s",
"ques":"Who directed 2014's Whiplash?",
"answ":"DAMIEN CHAZELLE",
"answ3":"DAMIAN CHAZELLE",
"answ2":"Damien Chazelle.",
},
{
"cat":"2010s",
"ques":"Who played Professor Arnold, who is kidnapped at the outset of the movie in Kingsman The Secret Service?",
"answ":"MARK HAMILL",
"answ2":"Mark Hamill.",
},
{
"cat":"2010s",
"ques":"What 2015 film starring Henry Cavill and Armie Hammer was a big screen adaptation of a 60s TV series?",
"answ":"THE MAN FROM UNCLE",
"answ3":"MAN FROM UNCLE",
"answ2":"The Man from U.N.C.L.E.",
},
{
"cat":"2010s",
"ques":"Who starred alongside Morgan Freeman and Michael Caine as a retiree planning to rob a bank in Going in Style?",
"answ":"ALAN ARKIN",
"answ2":"Alan Arkin.",
},
{
"cat":"2010s",
"ques":"What was the name of the demi-god played by The Rock in Disney's Moana?",
"answ":"MAUI",
"answ2":"Maui.",
},
{
"cat":"2010s",
"ques":"Who plays Gamemaker Plutarch Heavensbee in Catching Fire?",
"answ":"PHILIP SEYMOUR HOFFMAN",
"answ3":"PHILIP SEYMOUR HOFMAN",
"answ2":"Philip Seymour Hoffman.",
},
{
"cat":"2010s",
"ques":"In The Martian, what kind of vegetable does Mark Watney grow on Mars?",
"answ":"POTATO",
"answ3":"POTATOES",
"answ2":"Potato.",
},
{
"cat":"2010s",
"ques":"On Stranger Tides is the ____ entry in the Pirates of the Caribbean franchise.",
"answ":"4TH",
"answ3":"FOURTH",
"answ2":"Fourth.",
},
{
"cat":"2010s",
"ques":"Who voiced Shere Khan in 2016's The Jungle Book?",
"answ":"IDRIS ELBA",
"answ3":"IDRIS ALBA",
"answ2":"Idris Elba.",
},
{
"cat":"2010s",
"ques":"Which character was played by Josh Gad in the live-action Disney film Beauty and the Beast?",
"answ":"LEFOU",
"answ3":"LAFOU",
"answ2":"LeFou.",
},
{
"cat":"2010s",
"ques":"Texas Midland banks are being targeted by robbers in what 2016 flick?",
"answ":"HELL OR HIGH WATER",
"answ2":"Hell or High Water.",
},
{
"cat":"2010s",
"ques":"Matt Bomer played the assassin John Boy in what 2016 film?",
"answ":"THE NICE GUYS",
"answ3":"NICE GUYS",
"answ2":"The Nice Guys.",
},
{
"cat":"2010s",
"ques":"Death slowly walks toward whoever had sexual intercourse most recently in what 2015 thriller?",
"answ":"IT FOLLOWS",
"answ2":"It Follows.",
},
{
"cat":"2010s",
"ques":"In which 2010s comedy do teachers Charlie Day and Ice Cube have an impending face-off after school?",
"answ":"FIST FIGHT",
"answ2":"Fist Fight.",
},
{
"cat":"2010s",
"ques":"What actor played the albino mutant Caliban in Logan?",
"answ":"STEPHEN MERCHANT",
"answ3":"STEPHEN MERCHENT",
"answ2":"Stephen Merchant",
},
{
"cat":"2010s",
"ques":"Who voiced Disgust in Inside Out?",
"answ":"MINDY KALING",
"answ3":"MINDY KALLING",
"answ2":"Mindy Kaling.",
},
{
"cat":"2010s",
"ques":"Ralph Fiennes provided the voice to what character in The Lego Batman Movie?",
"answ":"ALFRED",
"answ3":"ALFRED PENNYWORTH",
"answ2":"Alfred Pennyworth.",
},
{
"cat":"2010s",
"ques":"What was the first name of Eddie Redmayne's character in Fantastic Beasts & Where to Find Them?",
"answ":"NEWT",
"answ2":"Newt.",
},
{
"cat":"2010s",
"ques":"What 2016 animated film features the songs 'Where You Are' and 'You're Welcome'?",
"answ":"MOANA",
"answ2":"Moana.",
},
{
"cat":"2010s",
"ques":"Who played Miss Peregrine in Miss Peregrine's Home for Peculiar Children?",
"answ":"EVA GREEN",
"answ2":"Eva Green.",
},
{
"cat":"2010s",
"ques":"What was the subtitle of the 2016 Teenage Mutant Ninja Turtles film?",
"answ":"OUT OF THE SHADOWS",
"answ2":"Out of the Shadows.",
},
{
"cat":"2010s",
"ques":"What film franchise saw a new chapter in 2016 entitled Origin of Evil?",
"answ":"OUIJA",
"answ2":"Ouija.",
},
{
"cat":"2010s",
"ques":"Who directed 2016's Passengers?",
"answ":"MORTEN TYLDUM",
"answ3":"MORTEN TILDUM",
"answ2":"Morten Tyldum.",
},
{
"cat":"2010s",
"ques":"Michael Fassbender romances whom in The Light Between Oceans?",
"answ":"ALICIA VIKANDER",
"answ2":"Alicia Vikander.",
},
{
"cat":"2010s",
"ques":"What actress stars as outside teen Casey in M. Night Shyamalan's Split?",
"answ":"ANYA TAYLOR JOY",
"answ2":"Anya Taylor-Joy.",
},
{
"cat":"2010s",
"ques":"J.A. Bayona directed which award-contending film which came out in limited release in 2016?",
"answ":"A MONSTER CALLS",
"answ2":"A Monster Calls.",
},
{
"cat":"2010s",
"ques":"In what 2010 film does Sylvester Stallone play a character named Barney Ross?",
"answ":"THE EXPENDABLES",
"answ3":"EXPENDABLES",
"answ2":"The Expendables.",
},
{
"cat":"2010s",
"ques":"Who played Howell, the drill sergeant of Andrew Garfield's character in Hacksaw Ridge?",
"answ":"VINCE VAUGHN",
"answ2":"Vince Vaughn.",
},
{
"cat":"2010s",
"ques":"Who starred as Amy Adams' boyfriend Gary in 2011's The Muppets?",
"answ":"JASON SEGEL",
"answ3":"JASON SIEGEL",
"answ2":"Jason Segel.",
},
{
"cat":"2010s",
"ques":"Mary Elizabeth Winstead played arctic-bound paleontologist Kate Lloyd in what 2011 thriller?",
"answ":"THE THING",
"answ2":"The Thing.",
},
];
var r2Q37 = [
{
"cat":"2010s",
"ques":"What is the first name of Leonardo DiCaprio's dead wife, played by Marion Cotillard in Inception?",
"answ":"MAL",
"answ2":"Mal.",
"option":["Mal", "Nadine", "Lena", "Alice"],
},
{
"cat":"2010s",
"ques":"Who directed Get Out?",
"answ":"JORDAN PEELE",
"answ2":"Jordan Peele.",
"option":["Jordan Peele", "James Wan", "Sam Raimi", "Spike Lee"],
},
{
"cat":"2010s",
"ques":"Who directed Arrival?",
"answ":"DENIS VILLENEUVE",
"answ3":"DENNIS VILLENEUVE",
"answ2":"Denis Villeneuve.",
"option":["Denis Villeneuve", "Spike Jonze", "Noah Baumbach", "Wes Anderson"],
},
{
"cat":"2010s",
"ques":"Hidden Figures is the inspirational story of 3 African-American women breaking new ground at what company?",
"answ":"NASA",
"answ2":"NASA.",
"option":["NASA", "Amazon", "Microsoft", "Apple"],
},
{
"cat":"2010s",
"ques":"In Arrival, in what U.S. state does the alien ship choose to park?",
"answ":"MONTANA",
"answ2":"Montana.",
"option":["Montana", "Kansas", "Utah", "Nebraska"],
},
{
"cat":"2010s",
"ques":"In Get Out, who did Chris' friend Rod work for?",
"answ":"TSA",
"answ3":"TRANSPORTATION SECURITY ADMINISTRATION",
"answ2":"The Transportation Security Administration (TSA).",
"option":["TSA", "FBI", "DMV", "FedEx"],
},
{
"cat":"2010s",
"ques":"In La La Land, to tease Sebastian what song did Mia request the 80s cover band to play at the party?",
"answ":"I RAN",
"answ2":"I Ran.",
"option":["I Ran", "Take On Me", "Beat It", "Sweet Dreams"],
},
{
"cat":"2010s",
"ques":"Who provided the voice for Barbara Gordon in The Lego Batman Movie?",
"answ":"ROSARIO DAWSON",
"answ2":"Rosario Dawson.",
"option":["Rosario Dawson", "Kerry Washington", "Tessa Thompson", "Jennifer Lopez"],
},
{
"cat":"2010s",
"ques":"In 2016's Snowden, who played the lead role of Edward Snowden?",
"answ":"JOSEPH GORDON LEVITT",
"answ3":"JOSEPH GORDON LEVIT",
"answ2":"Joseph Gordon-Levitt.",
"option":["Joseph Gordon-Levitt", "Ashton Kutcher", "Jesse Eisenberg", "Benedict Cumberbatch"],
},
{
"cat":"2010s",
"ques":"In Sing Street, what song do the boys shoot their first music video for?",
"answ":"THE RIDDLE OF THE MODEL",
"answ3":"RIDDLE OF THE MODEL",
"answ2":"The Riddle of the Model.",
"option":["The Riddle of the Model", "A Beautiful Sea", "Steppin' Out", "To Find You"],
},
{
"cat":"2010s",
"ques":"In Fantastic Beasts and Where to Find Them, who played the nefarious Percival Graves?",
"answ":"COLIN FARRELL",
"answ3":"COLIN FARELL",
"answ2":"Colin Farrell.",
"option":["Colin Farrell", "Ron Perlman", "Jon Voight", "Johnny Depp"],
},
{
"cat":"2010s",
"ques":"What stand-up comedian voices Snowball the bunny in The Secret Life Of Pets?",
"answ":"KEVIN HART",
"answ2":"Kevin Hart.",
"option":["Kevin Hart", "Chris Rock", "Adam Sandler", "Louis C.K."],
},
{
"cat":"2010s",
"ques":"Who played Judah Ben-Hur in 2016's Ben-Hur?",
"answ":"JACK HUSTON",
"answ2":"Jack Huston.",
"option":["Jack Huston", "Toby Kebbell", "Michiel Huisman", "Gerard Butler"],
},
{
"cat":"2010s",
"ques":"What was the subtitle for 2017's Underworld film?",
"answ":"BLOOD WARS",
"answ2":"Blood Wars.",
"option":["Blood Wars", "Awakening", "Endless War", "Evolution"],
},
{
"cat":"2010s",
"ques":"Who directed the critically acclaimed Hell or High Water?",
"answ":"DAVID MACKENZIE",
"answ2":"David Mackenzie.",
"option":["David Mackenzie", "Tom Ford", "Matt Ross", "Gavin O'Connor"],
},
{
"cat":"2010s",
"ques":"What actress plays Officer Saunders' wife in 2017's Patriots Day?",
"answ":"MICHELLE MONAGHAN",
"answ2":"Michelle Monaghan.",
"option":["Michelle Monaghan", "Kate Hudson", "Melissa Benoist", "Olivia Wilde"],
},
{
"cat":"2010s",
"ques":"In Moana, Maui tells Moana that sailing is called what?",
"answ":"WAYFINDING",
"answ2":"Wayfinding.",
"option":["Wayfinding", "Wavesurfing", "Pathseeking", "Outrigging"],
},
{
"cat":"2010s",
"ques":"Who played the Beast in 2017's Beauty and the Beast?",
"answ":"DAN STEVENS",
"answ2":"Dan Stevens.",
"option":["Dan Stevens", "Luke Evans", "Ewan McGregor", "Devon Sawa"],
},
{
"cat":"2010s",
"ques":"In 10 Cloverfield Lane, what beverage does Howard cool with the CO2 from an aerosol can?",
"answ":"VODKA",
"answ3":"WODKA",
"answ2":"Vodka.",
"option":["Vodka", "Chocolate Milk", "Whiskey", "Soda"],
},
{
"cat":"2010s",
"ques":"In Arrival, other than his wife's dying words what does General Shang give to Louise at the party?",
"answ":"PHONE NUMBER",
"answ3":"HIS PHONE NUMBER",
"answ2":"His phone number.",
"option":["His phone number", "His email address", "A commendation for her service", "His wife's phone number"],
},
{
"cat":"2010s",
"ques":"Who played the title character in the 2014 fantasy film Jack the Giant Slayer?",
"answ":"NICHOLAS HOULT",
"answ2":"Nicholas Hoult.",
"option":["Nicholas Hoult", "Ewan McGregor", "Jack O'Connell", "Sam Worthington"],
},
{
"cat":"2010s",
"ques":"Who provides the voice of the villain in Despicable Me 3?",
"answ":"TREY PARKER",
"answ2":"Trey Parker.",
"option":["Trey Parker", "Dennis Quaid", "Ed Harris", "Matt Stone"],
},
{
"cat":"2010s",
"ques":"Who played the lead character Desmond Doss in Hacksaw Ridge?",
"answ":"ANDREW GARFIELD",
"answ2":"Andrew Garfield.",
"option":["Andrew Garfield", "Nick Jonas", "Ed Skrein", "Tobey Maguire"],
},
{
"cat":"2010s",
"ques":"Who directed King Arthur Legend of the Sword?",
"answ":"GUY RITCHIE",
"answ2":"Guy Ritchie.",
"option":["Guy Ritchie", "James Gray", "David Ayer", "Ridley Scott"],
},
{
"cat":"2010s",
"ques":"What is the first name of Elizabeth Banks' character in Power Rangers?",
"answ":"RITA",
"answ2":"Rita.",
"option":["Rita", "Charlotte", "Sara", "Mary"],
},
{
"cat":"2010s",
"ques":"Who played Zeus in Percy Jackson & The Olympians?",
"answ":"SEAN BEAN",
"answ2":"Sean Bean.",
"option":["Sean Bean", "Pierce Brosnan", "Alan Rickman", "Liam Neeson"],
},
{
"cat":"2010s",
"ques":"In John Wick Chapter 2, in what European city does John find his target Gianna D'Antonio?",
"answ":"ROME",
"answ2":"Rome.",
"option":["Rome", "Paris", "Berlin", "Amsterdam"],
},
{
"cat":"2010s",
"ques":"Who plays the director of the Space Task Group, Al Harrison, in Hidden Figures?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
"option":["Kevin Costner", "Liam Neeson", "Dennis Quaid", "Ed Harris"],
},
{
"cat":"2010s",
"ques":"Who plays Pennywise in 2017's It?",
"answ":"BILL SKARSGARD",
"answ2":"Bill Skarsgård.",
"option":["Bill Skarsgård", "Gustaf Skarsgård", "Alexander Skarsgård", "Stellan Skarsgård"],
},
{
"cat":"2010s",
"ques":"In King Arthur Legend of the Sword, who played Arthur's father Uther?",
"answ":"ERIC BANA",
"answ2":"Eric Bana.",
"option":["Eric Bana", "Liam Neeson", "Anthony Hopkins", "Russell Crowe"],
},
{
"cat":"2010s",
"ques":"Who directed the Tom Cruise film American Made?",
"answ":"DOUG LIMAN",
"answ2":"Doug Liman.",
"option":["Doug Liman", "James Mangold", "Christopher McQuarrie", "Alex Kurtzman"],
},
{
"cat":"2010s",
"ques":"Who wrote and directed 2017's Wind River?",
"answ":"TAYLOR SHERIDAN",
"answ2":"Taylor Sheridan.",
"option":["Taylor Sheridan", "Denis Villeneuve", "Darren Aronofsky", "Alfonso Cuarón"],
},
{
"cat":"2010s",
"ques":"Who played racer Niki Lauda in the movie Rush?",
"answ":"DANIEL BRUHL",
"answ3":"DANIEL BRÜHL",
"answ2":"Daniel Brühl.",
"option":["Daniel Brühl", "Chris Hemsworth", "James Mangold", "Josh Brolin"],
},
{
"cat":"2010s",
"ques":"Who directed 2017's Murder on the Orient Express?",
"answ":"KENNETH BRANAGH",
"answ3":"KENNETH BRANAG",
"answ2":"Kenneth Branagh.",
"option":["Kenneth Branagh", "Gore Verbinski", "Joe Johnston", "Paul Feig"],
},
{
"cat":"2010s",
"ques":"Who directed the 2017 crime drama Detroit?",
"answ":"CATHERINE BIGELOW",
"answ3":"KATHRYN BIGELOW",
"answ2":"Kathryn Bigelow.",
"option":["Kathryn Bigelow", "Spike Lee", "Denzel Washington", "Patty Jenkins"],
},
{
"cat":"2010s",
"ques":"Who plays the first human born on Mars, Gardner Elliot in The Space Between Us?",
"answ":"ASA BUTTERFIELD",
"answ2":"Asa Butterfield.",
"option":["Asa Butterfield", "Logan Lerman", "Dylan O'Brien", "Tom Holland"],
},
{
"cat":"2010s",
"ques":"Who voiced the emoji Gene Meh in The Emoji Movie?",
"answ":"TJ MILLER",
"answ2":"T.J. Miller.",
"option":["T.J. Miller", "James Corden", "Jason Bateman", "Chris Parnell"],
},
{
"cat":"2010s",
"ques":"The Girl with the Dragon Tattoo, who played Henrik Vanger, the wealthy businessman who launches an extensive investigation into his family's affairs?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
"option":["Christopher Plummer", "Max von Sydow", "Donald Sutherland", "Stellan Skarsgard"],
},
{
"cat":"2010s",
"ques":"What famous actor cameos as an Asgardian playing Loki during a play in Thor Ragnarok?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
"option":["Matt Damon", "Sam Neill", "Liam Hemsworth", "Ryan Gosling"],
},
{
"cat":"2010s",
"ques":"What psychological horror-thriller starring Dane DeHaan and directed by Gore Verbinski was released in early 2017?",
"answ":"A CURE FOR WELLNESS",
"answ3":"CURE FOR WELLNESS",
"answ2":"A Cure For Wellness.",
"option":["A Cure For Wellness", "Bitter Harvest", "Don't Knock Twice", "Collide"],
},
{
"cat":"2010s",
"ques":"Set in Boston 1978, a meeting in a deserted warehouse between two gangs turns into a shootout and a game of survival in what film?",
"answ":"FREE FIRE",
"answ2":"Free Fire.",
"option":["Free Fire", "Sleight", "Aftermath", "Going in Style"],
},
{
"cat":"2010s",
"ques":"What actor has small roles as a thief in Baby Driver and the boyfriend of a murder victim in Wind River?",
"answ":"JON BERNTHAL",
"answ3":"JOHN BERNTHAL",
"answ2":"Jon Bernthal.",
"option":["Jon Bernthal", "Jeremy Renner", "Frank Grillo", "Eric Bana"],
},
{
"cat":"2010s",
"ques":"Bruce Greenwood plays the slimy President of the United States in what sequel released in September 2017?",
"answ":"KINGSMAN THE GOLDEN CIRCLE",
"answ3":"KINGSMEN THE GOLDEN CIRCLE",
"answ2":"Kingsman: The Golden Circle.",
"option":["Kingsman: The Golden Circle", "War for the Planet of the Apes", "Blade Runner 2049", "John Wick Chapter 2"],
},
{
"cat":"2010s",
"ques":"What is the profession of Charlie Sheen's character in Machete Kills?",
"answ":"PRESIDENT",
"answ3":"PRESIDENT OF THE UNITED STATES",
"answ2":"President of the United States.",
"option":["President of the United States", "Hitman", "Game-show host", "Martin Sheen impersonator"],
},
{
"cat":"2010s",
"ques":"Kate Winslet starred opposite Michael Fassbender in this 2015 biopic.",
"answ":"STEVE JOBS",
"answ2":"Steve Jobs.",
"option":["Steve Jobs", "The Mountain Between Us", "Spotlight", "Concussion"],
},
{
"cat":"2010s",
"ques":"In 2016's Lion, Saroo becomes seperated from his family after falling asleep where?",
"answ":"TRAIN",
"answ3":"A TRAIN",
"answ2":"Train.",
"option":["Train", "Boat", "Airport", "Bus"],
},
{
"cat":"2010s",
"ques":"In what US state does the movie Wind River take place?",
"answ":"WYOMING",
"answ2":"Wyoming.",
"option":["Wyoming", "Nebraska", "Alaska", "Texas"],
},
{
"cat":"2010s",
"ques":"Who plays Detective 'Big Nick' O'Brien in Den of Thieves?",
"answ":"GERARD BUTLER",
"answ2":"Gerard Butler.",
"option":["Gerard Butler", "Colin Farrell", "Frank Grillo", "Eric Bana"],
},
{
"cat":"2010s",
"ques":"Who directed Molly's Game?",
"answ":"AARON SORKIN",
"answ3":"ARON SORKIN",
"answ2":"Aaron Sorkin.",
"option":["Aaron Sorkin", "Bart Layton", "James Mangold", "Todd Phillips"],
},
{
"cat":"2010s",
"ques":"In The Commuter, who plays the mysterious woman who gives Liam Neeson his job and propels his life into chaos?",
"answ":"VERA FARMIGA",
"answ2":"Vera Farmiga.",
"option":["Vera Farmiga", "Elizabeth Banks", "Laura Dern", "Ruby Rose"],
},
{
"cat":"2010s",
"ques":"Who plays the villain Phoenix Buchanan in Paddington 2?",
"answ":"HUGH GRANT",
"answ2":"Hugh Grant.",
"option":["Hugh Grant", "Colin Firth", "Daniel Craig", "Christian Bale"],
},
{
"cat":"2010s",
"ques":"What 2017 awards contender has the tagline: 'There's no need to have class when you have talent'?",
"answ":"I TONYA",
"answ2":"I, Tonya.",
"option":["I, Tonya", "The Disaster Artist", "Phantom Thread", "Logan Lucky"],
},
{
"cat":"2010s",
"ques":"Who composed the score for Avengers Infinity War?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Patrick Doyle", "John Williams", "Brian Tyler"],
},
{
"cat":"2010s",
"ques":"In The Disaster Artist, who plays Greg Sestero's agent Iris Burton?",
"answ":"SHARON STONE",
"answ2":"Sharon Stone.",
"option":["Sharon Stone", "Alison Brie", "Jacki Weaver", "Megan Mullally"],
},
{
"cat":"2010s",
"ques":"In 2016's Lion, who plays Lucy, Saroo's girlfriend who he meets at university in Melbourne?",
"answ":"ROONEY MARA",
"answ2":"Rooney Mara.",
"option":["Rooney Mara", "Anne Hathaway", "Emily Blunt", "Kirsten Dunst"],
},
{
"cat":"2010s",
"ques":"Who stars as Nicole Kidman's eccentric daughter in Chan-Wook Park's 2013 indie thriller Stoker?",
"answ":"MIA WASIKOWSKA",
"answ2":"Mia Wasikowska.",
"option":["Mia Wasikowska", "Cara Delevingne", "Emma Roberts", "Chloë Grace Moretz"],
},
{
"cat":"2010s",
"ques":"Samuel L. Jackson played American entrepeneur George Washington Williams in this 2016 adventure film.",
"answ":"THE LEGEND OF TARZAN",
"answ3":"LEGEND OF TARZAN",
"answ2":"The Legend of Tarzan.",
"option":["The Legend of Tarzan", "Kong Skull Island", "The Mummy", "The Lost City of Z"],
},
{
"cat":"2010s",
"ques":"In 2018's Annihilation, what is the name given to the mysterious expanding zone where the rules of nature do not apply?",
"answ":"THE SHIMMER",
"answ3":"SHIMMER",
"answ2":"The Shimmer.",
"option":["The Shimmer", "The Shining", "The Zone", "The Shire"],
},
{
"cat":"2010s",
"ques":"In A Wrinkle in Time, who plays Meg's father, Dr. Alexander Murry, who mysteriously disappeared?",
"answ":"CHRIS PINE",
"answ2":"Chris Pine.",
"option":["Chris Pine", "Karl Urban", "Zach Galifianakis", "Robert Downey Jr."],
},
{
"cat":"2010s",
"ques":"Who played A.A. Milne in the film Goodbye Christopher Robin?",
"answ":"DOMHNALL GLEESON",
"answ3":"DOMNALL GLEESON",
"answ2":"Domhnall Gleeson.",
"option":["Domhnall Gleeson", "Eddie Redmayne", "Ben Whishaw", "Matthias Schoenaerts"],
},
{
"cat":"2010s",
"ques":"Who voices Chief, the leader of the main pack of alpha dogs, in Wes Anderson's Isle of Dogs?",
"answ":"BRYAN CRANSTON",
"answ2":"Bryan Cranston.",
"option":["Bryan Cranston", "Edward Norton", "Liev Schreiber", "Jeff Goldblum"],
},
{
"cat":"2010s",
"ques":"In Sam Raimi's Oz the Great and Powerful, who played Theodora who became the Wicked Witch of the West?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
"option":["Mila Kunis", "Natalie Portman", "Scarlett Johansson", "Eva Mendes"],
},
{
"cat":"2010s",
"ques":"In Crazy Rich Asians, before jetting off to Singapore with her wealthy boyfriend, Rachel Chu is shown to be a succesful NYU professor in what field?",
"answ":"ECONOMICS",
"answ2":"Economics.",
"option":["Economics", "Political Science", "Psychology", "Physics"],
},
{
"cat":"2010s",
"ques":"In The Incredibles 2, what kind of animal does Jack-Jack get into a backyard scuffle with?",
"answ":"RACCOON",
"answ2":"Raccoon.",
"option":["Raccoon", "Cat", "Fox", "Pigeon"],
},
{
"cat":"2010s",
"ques":"In Game Night, who plays Brooks, Jason Bateman's brother who sets up the interactive role-playing mystery game?",
"answ":"KYLE CHANDLER",
"answ2":"Kyle Chandler.",
"option":["Kyle Chandler", "Steve Carell", "James Marsden", "Bradley Cooper"],
},
{
"cat":"2010s",
"ques":"Who directed the 2018 film Love, Simon?",
"answ":"GREG BERLANTI",
"answ2":"Greg Berlanti.",
"option":["Greg Berlanti", "Jason Reitman", "Amy Heckerling", "Rob Reiner"],
},
{
"cat":"2010s",
"ques":"In Elysium, who plays agent Kruger, the loose cannon operative that will stop at nothing to retrieve the stolen data program?",
"answ":"SHARLTO COPLEY",
"answ2":"Sharlto Copley.",
"option":["Sharlto Copley", "Matt Damon", "Clive Owen", "Frank Grillo"],
},
{
"cat":"2010s",
"ques":"What actress played Sonia Kincaid, the wife of Samuel L. Jackson's character in The Hitman's Bodyguard?",
"answ":"SALMA HAYEK",
"answ3":"SELMA HAYEK",
"answ2":"Salma Hayek.",
"option":["Salma Hayek", "Mila Kunis", "Olivia Munn", "Penelope Cruz"],
},
{
"cat":"2010s",
"ques":"In BlacKkKlansman, who played John David Washington's undercover counterpart, Flip?",
"answ":"ADAM DRIVER",
"answ2":"Adam Driver.",
"option":["Adam Driver", "Adrien Brody", "Aaron Taylor-Johnson", "Topher Grace"],
},
{
"cat":"2010s",
"ques":"What 2018 action-comedy starred Mila Kunis and Kate McKinnon?",
"answ":"THE SPY WHO DUMPED ME",
"answ3":"SPY WHO DUMPED ME",
"answ2":"The Spy Who Dumped Me.",
"option":["The Spy Who Dumped Me", "Game Night", "Tag", "The Happytime Murders"],
},
{
"cat":"2010s",
"ques":"What 2018 historical drama stars Oscar Isaac and Ben Kingsley?",
"answ":"OPERATION FINALE",
"answ2":"Operation Finale.",
"option":["Operation Finale", "Sweet Country", "12 Strong", "Leave No Trace"],
},
{
"cat":"2010s",
"ques":"In Bumblebee, what does Charlie's mother get her for her birthday?",
"answ":"HELMET",
"answ3":"A HELMET",
"answ2":"Helmet.",
"option":["Helmet", "Bike", "Car", "Dog"],
},
{
"cat":"2010s",
"ques":"In Ant-Man and the Wasp, who plays old friend and former lab assistant to Hank Pym?",
"answ":"LAURENCE FISHBURNE",
"answ3":"LAWRENCE FISHBURNE",
"answ2":"Laurence Fishburne.",
"option":["Laurence Fishburne", "Louis Gossett Jr.", "Forest Whitaker", "Giancarlo Esposito"],
},
{
"cat":"2010s",
"ques":"Who plays Ted Kennedy in the drama Chappaquiddick?",
"answ":"JASON CLARKE",
"answ3":"JASON CLARK",
"answ2":"Jason Clarke.",
"option":["Jason Clarke", "Aaron Eckhart", "Joel Edgerton", "Clive Owen"],
},
{
"cat":"2010s",
"ques":"Which of New York City's boroughs is chosen as the location for the New Founding Fathers of America's initial social experiment in 2018's The First Purge?",
"answ":"STATEN ISLAND",
"answ2":"Staten Island.",
"option":["Staten Island", "The Bronx", "Queens", "Brooklyn"],
},
{
"cat":"2010s",
"ques":"What NBA All-Star player stars as the titular legendary streetballer in 2018's Uncle Drew?",
"answ":"KYRIE IRVING",
"answ2":"Kyrie Irving.",
"option":["Kyrie Irving", "Shaquille O'Neal", "Nate Robinson", "Reggie Miller"],
},
{
"cat":"2010s",
"ques":"What actress played mission Commander Lewis of Mark Watney's team in The Martian?",
"answ":"JESSICA CHASTAIN",
"answ2":"Jessica Chastain.",
"option":["Jessica Chastain", "Amy Adams", "Bryce Dallas Howard", "Nicole Kidman"],
},
{
"cat":"2010s",
"ques":"Who plays India, the daughter of Kidman's character in 2013's Stoker?",
"answ":"MIA WASIKOWSKA",
"answ2":"Mia Wasikowska.",
"option":["Mia Wasikowska", "Carey Mulligan", "Keira Knightley", "Saoirse Ronan"],
},
{
"cat":"2010s",
"ques":"In 2015's In the Heart of the Sea, who played author Herman Melville?",
"answ":"BEN WHISHAW",
"answ3":"BEN WISHAW",
"answ2":"Ben Whishaw.",
"option":["Ben Whishaw", "Chris Hemsworth", "Cilian Murphy", "Brendan Gleeson"],
},
{
"cat":"2010s",
"ques":"In Teen Titans Go! To the Movies!, what singer voices Tiger and sings the song 'Upbeat Inspirational Song About Life'?",
"answ":"MICHAEL BOLTON",
"answ2":"Michael Bolton.",
"option":["Michael Bolton", "Chris Isaak", "Tom Jones", "Tim McGraw"],
},
{
"cat":"2010s",
"ques":"What standup comedian plays a single woman that wants to adopt an athlete in Instant Family?",
"answ":"ILIZA SHLESINGER",
"answ3":"ILIZA SLESINGER",
"answ2":"Iliza Shlesinger.",
"option":["Iliza Shlesinger", "Tig Notaro", "Natasha Leggero", "Maria Bamford"],
},
{
"cat":"2010s",
"ques":"What is the name of the demon who prefers to inhabit the bodies of vulnerable males in Hereditary?",
"answ":"PAIMON",
"answ2":"Paimon.",
"option":["Paimon", "Abraxas", "Dagon", "Samael"],
},
{
"cat":"2010s",
"ques":"This 2018 movie takes place in San Jose, California and is completely told through computer and cell phone screens.",
"answ":"SEARCHING",
"answ2":"Searching.",
"option":["Searching", "Unsane", "Upgrade", "Vice"],
},
{
"cat":"2010s",
"ques":"In Mary Poppins Returns, who plays Michael Banks?",
"answ":"BEN WHISHAW",
"answ2":"Ben Whishaw.",
"option":["Ben Whishaw", "Tom Hiddleston", "James McAvoy", "Eddie Redmayne"],
},
{
"cat":"2010s",
"ques":"Who directed 2018's Mary Queen of Scots?",
"answ":"JOSIE ROURKE",
"answ2":"Josie Rourke.",
"option":["Josie Rourke", "Yorgos Lanthimos", "Ava DuVernay", "Rodrigo García"],
},
{
"cat":"2010s",
"ques":"In Overlord, the science lab is located beneath what kind of building?",
"answ":"CHURCH",
"answ2":"Church.",
"option":["Church", "Soccer stadium", "Police station", "Library"],
},
{
"cat":"2010s",
"ques":"Who plays Cassius 'Cash' Green in Sorry to Bother You?",
"answ":"LAKEITH STANFIELD",
"answ2":"Lakeith Stanfield.",
"option":["Lakeith Stanfield", "John Boyega", "Daniel Kaluuya", "Chadwick Boseman"],
},
{
"cat":"2010s",
"ques":"John C. Reilly and Steve Coogan shared the screen twice in 2018, one film was Stan & Ollie, what was the other?",
"answ":"HOLMES AND WATSON",
"answ2":"Holmes & Watson.",
"option":["Holmes & Watson", "The Sisters Brothers", "Ralph Breaks the Internet", "Hot Air"],
},
{
"cat":"2010s",
"ques":"In Game Night, Michelle thought she had hooked up for a one-night stand with what celebrity?",
"answ":"DENZEL WASHINGTON",
"answ2":"Denzel Washington.",
"option":["Denzel Washington", "Justin Timberlake", "Brad Pitt", "Liam Neeson"],
},
{
"cat":"2010s",
"ques":"Who played King Orm in Aquaman?",
"answ":"PATRICK WILSON",
"answ2":"Patrick Wilson.",
"option":["Patrick Wilson", "James Marsden", "Willem Dafoe", "Dolph Lundgren"],
},
{
"cat":"2010s",
"ques":"Who directed Welcome to Marwen?",
"answ":"ROBERT ZEMECKIS",
"answ2":"Robert Zemeckis.",
"option":["Robert Zemeckis", "Colin Trevorrow", "Adam McKay", "Bennett Miller"],
},
{
"cat":"2010s",
"ques":"You can find the character of Shank, voiced by Gal Gadot, and her game Slaughter Race, in what animated film?",
"answ":"RALPH BREAKS THE INTERNET",
"answ2":"Ralph Breaks the Internet.",
"option":["Ralph Breaks the Internet", "Inside Out", "The Emoji Movie", "Home"],
},
{
"cat":"2010s",
"ques":"Who plays Frank's wife, Dolores, in Green Book?",
"answ":"LINDA CARDELLINI",
"answ3":"LINDA CARDELINI",
"answ2":"Linda Cardellini.",
"option":["Linda Cardellini", "Katie Holmes", "Kate Beckinsale", "Rooney Mara"],
},
{
"cat":"2010s",
"ques":"In Creed II, who plays boxing trainer Tony 'Little Duke' Evers?",
"answ":"WOOD HARRIS",
"answ2":"Wood Harris.",
"option":["Wood Harris", "Russell Hornsby", "Colman Domingo", "Michael Beach"],
},
{
"cat":"2010s",
"ques":"Who stars alongside Kate Winslet as the other plane crash survivor in 2017's The Mountain Between Us?",
"answ":"IDRIS ELBA",
"answ3":"IDRIS ALBA",
"answ2":"Idris Elba.",
"option":["Idris Elba", "Chiwetel Ejiofor", "Chadwick Boseman", "Colman Domingo"],
},
{
"cat":"2010s",
"ques":"What smooth-jazz legend plays himself in A Bad Moms Christmas?",
"answ":"KENNY G",
"answ2":"Kenny G.",
"option":["Kenny G", "Richard Elliot", "Gerald Albright", "Kirk Whalum"],
},
{
"cat":"2010s",
"ques":"In what 2013 comedy does a character named Scottie P. get a misspelled tattoo saying 'No Ragrets'?",
"answ":"WE'RE THE MILLERS",
"answ3":"WE ARE THE MILLERS",
"answ2":"We're the Millers.",
"option":["We're the Millers", "The Internship", "The Hangover Part III", "Delivery Man"],
},
{
"cat":"2010s",
"ques":"Who plays Louis Creed, the father of Gage, in the 2019 version of Pet Semetary?",
"answ":"JASON CLARKE",
"answ3":"JASON CLARK",
"answ2":"Jason Clarke.",
"option":["Jason Clarke", "Joel Edgerton", "Jason Bateman", "Jai Courtney"],
},
{
"cat":"2010s",
"ques":"Who plays the billionaire Jack Morris who funds the underwater research facility that The Meg appears at?",
"answ":"RAIN WILSON",
"answ3":"RAINN WILSON",
"answ2":"Rainn Wilson.",
"option":["Rainn Wilson", "Dolph Lundgren", "Ken Watanabe", "Riz Ahmed"],
},
{
"cat":"2010s",
"ques":"BlacKkKlansman won Spike Lee his first ever Oscar. What award did he win?",
"answ":"BEST ADAPTED SCREENPLAY",
"answ3":"ADAPTED SCREENPLAY",
"answ2":"Best Adapted Screenplay.",
"option":["Best Adapted Screenplay", "Best Director", "Best Original Screenplay", "Best Editing"],
},
{
"cat":"2010s",
"ques":"Who voices Scar in 2019's The Lion King?",
"answ":"CHIWETEL EJIOFOR",
"answ3":"CHIWETEL EJOFOR",
"answ2":"Chiwetel Ejiofor.",
"option":["Chiwetel Ejiofor", "Djimon Hounsou", "John Kani", "Danny Glover"],
},
{
"cat":"2010s",
"ques":"Which Mission Impossible alumni played the villain Morgana, in The Kid Who Would Be King?",
"answ":"REBECCA FERGUSON",
"answ2":"Rebecca Ferguson.",
"option":["Rebecca Ferguson", "Vanessa Kirby", "Michelle Monaghan", "Simon Pegg"],
},
{
"cat":"2010s",
"ques":"What Oscar-winning actress plays Dr. Chiren, a master cyborg engineer in Alita: Battle Angel?",
"answ":"JENNIFER CONNELLY",
"answ3":"JENNIFER CONNOLLY",
"answ2":"Jennifer Connelly.",
"option":["Jennifer Connelly", "Cate Blanchett", "Rachel Weisz", "Tilda Swinton"],
},
{
"cat":"2010s",
"ques":"What is the title to the second Snow White and the Huntsman film?",
"answ":"THE HUNTSMAN WINTER'S WAR",
"answ3":"HUNTSMAN WINTER'S WAR",
"answ2":"The Huntsman: Winter's War.",
"option":["The Huntsman: Winter's War", "The Huntsman: Open Season", "The Huntsman: Snow White's Revenge", "The Huntsman: Happily Ever After"],
},
{
"cat":"2010s",
"ques":"In Hot Tub Time Machine 2, who plays a character who, after time travelling, becomes famous from stealing Black Eyed Peas songs for his own gain?",
"answ":"CRAIG ROBINSON",
"answ2":"Craig Robinson.",
"option":["Craig Robinson", "Rob Corddry", "John Cusack", "Bill Hader"],
},
{
"cat":"2010s",
"ques":"Which actress plays Molly, Jonah Hill's love interest, in 21 Jump Street?",
"answ":"BRIE LARSON",
"answ3":"BRIE LARSSON",
"answ2":"Brie Larson.",
"option":["Brie Larson", "Heather Graham", "Blake Lively", "Kirsten Dunst"],
},
{
"cat":"2010s",
"ques":"In the crime comedy Game Night, who plays Jason Bateman's brother who was kidnapped and must be found by Bateman and his friends?",
"answ":"KYLE CHANDLER",
"answ2":"Kyle Chandler.",
"option":["Kyle Chandler", "Jason Clarke", "James Marsden", "Sam Worthington"],
},
{
"cat":"2010s",
"ques":"Who directed 2014's Nightcrawler?",
"answ":"DAN GILROY",
"answ3":"DANIEL GILROY",
"answ2":"Dan Gilroy.",
"option":["Dan Gilroy", "Tony Gilroy", "Michael Mann", "Ridley Scott"],
},
{
"cat":"2010s",
"ques":"What Tom Hooper film was released in 2012?",
"answ":"LES MISERABLES",
"answ2":"Les Misérables.",
"option":["Les Misérables", "The King's Speech", "The Damned United", "The Danish Girl"],
},
{
"cat":"2010s",
"ques":"In Movie 43, Kate Winslet plays Beth, who goes on a blind date with a man that has a severe deformity. Who plays that man?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
"option":["Hugh Jackman", "Gerard Butler", "Jason Sudeikis", "Chris Pratt"],
},
{
"cat":"2010s",
"ques":"Michelle Williams appeared in two films in 2018, I Feel Pretty and _____?",
"answ":"VENOM",
"answ2":"Venom.",
"option":["Venom", "Mortal Engines", "Holmes & Watson", "Robin Hood"],
},
{
"cat":"2010s",
"ques":"In the remake of What Women Want, What Men Want, what is Ali Davis' profession?",
"answ":"SPORTS AGENT",
"answ2":"Sports agent.",
"option":["Sports agent", "Lawyer", "Psychologist", "Waitress"],
},
{
"cat":"2010s",
"ques":"Natalie Portman plays the warrior Isabel in what 2011 comedy?",
"answ":"YOUR HIGHNESS",
"answ2":"Your Highness.",
"option":["Your Highness", "Black Knight", "Paul", "The Green Hornet"],
},
{
"cat":"2010s",
"ques":"What Oscar-nominated actress played the lead in the 2013 film The Host?",
"answ":"SAOIRSE RONAN",
"answ3":"SAORSE RONAN",
"answ2":"Saoirse Ronan.",
"option":["Saoirse Ronan", "Jennifer Lawrence", "Shailene Woodley", "Scarlett Johansson"],
},

{
"cat":"2010s",
"ques":"2013's Beautiful Creatures takes place in what Southern US state?",
"answ":"SOUTH CAROLINA",
"answ2":"South Carolina.",
"option":["South Carolina", "Alabama", "Louisiana", "Mississippi"],
},
{
"cat":"2010s",
"ques":"Which actress is the lead in The Mortal Instruments: City of Bones?",
"answ":"LILY COLLINS",
"answ3":"LILLY COLLINS",
"answ2":"Lily Collins.",
"option":["Lily Collins", "Lily James", "Kaya Scodelario", "Cara Delavigne"],
},
{
"cat":"2010s",
"ques":"What 2019 film follows a young man who runs away from a care facility to make his dream of becoming a professional wrestler come true?",
"answ":"PEANUT BUTTER FALCON",
"answ3":"THE PEANUT BUTTER FALCON",
"answ2":"The Peanut Butter Falcon.",
"option":["The Peanut Butter Falcon", "After", "The Goldfinch", "Breakthrough"],
},
{
"cat":"2010s",
"ques":"The main events of The Nun take place at a monastery in what Eastern European country?",
"answ":"ROMANIA",
"answ2":"Romania.",
"option":["Romania", "Bulgaria", "Serbia", "Albania"],
},
{
"cat":"2010s",
"ques":"Marielle Heller directed what 2018 biopic starring Melissa McCarthy?",
"answ":"CAN YOU EVER FORGIVE ME",
"answ2":"Can You Ever Forgive Me?.",
"option":["Can You Ever Forgive Me?", "Kill the Messenger", "I, Tonya", "The Favourite"],
},
{
"cat":"2010s",
"ques":"Which MCU actor has small roles in the following films: The 5-Year Engagement, Zero Dark Thirty and Her?",
"answ":"CHRIS PRATT",
"answ2":"Chris Pratt.",
"option":["Chris Pratt", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
},
{
"cat":"2010s",
"ques":"What 2010s film opens with a big musical number on a Los Angeles freeway?",
"answ":"LA LA LAND",
"answ2":"La La Land.",
"option":["La La Land", "Cats", "Bohemian Rhapsody", "Rocketman"],
},
{
"cat":"2010s",
"ques":"Who played the character known as The Wise Man, who appears as a guiding force for the girls in their dream sequences, in 2011's Sucker Punch?",
"answ":"SCOTT GLENN",
"answ2":"Scott Glenn.",
"option":["Scott Glenn", "Oscar Isaac", "Jon Hamm", "Anthony Hopkins"],
},
{
"cat":"2010s",
"ques":"What 2014 film follows the character Riggan Thompson, as he tries to launch a Broadway adaptation of the short story What We Talk About When We Talk About Love?",
"answ":"BIRDMAN",
"answ3":"BIRDMAN OR THE UNEXPECTED VIRTUE OF IGNORANCE",
"answ2":"Birdman.",
"option":["Birdman", "Begin Again", "Collateral Beauty", "The Artist"],
},
{
"cat":"2010s",
"ques":"Which actor plays Lieutenant Colonel James Dolittle, who after completing air raids across Japan, ends up trapped in China in 2019's Midway?",
"answ":"AARON ECKHART",
"answ2":"Aaron Eckhart.",
"option":["Aaron Eckhart", "Nick Jonas", "Luke Evans", "Dennis Quaid"],
},
{
"cat":"2010s",
"ques":"Which actor plays Conall, the leader of a group of powerful fairies in Maleficent: Mistress of Evil?",
"answ":"CHIWETEL EJIOFOR",
"answ3":"CHIWETEL EJOFOR",
"answ2":"Chiwetel Ejiofor.",
"option":["Chiwetel Ejiofor", "Ed Skrein", "Idris Elba", "Robert Lindsay"],
},
{
"cat":"2010s",
"ques":"Who directed the 2019 remake of Black Christmas?",
"answ":"SOPHIA TAKAL",
"answ2":"Sophia Takal.",
"option":["Sophia Takal", "Jennifer Kent", "Leigh Janiak", "Karyn Kusama"],
},
{
"cat":"2010s",
"ques":"Who plays the adoptive mother of a young boy with otherworldly powers in Brightburn?",
"answ":"ELIZABETH BANKS",
"answ3":"ELISABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":["Elizabeth Banks", "Charlize Theron", "Amy Adams", "Toni Collette"],
},
{
"cat":"2010s",
"ques":"Who plays Roland Deschain in 2017's The Dark Tower?",
"answ":"IDRIS ELBA",
"answ3":"IDRIS ALBA",
"answ2":"Idris Elba.",
"option":["Idris Elba", "Chiwetel Ejiofor", "Michael B. Jordan", "Djimon Hounsou"],
},
{
"cat":"2010s",
"ques":"What 2014 film follows two teenage cancer patients named Hazel and Gus, as they fall in love?",
"answ":"THE FAULT IN OUR STARS",
"answ3":"FAULT IN OUR STARS",
"answ2":"The Fault in Our Stars.",
"option":["The Fault in Our Stars", "If I Stay", "The Best of Me", "Unbroken"],
},
{
"cat":"2010s",
"ques":"In Killer Joe, who plays 'Killer Joe' Cooper an assassin for hire?",
"answ":"MATTHEW MCCONAUGHEY",
"answ2":"Matthew McConaughey.",
"option":["Matthew McConaughey", "Emile Hirsch", "Thomas Hayden Church", "Josh Brolin"],
},
{
"cat":"2010s",
"ques":"Which actor plays the vampire Vladislav in What We Do in the Shadows?",
"answ":"JEMAINE CLEMENT",
"answ2":"Jemaine Clement.",
"option":["Jemaine Clement", "Taika Waititi", "Rhys Darby", "Jonny Brugh"],
},
{
"cat":"2010s",
"ques":"In 2014's If I Stay, Chloe Grace Moretz's character is taking lessons to become a professional player of what instrument?",
"answ":"CELLO",
"answ2":"Cello.",
"option":["Cello", "Violin", "Piano", "Trumpet"],
},
{
"cat":"2010s",
"ques":"Zoey Deutch stars as Samantha Kingston, a young woman that keeps waking up on Cupid's Day in which 2017 film?",
"answ":"BEFORE I FALL",
"answ2":"Before I Fall.",
"option":["Before I Fall", "Every Day", "Vampire Academy", "Paper Towns"],
},
{
"cat":"2010s",
"ques":"2017's Detroit depicts real-life riots which occured during what decade?",
"answ":"1960S",
"answ3":"60S",
"answ2":"1960s.",
"option":["1960s", "1970s", "1980s", "1990s"],
},
{
"cat":"2010s",
"ques":"In 2011's Young Adult, Charlize Theron plays a ghostwriter that has written several books in what genre?",
"answ":"YOUNG ADULT",
"answ3":"YA",
"answ2":"Young Adult.",
"option":["Young Adult", "Thriller", "Romance", "Mystery"],
},
];
tens = shuffle(tens);
r2Q37 = shuffle(r2Q37);