var monstermovies = [
{
"cat":"Monster Movies",
"ques":"In what year was The Water Horse: Legend of the Deep released?",
"answ":"2007",
"answ2":"2007.",
},
{
"cat":"Monster Movies",
"ques":"Which 1981 monster movie was directed by Sam Raimi and starred Bruce Campbell?",
"answ":"EVIL DEAD",
"answ2":"Evil Dead.",
},
{
"cat":"Monster Movies",
"ques":"Which 2000 monster movie was directed by David Twohy and starred Radha Mitchell and Vin Diesel?",
"answ":"PITCH BLACK",
"answ2":"Pitch Black.",
},
{
"cat":"Monster Movies",
"ques":"Which 1979 monster movie was directed by Ridley Scott and starred Sigourney Weaver?",
"answ":"ALIEN",
"answ2":"Alien.",
},
{
"cat":"Monster Movies",
"ques":"Which 2008 monster movie was directed by Matt Reeves and starred Mike Vogel?",
"answ":"CLOVERFIELD",
"answ2":"Cloverfield.",
},
{
"cat":"Monster Movies",
"ques":"Which 1954 monster movie was directed by Jack Arnold and starred Richard Carlson?",
"answ":"CREATURE FROM THE BLACK LAGOON",
"answ2":"Creature from the Black Lagoon.",
},
{
"cat":"Monster Movies",
"ques":"Which 1981 monster movie was directed by John Landis and starred David Naughton?",
"answ":"AN AMERICAN WEREWOLF IN LONDON",
"answ2":"An American Werewolf in London.",
},
{
"cat":"Monster Movies",
"ques":"Milla Jovovich and Tony Jaa star in what 2020 monster film directed by Paul W. S. Anderson?",
"answ":"MONSTER HUNTER",
"answ2":"Monster Hunter.",
},
{
"cat":"Monster Movies",
"ques":"Who portrays Count Dracula in the film Dracula 2000?",
"answ":"GERARD BUTLER",
"answ2":"Gerard Butler.",
},
{
"cat":"Monster Movies",
"ques":"Which Oscar-winning actor played the role of Abraham Van Helsing in Dracula 2000?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
},
{
"cat":"Monster Movies",
"ques":"Dylan O'Brien, Michael Rooker and Jessica Henwick star in what 2020 monster film?",
"answ":"LOVE AND MONSTERS",
"answ2":"Love and Monsters.",
},
{
"cat":"Monster Movies",
"ques":"In what 1954 Universal Monster film does an expedition searching for fossils along the Amazon River discover a prehistoric Gill-Man?",
"answ":"CREATURE FROM THE BLACK LAGOON",
"answ3":"THE CREATURE FROM THE BLACK LAGOON",
"answ2":"Creature from the Black Lagoon.",
},
{
"cat":"Monster Movies",
"ques":"Who played the role of Evelyn in The Mummy and The Mummy Returns?",
"answ":"RACHEL WEISZ",
"answ2":"Rachel Weisz.",
},
{
"cat":"Monster Movies",
"ques":"Claude Rains, Ralph Bellamy and Bela Lugosi have supporting roles in what 1941 Universal horror film?",
"answ":"THE WOLF MAN",
"answ2":"The Wolf Man.",
},
{
"cat":"Monster Movies",
"ques":"Who stars as a pilot named Raleigh Becket, in 2013's Pacific Rim?",
"answ":"CHARLIE HUNNAM",
"answ3":"CHARLY HUNNAM",
"answ2":"Charlie Hunnam.",
},
{
"cat":"Monster Movies",
"ques":"Which actress plays scientist Dr. Emma Russell, mother of Millie Bobby Brown's character, in Godzilla: King of the Monsters?",
"answ":"VERA FARMIGA",
"answ2":"Vera Farmiga.",
},
{
"cat":"Monster Movies",
"ques":"What iconic actor played Imhotep in 1932's The Mummy?",
"answ":"BORIS KARLOFF",
"answ2":"Boris Karloff.",
},
{
"cat":"Monster Movies",
"ques":"What is the subtitle of the 2019 Godzilla movie, directed by Michael Dougherty?",
"answ":"KING OF THE MONSTERS",
"answ3":"KING OF MONSTERS",
"answ2":"King of the Monsters.",
},
{
"cat":"Monster Movies",
"ques":"Which MCU actor plays James Conrad, leader of an expedition, in Kong: Skull Island?",
"answ":"TOM HIDDLESTON",
"answ2":"Tom Hiddleston.",
},
{
"cat":"Monster Movies",
"ques":"Which famous movie monster has been played by Robert De Niro, Christopher Lee and Aaron Eckhart?",
"answ":"FRANKENSTEIN'S MONSTER",
"answ2":"Frankenstein's Monster.",
},
{
"cat":"Monster Movies",
"ques":"Which actress plays teenager Madison Russell in Godzilla: King of the Monsters?",
"answ":"MILLIE BOBBY BROWN",
"answ2":"Millie Bobby Brown.",
},
{
"cat":"Monster Movies",
"ques":"Brendan Fraser and Rachel Weisz reteam against Arnold Vosloo's Mummy in what 2001 film?",
"answ":"THE MUMMY RETURNS",
"answ3":"MUMMY RETURNS",
"answ2":"The Mummy Returns.",
},
{
"cat":"Monster Movies",
"ques":"What famous Universal monster was portrayed by the actors Lon Chaney Jr. and Benicio Del Toro?",
"answ":"WOLFMAN",
"answ3":"THE WOLFMAN",
"answ2":"Wolfman.",
},
{
"cat":"Monster Movies",
"ques":"Kathryn Bigelow's Near Dark is about what kind of classic movie monster?",
"answ":"VAMPIRES",
"answ3":"VAMPIRE",
"answ2":"Vampires.",
},
{
"cat":"Monster Movies",
"ques":"Kevin Bacon plays the lead in what 1990 monster movie?",
"answ":"TREMORS",
"answ2":"Tremors.",
},
{
"cat":"Monster Movies",
"ques":"What is the name of the three-headed Kaiju that appears in Godzilla: King of the Monsters?",
"answ":"KING GHIDORAH",
"answ3":"KING GIDORAH",
"answ2":"King Ghidorah.",
},
{
"cat":"Monster Movies",
"ques":"Who directed Pacific Rim?",
"answ":"GUILLERMO DEL TORO",
"answ3":"GUILERMO DEL TORO",
"answ2":"Guillermo del Toro.",
},
{
"cat":"Monster Movies",
"ques":"Who played primate paleontologist Jack Prescott in 1976's King Kong?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
];
var r2Q40 = [
{
"cat":"Monster Movies",
"ques":"In 2014's Godzilla there was a nod to which famous Godzilla monster?",
"answ":"MOTHRA",
"answ2":"Mothra.",
"option":["Mothra", "Rodan", "King Ghidorah", "Battra"],
},
{
"cat":"Monster Movies",
"ques":"In what movie did the Scorpion King make his debut?",
"answ":"THE MUMMY RETURNS",
"answ3":"MUMMY RETURNS",
"answ2":"The Mummy Returns.",
"option":["The Mummy Returns", "The Mummy", "The Scorpion King", "The Mummy's Tomb"],
},
{
"cat":"Monster Movies",
"ques":"Who directed 2004's Van Helsing?",
"answ":"STEPHEN SOMMERS",
"answ2":"Stephen Sommers.",
"option":["Stephen Sommers", "Roland Emmerich", "Joel Schumacher", "John Woo"],
},
{
"cat":"Monster Movies",
"ques":"Who plays the female lead in the 1998 remake of Mighty Joe Young?",
"answ":"CHARLIZE THERON",
"answ2":"Charlize Theron.",
"option":["Charlize Theron", "Elizabeth Banks", "Kate Winslet", "Drew Barrymore"],
},
{
"cat":"Monster Movies",
"ques":"Who played Frankenstein's monster in 1994's Mary Shelley's Frankenstein?",
"answ":"ROBERT DE NIRO",
"answ3":"ROBERT DENIRO",
"answ2":"Robert De Niro.",
"option":["Robert De Niro", "John Cleese", "Kenneth Branagh", "Hugh Laurie"],
},
{
"cat":"Monster Movies",
"ques":"What franchise features an evil monster called Pinhead?",
"answ":"HELLRAISER",
"answ3":"HELL RAISER",
"answ2":"Hellraiser.",
"option":["Hellraiser", "The Evil Dead", "Godzilla", "The Conjuring"],
},
{
"cat":"Monster Movies",
"ques":"What is the subtitle of A Nightmare on Elm Street 3?",
"answ":"DREAM WARRIORS",
"answ2":"Dream Warriors.",
"option":["Dream Warriors", "Freddy's Revenge", "The Final Nightmare", "The Dream Child"],
},
{
"cat":"Monster Movies",
"ques":"Who directed 1987's The Monster Squad?",
"answ":"FRED DEKKER",
"answ2":"Fred Dekker.",
"option":["Fred Dekker", "Jan de Bont", "Wes Craven", "Shane Black"],
},
{
"cat":"Monster Movies",
"ques":"British actor Boris Karloff created a cinematic icon when he played the role of which monster?",
"answ":"FRANKENSTEIN'S MONSTER",
"answ3":"FRANKENSTEINS MONSTER",
"answ2":"Frankenstein's Monster.",
"option":["Frankenstein's Monster", "Dracula", "The Mummy", "Werewolf"],
},
{
"cat":"Monster Movies",
"ques":"In 2004's Van Helsing, what monster did Van Helsing find living in the cave below the burned down windmill?",
"answ":"FRANKSTEINS MONSTER",
"answ3":"FRANKENSTEIN'S MONSTER",
"answ2":"Frankenstein's monster.",
"option":["Frankenstein's monster", "Werewolf", "Vampire", "Mr. Hyde"],
},
{
"cat":"Monster Movies",
"ques":"Who directed the found footage monster film Cloverfield?",
"answ":"MATT REEVES",
"answ2":"Matt Reeves.",
"option":["Matt Reeves", "J. J. Abrams", "Drew Goddard", "Julius Onah"],
},
{
"cat":"Monster Movies",
"ques":"Who played Earl Bass in 1990's Tremors?",
"answ":"FRED WARD",
"answ2":"Fred Ward.",
"option":["Fred Ward", "James Coburn", "Michael Gross", "Tony Genaro"],
},
{
"cat":"Monster Movies",
"ques":"What 90s monster film stars Bill Pullman, Oliver Platt and Betty White?",
"answ":"LAKE PLACID",
"answ2":"Lake Placid.",
"option":["Lake Placid", "Tremors", "Alien Resurrection", "The Relic"],
},
{
"cat":"Monster Movies",
"ques":"Who played the lead, scientist Dr. Niko, in the 1998 sci-fi thriller Godzilla?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
"option":["Matthew Broderick", "Brendan Fraser", "Jeff Goldblum", "Ed Harris"],
},
{
"cat":"Monster Movies",
"ques":"What famous country music singer plays the wife in the survivalist couple, Heather Gummer in 1990's Tremors?",
"answ":"REBA MCENTIRE",
"answ3":"REBA MACENTIRE",
"answ2":"Reba McEntire.",
"option":["Reba McEntire", "Carrie Underwood", "Loretta Lynn", "Dolly Parton"],
},
{
"cat":"Monster Movies",
"ques":"What actor played the famed monster in I, Frankenstein?",
"answ":"AARON ECKHART",
"answ2":"Aaron Eckhart.",
"option":["Aaron Eckhart", "Edward Norton", "Clive Owen", "James McAvoy"],
},
{
"cat":"Monster Movies",
"ques":"Who played the ship's chef in 2005's King Kong?",
"answ":"ANDY SERKIS",
"answ2":"Andy Serkis.",
"option":["Andy Serkis", "Jack Black", "John Goodman", "Michael Peña"],
},
{
"cat":"Monster Movies",
"ques":"Which Straight Outta Compton cast member played geologist Houston Brooks in Kong: Skull Island?",
"answ":"COREY HAWKINS",
"answ2":"Corey Hawkins.",
"option":["Corey Hawkins", "O'Shea Jackson Jr.", "Jason Mitchell", "Aldis Hodge"],
},
{
"cat":"Monster Movies",
"ques":"Who directed 2014's Godzilla?",
"answ":"GARETH EDWARDS",
"answ2":"Gareth Edwards.",
"option":["Gareth Edwards", "Adam Wingard", "Michael Dougherty", "Jordan Vogt-Roberts"],
},
{
"cat":"Monster Movies",
"ques":"Who played US Navy officer Ford Brody in 2014's Godzilla?",
"answ":"AARON TAYLOR JOHNSON",
"answ2":"Aaron Taylor-Johnson.",
"option":["Aaron Taylor-Johnson", "Ezra Miller", "Joseph Gordon-Levitt", "Henry Cavill"],
},
{
"cat":"Monster Movies",
"ques":"Who played actress Ann Darrow in 2005's King Kong?",
"answ":"NAOMI WATTS",
"answ2":"Naomi Watts.",
"option":["Naomi Watts", "Jessica Chastain", "Kate Winslet", "Brie Larson"],
},
{
"cat":"Monster Movies",
"ques":"What year saw the release of I, Frankenstein?",
"answ":"2014",
"answ2":"2014.",
"option":["2014", "2011", "2012", "2015"],
},
{
"cat":"Monster Movies",
"ques":"Who played Van Helsing in 2004's Van Helsing?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
"option":["Hugh Jackman", "Edward Norton", "James McAvoy", "Henry Cavill"],
},
{
"cat":"Monster Movies",
"ques":"Who directed 2018's The Meg?",
"answ":"JON TURTELTAUB",
"answ3":"JOHN TURTELTAUB",
"answ2":"Jon Turteltaub.",
"option":["Jon Turteltaub", "Shane Black", "Roland Emmerich", "James Wan"],
},
{
"cat":"Monster Movies",
"ques":"What actress played the mummy in 2017's The Mummy?",
"answ":"SOFIA BOUTELLA",
"answ3":"SOPHIA BOUTELLA",
"answ2":"Sofia Boutella.",
"option":["Sofia Boutella", "Cara Delevingne", "Naomie Harris", "Naomi Scott"],
},
{
"cat":"Monster Movies",
"ques":"Who played Victor Frankenstein in 1994's Mary Shelley's Frankenstein?",
"answ":"KENNETH BRANAGH",
"answ3":"KENNETH BRANAUGH",
"answ2":"Kenneth Branagh.",
"option":["Kenneth Branagh", "John Cleese", "Liam Neeson", "Ian McShane"],
},
{
"cat":"Monster Movies",
"ques":"Who played former Jaeger pilot Jake Pentecost in Pacific Rim: Uprising?",
"answ":"JOHN BOYEGA",
"answ2":"John Boyega.",
"option":["John Boyega", "Michael B. Jordan", "Daniel Kaluuya", "Lakeith Stanfield"],
},
{
"cat":"Monster Movies",
"ques":"In Colossal, a giant monster attacks what Asian country whenever Anne Hathaway's character gets drunk?",
"answ":"SOUTH KOREA",
"answ2":"South Korea.",
"option":["South Korea", "Japan", "China", "Vietnam"],
},
{
"cat":"Monster Movies",
"ques":"What actress played photographer Mason Weaver in Kong: Skull Island?",
"answ":"BRIE LARSON",
"answ2":"Brie Larson.",
"option":["Brie Larson", "Naomie Watts", "Blake Lively", "Hilary Duff"],
},
{
"cat":"Monster Movies",
"ques":"In what state does 2019's Crawl take place?",
"answ":"FLORIDA",
"answ2":"Florida.",
"option":["Florida", "Alabama", "Georgia", "North Carolina"],
},
{
"cat":"Monster Movies",
"ques":"Mechagodzilla first appeared in what film?",
"answ":"GODZILLA VS MECHAGODZILLA",
"answ3":"GODZILLA VERSUS MECHAGODZILLA",
"answ2":"Godzilla vs Mechagodzilla.",
"option":["Godzilla vs Mechagodzilla", "Terror of Mechagodzilla", "Godzilla: Tokyo S.O.S.", "Godzilla Against Mechagodzilla"],
},
{
"cat":"Monster Movies",
"ques":"In Trick r' Treat, what is the name of the small boy in orange footie pajamas that terrorizes on old man throughout the film?",
"answ":"SAM",
"answ2":"Sam.",
"option":["Sam", "Damian", "George", "Steve"],
},
{
"cat":"Monster Movies",
"ques":"Who played screenwriter and hero Jack Driscoll in 2005's King Kong?",
"answ":"ADRIEN BRODY",
"answ3":"ADRIAN BRODY",
"answ2":"Adrien Brody.",
"option":["Adrien Brody", "Jack Black", "Luke Evans", "Colin Farrell"],
},
{
"cat":"Monster Movies",
"ques":"Excluding Godzilla himself, what monster has made the most appearances on film in the Godzilla universe?",
"answ":"MOTHRA",
"answ2":"Mothra.",
"option":["Mothra", "Rodan", "King Ghidorah", "Battra"],
},
{
"cat":"Monster Movies",
"ques":"What is the name of the 'domesticated' zombie who shoots Captain Rhodes in 1985's Day of the Dead?",
"answ":"BUB",
"answ2":"Bub.",
"option":["Bub", "Bud", "Bob", "Bart"],
},
{
"cat":"Monster Movies",
"ques":"Who played Frankenstein's Monster in 1931's Frankenstein?",
"answ":"BORIS KARLOFF",
"answ2":"Boris Karloff.",
"option":["Boris Karloff", "Henry Hull", "Lon Chaney Jr.", "Nelson Eddy"],
},
{
"cat":"Monster Movies",
"ques":"Who played Count Dracula in the 1992 gothic horror film Bram Stoker's Dracula?",
"answ":"GARY OLDMAN",
"answ2":"Gary Oldman.",
"option":["Gary Oldman", "Kiefer Sutherland", "Christopher Lee", "Gerard Butler"],
},
{
"cat":"Monster Movies",
"ques":"In 2013's Warm Bodies, who plays Julie's father and leader of the human survivors, Colonel Grigio?",
"answ":"JOHN MALKOVICH",
"answ2":"John Malkovich.",
"option":["John Malkovich", "Patrick Stewart", "Ed Harris", "Bruce Willis"],
},
{
"cat":"Monster Movies",
"ques":"Who played Charlize Theron's co-lead, Professor O'Hara in 1998's Mighty Joe Young?",
"answ":"BILL PAXTON",
"answ2":"Bill Paxton.",
"option":["Bill Paxton", "Jack Black", "Gerard Butler", "Denzel Washington"],
},
{
"cat":"Monster Movies",
"ques":"Who played the Mummy in the 2017 film?",
"answ":"SOFIA BOUTELLA",
"answ3":"SOPHIA BOUTELLA",
"answ2":"Sofia Boutella.",
"option":["Sofia Boutella", "Anya Taylor-Joy", "Chloe Bennet", "Cara Delevingne"],
},
{
"cat":"Monster Movies",
"ques":"What is the name of the 2016 film about an unemployed writer, Gloria, who is unwittingly causing a giant monster to wreak havoc halfway across the world?",
"answ":"COLOSSAL",
"answ3":"COLLOSAL",
"answ2":"Colossal.",
"option":["Colossal", "Giant", "Monster", "Havoc"],
},
{
"cat":"Monster Movies",
"ques":"What is the name of Raleigh Becket's Jaeger in Pacific Rim?",
"answ":"GIPSY DANGER",
"answ2":"Gipsy Danger.",
"option":["Gipsy Danger", "Coyote Tango", "Crimson Typhoon", "Brawler Yukon"],
},
{
"cat":"Monster Movies",
"ques":"What critically-acclaimed actor took over for Robert Englund as Freddy Krueger in the 2010 remake of A Nightmare on Elm Street?",
"answ":"JACKIE EARLE HALEY",
"answ3":"JACKIE EARL HALEY",
"answ2":"Jackie Earle Haley.",
"option":["Jackie Earle Haley", "Javier Bardem", "John Hawkes", "Thomas Haden Church"],
},
{
"cat":"Monster Movies",
"ques":"Who plays The Director in The Cabin in the Woods?",
"answ":"SIGOURNEY WEAVER",
"answ3":"SIGNOUREY WEAVER",
"answ2":"Sigourney Weaver.",
"option":["Sigourney Weaver", "Meryl Streep", "Jamie Lee Curtis", "Kate Winslet"],
},
{
"cat":"Monster Movies",
"ques":"This actor's first leading role in a feature film was as Steve Andrews in the 1958 version of The Blob.",
"answ":"STEVEN MCQUEEN",
"answ3":"STEVE MCQUEEN",
"answ2":"Steve McQueen.",
"option":["Steve McQueen", "Charles Bronson", "Robert Vaughn", "James Coburn"],
},
{
"cat":"Monster Movies",
"ques":"Which MCU actress plays the wife of Aaron Taylor-Johnson's character in 2014's Godzilla?",
"answ":"ELIZABETH OLSEN",
"answ3":"ELISABETH OLSEN",
"answ2":"Elizabeth Olsen.",
"option":["Elizabeth Olsen", "Brie Larson", "Scarlett Johansson", "Evangeline Lilly"],
},
{
"cat":"Monster Movies",
"ques":"Who was the original Wolf Man in 1941's The Wolf Man?",
"answ":"LON CHANEY JR",
"answ3":"LON CHANEY JUNIOR",
"answ2":"Lon Chaney Jr.",
"option":["Lon Chaney Jr.", "Boris Karloff", "Ricou Browning", "Bela Lugosi"],
},
{
"cat":"Monster Movies",
"ques":"In the Underworld franchise, what name is given to the vampires tasked with killing Lycans?",
"answ":"DEATH DEALERS",
"answ3":"DEATHDEALERS",
"answ2":"Death Dealers.",
"option":["Death Dealers", "Blood Servers", "Wolf Executioners", "Grave Diggers"],
},
{
"cat":"Monster Movies",
"ques":"In what 2010s film does Idris Elba say: 'Today we are cancelling the apocalypse'?",
"answ":"PACIFIC RIM",
"answ2":"Pacific Rim.",
"option":["Pacific Rim", "Godzilla", "Colossal", "The Meg"],
},
{
"cat":"Monster Movies",
"ques":"Who directed Dwayne Johnson in 2018's Rampage?",
"answ":"BRAD PEYTON",
"answ3":"BRETT PEYTON",
"answ2":"Brad Peyton.",
"option":["Brad Peyton", "Rawson Marshall Thurber", "David Leitch", "F. Gary Gray"],
},
{
"cat":"Monster Movies",
"ques":"In how many films did Bela Lugosi play Dracula?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "3", "4", "5"],
},
{
"cat":"Monster Movies",
"ques":"What 1986 film features a dangerous alien race known as Krites, who hijack their prison ship and crash land it in Kansas?",
"answ":"CRITTERS",
"answ2":"Critters.",
"option":["Critters", "Tremors", "Jeepers Creepers", "Dwellers"],
},
{
"cat":"Monster Movies",
"ques":"Who plays Julie, the girl who was rescued by a zombie in Warm Bodies?",
"answ":"TERESA PALMER",
"answ3":"THERESA PALMER",
"answ2":"Teresa Palmer.",
"option":["Teresa Palmer", "Chloe Grace Moretz", "Emma Roberts", "Amber Heard"],
},
{
"cat":"Monster Movies",
"ques":"What 1974 film from director Larry Cohen involves a mutant newborn baby who goes on a killing rampage?",
"answ":"IT'S ALIVE",
"answ2":"It's Alive.",
"option":["It's Alive", "The Creature", "Mutant", "The Baby"],
},
{
"cat":"Monster Movies",
"ques":"What actor played Jesse Hooker, the leader of a clan of vampires in 1987's Near Dark?",
"answ":"LANCE HENRIKSEN",
"answ2":"Lance Henriksen.",
"option":["Lance Henriksen", "Clancy Brown", "Willem Dafoe", "Kiefer Sutherland"],
},
{
"cat":"Monster Movies",
"ques":"In what country is the safe zone to where the survivors escape in World War Z?",
"answ":"CANADA",
"answ2":"Canada.",
"option":["Canada", "Israel", "Mexico", "South Korea"],
},
{
"cat":"Monster Movies",
"ques":"Which 1931 monster movie was directed by Rouben Mamoulian and starred Fredric March?",
"answ":"DR JEKYLL AND MR HYDE",
"answ2":"Dr. Jekyll and Mr. Hyde.",
"option":["Dr. Jekyll and Mr. Hyde", "Son of Frankenstein", "Island of Lost Souls", "Dracula"],
},
{
"cat":"Monster Movies",
"ques":"At the opening of Van Helsing, Frankenstein creates his monster while he is a guest in whose home?",
"answ":"DRACULA",
"answ3":"COUNT DRACULA",
"answ2":"Dracula.",
"option":["Dracula", "Dr. Jekyll", "The Invisible Man", "Stanis Khol/The Wolfman"],
},
{
"cat":"Monster Movies",
"ques":"Which 1981 monster movie was directed by Matthew Robbins and starred Peter MacNicol?",
"answ":"DRAGONSLAYER",
"answ2":"Dragonslayer.",
"option":["Dragonslayer", "Night of the Lepus", "Legend", "Jaws"],
},
{
"cat":"Monster Movies",
"ques":"Which 1931 monster movie was directed by James Whale and starred Colin Clive?",
"answ":"FRANKENSTEIN",
"answ2":"Frankenstein.",
"option":["Frankenstein", "The Wolf Man", "The Invisible Man", "The Mummy"],
},
{
"cat":"Monster Movies",
"ques":"Which 1954 monster movie was directed by Ishiro Honda and starred Takashi Shimura?",
"answ":"GODZILLA",
"answ2":"Godzilla.",
"option":["Godzilla", "Q", "The Fly", "Island of Lost Souls"],
},
{
"cat":"Monster Movies",
"ques":"What fake species of sandworm is the villain in Tremors?",
"answ":"GRABOID",
"answ2":"Graboid.",
"option":["Graboid", "Sublid", "Terreborg", "Cherimus"],
},
{
"cat":"Monster Movies",
"ques":"Who plays the re-animated Elizabeth, who sets herself on fire in Kenneth Branagh's adaptation of Frankenstein?",
"answ":"HELENA BONHAM CARTER",
"answ2":"Helena Bonham Carter.",
"option":["Helena Bonham Carter", "Emma Thompson", "Uma Thurman", "Gwyneth Paltrow"],
},
{
"cat":"Monster Movies",
"ques":"Which 1987 monster movie was directed by Clive Barker and starred Andrew Robinson?",
"answ":"HELLRAISER",
"answ2":"Hellraiser.",
"option":["Hellraiser", "Nightbreed", "The Monster Squad", "Friday the 13th"],
},
{
"cat":"Monster Movies",
"ques":"Which 2001 monster movie was directed by Victor Salva and starred Gina Philips?",
"answ":"JEEPERS CREEPERS",
"answ2":"Jeepers Creepers.",
"option":["Jeepers Creepers", "The Monster Squad", "Tremors", "Q"],
},
{
"cat":"Monster Movies",
"ques":"Which 1999 monster movie was directed by Steve Miner and starred Bridget Fonda?",
"answ":"LAKE PLACID",
"answ2":"Lake Placid.",
"option":["Lake Placid", "Gremlins", "Tremors", "Swamp Thing"],
},
{
"cat":"Monster Movies",
"ques":"Which 1993 monster movie was directed by Mark Jones and starred Warwick Davis?",
"answ":"LEPRECHAUN",
"answ2":"Leprechaun.",
"option":["Leprechaun", "Scrooged", "Gremlins", "Home for the Holidays"],
},
{
"cat":"Monster Movies",
"ques":"Who directed Jack Nicholson in Wolf?",
"answ":"MIKE NICHOLS",
"answ2":"Mike Nichols.",
"option":["Mike Nichols", "John Landis", "Ivan Reitman", "Harold Ramis"],
},
{
"cat":"Monster Movies",
"ques":"Which 1972 movie was directed by William F. Claxton and starred Stuart Whitman and Janet Leigh?",
"answ":"NIGHT OF THE LEPUS",
"answ2":"Night of the Lepus.",
"option":["Night of the Lepus", "The Brood", "Wolfen", "Anaconda"],
},
{
"cat":"Monster Movies",
"ques":"Which 1990 monster movie was directed by Clive Barker and starred Craig Sheffer?",
"answ":"NIGHTBREED",
"answ2":"Nightbreed.",
"option":["Nightbreed", "Hellraiser", "The Resurrected", "Candyman"],
},
{
"cat":"Monster Movies",
"ques":"What's the name of the magazine Veronica writes for in The Fly?",
"answ":"PARTICLE",
"answ2":"Particle.",
"option":["Particle", "Element", "Molecule", "Ion"],
},
{
"cat":"Monster Movies",
"ques":"Which 1978 monster movie was directed by Joe Dante and starred Bradford Dillman?",
"answ":"PIRANHA",
"answ2":"Piranha.",
"option":["Piranha", "Dragonslayer", "Island of Lost Souls", "An American Werewolf in London"],
},
{
"cat":"Monster Movies",
"ques":"In what 1980s movie does Kevin Peter Hall have dual credit as a helicopter pilot and the title monster?",
"answ":"PREDATOR",
"answ2":"Predator.",
"option":["Predator", "Alien", "Godzilla", "Pumpkinhead"],
},
{
"cat":"Monster Movies",
"ques":"Which 1982 monster movie was directed by Larry Cohen and starred Michael Moriarty and David Carradine?",
"answ":"Q",
"answ3":"Q THE WINGED SERPENT",
"answ2":"Q.",
"option":["Q", "Jaws", "The Blob", "Island of Lost Souls"],
},
{
"cat":"Monster Movies",
"ques":"Which 1985 monster movie was directed by Stuart Gordon and starred Jeffrey Combs?",
"answ":"RE ANIMATOR",
"answ2":"Re-Animator.",
"option":["Re-Animator", "Lake Placid", "Jurassic Park", "Jaws"],
},
{
"cat":"Monster Movies",
"ques":"Pumpkinhead was the first of only two films directed by what Hollywood special effects legend?",
"answ":"STAN WINSTON",
"answ2":"Stan Winston.",
"option":["Stan Winston", "Rick Baker", "Ray Harryhausen", "Tom Savini"],
},
{
"cat":"Monster Movies",
"ques":"Which 1982 monster movie was directed by Wes Craven and starred Louis Jourdan?",
"answ":"SWAMP THING",
"answ2":"Swamp Thing.",
"option":["Swamp Thing", "The Mist", "Gremlins", "Night of the Lepus"],
},
{
"cat":"Monster Movies",
"ques":"Which 1958 monster movie was directed by Irvin S. Yeaworth Jr. and starred Steve McQueen?",
"answ":"THE BLOB",
"answ2":"The Blob.",
"option":["The Blob", "Re-Animator", "Swamp Thing", "Q"],
},
{
"cat":"Monster Movies",
"ques":"Which 2006 monster movie was directed by Bong Joon-ho and starred Kang-ho Song?",
"answ":"THE HOST",
"answ2":"The Host.",
"option":["The Host", "The Day of the Triffids", "Hellraiser", "The Wolf Man"],
},
{
"cat":"Monster Movies",
"ques":"Which 1987 monster movie was directed by Fred Dekker and starred Andre Gower?",
"answ":"THE MONSTER SQUAD",
"answ3":"MONSTER SQUAD",
"answ2":"The Monster Squad.",
"option":["The Monster Squad", "Pete's Dragon", "Island of Lost Souls", "The Blob"],
},
{
"cat":"Monster Movies",
"ques":"Which 1959 monster movie was directed by Terence Fisher and starred Peter Cushing?",
"answ":"THE MUMMY",
"answ2":"The Mummy.",
"option":["The Mummy", "The Howling", "Jaws", "Legend"],
},
{
"cat":"Monster Movies",
"ques":"Which 1985 monster movie was directed by Larry Cohen and starred Michael Moriarty?",
"answ":"THE STUFF",
"answ2":"The Stuff.",
"option":["The Stuff", "Re-Animator", "Piranha", "Jaws"],
},
{
"cat":"Monster Movies",
"ques":"Which 1987 comedy is about a suburban family who take Bigfoot in as a houseguest?",
"answ":"HARRY AND THE HENDERSONS",
"answ2":"Harry and the Hendersons.",
"option":["Harry and the Hendersons", "The Legend of Boggy Creek", "Cry Wilderness", "Yeti: A Love Story"],
},
{
"cat":"Monster Movies",
"ques":"In Kong: Skull Island, what is the name of the organization that is trying to prove the existence of monsters?",
"answ":"MONARCH",
"answ2":"Monarch.",
"option":["Monarch", "Prodigium", "Venture", "Crypt"],
},
{
"cat":"Monster Movies",
"ques":"In Clive Barker’s Nightbreed, which famous horror director plays a psychologist and serial killer who goes to war with the monsters?",
"answ":"DAVID CRONENBERG",
"answ2":"David Cronenberg.",
"option":["David Cronenberg", "John Carpenter", "Tobe Hooper", "Wes Craven"],
},
];
monstermovies = shuffle(monstermovies);
r2Q40 = shuffle(r2Q40);