var r2Q45 = [
{
"cat":"Kevin Smith",
"ques":"Who starred as Jay's estranged daughter Milly in Jay and Silent Bob Reboot?",
"answ":"HARLEY QUINN SMITH",
"answ2":"Harley Quinn Smith.",
"option":["Harley Quinn Smith", "Selena Gomez", "Chloë Grace Moretz", "Lily-Rose Depp"],
},
{
"cat":"Kevin Smith",
"ques":"Which Kevin Smith film has the tagline 'They're not there to shop. - They're not there to work. - They're just there.'?",
"answ":"MALLRATS",
"answ2":"Mallrats.",
"option":["Mallrats", "Clerks", "Clerks II", "Clerks III"],
},
{
"cat":"Kevin Smith",
"ques":"In which Wes Craven directed Scream film do Kevin Smith and Jason Mewes appear as Jay and Silent Bob?",
"answ":"SCREAM 3",
"answ2":"Scream 3.",
"option":["Scream 3", "Scream", "Scream 2", "Scream 4"],
},
{
"cat":"Kevin Smith",
"ques":"Which Kevin Smith film featured the tagline 'Hollywood had it coming'?",
"answ":"JAY AND SILENT BOB STRIKE BACK",
"answ2":"Jay and Silent Bob Strike Back.",
"option":["Jay and Silent Bob Strike Back", "Jay and Silent Bob Reboot", "Clerks II", "Clerks III"],
},
{
"cat":"Kevin Smith",
"ques":"Kevin Smith, Jason Mewes, Carrie Fisher, and William Shatner all cameo in what 2009 comedy with the tagline 'Never tell them the odds.'?",
"answ":"FANBOYS",
"answ2":"Fanboys.",
"option":["Fanboys", "The Hangover", "Zombieland", "The Proposal"],
},
{
"cat":"Kevin Smith",
"ques":"Which actress played the main lead Gray, opposite Kevin Smith and Timothy Olyphant, in the romantic comedy Catch and Release?",
"answ":"JENNIFER GARNER",
"answ2":"Jennifer Garner.",
"option":["Jennifer Garner", "Katie Holmes", "Reese Witherspoon", "Hilary Duff"],
},
{
"cat":"Kevin Smith",
"ques":"In Mallrats, what Florida theme park is T.S. planning to take Brandi to in order to propose to her, to which Brodie says 'That's the most romantic thing I've ever heard.'?",
"answ":"UNIVERSAL STUDIOS FLORIDA",
"answ3":"UNIVERSAL STUDIOS",
"answ2":"Universal Studios.",
"option":["Universal Studios", "Walt Disney World", "Dinosaur World", "Adventure Island"],
},
{
"cat":"Kevin Smith",
"ques":"Which Kevin Smith film features Ralph Garman, Michael Parks, John Goodman, and Stephen Root?",
"answ":"RED STATE",
"answ2":"Red State.",
"option":["Red State", "Tusk", "Yoga Hosers", "Clerks III"],
},
{
"cat":"Kevin Smith",
"ques":"Of the following actors, who doesn't appear in Kevin Smith's Clerks II: Rosario Dawson, Wanda Sykes, Matt Damon, or Jason Lee?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
"option":["Matt Damon", "Rosario Dawson", "Jason Lee", "Wanda Sykes"],
},
{
"cat":"Kevin Smith",
"ques":"In Yoga Hosers, what do the media dub the Colleens after they save everyone from the potential Bratzi takeover and clear their names?",
"answ":"HERO CLERKS",
"answ2":"Hero Clerks.",
"option":["Hero Clerks", "Super Clerks", "Wonder Clerks", "Miracle Clerks"],
},
{
"cat":"Kevin Smith",
"ques":"Which actor says the following line in Jay and Silent Bob Strike Back: 'Oh, you're the executive producer. Well, why don't you executive produce me a latte'?",
"answ":"CHRIS ROCK",
"answ2":"Chris Rock.",
"option":["Chris Rock", "Kevin Smith", "Jason Lee", "Ben Affleck"],
},
{
"cat":"Kevin Smith",
"ques":"What actress stars as Becky, manager of the fast food restaurant Mooby's, in Clerks II?",
"answ":"ROSARIO DAWSON",
"answ2":"Rosario Dawson.",
"option":["Rosario Dawson", "Jennifer Garner", "Jennifer Schwalbach", "Charlize Theron"],
},
{
"cat":"Kevin Smith",
"ques":"Who plays Brodie Bruce, an unemployed, lazy, comic book-obsessed slacker, in Mallrats?",
"answ":"JASON LEE",
"answ2":"Jason Lee.",
"option":["Jason Lee", "Ben Affleck", "Kevin Smith", "Michael Rooker"],
},
{
"cat":"Kevin Smith",
"ques":"Who played God in Dogma?",
"answ":"ALANIS MORISSETTE",
"answ3":"ALANIS MORISETTE",
"answ2":"Alanis Morissette.",
"option":["Alanis Morissette", "Megan Fox", "Morgan Freeman", "Pamela Anderson"],
},
{
"cat":"Kevin Smith",
"ques":"What comedy legend starred as Cardinal Glick in Kevin Smith's Dogma?",
"answ":"GEORGE CARLIN",
"answ2":"George Carlin.",
"option":["George Carlin", "Mel Brooks", "John Cleese", "Richard Pryor"],
},
{
"cat":"Kevin Smith",
"ques":"Kevin Smith directed what 2011 horror thriller about a group of teens who encounter fundamentalists with an incredibly sinister agenda?",
"answ":"RED STATE",
"answ2":"Red State.",
"option":["Red State", "Don't Be Afraid of the Dark", "Fright Night", "You're Next"],
},
{
"cat":"Kevin Smith",
"ques":"Who plays Chaka King, the director of the Bluntman and Chronic film, in Jay and Silent Bob Strike Back?",
"answ":"CHRIS ROCK",
"answ2":"Chris Rock.",
"option":["Chris Rock", "Eddie Murphy", "Jordan Peele", "Morgan Freeman"],
},
{
"cat":"Kevin Smith",
"ques":"Who stars as Holden McNeil, a comic book artist hopelessly in love with a lesbian in 1997's Chasing Amy",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
"option":["Ben Affleck", "Jason Lee", "Matt Damon", "James Marsden"],
},
{
"cat":"Kevin Smith",
"ques":"What was the first film directed by Kevin Smith?",
"answ":"CLERKS",
"answ2":"Clerks.",
"option":["Clerks", "Mallrats", "Chasing Amy", "Jersey Girl"],
},
{
"cat":"Kevin Smith",
"ques":"Will Smith makes a cameo as himself in what Kevin Smith movie?",
"answ":"JERSEY GIRL",
"answ2":"Jersey Girl.",
"option":["Jersey Girl", "Clerks", "Jay and Silent Bob Reboot", "Jay and Silent Bob Strike Back"],
},
{
"cat":"Kevin Smith",
"ques":"This Kevin Smith film starred Ben Affleck and Matt Damon as fallen angels.",
"answ":"DOGMA",
"answ2":"Dogma.",
"option":["Dogma", "Mallrats", "Clerks II", "Jay and Silent Bob Strike Back"],
},
{
"cat":"Kevin Smith",
"ques":"What was the first film in which Kevin Smith played the character Silent Bob?",
"answ":"CLERKS",
"answ2":"Clerks.",
"option":["Clerks", "Mallrats", "Chasing Amy", "Dogma"],
},
{
"cat":"Kevin Smith",
"ques":"In what Marvel film does Kevin Smith have a small role as a forensic assistant named Jack Kirby?",
"answ":"DAREDEVIL",
"answ2":"Daredevil.",
"option":["Daredevil", "Spider-Man", "Hulk", "Doctor Strange"],
},
{
"cat":"Kevin Smith",
"ques":"What Kevin Smith film stars Justin Long as a character named Wallace Bryton?",
"answ":"TUSK",
"answ2":"Tusk.",
"option":["Tusk", "Cop Out", "Yoga Hosers", "Jersey Girl"],
},
{
"cat":"Kevin Smith",
"ques":"In Jersey Girl, who plays graduate student Maya who befriends Ben Affleck's character?",
"answ":"LIV TYLER",
"answ2":"Liv Tyler.",
"option":["Liv Tyler", "Jennifer Lopez", "Courtney Cox", "Jennifer Garner"],
},
{
"cat":"Kevin Smith",
"ques":"Who was Bruce Willis' co-lead in the Kevin Smith directed action-comedy Cop Out?",
"answ":"TRACY MORGAN",
"answ2":"Tracy Morgan.",
"option":["Tracy Morgan", "Kevin James", "Paul Rudd", "Martin Lawrence"],
},
{
"cat":"Kevin Smith",
"ques":"Who played Dante Hicks in Clerks?",
"answ":"BRIAN O'HALLORAN",
"answ3":"BRYAN O'HALLORAN",
"answ2":"Brian O'Halloran.",
"option":["Brian O'Halloran", "Scott Mosier", "Jason Mewes", "Jeff Anderson"],
},
{
"cat":"Kevin Smith",
"ques":"Michael Rooker stars as an evil father in which Kevin Smith film?",
"answ":"MALLRATS",
"answ2":"Mallrats.",
"option":["Mallrats", "Clerks", "Jersey Girl", "Dogma"],
},
{
"cat":"Kevin Smith",
"ques":"In Dogma, what kind of creature was Salma Hayek's Serendipity?",
"answ":"MUSE",
"answ2":"Muse.",
"option":["Muse", "Angel", "Seraphim", "Golgothan"],
},
{
"cat":"Kevin Smith",
"ques":"What is the name of the store in Clerks?",
"answ":"QUICK STOP",
"answ3":"QUICKSTOP",
"answ2":"Quick Stop.",
"option":["Quick Stop", "Mooby's", "Speedway", "One Stop"],
},
{
"cat":"Kevin Smith",
"ques":"Who played Miri in Zack and Miri Make a Porno?",
"answ":"ELIZABETH BANKS",
"answ3":"ELISABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":["Elizabeth Banks", "Charlize Theron", "Kirsten Dunst", "Leslie Mann"],
},
{
"cat":"Kevin Smith",
"ques":"Who played Zack in Zack and Miri Make a Porno?",
"answ":"SETH ROGEN",
"answ2":"Seth Rogen.",
"option":["Seth Rogen", "Jason Mewes", "Justin Long", "Jason Lee"],
},
{
"cat":"Kevin Smith",
"ques":"Which state are Loki and Bartleby banished to in Dogma?",
"answ":"WISCONSIN",
"answ2":"Wisconsin.",
"option":["Wisconsin", "New Jersey", "California", "Ohio"],
},
{
"cat":"Kevin Smith",
"ques":"This actress played Rene Mosier, Brodie's ex-girlfriend in Mallrats.",
"answ":"SHANNEN DOHERTY",
"answ3":"SHANNON DOHERTY",
"answ2":"Shannen Doherty.",
"option":["Shannen Doherty", "Joey Lauren Adams", "Renee Humphrey", "Claire Forlani"],
},
{
"cat":"Kevin Smith",
"ques":"Who portrays porn-star Brandon St. Randy in Zack and Miri Make a Porno?",
"answ":"JUSTIN LONG",
"answ2":"Justin Long.",
"option":["Justin Long", "Jason Mewes", "Jason Lee", "Ben Affleck"],
},
{
"cat":"Kevin Smith",
"ques":"In what Kevin Smith film will you hear the quote: 'All the Jedi had was a bunch of Muppets'?",
"answ":"CLERKS",
"answ2":"Clerks.",
"option":["Clerks", "Mallrats", "Dogma", "Jay and Silent Bob Strike Back"],
},
{
"cat":"Kevin Smith",
"ques":"Who plays comic book artist Banky Edwards in Chasing Amy?",
"answ":"JASON LEE",
"answ2":"Jason Lee.",
"option":["Jason Lee", "Jason Mewes", "Kevin Smith", "Ben Affleck"],
},
{
"cat":"Kevin Smith",
"ques":"In Jersey Girl, who plays Arthur, Ollie's one-time protégé who gets him the job interview in the city?",
"answ":"JASON BIGGS",
"answ2":"Jason Biggs.",
"option":["Jason Biggs", "Matt Damon", "Michael Cera", "Justin Long"],
},
{
"cat":"Kevin Smith",
"ques":"In Jay and Silent Bob Strike Back, there was a sequel mentioned to Good Will Hunting that was called Good Will Hunting 2: _________.",
"answ":"HUNTING SEASON",
"answ2":"Hunting Season.",
"option":["Hunting Season", "It Ain't Over Yet", "Hunters Assemble", "The Hunted"],
},
{
"cat":"Kevin Smith",
"ques":"Who plays retired seaman Howard Howe in Tusk?",
"answ":"MICHAEL PARKS",
"answ2":"Michael Parks.",
"option":["Michael Parks", "Johnny Depp", "Willem Dafoe", "Bryan Cranston"],
},
{
"cat":"Kevin Smith",
"ques":"In Dogma, what is the name of the new religious icon Cardinal Glick is trying to make famous through his 'Catholicism Wow' campaign?",
"answ":"BUDDY CHRIST",
"answ2":"Buddy Christ.",
"option":["Buddy Christ", "The Christinator", "Comrade Christ", "Big Christ"],
},
{
"cat":"Kevin Smith",
"ques":"What is the name of the first porn film that Zack and Miri set out to make in Zack and Miri Make a Porno?",
"answ":"STAR WHORES",
"answ2":"Star Whores.",
"option":["Star Whores", "Lord of the Dings", "Harry Pop-Her", "Indiana Bones"],
},
{
"cat":"Kevin Smith",
"ques":"In Jersey Girl, the family decides to do a song from Sweeney Todd for the talent show while everyone else does a song from what musical?",
"answ":"CATS",
"answ2":"Cats.",
"option":["Cats", "Wicked", "The Book of Mormon", "Chicago"],
},
{
"cat":"Kevin Smith",
"ques":"Which actor plays an eccentric detective named Guy Lapointe in Tusk and Yoga Hosers?",
"answ":"JOHNNY DEPP",
"answ2":"Johnny Depp.",
"option":["Johnny Depp", "Jason Lee", "Colin Farrell", "Ben Affleck"],
},
{
"cat":"Kevin Smith",
"ques":"Who has a cameo as a hippie named Brent, who Jay throws out of a van, in Jay and Silent Bob Strike Back?",
"answ":"SEANN WILLIAM SCOTT",
"answ3":"SEAN WILLIAM SCOTT",
"answ2":"Seann William Scott.",
"option":["Seann William Scott", "Justin Long", "Jason Biggs", "Matt Damon"],
},
{
"cat":"Kevin Smith",
"ques":"What type of food does Veronica bring to Dante for lunch in Clerks?",
"answ":"LASAGNA",
"answ2":"Lasagna.",
"option":["Lasagna", "Pizza", "Meatloaf", "Spaghetti"],
},
{
"cat":"Kevin Smith",
"ques":"In which film is Silent Bob asked for advice, and he responds with 'I got nothing.'?",
"answ":"CLERKS 2",
"answ3":"CLERKS II",
"answ2":"Clerks 2.",
"option":["Clerks 2", "Mallrats", "Dogma", "Jay and Silent Bob Strike Back"],
},
{
"cat":"Kevin Smith",
"ques":"Who plays the demon Azrael in Dogma?",
"answ":"JASON LEE",
"answ2":"Jason Lee.",
"option":["Jason Lee", "Joe Manganiello", "Brian O'Halloran", "Alan Rickman"],
},
{
"cat":"Kevin Smith",
"ques":"In Red State, the first onscreen victim of a radical fundamentalist church is a man who they say is guilty of what sin?",
"answ":"HOMOSEXUALITY",
"answ3":"BEING GAY",
"answ2":"Homosexuality.",
"option":["Homosexuality", "Adultery", "Performing abortions", "Drunkenness"],
},
{
"cat":"Kevin Smith",
"ques":"What is the first name of the 15 year old girl who is writing a book about men's sex drives in Mallrats?",
"answ":"TRICIA",
"answ2":"Tricia.",
"option":["Tricia", "Lynda", "Julie", "Mara"],
},
{
"cat":"Kevin Smith",
"ques":"What game is played on the roof of the convenience store in Clerks?",
"answ":"HOCKEY",
"answ3":"STREET HOCKEY",
"answ2":"Hockey.",
"option":["Hockey", "Basketball", "Dodgeball", "Golf"],
},
{
"cat":"Kevin Smith",
"ques":"Carrie Fisher plays a woman with what profession in Jay and Silent Bob Strike Back?",
"answ":"NUN",
"answ2":"Nun.",
"option":["Nun", "Librarian", "Hot dog vendor", "Lawyer"],
},
{
"cat":"Kevin Smith",
"ques":"In Dogma, which comedic actor plays Rufus the 13th apostle?",
"answ":"CHRIS ROCK",
"answ2":"Chris Rock.",
"option":["Chris Rock", "Ving Rhames", "Terry Crews", "Tracy Morgan"],
},
{
"cat":"Kevin Smith",
"ques":"Yoga Hosers takes place in what country?",
"answ":"CANADA",
"answ2":"Canada.",
"option":["Canada", "Australia", "Mexico", "United States"],
},
{
"cat":"Kevin Smith",
"ques":"In which Kevin Smith film does Ben Affleck's brother Casey have a quick cameo?",
"answ":"CHASING AMY",
"answ2":"Chasing Amy.",
"option":["Chasing Amy", "Mallrats", "Jay & Silent Bob Strike Back", "Clerks II"],
},
{
"cat":"Kevin Smith",
"ques":"What comic book legend plays himself in Mallrats, as he dispenses advice to Buddy?",
"answ":"STAN LEE",
"answ2":"Stan Lee.",
"option":["Stan Lee", "Jack Kirby", "Steve Ditko", "Frank Miller"],
},
{
"cat":"Kevin Smith",
"ques":"In 2010's Cop Out, James 'Jimmy' Monroe and Paul Hodges are detectives in which city?",
"answ":"NEW YORK",
"answ3":"NEW YORK CITY",
"answ2":"New York.",
"option":["New York", "Los Angeles", "Miami", "Cleveland"],
},
{
"cat":"Kevin Smith",
"ques":"In Clerks, Randall asks Dante which Star Wars film he prefers, what is Dante's answer?",
"answ":"EMPIRE",
"answ3":"THE EMPIRE STRIKES BACK",
"answ2":"The Empire Strikes Back.",
"option":["The Empire Strikes Back", "A New Hope", "The Phantom Menace", "Return of the Jedi"],
},
{
"cat":"Kevin Smith",
"ques":"Jennifer Lopez appears in which film from director Kevin Smith?",
"answ":"JERSEY GIRL",
"answ2":"Jersey Girl.",
"option":["Jersey Girl", "Chasing Amy", "Zack and Miri Make a Porno", "Cop Out"],
},
{
"cat":"Kevin Smith",
"ques":"Kevin Smith has a cameo in which film in the Die Hard franchise?",
"answ":"LIVE FREE OF DIE HARD",
"answ2":"Live Free or Die Hard.",
"option":["Live Free or Die Hard", "Die Hard 2", "Die Hard With a Vengeance", "A Good Day to Die Hard"],
},
{
"cat":"Kevin Smith",
"ques":"In Jay and Silent Bob Strike Back, which actor has a cameo as himself and says the line: 'It always comes back to that f-ing pie!'?",
"answ":"JASON BIGGS",
"answ3":"JASON BIGS",
"answ2":"Jason Biggs.",
"option":["Jason Biggs", "Jason Lee", "Chris Rock", "Seann William Scott"],
},
{
"cat":"Kevin Smith",
"ques":"Travis, Jarod and Billy Ray are kidnapped by a crazed cult after responding to an online ad in which Kevin Smith film?",
"answ":"RED STATE",
"answ2":"Red State.",
"option":["Red State", "Tusk", "Yoga Hosers", "Dogma"],
},
];
r2Q45 = shuffle(r2Q45);