var tomcruise = [
{
"cat":"Tom Cruise",
"ques":"What was Tom Cruise's call sign in Top Gun?",
"answ":"MAVERICK",
"answ2":"Maverick.",
},
{
"cat":"Tom Cruise",
"ques":"What is the name of the character played by Tom Cruise in the Mission: Impossible movies?",
"answ":"ETHAN HUNT",
"answ2":"Ethan Hunt.",
},
{
"cat":"Tom Cruise",
"ques":"What was the subtitle of the sequel to the Tom Cruise thriller Jack Reacher?",
"answ":"NEVER GO BACK",
"answ2":"Never Go Back.",
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise makes a cameo appearance in which Austin Powers movie?",
"answ":"GOLDMEMBER",
"answ3":"AUSTIN POWERS IN GOLDMEMBER",
"answ2":"Austin Powers in Goldmember.",
},
{
"cat":"Tom Cruise",
"ques":"Which Oscar-winning actor makes a cameo as Mission Commander Swanbeck in Mission: Impossible 2?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise performs the Journey song 'Don't Stop Believing' in the finale of what film?",
"answ":"ROCK OF AGES",
"answ2":"Rock of Ages.",
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays a race car driver alongside Robert Duvall and Nicole Kidman in what 1990 film?",
"answ":"DAYS OF THUNDER",
"answ2":"Days of Thunder.",
},
{
"cat":"Tom Cruise",
"ques":"In Born on the Fourth of July, which actor plays the paraplegic Charlie, who travels with Ron to a village after being kicked out of a bar?",
"answ":"WILLEM DAFOE",
"answ3":"WILLEM DEFOE",
"answ2":"Willem Dafoe.",
},
{
"cat":"Tom Cruise",
"ques":"In what film does Tom Cruise act opposite Kelly Preston, Jerry O'Connell, Beau Bridges and Bonnie Hunt?",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
},
{
"cat":"Tom Cruise",
"ques":"Who plays Tom Cruise's co-counsel, Lieutenant Commander JoAnne Galloway, in A Few Good Men?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
},
{
"cat":"Tom Cruise",
"ques":"Which Tom Cruise movie depicts a young Irish couple struggling to become landowners after immigrating to the U.S.?",
"answ":"FAR AND AWAY",
"answ2":"Far and Away.",
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise and Emily Blunt star together in what 2014 film?",
"answ":"EDGE OF TOMORROW",
"answ3":"LIVE DIE REPEAT",
"answ2":"Edge of Tomorrow/Live Die Repeat.",
},
{
"cat":"Tom Cruise",
"ques":"In what profession is Tom Cruise's character Barry Seal when he is hired by the CIA in American Made?",
"answ":"PILOT",
"answ3":"AIRLINE PILOT",
"answ2":"Pilot.",
},
{
"cat":"Tom Cruise",
"ques":"Who plays Tom Cruise's mentor Avery Tolar in 1993's The Firm?",
"answ":"GENE HACKMAN",
"answ2":"Gene Hackman.",
},
{
"cat":"Tom Cruise",
"ques":"Who directed Nicole Kidman and Tom Cruise in Eyes Wide Shut?",
"answ":"STANLEY KUBRICK",
"answ2":"Stanley Kubrick.",
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in Mission: Impossible II?",
"answ":"JOHN WOO",
"answ2":"John Woo.",
},
{
"cat":"Tom Cruise",
"ques":"Who played the lead samurai, Katsumoto, who captures and later befriends Tom Cruise in The Last Samurai?",
"answ":"KEN WATANABE",
"answ2":"Ken Watanabe.",
},
{
"cat":"Tom Cruise",
"ques":"Who plays the villainous arms dealer Owen Davian in Mission Impossible III?",
"answ":"PHILIP SEYMOUR HOFFMAN",
"answ2":"Philip Seymour Hoffman.",
},
{
"cat":"Tom Cruise",
"ques":"In what year was the film Jack Reacher released?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Tom Cruise",
"ques":"Who directed Knight and Day?",
"answ":"JAMES MANGOLD",
"answ2":"James Mangold.",
},
{
"cat":"Tom Cruise",
"ques":"What famous actor directed Tom Cruise in Lions for Lambs?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise and Cuba Gooding Jr. star together in what 1996 movie?",
"answ":"JERRY MAGUIRE",
"answ2":"Jerry Maguire.",
},
];
var r2Q46 = [
{
"cat":"Tom Cruise",
"ques":"Who plays the Prime Minister of the UK in Mission Impossible - Rogue Nation?",
"answ":"TOM HOLLANDER",
"answ2":"Tom Hollander.",
"option":["Tom Hollander", "Bill Nighy", "Ciarán Hinds", "Steve Pemberton"],
},
{
"cat":"Tom Cruise",
"ques":"In 1985's Legend, what must The Lord of Darkness destroy to create eternal darkness?",
"answ":"UNICORNS",
"answ2":"Unicorns.",
"option":["Unicorns", "Doves", "Griffins", "Phoenix"],
},
{
"cat":"Tom Cruise",
"ques":"What Tom Cruise film co-starred Meryl Streep?",
"answ":"LION FOR LAMBS",
"answ2":"Lion for Lambs.",
"option":["Lion for Lambs", "Tropic Thunder", "Magnolia", "Vanilla Sky"],
},
{
"cat":"Tom Cruise",
"ques":"What is the name of Cruise's short-tempered character in Tropic Thunder?",
"answ":"LES GROSSMAN",
"answ2":"Les Grossman.",
"option":["Les Grossman", "Tugg Speedman", "Jeff Portnoy", "Kirk Lazarus"],
},
{
"cat":"Tom Cruise",
"ques":"In what film did Cruise say: 'It seems to me that if there were any logic to our language trust would be a 4-letter word'.",
"answ":"RISKY BUSINESS",
"answ2":"Risky Business.",
"option":["Risky Business", "Jerry Maguire", "A Few Good Men", "Rain Man"],
},
{
"cat":"Tom Cruise",
"ques":"In the first Mission Impossible, what was the code name of the IMF mole?",
"answ":"JOB",
"answ2":"Job.",
"option":["Job", "Isaiah", "Leviticus", "Ezekiel"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Vanilla Sky?",
"answ":"CAMERON CROWE",
"answ3":"CAMERON CROW",
"answ2":"Cameron Crowe.",
"option":["Cameron Crowe", "Brad Bird", "Joseph Kosinski", "Adam Shankman"],
},
{
"cat":"Tom Cruise",
"ques":"What is Tom's character's last name in Cocktail?",
"answ":"FLANAGAN",
"answ2":"Flanagan.",
"option":["Flanagan", "Donnelly", "McDeere", "Mitchell"],
},
{
"cat":"Tom Cruise",
"ques":"From which prestigious law school did Mitch McDeere graduate in The Firm?",
"answ":"HARVARD",
"answ2":"Harvard.",
"option":["Harvard", "Vanderbilt", "William & Mary", "Yale"],
},
{
"cat":"Tom Cruise",
"ques":"Who played the young step-mother of Tom Cruise's character Frank 'TJ' Makey in Magnolia?",
"answ":"JULIANNE MOORE",
"answ2":"Julianne Moore.",
"option":["Julianne Moore", "Leslie Mann", "Marisa Tomei", "Penélope Cruz"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in one of his earlier roles in the film The Outsiders?",
"answ":"FRANCIS FORD COPPOLA",
"answ3":"FRANCIS FORD COPOLA",
"answ2":"Francis Ford Coppola.",
"option":["Francis Ford Coppola", "Paul Brickman", "Harold Becker", "Curtis Hanson"],
},
{
"cat":"Tom Cruise",
"ques":"Who played Tom Cruise's wife in The Firm?",
"answ":"JEANNE TRIPPLEHORN",
"answ3":"JEANE TRIPPLEHORN",
"answ2":"Jeanne Tripplehorn.",
"option":["Jeanne Tripplehorn", "Nicole Kidman", "Katie Holmes", "Renée Zellweger"],
},
{
"cat":"Tom Cruise",
"ques":"In Days of Thunder, who plays the doctor with whom Cole Trickle has a romance?",
"answ":"NICOLE KIDMAN",
"answ2":"Nicole Kidman.",
"option":["Nicole Kidman", "Cameron Diaz", "Katie Holmes", "Katherine Heigl"],
},
{
"cat":"Tom Cruise",
"ques":"The Color of Money is a sequel of sorts to what earlier film?",
"answ":"THE HUSTLER",
"answ2":"The Hustler.",
"option":["The Hustler", "All the Right Moves", "Risky Business", "Taps"],
},
{
"cat":"Tom Cruise",
"ques":"In Rock of Ages, who plays Sherrie, a young woman from Oklahoma who comes to LA with dreams of becoming a singer?",
"answ":"JULIANNE HOUGH",
"answ2":"Julianne Hough.",
"option":["Julianne Hough", "Catherine Zeta-Jones", "Miley Cyrus", "Selena Gomez"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays Stefan's girlfriend Lisa Lietzke in All The Right Moves?",
"answ":"LEA THOMPSON",
"answ3":"LEA THOMSON",
"answ2":"Lea Thompson.",
"option":["Lea Thompson", "Demi Moore", "Erika Eleniak", "Elisabeth Shue"],
},
{
"cat":"Tom Cruise",
"ques":"In Vanilla Sky, Tom Cruise falls in love with his best friend's girlfiend. Who was she played by?",
"answ":"PENELOPE CRUZ",
"answ2":"Penélope Cruz.",
"option":["Penélope Cruz", "Eva Mendes", "Salma Hayek", "Elisabeth Shue"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in Risky Business?",
"answ":"PAUL BRICKMAN",
"answ2":"Paul Brickman.",
"option":["Paul Brickman", "Ron Howard", "Barry Levinson", "Curtis Hanson"],
},
{
"cat":"Tom Cruise",
"ques":"What was Michael Ironside's call sign in Top Gun?",
"answ":"JESTER",
"answ2":"Jester.",
"option":["Jester", "Cougar", "Wolfman", "Viper"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays Tom Cruise's unit commander Master Sergeant Farell in Edge of Tomorrow?",
"answ":"BILL PAXTON",
"answ2":"Bill Paxton.",
"option":["Bill Paxton", "Ed Harris", "Dennis Quaid", "Michael Stuhlbarg"],
},
{
"cat":"Tom Cruise",
"ques":"Which Tom Cruise movie had the tagline: 'When he pours, he reigns'?",
"answ":"COCKTAIL",
"answ2":"Cocktail.",
"option":["Cocktail", "Risky Business", "Days of Thunder", "Eyes Wide Shut"],
},
{
"cat":"Tom Cruise",
"ques":"Miranda Otto played the mother of Tom Cruise's children in what movie?",
"answ":"WAR OF THE WORLDS",
"answ2":"War of the Worlds.",
"option":["War of the Worlds", "Vanilla Sky", "American Made", "Valkyrie"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays a futuristic detective in what Spielberg film?",
"answ":"MINORITY REPORT",
"answ2":"Minority Report.",
"option":["Minority Report", "A.I. Artificial Intelligence", "Ready Player One", "Close Encounters of the Third Kind"],
},
{
"cat":"Tom Cruise",
"ques":"In War of the Worlds, who plays Tom Cruise's daughter?",
"answ":"DAKOTA FANNING",
"answ2":"Dakota Fanning.",
"option":["Dakota Fanning", "Alexandra Daddario", "Anya Taylor-Joy", "Cara Delevingne"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in Jerry Maguire?",
"answ":"CAMERON CROWE",
"answ3":"CAMERON CROW",
"answ2":"Cameron Crowe.",
"option":["Cameron Crowe", "Kevin Costner", "Paul Thomas Anderson", "Sydney Pollack"],
},
{
"cat":"Tom Cruise",
"ques":"Who played Tom Cruise's love interest in Legend?",
"answ":"MIA SARA",
"answ2":"Mia Sara.",
"option":["Mia Sara", "Rene Russo", "Sharon Stone", "Kim Basinger"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in Interview with the Vampire?",
"answ":"NEIL JORDAN",
"answ2":"Neil Jordan.",
"option":["Neil Jordan", "Rob Reiner", "Roger Donaldson", "Curtis Hanson"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Rain Man?",
"answ":"BARRY LEVINSON",
"answ2":"Barry Levinson.",
"option":["Barry Levinson", "Cameron Crowe", "Michael Chapman", "Ron Howard"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays the thief that Ethan Hunt recruits and falls in love with, in Mission Impossible 2?",
"answ":"THANDIE NEWTON",
"answ2":"Thandie Newton.",
"option":["Thandie Newton", "Zoe Saldana", "Paula Patton", "Rosario Dawson"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays the character of Charlie Babbitt in what 1980s film?",
"answ":"RAIN MAN",
"answ3":"RAINMAN",
"answ2":"Rain Man.",
"option":["Rain Man", "Cocktail", "Risky Business", "The Color of Money"],
},
{
"cat":"Tom Cruise",
"ques":"What was the first name of the hitman played by Tom Cruise in the 2004 film Collateral?",
"answ":"VINCENT",
"answ2":"Vincent.",
"option":["Vincent", "Eugene", "Abraham", "Gregory"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise dances in his underwear to which song in the 1983 film Risky Business?",
"answ":"OLD TIME ROCK AND ROLL",
"answ2":"Old Time Rock and Roll.",
"option":["Old Time Rock and Roll", "Nothing's Gonna Stop Us Now", "Twist and Shout", "Touch Me (All Night Long)"],
},
{
"cat":"Tom Cruise",
"ques":"What was the first film Tom Cruise and Nicole Kidman starred in together?",
"answ":"DAYS OF THUNDER",
"answ2":"Days of Thunder.",
"option":["Days of Thunder", "Top Gun", "Eyes Wide Shut", "A Few Good Men"],
},
{
"cat":"Tom Cruise",
"ques":"What was the password that Tom Cruise used to enter the illicit masquerade in Eyes Wide Shut?",
"answ":"FIDELIO",
"answ2":"Fidelio.",
"option":["Fidelio", "Inferno", "Semper", "Perpetuum"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays a musician named Stacee Jaxx in which 2012 film?",
"answ":"ROCK OF AGES",
"answ2":"Rock of Ages.",
"option":["Rock of Ages", "Knight and Day", "The Vow", "Wanderlust"],
},
{
"cat":"Tom Cruise",
"ques":"What was the name of the character played by Tom Cruise in the 1990 film Days of Thunder?",
"answ":"COLE TRICKLE",
"answ2":"Cole Trickle.",
"option":["Cole Trickle", "Charlie Babbitt", "Bill Harford", "Ray Ferrier"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise's first role was a character by the name of Billy in what 1980s romantic drama?",
"answ":"ENDLESS LOVE",
"answ2":"Endless Love.",
"option":["Endless Love", "Taps", "The Outsiders", "Risky Business"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise received his first Oscar nomination for what film?",
"answ":"BORN ON THE FOURTH OF JULY",
"answ3":"BORN ON THE 4TH OF JULY",
"answ2":"Born on the Fourth of July.",
"option":["Born on the Fourth of July", "Rain Man", "The Color of Money", "Top Gun"],
},
{
"cat":"Tom Cruise",
"ques":"In A Few Good Men, Daniel Kaffee only had two things to eat in his apartment, Yoohoo and what breakfast cereal?",
"answ":"COCOA PUFFS",
"answ3":"COCO PUFFS",
"answ2":"Cocoa Puffs.",
"option":["Cocoa Puffs", "Cookie Crisp", "Cheerios", "Wheaties"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays an ex-Army investigator in this 2012 action film.",
"answ":"JACK REACHER",
"answ2":"Jack Reacher.",
"option":["Jack Reacher", "Lockout", "Premium Rush", "Knight and Day"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays pilot and disavowed IMF agent Franz Krieger, whom Tom Cruise recruits in 1996's Mission: Impossible?",
"answ":"JEAN RENO",
"answ2":"Jean Reno.",
"option":["Jean Reno", "Ving Rhames", "Jon Voight", "Alec Baldwin"],
},
{
"cat":"Tom Cruise",
"ques":"In Magnolia, an unusual event occurs when what type of animal falls from the skies above Los Angeles?",
"answ":"FROG",
"answ3":"FROGS",
"answ2":"Frogs.",
"option":["Frogs", "Fish", "Squids", "Locusts"],
},
{
"cat":"Tom Cruise",
"ques":"What oil brand served as the sponsor on Rowdy Burn's (Michael Rooker) car in the 1990 film Days of Thunder?",
"answ":"EXXON",
"answ3":"EXON",
"answ2":"Exxon.",
"option":["Exxon", "Amoco", "Texaco", "Chevron"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays a fast talking car dealer in this 1980s drama.",
"answ":"RAIN MAN",
"answ3":"RAINMAN",
"answ2":"Rain Man.",
"option":["Rain Man", "The Outsiders", "Atlantic City", "The Color of Money"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays Danny Witwer in the Tom Cruise film Minority Report?",
"answ":"COLIN FARRELL",
"answ3":"COLIN FARELL",
"answ2":"Colin Farrell.",
"option":["Colin Farrell", "Clive Owen", "Jude Law", "Christian Bale"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in the war drama Lion for Lambs?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
"option":["Robert Redford", "George Clooney", "Clint Eastwood", "Peter Berg"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise stars in what 2001 Cameron Crowe film?",
"answ":"VANILLA SKY",
"answ2":"Vanilla Sky.",
"option":["Vanilla Sky", "Almost Famous", "Jerry Maguire", "Elizabethtown"],
},
{
"cat":"Tom Cruise",
"ques":"In Risky Business, who plays the prostitute Lana?",
"answ":"REBECCA DE MORNAY",
"answ2":"Rebecca De Mornay.",
"option":["Rebecca De Mornay", "Madeleine Stowe", "Demi Moore", "Lea Thompson"],
},
{
"cat":"Tom Cruise",
"ques":"What store does Raymond say he gets his underwear from in Rain Man?",
"answ":"K MART",
"answ2":"K-Mart.",
"option":["K-Mart", "JC Penney", "Walmart", "Macy's"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays Tom Cruise's co-lead, Major Susan Turner, in Jack Reacher: Never Go Back?",
"answ":"COBY SMULDERS",
"answ3":"COBIE SMULDERS",
"answ2":"Cobie Smulders.",
"option":["Cobie Smulders", "Emily Blunt", "Rebecca Ferguson", "Rosamund Pike"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Born on the Fourth of July?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
"option":["Oliver Stone", "Edward Zwick", "Joe Wright", "Francis Ford Coppola"],
},
{
"cat":"Tom Cruise",
"ques":"In A Few Good Men, who plays Santiago's commanding officer, Lieutenant Jonathan James Kendrick?",
"answ":"KIEFER SUTHERLAND",
"answ2":"Kiefer Sutherland.",
"option":["Kiefer Sutherland", "Kevin Bacon", "Oliver Platt", "Tim Curry"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise and Morgan Freeman star in this 2013 sci-fi action film.",
"answ":"OBLIVION",
"answ2":"Oblivion.",
"option":["Oblivion", "Ender's Game", "Elysium", "Edge of Tomorrow"],
},
{
"cat":"Tom Cruise",
"ques":"In Jerry Maguire, Jerry is fired from a big sports agency. How many of the other employees leave with him to start a new agency?",
"answ":"1",
"answ3":"ONE",
"answ2":"One.",
"option":["1", "0", "2", "3"],
},
{
"cat":"Tom Cruise",
"ques":"Who plays club owner, Dennis Dupree, in Rock of Ages?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
"option":["Alec Baldwin", "Jack Black", "Paul Giamatti", "Kurt Russell"],
},
{
"cat":"Tom Cruise",
"ques":"In what 80s film does Tom Cruise run a brothel out of his parents' house?",
"answ":"RISKY BUSINESS",
"answ2":"Risky Business.",
"option":["Risky Business", "All the Right Moves", "Losin' It", "The Outsiders"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in Far and Away?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":["Ron Howard", "Tony Scott", "Oliver Stone", "Barry Levinson"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays a character by the name of Brian Flanagan in what 1980s drama?",
"answ":"COCKTAIL",
"answ2":"Cocktail.",
"option":["Cocktail", "Risky Business", "Rain Man", "The Color of Money"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays Cadet Captain David Shawn in what 1980s drama?",
"answ":"TAPS",
"answ2":"Taps.",
"option":["Taps", "Top Gun", "A Few Good Men", "Born on the Fourth of July"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays Major William Cage in what 2010s action film?",
"answ":"EDGE OF TOMORROW",
"answ3":"LIVE DIE REPEAT",
"answ2":"Edge of Tomorrow/Live Die Repeat.",
"option":["Edge of Tomorrow", "Knight and Day", "Oblivion", "The Mummy"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays police chief John Anderton in what sci-fi film?",
"answ":"MINORITY REPORT",
"answ2":"Minority Report.",
"option":["Minority Report", "Edge of Tomorrow", "Jack Reacher", "Knight and Day"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays Colonel Claus von Stauffenberg in what 2000s drama film?",
"answ":"VALKYRIE",
"answ2":"Valkyrie.",
"option":["Valkyrie", "The Mummy", "The Last Samurai", "Lions for Lambs"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays David Aames, a man charged with murder in what 2000s psychological thriller?",
"answ":"VANILLA SKY",
"answ2":"Vanilla Sky.",
"option":["Vanilla Sky", "Hard Candy", "Eyes Wide Shut", "The Machinist"],
},
{
"cat":"Tom Cruise",
"ques":"Ethan Hunt has to scale a building and outrun a sandstorm in which Middle Eastern city in Mission: Impossible - Ghost Protocol?",
"answ":"DUBAI",
"answ2":"Dubai.",
"option":["Dubai", "Tehran", "Cairo", "Baghdad"],
},
{
"cat":"Tom Cruise",
"ques":"What was the first name of the character played by Tom Cruise in the 2013 film Oblivion?",
"answ":"JACK",
"answ2":"Jack.",
"option":["Jack", "James", "Jonathan", "Thomas"],
},
{
"cat":"Tom Cruise",
"ques":"What was the name of the character played by Tom Cruise in the 1994 film Interview with the Vampire: The Vampire Chronicles?",
"answ":"LESTAT",
"answ2":"Lestat.",
"option":["Lestat", "Santiago", "Malloy", "Armand"],
},
{
"cat":"Tom Cruise",
"ques":"Who earned a Best Supporting Actress Oscar nomination for her performance in the 1993 Tom Cruise film The Firm?",
"answ":"HOLLY HUNTER",
"answ2":"Holly Hunter.",
"option":["Holly Hunter", "Jeanne Tripplehorn", "Stockard Channing", "Debra Winger"],
},
{
"cat":"Tom Cruise",
"ques":"Who directed Tom Cruise in the 2003 historical epic The Last Samurai?",
"answ":"EDWARD ZWICK",
"answ2":"Edward Zwick.",
"option":["Edward Zwick", "Mel Gibson", "Ridley Scott", "Tom Hooper"],
},
{
"cat":"Tom Cruise",
"ques":"Which Oscar-winning actor provides the voice-over narration for the Tom Cruise film War of the Worlds?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
"option":["Morgan Freeman", "Richard Dreyfuss", "Jeremy Irons", "Tom Hanks"],
},
 {
"cat":"Tom Cruise",
"ques":"Which celebrated director plays the villain 'The Zec' in the Tom Cruise thriller Jack Reacher?",
"answ":"WERNER HERZOG",
"answ2":"Werner Herzog.",
"option":["Werner Herzog", "Kenneth Branagh", "Quentin Tarantino", "David Lynch"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise in played Vietnam veteran Ron Kovic in which the 1989 drama?",
"answ":"BORN ON THE FOURTH OF JULY",
"answ2":"Born on the Fourth of July.",
"option":["Born on the Fourth of July", "Hamburger Hill", "Casualties of War", "In Country"],
},
{
"cat":"Tom Cruise",
"ques":"What was the name of the experimental battery that Tom Cruise is trying to protect in Knight and Day?",
"answ":"ZEPHYR",
"answ3":"THE ZEPHYR",
"answ2":"Zephyr.",
"option":["Zephyr", "Rabbit's Foot", "Genesis", "Rosebud"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise plays teenaged football player Stefen Djordjevic in which 1983 film?",
"answ":"ALL THE RIGHT MOVES",
"answ2":"All the Right Moves.",
"option":["All the Right Moves", "The Outsiders", "Endless Love", "Lucas"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise co-starred with C. Thomas Howell and Patrick Swayze in which 1983 film?",
"answ":"THE OUTSIDERS",
"answ2":"The Outsiders.",
"option":["The Outsiders", "Red Dawn", "Steel Dawn", "All the Right Moves"],
},
{
"cat":"Tom Cruise",
"ques":"Tom Cruise is on a road trip to which North American city in the 1983 film Losin' It?",
"answ":"TIJUANA",
"answ2":"Tijuana.",
"option":["Tijuana", "Las Vegas", "Reno", "Atlantic City"],
},
{
"cat":"Tom Cruise",
"ques":"Miranda Otto played the mother of Tom Cruise’s children in what movie?",
"answ":"WAR OF THE WORLDS",
"answ2":"War of the Worlds.",
"option":["War of the Worlds", "Valkyrie", "The Firm", "Minority Report"],
},
];
tomcruise = shuffle(tomcruise);
r2Q46 = shuffle(r2Q46);