var denzelwashington = [
{
"cat":"Denzel Washington",
"ques":"In Remember the Titans, what kind of fruit did coach Boone toss to rival coach Tyrell after their game?",
"answ":"BANANA",
"answ2":"Banana.",
},
{
"cat":"Denzel Washington",
"ques":"In The Book of Eli, which Oscar-winner plays the villainous warlord Carnegie?",
"answ":"GARY OLDMAN",
"answ2":"Gary Oldman.",
},
{
"cat":"Denzel Washington",
"ques":"Who directed Remember the Titans?",
"answ":"BOAZ YAKIN",
"answ2":"Boaz Yakin.",
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays coach Herman Boone in what football film?",
"answ":"REMEMBER THE TITANS",
"answ2":"Remember The Titans.",
},
{
"cat":"Denzel Washington",
"ques":"Who plays Denzel's partner Detective Jonesy in the 1998 supernatural horror crime thriller Fallen?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington reprised the role of Robert McCall in what 2018 action-sequel?",
"answ":"THE EQUALIZER 2",
"answ3":"EQUALIZER 2",
"answ2":"The Equalizer 2.",
},
{
"cat":"Denzel Washington",
"ques":"Who co-starred with Denzel Washington as young train conductor Will Colson, in the 2010 film Unstoppable?",
"answ":"CHRIS PINE",
"answ2":"Chris Pine.",
},
{
"cat":"Denzel Washington",
"ques":"What director plays Denzel Washington's best friend Shorty in Malcolm X?",
"answ":"SPIKE LEE",
"answ2":"Spike Lee.",
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a desperate father who is trying to secure a heart for his sick son's much needed transplant in what film?",
"answ":"JOHN Q",
"answ2":"John Q.",
},
{
"cat":"Denzel Washington",
"ques":"What film stars Denzel Washington as Detective John Hobbes, investgating what appears to be a series of copycat murders, after the original killer is put to death?",
"answ":"FALLEN",
"answ2":"Fallen.",
},
{
"cat":"Denzel Washington",
"ques":"What 2004 action film stars Denzel Washington and Dakota Fanning?",
"answ":"MAN ON FIRE",
"answ2":"Man On Fire.",
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington, Meg Ryan and Lou Diamond Phillips star in what 90s drama?",
"answ":"COURAGE UNDER FIRE",
"answ2":"Courage Under Fire.",
},
{
"cat":"Denzel Washington",
"ques":"In what biographical drama did Denzel Washington portray boxer Rubin Carter who was wrongly imprisoned for murder?",
"answ":"THE HURRICANE",
"answ2":"The Hurricane.",
},
{
"cat":"Denzel Washington",
"ques":"In The Equalizer, Denzel Washington seeks out those who hospitalized Alina, a teenage prostitute played by whom?",
"answ":"CHLOE GRACE MORETZ",
"answ3":"CHLOË GRACE MORETZ",
"answ2":"Chloë Grace Moretz.",
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington and Clive Owen star in which 2006 Spike Lee film?",
"answ":"INSIDE MAN",
"answ2":"Inside Man.",
},
{
"cat":"Denzel Washington",
"ques":"Who played the Preacher's Wife in the 1996 romantic comedy The Preacher's Wife?",
"answ":"WHITNEY HOUSTON",
"answ3":"WITNEY HOUSTON",
"answ2":"Whitney Houston.",
},
{
"cat":"Denzel Washington",
"ques":"What action-crime comedy stars Denzel Washington and Mark Wahlberg?",
"answ":"2 GUNS",
"answ3":"TWO GUNS",
"answ2":"2 Guns.",
},
{
"cat":"Denzel Washington",
"ques":"Who directed Denzel Washington in Man on Fire, Unstoppable, The Taking of Pelham 123 and Déjà Vu?",
"answ":"TONY SCOTT",
"answ2":"Tony Scott.",
},
{
"cat":"Denzel Washington",
"ques":"What basketball star played Jesus Shuttlesworth in He Got Game?",
"answ":"RAY ALLEN",
"answ2":"Ray Allen.",
},
{
"cat":"Denzel Washington",
"ques":"What was the first collaboration between Denzel Washington and director Edward Zwick?",
"answ":"GLORY",
"answ2":"Glory.",
},
];
var r2Q48 = [
{
"cat":"Denzel Washington",
"ques":"In which flick does Denzel play a train conductor named Frank?",
"answ":"UNSTOPPABLE",
"answ2":"Unstoppable.",
"option":["Unstoppable", "Safe House", "The Equalizer", "Man on Fire"],
},
{
"cat":"Denzel Washington",
"ques":"Who played Colonel Robert Gould Shaw in Glory?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
"option":["Matthew Broderick", "Morgan Freeman", "Samuel L. Jackson", "Sam Shepard"],
},
{
"cat":"Denzel Washington",
"ques":"Which Denzel film was based on a novel by Walter Mosley?",
"answ":"DEVIL IN A BLUE DRESS",
"answ2":"Devil in a Blue Dress.",
"option":["Devil in a Blue Dress", "The Mighty Quinn", "The Pelican Brief", "The Bone Collector"],
},
{
"cat":"Denzel Washington",
"ques":"How many total Oscars have been won by Denzel?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"Denzel Washington",
"ques":"Detective Alonzo Harris is assigned to evaluate a young officer played by whom in Training Day?",
"answ":"ETHAN HAWKE",
"answ3":"ETHAN HAWK",
"answ2":"Ethan Hawke.",
"option":["Ethan Hawke", "Mark Wahlberg", "Henry Cavill", "Matt Damon"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed 1996's The Preacher's Wife?",
"answ":"PENNY MARSHALL",
"answ2":"Penny Marshall.",
"option":["Penny Marshall", "Denzel Washington", "Carl Franklin", "Forest Whitaker"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington received his first Oscar nomination for acting in what film?",
"answ":"CRY FREEDOM",
"answ2":"Cry Freedom.",
"option":["Cry Freedom", "Malcom X", "The Hurricane", "Glory"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays the criminal mastermind that Denzel is trying to apprehend in 2006's Inside Man?",
"answ":"CLIVE OWEN",
"answ2":"Clive Owen.",
"option":["Clive Owen", "Ed Harris", "Guy Pierce", "Jude Law"],
},
{
"cat":"Denzel Washington",
"ques":"What veteran action director was at the helm for the 2006 sci-fi thriller Déjà Vu?",
"answ":"TONY SCOTT",
"answ2":"Tony Scott.",
"option":["Tony Scott", "Michael Bay", "John McTiernan", "John Woo"],
},
{
"cat":"Denzel Washington",
"ques":"In which film does Denzel pursue a homicidal virtual-reality character who escapes into the real world?",
"answ":"VIRTUOSITY",
"answ2":"Virtuosity.",
"option":["Virtuosity", "John Q.", "eXistenZ", "Gamer"],
},
{
"cat":"Denzel Washington",
"ques":"What 1998 thriller sees Denzel play Detective John Hobbes, who investigates a series of supernatural murders?",
"answ":"FALLEN",
"answ2":"Fallen.",
"option":["Fallen", "The Bone Collector", "John Q.", "Out of Time"],
},
{
"cat":"Denzel Washington",
"ques":"What city's sanitation department does Denzel work for in Fences?",
"answ":"PITTSBURGH",
"answ2":"Pittsburgh.",
"option":["Pittsburgh", "Detroit", "Cincinnati", "Baltimore"],
},
{
"cat":"Denzel Washington",
"ques":"In what movie did Denzel Washington play a quadrapalegic?",
"answ":"THE BONE COLLECTOR",
"answ3":"BONE COLLECTOR",
"answ2":"The Bone Collector.",
"option":["The Bone Collector", "Fallen", "Devil in a Blue Dress", "Heart Condition"],
},
{
"cat":"Denzel Washington",
"ques":"In what movie did Denzel Washington play an angel?",
"answ":"THE PREACHER'S WIFE",
"answ3":"PREACHER'S WIFE",
"answ2":"The Preacher's Wife.",
"option":["The Preacher's Wife", "Fallen", "The Mighty Quinn", "Power"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed The Equalizer?",
"answ":"ANTOINE FUQUA",
"answ3":"ANTOINE FUQA",
"answ2":"Antoine Fuqua.",
"option":["Antoine Fuqua", "Daniel Espinosa", "David Leitch", "Tony Scott"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed Denzel in 2012's Flight?",
"answ":"ROBERT ZEMECKIS",
"answ2":"Robert Zemeckis.",
"option":["Robert Zemeckis", "Paul Thomas Anderson", "Jonathan Demme", "Spike Lee"],
},
{
"cat":"Denzel Washington",
"ques":"In Much Ado About Nothing, Denzel played Don Pedro. Who played his evil half-brother, Don John?",
"answ":"KEANU REEVES",
"answ2":"Keanu Reeves.",
"option":["Keanu Reeves", "Michael Keaton", "Robert Sean Leonard", "Ewan McGregor"],
},
{
"cat":"Denzel Washington",
"ques":"What government agency did Denzel's character work for before becoming an international criminal in Safe House?",
"answ":"CIA",
"answ2":"CIA.",
"option":["CIA", "FBI", "NSA", "MI6"],
},
{
"cat":"Denzel Washington",
"ques":"In Remember the Titans, what is the name of the high school whose football team Denzel must co-coach?",
"answ":"TC WILLIAMS HIGH SCHOOL",
"answ3":"TC WILLIAMS",
"answ2":"T. C. Williams High School.",
"option":["T. C. Williams", "Annandale", "Burnsley", "West Potomac"],
},
{
"cat":"Denzel Washington",
"ques":"Who played submarine commander Captain Frank Ramsey opposite Denzel in Crimson Tide?",
"answ":"GENE HACKMAN",
"answ2":"Gene Hackman.",
"option":["Gene Hackman", "Ed Harris", "Sean Connery", "Donald Sutherland"],
},
{
"cat":"Denzel Washington",
"ques":"What rapper played Denzel's childhood friend Odessa in Ricochet?",
"answ":"ICE T",
"answ2":"Ice-T.",
"option":["Ice-T", "Ice Cube", "Snoop Dogg", "50 Cent"],
},
{
"cat":"Denzel Washington",
"ques":"What government agency did Denzel's character work for in The Siege?",
"answ":"FBI",
"answ2":"FBI.",
"option":["FBI", "CIA", "NSA", "LAPD"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington directed what 2002 biographical drama?",
"answ":"ANTWONE FISHER",
"answ3":"ANTOINE FISHER",
"answ2":"Antwone Fisher.",
"option":["Antwone Fisher", "Hotel Rwanda", "Frida", "Luther"],
},
{
"cat":"Denzel Washington",
"ques":"What actress played Solara in The Book of Eli?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
"option":["Mila Kunis", "Chloë Grace Moretz", "Rosario Dawson", "Jodie Foster"],
},
{
"cat":"Denzel Washington",
"ques":"Who played assistant coach Bill Yoast in Remember the Titans?",
"answ":"WILL PATTON",
"answ2":"Will Patton.",
"option":["Will Patton", "Ryan Hurst", "Steve Buscemi", "Don Cheadle"],
},
{
"cat":"Denzel Washington",
"ques":"In what film did Denzel play anti-apartheid activist Steve Biko?",
"answ":"CRY FREEDOM",
"answ2":"Cry Freedom.",
"option":["Cry Freedom", "Power", "Malcolm X", "Invictus"],
},
{
"cat":"Denzel Washington",
"ques":"In Déjà Vu, what is the name of the program that enables Denzel to look into the past?",
"answ":"SNOW WHITE",
"answ2":"Snow White.",
"option":["Snow White", "Cinderella", "Sleeping Beauty", "Pandora's Eye"],
},
{
"cat":"Denzel Washington",
"ques":"What is Denzel's occupation in Heart Condition?",
"answ":"LAWYER",
"answ2":"Lawyer.",
"option":["Lawyer", "Police officer", "Surgeon", "Pilot"],
},
{
"cat":"Denzel Washington",
"ques":"Who played Denzel Washington's co-lead Michael Stigman in the action comedy 2 Guns?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
"option":["Mark Wahlberg", "Paul Rudd", "Edward Norton", "Mark Ruffalo"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays the mad bomber that Denzel Washington uses time travel to catch in the 2006 film Déjà Vu?",
"answ":"JIM CAVIEZEL",
"answ2":"Jim Caviezel.",
"option":["Jim Caviezel", "Val Kilmer", "Dougray Scott", "Wes Bentley"],
},
{
"cat":"Denzel Washington",
"ques":"What instrument does Denzel Washington play in Mo' Better Blues?",
"answ":"TRUMPET",
"answ2":"Trumpet.",
"option":["Trumpet", "Guitar", "Piano", "Saxophone"],
},
{
"cat":"Denzel Washington",
"ques":"Virtuosity paired Denzel Washington with what future Oscar winner?",
"answ":"RUSSELL CROWE",
"answ3":"RUSSELL CROW",
"answ2":"Russell Crowe.",
"option":["Russell Crowe", "Adrien Brody", "Jamie Foxx", "Sean Penn"],
},
{
"cat":"Denzel Washington",
"ques":"Which Academy Award winning actress plays Eva Mae Fisher, Antwone's mother in Antwone Fisher?",
"answ":"VIOLA DAVIS",
"answ2":"Viola Davis.",
"option":["Viola Davis", "Angela Bassett", "Octavia Spencer", "Kerry Washington"],
},
{
"cat":"Denzel Washington",
"ques":"In Inside Man, who plays fixer Madeleine White who was brought in to protect the contents of a safe deposit box within the bank?",
"answ":"JODIE FOSTER",
"answ2":"Jodie Foster.",
"option":["Jodie Foster", "Michelle Williams", "Julianne Moore", "Sigourney Weaver"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays political reporter Gray Grantham alongside Julia Roberts in what 90s thriller?",
"answ":"THE PELICAN BRIEF",
"answ3":"PELICAN BRIEF",
"answ2":"The Pelican Brief.",
"option":["The Pelican Brief", "Philadelphia", "Devil in a Blue Dress", "The Bone Collector"],
},
{
"cat":"Denzel Washington",
"ques":"In He Got Game, Denzel Washington's character is serving a prison sentence at the Attica Correctional Facility which is located in what state?",
"answ":"NEW YORK",
"answ2":"New York.",
"option":["New York", "Texas", "California", "Florida"],
},
{
"cat":"Denzel Washington",
"ques":"In Inside Man, who plays Arthur Case, the chairman and founder of the Manhattan Trust Bank?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
"option":["Christopher Plummer", "Michael Caine", "Ian McKellen", "Michael Gambon"],
},
{
"cat":"Denzel Washington",
"ques":"What is Denzel Washington's character's job in Fences?",
"answ":"GARBAGEMAN",
"answ3":"TRASHMAN",
"answ2":"Garbageman.",
"option":["Garbageman", "Cleaner", "Teacher", "Lawyer"],
},
{
"cat":"Denzel Washington",
"ques":"How long does it take McCall to kill all the Russian mob members and Alina's pimp Slavi in The Equalizer?",
"answ":"19 SECONDS",
"answ2":"19 seconds.",
"option":["19 seconds", "16 seconds", "10 seconds", "24 seconds"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays Specialist Andrew Ilario who Denzel Washington interviews in Courage Under Fire?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
"option":["Matt Damon", "Mark Wahlberg", "Gerard Butler", "Ben Affleck"],
},
{
"cat":"Denzel Washington",
"ques":"In Glory, Denzel Washington's character is flogged after sneaking away from his unit and searching what?",
"answ":"SHOES",
"answ2":"Shoes.",
"option":["Shoes", "A gun", "A coat", "Food"],
},
{
"cat":"Denzel Washington",
"ques":"Robert Duvall plays the hostage negotiator, Lieutenant Frank Grimes, in what Denzel Washington film?",
"answ":"JOHN Q",
"answ2":"John Q.",
"option":["John Q", "Man on Fire", "The Equalizer 2", "The Pelican Brief"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington and Spike Lee have worked together how many times?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":["4", "3", "5", "6"],
},
{
"cat":"Denzel Washington",
"ques":"Who sang the theme song 'Streets of Philadelphia' for the film Philadelphia?",
"answ":"BRUCE SPRINGSTEEN",
"answ2":"Bruce Springsteen.",
"option":["Bruce Springsteen", "Billy Joel", "Bob Dylan", "David Bowie"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington stars alongside Bob Hoskins in what 1990 comedy about a dead lawyer whose ghost teams up with the cop who was donated his heart?",
"answ":"HEART CONDITION",
"answ2":"Heart Condition.",
"option":["Heart Condition", "Heart Attack", "Heart Valve", "Heart Donation"],
},
{
"cat":"Denzel Washington",
"ques":"Who played Dr. Betty Shabazz in the Denzel Washington film Malcolm X?",
"answ":"ANGELA BASSETT",
"answ3":"ANGELA BASETT",
"answ2":"Angela Bassett.",
"option":["Angela Bassett", "Viola Davis", "Octavia Spencer", "Regina King"],
},
{
"cat":"Denzel Washington",
"ques":"In the film 2 Guns, what government agency does Denzel's character Bobby work for?",
"answ":"DEA",
"answ3":"THE DEA",
"answ2":"DEA.",
"option":["DEA", "FBI", "CIA", "NSA"],
},
{
"cat":"Denzel Washington",
"ques":"In the film Flight, who plays a drugs dealer named Harling who delivers his inventory to Denzel's character in a hotel room?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
"option":["John Goodman", "William Hurt", "John C. Reilly", "William H. Macey"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays the villainous Dave York, Robert McCall's former partner, in The Equalizer 2?",
"answ":"PEDRO PASCAL",
"answ2":"Pedro Pascal.",
"option":["Pedro Pascal", "Bill Pullman", "Martin Csokas", "David Harbour"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington starred in what 90s film, which features supporting performances by Viggo Mortensen, James Gandolfini and Steve Zahn?",
"answ":"CRIMSON TIDE",
"answ2":"Crimson Tide.",
"option":["Crimson Tide", "Ricochet", "Fallen", "The Bone Collector"],
},
{
"cat":"Denzel Washington",
"ques":"What 2012 film stars Denzel Washington and Ryan Reynolds?",
"answ":"SAFE HOUSE",
"answ2":"Safe House.",
"option":["Safe House", "Two Guns", "Unstoppable", "Chaos Theory"],
},
{
"cat":"Denzel Washington",
"ques":"In 2016's The Magnificent Seven, who plays the villain Bartholomew Bogue who the Seven must defeat?",
"answ":"PETER SARSGAARD",
"answ3":"PETER SARSGARD",
"answ2":"Peter Sarsgaard.",
"option":["Peter Sarsgaard", "Alexander Skarsgard", "Vincent D'onofrio", "Michael Madsen"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington received his first Best Actor nomination for what film?",
"answ":"MALCOLM X",
"answ2":"Malcolm X.",
"option":["Malcolm X", "Mo' Better Blues", "Courage Under Fire", "The Hurricane"],
},
{
"cat":"Denzel Washington",
"ques":"What is Denzel Washington's second feature film, where he turns out to be the killer?",
"answ":"A SOLDIER'S STORY",
"answ2":"A Soldier's Story.",
"option":["A Soldier's Story", "The Mighty Quinn", "Power", "Heart Condition"],
},
{
"cat":"Denzel Washington",
"ques":"What was the first name of the character played by Denzel Washington in Training Day?",
"answ":"ALONZO",
"answ2":"Alonzo.",
"option":["Alonzo", "Bobby", "Keith", "Doug"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed Denzel Washington in the 1998 political thriller The Siege?",
"answ":"EDWARD ZWICK",
"answ2":"Edward Zwick.",
"option":["Edward Zwick", "Ted Demme", "Jonathan Demme", "Martin Campbell"],
},
{
"cat":"Denzel Washington",
"ques":"In which branch of the military does Denzel Washington's character serve in Courage Under Fire?",
"answ":"ARMY",
"answ3":"US ARMY",
"answ2":"Army.",
"option":["Army", "Air Force", "Navy", "Marines"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a public relations expert in which 1986 political drama?",
"answ":"POWER",
"answ2":"Power.",
"option":["Power", "Salvador", "Reds", "Secret Honor"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays Ben Marco in the 2004 film The Manchurian Candidate, a role originally played in 1962 by which actor?",
"answ":"FRANK SINATRA",
"answ2":"Frank Sinatra.",
"option":["Frank Sinatra", "Robert Mitchum", "Laurence Harvey", "Cary Grant"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a character by the name of Bleek Gilliam in what 1990s film?",
"answ":"MO BETTER BLUES",
"answ2":"Mo Better Blues.",
"option":["Mo Better Blues", "Fallen", "Heart Condition", "Courage Under Fire"],
},
{
"cat":"Denzel Washington",
"ques":"What was the first name of the character played by Denzel Washington in the 2013 film 2 Guns?",
"answ":"BOBBY",
"answ2":"Bobby.",
"option":["Bobby", "Stig", "Danny", "Quince"],
},
{
"cat":"Denzel Washington",
"ques":"In 2016s The Magnificent Seven, Denzel Washington was the leader of the Seven. Who played his counterpart in the original 1960 film?",
"answ":"YUL BRYNNER",
"answ2":"Yul Brynner.",
"option":["Yul Brynner", "John Wayne", "Steve McQueen", "James Coburn"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington and Sarita Choudhury star in waht 1990s romantic drama?",
"answ":"MISSISSIPPI MASALA",
"answ2":"Mississippi Masala.",
"option":["Mississippi Masala", "Career Opportunities", "The Man in the Moon", "The Preacher's Wife"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays Detective Keith Frazier in what 2000s drama?",
"answ":"INSIDE MAN",
"answ2":"Inside Man.",
"option":["Inside Man", "Deja Vu", "American Gangster", "Man on Fire"],
},
{
"cat":"Denzel Washington",
"ques":"In The Preacher's Wife, Denzel Washington plays an angel sent to save the marriage of Whitney Houston and which actor?",
"answ":"COURTNEY B VANCE",
"answ2":"Courtney B. Vance.",
"option":["Courtney B. Vance", "Laurence Fishburne", "Dennis Haysbert", "Keenen Ivory Wayans"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington played criminal Frank Lucas in which 2007 drama?",
"answ":"AMERICAN GANGSTER",
"answ2":"American Gangster.",
"option":["American Gangster", "Inside Man", "Safe House", "Out of Time"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays Denzel Washington's long-lost father in the 1981 comedy Carbon Copy?",
"answ":"GEORGE SEGAL",
"answ2":"George Segal.",
"option":["George Segal", "Joseph Bologna", "Paul Sorvino", "Robert Forster"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a reporter for the Washington Herald in which 1993 thriller?",
"answ":"THE PELICAN BRIEF",
"answ3":"PELICAN BRIEF",
"answ2":"The Pelican Brief.",
"option":["The Pelican Brief", "Virtuosity", "Philadelphia", "The Bone Collector"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington has to break up a fight over which Marvel superhero in Tony Scott's Crimson Tide?",
"answ":"SILVER SURFER",
"answ3":"THE SILVER SURFER",
"answ2":"Silver Surfer.",
"option":["Silver Surfer", "Spider-Man", "Captain America", "Wolverine"],
},
{
"cat":"Denzel Washington",
"ques":"In which 1998 film does Denzel Washington play the father of a basketball player?",
"answ":"HE GOT GAME",
"answ2":"He Got Game.",
"option":["He Got Game", "Summer of Sam", "Bamboozled", "Red Hook Summer"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington played lawyer Joe Miller in which 1993 film?",
"answ":"PHILADELPHIA",
"answ2":"Philadelphia.",
"option":["Philadelphia", "Cry Freedom", "The Pelican Brief", "Mississippi Masala"],
},
{
"cat":"Denzel Washington",
"ques":"What is the name of the body-hopping fallen angel Denzel Washington is trying to stop in the thriller Fallen?",
"answ":"AZAZEL",
"answ2":"Azazel.",
"option":["Azazel", "Balthazar", "Gabriel", "Castiel"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays Denzel Washington's nurse, Thelma, in the 1999 film The Bone Collector?",
"answ":"QUEEN LATIFAH",
"answ2":"Queen Latifah.",
"option":["Queen Latifah", "Octavia Spencer", "Kimberly Elise", "Regina Hall"],
},
{
"cat":"Denzel Washington",
"ques":"In which film does Denzel Washington play a cyborg ex-cop?",
"answ":"VIRTUOSITY",
"answ2":"Virtuosity.",
"option":["Virtuosity", "The Book of Eli", "The Equalizer", "Deja Vu"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a Chief of Police in which U.S. state in the 2003 film Out of Time?",
"answ":"FLORIDA",
"answ2":"Florida.",
"option":["Florida", "Hawaii", "Louisiana", "Alaska"],
},
{
"cat":"Denzel Washington",
"ques":"In The Great Debaters, Denzel Washington's debate team competes against which Ivy League college in the championships?",
"answ":"HARVARD",
"answ2":"Harvard.",
"option":["Harvard", "Cornell", "Princeton", "Dartmouth"],
},
 {
"cat":"Denzel Washington",
"ques":"Who plays the cop who is haunted by the ghost of Denzel Washington after a heart transplant, in Heart Condition?",
"answ":"BOB HOSKINS",
"answ2":"Bob Hoskins.",
"option":["Bob Hoskins", "Dabney Coleman", "Dana Carvey", "Dan Aykroyd"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed Denzel Washington in the 1996 film Courage Under Fire?",
"answ":"EDWARD ZWICK",
"answ2":"Edward Zwick.",
"option":["Edward Zwick", "Sidney Lumet", "Ron Howard", "Barry Levinson"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays the hitman with a vendetta against Denzel Washington in the 1991 film Ricochet?",
"answ":"JOHN LITHGOW",
"answ2":"John Lithgow.",
"option":["John Lithgow", "Tommy Lee Jones", "Gabriel Byrne", "Tony Goldwyn"],
},
{
"cat":"Denzel Washington",
"ques":"In Training Day, Denzel Washington taught us that 'butt naked' is a street name for what drug?",
"answ":"PCP",
"answ2":"PCP.",
"option":["PCP", "Flakka", "Methamphetamine", "Crack"],
},
{
"cat":"Denzel Washington",
"ques":"Who directed Denzel Washington in the 1984 film A Soldier's Story?",
"answ":"NORMAN JEWISON",
"answ2":"Norman Jewison.",
"option":["Norman Jewison", "Clint Eastwood", "Francis Ford Coppola", "John Schlesinger"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a character by the name of Private Trip in what 1980s drama?",
"answ":"GLORY",
"answ2":"Glory.",
"option":["Glory", "Heart Condition", "The Mighty Quinn", "Cry Freedom"],
},
{
"cat":"Denzel Washington",
"ques":"In Antwone Fisher, Denzel Washington is a doctor in what specialty?",
"answ":"PSYCHIATRY",
"answ2":"Psychiatry.",
"option":["Psychiatry", "Cardiology", "Pediatrics", "Oncology"],
},
{
"cat":"Denzel Washington",
"ques":"Who plays Denzel Washington's trumpet-playing brother in Fences?",
"answ":"MYKELTI WILLIAMSON",
"answ2":"Mykelti Williamson.",
"option":["Mykelti Williamson", "Don Cheadle", "Ernie Hudson", "Samuel L. Jackson"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington made his big screen debut in which 1981 comedy?",
"answ":"CARBON COPY",
"answ2":"Carbon Copy.",
"option":["Carbon Copy", "Modern Romance", "Nice Dreams", "Saturday the 14th"],
},
{
"cat":"Denzel Washington",
"ques":"What was the name of the real-life boxer played by Denzel Washington in the 1999 film The Hurricane?",
"answ":"RUBIN CARTER",
"answ3":"RUBEN CARTER",
"answ2":"Rubin Carter.",
"option":["Rubin Carter", "Joe Frazier", "Sonny Liston", "Michael Spinks"],
},
{
"cat":"Denzel Washington",
"ques":"Which actress earned an Oscar for playing Rose Maxson in Fences?",
"answ":"VIOLA DAVIS",
"answ2":"Viola Davis.",
"option":["Viola Davis", "Octavia Spencer", "Naomie Harris", "Ruth Negga"],
},
 {
"cat":"Denzel Washington",
"ques":"Denzel Washington plays a pilot by the name of Whip Whitaker in what 2010s film?",
"answ":"FLIGHT",
"answ2":"Flight.",
"option":["Flight", "Cloud Atlas", "The Equalizer", "Shame"],
},
{
"cat":"Denzel Washington",
"ques":"Denzel Washington plays the police chief of a Caribbean island in which 1989 film?",
"answ":"THE MIGHTY QUINN",
"answ3":"MIGHTY QUINN",
"answ2":"The Mighty Quinn.",
"option":["The Mighty Quinn", "Out of Time", "The Bone Collector", "A Soldier's Story"],
},

];
denzelwashington = shuffle(denzelwashington);
r2Q48 = shuffle(r2Q48);