var scarlettjohansson = [
{
"cat":"Scarlett Johansson",
"ques":"Who directed the 2014 Scarlett Johansson action flick Lucy?",
"answ":"LUC BESSON",
"answ2":"Luc Besson.",
},
{
"cat":"Scarlett Johansson",
"ques":"What actor starred opposite Scarlett Johansson in Marriage Story?",
"answ":"ADAM DRIVER",
"answ2":"Adam Driver.",
},
{
"cat":"Scarlett Johansson",
"ques":"What 2003 film stars Scarlett Johansson and Bill Murray?",
"answ":"LOST IN TRANSLATION",
"answ2":"Lost in Translation.",
},
{
"cat":"Scarlett Johansson",
"ques":"A former tennis pro falls for Scarlett who happens to be dating his friend and soon-to-be-brother-in-law in what film?",
"answ":"MATCH POINT",
"answ2":"Match Point.",
},
];
var r2Q51 = [
{
"cat":"Scarlett Johansson",
"ques":"Who directed Scarlett in the 2005 sci-fi thriller The Island?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Peter Webber</button><button id=incop2 class=buttons003 onclick=qinc()>Spike Jonze</button><button id=corop class=buttons003 onclick=qcor()>Michael Bay</button><button id=incop4 class=buttons003 onclick=qinc()>Luc Besson</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"In what 2009 romantic comedy were Scarlett Johansson and Bradley Cooper romantically involved?",
"answ":"HE'S JUST NOT THAT INTO YOU",
"answ2":"He's Just Not That into You.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Friends with Benefits</button><button id=incop2 class=buttons003 onclick=qinc()>It's Complicated</button><button id=incop3 class=buttons003 onclick=qinc()>The Proposal</button><button id=corop class=buttons003 onclick=qcor()>He's Just Not That into You</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"In which film does Scarlett play a character with the first name Charlotte?",
"answ":"LOST IN TRANSLATION",
"answ2":"Lost in Translation.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Girl with a Pearl Earring</button><button id=corop class=buttons003 onclick=qcor()>Lost in Translation</button><button id=incop3 class=buttons003 onclick=qinc()>The Prestige</button><button id=incop4 class=buttons003 onclick=qinc()>He's Just Not That Into You</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"What famous actress did Scarlett portray in the movie Hitchcock?",
"answ":"JANET LEIGH",
"answ2":"Janet Leigh.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Katharine Hepburn</button><button id=corop class=buttons003 onclick=qcor()>Janet Leigh</button><button id=incop3 class=buttons003 onclick=qinc()>Marilyn Monroe</button><button id=incop4 class=buttons003 onclick=qinc()>Grace Kelly</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"What Marvel film was the first appearance of Scarlett as Natasha Romanov?",
"answ":"IRON MAN 2",
"answ2":"Iron Man 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Captain America The Winter Soldier</button><button id=corop class=buttons003 onclick=qcor()>Iron Man 2</button><button id=incop3 class=buttons003 onclick=qinc()>Iron Man 3</button><button id=incop4 class=buttons003 onclick=qinc()>Captain America The First Avenger</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett plays an assistant named Olivia Wenscombe in early 1900s London in which film?",
"answ":"THE PRESTIGE",
"answ2":"The Prestige.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Other Boleyn Girl</button><button id=corop class=buttons003 onclick=qcor()>The Prestige</button><button id=incop3 class=buttons003 onclick=qinc()>Girl with a Pearl Earring</button><button id=incop4 class=buttons003 onclick=qinc()>The Horse Whisperer</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"How many times has Jon Favreau directed Scarlett Johansson?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson and Jonathan Rhys Meyers star in which Woody Allen film?",
"answ":"MATCH POINT",
"answ2":"Match Point.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Match Point</button><button id=incop2 class=buttons003 onclick=qinc()>Midnight in Paris</button><button id=incop3 class=buttons003 onclick=qinc()>Blue Jasmine</button><button id=incop4 class=buttons003 onclick=qinc()>Irrational Man</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who directed The Horse Whisperer?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Robert Redford</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop3 class=buttons003 onclick=qinc()>Kenneth Branagh</button><button id=incop4 class=buttons003 onclick=qinc()>Erik Fleming</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Brian De Palma directed what film that featured Scarlett Johansson?",
"answ":"THE BLACK DAHLIA",
"answ3":"BLACK DAHLIA",
"answ2":"The Black Dahlia.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Black Dahlia</button><button id=incop2 class=buttons003 onclick=qinc()>Femme Fatale</button><button id=incop3 class=buttons003 onclick=qinc()>Mission to Mars</button><button id=incop4 class=buttons003 onclick=qinc()>Snake Eyes</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who plays the artist Scarlett Johansson works for in Girl with a Pearl Earring?",
"answ":"COLIN FIRTH",
"answ2":"Colin Firth.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Colin Firth</button><button id=incop2 class=buttons003 onclick=qinc()>David Thewlis</button><button id=incop3 class=buttons003 onclick=qinc()>Colin Farrell</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Isaacs</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who directed Lost in Translation?",
"answ":"SOFIA COPPOLA",
"answ3":"SOPHIA COPPOLA",
"answ2":"Sofia Coppola.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sofia Coppola</button><button id=incop2 class=buttons003 onclick=qinc()>Jon Favreau</button><button id=incop3 class=buttons003 onclick=qinc()>Luc Besson</button><button id=incop4 class=buttons003 onclick=qinc()>Spike Jonze</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson and Rebecca Hall fall for the same man in The Prestige and what other movie?",
"answ":"VICKY CRISTINA BARCELONA",
"answ3":"VICKY CHRISTINA BARCELONA",
"answ2":"Vicky Cristina Barcelona.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Vicky Cristina Barcelona</button><button id=incop2 class=buttons003 onclick=qinc()>Lay the Favourite</button><button id=incop3 class=buttons003 onclick=qinc()>Ghost World</button><button id=incop4 class=buttons003 onclick=qinc()>Chef</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson stars in this 2013 sci-fi film about an extraterrestrial who drives around Scotland attempting to lure unsuspecting men into her van.",
"answ":"UNDER THE SKIN",
"answ2":"Under the Skin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Under the Skin</button><button id=incop2 class=buttons003 onclick=qinc()>Lucy</button><button id=incop3 class=buttons003 onclick=qinc()>The Spirit</button><button id=incop4 class=buttons003 onclick=qinc()>Ghost in the Shell</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who plays Professor Norman in Luc Besson's Lucy?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Morgan Freeman</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Caine</button><button id=incop3 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=incop4 class=buttons003 onclick=qinc()>Liam Neeson</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson finds herself in a troubled relationship with whom in the romantic-comedy/drama Don Jon?",
"answ":"JOSEPH GORDON LEVITT",
"answ3":"JOSEPH GORDON LEVIT",
"answ2":"Joseph Gordon-Levitt.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Joseph Gordon-Levitt</button><button id=incop2 class=buttons003 onclick=qinc()>Dylan O'Brien</button><button id=incop3 class=buttons003 onclick=qinc()>Chris O'Donnell</button><button id=incop4 class=buttons003 onclick=qinc()>Jeremy Renner</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"What type of animal did Scarlett Johansson voice in the 2016 animated film Sing?",
"answ":"PORCUPINE",
"answ2":"Porcupine.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Porcupine</button><button id=incop2 class=buttons003 onclick=qinc()>Elephant</button><button id=incop3 class=buttons003 onclick=qinc()>Pig</button><button id=incop4 class=buttons003 onclick=qinc()>Rabbit</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson played Mary Boleyn in The Other Boleyn Girl. Who played her sister, Ann?",
"answ":"NATALIE PORTMAN",
"answ2":"Natalie Portman.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Natalie Portman</button><button id=incop2 class=buttons003 onclick=qinc()>Keira Knightley</button><button id=incop3 class=buttons003 onclick=qinc()>Emma Stone</button><button id=incop4 class=buttons003 onclick=qinc()>Mila Kunis</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"How many Academy Awards has Scarlett Johansson been nominated for in her career?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>0</button><button id=incop2 class=buttons003 onclick=qinc()>1</button><button id=corop class=buttons003 onclick=qcor()>2</button><button id=incop4 class=buttons003 onclick=qinc()>3</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Which Scarlett Johansson film shares its title with both a novel and a famous painting?",
"answ":"GIRL WITH A PEARL EARRING",
"answ3":"THE GIRL WITH A PEARL EARRING",
"answ2":"Girl with a Pearl Earring.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Girl with a Pearl Earring</button><button id=incop2 class=buttons003 onclick=qinc()>Vicky Cristina Barcelona</button><button id=incop3 class=buttons003 onclick=qinc()>A Good Woman</button><button id=incop4 class=buttons003 onclick=qinc()>The Other Boleyn Girl</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who plays the nefarious Dr. Bernard Merrick in Michael Bay's The Island?",
"answ":"SEAN BEAN",
"answ2":"Sean Bean.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sean Bean</button><button id=incop2 class=buttons003 onclick=qinc()>Ed Harris</button><button id=incop3 class=buttons003 onclick=qinc()>Antonio Banderas</button><button id=incop4 class=buttons003 onclick=qinc()>Gary Oldman</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett played Samuel L. Jackson's evil accomplice Silken Floss in what 2008 film?",
"answ":"THE SPIRIT",
"answ2":"The Spirit.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Spirit</button><button id=incop2 class=buttons003 onclick=qinc()>Vicky Cristina Barcelona</button><button id=incop3 class=buttons003 onclick=qinc()>Astro Boy</button><button id=incop4 class=buttons003 onclick=qinc()>Jumper</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"What 2005 film starred Scarlett Johansson opposite Ewan McGregor?",
"answ":"THE ISLAND",
"answ2":"The Island.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Island</button><button id=incop2 class=buttons003 onclick=qinc()>Match Point</button><button id=incop3 class=buttons003 onclick=qinc()>The Black Dahlia</button><button id=incop4 class=buttons003 onclick=qinc()>Girl with a Pearl Earring</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Rooney Mara plays the childhood sweetheart to a character by the name of Theodore in which Scarlett Johansson co-starring film?",
"answ":"HER",
"answ2":"Her.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>We Bought a Zoo</button><button id=corop class=buttons003 onclick=qcor()>Her</button><button id=incop3 class=buttons003 onclick=qinc()>Match Point</button><button id=incop4 class=buttons003 onclick=qinc()>Sing</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson made her feature film debut in which 1994 film?",
"answ":"NORTH",
"answ2":"North.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>If Lucy Fell</button><button id=incop2 class=buttons003 onclick=qinc()>My Father the Hero</button><button id=corop class=buttons003 onclick=qcor()>North</button><button id=incop4 class=buttons003 onclick=qinc()>Monkey Trouble</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"What is the name of the snake, voiced by Scarlett Johansson in 2016's The Jungle Book?",
"answ":"KAA",
"answ3":"KA",
"answ2":"Kaa.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Raksha</button><button id=incop2 class=buttons003 onclick=qinc()>Ikka</button><button id=corop class=buttons003 onclick=qcor()>Kaa</button><button id=incop4 class=buttons003 onclick=qinc()>Raquel</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"In Lost in Translation, Bob Harris is in Tokyo to film a commercial for what kind of product?",
"answ":"WHISKEY",
"answ3":"WHISKY",
"answ2":"Whisky.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Toothpaste</button><button id=incop2 class=buttons003 onclick=qinc()>Sneakers</button><button id=corop class=buttons003 onclick=qcor()>Whiskey</button><button id=incop4 class=buttons003 onclick=qinc()>Car</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who played Scarlett Johansson's son, Jojo, in Jojo Rabbit?",
"answ":"ROMAN GRIFFIN DAVIS",
"answ2":"Roman Griffin Davis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Archie Yates</button><button id=incop2 class=buttons003 onclick=qinc()>Jacob Tremblay</button><button id=corop class=buttons003 onclick=qcor()>Roman Griffin Davis</button><button id=incop4 class=buttons003 onclick=qinc()>Jack Dylan Grazer</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Scarlett Johansson voiced a character named Nutmeg in what 2018 film?",
"answ":"ISLE OF DOGS",
"answ2":"Isle of Dogs.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ready Player One</button><button id=incop2 class=buttons003 onclick=qinc()>The Grinch</button><button id=corop class=buttons003 onclick=qcor()>Isle of Dogs</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Rabbit</button><br/>",
},
{
"cat":"Scarlett Johansson",
"ques":"Who directed 2019's Marriage Story?",
"answ":"NOAH BAUMBACH",
"answ2":"Noah Baumbach.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wes Anderson</button><button id=incop2 class=buttons003 onclick=qinc()>Spike Jonze</button><button id=corop class=buttons003 onclick=qcor()>Noah Baumbach</button><button id=incop4 class=buttons003 onclick=qinc()>Olivia Wilde</button><br/>",
},
];
scarlettjohansson = shuffle(scarlettjohansson);
r2Q51 = shuffle(r2Q51);