var r2Q54 = [
{
"cat":"Video Game Movies",
"ques":"Who played Mario in 1993's Super Mario Bros.?",
"answ":"BOB HOSKINS",
"answ2":"Bob Hoskins.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Farley</button><button id=incop2 class=buttons003 onclick=qinc()>ohn Leguizamo</button><button id=corop class=buttons003 onclick=qcor()>Bob Hoskins</button><button id=incop4 class=buttons003 onclick=qinc()>Dennis Hopper</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Simon McQuoid directed what 2021 action film that stars Lewis Tan and is based on a popular video game franchise?",
"answ":"MORTAL KOMBAT",
"answ2":"Mortal Kombat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sonic the Hedgehog</button><button id=incop2 class=buttons003 onclick=qinc()>Warcraft</button><button id=corop class=buttons003 onclick=qcor()>Mortal Kombat</button><button id=incop4 class=buttons003 onclick=qinc()>Werewolves Within</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Duncan Jones directed what 2016 video game film starring Paula Patton, Toby Kebbell, Ben Foster and Dominic Cooper?",
"answ":"WARCRAFT",
"answ2":"Warcraft.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Assassin's Creed</button><button id=incop2 class=buttons003 onclick=qinc()>Tomb Raider</button><button id=corop class=buttons003 onclick=qcor()>Warcraft</button><button id=incop4 class=buttons003 onclick=qinc()>Hitman: Agent 47</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who plays the villainous Doctor Eggman in the 2020 theatrical release, Sonic the Hedgehog?",
"answ":"JIM CARREY",
"answ2":"Jim Carrey.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nicolas Cage</button><button id=incop2 class=buttons003 onclick=qinc()>Kumail Nunjiani</button><button id=corop class=buttons003 onclick=qcor()>Jim Carrey</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Harris</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Which actor plays Sheriff Tom Wachowski of Green Hills opposite Sonic in Sonic the Hedgehog?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Evans</button><button id=incop2 class=buttons003 onclick=qinc()>Mark Wahlberg</button><button id=corop class=buttons003 onclick=qcor()>James Marsden</button><button id=incop4 class=buttons003 onclick=qinc()>Chris Hemsworth</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Alicia Vikander and Dominic West star in what 2018 video game adaptation?",
"answ":"TOMB RAIDER",
"answ2":"Tomb Raider.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rampage</button><button id=incop2 class=buttons003 onclick=qinc()>Assassin's Creed</button><button id=corop class=buttons003 onclick=qcor()>Tomb Raider</button><button id=incop4 class=buttons003 onclick=qinc()>Monster Hunter</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Timothy Olyphant stars as the lead in what 2007 film based off a video game series?",
"answ":"HITMAN",
"answ2":"Hitman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Far Cry</button><button id=incop2 class=buttons003 onclick=qinc()>Postal</button><button id=corop class=buttons003 onclick=qcor()>Hitman</button><button id=incop4 class=buttons003 onclick=qinc()>Max Payne</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who starred as the title character in the 2008 video game adaptation Max Payne?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Evans</button><button id=incop2 class=buttons003 onclick=qinc()>Liam Hemsworth</button><button id=corop class=buttons003 onclick=qcor()>Mark Wahlberg</button><button id=incop4 class=buttons003 onclick=qinc()>Edward Norton</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who directed Lara Croft Tomb Raider: The Cradle of Life?",
"answ":"JAN DE BONT",
"answ3":"JAN DE BOND",
"answ2":"Jan de Bont.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Simon West</button><button id=incop2 class=buttons003 onclick=qinc()>Roar Uthaug</button><button id=corop class=buttons003 onclick=qcor()>Jan de Bont</button><button id=incop4 class=buttons003 onclick=qinc()>Stephen Sommers</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who played Luigi in the 1993 video game monstrosity Super Mario Bros.?",
"answ":"JOHN LEGUIZAMO",
"answ2":"John Leguizamo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Armand Assante</button><button id=incop2 class=buttons003 onclick=qinc()>Andy Garcia</button><button id=corop class=buttons003 onclick=qcor()>John Leguizamo</button><button id=incop4 class=buttons003 onclick=qinc()>Dan Castellaneta</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who provides the voice of Vanellope in Wreck-It Ralph?",
"answ":"SARAH SILVERMAN",
"answ3":"SARA SILVERMAN",
"answ2":"Sarah Silverman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jane Lynch</button><button id=incop2 class=buttons003 onclick=qinc()>Tina Fey</button><button id=corop class=buttons003 onclick=qcor()>Sarah Silverman</button><button id=incop4 class=buttons003 onclick=qinc()>Amy Poehler</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who played Alex West, a tomb raider with unscrupulous methods in Lara Croft Tomb Raider?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guy Pierce</button><button id=corop class=buttons003 onclick=qcor()>Daniel Craig</button><button id=incop3 class=buttons003 onclick=qinc()>Channing Tatum</button><button id=incop4 class=buttons003 onclick=qinc()>Clive Owen</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In Ready Player One, what is the avatar name of Tye Sheridan's Wade Watts?",
"answ":"PARZIVAL",
"answ3":"PARCIVAL",
"answ2":"Parzival.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Parzival</button><button id=incop2 class=buttons003 onclick=qinc()>Artemis</button><button id=incop3 class=buttons003 onclick=qinc()>Tracer</button><button id=incop4 class=buttons003 onclick=qinc()>Aech</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"How many Resident Evil films are there?",
"answ":"SIX",
"answ3":"6",
"answ2":"6.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>4</button><button id=incop2 class=buttons003 onclick=qinc()>5</button><button id=corop class=buttons003 onclick=qcor()>6</button><button id=incop4 class=buttons003 onclick=qinc()>7</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"A woman named Rose goes in search for her adopted daughter within the confines of a strange desolate town in what film?",
"answ":"SILENT HILL",
"answ2":"Silent Hill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Corpse Party</button><button id=incop2 class=buttons003 onclick=qinc()>Doom</button><button id=corop class=buttons003 onclick=qcor()>Silent Hill</button><button id=incop4 class=buttons003 onclick=qinc()>Alone in the Dark</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who plays president Will Cooper in Pixels?",
"answ":"KEVIN JAMES",
"answ2":"Kevin James.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rob Schneider</button><button id=incop2 class=buttons003 onclick=qinc()>Adam Sandler</button><button id=corop class=buttons003 onclick=qcor()>Kevin James</button><button id=incop4 class=buttons003 onclick=qinc()>Chris Rock</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who played Lara Croft's father Lord Richard Croft in the first Tomb Raider film with Angelina Jolie?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Woods</button><button id=incop2 class=buttons003 onclick=qinc()>Donald Sutherland</button><button id=corop class=buttons003 onclick=qcor()>Jon Voight</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Plummer</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In Ready Player One, what Atari 2600 game had to be beaten in order to receive the final Easter egg and be awarded the last key?",
"answ":"ADVENTURE",
"answ2":"Adventure.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pac-Man</button><button id=incop2 class=buttons003 onclick=qinc()>Space Invaders</button><button id=corop class=buttons003 onclick=qcor()>Adventure</button><button id=incop4 class=buttons003 onclick=qinc()>Asteroids</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In Ralph Breaks the Internet, who voices the search engine character KnowsMore?",
"answ":"ALAN TUDYK",
"answ2":"Alan Tudyk.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Ratzenberger</button><button id=incop2 class=buttons003 onclick=qinc()>Jack McBrayer</button><button id=corop class=buttons003 onclick=qcor()>Alan Tudyk</button><button id=incop4 class=buttons003 onclick=qinc()>Alfred Molina</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who stars as the gun-for-hire known only as Agent 47 in 2007's Hitman?",
"answ":"TIMOTHY OLYPHANT",
"answ3":"TIMOTHY OLIPHANT",
"answ2":"Timothy Olyphant.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rob Lowe</button><button id=incop2 class=buttons003 onclick=qinc()>Kiefer Sutherland</button><button id=corop class=buttons003 onclick=qcor()>Timothy Olyphant</button><button id=incop4 class=buttons003 onclick=qinc()>Orlando Bloom</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Mike Newell directed what film based on a video game starring Jake Gyllenhaal?",
"answ":"PRINCE OF PERSIA",
"answ3":"PRINCE OF PERSIA THE SANDS OF TIME",
"answ2":"Prince of Persia: The Sands of Time.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Far Cry</button><button id=incop2 class=buttons003 onclick=qinc()>Doom</button><button id=corop class=buttons003 onclick=qcor()>Prince of Persia: The Sands of Time</button><button id=incop4 class=buttons003 onclick=qinc()>Silent Hill</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In 1995's Mortal Kombat, after defeating what character did Johnny Cage leave an autographed photo on which he wrote 'To my greatest fan'?",
"answ":"SCORPION",
"answ2":"Scorpion.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Goro</button><button id=incop2 class=buttons003 onclick=qinc()>Sub-Zero</button><button id=incop3 class=buttons003 onclick=qinc()>Kano</button><button id=corop class=buttons003 onclick=qcor()>Scorpion</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who plays Monarch, the eccentric wealthy DJ who invites elite drivers to a winner-take-all race, in 2014's Need for Speed?",
"answ":"MICHAEL KEATON",
"answ2":"Michael Keaton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop2 class=buttons003 onclick=qinc()>Dominic Cooper</button><button id=corop class=buttons003 onclick=qcor()>Michael Keaton</button><button id=incop4 class=buttons003 onclick=qinc()>Rami Malek</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Paul W.S. Anderson has directed how many installments of the Resident Evil franchise?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In 2008's neo-noir Max Payne, who stars alongside Mark Wahlberg as Mona Sex, a woman trying to solve her sister's murder?",
"answ":"MILA KUNIS",
"answ2":"Mila Kunis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scarlett Johansson</button><button id=incop2 class=buttons003 onclick=qinc()>Natalie Portman</button><button id=corop class=buttons003 onclick=qcor()>Mila Kunis</button><button id=incop4 class=buttons003 onclick=qinc()>Brie Larson</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What is the name of the alien-hunting video game that Ralph goes into, in Wreck-It Ralph?",
"answ":"HERO'S DUTY",
"answ2":"Hero's Duty.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Space Quest</button><button id=incop2 class=buttons003 onclick=qinc()>Journey of Heroes</button><button id=corop class=buttons003 onclick=qcor()>Hero's Duty</button><button id=incop4 class=buttons003 onclick=qinc()>Calhoun's Quest</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"At the beginning of the film Mortal Kombat, who is the reigning Mortal Kombat champion?",
"answ":"GORO",
"answ2":"Goro.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shang Tsung</button><button id=corop class=buttons003 onclick=qcor()>Goro</button><button id=incop3 class=buttons003 onclick=qinc()>Princess Kitana</button><button id=incop4 class=buttons003 onclick=qinc()>Shao Khan</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Flynn's Arcade is featured in what film?",
"answ":"TRON",
"answ2":"Tron.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wreck-It Ralph</button><button id=corop class=buttons003 onclick=qcor()>Tron</button><button id=incop3 class=buttons003 onclick=qinc()>Doom</button><button id=incop4 class=buttons003 onclick=qinc()>Ready Player One</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who plays Garona Halforcen, the half-orc/half human hybrid in Warcraft?",
"answ":"PAULA PATTON",
"answ2":"Paula Patton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Léa Seydoux</button><button id=corop class=buttons003 onclick=qcor()>Paula Patton</button><button id=incop3 class=buttons003 onclick=qinc()>Jaimie Alexander</button><button id=incop4 class=buttons003 onclick=qinc()>Regina Hall</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who plays Alan Rikkin, CEO of Abstergo Industries, in Assassin's Creed?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brendan Gleeson</button><button id=corop class=buttons003 onclick=qcor()>Jeremy Irons</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Fassbender</button><button id=incop4 class=buttons003 onclick=qinc()>Kurt Russell</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What video game movie franchise had the 2012 entry Revelation?",
"answ":"SILENT HILL",
"answ2":"Silent Hill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Resident Evil</button><button id=corop class=buttons003 onclick=qcor()>Silent Hill</button><button id=incop3 class=buttons003 onclick=qinc()>Tomb Raider</button><button id=incop4 class=buttons003 onclick=qinc()>Final Fantasy</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What animated video game franchise features the voice talents of Jason Sudeikis and Josh Gad?",
"answ":"ANGRY BIRDS",
"answ2":"Angry Birds.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Angry Birds</button><button id=incop2 class=buttons003 onclick=qinc()>Pokemon</button><button id=incop3 class=buttons003 onclick=qinc()>Final Fantasy</button><button id=incop4 class=buttons003 onclick=qinc()>Wreck-It Ralph</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Which Fast and Furious actress plays the character Rain in the Resident Evil franchise?",
"answ":"MICHELLE RODRIGUEZ",
"answ2":"Michelle Rodriguez.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michelle Rodriguez</button><button id=incop2 class=buttons003 onclick=qinc()>Jordana Brewster</button><button id=incop3 class=buttons003 onclick=qinc()>Gal Gadot</button><button id=incop4 class=buttons003 onclick=qinc()>Eva Mendes</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In Ralph Breaks the Internet, who voices the racer simply known as Shank?",
"answ":"GAL GADOT",
"answ2":"Gal Gadot.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gal Gadot</button><button id=incop2 class=buttons003 onclick=qinc()>Taraji P. Henson</button><button id=incop3 class=buttons003 onclick=qinc()>Sarah Silverman</button><button id=incop4 class=buttons003 onclick=qinc()>Halle Berry</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What was the name of the character played by Christopher Lambert in 1995's Mortal Kombat?",
"answ":"RAYDEN",
"answ3":"RAIDEN",
"answ2":"Raiden.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Raiden</button><button id=incop2 class=buttons003 onclick=qinc()>Kano</button><button id=incop3 class=buttons003 onclick=qinc()>Jax</button><button id=incop4 class=buttons003 onclick=qinc()>Liu Kang</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What is the subtitle of the sequel to Lara Croft Tomb Raider?",
"answ":"CRADLE OF LIFE",
"answ3":"THE CRADLE OF LIFE",
"answ2":"The Cradle of Life.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Cradle of Life</button><button id=incop2 class=buttons003 onclick=qinc()>The Angel of Darkness</button><button id=incop3 class=buttons003 onclick=qinc()>Shadow of the Tomb Raider</button><button id=incop4 class=buttons003 onclick=qinc()>Temple of Osiris</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who provides the voice of Ralph in Wreck-It Ralph?",
"answ":"JOHN C REILLY",
"answ3":"JOHN REILLY",
"answ2":"John C. Reilly.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John C. Reilly</button><button id=incop2 class=buttons003 onclick=qinc()>Will Ferrell</button><button id=incop3 class=buttons003 onclick=qinc()>Steve Carell</button><button id=incop4 class=buttons003 onclick=qinc()>Ben Stiller</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Which actor plays the villain Prince Nizam of Persia in Prince of Persia: The Sands of Time?",
"answ":"BEN KINGSLEY",
"answ2":"Ben Kingsley.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ben Kingsley</button><button id=incop2 class=buttons003 onclick=qinc()>Gary Oldman</button><button id=incop3 class=buttons003 onclick=qinc()>Sean Bean</button><button id=incop4 class=buttons003 onclick=qinc()>John Hurt</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In Super Mario Bros, what is the name of the girl who Mario and Luigi travel to an alternate dimension to save?",
"answ":"DAISY",
"answ3":"PRINCESS DAISY",
"answ2":"Daisy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Penelope</button><button id=incop2 class=buttons003 onclick=qinc()>Fiona</button><button id=incop3 class=buttons003 onclick=qinc()>Samantha</button><button id=corop class=buttons003 onclick=qcor()>Daisy</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What franchise had an installment with the subtitle The Legend of Chun Li?",
"answ":"STREET FIGHTER",
"answ2":"Street Fighter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tomb Raider</button><button id=incop2 class=buttons003 onclick=qinc()>Resident Evil</button><button id=incop3 class=buttons003 onclick=qinc()>Mortal Kombat</button><button id=corop class=buttons003 onclick=qcor()>Street Fighter</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Which actors plays the lead Sergeant John 'Reaper' Grimm in the 2005 video game adaptation Doom?",
"answ":"KARL URBAN",
"answ2":"Karl Urban.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Vin Diesel</button><button id=incop2 class=buttons003 onclick=qinc()>Christian Bale</button><button id=incop3 class=buttons003 onclick=qinc()>Dwayne Johnson</button><button id=corop class=buttons003 onclick=qcor()>Karl Urban</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"In The Angry Birds franchise, what is the name of the island that the birds live on?",
"answ":"BIRD ISLAND",
"answ2":"Bird Island.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Flightless Island</button><button id=incop2 class=buttons003 onclick=qinc()>Mighty Eagle Land</button><button id=incop3 class=buttons003 onclick=qinc()>Slingshot Land</button><button id=corop class=buttons003 onclick=qcor()>Bird Island</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What is the name of the secret government facility that a virus escapes from in 2002's Resident Evil?",
"answ":"THE HIVE",
"answ2":"The Hive.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Raft</button><button id=incop2 class=buttons003 onclick=qinc()>The Nexus</button><button id=incop3 class=buttons003 onclick=qinc()>The Cradle</button><button id=corop class=buttons003 onclick=qcor()>The Hive</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"What 1999 sci-fi adventure movie based on a video game, stars Freddie Prinze Jr and Matthew Lillard?",
"answ":"WING COMMANDER",
"answ2":"Wing Commander.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Far Cry</button><button id=incop2 class=buttons003 onclick=qinc()>Hitman</button><button id=incop3 class=buttons003 onclick=qinc()>Company of Heroes</button><button id=corop class=buttons003 onclick=qcor()>Wing Commander</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"After the murders of his family and his partner, a maverick cop becomes hell-bent on revenge in what 2008 film?",
"answ":"MAX PAYNE",
"answ2":"Max Payne.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hitman</button><button id=corop class=buttons003 onclick=qcor()>Max Payne</button><button id=incop3 class=buttons003 onclick=qinc()>Wing Commander</button><button id=incop4 class=buttons003 onclick=qinc()>Doom</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Who directed 1995's Mortal Kombat?",
"answ":"PAUL W S ANDERSON",
"answ3":"PAUL W ANDERSON",
"answ2":"Paul W.S. Anderson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John R. Leonetti</button><button id=corop class=buttons003 onclick=qcor()>Paul W.S. Anderson</button><button id=incop3 class=buttons003 onclick=qinc()>Simon McQuoid</button><button id=incop4 class=buttons003 onclick=qinc()>Russell Mulcahy</button><br/>",
},
{
"cat":"Video Game Movies",
"ques":"Sean Bean, Laurie Holden and Deborah Kara Unger appear in what video game film franchise?",
"answ":"SILENT HILL",
"answ2":"Silent Hill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tomb Raider</button><button id=corop class=buttons003 onclick=qcor()>Silent Hill</button><button id=incop3 class=buttons003 onclick=qinc()>Resident Evil</button><button id=incop4 class=buttons003 onclick=qinc()>Final Fantasy</button><br/>",
},
];
r2Q54 = shuffle(r2Q54);