var christophernolan = [
{
"cat":"Christopher Nolan",
"ques":"What Nolan movie released in 2017 received an Oscar nomination for Best Picture?",
"answ":"DUNKIRK",
"answ2":"Dunkirk.",
},
{
"cat":"Christopher Nolan",
"ques":"What film was the first collaboration between Christopher Nolan and Christian Bale?",
"answ":"BATMAN BEGINS",
"answ2":"Batman Begins.",
},
{
"cat":"Christopher Nolan",
"ques":"Which actor plays Mr. Dawson, a civilian sailor that tries to save lives in Dunkirk?",
"answ":"MARK RYLANCE",
"answ2":"Mark Rylance.",
},
{
"cat":"Christopher Nolan",
"ques":"In which Nolan film will you find a ship named Endurance?",
"answ":"INTERSTELLAR",
"answ2":"Interstellar.",
},
{
"cat":"Christopher Nolan",
"ques":"What actor has trouble sleeping in Insomnia?",
"answ":"AL PACINO",
"answ2":"Al Pacino.",
},
{
"cat":"Christopher Nolan",
"ques":"Robin Williams appeared in what Christopher Nolan film?",
"answ":"INSOMNIA",
"answ2":"Insomnia.",
},
];
var r2Q55 = [
{
"cat":"Christopher Nolan",
"ques":"In Inception, who played Mr. Saito, the businessman who hired DiCaprio and his team?",
"answ":"KEN WATANABE",
"answ2":"Ken Watanabe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>BD Wong</button><button id=incop2 class=buttons003 onclick=qinc()>Hiroyuki Sanada</button><button id=corop class=buttons003 onclick=qcor()>Ken Watanabe</button><button id=incop4 class=buttons003 onclick=qinc()>Andy Garcia</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Dunkirk, who played Royal Air Force pilot Farrier, who was the last in the air?",
"answ":"TOM HARDY",
"answ2":"Tom Hardy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cillian Murphy</button><button id=incop2 class=buttons003 onclick=qinc()>Ed Harris</button><button id=corop class=buttons003 onclick=qcor()>Tom Hardy</button><button id=incop4 class=buttons003 onclick=qinc()>Harry Styles</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Prestige, what are Borden's last words before he is hanged?",
"answ":"ABRACADABRA",
"answ2":"Abracadabra.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Are you watching?</button><button id=incop2 class=buttons003 onclick=qinc()>Goodbye</button><button id=corop class=buttons003 onclick=qcor()>Abracadabra</button><button id=incop4 class=buttons003 onclick=qinc()>See you later</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who played Detective Ellie Burr in Insomnia?",
"answ":"HILARY SWANK",
"answ3":"HILLARY SWANK",
"answ2":"Hilary Swank.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Crystal Lowe</button><button id=corop class=buttons003 onclick=qcor()>Hilary Swank</button><button id=incop3 class=buttons003 onclick=qinc()>Maura Tierney</button><button id=incop4 class=buttons003 onclick=qinc()>Jennifer Garner</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Inception, the dreamers use an object to distinguish dreams from reality. What do they call this object?",
"answ":"TOTEM",
"answ3":"A TOTEM",
"answ2":"Totem.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Token</button><button id=corop class=buttons003 onclick=qcor()>Totem</button><button id=incop3 class=buttons003 onclick=qinc()>Charm</button><button id=incop4 class=buttons003 onclick=qinc()>Anchor</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"The protagonist in Memento suffers from what?",
"answ":"ANTEROGRADE AMNESIA",
"answ3":"AMNESIA",
"answ2":"Anterograde amnesia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Aphasia</button><button id=corop class=buttons003 onclick=qcor()>Amnesia</button><button id=incop3 class=buttons003 onclick=qinc()>Aphagia</button><button id=incop4 class=buttons003 onclick=qinc()>Blindness</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What is the name of the Gotham City district where Batman fights the escaped Arkham Asylum convicts in Batman Begins?",
"answ":"NARROWS",
"answ3":"THE NARROWS",
"answ2":"The Narrows.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Glades</button><button id=corop class=buttons003 onclick=qcor()>The Narrows</button><button id=incop3 class=buttons003 onclick=qinc()>South End</button><button id=incop4 class=buttons003 onclick=qinc()>Orchid Bay</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who played McConaughey's father-in-law in Interstellar?",
"answ":"JOHN LITHGOW",
"answ3":"JOHN LITGOW",
"answ2":"John Lithgow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Caine</button><button id=corop class=buttons003 onclick=qcor()>John Lithgow</button><button id=incop3 class=buttons003 onclick=qinc()>James Cromwell</button><button id=incop4 class=buttons003 onclick=qinc()>John Larroquette</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In what state does Insomnia primarily take place?",
"answ":"ALASKA",
"answ2":"Alaska.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>California</button><button id=corop class=buttons003 onclick=qcor()>Alaska</button><button id=incop3 class=buttons003 onclick=qinc()>Vermont</button><button id=incop4 class=buttons003 onclick=qinc()>Texas</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays stage engineer John Cutter, who works with both Borden and Angier in The Prestige?",
"answ":"MICHAEL CAINE",
"answ2":"Michael Caine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andy Serkis</button><button id=corop class=buttons003 onclick=qcor()>Michael Caine</button><button id=incop3 class=buttons003 onclick=qinc()>Ricky Jay</button><button id=incop4 class=buttons003 onclick=qinc()>Christopher Plummer</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Inception, what is Joseph Gordon-Levitt's character's first name?",
"answ":"ARTHUR",
"answ2":"Arthur.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andrew</button><button id=incop2 class=buttons003 onclick=qinc()>Arnold</button><button id=corop class=buttons003 onclick=qcor()>Arthur</button><button id=incop4 class=buttons003 onclick=qinc()>Aaron</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"At the end of Batman Begins, Jim Gordon holds what rank in the GCPD?",
"answ":"LIEUTENANT",
"answ2":"Lieutenant.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Captain</button><button id=incop2 class=buttons003 onclick=qinc()>Sergeant</button><button id=corop class=buttons003 onclick=qcor()>Lieutenant</button><button id=incop4 class=buttons003 onclick=qinc()>Corporal</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays Teddy, the man in the photo who was shot in Memento?",
"answ":"JOE PANTOLIANO",
"answ2":"Joe Pantoliano.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guy Pierce</button><button id=incop2 class=buttons003 onclick=qinc()>Russ Feja</button><button id=incop3 class=buttons003 onclick=qinc()>Mark Boone Jr</button><button id=corop class=buttons003 onclick=qcor()>Joe Pantoliano</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In which Christopher Nolan film does Carrie-Anne Moss play a character named Natalie?",
"answ":"MEMENTO",
"answ2":"Memento.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Memento</button><button id=incop2 class=buttons003 onclick=qinc()>Inception</button><button id=incop3 class=buttons003 onclick=qinc()>Dunkirk</button><button id=incop4 class=buttons003 onclick=qinc()>Insomnia</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Dark Knight Rises, who played the character of John Daggett who is a rival billionaire who employs Bane to take over Wayne Enterprises?",
"answ":"BEN MENDELSOHN",
"answ2":"Ben Mendelsohn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guy Pierce</button><button id=incop2 class=buttons003 onclick=qinc()>Aidan Gillen</button><button id=corop class=buttons003 onclick=qcor()>Ben Mendelsohn</button><button id=incop4 class=buttons003 onclick=qinc()>Cillian Murphy</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Interstellar who played Jessica Chastain's brother as an adult?",
"answ":"CASEY AFFLECK",
"answ2":"Casey Affleck.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joseph Gordon-Levitt</button><button id=corop class=buttons003 onclick=qcor()>Casey Affleck</button><button id=incop3 class=buttons003 onclick=qinc()>Topher Grace</button><button id=incop4 class=buttons003 onclick=qinc()>Armie Hammer</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What replicated objects lie in a wooded clearing at the opening of The Prestige?",
"answ":"TOP HATS",
"answ3":"TOP HAT",
"answ2":"Top hats.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Light bulbs</button><button id=corop class=buttons003 onclick=qcor()>Top hats</button><button id=incop3 class=buttons003 onclick=qinc()>Playing cards</button><button id=incop4 class=buttons003 onclick=qinc()>Candles</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Nolan's directorial debut feature Following, the main character is an unemployed what?",
"answ":"WRITER",
"answ2":"Writer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Locksmith</button><button id=incop2 class=buttons003 onclick=qinc()>Construction worker</button><button id=incop3 class=buttons003 onclick=qinc()>Teacher</button><button id=corop class=buttons003 onclick=qcor()>Writer</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays the shell shocked soldier that Mark Rylance rescues at sea in Dunkirk?",
"answ":"CILLIAN MURPHY",
"answ3":"CILIAN MURPHY",
"answ2":"Cillian Murphy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry Styles</button><button id=incop2 class=buttons003 onclick=qinc()>Alfie Allen</button><button id=incop3 class=buttons003 onclick=qinc()>Tom Hardy</button><button id=corop class=buttons003 onclick=qcor()>Cillian Murphy</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays adult Murph in Christopher Nolan's Interstellar?",
"answ":"JESSICA CHASTAIN",
"answ2":"Jessica Chastain.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Amy Adams</button><button id=incop2 class=buttons003 onclick=qinc()>Bryce Dallas Howard</button><button id=corop class=buttons003 onclick=qcor()>Jessica Chastain</button><button id=incop4 class=buttons003 onclick=qinc()>Emma Stone</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"How many movies directed by Christopher Nolan have had their scores composed by Hans Zimmer?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>4</button><button id=incop2 class=buttons003 onclick=qinc()>5</button><button id=corop class=buttons003 onclick=qcor()>6</button><button id=incop4 class=buttons003 onclick=qinc()>7</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Prestige, Robert Angier's wife Julia dies during a botched magic trick. How did she die?",
"answ":"SHE DROWNS",
"answ3":"DROWNING",
"answ2":"She drowns.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Decapitation</button><button id=incop2 class=buttons003 onclick=qinc()>Poison</button><button id=corop class=buttons003 onclick=qcor()>Drowning</button><button id=incop4 class=buttons003 onclick=qinc()>Allergic reaction</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Batman Begins, who plays William Earle, CEO of Wayne Enterprises while Bruce was 'away'?",
"answ":"RUTGER HAUER",
"answ2":"Rutger Hauer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Wilkinson</button><button id=corop class=buttons003 onclick=qcor()>Rutger Hauer</button><button id=incop3 class=buttons003 onclick=qinc()>John Glover</button><button id=incop4 class=buttons003 onclick=qinc()>Bruce Greenwood</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who played Hugh Jackman's assistant and lover Olivia in The Prestige?",
"answ":"SCARLETT JOHANSSON",
"answ3":"SCARLETT JOHANSON",
"answ2":"Scarlett Johansson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Olivia Wilde</button><button id=corop class=buttons003 onclick=qcor()>Scarlett Johansson</button><button id=incop3 class=buttons003 onclick=qinc()>Cate Blanchett</button><button id=incop4 class=buttons003 onclick=qinc()>Bryce Dallas Howard</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What was the first Christopher Nolan film in which Hans Zimmer received an Best Original Score nomination?",
"answ":"INCEPTION",
"answ2":"Inception.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Batman Begins</button><button id=corop class=buttons003 onclick=qcor()>Inception</button><button id=incop3 class=buttons003 onclick=qinc()>Interstellar</button><button id=incop4 class=buttons003 onclick=qinc()>The Dark Knight</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What was the name of Christopher Nolan's first feature film?",
"answ":"FOLLOWING",
"answ2":"Following.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Memento</button><button id=corop class=buttons003 onclick=qcor()>Following</button><button id=incop3 class=buttons003 onclick=qinc()>Insomnia</button><button id=incop4 class=buttons003 onclick=qinc()>Brick</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Insomnia, who plays the murder suspect Walter Finch?",
"answ":"ROBIN WILLIAMS",
"answ2":"Robin Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Caine</button><button id=corop class=buttons003 onclick=qcor()>Robin Williams</button><button id=incop3 class=buttons003 onclick=qinc()>John Goodman</button><button id=incop4 class=buttons003 onclick=qinc()>Jude Law</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"David Bowie makes a cameo in what Christopher Nolan movie?",
"answ":"THE PRESTIGE",
"answ3":"PRESTIGE",
"answ2":"The Prestige.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Memento</button><button id=corop class=buttons003 onclick=qcor()>The Prestige</button><button id=incop3 class=buttons003 onclick=qinc()>Insomnia</button><button id=incop4 class=buttons003 onclick=qinc()>Batman Begins</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Dunkirk, what item on Tom Hardy's Spitfire plane gets damaged during a dogfight?",
"answ":"FUEL GAUGE",
"answ2":"Fuel gauge.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Fuel gauge</button><button id=incop2 class=buttons003 onclick=qinc()>Airspeed indicator</button><button id=incop3 class=buttons003 onclick=qinc()>Magnetic compass</button><button id=incop4 class=buttons003 onclick=qinc()>Altimeter</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Christopher Nolan was an executive producer on this 2014 Johnny Depp flop.",
"answ":"TRANSCENDENCE",
"answ2":"Transcendence.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Transcendence</button><button id=incop2 class=buttons003 onclick=qinc()>The Lone Ranger</button><button id=incop3 class=buttons003 onclick=qinc()>Mortdecai</button><button id=incop4 class=buttons003 onclick=qinc()>Black Mass</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Wally Pfister won his Best Cinematography Academy Award for what Christopher Nolan film?",
"answ":"INCEPTION",
"answ2":"Inception.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Inception</button><button id=incop2 class=buttons003 onclick=qinc()>Dunkirk</button><button id=incop3 class=buttons003 onclick=qinc()>The Prestige</button><button id=incop4 class=buttons003 onclick=qinc()>Insomnia</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Dunkirk, what is the name of the sailing vessel captained by Mark Rylance's character?",
"answ":"MOONSTONE",
"answ3":"THE MOONSTONE",
"answ2":"Moonstone.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Moonstone</button><button id=incop2 class=buttons003 onclick=qinc()>Medway Queen</button><button id=incop3 class=buttons003 onclick=qinc()>Tamzine</button><button id=incop4 class=buttons003 onclick=qinc()>Sundowner</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays Dr. Mann, the brilliant scientist who was one of the original astronauts sent through the wormhole in Interstellar?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Matt Damon</button><button id=incop2 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=incop3 class=buttons003 onclick=qinc()>Bill Paxton</button><button id=incop4 class=buttons003 onclick=qinc()>Woody Harrelson</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Finish the quote from The Dark Knight Rises: 'You don't fear death. You welcome it. Your punishment must be more ____'?",
"answ":"SEVERE",
"answ2":"Severe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Creative</button><button id=incop2 class=buttons003 onclick=qinc()>Brutal</button><button id=incop3 class=buttons003 onclick=qinc()>Interesting</button><button id=corop class=buttons003 onclick=qcor()>Severe</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Anne Hathaway appears in The Dark Knight Rises and what other film from director Christopher Nolan?",
"answ":"INTERSTELLAR",
"answ2":"Interstellar.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Inception</button><button id=incop2 class=buttons003 onclick=qinc()>The Prestige</button><button id=incop3 class=buttons003 onclick=qinc()>Memento</button><button id=corop class=buttons003 onclick=qcor()>Interstellar</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Which actress plays Dr. Amelia Brand, the daughter of Michael Caine's character in Interstellar?",
"answ":"ANNE HATHAWAY",
"answ2":"Anne Hathaway.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Chastain</button><button id=incop2 class=buttons003 onclick=qinc()>Jennifer Garner</button><button id=incop3 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=corop class=buttons003 onclick=qcor()>Anne Hathaway</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Dark Knight Rises, what is the name of the computer program that Selina Kyle is after, where you can erase your name from all databases?",
"answ":"CLEAN SLATE",
"answ2":"Clean Slate.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fresh Start</button><button id=corop class=buttons003 onclick=qcor()>Clean Slate</button><button id=incop3 class=buttons003 onclick=qinc()>New Beginning</button><button id=incop4 class=buttons003 onclick=qinc()>Do Over</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Which Christopher Nolan film features the actors Jeremy Theobald, Alex Haw and Lucy Russell?",
"answ":"FOLLOWING",
"answ2":"Following.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Following</button><button id=incop2 class=buttons003 onclick=qinc()>Memento</button><button id=incop3 class=buttons003 onclick=qinc()>Insomnia</button><button id=incop4 class=buttons003 onclick=qinc()>Dunkirk</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays tough guy Eames in Nolan's Inception?",
"answ":"TOM HARDY",
"answ2":"Tom Hardy.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tom Hardy</button><button id=incop2 class=buttons003 onclick=qinc()>Cillian Murphy</button><button id=incop3 class=buttons003 onclick=qinc()>Ving Rhames</button><button id=incop4 class=buttons003 onclick=qinc()>Joseph Gordon-Levitt</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Interstellar, what is the name of the spacecraft that Matthew McConaughey is recruited to pilot?",
"answ":"ENDURANCE",
"answ3":"THE ENDURANCE",
"answ2":"Endurance.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Endurance</button><button id=incop2 class=buttons003 onclick=qinc()>Explorer</button><button id=incop3 class=buttons003 onclick=qinc()>Nostromo</button><button id=incop4 class=buttons003 onclick=qinc()>Daedalus</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who played Nikola Tesla in The Prestige?",
"answ":"DAVID BOWIE",
"answ2":"David Bowie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andy Serkis</button><button id=incop2 class=buttons003 onclick=qinc()>Ricky Jay</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Caine</button><button id=corop class=buttons003 onclick=qcor()>David Bowie</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who played Tommy in Dunkirk?",
"answ":"FIONN WHITEHEAD",
"answ3":"FION WHITEHEAD",
"answ2":"Fionn Whitehead.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry Styles</button><button id=incop2 class=buttons003 onclick=qinc()>Logan Lerman</button><button id=incop3 class=buttons003 onclick=qinc()>Barry Keoghan</button><button id=corop class=buttons003 onclick=qcor()>Fionn Whitehead</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Memento, Leonard is looking for someone with what name?",
"answ":"JOHN G",
"answ3":"JOHN",
"answ2":"John G.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry V.</button><button id=incop2 class=buttons003 onclick=qinc()>Lester B.</button><button id=incop3 class=buttons003 onclick=qinc()>Chris D.</button><button id=corop class=buttons003 onclick=qcor()>John G.</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Insomnia, Will and Hap are sent from what U.S. city to assist with the murder investigation?",
"answ":"LOS ANGELES",
"answ3":"LA",
"answ2":"Los Angeles.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago</button><button id=incop2 class=buttons003 onclick=qinc()>San Francisco</button><button id=incop3 class=buttons003 onclick=qinc()>New York</button><button id=corop class=buttons003 onclick=qcor()>Los Angeles</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What is the name that Liam Neeson uses when he first introduces himself to Bruce in Batman Begins?",
"answ":"DUCARD",
"answ3":"HENRI DUCARD",
"answ2":"Henri Ducard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dennis Cowan</button><button id=incop2 class=buttons003 onclick=qinc()>Nathan Dean</button><button id=incop3 class=buttons003 onclick=qinc()>Abraham Davis</button><button id=corop class=buttons003 onclick=qcor()>Henri Ducard</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What NFL team cameos in The Dark Knight Rises as The Gotham Rogues?",
"answ":"PITTSBURGH STEELERS",
"answ2":"Pittsburgh Steelers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>New York Jets</button><button id=incop2 class=buttons003 onclick=qinc()>Miami Dolphins</button><button id=incop3 class=buttons003 onclick=qinc()>Cleveland Browns</button><button id=corop class=buttons003 onclick=qcor()>Pittsburgh Steelers</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Which cinematographer has Nolan collaborated with the most?",
"answ":"WALLY PFISTER",
"answ3":"WALLY FISTER",
"answ2":"Wally Pfister.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emmanuel Lubezki</button><button id=incop2 class=buttons003 onclick=qinc()>Hoyte van Hoytema</button><button id=incop3 class=buttons003 onclick=qinc()>Roger Deakins</button><button id=corop class=buttons003 onclick=qcor()>Wally Pfister</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Prestige what magic trick did Robert Angier steal from Alfred Borden?",
"answ":"THE TRANSPORTED MAN",
"answ3":"TRANSPORTED MAN",
"answ2":"The Transported Man.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Transported Man</button><button id=incop2 class=buttons003 onclick=qinc()>The Drill of Death</button><button id=incop3 class=buttons003 onclick=qinc()>The Cabinet Escape</button><button id=incop4 class=buttons003 onclick=qinc()>The Bullet Catch</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Interstellar, what is the last viable crop on Earth?",
"answ":"CORN",
"answ3":"MAIZE",
"answ2":"Corn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Corn</button><button id=incop2 class=buttons003 onclick=qinc()>Potato</button><button id=incop3 class=buttons003 onclick=qinc()>Rice</button><button id=incop4 class=buttons003 onclick=qinc()>Wheat</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Batman Begins, what actor pretended to be Ra's al Ghul, before it was revealed it was actually Liam Neeson?",
"answ":"KEN WATANABE",
"answ2":"Ken Watanabe.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ken Watanabe</button><button id=incop2 class=buttons003 onclick=qinc()>Tom Wilkinson</button><button id=incop3 class=buttons003 onclick=qinc()>Rutger Hauer</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Nighy</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What movie gave Nolan his first Best Director nomination?",
"answ":"DUNKIRK",
"answ2":"Dunkirk.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dunkirk</button><button id=incop2 class=buttons003 onclick=qinc()>The Dark Knight</button><button id=incop3 class=buttons003 onclick=qinc()>The Prestige</button><button id=incop4 class=buttons003 onclick=qinc()>Inception</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Dark Knight, Bruce has to travel to what city in order to retrieve the accountant that is holding all the mobsters' money",
"answ":"HONG KONG",
"answ2":"Hong Kong.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hong Kong</button><button id=incop2 class=buttons003 onclick=qinc()>Paris</button><button id=incop3 class=buttons003 onclick=qinc()>Berlin</button><button id=incop4 class=buttons003 onclick=qinc()>Moscow</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Dark Knight Rises, what is the name of the police officer played by Joseph Gordon-Levitt?",
"answ":"JOHN BLAKE",
"answ2":"John Blake.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joseph Chill</button><button id=corop class=buttons003 onclick=qcor()>John Blake</button><button id=incop3 class=buttons003 onclick=qinc()>Peter Foley</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Wilson</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"What is the name of the company that hired Cobb's team in Inception?",
"answ":"COBOL ENGINEERING",
"answ2":"Cobol Engineering.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Virtucon</button><button id=corop class=buttons003 onclick=qcor()>Cobol Engineering</button><button id=incop3 class=buttons003 onclick=qinc()>Proclus Global</button><button id=incop4 class=buttons003 onclick=qinc()>Fischer Morrow</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays the younger version of Matthew McConaughey's son in Interstellar?",
"answ":"TIMOTHEE CHALAMET",
"answ3":"TIMOTHE CHALAMET",
"answ2":"Timothée Chalamet.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Holland</button><button id=corop class=buttons003 onclick=qcor()>Timothée Chalamet</button><button id=incop3 class=buttons003 onclick=qinc()>Nick Robinson</button><button id=incop4 class=buttons003 onclick=qinc()>Thomas Brodie-Sangster</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"Who plays Carmine Falcone in Batman Begins?",
"answ":"TOM WILKINSON",
"answ2":"Tom Wilkinson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ken Watanabe</button><button id=corop class=buttons003 onclick=qcor()>Tom Wilkinson</button><button id=incop3 class=buttons003 onclick=qinc()>John Doman</button><button id=incop4 class=buttons003 onclick=qinc()>Eric Roberts</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In Inception, Ariadne's totem is a slightly hollowed out chess piece, what chess piece is it?",
"answ":"BISHOP",
"answ2":"Bishop.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>King</button><button id=corop class=buttons003 onclick=qcor()>Bishop</button><button id=incop3 class=buttons003 onclick=qinc()>Queen</button><button id=incop4 class=buttons003 onclick=qinc()>Rook</button><br/>",
},
{
"cat":"Christopher Nolan",
"ques":"In The Prestige, Michael Caine's character explains that every great magic trick has how many parts?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
];
christophernolan = shuffle(christophernolan);
r2Q55 = shuffle(r2Q55);