var r2Q57 = [
{
"cat":"Meryl Streep",
"ques":"Meryl Streep famously said the line: 'The Dingo's got my baby' in what movie?",
"answ":"A CRY IN THE DARK",
"answ3":"EVIL ANGELS",
"answ2":"A Cry in the Dark.",
"option":["A Cry in the Dark", "Silkwood", "Sophie's Choice", "Ironweed"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep has a small role as cousin Topsy in what Disney film?",
"answ":"MARY POPPINS RETURNS",
"answ2":"Mary Poppins Returns.",
"option":["Mary Poppins Returns", "Enchanted", "Cinderella", "Maleficent"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed Meryl Streep and Anne Hathaway in the film The Devil Wears Prada?",
"answ":"DAVID FRANKEL",
"answ2":"David Frankel.",
"option":["David Frankel", "Neil Marshall", "Catherine Johnson", "Jonathan Demme"],
},
{
"cat":"Meryl Streep",
"ques":"In what film was Meryl Streep directed by Woody Allen?",
"answ":"MANHATTAN",
"answ2":"Manhattan.",
"option":["Manhattan", "To Rome With Love", "Cafe Society", "Annie Hall"],
},
{
"cat":"Meryl Streep",
"ques":"In the film Little Women, which actor plays Mr. Lawrence who is the father to Timothée Chalamet's character?",
"answ":"CHRIS COOPER",
"answ2":"Chris Cooper.",
"option":["Chris Cooper", "Jon Lithgow", "Jeff Bridges", "Nick Nolte"],
},
{
"cat":"Meryl Streep",
"ques":"In what 2008 drama do Meryl Streep and Amy Adams play nuns?",
"answ":"DOUBT",
"answ2":"Doubt.",
"option":["Doubt", "It's Complicated", "Lions for Lambs", "Julie & Julia"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep plays real life chef Julia Child in what 2009 film?",
"answ":"JULIE AND JULIA",
"answ2":"Julie & Julia.",
"option":["Julie & Julia", "The Hours", "Defending Your Life", "Rendition"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep and Alec Baldwin play an ex-wife and ex-husband in what 2009 romcom?",
"answ":"IT'S COMPLICATED",
"answ2":"It's Complicated.",
"option":["It's Complicated", "Mamma Mia!", "Hope Springs", "Julie & Julia"],
},
{
"cat":"Meryl Streep",
"ques":"John C. Reilly and Kevin Bacon star as bank robbing villains that take Meryl Streep and her family hostage in which film?",
"answ":"THE RIVER WILD",
"answ3":"RIVER WILD",
"answ2":"The River Wild.",
"option":["The River Wild", "Death Becomes Her", "Postcards from the Edge", "Doubt"],
},
{
"cat":"Meryl Streep",
"ques":"Who played writer Helen Sharp opposite Meryl Streep in Death Becomes Her?",
"answ":"GOLDIE HAWN",
"answ2":"Goldie Hawn.",
"option":["Goldie Hawn", "Catherine Keener", "Marisa Tomei", "Nicole Kidman"],
},
{
"cat":"Meryl Streep",
"ques":"In which 2014 musical does Meryl play a character simply known as The Witch opposite characters like Cinderella and the Baker?",
"answ":"INTO THE WOODS",
"answ2":"Into the Woods.",
"option":["Into the Woods", "Cinderella", "Mary Poppins Returns", "The Giver"],
},
{
"cat":"Meryl Streep",
"ques":"Who plays Meryl's daughter Sophie in Mamma Mia?",
"answ":"AMANDA SEYFRIED",
"answ2":"Amanda Seyfried.",
"option":["Amanda Seyfried", "Anna Paquin", "Lindsay Lohan", "Kristen Bell"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep starred in both Adaptation and The Hours in what year?",
"answ":"2002",
"answ2":"2002.",
"option":["2002", "2001", "2000", "2003"],
},
{
"cat":"Meryl Streep",
"ques":"According to Meryl Streep's Miranda Priestly, what is the actual color of Andy's blue sweater in The Devil's Wears Prada?",
"answ":"CERULEAN",
"answ2":"Cerulean.",
"option":["Cerulean", "Purple", "Azure", "Indigo"],
},
{
"cat":"Meryl Streep",
"ques":"For which film did Meryl Streep win her first Oscar?",
"answ":"KRAMER VS KRAMER",
"answ2":"Kramer vs Kramer.",
"option":["Kramer vs Kramer", "Sophie's Choice", "The Deer Hunter", "The Devil Wears Prada"],
},
{
"cat":"Meryl Streep",
"ques":"In an attempt to rekindle their marriage Meryl performs fellatio on Tommy Lee Jones at a movie theater in which film?",
"answ":"HOPE SPRINGS",
"answ2":"Hope Springs.",
"option":["Hope Springs", "It's Complicated", "The Hours", "Heartburn"],
},
{
"cat":"Meryl Streep",
"ques":"What was the first name of Meryl's character in The Devil Wears Prada?",
"answ":"MIRANDA	",
"answ2":"Miranda.",
"option":["Miranda", "Lucy", "Diana", "Rebecca"],
},
{
"cat":"Meryl Streep",
"ques":"What 1978 film features Meryl Streep, Christopher Walken and John Savage?",
"answ":"THE DEER HUNTER",
"answ2":"The Deer Hunter.",
"option":["The Deer Hunter", "Midnight Express", "Heaven Can Wait", "Coming Home"],
},
{
"cat":"Meryl Streep",
"ques":"Who played big-game hunter, Denys Finch Hatton, opposite Meryl Streep in 1985's Out of Africa?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
"option":["Robert Redford", "Kevin Costner", "Clint Eastwood", "Patrick Swayze"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep and Tom Hanks star in what 2017 historical thriller about The Pentagon Papers?",
"answ":"THE POST",
"answ2":"The Post.",
"option":["The Post", "Spotlight", "This Changes Everything", "A Hologram for the King"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep and George Clooney star together in what 2009 animated film?",
"answ":"FANTASTIC MR FOX",
"answ3":"THE FANTASTIC MR FOX",
"answ2":"Fantastic Mr. Fox.",
"option":["Fantastic Mr. Fox", "The Ant Bully", "Monsters vs. Aliens", "9"],
},
{
"cat":"Meryl Streep",
"ques":"Nora Ephron directed Meryl Streep and Amy Adams in what 2009 drama?",
"answ":"JULIE AND JULIA",
"answ2":"Julie & Julia.",
"option":["Julie & Julia", "It's Complicated", "Lions for Lambs", "The Iron Lady"],
},
{
"cat":"Meryl Streep",
"ques":"What 90s romantic drama stars Clint Eastwood and Meryl Streep?",
"answ":"THE BRIDGES OF MADISON COUNTY",
"answ3":"BRIDGES OF MADISON COUNTY",
"answ2":"The Bridges of Madison County.",
"option":["The Bridges of Madison County", "The House of the Spirits", "Before and After", "Dancing at Lughnasa"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep portrays Margaret Thatcher in this 2012 film.",
"answ":"THE IRON LADY",
"answ3":"IRON LADY",
"answ2":"The Iron Lady.",
"option":["The Iron Lady", "The King's Speech", "Margaret", "Suffragette"],
},
{
"cat":"Meryl Streep",
"ques":"Who plays Meryl Streep's ex-husband in 2009's It's Complicated?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
"option":["Alec Baldwin", "Bruce Willis", "Anthony Hopkins", "Jack Nicholson"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep won a Best Actress Oscar for what 2012 film?",
"answ":"THE IRON LADY",
"answ3":"IRON LADY",
"answ2":"The Iron Lady.",
"option":["The Iron Lady", "Hope Springs", "Julie & Julia", "Suffragette"],
},
{
"cat":"Meryl Streep",
"ques":"Who plays Meryl Streep's husband in 1994's The River Wild?",
"answ":"DAVID STRATHAIRN",
"answ3":"DAVID STRATHARN",
"answ2":"David Strathairn.",
"option":["David Strathairn", "Harrison Ford", "Kevin Bacon", "Liam Neeson"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed Meryl Streep in Ricki and The Flash?",
"answ":"JONATHAN DEMME",
"answ2":"Jonathan Demme.",
"option":["Jonathan Demme", "John Wells", "Robert Redford", "David Frankel"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep received her first Oscar nomination for her performance in which film?",
"answ":"THE DEER HUNTER",
"answ3":"DEER HUNTER",
"answ2":"The Deer Hunter.",
"option":["The Deer Hunter", "Kramer vs. Kramer", "Sophie's Choice", "The French Lieutenant's Woman"],
},
{
"cat":"Meryl Streep",
"ques":"Who played Meryl Streep's husband in 1988's Evil Angels?",
"answ":"SAM NEILL",
"answ2":"Sam Neill.",
"option":["Sam Neill", "Jack Nicholson", "Robert De Niro", "Kurt Russell"],
},
{
"cat":"Meryl Streep",
"ques":"In what film does Meryl Streep play a ruthless fashion magazine editor?",
"answ":"DEVIL WEARS PRADA",
"answ3":"THE DEVIL WEARS PRADA",
"answ2":"The Devil Wears Prada.",
"option":["The Devil Wears Prada", "Adaptation", "She-Devil", "Sophie's Choice"],
},
{
"cat":"Meryl Streep",
"ques":"In Hope Springs, Meryl Streep plays a woman who is looking to reignite her marriage. Who plays her husband?",
"answ":"TOMMY LEE JONES",
"answ2":"Tommy Lee Jones.",
"option":["Tommy Lee Jones", "Harrison Ford", "Dennis Quaid", "Liam Neeson"],
},
{
"cat":"Meryl Streep",
"ques":"How many Academy Awards has Meryl Streep won in her career?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "1", "4"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed Meryl Streep in the 1983 film Silkwood?",
"answ":"MIKE NICHOLS",
"answ2":"Mike Nichols.",
"option":["Mike Nichols", "Alan J. Pakula", "Robert Benton", "Sydney Pollack"],
},
{
"cat":"Meryl Streep",
"ques":"What 2002 film from Spike Jonze stars Nicolas Cage and Meryl Streep as real life writers Charlie Kaufman and Susan Orlean?",
"answ":"ADAPTATION",
"answ2":"Adaptation.",
"option":["Adaptation", "One True Thing", "Music of the Heart", "The Hours"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep starred as Lindy Chamberlain in what 1988 film?",
"answ":"A CRY IN THE DARK",
"answ2":"A Cry in the Dark.",
"option":["A Cry in the Dark", "Ironweed", "She-Devil", "Postcards from the Edge"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed 2006's A Prairie Home Companion?",
"answ":"ROBERT ALTMAN",
"answ2":"Robert Altman.",
"option":["Robert Altman", "Nora Ephron", "Nancy Meyers", "Mike Nichols"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep plays violinist Roberta Guaspari in what film?",
"answ":"MUSIC OF THE HEART",
"answ2":"Music of the Heart.",
"option":["Music of the Heart", "A Little Night Music", "Can't Stop the Music", "Miss Saigon"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep stars alongside Liam Neeson and Edward Furlong in what 90s film?",
"answ":"BEFORE AND AFTER",
"answ2":"Before and After.",
"option":["Before and After", "The House of the Spirits", "The River Wild", "One True Thing"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep starred as vain actress Madeline Ashton in this 1992 comedy.",
"answ":"DEATH BECOMES HER",
"answ2":"Death Becomes Her.",
"option":["Death Becomes Her", "Postcards From The Edge", "Noises Off", "Straight Talk"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed 2014's Into the Woods?",
"answ":"ROB MARSHALL",
"answ2":"Rob Marshall.",
"option":["Rob Marshall", "Bill Condon", "Joel Schumacher", "Baz Luhrmann"],
},
{
"cat":"Meryl Streep",
"ques":"Kevin Kline plays Meryl Streep's emotionally unstable lover, Nathan Landau, in this film.",
"answ":"SOPHIE'S CHOICE",
"answ2":"Sophie's Choice.",
"option":["Sophie's Choice", "Silkwood", "August Osage County", "Julie and Julia"],
},
{
"cat":"Meryl Streep",
"ques":"In what film does Meryl Steep act opposite Stanley Tucci, Emily Blunt and Simon Baker?",
"answ":"DEVIL WEARS PRADA",
"answ3":"THE DEVIL WEARS PRADA",
"answ2":"The Devil Wears Prada.",
"option":["The Devil Wears Prada", "Into the Woods", "August Osage County", "The Bridges of Madison County"],
},
{
"cat":"Meryl Streep",
"ques":"Who directed Meryl Streep in the 2008 film Doubt?",
"answ":"JOHN PATRICK SHANLEY",
"answ2":"John Patrick Shanley.",
"option":["John Patrick Shanley", "Nancy Meyers", "Gavin Hood", "David Frankel"],
},
{
"cat":"Meryl Streep",
"ques":"What is the only film in which Meryl Streep has returned to reprise her role for a sequel?",
"answ":"MAMMA MIA HERE WE GO AGAIN",
"answ2":"Mamma Mia Here We Go Again.",
"option":["Mamma Mia Here We Go Again", "The Huntsman: Winter's War", "Shrek 2", "Stuart Little 2"],
},
{
"cat":"Meryl Streep",
"ques":"Which Spielberg film did Meryl get her most recent nomination or Best Actress?",
"answ":"THE POST",
"answ2":"The Post.",
"option":["The Post", "Ready Player One", "Bridge of Spies", "Lincoln"],
},
{
"cat":"Meryl Streep",
"ques":"Meryl Streep plays a shady U.S. Senator by the name of Eleanor Shaw in what 2000s film?",
"answ":"THE MANCHURIAN CANDIDATE",
"answ3":"MANCHURIAN CANDIDATE",
"answ2":"The Manchurian Candidate.",
"option":["The Manchurian Candidate", "Lions for Lambs", "The Hours", "Rendition"],
},
];
r2Q57 = shuffle(r2Q57);