var jamesbond = [
{
"cat":"James Bond",
"ques":"Who directed Skyfall?",
"answ":"SAM MENDES",
"answ2":"Sam Mendes.",
},
{
"cat":"James Bond",
"ques":"Who plays James Bond in the 1983 film Never Say Never Again?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
},
{
"cat":"James Bond",
"ques":"What was the second film that Roger Moore played Bond in?",
"answ":"THE MAN WITH THE GOLDEN GUN",
"answ3":"MAN WITH THE GOLDEN GUN",
"answ2":"The Man with the Golden Gun.",
},
{
"cat":"James Bond",
"ques":"In which of the Daniel Craig James Bond films does 007 first face off against the famous villain Blofeld?",
"answ":"SPECTRE",
"answ2":"Spectre.",
},
{
"cat":"James Bond",
"ques":"In License to Kill, what are Sanchez's scientists dissolving cocaine in?",
"answ":"PETROL",
"answ3":"GASOLINE",
"answ2":"Petrol/Gasoline.",
},
{
"cat":"James Bond",
"ques":"Who directed From Russia with Love and Thunderball?",
"answ":"TERENCE YOUNG",
"answ2":"Terence Young.",
},
{
"cat":"James Bond",
"ques":"Gloria Hendry and Jane Seymour play Bond girls in what James Bond film?",
"answ":"LIVE AND LET DIE",
"answ2":"Live and Let Die.",
},
{
"cat":"James Bond",
"ques":"In A View to a Kill, Bond first sees Max Zorin at what specific type of sporting event?",
"answ":"HORSE RACE",
"answ3":"HORSE RACING",
"answ2":"Horse race.",
},
{
"cat":"James Bond",
"ques":"Who plays James Bond in Tomorrow Never Dies?",
"answ":"PIERCE BROSNAN",
"answ2":"Pierce Brosnan.",
},
{
"cat":"James Bond",
"ques":"How many Daniel Craig James Bond film has Sam Mendes directed?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"James Bond",
"ques":"Robert Carlyle plays a Bond villain that feels no pain in which James Bond film?",
"answ":"THE WORLD IS NOT ENOUGH",
"answ2":"The World Is Not Enough.",
},
{
"cat":"James Bond",
"ques":"A View to Kill was the last Bond movie to star which actor as 007?",
"answ":"ROGER MOORE",
"answ2":"Roger Moore.",
},
{
"cat":"James Bond",
"ques":"Which James Bond movie featured Pierce Brosnan's first appearance as Agent 007?",
"answ":"GOLDENEYE",
"answ2":"GoldenEye.",
},
{
"cat":"James Bond",
"ques":"Who played James Bond in The Living Daylights?",
"answ":"TIMOTHY DALTON",
"answ2":"Timothy Dalton.",
},
{
"cat":"James Bond",
"ques":"Who plays James Bond in the films You Only Live Twice and Diamonds Are Forever?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
},
];
var r2Q58 = [
{
"cat":"James Bond",
"ques":"In Die Another Day, Miranda Frost is an expert in what olympic event?",
"answ":"FENCING",
"answ2":"Fencing.",
"option":["Fencing", "Swimming", "Judo", "Sailing"],
},
{
"cat":"James Bond",
"ques":"Who plays nuclear physicist Christmas Jones in the 1999 James Bond film The World is Not Enough?",
"answ":"DENISE RICHARDS",
"answ2":"Denise Richards.",
"option":["Denise Richards", "Sophie Marceau", "Gemma Arterton", "Rosamund Pike"],
},
{
"cat":"James Bond",
"ques":"Who plays the villainous Raoul Silva in the James Bond film Skyfall?",
"answ":"JAVIER BARDEM",
"answ2":"Javier Bardem.",
"option":["Javier Bardem", "Jeffrey Dean Morgan", "Benicio del Toro", "Kirk Acevedo"],
},
{
"cat":"James Bond",
"ques":"1983 saw the release of the official Bond film Octopussy as well as what unofficial Bond film starring Sean Connery?",
"answ":"NEVER SAY NEVER AGAIN",
"answ2":"Never Say Never Again.",
"option":["Never Say Never Again", "Moonraker", "For Your Eyes Only", "A View to Kill"],
},
{
"cat":"James Bond",
"ques":"What Oscar-nominated actress plays Moneypenny in recent Bond films Skyfall and Spectre?",
"answ":"NAOMIE HARRIS",
"answ2":"Naomie Harris.",
"option":["Naomie Harris", "Judi Dench", "Maggie Smith", "Samantha Bond"],
},
{
"cat":"James Bond",
"ques":"What Oscar-winning actress played Jinx opposite Pierce Brosnan in Die Another Day?",
"answ":"HALLE BARRY",
"answ3":"HALLE BERRY",
"answ2":"Halle Berry.",
"option":["Halle Berry", "Rosamund Pike", "Judi Dench", "Samantha Bond"],
},
{
"cat":"James Bond",
"ques":"What was the first James Bond movie to receive an Oscar?",
"answ":"GOLDFINGER",
"answ2":"Goldfinger.",
"option":["Goldfinger", "Diamonds Are Forever", "From Russia with Love", "The Spy Who Loved Me"],
},
{
"cat":"James Bond",
"ques":"Who played the sexy Bond baddie Xenia Onatopp in GoldenEye?",
"answ":"FAMKE JANSSEN",
"answ3":"FAMKE JANSEN",
"answ2":"Famke Janssen.",
"option":["Famke Janssen", "Eva Green", "Halle Berry", "Michelle Yeoh"],
},
{
"cat":"James Bond",
"ques":"How many James Bond movies did the villain named 'Jaws' appear in?",
"answ":"TWO",
"answ3":"2",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"James Bond",
"ques":"What actress played Vesper Lynd in 2006's Casino Royale?",
"answ":"EVA GREEN",
"answ2":"Eva Green.",
"option":["Eva Green", "Naomie Harris", "Olga Kurylenko", "Gemma Arterton"],
},
{
"cat":"James Bond",
"ques":"Actress Michelle Yeoh appeared in which Bond movie?",
"answ":"TOMORROW NEVER DIES",
"answ2":"Tomorrow Never Dies.",
"option":["Tomorrow Never Dies", "Die Another Day", "GoldenEye", "The World is Not Enough"],
},
{
"cat":"James Bond",
"ques":"In The World is Not Enough, who played the main villain, Renard, who had a bullet lodged in his brain which rendered him impervious to pain?",
"answ":"ROBERT CARLYLE",
"answ2":"Robert Carlyle.",
"option":["Robert Carlyle", "Jonathan Pryce", "Toby Stephens", "Michael Madsen"],
},
{
"cat":"James Bond",
"ques":"Who played Ernst Stavro Blofeld in 2015's Spectre?",
"answ":"CHRISTOPH WALTZ",
"answ2":"Christoph Waltz.",
"option":["Christoph Waltz", "Ralph Fiennes", "Daniel Brühl", "Rami Malek"],
},
{
"cat":"James Bond",
"ques":"Which James Bond movie featured Sean Bean as the villain?",
"answ":"GOLDENEYE",
"answ2":"GoldenEye.",
"option":["GoldenEye", "Casino Royale", "Die Another Day", "Tomorrow Never Dies"],
},
{
"cat":"James Bond",
"ques":"The unofficial Bond film Never Say Never Agin was released in 1983. What official Bond film was released the same year?",
"answ":"OCTOPUSSY",
"answ2":"Octopussy.",
"option":["Octopussy", "For Your Eyes Only", "A View to a Kill", "The Living Daylights"],
},
{
"cat":"James Bond",
"ques":"What type of gun has historically been James Bond's weapon of choice?",
"answ":"WALTHER PPK",
"answ3":"WALTER PPK",
"answ2":"Walther PPK.",
"option":["Walther PPK", "Glock 18", "Desert Eagle", "Beretta 418"],
},
{
"cat":"James Bond",
"ques":"Roger Spottiswoode directed which Pierce Brosnan Bond film?",
"answ":"TOMORROW NEVER DIES",
"answ2":"Tomorrow Never Dies.",
"option":["Tomorrow Never Dies", "The World Is Not Enough", "Die Another Day", "GoldenEye"],
},
{
"cat":"James Bond",
"ques":"In how many movies did Roger Moore star as James Bond?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":["7", "6", "5", "8"],
},
{
"cat":"James Bond",
"ques":"In how many movies did Timothy Dalton star as James Bond?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"James Bond",
"ques":"In how many movies did Pierce Brosnan star as James Bond?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":["4", "2", "3", "1"],
},
{
"cat":"James Bond",
"ques":"Who portrayed Blofeld in On Her Majesty's Secret Service?",
"answ":"TELLY SAVALAS",
"answ2":"Telly Savalas.",
"option":["Telly Savalas", "Bernard Lee", "Desmond Llewelyn", "Bernard Horsfall"],
},
{
"cat":"James Bond",
"ques":"Which Bond film's tagline was 'The dead are alive'?",
"answ":"SPECTRE",
"answ2":"Spectre.",
"option":["Spectre", "A View to Kill", "The Living Daylights", "You Only Live Twice"],
},
{
"cat":"James Bond",
"ques":"Olga Kurylenko played a Bond girl named Camille in what Daniel Craig Bond film?",
"answ":"QUANTUM OF SOLACE",
"answ2":"Quantum of Solace.",
"option":["Quantum of Solace", "Spectre", "Casino Royale", "Skyfall"],
},
{
"cat":"James Bond",
"ques":"Which Bond film is set primarily in Japan?",
"answ":"YOU ONLY LIVE TWICE",
"answ2":"You Only Live Twice.",
"option":["You Only Live Twice", "Octopussy", "Die Another Day", "License to Kill"],
},
{
"cat":"James Bond",
"ques":"What artist performed 3 title songs in the Bond franchise?",
"answ":"SHIRLEY BASSEY",
"answ2":"Shirley Bassey.",
"option":["Shirley Bassey", "Rita Coolidge", "Sheena Easton", "Gladys Knight"],
},
{
"cat":"James Bond",
"ques":"The evil organization of Janus can be found in which Pierce Brosnan-era Bond film?",
"answ":"GOLDENEYE",
"answ2":"GoldenEye.",
"option":["GoldenEye", "Tomorrow Never Dies", "The World Is Not Enough", "Die Another Day"],
},
{
"cat":"James Bond",
"ques":"In which James Bond film will you find a villain named Hugo Drax?",
"answ":"MOONRAKER",
"answ2":"Moonraker.",
"option":["Moonraker", "Tomorrow Never Dies", "On Her Majesty's Secret Service", "A View to a Kill"],
},
{
"cat":"James Bond",
"ques":"Who played Tracy di Vicenzo, the woman James Bond marries at the end of On Her Majesty's Secret Service?",
"answ":"DIANA RIGG",
"answ2":"Diana Rigg.",
"option":["Diana Rigg", "Britt Erkland", "Ursula Andress", "Honor Blackman"],
},
{
"cat":"James Bond",
"ques":"Who sang the title song for the James Bond movie Thunderball?",
"answ":"TOM JONES",
"answ2":"Tom Jones.",
"option":["Tom Jones", "Louis Armstrong", "Shirley Bassey", "Rita Coolidge"],
},
{
"cat":"James Bond",
"ques":"Which villain responded to Bond with 'No, Mr. Bond. I expect you to die.' after James asked if he was expected to talk?",
"answ":"AURIC GOLDFINGER",
"answ3":"GOLDFINGER",
"answ2":"Auric Goldfinger.",
"option":["Auric Goldfinger", "Ernst Stavro Blofeld", "Dr. No", "Jaws"],
},
{
"cat":"James Bond",
"ques":"Who plays Scaramanga, the assassin hired to kill James Bond, in The Man with the Golden Gun?",
"answ":"CHRISTOPHER LEE",
"answ2":"Christopher Lee.",
"option":["Christopher Lee", "Donald Sutherland", "Max von Sydow", "Michael Caine"],
},
{
"cat":"James Bond",
"ques":"How many Bond movies have won the Oscar for Best Original Song?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"James Bond",
"ques":"What Harry Potter actor played former Russian maffia boss and casino owner Valentin Zukofski in The World is Not Enough?",
"answ":"ROBBIE COLTRANE",
"answ2":"Robbie Coltrane.",
"option":["Robbie Coltrane", "Alan Rickman", "Michael Gambon", "Ralph Fiennes"],
},
{
"cat":"James Bond",
"ques":"In the 2002 film Die Another Day, James Bond spends 14 months as a prisoner in which country?",
"answ":"NORTH KOREA",
"answ2":"North Korea.",
"option":["North Korea", "China", "Russia", "Iran"],
},
{
"cat":"James Bond",
"ques":"Who portrayed Blofeld in You Only Live Twice?",
"answ":"DONALD PLEASENCE",
"answ3":"DONALD PLEASANCE",
"answ2":"Donald Pleasence.",
"option":["Donald Pleasence", "Christopher Lee", "Gert Fröbe", "Adolfo Celi"],
},
{
"cat":"James Bond",
"ques":"Bond gives Dominic Green a can of what to drink, while stranding him in the desert in Quantum of Solace?",
"answ":"MOTOR OIL",
"answ2":"Motor oil.",
"option":["Motor oil", "Beer", "Antifreeze", "Drain cleaner"],
},
{
"cat":"James Bond",
"ques":"Which actor from the X-Men franchise plays computer programmer Boris Grishenko in GoldenEye?",
"answ":"ALAN CUMMING",
"answ2":"Alan Cumming.",
"option":["Alan Cumming", "Brian Cox", "Bruce Davison", "Aaron Stanford"],
},
{
"cat":"James Bond",
"ques":"Dr. No largely takes place in what country in the Caribbean?",
"answ":"JAMAICA",
"answ2":"Jamaica.",
"option":["Jamaica", "Cuba", "Dominican Republic", "Haiti"],
},
{
"cat":"James Bond",
"ques":"Which Roger Moore Bond film has a villain named Kananga?",
"answ":"LIVE AND LET DIE",
"answ2":"Live and Let Die.",
"option":["Live and Let Die", "A View to a Kill", "The Spy Who Loved Me", "For Your Eyes Only"],
},
{
"cat":"James Bond",
"ques":"Which alternative rock band performed the title song in The World Is Not Enough?",
"answ":"GARBAGE",
"answ2":"Garbage.",
"option":["Garbage", "Nirvana", "Pearl Jam", "Pixies"],
},
{
"cat":"James Bond",
"ques":"Which actress plays Madeleine Swann in Spectre?",
"answ":"LEA SEYDOUX",
"answ2":"Léa Seydoux.",
"option":["Léa Seydoux", "Marion Cotillard", "Gemma Arterton", "Bérénice Marlohe"],
},
{
"cat":"James Bond",
"ques":"Bond girl Kara Milovy plays what classical music instrument in The Living Daylights?",
"answ":"CELLO",
"answ2":"Cello.",
"option":["Cello", "Harp", "Piano", "Lute"],
},
{
"cat":"James Bond",
"ques":"Which character in the Bond franchise has been played by actors Bernard Lee and Robert Brown?",
"answ":"M",
"answ2":"M.",
"option":["M", "Le Chiffre", "Ernst Stavro Blofeld", "Q"],
},
{
"cat":"James Bond",
"ques":"In Live and Let Die, Jane Seymour plays a Bond girl who shares her name with a type of card game. What is her name?",
"answ":"SOLITAIRE",
"answ2":"Solitaire.",
"option":["Solitaire", "Uno", "Patience", "Poker"],
},
{
"cat":"James Bond",
"ques":"What was Pierce Brosnan's first James Bond film?",
"answ":"GOLDENEYE",
"answ2":"GoldenEye.",
"option":["GoldenEye", "Tomorrow Never Dies", "The World Is Not Enough", "Die Another Day"],
},
{
"cat":"James Bond",
"ques":"In 1964's Goldfinger, after destroying a drug laboratory in Latin America, James Bond travels where for a vacation?",
"answ":"MIAMI",
"answ2":"Miami.",
"option":["Miami", "Atlantic City", "Grand Canyon", "New Orleans"],
},
{
"cat":"James Bond",
"ques":"Who played Bond girl Kara Milovy in The Living Daylights?",
"answ":"MARYAM D'ABO",
"answ2":"Maryam d'Abo.",
"option":["Maryam d'Abo", "Carey Lowell", "Tanya Roberts", "Kell Tyler"],
},
{
"cat":"James Bond",
"ques":"Gemma Arterton plays a Bond girl in Quantum of Solace whose name evokes a famous Beatles song. What is her name?",
"answ":"STRAWBERRY FIELDS",
"answ2":"Strawberry Fields.",
"option":["Strawberry Fields", "Penny Lane", "Eleanor Rigby", "Maggie Mae"],
},
{
"cat":"James Bond",
"ques":"Who directed every official James Bond film that was released in the 1980s?",
"answ":"JOHN GLEN",
"answ3":"JOHN GLENN",
"answ2":"John Glen.",
"option":["John Glen", "Lewis Gilbert", "Peter Hunt", "Martin Campbell"],
},
{
"cat":"James Bond",
"ques":"Bond gets married to a woman named Tracy in what James Bond film?",
"answ":"ON HER MAJESTY'S SECRET SERVICE",
"answ2":"On Her Majesty's Secret Service.",
"option":["On Her Majesty's Secret Service", "You Only Live Twice", "For Your Eyes Only", "The Living Daylights"],
},
{
"cat":"James Bond",
"ques":"In what Roger Moore Bond film does Bond drop a villain who appears to be Blofeld into a factory chimney during the film's cold open?",
"answ":"FOR YOUR EYES ONLY",
"answ2":"For Your Eyes Only.",
"option":["For Your Eyes Only", "Live and Let Die", "The Spy Who Loved Me", "A View to a Kill"],
},
{
"cat":"James Bond",
"ques":"In Tomorrow Never Dies, who stars as Elliot Carver, a psychotic media mogul who plans to provoke global war to boost sales and ratings for his news division?",
"answ":"JONATHAN PRYCE",
"answ3":"JONATHAN PRICE",
"answ2":"Jonathan Pryce.",
"option":["Jonathan Pryce", "Richard Dreyfuss", "James Woods", "Sean Bean"],
},
{
"cat":"James Bond",
"ques":"Sean Connery played James Bond seven times. What was the fourth film in which he portrayed the spy?",
"answ":"THUNDERBALL",
"answ2":"Thunderball.",
"option":["Thunderball", "You Only Live Twice", "Diamonds Are Forever", "Goldfinger"],
},
{
"cat":"James Bond",
"ques":"Which famous pop band performed the title track for 1985's A View to a Kill?",
"answ":"DURAN DURAN",
"answ2":"Duran Duran.",
"option":["Duran Duran", "A-ha", "The Pretenders", "Aerosmith"],
},
{
"cat":"James Bond",
"ques":"What year saw the release of the James Bond film GoldenEye?",
"answ":"1995",
"answ2":"1995.",
"option":["1995", "1994", "1996", "1997"],
},
{
"cat":"James Bond",
"ques":"What famous landmark does Grace Jones jump from in A View to a Kill?",
"answ":"THE EIFFEL TOWER",
"answ3":"EIFFEL TOWER",
"answ2":"Eiffel Tower.",
"option":["Eiffel Tower", "Statue of Liberty", "Big Ben", "Notre Dame"],
},
{
"cat":"James Bond",
"ques":"In the Bond franchise, who was the first actor to portray M?",
"answ":"BERNARD LEE",
"answ2":"Bernard Lee.",
"option":["Bernard Lee", "Jack Lord", "Robert Brown", "Anthony Dawson"],
},
{
"cat":"James Bond",
"ques":"In The Man with the Golden Gun, what is the name of Scaramanga's tiny assistant ?",
"answ":"NICK NACK",
"answ3":"NICK",
"answ2":"Nick Nack.",
"option":["Nick Nack", "Andrea Anders", "Joey Joe", "Jack Jack"],
},
{
"cat":"James Bond",
"ques":"Name the movie: James Bond investigates the hijacking of British and Russian submarines carrying nuclear warheads with the help of a KGB agent whose lover he killed.",
"answ":"THE SPY WHO LOVED ME",
"answ3":"SPY WHO LOVED ME",
"answ2":"The Spy Who Loved Me.",
"option":["The Spy Who Loved Me", "Diamonds Are Forever", "The Man with the Golden Gun", "The Living Daylights"],
},
{
"cat":"James Bond",
"ques":"John Glen holds the record for directing the most James Bond films with how many entries to his name?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
"option":["5", "6", "7", "3"],
},
{
"cat":"James Bond",
"ques":"Spectre opens with James Bond carrying out an unauthorized mission on the Day of the Dead in which Latin American city?",
"answ":"MEXICO CITY",
"answ2":"Mexico City.",
"option":["Mexico City", "Buenos Aires", "Bogota", "Rio de Janeiro"],
},
{
"cat":"James Bond",
"ques":"In License to Kill, villain Franz Sanchez torments Felix Leiter by having what type of animal attack him?",
"answ":"SHARK",
"answ3":"SHARKS",
"answ2":"Shark.",
"option":["Shark", "Tiger", "Snake", "Alligator"],
},
{
"cat":"James Bond",
"ques":"Which James Bond movie marks the first appearance of John Cleese in the franchise?",
"answ":"THE WORLD IS NOT ENOUGH",
"answ2":"The World Is Not Enough.",
"option":["The World Is Not Enough", "Tomorrow Never Dies", "GoldenEye", "Die Another Day"],
},
{
"cat":"James Bond",
"ques":"Which actress played Bond girl Tiffany Case in Diamonds Are Forever?",
"answ":"JILL ST JOHN",
"answ3":"JILL SAINT JOHN",
"answ2":"Jill St. John.",
"option":["Jill St. John", "Jill Ireland", "Jane Seymour", "Maude Adams"],
},
{
"cat":"James Bond",
"ques":"In 1969's On Her Majesty's Secret Service, Bond takes what false identity in order to infiltrate Blofeld's mountain estate?",
"answ":"HILLARY BRAY",
"answ3":"HILARY BRAY",
"answ2":"Hillary Bray.",
"option":["Sir Hillary Bray", "Sir William Roberts", "Sir Albert Kinkaid", "Sir Myron Hingle"],
},
{
"cat":"James Bond",
"ques":"In which Roger Moore film does a fake faberge egg, and a fellow agent's death, lead 007 to uncover an international jewel-smuggling operation?",
"answ":"OCTOPUSSY",
"answ2":"Octopussy.",
"option":["Octopussy", "Live and Let Die", "The Man with the Golden Gun", "Moonraker"],
},
{
"cat":"James Bond",
"ques":"Who performed the theme song for Live and Let Die?",
"answ":"WINGS",
"answ3":"PAUL MCCARTNEY AND WINGS",
"answ2":"Paul McCartney and Wings.",
"option":["Paul McCartney and Wings", "Louis Armstrong", "Duran Duran", "Shirley Bassey"],
},
{
"cat":"James Bond",
"ques":"What singer has a role in 1989's Licence To Kill as a corrupt televangelist named Joe Butcher?",
"answ":"WAYNE NEWTON",
"answ2":"Wayne Newton.",
"option":["Wayne Newton", "David Bowie", "Randy Newman", "Billy Joel"],
},
{
"cat":"James Bond",
"ques":"Dr. No was the first Eon produced film in the James Bond franchise, what was the second?",
"answ":"FROM RUSSIA WITH LOVE",
"answ2":"From Russia with Love.",
"option":["From Russia with Love", "You Only Live Twice", "Thunderball", "Goldfinger"],
},
{
"cat":"James Bond",
"ques":"Charles Gray plays Bond's archenemy Blofeld in which Sean Connery Bond film?",
"answ":"DIAMONDS ARE FOREVER",
"answ2":"Diamonds Are Forever.",
"option":["Diamonds Are Forever", "Live and Let Die", "The Man with the Golden Gun", "On Her Majesty's Secret Service"],
},
{
"cat":"James Bond",
"ques":"In 1977's The Spy Who Loved Me, Bond and Amasova visit Stromberg's base and discover that he has launched a new supertanker called what?",
"answ":"LIPARUS",
"answ2":"Liparus.",
"option":["Liparus", "Atlantis", "Gogol", "Marina"],
},
{
"cat":"James Bond",
"ques":"Which actress played the first Bond girl, Honey Ryder, in the film Dr. No?",
"answ":"URSULA ANDRESS",
"answ2":"Ursula Andress.",
"option":["Ursula Andress", "Daniela Bianchi", "Claudine Auger", "Diana Rigg"],
},
{
"cat":"James Bond",
"ques":"Who famously composed the scores for 11 James Bond films including Goldfinger and Diamonds Are Forever?",
"answ":"JOHN BARRY",
"answ2":"John Barry.",
"option":["John Barry", "Bill Conti", "David Arnold", "George Martin"],
},
{
"cat":"James Bond",
"ques":"'All Time High' by Rita Coolidge was the theme tune to which Bond film?",
"answ":"OCTOPUSSY",
"answ2":"Octopussy.",
"option":["Octopussy", "Thunderball", "You Only Live Twice", "The Living Daylights"],
},
{
"cat":"James Bond",
"ques":"In Spectre, what type of transportation does Bond throw Mr. Hinx off of, killing him?",
"answ":"TRAIN",
"answ2":"Train.",
"option":["Train", "Car", "Plane", "Bus"],
},
{
"cat":"James Bond",
"ques":"In what country does Bond first meet Major Amasova and Jaws in The Spy Who Loved Me?",
"answ":"EGYPT",
"answ2":"Egypt.",
"option":["Egypt", "France", "Brazil", "Germany"],
},
{
"cat":"James Bond",
"ques":"In which Brosnan Bond film does Q give Bond a car that can turn invisible?",
"answ":"DIE ANOTHER DAY",
"answ2":"Die Another Day.",
"option":["Die Another Day", "The World Is Not Enough", "Tomorrow Never Dies", "GoldenEye"],
},
{
"cat":"James Bond",
"ques":"The yacht known as Disco Volante belongs to the main villain of what Bond film?",
"answ":"THUNDERBALL",
"answ2":"Thunderball.",
"option":["Thunderball", "Skyfall", "Goldfinger", "GoldenEye"],
},
{
"cat":"James Bond",
"ques":"What sport do Goldfinger and Bond play together in Goldfinger?",
"answ":"GOLF",
"answ2":"Golf.",
"option":["Golf", "Croquet", "Pool", "Tennis"],
},
{
"cat":"James Bond",
"ques":"James Bond famously drives what brand of car in the film Goldfinger?",
"answ":"ASTON MARTIN",
"answ2":"Aston Martin.",
"option":["Aston Martin", "Ferrari", "Porsche", "Audi"],
},
];
jamesbond = shuffle(jamesbond);
r2Q58 = shuffle(r2Q58);