var oscarmovies = [
{
"cat":"Oscar Movies",
"ques":"What is the first sports movie to win Best Picture?",
"answ":"ROCKY",
"answ2":"Rocky.",
},
{
"cat":"Oscar Movies",
"ques":"Which actor earned a Best Actor nomination for his performance as Jacob Yi in 2020's Minari?",
"answ":"STEVEN YEUN",
"answ2":"Steven Yeun.",
},
{
"cat":"Oscar Movies",
"ques":"Which Oscar-nominated film released in 2010 featured performances by Annette Bening, Julianne Moore and Mark Ruffalo?",
"answ":"THE KIDS ARE ALL RIGHT",
"answ2":"The Kids Are All Right.",
},
{
"cat":"Oscar Movies",
"ques":"Which actress won an Oscar for her performance as divorce lawyer Nora Fanshaw in the film Marriage Story?",
"answ":"LAURA DERN",
"answ2":"Laura Dern.",
},
{
"cat":"Oscar Movies",
"ques":"Which actress received Oscar nominations for her performances in the films Dangerous Liaisons, The Wife and Hillbilly Elegy?",
"answ":"GLENN CLOSE",
"answ2":"Glenn Close.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Actor Oscar for playing an elderly man struggling with dementia in the 2020 film The Father?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
},
{
"cat":"Oscar Movies",
"ques":"Actress Frances McDormand and director Chloe Zhao won Oscars for what 2020 drama?",
"answ":"NOMADLAND",
"answ2":"Nomadland.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Joaquin Phoenix receive his first Oscar nomination?",
"answ":"GLADIATOR",
"answ2":"Gladiator.",
},
{
"cat":"Oscar Movies",
"ques":"Ludwig Göransson won a Best Original Score oscar for what 2018 MCU film?",
"answ":"BLACK PANTHER",
"answ2":"Black Panther.",
},
{
"cat":"Oscar Movies",
"ques":"Emerald Fennell won a Best Original Screenplay Oscar for what 2020 film starring Carey Mulligan and Bo Burnham?",
"answ":"PROMISING YOUNG WOMAN",
"answ2":"Promising Young Woman.",
},
{
"cat":"Oscar Movies",
"ques":"Martin Scorsese lost Best Director for Goodfellas to what famous actor turned director in 1991?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
},
{
"cat":"Oscar Movies",
"ques":"Who was nominated for a Best Supporting Actor Oscar for their role of Abbie Hoffman in The Trial of the Chicago Seven?",
"answ":"SACHA BARON COHEN",
"answ3":"SASHA BARON COHEN",
"answ2":"Sacha Baron Cohen.",
},
{
"cat":"Oscar Movies",
"ques":"For what film did Alicia Vikander win her Best Supporting Actress Oscar?",
"answ":"THE DANISH GIRL",
"answ2":"The Danish Girl.",
},
{
"cat":"Oscar Movies",
"ques":"What non-English language film won the Best Picture Oscar in 2020?",
"answ":"PARASITE",
"answ3":"PARASYTE",
"answ2":"Parasite.",
},
{
"cat":"Oscar Movies",
"ques":"Robert Duvall received a Best Supporting Actor nomination for what 2014 courtroom drama that starred Robert Downey Jr?",
"answ":"THE JUDGE",
"answ2":"The Judge.",
},
{
"cat":"Oscar Movies",
"ques":"Who received a Best Director nomination for the film The Elephant Man?",
"answ":"DAVID LYNCH",
"answ2":"David Lynch.",
},
{
"cat":"Oscar Movies",
"ques":"Leonardo DiCaprio received his first Best Actor nomination for what 2004 film?",
"answ":"THE AVIATOR",
"answ2":"The Aviator.",
},
{
"cat":"Oscar Movies",
"ques":"Anna Paquin and Holly Hunter both won Oscars for what 1993 film?",
"answ":"THE PIANO",
"answ2":"The Piano.",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Original Screenplay Oscar for the classic 1960s film The Producers?",
"answ":"MEL BROOKS",
"answ2":"Mel Brooks.",
},
{
"cat":"Oscar Movies",
"ques":"Which actress has been nominated for three Best Supporting Actress Oscars, the first of which was for Mississippi Burning?",
"answ":"FRANCES MCDORMAND",
"answ2":"Frances McDormand.",
},
{
"cat":"Oscar Movies",
"ques":"Who received Oscar nominations for his performances in the films Bonnie and Clyde, Mississippi Burning and Unforgiven?",
"answ":"GENE HACKMAN",
"answ2":"Gene Hackman.",
},
{
"cat":"Oscar Movies",
"ques":"Which actor received Oscar nominations for his performances in the films Raging Bull, Goodfellas and The Irishman?",
"answ":"ROBERT DE NIRO",
"answ2":"Robert De Niro.",
},
{
"cat":"Oscar Movies",
"ques":"Which actor received Oscar nominations for his performances in the films Cry Freedom and The Hurricane?",
"answ":"DENZEL WASHINGTON",
"answ2":"Denzel Washington.",
},
{
"cat":"Oscar Movies",
"ques":"Robin Williams received his second Best Actor Oscar nomination for what 1989 film?",
"answ":"DEAD POETS SOCIETY",
"answ2":"Dead Poets Society.",
},
{
"cat":"Oscar Movies",
"ques":"What 2004 Marvel movie sequel won the Oscar for Best Visual Effects?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDER MAN II",
"answ2":"Spider-Man 2.",
},
{
"cat":"Oscar Movies",
"ques":"Name this Best Picture winning film: A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse.",
"answ":"ONE FLEW OVER THE CUCKOO'S NEST",
"answ2":"One Flew Over the Cuckoo's Nest.",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Director Oscar for the film Life of Pi?",
"answ":"ANG LEE",
"answ2":"Ang Lee.",
},
{
"cat":"Oscar Movies",
"ques":"Roger Deakins won his first ever Oscar for Best Cinematography for what sci-fi film?",
"answ":"BLADE RUNNER 2049",
"answ2":"Blade Runner 2049.",
},
{
"cat":"Oscar Movies",
"ques":"What is the most recent film to earn Mel Gibson a Best Director nomination?",
"answ":"HACKSAW RIDGE",
"answ2":"Hacksaw Ridge.",
},
{
"cat":"Oscar Movies",
"ques":"Kim Basinger won an Oscar for Best Supporting Actress for her role in what 1997 film?",
"answ":"LA CONFIDENTIAL",
"answ3":"L A CONFIDENTIAL",
"answ2":"L.A. Confidential.",
},
{
"cat":"Oscar Movies",
"ques":"Daniel Day-Lewis won his second Best Actor Oscar for what 2007 film?",
"answ":"THERE WILL BE BLOOD",
"answ2":"There Will Be Blood.",
},
{
"cat":"Oscar Movies",
"ques":"Who won Best Actress for her role as Viola de Lesseps in 1998's Shakespeare in Love?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
},
{
"cat":"Oscar Movies",
"ques":"Daniel Kaluuya received a Best Actor nomination for what 2017 film?",
"answ":"GET OUT",
"answ2":"Get Out.",
},
{
"cat":"Oscar Movies",
"ques":"Jack Nicholson won his first Oscar for what film?",
"answ":"ONE FLEW OVER THE CUCKOO'S NEST",
"answ2":"One Flew Over the Cuckoo's Nest.",
},
{
"cat":"Oscar Movies",
"ques":"What Best Picture winning film was directed by Guillermo Del Toro?",
"answ":"THE SHAPE OF WATER",
"answ3":"SHAPE OF WATER",
"answ2":"The Shape of Water.",
},
{
"cat":"Oscar Movies",
"ques":"Which actor received an Oscar nommination for 2016's Hell or High Water?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"Oscar Movies",
"ques":"What actor won the Best Actor Oscar for his role in Rain Man?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
},
{
"cat":"Oscar Movies",
"ques":"Melissa Leo won a Best Supporting Actress Oscar for what boxing drama?",
"answ":"THE FIGHTER",
"answ2":"The Fighter.",
},
{
"cat":"Oscar Movies",
"ques":"What film starring Tom Hanks and directed by Robert Zemeckis won Best Picture at the 1995 Academy Awards?",
"answ":"FORREST GUMP",
"answ2":"Forrest Gump.",
},
{
"cat":"Oscar Movies",
"ques":"What film for the 2013 Academy Awards beat out such films as Life of Pi, Django Unchained and Silver Linings Playbook for the Best Picture Award?",
"answ":"ARGO",
"answ2":"Argo.",
},
{
"cat":"Oscar Movies",
"ques":"Who won Best Supporting Actor for The Godfather Part II?",
"answ":"ROBERT DE NIRO",
"answ3":"ROBERT DENIRO",
"answ2":"Robert De Niro.",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for portraying musician Ray Charles in Ray?",
"answ":"JAMIE FOXX",
"answ3":"JAMIE FOX",
"answ2":"Jamie Foxx.",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Supporting Actor Oscar in 2016 for his role in Moonlight?",
"answ":"MAHERSHALA ALI",
"answ3":"MAHERSALA ALI",
"answ2":"Mahershala Ali.",
},
{
"cat":"Oscar Movies",
"ques":"What film released in 1999 won Best Picture at the Academy Awards?",
"answ":"AMERICAN BEAUTY",
"answ2":"American Beauty.",
},
{
"cat":"Oscar Movies",
"ques":"Which actress received a Best Lead Actress Oscar nomination for 1988's Dangerous Liaisons?",
"answ":"GLENN CLOSE",
"answ2":"Glenn Close.",
},
{
"cat":"Oscar Movies",
"ques":"What film released in 2000 won Best Picture at the Academy Awards?",
"answ":"GLADIATOR",
"answ2":"Gladiator.",
},
{
"cat":"Oscar Movies",
"ques":"Which film saw Nicole Kidman receive her first Oscar nomination?",
"answ":"MOULIN ROUGE",
"answ2":"Moulin Rouge!.",
},
{
"cat":"Oscar Movies",
"ques":"Which movie earned Clint Eastwood his first Oscar as Best Director?",
"answ":"UNFORGIVEN",
"answ2":"Unforgiven.",
},
{
"cat":"Oscar Movies",
"ques":"What Oscar nominated 2014 film featured Benedict Cumberbatch and had a tagline: 'Behind every code is an enigma'?",
"answ":"THE IMITATION GAME",
"answ3":"IMITATION GAME",
"answ2":"The Imitation Game.",
},
{
"cat":"Oscar Movies",
"ques":"Which one of the following 1988 films was NOT nominated for Best Picture: Rain Man, Bull Durham or Working Girl?",
"answ":"BULL DURHAM",
"answ2":"Bull Durham.",
},
{
"cat":"Oscar Movies",
"ques":"Who was the only person to win an Academy Award for acting in the 2014 film Boyhood?",
"answ":"PATRICIA ARQUETTE",
"answ2":"Patricia Arquette.",
},
{
"cat":"Oscar Movies",
"ques":"Only two sequels have ever won Best Picture at the Academy Awards, The Godfather Part II and what other film?",
"answ":"THE LORD OF THE RINGS RETURN OF THE KING",
"answ3":"LORD OF THE RINGS RETURN OF THE KING",
"answ2":"The Lord of the Rings: Return of the King.",
},
{
"cat":"Oscar Movies",
"ques":"Which film released in 1993 won Best Picture at the Academy Awards?",
"answ":"SCHINDLER'S LIST",
"answ3":"SCHINDLERS LIST",
"answ2":"Schindler's List.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Academy Award for Best Actress for her role as a mother adjusting to her daughter's interracial relationship in 1967's Guess Who's Coming to Dinner?",
"answ":"KATHARINE HEPBURN",
"answ3":"KATHERINE HEPBURN",
"answ2":"Katharine Hepburn.",
},
{
"cat":"Oscar Movies",
"ques":"This actor has won the most Academy Awards for Best Picture in a Motion Picture, with 3.",
"answ":"DANIEL DAY LEWIS",
"answ2":"Daniel Day-Lewis.",
},
{
"cat":"Oscar Movies",
"ques":"Jonah Hill received his first Academy Award nomination for which film?",
"answ":"MONEYBALL",
"answ2":"Moneyball.",
},
{
"cat":"Oscar Movies",
"ques":"What 1985 film tied the record for most nominations without any wins with 11 total?",
"answ":"COLOR PURPLE",
"answ3":"THE COLOR PURPLE",
"answ2":"The Color Purple.",
},
{
"cat":"Oscar Movies",
"ques":"Eddie Murphy earned an Oscar nomination for his performance in which movie musical?",
"answ":"DREAMGIRLS",
"answ2":"Dreamgirls.",
},
{
"cat":"Oscar Movies",
"ques":"Gary Oldman received his first Best Actor nomination for what 2011 film?",
"answ":"TINKER TAILOR SOLDIER SPY",
"answ2":"Tinker Tailor Soldier Spy.",
},
{
"cat":"Oscar Movies",
"ques":"What movie got M. Night Shyamalan his 2 Oscar nominations?",
"answ":"THE SIXTH SENSE",
"answ3":"SIXTH SENSE",
"answ2":"The Sixth Sense.",
},
{
"cat":"Oscar Movies",
"ques":"The song 'You'll Be In My Heart' won Best Original Song for which animated film?",
"answ":"TARZAN",
"answ2":"Tarzan.",
},
{
"cat":"Oscar Movies",
"ques":"Toy Story 3 was the most recent animated film to be nominated for Best Picture at the Academy Awards, what was the first?",
"answ":"BEAUTY AND THE BEAST",
"answ2":"Beauty and the Beast.",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Morgan Freeman receive his first Oscar nomination for Best Actor?",
"answ":"DRIVING MISS DAISY",
"answ2":"Driving Miss Daisy.",
},
{
"cat":"Oscar Movies",
"ques":"Released in 1930, what World War I drama won the Academy Award for Best Picture and Best Director?",
"answ":"ALL QUIET ON THE WESTERN FRONT",
"answ3":"ALL QUIET ON THE WEST FRONT",
"answ2":"All Quiet on the Western Front.",
},
{
"cat":"Oscar Movies",
"ques":"Which of the following 1989 films was NOT nominated for Best Picture: Dead Poets Society, Field of Dreams or Born on the 4th of July?",
"answ":"BORN ON THE FOURTH OF JULY",
"answ3":"BORN ON THE 4TH OF JULY",
"answ2":"Born on the 4th of July.",
},
{
"cat":"Oscar Movies",
"ques":"Which film, released in 2001, won Best Picture at the Academy Awards?",
"answ":"A BEAUTIFUL MIND",
"answ2":"A Beautiful Mind.",
},
{
"cat":"Oscar Movies",
"ques":"What Broadway legend received a Best Actress Oscar nomination for her role in 1969's The Sterile Cuckoo?",
"answ":"LIZA MINNELLI",
"answ3":"LIZA MINELLI",
"answ2":"Liza Minnelli.",
},
{
"cat":"Oscar Movies",
"ques":"For which role did George C. Scott win, but declined to accept the Oscar?",
"answ":"PATTON",
"answ3":"GENERAL PATTON",
"answ2":"Patton.",
},
{
"cat":"Oscar Movies",
"ques":"Sissy Spacek received her only Academy Award win for Best Actress in what film?",
"answ":"COAL MINER'S DAUGHTER",
"answ3":"COAL MINERS DAUGHTER",
"answ2":"Coal Miner's Daughter.",
},
{
"cat":"Oscar Movies",
"ques":"What was the silent movie sensation that won Best Picture at the 2011 Oscars?",
"answ":"THE ARTIST",
"answ2":"The Artist.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Actress Oscar at the 2007 Academy Awards for her lead role in The Queen?",
"answ":"HELEN MIRREN",
"answ2":"Helen Mirren.",
},
{
"cat":"Oscar Movies",
"ques":"What is the first film to win the Academy Award for Best Picture?",
"answ":"WINGS",
"answ2":"Wings.",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Academy Award for playing accused spy Rudolf Abel in Bridge of Spies?",
"answ":"MARK RYLANCE",
"answ3":"MARC RYLANCE",
"answ2":"Mark Rylance.",
},
{
"cat":"Oscar Movies",
"ques":"For what film has Natalie Portman won an Oscar?",
"answ":"BLACK SWAN",
"answ2":"Black Swan.",
},
{
"cat":"Oscar Movies",
"ques":"Holly Hunter won a Best Actress Oscar for which 1993 film?",
"answ":"THE PIANO",
"answ2":"The Piano.",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Academy Award for their role in A Fish Called Wanda?",
"answ":"KEVIN KLINE",
"answ2":"Kevin Kline.",
},
{
"cat":"Oscar Movies",
"ques":"Dustin Hoffman and Meryl Streep played an estranged married couple in what Oscar winning film?",
"answ":"KRAMER VS KRAMER",
"answ3":"KRAMER VERSUS KRAMER",
"answ2":"Kramer vs Kramer.",
},
{
"cat":"Oscar Movies",
"ques":"What 1970's sports film won Best Director for John G. Avildsen?",
"answ":"ROCKY",
"answ2":"Rocky.",
},
{
"cat":"Oscar Movies",
"ques":"Peter Ustinov won a Best Supporting Actor Oscar for what 1960 classic?",
"answ":"SPARTACUS",
"answ2":"Spartacus.",
},
{
"cat":"Oscar Movies",
"ques":"Jack Nicholson, Helen Hunt and Greg Kinnear received Oscar nominations for what 90s film?",
"answ":"AS GOOD AS IT GETS",
"answ2":"As Good as It Gets.",
},
{
"cat":"Oscar Movies",
"ques":"What 2002 movie garnered Oscar nominations for writer Charlie Kaufman and his fictional brother Donald?",
"answ":"ADAPTATION",
"answ2":"Adaptation.",
},
{
"cat":"Oscar Movies",
"ques":"What film released in 2015 won Best Picture?",
"answ":"SPOTLIGHT",
"answ2":"Spotlight",
},
{
"cat":"Oscar Movies",
"ques":"Name the film that earned both stars Denzel Washington and Viola Davis Oscar nominations",
"answ":"FENCES",
"answ2":"Fences.",
},
{
"cat":"Oscar Movies",
"ques":"Sean Penn earned an Oscar nomination for playing a mentally challenged father in what 2001 film?",
"answ":"I AM SAM",
"answ2":"I Am Sam.",
},
{
"cat":"Oscar Movies",
"ques":"What Danny Boyle movie released in 2008 took home the Best Picture Oscar?",
"answ":"SLUMDOG MILLIONAIRE",
"answ2":"Slumdog Millionaire.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Oscar for Best Actor for On The Waterfront?",
"answ":"MARLON BRANDO",
"answ2":"Marlon Brando.",
},
{
"cat":"Oscar Movies",
"ques":"How many Oscars did Titanic win?",
"answ":"11",
"answ3":"ELEVEN",
"answ2":"11.",
},
{
"cat":"Oscar Movies",
"ques":"Name the film that saw Julianne Moore win her first Best Actress Oscar.",
"answ":"STILL ALICE",
"answ2":"Still Alice.",
},
{
"cat":"Oscar Movies",
"ques":"Who starred as Karen von Blixen in the Best Picture winner Out of Africa?",
"answ":"MERYL STREEP",
"answ2":"Meryl Streep.",
},
{
"cat":"Oscar Movies",
"ques":"Kate Winslet won a Best Actress Oscar for what 2009 film?",
"answ":"THE READER",
"answ2":"The Reader.",
},
{
"cat":"Oscar Movies",
"ques":"Tilda Swinton won a Best Supporting Actress Oscar for her role in what 2008 film?",
"answ":"MICHAEL CLAYTON",
"answ2":"Michael Clayton.",
},
{
"cat":"Oscar Movies",
"ques":"Billy Bob Thornton won his first Academy Award for which 1996 film?",
"answ":"SLING BLADE",
"answ3":"SLINGBLADE",
"answ2":"Sling Blade.",
},
{
"cat":"Oscar Movies",
"ques":"Dan Aykroyd earned a Best Supporting Actor nomination for his role as Boolie Werthan in what 1989 film?",
"answ":"DRIVING MISS DAISY",
"answ2":"Driving Miss Daisy.",
},
{
"cat":"Oscar Movies",
"ques":"Oliver Stone won his second Best Director statue after Platoon for which film?",
"answ":"BORN ON THE FOURTH OF JULY",
"answ3":"BORN ON THE 4TH OF JULY",
"answ2":"Born on the Fourth of July.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Jennifer Connelly win her Academy Award?",
"answ":"A BEAUTIFUL MIND",
"answ2":"A Beautiful Mind.",
},
{
"cat":"Oscar Movies",
"ques":"Who won Best Actress for 2006's The Queen?",
"answ":"HELEN MIRREN",
"answ2":"Helen Mirren.",
},
{
"cat":"Oscar Movies",
"ques":"For which movie did Louis Gosset Jr. win his Academy Award for Best Supporting Actor?",
"answ":"AN OFFICER AND A GENTLEMAN",
"answ3":"OFFICER AND A GENTLEMAN",
"answ2":"An Officer and a Gentleman.",
},
{
"cat":"Oscar Movies",
"ques":"What was the first film that earned Michael Douglas a nomination for acting?",
"answ":"WALL STREET",
"answ2":"Wall Street.",
},
{
"cat":"Oscar Movies",
"ques":"Martin Landau won an Oscar for playing Bela Lugosi in what film?",
"answ":"ED WOOD",
"answ2":"Ed Wood.",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for the role of Javier Rodriguez in the film Traffic?",
"answ":"BENICIO DEL TORO",
"answ2":"Benicio Del Toro.",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for the role of Velma Kelly in Chicago?",
"answ":"CATHERINE ZETA JONES",
"answ3":"CATHARINE ZETA JONES",
"answ2":"Catherine Zeta-Jones.",
},
{
"cat":"Oscar Movies",
"ques":"Who was nominated for Best Supporting Actress for her work in 1989's Steel Magnolias?",
"answ":"JULIA ROBERTS",
"answ2":"Julia Roberts.",
},
{
"cat":"Oscar Movies",
"ques":"Sean Connery has won one Oscar for which film?",
"answ":"THE UNTOUCHABLES",
"answ2":"The Untouchables.",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Kevin Spacey win his first Oscar?",
"answ":"THE USUAL SUSPECTS",
"answ3":"USUAL SUSPECTS",
"answ2":"The Usual Suspects.",
},
{
"cat":"Oscar Movies",
"ques":"Jonathan Demme won Best Director for what 1991 film?",
"answ":"THE SILENCE OF THE LAMBS",
"answ3":"SILENCE OF THE LAMBS",
"answ2":"The Silence of the Lambs.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the 1972 Best Actress Oscar for her performance in Cabaret?",
"answ":"LIZA MINNELLI",
"answ3":"LIZA MINELLI",
"answ2":"Liza Minnelli.",
},
{
"cat":"Oscar Movies",
"ques":"What 1979 Best Picture winner also saw Oscar wins for stars Dustin Hoffman and Meryl Streep?",
"answ":"KRAMER VS KRAMER",
"answ3":"KRAMER VERSUS KRAMER",
"answ2":"Kramer vs. Kramer.",
},
{
"cat":"Oscar Movies",
"ques":"How many acting nominations did Birdman receive?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Julia Roberts win Best Actress?",
"answ":"ERIN BROCKOVICH",
"answ2":"Erin Brockovich.",
},
{
"cat":"Oscar Movies",
"ques":"For what film did James Caan receive his only Oscar nomination?",
"answ":"THE GODFATHER",
"answ3":"GODFATHER",
"answ2":"The Godfather.",
},
{
"cat":"Oscar Movies",
"ques":"What 2014 film won the Academy Award for Best Animated Feature?",
"answ":"BIG HERO 6",
"answ3":"BIG HERO SIX",
"answ2":"Big Hero 6.",
},
{
"cat":"Oscar Movies",
"ques":"Who was nominated for Best Supporting Actor for his role in The Departed?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Actress Oscar for her role in As Good as It Gets?",
"answ":"HELEN HUNT",
"answ2":"Helen Hunt.",
},
{
"cat":"Oscar Movies",
"ques":"What movie released in 1995 received the Oscar for Best Picture?",
"answ":"BRAVEHEART",
"answ2":"Braveheart.",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Al Pacino get a Best Supporting Actor nomination the same year Joe Pesci won for Goodfellas?",
"answ":"DICK TRACY",
"answ2":"Dick Tracy.",
},
{
"cat":"Oscar Movies",
"ques":"Who won Best Supporting Actress for her role in Chicago?",
"answ":"CATHERINE ZETA JONES",
"answ3":"CATHARINE ZETA JONES",
"answ2":"Catherine Zeta-Jones.",
},
{
"cat":"Oscar Movies",
"ques":"For which 1999 film did Hilary Swank win her first Best Actress Oscar?",
"answ":"BOYS DON'T CRY",
"answ2":"Boys Don't Cry.",
},
{
"cat":"Oscar Movies",
"ques":"Paul Haggis directed which movie that won Best Picture?",
"answ":"CRASH",
"answ2":"Crash.",
},
{
"cat":"Oscar Movies",
"ques":"Whoopie Goldberg won Best Supporting Actress for what film?",
"answ":"GHOST",
"answ2":"Ghost.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did George C. Scott win his Best Actor Oscar?",
"answ":"PATTON",
"answ2":"Patton.",
},
{
"cat":"Oscar Movies",
"ques":"Jamie Foxx won his first Academy Award for what film?",
"answ":"RAY",
"answ2":"Ray.",
},
{
"cat":"Oscar Movies",
"ques":"Angelina Jolie got a Best Actress nomination for what 2008 film?",
"answ":"CHANGELING",
"answ2":"Changeling.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Robert Zemeckis win his Best Director Oscar?",
"answ":"FORREST GUMP",
"answ2":"Forrest Gump.",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Jack Palance win a Best Supporting Actor Oscar?",
"answ":"CITY SLICKERS",
"answ2":"City Slickers.",
},
{
"cat":"Oscar Movies",
"ques":"Who is the first woman to win an Oscar for Best Director?",
"answ":"KATHRYN BIGELOW",
"answ2":"Kathryn Bigelow.",
},
{
"cat":"Oscar Movies",
"ques":"Jeff Bridges finally won a Best Actor Oscar for which film?",
"answ":"CRAZY HEART",
"answ2":"Crazy Heart.",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Actress Oscar for her role in Dead Man Walking?",
"answ":"SUSAN SARANDON",
"answ2":"Susan Sarandon.",
},
{
"cat":"Oscar Movies",
"ques":"Paul Thomas Anderson has never won an Oscar though he was nominated once for which film?",
"answ":"THERE WILL BE BLOOD",
"answ2":"There Will Be Blood.",
},
{
"cat":"Oscar Movies",
"ques":"Renée Zellweger won her first Academy Award for her performance in which 2003 film?",
"answ":"COLD MOUNTAIN",
"answ2":"Cold Mountain.",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Supporting Actress Oscar for her role as Linda Ash in Mighty Aphrodite?",
"answ":"MIRA SORVINO",
"answ2":"Mira Sorvino.",
},
{
"cat":"Oscar Movies",
"ques":"Javier Bardem won the Academy Award for Best Supporting Actor in 2007 for his role in which film?",
"answ":"NO COUNTRY FOR OLD MEN",
"answ2":"No Country for Old Men.",
},
{
"cat":"Oscar Movies",
"ques":"Which film won Tom Hooper the Academy Award for Best Director?",
"answ":"THE KING'S SPEECH",
"answ3":"THE KINGS SPEECH",
"answ2":"The King's Speech.",
},
{
"cat":"Oscar Movies",
"ques":"Name the Oscar winning actress who starred in Fargo and Wonder Boys.",
"answ":"FRANCES MCDORMAND",
"answ3":"FRANCIS MCDORMAND",
"answ2":"Frances McDormand.",
},
{
"cat":"Oscar Movies",
"ques":"What Christopher Nolan film released in 2010 was nominated for Best Picture?",
"answ":"INCEPTION",
"answ2":"Inception.",
},
{
"cat":"Oscar Movies",
"ques":"Which actress received an Oscar nomination for playing Bonnie in 1967's Bonnie and Clyde?",
"answ":"FAYE DUNAWAY",
"answ3":"FAY DUNAWAY",
"answ2":"Faye Dunaway.",
},
{
"cat":"Oscar Movies",
"ques":"What musical released in 2002 received the Oscar for Best Picture?",
"answ":"CHICAGO",
"answ2":"Chicago.",
},
{
"cat":"Oscar Movies",
"ques":"In 1991 Beauty & the Beast became the first animated feature to be nominated for Best Picture, what film did it lose to?",
"answ":"THE SILENCE OF THE LAMBS",
"answ3":"SILENCE OF THE LAMBS",
"answ2":"The Silence of the Lambs.",
},
{
"cat":"Oscar Movies",
"ques":"How many times has Liam Neeson been nominated for an Oscar?",
"answ":"1",
"answ3":"ONE",
"answ2":"1.",
},
{
"cat":"Oscar Movies",
"ques":"Making her feature film debut Julie Andrews won an Oscar for what film?",
"answ":"MARY POPPINS",
"answ2":"Mary Poppins.",
},
{
"cat":"Oscar Movies",
"ques":"Helen Hunt won the 1998 Best Actress Oscar for her performance in which film?",
"answ":"AS GOOD AS IT GETS",
"answ2":"As Good As It Gets.",
},
{
"cat":"Oscar Movies",
"ques":"What was the first color film to win Best Picture at the Academy Awards?",
"answ":"GONE WITH THE WIND",
"answ2":"Gone With The Wind.",
},
{
"cat":"Oscar Movies",
"ques":"What war film released in 1970 received the Oscar for Best Picture?",
"answ":"PATTON",
"answ2":"Patton.",
},
{
"cat":"Oscar Movies",
"ques":"Which actor has the record for most Oscar nominations without a single win?",
"answ":"PETER O'TOOLE",
"answ2":"Peter O'Toole.",
},
{
"cat":"Oscar Movies",
"ques":"Who are the only brothers to be nominated for acting Oscars? Write down their last name only.",
"answ":"PHOENIX",
"answ2":"River and Joaquin Phoenix.",
},
{
"cat":"Oscar Movies",
"ques":"Daniel Day-Lewis, Martin Scorsese and U2 all received Oscar nominations for what film?",
"answ":"GANGS OF NEW YORK",
"answ2":"Gangs of New York",
},
];
var r2Q6 = [
{
"cat":"Oscar Movies",
"ques":"John Wayne was nominated three times for an Academy Award but only won once. What film did he win for?",
"answ":"TRUE GRIT",
"answ2":"True Grit.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sands of Iwo Jima</button><button id=incop2 class=buttons003 onclick=qinc()>Fort Apache</button><button id=corop class=buttons003 onclick=qcor()>True Grit</button><button id=incop4 class=buttons003 onclick=qinc()>The Alamo</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What director has won the most Oscars for directing?",
"answ":"JOHN FORD",
"answ2":"John Ford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Steven Spielberg</button><button id=corop class=buttons003 onclick=qcor()>John Ford</button><button id=incop3 class=buttons003 onclick=qinc()>Frank Capra</button><button id=incop4 class=buttons003 onclick=qinc()>Clint Eastwood</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What composer has the most Oscar wins for Best Original Score?",
"answ":"ALFRED NEWMAN",
"answ2":"Alfred Newman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Horner</button><button id=incop2 class=buttons003 onclick=qinc()>John Williams</button><button id=corop class=buttons003 onclick=qcor()>Alfred Newman</button><button id=incop4 class=buttons003 onclick=qinc()>Howard Shore</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won the 1953 Best Actor Oscar for his portrayal of Marshall Will Kane in the film High Noon?",
"answ":"GARY COOPER",
"answ2":"Gary Cooper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kirk Douglas</button><button id=incop2 class=buttons003 onclick=qinc()>Marlon Brando</button><button id=corop class=buttons003 onclick=qcor()>Gary Cooper</button><button id=incop4 class=buttons003 onclick=qinc()>José Ferrer</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Academy Awards did 1962's Lawrence of Arabia win?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=incop3 class=buttons003 onclick=qinc()>5</button><button id=corop class=buttons003 onclick=qcor()>7</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Academy Award for Best Supporting Actress for playing Cher's mother in 1987's Moonstruck?",
"answ":"OLYMPIA DUKAKIS",
"answ2":"Olympia Dukakis.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Olympia Dukakis</button><button id=incop2 class=buttons003 onclick=qinc()>Audrey Hepburn</button><button id=incop3 class=buttons003 onclick=qinc()>Margot Kidder</button><button id=incop4 class=buttons003 onclick=qinc()>Anne Archer</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Jennifer Hudson won an Oscar for her performance in which 2006 musical?",
"answ":"DREAMGIRLS",
"answ3":"DREAM GIRLS",
"answ2":"Dreamgirls.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Moulin Rouge!</button><button id=incop2 class=buttons003 onclick=qinc()>Chicago</button><button id=incop3 class=buttons003 onclick=qinc()>Dreamgirls</button><button id=corop class=buttons003 onclick=qcor()>Walk the Line</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"At 82 years old at the time, who is the oldest person to win an Academy Award for acting?",
"answ":"CHRISTOPHER PLUMMER",
"answ2":"Christopher Plummer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Tandy</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Duvall</button><button id=corop class=buttons003 onclick=qcor()>Christopher Plummer</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Fonda</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Which film won Best Picture of 2013?",
"answ":"12 YEARS A SLAVE",
"answ3":"TWELVE YEARS A SLAVE",
"answ2":"12 Years a Slave.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gravity</button><button id=incop2 class=buttons003 onclick=qinc()>Blue Jasmine</button><button id=corop class=buttons003 onclick=qcor()>12 Years a Slave</button><button id=incop4 class=buttons003 onclick=qinc()>Dallas Buyers Club</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What popular 90s comedy television actor portrayed Andrew Neiman's father in 2014's Whiplash?",
"answ":"PAUL REISER",
"answ2":"Paul Reiser.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ed O'Neill</button><button id=incop2 class=buttons003 onclick=qinc()>Tim Allen</button><button id=corop class=buttons003 onclick=qcor()>Paul Reiser</button><button id=incop4 class=buttons003 onclick=qinc()>Kelsey Grammer</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Humphrey Bogart win his only Best Actor Oscar?",
"answ":"THE AFRICAN QUEEN",
"answ2":"The African Queen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Casablanca</button><button id=corop class=buttons003 onclick=qcor()>The African Queen</button><button id=incop3 class=buttons003 onclick=qinc()>The Maltese Falcon</button><button id=incop4 class=buttons003 onclick=qinc()>The Treasure of the Sierra Madre</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who played the role of 'The Unsinkable' Molly Brown in Titanic?",
"answ":"KATHY BATES",
"answ2":"Kathy Bates.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kate Winslet</button><button id=corop class=buttons003 onclick=qcor()>Kathy Bates</button><button id=incop3 class=buttons003 onclick=qinc()>Frances McDormand</button><button id=incop4 class=buttons003 onclick=qinc()>Maggie Smith</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which movie did Rachel Weisz win an acting Oscar?",
"answ":"THE CONSTANT GARDENER",
"answ3":"CONSTANT GARDENER",
"answ2":"The Constant Gardener.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Favourite</button><button id=corop class=buttons003 onclick=qcor()>The Constant Gardener</button><button id=incop3 class=buttons003 onclick=qinc()>The Whistleblower</button><button id=incop4 class=buttons003 onclick=qinc()>Youth</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who played hitman Anton Chigurh in No Country for Old Men?",
"answ":"JAVIER BARDEM",
"answ2":"Javier Bardem.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tommy Lee Jones</button><button id=corop class=buttons003 onclick=qcor()>Javier Bardem</button><button id=incop3 class=buttons003 onclick=qinc()>Woody Harrelson</button><button id=incop4 class=buttons003 onclick=qinc()>Antonio Banderas</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what film did Ryan Gosling receive his first Oscar nomination?",
"answ":"HALF NELSON",
"answ2":"Half Nelson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lars and the Real Girl</button><button id=corop class=buttons003 onclick=qcor()>Half Nelson</button><button id=incop3 class=buttons003 onclick=qinc()>Blue Valentine</button><button id=incop4 class=buttons003 onclick=qinc()>The Big Short</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who played Kevin Spacey's wife Carolyn in American Beauty?",
"answ":"ANNETTE BENING",
"answ3":"ANNETTE BENNING",
"answ2":"Annette Bening.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Allison Janney</button><button id=corop class=buttons003 onclick=qcor()>Annette Bening</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=incop4 class=buttons003 onclick=qinc()>Frances McDormand</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What movie released in 1998 received the Oscar for Best Picture?",
"answ":"SHAKESPEARE IN LOVE",
"answ2":"Shakespeare in Love.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Saving Private Ryan</button><button id=corop class=buttons003 onclick=qcor()>Shakespeare in Love</button><button id=incop3 class=buttons003 onclick=qinc()>The Thin Red Line</button><button id=incop4 class=buttons003 onclick=qinc()>Life is Beautiful</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who was the first performer to win two consecutive Academy Awards?",
"answ":"LUISE RAINER",
"answ3":"LOUISE RAINER",
"answ2":"Luise Rainer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Katherine Hepburn</button><button id=incop2 class=buttons003 onclick=qinc()>Tom Hanks</button><button id=incop3 class=buttons003 onclick=qinc()>Jason Robards</button><button id=corop class=buttons003 onclick=qcor()>Luise Rainer</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What movie did Alec Guinness win his Best Actor Oscar for?",
"answ":"THE BRIDGE ON THE RIVER KWAI",
"answ3":"BRIDGE ON THE RIVER KWAI",
"answ2":"The Bridge on the River Kwai.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Lavender Hill Mob</button><button id=incop2 class=buttons003 onclick=qinc()>The Ladykillers</button><button id=incop3 class=buttons003 onclick=qinc()>The Swan</button><button id=corop class=buttons003 onclick=qcor()>The Bridge on the River Kwai</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What famous actor refused to accept his Best Actor Oscar in 1972?",
"answ":"MARLON BRANDO",
"answ2":"Marlon Brando.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joe Pesci</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Caine</button><button id=incop3 class=buttons003 onclick=qinc()>Peter O'Toole</button><button id=corop class=buttons003 onclick=qcor()>Marlon Brando</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Three films hold the record for most Oscar nominations received. How many nominations did they get?",
"answ":"14",
"answ3":"FOURTEEN",
"answ2":"14.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>11</button><button id=incop2 class=buttons003 onclick=qinc()>13</button><button id=corop class=buttons003 onclick=qcor()>14</button><button id=incop4 class=buttons003 onclick=qinc()>15</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who was the first actor/actress to win 4 Academy Awards?",
"answ":"KATHARINE HEPBURN",
"answ3":"KATHERINE HEPBURN",
"answ2":"Katharine Hepburn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Daniel Day-Lewis</button><button id=incop2 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=corop class=buttons003 onclick=qcor()>Katharine Hepburn</button><button id=incop4 class=buttons003 onclick=qinc()>Shelley Winters</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Best Director Oscars has Paul Thomas Anderson won?",
"answ":"0",
"answ3":"NONE",
"answ2":"0.",
"option":"<button id=corop class=buttons003 onclick=qcor()>0</button><button id=incop2 class=buttons003 onclick=qinc()>1</button><button id=incop3 class=buttons003 onclick=qinc()>2</button><button id=incop4 class=buttons003 onclick=qinc()>3</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Supporting Actor Oscar for his performance in 1989's Glory?",
"answ":"DENZEL WASHINGTON",
"answ2":"Denzel Washington.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Denzel Washington</button><button id=incop2 class=buttons003 onclick=qinc()>Morgan Freeman</button><button id=incop3 class=buttons003 onclick=qinc()>Matthew Broderick</button><button id=incop4 class=buttons003 onclick=qinc()>Samuel L. Jackson</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Two Christopher Nolan films have received a Best Picture nomination. Inception and what other film?",
"answ":"DUNKIRK",
"answ2":"Dunkirk.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dunkirk</button><button id=incop2 class=buttons003 onclick=qinc()>Interstellar</button><button id=incop3 class=buttons003 onclick=qinc()>The Dark Knight Rises</button><button id=incop4 class=buttons003 onclick=qinc()>The Prestige</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for portraying Oscar winner Katharine Hepburn?",
"answ":"CATE BLANCHETT",
"answ3":"CATE BLANCHET",
"answ2":"Cate Blanchett.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Cate Blanchett</button><button id=incop2 class=buttons003 onclick=qinc()>Kate Winslet</button><button id=incop3 class=buttons003 onclick=qinc()>Kim Basinger</button><button id=incop4 class=buttons003 onclick=qinc()>Jessica Lange</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who is the youngest actor/actress to take home an Oscar?",
"answ":"TATUM O'NEAL",
"answ2":"Tatum O'Neal.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tatum O'Neal</button><button id=incop2 class=buttons003 onclick=qinc()>Anna Paquin</button><button id=incop3 class=buttons003 onclick=qinc()>Adrien Brody</button><button id=incop4 class=buttons003 onclick=qinc()>Mary Badham</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which movie did Marlon Brando win his first Oscar?",
"answ":"ON THE WATERFRONT",
"answ2":"On the Waterfront.",
"option":"<button id=corop class=buttons003 onclick=qcor()>On the Waterfront</button><button id=incop2 class=buttons003 onclick=qinc()>A Streetcar Named Desire</button><button id=incop3 class=buttons003 onclick=qinc()>The Godfather</button><button id=incop4 class=buttons003 onclick=qinc()>Julius Caesar</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first film for which Matthew McConaughey received an Oscar nomination?",
"answ":"DALLAS BUYERS CLUB",
"answ2":"Dallas Buyers Club.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dallas Buyers Club</button><button id=incop2 class=buttons003 onclick=qinc()>Mud</button><button id=incop3 class=buttons003 onclick=qinc()>Killer Joe</button><button id=incop4 class=buttons003 onclick=qinc()>A Time to Kill</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what film did Gwyneth Paltrow win her Best Actress Oscar?",
"answ":"SHAKESPEARE IN LOVE",
"answ2":"Shakespeare in Love.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Shakespeare in Love</button><button id=incop2 class=buttons003 onclick=qinc()>The Talented Mr. Ripley</button><button id=incop3 class=buttons003 onclick=qinc()>Se7en</button><button id=incop4 class=buttons003 onclick=qinc()>	The Royal Tenenbaums</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Name the film that upset Avatar to win Best Picture at the 2010 Oscar ceremony.",
"answ":"THE HURT LOCKER",
"answ3":"HURT LOCKER",
"answ2":"The Hurt Locker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Hurt Locker</button><button id=incop2 class=buttons003 onclick=qinc()>The Blind Side</button><button id=incop3 class=buttons003 onclick=qinc()>Slumdog Millionaire</button><button id=incop4 class=buttons003 onclick=qinc()>A Serious Man</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Actress Oscar for her role in the 1984 film Places in the Heart?",
"answ":"SALLY FIELD",
"answ3":"SALLIE FIELD",
"answ2":"Sally Field.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sally Field</button><button id=incop2 class=buttons003 onclick=qinc()>Jessica Lange</button><button id=incop3 class=buttons003 onclick=qinc()>Sissy Spacek</button><button id=incop4 class=buttons003 onclick=qinc()>Geraldine Page</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What is the name of the killer that Hannibal Lecter assists the FBI in identifying in Silence of the Lambs?",
"answ":"BUFFALO BILL",
"answ2":"Buffalo Bill.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Buffalo Bill</button><button id=incop2 class=buttons003 onclick=qinc()>Jack Crawford</button><button id=incop3 class=buttons003 onclick=qinc()>Sissy Spacek</button><button id=incop4 class=buttons003 onclick=qinc()>Curly Bill</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Mel Brooks won his only Academy Award for Original Screenplay for which film?",
"answ":"THE PRODUCERS",
"answ2":"The Producers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>History of the World Part 1</button><button id=incop2 class=buttons003 onclick=qinc()>Blazing Saddles</button><button id=incop3 class=buttons003 onclick=qinc()>Young Frankenstein</button><button id=corop class=buttons003 onclick=qcor()>The Producers</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Name the actor who won Best Actor for 1976's Network.",
"answ":"PETER FINCH",
"answ2":"Peter Finch.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Peter Finch</button><button id=incop2 class=buttons003 onclick=qinc()>Lance Henriksen</button><button id=incop3 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><button id=incop4 class=buttons003 onclick=qinc()>Woody Allen</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What musical based on a Charles Dickens novel won the Academy Award for Best Picture in 1969?",
"answ":"OLIVER",
"answ2":"Oliver.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nicholas Nickleby</button><button id=incop2 class=buttons003 onclick=qinc()>A Christmas Carol</button><button id=incop3 class=buttons003 onclick=qinc()>Great Expectations</button><button id=corop class=buttons003 onclick=qcor()>Oliver</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What lady won her first Best Actress Oscar for her role in 1992's Howard's End?",
"answ":"EMMA THOMPSON",
"answ3":"EMMA THOMSON",
"answ2":"Emma Thompson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Holly Hunter</button><button id=incop2 class=buttons003 onclick=qinc()>Mary McDonnell</button><button id=incop3 class=buttons003 onclick=qinc()>Susan Sarandon</button><button id=corop class=buttons003 onclick=qcor()>Emma Thompson</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who directed the 2003 Best Picture winner Chicago?",
"answ":"ROB MARSHALL",
"answ2":"Rob Marshall.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hooper</button><button id=incop2 class=buttons003 onclick=qinc()>Bill Condon</button><button id=incop3 class=buttons003 onclick=qinc()>Adam Shankman</button><button id=corop class=buttons003 onclick=qcor()>Rob Marshall</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Martin Scorsese lost Best Director for Raging Bull to what famous actor turned director in 1980?",
"answ":"ROBERT REDFORD",
"answ2":"Robert Redford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Clint Eastwood</button><button id=incop2 class=buttons003 onclick=qinc()>Warren Beatty</button><button id=incop3 class=buttons003 onclick=qinc()>Ron Howard</button><button id=corop class=buttons003 onclick=qcor()>Robert Redford</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Spakespeare in Love won Best Picture over what war film in 1998?",
"answ":"SAVING PRIVATE RYAN",
"answ2":"Saving Private Ryan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Black Hawk Down</button><button id=incop2 class=buttons003 onclick=qinc()>Zero Dark Thirty</button><button id=incop3 class=buttons003 onclick=qinc()>Windtalkers</button><button id=corop class=buttons003 onclick=qcor()>Saving Private Ryan</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Million Dollar Baby was directed by whom?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>David O. Russell</button><button id=incop2 class=buttons003 onclick=qinc()>Bennett Miller</button><button id=incop3 class=buttons003 onclick=qinc()>Leon Gast</button><button id=corop class=buttons003 onclick=qcor()>Clint Eastwood</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first film to receive an Academy Award nomination in each of the 4 performance categories?",
"answ":"MY MAN GODFREY",
"answ2":"My Man Godfrey.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A Streetcar Named Desire</button><button id=incop2 class=buttons003 onclick=qinc()>The Color Purple</button><button id=corop class=buttons003 onclick=qcor()>My Man Godfrey</button><button id=incop4 class=buttons003 onclick=qinc()>The Turning Point</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Titanic and La La Land are tied with what other film for the most Oscar nominations ever?",
"answ":"ALL ABOUT EVE",
"answ2":"All About Eve.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gone with the Wind</button><button id=incop2 class=buttons003 onclick=qinc()>Casablanca</button><button id=corop class=buttons003 onclick=qcor()>All About Eve</button><button id=incop4 class=buttons003 onclick=qinc()>Ben-Hur</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Michael Douglas won his first Oscar for producing what film?",
"answ":"ONE FLEW OVER THE CUCKOO'S NEST",
"answ2":"One Flew Over the Cuckoo's Nest.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wall Street</button><button id=incop2 class=buttons003 onclick=qinc()>Fatal Attraction</button><button id=corop class=buttons003 onclick=qcor()>One Flew Over the Cuckoo's Nest</button><button id=incop4 class=buttons003 onclick=qinc()>Behind the Candelabra</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Sydney Pollack won the Best Director Oscar for which film?",
"answ":"OUT OF AFRICA",
"answ2":"Out of Africa.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Reader</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Clayton</button><button id=corop class=buttons003 onclick=qcor()>Out of Africa</button><button id=incop4 class=buttons003 onclick=qinc()>Tootsie</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which film did singer/actress Cher win her only Academy Award?",
"answ":"MOONSTRUCK",
"answ2":"Moonstruck.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Suspect</button><button id=incop2 class=buttons003 onclick=qinc()>Silkwood</button><button id=corop class=buttons003 onclick=qcor()>Moonstruck</button><button id=incop4 class=buttons003 onclick=qinc()>The Player</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"In which film does Barbra Streisand sing the Academy Award nominated song 'Papa Can You Hear Me'?",
"answ":"YENTL",
"answ2":"Yentl.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Funny Lady</button><button id=incop2 class=buttons003 onclick=qinc()>A Star Is Born</button><button id=corop class=buttons003 onclick=qcor()>Yentl</button><button id=incop4 class=buttons003 onclick=qinc()>Nuts</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who played Hollywood make-up artist John Chambers in the Oscar winning film Argo?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bryan Cranston</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Arkin</button><button id=corop class=buttons003 onclick=qcor()>John Goodman</button><button id=incop4 class=buttons003 onclick=qinc()>Ben Affleck</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what film did Jack Nicholson receive his first Oscar nomination?",
"answ":"EASY RIDER",
"answ2":"Easy Rider.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Easy Rider</button><button id=incop2 class=buttons003 onclick=qinc()>Five Easy Pieces</button><button id=incop3 class=buttons003 onclick=qinc()>One Flew Over the Cuckoo's Nest</button><button id=incop4 class=buttons003 onclick=qinc()>The Last Detail</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Actress Ingrid Bergman won her second Best Actress Oscar for which film?",
"answ":"ANASTASIA",
"answ2":"Anastasia.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Anastasia</button><button id=incop2 class=buttons003 onclick=qinc()>Gaslight</button><button id=incop3 class=buttons003 onclick=qinc()>Joan of Arc</button><button id=incop4 class=buttons003 onclick=qinc()>Autumn Sonata</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who was the only performer to be nominated for an Oscar in 1970's Little Big Man?",
"answ":"CHIEF DAN GEORGE",
"answ3":"DAN GEORGE",
"answ2":"Chief Dan George.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Martin Balsam</button><button id=corop class=buttons003 onclick=qcor()>Chief Dan George</button><button id=incop3 class=buttons003 onclick=qinc()>Faye Dunaway</button><button id=incop4 class=buttons003 onclick=qinc()>Dustin Hoffman</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for portraying an Oscar winning actress in The Aviator?",
"answ":"CATE BLANCHETT",
"answ3":"CATE BLANCHET",
"answ2":"Cate Blanchett.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kate Beckinsale</button><button id=corop class=buttons003 onclick=qcor()>Cate Blanchett</button><button id=incop3 class=buttons003 onclick=qinc()>Gwen Stefani</button><button id=incop4 class=buttons003 onclick=qinc()>Meryl Streep</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first Disney movie to win an Oscar for Best Original Song?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pinocchio</button><button id=incop2 class=buttons003 onclick=qinc()>Dumbo</button><button id=incop3 class=buttons003 onclick=qinc()>Bambi</button><button id=incop4 class=buttons003 onclick=qinc()>Snow White</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Other than Chaplin, what is the only other film for which Robert Downey Jr. has been nominated for an Oscar?",
"answ":"TROPIC THUNDER",
"answ2":"Tropic Thunder.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tropic Thunder</button><button id=incop2 class=buttons003 onclick=qinc()>Sherlock Holmes</button><button id=incop3 class=buttons003 onclick=qinc()>Kiss Kiss Bang Bang</button><button id=incop4 class=buttons003 onclick=qinc()>Zodiac</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which film did James Stewart receive his only Best Actor Oscar win?",
"answ":"THE PHILADELPHIA STORY",
"answ3":"PHILADELPHIA STORY",
"answ2":"The Philadelphia Story.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Philadelphia Story</button><button id=incop2 class=buttons003 onclick=qinc()>Harvey</button><button id=incop3 class=buttons003 onclick=qinc()>It's a Wonderful Life</button><button id=incop4 class=buttons003 onclick=qinc()>Anatomy of a Murder</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What actress won an Oscar for her role as Mona Lisa in My Cousin Vinny?",
"answ":"MARISA TOMEI",
"answ2":"Marisa Tomei.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Marisa Tomei</button><button id=incop2 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><button id=incop3 class=buttons003 onclick=qinc()>Jennifer Connelly</button><button id=incop4 class=buttons003 onclick=qinc()>Jessica Alba</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which Woody Allen movie did Dianne Wiest win a Best Supporting Actress Oscar?",
"answ":"BULLETS OVER BROADWAY",
"answ2":"Bullets over Broadway.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Bullets over Broadway</button><button id=incop2 class=buttons003 onclick=qinc()>Hannah and Her Sisters</button><button id=incop3 class=buttons003 onclick=qinc()>Vicky Cristina Barcelona</button><button id=incop4 class=buttons003 onclick=qinc()>Mighty Aphrodite</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Julie Andrews receive her Best Actress Oscar?",
"answ":"MARY POPPINS",
"answ2":"Mary Poppins.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mary Poppins</button><button id=incop2 class=buttons003 onclick=qinc()>Victor/Victoria</button><button id=incop3 class=buttons003 onclick=qinc()>The Sound of Music</button><button id=incop4 class=buttons003 onclick=qinc()>That's Life!</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Emma Thompson win her first Oscar?",
"answ":"HOWARDS END",
"answ2":"Howards End.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Howards End</button><button id=incop2 class=buttons003 onclick=qinc()>Sense and Sensibility</button><button id=incop3 class=buttons003 onclick=qinc()>The Remains of the Day</button><button id=incop4 class=buttons003 onclick=qinc()>The Winter Guest</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which film did Sidney Poitier receive his only Oscar?",
"answ":"LILIES OF THE FIELD",
"answ3":"LILLIES OF THE FIELD",
"answ2":"Lilies of the Field.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Lilies of the Field</button><button id=incop2 class=buttons003 onclick=qinc()>The Defiant Ones</button><button id=incop3 class=buttons003 onclick=qinc()>A Patch of Blue</button><button id=incop4 class=buttons003 onclick=qinc()>A Raisin in the Sun</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won a Best Actress Oscar for the 1971 film Klute?",
"answ":"JANE FONDA",
"answ2":"Jane Fonda.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jane Fonda</button><button id=incop2 class=buttons003 onclick=qinc()>Julie Christie</button><button id=incop3 class=buttons003 onclick=qinc()>Glenda Jackson</button><button id=incop4 class=buttons003 onclick=qinc()>Liza Minnelli</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Academy Award for writing Argo?",
"answ":"CHRIS TERRIO",
"answ2":"Chris Terrio.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Aaron Sorkin</button><button id=incop2 class=buttons003 onclick=qinc()>Billy Ray</button><button id=corop class=buttons003 onclick=qcor()>Chris Terrio</button><button id=incop4 class=buttons003 onclick=qinc()>Drew Goddard</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What drama won Best Picture for movies released in 1996?",
"answ":"THE ENGLISH PATIENT",
"answ3":"ENGLISH PATIENT",
"answ2":"The English Patient.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Braveheart</button><button id=incop2 class=buttons003 onclick=qinc()>Shine</button><button id=corop class=buttons003 onclick=qcor()>The English Patient</button><button id=incop4 class=buttons003 onclick=qinc()>Secrets & Lies</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What Barbra Streisand directed film was nominated for Best Picture?",
"answ":"THE PRINCE OF TIDES",
"answ3":"PRINCE OF TIDES",
"answ2":"The Prince of Tides.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Yentl</button><button id=incop2 class=buttons003 onclick=qinc()>Nuts</button><button id=corop class=buttons003 onclick=qcor()>The Prince of Tides</button><button id=incop4 class=buttons003 onclick=qinc()>The Mirror Has Two Faces</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who played Commodus in the Oscar winning film Gladiator?",
"answ":"JOAQUIN PHOENIX",
"answ2":"Joaquin Phoenix.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andy Garcia</button><button id=incop2 class=buttons003 onclick=qinc()>Russell Crowe</button><button id=corop class=buttons003 onclick=qcor()>Joaquin Phoenix</button><button id=incop4 class=buttons003 onclick=qinc()>Djimon Hounsou</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Actor Jack Lemmon won his sole Best Actor Oscar for which film?",
"answ":"SAVE THE TIGER",
"answ2":"Save the Tiger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Apartment</button><button id=incop2 class=buttons003 onclick=qinc()>The China Syndrome</button><button id=corop class=buttons003 onclick=qcor()>Save the Tiger</button><button id=incop4 class=buttons003 onclick=qinc()>Some Like It Hot</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who was the first African-American to be nominated for the Best Director Academy Award?",
"answ":"JOHN SINGLETON",
"answ2":"John Singleton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Spike Lee</button><button id=incop2 class=buttons003 onclick=qinc()>Barry Jenkins</button><button id=corop class=buttons003 onclick=qcor()>John Singleton</button><button id=incop4 class=buttons003 onclick=qinc()>Sidney Poitier</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Steven Soderbergh receive his Best Director Oscar?",
"answ":"TRAFFIC",
"answ2":"Traffic.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Erin Brockovich</button><button id=incop2 class=buttons003 onclick=qinc()>Sex, Lies and Videotape</button><button id=corop class=buttons003 onclick=qcor()>Traffic</button><button id=incop4 class=buttons003 onclick=qinc()>Contagion</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Goldie Hawn win her only Oscar?",
"answ":"CACTUS FLOWER",
"answ2":"Cactus Flower.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Cactus Flower</button><button id=incop2 class=buttons003 onclick=qinc()>Foul Play</button><button id=incop3 class=buttons003 onclick=qinc()>Private Benjamin</button><button id=incop4 class=buttons003 onclick=qinc()>Shampoo</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What director has received the most Best Director nominations at the Academy Awards?",
"answ":"WILLIAM WYLER",
"answ2":"William Wyler.",
"option":"<button id=corop class=buttons003 onclick=qcor()>William Wyler</button><button id=incop2 class=buttons003 onclick=qinc()>Martin Scorsese</button><button id=incop3 class=buttons003 onclick=qinc()>David Lean</button><button id=incop4 class=buttons003 onclick=qinc()>Fred Zinnemann</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What movie was Al Pacino's first Oscar nomination for Best Actor?",
"answ":"SERPICO",
"answ2":"Serpico.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Godfather</button><button id=incop2 class=buttons003 onclick=qinc()>The Godfather Part II</button><button id=corop class=buttons003 onclick=qcor()>Serpico</button><button id=incop4 class=buttons003 onclick=qinc()>Dog Day Afternoon</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Tom Hanks won his Best Actor Oscar for Philadelphia, a film that only won one other Oscar in which category?",
"answ":"BEST ORIGINAL SONG",
"answ3":"BEST SONG",
"answ2":"Best Original Song.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Actress</button><button id=incop2 class=buttons003 onclick=qinc()>Best Original Screenplay</button><button id=corop class=buttons003 onclick=qcor()>Best Original Song</button><button id=incop4 class=buttons003 onclick=qinc()>Best Supporting Actress</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Tom Berenger and whom were nominated for Best Supporting Actor in Platoon?",
"answ":"WILLEM DAFOE",
"answ3":"WILLEM DEFOE",
"answ2":"Willem Dafoe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Keith David</button><button id=incop2 class=buttons003 onclick=qinc()>Charlie Sheen</button><button id=corop class=buttons003 onclick=qcor()>Willem Dafoe</button><button id=incop4 class=buttons003 onclick=qinc()>Forest Whitaker</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"David Fincher has been nominated for Best Director twice, for the Social Network and what other film?",
"answ":"THE CURIOUS CASE OF BENJAMIN BUTTON",
"answ3":"CURIOUS CASE OF BENJAMIN BUTTON",
"answ2":"The Curious Case of Benjamin Button.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Girl with the Dragon Tattoo</button><button id=incop2 class=buttons003 onclick=qinc()>Gone Girl</button><button id=corop class=buttons003 onclick=qcor()>The Curious Case of Benjamin Button</button><button id=incop4 class=buttons003 onclick=qinc()>Zodiac</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For which film released in 2005 did Natalie Portman receive her first Oscar nomination?",
"answ":"CLOSER",
"answ2":"Closer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Garden State</button><button id=corop class=buttons003 onclick=qcor()>Closer</button><button id=incop3 class=buttons003 onclick=qinc()>Paris, je t'aime</button><button id=incop4 class=buttons003 onclick=qinc()>The Darjeeling Limited</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Jack Nicholson was nominated for an Academy Award three years in a row for The Last Detail, Chinatown and what movie?",
"answ":"ONE FLEW OVER THE CUCKOO'S NEST",
"answ3":"ONE FLEW OVER THE CUCKOOS NEST",
"answ2":"One Flew Over the Cuckoos's Nest.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Terms of Endearment</button><button id=corop class=buttons003 onclick=qcor()>One Flew Over the Cuckoos's Nest</button><button id=incop3 class=buttons003 onclick=qinc()>Prizzi's Honor</button><button id=incop4 class=buttons003 onclick=qinc()>As Good As It Gets</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"The Vietnam War film Coming Home was nominated for Best Picture in 1979. What other Vietnam War movie did it lose to?",
"answ":"THE DEER HUNTER",
"answ3":"DEER HUNTER",
"answ2":"The Deer Hunter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Apocalypse Now</button><button id=corop class=buttons003 onclick=qcor()>The Deer Hunter</button><button id=incop3 class=buttons003 onclick=qinc()>Patton</button><button id=incop4 class=buttons003 onclick=qinc()>Platoon</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Not counting his Honorary Award, Paul Newman won his only Oscar for his performance in what film?",
"answ":"THE COLOR OF MONEY",
"answ3":"COLOR OF MONEY",
"answ2":"The Color of Money.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Hustler</button><button id=corop class=buttons003 onclick=qcor()>The Color of Money</button><button id=incop3 class=buttons003 onclick=qinc()>The Towering Inferno</button><button id=incop4 class=buttons003 onclick=qinc()>Road to Perdition</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"While Argo won Best Picture for films released in 2012, Ben Affleck was famously not nominated for Best Director. Who won Best Director that year?",
"answ":"ANG LEE",
"answ2":"Ang Lee.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>David O. Russell</button><button id=corop class=buttons003 onclick=qcor()>Ang Lee</button><button id=incop3 class=buttons003 onclick=qinc()>Martin Scorsese</button><button id=incop4 class=buttons003 onclick=qinc()>Steven Spielberg</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Sigourney Weaver receive her first Oscar nomination?",
"answ":"ALIENS",
"answ2":"Aliens.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Working Girl</button><button id=corop class=buttons003 onclick=qcor()>Aliens</button><button id=incop3 class=buttons003 onclick=qinc()>Gorillas in the Mist</button><button id=incop4 class=buttons003 onclick=qinc()>The Year of Living Dangerously</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What is the only Coen Brothers directed film to win Best Picture at the Oscars?",
"answ":"NO COUNTRY FOR OLD MEN",
"answ2":"No Country For Old Men.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fargo</button><button id=corop class=buttons003 onclick=qcor()>No Country For Old Men</button><button id=incop3 class=buttons003 onclick=qinc()>True Grit</button><button id=incop4 class=buttons003 onclick=qinc()>A Serious Man</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Penelope Cruz has won her only Academy Award for her role in what film?",
"answ":"VICKY CRISTINA BARCELONA",
"answ3":"VICKY KRISTINA BARCELONA",
"answ2":"Vicky Cristina Barcelona.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Volver</button><button id=corop class=buttons003 onclick=qcor()>Vicky Cristina Barcelona</button><button id=incop3 class=buttons003 onclick=qinc()>Nine</button><button id=incop4 class=buttons003 onclick=qinc()>Broken Embraces</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Leonardo DiCaprio's first Oscar nomination came for What's Eating Gilbert Grape in 1995. Who did he lose to?",
"answ":"TOMMY LEE JONES",
"answ2":"Tommy Lee Jones.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ralph Fiennes</button><button id=incop2 class=buttons003 onclick=qinc()>John Malkovich</button><button id=incop3 class=buttons003 onclick=qinc()>Pete Postlewaite</button><button id=corop class=buttons003 onclick=qcor()>Tommy Lee Jones</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who is the only actress to win an Oscar for playing a man?",
"answ":"LINDA HUNT",
"answ2":"Linda Hunt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hilary Swank</button><button id=incop2 class=buttons003 onclick=qinc()>Scarlett Johansson</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=corop class=buttons003 onclick=qcor()>Linda Hunt</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Name the movie for which actor Frank Langella was nominated for an Academy Award.",
"answ":"FROST/NIXON",
"answ3":"FROST NIXON",
"answ2":"Frost/Nixon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Captain Fantastic</button><button id=incop2 class=buttons003 onclick=qinc()>Good Night, and Good Luck</button><button id=incop3 class=buttons003 onclick=qinc()>Starting Out in the Evening</button><button id=corop class=buttons003 onclick=qcor()>Frost/Nixon</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won an Oscar for playing Queen Elizabeth I in Shakespeare in Love?",
"answ":"JUDI DENCH",
"answ2":"Judi Dench.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gwyneth Paltrow</button><button id=incop2 class=buttons003 onclick=qinc()>Maggie Smith</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=corop class=buttons003 onclick=qcor()>Judi Dench</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Citizen Kane famously did not win Best Picture, what film beat it to win Best Picture for films released in 1941?",
"answ":"HOW GREEN WAS MY VALLEY",
"answ2":"How Green Was My Valley.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Maltese Falcon</button><button id=incop2 class=buttons003 onclick=qinc()>Here Comes Mr. Jordan</button><button id=incop3 class=buttons003 onclick=qinc()>Hold Back the Dawn</button><button id=corop class=buttons003 onclick=qcor()>How Green Was My Valley</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Frank Sinatra win his Oscar for Best Supporting Actor?",
"answ":"FROM HERE TO ETERNITY",
"answ2":"From Here to Eternity.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Man with the Golden Arm</button><button id=incop2 class=buttons003 onclick=qinc()>The House I Live In</button><button id=incop3 class=buttons003 onclick=qinc()>Never So Few</button><button id=corop class=buttons003 onclick=qcor()>From Here to Eternity</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Nicole Kidman won her only Oscar for her acting performance in what film?",
"answ":"THE HOURS",
"answ2":"The Hours.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lion</button><button id=incop2 class=buttons003 onclick=qinc()>Rabbit Hole</button><button id=incop3 class=buttons003 onclick=qinc()>Moulin Rouge!</button><button id=corop class=buttons003 onclick=qcor()>The Hours</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Tommy Lee Jones receive his first Oscar nomination?",
"answ":"JFK",
"answ2":"JFK.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Love Story</button><button id=incop2 class=buttons003 onclick=qinc()>Coal Miner's Daughter</button><button id=corop class=buttons003 onclick=qcor()>JFK</button><button id=incop4 class=buttons003 onclick=qinc()>The Fugitive</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie has Martin Scorsese won his only Best Director Oscar?",
"answ":"THE DEPARTED",
"answ2":"The Departed.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Irishman</button><button id=incop2 class=buttons003 onclick=qinc()>The Wolf of Wall Street</button><button id=corop class=buttons003 onclick=qcor()>The Departed</button><button id=incop4 class=buttons003 onclick=qinc()>Hugo</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What is the only Spielberg film to have one of his actors win Best Actor at the Academy Awards?",
"answ":"LINCOLN",
"answ2":"Lincoln.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Schindler's List</button><button id=incop2 class=buttons003 onclick=qinc()>Saving Private Ryan</button><button id=corop class=buttons003 onclick=qcor()>Lincoln</button><button id=incop4 class=buttons003 onclick=qinc()>Bridge of Spies</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"As of 2020, what was Russell Crowe's last Oscar nomination?",
"answ":"A BEAUTIFUL MIND",
"answ2":"A Beautiful Mind.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Insider</button><button id=incop2 class=buttons003 onclick=qinc()>Gladiator</button><button id=corop class=buttons003 onclick=qcor()>A Beautiful Mind</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella Man</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Michel Hazanavicius won Best Director for directing which film?",
"answ":"THE ARTIST",
"answ2":"The Artist.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Search</button><button id=incop2 class=buttons003 onclick=qinc()>The Players</button><button id=corop class=buttons003 onclick=qcor()>The Artist</button><button id=incop4 class=buttons003 onclick=qinc()>Redoubtable</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Oscars did The Silence of the Lambs win?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=incop2 class=buttons003 onclick=qinc()>4</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who won the Best Director Oscar for Terms of Endearment?",
"answ":"JAMES L BROOKS",
"answ3":"JAMES BROOKS",
"answ2":"James L. Brooks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mike Nichols</button><button id=incop2 class=buttons003 onclick=qinc()>Bruce Beresford</button><button id=corop class=buttons003 onclick=qcor()>James L. Brooks</button><button id=incop4 class=buttons003 onclick=qinc()>Sydney Pollack</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who sang the Oscar winning song 'Secret Love' from the 1953 western comedy Calamity Jane?",
"answ":"DORIS DAY",
"answ2":"Doris Day.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Marilyn Monroe</button><button id=corop class=buttons003 onclick=qcor()>Doris Day</button><button id=incop3 class=buttons003 onclick=qinc()>Jane Russell</button><button id=incop4 class=buttons003 onclick=qinc()>Betty Grable</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Alan Arkin won his first Oscar for Best Supporting Actor for which film?",
"answ":"LITTLE MISS SUNSHINE",
"answ2":"Little Miss Sunshine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Argo</button><button id=corop class=buttons003 onclick=qcor()>Little Miss Sunshine</button><button id=incop3 class=buttons003 onclick=qinc()>The Heart Is a Lonely Hunter</button><button id=incop4 class=buttons003 onclick=qinc()>The Rocketeer</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what movie did Jack Nicholson receive his first Oscar nomination for Best Actor?",
"answ":"FIVE EASY PIECES",
"answ2":"Five Easy Pieces.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>One Flew Over the Cuckoo's Nest</button><button id=incop2 class=buttons003 onclick=qinc()>Chinatown</button><button id=corop class=buttons003 onclick=qcor()>Five Easy Pieces</button><button id=incop4 class=buttons003 onclick=qinc()>Prizzi's Honor</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Oscars has Emma Stone been nominated for?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who was the first African-American performer to win an Academy Award?",
"answ":"HATTIE MCDANIEL",
"answ3":"HATTY MCDANIEL",
"answ2":"Hattie McDaniel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dorothy Dandridge</button><button id=incop2 class=buttons003 onclick=qinc()>Rupert Crosse</button><button id=corop class=buttons003 onclick=qcor()>Hattie McDaniel</button><button id=incop4 class=buttons003 onclick=qinc()>Juanita Moore</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first hip-hop/rap song to win Best Original Song at the Oscars?",
"answ":"LOSE YOURSELF",
"answ2":"Lose Yourself.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>All The Stars</button><button id=incop2 class=buttons003 onclick=qinc()>Glory</button><button id=corop class=buttons003 onclick=qcor()>Lose Yourself</button><button id=incop4 class=buttons003 onclick=qinc()>It's Hard out Here for a Pimp</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What actor was nominated for an Oscar for their role in Starman?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Donald Pleasence</button><button id=incop2 class=buttons003 onclick=qinc()>Kurt Russell</button><button id=corop class=buttons003 onclick=qcor()>Jeff Bridges</button><button id=incop4 class=buttons003 onclick=qinc()>Sam Neill</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"This actress won the Oscar for Best Supporting Actress at the 2018 Academy Awards.",
"answ":"ALLISON JANNEY",
"answ2":"Allison Janney.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Octavia Spencer</button><button id=incop2 class=buttons003 onclick=qinc()>Nicole Kidman</button><button id=corop class=buttons003 onclick=qcor()>Allison Janney</button><button id=incop4 class=buttons003 onclick=qinc()>Laura Dern</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What actress won an Academy Award for Best Actress in the 1954 film The Country Girl?",
"answ":"GRACE KELLY",
"answ2":"Grace Kelly.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Audrey Hepburn</button><button id=incop2 class=buttons003 onclick=qinc()>Donna Reed</button><button id=corop class=buttons003 onclick=qcor()>Grace Kelly</button><button id=incop4 class=buttons003 onclick=qinc()>Jo Van Fleet</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Christian Bale has won his only Academy Award for his role in what film?",
"answ":"THE FIGHTER",
"answ2":"The Fighter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>American Hustle</button><button id=incop2 class=buttons003 onclick=qinc()>The Big Short</button><button id=corop class=buttons003 onclick=qcor()>The Fighter</button><button id=incop4 class=buttons003 onclick=qinc()>Vice</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Abigail Breslin received her first Oscar nomination for her supporting role in what 2006 film?",
"answ":"LITTLE MISS SUNSHINE",
"answ2":"Little Miss Sunshine.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Raising Helen</button><button id=incop2 class=buttons003 onclick=qinc()>The Ultimate Gift</button><button id=corop class=buttons003 onclick=qcor()>Little Miss Sunshine</button><button id=incop4 class=buttons003 onclick=qinc()>Definitely, Maybe</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Susan Sarandon has won her only Academy Award for her role in what film?",
"answ":"DEAD MAN WALKING",
"answ2":"Dead Man Walking.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Client</button><button id=incop2 class=buttons003 onclick=qinc()>Thelma & Louise</button><button id=corop class=buttons003 onclick=qcor()>Dead Man Walking</button><button id=incop4 class=buttons003 onclick=qinc()>Lorenzo's Oil</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"All the President's Men lost to which film for Best Picture at the Academy Awards?",
"answ":"ROCKY",
"answ2":"Rocky.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Network</button><button id=incop2 class=buttons003 onclick=qinc()>One Flew Over the Cuckoo's Nest</button><button id=corop class=buttons003 onclick=qcor()>Rocky</button><button id=incop4 class=buttons003 onclick=qinc()>Taxi Driver</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Academy Awards did The Shape of Water win in 2018?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"This film was the last musical to win the Best Picture Oscar.",
"answ":"CHICAGO",
"answ2":"Chicago.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>My Fair Lady</button><button id=incop2 class=buttons003 onclick=qinc()>An American in Paris</button><button id=incop3 class=buttons003 onclick=qinc()>Oliver!</button><button id=corop class=buttons003 onclick=qcor()>Chicago</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Almost Famous received 4 Oscar nominations and won one. For what category did the movie win?",
"answ":"BEST ORIGINAL SCREENPLAY",
"answ3":"ORIGINAL SCREENPLAY",
"answ2":"Best Original Screenplay.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Supporting Actress</button><button id=corop class=buttons003 onclick=qcor()>Best Original Screenplay</button><button id=incop3 class=buttons003 onclick=qinc()>Best Original Score</button><button id=incop4 class=buttons003 onclick=qinc()>Best Editing</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Tom Hanks received his first Best Actor nomination for what film?",
"answ":"BIG",
"answ2":"Big.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Philadelphia</button><button id=corop class=buttons003 onclick=qcor()>Big</button><button id=incop3 class=buttons003 onclick=qinc()>Forrest Gump</button><button id=incop4 class=buttons003 onclick=qinc()>Saving Private Ryan</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"This film was the last Best Picture winner to also win Oscars in every other category it was nominated in.",
"answ":"THE LORD OF THE RINGS THE RETURN OF THE KING",
"answ3":"LORD OF THE RINGS THE RETURN OF THE KING",
"answ2":"The Lord of the Rings: The Return of the King.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Spotlight</button><button id=corop class=buttons003 onclick=qcor()>The Lord of the Rings: The Return of the King</button><button id=incop3 class=buttons003 onclick=qinc()>Moonlight</button><button id=incop4 class=buttons003 onclick=qinc()>No Country for Old Men</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Shirley MacLaine won the Best Actress Oscar for what film?",
"answ":"TERMS OF ENDEARMENT",
"answ2":"Terms of Endearment.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Turning Point</button><button id=corop class=buttons003 onclick=qcor()>Terms of Endearment</button><button id=incop3 class=buttons003 onclick=qinc()>Irma la Douce</button><button id=incop4 class=buttons003 onclick=qinc()>The Apartment</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Al Pacino was nominated for 2 Academy Awards for films released in 1992. He won for Scent of a Woman, what was the other film he was nominated for?",
"answ":"GLENGARRY GLEN ROSS",
"answ3":"GLENGARRY GLENN ROSS",
"answ2":"Glengarry Glen Ross.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Frankie and Johnny</button><button id=corop class=buttons003 onclick=qcor()>Glengarry Glen Ross</button><button id=incop3 class=buttons003 onclick=qinc()>The Godfather Part III</button><button id=incop4 class=buttons003 onclick=qinc()>Carlito's Way</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Lina Wertmuller was the first woman to be nominated for this category in 1977.",
"answ":"BEST DIRECTOR",
"answ3":"DIRECTOR",
"answ2":"Best Director.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Original Screenplay</button><button id=corop class=buttons003 onclick=qcor()>Best Director</button><button id=incop3 class=buttons003 onclick=qinc()>Best Adapted Screenplay</button><button id=incop4 class=buttons003 onclick=qinc()>Best Original Score</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many Oscars did La La Land win at the 89th Academy Awards?",
"answ":"SIX",
"answ3":"6",
"answ2":"6.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>10</button><button id=corop class=buttons003 onclick=qcor()>6</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>7</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"For what film did legendary director Akira Kurosawa receive his only Oscar nomination for Best Director?",
"answ":"RAN",
"answ2":"Ran.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Seven Samurai</button><button id=corop class=buttons003 onclick=qcor()>Ran</button><button id=incop3 class=buttons003 onclick=qinc()>The Hidden Fortress</button><button id=incop4 class=buttons003 onclick=qinc()>Rashomon</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Robin Williams received his first Oscar nomination for Best Actor for which film?",
"answ":"GOODMORNING VIETNAM",
"answ3":"GOODMORNING  VIETNAM",
"answ2":"Good Morning, Vietnam.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Fisher King</button><button id=corop class=buttons003 onclick=qcor()>Good Morning, Vietnam</button><button id=incop3 class=buttons003 onclick=qinc()>Dead Poets Society</button><button id=incop4 class=buttons003 onclick=qinc()>Good Will Hunting</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Warren Beatty has been nominated in over 4 different Oscar categories, for which one has he won his only Oscar?",
"answ":"BEST DIRECTOR",
"answ3":"DIRECTOR",
"answ2":"Best Director.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Actor</button><button id=corop class=buttons003 onclick=qcor()>Best Director</button><button id=incop3 class=buttons003 onclick=qinc()>Best Original Screenplay</button><button id=incop4 class=buttons003 onclick=qinc()>Best Supporting Actor</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Jeff Bridges has been nominated for an Academy Award 7 times, what film got him his first nomination?",
"answ":"THE LAST PICTURE SHOW",
"answ3":"LAST PICTURE SHOW",
"answ2":"The Last Picture Show.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Thunderbolt and Lightfoot</button><button id=corop class=buttons003 onclick=qcor()>The Last Picture Show</button><button id=incop3 class=buttons003 onclick=qinc()>Starman</button><button id=incop4 class=buttons003 onclick=qinc()>Crazy Heart</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who received Best Director nominations for the classic films A Foreign Affair, Stalag 17 and Witness For The Prosecution?",
"answ":"BILLY WILDER",
"answ2":"Billy Wilder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Huston</button><button id=corop class=buttons003 onclick=qcor()>Billy Wilder</button><button id=incop3 class=buttons003 onclick=qinc()>William Wyler</button><button id=incop4 class=buttons003 onclick=qinc()>Carol Reed</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Name this Best Picture winning film from the synopsis: A young nurse tends to a badly-burned plane crash victim. Flashbacks reveal his involvement in a fateful love affair.",
"answ":"THE ENGLISH PATIENT",
"answ2":"The English Patient.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>American Beauty</button><button id=corop class=buttons003 onclick=qcor()>The English Patient</button><button id=incop3 class=buttons003 onclick=qinc()>Chariots of Fire</button><button id=incop4 class=buttons003 onclick=qinc()>In the Heat of the Night</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Nicolas Cage won his only Oscar for which film?",
"answ":"LEAVING LAS VEGAS",
"answ2":"Leaving Las Vegas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Adaptation</button><button id=corop class=buttons003 onclick=qcor()>Leaving Las Vegas</button><button id=incop3 class=buttons003 onclick=qinc()>Raising Arizona</button><button id=incop4 class=buttons003 onclick=qinc()>Moonstruck</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Michael Keaton received his only Oscar nomination for what film?",
"answ":"BIRDMAN",
"answ3":"BIRDMAN OR THE UNEXPECTED VIRTUE OF IGNORANCE",
"answ2":"Birdman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Founder</button><button id=corop class=buttons003 onclick=qcor()>Birdman</button><button id=incop3 class=buttons003 onclick=qinc()>Spotlight</button><button id=incop4 class=buttons003 onclick=qinc()>Beetlejuice</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first musical to win Best Picture?",
"answ":"THE BROADWAY MELODY",
"answ3":"BROADWAY MELODY",
"answ2":"The Broadway Melody.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>An American in Paris</button><button id=corop class=buttons003 onclick=qcor()>The Broadway Melody</button><button id=incop3 class=buttons003 onclick=qinc()>Gigi</button><button id=incop4 class=buttons003 onclick=qinc()>West Side Story</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What was the first Paul Thomas Anderson film nominated for Best Picture?",
"answ":"THERE WILL BE BLOOD",
"answ2":"There Will Be Blood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Magnolia</button><button id=corop class=buttons003 onclick=qcor()>There Will Be Blood</button><button id=incop3 class=buttons003 onclick=qinc()>Boogie Nights</button><button id=incop4 class=buttons003 onclick=qinc()>Phantom Thread</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Matt Damon has been nominated for the Best Actor Oscar twice. For Good Will Hunting and what 2010's film?",
"answ":"THE MARTIAN",
"answ2":"The Martian.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ford v Ferrari</button><button id=corop class=buttons003 onclick=qcor()>The Martian</button><button id=incop3 class=buttons003 onclick=qinc()>Interstellar</button><button id=incop4 class=buttons003 onclick=qinc()>The Monuments Men</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"How many times has David Lynch been nominated for Best Director?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>0</button><button id=incop2 class=buttons003 onclick=qinc()>1</button><button id=incop3 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Who directed the film Bowling for Columbine, which won the Oscar for Best Documentary Feature?",
"answ":"MICHAEL MOORE",
"answ2":"Michael Moore.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael Moore</button><button id=incop2 class=buttons003 onclick=qinc()>Errol Morris</button><button id=incop3 class=buttons003 onclick=qinc()>Morgan Spurlock</button><button id=incop4 class=buttons003 onclick=qinc()>Joe Berlinger</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What film won the Best Original Song Oscar for 'Colors of the Wind'?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pocahontas</button><button id=incop2 class=buttons003 onclick=qinc()>The Lion King</button><button id=incop3 class=buttons003 onclick=qinc()>Aladdin</button><button id=incop4 class=buttons003 onclick=qinc()>The Prince of Egypt</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Timothy Hutton was 20 years old when he won an Oscar for Best Supporting Actor, what film did he win for?",
"answ":"ORDINARY PEOPLE",
"answ2":"Ordinary People.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ordinary People</button><button id=incop2 class=buttons003 onclick=qinc()>Taps</button><button id=incop3 class=buttons003 onclick=qinc()>The General's Daughter</button><button id=incop4 class=buttons003 onclick=qinc()>Beautiful Girls</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Scarlett Johansson was recently nominated for two acting nominations in the same year. Which actress achieved this feat previously in 2007?",
"answ":"CATE BLANCHETT",
"answ2":"Cate Blanchett.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Julianne Moore</button><button id=corop class=buttons003 onclick=qcor()>Cate Blanchett</button><button id=incop3 class=buttons003 onclick=qinc()>Emma Thompson</button><button id=incop4 class=buttons003 onclick=qinc()>Meryl Streep</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"What 1997 film earned Robin William his only Oscar win?",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mrs. Doubtfire</button><button id=corop class=buttons003 onclick=qcor()>Good Will Hunting</button><button id=incop3 class=buttons003 onclick=qinc()>The Birdcage</button><button id=incop4 class=buttons003 onclick=qinc()>Hamlet</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Steven Spielberg's Empire of the Sun was nominated for a total of 6 Oscars, but lost every one to what Best Picture winner?",
"answ":"LAST EMPEROR",
"answ3":"THE LAST EMPEROR",
"answ2":"The Last Emperor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rain Man</button><button id=corop class=buttons003 onclick=qcor()>The Last Emperor</button><button id=incop3 class=buttons003 onclick=qinc()>Platoon</button><button id=incop4 class=buttons003 onclick=qinc()>Moonstruck</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Anne Hathaway received her first Oscar nomination for playing a woman recently released from rehab in what 2000s drama?",
"answ":"RACHEL GETTING MARRIED",
"answ2":"Rachel Getting Married.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Colossal</button><button id=corop class=buttons003 onclick=qcor()>Rachel Getting Married</button><button id=incop3 class=buttons003 onclick=qinc()>Becoming Jane</button><button id=incop4 class=buttons003 onclick=qinc()>Love & Other Drugs</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Spike Lee received his first Oscar nomination in which category?",
"answ":"BEST ORIGINAL SCREENPLAY",
"answ3":"ORIGINAL SCREENPLAY",
"answ2":"Best Original Screenplay.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Picture</button><button id=corop class=buttons003 onclick=qcor()>Best Original Screenplay</button><button id=incop3 class=buttons003 onclick=qinc()>Best Director</button><button id=incop4 class=buttons003 onclick=qinc()>Best Adapted Screenplay</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Viola Davis won an acting Oscar for what 2010s drama?",
"answ":"FENCES",
"answ2":"Fences.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Help</button><button id=corop class=buttons003 onclick=qcor()>Fences</button><button id=incop3 class=buttons003 onclick=qinc()>Prisoners</button><button id=incop4 class=buttons003 onclick=qinc()>Widows</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Few performers have ever been nominated for playing the same character twice, who is the most recent actor to achieve this feat?",
"answ":"SYLVESTER STALLONE",
"answ2":"Sylvester Stallone.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Al Pacino</button><button id=corop class=buttons003 onclick=qcor()>Sylvester Stallone</button><button id=incop3 class=buttons003 onclick=qinc()>Robert De Niro</button><button id=incop4 class=buttons003 onclick=qinc()>Harrison Ford</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"The films Annie Hall, The Deer Hunter and The Sting won Best Picture in what decade?",
"answ":"1970S",
"answ3":"70S",
"answ2":"1970s.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1960s</button><button id=corop class=buttons003 onclick=qcor()>1970s</button><button id=incop3 class=buttons003 onclick=qinc()>1980s</button><button id=incop4 class=buttons003 onclick=qinc()>1990s</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"In Steven Spielberg's Amistad, who was the only performer to be nominated for an acting Oscar?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Djimon Hounsou</button><button id=corop class=buttons003 onclick=qcor()>Anthony Hopkins</button><button id=incop3 class=buttons003 onclick=qinc()>Matthew McConaughey</button><button id=incop4 class=buttons003 onclick=qinc()>Morgan Freeman</button><br/>",
},
{
"cat":"Oscar Movies",
"ques":"Several films had the honor of being nominated for all 4 acting awards, name the most recent film to accomplish this feat.",
"answ":"AMERICAN HUSTLE",
"answ2":"American Hustle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Silver Linings Playbook</button><button id=corop class=buttons003 onclick=qcor()>American Hustle</button><button id=incop3 class=buttons003 onclick=qinc()>La La Land</button><button id=incop4 class=buttons003 onclick=qinc()>Network</button><br/>",
},
];
oscarmovies = shuffle(oscarmovies);
r2Q6 = shuffle(r2Q6);