var r2Q62 = [
{
"cat":"Eddie Murphy",
"ques":"Who directed Nutty Professor II: The Klumps?",
"answ":"PETER SEGAL",
"answ2":"Peter Segal.",
"option":["Peter Segal", "Walter Hill", "Steve Carr", "Bill Condon"],
},
{
"cat":"Eddie Murphy",
"ques":"Name the movie in which Eddie Murphy announces: 'There's a new sheriff in town, and his name is Reggie Hammond.'",
"answ":"48 HRS",
"answ2":"48 Hrs.",
"option":["48 Hrs", "Showtime", "Beverly Hills Cop", "Harlem Nights"],
},
{
"cat":"Eddie Murphy",
"ques":"In Coming to America, Daryl is living off his father's invention of a hair product. What is the name of that product?",
"answ":"SOUL GLO",
"answ2":"Soul-Glo.",
"option":["Soul-Glo", "Vidal Sassoon", "Curly Q", "Peek-A-Boo"],
},
{
"cat":"Eddie Murphy",
"ques":"James Garner and Chi McBride appear in what 1990's Eddie Murphy film?",
"answ":"THE DISTINGUISHED GENTLEMAN",
"answ3":"DISTINGUISHED GENTLEMAN",
"answ2":"The Distinguished Gentleman.",
"option":["The Distinguished Gentleman", "Boomerang", "Bowfinger", "Holy Man"],
},
{
"cat":"Eddie Murphy",
"ques":"Beverly Hills Cop Axel Foley was originally from what city?",
"answ":"DETROIT",
"answ2":"Detroit.",
"option":["Detroit", "Chicago", "New York", "Boston"],
},
{
"cat":"Eddie Murphy",
"ques":"What 90s Eddie Murphy film featuring Martin Lawrence has the tagline: 'A player who's about to be played'?",
"answ":"BOOMERANG",
"answ2":"Boomerang.",
"option":["Boomerang", "Bowfinger", "The Distinguished Gentleman", "Holy Man"],
},
{
"cat":"Eddie Murphy",
"ques":"Who plays the lead role of Josh Kovaks alongside Eddie Murphy and Matthew Broderick in the film Tower Heist?",
"answ":"BEN STILLER",
"answ2":"Ben Stiller.",
"option":["Ben Stiller", "Steve Carell", "John C. Reilly", "Martin Lawrence"],
},
{
"cat":"Eddie Murphy",
"ques":"Which famous singer plays Eddie Murphy's love interest Denise in Nutty Professor II?",
"answ":"JANET JACKSON",
"answ2":"Janet Jackson.",
"option":["Janet Jackson", "Madonna", "Tina Turner", "Whitney Houston"],
},
{
"cat":"Eddie Murphy",
"ques":"Who directed Eddie Murphy in 1995's Vampire in Brooklyn?",
"answ":"WES CRAVEN",
"answ2":"Wes Craven.",
"option":["Wes Craven", "Thomas Carter", "John Landis", "Martin Brest"],
},
{
"cat":"Eddie Murphy",
"ques":"Who played love interest Carla Purdy in 1996's The Nutty Professor?",
"answ":"JADA PINKETT SMITH",
"answ3":"JADA PINKETT",
"answ2":"Jada Pinkett Smith.",
"option":["Jada Pinkett Smith", "Gina Torres", "Angela Bassett", "Viola Davis"],
},
{
"cat":"Eddie Murphy",
"ques":"In Coming to America, what is the name of the fictional African country that Akeem is the crown prince of?",
"answ":"ZAMUNDA",
"answ2":"Zamunda.",
"option":["Zamunda", "Sangala", "Natumbe", "Kalubya"],
},
{
"cat":"Eddie Murphy",
"ques":"What is the first name of Professor Klump in The Nutty Professor films?",
"answ":"SHERMAN",
"answ2":"Sherman.",
"option":["Sherman", "Isaac", "Ernie", "Dean"],
},
{
"cat":"Eddie Murphy",
"ques":"In what 90s comedy does Eddie Murphy have a dual role as a movie star and his nerdy brother Jiff?",
"answ":"BOWFINGER",
"answ2":"Bowfinger.",
"option":["Bowfinger", "The Distinguished Gentleman", "Coming to America", "Boomerang"],
},
{
"cat":"Eddie Murphy",
"ques":"In the 2016 film Mr. Church, Eddie's character gets hired to do what for a family in need?",
"answ":"COOK",
"answ3":"COOKING",
"answ2":"Cook.",
"option":["Cook", "Fix the roof", "Gardening", "Paint the house"],
},
{
"cat":"Eddie Murphy",
"ques":"Who plays Ricky Hayman, an executive at a home shopping network on the verge of losing his job in 1998's Holy Man?",
"answ":"JEFF GOLDBLUM",
"answ2":"Jeff Goldblum.",
"option":["Jeff Goldblum", "Jim Belushi", "Michael Keaton", "Oliver Platt"],
},
{
"cat":"Eddie Murphy",
"ques":"Who portrayed Bruno, Eddie Murphy's android friend in The Adventures of Pluto Nash?",
"answ":"RANDY QUAID",
"answ2":"Randy Quaid.",
"option":["Randy Quaid", "Eddie Griffin", "William Shatner", "Luis Guzmán"],
},
{
"cat":"Eddie Murphy",
"ques":"In Meet Dave, who played single mother Gina Morrison?",
"answ":"ELIZABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":["Elizabeth Banks", "Drew Barrymore", "Jennifer Aniston", "Charlize Theron"],
},
{
"cat":"Eddie Murphy",
"ques":"Who played Eddie Murphy's wife in A Thousand Words?",
"answ":"KERRY WASHINGTON",
"answ2":"Kerry Washington.",
"option":["Kerry Washington", "Thandie Newton", "Salma Hayek", "Téa Leoni"],
},
{
"cat":"Eddie Murphy",
"ques":"In 1996's The Nutty Professor, what is the false identity that Professor Sherman assumes when he is his thinner self?",
"answ":"BUDDY LOVE",
"answ2":"Buddy Love.",
"option":["Buddy Love", "Sherman Klump", "Reggie Hammond", "Axel Foley"],
},
{
"cat":"Eddie Murphy",
"ques":"Who co-stars with Eddie Murphy as Robert K. Bowfinger in 1999's Bowfinger?",
"answ":"STEVE MARTIN",
"answ2":"Steve Martin.",
"option":["Steve Martin", "Jon Voight", "Leslie Nielsen", "Martin Lawrence"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy goes to a theme park known as Wonder World, in an attempt to stop a gang of counterfeiters who are responsible for the death of his boss in what film?",
"answ":"BEVERLY HILLS COP 3",
"answ3":"BEVERLY HILLS COP III",
"answ2":"Beverly Hills Cop III.",
"option":["Beverly Hills Cop III", "Harlem Nights", "I Spy", "Beverly Hills Cop II"],
},
{
"cat":"Eddie Murphy",
"ques":"Who directed Eddie Murphy in the Rudy Ray Moore biopic, Dolemite is My Name?",
"answ":"CRAIG BREWER",
"answ2":"Craig Brewer.",
"option":["Craig Brewer", "Frank Oz", "Eddie Murphy", "Bruce Beresford"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy plays Chandler Jarrell, who is informed that he is 'The Chosen One' in what 1986 film?",
"answ":"THE GOLDEN CHILD",
"answ3":"GOLDEN CHILD",
"answ2":"The Golden Child.",
"option":["The Golden Child", "Harlem Nights", "Boomerang", "Holy Man"],
},
{
"cat":"Eddie Murphy",
"ques":"Who voices King Harold, Fiona's father, in Shrek 2?",
"answ":"JOHN CLEESE",
"answ2":"John Cleese.",
"option":["John Cleese", "Rupert Everett", "Antonio Banderas", "John Lithgow"],
},
{
"cat":"Eddie Murphy",
"ques":"In Beverly Hills Cop, what city was Eddie Murphy based before he moved out to Beverly Hills?",
"answ":"DETROIT",
"answ2":"Detroit.",
"option":["Detroit", "Chicago", "New York", "Miami"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy and Martin Lawrence share the screen as a loudmouth Harlem grifter Ray and the no-nonsense Claude in what 1999 film?",
"answ":"LIFE",
"answ2":"Life.",
"option":["Life", "Boomerang", "The Nutty Professor", "Bowfinger"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy and Robert De Niro play two cops who are paired for a reality police show and run into real trouble with a crime lord in what 2002 film?",
"answ":"SHOWTIME",
"answ3":"SHOW TIME",
"answ2":"Showtime.",
"option":["Showtime", "Boomerang", "Imagine That", "Bowfinger"],
},
{
"cat":"Eddie Murphy",
"ques":"What 80s film was the first sequel that Eddie Murphy starred in?",
"answ":"BEVERLY HILLS COP 2",
"answ3":"BEVERLY HILLS COP II",
"answ2":"Beverly Hills Cop II.",
"option":["Beverly Hills Cop II", "Another 48 Hrs.", "Nutty Professor II: The Klumps", "Dr. Dolittle 2"],
},
{
"cat":"Eddie Murphy",
"ques":"Which classic comedy was the feature film debut of Eddie Murphy?",
"answ":"48 HRS",
"answ3":"48 HOURS",
"answ2":"48 Hrs.",
"option":["48 Hrs.", "Beverly Hills Cop", "Coming to America", "Trading Places"],
},
{
"cat":"Eddie Murphy",
"ques":"Who directed Eddie Murphy in Harlem Nights?",
"answ":"EDDIE MURPHY",
"answ2":"Eddie Murphy.",
"option":["Eddie Murphy", "Walter Hill", "Tony Scott", "Martin Brest"],
},
{
"cat":"Eddie Murphy",
"ques":"Martin Brest directed Eddie Murphy in what 1984 comedy, where he is investigating his friend's murder in California?",
"answ":"BEVERLY HILLS COP",
"answ2":"Beverly Hills Cop.",
"option":["Beverly Hills Cop", "The Golden Child", "Best Defense", "Beverly Hills Cop II"],
},
{
"cat":"Eddie Murphy",
"ques":"Which actress stars as special agent Rachel Wright, who gets placed under arrest by Eddie Murphy and Owen Wilson's characters in I Spy?",
"answ":"FAMKE JANSSEN",
"answ3":"FAMKE JANSEN",
"answ2":"Famke Janssen.",
"option":["Famke Janssen", "Halle Berry", "Rachel Weisz", "Regina King"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy has received 1 Oscar nomination for which film?",
"answ":"DREAMGIRLS",
"answ2":"Dreamgirls.",
"option":["Dreamgirls", "Dolemite Is My Name", "The Distinguished Gentleman", "Mr. Church"],
},
{
"cat":"Eddie Murphy",
"ques":"Which actor plays Phil Ryerson, one of three men who run a daycare known as Daddy Day Care, in the film Daddy Day Care?",
"answ":"JEFF GARLIN",
"answ2":"Jeff Garlin.",
"option":["Jeff Garlin", "Steve Zahn", "John Goodman", "Owen Wilson"],
},
{
"cat":"Eddie Murphy",
"ques":"Eddie Murphy plays Sherman Klump alongside Jada Pinkett Smith in what 90s film?",
"answ":"THE NUTTY PROFESSOR",
"answ3":"NUTTY PROFESSOR",
"answ2":"The Nutty Professor.",
"option":["The Nutty Professor", "Metro", "Norbit", "Dr. Dolittle"],
},
{
"cat":"Eddie Murphy",
"ques":"What was the first movie that starred both Eddie Murphy and Arsenio Hall?",
"answ":"COMING TO AMERICA",
"answ2":"Coming to America.",
"option":["Coming to America", "Trading Places", "The Golden Child", "Beverly Hills Cop"],
},
{
"cat":"Eddie Murphy",
"ques":"What stand up comic played Maurice, Akeem's co-worker in Coming To America?",
"answ":"LOUIE ANDERSON",
"answ3":"LOUI ANDERSON",
"answ2":"Louie Anderson.",
"option":["Louie Anderson", "Don Rickles", "George Carlin", "Bob Newhart"],
},
{
"cat":"Eddie Murphy",
"ques":"In Coming to America, Daryll is living off his father's invention of a hair product. What is the name of that product?",
"answ":"SOUL GLO",
"answ3":"SOUL GLOW",
"answ2":"Soul Glo.",
"option":["Soul Glo", "Zamunda Shampoo", "Golden Glow", "Jenkers"],
},
{
"cat":"Eddie Murphy",
"ques":"Who directed Eddie Murphy in Norbit?",
"answ":"BRIAN ROBBINS",
"answ3":"BRYAN ROBBINS",
"answ2":"Brian Robbins.",
"option":["Brian Robbins", "Bill Condon", "Steve Carr", "Ted Demme"],
},
{
"cat":"Eddie Murphy",
"ques":"Who directed Bowfinger?",
"answ":"FRANK OZ",
"answ2":"Frank Oz.",
"option":["Frank Oz", "Betty Thomas", "Brian Robbins", "Thomas Carter"],
},
{
"cat":"Eddie Murphy",
"ques":"Who starred as Jack Cates alongside Eddie Murphy in 48 Hrs?",
"answ":"NICK NOLTE",
"answ2":"Nick Nolte.",
"option":["Nick Nolte", "Mel Gibson", "Ben Stiller", "Randy Quaid"],
},
{
"cat":"Eddie Murphy",
"ques":"Who played Louis Winthorpe III in Trading Places?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
"option":["Dan Aykroyd", "Jim Belushi", "Charlie Sheen", "Bill Murray"],
},
{
"cat":"Eddie Murphy",
"ques":"What is the name of Randolph Duke's brother in Trading Places?",
"answ":"MORTIMER",
"answ3":"MORTIMER DUKE",
"answ2":"Mortimer.",
"option":["Mortimer", "Henry", "Mycroft", "Clarence"],
},
{
"cat":"Eddie Murphy",
"ques":"In Trading Places, who plays Ophelia the prostitute that agrees to help Winthorpe?",
"answ":"JAMIE LEE CURTIS",
"answ2":"Jamie Lee Curtis.",
"option":["Jamie Lee Curtis", "Halle Berry", "Charlotte Lewis", "Kate Capshaw"],
},
{
"cat":"Eddie Murphy",
"ques":"In Holy Man, Eddie Murphy plays an evangelist who simply goes by what letter?",
"answ":"G",
"answ2":"G.",
"option":["G", "K", "D", "J"],
},
];
r2Q62 = shuffle(r2Q62);