var r2Q63 = [
{
"cat":"Audrey Hepburn",
"ques":"What actor plays Hamilton Bartholomew, a CIA administrator, in Charade?",
"answ":"WALTER MATTHAU",
"answ2":"Walter Matthau.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cary Grant</button><button id=incop2 class=buttons003 onclick=qinc()>James Coburn</button><button id=corop class=buttons003 onclick=qcor()>Walter Matthau</button><button id=incop4 class=buttons003 onclick=qinc()>James Garner</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What 60s film got Audrey Hepburn her last Oscar nomination?",
"answ":"WAIT UNTIL DARK",
"answ2":"Wait Until Dark.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Two for the Road</button><button id=incop2 class=buttons003 onclick=qinc()>How to Steal a Million</button><button id=corop class=buttons003 onclick=qcor()>Wait Until Dark</button><button id=incop4 class=buttons003 onclick=qinc()>My Fair Lady</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Audrey Hepburn's character suffers from what disability in the thriller Wait Until Dark?",
"answ":"BLINDNESS",
"answ3":"SHE'S BLIND",
"answ2":"Blindness.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>She can't walk</button><button id=incop2 class=buttons003 onclick=qinc()>She has one arm</button><button id=corop class=buttons003 onclick=qcor()>Blindness</button><button id=incop4 class=buttons003 onclick=qinc()>Deafness</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Which film in Audrey Hepburn's filmography was the only one to win Best Picture?",
"answ":"MY FAIR LADY",
"answ2":"My Fair Lady.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sabrina</button><button id=incop2 class=buttons003 onclick=qinc()>Charade</button><button id=corop class=buttons003 onclick=qcor()>My Fair Lady</button><button id=incop4 class=buttons003 onclick=qinc()>Always</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What romantic comedy starring Audrey Hepburn and Humphrey Bogart had a 90s remake which starred Harrison Ford?",
"answ":"SABRINA",
"answ2":"Sabrina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charade</button><button id=incop2 class=buttons003 onclick=qinc()>Breakfast at Tiffany's</button><button id=incop3 class=buttons003 onclick=qinc()>Green Mansions</button><button id=corop class=buttons003 onclick=qcor()>Sabrina</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What song does Audrey Hepburn sing in Breakfast at Tiffany's?",
"answ":"MOON RIVER",
"answ2":"Moon River.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>On How to Be Lovely</button><button id=corop class=buttons003 onclick=qcor()>Moon River</button><button id=incop3 class=buttons003 onclick=qinc()>I Could Have Danced All Night</button><button id=incop4 class=buttons003 onclick=qinc()>He Loves and She Loves</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What is the name of the 1963 romantic mystery starring Cary Grant and Audrey Hepburn?",
"answ":"CHARADE",
"answ2":"Charade.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>That Touch of Mink</button><button id=incop2 class=buttons003 onclick=qinc()>The Grass Is Greener</button><button id=corop class=buttons003 onclick=qcor()>Charade</button><button id=incop4 class=buttons003 onclick=qinc()>Father Goose</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In How To Steal A Million, what type of object is Audrey Hepburn's character attempting to steal, which is worth a million dollars?",
"answ":"STATUE",
"answ3":"VENUE STATUE",
"answ2":"Statue.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Painting</button><button id=incop2 class=buttons003 onclick=qinc()>Diamond</button><button id=corop class=buttons003 onclick=qcor()>Statue</button><button id=incop4 class=buttons003 onclick=qinc()>Historical Document</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In director Billy Wilder's Love In The Afternoon, what musical instrument did Audrey Hepburn play?",
"answ":"CELLO",
"answ2":"Cello.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Saxophone</button><button id=incop2 class=buttons003 onclick=qinc()>Violin</button><button id=corop class=buttons003 onclick=qcor()>Cello</button><button id=incop4 class=buttons003 onclick=qinc()>Piano</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What actor stars as Pierre Bezukhov opposite Audrey in War and Peace?",
"answ":"HENRY FONDA",
"answ2":"Henry Fonda.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cary Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Kirk Douglas</button><button id=corop class=buttons003 onclick=qcor()>Henry Fonda</button><button id=incop4 class=buttons003 onclick=qinc()>James Stewart</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Which 1980s film tells the story of three private detectives investigating two beautiful women for infidelity?",
"answ":"THEY ALL LAUGHED",
"answ2":"They All Laughed.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Always</button><button id=incop2 class=buttons003 onclick=qinc()>Bloodline</button><button id=corop class=buttons003 onclick=qcor()>They All Laughed</button><button id=incop4 class=buttons003 onclick=qinc()>Wait Until Dark</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In which Audrey Hepburn film does her character attend Le Cordon Bleu in Paris?",
"answ":"SABRINA",
"answ2":"Sabrina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Roman Holiday</button><button id=incop2 class=buttons003 onclick=qinc()>Monte Carlo Baby</button><button id=corop class=buttons003 onclick=qcor()>Sabrina</button><button id=incop4 class=buttons003 onclick=qinc()>Love in the Afternoon</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Including her win, Audrey Hepburn received how many total Oscar nominations all in the category of Best Actress?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop4 class=buttons003 onclick=qinc()>7</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In Funny Face, Audrey Hepburn's character works at what type of establishment, before a fashion photographer discovers her?",
"answ":"BOOK STORE",
"answ3":"BOOK SHOP",
"answ2":"Book store.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Restaurant</button><button id=incop2 class=buttons003 onclick=qinc()>Grocery store</button><button id=corop class=buttons003 onclick=qcor()>Book store</button><button id=incop4 class=buttons003 onclick=qinc()>Bakery</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Composer John Williams, credited under the name Johnny Williams, did the music for what 1966 Audrey Hepburn film?",
"answ":"HOW TO STEAL A MILLION",
"answ2":"How to Steal a Million.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wait Until Dark</button><button id=incop2 class=buttons003 onclick=qinc()>Paris When it Sizzles</button><button id=corop class=buttons003 onclick=qcor()>How to Steal a Million</button><button id=incop4 class=buttons003 onclick=qinc()>Two for the Road</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What actor stars alongside Audrey Hepburn in the 1957 romantic musical Funny Face?",
"answ":"FRED ASTAIRE",
"answ2":"Fred Astaire.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anthony Perkins</button><button id=incop2 class=buttons003 onclick=qinc()>Peter Finch</button><button id=corop class=buttons003 onclick=qcor()>Fred Astaire</button><button id=incop4 class=buttons003 onclick=qinc()>George Peppard</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Which James Bond actor plays Robin Hood opposite Audrey Hepburn's Maid Marian in 1976's Robin and Marian?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>George Lazenby</button><button id=incop2 class=buttons003 onclick=qinc()>Roger Moore</button><button id=corop class=buttons003 onclick=qcor()>Sean Connery</button><button id=incop4 class=buttons003 onclick=qinc()>David Niven</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Audrey Hepburn is given the religious name of Sister Luke in this 1959 Fred Zinnemann film.",
"answ":"THE NUN'S STORY",
"answ3":"NUN'S STORY",
"answ2":"The Nun's Story.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Nun's Story</button><button id=incop2 class=buttons003 onclick=qinc()>Roger Moore</button><button id=incop3 class=buttons003 onclick=qinc()>Sean Connery</button><button id=incop4 class=buttons003 onclick=qinc()>David Niven</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Who directed Audrey Hepburn in Love in the Afternoon?",
"answ":"BILLY WILDER",
"answ2":"Billy Wilder.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Billy Wilder</button><button id=incop2 class=buttons003 onclick=qinc()>William Wyler</button><button id=incop3 class=buttons003 onclick=qinc()>Stanley Donen</button><button id=incop4 class=buttons003 onclick=qinc()>Terence Young</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In which movie does Audrey Hepburn portray a schoolteacher accused of lesbianism?",
"answ":"THE CHILDREN'S HOUR",
"answ3":"CHILDREN'S HOUR",
"answ2":"The Children's Hour.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Children's Hour</button><button id=incop2 class=buttons003 onclick=qinc()>Secret People</button><button id=incop3 class=buttons003 onclick=qinc()>Love in the Afternoon</button><button id=incop4 class=buttons003 onclick=qinc()>My Fair Lady</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In How to Steal a Million, what actor plays Audrey Hepburn's love interest?",
"answ":"PETER O'TOOLE",
"answ2":"Peter O'Toole.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Peter O'Toole</button><button id=incop2 class=buttons003 onclick=qinc()>Gregory Peck</button><button id=incop3 class=buttons003 onclick=qinc()>Cary Grant</button><button id=incop4 class=buttons003 onclick=qinc()>Sean Connery</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"In The Nun's Story, while Audrey Hepburn's character is ill, someone gives her a pet what?",
"answ":"MONKEY",
"answ2":"Monkey.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Monkey</button><button id=incop2 class=buttons003 onclick=qinc()>Ferret</button><button id=incop3 class=buttons003 onclick=qinc()>Cat</button><button id=incop4 class=buttons003 onclick=qinc()>Parrot</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"You'll find the characters Professor Henry Higgins, Alfred P. Doolittle and Colonel Hugh Pickering in what Hepburn film?",
"answ":"MY FAIR LADY",
"answ2":"My Fair Lady.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sabrina</button><button id=incop2 class=buttons003 onclick=qinc()>Roman Holiday</button><button id=incop3 class=buttons003 onclick=qinc()>Love in the Afternoon</button><button id=corop class=buttons003 onclick=qcor()>My Fair Lady</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Which Oscar nominee co-stars with Audrey in the film Two for the Road as Mark Wallace?",
"answ":"ALBERT FINNEY",
"answ2":"Albert Finney.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alec Guinness</button><button id=incop2 class=buttons003 onclick=qinc()>Rex Harrison</button><button id=incop3 class=buttons003 onclick=qinc()>Henry Fonda</button><button id=corop class=buttons003 onclick=qcor()>Albert Finney</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Audrey Hepburn starred in what 1956 epic-war film based on a famous Russian novel?",
"answ":"WAR AND PEACE",
"answ2":"War and Peace.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Unforgiven</button><button id=incop2 class=buttons003 onclick=qinc()>Bloodline</button><button id=incop3 class=buttons003 onclick=qinc()>Roman Holiday</button><button id=corop class=buttons003 onclick=qcor()>War and Peace</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"The song 'Moon River' was written for what Audrey Hepburn movie?",
"answ":"BREAKFAST AT TIFFANY'S",
"answ2":"Breakfast at Tiffany's.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Breakfast at Tiffany's</button><button id=incop2 class=buttons003 onclick=qinc()>The Unforgiven</button><button id=incop3 class=buttons003 onclick=qinc()>My Fair Lady</button><button id=incop4 class=buttons003 onclick=qinc()>Wait Until Dark</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"For what film did actress Audrey Hepburn win her one and only Academy Award for acting?",
"answ":"ROMAN HOLIDAY",
"answ2":"Roman Holiday.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sabrina</button><button id=incop2 class=buttons003 onclick=qinc()>My Fair Lady</button><button id=incop3 class=buttons003 onclick=qinc()>Breakfast at Tiffany's</button><button id=corop class=buttons003 onclick=qcor()>Roman Holiday</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Audrey Hepburn's final appearance came in what Steven Spielberg film?",
"answ":"ALWAYS",
"answ2":"Always.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Sugarland Express</button><button id=incop2 class=buttons003 onclick=qinc()>1941</button><button id=incop3 class=buttons003 onclick=qinc()>The Color Purple</button><button id=corop class=buttons003 onclick=qcor()>Always</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"Who plays Robin Hood opposite Audrey Hepburn's Maid Marian in the film Robian and Marian?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Arkin</button><button id=incop2 class=buttons003 onclick=qinc()>Albert Finney</button><button id=incop3 class=buttons003 onclick=qinc()>James Mason</button><button id=corop class=buttons003 onclick=qcor()>Sean Connery</button><br/>",
},
{
"cat":"Audrey Hepburn",
"ques":"What actor stars opposite Audrey Hepburn as Detective John Russo in the 1981 rom-com They All Laughed?",
"answ":"BEN GAZZARA",
"answ3":"BEN GAZARA",
"answ2":"Ben Gazzara.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Arkin</button><button id=incop2 class=buttons003 onclick=qinc()>John Goodman</button><button id=incop3 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><button id=corop class=buttons003 onclick=qcor()>Ben Gazzara</button><br/>",
},
];
r2Q63 = shuffle(r2Q63);