var r2Q64 = [
{
"cat":"Kurt Russell",
"ques":"In what film will you find Bill Paxton and Sam Elliott playing Kurt Russell's brothers?",
"answ":"TOMBSTONE",
"answ2":"Tombstone.",
"option":["Tombstone", "Wyatt Earp", "Soldier", "Backdraft"],
},
{
"cat":"Kurt Russell",
"ques":"What was the name of the boat in 1992's Captain Ron?",
"answ":"THE WANDERER",
"answ3":"WANDERER",
"answ2":"Wanderer.",
"option":["Wanderer", "Surprise", "Venture", "Ocean Runner"],
},
{
"cat":"Kurt Russell",
"ques":"What 80s action star famously died in the first act of Executive Decision?",
"answ":"STEVEN SEAGAL",
"answ2":"Steven Seagal.",
"option":["Steven Seagal", "Jean-Claude Van Damme", "Chuck Norris", "Arnold Schwarzenegger"],
},
{
"cat":"Kurt Russell",
"ques":"Who directed 2005's Sky High?",
"answ":"MIKE MITCHELL",
"answ2":"Mike Mitchell.",
"option":["Mike Mitchell", "James Gunn", "Paul Feig", "Ron Shelton"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a character named Ego in what film?",
"answ":"GUARDIANS OF THE GALAXY VOL 2",
"answ3":"GUARDIANS OF THE GALAXY VOLUME 2",
"answ2":"Guardians of the Galaxy Vol 2.",
"option":["Guardians of the Galaxy Vol 2", "The Best of Times", "Sky High", "Furious 7"],
},
{
"cat":"Kurt Russell",
"ques":"What Egyptian god isn't a god but an alien in 1994's Stargate?",
"answ":"RA",
"answ2":"Ra.",
"option":["Ra", "Horus", "Set", "Anubis"],
},
{
"cat":"Kurt Russell",
"ques":"In what 80s film did Kurt Russell co-star with Meryl Streep?",
"answ":"SILKWOOD",
"answ2":"Silkwood.",
"option":["Silkwood", "The Mean Season", "Postcards From The Edge", "Falling In Love"],
},
{
"cat":"Kurt Russell",
"ques":"Who directed Kurt Russell in Backdraft?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":["Ron Howard", "Tony Scott", "Renny Harlin", "Peter Hyams"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a reporter in what 1985 film directed by Phillip Borsos?",
"answ":"THE MEAN SEASON",
"answ3":"MEAN SEASON",
"answ2":"The Mean Season.",
"option":["The Mean Season", "Under Fire", "Absence of Malice", "The Killing Field"],
},
{
"cat":"Kurt Russell",
"ques":"What famous comedic actor stars opposite Kurt Russell as a character named Jack Dundee in 1986's football comedy The Best of Times?",
"answ":"ROBIN WILLIAMS",
"answ2":"Robin Williams.",
"option":["Robin Williams", "Billy Crystal", "Steve Martin", "Chevy Chase"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell stars as a motorist whose wife is kidnapped in which 90s thriller?",
"answ":"BREAKDOWN",
"answ2":"Breakdown.",
"option":["Breakdown", "Nick of Time", "The Vanishing", "Kalifornia"],
},
{
"cat":"Kurt Russell",
"ques":"Who plays police chief Hauk in the Kurt Russell classic Escape from New York?",
"answ":"LEE VAN CLEEF",
"answ3":"LEE VANCLEEF",
"answ2":"Lee Van Cleef.",
"option":["Lee Van Cleef", "Rutger Hauer", "Donald Pleasence", "Peter Fonda"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a trained killer who is dumped on a barren planet in what 90s sci-fi action film?",
"answ":"SOLDIER",
"answ2":"Soldier.",
"option":["Soldier", "Stargate", "Breakdown", "Executive Decision"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred in this 1984 Jonathan Demme film opposite Goldie Hawn.",
"answ":"SWING SHIFT",
"answ2":"Swing Shift.",
"option":["Swing Shift", "Melvin and Howard", "Married to the Mob", "Something Wild"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred with Mel Gibson and Michelle Pfeiffer in what 1988 crime thriller?",
"answ":"TEQUILA SUNRISE",
"answ2":"Tequila Sunrise.",
"option":["Tequila Sunrise", "The Mean Season", "Silkwood", "The Bounty"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell first appeared in which Fast and the Furious movie?",
"answ":"FURIOUS 7",
"answ3":"FURIOUS AND FURIOUS 7",
"answ2":"Furious 7.",
"option":["Furious 7", "The Fate of the Furious", "Fast & Furious 6", "Fast Five"],
},
{
"cat":"Kurt Russell",
"ques":"What actor plays the character Thomas J. Murphy, opposite Kurt Russell in 3000 Miles to Graceland?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
"option":["Kevin Costner", "Pierce Brosnan", "Michael Rooker", "Gary Busey"],
},
{
"cat":"Kurt Russell",
"ques":"What is Kurt Russell hired to make for Goldie Hawn's yacht in Overboard?",
"answ":"CLOSET",
"answ3":"A CLOSET",
"answ2":"A closet.",
"option":["A closet", "A bathroom", "A kitchen", "A fence"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred as Steve Stronghold in this 2005 family comedy.",
"answ":"SKY HIGH",
"answ2":"Sky High.",
"option":["Sky High", "Dreamer", "Vanilla Sky", "Touchback"],
},
{
"cat":"Kurt Russell",
"ques":"In what Kurt Russell film will you find the quote: 'Give my regards to King Tut'?",
"answ":"STARGATE",
"answ3":"STAR GATE",
"answ2":"Stargate.",
"option":["Stargate", "Big Trouble in Little China", "The Thing", "Tango & Cash"],
},
{
"cat":"Kurt Russell",
"ques":"In what western does Kurt Russell play Sheriff Franklin Hunt?",
"answ":"BONE TOMAHAWK",
"answ2":"Bone Tomahawk.",
"option":["Bone Tomahawk", "Unforgiven", "The Hateful Eight", "Tombstone"],
},
{
"cat":"Kurt Russell",
"ques":"Which sports film finds Kurt Russell coaching the 1980 US men's hockey team?",
"answ":"MIRACLE",
"answ2":"Miracle.",
"option":["Miracle", "Slap Shot", "The Cutting Edge", "White Lightning"],
},
{
"cat":"Kurt Russell",
"ques":"Which actress plays Kurt Russell's wife in the 1992 thriller Unlawful Entry?",
"answ":"MADELEINE STOWE",
"answ2":"Madeleine Stowe.",
"option":["Madeleine Stowe", "Andie MacDowell", "Demi Moore", "Melanie Griffith"],
},
{
"cat":"Kurt Russell",
"ques":"What is the nickname of Jack Burton's rig in Big Trouble in Little China?",
"answ":"PORK CHOP EXPRESS",
"answ3":"THE PORK CHOP EXPRESS",
"answ2":"The Pork Chop Express.",
"option":["The Pork Chop Express", "The Beast", "The Tank", "The Meat Wagon"],
},
{
"cat":"Kurt Russell",
"ques":"What is the full name of Kurt Russell's character in Escape from New York?",
"answ":"SNAKE PLISSKEN",
"answ3":"SNAKE PLISKEN",
"answ2":"Snake Plissken.",
"option":["Snake Plissken", "R.J. MacReady", "Jamie McPheeters", "Dean Proffitt"],
},
{
"cat":"Kurt Russell",
"ques":"What computer game does Kurt Russell's MacReady play in The Thing?",
"answ":"CHESS",
"answ2":"Chess.",
"option":["Chess", "Pac-Man", "Pong", "Zork"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell voices a dog named Copper in what Disney film?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":["The Fox and the Hound", "Bolt", "Zootopia", "The Great Mouse Detective"],
},
{
"cat":"Kurt Russell",
"ques":"The film Backdraft features two firefighter brothers, played by Kurt Russell and ____",
"answ":"WILLIAM BALDWIN",
"answ3":"BILLY BALDWIN",
"answ2":"William Baldwin.",
"option":["William Baldwin", "Michael Keaton", "Kevin Costner", "Ed Harris"],
},
{
"cat":"Kurt Russell",
"ques":"For Kurt Russell and Kevin Costner, how many miles was it to Graceland in their 2001 movie?",
"answ":"3000",
"answ3":"3000 MILES",
"answ2":"3000.",
"option":["3000", "2000", "1000", "4000"],
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays the character John Ruth, also known as The Hangman, in what Tarantino film?",
"answ":"THE HATEFUL EIGHT",
"answ3":"HATEFUL EIGHT",
"answ2":"The Hateful Eight.",
"option":["The Hateful Eight", "Once Upon a Time in Hollywood", "Django Unchained", "Jackie Brown"],
},
];
r2Q64 = shuffle(r2Q64);