var r2Q64 = [
{
"cat":"Kurt Russell",
"ques":"In what film will you find Bill Paxton and Sam Elliott playing Kurt Russell's brothers?",
"answ":"TOMBSTONE",
"answ2":"Tombstone.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wyatt Earp</button><button id=incop2 class=buttons003 onclick=qinc()>Soldier</button><button id=incop3 class=buttons003 onclick=qinc()>Backdraft</button><button id=corop class=buttons003 onclick=qcor()>Tombstone</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What was the name of the boat in 1992's Captain Ron?",
"answ":"THE WANDERER",
"answ3":"WANDERER",
"answ2":"Wanderer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Surprise</button><button id=incop2 class=buttons003 onclick=qinc()>Venture</button><button id=incop3 class=buttons003 onclick=qinc()>Ocean Runner</button><button id=corop class=buttons003 onclick=qcor()>Wanderer</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What 80s action star famously died in the first act of Executive Decision?",
"answ":"STEVEN SEAGAL",
"answ2":"Steven Seagal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jean-Claude Van Damme</button><button id=corop class=buttons003 onclick=qcor()>Steven Seagal</button><button id=incop3 class=buttons003 onclick=qinc()>Chuck Norris</button><button id=incop4 class=buttons003 onclick=qinc()>Arnold Schwarzenegger</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Who directed 2005's Sky High?",
"answ":"MIKE MITCHELL",
"answ2":"Mike Mitchell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Gunn</button><button id=incop2 class=buttons003 onclick=qinc()>Paul Feig</button><button id=incop3 class=buttons003 onclick=qinc()>Ron Shelton</button><button id=corop class=buttons003 onclick=qcor()>Mike Mitchell</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a character named Ego in what film?",
"answ":"GUARDIANS OF THE GALAXY VOL 2",
"answ3":"GUARDIANS OF THE GALAXY VOLUME 2",
"answ2":"Guardians of the Galaxy Vol 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Best of Times</button><button id=incop2 class=buttons003 onclick=qinc()>Sky High</button><button id=incop3 class=buttons003 onclick=qinc()>Furious 7</button><button id=corop class=buttons003 onclick=qcor()>Guardians of the Galaxy Vol 2</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What Egyptian god isn't a god but an alien in 1994's Stargate?",
"answ":"RA",
"answ2":"Ra.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Horus</button><button id=incop2 class=buttons003 onclick=qinc()>Set</button><button id=incop3 class=buttons003 onclick=qinc()>Anubis</button><button id=corop class=buttons003 onclick=qcor()>Ra</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"In what 80s film did Kurt Russell co-star with Meryl Streep?",
"answ":"SILKWOOD",
"answ2":"Silkwood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Mean Season</button><button id=incop2 class=buttons003 onclick=qinc()>Postcards From The Edge</button><button id=incop3 class=buttons003 onclick=qinc()>Falling In Love</button><button id=corop class=buttons003 onclick=qcor()>Silkwood</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Who directed Kurt Russell in Backdraft?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ron Howard</button><button id=incop2 class=buttons003 onclick=qinc()>Tony Scott</button><button id=incop3 class=buttons003 onclick=qinc()>Renny Harlin</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Hyams</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a reporter in what 1985 film directed by Phillip Borsos?",
"answ":"THE MEAN SEASON",
"answ3":"MEAN SEASON",
"answ2":"The Mean Season.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Mean Season</button><button id=incop2 class=buttons003 onclick=qinc()>Under Fire</button><button id=incop3 class=buttons003 onclick=qinc()>Absence of Malice</button><button id=incop4 class=buttons003 onclick=qinc()>The Killing Field</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What famous comedic actor stars opposite Kurt Russell as a character named Jack Dundee in 1986's football comedy The Best of Times?",
"answ":"ROBIN WILLIAMS",
"answ2":"Robin Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Billy Crystal</button><button id=incop2 class=buttons003 onclick=qinc()>Steve Martin</button><button id=incop3 class=buttons003 onclick=qinc()>Chevy Chase</button><button id=corop class=buttons003 onclick=qcor()>Robin Williams</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell stars as a motorist whose wife is kidnapped in which 90s thriller?",
"answ":"BREAKDOWN",
"answ2":"Breakdown.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Breakdown</button><button id=incop2 class=buttons003 onclick=qinc()>Nick of Time</button><button id=incop3 class=buttons003 onclick=qinc()>The Vanishing</button><button id=incop4 class=buttons003 onclick=qinc()>Kalifornia</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Who plays police chief Hauk in the Kurt Russell classic Escape from New York?",
"answ":"LEE VAN CLEEF",
"answ3":"LEE VANCLEEF",
"answ2":"Lee Van Cleef.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rutger Hauer</button><button id=corop class=buttons003 onclick=qcor()>Lee Van Cleef</button><button id=incop3 class=buttons003 onclick=qinc()>Donald Pleasence</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Fonda</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays a trained killer who is dumped on a barren planet in what 90s sci-fi action film?",
"answ":"SOLDIER",
"answ2":"Soldier.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Soldier</button><button id=incop2 class=buttons003 onclick=qinc()>Stargate</button><button id=incop3 class=buttons003 onclick=qinc()>Breakdown</button><button id=incop4 class=buttons003 onclick=qinc()>Executive Decision</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred in this 1984 Jonathan Demme film opposite Goldie Hawn.",
"answ":"SWING SHIFT",
"answ2":"Swing Shift.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Melvin and Howard</button><button id=incop2 class=buttons003 onclick=qinc()>Married to the Mob</button><button id=incop3 class=buttons003 onclick=qinc()>Something Wild</button><button id=corop class=buttons003 onclick=qcor()>Swing Shift</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred with Mel Gibson and Michelle Pfeiffer in what 1988 crime thriller?",
"answ":"TEQUILA SUNRISE",
"answ2":"Tequila Sunrise.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Mean Season</button><button id=incop2 class=buttons003 onclick=qinc()>Silkwood</button><button id=incop3 class=buttons003 onclick=qinc()>The Bounty</button><button id=corop class=buttons003 onclick=qcor()>Tequila Sunrise</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell first appeared in which Fast and the Furious movie?",
"answ":"FURIOUS 7",
"answ3":"FURIOUS AND FURIOUS 7",
"answ2":"Furious 7.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Fate of the Furious</button><button id=incop2 class=buttons003 onclick=qinc()>Fast & Furious 6</button><button id=incop3 class=buttons003 onclick=qinc()>Fast Five</button><button id=corop class=buttons003 onclick=qcor()>Furious 7</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What actor plays the character Thomas J. Murphy, opposite Kurt Russell in 3000 Miles to Graceland?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kevin Costner</button><button id=incop2 class=buttons003 onclick=qinc()>Pierce Brosnan</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Rooker</button><button id=incop4 class=buttons003 onclick=qinc()>Gary Busey</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What is Kurt Russell hired to make for Goldie Hawn's yacht in Overboard?",
"answ":"CLOSET",
"answ3":"A CLOSET",
"answ2":"A closet.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A closet</button><button id=incop2 class=buttons003 onclick=qinc()>A bathroom</button><button id=incop3 class=buttons003 onclick=qinc()>A kitchen</button><button id=incop4 class=buttons003 onclick=qinc()>A fence</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell starred as Steve Stronghold in this 2005 family comedy.",
"answ":"SKY HIGH",
"answ2":"Sky High.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sky High</button><button id=incop2 class=buttons003 onclick=qinc()>Dreamer</button><button id=incop3 class=buttons003 onclick=qinc()>Vanilla Sky</button><button id=incop4 class=buttons003 onclick=qinc()>Touchback</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"In what Kurt Russell film will you find the quote: 'Give my regards to King Tut'?",
"answ":"STARGATE",
"answ3":"STAR GATE",
"answ2":"Stargate.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Big Trouble in Little China</button><button id=corop class=buttons003 onclick=qcor()>Stargate</button><button id=incop3 class=buttons003 onclick=qinc()>The Thing</button><button id=incop4 class=buttons003 onclick=qinc()>Tango & Cash</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"In what western does Kurt Russell play Sheriff Franklin Hunt?",
"answ":"BONE TOMAHAWK",
"answ2":"Bone Tomahawk.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Unforgiven</button><button id=incop2 class=buttons003 onclick=qinc()>The Hateful Eight</button><button id=incop3 class=buttons003 onclick=qinc()>Tombstone</button><button id=corop class=buttons003 onclick=qcor()>Bone Tomahawk</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Which sports film finds Kurt Russell coaching the 1980 US men's hockey team?",
"answ":"MIRACLE",
"answ2":"Miracle.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Miracle</button><button id=incop2 class=buttons003 onclick=qinc()>Slap Shot</button><button id=incop3 class=buttons003 onclick=qinc()>The Cutting Edge</button><button id=incop4 class=buttons003 onclick=qinc()>White Lightning</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Which actress plays Kurt Russell's wife in the 1992 thriller Unlawful Entry?",
"answ":"MADELEINE STOWE",
"answ2":"Madeleine Stowe.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andie MacDowell</button><button id=incop2 class=buttons003 onclick=qinc()>Demi Moore</button><button id=incop3 class=buttons003 onclick=qinc()>Melanie Griffith</button><button id=corop class=buttons003 onclick=qcor()>Madeleine Stowe</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What is the nickname of Jack Burton's rig in Big Trouble in Little China?",
"answ":"PORK CHOP EXPRESS",
"answ3":"THE PORK CHOP EXPRESS",
"answ2":"The Pork Chop Express.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Beast</button><button id=incop2 class=buttons003 onclick=qinc()>The Tank</button><button id=incop3 class=buttons003 onclick=qinc()>The Meat Wagon</button><button id=corop class=buttons003 onclick=qcor()>The Pork Chop Express</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What is the full name of Kurt Russell's character in Escape from New York?",
"answ":"SNAKE PLISSKEN",
"answ3":"SNAKE PLISKEN",
"answ2":"Snake Plissken.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>R.J. MacReady</button><button id=incop2 class=buttons003 onclick=qinc()>Jamie McPheeters</button><button id=incop3 class=buttons003 onclick=qinc()>Dean Proffitt</button><button id=corop class=buttons003 onclick=qcor()>Snake Plissken</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"What computer game does Kurt Russell's MacReady play in The Thing?",
"answ":"CHESS",
"answ2":"Chess.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pac-Man</button><button id=incop2 class=buttons003 onclick=qinc()>Pong</button><button id=incop3 class=buttons003 onclick=qinc()>Zork</button><button id=corop class=buttons003 onclick=qcor()>Chess</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell voices a dog named Copper in what Disney film?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bolt</button><button id=incop2 class=buttons003 onclick=qinc()>Zootopia</button><button id=incop3 class=buttons003 onclick=qinc()>The Great Mouse Detective</button><button id=corop class=buttons003 onclick=qcor()>The Fox and the Hound</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"The film Backdraft features two firefighter brothers, played by Kurt Russell and ____",
"answ":"WILLIAM BALDWIN",
"answ3":"BILLY BALDWIN",
"answ2":"William Baldwin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Costner</button><button id=incop3 class=buttons003 onclick=qinc()>Ed Harris</button><button id=corop class=buttons003 onclick=qcor()>William Baldwin</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"For Kurt Russell and Kevin Costner, how many miles was it to Graceland in their 2001 movie?",
"answ":"3000",
"answ3":"3000 MILES",
"answ2":"3000.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1000</button><button id=incop2 class=buttons003 onclick=qinc()>2000</button><button id=corop class=buttons003 onclick=qcor()>3000</button><button id=incop4 class=buttons003 onclick=qinc()>4000</button><br/>",
},
{
"cat":"Kurt Russell",
"ques":"Kurt Russell plays the character John Ruth, also known as The Hangman, in what Tarantino film?",
"answ":"THE HATEFUL EIGHT",
"answ3":"HATEFUL EIGHT",
"answ2":"The Hateful Eight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Once Upon a Time in Hollywood</button><button id=incop2 class=buttons003 onclick=qinc()>Django Unchained</button><button id=incop3 class=buttons003 onclick=qinc()>Jackie Brown</button><button id=corop class=buttons003 onclick=qcor()>The Hateful Eight</button><br/>",
},
];
r2Q64 = shuffle(r2Q64);