var yaadaptations = [
{
"cat":"YA Adaptations",
"ques":"In The Maze Runner series, who plays the lead, Thomas?",
"answ":"DYLAN O'BRIEN",
"answ2":"Dylan O'Brien.",
},
{
"cat":"YA Adaptations",
"ques":"Saoirse Ronan, Jake Abel and Max Irons star in what 2013 YA sci-fi thriller?",
"answ":"THE HOST",
"answ2":"The Host.",
},
{
"cat":"YA Adaptations",
"ques":"Who played the lead character, Beatrice 'Tris' Prior, in the Divergent films?",
"answ":"SHAILENE WOODLEY",
"answ3":"SHAYLENE WOODLEY",
"answ2":"Shailene Woodley.",
},
{
"cat":"YA Adaptations",
"ques":"Who played Gale Hawthorne in The Hunger Games?",
"answ":"LIAM HEMSWORTH",
"answ2":"Liam Hemsworth.",
},
{
"cat":"YA Adaptations",
"ques":"What was the subtitle of the first film sequel to The Hunger Games?",
"answ":"CATCHING FIRE",
"answ2":"Catching Fire.",
},
{
"cat":"YA Adaptations",
"ques":"Which dystopian YA film feature performances by Amandla Stenberg and Alexander Ludwig?",
"answ":"THE HUNGER GAMES",
"answ3":"HUNGER GAMES",
"answ2":"The Hunger Games.",
},
{
"cat":"YA Adaptations",
"ques":"What is the subtitle title of the second film in the Divergent series released in 2015?",
"answ":"INSURGENT",
"answ2":"Insurgent.",
},
{
"cat":"YA Adaptations",
"ques":"Who played Haymitch Abernathy in The Hunger Games?",
"answ":"WOODY HARRELSON",
"answ2":"Woody Harrelson.",
},
];
var r2Q69 = [
{
"cat":"YA Adaptations",
"ques":"Who played Effie Trinket in The Hunger Games franchise?",
"answ":"ELIZABETH BANKS",
"answ3":"ELISABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Olivia Wilde</button><button id=incop2 class=buttons003 onclick=qinc()>Cate Blanchett</button><button id=corop class=buttons003 onclick=qcor()>Elizabeth Banks</button><button id=incop4 class=buttons003 onclick=qinc()>Hilary Duff</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"How many films are in the Twilight movie series?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=incop2 class=buttons003 onclick=qinc()>4</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Which actor plays the lead of Augustus Waters in The Fault in Our Stars?",
"answ":"ANSEL ELGORT",
"answ2":"Ansel Elgort.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dylan O'Brien</button><button id=incop2 class=buttons003 onclick=qinc()>Nick Robinson</button><button id=incop3 class=buttons003 onclick=qinc()>Logan Miller</button><button id=corop class=buttons003 onclick=qcor()>Ansel Elgort</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"In The Fault in Our Stars, Hazel and Gus travel to which European city?",
"answ":"AMSTERDAM",
"answ2":"Amsterdam.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paris</button><button id=incop2 class=buttons003 onclick=qinc()>Milan</button><button id=incop3 class=buttons003 onclick=qinc()>Berlin</button><button id=corop class=buttons003 onclick=qcor()>Amsterdam</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Who played Lord Asriel, Lyra's strict and mysterious adventurer uncle in The Golden Compass?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugh Jackman</button><button id=incop2 class=buttons003 onclick=qinc()>James McAvoy</button><button id=incop3 class=buttons003 onclick=qinc()>Gerard Butler</button><button id=corop class=buttons003 onclick=qcor()>Daniel Craig</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"The human race is almost extinct as a series of alien attacks cause natural disasters in which 2016 film?",
"answ":"THE FIFTH WAVE",
"answ3":"THE 5H WAVE",
"answ2":"The 5th Wave.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The 5th Wave</button><button id=incop2 class=buttons003 onclick=qinc()>The Maze Runner</button><button id=incop3 class=buttons003 onclick=qinc()>Code 8</button><button id=incop4 class=buttons003 onclick=qinc()>Paradox</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What 2015 YA film featured Giancarlo Esposito?",
"answ":"MAZE RUNNER THE SCORCH TRIALS",
"answ3":"THE SCORCH TRIALS",
"answ2":"Maze Runner: The Scorch Trials.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Allegiant</button><button id=corop class=buttons003 onclick=qcor()>Maze Runner: The Scorch Trials</button><button id=incop3 class=buttons003 onclick=qinc()>The Hunger Games: Mockingjay Part 2</button><button id=incop4 class=buttons003 onclick=qinc()>The Twilight Saga: Breaking Dawn Part 2</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Which dystopian YA film features the Bureau of Genetic Welfare?",
"answ":"THE DIVERGENT SERIES ALLEGIANT",
"answ3":"ALLEGIANT",
"answ2":"Allegiant.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Maze Runner</button><button id=corop class=buttons003 onclick=qcor()>Allegiant</button><button id=incop3 class=buttons003 onclick=qinc()>Insurgent</button><button id=incop4 class=buttons003 onclick=qinc()>Catching Fire</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Who played the vile President Coriolanus Snow  in The Hunger Games?",
"answ":"DONALD SUTHERLAND",
"answ2":"Donald Sutherland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=corop class=buttons003 onclick=qcor()>Donald Sutherland</button><button id=incop3 class=buttons003 onclick=qinc()>Ian McKellen</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Gambon</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Who played show host Caesar Flickerman in The Hunger Games?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mark Strong</button><button id=corop class=buttons003 onclick=qcor()>Stanley Tucci</button><button id=incop3 class=buttons003 onclick=qinc()>Jude Law</button><button id=incop4 class=buttons003 onclick=qinc()>Woody Harrelson</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"In Maze Runner: The Death Cure, whose blood is the secret to curing the flare?",
"answ":"THOMAS",
"answ2":"Thomas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chuck</button><button id=corop class=buttons003 onclick=qcor()>Thomas</button><button id=incop3 class=buttons003 onclick=qinc()>Minho</button><button id=incop4 class=buttons003 onclick=qinc()>Teresa</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Who plays Bella's first friend, Jessica Stanley, in Twilight?",
"answ":"ANNA KENDRICK",
"answ2":"Anna Kendrick.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nikki Reed</button><button id=corop class=buttons003 onclick=qcor()>Anna Kendrick</button><button id=incop3 class=buttons003 onclick=qinc()>Ashley Greene</button><button id=incop4 class=buttons003 onclick=qinc()>Elizabeth Reaser</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What real-life musician plays the character Cinna, who gives Katniss her wardrobe, in The Hunger Games films?",
"answ":"LENNY KRAVITZ",
"answ2":"Lenny Kravitz.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Snoop Dogg</button><button id=incop2 class=buttons003 onclick=qinc()>Usher</button><button id=incop3 class=buttons003 onclick=qinc()>Ludacris</button><button id=corop class=buttons003 onclick=qcor()>Lenny Kravitz</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What is the name of Katniss's sister in The Hunger Games series?",
"answ":"PRIM",
"answ3":"PRIMROSE",
"answ2":"Prim.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Rue</button><button id=incop2 class=buttons003 onclick=qinc()>Johanna</button><button id=corop class=buttons003 onclick=qcor()>Prim</button><button id=incop4 class=buttons003 onclick=qinc()>Effie</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Giancarlo Esposito plays Jorge, one of the leaders of a dangerous band of survivors, in what young adult dystopian franchise of the 2010s?",
"answ":"THE MAZE RUNNER",
"answ3":"MAZE RUNNER",
"answ2":"The Maze Runner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Hunger Games</button><button id=corop class=buttons003 onclick=qcor()>The Maze Runner</button><button id=incop3 class=buttons003 onclick=qinc()>Divergent</button><button id=incop4 class=buttons003 onclick=qinc()>Percy Jackson</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"In the first Maze Runner film, the youths are forced to live in a large area that they call the what?",
"answ":"GLADE",
"answ3":"THE GLADE",
"answ2":"The Glade.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Cube</button><button id=incop2 class=buttons003 onclick=qinc()>The Square</button><button id=corop class=buttons003 onclick=qcor()>The Glade</button><button id=incop4 class=buttons003 onclick=qinc()>The Grave</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What was the full title for the final Mazer Runner film?",
"answ":"THE DEATH CURE",
"answ3":"MAZE RUNNER THE DEATH CURE",
"answ2":"Maze Runner The Death Cure.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Maze Runner Final Lap</button><button id=incop2 class=buttons003 onclick=qinc()>Maze Runner The Death Race</button><button id=corop class=buttons003 onclick=qcor()>Maze Runner The Death Cure</button><button id=incop4 class=buttons003 onclick=qinc()>Maze Runner the End Game</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Kate Winslet played the villain Jeanine Matthews, in this film franchise, based off a series of young adult books.",
"answ":"DIVERGENT",
"answ2":"Divergent.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Golden Compass</button><button id=corop class=buttons003 onclick=qcor()>Divergent</button><button id=incop3 class=buttons003 onclick=qinc()>Percy Jackson</button><button id=incop4 class=buttons003 onclick=qinc()>Hunger Games</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"How many seperate factions are there in the dystopian society for teenagers to choose from in the Divergent series?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>4</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop3 class=buttons003 onclick=qinc()>6</button><button id=incop4 class=buttons003 onclick=qinc()>8</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What is the subtitle of the second Twilight film?",
"answ":"NEW MOON",
"answ2":"New Moon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eclipse</button><button id=corop class=buttons003 onclick=qcor()>New Moon</button><button id=incop3 class=buttons003 onclick=qinc()>Breaking Dawn</button><button id=incop4 class=buttons003 onclick=qinc()>Catching Fire</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"How many total people are picked to compete in the Hunger Games?",
"answ":"24",
"answ2":"24.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>16</button><button id=corop class=buttons003 onclick=qcor()>24</button><button id=incop3 class=buttons003 onclick=qinc()>20</button><button id=incop4 class=buttons003 onclick=qinc()>28</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the organization that was trying to find a cure for the flare in the Maze Runner series?",
"answ":"WICKED",
"answ3":"WCKED",
"answ2":"WCKED/WICKED.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>KSI</button><button id=corop class=buttons003 onclick=qcor()>WCKED</button><button id=incop3 class=buttons003 onclick=qinc()>MAZE</button><button id=incop4 class=buttons003 onclick=qinc()>ACME</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What faction was Tris born into in Divergent?",
"answ":"ABNEGATION",
"answ2":"Abnegation.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Amity</button><button id=corop class=buttons003 onclick=qcor()>Abnegation</button><button id=incop3 class=buttons003 onclick=qinc()>Dauntless</button><button id=incop4 class=buttons003 onclick=qinc()>Candor</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the leader of the runners in The Maze Runner?",
"answ":"MINHO",
"answ3":"MINO",
"answ2":"Minho.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Minho</button><button id=incop2 class=buttons003 onclick=qinc()>Newt</button><button id=incop3 class=buttons003 onclick=qinc()>Chuck</button><button id=incop4 class=buttons003 onclick=qinc()>Gally</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"In Allegiant, who shoots Evelyn before releasing the gas?",
"answ":"PETER",
"answ2":"Peter.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Peter</button><button id=incop2 class=buttons003 onclick=qinc()>Tris</button><button id=incop3 class=buttons003 onclick=qinc()>Caleb</button><button id=incop4 class=buttons003 onclick=qinc()>David</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the resistance group led by Vince in Maze Runner: The Scorch Trials?",
"answ":"THE RIGHT ARM",
"answ3":"RIGHT ARM",
"answ2":"The Right Arm.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Right Arm</button><button id=incop2 class=buttons003 onclick=qinc()>The Black Hand</button><button id=incop3 class=buttons003 onclick=qinc()>The Crooked Leg</button><button id=incop4 class=buttons003 onclick=qinc()>The Red Ear</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Shailene Woodley stars as a teen cancer patient in this 2014 film based on the novel by John Green?",
"answ":"THE FAULT IN OUR STARS",
"answ2":"The Fault in Our Stars.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paper Towns</button><button id=corop class=buttons003 onclick=qcor()>The Fault in Our Stars</button><button id=incop3 class=buttons003 onclick=qinc()>The Spectacular Now</button><button id=incop4 class=buttons003 onclick=qinc()>White Bird in a Blizzard</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Which actress plays the rapidly grown version of Renesmee, Bella and Edward's daughter in Twilight Breaking Dawn Part 2?",
"answ":"MACKENZIE FOY",
"answ2":"Mackenzie Foy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joey King</button><button id=corop class=buttons003 onclick=qcor()>Mackenzie Foy</button><button id=incop3 class=buttons003 onclick=qinc()>Lulu Wilson</button><button id=incop4 class=buttons003 onclick=qinc()>McKenna Grace</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Who directed The Hunger Games installments: Catching Fire, Mockingjay Part 1 and Mockingjay Part 2?",
"answ":"FRANCIS LAWRENCE",
"answ2":"Francis Lawrence.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Robert Schwentke</button><button id=corop class=buttons003 onclick=qcor()>Francis Lawrence</button><button id=incop3 class=buttons003 onclick=qinc()>Neil Burger</button><button id=incop4 class=buttons003 onclick=qinc()>Gary Ross</button><br/>",
},
{
"cat":"YA Adaptations",
"ques":"Amandla Stenberg and Mandy Moore star in what 2018 dystopian film about superpowered teenagers on the run from the government?",
"answ":"THE DARKEST MINDS",
"answ3":"DARKEST MINDS",
"answ2":"The Darkest Minds.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Giver</button><button id=corop class=buttons003 onclick=qcor()>The Darkest Minds</button><button id=incop3 class=buttons003 onclick=qinc()>Maze Runner: The Death Cure</button><button id=incop4 class=buttons003 onclick=qinc()>Divergent</button><br/>",
},
];
r2Q69 = shuffle(r2Q69);
yaadaptations = shuffle(yaadaptations)