var r2Q69 = [
{
"cat":"YA Adaptations",
"ques":"Who played Effie Trinket in The Hunger Games franchise?",
"answ":"ELIZABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":["Elizabeth Banks", "Olivia Wilde", "Cate Blanchett", "Hilary Duff"],
},
{
"cat":"YA Adaptations",
"ques":"In how many installments of the Hunger Games franchise does Lenny Kravitz feature as Cinna?",
"answ":"2",
"answ2":"2 (The Hunger Games, Catching Fire).",
"option":["2", "3", "1", "4"],
},
{
"cat":"YA Adaptations",
"ques":"In The Maze Runner, which of the boys attacked Thomas, and appears to remember things about Thomas?",
"answ2":"Ben.",
"answ":"BEN",
"option":["Ben","Alby","Minho","Chuck"],
},
{
"cat":"YA Adaptations",
"ques":"The Twilight series of movies are based on books by which author?",
"answ2":"Stephenie Meyer.",
"answ":"STEPHENIE MEYER",
"option":["Stephenie Meyer","Richelle Mead","Charlaine Harris","Suzanne Collins"],
},
{
"cat":"YA Adaptations",
"ques":"In the The Hunger Games series which actress played the part of Primrose Everdeen?",
"answ":"WILLOW SHIELDS",
"answ2":"Willow Shields.",
"option":["Willow Shields", "Jennifer Lawrence", "Amandla Stenberg", "Jenna Ortega"],
},
{
"cat":"YA Adaptations",
"ques":"Who directed Mortal Engines?",
"answ":"CHRISTIAN RIVERS",
"answ2":"Christian Rivers.",
"option":["Christian Rivers", "Joseph Kosinski", "Neil Burger", "Robert Rodriguez"],
},
{
"cat":"YA Adaptations",
"ques":"Which Star Wars actor plays the character Ethan Wate in 2013's Beautiful Creatures?",
"answ":"ALDEN EHRENREICH",
"answ2":"Alden Ehrenreich.",
"option":["Alden Ehrenreich", "Donald Glover", "John Boyega", "Oscar Isaac"],
},
{
"cat":"YA Adaptations",
"ques":"How many films have been theatrically released in The Maze Runner franchise?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "4", "5"],
},
{
"cat":"YA Adaptations",
"ques":"What young adult film has the tagline: 'He's done keeping his story straight'?",
"answ":"LOVE SIMON",
"answ2":"Love Simon.",
"option":["Love Simon", "Call Me By Your Name", "The Perks of Being a Wallflower", "Before I Fall"],
},
{
"cat":"YA Adaptations",
"ques":"Which actor stars as Daniel/John Smith/Number Four in the 2011 film I Am Number Four?",
"answ":"ALEX PETTYFER",
"answ2":"Alex Pettyfer.",
"option":["Alex Pettyfer", "Logan Lerman", "Harry Styles", "Freddie Highmore"],
},
{
"cat":"YA Adaptations",
"ques":"Zoey Deutsch stars as Samantha Kingston, a young woman that keeps waking up on Cupid's Day in which 2017 film?",
"answ":"BEFORE I FALL",
"answ2":"Before I Fall.",
"option":["Before I Fall", "Fallen", "Everything, Everything", "November Criminals"],
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the small parasitic aliens that travel to other planets inserting themselves into a host body in the 2013 film The Host?",
"answ":"SOULS",
"answ2":"Souls.",
"option":["Souls", "Spirits", "Hosts", "Bodies"],
},
{
"cat":"YA Adaptations",
"ques":"Which 2015 YA film features an Erudite leader named Jeanine and her mind-controlled Dauntless soldiers?",
"answ":"INSURGENT",
"answ2":"Insurgent.",
"option":["Insurgent", "Divergent", "The Maze Runner", "Catching Fire"],
},
{
"cat":"YA Adaptations",
"ques":"Rose Hathaway, the lead for the 2014 film Vampire Academy is a 17-year-old Dhampir, which is half vampire and half what?",
"answ":"HUMAN",
"answ2":"Human.",
"option":["Human", "Demon", "Dragon", "Werewolf"],
},
{
"cat":"YA Adaptations",
"ques":"Philip Seymour Hoffman appears in what 2010s YA franchise?",
"answ":"THE HUNGER GAMES",
"answ3":"HUNGER GAMES",
"answ2":"The Hunger Games.",
"option":["The Hunger Games", "The Maze Runner", "Divergent", "Twilight"],
},
{
"cat":"YA Adaptations",
"ques":"You'll find the MEDUSA, a quantum energy-based super weapon that instantly destroys cities in what 2010s YA movie?",
"answ":"MORTAL ENGINES",
"answ2":"Mortal Engines.",
"option":["Mortal Engines", "The Giver", "The Darkest Minds", "The Mortal Instruments: City of Bones"],
},
{
"cat":"YA Adaptations",
"ques":"In Twilight: Breaking Dawn Part 1, in what month do Bella and Edward get married?",
"answ":"AUGUST",
"answ2":"August.",
"option":["August", "September", "May", "January"],
},
{
"cat":"YA Adaptations",
"ques":"In The Maze Runner series, who plays the lead, Thomas?",
"answ":"DYLAN O'BRIEN",
"answ2":"Dylan O'Brien.",
"option":["Dylan O'Brien", "Nick Robinson", "Josh Hutcherson", "Logan Lerman"],
},
{
"cat":"YA Adaptations",
"ques":"Who directed 2010's Percy Jackson and the Lightning Thief?",
"answ":"CHRIS COLUMBUS",
"answ2":"Chris Columbus.",
"option":["Chris Columbus", "Peter Weir", "Gary Ross", "Francis Lawrence"],
},
{
"cat":"YA Adaptations",
"ques":"Who directed The Twilight Saga: Eclipse?",
"answ":"DAVID SLADE",
"answ2":"David Slade.",
"option":["David Slade", "Catherine Hardwicke", "Neil Burger", "Wes Ball"],
},
{
"cat":"YA Adaptations",
"ques":"Who stars as Annabeth Chase, Percy's love interest in Percy Jackson and the Lightning Thief?",
"answ":"ALEXANDRA DADDARIO",
"answ2":"Alexandra Daddario.",
"option":["Alexandra Daddario", "Alice Eve", "Selena Gomez", "Blake Lively"],
},
{
"cat":"YA Adaptations",
"ques":"Which actress starred as the villainous Medusa, who can turn people into stone, in Percy Jackson and the Lightning Thief?",
"answ":"UMA THURMAN",
"answ2":"Uma Thurman.",
"option":["Uma Thurman", "Frances McDormand", "Cate Blanchett", "Jessica Chastain"],
},
{
"cat":"YA Adaptations",
"ques":"Which James Bond actor starred as the centaur Chiron, in Percy Jackson and the Lightning Thief?",
"answ":"PIERCE BROSNAN",
"answ2":"Pierce Brosnan.",
"option":["Pierce Brosnan", "Daniel Craig", "Sean Connery", "Timothy Hutton"],
},
{
"cat":"YA Adaptations",
"ques":"Saoirse Ronan, Jake Abel and Max Irons star in what 2013 YA sci-fi thriller?",
"answ":"THE HOST",
"answ2":"The Host.",
"option":["The Host", "Percy Jackson: Sea of Monsters", "The Mortal Instruments: City of Bones", "The Hunger Games: Catching Fire"],
},
{
"cat":"YA Adaptations",
"ques":"Who played the lead character, Beatrice 'Tris' Prior, in the Divergent films?",
"answ":"SHAILENE WOODLEY",
"answ3":"SHAYLENE WOODLEY",
"answ2":"Shailene Woodley.",
"option":["Shailene Woodley", "Jennifer Lawrence", "Chloë Grace Moretz", "Alexandra Daddario"],
},
{
"cat":"YA Adaptations",
"ques":"Who played Gale Hawthorne in The Hunger Games?",
"answ":"LIAM HEMSWORTH",
"answ2":"Liam Hemsworth.",
"option":["Liam Hemsworth", "Ryan Gosling", "Channing Tatum", "Dylan O'Brien"],
},
{
"cat":"YA Adaptations",
"ques":"What was the subtitle of the first film sequel to The Hunger Games?",
"answ":"CATCHING FIRE",
"answ2":"Catching Fire.",
"option":["Catching Fire", "Mockingjay Part 1", "The Scorch Trials", "The Death Cure"],
},
{
"cat":"YA Adaptations",
"ques":"Which dystopian YA film feature performances by Amandla Stenberg and Alexander Ludwig?",
"answ":"THE HUNGER GAMES",
"answ3":"HUNGER GAMES",
"answ2":"The Hunger Games.",
"option":["The Hunger Games", "Divergent", "The Maze Runner", "The Fifth Wave"],
},
{
"cat":"YA Adaptations",
"ques":"What is the subtitle title of the second film in the Divergent series released in 2015?",
"answ":"INSURGENT",
"answ2":"Insurgent.",
"option":["Insurgent", "The Scorch Trials", "The Death Cure", "Allegiant"],
},
{
"cat":"YA Adaptations",
"ques":"Who played Haymitch Abernathy in The Hunger Games?",
"answ":"WOODY HARRELSON",
"answ2":"Woody Harrelson.",
"option":["Woody Harrelson", "Ewan McGregor", "Daniel Craig", "Ed Harris"],
},
{
"cat":"YA Adaptations",
"ques":"How many films are in the Twilight movie series?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":["5", "4", "3", "6"],
},
{
"cat":"YA Adaptations",
"ques":"Which actor plays the lead of Augustus Waters in The Fault in Our Stars?",
"answ":"ANSEL ELGORT",
"answ2":"Ansel Elgort.",
"option":["Ansel Elgort", "Dylan O'Brien", "Nick Robinson", "Logan Miller"],
},
{
"cat":"YA Adaptations",
"ques":"In The Fault in Our Stars, Hazel and Gus travel to which European city?",
"answ":"AMSTERDAM",
"answ2":"Amsterdam.",
"option":["Amsterdam", "Paris", "Milan", "Berlin"],
},
{
"cat":"YA Adaptations",
"ques":"Who played Lord Asriel, Lyra's strict and mysterious adventurer uncle in The Golden Compass?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
"option":["Daniel Craig", "Hugh Jackman", "James McAvoy", "Gerard Butler"],
},
{
"cat":"YA Adaptations",
"ques":"The human race is almost extinct as a series of alien attacks cause natural disasters in which 2016 film?",
"answ":"THE FIFTH WAVE",
"answ3":"THE 5H WAVE",
"answ2":"The 5th Wave.",
"option":["The 5th Wave", "The Maze Runner", "Code 8", "Paradox"],
},
{
"cat":"YA Adaptations",
"ques":"What 2015 YA film featured Giancarlo Esposito?",
"answ":"MAZE RUNNER THE SCORCH TRIALS",
"answ3":"THE SCORCH TRIALS",
"answ2":"Maze Runner: The Scorch Trials.",
"option":["Maze Runner: The Scorch Trials", "Allegiant", "The Hunger Games: Mockingjay Part 2", "The Twilight Saga: Breaking Dawn Part 2"],
},
{
"cat":"YA Adaptations",
"ques":"Which dystopian YA film features the Bureau of Genetic Welfare?",
"answ":"THE DIVERGENT SERIES ALLEGIANT",
"answ3":"ALLEGIANT",
"answ2":"Allegiant.",
"option":["Allegiant", "The Maze Runner", "Insurgent", "Catching Fire"],
},
{
"cat":"YA Adaptations",
"ques":"Who played the vile President Coriolanus Snow in The Hunger Games?",
"answ":"DONALD SUTHERLAND",
"answ2":"Donald Sutherland.",
"option":["Donald Sutherland", "Christopher Plummer", "Ian McKellen", "Michael Gambon"],
},
{
"cat":"YA Adaptations",
"ques":"Who played show host Caesar Flickerman in The Hunger Games?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":["Stanley Tucci", "Mark Strong", "Jude Law", "Woody Harrelson"],
},
{
"cat":"YA Adaptations",
"ques":"In Maze Runner: The Death Cure, whose blood is the secret to curing the flare?",
"answ":"THOMAS",
"answ2":"Thomas.",
"option":["Thomas", "Chuck", "Minho", "Teresa"],
},
{
"cat":"YA Adaptations",
"ques":"Who plays Bella's first friend, Jessica Stanley, in Twilight?",
"answ":"ANNA KENDRICK",
"answ2":"Anna Kendrick.",
"option":["Anna Kendrick", "Nikki Reed", "Ashley Greene", "Elizabeth Reaser"],
},
{
"cat":"YA Adaptations",
"ques":"What real-life musician plays the character Cinna, who gives Katniss her wardrobe, in The Hunger Games films?",
"answ":"LENNY KRAVITZ",
"answ2":"Lenny Kravitz.",
"option":["Lenny Kravitz", "Snoop Dogg", "Usher", "Ludacris"],
},
{
"cat":"YA Adaptations",
"ques":"What is the name of Katniss's sister in The Hunger Games series?",
"answ":"PRIM",
"answ3":"PRIMROSE",
"answ2":"Prim.",
"option":["Prim", "Rue", "Johanna", "Effie"],
},
{
"cat":"YA Adaptations",
"ques":"Giancarlo Esposito plays Jorge, one of the leaders of a dangerous band of survivors, in what young adult dystopian franchise of the 2010s?",
"answ":"THE MAZE RUNNER",
"answ3":"MAZE RUNNER",
"answ2":"The Maze Runner.",
"option":["The Maze Runner", "The Hunger Games", "Divergent", "Percy Jackson"],
},
{
"cat":"YA Adaptations",
"ques":"In the first Maze Runner film, the youths are forced to live in a large area that they call the what?",
"answ":"GLADE",
"answ3":"THE GLADE",
"answ2":"The Glade.",
"option":["The Glade", "The Cube", "The Square", "The Grave"],
},
{
"cat":"YA Adaptations",
"ques":"What was the full title for the final Mazer Runner film?",
"answ":"THE DEATH CURE",
"answ3":"MAZE RUNNER THE DEATH CURE",
"answ2":"Maze Runner: The Death Cure.",
"option":["Maze Runner: The Death Cure", "Maze Runner: Final Lap", "Maze Runner: The Death Race", "Maze Runner: the End Game"],
},
{
"cat":"YA Adaptations",
"ques":"Kate Winslet played the villain Jeanine Matthews, in this film franchise, based off a series of young adult books.",
"answ":"DIVERGENT",
"answ2":"Divergent.",
"option":["Divergent", "Golden Compass", "Percy Jackson", "Hunger Games"],
},
{
"cat":"YA Adaptations",
"ques":"How many seperate factions are there in the dystopian society for teenagers to choose from in the Divergent series?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
"option":["5", "4", "6", "8"],
},
{
"cat":"YA Adaptations",
"ques":"What is the subtitle of the second Twilight film?",
"answ":"NEW MOON",
"answ2":"New Moon.",
"option":["New Moon", "Eclipse", "Breaking Dawn", "Catching Fire"],
},
{
"cat":"YA Adaptations",
"ques":"How many total people are picked to compete in the Hunger Games?",
"answ":"24",
"answ2":"24.",
"option":["24", "16", "20", "28"],
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the organization that was trying to find a cure for the flare in the Maze Runner series?",
"answ":"WICKED",
"answ3":"WCKED",
"answ2":"WCKED/WICKED.",
"option":["WCKED", "KSI", "MAZE", "ACME"],
},
{
"cat":"YA Adaptations",
"ques":"What faction was Tris born into in Divergent?",
"answ":"ABNEGATION",
"answ2":"Abnegation.",
"option":["Abnegation", "Amity", "Dauntless", "Candor"],
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the leader of the runners in The Maze Runner?",
"answ":"MINHO",
"answ3":"MINO",
"answ2":"Minho.",
"option":["Minho", "Newt", "Chuck", "Gally"],
},
{
"cat":"YA Adaptations",
"ques":"In Allegiant, who shoots Evelyn before releasing the gas?",
"answ":"PETER",
"answ2":"Peter.",
"option":["Peter", "Tris", "Caleb", "David"],
},
{
"cat":"YA Adaptations",
"ques":"What is the name of the resistance group led by Vince in Maze Runner: The Scorch Trials?",
"answ":"THE RIGHT ARM",
"answ3":"RIGHT ARM",
"answ2":"The Right Arm.",
"option":["The Right Arm", "The Black Hand", "The Crooked Leg", "The Red Ear"],
},
{
"cat":"YA Adaptations",
"ques":"Shailene Woodley stars as a teen cancer patient in this 2014 film based on the novel by John Green?",
"answ":"THE FAULT IN OUR STARS",
"answ3":"FAULT IN OUR STARS",
"answ2":"The Fault in Our Stars.",
"option":["The Fault in Our Stars", "Paper Towns", "The Spectacular Now", "White Bird in a Blizzard"],
},
{
"cat":"YA Adaptations",
"ques":"Which actress plays the rapidly grown version of Renesmee, Bella and Edward's daughter in Twilight Breaking Dawn Part 2?",
"answ":"MACKENZIE FOY",
"answ2":"Mackenzie Foy.",
"option":["Mackenzie Foy", "Joey King", "Lulu Wilson", "McKenna Grace"],
},
{
"cat":"YA Adaptations",
"ques":"Who directed The Hunger Games installments: Catching Fire, Mockingjay Part 1 and Mockingjay Part 2?",
"answ":"FRANCIS LAWRENCE",
"answ2":"Francis Lawrence.",
"option":["Francis Lawrence", "Robert Schwentke", "Neil Burger", "Gary Ross"],
},
{
"cat":"YA Adaptations",
"ques":"Amandla Stenberg and Mandy Moore star in what 2018 dystopian film about superpowered teenagers on the run from the government?",
"answ":"THE DARKEST MINDS",
"answ3":"DARKEST MINDS",
"answ2":"The Darkest Minds.",
"option":["The Darkest Minds", "The Giver", "Maze Runner: The Death Cure", "Divergent"],
},
{
"cat":"YA Adaptations",
"ques":"The actors Peter Facinelli, Elizabeth Reaser and Michael Sheen appear in which YA franchise?",
"answ":"TWILIGHT",
"answ2":"Twilight.",
"option":["Twilight", "Divergent", "The Maze Runner", "The Hunger Games"],
},
{
"cat":"YA Adaptations",
"ques":"Which Hunger Game film begins with Katniss, Beetee and Finnick Odair being taken to a below-ground district named District 13 that has been spearheading the rebellion?",
"answ":"MOCKINGJAY PART 1",
"answ3":"THE HUNGER GAMES MOCKINGJAY PART 1",
"answ2":"The Hunger Games: Mockingjay Part 1.",
"option":["The Hunger Games: Mockingjay Part 1", "The Hunger Games: Mockingjay Part 2", "The Hunger Games: Catching Fire", "The Hunger Games"],
},
{
"cat":"YA Adaptations",
"ques":"In 1983's The Outsiders, what term do the two gangs use to refer to the big, planned fight that they get into with each other?",
"answ":"RUMBLE",
"answ2":"Rumble.",
"option":["Rumble", "Shakedown", "Thrash", "Tussle"],
},
{
"cat":"YA Adaptations",
"ques":"How many films were released theatrically in the Divergent series?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "4", "2", "5"],
},
{
"cat":"YA Adaptations",
"ques":"What 2019 film stars Yara Shahidi as a teenager who falls in love while facing deportation?",
"answ":"THE SUN IS ALSO A STAR",
"answ2":"The Sun Is Also A Star.",
"option":["The Sun Is Also A Star", "Five Feet Apart", "The Fault in Our Stars", "Paper Towns"],
},
{
"cat":"YA Adaptations",
"ques":"Haley Lu Richardson and Cole Sprouse star together in what recent YA film?",
"answ":"FIVE FEET APART",
"answ2":"Five Feet Apart.",
"option":["Five Feet Apart", "The Darkest Minds", "After We Fell", "One Of Us Is Lying"],
},
];
r2Q69 = shuffle(r2Q69);