var r2Q70 = [
{
"cat":"DreamWorks Animation",
"ques":"Who voices the Easter Bunny in Rise of the Guardians?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ryan Reynolds</button><button id=incop2 class=buttons003 onclick=qinc()>Chris Hemsworth</button><button id=incop3 class=buttons003 onclick=qinc()>Zach Braff</button><button id=corop class=buttons003 onclick=qcor()>Hugh Jackman</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Chicken Run, what movie star provides the voice of the rooster Rocky?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=incop2 class=buttons003 onclick=qinc()>Anthony Hopkins</button><button id=incop3 class=buttons003 onclick=qinc()>Bruce Willis</button><button id=corop class=buttons003 onclick=qcor()>Mel Gibson</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who directed Shrek Forever After?",
"answ":"MIKE MITCHELL",
"answ2":"Mike Mitchell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Miller</button><button id=incop2 class=buttons003 onclick=qinc()>David Soren</button><button id=incop3 class=buttons003 onclick=qinc()>Tom McGrath</button><button id=corop class=buttons003 onclick=qcor()>Mike Mitchell</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Chris Sanders and Dean DeBlois directed what 2010 DreamWorks film?",
"answ":"HOW TO TRAIN YOUR DRAGON",
"answ2":"How to Train Your Dragon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shrek Forever After</button><button id=incop2 class=buttons003 onclick=qinc()>Kung Fu Panda 2</button><button id=incop3 class=buttons003 onclick=qinc()>Megamind</button><button id=corop class=buttons003 onclick=qcor()>How to Train Your Dragon</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which DreamWorks film features musical performances by Justin Timberlake, Anthony Ramos and Kelly Clarkson?",
"answ":"TROLLS WORLD TOUR",
"answ2":"Trolls World Tour.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Trolls World Tour</button><button id=incop2 class=buttons003 onclick=qinc()>Trolls</button><button id=incop3 class=buttons003 onclick=qinc()>The Croods: A New Age</button><button id=incop4 class=buttons003 onclick=qinc()>Mr. Peabody & Sherman</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What is the subtitle of the 2020 sequel to The Croods?",
"answ":"A NEW AGE",
"answ3":"THE CROODS A NEW AGE",
"answ2":"A New Age.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A New Age</button><button id=incop2 class=buttons003 onclick=qinc()>The Meltdown</button><button id=incop3 class=buttons003 onclick=qinc()>Continental Drift</button><button id=incop4 class=buttons003 onclick=qinc()>Collision Course</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices the hypochondriac reticulated giraffe Melman in the Madagascar franchise?",
"answ":"DAVID SCHWIMMER",
"answ2":"David Schwimmer.",
"option":"<button id=corop class=buttons003 onclick=qcor()>David Schwimmer</button><button id=incop2 class=buttons003 onclick=qinc()>John C. Reilly</button><button id=incop3 class=buttons003 onclick=qinc()>Ben Stiller</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Carell</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Will Ferrell provides the voice of the title character in what 2010s Dreamworks film?",
"answ":"MEGAMIND",
"answ2":"Megamind.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Megamind</button><button id=incop2 class=buttons003 onclick=qinc()>Sinbad: Legend of the Seven Seas</button><button id=incop3 class=buttons003 onclick=qinc()>Kung Fu Panda</button><button id=incop4 class=buttons003 onclick=qinc()>Puss in Boots</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which actor voices Turbo, a garden snail in the film Turbo?",
"answ":"RYAN REYNOLDS",
"answ2":"Ryan Reynolds.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ryan Reynolds</button><button id=incop2 class=buttons003 onclick=qinc()>Zac Efron</button><button id=incop3 class=buttons003 onclick=qinc()>Justin Timberlake</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Helms</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which actor voices Adam Flayman, who is Barry B. Benson's best friend, in Bee Movie?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jack Black</button><button id=corop class=buttons003 onclick=qcor()>Matthew Broderick</button><button id=incop3 class=buttons003 onclick=qinc()>Bradley Cooper</button><button id=incop4 class=buttons003 onclick=qinc()>Jon Favreau</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which DreamWorks film has such characters as B.O.B., Dr. Cockroach, Link and Insectosaurus?",
"answ":"MONSTERS VS ALIENS",
"answ2":"Monsters vs. Aliens.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Trolls</button><button id=corop class=buttons003 onclick=qcor()>Monsters vs. Aliens</button><button id=incop3 class=buttons003 onclick=qinc()>The Croods</button><button id=incop4 class=buttons003 onclick=qinc()>Flushed Away</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Steve Martin and Martin Short have supporting performances in what 90s DreamWorks film?",
"answ":"THE PRINCE OF EGYPT",
"answ3":"PRINCE OF EGYPT",
"answ2":"The Prince of Egypt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sinbad: Legend of the Seven Seas</button><button id=corop class=buttons003 onclick=qcor()>The Prince of Egypt</button><button id=incop3 class=buttons003 onclick=qinc()>Antz</button><button id=incop4 class=buttons003 onclick=qinc()>The Road to El Dorado</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What 2010s DreamWorks film has a main villain named Lord Shen, who uses gunpowder and weapons for nefarious purposes?",
"answ":"KUNG FU PANDA 2",
"answ3":"KUNG FU PANDA II",
"answ2":"Kung Fu Panda 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>How to Train Your Dragon</button><button id=corop class=buttons003 onclick=qcor()>Kung Fu Panda 2</button><button id=incop3 class=buttons003 onclick=qinc()>Shrek Forever After</button><button id=incop4 class=buttons003 onclick=qinc()>Megamind</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Jerome Horwitz Elementary School can be found in which 2010's DreamWorks film?",
"answ":"CAPTAIN UNDERPANTS",
"answ3":"CAPTAIN UNDERPANTS THE FIRST EPIC MOVIE",
"answ2":"Captain Underpants: The First Epic Movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mr. Peabody & Sherman</button><button id=corop class=buttons003 onclick=qcor()>Captain Underpants: The First Epic Movie</button><button id=incop3 class=buttons003 onclick=qinc()>The Boss Baby</button><button id=incop4 class=buttons003 onclick=qinc()>Rise of the Guardians</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What type of animal does Bruce Willis voice in Over the Hedge?",
"answ":"RACCOON",
"answ2":"Raccoon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Squirrel</button><button id=corop class=buttons003 onclick=qcor()>Raccoon</button><button id=incop3 class=buttons003 onclick=qinc()>Fox</button><button id=incop4 class=buttons003 onclick=qinc()>Beaver</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who is Prince Charming's mother in Shrek 2",
"answ":"FAIRY GODMOTHER",
"answ3":"THE FAIRY GODMOTHER",
"answ2":"Fairy Godmother.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Queen Lillian</button><button id=corop class=buttons003 onclick=qcor()>Fairy Godmother</button><button id=incop3 class=buttons003 onclick=qinc()>Maleficent</button><button id=incop4 class=buttons003 onclick=qinc()>Snow White</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Shrek 2, who hires Puss in Boots to kill Shrek?",
"answ":"KING HAROLD",
"answ3":"HAROLD",
"answ2":"King Harold.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Prince Charming</button><button id=corop class=buttons003 onclick=qcor()>King Harold</button><button id=incop3 class=buttons003 onclick=qinc()>Lord Farquaad</button><button id=incop4 class=buttons003 onclick=qinc()>Fairy Godmother</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What type of dragon has two heads in the How to Train Your Dragon series?",
"answ":"ZIPPLEBACK",
"answ2":"Zippleback.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Typhoomerang</button><button id=incop2 class=buttons003 onclick=qinc()>Fireworm</button><button id=incop3 class=buttons003 onclick=qinc()>Hobblegrunt</button><button id=corop class=buttons003 onclick=qcor()>Zippleback</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Captain Underpants, in what type of location do George and Harold write their comics and hang out after school?",
"answ":"TREEHOUSE",
"answ2":"Treehouse.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Basement</button><button id=incop2 class=buttons003 onclick=qinc()>Garage</button><button id=incop3 class=buttons003 onclick=qinc()>Mall</button><button id=corop class=buttons003 onclick=qcor()>Treehouse</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which DreamWorks animation film features Paul Giamatti, Samuel L. Jackson, Michael Pena and Snoop Dogg?",
"answ":"TURBO",
"answ2":"Turbo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shark Tale</button><button id=incop2 class=buttons003 onclick=qinc()>Mr. Peabody and Sherman</button><button id=incop3 class=buttons003 onclick=qinc()>Over the Hedge</button><button id=corop class=buttons003 onclick=qcor()>Turbo</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Bee Movie, what type of shop does Vanessa have?",
"answ":"FLOWER SHOP",
"answ2":"Flower shop.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Trolls World Tour</button><button id=incop2 class=buttons003 onclick=qinc()>Mr. Peabody and Sherman</button><button id=incop3 class=buttons003 onclick=qinc()>Penguins of Madagascar</button><button id=corop class=buttons003 onclick=qcor()>Abominable</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which DreamWorks film features the following locations: Gobi Desert, Mount Everest and Shanghai?",
"answ":"ABOMINABLE",
"answ2":"Abominable.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Trolls World Tour</button><button id=incop2 class=buttons003 onclick=qinc()>Mr. Peabody and Sherman</button><button id=incop3 class=buttons003 onclick=qinc()>Penguins of Madagascar</button><button id=corop class=buttons003 onclick=qcor()>Abominable</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices pampered rodent Roddy in Flushed Away?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=incop2 class=buttons003 onclick=qinc()>Christian Bale</button><button id=incop3 class=buttons003 onclick=qinc()>James McAvoy</button><button id=corop class=buttons003 onclick=qcor()>Hugh Jackman</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"At the end of Rise of the Guardians, who becomes the newest guardian?",
"answ":"JACK FROST",
"answ2":"Jack Frost.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Santa Claus</button><button id=incop2 class=buttons003 onclick=qinc()>Sandman</button><button id=incop3 class=buttons003 onclick=qinc()>Easter Bunny</button><button id=corop class=buttons003 onclick=qcor()>Jack Frost</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which actor is called to the stand during the trial in Bee Movie?",
"answ":"RAY LIOTTA",
"answ2":"Ray Liotta.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kathy Bates</button><button id=incop2 class=buttons003 onclick=qinc()>Oprah Winfrey</button><button id=incop3 class=buttons003 onclick=qinc()>Barry Levinson</button><button id=corop class=buttons003 onclick=qcor()>Ray Liotta</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What is the name of Guy's pet sloth in The Croods?",
"answ":"BELT",
"answ2":"Belt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Barry</button><button id=incop2 class=buttons003 onclick=qinc()>Billy</button><button id=incop3 class=buttons003 onclick=qinc()>Bango</button><button id=corop class=buttons003 onclick=qcor()>Belt</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Bruce Willis provides the voice of a scheming raccoon named RJ in which 2000s film?",
"answ":"OVER THE HEDGE",
"answ2":"Over the Hedge.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Over the Hedge</button><button id=incop2 class=buttons003 onclick=qinc()>Chicken Run</button><button id=incop3 class=buttons003 onclick=qinc()>Open Season</button><button id=incop4 class=buttons003 onclick=qinc()>Flushed Away</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices Don Lino, a shark and leader of a mob consisting of criminally-inclined great white sharks in Shark Tale?",
"answ":"ROBERT DE NIRO",
"answ3":"ROBERT DENIRO",
"answ2":"Robert De Niro.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Robert De Niro</button><button id=incop2 class=buttons003 onclick=qinc()>Danny DeVito</button><button id=incop3 class=buttons003 onclick=qinc()>Al Pacino</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Douglas</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What 2019 film follows three teenagers who must help a Yeti return to his family before others can find him?",
"answ":"ABOMINABLE",
"answ2":"Abominable.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Abominable</button><button id=incop2 class=buttons003 onclick=qinc()>Home</button><button id=incop3 class=buttons003 onclick=qinc()>Smallfoot</button><button id=incop4 class=buttons003 onclick=qinc()>Missing Link</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which late night talk show host provides the voice of Tim's Dad in The Boss Baby?",
"answ":"JIMMY KIMMEL",
"answ2":"Jimmy Kimmel.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jimmy Kimmel</button><button id=incop2 class=buttons003 onclick=qinc()>Stephen Colbert</button><button id=incop3 class=buttons003 onclick=qinc()>Seth Myers</button><button id=incop4 class=buttons003 onclick=qinc()>Jimmy Fallon</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who provides the voice of Queen Lillian in Shrek 2 and Shrek the Third?",
"answ":"JULIE ANDREWS",
"answ2":"Julie Andrews.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Glenn Close</button><button id=corop class=buttons003 onclick=qcor()>Julie Andrews</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=incop4 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voiced Chicken Little in the 2005 film Chicken Little?",
"answ":"ZACH BRAFF",
"answ2":"Zach Braff.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Justin Long</button><button id=corop class=buttons003 onclick=qcor()>Zach Braff</button><button id=incop3 class=buttons003 onclick=qinc()>Jesse Eisenberg</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Zahn</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What is the name of the character voiced by David Schwimmer in the Madagascar series?",
"answ":"MELVIN",
"answ2":"Melvin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Marty</button><button id=incop2 class=buttons003 onclick=qinc()>Alex</button><button id=incop3 class=buttons003 onclick=qinc()>King Julien</button><button id=corop class=buttons003 onclick=qcor()>Melvin</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What action movie star lent his voice to a character in Antz?",
"answ":"SYLVESTER STALLONE",
"answ2":"Sylvester Stallone.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chuck Norris</button><button id=corop class=buttons003 onclick=qcor()>Sylvester Stallone</button><button id=incop3 class=buttons003 onclick=qinc()>Jean-Claude van Damme</button><button id=incop4 class=buttons003 onclick=qinc()>Steven Seagal</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What 1998 movie was the first film released by DreamWorks Animation?",
"answ":"ANTZ",
"answ3":"ANTS",
"answ2":"Antz.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Antz</button><button id=incop2 class=buttons003 onclick=qinc()>The Prince of Egypt</button><button id=incop3 class=buttons003 onclick=qinc()>Sinbad: Legend of the Seven Seas</button><button id=incop4 class=buttons003 onclick=qinc()>Shrek</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Humpty Dumpty appears as an antagonist in what film set in the Shrek universe?",
"answ":"PUSS IN BOOTS",
"answ2":"Puss in Boots.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Puss in Boots</button><button id=incop2 class=buttons003 onclick=qinc()>Shrek Forever After</button><button id=incop3 class=buttons003 onclick=qinc()>Shrek 2</button><button id=incop4 class=buttons003 onclick=qinc()>Shrek the Third</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices The Colonel in Spirit: Stallion of the Cimarron?",
"answ":"JAMES CROMWELL",
"answ2":"James Cromwell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>James Cromwell</button><button id=incop2 class=buttons003 onclick=qinc()>John Goodman</button><button id=incop3 class=buttons003 onclick=qinc()>Robert De Niro</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Douglas</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What is the name of the youngest member of the Penguin squad in Penguins of Madagascar?",
"answ":"PRIVATE",
"answ2":"Private.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Private</button><button id=incop2 class=buttons003 onclick=qinc()>Skipper</button><button id=incop3 class=buttons003 onclick=qinc()>Kowalski</button><button id=incop4 class=buttons003 onclick=qinc()>Rico</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Megamind, What is the name of the superhero voiced by Brad Pitt that Megamind fights?",
"answ":"METRO MAN",
"answ3":"METROMAN",
"answ2":"Metro Man.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Metro Man</button><button id=incop2 class=buttons003 onclick=qinc()>Incredible Man</button><button id=incop3 class=buttons003 onclick=qinc()>Meta Man</button><button id=incop4 class=buttons003 onclick=qinc()>Universal Man</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In The Boss Baby, Francis E. Francis is trying to decrease the world's love for babies by increasing love for what?",
"answ":"PUPPIES",
"answ3":"DOGS",
"answ2":"Puppies.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Puppies</button><button id=incop2 class=buttons003 onclick=qinc()>Cats</button><button id=incop3 class=buttons003 onclick=qinc()>Sheep</button><button id=incop4 class=buttons003 onclick=qinc()>Panda's</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What Oscar was Kung Fu Panda 2 nominated for?",
"answ":"BEST ANIMATED FEATURE",
"answ3":"ANIMATED FEATURE",
"answ2":"Best Animated Feature.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Best Animated Feature</button><button id=incop2 class=buttons003 onclick=qinc()>Best Original Song</button><button id=incop3 class=buttons003 onclick=qinc()>Best Original Score</button><button id=incop4 class=buttons003 onclick=qinc()>Best Sound</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which character tricks Shrek into allowing himself to be erased from existence in Shrek Forever After?",
"answ":"RUMPELSTILTSKIN",
"answ2":"Rumpelstiltskin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rumpelstiltskin</button><button id=incop2 class=buttons003 onclick=qinc()>Donkey</button><button id=incop3 class=buttons003 onclick=qinc()>Prince Charming</button><button id=incop4 class=buttons003 onclick=qinc()>Merlin</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voiced Hiccup's mother in How to Train Your Dragon 2?",
"answ":"CATE BLANCHETT",
"answ3":"CATE BLANCHET",
"answ2":"Cate Blanchett.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Glenn Close</button><button id=corop class=buttons003 onclick=qcor()>Cate Blanchett</button><button id=incop3 class=buttons003 onclick=qinc()>Nicole Kidman</button><button id=incop4 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices Marty the zebra in the Madagascar film franchise?",
"answ":"CHRIS ROCK",
"answ2":"Chris Rock.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jamie Foxx</button><button id=corop class=buttons003 onclick=qcor()>Chris Rock</button><button id=incop3 class=buttons003 onclick=qinc()>Eddie Murphy</button><button id=incop4 class=buttons003 onclick=qinc()>Marlon Wayans</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What is the name of Hiccup's dragon in How to Train Your Dragon?",
"answ":"TOOTHLESS",
"answ2":"Toothless.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gronckle</button><button id=corop class=buttons003 onclick=qcor()>Toothless</button><button id=incop3 class=buttons003 onclick=qinc()>Haggard</button><button id=incop4 class=buttons003 onclick=qinc()>Snotlout</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In which Shrek film does Donkey turn into a horse after drinking some of the potion called 'Happily Ever After'?",
"answ":"SHREK 2",
"answ3":"SHREK II",
"answ2":"Shrek 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shrek</button><button id=corop class=buttons003 onclick=qcor()>Shrek 2</button><button id=incop3 class=buttons003 onclick=qinc()>Shrek the Third</button><button id=incop4 class=buttons003 onclick=qinc()>Shrek Forever After</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"What kind of animal is Gary Oldman's villainous Lord Shen in Kung Fu Panda 2?",
"answ":"PEACOCK",
"answ2":"Peacock.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Goat</button><button id=corop class=buttons003 onclick=qcor()>Peacock</button><button id=incop3 class=buttons003 onclick=qinc()>Snake</button><button id=incop4 class=buttons003 onclick=qinc()>Scorpion</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In what 2010s DreamWorks Animation film will you find the WABAC Machine?",
"answ":"MR PEABODY AND SHERMAN",
"answ2":"Mr. Peabody and Sherman",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Home</button><button id=corop class=buttons003 onclick=qcor()>Mr. Peabody and Sherman</button><button id=incop3 class=buttons003 onclick=qinc()>Megamind</button><button id=incop4 class=buttons003 onclick=qinc()>The Boss Baby</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"In Captain Underpants, what is the profession of Mr. Krupp, a man who is hypnotized into becoming the title hero?",
"answ":"PRINCIPAL",
"answ3":"SCHOOL PRINCIPAL",
"answ2":"Principal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lawyer</button><button id=corop class=buttons003 onclick=qcor()>Principal</button><button id=incop3 class=buttons003 onclick=qinc()>Police officer</button><button id=incop4 class=buttons003 onclick=qinc()>Janitor</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who provides the voice of Li, Po's long lost father in Kung Fu Panda 3?",
"answ":"BRYAN CRANSTON",
"answ2":"Bryan Cranston.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alec Baldwin</button><button id=corop class=buttons003 onclick=qcor()>Bryan Cranston</button><button id=incop3 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Carell</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Amy Poehler voices Snow White and Maya Rudolph voices Rapunzel in which film in the Shrek franchise?",
"answ":"SHREK THE THIRD",
"answ3":"SHREK 3",
"answ2":"Shrek the Third.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shrek</button><button id=incop2 class=buttons003 onclick=qinc()>Shrek 2</button><button id=corop class=buttons003 onclick=qcor()>Shrek the Third</button><button id=incop4 class=buttons003 onclick=qinc()>Shrek Forever After</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Which comedian voices George Beard, one of the two boys behind the creation of Captain Underpants in the film Captain Underpants?",
"answ":"KEVIN HART",
"answ2":"Kevin Hart.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dave Chapelle</button><button id=corop class=buttons003 onclick=qcor()>Kevin Hart</button><button id=incop3 class=buttons003 onclick=qinc()>Adam Sandler</button><button id=incop4 class=buttons003 onclick=qinc()>Chris Rock</button><br/>",
},
{
"cat":"DreamWorks Animation",
"ques":"Who voices Pharaoh Seti, Rameses's father and Moses's adoptive father in The Prince of Egypt?",
"answ":"PATRICK STEWART",
"answ2":"Patrick Stewart.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=corop class=buttons003 onclick=qcor()>Patrick Stewart</button><button id=incop3 class=buttons003 onclick=qinc()>Pierce Brosnan</button><button id=incop4 class=buttons003 onclick=qinc()>Val Kilmer</button><br/>",
},
];
r2Q70 = shuffle(r2Q70);