var r2Q71 = [
{
"cat":"Remakes and Reboots",
"ques":"Which actress played Dre Parker's mother in 2010's The Karate Kid?",
"answ":"TARAJI P HENSON",
"answ2":"Taraji P. Henson.",
"option":["Taraji P. Henson", "Viola Davis", "Octavia Spencer", "Jada Pinkett Smith"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2005 comedy film starring Rene Russo was remade from a movie originally released in 1968 and directed by Melville Shavelson?",
"answ2":"Yours, Mine and Ours.",
"answ":"YOURS MINE AND OURS",
"option":["Yours, Mine and Ours","Adam's Apples","Beauty Shop","Dirty Deeds"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2014 film starring Kevin Hart was remade from a movie originally released in 1986 and directed by Edward Zwick?",
"answ2":"About Last Night.",
"answ":"ABOUT LAST NIGHT",
"option":["About Last Night","Hot Young Bloods","Love on the Cloud","Neighbors"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2005 film starring Drew Barrymore was remade from a movie originally released in 1997 and directed by David Evans?",
"answ2":"Fever Pitch.",
"answ":"FEVER PITCH",
"option":["Fever Pitch","Bewitched","The Chumscrubber","Dark Horse"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1989 comedy film starring Robert De Niro was remade from a movie originally released in 1955 and directed by Michael Curtiz?",
"answ2":"We're No Angels.",
"answ":"WE'RE NO ANGELS",
"option":["We're No Angels","The Burbs","Dream a Little Dream","Identity Crisis"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2006 film starring Billy Bob Thornton was remade from a movie originally released in 1960 and directed by Robert Hamer?",
"answ2":"School for Scoundrels.",
"answ":"SCHOOL FOR SCOUNDRELS",
"option":["School for Scoundrels","The Longest Yard","Man of the House","Mutual Appreciation"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2011 horror film is a remake of a movie originally released in 1982 and directed by John Carpenter?",
"answ2":"The Thing.",
"answ":"THE THING",
"option":["The Thing","Invasion of the Body Snatchers","The Last House on the Left","Monsterz"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2001 horror film starring Tony Shalhoub is a remake of a movie originally released in 1960 and directed by William Castle?",
"answ2":"13 Ghosts.",
"answ":"13 GHOSTS",
"option":["13 Ghosts","Prom Night","Silent House","House of Wax"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1999 horror film starring Liam Neeson is a remake of a movie originally released in 1963 and directed by Robert Wise?",
"answ2":"The Haunting.",
"answ":"THE HAUNTING",
"option":["The Haunting","It's Alive","Curse of the Cannibal Confederates","Don't Be Afraid of the Dark"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2005 supernatural horror film is a remake of a Japanese movie originally released in 2002 and directed by Hideo Nakata?",
"answ2":"Dark Water.",
"answ":"DARK WATER",
"option":["Dark Water","Near Dark","Dawn of the Dead","The Eye"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1996 film starring Sharon Stone is a remake of a movie originally released in 1955 and directed by H.G. Clouzot?",
"answ2":"Diabolique.",
"answ":"DIABOLIQUE",
"option":["Diabolique","Prom Night","The Happiness of the Katakuris","The Hitcher"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1993 film starring John Goodman was remade from a movie originally released in 1950 and directed by George Cukor?",
"answ2":"Born Yesterday.",
"answ":"BORN YESTERDAY",
"option":["Born Yesterday","Airborne","Cool Runnings","Fatal Instinct"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1997 comedy film starring Christina Ricci was remade from a movie originally released in 1965 and directed by Robert Stevenson?",
"answ2":"That Darn Cat.",
"answ":"THAT DARN CAT",
"option":["That Darn Cat","The Associate","The Cable Guy","House Arrest"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2009 musical film was remake of a movie originally released in 1980 and directed by Alan Parker?",
"answ2":"Fame.",
"answ":"FAME",
"option":["Fame","Antichrist","A Single Man","The Last Station"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2004 film was remake of a movie originally released in 1996 and directed by Gilles Mimouni?",
"answ2":"Wicker Park.",
"answ":"WICKER PARK",
"option":["Wicker Park","Wild Side","Nobody Knows","My Summer of Love"],
},
{
"cat":"Remakes & Reboots",
"ques":"In the 2008 remake of the 1951 science-fiction classic The Day the Earth Stood Still, in what city does the flying saucer land?",
"answ":"NEW YORK",
"answ3":"NEW YORK CITY",
"answ2":"New York City.",
"option":["New York City", "Detroit", "Los Angeles", "Philadelphia"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1945 film directed by Leslie Arliss was remade in 1983?",
"answ":"THE WICKED LADY",
"answ2":"The Wicked Lady.",
"option":["The Wicked Lady", "Scarface", "The Outsiders", "WarGames"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1956 Mario Soldati film was remade in 1995 starring Keanu Reeves?",
"answ2":"A Walk in the Clouds.",
"answ":"A WALK IN THE CLOUDS",
"option":["A Walk in the Clouds","East of Eden","I'll Cry Tomorrow","Rebel Without a Cause"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1969 Claude Chabrol film was remade in 2002 starring Richard Gere?",
"answ2":"Unfaithful.",
"answ":"UNFAITHFUL",
"option":["Unfaithful","The Best Day of My Life","City of God","Distant"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1996 film was remade from a movie originally released in 1963 and directed by Jerry Lewis?",
"answ":"THE NUTTY PROFESSOR",
"answ2":"The Nutty Professor.",
"option":["The Nutty Professor", "Crash", "Tin Cup", "Down Periscope"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2008 film was remade from a movie originally released in 1975 and directed by Paul Bartel?",
"answ":"DEATH RACE",
"answ2":"Death Race.",
"option":["Death Race", "Get Smart", "Speed Racer", "Righteous Kill"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1998 film was remade from a movie originally released in 1958 and directed by Irvin S. Yeaworth Jr.?",
"answ":"THE BLOB",
"answ2":"The Blob.",
"option":["The Blob", "Fallen", "What Dreams May Come", "Hope Floats"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which actress plays Heather Fitzgerald alongside Katie Cassidy in 2006's Black Christmas?",
"answ":"MARY ELIZABETH WINSTEAD",
"answ2":"Mary Elizabeth Winstead.",
"option":["Mary Elizabeth Winstead", "Jessica Chastain", "Emma Stone", "Elliot Page"],
},
{
"cat":"Remakes & Reboots",
"ques":"This 1981 film starring Joe Spinell received a 2013 remake starring Elijah Wood.",
"answ":"MANIAC",
"answ2":"Maniac.",
"option":["Maniac", "Wolf", "Locke", "The Great Gatsby"],
},
{
"cat":"Remakes & Reboots",
"ques":"This Buffy the Vampire Slayer actress featured as Melissa Kitt in the 2006 version of Black Christmas.",
"answ":"MICHELLE TRACHTENBERG",
"answ2":"Michelle Trachtenberg.",
"option":["Michelle Trachtenberg", "Sarah Michelle Gellar", "Alyson Hannigan", "Eliza Dushku"],
},
{
"cat":"Remakes & Reboots",
"ques":"Sophia Takal directed this 2019 holiday slasher film, which is the second remake of a 1970s film.",
"answ":"BLACK CHRISTMAS",
"answ2":"Black Christmas.",
"option":["Black Christmas", "Halloween", "Truth or Dare", "Better Watch Out"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1968 film directed by J. Lee Thompson was remade in 1991?",
"answ":"CAPE FEAR",
"answ2":"Cape Fear.",
"option":["Cape Fear", "Sleeping With the Enemy", "Backdraft", "The Fisher King"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1954 film directed by Hitchcock was remade in 1998 and titled A Perfect Murder?",
"answ":"DIAL M FOR MURDER",
"answ2":"Dial M for Murder.",
"option":["Dial M for Murder", "Psycho", "Vertigo", "North by Northwest"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1954 Billy Wilder film was remade in 1995?",
"answ":"SABRINA",
"answ2":"Sabrina.",
"option":["Sabrina", "Dangerous Minds", "It Takes Two", "A Walk in the Clouds"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 2004 Norio Tsuruta film was remade in 2007 starring Sandra Bullock?",
"answ2":"Premonition.",
"answ":"PREMONITION",
"option":["Premonition","Atonement","The Invisible","Reign Over Me"],
},
{
"cat":"Reboots & Remakes",
"ques":"Which 2004 film was remade from a movie originally released in 1962 and directed by John Frankenheimer?",
"answ":"THE MANCHURIAN CANDIDATE",
"answ2":"The Manchurian Candidate.",
"option":["The Manchurian Candidate", "Hidalgo", "Around the World in 80 Days", "The Stepford Wives"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1986 film was remade from a movie originally released in 1953 and directed by William Cameron Menzies?",
"answ":"INVADERS FROM MARS",
"answ2":"Invaders from Mars.",
"option":["Invaders from Mars", "The Fly", "Blue Velvet", "Critters"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which 2006 film was remade from a movie originally released in 2000 and directed by Lee Hyun-seung?",
"answ":"THE LAKE HOUSE",
"answ2":"The Lake House.",
"option":["The Lake House", "Babel", "Lady in the Water", "Deja Vu"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1968 Robert Ellis Miller film was remade in 2001 starring Keanu Reeves?",
"answ2":"Sweet November.",
"answ":"SWEET NOVEMBER",
"option":["Sweet November","In Praise of Love","The Last Castle","Nowhere in Africa"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1975 Bryan Forbes film was remade in 2004 starring Nicole Kidman?",
"answ2":"The Stepford Wives.",
"answ":"THE STEPFORD WIVES",
"option":["The Stepford Wives","The Aviator","Garden State","Innocence"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1947 Norman Z. McLeod film was remade in 2013 starring Ben Stiller?",
"answ2":"The Secret Life of Walter Mitty.",
"answ":"THE SECRET LIFE OF WALTER MITTY",
"option":["The Secret Life of Walter Mitty","Chasing Mavericks","End of Watch","People Like Us"],
},
{
"cat":"Remakes & Reboots",
"ques":"Who directed the 2011 remake of Footloose starring Julianne Hough and Kenny Wormald?",
"answ":"CRAIG BREWER",
"answ2":"Craig Brewer.",
"option":["Craig Brewer", "Bille Woodruff", "Albert Brooks", "Gregory Jacobs"],
},
{
"cat":"Remakes & Reboots",
"ques":"Bruce Greenwood, Paul Rudd and Zach Galifianakis star in what 2010 comedy remake directed by Jay Roach?",
"answ":"DINNER FOR SCHMUCKS",
"answ2":"Dinner for Schmucks.",
"option":["Dinner for Schmucks", "Death at a Funeral", "Due Date", "The Longest Yard"],
},
{
"cat":"Remakes & Reboots",
"ques":"What horror remake was co-written by Frank Darabont and takes place in the small town of Arborville, California?",
"answ":"THE BLOB",
"answ2":"The Blob.",
"option":["The Blob", "The Fly", "The Thing", "Halloween"],
},
{
"cat":"Remakes & Reboots",
"ques":"Who voiced the character of Chucky in the 2019 remake of Child's Play?",
"answ":"MARK HAMILL",
"answ2":"Mark Hamill.",
"option":["Mark Hamill", "Kurt Russell", "Christopher Walken", "Jeff Bridges"],
},
{
"cat":"Remakes & Reboots",
"ques":"Who plays Melina, a member of the Resistance and love interested of Colin Farrell's Quaid, in 2012's Total Recall?",
"answ":"JESSICA BIEL",
"answ2":"Jessica Biel.",
"option":["Jessica Biel", "Scarlett Johansson", "Elizabeth Banks", "Alexandra Daddario"],
},
{
"cat":"Remakes & Reboots",
"ques":"Dan Stevens and Kevin Kline appear in what live action Disney remake?",
"answ":"BEAUTY AND THE BEAST",
"answ2":"Beauty and the Beast.",
"option":["Beauty and the Beast", "Dumbo", "Cinderella", "Aladdin"],
},
{
"cat":"Remakes & Reboots",
"ques":"What 1980s horror remake involves a fictional scientific publication called Particle Magazine?",
"answ":"THE FLY",
"answ2":"The Fly.",
"option":["The Fly", "The Bad Seed", "Cat People", "The Fog"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which actress plays teenager Mattie Ross in the 2010 film True Grit?",
"answ":"HAILEE STEINFELD",
"answ2":"Hailee Steinfeld.",
"option":["Hailee Steinfeld", "Chloe Grace Moretz", "Zoey Deutch", "Selena Gomez"],
},
{
"cat":"Remakes & Reboots",
"ques":"Joel Kinneman and Gary Oldman star in what 2014 remake of an 80s sci-fi action film?",
"answ":"ROBOCOP",
"answ2":"Robocop.",
"option":["Robocop", "Evil Dead", "Red Dawn", "WarGames"],
},
{
"cat":"Remakes & Reboots",
"ques":"Kodi Smit-McPhee stars as Owen, a young boy who befriends a vampire in this horror remake.",
"answ":"LET ME IN",
"answ2":"Let Me In.",
"option":["Let Me In", "Vampire Academy", "30 Days of Night", "Vampire's Kiss"],
},
{
"cat":"Remakes & Reboots",
"ques":"Actor Rodrigo Santoro plays Jesus Christ in this 2010s remake.",
"answ":"BEN HUR",
"answ2":"Ben-Hur.",
"option":["Ben-Hur", "Son of God", "Risen", "The Passion of the Christ"],
},
{
"cat":"Remakes & Reboots",
"ques":"Which actor appeared in the 2010s films Robocop, Kong: Skull Island and The Legend of Tarzan?",
"answ":"SAMUEL L JACKSON",
"answ2":"Samuel L. Jackson.",
"option":["Samuel L. Jackson", "Tom Hiddleston", "Karl Urban", "Djimon Hounsou"],
},
{
"cat":"Remakes and Reboots",
"ques":"Which British actress played Riley Stone in 2019's Black Christmas?",
"answ":"IMOGEN POOTS",
"answ2":"Imogen Poots.",
"option":["Imogen Poots", "Emilia Clarke", "Carey Mulligan", "Felicity Jones"],
},
{
"cat":"Remakes and Reboots",
"ques":"Dominic West, Wayne Knight and Julie Benz all feature in what 2008 comic book reboot?",
"answ":"PUNISHER WAR ZONE",
"answ2":"Punisher: War Zone.",
"option":["Punisher: War Zone", "Superman Returns", "The Spirit", "The Incredible Hulk"],
},
{
"cat":"Remakes and Reboots",
"ques":"Alexandre Aja directed what 2006 remake of a Wes Craven classic in which a family falls victim to mutated cannibals in the desert?",
"answ":"THE HILLS HAVE EYES",
"answ2":"The Hills Have Eyes.",
"option":["The Hills Have Eyes", "The Grudge", "My Bloody Valentine", "The Texas Chainsaw Massacre"],
},
{
"cat":"Remakes and Reboots",
"ques":"Who plays the role of Peter Vincent in 2011's Fright Night?",
"answ":"DAVID TENNANT",
"answ2":"David Tennant.",
"option":["David Tennant", "James Marsden", "Colin Farrell", "Mads Mikkelsen"],
},
{
"cat":"Remakes and Reboots",
"ques":"What 1976 Brian De Palma film was remade in 2013?",
"answ":"CARRIE",
"answ2":"Carrie.",
"option":["Carrie", "The Omen", "Rattlers", "The Tenant"],
},
{
"cat":"Remakes and Reboots",
"ques":"What 1979 horror film directed by Stuart Rosenberg was remade in 2005?",
"answ":"THE AMITYVILLE HORROR",
"answ3":"AMITYVILLE HORROR",
"answ2":"The Amityville Horror.",
"option":["The Amityville Horror", "The Omen", "The Brood", "The Visitor"],
},
{
"cat":"Remakes and Reboots",
"ques":"Johnny Depp and Angelina Jolie star in what 2010 mystery thriller?",
"answ":"THE TOURIST",
"answ2":"The Tourist.",
"option":["The Tourist", "Salt", "Public Enemies", "Changeling"],
},
{
"cat":"Remakes and Reboots",
"ques":"What remake stars Denzel Washington, Chris Pratt, Ethan Hawke and Vincent D'Onofrio?",
"answ":"THE MAGNIFICENT SEVEN",
"answ3":"MAGNIFICENT SEVEN",
"answ2":"The Magnificent Seven.",
"option":["The Magnificent Seven", "The Manchurian Candidate", "The Equalizer", "Inside Man"],
},
{
"cat":"Remakes and Reboots",
"ques":"Which 1972 Soviet sci-fi film was remade in 2002 starring George Clooney and Natascha McElhone?",
"answ":"SOLARIS",
"answ2":"Solaris.",
"option":["Solaris", "Cosmic Voyage", "Ad Astra", "The Time Machine"],
},
{
"cat":"Remakes and Reboots",
"ques":"In Tron: Legacy, which actor plays Kevin Flynn, the former CEO of ENCOM International and creator of the popular arcade game Tron?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
"option":["Jeff Bridges", "Michael Douglas", "Christopher Plummer", "Patrick Stewart"],
},
{
"cat":"Remakes and Reboots",
"ques":"Which actor appeared in the 2000s remakes Planet Of The Apes, The Italian Job and The Departed?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
"option":["Mark Wahlberg", "Matt Damon", "Jason Statham", "Ethan Hawke"],
},
{
"cat":"Remakes and Reboots",
"ques":"What 2000 crime film starred Sylvester Stallone, and was a remake of a 1971 Michael Caine film?",
"answ":"GET CARTER",
"answ2":"Get Carter.",
"option":["Get Carter", "Escape Plan", "Shade", "Driven"],
},
{
"cat":"Remakes and Reboots",
"ques":"What 2014 remake of a 1980s romance movie stars Gabriella Wilde, Alex Pettyfer and Bruce Greenwood?",
"answ":"ENDLESS LOVE",
"answ2":"Endless Love.",
"option":["Endless Love", "Valley Girl", "Working Girl", "Can't Buy Me Love"],
},
{
"cat":"Remakes and Reboots",
"ques":"What is the title of the 2020 animated reboot of the Scooby-Doo franchise?",
"answ":"SCOOB",
"answ2":"Scoob!.",
"option":["Scoob!", "Scooby-Doo Returns", "Scooby-Doo", "Scooby-Doo: Monsters Unleashed"],
},
{
"cat":"Remakes and Reboots",
"ques":"Craig Gillespie directed what 2011 horror remake featuring Imogen Poots and Toni Collette?",
"answ":"FRIGHT NIGHT",
"answ2":"Fright Night.",
"option":["Fright Night", "A Nightmare on Elm Street ", "The Crazies", "Let Me In"],
},
{
"cat":"Remakes and Reboots",
"ques":"A police officer investigates several murders that are seemingly connected to a single house in what 2020 horror reboot?",
"answ":"THE GRUDGE",
"answ2":"The Grudge.",
"option":["The Grudge", "The Wolfman", "I Spit on Your Grave", "Don't Be Afraid of the Dark"],
},
{
"cat":"Remakes and Reboots",
"ques":"Katie Holmes and Guy Pearce star in what 2010 horror film co-written by Guillermo del Toro?",
"answ":"DON'T BE AFRAID OF THE DARK",
"answ2":"Don't Be Afraid of the Dark.",
"option":["Don't Be Afraid of the Dark", "Maniac", "The Town That Dreaded Sundown", "Poltergeist"],
},
{
"cat":"Remakes and Reboots",
"ques":"Which actor played Freddy Krueger in the 2010 remake of A Nightmare on Elm Street?",
"answ":"JACKIE EARLE HALEY",
"answ3":"JACKIE EARL HALEY",
"answ2":"Jackie Earle Haley.",
"option":["Jackie Earle Haley", "Robert Englund", "Clancy Brown", "Jason Ritter"],
},
{
"cat":"Remakes and Reboots",
"ques":"Rooney Mara, Jackie Earle Haley and Clancy Brown appear in what 2010 horror remake?",
"answ":"A NIGHTMARE ON ELM STREET",
"answ2":"A Nightmare on Elm Street.",
"option":["A Nightmare on Elm Street", "Don't Be Afraid of the Dark", "Fright Night", "The Texas Chain Saw Massacre"],
},
{
"cat":"Remakes and Reboots",
"ques":"Which MCU director also directed the 2010 remake of The Wolfman?",
"answ":"JOE JOHNSTON",
"answ2":"Joe Johnston.",
"option":["Joe Johnston", "Jon Watts", "Peyton Reed", "Scott Derrickson"],
},
];
r2Q71 = shuffle(r2Q71);