var r2Q71 = [
{
"cat":"Remakes and Reboots",
"ques":"Which actress played Dre Parker's mother in 2010's The Karate Kid?",
"answ":"TARAJI P HENSON",
"answ2":"Taraji P. Henson.",
},
{
"cat":"Remakes and Reboots",
"ques":"Dominic West, Wayne Knight and Julie Benz all feature in what 2008 comic book reboot?",
"answ":"PUNISHER WAR ZONE",
"answ2":"Punisher: War Zone.",
},
{
"cat":"Remakes & Reboots",
"ques":"Alexandre Aja directed what 2006 remake of a Wes Craven classic in which a family falls victim to mutated cannibals in the desert?",
"answ":"THE HILLS HAVE EYES",
"answ2":"The Hills Have Eyes.",
},
{
"cat":"Remakes and Reboots",
"ques":"Who plays the role of Peter Vincent in 2011's Fright Night?",
"answ":"DAVID TENNANT",
"answ2":"David Tennant.",
},
{
"cat":"Remakes and Reboots",
"ques":"What 1976 Brian De Palma film was remade in 2013?",
"answ":"CARRIE",
"answ2":"Carrie.",
},
{
"cat":"Remakes and Reboots",
"ques":"What 1979 horror film directed by Stuart Rosenberg was remade in 2005?",
"answ":"THE AMITYVILLE HORROR",
"answ3":"AMITYVILLE HORROR",
"answ2":"The Amityville Horror.",
},
{
"cat":"Remakes and Reboots",
"ques":"Johnny Depp and Angelina Jolie star in what 2010 mystery thriller?",
"answ":"THE TOURIST",
"answ2":"The Tourist.",
},
{
"cat":"Remakes and Reboots",
"ques":"What remake stars Denzel Washington, Chris Pratt, Ethan Hawke and Vincent D'Onofrio?",
"answ":"THE MAGNIFICENT SEVEN",
"answ3":"MAGNIFICENT SEVEN",
"answ2":"The Magnificent Seven.",
},
{
"cat":"Remakes & Reboots",
"ques":"Which 1972 Soviet sci-fi film was remade in 2002 starring George Clooney and Natascha McElhone?",
"answ":"SOLARIS",
"answ2":"Solaris.",
},
{
"cat":"Remakes and Reboots",
"ques":"In Tron: Legacy, which actor plays Kevin Flynn, the former CEO of ENCOM International and creator of the popular arcade game Tron?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"Remakes and Reboots",
"ques":"Which actor appeared in the 2000s remakes Planet Of The Apes, The Italian Job and The Departed?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
},
{
"cat":"Remakes and Reboots",
"ques":"What 2000 crime film starred Sylvester Stallone, and was a remake of a 1971 Michael Caine film?",
"answ":"GET CARTER",
"answ2":"Get Carter.",
},
{
"cat":"Remakes and Reboots",
"ques":"What 2014 remake of a 1980s romance movie stars Gabriella Wilde, Alex Pettyfer and Bruce Greenwood?",
"answ":"ENDLESS LOVE",
"answ2":"Endless Love.",
},
{
"cat":"Remakes and Reboots",
"ques":"What is the title of the 2020 animated reboot of the Scooby-Doo franchise?",
"answ":"SCOOB!",
"answ3":"SCOOB",
"answ2":"Scoob!.",
},
{
"cat":"Remakes and Reboots",
"ques":"Craig Gillespie directed what 2011 horror remake featuring Imogen Poots and Toni Collette?",
"answ":"FRIGHT NIGHT",
"answ2":"Fright Night.",
},
{
"cat":"Remakes and Reboots",
"ques":"A police officer investigates several murders that are seemingly connected to a single house in what 2020 horror reboot?",
"answ":"THE GRUDGE",
"answ2":"The Grudge.",
},
{
"cat":"Remakes and Reboots",
"ques":"Katie Holmes and Guy Pearce star in what 2010 horror film co-written by Guillermo del Toro?",
"answ":"DON'T BE AFRAID OF THE DARK",
"answ2":"Don't Be Afraid of the Dark.",
},
{
"cat":"Remakes and Reboots",
"ques":"Which actor played Freddy Krueger in the 2010 remake of A Nightmare on Elm Street?",
"answ":"JACKIE EARLE HALEY",
"answ3":"JACKIE EARL HALEY",
"answ2":"Jackie Earle Haley.",
},
{
"cat":"Remakes and Reboots",
"ques":"Rooney Mara, Jackie Earle Haley and Clancy Brown appear in what 2010 horror remake?",
"answ":"A NIGHTMARE ON ELM STREET",
"answ2":"A Nightmare on Elm Street.",
},
{
"cat":"Remakes and Reboots",
"ques":"Which MCU director also directed the 2010 remake of The Wolfman?",
"answ":"JOE JOHNSTON",
"answ2":"Joe Johnston.",
},
];
r2Q71 = shuffle(r2Q71);