var r2Q73 = [
{
"cat":"Matt & Ben",
"ques":"Ben Affleck, Vin Diesel and Giovanni Ribisi star in what 2000s crime film?",
"answ":"BOILER ROOM",
"answ2":"Boiler Room.",
"option":["Boiler Room", "Reindeer Games", "Changing Lanes", "State of Play"],
},
{
"cat":"Matt & Ben",
"ques":"What is the first film that featured Matt Damon and Ben Affleck in the same cast?",
"answ":"SCHOOL TIES",
"answ2":"School Ties.",
"option":["School Ties", "Chasing Amy", "Good Will Hunting", "Dogma"],
},
{
"cat":"Matt & Ben",
"ques":"Ben Affleck, Charlize Theron and Gary Sinise star in what 2000 crime thriller?",
"answ":"REINDEER GAMES",
"answ2":"Reindeer Games.",
"option":["Reindeer Games", "Boiler Room", "Changing Lanes", "The Sum of All Fears"],
},
{
"cat":"Matt & Ben",
"ques":"Before playing Batman, Ben Affleck had portrayed what other comic books superhero?",
"answ":"DAREDEVIL",
"answ2":"Daredevil.",
"option":["Daredevil", "Superman", "Human Torch", "Captain America"],
},
{
"cat":"Matt & Ben",
"ques":"Which actress co-stars with Matt Damon in the film We Bought A Zoo as the lead zookeeper Kelly Foster?",
"answ":"SCARLETT JOHANSSON",
"answ2":"Scarlett Johansson.",
"option":["Scarlett Johansson", "Amy Adams", "Anne Hathaway", "Cameron Diaz"],
},
{
"cat":"Matt & Ben",
"ques":"Who directed The Bourne Ultimatum?",
"answ":"PAUL GREENGRASS",
"answ2":"Paul Greengrass.",
"option":["Paul Greengrass", "Shane Black", "Doug Liman", "Christopher McQuarrie"],
},
{
"cat":"Matt & Ben",
"ques":"In Stuck On You, conjoined twins Bob and Walt run what type of establishment?",
"answ":"RESTAURANT",
"answ2":"Restaurant.",
"option":["Restaurant", "Movie Theater", "Book store", "Pharmacy"],
},
{
"cat":"Matt & Ben",
"ques":"Who directed Ben Affleck in The Accountant and The Way Back?",
"answ":"GAVIN O'CONNOR",
"answ3":"GAVIN O CONNOR",
"answ2":"Gavin O'Connor.",
"option":["Gavin O'Connor", "", "", ""],
},
{
"cat":"Matt & Ben",
"ques":"Which actress plays Ben Affleck's love interest in the drama Bounce?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
"option":["Gwyneth Paltrow", "Charlize Theron", "Cate Blanchett", "Kate Beckinsale"],
},
{
"cat":"Matt & Ben",
"ques":"Which actor plays mathematics professor Gerald Lambeau in Good Will Hunting?",
"answ":"STELLAN SKARSGARD",
"answ2":"Stellan Skarsgard.",
"option":["Stellan Skarsgard", "Robin Williams", "Geoffrey Rush", "Tom Wilkinson"],
},
{
"cat":"Matt & Ben",
"ques":"Matt Damon received his first acting Oscar nomination for which film?",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
"option":["Good Will Hunting", "Invictus", "The Martian", "Behind the Candelabra"],
},
{
"cat":"Matt & Ben",
"ques":"How many Oscars has Matt Damon won?",
"answ":"1",
"answ3":"ONE",
"answ2":"1.",
"option":["1", "0", "2", "3"],
},
{
"cat":"Matt & Ben",
"ques":"Which film was the directorial debut for Ben Affleck?",
"answ":"GONE BABY GONE",
"answ2":"Gone Baby Gone.",
"option":["Gone Baby Gone", "Argo", "The Town", "Live by Night"],
},
{
"cat":"Matt & Ben",
"ques":"Matt Damon and Penélope Cruz star in what romantic western directed by Billy Bob Thornton?",
"answ":"ALL THE PRETTY HORSES",
"answ2":"All the Pretty Horses.",
"option":["All the Pretty Horses", "The Majestic", "EuroTrip", "When In Rome"],
},
{
"cat":"Matt & Ben",
"ques":"Ben Affleck and Gwyneth Paltrow star together in what 2000 romantic drama?",
"answ":"BOUNCE",
"answ2":"Bounce.",
"option":["Bounce", "Daddy and Them", "The Third Wheel", "Dazed and Confused"],
},
{
"cat":"Matt & Ben",
"ques":"The 2010 action thriller Green Zone, starring Matt Damon, is set in which country?",
"answ":"IRAQ",
"answ2":"Iraq.",
"option":["Iraq", "Russia", "Afghanistan", "Vietnam"],
},
{
"cat":"Matt & Ben",
"ques":"Who directed Matt Damon in the 2010 action thriller Green Zone?",
"answ":"PAUL GREENGRASS",
"answ2":"Paul Greengrass.",
"option":["Paul Greengrass", "Tony Scott", "Charles Ferguson", "Clint Eastwood"],
},
{
"cat":"Matt & Ben",
"ques":"Which famous actor directed Matt Damon in the 2010 fantasy disaster film Hereafter?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
"option":["Clint Eastwood", "Robert Redford", "Ben Affleck", "Billy Bob Thornton"],
},
{
"cat":"Matt & Ben",
"ques":"Ben Affleck stars alongside Kevin Costner, Chris Cooper and Tommy Lee Jones in what 2010 drama?",
"answ":"THE COMPANY MEN",
"answ2":"The Company Men.",
"option":["The Company Men", "Argo", "The Town", "Runner Runner"],
},
];
r2Q73 = shuffle(r2Q73);