var r2Q75 = [ 
{
"cat":"Keanu Reeves",
"ques":"In John Wick: Chapter 2, how many bullets does the Bowery King give John when John asked for a gun?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":["7", "12", "6", "14"],
},
{
"cat":"Keanu Reeves",
"ques":"In Constantine, John Constantine learns that he is sick, and likely to die, from what specific disease?",
"answ":"LUNG CANCER",
"answ2":"Lung cancer.",
"option":["Lung cancer", "Brain cancer", "Melanoma", "Kidney disease"],
},
{
"cat":"Keanu Reeves",
"ques":"Which late actor co-starred with Keanu Reeves in the drama My Own Private Idaho as Mikey Waters?",
"answ":"RIVER PHOENIX",
"answ2":"River Phoenix.",
"option":["River Phoenix", "Heath Ledger", "Robin Williams", "Richard Harris"],
},
{
"cat":"Keanu Reeves",
"ques":"In Point Break, Johnny Utah played football at what university before becoming an FBI agent?",
"answ":"OHIO STATE UNIVERSITY",
"answ3":"OHIO STATE",
"answ2":"Ohio State University.",
"option":["Ohio State University", "Harvard University", "Stanford University", "Columbia University"],
},
{
"cat":"Keanu Reeves",
"ques":"In John Wick, who plays John's mentor Marcus who helps him throughout the film?",
"answ":"WILLEM DAFOE",
"answ2":"Willem Dafoe.",
"option":["Willem Dafoe", "Lawrence Fishburne", "John Malkovich", "Ian McShane"],
},
{
"cat":"Keanu Reeves",
"ques":"What number are Bill & Ted thinking of when they play the guessing game with their future selves?",
"answ":"69",
"answ2":"69.",
"option":["69", "7", "13", "1000000"],
},
{
"cat":"Keanu Reeves",
"ques":"What grade do Bill and Ted have to get on their history report so they don't flunk out of school?",
"answ":"A+",
"answ2":"A+.",
"option":["A+", "B+", "A-", "B"],
},
{
"cat":"Keanu Reeves",
"ques":"The Keanu Reeves/Sandra Bullock fantasy romance The Lake House is a remake of a film from which country?",
"answ":"SOUTH KOREA",
"answ2":"South Korea.",
"option":["South Korea", "Japan", "Italy", "Romania"],
},
{
"cat":"Keanu Reeves",
"ques":"What Game of Thrones star plays Iosef Tarasov, the man who steals John Wick's car and kills his dog, in John Wick?",
"answ":"ALFIE ALLEN",
"answ2":"Alfie Allen.",
"option":["Alfie Allen", "Kit Harrington", "Daniel Portman", "Iwan Rheon"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays Missy in the Bill & Ted films?",
"answ":"AMY STOCH",
"answ2":"Amy Stoch.",
"option":["Amy Stoch", "Courtney Thorne-Smith", "Kelly Preston", "Martha Plimpton"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a character by the name of Bob Arctor in what 2000s crime drama?",
"answ":"A SCANNER DARKLY",
"answ2":"A Scanner Darkly.",
"option":["A Scanner Darkly", "Hardball", "The Watcher", "Street Kings"],
},
{
"cat":"Keanu Reeves",
"ques":"What Oscar-winning actress did Reeves star with in Sweet November and The Devil's Advocate?",
"answ":"CHARLIZE THERON",
"answ2":"Charlize Theron.",
"option":["Charlize Theron", "Cate Blanchett", "Tilda Swinton", "Patricia Arquette"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves stars in a minor role in what 2000s drama starring Robin Wright, Blake Lively and Maria Bello?",
"answ":"THE PRIVATE LIVES OF PIPPA LEE",
"answ3":"PRIVATE LIVES OF PIPPA LEE",
"answ2":"The Private Lives of Pippa Lee.",
"option":["The Private Lives of Pippa Lee", "Street Kings", "Ellie Parker", "The Gift"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a gambler who in exchange for money to repay his debts he must coach a baseball team of troubled 5th grade kids in what 2000s comedy-drama?",
"answ":"HARDBALL",
"answ2":"Hardball.",
"option":["Hardball", "The Replacements", "The Watcher", "Thumbsucker"],
},
{
"cat":"Keanu Reeves",
"ques":"What 1988 film featured Keanu Reeves and Uma Thurman?",
"answ":"DANGEROUS LIAISONS",
"answ2":"Dangerous Liaisons.",
"option":["Dangerous Liaisons", "Who Framed Roger Rabbit", "Beaches", "A Fish Called Wanda"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 2006 sci-fi film A Scanner Darkly?",
"answ":"RICHARD LINKLATER",
"answ2":"Richard Linklater.",
"option":["Richard Linklater", "Paul Verhoeven", "Darren Aronofsky", "Vincenzo Natali"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 2008 cop drama Street Kings?",
"answ":"DAVID AYER",
"answ2":"David Ayer.",
"option":["David Ayer", "Antoine Fuqua", "Joe Carnahan", "Brett Ratner"],
},
{
"cat":"Keanu Reeves",
"ques":"Which actress does Keanu Reeves fall for in the 2003 rom-com Something's Gotta Give?",
"answ":"DIANE KEATON",
"answ2":"Diane Keaton.",
"option":["Diane Keaton", "Tilda Swinton", "Amanda Peet", "Rachel Weisz"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays the villain Don John in which 1993 Shakespeare film?",
"answ":"MUCH ADO ABOUT NOTHING",
"answ2":"Much Ado About Nothing.",
"option":["Much Ado About Nothing", "The Twelfth Night", "Hamlet", "Titus"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays the villainous Donaka Mark in which 2013 action movie?",
"answ":"MAN OF TAI CHI",
"answ2":"Man of Tai Chi.",
"option":["Man of Tai Chi", "Knock Knock", "The Bad Batch", "Henry's Crime"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays the abusive husband of which actress in the 2000 film The Gift?",
"answ":"HILARY SWANK",
"answ2":"Hilary Swank.",
"option":["Hilary Swank", "Cate Blanchett", "Katie Holmes", "Ashley Judd"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays the leader of a dystopian civilization in which 2016 sci-fi film?",
"answ":"THE BAD BATCH",
"answ2":"The Bad Batch.",
"option":["The Bad Batch", "Midnight Special", "The 5th Wave", "Allegiant"],
},
{
"cat":"Keanu Reeves",
"ques":"In which 1990s thriller does Keanu Reeves discover the secret to harvesting power from water?",
"answ":"CHAIN REACTION",
"answ2":"Chain Reaction.",
"option":["Chain Reaction", "Johnny Mnemonic", "The Trigger Effect", "The Weight of Water"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a bumbling hitman in the 1990 comedy I Love You to Death. Who played his would-be victim?",
"answ":"KEVIN KLINE",
"answ2":"Kevin Kline.",
"option":["Kevin Kline", "John Cleese", "Dudley Moore", "Elliott Gould"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 2015 erotic thriller Knock Knock?",
"answ":"ELI ROTH",
"answ2":"Eli Roth.",
"option":["Eli Roth", "Joel Edgerton", "James Wan", "Adam Wingard"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a serial killer who taunts a retired FBI agent in what 2000 thriller?",
"answ":"THE WATCHER",
"answ2":"The Watcher.",
"option":["The Watcher", "Taking Lives", "Murder By Numbers", "Untraceable"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves goes on a road trip with Thomas Jane in which 1997 drama?",
"answ":"THE LAST TIME I COMMITTED SUICIDE",
"answ2":"The Last Time I Committed Suicide.",
"option":["The Last Time I Committed Suicide", "Johnny Mnemonic", "Lost Highway", "A Walk in the Clouds"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a character by the name of Jack Traven in what 90s film?",
"answ":"SPEED",
"answ2":"Speed.",
"option":["Speed", "A Walk in the Clouds", "Point Break", "Johnny Mnemonic"],
},
{
"cat":"Keanu Reeves",
"ques":"Which rock star plays a coffee shop waitress in the Keanu Reeves crime comedy Feeling Minnesota?",
"answ":"COURTNEY LOVE",
"answ2":"Courtney Love.",
"option":["Courtney Love", "Sheryl Crow", "Gwen Stefani", "Shirley Manson"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays the mute assassin Ares opposite Keanu Reeves in John Wick: Chapter 2?",
"answ":"RUBY ROSE",
"answ2":"Ruby Rose.",
"option":["Ruby Rose", "Common", "Laurence Fishburne", "Bridget Moynahan"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays Satan opposite Keanu Reeves in the 2005 film Constantine?",
"answ":"PETER STORMARE",
"answ2":"Peter Stormare.",
"option":["Peter Stormare", "Al Pacino", "Peter Fonda", "Steve Buscemi"],
},
{
"cat":"Keanu Reeves",
"ques":"Which action star plays an assassin street preacher in the Keanu Reeves film Johnny Mnemonic?",
"answ":"DOLPH LUNDGREN",
"answ2":"Dolph Lundgren.",
"option":["Dolph Lundgren", "Jean-Claude Van Damme", "Jason Statham", "Vin Diesel"],
},
{
"cat":"Keanu Reeves",
"ques":"What was the name of the character played by Keanu Reeves in the 1991 film Point Break?",
"answ":"JOHNNY UTAH",
"answ2":"Johnny Utah.",
"option":["Johnny Utah", "Richie Nebraska", "Stevie California", "Max Florida"],
},
{
"cat":"Keanu Reeves",
"ques":"Who played Keanu Reeves' fiancee in Bram Stoker's Dracula?",
"answ":"WINONA RYDER",
"answ2":"Winona Ryder.",
"option":["Winona Ryder", "Christina Ricci", "Sadie Frost", "Monica Bellucci"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 1993 comedy-drama Even Cowgirls Get the Blues?",
"answ":"GUS VAN SANT",
"answ2":"Gus Van Sant.",
"option":["Gus Van Sant", "Jonathan Demme", "Lawrence Kasdan", "Penelope Spheeris"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves played Dr. Julian Mercer in which 2003 film?",
"answ":"SOMETHING'S GOTTA GIVE",
"answ2":"Something's Gotta Give.",
"option":["Something's Gotta Give", "Hardball", "Sweet November", "The Replacements"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a warrior named Kai in which 2013 action-fantasy?",
"answ":"47 RONIN",
"answ2":"47 Ronin.",
"option":["47 Ronin", "The Great Wall", "Prince of Persia", "Clash of the Titans"],
},
{
"cat":"Keanu Reeves",
"ques":"What 2016 film is the first theatrically-released feature in which Keanu Reeves has a voice credit?",
"answ":"KEANU",
"answ2":"Keanu.",
"option":["Keanu", "Rogue One", "Finding Dory", "The Jungle Book"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves plays a lawyer named Kevin Lomax in what 1997 film?",
"answ":"THE DEVIL'S ADVOCATE",
"answ3":"DEVIL'S ADVOCATE",
"answ2":"The Devil's Advocate.",
"option":["The Devil's Advocate", "The Watcher", "City Hall", "The Gift"],
},
{
"cat":"Keanu Reeves",
"ques":"What was the name of the alien played by Keanu Reeves in the 2008 film The Day the Earth Stood Still?",
"answ":"KLAATU",
"answ3":"KLATU",
"answ2":"Klaatu.",
"option":["Klaatu", "Nilbog", "Gort", "Fremulon"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays the Bowery King in John Wick: Chapter 2?",
"answ":"LAURENCE FISHBURNE",
"answ2":"Laurence Fishburne.",
"option":["Laurence Fishburne", "Ian McShane", "William Hurt", "Peter Stormare"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves made his directorial debut in what 2013 film?",
"answ":"MAN OF TAI CHI",
"answ2":"Man of Tai Chi.",
"option":["Man of Tai Chi", "Ong-Bak", "John Wick", "The Final Master"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays Keanu Reeves' hitman partner 1990 film I Love You to Death?",
"answ":"WILLIAM HURT",
"answ2":"William Hurt.",
"option":["William Hurt", "Kevin Kline", "Kevin Bacon", "River Phoenix"],
},
{
"cat":"Keanu Reeves",
"ques":"What is the name of the alien Bill & Ted enlist from heaven to build robot versions of themselves in Bill & Ted's Bogus Journey?",
"answ":"STATION",
"answ2":"Station.",
"option":["Station", "Bogus", "Radical", "Gear"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 1988 historical drama Dangerous Liaisons?",
"answ":"STEPHEN FREARS",
"answ3":"STEVEN FREARS",
"answ2":"Stephen Frears.",
"option":["Stephen Frears", "Milos Forman", "James Ivory", "Brian Gilbert"],
},
{
"cat":"Keanu Reeves",
"ques":"Which legendary actor plays the grandfather who welcomes Keanu Reeves to the family in the 1995 film A Walk in the Clouds?",
"answ":"ANTHONY QUINN",
"answ2":"Anthony Quinn.",
"option":["Anthony Quinn", "Marlon Brando", "Kirk Douglas", "Sidney Poitier"],
},
{
"cat":"Keanu Reeves",
"ques":"What kind of doctor does Keanu Reeves play in the 2005 film Thumbsucker?",
"answ":"ORTHODONTIST",
"answ3":"DENTIST",
"answ2":"Orthodontist.",
"option":["Orthodontist", "Psychologist", "Pediatrician", "Hematologist"],
},
{
"cat":"Keanu Reeves",
"ques":"Who plays the assassin who tries to kill John Wick in his room at The Continental in the first John Wick film?",
"answ":"ADRIANNE PALICKI",
"answ3":"ADRIANE PALICKI",
"answ2":"Adrianne Palicki.",
"option":["Adrianne Palicki", "Lance Reddick", "Clarke Peters", "Gal Gadot"],
},
{
"cat":"Keanu Reeves",
"ques":"In John Wick: Chapter 2, in what European city does John find his target Gianna D'Antonio?",
"answ":"ROME",
"answ2":"Rome.",
"option":["Rome", "Athens", "Berlin", "Florence"],
},
{
"cat":"Keanu Reeves",
"ques":"In Bill & Ted's Excellent Adventure, in what city do Bill & Ted live?",
"answ":"SAN DIMAS",
"answ2":"San Dimas.",
"option":["San Dimas", "Beverly Hills", "Santa Monica", "Palm Springs"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 1991 film My Own Private Idaho?",
"answ":"GUS VAN SANT",
"answ2":"Gus Van Sant.",
"option":["Gus Van Sant", "John Waters", "Steven Soderbergh", "Francis Ford Coppola"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Keanu Reeves in the 1993 film Little Buddha?",
"answ":"BERNARDO BERTOLUCCI",
"answ2":"Bernardo Bertolucci.",
"option":["Bernardo Bertolucci", "Neil Jordan", "Neil Jordan", "Jean-Jacques Annaud"],
},
{
"cat":"Keanu Reeves",
"ques":"Who directed Bill & Ted's Excellent Adventure?",
"answ":"STEPHEN HEREK",
"answ3":"STEVEN HEREK",
"answ2":"Stephen Herek.",
"option":["Stephen Herek", "Peter Hewitt", "Frank Oz", "John Hughes"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves goes undercover in the battle against what drug in A Scanner Darkly?",
"answ":"SUBSTANCE D",
"answ2":"Substance D.",
"option":["Substance D", "Substance Z", "Substance Y", "Substance O"],
},
{
"cat":"Keanu Reeves",
"ques":"What was the name of the character played by Keanu Reeves in the 1989 film Bill & Ted's Excellent Adventure?",
"answ":"TED",
"answ2":"Ted.",
"option":["Ted", "Bill", "Johnny", "Donnie"],
},
{
"cat":"Keanu Reeves",
"ques":"In The Matrix, what is Keanu Reeves character's full real name?",
"answ":"THOMAS ANDERSON",
"answ2":"Thomas Anderson.",
"option":["Thomas Anderson", "James Anderson", "Thomas Smith", "Abraham Anderson"],
},
{
"cat":"Keanu Reeves",
"ques":"What Oscar-winning actress did Reeves star with in Thumbsucker and Constantine?",
"answ":"TILDA SWINTON",
"answ2":"Tilda Swinton.",
"option":["Tilda Swinton", "Juliette Binoche", "Brie Larson", "Anne Hathaway"],
},
{
"cat":"Keanu Reeves",
"ques":"Keanu Reeves co-stars with Steve Martin, Dianne Wiest and Joaquin Phoenix in which 1989 comedy?",
"answ":"PARENTHOOD",
"answ2":"Parenthood.",
"option":["Parenthood", "I Love You to Death", "Dirty Rotten Scoundrels", "L.A. Story"],
},
{
"cat":"Keanu Reeves",
"ques":"My Own Private Idaho starring Keanu Reeves was loosely adapted from the works of what writer?",
"answ":"WILLIAM SHAKESPEARE",
"answ3":"SHAKESPEARE",
"answ2":"William Shakespeare.",
"option":["William Shakespeare", "Jane Austen", "William Faulkner", "TS Eliot"],
},
{
"cat":"Keanu Reeves",
"ques":"In what state is the lake house rented by Keanu Reeves in the movie The Lake House?",
"answ":"WISCONSIN",
"answ2":"Wisconsin.",
"option":["Wisconsin", "Vermont", "North Carolina", "Iowa"],
},
{
"cat":"Keanu Reeves",
"ques":"In Bill & Ted's Excellent Adventure, what is Bill & Ted's band called?",
"answ":"WYLD STALLYNS",
"answ2":"Wyld Stallyns.",
"option":["Wyld Stallyns", "Grey Horsys", "Ferocyous Naggs", "Purtty Ponyys"],
},
];
r2Q75 = shuffle(r2Q75);