var r2Q76 = [
{
"cat":"Natalie Portman",
"ques":"What color wig does Natalie Portman wear when she performs a striptease for Clive Owen in Closer?",
"answ":"PINK",
"answ2":"Pink.",
"option":["Pink", "Red", "Blonde", "Green"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays Natalie Portman's mother in the 1999 comedy Anywhere But Here?",
"answ":"SUSAN SARANDON",
"answ2":"Susan Sarandon.",
"option":["Susan Sarandon", "Julianne Moore", "Annette Bening", "Helen Hunt"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays King Henry VIII, opposite Natalie Portman's Anne Boleyn, in The Other Boleyn Girl?",
"answ":"ERIC BANA",
"answ2":"Eric Bana.",
"option":["Eric Bana", "Mark Rylance", "Stuart Townsend", "Jim Sturgess"],
},
{
"cat":"Natalie Portman",
"ques":"Who played the overbearing mother to Natalie Portman's character in Black Swan?",
"answ":"BARBARA HERSHEY",
"answ2":"Barbara Hershey.",
"option":["Barbara Hershey", "Jacki Weaver", "Diane Lane", "Ellen Barkin"],
},
{
"cat":"Natalie Portman",
"ques":"What ensemble film featured Natalie Portman, Uma Thurman, and Michael Rapaport?",
"answ":"BEAUTIFUL GIRLS",
"answ2":"Beautiful Girls.",
"option":["Beautiful Girls", "Valentine's Day", "Gosford Park", "Much Ado About Nothing"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays the journalist Natalie Portman opens up to in Jackie?",
"answ":"BILLY CRUDUP",
"answ2":"Billy Crudup.",
"option":["Billy Crudup", "Peter Sarsgaard", "Jeremy Davies", "Lukas Haas"],
},
{
"cat":"Natalie Portman",
"ques":"What 2003 film cast Natalie Portman as Sara, a lonely widow?",
"answ":"COLD MOUNTAIN",
"answ2":"Cold Mountain.",
"option":["Cold Mountain", "In the Bedroom", "Affliction", "North Country"],
},
{
"cat":"Natalie Portman",
"ques":"Who directed Natalie Portman in the 2015 drama Knight of Cups?",
"answ":"TERRENCE MALICK",
"answ3":"TERRANCE MALICK",
"answ2":"Terrence Malick.",
"option":["Terrence Malick", "Bennett Miller", "Angelina Jolie", "Richard Linklater"],
},
{
"cat":"Natalie Portman",
"ques":"What is Natalie Portman's profession in the open relationship romantic comedy No Strings Attached?",
"answ":"DOCTOR",
"answ2":"Doctor.",
"option":["Doctor", "Lawyer", "Politician", "Writer"],
},
{
"cat":"Natalie Portman",
"ques":"In Garden State, Natalie Portman's character is a compulsive liar who lives with what medical condition?",
"answ":"EPILEPSY",
"answ2":"Epilepsy.",
"option":["Epilepsy", "Tourette's Syndrome", "Narcolepsy", "Diabetes"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays Natalie Portman's ex-con brother-in-law in the 2009 war drama Brothers?",
"answ":"JAKE GYLLENHAAL",
"answ2":"Jake Gyllenhaal.",
"option":["Jake Gyllenhaal", "Peter Sarsgaard", "Tobey Maguire", "Zac Efron"],
},
{
"cat":"Natalie Portman",
"ques":"In what film does Natalie Portman play the stepdaughter of a cop?",
"answ":"HEAT",
"answ2":"Heat.",
"option":["Heat", "Leon: The Professional", "Cop Land", "Clueless"],
},
{
"cat":"Natalie Portman",
"ques":"In which film does Natalie Portman play a model for a famed Spanish painter?",
"answ":"GOYA'S GHOSTS",
"answ3":"GOYAS GHOSTS",
"answ2":"Goya's Ghosts.",
"option":["Goya's Ghosts", "Frida", "The Girl with the Pearl Earring", "Big Eyes"],
},
{
"cat":"Natalie Portman",
"ques":"Natalie Portman plays the ex-girlfriend to which actor The Darjeeling Limited?",
"answ":"JASON SCHWARTZMAN",
"answ2":"Jason Schwartzman.",
"option":["Jason Schwartzman", "Adrien Brody", "Owen Wilson", "Bill Murray"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays Bobby Kennedy opposite Natalie Portman's Jackie Kennedy, in the 2016 film Jackie?",
"answ":"PETER SARSGAARD",
"answ2":"Peter Sarsgaard.",
"option":["Peter Sarsgaard", "Matt Damon", "Steven Culp", "Sam Rockwell"],
},
{
"cat":"Natalie Portman",
"ques":"In which Natalie Portman movie does she defend her home from a gang called 'The Bishop Boys'?",
"answ":"JANE GOT A GUN",
"answ2":"Jane Got a Gun.",
"option":["Jane Got a Gun", "The Beguiled", "Cold Mountain", "The Missing"],
},
{
"cat":"Natalie Portman",
"ques":"Natalie Portman co-stars in which 1996 Woody Allen comedy?",
"answ":"EVERYONE SAYS I LOVE YOU",
"answ2":"Everyone Says I Love You.",
"option":["Everyone Says I Love You", "Celebrity", "Sweet and Lowdown", "Manhattan Murder Mystery"],
},
{
"cat":"Natalie Portman",
"ques":"Natalie Portman stars as a woman who believes she can talk to ghosts in what 2016 drama?",
"answ":"PLANETARIUM",
"answ2":"Planetarium.",
"option":["Planetarium", "Song to Song", "Jane Got a Gun", "Black Swan"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays Natalie Portman's stepfather in the 1995 crime drama Heat?",
"answ":"AL PACINO",
"answ2":"Al Pacino.",
"option":["Al Pacino", "Robert De Niro", "Val Kilmer", "Tom Sizemore"],
},
{
"cat":"Natalie Portman",
"ques":"Who directed Natalie Portman in the 1996 film Beautiful Girls?",
"answ":"TED DEMME",
"answ2":"Ted Demme.",
"option":["Ted Demme", "Luc Besson", "Kenneth Lonergan", "Richard Linklater"],
},
{
"cat":"Natalie Portman",
"ques":"What was the first name of the character played by Natalie Portman in the 1994 film Leon: The Professional?",
"answ":"MATHILDA",
"answ2":"Mathilda.",
"option":["Mathilda", "Leslie", "Evey", "Anne"],
},
{
"cat":"Natalie Portman",
"ques":"In which 2007 film does Natalie Portman receive a gift called a Congreve Cube?",
"answ":"MR MAGORIUM'S WONDER EMPORIUM",
"answ3":"MR MAGORIUMS WONDER EMPORIUM",
"answ2":"Mr. Magorium's Wonder Emporium.",
"option":["Mr. Magorium's Wonder Emporium", "Revenge of the Sith", "V for Vendetta", "Black Swan"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays Natalie Portman's father in the 1996 sci-fi comedy Mars Attacks!?",
"answ":"JACK NICHOLSON",
"answ2":"Jack Nicholson.",
"option":["Jack Nicholson", "Pierce Brosnan", "Martin Short", "Tom Jones"],
},
{
"cat":"Natalie Portman",
"ques":"Which Oscar-winning filmmaker directed Natalie Portman in the Civil War drama Cold Mountain?",
"answ":"ANTHONY MINGHELLA",
"answ2":"Anthony Minghella.",
"option":["Anthony Minghella", "Kathryn Bigelow", "Ang Lee", "Bernardo Bertolucci"],
},
{
"cat":"Natalie Portman",
"ques":"Who plays the titular metalhead opposite Natalie Portman in the 2010 film Hesher?",
"answ":"JOSEPH GORDON LEVITT",
"answ2":"Joseph Gordon-Levitt.",
"option":["Joseph Gordon-Levitt", "Anton Yelchin", "Sam Worthington", "James Franco"],
},
{
"cat":"Natalie Portman",
"ques":"In which movie does an abandoned Natalie Portman secretly live in a Wal-Mart?",
"answ":"WHERE THE HEART IS",
"answ2":"Where the Heart Is.",
"option":["Where the Heart Is", "Anywhere But Here", "The Other Woman", "Hesher"],
},
{
"cat":"Natalie Portman",
"ques":"Natalie Portman directed one of the short films, and starred in one of the others, in which 2008 anthology film?",
"answ":"NEW YORK I LOVE YOU",
"answ2":"New York, I Love You.",
"option":["New York, I Love You", "The ABCs of Death", "Four Rooms", "Paris, je t'aime"],
},
{
"cat":"Natalie Portman",
"ques":"Natalie Portman had a cameo in which 2007 Wes Anderson movie?",
"answ":"THE DARJEELING LIMITED",
"answ3":"DARJEELING LIMITED",
"answ2":"The Darjeeling Limited.",
"option":["The Darjeeling Limited", "Moonrise Kingdom", "The Life Aquatic with Steve Zissou", "Fantastic Mr. Fox"],
},
];
r2Q76 = shuffle(r2Q76);