var r2Q77 = [
{
"cat":"Bruce Willis",
"ques":"In Mercury Rising, who plays the villainous Lt. Colonel Nichols Kudrow, who sees the boy's ability to decipher the Mercury Code as a grave liability?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
"option":["Alec Baldwin", "Morgan Freeman", "Tommy Lee Jones", "Val Kilmer"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays undercover FBI agent Art Jeffries in what 1998 thriller?",
"answ":"MERCURY RISING",
"answ2":"Mercury Rising.",
"option":["Mercury Rising", "The Jackal", "The Siege", "Nancy Drew"],
},
{
"cat":"Bruce Willis",
"ques":"Who played Bruce Willis's wife in the 1999 film The Story of Us?",
"answ":"MICHELLE PFEIFFER",
"answ2":"Michelle Pfeiffer.",
"option":["Michelle Pfeiffer", "Joan Allen", "Meg Ryan", "Goldie Hawn"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis played a character by the name of Bill Capra in what 1994 film?",
"answ":"COLOR OF NIGHT",
"answ2":"Color of Night.",
"option":["Color of Night", "The Player", "Mortal Thoughts", "North"],
},
{
"cat":"Bruce Willis",
"ques":"The first starring role for Bruce Willis was in what 1987 feature?",
"answ":"BLIND DATE",
"answ2":"Blind Date.",
"option":["Blind Date", "Into the Night", "After Hours", "Kentucky Fried Movie"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a character by the name of Bo Weinberg in what 1991 crime drama?",
"answ":"BILLY BATHGATE",
"answ2":"Billy Bathgate.",
"option":["Billy Bathgate", "Color of Night", "Pulp Fiction", "Hudson Hawk"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays himself in what 1992 crime comedy?",
"answ":"THE PLAYER",
"answ2":"The Player.",
"option":["The Player", "Mortal Thoughts", "The Last Boy Scout", "Color of Night"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a character by the name of Butch Coolidge in what 1990s crime film?",
"answ":"PULP FICTION",
"answ2":"Pulp Fiction.",
"option":["Pulp Fiction", "Natural Born Killers", "Carlito's Way", "The Jackal"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays Police Captain Duffy Sharp in what Wes Anderson film?",
"answ":"MOONRISE KINGDOM",
"answ2":"Moonrise Kingdom.",
"option":["Moonrise Kingdom", "The Grand Budapest Hotel", "Fantastic Mr. Fox", "The Royal Tenenbaums"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis stars alongside Paul Newman and Jessica Tandy in what 1990s comedy-drama?",
"answ":"NOBODY'S FOOL",
"answ2":"Nobody's Fool.",
"option":["Nobody's Fool", "Last Man Standing", "The Bonfire of the Vanities", "Color of Night"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays computer expert Theo in Die Hard?",
"answ":"CLARENCE GILYARD JR",
"answ3":"CLARENCE GILYARD JR",
"answ2":"Clarence Gilyard.",
"option":["Clarence Gilyard", "De'voreaux White", "Hart Bochner", "Alan Rickman"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a character by the name of Colonel William McNamara in what 2002 drama film?",
"answ":"HART'S WAR",
"answ3":"HARTS WAR",
"answ2":"Hart's War.",
"option":["Hart's War", "Hostage", "Tears of the Sun", "Planet Terror"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a homicide detective by the name of Tom Hardy in what 1993 action thriller?",
"answ":"STRIKING DISTANCE",
"answ2":"Striking Distance.",
"option":["Striking Distance", "Surrogates", "Catch .44", "RED"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the waitress that Bruce Willis discovers is a gambling prodigy in the comedy-drama Lay the Favorite?",
"answ":"REBECCA HALL",
"answ2":"Rebecca Hall.",
"option":["Rebecca Hall", "Jessica Chastain", "Eva Mendes", "Heather Graham"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Vincent, the guy who shoots Bruce Willis in The Sixth Sense?",
"answ":"DONNIE WAHLBERG",
"answ2":"Donnie Wahlberg.",
"option":["Donnie Wahlberg", "Noah Taylor", "Richmond Arquette", "Aaron Carter"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays Dr. Malcolm Crowe in which 1999 thriller?",
"answ":"THE SIXTH SENSE",
"answ3":"SIXTH SENSE",
"answ2":"The Sixth Sense.",
"option":["The Sixth Sense", "The Siege", "Hart's War", "Unbreakable"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a salesman who sells what in the 1999 film Breakfast of Champions?",
"answ":"CARS",
"answ2":"Cars.",
"option":["Cars", "Insurance", "Computers", "Real Estate"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays General William Devereaux in which 1998 political thriller?",
"answ":"THE SIEGE",
"answ2":"The Siege.",
"option":["The Siege", "Hart's War", "Snake Eyes", "Arlington Road"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed the Bruce Willis sci-fi thriller Surrogates?",
"answ":"JONATHAN MOSTOW",
"answ2":"Jonathan Mostow.",
"option":["Jonathan Mostow", "McG", "Andrew Niccol", "Jon M. Chu"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis and Halle Berry have co-starred in two films together: The Last Boy Scout, and which other film?",
"answ":"PERFECT STRANGER",
"answ2":"Perfect Stranger.",
"option":["Perfect Stranger", "Movie 43", "Red 2", "Lucky Number Slevin"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis makes a cameo as the executive vice-president of a fast food chain in what 2006 comedy-drama?",
"answ":"FAST FOOD NATION",
"answ2":"Fast Food Nation.",
"option":["Fast Food Nation", "Thank You For Smoking", "About a Boy", "The Royal Tenenbaums"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays single dad Harry S. Stamper in which 1998 blockbuster?",
"answ":"ARMAGEDDON",
"answ3":"ARMEGEDDON",
"answ2":"Armageddon.",
"option":["Armageddon", "The Fifth Element", "The Sixth Sense", "G.I. Joe Retaliation"],
},
{
"cat":"Bruce Willis",
"ques":"In Die Hard, what is the first name of John McClane's wife?",
"answ":"HOLLY",
"answ2":"Holly.",
"option":["Holly", "Lucy", "Connie", "Annie"],
},
{
"cat":"Bruce Willis",
"ques":"Richard E. Grant and Sandra Bernhard play Bruce Willis's nemeses in which 1991 comedy thriller?",
"answ":"HUDSON HAWK",
"answ2":"Hudson Hawk.",
"option":["Hudson Hawk", "The Last Boy Scout", "Billy Bathgate", "Death Becomes Her"],
},
{
"cat":"Bruce Willis",
"ques":"Which hip hop artist plays the informant Bruce Willis is assigned to protect in the thriller 16 Blocks?",
"answ":"MOS DEF",
"answ2":"Mos Def.",
"option":["Mos Def", "Ice Cube", "Ludacris", "Bow Wow"],
},
{
"cat":"Bruce Willis",
"ques":"Which 1995 Bruce Willis thriller was based on a classic French short film called 'La Jetée'?",
"answ":"TWELVE MONKEYS",
"answ3":"12 MONKEYS",
"answ2":"Twelve Monkeys.",
"option":["Twelve Monkeys", "Last Man Standing", "Color of Night", "Die Hard with a Vengeance"],
},
{
"cat":"Bruce Willis",
"ques":"Who played Bruce Willis's wife in the 1991 thriller Mortal Thoughts?",
"answ":"GLENNE HEADLY",
"answ3":"GLENN HEADLY",
"answ2":"Glenne Headly.",
"option":["Glenne Headly", "Demi Moore", "Geena Davis", "Victoria Tennant"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Walter Smith, the money launderer taken hostage in the 2005 Bruce Willis thriller, Hostage?",
"answ":"KEVIN POLLAK",
"answ2":"Kevin Pollak.",
"option":["Kevin Pollak", "Ben Foster", "Michael Shannon", "Jeff Daniels"],
},
{
"cat":"Bruce Willis",
"ques":"Who played the villain Simon Gruber in Die Hard with a Vengeance?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
"option":["Jeremy Irons", "William Sadler", "Alan Rickman", "Gary Oldman"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a hitman who moves in next door to a dentist played by which actor in the crime comedy The Whole Nine Yards?",
"answ":"MATTHEW PERRY",
"answ2":"Matthew Perry.",
"option":["Matthew Perry", "Kevin James", "Steve Martin", "Ray Romano"],
},
{
"cat":"Bruce Willis",
"ques":"Who played Bruce Willis's neurotic partner in crime in the 2001 film Bandits?",
"answ":"BILLY BOB THORNTON",
"answ2":"Billy Bob Thornton.",
"option":["Billy Bob Thornton", "Sam Rockwell", "Chris Rock", "James Caan"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Die Hard?",
"answ":"JOHN MCTIERNAN",
"answ2":"John McTiernan.",
"option":["John McTiernan", "Mark L. Lester", "Richard Donner", "Roger Spottiswoode"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Bruce Willis in the 1996 film Last Man Standing?",
"answ":"WALTER HILL",
"answ2":"Walter Hill.",
"option":["Walter Hill", "John Carpenter", "John Woo", "Martin Campbell"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a drifting gunslinger-for hire in the middle of an Irish and Italian mafia war in a Prohibition era ghost town in what film?",
"answ":"LAST MAN STANDING",
"answ2":"Last Man Standing.",
"option":["Last Man Standing", "16 Blocks", "Tears of the Sun", "Striking Distance"],
},
{
"cat":"Bruce Willis",
"ques":"What was the name of Milla Jovovich's character in The Fifth Element?",
"answ":"LEELOO",
"answ3":"LELO",
"answ2":"Leeloo.",
"option":["Leeloo", "Shauna", "Rose", "Filu"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Bruce Willis in the 2003 film Tears of the Sun?",
"answ":"ANTOINE FUQUA",
"answ2":"Antoine Fuqua.",
"option":["Antoine Fuqua", "Peter Berg", "Michael Bay", "John McTiernan"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Bruce Willis in the 2007 film Planet Terror?",
"answ":"ROBERT RODRIGUEZ",
"answ2":"Robert Rodriguez.",
"option":["Robert Rodriguez", "George Romero", "John Carpenter", "Zack Snyder"],
},
{
"cat":"Bruce Willis",
"ques":"In the 2007 Bruce Willis crime thriller Lucky Number Slevin, who plays Slevin?",
"answ":"JOSH HARTNETT",
"answ2":"Josh Hartnett.",
"option":["Josh Hartnett", "Bruce Willis", "Morgan Freeman", "Lucy Liu"],
},
{
"cat":"Bruce Willis",
"ques":"Who provides the voice of Bruce Willis's baby sister in the sequel Look Who's Talking Too?",
"answ":"ROSEANNE BARR",
"answ2":"Roseanne Barr.",
"option":["Roseanne Barr", "Joan Cusack", "Ellen DeGeneres", "Lily Tomlin"],
},
{
"cat":"Bruce Willis",
"ques":"In Die Hard, what is the name of the tower where a majority of the film takes place?",
"answ":"NAKATOMI PLAZA",
"answ2":"Nakatomi Plaza.",
"option":["Nakatomi Plaza", "Century City Plaza", "Nagasaki Plaza", "Norishimo Plaza"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays multiple characters in which 1994 family movie?",
"answ":"NORTH",
"answ2":"North.",
"option":["North", "The Flintstones", "Blank Check", "Cabin Boy"],
},
{
"cat":"Bruce Willis",
"ques":"John McClane is a police officer from what city in Die Hard?",
"answ":"NEW YORK CITY",
"answ3":"NEW YORK",
"answ2":"New York City.",
"option":["New York City", "Detroit", "Los Angeles", "Philadelphia"],
},
{
"cat":"Bruce Willis",
"ques":"In what 1994 flop does Bruce Willis dress up as the Easter Bunny?",
"answ":"NORTH",
"answ2":"North.",
"option":["North", "Milk Money", "Baby's Day Out", "With Honors"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Bruce Willis in the 1990 film The Bonfire of the Vanities?",
"answ":"BRIAN DE PALMA",
"answ3":"BRYAN DE PALMA",
"answ2":"Brian De Palma.",
"option":["Brian De Palma", "Oliver Stone", "Woody Allen", "Alan Parker"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays himself in which 2004 caper movie?",
"answ":"OCEAN'S TWELVE",
"answ3":"OCEANS 12",
"answ2":"Ocean's Twelve.",
"option":["Ocean's Twelve", "The Italian Job", "The Score", "Matchstick Men"],
},
{
"cat":"Bruce Willis",
"ques":"Who played Sgt. Al Powell in Die Hard?",
"answ":"REGINALD VELJOHNSON",
"answ2":"Reginald VelJohnson.",
"option":["Reginald VelJohnson", "Charles S. Dutton", "Frankie Faison", "Steven Williams"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays former IRA sniper Declan Mulqueen opposite Bruce Willis in 1997s The Jackal?",
"answ":"RICHARD GERE",
"answ2":"Richard Gere.",
"option":["Richard Gere", "Brad Pitt", "Patrick Stewart", "Jason Isaacs"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis meets an eight-year-old version of himself in which 2000 family movie?",
"answ":"THE KID",
"answ2":"The Kid.",
"option":["The Kid", "North", "Nim's Island", "The Last Mimzy"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays FBI Deputy Director Carter Preston in 1997s The Jackal?",
"answ":"SIDNEY POITIER",
"answ2":"Sidney Poitier.",
"option":["Sidney Poitier", "Richard Gere", "Jack Nicholson", "Alec Baldwin"],
},
{
"cat":"Bruce Willis",
"ques":"Which actor played Bruce Willis's son in the 2006 crime film Alpha Dog?",
"answ":"EMILE HIRSCH",
"answ2":"Emile Hirsch.",
"option":["Emile Hirsch", "Justin Timberlake", "Ben Foster", "Jai Courtney"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis is set up on a blind with whom in the romantic comedy Blind Date?",
"answ":"KIM BASINGER",
"answ2":"Kim Basinger.",
"option":["Kim Basinger", "Goldie Hawn", "Michelle Pfeiffer", "Heather Locklear"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Bruce Willis' brother Ted who sets him up on a blind date in the 1980s romantic comedy Blind Date?",
"answ":"PHIL HARTMAN",
"answ2":"Phil Hartman.",
"option":["Phil Hartman", "Tom Hanks", "Jim Belushi", "John Larroquette"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Bruce Willis' co-lead in the 1988 mystery action film Sunset?",
"answ":"JAMES GARNER",
"answ2":"James Garner.",
"option":["James Garner", "Charlton Heston", "Charles Bronson", "Mel Gibson"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a legendary Western actor who teams up with a legendary lawman to solve a murder at the Academy Awards in 1929 Hollywood in what film?",
"answ":"SUNSET",
"answ2":"Sunset.",
"option":["Sunset", "Sunrise", "After the Sunset", "The Sunset Boys"],
},
{
"cat":"Bruce Willis",
"ques":"In Sunset, who plays the producer and studio head Alfie Alperin who wants to produce an epic Western about Wyatt Earp?",
"answ":"MALCOLM MCDOWELL",
"answ2":"Malcolm McDowell.",
"option":["Malcolm McDowell", "Charles Bronson", "Alan Arkin", "James Garner"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays John McClane's wife Holly in Die Hard?",
"answ":"BONNIE BEDELIA",
"answ2":"Bonnie Bedelia.",
"option":["Bonnie Bedelia", "Kirstie Alley", "Michelle Pfeiffer", "Carrie Fisher"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Hans Gruber in Die Hard?",
"answ":"ALAN RICKMAN",
"answ2":"Alan Rickman.",
"option":["Alan Rickman", "Jeremy Irons", "Tom Berenger", "Dolph Lundgren"],
},
{
"cat":"Bruce Willis",
"ques":"What is the name of the John McClane's limo driver in Die Hard?",
"answ":"ARGYLE",
"answ2":"Argyle.",
"option":["Argyle", "Marco", "Theo", "Harry"],
},
{
"cat":"Bruce Willis",
"ques":"In Look Who's Talking, who plays James, the cab driver who ultimately becomes Mikey's step-father?",
"answ":"JOHN TRAVOLTA",
"answ2":"John Travolta.",
"option":["John Travolta", "George Segal", "Kiefer Sutherland", "Steve Martin"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Mikey's mother in Look Who's Talking?",
"answ":"KIRSTIE ALLEY",
"answ2":"Kirstie Alley.",
"option":["Kirstie Alley", "Michelle Pfeiffer", "Diane Lane", "Sissy Spacek"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Mikey's birth father in Look Who's Talking?",
"answ":"GEORGE SEGAL",
"answ2":"George Segal.",
"option":["George Segal", "John Travolta", "Kiefer Sutherland", "Tom Berenger"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Grandpa Vincent in Look Who's Talking?",
"answ":"ABE VIGODA",
"answ2":"Abe Vigoda.",
"option":["Abe Vigoda", "Alan Arkin", "Michael Caine", "Kurtwood Smith"],
},
{
"cat":"Bruce Willis",
"ques":"The romantic comedy Look Who's Talking was released in what year?",
"answ":"1989",
"answ2":"1989.",
"option":["1989", "1988", "1992", "1985"],
},
{
"cat":"Bruce Willis",
"ques":"Who directed Die Hard 2?",
"answ":"RENNY HARLIN",
"answ2":"Renny Harlin.",
"option":["Renny Harlin", "John McTiernan", "Len Wiseman", "John Moore"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the lead villain Stuart in Die Hard 2?",
"answ":"WILLIAM SADLER",
"answ2":"William Sadler.",
"option":["William Sadler", "Jeremy Irons", "Alan Rickman", "Dolph Lundgren"],
},
{
"cat":"Bruce Willis",
"ques":"In what year was Look Who's Talking Too released?",
"answ":"1990",
"answ2":"1990.",
"option":["1990", "1988", "1993", "1995"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Joey, the baby gym instructor in Look Who's Talking Too?",
"answ":"GILBERT GOTTFRIED",
"answ2":"Gilbert Gottfried.",
"option":["Gilbert Gottfried", "Mel Brooks", "Jamie Foxx", "Damon Wayans"],
},
{
"cat":"Bruce Willis",
"ques":"Who voices Mikey's playmate Eddie in Look Who's Talking Too?",
"answ":"DAMON WAYANS",
"answ2":"Damon Wayans.",
"option":["Damon Wayans", "Jamie Foxx", "Eddie Murphy", "Mel Brooks"],
},
{
"cat":"Bruce Willis",
"ques":"Who make a cameo appearance in Look Who's Talking Too voicing Mr. Toilet Man?",
"answ":"MEL BROOKS",
"answ2":"Mel Brooks.",
"option":["Mel Brooks", "Gilbert Gottfried", "Steve Martin", "Chevy Chase"],
},
{
"cat":"Bruce Willis",
"ques":"What year was The Bonfire of the Vanities released?",
"answ":"1990",
"answ2":"1990.",
"option":["1990", "1988", "1992", "1994"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Wall Street bond trader Sherman McCoy in The Bonfire of the Vanities?",
"answ":"TOM HANKS",
"answ2":"Tom Hanks.",
"option":["Tom Hanks", "Bruce Willis", "Sean Penn", "Dan Aykroyd"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Southern belle gold digger Maria Ruskin in The Bonfire of the Vanities?",
"answ":"MELANIE GRIFFITH",
"answ2":"Melanie Griffith.",
"option":["Melanie Griffith", "Michelle Pfeiffer", "Nicole Kidman", "Julia Louis-Dreyfus"],
},
{
"cat":"Bruce Willis",
"ques":"What year was The Last Boy Scout released?",
"answ":"1991",
"answ2":"1991.",
"option":["1991", "1992", "1990", "1988"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Bruce Willis co-lead Jimmy Dix in The Last Boy Scout?",
"answ":"DAMON WAYANS",
"answ2":"Damon Wayans.",
"option":["Damon Wayans", "Jamie Foxx", "Eddie Murphy", "Blair Underwood"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the exotic dancer Cory in The Last Boy Scout?",
"answ":"HALLE BERRY",
"answ2":"Halle Berry.",
"option":["Halle Berry", "Vanessa Williams", "Jada Pinkett Smith", "Vivica A. Fox"],
},
{
"cat":"Bruce Willis",
"ques":"What year saw the release of the gangster film Billy Bathgate?",
"answ":"1991",
"answ2":"1991.",
"option":["1991", "1988", "1994", "1990"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the gangster that goes by the name Dutch Schultz in Billy Bathgate?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
"option":["Dustin Hoffman", "Bruce Willis", "Sean Penn", "Robert De Niro"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the beautiful Drew Preston in Billy Bathgate?",
"answ":"NICOLE KIDMAN",
"answ2":"Nicole Kidman.",
"option":["Nicole Kidman", "Melanie Griffith", "Demi Moore", "Michelle Pfeiffer"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays a master burglar and safecracker in what action comedy?",
"answ":"HUDSON HAWK",
"answ2":"Hudson Hawk.",
"option":["Hudson Hawk", "Billy Bathgate", "Dick Tracy", "Mortal Thoughts"],
},
{
"cat":"Bruce Willis",
"ques":"In what year was the action comedy Hudson Hawk released?",
"answ":"1991",
"answ2":"1991.",
"option":["1991", "1986", "1993", "1995"],
},
{
"cat":"Bruce Willis",
"ques":"You'll find the character of Tommy 'Five-Tone' Messina in what 90s action comedy?",
"answ":"HUDSON HAWK",
"answ2":"Hudson Hawk.",
"option":["Hudson Hawk", "Dick Tracy", "Snatch", "Lock, Stock and Two Smoking Barrels"],
},
{
"cat":"Bruce Willis",
"ques":"What 90s thriller stars Demi Moore, Glenne Headly, Bruce Willis and Harvey Keitel?",
"answ":"MORTAL THOUGHTS",
"answ2":"Mortal Thoughts.",
"option":["Mortal Thoughts", "Cape Fear", "Primal Fear", "The Hand that Rocks the Cradle"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays the lead Cynthia Kellogg in the 90s thriller Mortal Thoughts?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
"option":["Demi Moore", "Michelle Pfeiffer", "Nicole Kidman", "Melanie Griffith"],
},
{
"cat":"Bruce Willis",
"ques":"Who plays Detective John Woods in the 90s thriller Mortal Thoughts?",
"answ":"HARVEY KEITEL",
"answ2":"Harvey Keitel.",
"option":["Harvey Keitel", "Sean Penn", "Morgan Freeman", "Samuel L. Jackson"],
},
{
"cat":"Bruce Willis",
"ques":"Bruce Willis plays an abusive husband by the name of the Jimmy Urbanski in what 90s thriller?",
"answ":"MORTAL THOUGHTS",
"answ2":"Mortal Thoughts.",
"option":["Mortal Thoughts", "Billy Bathgate", "Primal Fear", "The Hand that Rocks the Cradle"],
},
];
r2Q77 = shuffle(r2Q77);