var r2Q78 = [
{
"cat":"Russell Crowe",
"ques":"Russell Crowe falls in love with an apprentice magician in which 1995 comedy?",
"answ":"ROUGH MAGIC",
"answ2":"Rough Magic.",
"option":["Rough Magic", "The Great Buck Howard", "The Escape Artist", "A Simple Wish"],
},
{
"cat":"Russell Crowe",
"ques":"Which film marked the first collaboration between Ron Howard and Russell Crowe?",
"answ":"A BEAUTIFUL MIND",
"answ2":"A Beautiful Mind.",
"option":["A Beautiful Mind", "Master and Commander", "Robin Hood", "Cinderella Man"],
},
{
"cat":"Russell Crowe",
"ques":"In the 1991 drama Proof, Russell Crowe befriends a blind photographer, played by which future MCU villain?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
"option":["Hugo Weaving", "Robert Redford", "Andy Serkis", "Ben Kingsley"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays a character by the name of Bud White in what 1990s crime drama?",
"answ":"LA CONFIDENTIAL",
"answ2":"LA Confidential.",
"option":["LA Confidential", "Heaven's Burning", "Millers Crossing", "Proof of Life"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays investigative reporter Cal McAffrey in what 2000s thriller?",
"answ":"STATE OF PLAY",
"answ2":"State of Play.",
"option":["State of Play", "Identity", "88 Minutes", "Frailty"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays a Captain Jack Aubrey in what 2000s adventure film?",
"answ":"MASTER AND COMMANDER",
"answ3":"MASTER AND COMMANDER THE FAR SIDE OF THE WORLD",
"answ2":"Master and Commander: The Far Side of the World.",
"option":["Master and Commander: The Far Side of the World", "Cold Mountain", "Peter Pan", "The Poseidon Adventure"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays an Australian farmer in what 2010s historical fiction war drama?",
"answ":"THE WATER DIVINER",
"answ2":"The Water Diviner.",
"option":["The Water Diviner", "The Flowers of War", "The Conspirator", "The Physician"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays the mayor of what U.S. city in the 2013 crime thriller Broken City?",
"answ":"NEW YORK CITY",
"answ3":"NEW YORK",
"answ2":"New York City.",
"option":["New York City", "Baltimore", "Boston", "Chicago"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays CIA Chief Ed Hoffman in which 2008 thriller?",
"answ":"BODY OF LIES",
"answ2":"Body of Lies.",
"option":["Body of Lies", "Proof of Life", "The Next Three Days", "State of Play"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays a neo-Nazi named Hando in what 1992 drama?",
"answ":"ROMPER STOMPER",
"answ2":"Romper Stomper.",
"option":["Romper Stomper", "No Way Back", "American History X", "Rough Magic"],
},
{
"cat":"Russell Crowe",
"ques":"In Gladiator, what animals are embossed on Maximus' armor?",
"answ":"HORSES",
"answ2":"Horses.",
"option":["Horses", "Falcons", "Eagles", "Bears"],
},
{
"cat":"Russell Crowe",
"ques":"Who directed Russell Crowe in the 2016 film The Nice Guys?",
"answ":"SHANE BLACK",
"answ2":"Shane Black.",
"option":["Shane Black", "David McKenzie", "Ridley Scott", "J.C. Chandor"],
},
{
"cat":"Russell Crowe",
"ques":"Who played Russell Crowe's enemy Prince John in the 2010 film Robin Hood?",
"answ":"OSCAR ISAAC",
"answ2":"Oscar Isaac.",
"option":["Oscar Isaac", "Tom Hardy", "Benedict Cumberbatch", "Tom Hiddleston"],
},
{
"cat":"Russell Crowe",
"ques":"Who directed Russell Crowe in the 1999 film The Insider?",
"answ":"MICHAEL MANN",
"answ2":"Michael Mann.",
"option":["Michael Mann", "Ridley Scott", "Tony Scott", "Shane Black"],
},
{
"cat":"Russell Crowe",
"ques":"Which actor earned an Academy Award nomination for the 2005 Russell Crowe film Cinderella Man?",
"answ":"PAUL GIAMATTI",
"answ2":"Paul Giamatti.",
"option":["Paul Giamatti", "Russell Crowe", "Jennifer Connelly", "Matt Dillon"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays which sport in the 1999 film Mystery, Alaska?",
"answ":"ICE HOCKEY",
"answ3":"HOCKEY",
"answ2":"Ice hockey.",
"option":["Hockey", "Baseball", "Football", "Bowling"],
},
{
"cat":"Russell Crowe",
"ques":"Who plays Russell Crowe's wife, who has been wrongly convicted of murder, in the 2010 thriller The Next Three Days?",
"answ":"ELIZABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":["Elizabeth Banks", "Michelle Pfeiffer", "Gwyneth Paltrow", "Michelle Monaghan"],
},
{
"cat":"Russell Crowe",
"ques":"What was the name of the mathematician played by Russell Crowe in the 2001 film A Beautiful Mind?",
"answ":"JOHN NASH",
"answ2":"John Nash.",
"option":["John Nash", "Gerald Lambeau", "Gunter Janek", "Max Cohen"],
},
{
"cat":"Russell Crowe",
"ques":"Who plays Fanny Chanel, the cafe owner Russell Crowe falls in love with in the drama A Good Year?",
"answ":"MARION COTILLARD",
"answ2":"Marion Cotillard.",
"option":["Marion Cotillard", "Juliette Binoche", "Julie Delpy", "Eva Green"],
},
{
"cat":"Russell Crowe",
"ques":"Who plays Marian opposite Russell Crowe in the 2010 action movie Robin Hood?",
"answ":"CATE BLANCHETT",
"answ2":"Cate Blanchett.",
"option":["Cate Blanchett", "Lena Headey", "Kate Winslet", "Rebecca Hall"],
},
{
"cat":"Russell Crowe",
"ques":"Who plays the congressman that reporter Russell Crowe is investigating in the 2009 film State of Play?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
"option":["Ben Affleck", "Christian Bale", "Alec Baldwin", "Liam Neeson"],
},
{
"cat":"Russell Crowe",
"ques":"Which actor plays the outlaw who takes over Russell Crowe's gang, after Crowe is arrested, in the western 3:10 to Yuma?",
"answ":"BEN FOSTER",
"answ2":"Ben Foster.",
"option":["Ben Foster", "Christian Bale", "Alan Tudyk", "Charlie Hunnam"],
},
{
"cat":"Russell Crowe",
"ques":"Who directed Russell Crowe in the 2006 film A Good Year?",
"answ":"RIDLEY SCOTT",
"answ2":"Ridley Scott.",
"option":["Ridley Scott", "Rob Reiner", "Woody Allen", "Garry Marshall"],
},
{
"cat":"Russell Crowe",
"ques":"What was the first name of the character played by Russell Crowe in the 2000 film 'Gladiator'?",
"answ":"MAXIMUS",
"answ2":"Maximus.",
"option":["Maximus", "Lucius", "Proximo", "Gracchus"],
},
{
"cat":"Russell Crowe",
"ques":"Who plays Russell Crowe's wife in 2013's Broken City?",
"answ":"CATHERINE ZETA JONES",
"answ3":"KATHERINE ZETA JONES",
"answ2":"Catherine Zeta-Jones.",
"option":["Catherine Zeta-Jones", "Kim Basinger", "Gina Gershon", "Salma Hayek"],
},
{
"cat":"Russell Crowe",
"ques":"Who played the slave dealer Proximo in Gladiator?",
"answ":"OLIVER REED",
"answ2":"Oliver Reed.",
"option":["Oliver Reed", "Djimon Hounsou", "Joaquin Phoenix", "Derek Jacobi"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays the villainous Pearly Soames in which 2014 fantasy film?",
"answ":"WINTER'S TALE",
"answ2":"Winter's Tale.",
"option":["Winter's Tale", "How to Train Your Dragon 2", "The Book of Life", "Jack the Giant Slayer"],
},
{
"cat":"Russell Crowe",
"ques":"Who played Marcus Aurelius in Gladiator?",
"answ":"RICHARD HARRIS",
"answ2":"Richard Harris.",
"option":["Richard Harris", "Joaquin Phoenix", "Oliver Reed", "Derek Jacobi"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays Detective Richie Roberts in which 2007 crime drama?",
"answ":"AMERICAN GANGSTER",
"answ2":"American Gangster.",
"option":["American Gangster", "Zodiac", "In the Valley of Elah", "Michael Clayton"],
},
{
"cat":"Russell Crowe",
"ques":"Which 'Game of Thrones' actor played Friar Tuck in the Russell Crowe film 'Robin Hood'?",
"answ":"MARK ADDY",
"answ2":"Mark Addy.",
"option":["Mark Addy", "Peter Dinklage", "Liam Cunningham", "John Bradley"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe plays a serial killer named SID 6.7 in which 1995 sci-fi film?",
"answ":"VIRTUOSITY",
"answ2":"Virtuosity.",
"option":["Virtuosity", "Tank Girl", "Screamers", "The City of Lost Children"],
},
{
"cat":"Russell Crowe",
"ques":"Russell Crowe gets married to Salma Hayek in which 1997 film?",
"answ":"BREAKING UP",
"answ2":"Breaking Up.",
"option":["Breaking Up", "Fools Rush In", "Four Rooms", "Timecode"],
},
{
"cat":"Russell Crowe",
"ques":"In the 2000 thriller Proof of Life, Russell Crowe plays a hostage negotiator helping which actress find her husband?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
"option":["Meg Ryan", "Julia Roberts", "Jennifer Lopez", "Helen Hunt"],
},
{
"cat":"Russell Crowe",
"ques":"Who directed Russell Crowe in the 2003 historical epic 'Master and Commander: The Far Side of the World'?",
"answ":"PETER WEIR",
"answ2":"Peter Weir.",
"option":["Peter Weir", "Gore Verbinski", "Ron Howard", "Edward Zwick"],
},
];
r2Q78 = shuffle(r2Q78);