var nineties = [
{
"cat":"90s",
"ques":"Who played the titular character in Maverick?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"90s",
"ques":"Spike Lee directed John Leguizamo, Adrien Brody and Mira Sorvino in what 1999 crime film about the 1977 David Berkowitz serial murders?",
"answ":"SUMMER OF SAM",
"answ2":"Summer of Sam.",
},
{
"cat":"90s",
"ques":"Who starred as Archangel Gabriel in the 1990 film The Prophecy?",
"answ":"CHRISTOPHER WALKEN",
"answ2":"Christopher Walken.",
},
{
"cat":"90s",
"ques":"Who stars as Julie Pierce, Mr. Miyagi's new pupil in 1994's The Next Karate Kid?",
"answ":"HILARY SWANK",
"answ2":"Hilary Swank.",
},
{
"cat":"90s",
"ques":"In what 90s film does Jeff Goldblum say the line: 'What have they got in there, King Kong?'",
"answ":"JURASSIC PARK",
"answ2":"Jurassic Park.",
},
{
"cat":"90s",
"ques":"What 90s spoof comedy had a sequel with the subtitle Part Deux?",
"answ":"HOT SHOTS",
"answ2":"Hot Shots!.",
},
{
"cat":"90s",
"ques":"Who stars as the lead character Hawkeye in the 1992 historical drama The Last of the Mohicans?",
"answ":"DANIEL DAY LEWIS",
"answ2":"Daniel Day-Lewis.",
},
{
"cat":"90s",
"ques":"Which actor has roles in the following 90s films: The Insider, The Quick and the Dead and L.A. Confidential?",
"answ":"RUSSELL CROWE",
"answ3":"RUSSELL CROW",
"answ2":"Russell Crowe.",
},
{
"cat":"90s",
"ques":"Who stars as a nomad simply known as The Postman in 1997's The Postman?",
"answ":"KEVIN COSTNER",
"answ2":"Kevin Costner.",
},
{
"cat":"90s",
"ques":"Which James Bond actor plays King Arthur in the 1995 film First Knight?",
"answ":"SEAN CONNERY",
"answ3":"SEAN CONNORY",
"answ2":"Sean Connery.",
},
{
"cat":"90s",
"ques":"In what 90s comedy will you hear a character say: 'Oh, and this one time, at band camp...'?",
"answ":"AMERICAN PIE",
"answ2":"American Pie.",
},
{
"cat":"90s",
"ques":"Tobey Maguire and Reese Witherspoon star as two teenage siblings who find themselves in a 1950s sitcom, in what 1998 film?",
"answ":"PLEASANTVILLE",
"answ2":"Pleasantville.",
},
{
"cat":"90s",
"ques":"Which MCU actor played a tabloid reporter named Wayne Gale in the 1994 film Natural Born Killers?",
"answ":"ROBERT DOWNEY JR",
"answ3":"ROBERT DOWNEY JUNIOR",
"answ2":"Robert Downey Jr.",
},
{
"cat":"90s",
"ques":"In what 90s film will you find the characters Marge Gunderson and Jerry Lundergaard?",
"answ":"FARGO",
"answ2":"Fargo.",
},
{
"cat":"90s",
"ques":"Who plays small-town detective Marge Gunderson in 1996's Fargo?",
"answ":"FRANCES MCDORMAND",
"answ3":"FRANCIS MCDORMAND",
"answ2":"Frances McDormand.",
},
{
"cat":"90s",
"ques":"What 1999 film stars Reese Witherspoon as an overly ambitious high school student who runs for class president named Tracy Flick?",
"answ":"ELECTION",
"answ2":"Election.",
},
{
"cat":"90s",
"ques":"Who plays Tom Mullen, whose son is kidnapped at a science fair in Central Park, in 1996's Ransom?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"90s",
"ques":"Which actress starred as Angela Bennett in the 90s tech thriller The Net?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
},
{
"cat":"90s",
"ques":"Tom Cruise plays Lt. Daniel Kaffee in what 1992 film?",
"answ":"A FEW GOOD MEN",
"answ2":"A Few Good Men.",
},
{
"cat":"90s",
"ques":"Which actor starred in the 90s films Cadillac Man, Toys and Jakob the Liar?",
"answ":"ROBIN WILLIAMS",
"answ2":"Robin Williams.",
},
{
"cat":"90s",
"ques":"Which Oscar nominee stars in Strange Days as Lenny Nero?",
"answ":"RALPH FIENNES",
"answ3":"RALPH FIENES",
"answ2":"Ralph Fiennes.",
},
{
"cat":"90s",
"ques":"Which actress plays Theresa Osborne, a former reporter and researcher for the Chicago Tribune in Message in a Bottle?",
"answ":"ROBIN WRIGHT",
"answ2":"Robin Wright.",
},
{
"cat":"90s",
"ques":"Who directed 1997's The Lost World: Jurassic Park?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"90s",
"ques":"Who plays the role of Lester 'Worm' Murphy in 1998's Rounders?",
"answ":"EDWARD NORTON",
"answ2":"Edward Norton.",
},
{
"cat":"90s",
"ques":"Shelley Duvall and Christopher Lloyd play a married couple in what 90s Hulk Hogan film?",
"answ":"SUBURBAN COMMANDO",
"answ2":"Suburban Commando.",
},
{
"cat":"90s",
"ques":"John Cusack plays Martin, a hitman who is depressed and disillusioned with his work, in what movie?",
"answ":"GROSSE POINTE BLANK",
"answ3":"GROSSE POINT BLANK",
"answ2":"Grosse Pointe Blank.",
},
{
"cat":"90s",
"ques":"What blockbuster, released in 1990, has a main character named Kevin McCallister?",
"answ":"HOME ALONE",
"answ2":"Home Alone.",
},
{
"cat":"90s",
"ques":"Robert De Niro plays a gangster named Sam 'Ace' Rothstein in what 1995 crime film?",
"answ":"CASINO",
"answ2":"Casino.",
},
{
"cat":"90s",
"ques":"Who co-starred opposite Charlie Sheen in 1990's Men At Work?",
"answ":"EMILIO ESTEVEZ",
"answ2":"Emilio Estevez.",
},
{
"cat":"90s",
"ques":"In Jurassic Park, who plays park owner John Hammond?",
"answ":"RICHARD ATTENBOROUGH",
"answ2":"Richard Attenborough.",
},
{
"cat":"90s",
"ques":"What music star played a psychotic character named Bishop in the 1992 crime-thriller Juice?",
"answ":"TUPAC SHAKUR",
"answ3":"TUPAC",
"answ2":"Tupac Shakur.",
},
{
"cat":"90s",
"ques":"In Forrest Gump, Forrest meets which member of The Beatles?",
"answ":"JOHN LENNON",
"answ2":"John Lennon.",
},
{
"cat":"90s",
"ques":"Who played the titular father in the 1991's remake of Father of the Bride?",
"answ":"STEVE MARTIN",
"answ2":"Steve Martin.",
},
{
"cat":"90s",
"ques":"What 90s romantic drama stars Sarah Michelle Geller, Ryan Philippe and Reese Witherspoon?",
"answ":"CRUEL INTENTIONS",
"answ2":"Cruel Intentions.",
},
{
"cat":"90s",
"ques":"Who plays Fred Flintstone in 1994's The Flintstones?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
},
{
"cat":"90s",
"ques":"This 1997 crime drama was based off a true story and starred Al Pacino and Johnny Depp.",
"answ":"DONNIE BRASCO",
"answ3":"DONNY BRASCO",
"answ2":"Donnie Brasco.",
},
{
"cat":"90s",
"ques":"Al Pacino and Russell Crowe star in what Michael Mann film about exposing Big Tobacco on 60 Minutes?",
"answ":"THE INSIDER",
"answ2":"The Insider.",
},
{
"cat":"90s",
"ques":"What actor plays Furious Styles, father of Cuba Gooding Jr.'s character in Boyz n the Hood?",
"answ":"LAURENCE FISHBURNE",
"answ3":"LAURENCE FISHBURN",
"answ2":"Laurence Fishburne.",
},
{
"cat":"90s",
"ques":"What is the title of the 1991 sequel to Bill and Ted's Excellent Adventure?",
"answ":"BILL AND TED'S BOGUS JOURNEY",
"answ3":"BILL AND TEDS BOGUS JOURNEY",
"answ2":"Bill & Ted's Bogus Journey.",
},
{
"cat":"90s",
"ques":"After being in London, An American Werewolf went where in the sequel?",
"answ":"PARIS",
"answ2":"Paris.",
},
{
"cat":"90s",
"ques":"In 1995's Casino, who plays De Niro's wife Ginger McKenna?",
"answ":"SHARON STONE",
"answ2":"Sharon Stone.",
},
{
"cat":"90s",
"ques":"Who directed 1995's The American President?",
"answ":"ROB REINER",
"answ2":"Rob Reiner.",
},
{
"cat":"90s",
"ques":"What 90s teen drama starred Tyrin Turner, Jada Pinkett, Larenz Tate and Samuel L. Jackson?",
"answ":"MENACE II SOCIETY",
"answ3":"MENACE TO SOCIETY",
"answ2":"Menace II Society.",
},
{
"cat":"90s",
"ques":"What 90s action/thriller stars Steven Seagal, Kurt Russell and Halle Berry?",
"answ":"EXECUTIVE DECISION",
"answ2":"Executive Decision.",
},
{
"cat":"90s",
"ques":"Jeff Goldblum famously says the line: 'Must go faster...' in both Jurassic Park and what other 90s film?",
"answ":"INDEPENDENCE DAY",
"answ2":"Independence Day.",
},
{
"cat":"90s",
"ques":"Who plays Walter Sobchak in The Big Lebowski?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
},
{
"cat":"90s",
"ques":"Robert Benton directed what 90s crime film starring Bruce Willis, Dustin Hoffman, Loren Dean and Nicole Kidman?",
"answ":"BILLY BATHGATE",
"answ2":"Billy Bathgate.",
},
{
"cat":"90s",
"ques":"High school student Dave, tells his parents that his new friend Link is a foreign exchange student from Estonia in what 90s comedy?",
"answ":"ENCINO MAN",
"answ2":"Encino Man.",
},
{
"cat":"90s",
"ques":"Who stars as Tracy Flick, an irritating overachiever who goes to great lengths to become the president of the student council in 1999's Election?",
"answ":"REESE WITHERSPOON",
"answ2":"Reese Witherspoon.",
},
{
"cat":"90s",
"ques":"What child actor stars alongside a villainous Macaulay Culkin in 1993's The Good Son?",
"answ":"ELIJAH WOOD",
"answ2":"Elijah Wood.",
},
{
"cat":"90s",
"ques":"Actor/martial artist Ernie Reyes Jr. played the lead role of Johnny in what 1993 family-action film?",
"answ":"SURF NINJAS",
"answ2":"Surf Ninjas.",
},
{
"cat":"90s",
"ques":"In 10 Things I Hate About You, who plays the new student Cameron James who is trying to get a date with Bianca?",
"answ":"JOSEPH GORDON LEVITT",
"answ2":"Joseph Gordon-Levitt.",
},
{
"cat":"90s",
"ques":"Who directed the 1995 crime drama Heat?",
"answ":"MICHAEL MANN",
"answ2":"Michael Mann.",
},
{
"cat":"90s",
"ques":"What 90s movie features Meg Ryan and Nicolas Cage?",
"answ":"CITY OF ANGELS",
"answ2":"City of Angels.",
},
{
"cat":"90s",
"ques":"Which actor becomes embroiled in a nightmarish friendship with Jim Carrey in The Cable Guy?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
},
{
"cat":"90s",
"ques":"What 1999 drama follows an 18-year-old girl in the 1960s who is committed to a woman's mental institution?",
"answ":"GIRL INTERRUPTED",
"answ3":"GIRL  INTERRUPTED",
"answ2":"Girl Interrupted.",
},
{
"cat":"90s",
"ques":"Who directed Independence Day?",
"answ":"ROLAND EMMERICH",
"answ2":"Roland Emmerich.",
},
{
"cat":"90s",
"ques":"What 90s sci-fi horror film stars Laurence Fishburne and Sam Neill?",
"answ":"EVENT HORIZON",
"answ2":"Event Horizon.",
},
{
"cat":"90s",
"ques":"Robin Williams plays Sean Maguire in what Academy Award winning film?",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
},
{
"cat":"90s",
"ques":"What 90s war film starring Jeff Daniels was shot on the battlefields where the actual events took place?",
"answ":"GETTYSBURG",
"answ2":"Gettysburg.",
},
{
"cat":"90s",
"ques":"What character name does Brad Pitt go by in Fight Club?",
"answ":"TYLER DURDEN",
"answ2":"Tyler Durden.",
},
{
"cat":"90s",
"ques":"Who played the character Dewey in Scream?",
"answ":"DAVID ARQUETTE",
"answ2":"David Arquette.",
},
{
"cat":"90s",
"ques":"What 1998 comedy takes place at a graduation party and starred Jennifer Love Hewitt, Ethan Embry, Seth Green and Lauren Ambrose?",
"answ":"CAN'T HARDLY WAIT",
"answ2":"Can't Hardly Wait.",
},
{
"cat":"90s",
"ques":"Who plays Doc Holliday in Tombstone?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
},
{
"cat":"90s",
"ques":"Who plays the California Angels manager George Knox in 1994's Angels in the Outfield?",
"answ":"DANNY GLOVER",
"answ2":"Danny Glover.",
},
{
"cat":"90s",
"ques":"Who plays car salesman Jerry Lundegaard in Fargo?",
"answ":"WILLIAM H MACY",
"answ2":"William H. Macy.",
},
{
"cat":"90s",
"ques":"In Space Jam, who voices the main villain, Swackhammer?",
"answ":"DANNY DEVITO",
"answ3":"DANNY DE VITO",
"answ2":"Danny DeVito.",
},
{
"cat":"90s",
"ques":"Who plays the newly trained Zorro in The Mask of Zorro?",
"answ":"ANTONIO BANDERAS",
"answ2":"Antonio Banderas.",
},
{
"cat":"90s",
"ques":"Guy Pierce played a character named Ed Exley in what 90s crime drama?",
"answ":"LA CONFIDENTIAL",
"answ3":"L A CONFIDENTIAL",
"answ2":"L.A. Confidential.",
},
{
"cat":"90s",
"ques":"In Air Force One, who played the leader of the Russian terrorists who hijacked the plane?",
"answ":"GARY OLDMAN",
"answ2":"Gary Oldman.",
},
{
"cat":"90s",
"ques":"Who plays student Max Fischer in the movie Rushmore?",
"answ":"JASON SCHWARTZMAN",
"answ3":"JASON SCHWARTZMANN",
"answ2":"Jason Schwartzman.",
},
{
"cat":"90s",
"ques":"In The Boondock Saints, who plays FBI agent Paul Smecker who is assigned to the murders linked to the MacManus brothers?",
"answ":"WILLEM DAFOE",
"answ3":"WILLEM DEFOE",
"answ2":"Willem Dafoe.",
},
{
"cat":"90s",
"ques":"Which film sees Harvey Keitel investigate a drug-related shooting involving Mekhi Phifer and Isaiah Washington?",
"answ":"CLOCKERS",
"answ2":"Clockers.",
},
{
"cat":"90s",
"ques":"What hip-hop legend plays camera man Danny Rich in 1997's Anaconda?",
"answ":"ICE CUBE",
"answ2":"Ice Cube.",
},
{
"cat":"90s",
"ques":"Who plays quarterback Jonathan 'Mox' Moxon in Varsity Blues?",
"answ":"JAMES VAN DER BEEK",
"answ3":"JAMES VANDERBEEK",
"answ2":"James Van Der Beek.",
},
{
"cat":"90s",
"ques":"Who plays Mr. Brown in Reservoir Dogs?",
"answ":"QUENTIN TARANTINO",
"answ2":"Quentin Tarantino.",
},
{
"cat":"90s",
"ques":"What legendary composer was played by Gary Oldman in the film Immortal Beloved?",
"answ":"BEETHOVEN",
"answ3":"LUDWIG VON BEETHOVEN",
"answ2":"Ludwig van Beethoven.",
},
{
"cat":"90s",
"ques":"Elijah Wood is sent off to spend the summer with his Uncle Porter in 1996's Flipper. What Aussie plays Porter?",
"answ":"PAUL HOGAN",
"answ2":"Paul Hogan.",
},
{
"cat":"90s",
"ques":"Bruce Willis protects a nine-year old autistic savant that deciphered a top secret code in what 90s movie?",
"answ":"MERCURY RISING",
"answ2":"Mercury Rising.",
},
{
"cat":"90s",
"ques":"Gene Hackman plays Captain Frank Ramsey in what flick?",
"answ":"CRIMSON TIDE",
"answ2":"Crimson Tide.",
},
{
"cat":"90s",
"ques":"What 1999 movie stars John Travolta and Madeleine Stowe as investigators of a murder in the army?",
"answ":"THE GENERAL'S DAUGHTER",
"answ3":"GENERAL'S DAUGHTER",
"answ2":"The General's Daughter.",
},
{
"cat":"90s",
"ques":"Who played thief Simon Templar in 1997's The Saint?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
},
{
"cat":"90s",
"ques":"What screen name does Mark Wahlberg give himself in Boogie Nights?",
"answ":"DIRK DIGGLER",
"answ2":"Dirk Diggler.",
},
{
"cat":"90s",
"ques":"You'll find the character of Stanley Ipkiss in what 90s comedy?",
"answ":"THE MASK",
"answ2":"The Mask.",
},
{
"cat":"90s",
"ques":"Which actor plays Zorg in The Fifth Element?",
"answ":"GARY OLDMAN",
"answ2":"Gary Oldman.",
},
{
"cat":"90s",
"ques":"Who plays Faye, the love interest of the lead guitarist/singer Jimmy, in That Thing you Do!?",
"answ":"LIV TYLER",
"answ2":"Liv Tyler.",
},
{
"cat":"90s",
"ques":"What was the weapon of choice used by the killer that Michael Douglas is trying to track down in Basic Instinct?",
"answ":"ICE PICK",
"answ2":"Ice Pick.",
},
{
"cat":"90s",
"ques":"What 90s film features wrongfully accused convict Andy Dufresne?",
"answ":"THE SHAWSHANK REDEMPTION",
"answ3":"SHAWSHANK REDEMPTION",
"answ2":"The Shawshank Redemption.",
},
{
"cat":"90s",
"ques":"What NBA superstar played the genie Kazaam in Kazaam?",
"answ":"SHAQUILLE O'NEAL",
"answ3":"SHAQ",
"answ2":"Shaquille O'Neal.",
},
{
"cat":"90s",
"ques":"Who plays Secret Service Agent Frank Horrigan in 1993's In the Line of Fire?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
},
{
"cat":"90s",
"ques":"Who played Sarah Mathews in the 90s comedy film Made in America?",
"answ":"WHOOPI GOLDBERG",
"answ3":"WHOOPIE GOLDBERG",
"answ2":"Whoopi Goldberg.",
},
{
"cat":"90s",
"ques":"Who played Hal Jackson in the 90s comedy film Made in America?",
"answ":"TED DANSON",
"answ2":"Ted Danson.",
},
{
"cat":"90s",
"ques":"What James Spader 90s sci-fi film went on to spawn a 10 season long TV series and 2 spin-off series?",
"answ":"STARGATE",
"answ2":"Stargate.",
},
{
"cat":"90s",
"ques":"Who plays the title character in the 1999 film The 13th Warrior?",
"answ":"ANTONIO BANDERAS",
"answ2":"Antonio Banderas.",
},
{
"cat":"90s",
"ques":"What 1996 film directed by Nora Ephron stars John Travolta as a boozy archangel?",
"answ":"MICHAEL",
"answ2":"Michael.",
},
{
"cat":"90s",
"ques":"In what 1997 comedy do British steelworkers form a male-stripper act?",
"answ":"THE FULL MONTY",
"answ3":"FULL MONTY",
"answ2":"The Full Monty.",
},
{
"cat":"90s",
"ques":"Who played TV meteorologist Harris K. Telemacher in the film L.A. Story?",
"answ":"STEVE MARTIN",
"answ2":"Steve Martin.",
},
{
"cat":"90s",
"ques":"Who plays the younger brother of Edward Norton's character in 1998's American History X?",
"answ":"EDWARD FURLONG",
"answ2":"Edward Furlong.",
},
{
"cat":"90s",
"ques":"What 90s film is about a scheme to cover up a presidential scandal by producing a fake war?",
"answ":"WAG THE DOG",
"answ2":"Wag the Dog.",
},
{
"cat":"90s",
"ques":"Liam Neeson plays Dr. David Marrow who intends to study the psychological response to fear in what 90s horror film?",
"answ":"THE HAUNTING",
"answ2":"The Haunting.",
},
{
"cat":"90s",
"ques":"Who starred opposite Mel Gibson as Jimmy Shaker, a NYPD detective turned kidnapper in 1996's Ransom?",
"answ":"GARY SINISE",
"answ2":"Gary Sinise.",
},
{
"cat":"90s",
"ques":"The Long Kiss Goodnight stars which actress as a schoolteacher who has a past as an assassin?",
"answ":"GEENA DAVIS",
"answ3":"GINA DAVIS",
"answ2":"Geena Davis.",
},
{
"cat":"90s",
"ques":"Danny Glover manages a Major League Baseball team that includes pitcher Tony Danza in what 1994 movie?",
"answ":"ANGELS IN THE OUTFIELD",
"answ2":"Angels in the Outfield.",
},
{
"cat":"90s",
"ques":"Tim Curry plays the devious Cardinal Richelieu in what 1993 Disney film?",
"answ":"THE THREE MUSKETEERS",
"answ3":"THREE MUSKETEERS",
"answ2":"The Three Musketeers.",
},
{
"cat":"90s",
"ques":"In A Few Good Men, what order does Jack Nicholson give his men that led to the death of Marine Private Santiago?",
"answ":"CODE RED",
"answ2":"Code Red.",
},
{
"cat":"90s",
"ques":"What country did the Turtles time travel back to in Teenage Mutant Ninja Turtles III?",
"answ":"JAPAN",
"answ2":"Japan.",
},
{
"cat":"90s",
"ques":"In 1998's Dark City, who played Inspector Frank Bumstead?",
"answ":"WILLIAM HURT",
"answ2":"William Hurt.",
},
{
"cat":"90s",
"ques":"What 1994 film centers around an optimistic equine hero that was based on a 1877 novel?",
"answ":"BLACK BEAUTY",
"answ2":"Black Beauty.",
},
{
"cat":"90s",
"ques":"What 90s spoof film features Charlie Sheen, Jon Cryer and Ryan Stiles?",
"answ":"HOT SHOTS",
"answ2":"Hot Shots!.",
},
{
"cat":"90s",
"ques":"Who played Mel Gibson's father in 1994's Maverick?",
"answ":"JAMES GARNER",
"answ2":"James Garner.",
},
{
"cat":"90s",
"ques":"What 1999 movie features a man with supernatural powers and a mouse named Mr. Jingles?",
"answ":"THE GREEN MILE",
"answ3":"GREEN MILE",
"answ2":"The Green Mile.",
},
{
"cat":"90s",
"ques":"A professor discovers a rubber-like super-bouncy substance in what 90s family film?",
"answ":"FLUBBER",
"answ2":"Flubber.",
},
{
"cat":"90s",
"ques":"The film Backdraft features two firefighter brothers, played by Kurt Russell and ____",
"answ":"WILLIAM BALDWIN",
"answ3":"BILLY BALDWIN",
"answ2":"William Baldwin.",
},
{
"cat":"90s",
"ques":"Who directed and starred as Hamlet, in 1996's Hamlet?",
"answ":"KENNETH BRANAGH",
"answ3":"KENNETH BRANAUGH",
"answ2":"Kenneth Branagh.",
},
{
"cat":"90s",
"ques":"Who plays Keanu Reeves' love interest in Point Break?",
"answ":"LORI PETTY",
"answ2":"Lori Petty.",
},
{
"cat":"90s",
"ques":"What 80s star played Joe Pesci's nephew on trial for murder in My Cousin Vinny?",
"answ":"RALPH MACCHIO",
"answ3":"RALPH MACHIO",
"answ2":"Ralph Macchio.",
},
{
"cat":"90s",
"ques":"Who directed Val Kilmer as Jim Morrison in 1991's The Doors?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
},
{
"cat":"90s",
"ques":"Michael Douglas and Sean Penn played brothers in which film?",
"answ":"THE GAME",
"answ2":"The Game.",
},
{
"cat":"90s",
"ques":"Who played Stu Macher in 1996's Scream?",
"answ":"MATTHEW LILLARD",
"answ2":"Matthew Lillard.",
},
{
"cat":"90s",
"ques":"Who played John Connor in Terminator 2 Judgment Day?",
"answ":"EDWARD FURLONG",
"answ2":"Edward Furlong.",
},
{
"cat":"90s",
"ques":"What 1993 movie paired Jack Lemmon and Walter Matthau as the best of enemies until something came between?",
"answ":"GRUMPY OLD MEN",
"answ2":"Grumpy Old Men.",
},
{
"cat":"90s",
"ques":"Which 90's action film features criminals with nicknames like Diamond Dog and Baby-O?",
"answ":"CON AIR",
"answ2":"Con Air.",
},
{
"cat":"90s",
"ques":"What popular comedian played a teacher in The Faculty?",
"answ":"JON STEWART",
"answ2":"Jon Stewart.",
},
{
"cat":"90s",
"ques":"Who stars as the lead actress in the 1995 pirate film Cutthroat Island?",
"answ":"GEENA DAVIS",
"answ3":"GINA DAVIS",
"answ2":"Geena Davis.",
},
{
"cat":"90s",
"ques":"Who is the assassination target in the 1993 film In the Line Of Fire?",
"answ":"US PRESIDENT",
"answ3":"THE US PRESIDENT",
"answ2":"The U.S. President.",
},
{
"cat":"90s",
"ques":"Set on a farm, this 1993 animated musical is based on a book by E.B. White.",
"answ":"CHARLOTTE'S WEB",
"answ3":"CHARLOTTES WEB",
"answ2":"Charlotte's Web.",
},
];
var r2Q8 = [
{
"cat":"90s",
"ques":"What dessert does Hamilton 'Ham' Porter teach Scotty Smalls to make in The Sandlot?",
"answ":"S'MORES",
"answ3":"SMORES",
"answ2":"S'mores.",
"option":"<button id=corop class=buttons003 onclick=qcor()>S'mores</button><button id=incop2 class=buttons003 onclick=qinc()>Tiramisu</button><button id=incop3 class=buttons003 onclick=qinc()>Cheesecake</button><button id=incop4 class=buttons003 onclick=qinc()>Panna cotta</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Lancelot in First Knight?",
"answ":"RICHARD GERE",
"answ2":"Richard Gere.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sean Connery</button><button id=incop2 class=buttons003 onclick=qinc()>Gerard Butler</button><button id=corop class=buttons003 onclick=qcor()>Richard Gere</button><button id=incop4 class=buttons003 onclick=qinc()>Aaron Eckhart</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the title role in the 1995 remake of Sabrina?",
"answ":"JULIA ORMOND",
"answ2":"Julia Ormond.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Julia Ormond</button><button id=incop2 class=buttons003 onclick=qinc()>Lauren Holly</button><button id=incop3 class=buttons003 onclick=qinc()>Julia Roberts</button><button id=incop4 class=buttons003 onclick=qinc()>Laura Dern</button><br/>",
},
{
"cat":"90s",
"ques":"Which 1997 film features Cyrus The Virus, Diamond Dog and Johnny 23?",
"answ":"CON AIR",
"answ2":"Con Air.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Con Air</button><button id=incop2 class=buttons003 onclick=qinc()>Men in Black</button><button id=incop3 class=buttons003 onclick=qinc()>The Fifth Element</button><button id=incop4 class=buttons003 onclick=qinc()>Starship Troopers</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays caveman Link in Encino Man?",
"answ":"BRENDAN FRASER",
"answ2":"Brendan Fraser.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sean Astin</button><button id=incop2 class=buttons003 onclick=qinc()>Charlie Sheen</button><button id=incop3 class=buttons003 onclick=qinc()>Pauly Shore</button><button id=corop class=buttons003 onclick=qcor()>Brendan Fraser</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays Jake Gyllenhaal's stern father in October Sky?",
"answ":"CHRIS COOPER",
"answ2":"Chris Cooper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kevin Spacey</button><button id=incop2 class=buttons003 onclick=qinc()>Willem Dafoe</button><button id=incop3 class=buttons003 onclick=qinc()>Brian Cox</button><button id=corop class=buttons003 onclick=qcor()>Chris Cooper</button><br/>",
},
{
"cat":"90s",
"ques":"What was the name of Milla Jovovich's character in The Fifth Element?",
"answ":"LEELOO",
"answ2":"Leeloo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lila</button><button id=corop class=buttons003 onclick=qcor()>Leeloo</button><button id=incop3 class=buttons003 onclick=qinc()>Samantha</button><button id=incop4 class=buttons003 onclick=qinc()>Lilly</button><br/>",
},
{
"cat":"90s",
"ques":"In which film will you find Colonel Nathan Jessup?",
"answ":"A FEW GOOD MEN",
"answ2":"A Few Good Men.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Rock</button><button id=corop class=buttons003 onclick=qcor()>A Few Good Men</button><button id=incop3 class=buttons003 onclick=qinc()>Con Air</button><button id=incop4 class=buttons003 onclick=qinc()>Speed</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the famous movie star that John Travolta pitches his movie idea to in Get Shorty?",
"answ":"DANNY DEVITO",
"answ2":"Danny DeVito.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=incop2 class=buttons003 onclick=qinc()>Rene Russo</button><button id=corop class=buttons003 onclick=qcor()>Danny DeVito</button><button id=incop4 class=buttons003 onclick=qinc()>James Woods</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed Sense and Sensibility?",
"answ":"ANG LEE",
"answ2":"Ang Lee.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cary Fukunaga</button><button id=incop2 class=buttons003 onclick=qinc()>Joe Wright</button><button id=corop class=buttons003 onclick=qcor()>Ang Lee</button><button id=incop4 class=buttons003 onclick=qinc()>Mira Nair</button><br/>",
},
{
"cat":"90s",
"ques":"Who played U.S. Customs agent Dave Kujan in The Usual Suspects?",
"answ":"CHAZZ PALMINTERI",
"answ2":"Chazz Palminteri.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Benicio del Toro</button><button id=corop class=buttons003 onclick=qcor()>Chazz Palminteri</button><button id=incop3 class=buttons003 onclick=qinc()>Morgan Freeman</button><button id=incop4 class=buttons003 onclick=qinc()>Stephen Baldwin</button><br/>",
},
{
"cat":"90s",
"ques":"Who is transformed into a prom princess in She's All That?",
"answ":"RACHAEL LEIGH COOK",
"answ2":"Rachael Leigh Cook.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Drew Barrymore</button><button id=corop class=buttons003 onclick=qcor()>Rachael Leigh Cook</button><button id=incop3 class=buttons003 onclick=qinc()>Blake Lively</button><button id=incop4 class=buttons003 onclick=qinc()>Christina Applegate</button><br/>",
},
{
"cat":"90s",
"ques":"During which event was Mickey to be interviewed in Natural Born Killers?",
"answ":"SUPER BOWL",
"answ3":"THE SUPER BOWL",
"answ2":"Super Bowl.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christmas Eve</button><button id=corop class=buttons003 onclick=qcor()>Super Bowl</button><button id=incop3 class=buttons003 onclick=qinc()>Airing of Cheers</button><button id=incop4 class=buttons003 onclick=qinc()>Beauty pageant</button><br/>",
},
{
"cat":"90s",
"ques":"Ryan Philippe and Neve Campbell starred in which film about a popular New York City nightclub?",
"answ":"54",
"answ2":"54.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Company</button><button id=corop class=buttons003 onclick=qcor()>54</button><button id=incop3 class=buttons003 onclick=qinc()>Cruel Intentions</button><button id=incop4 class=buttons003 onclick=qinc()>Homegrown</button><br/>",
},
{
"cat":"90s",
"ques":"Who played the father of the Boondock Saints?",
"answ":"BILLY CONNOLLY",
"answ2":"Billy Connolly.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Billy Connolly</button><button id=incop2 class=buttons003 onclick=qinc()>Willem Dafoe</button><button id=incop3 class=buttons003 onclick=qinc()>Peter Fonda</button><button id=incop4 class=buttons003 onclick=qinc()>John Cleese</button><br/>",
},
{
"cat":"90s",
"ques":"Which famous artist paints Danielle's portrait in the romantic fantasy Ever After?",
"answ":"LEONARDO DA VINCI",
"answ2":"Leonardo da Vinci.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michelangelo</button><button id=corop class=buttons003 onclick=qcor()>Leonardo da Vinci</button><button id=incop3 class=buttons003 onclick=qinc()>Raphael</button><button id=incop4 class=buttons003 onclick=qinc()>Vincent van Gogh</button><br/>",
},
{
"cat":"90s",
"ques":"What actor makes a cameo as Mia and Vincent's waiter at Jack Rabbit Slim's in Pulp Fiction?",
"answ":"STEVE BUSCEMI",
"answ2":"Steve Buscemi.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Steve Buscemi</button><button id=incop2 class=buttons003 onclick=qinc()>Tim Roth</button><button id=incop3 class=buttons003 onclick=qinc()>Kurt Russell</button><button id=incop4 class=buttons003 onclick=qinc()>Brad Pitt</button><br/>",
},
{
"cat":"90s",
"ques":"What actress played Julia Roberts' sister in 1995's Something to Talk About?",
"answ":"KYRA SEDGWICK",
"answ3":"KYRA SEDGEWICK",
"answ2":"Kyra Sedgwick.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kyra Sedgwick</button><button id=incop2 class=buttons003 onclick=qinc()>Mary-Louise Parker</button><button id=incop3 class=buttons003 onclick=qinc()>Nancy Travis</button><button id=incop4 class=buttons003 onclick=qinc()>Annabella Sciorra</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Romeo in 1996's Romeo + Juliet?",
"answ":"LEONARDO DICAPRIO",
"answ2":"Leonardo DiCaprio.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brad Pitt</button><button id=incop2 class=buttons003 onclick=qinc()>Johnny Depp</button><button id=corop class=buttons003 onclick=qcor()>Leonardo DiCaprio</button><button id=incop4 class=buttons003 onclick=qinc()>Edward Norton</button><br/>",
},
{
"cat":"90s",
"ques":"What is the name of Keanu Reeves' character in Point Break?",
"answ":"JOHNNY UTAH",
"answ2":"Johnny Utah.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Angelo Pappas</button><button id=incop2 class=buttons003 onclick=qinc()>Thomas Anderson</button><button id=corop class=buttons003 onclick=qcor()>Johnny Utah</button><button id=incop4 class=buttons003 onclick=qinc()>Jack Traven</button><br/>",
},
{
"cat":"90s",
"ques":"In The Big Lebowski, what was the Dude doing when the nihilists broke into his house?",
"answ":"BATHING",
"answ3":"TAKING A BATH",
"answ2":"Bathing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shaving</button><button id=incop2 class=buttons003 onclick=qinc()>Sleeping</button><button id=corop class=buttons003 onclick=qcor()>Bathing</button><button id=incop4 class=buttons003 onclick=qinc()>Watching TV</button><br/>",
},
{
"cat":"90s",
"ques":"What actress plays the blonde bimbo in Empire Records?",
"answ":"RENEE ZELLWEGER",
"answ2":"Renée Zellweger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anna Faris</button><button id=incop2 class=buttons003 onclick=qinc()>Alicia Silverstone</button><button id=corop class=buttons003 onclick=qcor()>Renée Zellweger</button><button id=incop4 class=buttons003 onclick=qinc()>Cameron Diaz</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays gangster Dutch Schultz in the film Billy Bathgate?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bruce Willis</button><button id=incop2 class=buttons003 onclick=qinc()>Al Pacino</button><button id=corop class=buttons003 onclick=qcor()>Dustin Hoffman</button><button id=incop4 class=buttons003 onclick=qinc()>Robert De Niro</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s movie features a character named Sonny Koufax?",
"answ":"BIG DADDY",
"answ2":"Big Daddy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Wedding Singer</button><button id=incop2 class=buttons003 onclick=qinc()>Snake Eyes</button><button id=corop class=buttons003 onclick=qcor()>Big Daddy</button><button id=incop4 class=buttons003 onclick=qinc()>She's All That</button><br/>",
},
{
"cat":"90s",
"ques":"What popular 90s film was adapted from a Chuck Palahniuk novel?",
"answ":"FIGHT CLUB",
"answ2":"Fight Club.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Usual Suspects</button><button id=incop2 class=buttons003 onclick=qinc()>Se7en</button><button id=incop3 class=buttons003 onclick=qinc()>The Sixth Sense</button><button id=corop class=buttons003 onclick=qcor()>Fight Club</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the wife of Robert De Niro's therapist in Analyze This?",
"answ":"LISA KUDROW",
"answ2":"Lisa Kudrow.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Lisa Kudrow</button><button id=incop2 class=buttons003 onclick=qinc()>Jennifer Aniston</button><button id=incop3 class=buttons003 onclick=qinc()>Ashley Judd</button><button id=incop4 class=buttons003 onclick=qinc()>Katie Holmes</button><br/>",
},
{
"cat":"90s",
"ques":"Johnny Depp goes undercover as what in Donnie Brasco?",
"answ":"JEWEL THIEF",
"answ2":"Jewel thief.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jewel thief</button><button id=incop2 class=buttons003 onclick=qinc()>Drugs dealer</button><button id=incop3 class=buttons003 onclick=qinc()>Hitman</button><button id=incop4 class=buttons003 onclick=qinc()>Prisoner</button><br/>",
},
{
"cat":"90s",
"ques":"In which movie is John Travolta is zapped by a bright light in the sky, leaving him with extrasensory perception?",
"answ":"PHENOMENON",
"answ2":"Phenomenon.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Phenomenon</button><button id=incop2 class=buttons003 onclick=qinc()>Battlefield Earth</button><button id=incop3 class=buttons003 onclick=qinc()>Basic</button><button id=incop4 class=buttons003 onclick=qinc()>Michael</button><br/>",
},
{
"cat":"90s",
"ques":"In From Dusk Till Dawn, who plays the RV driving patriarch whose family gets kidnapped by the Gecko brothers?",
"answ":"HARVEY KEITEL",
"answ2":"Harvey Keitel.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Harvey Keitel</button><button id=incop2 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop3 class=buttons003 onclick=qinc()>John Lithgow</button><button id=incop4 class=buttons003 onclick=qinc()>Kurt Russell</button><br/>",
},
{
"cat":"90s",
"ques":"Alicia Silverstone plays a character named Cher in what 90s film?",
"answ":"CLUELESS",
"answ2":"Clueless.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Clueless</button><button id=incop2 class=buttons003 onclick=qinc()>Fast Times at Ridgemont High</button><button id=incop3 class=buttons003 onclick=qinc()>The Babysitter</button><button id=incop4 class=buttons003 onclick=qinc()>Mallrats</button><br/>",
},
{
"cat":"90s",
"ques":"In Basic Instinct, what is the occupation of suspected murderer Catherine Tramell?",
"answ":"NOVELIST",
"answ3":"WRITER",
"answ2":"Novelist.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Novelist</button><button id=incop2 class=buttons003 onclick=qinc()>Teacher</button><button id=incop3 class=buttons003 onclick=qinc()>Surgeon</button><button id=incop4 class=buttons003 onclick=qinc()>Dentist</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s movie stars Kevin Spacey as a police officer who must diffuse a hostage situation?",
"answ":"THE NEGOTIATOR",
"answ2":"The Negotiator.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Internal Affairs</button><button id=corop class=buttons003 onclick=qcor()>The Negotiator</button><button id=incop3 class=buttons003 onclick=qinc()>Striking Distance</button><button id=incop4 class=buttons003 onclick=qinc()>Chain Reaction</button><br/>",
},
{
"cat":"90s",
"ques":"What film stars Meg Ryan as a pompous academic and Walter Matthau as her uncle Albert Einstein?",
"answ":"IQ",
"answ2":"I.Q.",
"option":"<button id=corop class=buttons003 onclick=qcor()>I.Q.</button><button id=incop2 class=buttons003 onclick=qinc()>With Honors</button><button id=incop3 class=buttons003 onclick=qinc()>Nothing to Lose</button><button id=incop4 class=buttons003 onclick=qinc()>Incident in a Small Town</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s action comedy stars Dennis Rodman and Dane Cook?",
"answ":"SIMON SEZ",
"answ2":"Simon Sez.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Simon Sez</button><button id=incop2 class=buttons003 onclick=qinc()>Double Team</button><button id=incop3 class=buttons003 onclick=qinc()>Death Warrant</button><button id=incop4 class=buttons003 onclick=qinc()>Fire Down Below</button><br/>",
},
{
"cat":"90s",
"ques":"What actor plays Geordi La Forge in Star Trek Generations?",
"answ":"LEVAR BURTON",
"answ2":"LeVar Burton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jonathan Frakes</button><button id=incop2 class=buttons003 onclick=qinc()>Brent Spiner</button><button id=corop class=buttons003 onclick=qcor()>LeVar Burton</button><button id=incop4 class=buttons003 onclick=qinc()>Gates McFadden</button><br/>",
},
{
"cat":"90s",
"ques":"Thelma and Louise want to avoid being on what TV show?",
"answ":"GERALDO",
"answ2":"Geraldo.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Geraldo</button><button id=incop2 class=buttons003 onclick=qinc()>Oprah</button><button id=incop3 class=buttons003 onclick=qinc()>Donahue</button><button id=incop4 class=buttons003 onclick=qinc()>Sally Jessy</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1999 The Thomas Crown Affair remake, what does Crown steal?",
"answ":"PAINTING",
"answ3":"A PAINTING",
"answ2":"A painting.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A painting</button><button id=incop2 class=buttons003 onclick=qinc()>A sculpture</button><button id=incop3 class=buttons003 onclick=qinc()>An ancient book</button><button id=incop4 class=buttons003 onclick=qinc()>A car</button><br/>",
},
{
"cat":"90s",
"ques":"Which 90s crime film featured the quote: 'Neri, take a train to Rome. Light a candle for the archbishop'?",
"answ":"THE GODFATHER PART III",
"answ3":"THE GODFATHER III",
"answ2":"The Godfather Part III.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Godfather Part III</button><button id=incop2 class=buttons003 onclick=qinc()>Casino</button><button id=incop3 class=buttons003 onclick=qinc()>Goodfellas</button><button id=incop4 class=buttons003 onclick=qinc()>Heat</button><br/>",
},
{
"cat":"90s",
"ques":"What Spike Lee movie has a lead character by the name of Jesus Shuttlesworth?",
"answ":"HE GOT GAME",
"answ2":"He Got Game.",
"option":"<button id=corop class=buttons003 onclick=qcor()>He Got Game</button><button id=incop2 class=buttons003 onclick=qinc()>Jungle Fever</button><button id=incop3 class=buttons003 onclick=qinc()>Do the Right Thing</button><button id=incop4 class=buttons003 onclick=qinc()>Crooklyn</button><br/>",
},
{
"cat":"90s",
"ques":"In what US city does the film The Craft take place?",
"answ":"LOS ANGELES",
"answ3":"LA",
"answ2":"Los Angeles.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Los Angeles</button><br /><button id=incop2 class=buttons003 onclick=qinc()>New York</button><button id=incop3 class=buttons003 onclick=qinc()>Chicago</button><button id=incop4 class=buttons003 onclick=qinc()>Miami</button><br/>",
},
{
"cat":"90s",
"ques":"What was the main hobby of The Dude and Walter in The Big Lebowski?",
"answ":"BOWLING",
"answ2":"Bowling.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Bowling</button><br /><button id=incop2 class=buttons003 onclick=qinc()>Fishing</button><button id=incop3 class=buttons003 onclick=qinc()>Swimming</button><button id=incop4 class=buttons003 onclick=qinc()>Tennis</button><br/>",
},
{
"cat":"90s",
"ques":"What war served as the backdrop for 1998's The Mask of Zorro?",
"answ":"MEXICAN AMERICAN WAR",
"answ3":"MEXICAN WAR",
"answ2":"Mexican–American War.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mexican–American War</button><br /><button id=incop2 class=buttons003 onclick=qinc()>Spanish-American War</button><button id=incop3 class=buttons003 onclick=qinc()>American Civil War</button><button id=incop4 class=buttons003 onclick=qinc()>World War I</button><br/>",
},
{
"cat":"90s",
"ques":"What was Jim Carrey's character's full name in The Truman Show?",
"answ":"TRUMAN BURBANK",
"answ2":"Truman Burbank.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Truman Warner</button><br /><button id=corop class=buttons003 onclick=qcor()>Truman Burbank</button><button id=incop3 class=buttons003 onclick=qinc()>Truman Ellis</button><button id=incop4 class=buttons003 onclick=qinc()>Truman Eubanks</button><br/>",
},
{
"cat":"90s",
"ques":"In The Rocketeer, what item does Peevy use to patch the bullet hole in the rocket pack?",
"answ":"GUM",
"answ3":"CHEWING GUM",
"answ2":"Chewing Gum.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Duct Tape</button><button id=incop2 class=buttons003 onclick=qinc()>Screw</button><button id=incop3 class=buttons003 onclick=qinc()>Band-aid</button><button id=corop class=buttons003 onclick=qcor()>Chewing Gum</button><br/>",
},
{
"cat":"90s",
"ques":"When Neo experiences déjà vu in The Matrix, what animal does he see twice?",
"answ":"CAT",
"answ3":"A CAT",
"answ2":"Cat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mouse</button><button id=incop2 class=buttons003 onclick=qinc()>Horse</button><button id=incop3 class=buttons003 onclick=qinc()>Dog</button><button id=corop class=buttons003 onclick=qcor()>Cat</button><br/>",
},
{
"cat":"90s",
"ques":"In which movie does Sylvester Stallone play a character named Angelo 'Snaps' Provolone?",
"answ":"OSCAR",
"answ2":"Oscar.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Specialist</button><button id=corop class=buttons003 onclick=qcor()>Oscar</button><button id=incop3 class=buttons003 onclick=qinc()>Junior</button><button id=incop4 class=buttons003 onclick=qinc()>Stop! Or My Mom Will Shoot</button><br/>",
},
{
"cat":"90s",
"ques":"In Ace Ventura Pet Detective, what kind of animal was Ace seeking througout the majority of the film?",
"answ":"DOLPHIN",
"answ2":"Dolphin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dog</button><button id=corop class=buttons003 onclick=qcor()>Dolphin</button><button id=incop3 class=buttons003 onclick=qinc()>Parrot</button><button id=incop4 class=buttons003 onclick=qinc()>Monkey</button><br/>",
},
{
"cat":"90s",
"ques":"What kind of animal is Willy, in Free Willy?",
"answ":"ORCA",
"answ3":"KILLER WHALE",
"answ2":"Orca/Killer Whale.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sea Lion</button><button id=corop class=buttons003 onclick=qcor()>Orca</button><button id=incop3 class=buttons003 onclick=qinc()>Walrus</button><button id=incop4 class=buttons003 onclick=qinc()>Shark</button><br/>",
},
{
"cat":"90s",
"ques":"In what film does Hulk Hogan play an interstellar bounty hunter?",
"answ":"SUBURBAN COMMANDO",
"answ2":"Suburban Commando.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>No Holds Barred</button><button id=corop class=buttons003 onclick=qcor()>Suburban Commando</button><button id=incop3 class=buttons003 onclick=qinc()>Thunder Lips</button><button id=incop4 class=buttons003 onclick=qinc()>Earth Girls Are Easy</button><br/>",
},
{
"cat":"90s",
"ques":"Who was Zorro before passing it on to Antonio Banderas in The Mask of Zorro?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sean Connery</button><button id=corop class=buttons003 onclick=qcor()>Anthony Hopkins</button><button id=incop3 class=buttons003 onclick=qinc()>Christopher Plummer</button><button id=incop4 class=buttons003 onclick=qinc()>Donald Sutherland</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays God in the 1999 movie Dogma?",
"answ":"ALANIS MORISSETTE",
"answ3":"ALANIS MORISETTE",
"answ2":"Alanis Morissette.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Megan Fox</button><button id=corop class=buttons003 onclick=qcor()>Alanis Morissette</button><button id=incop3 class=buttons003 onclick=qinc()>Milla Jovovich</button><button id=incop4 class=buttons003 onclick=qinc()>Pamela Anderson</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Doc Brown's love interest in Back to the Future Part III?",
"answ":"MARY STEENBURGEN",
"answ2":"Mary Steenburgen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lea Thompson</button><button id=incop2 class=buttons003 onclick=qinc()>Elisabeth Shue</button><button id=corop class=buttons003 onclick=qcor()>Mary Steenburgen</button><button id=incop4 class=buttons003 onclick=qinc()>Demi Moore</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Claudia in Interview with the Vampire?",
"answ":"KIRSTEN DUNST",
"answ3":"KRISTEN DUNST",
"answ2":"Kirsten Dunst.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Thandie Newton</button><button id=incop2 class=buttons003 onclick=qinc()>Hilary Swank</button><button id=corop class=buttons003 onclick=qcor()>Kirsten Dunst</button><button id=incop4 class=buttons003 onclick=qinc()>Demi Moore</button><br/>",
},
{
"cat":"90s",
"ques":"What brand of shaving cream did Dennis use to smuggle out dinosaur embryos in Jurassic Park?",
"answ":"BARBASOL",
"answ2":"Barbasol.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brut</button><button id=incop2 class=buttons003 onclick=qinc()>Magic Shave</button><button id=corop class=buttons003 onclick=qcor()>Barbasol</button><button id=incop4 class=buttons003 onclick=qinc()>Proraso</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s movie features Bruce Willis playing a Pittsburgh cop named Tom Hardy?",
"answ":"STRIKING DISTANCE",
"answ2":"Striking Distance.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mortal Thoughts</button><button id=incop2 class=buttons003 onclick=qinc()>Billy Bathgate</button><button id=corop class=buttons003 onclick=qcor()>Striking Distance</button><button id=incop4 class=buttons003 onclick=qinc()>Color of Night</button><br/>",
},
{
"cat":"90s",
"ques":"In The Shawshank Redemption what bombshell was on the poster in Andy's cell?",
"answ":"RITA HAYWORTH",
"answ2":"Rita Hayworth.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pamela Anderson</button><button id=incop2 class=buttons003 onclick=qinc()>Marilyn Monroe</button><button id=corop class=buttons003 onclick=qcor()>Rita Hayworth</button><button id=incop4 class=buttons003 onclick=qinc()>Brigitte Bardot</button><br/>",
},
{
"cat":"90s",
"ques":"In the 90s film Get Shorty, who plays mobster Ray Barboni?",
"answ":"DENNIS FARINA",
"answ2":"Dennis Farina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Al Pacino</button><button id=incop2 class=buttons003 onclick=qinc()>Joe Pesci</button><button id=corop class=buttons003 onclick=qcor()>Dennis Farina</button><button id=incop4 class=buttons003 onclick=qinc()>James Gandolfini</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Birdie in the 1994 basketball drama Above the Rim?",
"answ":"TUPAC SHAKUR",
"answ2":"Tupac Shakur.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Marlon Wayans</button><button id=corop class=buttons003 onclick=qcor()>Tupac Shakur</button><button id=incop3 class=buttons003 onclick=qinc()>Kadeem Hardison</button><button id=incop4 class=buttons003 onclick=qinc()>James Marshall</button><br/>",
},
{
"cat":"90s",
"ques":"Robin Williams won an Oscar for Best Supporting Actor in what 90s film?",
"answ":"GOOD WILL HUNTING",
"answ2":"Good Will Hunting.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dead Poets Society</button><button id=incop2 class=buttons003 onclick=qinc()>The Fisher King</button><button id=corop class=buttons003 onclick=qcor()>Good Will Hunting</button><button id=incop4 class=buttons003 onclick=qinc()>Good Morning, Vietnam</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Albert Einstein in the 1994 romantic comedy IQ?",
"answ":"WALTER MATTHAU",
"answ2":"Walter Matthau.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>JK Simmons</button><button id=corop class=buttons003 onclick=qcor()>Walter Matthau</button><button id=incop3 class=buttons003 onclick=qinc()>George Segal</button><button id=incop4 class=buttons003 onclick=qinc()>Art Carney</button><br/>",
},
{
"cat":"90s",
"ques":"Who stars opposite Harrison Ford in the film Six Days Seven Nights?",
"answ":"ANNE HECHE",
"answ2":"Anne Heche.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anne Archer</button><button id=corop class=buttons003 onclick=qcor()>Anne Heche</button><button id=incop3 class=buttons003 onclick=qinc()>Sela Ward</button><button id=incop4 class=buttons003 onclick=qinc()>Kelly McGillis</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the beautiful scientist Dr. Emma Russell in 1997's The Saint?",
"answ":"ELISABETH SHUE",
"answ3":"ELIZABETH SHUE",
"answ2":"Elisabeth Shue.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Phoebe Cates</button><button id=incop2 class=buttons003 onclick=qinc()>Meg Ryan</button><button id=incop3 class=buttons003 onclick=qinc()>Julia Roberts</button><button id=corop class=buttons003 onclick=qcor()>Elisabeth Shue</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1993 movie Gettysburg, who portrayed General Robert E. Lee?",
"answ":"MARTIN SHEEN",
"answ2":"Martin Sheen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Berenger</button><button id=incop2 class=buttons003 onclick=qinc()>Gene Hackman</button><button id=corop class=buttons003 onclick=qcor()>Martin Sheen</button><button id=incop4 class=buttons003 onclick=qinc()>Sam Elliott</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Billy Crystal's son in City Slickers?",
"answ":"JAKE GYLLENHAAL",
"answ3":"JAKE GYLENHAAL",
"answ2":"Jake Gyllenhaal.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jake Gyllenhaal</button><button id=incop2 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=incop3 class=buttons003 onclick=qinc()>Joseph Gordon-Levitt</button><button id=incop4 class=buttons003 onclick=qinc()>Macaulay Culkin</button><br/>",
},
{
"cat":"90s",
"ques":"In The Rocketeer, what does Cliff disguise himself as at the South Seas Club in order to get to Jenny?",
"answ":"A WAITER",
"answ3":"WAITER",
"answ2":"A waiter.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A chef</button><button id=incop2 class=buttons003 onclick=qinc()>A cop</button><button id=incop3 class=buttons003 onclick=qinc()>A valet</button><button id=corop class=buttons003 onclick=qcor()>A waiter</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed the Daniel Day-Lewis masterpiece The Last of the Mohicans?",
"answ":"MICHAEL MAN",
"answ3":"MICHAEL MANN",
"answ2":"Michael Mann.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paul Thomas Anderson</button><button id=incop2 class=buttons003 onclick=qinc()>Carlos Sorín</button><button id=incop3 class=buttons003 onclick=qinc()>Jim Sheridan</button><button id=corop class=buttons003 onclick=qcor()>Michael Mann</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Harrison Ford's love interest Kay Chandler in 1999's Random Hearts?",
"answ":"KRISTIN SCOTT THOMAS",
"answ2":"Kristin Scott Thomas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kelly Lynch</button><button id=incop2 class=buttons003 onclick=qinc()>Miranda Richardson</button><button id=corop class=buttons003 onclick=qcor()>Kristin Scott Thomas</button><button id=incop4 class=buttons003 onclick=qinc()>Mary Elizabeth Mastrantonio</button><br/>",
},
{
"cat":"90s",
"ques":"Which actor played the character of Mumbles in 1990's Dick Tracy?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Douglas</button><button id=corop class=buttons003 onclick=qcor()>Dustin Hoffman</button><button id=incop4 class=buttons003 onclick=qinc()>Al Pacino</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays a former IRA sniper named Declan Mulqueen in 1997's The Jackal?",
"answ":"RICHARD GERE",
"answ2":"Richard Gere.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bruce Willis</button><button id=incop2 class=buttons003 onclick=qinc()>Daniel Craig</button><button id=corop class=buttons003 onclick=qcor()>Richard Gere</button><button id=incop4 class=buttons003 onclick=qinc()>Dennis Quaid</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays actor Cameron Drake who 'outs' his former English teacher as being gay in 1997's In & Out?",
"answ":"MATT DILLON",
"answ2":"Matt Dillon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Matt Damon</button><button id=incop2 class=buttons003 onclick=qinc()>Ben Affleck</button><button id=corop class=buttons003 onclick=qcor()>Matt Dillon</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Bateman</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Drew Barrymore's evil stepmother in Ever After?",
"answ":"ANJELICA HUSTON",
"answ3":"ANGELICA HUSTON",
"answ2":"Anjelica Huston.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Helen Mirren</button><button id=corop class=buttons003 onclick=qcor()>Anjelica Huston</button><button id=incop3 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=incop4 class=buttons003 onclick=qinc()>Julie Andrews</button><br/>",
},
{
"cat":"90s",
"ques":"What is the name of the American submarine captured by Scott Glenn in The Hunt for Red October?",
"answ":"USS DALLAS",
"answ2":"USS Dallas.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>USS Indianapolis</button><button id=corop class=buttons003 onclick=qcor()>USS Dallas</button><button id=incop3 class=buttons003 onclick=qinc()>USS Tennessee</button><button id=incop4 class=buttons003 onclick=qinc()>USS Omaha</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed 1998's Hope Floats?",
"answ":"FOREST WHITAKER",
"answ3":"FORREST WHITAKER",
"answ2":"Forest Whitaker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Forest Whitaker</button><button id=incop2 class=buttons003 onclick=qinc()>Griffin Dunne</button><button id=incop3 class=buttons003 onclick=qinc()>Jon Turteltaub</button><button id=incop4 class=buttons003 onclick=qinc()>Marc Lawrence</button><br/>",
},
{
"cat":"90s",
"ques":"In 1991's Father of the Bride, Steve Martin's character owns a company that produces what?",
"answ":"SHOES",
"answ3":"SNEAKERS",
"answ2":"Sneakers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sneakers</button><button id=incop2 class=buttons003 onclick=qinc()>Coffee Makers</button><button id=incop3 class=buttons003 onclick=qinc()>Candy</button><button id=incop4 class=buttons003 onclick=qinc()>Basketballs</button><br/>",
},
{
"cat":"90s",
"ques":"What movie starred Tommy Lee Jones as a parole officer who supervises Ashley Judd's character?",
"answ":"DOUBLE JEOPARDY",
"answ2":"Double Jeopardy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>U.S. Marshals</button><button id=incop2 class=buttons003 onclick=qinc()>High Crimes</button><button id=corop class=buttons003 onclick=qcor()>Double Jeopardy</button><button id=incop4 class=buttons003 onclick=qinc()>The Client</button><br/>",
},
{
"cat":"90s",
"ques":"In Fight Club, what is the Narrator's (Edward Norton) power animal?",
"answ":"PENGUIN",
"answ2":"Penguin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wolf</button><button id=incop2 class=buttons003 onclick=qinc()>Whale</button><button id=corop class=buttons003 onclick=qcor()>Penguin</button><button id=incop4 class=buttons003 onclick=qinc()>Duck</button><br/>",
},
{
"cat":"90s",
"ques":"In which 1998 film does John Travolta play a southern Democrat who runs for president?",
"answ":"PRIMARY COLORS",
"answ2":"Primary Colors.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Contender</button><button id=incop2 class=buttons003 onclick=qinc()>American Dreamz</button><button id=corop class=buttons003 onclick=qcor()>Primary Colors</button><button id=incop4 class=buttons003 onclick=qinc()>Swing Vote</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the character of Brock Lovett in Titanic, who Rose tells her story to?",
"answ":"BILL PAXTON",
"answ2":"Bill Paxton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Billy Zane</button><button id=incop2 class=buttons003 onclick=qinc()>Anthony Michael Hall</button><button id=corop class=buttons003 onclick=qcor()>Bill Paxton</button><button id=incop4 class=buttons003 onclick=qinc()>Gary Sinise</button><br/>",
},
{
"cat":"90s",
"ques":"What midwestern US city is the setting for Backdraft?",
"answ":"CHICAGO",
"answ2":"Chicago.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cincinnati</button><button id=incop2 class=buttons003 onclick=qinc()>Indianapolis</button><button id=corop class=buttons003 onclick=qcor()>Chicago</button><button id=incop4 class=buttons003 onclick=qinc()>Cleveland</button><br/>",
},
{
"cat":"90s",
"ques":"In Meet Joe Black, who plays Susan Parrish, the young woman who falls in love with Joe Black?",
"answ":"CLAIRE FORLANI",
"answ2":"Claire Forlani.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Julia Ormond</button><button id=corop class=buttons003 onclick=qcor()>Claire Forlani</button><button id=incop3 class=buttons003 onclick=qinc()>Jessica Biel</button><button id=incop4 class=buttons003 onclick=qinc()>Minnie Driver</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Brad Pitt's love interest in 1993's Kalifornia?",
"answ":"JULIETTE LEWIS",
"answ2":"Juliette Lewis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Julia Ormond</button><button id=corop class=buttons003 onclick=qcor()>Juliette Lewis</button><button id=incop3 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><button id=incop4 class=buttons003 onclick=qinc()>Uma Thurman</button><br/>",
},
{
"cat":"90s",
"ques":"What was Brad Pitt's character's name in True Romance?",
"answ":"FLOYD",
"answ2":"Floyd.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lucas</button><button id=corop class=buttons003 onclick=qcor()>Floyd</button><button id=incop3 class=buttons003 onclick=qinc()>Flynt</button><button id=incop4 class=buttons003 onclick=qinc()>Purple</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays Basil Exposition in Austin Powers: International Man of Mystery?",
"answ":"MICHAEL YORK",
"answ2":"Michael York.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mike Myers</button><button id=corop class=buttons003 onclick=qcor()>Michael York</button><button id=incop3 class=buttons003 onclick=qinc()>Verne Troyer</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Caine</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Johnny Ringo in 1993's Tombstone?",
"answ":"MICHAEL BIEHN",
"answ2":"Michael Biehn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Val Kilmer</button><button id=corop class=buttons003 onclick=qcor()>Michael Biehn</button><button id=incop3 class=buttons003 onclick=qinc()>Kurt Russell</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Paxton</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed Silence of the Lambs?",
"answ":"JONATHAN DEMME",
"answ2":"Jonathan Demme.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ted Demme</button><button id=incop2 class=buttons003 onclick=qinc()>David Fincher</button><button id=corop class=buttons003 onclick=qcor()>Jonathan Demme</button><button id=incop4 class=buttons003 onclick=qinc()>John McTiernan</button><br/>",
},
{
"cat":"90s",
"ques":"In Titanic, who played the ship's captain, Captain Edward John Smith?",
"answ":"BERNARD HILL",
"answ2":"Bernard Hill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bill Pullman</button><button id=incop2 class=buttons003 onclick=qinc()>John Noble</button><button id=corop class=buttons003 onclick=qcor()>Bernard Hill</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Caine</button><br/>",
},
{
"cat":"90s",
"ques":"Who stars alongside Nicole Kidman as a pair of witch sisters in 1998's Practical Magic?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michelle Pfeiffer</button><button id=incop2 class=buttons003 onclick=qinc()>Meryl Streep</button><button id=corop class=buttons003 onclick=qcor()>Sandra Bullock</button><button id=incop4 class=buttons003 onclick=qinc()>Cameron Diaz</button><br/>",
},
{
"cat":"90s",
"ques":"Which actress plays the lead opposite Kevin Costner in Dances with Wolves?",
"answ":"MARY MCDONNELL",
"answ3":"MARY MACDONNELL",
"answ2":"Mary McDonnell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeanne Tripplehorn</button><button id=incop2 class=buttons003 onclick=qinc()>Ashley Judd</button><button id=corop class=buttons003 onclick=qcor()>Mary McDonnell</button><button id=incop4 class=buttons003 onclick=qinc()>Olivia Williams</button><br/>",
},
{
"cat":"90s",
"ques":"Who starred as Julie Pierce, Mr Miyagi's new pupil, in The Next Karate Kid?",
"answ":"HILARY SWANK",
"answ3":"HILLARY SWANK",
"answ2":"Hilary Swank.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Drew Barrymore</button><button id=incop2 class=buttons003 onclick=qinc()>Amy Adams</button><button id=corop class=buttons003 onclick=qcor()>Hilary Swank</button><button id=incop4 class=buttons003 onclick=qinc()>Jessica Chastain</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1998 animated film Antz, the colony is attacked by an army of what creature?",
"answ":"TERMITES",
"answ3":"TERMITE",
"answ2":"Termites.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mosquitoes</button><button id=incop2 class=buttons003 onclick=qinc()>Grashoppers</button><button id=corop class=buttons003 onclick=qcor()>Termites</button><button id=incop4 class=buttons003 onclick=qinc()>Ladybugs</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1999 version of The Mummy, what is the first name of Brendan Fraser's character?",
"answ":"RICK",
"answ2":"Rick.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nick</button><button id=incop2 class=buttons003 onclick=qinc()>Henry</button><button id=incop3 class=buttons003 onclick=qinc()>John</button><button id=corop class=buttons003 onclick=qcor()>Rick</button><br/>",
},
{
"cat":"90s",
"ques":"In Mrs. Doubtfire, who plays Stu, the boyfriend to Robin William's ex-wife?",
"answ":"PIERCE BROSNAN",
"answ2":"Pierce Brosnan.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pierce Brosnan</button><button id=incop2 class=buttons003 onclick=qinc()>Gerard Butler</button><button id=incop3 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=incop4 class=buttons003 onclick=qinc()>Aaron Eckhart</button><br/>",
},
{
"cat":"90s",
"ques":"What actor co-stars with Virginia Madsen as drifter Harry Madox in the 1990 neo-noir The Hot Spot?",
"answ":"DON JOHNSON",
"answ2":"Don Johnson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Matt Damon</button><button id=corop class=buttons003 onclick=qcor()>Don Johnson</button><button id=incop3 class=buttons003 onclick=qinc()>Billy Bob Thornton</button><button id=incop4 class=buttons003 onclick=qinc()>Danny Huston</button><br/>",
},
{
"cat":"90s",
"ques":"Dan Aykroyd and Daniel Stern play rabid NBA fans who kidnap a player played by Damon Wayans in what 90s comedy?",
"answ":"CELTIC PRIDE",
"answ2":"Celtic Pride.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Great White Hype</button><button id=corop class=buttons003 onclick=qcor()>Celtic Pride</button><button id=incop3 class=buttons003 onclick=qinc()>The Player</button><button id=incop4 class=buttons003 onclick=qinc()>The Big Green</button><br/>",
},
{
"cat":"90s",
"ques":"In the movie Rudy, who played D-Bob, Rudy's best friend once he got into Notre Dame?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Vince Vaughn</button><button id=corop class=buttons003 onclick=qcor()>Jon Favreau</button><button id=incop3 class=buttons003 onclick=qinc()>Gerard Butler</button><button id=incop4 class=buttons003 onclick=qinc()>Sean Astin</button><br/>",
},
{
"cat":"90s",
"ques":"Whoopi Goldberg plays a housekeeper who lights up the life of a grieving widower and his daughter in this 1994 film.",
"answ":"CORRINA CORRINA",
"answ3":"CORRINA  CORRINA",
"answ2":"Corrina Corrina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Color Purple</button><button id=corop class=buttons003 onclick=qcor()>Corrina, Corrina</button><button id=incop3 class=buttons003 onclick=qinc()>Clara's Heart</button><button id=incop4 class=buttons003 onclick=qinc()>The Long Walk Home</button><br/>",
},
{
"cat":"90s",
"ques":"What comedic actor played sound engineer Gary Dixon in Anaconda?",
"answ":"OWEN WILSON",
"answ2":"Owen Wilson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eddie Murphy</button><button id=incop2 class=buttons003 onclick=qinc()>Ben Stiller</button><button id=incop3 class=buttons003 onclick=qinc()>Vince Vaughn</button><button id=corop class=buttons003 onclick=qcor()>Owen Wilson</button><br/>",
},
{
"cat":"90s",
"ques":"In Wayne's World what song is Wayne 'denied' from playing in the guitar shop?",
"answ":"STAIRWAY TO HEAVEN",
"answ2":"Stairway to Heaven.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hotel California</button><button id=incop2 class=buttons003 onclick=qinc()>Eye of the Tiger</button><button id=incop3 class=buttons003 onclick=qinc()>Purple Rain</button><button id=corop class=buttons003 onclick=qcor()>Stairway to Heaven</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays Amy March, the youngest of the March girls, in 1994's Little Women?",
"answ":"KIRSTEN DUNST",
"answ3":"KRISTEN DUNST",
"answ2":"Kirsten Dunst.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Winona Ryder</button><button id=incop2 class=buttons003 onclick=qinc()>Scarlett Johansson</button><button id=incop3 class=buttons003 onclick=qinc()>Drew Barrymore</button><button id=corop class=buttons003 onclick=qcor()>Kirsten Dunst</button><br/>",
},
{
"cat":"90s",
"ques":"Which 90s film is about three of the most popular girls at Reagan High accidentally killing the prom queen when a kidnapping goes horribly wrong?",
"answ":"JAWBREAKER",
"answ2":"Jawbreaker.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Craft</button><button id=incop2 class=buttons003 onclick=qinc()>Dangerous Minds</button><button id=incop3 class=buttons003 onclick=qinc()>A Feast at Midnight</button><button id=corop class=buttons003 onclick=qcor()>Jawbreaker</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1993 thriller Falling Down, who plays the wife of Michael Douglas' 'D-Fens', Beth Trevino?",
"answ":"BARBARA HERSHEY",
"answ2":"Barbara Hershey.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Barbara Hershey</button><button id=incop2 class=buttons003 onclick=qinc()>Tuesday Weld</button><button id=incop3 class=buttons003 onclick=qinc()>Sharon Stone</button><button id=incop4 class=buttons003 onclick=qinc()>Rachel Ticotin</button><br/>",
},
{
"cat":"90s",
"ques":"What real grunge band were members of Cliff's band in the 1992 Cameron Crowe film, Singles?",
"answ":"PEARL JAM",
"answ2":"Pearl Jam.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pearl Jam</button><button id=incop2 class=buttons003 onclick=qinc()>Nirvana</button><button id=incop3 class=buttons003 onclick=qinc()>Soundgarden</button><button id=incop4 class=buttons003 onclick=qinc()>Melvins</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed American History X?",
"answ":"TONY KAYE",
"answ2":"Tony Kaye.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tony Kaye</button><button id=incop2 class=buttons003 onclick=qinc()>Spike Lee</button><button id=incop3 class=buttons003 onclick=qinc()>Ridley Scott</button><button id=incop4 class=buttons003 onclick=qinc()>Oliver Stone</button><br/>",
},
{
"cat":"90s",
"ques":"What famous actor says the line: 'That'll do pig' in 1995's Babe?",
"answ":"JAMES CROMWELL",
"answ2":"James Cromwell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>James Cromwell</button><button id=incop2 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop3 class=buttons003 onclick=qinc()>Liam Neeson</button><button id=incop4 class=buttons003 onclick=qinc()>Ed Harris</button><br/>",
},
{
"cat":"90s",
"ques":"In 1995's Friday, who plays the Big Worm, the psychopathic neighborhood drug supplier?",
"answ":"FAIZON LOVE",
"answ2":"Faizon Love.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Lister Jr.</button><button id=incop2 class=buttons003 onclick=qinc()>Ice Cube</button><button id=incop3 class=buttons003 onclick=qinc()>Bernie Mac</button><button id=corop class=buttons003 onclick=qcor()>Faizon Love</button><br/>",
},
{
"cat":"90s",
"ques":"In Home Alone, what appliance located in the basement is Kevin afraid of?",
"answ":"FURNACE",
"answ3":"THE FURNACE",
"answ2":"Furnace.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dishwasher</button><button id=incop2 class=buttons003 onclick=qinc()>Air conditioner</button><button id=incop3 class=buttons003 onclick=qinc()>Trash compactor</button><button id=corop class=buttons003 onclick=qcor()>Furnace</button><br/>",
},
{
"cat":"90s",
"ques":"Who played reporter Gale Weathers in 1996's Scream?",
"answ":"COURTENEY COX",
"answ3":"COURTNEX COX",
"answ2":"Courteney Cox.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Neve Campbell</button><button id=incop2 class=buttons003 onclick=qinc()>Meg Ryan</button><button id=incop3 class=buttons003 onclick=qinc()>Jodie Foster</button><button id=corop class=buttons003 onclick=qcor()>Courteney Cox</button><br/>",
},
{
"cat":"90s",
"ques":"In 1992's Under Siege, the battleship that was hijacked shares its name with what state?",
"answ":"MISSOURI",
"answ2":"Missouri.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Missouri</button><button id=incop2 class=buttons003 onclick=qinc()>Montana</button><button id=incop3 class=buttons003 onclick=qinc()>Mississippi</button><button id=incop4 class=buttons003 onclick=qinc()>Michigan</button><br/>",
},
{
"cat":"90s",
"ques":"In what movie does Christian Slater play a teenage pirate radio DJ?",
"answ":"PUMP UP THE VOLUME",
"answ2":"Pump Up the Volume.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pump Up the Volume</button><button id=incop2 class=buttons003 onclick=qinc()>The Wizard</button><button id=incop3 class=buttons003 onclick=qinc()>Beyond the Stars</button><button id=incop4 class=buttons003 onclick=qinc()>Untamed Heart</button><br/>",
},
{
"cat":"90s",
"ques":"In Hot Shots! Part Deux, who plays President Thomas 'Tug' Benson?",
"answ":"LLOYD BRIDGES",
"answ3":"LOYD BRIDGES",
"answ2":"Lloyd Bridges.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Lloyd Bridges</button><button id=incop2 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=incop3 class=buttons003 onclick=qinc()>John Cleese</button><button id=incop4 class=buttons003 onclick=qinc()>Leslie Nielsen</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1992 Steve Martin comedy Leap of Faith, who plays Will Braverman, a sheriff who tries to prevent the townspeople from being conned?",
"answ":"LIAM NEESON",
"answ3":"LIAM NEESSON",
"answ2":"Liam Neeson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Liam Neeson</button><button id=incop2 class=buttons003 onclick=qinc()>Jeff Bridges</button><button id=incop3 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop4 class=buttons003 onclick=qinc()>Willem Dafoe</button><br/>",
},
{
"cat":"90s",
"ques":"In Starship Troopers, who plays the physically gifted Col. Carl Jenkins who leads the Military Intelligence effort against the bugs?",
"answ":"NEIL PATRICK HARRIS",
"answ2":"Neil Patrick Harris.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jake Busey</button><button id=incop2 class=buttons003 onclick=qinc()>Casper Van Dien</button><button id=incop3 class=buttons003 onclick=qinc()>Seth Gilliam</button><button id=corop class=buttons003 onclick=qcor()>Neil Patrick Harris</button><br/>",
},
{
"cat":"90s",
"ques":"In Speed, what speed does the bus have to maintain to not explode?",
"answ":"50",
"answ3":"50 MPH",
"answ2":"50 mph.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>30 mph</button><button id=incop2 class=buttons003 onclick=qinc()>40 mph</button><button id=corop class=buttons003 onclick=qcor()>50 mph</button><button id=incop4 class=buttons003 onclick=qinc()>60 mph</button><br/>",
},
{
"cat":"90s",
"ques":"Noah Emmerich plays Jim Carrey's best friend in what 90s film?",
"answ":"THE TRUMAN SHOW",
"answ3":"TRUMAN SHOW",
"answ2":"The Truman Show.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Cable Guy</button><button id=incop2 class=buttons003 onclick=qinc()>The Mask</button><button id=corop class=buttons003 onclick=qcor()>The Truman Show</button><button id=incop4 class=buttons003 onclick=qinc()>Ace Ventura: Pet Detective</button><br/>",
},
{
"cat":"90s",
"ques":"Who played Arnold Schwarzenegger's annoying next door neighbor Ted, in Jingle All the Way?",
"answ":"PHIL HARTMAN",
"answ2":"Phil Hartman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jim Belushi</button><button id=incop2 class=buttons003 onclick=qinc()>Tim Curry</button><button id=corop class=buttons003 onclick=qcor()>Phil Hartman</button><button id=incop4 class=buttons003 onclick=qinc()>Jon Lovitz</button><br/>",
},
{
"cat":"90s",
"ques":"Eduardo Sanchez and Daniel Myrick directed which 90s horror film?",
"answ":"THE BLAIR WITCH PROJECT",
"answ3":"BLAIR WITCH PROJECT",
"answ2":"The Blair Witch Project.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scream</button><button id=incop2 class=buttons003 onclick=qinc()>Tremors</button><button id=corop class=buttons003 onclick=qcor()>The Blair Witch Project</button><button id=incop4 class=buttons003 onclick=qinc()>Fallen</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the sheltered and naïve Cecile Caldwell in 1999's Cruel Intentions?",
"answ":"SELMA BLAIR",
"answ2":"Selma Blair.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jennifer Love Hewitt</button><button id=incop2 class=buttons003 onclick=qinc()>Neve Campbell</button><button id=corop class=buttons003 onclick=qcor()>Selma Blair</button><button id=incop4 class=buttons003 onclick=qinc()>Courteney Cox</button><br/>",
},
{
"cat":"90s",
"ques":"Which character kills the traitorous Malagant in 1995's First Knight?",
"answ":"LANCELOT",
"answ2":"Lancelot.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Percival</button><button id=corop class=buttons003 onclick=qcor()>Lancelot</button><button id=incop3 class=buttons003 onclick=qinc()>Guinevere</button><button id=incop4 class=buttons003 onclick=qinc()>King Arthur</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays Mark Renton, who is trying to 'choose life' away from heroin, in Danny Boyle's Trainspotting?",
"answ":"EWAN MCGREGOR",
"answ2":"Ewan McGregor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ralph Fiennes</button><button id=corop class=buttons003 onclick=qcor()>Ewan McGregor</button><button id=incop3 class=buttons003 onclick=qinc()>Robert Downey Jr.</button><button id=incop4 class=buttons003 onclick=qinc()>Matt Damon</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the young activist Nina, who tags along with Bulworth, in 1998's Bulworth?",
"answ":"HALLE BERRY",
"answ3":"HALLE BARRY",
"answ2":"Halle Berry.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cameron Diaz</button><button id=corop class=buttons003 onclick=qcor()>Halle Berry</button><button id=incop3 class=buttons003 onclick=qinc()>Christina Applegate</button><button id=incop4 class=buttons003 onclick=qinc()>Jennifer Aniston</button><br/>",
},
{
"cat":"90s",
"ques":"What 1990 film was directed by Jerry Zucker and received a Best Picture Oscar nomination?",
"answ":"GHOST",
"answ2":"Ghost.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Awakenings</button><button id=corop class=buttons003 onclick=qcor()>Ghost</button><button id=incop3 class=buttons003 onclick=qinc()>The Prince of Tides</button><button id=incop4 class=buttons003 onclick=qinc()>Bugsy</button><br/>",
},
{
"cat":"90s",
"ques":"Who played the lead, Mitch Robbins, in 1992's City Slickers?",
"answ":"BILLY CRYSTAL",
"answ2":"Billy Crystal.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Martin Short</button><button id=corop class=buttons003 onclick=qcor()>Billy Crystal</button><button id=incop3 class=buttons003 onclick=qinc()>Eddie Murphy</button><button id=incop4 class=buttons003 onclick=qinc()>Robert Downey Jr.</button><br/>",
},
{
"cat":"90s",
"ques":"What is the subtitle of Gremlins 2?",
"answ":"THE NEW BATCH",
"answ3":"GREMLINS 2 THE NEW BATCH",
"answ2":"The New Batch.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Secrets of the Mogwai</button><button id=corop class=buttons003 onclick=qcor()>The New Batch</button><button id=incop3 class=buttons003 onclick=qinc()>Monsters Unleashed</button><button id=incop4 class=buttons003 onclick=qinc()>They're Back</button><br/>",
},
{
"cat":"90s",
"ques":"In 1995's Casper, which of the 4 main Ghostbusters actors has a cameo as his character from the Ghostbusters franchise?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bill Murray</button><button id=corop class=buttons003 onclick=qcor()>Dan Aykroyd</button><button id=incop3 class=buttons003 onclick=qinc()>Harold Ramis</button><button id=incop4 class=buttons003 onclick=qinc()>Ernie Hudson</button><br/>",
},
{
"cat":"90s",
"ques":"What actor stars in The Hard Way as a pampered Hollywood star posing as a cop to research a role?",
"answ":"MICHAEL J FOX",
"answ2":"Michael J. Fox.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael J. Fox</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Downey Jr.</button><button id=incop3 class=buttons003 onclick=qinc()>C. Thomas Howell</button><button id=incop4 class=buttons003 onclick=qinc()>David Duchovny</button><br/>",
},
{
"cat":"90s",
"ques":"What Spider-Man franchise actor plays drug dealer Rashad Jackson in Paul Thomas Anderson's Boogie Nights?",
"answ":"ALFRED MOLINA",
"answ2":"Alfred Molina.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alfred Molina</button><button id=incop2 class=buttons003 onclick=qinc()>Tobey Maguire</button><button id=incop3 class=buttons003 onclick=qinc()>James Franco</button><button id=incop4 class=buttons003 onclick=qinc()>Cliff Robertson</button><br/>",
},
{
"cat":"90s",
"ques":"In what 1994 film does Joe Pesci play a homeless man who offers life advice to a college student?",
"answ":"WITH HONORS",
"answ2":"With Honors.",
"option":"<button id=corop class=buttons003 onclick=qcor()>With Honors</button><button id=incop2 class=buttons003 onclick=qinc()>A Bronx Tale</button><button id=incop3 class=buttons003 onclick=qinc()>8 Heads in a Duffel Bag</button><button id=incop4 class=buttons003 onclick=qinc()>Jimmy Hollywood</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s comedy drama features an ensemble cast which includes Vanessa Williams, Vivica A. Fox and Nia Long?",
"answ":"SOUL FOOD",
"answ2":"Soul Food.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Soul Food</button><button id=incop2 class=buttons003 onclick=qinc()>Dance with Me</button><button id=incop3 class=buttons003 onclick=qinc()>Johnson Family Vacation</button><button id=incop4 class=buttons003 onclick=qinc()>Another You</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays English cartographer Reginald, in the 1995 dramedy The Englishman Who Went Up a Hill But Came Down a Mountain?",
"answ":"HUGH GRANT",
"answ2":"Hugh Grant.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hugh Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Pierce Brosnan</button><button id=incop3 class=buttons003 onclick=qinc()>Colin Firth</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Nighy</button><br/>",
},
{
"cat":"90s",
"ques":"As corruption grows in 1950s Los Angeles, three policemen investigate a series of murders with their own brand of justice, in what film?",
"answ":"LA CONFIDENTIAL",
"answ3":"L A CONFIDENTIAL",
"answ2":"L.A. Confidential.",
"option":"<button id=corop class=buttons003 onclick=qcor()>L.A. Confidential</button><button id=incop2 class=buttons003 onclick=qinc()>Donnie Brasco</button><button id=incop3 class=buttons003 onclick=qinc()>Fallen</button><button id=incop4 class=buttons003 onclick=qinc()>Out of Sight</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1990 comedy The Freshman, Matthew Broderick's character studies what subject at NYU college?",
"answ":"FILM",
"answ2":"Film.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Film</button><button id=incop2 class=buttons003 onclick=qinc()>History</button><button id=incop3 class=buttons003 onclick=qinc()>Chemistry</button><button id=incop4 class=buttons003 onclick=qinc()>English</button><br/>",
},
{
"cat":"90s",
"ques":"In American History X, Norton's racist character ends up bonding with an African-American man in prison, over their love of what sport?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Basketball</button><button id=incop2 class=buttons003 onclick=qinc()>Baseball</button><button id=incop3 class=buttons003 onclick=qinc()>Football</button><button id=incop4 class=buttons003 onclick=qinc()>Boxing</button><br/>",
},
{
"cat":"90s",
"ques":"Who directed The Long Kiss Goodnight, starring Geena Davis and Samuel L. Jackson?",
"answ":"RENNY HARLIN",
"answ2":"Renny Harlin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Renny Harlin</button><button id=incop2 class=buttons003 onclick=qinc()>Spike Lee</button><button id=incop3 class=buttons003 onclick=qinc()>Kevin Hooks</button><button id=incop4 class=buttons003 onclick=qinc()>Tony Scott</button><br/>",
},
{
"cat":"90s",
"ques":"Which 1992 Woody Allen film was the last collaboration between him and Mia Farrow?",
"answ":"HUSBANDS AND WIVES",
"answ2":"Husbands and Wives.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Husbands and Wives</button><button id=incop2 class=buttons003 onclick=qinc()>Manhattan Murder Mystery</button><button id=incop3 class=buttons003 onclick=qinc()>Shadows and Fog</button><button id=incop4 class=buttons003 onclick=qinc()>Alice</button><br/>",
},
{
"cat":"90s",
"ques":"Kate Winslet starred with Melanie Lynskey in this 1994 film, directed by Peter Jackson.",
"answ":"HEAVENLY CREATURES",
"answ2":"Heavenly Creatures.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Heavenly Creatures</button><button id=incop2 class=buttons003 onclick=qinc()>Braindead</button><button id=incop3 class=buttons003 onclick=qinc()>Forgotten Silver</button><button id=incop4 class=buttons003 onclick=qinc()>The Frighteners</button><br/>",
},
{
"cat":"90s",
"ques":"In Alien 3, what Game of Thrones actor plays former inmate and facility doctor, Dr. Clemens?",
"answ":"CHARLES DANCE",
"answ2":"Charles Dance.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Charles Dance</button><button id=incop2 class=buttons003 onclick=qinc()>Sean Bean</button><button id=incop3 class=buttons003 onclick=qinc()>Iain Glen</button><button id=incop4 class=buttons003 onclick=qinc()>Liam Cunningham</button><br/>",
},
{
"cat":"90s",
"ques":"Natalie Portman makes a cameo as the president's daughter in what 90s comedy?",
"answ":"MARS ATTACKS",
"answ2":"Mars Attacks!.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Wild Wild West</button><button id=incop2 class=buttons003 onclick=qinc()>Hot Shots!</button><button id=incop3 class=buttons003 onclick=qinc()>Get Shorty</button><button id=corop class=buttons003 onclick=qcor()>Mars Attacks!</button><br/>",
},
{
"cat":"90s",
"ques":"In 1990's My Blue Heaven, what famous comedian plays a mobster who moves to suburbia?",
"answ":"STEVE MARTIN",
"answ2":"Steve Martin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Robin Williams</button><button id=incop2 class=buttons003 onclick=qinc()>Eddie Murphy</button><button id=incop3 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=corop class=buttons003 onclick=qcor()>Steve Martin</button><br/>",
},
{
"cat":"90s",
"ques":"Which actress known from TV's The Simpsons, stars as a single mom turned stand-up comic in 1992's This Is My Life?",
"answ":"JULIE KAVNER",
"answ3":"JULIE KAFNER",
"answ2":"Julie Kavner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nancy Cartwright</button><button id=incop2 class=buttons003 onclick=qinc()>Yeardley Smith</button><button id=incop3 class=buttons003 onclick=qinc()>Tress MacNeille</button><button id=corop class=buttons003 onclick=qcor()>Julie Kavner</button><br/>",
},
{
"cat":"90s",
"ques":"What 1992 comedy has multiple endings, including the 'scooby-doo' ending?",
"answ":"WAYNE'S WORLD",
"answ2":"Wayne's World.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ace Ventura: Pet Detective</button><button id=incop2 class=buttons003 onclick=qinc()>The Nutty Professor</button><button id=incop3 class=buttons003 onclick=qinc()>Clue</button><button id=corop class=buttons003 onclick=qcor()>Wayne's World</button><br/>",
},
{
"cat":"90s",
"ques":"What 1999 comedy stars Steve Martin and Eddie Murphy and depicts the making of a fictional film called 'Chubby Rain'?",
"answ":"BOWFINGER",
"answ2":"Bowfinger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mixed Nuts</button><button id=incop2 class=buttons003 onclick=qinc()>Bringing Down the House</button><button id=incop3 class=buttons003 onclick=qinc()>Housesitter</button><button id=corop class=buttons003 onclick=qcor()>Bowfinger</button><br/>",
},
{
"cat":"90s",
"ques":"What Best Picture winning film had the characters Ned Logan, W.W. Beauchamp, Delilah Fitzgerald and Skinny Dubois?",
"answ":"UNFORGIVEN",
"answ2":"Unforgiven.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dances with Wolves</button><button id=incop2 class=buttons003 onclick=qinc()>Platoon</button><button id=incop3 class=buttons003 onclick=qinc()>The Last Emperor</button><button id=corop class=buttons003 onclick=qcor()>Unforgiven</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays Dracula in 1995's Dracula, Dead and Loving It?",
"answ":"LESLIE NIELSEN",
"answ2":"Leslie Nielsen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=corop class=buttons003 onclick=qcor()>Leslie Nielsen</button><button id=incop3 class=buttons003 onclick=qinc()>Steve Martin</button><button id=incop4 class=buttons003 onclick=qinc()>John Cleese</button><br/>",
},
{
"cat":"90s",
"ques":"In the 1990 movie Presumed Innocent, who plays lawyer Alejandro 'Sandy' Stern?",
"answ":"RAUL JULIA",
"answ2":"Raul Julia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Andy Garcia</button><button id=corop class=buttons003 onclick=qcor()>Raul Julia</button><button id=incop3 class=buttons003 onclick=qinc()>Edward James Olmos</button><button id=incop4 class=buttons003 onclick=qinc()>Esai Morales</button><br/>",
},
{
"cat":"90s",
"ques":"In Austin Powers: The Spy Who Shagged Me, Dr. Evil and Scott exchange emotional words on national tv, on whose talk show?",
"answ":"JERRY SPRINGER",
"answ2":"Jerry Springer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dr Phil</button><button id=incop2 class=buttons003 onclick=qinc()>Maury</button><button id=incop3 class=buttons003 onclick=qinc()>Oprah</button><button id=corop class=buttons003 onclick=qcor()>Jerry Springer</button><br/>",
},
{
"cat":"90s",
"ques":"Which 1994 thriller, based on a Michael Crichton novel, stars Michael Douglas and Demi Moore?",
"answ":"DISCLOSURE",
"answ2":"Disclosure.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Game</button><button id=incop2 class=buttons003 onclick=qinc()>Basic Instinct</button><button id=incop3 class=buttons003 onclick=qinc()>A Perfect Murder</button><button id=corop class=buttons003 onclick=qcor()>Disclosure</button><br/>",
},
{
"cat":"90s",
"ques":"What 90s film starring Robert De Niro has Sean Bean as the character Spence, an English firearms specialist dismissed from the team, early in the film?",
"answ":"RONIN",
"answ2":"Ronin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Casino</button><button id=incop2 class=buttons003 onclick=qinc()>A Bronx Tale</button><button id=incop3 class=buttons003 onclick=qinc()>Night and the City</button><button id=corop class=buttons003 onclick=qcor()>Ronin</button><br/>",
},
{
"cat":"90s",
"ques":"What item does Forrest place inside a copy of Curious George in Forrest Gump?",
"answ":"FEATHER",
"answ3":"A FEATHER",
"answ2":"Feather.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Letter</button><button id=incop2 class=buttons003 onclick=qinc()>Ticket</button><button id=corop class=buttons003 onclick=qcor()>Feather</button><button id=incop4 class=buttons003 onclick=qinc()>Medal</button><br/>",
},
{
"cat":"90s",
"ques":"What 1999 drama stars Sarah Michelle Gellar, Ryan Philippe and Reese Witherspoon?",
"answ":"CRUEL INTENTIONS",
"answ2":"Cruel Intentions.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Best Laid Plans</button><button id=incop2 class=buttons003 onclick=qinc()>Playing by Heart</button><button id=corop class=buttons003 onclick=qcor()>Cruel Intentions</button><button id=incop4 class=buttons003 onclick=qinc()>Way of the Gun</button><br/>",
},
{
"cat":"90s",
"ques":"In what 90s film does Nicole Kidman play Suzanne Stone, a local newswoman who conspires to have her husband killed?",
"answ":"TO DIE FOR",
"answ2":"To Die For.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Malice</button><button id=incop2 class=buttons003 onclick=qinc()>Billy Bathgate</button><button id=corop class=buttons003 onclick=qcor()>To Die For</button><button id=incop4 class=buttons003 onclick=qinc()>The Portrait of a Lady</button><br/>",
},
{
"cat":"90s",
"ques":"In Tommy Boy, which comedic actor plays 'auto parts king' Ray Zalinsky?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Candy</button><button id=incop2 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=corop class=buttons003 onclick=qcor()>Dan Aykroyd</button><button id=incop4 class=buttons003 onclick=qinc()>John Belushi</button><br/>",
},
{
"cat":"90s",
"ques":"You'll find the gold Book of Amun-Ra and the black Book of the Dead in what 1999 action horror film?",
"answ":"THE MUMMY",
"answ3":"MUMMY",
"answ2":"The Mummy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Species</button><button id=incop2 class=buttons003 onclick=qinc()>Blade</button><button id=corop class=buttons003 onclick=qcor()>The Mummy</button><button id=incop4 class=buttons003 onclick=qinc()>Spawn</button><br/>",
},
{
"cat":"90s",
"ques":"What 1991 film stars Kathy Bates and Jessica Tandy and tells parallel stories about Alabama women during two different time periods?",
"answ":"FRIED GREEN TOMATOES",
"answ2":"Fried Green Tomatoes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Steel Magnolias</button><button id=corop class=buttons003 onclick=qcor()>Fried Green Tomatoes</button><button id=incop3 class=buttons003 onclick=qinc()>Home Of Our Own</button><button id=incop4 class=buttons003 onclick=qinc()>Used People</button><br/>",
},
{
"cat":"90s",
"ques":"Jerry Zucker directed what 1990 romance film that featured supporting performances from Whoopi Goldberg and Tony Goldwyn?",
"answ":"GHOST",
"answ2":"Ghost.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soapdish</button><button id=incop2 class=buttons003 onclick=qinc()>Ruthless People</button><button id=corop class=buttons003 onclick=qcor()>Ghost</button><button id=incop4 class=buttons003 onclick=qinc()>Corrina, Corrina</button><br/>",
},
{
"cat":"90s",
"ques":"Drew Barrymore stars as a Renaissance-era Cinderella in what 1998 film?",
"answ":"EVER AFTER",
"answ2":"Ever After.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anastasia</button><button id=incop2 class=buttons003 onclick=qinc()>Ella Enchanted</button><button id=corop class=buttons003 onclick=qcor()>Ever After</button><button id=incop4 class=buttons003 onclick=qinc()>Cinderella</button><br/>",
},
{
"cat":"90s",
"ques":"Bill Paxton plays a sleazy car salesman named Simon in what 90s film from director James Cameron?",
"answ":"TRUE LIES",
"answ2":"True Lies.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Abyss</button><button id=incop2 class=buttons003 onclick=qinc()>Terminator 2: Judgment Day</button><button id=corop class=buttons003 onclick=qcor()>True Lies</button><button id=incop4 class=buttons003 onclick=qinc()>Titanic</button><br/>",
},
{
"cat":"90s",
"ques":"Who plays the lead and title character of the 1993 dramedy Dave?",
"answ":"KEVIN KLINE",
"answ2":"Kevin Kline.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=incop2 class=buttons003 onclick=qinc()>Frank Langella</button><button id=corop class=buttons003 onclick=qcor()>Kevin Kline</button><button id=incop4 class=buttons003 onclick=qinc()>Ben Kingsley</button><br/>",
},
{
"cat":"90s",
"ques":"What 1995 film finds human civilization having being relegated to ramshackle floating communities known as atolls?",
"answ":"WATERWORLD",
"answ2":"Waterworld.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Postman</button><button id=incop2 class=buttons003 onclick=qinc()>Battlefield Earth</button><button id=corop class=buttons003 onclick=qcor()>Waterworld</button><button id=incop4 class=buttons003 onclick=qinc()>The Day After Tomorrow</button><br/>",
},
];
nineties = shuffle(nineties);
r2Q8 = shuffle(r2Q8);