function shuffle(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
  return array;
}
var question001 = [
{
"cat":"Disney",
"ques":"Who voices the character of Buzz Lightyear in the Toy Story movies?",
"answ":"TIM ALLEN",
"answ2":"Tim Allen.",
},
{
"cat":"Disney",
"ques":"To which 90s Disney animated film does George Takei lend his voice?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"Which Pixar film features the characters Francis, Slim, Molt and Dot?",
"answ":"A BUG'S LIFE",
"answ3":"A BUGS LIFE",
"answ2":"A Bug's Life.",
},
{
"cat":"Disney",
"ques":"What is the name of the Triceratops toy that Bonnie has in Toy Story 3 and 4?",
"answ":"TRIXIE",
"answ2":"Trixie.",
},
{
"cat":"Disney",
"ques":"Who voices Mr. Soil in A Bug's Life?",
"answ":"RODDY MCDOWALL",
"answ2":"Roddy McDowall.",
},
{
"cat":"Disney",
"ques":"Who voices the Cheshire Cat in the live action Alice in Wonderland films?",
"answ":"STEPHEN FRY",
"answ2":"Stephen Fry.",
},
{
"cat":"Disney",
"ques":"In Maleficent, what material is lethal to fairies?",
"answ":"IRON",
"answ2":"Iron.",
},
{
"cat":"Disney",
"ques":"Kirby is an alien that appears in what Disney animated film?",
"answ":"CHICKEN LITTLE",
"answ2":"Chicken Little.",
},
{
"cat":"Disney",
"ques":"Which Disney princess has a relationship with Prince Charming?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"What kind of pet does Alice have with her at the start of Alice in Wonderland?",
"answ":"CAT",
"answ2":"Cat.",
},
{
"cat":"Disney",
"ques":"What type of animal falls in love with Arthur in The Sword of the Stone?",
"answ":"SQUIRREL",
"answ2":"Squirrel.",
},
{
"cat":"Disney",
"ques":"Moana has two animal sidekicks, a pig and a _____.",
"answ":"ROOSTER",
"answ3":"CHICKEN",
"answ2":"Rooster.",
},
{
"cat":"Disney",
"ques":"Which Lion King character is voiced by Rowan Atkinson?",
"answ":"ZAZU",
"answ2":"Zazu.",
},
{
"cat":"Disney",
"ques":"Which Disney animated film features the characters Eugene, Maximus and Pascal?",
"answ":"TANGLED",
"answ2":"Tangled.",
},
{
"cat":"Disney",
"ques":"Who plays Queen Clarisse in The Princess Diaries?",
"answ":"JULIE ANDREWS",
"answ2":"Julie Andrews.",
},
{
"cat":"Disney",
"ques":"What type of animal is Chief in The Fox and the Hound?",
"answ":"DOG",
"answ2":"Dog.",
},
{
"cat":"Disney",
"ques":"Mackenzie Foy plays the lead Clara Stahlbaum in what 2010s Disney live action film?",
"answ":"THE NUTCRACKER AND THE FOUR REALMS",
"answ3":"NUTCRACKER AND THE FOUR REALMS",
"answ2":"The Nutcracker and the Four Realms.",
},
{
"cat":"Disney",
"ques":"Which Disney animated film features a chief medic named Dr. Joshua Sweet?",
"answ":"ATLANTIS THE LOST EMPIRE",
"answ3":"ATLANTIS",
"answ2":"Atlantis The Lost Empire.",
},
{
"cat":"Disney",
"ques":"Which Pixar film features a landmark called Clawtooth Mountain?",
"answ":"THE GOOD DINOSAUR",
"answ3":"GOOD DINOSAUR",
"answ2":"The Good Dinosaur.",
},
{
"cat":"Disney",
"ques":"David Ogden Stiers is the narrator of 1991's Beauty and the Beast, and also voices which character?",
"answ":"COGSWORTH",
"answ2":"Cogsworth.",
},
{
"cat":"Disney",
"ques":"In Frozen, what is the name of the enchanted snow-monster created to serve as Elsa's palace guard?",
"answ":"MARSHMALLOW",
"answ3":"MARSHMELLOW",
"answ2":"Marshmallow.",
},
{
"cat":"Disney",
"ques":"What type of creature kills Anty, the ant that the kids befriend in Honey, I Shrunk the Kids?",
"answ":"SCORPION",
"answ2":"Scorpion.",
},
{
"cat":"Disney",
"ques":"In which Disney animated film will you find the characters Kala, Kerchak, Terk and Tambor?",
"answ":"TARZAN",
"answ2":"Tarzan.",
},
{
"cat":"Disney",
"ques":"Jennifer Garner and Steve Carrell play parents to a child who wishes his family's day be ruined in what Disney live-action film?",
"answ":"ALEXANDER AND THE TERRIBLE HORRIBLE NO GOOD VERY BAD DAY",
"answ2":"Alexander and the Terrible, Horrible, No Good, Very Bad Day.",
},
{
"cat":"Disney",
"ques":"In Wreck-It Ralph, what game does Sergeant Calhoun originate from?",
"answ":"HERO'S DUTY",
"answ2":"Hero's Duty.",
},
{
"cat":"Disney",
"ques":"In Zootopia, what is the name of the red fox that bullies Judy as a child?",
"answ":"GIDEON",
"answ3":"GIDEON GREY",
"answ2":"Gideon Grey.",
},
{
"cat":"Disney",
"ques":"What is the name of the legendary feral bear from Brave?",
"answ":"MOR'DU",
"answ3":"MORDU",
"answ2":"Mor'du.",
},
{
"cat":"Disney",
"ques":"In Zootopia, what is the name of the sloth work works at the DMV?",
"answ":"FLASH",
"answ2":"Flash.",
},
{
"cat":"Disney",
"ques":"In Wreck-It Ralph, what is the name of the town inside of the Fix-It Felix Jr game?",
"answ":"NICELAND",
"answ2":"Niceland.",
},
{
"cat":"Disney",
"ques":"What is the name of Moana's grandmother?",
"answ":"TALA",
"answ3":"GRAMMA TALA",
"answ2":"Tala.",
},
{
"cat":"Disney",
"ques":"In Frozen, what is the name of Elsa and Anna's father?",
"answ":"KING AGNARR",
"answ3":"AGNARR",
"answ2":"Agnarr.",
},
{
"cat":"Disney",
"ques":"In the original Aladdin, what is the name of the Captain of the Sultan's guard?",
"answ":"RAZOUL",
"answ2":"Razoul.",
},
{
"cat":"Disney",
"ques":"What is the name of the Tremaine family's black cat in Cinderella?",
"answ":"LUCIFER",
"answ2":"Lucifer.",
},
{
"cat":"Disney",
"ques":"Mulan is set in which country?",
"answ":"CHINA",
"answ2":"China.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Bagheera in The Jungle Book?",
"answ":"PANTHER",
"answ3":"BLACK PANTHER",
"answ2":"Panther.",
},
{
"cat":"Disney",
"ques":"Which famous actor voiced John Smith in the 1995 version of Pocahontas?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Disney",
"ques":"What is the first name of Bob Parrs wife in The Incredibles?",
"answ":"HELEN",
"answ2":"Helen.",
},
{
"cat":"Disney",
"ques":"What kind of animal is Big Mama in the film The Fox and the Hound?",
"answ":"OWL",
"answ2":"Owl.",
},
{
"cat":"Disney",
"ques":"Flik is the leading character in which Pixar film?",
"answ":"A BUG'S LIFE",
"answ3":"A BUGS LIFE",
"answ2":"A Bug's Life.",
},
{
"cat":"Disney",
"ques":"Kingdom of the Sun was the original title of which 2000 Disney film?",
"answ":"THE EMPEROR'S NEW GROOVE",
"answ3":"EMPEROR'S NEW GROOVE",
"answ2":"The Emperor's New Groove.",
},
{
"cat":"Disney",
"ques":"Who voiced the Genie in the 1992 Disney film Aladdin?",
"answ":"ROBIN WILLIAMS",
"answ2":"Robin Williams.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Iago in Aladdin?",
"answ":"PARROT",
"answ3":"MACAW",
"answ2":"Parrot/Macaw.",
},
{
"cat":"Disney",
"ques":"In which Disney film would you find the song 'Under the Sea'?",
"answ":"THE LITTLE MERMAID",
"answ3":"LITTLE MERMAID",
"answ2":"The Little Mermaid.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Bill the chimney sweep in Alice in Wonderland?",
"answ":"LIZARD",
"answ2":"Lizard.",
},
{
"cat":"Disney",
"ques":"Which Disney film centres around the character of a deformed bell ringer?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"The suburban town Oakey Oakes is the setting for which 2000s Disney film?",
"answ":"CHICKEN LITTLE",
"answ2":"Chicken Little.",
},
{
"cat":"Disney",
"ques":"In what year is the movie Wall-E set?",
"answ":"2805",
"answ2":"2805.",
},
{
"cat":"Disney",
"ques":"Which Disney movie is mainly set on Dixon Ranch?",
"answ":"HOME ON THE RANGE",
"answ2":"Home on the Range.",
},
{
"cat":"Disney",
"ques":"Which famous actress voiced Jane in 1999's Tarzan?",
"answ":"MINNIE DRIVER",
"answ2":"Minnie Driver.",
},
{
"cat":"Disney",
"ques":"Who provided the voice for the character Hopper in A Bugs Life?",
"answ":"KEVIN SPACEY",
"answ2":"Kevin Spacey.",
},
{
"cat":"Disney",
"ques":"Who voiced Bolt in the movie of the same name?",
"answ":"JOHN TRAVOLTA",
"answ2":"John Travolta.",
},
{
"cat":"Disney",
"ques":"The Lion king is loosely based on which Shakespeare play?",
"answ":"HAMLET",
"answ2":"Hamlet.",
},
{
"cat":"Disney",
"ques":"What is the name of Aladdin's love interest?",
"answ":"JASMINE",
"answ3":"JASMIN",
"answ2":"Jasmine.",
},
{
"cat":"Disney",
"ques":"What kind of fish is Nemo?",
"answ":"CLOWNFISH",
"answ3":"CLOWN FISH",
"answ2":"Clownfish.",
},
{
"cat":"Disney",
"ques":"What type of object is Cogsworth, in the Disney film Beauty and The Beast?",
"answ":"CLOCK",
"answ3":"A CLOCK",
"answ2":"Clock.",
},
{
"cat":"Disney",
"ques":"What was the original name of Mickey Mouse?",
"answ":"MORTIMER MOUSE",
"answ3":"MORTIMER",
"answ2":"Mortimer.",
},
{
"cat":"Disney",
"ques":"What is the name of the little girl who is unafraid of all monsters except Randall in Monsters Inc?",
"answ":"BOO",
"answ2":"Boo.",
},
{
"cat":"Disney",
"ques":"What famous comedian voiced Mushu in the film Mulan?",
"answ":"EDDIE MURPHY",
"answ2":"Eddie Murphy.",
},
{
"cat":"Disney",
"ques":"How many wishes does the Genie grant to Aladdin when emerging from the magic lamp?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Disney",
"ques":"Peach, Bloat, Gurgle and Bubbles are all characters in which movie?",
"answ":"FINDING NEMO",
"answ3":"FINDING DORY",
"answ2":"Finding Nemo.",
},
{
"cat":"Disney",
"ques":"What is the name of the Fox in the 1981 movie The Fox and the Hound?",
"answ":"TOD",
"answ3":"TODD",
"answ2":"Tod.",
},
{
"cat":"Disney",
"ques":"In which city is The Aristocats set?",
"answ":"PARIS",
"answ2":"Paris.",
},
{
"cat":"Disney",
"ques":"What kind of animal is Wheezy, a toy Woody meets in Toy Story 2?",
"answ":"PENGUIN",
"answ3":"A PENGUIN",
"answ2":"Penguin.",
},
{
"cat":"Disney",
"ques":"Which Disney film featured Demi Moore, Kevin Kline and Jason Alexander as voice actors?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"Which is the only one of the Seven Dwarfs not to have a beard?",
"answ":"DOPEY",
"answ2":"Dopey.",
},
{
"cat":"Disney",
"ques":"What year saw the release of the original Lady and The Tramp?",
"answ":"1955",
"answ2":"1955.",
},
{
"cat":"Disney",
"ques":"Pacha, voiced by John Goodman, appears in which Disney film?",
"answ":"THE EMPEROR'S NEW GROOVE",
"answ3":"EMPEROR'S NEW GROOVE",
"answ2":"The Emperors New Groove.",
},
{
"cat":"Disney",
"ques":"In what decade did Disney release Snow White and The Seven Dwarfs?",
"answ":"1930S",
"answ3":"30S",
"answ2":"1930s.",
},
{
"cat":"Disney",
"ques":"Pongo is a leading character in which Disney movie?",
"answ":"ONE HUNDRED AND ONE DALMATIANS",
"answ3":"101 DALMATIANS",
"answ2":"One Hundred and One Dalmatians.",
},
{
"cat":"Disney",
"ques":"Geppetto is a character in which Disney film?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Disney",
"ques":"In 2009 what became the second animated film in history to be nominated for a Best Picture Oscar?",
"answ":"UP",
"answ2":"Up.",
},
{
"cat":"Disney",
"ques":"Jim Hawkins is the leading character of which film?",
"answ":"TREASURE PLANET",
"answ2":"Treasure Planet.",
},
{
"cat":"Disney",
"ques":"Who voices Scar in the original The Lion King?",
"answ":"JEREMY IRONS",
"answ2":"Jeremy Irons.",
},
{
"cat":"Disney",
"ques":"In what year was The Aristocats released?",
"answ":"1970",
"answ2":"1970.",
},
{
"cat":"Disney",
"ques":"Esmeralda is the romantic interest in which Disney film?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"Doctor Calico is the villain in which 2000s Disney movie?",
"answ":"BOLT",
"answ2":"Bolt.",
},
{
"cat":"Disney",
"ques":"'When You Wish Upon a Star' is an Oscar winning song from which movie?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Disney",
"ques":"In which city is One Hundred and One Dalmatians set?",
"answ":"LONDON",
"answ2":"London.",
},
{
"cat":"Disney",
"ques":"What is first name of Pongo's owner in One Hundred and One Dalmatians?",
"answ":"ROGER",
"answ3":"ROGER RADCLIFFE",
"answ2":"Roger.",
},
{
"cat":"Disney",
"ques":"What is the name of Lady's owner in Lady and The Tramp?",
"answ":"DARLING",
"answ3":"ELIZABETH",
"answ2":"Darling.",
},
{
"cat":"Disney",
"ques":"What year was Chicken Little released?",
"answ":"2005",
"answ2":"2005.",
},
{
"cat":"Disney",
"ques":"What is the name of the character voiced by Eva Garbor in The Aristocats?",
"answ":"DUCHESS",
"answ2":"Duchess.",
},
{
"cat":"Disney",
"ques":"Madame Medusa is a villainous treasure huntress in which Disney film?",
"answ":"THE RESCUERS",
"answ2":"The Rescuers.",
},
{
"cat":"Disney",
"ques":"Princess Atta appears in which Pixar film?",
"answ":"A BUG'S LIFE",
"answ2":"A Bug's Life.",
},
{
"cat":"Disney",
"ques":"What colour is the fairy who brings Pinocchio to life in the 1940 film?",
"answ":"BLUE",
"answ2":"Blue.",
},
{
"cat":"Disney",
"ques":"What kind of animal is the Disney character Thomas O Malley?",
"answ":"CAT",
"answ2":"Cat.",
},
{
"cat":"Disney",
"ques":"In what year was the film Pocahontas released?",
"answ":"1995",
"answ2":"1995.",
},
{
"cat":"Disney",
"ques":"What was the name of the mouse who was Dumbo's best friend?",
"answ":"TIMOTHY",
"answ3":"TIMOTHY Q MOUSE",
"answ2":"Timothy Q. Mouse.",
},
{
"cat":"Disney",
"ques":"Kaa, who features in The Jungle Book, is what kind of creature?",
"answ":"SNAKE",
"answ3":"PYTHON",
"answ2":"Python/Snake.",
},
{
"cat":"Disney",
"ques":"Ilene Woods provided the voice for which Disney Princess?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"'You Can Fly' and 'A Pirates Life' are songs from which Disney film?",
"answ":"PETER PAN",
"answ2":"Peter Pan.",
},
{
"cat":"Disney",
"ques":"What is the name of Bolt's human co-star in his TV show featured in the movie Bolt?",
"answ":"PENNY",
"answ2":"Penny.",
},
{
"cat":"Disney",
"ques":"What is the name of Marlin's wife and Nemo's mother in Finding Nemo?",
"answ":"CORAL",
"answ2":"Coral.",
},
{
"cat":"Disney",
"ques":"How many puppies does Perdiat first give birth to in One Hundred and One Dalmatians?",
"answ":"FIFTEEN",
"answ3":"15",
"answ2":"15.",
},
{
"cat":"Disney",
"ques":"In Pinocchio the fairy tells Pinocchio that he can only become a real boy if he is 'Brave, truthful and ____'",
"answ":"UNSELFISH",
"answ2":"Unselfish.",
},
{
"cat":"Disney",
"ques":"In what year was the original Cinderella released?",
"answ":"1950",
"answ2":"1950.",
},
{
"cat":"Disney",
"ques":"What kind of animal is Flower in the animated movie Bambi?",
"answ":"SKUNK",
"answ2":"Skunk.",
},
{
"cat":"Disney",
"ques":"What kind of animal is Bambi's friend Thumper?",
"answ":"RABBIT",
"answ3":"BUNNY",
"answ2":"Rabbit.",
},
{
"cat":"Disney",
"ques":"In Toy Story, what was the name of the TV Show of which Woody was the star?",
"answ":"WOODY'S ROUND UP",
"answ3":"WOODY'S ROUNDUP",
"answ2":"Woody's Round Up.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Shere Khan in The Jungle Book?",
"answ":"TIGER",
"answ3":"BENGAL TIGER",
"answ2":"Tiger.",
},
{
"cat":"Disney",
"ques":"In Toy Story 2, what was the name of the Horse?",
"answ":"BULLSEYE",
"answ2":"Bullseye.",
},
{
"cat":"Disney",
"ques":"What is the name of Aladdin's monkey?",
"answ":"ABU",
"answ2":"Abu.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Sebestian in The Little Mermaid?",
"answ":"CRAB",
"answ2":"Crab.",
},
{
"cat":"Disney",
"ques":"Monstropolis is the setting for which film?",
"answ":"MONSTERS INC",
"answ2":"Monsters Inc.",
},
{
"cat":"Disney",
"ques":"What is the name of Woody's owner in Toy Story?",
"answ":"ANDY",
"answ2":"Andy.",
},
{
"cat":"Disney",
"ques":"Which actress provides the voice of Esmeralda in The Hunchback of Notre Dame?",
"answ":"DEMI MOORE",
"answ2":"Demi Moore.",
},
{
"cat":"Disney",
"ques":"What type of bird does Ariel take her Earthly goods to for investigation on The Little Mermaid?",
"answ":"SEAGULL",
"answ3":"GULL",
"answ2":"Seagull.",
},
{
"cat":"Disney",
"ques":"In which country is the film The Hunchback of Notre Dame set?",
"answ":"FRANCE",
"answ2":"France.",
},
{
"cat":"Disney",
"ques":"Who voices the character of Rapunzel in Tangled?",
"answ":"MANDY MOORE",
"answ2":"Mandy Moore.",
},
{
"cat":"Disney",
"ques":"Who voices the character of Lightning McQueen in Cars?",
"answ":"OWEN WILSON",
"answ2":"Owen Wilson.",
},
{
"cat":"Disney",
"ques":"'My Funny Friend and Me' is a song from which 2000s Disney film??",
"answ":"THE EMPEROR'S NEW GROOVE",
"answ3":"EMPEROR'S NEW GROOVE",
"answ2":"The Emperors New Groove.",
},
{
"cat":"Disney",
"ques":"What is the name of Ariel's fish friend The Little Mermaid?",
"answ":"FLOUNDER",
"answ2":"Flounder.",
},
{
"cat":"Disney",
"ques":"What character is held prisoner by Madame Medusa in The Rescuers?",
"answ":"PENNY",
"answ2":"Penny.",
},
{
"cat":"Disney",
"ques":"Wreck it Ralph was released in which year?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Disney",
"ques":"What is the name of the Hound in the 1981 movie The Fox and the Hound?",
"answ":"COPPER",
"answ2":"Copper.",
},
{
"cat":"Disney",
"ques":"Which restaurant does Andy visit on his birthday in Toy Story?",
"answ":"PIZZA PLANET",
"answ2":"Pizza Planet.",
},
{
"cat":"Disney",
"ques":"What instrument does the alligator play who offers to undo Naveen's curse in The Princess and the Frog?",
"answ":"TRUMPET",
"answ2":"Trumpet.",
},
{
"cat":"Disney",
"ques":"In Beauty and The Beats what type of object is Lumiere?",
"answ":"CANDLE",
"answ3":"CANDELABRA",
"answ2":"Candle/Candelabra.",
},
{
"cat":"Disney",
"ques":"What does Ariel sacrifice to be given human legs in The Little Mermaid?",
"answ":"HER VOICE",
"answ3":"VOICE",
"answ2":"Her voice.",
},
{
"cat":"Disney",
"ques":"What is the name of the Bloodhound dog featured in Lady and the Tramp?",
"answ":"TRUSTY",
"answ2":"Trusty.",
},
{
"cat":"Disney",
"ques":"Who voices Ralph in the 2012 movie Wreck it Ralph?",
"answ":"JOHN C REILLY",
"answ2":"John C. Reilly.",
},
{
"cat":"Disney",
"ques":"In which Disney film would you hear the song 'Be Our Guest'?",
"answ":"BEAUTY AND THE BEAST",
"answ2":"Beauty and The Beast.",
},
{
"cat":"Disney",
"ques":"What is the name of Ariel's father and King in The Little Mermaid?",
"answ":"KING TRITON",
"answ3":"TRITON",
"answ2":"Triton.",
},
{
"cat":"Disney",
"ques":"What is the name of Jafar's bird in Aladdin?",
"answ":"IAGO",
"answ2":"Iago.",
},
{
"cat":"Disney",
"ques":"What kind of animal is Sergeant Tibbs in One Hundred and One Dalmatians?",
"answ":"CAT",
"answ2":"Cat.",
},
{
"cat":"Disney",
"ques":"Who provides the voice of adult Simba in the original The Lion King?",
"answ":"MATTHEW BRODERICK",
"answ2":"Matthew Broderick.",
},
{
"cat":"Disney",
"ques":"Bob Parr is a leading character, and head of the family, in which animated movie?",
"answ":"THE INCREDIBLES",
"answ3":"INCREDIBLES",
"answ2":"The Incredibles.",
},
{
"cat":"Disney",
"ques":"Which Disney film celebrated its 70th Anniversary in 2007?",
"answ":"SNOW WHITE AND THE SEVEN DWARFS",
"answ3":"SNOW WHITE",
"answ2":"Snow White and the Seven Dwarfs.",
},
{
"cat":"Disney",
"ques":" What is the name of the yodelling cowgirl that Woody meets in Toy Story 2?",
"answ":"JESSIE",
"answ3":"JESSY",
"answ2":"Jessie.",
},
{
"cat":"Disney",
"ques":"What is the name of the masculine hunter who seeks Belle's affections in Beauty and the Beast?",
"answ":"GASTON",
"answ2":"Gaston.",
},
{
"cat":"Disney",
"ques":"What part of Woody is ripped off in Toy Story 2 forcing Andy to leave him behind?",
"answ":"ARM",
"answ3":"HIS ARM",
"answ2":"His arm.",
},
{
"cat":"Disney",
"ques":"Thomas O'Malley is a character in which Disney film?",
"answ":"ARISTOCATS",
"answ3":"THE ARISTOCATS",
"answ2":"The Aristocats.",
},
{
"cat":"Disney",
"ques":"What is the name of the robot that Wall-E falls in love with?",
"answ":"EVE",
"answ2":"EVE.",
},
{
"cat":"Disney",
"ques":"'Sing Sweet Nightingale' and 'The Work Song' feature in which Disney movie?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"Who was the composer for the original The Lion King?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Disney",
"ques":"What is the name of the Scottish Terrier in Lady and the Tramp?",
"answ":"JOCK",
"answ2":"Jock.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Timon in The Lion King?",
"answ":"MEERKAT",
"answ2":"Meerkat.",
},
{
"cat":"Disney",
"ques":"'The Circle of Life' is a song that features in which Disney film?",
"answ":"THE LION KING",
"answ3":"LION KING",
"answ2":"The Lion King.",
},
{
"cat":"Disney",
"ques":"What is the name of Dumbo's mother?",
"answ":"MRS JUMBO",
"answ3":"JUMBO",
"answ2":"Mrs Jumbo.",
},
{
"cat":"Disney",
"ques":"Tangled was released in which year?",
"answ":"2010",
"answ2":"2010.",
},
{
"cat":"Disney",
"ques":"In The Rescuers in which city is the Rescue Aid Society located?",
"answ":"NEW YORK",
"answ2":"New York.",
},
{
"cat":"Disney",
"ques":"Dairy cows named Maggie, Mrs. Colloway and Grace are leading characters in which movie?",
"answ":"HOME ON THE RANGE",
"answ2":"Home on the Range.",
},
{
"cat":"Disney",
"ques":"Which year saw the release of the first Monsters Inc movie?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Disney",
"ques":"Which God is the father of Hercules in the Disney film of the same name?",
"answ":"ZEUS",
"answ2":"Zeus.",
},
{
"cat":"Disney",
"ques":"What is the name of the young tea cup who befriends Belle in Beauty and The Beast?",
"answ":"CHIP",
"answ2":"Chip.",
},
{
"cat":"Disney",
"ques":"Lewis, an aspiring young inventor at an orphanage, is the lead character in which film?",
"answ":"MEET THE ROBINSONS",
"answ2":"Meet the Robinsons.",
},
{
"cat":"Disney",
"ques":"In what year was The Little Mermaid released?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Disney",
"ques":"In what year was the original The Lion King released?",
"answ":"1994",
"answ2":"1994.",
},
{
"cat":"Disney",
"ques":"In what year was the original Beauty and the Beast released?",
"answ":"1991",
"answ2":"1991.",
},
{
"cat":"Disney",
"ques":"Which animated Disney movie is based on a book by Edgar Rice Burroughs?",
"answ":"TARZAN",
"answ2":"Tarzan.",
},
{
"cat":"Disney",
"ques":"In which Disney film would you find the song 'Love is a Song'?",
"answ":"BAMBI",
"answ2":"Bambi.",
},
{
"cat":"Disney",
"ques":"The Disney animated classic One Hundred and One Dalmatians was released in which year?",
"answ":"1961",
"answ2":"1961.",
},
{
"cat":"Disney",
"ques":"Mr Smee is a villainous character in which film?",
"answ":"PETER PAN",
"answ2":"Peter Pan.",
},
{
"cat":"Disney",
"ques":"Peter Pan was released in which year?",
"answ":"1953",
"answ2":"1953.",
},
{
"cat":"Disney",
"ques":"'When You Wish Upon A Star' is featured in which Disney film?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Disney",
"ques":"In what decade was the original Alice in Wonderland released??",
"answ":"1950S",
"answ3":"50S",
"answ2":"1950s.",
},
{
"cat":"Disney",
"ques":"What is the name of Simba's love interest in The Lion King?",
"answ":"NALA",
"answ2":"Nala.",
},
{
"cat":"Disney",
"ques":"What colour is Pinocchio's hat?",
"answ":"YELLOW",
"answ2":"Yellow.",
},
{
"cat":"Disney",
"ques":"What is the name of the evil Fairy in Sleeping Beauty?",
"answ":"MALEFICENT",
"answ2":"Maleficent.",
},
{
"cat":"Disney",
"ques":"Which 90S Disney film is set in the year 1607?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Disney",
"ques":"What was the third animated feature film to be released by Disney?",
"answ":"FANTASIA",
"answ2":"Fantasia.",
},
{
"cat":"Disney",
"ques":"Lady Tremaine is the step mother of whom?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"In the Jungle Book what kind of animal is Colonel Hathi?",
"answ":"ELEPHANT",
"answ3":"AN ELEPHANT",
"answ2":"Elephant.",
},
{
"cat":"Disney",
"ques":"'What Made the Red Man Red' is a key song in which film?",
"answ":"PETER PAN",
"answ2":"Peter Pan.",
},
{
"cat":"Disney",
"ques":"What was the first Disney animated film to be nominated for a Best Picture Oscar?",
"answ":"BEAUTY AND THE BEAST",
"answ2":"Beauty and the Beast.",
},
{
"cat":"Disney",
"ques":"Tony's Italian Restaurant is key to which film?",
"answ":"LADY AND THE TRAMP",
"answ2":"Lady and the Tramp.",
},
{
"cat":"Disney",
"ques":"Leopold Stokowski famously conducted the music to which film?",
"answ":"FANTASIA",
"answ2":"Fantasia.",
},
{
"cat":"Disney",
"ques":"Which of the 7 Dwarfs wears glasses?",
"answ":"DOC",
"answ2":"Doc.",
},
{
"cat":"Disney",
"ques":"Jaq and Gus are animal friends of whom?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"In which film do characters recall the tale of The Walrus and the Carpenter?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
},
{
"cat":"Disney",
"ques":"Who is Princess Aurora's mother?",
"answ":"LEAH",
"answ3":"QUEEN LEAH",
"answ2":"Queen Leah.",
},
{
"cat":"Disney",
"ques":"Who is Princess Aurora's father?",
"answ":"STEFAN",
"answ3":"KING STEFAN",
"answ2":"King Stefan.",
},
{
"cat":"Disney",
"ques":"Dinky and Boomer are characters in which film?",
"answ":"THE FOX AND THE HOUND",
"answ3":"FOX AND THE HOUND",
"answ2":"The Fox and the Hound.",
},
{
"cat":"Disney",
"ques":"Drizella is a character in which Disney movie?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"Olivia Flaversham is the main character in which film?",
"answ":"THE GREAT MOUSE DETECTIVE",
"answ3":"GREAT MOUSE DETECTIVE",
"answ2":"The Great Mouse Detective.",
},
{
"cat":"Disney",
"ques":"What year was the original Bambi released??",
"answ":"1942",
"answ2":"1942.",
},
{
"cat":"Disney",
"ques":"Tweedledum can be found in which film?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
},
{
"cat":"Disney",
"ques":"Which Disney film begins with the death of the King of England?",
"answ":"THE SWORD IN THE STONE",
"answ3":"SWORD IN THE STONE",
"answ2":"The Sword in the Stone.",
},
{
"cat":"Disney",
"ques":"Flora, Fauna and Merryweather feature in which movie?",
"answ":"SLEEPING BEAUTY",
"answ2":"Sleeping Beauty.",
},
{
"cat":"Disney",
"ques":"'Biddidi-Boddidi-Boo' comes from which film?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"Which Disney film begins with a flock of storks delivering babies?",
"answ":"DUMBO",
"answ2":"Dumbo.",
},
{
"cat":"Disney",
"ques":"A bottle of potion marked Drink Me is key to which film?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
},
{
"cat":"Disney",
"ques":"'A Dream is a Wish Your Hart Makes' is a song from which Disney film?",
"answ":"CINDERELLA",
"answ2":"Cinderella.",
},
{
"cat":"Disney",
"ques":"'Trust In Me' is a song from which Disney film?",
"answ":"THE JUNGLE BOOK",
"answ2":"The Jungle Book.",
},
{
"cat":"Disney",
"ques":"What is the Darling family's father called in Peter Pan?",
"answ":"GEORGE",
"answ3":"GEORGE DARLING",
"answ2":"George.",
},
{
"cat":"Disney",
"ques":"In Pinocchio what kind of animal is Gideon?",
"answ":"CAT",
"answ2":"Cat.",
},
{
"cat":"Disney",
"ques":"'Chim Chim Cher-ee'  is a song from which Disney film?",
"answ":"MARY POPPINS",
"answ2":"Mary Poppins.",
},
{
"cat":"Disney",
"ques":"What is the name of Pocanhontas' father?",
"answ":"CHIEF POWHATAN",
"answ3":"POWHATAN",
"answ2":"Chief Powhatan.",
},
{
"cat":"Disney",
"ques":"What year was Sleeping Beauty released?",
"answ":"1959",
"answ2":"1959.",
},
{
"cat":"Disney",
"ques":"Princess Aurora is the leading role in which film?",
"answ":"SLEEPING BEAUTY",
"answ2":"Sleeping Beauty.",
},
{
"cat":"Disney",
"ques":"'Baby Mine' is a musical number in which Disney film?",
"answ":"DUMBO",
"answ2":"Dumbo.",
},
{
"cat":"Disney",
"ques":"Which was the second Disney animated feature film to be released?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Disney",
"ques":"A Whole New World is a song from which Disney film?",
"answ":"ALADDIN",
"answ3":"ALLADIN",
"answ2":"Aladdin.",
},
{
"cat":"Disney",
"ques":"Honest John the Fox leads the character astray in which film?",
"answ":"PINOCCHIO",
"answ3":"PINOCHIO",
"answ2":"Pinocchio.",
},
{
"cat":"Disney",
"ques":"Professor Rattigan is the main villain in which film?",
"answ":"THE GREAT MOUSE DETECTIVE",
"answ3":"GREAT MOUSE DETECTIVE",
"answ2":"The Great Mouse Detective.",
},
{
"cat":"Disney",
"ques":"The lead character in which film is often called 'Wart'?",
"answ":"THE SWORD IN THE STONE",
"answ3":"SWORD IN THE STONE",
"answ2":"The Sword in the Stone.",
},
{
"cat":"Disney",
"ques":"'Let's Get Together' is a song from which live-action Disney film?",
"answ":"THE PARENT TRAP",
"answ2":"The Parent Trap.",
},
{
"cat":"Disney",
"ques":"The Unbirthday Song can be found in which Disney film?",
"answ":"ALICE IN WONDERLAND",
"answ2":"Alice in Wonderland.",
},
{
"cat":"Disney",
"ques":"In which city is the Great Mouse Detective set?",
"answ":"LONDON",
"answ2":"London.",
},
{
"cat":"Disney",
"ques":" What us the name of Wendy Darlings mother in Peter Pan?",
"answ":"MARY",
"answ3":"MARY DARLING",
"answ2":"Mary Darling.",
},
{
"cat":"Disney",
"ques":"What does Hakuna Matata mean?",
"answ":"NO WORRIES",
"answ2":"No Worries.",
},
{
"cat":"Disney",
"ques":"In Aladdin, what is the name of Jasmine's pet tiger?",
"answ":"RAJAH",
"answ3":"RAJA",
"answ2":"Rajah.",
},
{
"cat":"Disney",
"ques":"The song 'I'll Make a Man Out of You', is performed while young men are trained to be soldiers for war in what Disney film?",
"answ":"MULAN",
"answ2":"Mulan.",
},
{
"cat":"Disney",
"ques":"What classic Disney film is a series of animated scenes set to famous classical music pieces, such as The Nutcracker Suite?",
"answ":"FANTASIA",
"answ2":"Fantasia.",
},
{
"cat":"Disney",
"ques":"This Academy Award winning actress played Lady Tremaine, the evil stepmother in Disney's live-action adaptation of Cinderella.",
"answ":"CATE BLANCHETT",
"answ3":"KATE BLANCHETT",
"answ2":"Cate Blanchett.",
},
{
"cat":"Disney",
"ques":"What Disney villain has blue flames for hair?",
"answ":"HADES",
"answ2":"Hades.",
},
{
"cat":"Disney",
"ques":"Which SNL alum provides the voice of Kuzco in The Emperor's New Groove?",
"answ":"DAVID SPADE",
"answ2":"David Spade.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin who does Aladdin pretend to be to safe Jasmine from having her hand cut off by the merchant in the marketplace?",
"answ":"HER BROTHER",
"answ3":"BROTHER",
"answ2":"Her brother.",
},
{
"cat":"Disney",
"ques":"What Disney animated film series features two lead characters by the names of Bernard and Bianca?",
"answ":"THE RESCUERS",
"answ3":"RESCUERS",
"answ2":"The Rescuers.",
},
{
"cat":"Disney",
"ques":"What 2016 Disney remake stars Robert Redford and Bryce Dallas Howard?",
"answ":"PETE'S DRAGON",
"answ2":"Pete's Dragon.",
},
{
"cat":"Disney",
"ques":"What 1954 Disney film features Captain Nemo, and his ship, the Nautilus?",
"answ":"20000 LEAGUES UNDER THE SEA",
"answ3":"20 000 LEAGUES UNDER THE SEA",
"answ2":"20,000 Leagues Under the Sea.",
},
{
"cat":"Disney",
"ques":"What Disney animated movie features the Billy Joel song 'Why Should I Worry'?",
"answ":"OLIVER AND COMPANY",
"answ2":"Oliver & Company.",
},
{
"cat":"Disney",
"ques":"Prince Philip is the prince from what Disney animated classic?",
"answ":"SLEEPING BEAUTY",
"answ2":"Sleeping Beauty.",
},
{
"cat":"Disney",
"ques":"What country does the Disney classic Beauty and the Beast take place in?",
"answ":"FRANCE",
"answ2":"France.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, what kind of animals are Ursula's pets?",
"answ":"EELS",
"answ3":"MORAY EELS",
"answ2":"Eels.",
},
{
"cat":"Disney",
"ques":"You'll find a demon-like villain named The Horned King in what Disney animated film?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"What was the name of the sequel to Disney's The Rescuers?",
"answ":"THE RESCUERS DOWN UNDER",
"answ3":"RESCUERS DOWN UNDER",
"answ2":"The Rescuers Down Under.",
},
{
"cat":"Disney",
"ques":"The world 'parley' is used in order to stop a fight and talk things out in what live-action Disney adventure?",
"answ":"PIRATES OF THE CARIBBEAN",
"answ3":"PIRATES OF THE CARIBBEAN THE CURSE OF THE BLACK PEARL",
"answ2":"Pirates of the Caribbean: The Curse of the Black Pearl.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, for how many years does the Genie tell Aladdin he's been trapped in the lamp?",
"answ":"10 000",
"answ3":"10000",
"answ2":"10,000.",
},
{
"cat":"Disney",
"ques":"In 1992's Aladdin, what is the name of the flying carpet?",
"answ":"CARPET",
"answ2":"Carpet.",
},
{
"cat":"Disney",
"ques":"Who plays the singing prince in the live-action animation hybrid Enchanted?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
},
{
"cat":"Disney",
"ques":"In Disney's Robin Hood, what type of animal is Robin Hood?",
"answ":"FOX",
"answ2":"Fox.",
},
{
"cat":"Disney",
"ques":"Captain Hook has his hook on his ____ hand.",
"answ":"LEFT",
"answ3":"LEFT HAND",
"answ2":"His left hand.",
},
{
"cat":"Disney",
"ques":"Who voices Iago in 1992's Aladdin?",
"answ":"GILBERT GOTTFRIED",
"answ2":"Gilbert Gottfried.",
},
{
"cat":"Disney",
"ques":"What is the name of the walking talking clock in Disney's Beauty and the Beast?",
"answ":"COGSWORTH",
"answ2":"Cogsworth.",
},
{
"cat":"Disney",
"ques":"Tiana is the name of the lead character in what Disney film?",
"answ":"THE PRINCESS AND THE FROG",
"answ3":"PRINCESS AND THE FROG",
"answ2":"The Princess and the Frog.",
},
{
"cat":"Disney",
"ques":"Judge Frollo is the villain of which Disney film?",
"answ":"THE HUNCHBACK OF NOTRE DAME",
"answ3":"HUNCHBACK OF NOTRE DAME",
"answ2":"The Hunchback of Notre Dame.",
},
{
"cat":"Disney",
"ques":"Meeko and Flit are the names of two characters in what Disney film?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Disney",
"ques":"Which Disney film features a pig herder named Taran who must go on a quest to stop the evil Horned King?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"Mandy Moore and Zachary Levi provide voices in which Disney film?",
"answ":"TANGLED",
"answ2":"Tangled.",
},
{
"cat":"Disney",
"ques":"Herbie Rides Again was the sequel to what Disney classic?",
"answ":"THE LOVE BUG",
"answ2":"The Love Bug.",
},
{
"cat":"Disney",
"ques":"What is the name of the supervillain in The Incredibles?",
"answ":"SYNDROME",
"answ2":"Syndrome.",
},
{
"cat":"Disney",
"ques":"At the end of Toy Story, what gift does Andy get for Christmas?",
"answ":"PUPPY",
"answ3":"DOG",
"answ2":"Puppy/Dog.",
},
{
"cat":"Disney",
"ques":"Who composed the score for Up?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Disney",
"ques":"What was Pixar's third theatrically released film that was released in 1999?",
"answ":"TOY STORY 2",
"answ2":"Toy Story 2.",
},
{
"cat":"Disney",
"ques":"What is the first and last name of the one-eyed green monster voiced by Billy Crystal in Monster's, Inc?",
"answ":"MIKE WAZOWSKI",
"answ2":"Mike Wazowski.",
},
{
"cat":"Disney",
"ques":"Toy Story was the first film released by Pixar, which 1998 film was the second?",
"answ":"A BUG'S LIFE",
"answ2":"A Bug's Life.",
},
{
"cat":"Disney",
"ques":"In Coco, what is the name of the famous song that Ernesto De La Cruz stole from Hector?",
"answ":"REMEMBER ME",
"answ2":"Remember Me.",
},
{
"cat":"Disney",
"ques":"Emperor Zurg is the arch nemesis of which Pixar character?",
"answ":"BUZZ LIGHTYEAR",
"answ2":"Buzz Lightyear.",
},
{
"cat":"Disney",
"ques":"What relation does Coco have to Miguel in Coco?",
"answ":"GREAT GRANDMOTHER",
"answ2":"Great-grandmother.",
},
{
"cat":"Disney",
"ques":"Who voices the character of The Underminer in The Incredibles and The Incredibles 2?",
"answ":"JOHN RATZENBERGER",
"answ2":"John Ratzenberger.",
},
{
"cat":"Disney",
"ques":"In what Pixar film does Sigourney Weaver provide the voice of a character called Ship's Computer?",
"answ":"WALL E",
"answ2":"WALL-E.",
},
{
"cat":"Disney",
"ques":"What storybook character has the affection of Woody in Toy Story?",
"answ":"BO PEEP",
"answ2":"Bo Peep.",
},
{
"cat":"Disney",
"ques":"Released in 2007, what was the eight Pixar film?",
"answ":"RATATOUILLE",
"answ3":"RATATOUILE",
"answ2":"Ratatouille.",
},
{
"cat":"Disney",
"ques":"In A Bug's Life, what is the actual occupation of the fake warriors that Flick hires?",
"answ":"CIRCUS PERFORMERS",
"answ3":"CIRCUS ARTISTS",
"answ2":"Circus performers.",
},
{
"cat":"Disney",
"ques":"Who voices regal blue tang Dory, in Finding Nemo and Finding Dory?",
"answ":"ELLEN DEGENERES",
"answ2":"Ellen DeGeneres.",
},
{
"cat":"Disney",
"ques":"What is the first name of the speedster son in The Incredibles?",
"answ":"DASH",
"answ3":"DASHIELL",
"answ2":"Dash.",
},
{
"cat":"Disney",
"ques":"Carl Fredricksen is a character in what Pixar film?",
"answ":"UP",
"answ2":"Up.",
},
{
"cat":"Disney",
"ques":"Who directed Ratatouille?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"Disney",
"ques":"Who provided the voice of Edna Mode in The Incredibles?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"Disney",
"ques":"Who directed Toy Story 2?",
"answ":"JOHN LASSETER",
"answ2":"John Lasseter.",
},
{
"cat":"Disney",
"ques":"Who directed Monsters, Inc?",
"answ":"PETE DOCTER",
"answ3":"PETER DOCTER",
"answ2":"Pete Docter.",
},
{
"cat":"Disney",
"ques":"Who provides the bubbly voice of Joy in Inside Out?",
"answ":"AMY POEHLER",
"answ2":"Amy Poehler.",
},
{
"cat":"Disney",
"ques":"Who voiced Jafar in 1992's Aladdin?",
"answ":"JONATHAN FREEMAN",
"answ2":"Jonathan Freeman.",
},
{
"cat":"Disney",
"ques":"Who voiced Jasmine in 1992's Aladdin?",
"answ":"LINDA LARKIN",
"answ2":"Linda Larkin.",
},
{
"cat":"Disney",
"ques":"Who voiced the title character in Chicken Little?",
"answ":"ZACH BRAFF",
"answ2":"Zach Braff.",
},
{
"cat":"Disney",
"ques":"Who voices Jim Hawkins in Treasure Planet?",
"answ":"JOSEPH GORDON LEVITT",
"answ2":"Joseph Gordon-Levitt.",
},
{
"cat":"Disney",
"ques":"Who voices linguist Milo James Thatch in Atlantis: The Lost Empire?",
"answ":"MICHAEL J FOX",
"answ2":"Michael J. Fox.",
},
{
"cat":"Disney",
"ques":"Who voiced Mulan in the 1998 film?",
"answ":"MING NA WEN",
"answ2":"Ming-Na Wen.",
},
{
"cat":"Disney",
"ques":"What actor voiced Phil in 1997's Hercules?",
"answ":"DANNY DEVITO",
"answ2":"Danny DeVito.",
},
{
"cat":"Disney",
"ques":"What kind of creature is Hercules' friend Phil?",
"answ":"SATYR",
"answ2":"Satyr.",
},
{
"cat":"Disney",
"ques":"What actor voiced Hades in 1997's Hercules?",
"answ":"JAMES WOODS",
"answ2":"James Woods.",
},
{
"cat":"Disney",
"ques":"Jodi Benson voiced what Disney Princess?",
"answ":"ARIEL",
"answ3":"THE LITTLE MERMAID",
"answ2":"Ariel/The Little Mermaid.",
},
{
"cat":"Disney",
"ques":"What famous singer voiced Dodger in Oliver and Company?",
"answ":"BILLY JOEL",
"answ2":"Billy Joel.",
},
{
"cat":"Disney",
"ques":"Taran is the main character of what Disney movie?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"Who directed the 2016 remake of The Jungle Book?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
},
{
"cat":"Disney",
"ques":"Who voiced Baloo in 2016's The Jungle Book?",
"answ":"BILL MURRAY",
"answ2":"Bill Murray.",
},
{
"cat":"Disney",
"ques":"Who voiced Bagheera in 2016's The Jungle Book?",
"answ":"BEN KINGSLEY",
"answ2":"Ben Kingsley.",
},
{
"cat":"Disney",
"ques":"Who voiced adult Simba in 2019's The Lion King?",
"answ":"DONALD GLOVER",
"answ2":"Donald Glover.",
},
{
"cat":"Disney",
"ques":"Who voiced Scar in 2019's The Lion King?",
"answ":"CHIWETEL EJIOFOR",
"answ2":"Chiwetel Ejiofor.",
},
{
"cat":"Disney",
"ques":"Who played adult Beast in 2017's Beauty and the Beast?",
"answ":"DAN STEVENS",
"answ2":"Dan Stevens.",
},
{
"cat":"Disney",
"ques":"Who played adult Belle in 2017's Beauty and the Beast?",
"answ":"EMMA WATSON",
"answ2":"Emma Watson.",
},
{
"cat":"Disney",
"ques":"Who directed Toy Story 4?",
"answ":"JOSH COOLEY",
"answ2":"Josh Cooley.",
},
{
"cat":"Disney",
"ques":"Who voiced daredevil toy Duke Caboom in Toy Story 4?",
"answ":"KEANU REEVES",
"answ2":"Keanu Reeves.",
},
{
"cat":"Disney",
"ques":"Who voices Mr. Potato Head in the Toy Story films?",
"answ":"DON RICKLES",
"answ2":"Don Rickles.",
},
{
"cat":"Disney",
"ques":"Who directed 2019's Aladdin?",
"answ":"GUY RITCHIE",
"answ2":"Guy Ritchie.",
},
{
"cat":"Disney",
"ques":"Who portrayed Mary Poppins in Mary Poppins Returns?",
"answ":"EMILY BLUNT",
"answ2":"Emily Blunt.",
},
{
"cat":"Disney",
"ques":"Who played the cockney lamplighter Jack in Mary Poppins Returns?",
"answ":"LIN MANUEL MIRANDA",
"answ2":"Lin-Manuel Miranda.",
},
{
"cat":"Disney",
"ques":"Who directed Finding Dory?",
"answ":"ANDREW STANTON",
"answ2":"Andrew Stanton.",
},
{
"cat":"Disney",
"ques":"Who voiced Winnie the Pooh in the 2011 film?",
"answ":"JIM CUMMINGS",
"answ2":"Jim Cummings.",
},
{
"cat":"Disney",
"ques":"What Oscar-winning actor voiced the bear Kenai in Brother Bear?",
"answ":"JOAQUIN PHOENIX",
"answ2":"Joaquin Phoenix.",
},
{
"cat":"Disney",
"ques":"Who directed the following Disney films: The Jungle Book, Robin Hood, The Aristocats and The Sword in the Stone?",
"answ":"WOLFGANG REITHERMAN",
"answ3":"WOLFGANG REITERMAN",
"answ2":"Wolfgang Reitherman.",
},
{
"cat":"Disney",
"ques":"You'll find James Henry Trotter, a young orphan whose parents were devoured by a rhinoceros in what Disney fim?",
"answ":"JAMES AND THE GIANT PEACH",
"answ2":"James and the Giant Peach.",
},
{
"cat":"Disney",
"ques":"Hayden Panettiere voices a lemur in what 2000s Disney film?",
"answ":"DINOSAUR",
"answ2":"Dinosaur.",
},
{
"cat":"Disney",
"ques":"What Oscar-winning actress voiced a cow named Mrs. Calloway in Home on the Range?",
"answ":"JUDI DENCH",
"answ2":"Judi Dench.",
},
{
"cat":"Disney",
"ques":"You'll find characters named Baymax, Hiro, Wasabi and Go Go in what Disney film?",
"answ":"BIG HERO 6",
"answ3":"BIG HERO SIX",
"answ2":"Big Hero 6.",
},
{
"cat":"Disney",
"ques":"Who directed 2019's Dumbo?",
"answ":"TIM BURTON",
"answ2":"Tim Burton.",
},
{
"cat":"Disney",
"ques":"In 2019's Dumbo, who plays ruthless amusement park owner V.A. Vandevere?",
"answ":"MICHAEL KEATON",
"answ2":"Michael Keaton.",
},
{
"cat":"Disney",
"ques":"Who directed 2018's Christopher Robin?",
"answ":"MARC FORSTER",
"answ2":"Marc Forster.",
},
{
"cat":"Disney",
"ques":"Who played Christopher Robin in the 2018 film?",
"answ":"EWAN MCGREGOR",
"answ2":"Ewan McGregor.",
},
{
"cat":"Disney",
"ques":"Who directed Coco?",
"answ":"LEE UNKRICH",
"answ2":"Lee Unkrich.",
},
{
"cat":"Disney",
"ques":"Who directed 2015's Cinderella?",
"answ":"KENNETH BRANAGH",
"answ2":"Kenneth Branagh.",
},
{
"cat":"Disney",
"ques":"Who played Cinderella in the 2015 film?",
"answ":"LILY JAMES",
"answ2":"Lily James.",
},
{
"cat":"Disney",
"ques":"Who played the Fairy Godmmother in the 2015 film Cinderella?",
"answ":"HELENA BONHAM CARTER",
"answ2":"Helena Bonham Carter.",
},
{
"cat":"Disney",
"ques":"Who played Alice in the 2010 remake of Alice in Wonderland?",
"answ":"MIA WASIKOWSKA",
"answ2":"Mia Wasikowska.",
},
{
"cat":"Disney",
"ques":"In the original Alice in Wonderland, what two words are on the bottle of the shrinking mixture?",
"answ":"DRINK ME",
"answ2":"Drink Me.",
},
{
"cat":"Disney",
"ques":"Who laughs at Bambi's first attempt to walk?",
"answ":"THUMPER",
"answ2":"Thumper.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, what object does Ariel mistakenly use to comb her hair?",
"answ":"A FORK",
"answ3":"FORK",
"answ2":"A fork.",
},
{
"cat":"Disney",
"ques":"In Pinocchio, what famous painting can be seen in the billiard room in Pleasure Island?",
"answ":"THE MONA LISA",
"answ3":"MONA LISA",
"answ2":"The Mona Lisa.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, how many days does Ariel have to find true love?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Disney",
"ques":"In the original Lion King, who is the first lion to discover Simba isn't dead?",
"answ":"NALA",
"answ2":"Nala.",
},
{
"cat":"Disney",
"ques":"How many Oscar nominations did Beauty and the Beast receive?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
},
{
"cat":"Disney",
"ques":"Who was not invited to the party to celebrate the birth of Princess Aurora?",
"answ":"MALEFICENT",
"answ2":"Maleficent.",
},
{
"cat":"Disney",
"ques":"Who is the only one of the Seven Dwarfs with blue eyes?",
"answ":"DOPEY",
"answ2":"Dopey.",
},
{
"cat":"Disney",
"ques":"What are the first four spoken words in the original Cinderella?",
"answ":"ONCE UPON A TIME",
"answ2":"Once Upon a Time.",
},
{
"cat":"Disney",
"ques":"What is the name of Geppetto's pet cat?",
"answ":"FIGARO",
"answ2":"Figaro.",
},
{
"cat":"Disney",
"ques":"In which country is the original The Jungle Book set?",
"answ":"INDIA",
"answ2":"India.",
},
{
"cat":"Disney",
"ques":"Which U.S. state provides the setting for Pocahontas?",
"answ":"VIRGINIA",
"answ2":"Virginia.",
},
{
"cat":"Disney",
"ques":"In Toy Story, who does Mr. Potato Head get stuck with as a moving buddy?",
"answ":"REX",
"answ2":"Rex.",
},
{
"cat":"Disney",
"ques":"In what year was the original The Little Mermaid released?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Disney",
"ques":"In Fantasia, who provided Mickey Mouse's voice at the end of The Sorcerer's Apprentice sequence?",
"answ":"WALT DISNEY",
"answ2":"Walt Disney.",
},
{
"cat":"Disney",
"ques":"What is the name of the green dinosaurs in Toy Story?",
"answ":"REX",
"answ2":"Rex.",
},
{
"cat":"Disney",
"ques":"Who locks Pinocchio into a bird cage?",
"answ":"STROMBOLI",
"answ2":"Stromboli.",
},
{
"cat":"Disney",
"ques":"In the original Hercules film, what gift does Hercules' father give him at his birth?",
"answ":"PEGASUS",
"answ3":"FLYING HORSE",
"answ2":"Pegasus.",
},
{
"cat":"Disney",
"ques":"In the original Mulan, what fruit is Mulan given for serenity before her visit to the Matchmaker?",
"answ":"APPLE",
"answ3":"AN APPLE",
"answ2":"An apple.",
},
{
"cat":"Disney",
"ques":"According to the spell how many years will Princess Aurora fall into a deep sleep?",
"answ":"100",
"answ3":"HUNDRED",
"answ2":"100.",
},
{
"cat":"Disney",
"ques":"What does Aladdin convince Jafar is even more powerful than a sorcerer?",
"answ":"GENIE",
"answ3":"A GENIE",
"answ2":"A genie.",
},
{
"cat":"Disney",
"ques":"In Beauty and the Beast, how many dozen eggs does Gaston claim to eat before breakfast?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
},
{
"cat":"Disney",
"ques":"In Beauty and the Beast, what is Belle's father's profession?",
"answ":"INVENTOR",
"answ2":"Inventor.",
},
{
"cat":"Disney",
"ques":"In Jafar, what does Jafar turn Rajah into?",
"answ":"TIGER CUB",
"answ3":"CUB",
"answ2":"Tiger Cub.",
},
{
"cat":"Disney",
"ques":"In which year was Fantasia released?",
"answ":"1940",
"answ2":"1940.",
},
{
"cat":"Disney",
"ques":"In Alice in Wonderland, what does the White Rabbit carry along with his famous watch?",
"answ":"UMBRELLA",
"answ3":"AN UMBRELLA",
"answ2":"An umbrella.",
},
{
"cat":"Disney",
"ques":"In the original Tarzan, what European city does Jane come from?",
"answ":"LONDON",
"answ2":"London.",
},
{
"cat":"Disney",
"ques":"What is the name of the enormous whale that appears in Pinocchio?",
"answ":"MONSTRO",
"answ2":"Monstro.",
},
{
"cat":"Disney",
"ques":"What does Timothy Q. Mouse have under his hat when he first meets Dumbo?",
"answ":"PEANUT",
"answ3":"A PEANUT",
"answ2":"Peanut.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, what name does Ursula go by when she disguises herself as a human to steal Eric from Ariel?",
"answ":"VANESSA",
"answ2":"Vanessa.",
},
{
"cat":"Disney",
"ques":"What is the name of Maleficent's pet raven in Sleeping Beaut??",
"answ":"DIABLO",
"answ2":"Diablo.",
},
{
"cat":"Disney",
"ques":"In The Lion King, what is Simba's mother's name?",
"answ":"SARABI",
"answ2":"Sarabi.",
},
{
"cat":"Disney",
"ques":"What is the name of Prince Phillip's horse in Sleeping Beauty?",
"answ":"SAMSON",
"answ2":"Samson.",
},
{
"cat":"Disney",
"ques":"What baby animal does Moana rescue as a toddler?",
"answ":"SEA TURTLE",
"answ3":"TURTLE",
"answ2":"Turtle.",
},
{
"cat":"Disney",
"ques":"In the original Mulan, what type of animal perches on the shoulder of the villain Shan Yu?",
"answ":"FALCON",
"answ3":"BIRD",
"answ2":"Falcon.",
},
{
"cat":"Disney",
"ques":"In Peter Pan, which of the Darling children wears a tophat?",
"answ":"JOHN",
"answ2":"John.",
},
{
"cat":"Disney",
"ques":"In Alice in Wonderland, what is the name of Alice's pet kitten?",
"answ":"DINAH",
"answ3":"DINA",
"answ2":"Dinah.",
},
{
"cat":"Disney",
"ques":"Which Disney princess has a racoon for a sidekick?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Disney",
"ques":"In The Little Mermaid, Ursula is accompanied by two moray eels. Name one of them.",
"answ":"JETSAM",
"answ3":"FLOTSAM",
"answ2":"Jetsam/Flotsam.",
},
{
"cat":"Disney",
"ques":"How many sisters does Ariel have?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
},
{
"cat":"Disney",
"ques":"In the original Mulan, what is the name of Mulan’s horse?",
"answ":"KHAN",
"answ2":"Khan.",
},
{
"cat":"Disney",
"ques":"What is the name of Andy’s evil neighbor in Toy Story?",
"answ":"SID",
"answ2":"Sid.",
},
{
"cat":"Disney",
"ques":"Emperor Kuzco turns into what animal in The Emperor’s New Groove?",
"answ":"LLAMA",
"answ3":"LAMA",
"answ2":"Llama.",
},
{
"cat":"Disney",
"ques":"Rapunzel’s chameleon in Tangled is called what?",
"answ":"PASCAL",
"answ2":"Pascal.",
},
{
"cat":"Disney",
"ques":"In Toy Story 2, which character tells Buzz that he’s his father? ",
"answ":"EMPEROR ZURG",
"answ3":"ZURG",
"answ2":"Emperor Zurg.",
},
{
"cat":"Disney",
"ques":"Stitch is also known as Experiment _____.",
"answ":"626",
"answ2":"626.",
},
{
"cat":"Disney",
"ques":"What is the name of Goofy’s son in the movie A Goofy Movie?",
"answ":"MAXIMILIAN",
"answ3":"MAX",
"answ2":"Max.",
},
{
"cat":"Disney",
"ques":"In what city does Aladdin live?",
"answ":"AGRABAH",
"answ3":"AGRABA",
"answ2":"Agrabah.",
},
{
"cat":"Disney",
"ques":"What is the first name of Belle’s father in the movie Beauty and the Beast?",
"answ":"MAURICE",
"answ2":"Maurice.",
},
{
"cat":"Disney",
"ques":"What was the name of Miguel’s dog companion in the movie Coco?",
"answ":"DANTE",
"answ2":"Dante.",
},
{
"cat":"Disney",
"ques":"A pub called The Snuggly Duckling appears in what 2010s Disney film?",
"answ":"TANGLED",
"answ2":"Tangled",
},
{
"cat":"Disney",
"ques":"The Black Cauldron was released in what year?",
"answ":"1985",
"answ2":"1985.",
},
{
"cat":"Disney",
"ques":"Who voiced Heihei in Moana?",
"answ":"ALAN TUDYK",
"answ2":"Alan Tudyk.",
},
{
"cat":"Disney",
"ques":"What 'magic' item does Timothy give to Dumbo to make him fly again in Dumbo?",
"answ":"FEATHER",
"answ2":"Feather.",
},
{
"cat":"Disney",
"ques":"In the Lake Titicaca segment of Saludos Amigos, what Disney character goes on a tourist trip?",
"answ":"DONALD DUCK",
"answ2":"Donald Duck.",
},
{
"cat":"Disney",
"ques":"What Disney character said: 'I wasn't going to eat it. I was just going to taste it.'",
"answ":"WINNIE THE POOH",
"answ2":"Winnie The Pooh.",
},
{
"cat":"Disney",
"ques":"Who voiced Georgette in Oliver & Company?",
"answ":"BETTE MIDLER",
"answ2":"Bette Midler.",
},
{
"cat":"Disney",
"ques":"You'll find characters named Archimedes, Lord Ector and Sir Kay in what Disney film?",
"answ":"SWORD IN THE STONE",
"answ3":"THE SWORD IN THE STONE",
"answ2":"The Sword in the Stone.",
},
{
"cat":"Disney",
"ques":"There were two animated Disney movies released in 1977, name one.",
"answ":"THE MANY ADVENTURES OF WINNIE THE POOH",
"answ3":"THE RESCUERS",
"answ2":"The Many Adventures of Winnie the Pooh/The Rescuers.",
},
{
"cat":"Disney",
"ques":"What is the name of the diamond they are looking for in The Rescuers?",
"answ":"DEVIL'S EYE",
"answ3":"THE DEVIL'S EYE",
"answ2":"Devil's Eye.",
},
{
"cat":"Disney",
"ques":"Aladar was what type of dinosaur in the film Dinosaur?",
"answ":"IGUANODON",
"answ3":"IGUANADON",
"answ2":"Iguanodon .",
},
{
"cat":"Disney",
"ques":"What Disney animated character said: 'For the first time in my life things are starting to go right.'",
"answ":"ALADDIN",
"answ2":"Aladdin.",
},
{
"cat":"Disney",
"ques":"What is the name of the naughty boy that befriended Pinocchio on the way to Pleasure Island?",
"answ":"LAMPWICK",
"answ2":"Lampwick.",
},
{
"cat":"Disney",
"ques":"What is the name of the stag that Bambi has to fight to earn the right to Faline's affection?",
"answ":"RONNO",
"answ2":"Ronno.",
},
{
"cat":"Disney",
"ques":"Which famous singer narrated The Legend of Sleepy Hollow segment in The Adventures of Ichabod and Mr. Toad?",
"answ":"BING CROSBY",
"answ2":"Bing Crosby.",
},
{
"cat":"Disney",
"ques":"What is the name of Cinderella's dog that gets turned into a footman?",
"answ":"BRUNO",
"answ2":"Bruno.",
},
{
"cat":"Disney",
"ques":"What Disney animated movie features the songs 'Belle Note' and The Siamese Cats Song'?",
"answ":"LADY AND THE TRAMP",
"answ2":"Lady and the Tramp.",
},
{
"cat":"Disney",
"ques":"What actor who also starred in Hitchcock's The Birds, voiced Pongo in One Hundred and One Dalmatians?",
"answ":"ROD TAYLOR",
"answ2":"Rod Taylor.",
},
{
"cat":"Disney",
"ques":"What 40s animated film includes the segments 'Casey at the Bat', 'Blue Bayou' and 'Peter and the Wolf'?",
"answ":"MAKE MINE MUSIC",
"answ2":"Make Mine Music.",
},
{
"cat":"Disney",
"ques":"In Alice in Wonderland, what is the name of the poem Tweedle Dum and Tweedle Dee tell to Alice?",
"answ":"THE WALRUS AND THE CARPENTER",
"answ3":"WALRUS AND THE CARPENTER",
"answ2":"The Walrus and the Carpenter.",
},
{
"cat":"Disney",
"ques":"According to a Disney film, if you 'follow the second star to the right and go straight on til' morning' you'll arrive where?",
"answ":"NEVERLAND",
"answ2":"Neverland.",
},
{
"cat":"Disney",
"ques":"Fflewddur Fflam is a character from what 80s Disney movie?",
"answ":"THE BLACK CAULDRON",
"answ3":"BLACK CAULDRON",
"answ2":"The Black Cauldron.",
},
{
"cat":"Disney",
"ques":"What famous singer voices Penny in Bolt?",
"answ":"MILEY CYRUS",
"answ2":"Miley Cyrus.",
},
{
"cat":"Disney",
"ques":"In The Princess and the Frog, what character marries Tiana and Naveen?",
"answ":"MAMA ODIE",
"answ2":"Mama Odie.",
},
{
"cat":"Disney",
"ques":"The Three Caballeros are Panchito Pistoles, José Carioca and ____",
"answ":"DONALD DUCK",
"answ2":"Donald Duck.",
},
{
"cat":"Disney",
"ques":"What animal does Robin Hood disguise himself as when he participates in the archery tournament?",
"answ":"STORK",
"answ2":"Stork.",
},
{
"cat":"Disney",
"ques":"In The Rescuers, what organization do Bernard and Bianca belong to?",
"answ":"RESCUE AID SOCIETY",
"answ2":"Rescue Aid Society.",
},
{
"cat":"Disney",
"ques":"What movie features a hamster named Rhino and a cat named Mittens?",
"answ":"BOLT",
"answ2":"Bolt.",
},
{
"cat":"Disney",
"ques":"In the original Mulan, when Mulan is pretending to be a man, what name does she go by?",
"answ":"PING",
"answ2":"Ping.",
},
{
"cat":"Disney",
"ques":"'The Whale Who Wanted to Sing at the Met' is featured in what animated anthology film?",
"answ":"MAKE MINE MUSIC",
"answ2":"Make Mine Music.",
},
{
"cat":"Disney",
"ques":"What is the name of the flowers that turn predators back into their primitive state in Zootopia?",
"answ":"NIGHT HOWLERS",
"answ2":"Night howlers.",
},
{
"cat":"Disney",
"ques":"Name one of the two directors from Frozen.",
"answ":"JENNIFER LEE",
"answ3":"CHRIS BUCK",
"answ2":"Jennifer Lee/Chris Buck.",
},
{
"cat":"Disney",
"ques":"Who runs the puppet show that Honest John and Gideon convince Pinocchio to join?",
"answ":"STROMBOLI",
"answ2":"Stromboli.",
},
{
"cat":"Disney",
"ques":"What is the name of Pocahontas' raccoon friend?",
"answ":"MEEKO",
"answ2":"Meeko.",
},
{
"cat":"Disney",
"ques":"What is the name of the sentient circus train that takes the circus from place to place in Dumbo?",
"answ":"CASEY JUNIOR",
"answ2":"Casey Junior.",
},
{
"cat":"Disney",
"ques":"In 2011's Winnie the Pooh, what is the name of the monster they think has kidnapped Christopher Robin?",
"answ":"BACKSON",
"answ3":"THE BACKSON",
"answ2":"Backson.",
},
{
"cat":"Disney",
"ques":"In Ralph Breaks the Internet, what is the name of the lead character in the game Slaughter Race?",
"answ":"SHANK",
"answ2":"Shank.",
},
{
"cat":"Disney",
"ques":"In Atlantis: The Lost Empire, Milo is cartographer from what institute? ",
"answ":"SMITHSONIAN",
"answ3":"THE SMITHSONIAN",
"answ2":"The Smithsonian.",
},
{
"cat":"Disney",
"ques":"What kind of sport does Chicken Little play in order to recover his reputation and make his father proud?",
"answ":"BASEBALL",
"answ2":"Baseball.",
},
{
"cat":"Disney",
"ques":"'For the First Time in Forever' and 'In Summer' are songs from which Disney film?",
"answ":"FROZEN",
"answ2":"Frozen.",
},
{
"cat":"Disney",
"ques":"Who voiced Zeus in 1997's Hercules?",
"answ":"RIP TORN",
"answ2":"Rip Torn.",
},
{
"cat":"Disney",
"ques":"In The Princess and the Frog, Ray believes that the Evening Star is another firefly named what?",
"answ":"EVANGELINE",
"answ2":"Evangeline.",
},
{
"cat":"Disney",
"ques":"In Meet the Robinsons, who voices Cornelius, the grown up version of Lewis?",
"answ":"TOM SELLECK",
"answ2":"Tom Selleck.",
},
{
"cat":"Disney",
"ques":"In Lilo & Stitch what is Nani's profession?",
"answ":"WAITRESS",
"answ2":"Waitress.",
},
{
"cat":"Disney",
"ques":"In 1999's Tarzan, what kind of animal is Tantor?",
"answ":"ELEPHANT",
"answ2":"Elephant.",
},
{
"cat":"Disney",
"ques":"Who voices Bernard in The Rescuers?",
"answ":"BOB NEWHART",
"answ2":"Bob Newhart.",
},
{
"cat":"Disney",
"ques":"In the original Mulan, what item that belonged to Shan Yu is offered to Mulan as a gift at the end of the film?",
"answ":"SWORD",
"answ3":"HIS SWORD",
"answ2":"His sword.",
},
{
"cat":"Disney",
"ques":"What Disney villain lives in Bald Mountain?",
"answ":"CHERNABOG",
"answ2":"Chernabog.",
},
{
"cat":"Disney",
"ques":"What is the name of the girl that adopts Oliver in Oliver & Company?",
"answ":"JENNY",
"answ3":"JENNIFER",
"answ2":"Jenny.",
},
{
"cat":"Disney",
"ques":"What is the name of the land that The Black Cauldron is set in?",
"answ":"PRYDAIN",
"answ3":"PRIDAIN",
"answ2":"Prydain.",
},
{
"cat":"Disney",
"ques":"What singer wrote the Oscar-nominated song 'My Funny Friend And Me' from The Emperor's New Groove?",
"answ":"STING",
"answ2":"Sting.",
},
{
"cat":"Disney",
"ques":"What is the name of the female gorilla who raised Tarzan?",
"answ":"KALA",
"answ2":"Kala.",
},
{
"cat":"Disney",
"ques":"What is the name of the leopard who killed Tarzan's parents?",
"answ":"SABOR",
"answ2":"Sabor.",
},
{
"cat":"Disney",
"ques":"What is the name of the annual event that happens in The Hunchback of Notre Dame?",
"answ":"FESTIVAL OF FOOLS",
"answ2":"Festival of Fools.",
},
{
"cat":"Disney",
"ques":"What kind of dinosaur is Baylene in the movie Dinosaur?",
"answ":"BRACHIOSAURUS",
"answ2":"Brachiosaurus.",
},
{
"cat":"Disney",
"ques":"What does Kuzco want to call his new summer home in The Emperor's New Groove?",
"answ":"KUZCOTOPIA",
"answ2":"Kuzcotopia.",
},
{
"cat":"Disney",
"ques":"What is the name of the villainous giant crab in Moana?",
"answ":"TAMATOA",
"answ2":"Tamatoa.",
},
{
"cat":"Disney",
"ques":"What is the name of the talking tree in Pocahontas?",
"answ":"GRANDMOTHER WILLOW",
"answ2":"Grandmother Willow.",
},
{
"cat":"Disney",
"ques":"Flounder puts a statue of who in Ariel's Secret Grotto?",
"answ":"PRINCE ERIC",
"answ3":"PRINCE ERIK",
"answ2":"Prince Eric.",
},
{
"cat":"Disney",
"ques":"The refrain from which classic Disney song can be heard during the logo that opens all Walt Disney Pictures movies?",
"answ":"WHEN YOU WISH UPON A STAR",
"answ2":"When You Wish Upon a Star.",
},
{
"cat":"Disney",
"ques":"What is the name of Dwayne Johnson's character in Moana?",
"answ":"MAUI",
"answ2":"Maui.",
},
{
"cat":"Disney",
"ques":"What is the name of Wreck-It Ralph's video game partner voiced by 30 Rock alum Jack McBrayer?",
"answ":"FIX IT FELIX JR",
"answ3":"FIX IT FELIX",
"answ2":"Fix-It Felix Jr.",
},
{
"cat":"Disney",
"ques":"In the original Alice in Wonderland, the Queen of Hearts challenges Alice to a round of what game?",
"answ":"CROQUET",
"answ2":"Croquet.",
},
{
"cat":"Disney",
"ques":"The Princess and the Frog takes place in what U.S. state?",
"answ":"LOUISIANA",
"answ2":"Louisiana.",
},
{
"cat":"Disney",
"ques":"What is the name of the inflatable robot originally built to be a medical assistant in Big Hero 6?",
"answ":"BAYMAX",
"answ2":"Baymax.",
},
{
"cat":"Disney",
"ques":"What is the name of the forest that provides the setting for Disney's Winnie the Pooh films?",
"answ":"HUNDRED ACRE WOOD",
"answ3":"THE HUNDRED ACRE WOOD",
"answ2":"The Hundred Acre Wood.",
},
{
"cat":"Disney",
"ques":"In Tangled, what item does Rapunzel use to attack Flynn after he first enters her tower?",
"answ":"FRYING PAN",
"answ3":"A FRYING PAN",
"answ2":"Frying pan.",
},
{
"cat":"Disney",
"ques":"In Aladdin, Jafar holds this title in the Sultan's court.",
"answ":"GRAND VIZIER",
"answ2":"Grand Vizier.",
},
{
"cat":"Disney",
"ques":"What Disney animated film features the songs: 'Zero to Hero' and 'Go the Distance'?",
"answ":"HERCULES",
"answ2":"Hercules.",
},
{
"cat":"Disney",
"ques":"Minnie Driver, Glenn Close, Rosie O'Donnell and Wayne Knight all lent their voices to what 1998 Disney animated film?",
"answ":"TARZAN",
"answ2":"Tarzan.",
},
];