var speedquestion001 = [
{
"cat":"Mixed Bag",
"ques":"Which of the following 2007 films was NOT nominated for Best Picture: Juno, There Will Be Blood, Gone Baby Gone.",
"answ":"GONE BABY GONE",
"answ2":"Gone Baby Gone.",
},
{
"cat":"Mixed Bag",
"ques":"Who stars as Nick, a man who acquires the gift to hear what women are thinking in the film What Women Want?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor plays the character Richard B. Riddick in the Riddick franchise?",
"answ":"VIN DIESEL",
"answ2":"Vin Diesel.",
},
{
"cat":"Mixed Bag",
"ques":"Which comedic actor played the titular character in Little Nicky?",
"answ":"ADAM SANDLER",
"answ2":"Adam Sandler.",
},
{
"cat":"Mixed Bag",
"ques":"Who played male nurse Greg Focker in Meet the Parents?",
"answ":"BEN STILLER",
"answ2":"Ben Stiller.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the role of Charlie Baileygates in Me Myself & Irene?",
"answ":"JIM CARREY",
"answ2":"Jim Carrey.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays alcoholic Gwen Cummings in 28 Days?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
},
{
"cat":"Mixed Bag",
"ques":"Which legendary actor plays the role of William Forrester in Finding Forrester?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
},
{
"cat":"Mixed Bag",
"ques":"Who starred as mob enforcer Jack Carter in the 2000 remake of Get Carter?",
"answ":"SYLVESTER STALLONE",
"answ2":"Sylvester Stallone.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2010's Inception?",
"answ":"CHRISTOPHER NOLAN",
"answ2":"Christopher Nolan.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Dre Parker in 2010's The Karate Kid?",
"answ":"JADEN SMITH",
"answ2":"Jaden Smith.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the title hero in 2010's Robin Hood?",
"answ":"RUSSELL CROWE",
"answ2":"Russell Crowe.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress plays the titular character in 2010's Alice in Wonderland?",
"answ":"MIA WASIKOWSKA",
"answ2":"Mia Wasikowska.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Hollywood talent agent Lenny Feder in 2010's Grown Ups?",
"answ":"ADAM SANDLER",
"answ2":"Adam Sandler.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2010's The Social Network?",
"answ":"DAVID FINCHER",
"answ2":"David Fincher.",
},
{
"cat":"Mixed Bag",
"ques":"Who starred as professional boxer Micky Ward in 2010's The Fighter?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
},
{
"cat":"Mixed Bag",
"ques":"Which famous actor directed 2010's The Town?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
},
{
"cat":"Mixed Bag",
"ques":"Who starred as bounty hunter Milo Boyd in The Bounty Hunter?",
"answ":"GERARD BUTLER",
"answ2":"Gerard Butler",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the first Insidious film?",
"answ":"JAMES WAN",
"answ2":"James Wan.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2010's Cop Out?",
"answ":"KEVIN SMITH",
"answ2":"Kevin Smith.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor played the lead role of Spencer in the 2010 action comedy Killers?",
"answ":"ASHTON KUTCHER",
"answ2":"Ashton Kutcher.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the titular character in 2010's Machete?",
"answ":"DANNY TREJO",
"answ2":"Danny Trejo.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the titular character in 2020's Dolittle?",
"answ":"ROBERT DOWNEY JR",
"answ2":"Robert Downey Jr.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2020's Tenet?",
"answ":"CHRISTOPHER NOLAN",
"answ2":"Christopher Nolan.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Gladiator?",
"answ":"RIDLEY SCOTT",
"answ2":"Ridley Scott.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Almost Famous?",
"answ":"CAMERON CROWE",
"answ2":"Cameron Crowe.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Memento?",
"answ":"CHRISTOPHER NOLAN",
"answ2":"Christopher Nolan.",
},
{
"cat":"Mixed Bag",
"ques":"Which franchise features characters suchs as Oz, Finch, Nadia and Sherman?",
"answ":"AMERICAN PIE",
"answ2":"American Pie.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the film Multiplicity?",
"answ":"HAROLD RAMIS",
"answ2":"Harold Ramis.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor appeared in the films Dazed & Confused, Sahara and Tropic Thunder?",
"answ":"MATTHEW MCCONAUGHEY",
"answ2":"Matthew McConaughey.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of Jaws: the Revenge, Teen Wolf Too and Beverly Hills Cop II?",
"answ":"1987",
"answ2":"1987.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress voiced characters in ParaNorman and Trolls?",
"answ":"ANNA KENDRICK",
"answ2":"Anna Kendrick.",
},
{
"cat":"Mixed Bag",
"ques":"Which animated franchise features the characters Princess Fiona, King Harold and Queen Lillian?",
"answ":"SHREK",
"answ2":"Shrek.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Katniss Everdeen in The Hunger Games franchise?",
"answ":"JENNIFER LAWRENCE",
"answ2":"Jennifer Lawrence.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor plays Vincent Mancini, nephew of Michael Corleone in The Godfather Part 3?",
"answ":"ANDY GARCIA",
"answ2":"Andy Garcia.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Wolf of Wall Street?",
"answ":"MARTIN SCORSESE",
"answ2":"Martin Scorsese.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Sherlock Holmes in the film Enola Holmes?",
"answ":"HENRY CAVILL",
"answ2":"Henry Cavill.",
},
{
"cat":"Mixed Bag",
"ques":"Who played FBI agent Carl Hanratty in Catch Me If You Can?",
"answ":"TOM HANKS",
"answ2":"Tom Hanks.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the lead role of Benjamin Gates in National Treasure?",
"answ":"NICOLAS CAGE",
"answ3":"NIC CAGE",
"answ2":"Nicolas Cage.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress played the lead role in Runaway Bride?",
"answ":"JULIA ROBERTS",
"answ2":"Julia Roberts.",
},
{
"cat":"Mixed Bag",
"ques":"What animated Disney film features the song 'Son of Man'?",
"answ":"TARZAN",
"answ2":"Tarzan.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Blade Runner?",
"answ":"RIDLEY SCOTT",
"answ2":"Ridley Scott.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of the following films: The Last Starfighter, Gremlins and Dune?",
"answ":"1984",
"answ2":"1984.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Fred Rogers in A Beautiful Day in the Neighborhood?",
"answ":"TOM HANKS",
"answ2":"Tom Hanks.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress plays the lead role in Salt?",
"answ":"ANGELINA JOLIE",
"answ2":"Angelina Jolie.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2002's Spider-Man?",
"answ":"SAM RAIMI",
"answ2":"Sam Raimi.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Captain James Hook in the film Hook?",
"answ":"DUSTIN HOFFMAN",
"answ2":"Dustin Hoffman.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Mutt Williams in Indiana Jones and The Kingdom of the Crystal Skull?",
"answ":"SHIA LABEOUF",
"answ3":"SHIA LABOEUF",
"answ2":"Shia LaBeouf.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Roger Murtaugh in the Lethal Weapon franchise?",
"answ":"DANNY GLOVER",
"answ2":"Danny Glover.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays J. Edgar Hoover in 2011's J. Edgar?",
"answ":"LEONARDO DICAPRIO",
"answ2":"Leonardo DiCaprio.",
},
{
"cat":"Mixed Bag",
"ques":"Who won their only Academy Award for Best Supporting Actor in Million Dollar Baby?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress was nominated for her role as Charlene Fleming in The Fighter?",
"answ":"AMY ADAMS",
"answ2":"Amy Adams.",
},
{
"cat":"Mixed Bag",
"ques":"Who provided the score for 1979's Alien?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Ash Williams in Army of Darkness?",
"answ":"BRUCE CAMPBELL",
"answ2":"Bruce Campbell.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays law student Ellen Roark in A Time to Kill?",
"answ":"SANDRA BULLOCK",
"answ2":"Sandra Bullock.",
},
{
"cat":"Mixed Bag",
"ques":"In what year were the films The Shawshank Redemption and The Mask released?",
"answ":"1994",
"answ2":"1994.",
},
{
"cat":"Mixed Bag",
"ques":"In what 80s film will you find the characters Goose, Iceman and Merlin?",
"answ":"TOP GUN",
"answ2":"Top Gun.",
},
{
"cat":"Mixed Bag",
"ques":"Aslan is what type of animal in The Chronicles of Narnia films?",
"answ":"LION",
"answ2":"Lion.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Following and Insomnia?",
"answ":"CHRISTOPHER NOLAN",
"answ2":"Christopher Nolan.",
},
{
"cat":"Mixed Bag",
"ques":"Tobin Bell plays what iconic horror movie icon?",
"answ":"JIGSAW",
"answ2":"Jigsaw.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Freddy Krueger in 1984's A Nightmare on Elm Street?",
"answ":"ROBERT ENGLUND",
"answ2":"Robert Englund.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress plays Letty Ortiz in the Fast and Furious franchise?",
"answ":"MICHELLE RODRIGUEZ",
"answ2":"Michelle Rodriguez.",
},
{
"cat":"Mixed Bag",
"ques":"Joe Johnston directed Robin Williams and Bonnie Hunt in what 1995 adventure film?",
"answ":"JUMANJI",
"answ2":"Jumanji.",
},
{
"cat":"Mixed Bag",
"ques":"What horror franchise features such actors as David Arquette, Matthew Lillard and Emma Roberts?",
"answ":"SCREAM",
"answ2":"Scream.",
},
{
"cat":"Mixed Bag",
"ques":"Who won an Academy Award for playing Sophie Zawitowkski in 1982's Sophie's Choice?",
"answ":"MERYL STREEP",
"answ2":"Meryl Streep.",
},
{
"cat":"Mixed Bag",
"ques":"Who voices Megatron in 2007's Transformers?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
},
{
"cat":"Mixed Bag",
"ques":"Who voiced Woody in the Toy Story series?",
"answ":"TOM HANKS",
"answ2":"Tom Hanks.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2007's Transformers?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 1984's The Terminator?",
"answ":"JAMES CAMERON",
"answ2":"James Cameron.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Detective Jimmy Monroe in Cop Out?",
"answ":"BRUCE WILLIS",
"answ2":"Bruce Willis.",
},
{
"cat":"Mixed Bag",
"ques":"Joaquin Phoenix plays Johnny Cash in what film?",
"answ":"WALK THE LINE",
"answ2":"Walk the Line.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Tinker Bell in Hook?",
"answ":"JULIA ROBERTS",
"answ2":"Julia Roberts.",
},
{
"cat":"Mixed Bag",
"ques":"The film Super 8 came out in what year?",
"answ":"2011",
"answ2":"2011.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Old School?",
"answ":"TODD PHILLIPS",
"answ3":"TODD PHILIPS",
"answ2":"Todd Phillips.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the lead character Ray Ferrier in 2005's War of the Worlds?",
"answ":"TOM CRUISE",
"answ2":"Tom Cruise.",
},
{
"cat":"Mixed Bag",
"ques":"Kurt Russell plays R.J. MacReady in what 1982 film?",
"answ":"THE THING",
"answ2":"The Thing.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the lead role of Becky Fuller in 2010's Morning Glory?",
"answ":"RACHEL MCADAMS",
"answ2":"Rachel McAdams.",
},
{
"cat":"Mixed Bag",
"ques":"What year did Zombieland come out?",
"answ":"2009",
"answ2":"2009.",
},
{
"cat":"Mixed Bag",
"ques":"John Woo directed Nicolas Cage in what 2002 war film?",
"answ":"WINDTALKERS",
"answ2":"Windtalkers.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the films: The Hunger Games: Mockingjay Part 2, I Am Legend and Red Sparrow?",
"answ":"FRANCIS LAWRENCE",
"answ2":"Francis Lawrence.",
},
{
"cat":"Mixed Bag",
"ques":"What 2009 film featured the film debut of Chris Hemsworth?",
"answ":"STAR TREK",
"answ2":"Star Trek.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor stars as Barry Seal in American Made?",
"answ":"TOM CRUISE",
"answ2":"Tom Cruise.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress won an Oscar for her performance in The Reader?",
"answ":"KATE WINSLET",
"answ2":"Kate Winslet.",
},
{
"cat":"Mixed Bag",
"ques":"In what animated film does a criminal mastermind plan to steal the moon?",
"answ":"DESPICABLE ME",
"answ2":"Despicable Me.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the films Bugsy and Good Morning, Vietnam?",
"answ":"BARRY LEVINSON",
"answ2":"Barry Levinson.",
},
{
"cat":"Mixed Bag",
"ques":"James Cameron's Aliens came out in what year?",
"answ":"1986",
"answ2":"1986.",
},
{
"cat":"Mixed Bag",
"ques":"What actor starred as Charlie Kenton in Real Steel?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
},
{
"cat":"Mixed Bag",
"ques":"How many times did Andy Serkis portray the role of Caesar in the Planet of the Apes films?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Jurassic World?",
"answ":"COLIN TREVORROW",
"answ3":"COLIN TREVOROW",
"answ2":"Colin Trevorrow.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress stars in the following films: Chef, We Bought a Zoo and Rough Night?",
"answ":"SCARLETT JOHANSSON",
"answ3":"SCARLETT JOHANSON",
"answ2":"Scarlett Johansson.",
},
{
"cat":"Mixed Bag",
"ques":"How many installments are there in the Terminator franchise?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 1982's Tootsie?",
"answ":"SYDNEY POLLACK",
"answ3":"SIDNEY POLLACK",
"answ2":"Sydney Pollack.",
},
{
"cat":"Mixed Bag",
"ques":"In Get Smart, what Godfather actor plays the President of the United States?",
"answ":"JAMES CAAN",
"answ2":"James Caan.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor voices Yogi Bear, in 2010's Yogi Bear?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Jack Twist in Brokeback Mountain?",
"answ":"JAKE GYLLENHAAL",
"answ3":"JAKE GYLENHAAL",
"answ2":"Jake Gyllenhaal.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays FBI agent Nelville Flynn in Snakes on a Plane?",
"answ":"SAMUEL L JACKSON",
"answ3":"SAM JACKSON",
"answ2":"Samuel L. Jackson.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the villainous Captain Barbossa in the Pirates of the Caribbean series?",
"answ":"GEOFFREY RUSH",
"answ2":"Geoffrey Rush.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress appears in Charade, Roman Holiday and My Fair Lady?",
"answ":"AUDREY HEPBURN",
"answ2":"Audrey Hepburn.",
},
{
"cat":"Mixed Bag",
"ques":"Anthony Minghella directed Matt Damon in what 1999 film?",
"answ":"THE TALENTED MR RIPLEY",
"answ2":"The Talented Mr. Ripley.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays military advisor Nathan Algren in The Last Samurai?",
"answ":"TOM CRUISE",
"answ2":"Tom Cruise.",
},
{
"cat":"Mixed Bag",
"ques":"Who provided the score for Frankenweenie and Dark Shadows?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress appears in the films Contagion, The Royal Tenenbaums and Shallow Hal?",
"answ":"GWYNETH PALTROW",
"answ2":"Gwyneth Paltrow.",
},
{
"cat":"Mixed Bag",
"ques":"How many total installments of the Middle Earth films did Peter Jackson direct?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
},
{
"cat":"Mixed Bag",
"ques":"Which male actor was Oscar nominated for the film Les Miserables?",
"answ":"HUGH JACKMAN",
"answ2":"Hugh Jackman.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress plays the elf Tauriel in the Hobbit films?",
"answ":"EVANGELINE LILLY",
"answ2":"Evangeline Lilly.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of The Imitation Game and Neighbors?",
"answ":"2014",
"answ2":"2014.",
},
{
"cat":"Mixed Bag",
"ques":"In what Spielberg film does Robin Williams have a cameo as the voice of a character named Dr. Know?",
"answ":"AI ARTIFICIAL INTELLIGENCE",
"answ3":"AI",
"answ2":"A.I. Artificial Intelligence.",
},
{
"cat":"Mixed Bag",
"ques":"Which film covers the financial housing crisis of 2007 and 2008?",
"answ":"THE BIG SHORT",
"answ3":"BIG SHORT",
"answ2":"The Big Short.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor is in the films The Counselor, Song to Song and Assassin's Creed?",
"answ":"MICHAEL FASSBENDER",
"answ2":"Michael Fassbender.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the films Hunger and Shame?",
"answ":"STEVE MCQUEEN",
"answ2":"Steve McQueen.",
},
{
"cat":"Mixed Bag",
"ques":"Which biopic tells the story of Brian Wilson in the 1960s and 1980s?",
"answ":"LOVE AND MERCY",
"answ2":"Love & Mercy.",
},
{
"cat":"Mixed Bag",
"ques":"In what year was Denis Villeneuve's Prisoners released?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor plays musician Bad Blake in Crazy Heart?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"Mixed Bag",
"ques":"Who stars as Kathryn Merteuil in 1999's Cruel Intentions?",
"answ":"SARAH MICHELLE GELLAR",
"answ3":"SARA MICHELLE GELLAR",
"answ2":"Sarah Michelle Gellar.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Road Warrior?",
"answ":"GEORGE MILLER",
"answ2":"George Miller.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the lead role of Larry Donner in Throw Momma From the Train?",
"answ":"BILLY CRYSTAL",
"answ2":"Billy Crystal.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of Martin Campbell's Casino Royale?",
"answ":"2006",
"answ2":"2006.",
},
{
"cat":"Mixed Bag",
"ques":"Paul Newman and Robert Redford play two grifters in what 1973 film?",
"answ":"THE STING",
"answ2":"The Sting.",
},
{
"cat":"Mixed Bag",
"ques":"In what film does Nicolas Cage have to steal the Declaration of Independence?",
"answ":"NATIONAL TREASURE",
"answ2":"National Treasure.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of Unforgiven?",
"answ":"1992",
"answ2":"1992.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the film Exodus: Gods and Kings?",
"answ":"RIDLEY SCOTT",
"answ2":"Ridley Scott.",
},
{
"cat":"Mixed Bag",
"ques":"Who stars as Rafe McCawley in Pearl Harbor?",
"answ":"BEN AFFLECK",
"answ2":"Ben Affleck.",
},
{
"cat":"Mixed Bag",
"ques":"Denzel Washington and Viola Davis play husband and wife in what film?",
"answ":"FENCES",
"answ2":"Fences.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the 2012 comedy This is 40?",
"answ":"JUDD APATOW",
"answ2":"Judd Apatow.",
},
{
"cat":"Mixed Bag",
"ques":"An aspiring stand-up comic falls in love with Emily Gardner in what 2017 romcom?",
"answ":"THE BIG SICK",
"answ3":"BIG SICK",
"answ2":"The Big Sick.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor has roles in the films Bugsy, The Love Guru and Sexy Beast?",
"answ":"BEN KINGSLEY",
"answ2":"Ben Kingsley.",
},
{
"cat":"Mixed Bag",
"ques":"Which actress plays Eddie Redmayne's wife in The Danish Girl?",
"answ":"ALICIA VIKANDER",
"answ2":"Alicia Vikander.",
},
{
"cat":"Mixed Bag",
"ques":"Which romance film sees Julia Roberts going to Italy, India and Indonesia?",
"answ":"EAT PRAY LOVE",
"answ2":"Eat Pray Love.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor plays Naomi Watts' husband in The Impossible?",
"answ":"EWAN MCGREGOR",
"answ3":"EWAN MACGREGOR",
"answ2":"Ewan McGregor.",
},
{
"cat":"Mixed Bag",
"ques":"Frank Oz and Jim Henson co-directed what 1982 adventure fantasy?",
"answ":"THE DARK CRYSTAL",
"answ3":"DARK CRYSTAL",
"answ2":"The Dark Crystal.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Tom Cruise in Days of Thunder?",
"answ":"TONY SCOTT",
"answ2":"Tony Scott.",
},
{
"cat":"Mixed Bag",
"ques":"In which Ron Howard film does Matthew McConaughey play Ed Pekurny?",
"answ":"EDTV",
"answ2":"EDtv.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the lead role of Cecilia Kass in 2020's The Invisible Man?",
"answ":"ELISABETH MOSS",
"answ3":"ELIZABETH MOSS",
"answ2":"Elisabeth Moss.",
},
{
"cat":"Mixed Bag",
"ques":"Richard Donner directed Mel Gibson and James Garner in what 1994 film?",
"answ":"MAVERICK",
"answ2":"Maverick.",
},
{
"cat":"Mixed Bag",
"ques":"Stephen Sommers' The Mummy Returns was released in what year?",
"answ":"2001",
"answ2":"2001.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the protagonist Jake Sully in Avatar?",
"answ":"SAM WORTHINGTON",
"answ2":"Sam Worthington.",
},
{
"cat":"Mixed Bag",
"ques":"Which superhero actor plays Justin Long's boyfriend in Zack and Miri Make A Porno?",
"answ":"BRANDON ROUTH",
"answ3":"BRENDAN ROUTH",
"answ2":"Brandon Routh.",
},
{
"cat":"Mixed Bag",
"ques":"James DeMonaco directed the first 3 installments of what recent horror/thriller franchise?",
"answ":"THE PURGE",
"answ3":"PURGE",
"answ2":"The Purge.",
},
{
"cat":"Mixed Bag",
"ques":"What is the subtitle of the second National Treasure film?",
"answ":"BOOK OF SECRETS",
"answ2":"Book of Secrets.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Hansel, Zoolander's male model enemy, in Zoolander?",
"answ":"OWEN WILSON",
"answ2":"Owen Wilson.",
},
{
"cat":"Mixed Bag",
"ques":"Harrison Ford plays the character of Max Drummer in what 2014 Sylvester Stallone film?",
"answ":"THE EXPENDABLES 3",
"answ3":"EXPENDABLES 3",
"answ2":"The Expendables 3.",
},
{
"cat":"Mixed Bag",
"ques":"What John Carpenter film follows the adventures of Jack Burton going against the evil Emperor Lo Pan?",
"answ":"BIG TROUBLE IN LITTLE CHINA",
"answ2":"Big Trouble in Little China.",
},
{
"cat":"Mixed Bag",
"ques":"Which villain runs for Mayor of Gotham City in Batman Returns?",
"answ":"THE PENGUIN",
"answ3":"PENGUIN",
"answ2":"The Penguin.",
},
{
"cat":"Mixed Bag",
"ques":"Who stars as Det. John Book in Witness?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Mixed Bag",
"ques":"What MCU film received a Best Picture nomination?",
"answ":"BLACK PANTHER",
"answ2":"Black Panther.",
},
{
"cat":"Mixed Bag",
"ques":"Angelina Jolie stars in what 2014 Disney film?",
"answ":"MALEFICENT",
"answ2":"Maleficent.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor stars as Balian of Ibelin, the lead of Ridley Scott's Kingdom of Heaven?",
"answ":"ORLANDO BLOOM",
"answ2":"Orlando Bloom.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the 2019 film Us?",
"answ":"JORDAN PEELE",
"answ3":"JORDAN PEEL",
"answ2":"Jordan Peele.",
},
{
"cat":"Mixed Bag",
"ques":"In what year were the comedies Anchorman, Dodgeball and Mean Girls released?",
"answ":"2004",
"answ2":"2004.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Grocer, the chief rival to John Cusack's character in Grosse Pointe Blank?",
"answ":"DAN AYKROYD",
"answ3":"DAN AKROYD",
"answ2":"Dan Aykroyd.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the title character in Uncle Buck?",
"answ":"JOHN CANDY",
"answ2":"John Candy.",
},
{
"cat":"Mixed Bag",
"ques":"Denzel Washington had famously never done a sequel to one of his films until which 2018 film?",
"answ":"THE EQUALIZER 2",
"answ3":"EQUALIZER 2",
"answ2":"The Equalizer 2.",
},
{
"cat":"Mixed Bag",
"ques":"Which 2005 Steve Carell film served as Judd Apatow's directorial debut?",
"answ":"THE 40 YEAR OLD VIRGIN",
"answ3":"40 YEAR OLD VIRGIN",
"answ2":"The 40-Year-Old Virgin.",
},
{
"cat":"Mixed Bag",
"ques":"Which Oscar nominated coming-of-age movie was filmed over a 12-year period?",
"answ":"BOYHOOD",
"answ2":"Boyhood.",
},
{
"cat":"Mixed Bag",
"ques":"What film released in 2014 won Best Picture at the Academy Awards?",
"answ":"BIRDMAN",
"answ2":"Birdman.",
},
{
"cat":"Mixed Bag",
"ques":"The 1996 comedy Kingpin revolves around which sport?",
"answ":"BOWLING",
"answ2":"Bowling.",
},
{
"cat":"Mixed Bag",
"ques":"Which film stars the following actors: Val Kilmer, Michael Rapaport, Dennis Hopper, Brad Pitt, Gary Oldman?",
"answ":"TRUE ROMANCE",
"answ2":"True Romance.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays linguist Louise Banks in Arrival?",
"answ":"AMY ADAMS",
"answ2":"Amy Adams.",
},
{
"cat":"Mixed Bag",
"ques":"Who played U.S. President James Marshall in Air Force One?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
},
{
"cat":"Mixed Bag",
"ques":"What kind of creature is Gizmo in Gremlins?",
"answ":"MOGWAI",
"answ2":"Mogwai.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Scotty in J.J. Abrams's Star Trek?",
"answ":"SIMON PEGG",
"answ2":"Simon Pegg.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Shutter Island?",
"answ":"MARTIN SCORSESE",
"answ2":"Martin Scorsese.",
},
{
"cat":"Mixed Bag",
"ques":"Who stars as the lead in 2018's Death Wish?",
"answ":"BRUCE WILLIS",
"answ2":"Bruce Willis.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the well-meaning inventor father in Honey, I Shrunk the Kids?",
"answ":"RICK MORANIS",
"answ2":"Rick Moranis.",
},
{
"cat":"Mixed Bag",
"ques":"What 2006 sci-fi film co-stars Julianne Moore, Michael Caine, Chiwetel Ejiofor and Clive Owen?",
"answ":"CHILDREN OF MEN",
"answ2":"Children of Men.",
},
{
"cat":"Mixed Bag",
"ques":"What 1985 John Hughes movie involves two teenage boys who create a woman using their computer?",
"answ":"WEIRD SCIENCE",
"answ2":"Weird Science.",
},
{
"cat":"Mixed Bag",
"ques":"What year saw the release of the Victor Flemming movie, Gone With The Wind?",
"answ":"1939",
"answ2":"1939.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor played Sonny Corleone in The Godfather?",
"answ":"JAMES CAAN",
"answ2":"James Caan.",
},
{
"cat":"Mixed Bag",
"ques":"What character did Kevin Smith portray in Clerks, Mallrats and Dogma?",
"answ":"SILENT BOB",
"answ2":"Silent Bob.",
},
{
"cat":"Mixed Bag",
"ques":"Leslie Nielsen plays the incompetent Frank Drebin in what comedy franchise?",
"answ":"THE NAKED GUN",
"answ3":"NAKED GUN",
"answ2":"The Naked Gun.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2006's Apocalypto?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Mixed Bag",
"ques":"What was the first collaboration between actor Tom Hanks and director Steven Spielberg?",
"answ":"SAVING PRIVATE RYAN",
"answ2":"Saving Private Ryan.",
},
{
"cat":"Mixed Bag",
"ques":"What movie features the ensemble cast of Forest Whitaker, Nicolas Cage, Sean Penn, Jennifer Jason Leigh and Phoebe Cates?",
"answ":"FAST TIMES AT RIDGEMONT HIGH",
"answ3":"FAST TIMES AT RIDGEMOND HIGH",
"answ2":"Fast Times at Ridgemont High.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the 1995 western The Quick and the Dead?",
"answ":"SAM RAIMI",
"answ2":"Sam Raimi.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Dana Barrett in 1984's Ghostbusters?",
"answ":"SIGOURNEY WEAVER",
"answ3":"SIGNOUREY WEAVER",
"answ2":"Sigourney Weaver.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Gomer Pyle in Full Metal Jacket?",
"answ":"VINCENT D'ONOFRIO",
"answ3":"VINCENT D'NOFRIO",
"answ2":"Vincent D'Onofrio.",
},
{
"cat":"Mixed Bag",
"ques":"This actor played Willy Wonka in the 2005 film Charlie and the Chocolate Factory.",
"answ":"JOHNNY DEPP",
"answ2":"Johnny Depp.",
},
{
"cat":"Mixed Bag",
"ques":"Who wrote and directed 2000's crime comedy Snatch?",
"answ":"GUY RITCHIE",
"answ2":"Guy Ritchie.",
},
{
"cat":"Mixed Bag",
"ques":"In 1954's Rear Window, who played injured photographer L.B. 'Jeff' Jefferies?",
"answ":"JAMES STEWART",
"answ3":"JIMMY STEWART",
"answ2":"James Stewart.",
},
{
"cat":"Mixed Bag",
"ques":"In what post-apocalyptic tale does Denzel Washington play a blind man?",
"answ":"THE BOOK OF ELI",
"answ3":"BOOK OF ELI",
"answ2":"The Book of Eli.",
},
{
"cat":"Mixed Bag",
"ques":"What actress plays Anna Scott in Notting Hill?",
"answ":"JULIA ROBERTS",
"answ2":"Julia Roberts.",
},
{
"cat":"Mixed Bag",
"ques":"In the Star Wars franchise, Queen Amidala is from which planet?",
"answ":"NABOO",
"answ2":"Naboo.",
},
{
"cat":"Mixed Bag",
"ques":"Which eye is Kubo missing in Kubo and the Two Strings?",
"answ":"LEFT EYE",
"answ3":"LEFT",
"answ2":"Left eye.",
},
{
"cat":"Mixed Bag",
"ques":"What is the subtitle of the 1993 Robin Hood spoof, which was directed by Mel Brooks?",
"answ":"MEN IN TIGHTS",
"answ3":"MAN IN TIGHTS",
"answ2":"Men in tights.",
},
{
"cat":"Mixed Bag",
"ques":"What teen-comedy franchise features characters named Jim Levenstein, Michelle Flaherty and Paul Finch?",
"answ":"AMERICAN PIE",
"answ2":"American Pie.",
},
{
"cat":"Mixed Bag",
"ques":"The Hunger Games: Catching Fire was released in what year?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"Mixed Bag",
"ques":"Daniel Craig took on the role of 007 for the first time in what 2006 James Bond film?",
"answ":"CASINO ROYALE",
"answ2":"Casino Royale.",
},
{
"cat":"Mixed Bag",
"ques":"Which one of the following actors has NOT played Hamlet in a film: Kenneth Branagh, Joseph Fiennes or Mel Gibson?",
"answ":"JOSEPH FIENNES",
"answ2":"Joseph Fiennes.",
},
{
"cat":"Mixed Bag",
"ques":"Who played ballerina Nina Sayers and The Swan Queen in Black Swan?",
"answ":"NATALIE PORTMAN",
"answ2":"Natalie Portman.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film from the following characters: Heywood, Warden Norton, Captain Hadley, Red, Brooks.",
"answ":"THE SHAWSHANK REDEMPTION",
"answ3":"SHAWSHANK REDEMPTION",
"answ2":"The Shawshank Redemption.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Adventures of Tintin?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"Mixed Bag",
"ques":"In Clue, who plays Wadsworth the butler?",
"answ":"TIM CURRY",
"answ2":"Tim Curry.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Ruth Bader Ginsburg in On the Basis of Sex?",
"answ":"FELICITY JONES",
"answ2":"Felicity Jones.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Jackie Robinson in 42?",
"answ":"CHADWICK BOSEMAN",
"answ3":"CHADWICK BOZEMAN",
"answ2":"Chadwick Boseman.",
},
{
"cat":"Mixed Bag",
"ques":"What drama stars Ron Rifkin, Guy Pearce, Danny DeVito and Russel Crowe?",
"answ":"LA CONFIDENTIAL",
"answ3":"L A CONFIDENTIAL",
"answ2":"L.A. Confidential.",
},
{
"cat":"Mixed Bag",
"ques":"Finish the quote: 'On Wednesdays we wear ____'",
"answ":"PINK",
"answ2":"Pink.",
},
{
"cat":"Mixed Bag",
"ques":"Which year saw the release of the Ang Lee film Life of Pi?",
"answ":"2012",
"answ2":"2012.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Minority Report?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"Mixed Bag",
"ques":"Which actor appeared in the films Chronicle, Red Tails and That Awkward Moment?",
"answ":"MICHAEL B JORDAN",
"answ2":"Michael B. Jordan.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays the wizard Shazam in Shazam!?",
"answ":"DJIMON HOUNSOU",
"answ3":"DJIMON HONSOU",
"answ2":"Djimon Hounsou.",
},
{
"cat":"Mixed Bag",
"ques":"What is Jim Carrey's profession in 1997's Liar Liar?",
"answ":"LAWYER",
"answ2":"Lawyer.",
},
{
"cat":"Mixed Bag",
"ques":"Reese Witherspoon, Josh Lucas and Patrick Dempsey starred in what 2002 rom-com?",
"answ":"SWEET HOME ALABAMA",
"answ2":"Sweet Home Alabama.",
},
{
"cat":"Mixed Bag",
"ques":"Name the movie that begins with the narrated line: 'People are always asking me if I know Tyler Durden.'?",
"answ":"FIGHT CLUB",
"answ2":"Fight Club.",
},
{
"cat":"Mixed Bag",
"ques":"What action film franchise features the following characters: Luther, Benji, Ethan Hunt, Lindsey Farris?",
"answ":"MISSION IMPOSSIBLE",
"answ2":"Mission: Impossible.",
},
{
"cat":"Mixed Bag",
"ques":"In Disney's Frozen, who voices Anna?",
"answ":"KRISTEN BELL",
"answ3":"KIRSTEN BELL",
"answ2":"Kristen Bell.",
},
{
"cat":"Mixed Bag",
"ques":"Ben Affleck and Jon Favreau are a team of lawyers in what comic book film?",
"answ":"DAREDEVIL",
"answ2":"Daredevil.",
},
{
"cat":"Mixed Bag",
"ques":"The Incredible Hulk starring Edward Norton was released in what year?",
"answ":"2008",
"answ2":"2008.",
},
{
"cat":"Mixed Bag",
"ques":"This 1980s film starred Chris Sarandon, Robin Wright, Cary Elwes, Mandy Patinkin and Andre the Giant.",
"answ":"THE PRINCESS BRIDE",
"answ3":"PRINCESS BRIDE",
"answ2":"The Princess Bride.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Outlaw Josey Wales?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Natalie Portman's assistant Darcy in Thor and Thor: The Dark World?",
"answ":"KAT DENNINGS",
"answ2":"Kat Dennings.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Biff in Back to the Future?",
"answ":"THOMAS F WILSON",
"answ3":"THOMAS WILSON",
"answ2":"Thomas F. Wilson.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Julie Powell alongside Meryl Streep in Julie & Julia?",
"answ":"AMY ADAMS",
"answ2":"Amy Adams.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Ramesses in Exodus: Gods and Kings?",
"answ":"JOEL EDGERTON",
"answ3":"JOEL EDGARTON",
"answ2":"Joel Edgerton.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Jim's father in American Pie?",
"answ":"EUGENE LEVY",
"answ3":"EUGENE LEVI",
"answ2":"Eugene Levy.",
},
{
"cat":"Mixed Bag",
"ques":"What was the title of the 1996 sequel to Escape From New York?",
"answ":"ESCAPE FROM LA",
"answ3":"ESCAPE FROM L A",
"answ2":"Escape from L.A.",
},
{
"cat":"Mixed Bag",
"ques":"Who voiced Michael 'Mike' Wazowski in Monsters Inc.?",
"answ":"BILLY CRYSTAL",
"answ2":"Billy Crystal.",
},
{
"cat":"Mixed Bag",
"ques":"What actor won Best Supporting Actor at the Oscars for his performance in Bridge of Spies?",
"answ":"MARK RYLANCE",
"answ2":"Mark Rylance.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Disaster Artist?",
"answ":"JAMES FRANCO",
"answ2":"James Franco.",
},
{
"cat":"Mixed Bag",
"ques":"Who voiced King Candy, the ruler of Sugar Rush, in Wreck-It-Ralph?",
"answ":"ALAN TUDYK",
"answ3":"ALAN TUDIK",
"answ2":"Alan Tudyk.",
},
{
"cat":"Mixed Bag",
"ques":"What is the final film of the Marvel Cinematic Universe's Phase 2?",
"answ":"ANT MAN",
"answ3":"ANTMAN",
"answ2":"Ant-Man.",
},
{
"cat":"Mixed Bag",
"ques":"Which member of the Friends cast appears in the 1999 film Three To Tango?",
"answ":"MATTHEW PERRY",
"answ2":"Matthew Perry.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film from the following characters: Harry, Chick, Bear, Dan Truman, AJ, Grace, Rockhound.",
"answ":"ARMAGEDDON",
"answ3":"ARMEGEDDON",
"answ2":"Armageddon.",
},
{
"cat":"Mixed Bag",
"ques":"Will Smith, Kevin Kline and Salma Hayek star together in what movie?",
"answ":"WILD WILD WEST",
"answ2":"Wild Wild West.",
},
{
"cat":"Mixed Bag",
"ques":"Robin Williams, Paul L. Smith and Shelley Duvall star together in this comedy.",
"answ":"POPEYE",
"answ2":"Popeye.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2017's The Mummy?",
"answ":"ALEX KURTZMAN",
"answ2":"Alex Kurtzman.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Veronica Corningstone in Anchorman: The Legend of Ron Burgundy?",
"answ":"CHRISTINA APPLEGATE",
"answ2":"Christina Applegate.",
},
{
"cat":"Mixed Bag",
"ques":"In The Wizard of Oz, what does the Tin Man want?",
"answ":"A HEART",
"answ3":"HEART",
"answ2":"A heart.",
},
{
"cat":"Mixed Bag",
"ques":"What was the nickname children called Samuel L. Jackson's Elijah Prince in Unbreakable?",
"answ":"MR GLASS",
"answ3":"MISTER GLASS",
"answ2":"Mr. Glass.",
},
{
"cat":"Mixed Bag",
"ques":"Ben Stiller, Robin Williams and Dick Van Dyke star in what 2006 family film?",
"answ":"NIGHT AT THE MUSEUM",
"answ2":"Night at the Museum.",
},
{
"cat":"Mixed Bag",
"ques":"Name the movie from the following characters: Jim, Bart, Taggert, Lili von Shtüpp, Mongo, Hedley Lamarr.",
"answ":"BLAZING SADDLES",
"answ2":"Blazing Saddles.",
},
{
"cat":"Mixed Bag",
"ques":"How many Karate Kid movies featured Pat Morita as Mr. Miyagi?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"Mixed Bag",
"ques":"In The Wizard of Oz, who is the first of the three companions that Dorothy met on her quest to meet The Wizard?",
"answ":"SCARECROW",
"answ2":"Scarecrow.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Tom Hanks' love interest in You've Got Mail?",
"answ":"MEG RYAN",
"answ2":"Meg Ryan.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the original Point Break?",
"answ":"KATHRYN BIGELOW",
"answ3":"KATHERINE BIGELOW",
"answ2":"Kathryn Bigelow.",
},
{
"cat":"Mixed Bag",
"ques":"In Say Anything, John Cusack holds up what out the front of Diane Court's bedroom window?",
"answ":"BOOMBOX",
"answ2":"Boombox.",
},
{
"cat":"Mixed Bag",
"ques":"Name the movie from the tagline: 'One dream. Four Jamaicans. Twenty below zero.'",
"answ":"COOL RUNNINGS",
"answ2":"Cool Runnings.",
},
{
"cat":"Mixed Bag",
"ques":"Kurt Russell played USA Olympic hockey coach Herb Brooks in what film?",
"answ":"MIRACLE",
"answ2":"Miracle.",
},
{
"cat":"Mixed Bag",
"ques":"What classic Greek mythology figure did Brad Pitt portray in 2004's Troy?",
"answ":"ACHILLES",
"answ2":"Achilles.",
},
{
"cat":"Mixed Bag",
"ques":"What was the nickname of Indiana's child sidekick in Indiana Jones and the Temple of Doom?",
"answ":"SHORT ROUND",
"answ2":"Short Round.",
},
{
"cat":"Mixed Bag",
"ques":"In what 2016 crime-comedy will you hear the quote: 'I had to question the mermaids'?",
"answ":"THE NICE GUYS",
"answ3":"NICE GUYS",
"answ2":"The Nice Guys.",
},
{
"cat":"Mixed Bag",
"ques":"Who was the voice and puppeteer of Yoda?",
"answ":"FRANK OZ",
"answ2":"Frank Oz.",
},
{
"cat":"Mixed Bag",
"ques":"The first Scary Movie was released in what year?",
"answ":"2000",
"answ2":"2000.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the 1992 biopic Malcolm X?",
"answ":"SPIKE LEE",
"answ2":"Spike Lee.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Father Merrin in 1973's The Exorcist?",
"answ":"MAX VON SYDOW",
"answ3":"MAX VON SIDOW",
"answ2":"Max von Sydow.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of Samuel L. Jackson's hero alter-ego in The Incredibles?",
"answ":"FROZONE",
"answ2":"Frozone.",
},
{
"cat":"Mixed Bag",
"ques":"Zack Snyder directed what 2011 film starring Emily Browning and Abbie Cornish?",
"answ":"SUCKER PUNCH",
"answ2":"Sucker Punch.",
},
{
"cat":"Mixed Bag",
"ques":"What actress starred as the 'Amazing' Amy Dunne in Gone Girl?",
"answ":"ROSAMUND PIKE",
"answ2":"Rosamund Pike.",
},
{
"cat":"Mixed Bag",
"ques":"What 90s action film stars Antonio Banderas and Salma Hayek?",
"answ":"DESPERADO",
"answ2":"Desperado.",
},
{
"cat":"Mixed Bag",
"ques":"Which Disney film features the song 'I Wan'na Be Like You'?",
"answ":"THE JUNGLE BOOK",
"answ3":"JUNGLE BOOK",
"answ2":"The Jungle Book.",
},
{
"cat":"Mixed Bag",
"ques":"Which Hitchcock movie stars James Stewart as a photographer who thinks his neighbor is a murderer?",
"answ":"REAR WINDOW",
"answ2":"Rear Window.",
},
{
"cat":"Mixed Bag",
"ques":"Finish the quote from V for Vendetta: 'Remember, Remember the ____ of November.'",
"answ":"FIFTH",
"answ3":"5TH",
"answ2":"Fifth.",
},
{
"cat":"Mixed Bag",
"ques":"What film was the directorial debut of Ryan Coogler?",
"answ":"FRUITVALE STATION",
"answ2":"Fruitvale Station.",
},
{
"cat":"Mixed Bag",
"ques":"Quentin Tarantino wrote the screenplay for which 1990s vampire flick?",
"answ":"FROM DUSK TILL DAWN",
"answ2":"From Dusk Till Dawn.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed The Exorcist?",
"answ":"WILLIAM FRIEDKIN",
"answ2":"William Friedkin.",
},
{
"cat":"Mixed Bag",
"ques":"Anchorman: The Legend of Ron Burgundy is set in what U.S. city?",
"answ":"SAN DIEGO",
"answ2":"San Diego.",
},
{
"cat":"Mixed Bag",
"ques":"In Gremlins, what does Randall name the mogwai he buys for his son?",
"answ":"GIZMO",
"answ3":"GISMO",
"answ2":"Gizmo.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 1987's Wall Street?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the crime lord with the mythical reputation in The Usual Suspects?",
"answ":"KEYSER SOZE",
"answ3":"KEYSER SÖZE",
"answ2":"Keyser Söze.",
},
{
"cat":"Mixed Bag",
"ques":"In The Terminator, who plays Sarah Connor?",
"answ":"LINDA HAMILTON",
"answ2":"Linda Hamilton.",
},
{
"cat":"Mixed Bag",
"ques":"Morgan Spurlock packs on pounds while living on McDonald's in what film?",
"answ":"SUPER SIZE ME",
"answ2":"Super Size Me.",
},
{
"cat":"Mixed Bag",
"ques":"Name the 1995 movie starring Gene Hackman and Denzel Washington.",
"answ":"CRIMSON TIDE",
"answ2":"Crimson Tide.",
},
{
"cat":"Mixed Bag",
"ques":"What was the nationality of the terrorists in Die Hard?",
"answ":"GERMAN",
"answ3":"GERMANY",
"answ2":"German.",
},
{
"cat":"Mixed Bag",
"ques":"Who portrayed Mark Zuckerberg in The Social Network?",
"answ":"JESSE EISENBERG",
"answ2":"Jesse Eisenberg.",
},
{
"cat":"Mixed Bag",
"ques":"This Steven Spielberg film came out in 1982 and starred Dee Wallace, Drew Barrymore and Henry Thomas.",
"answ":"ET THE EXTRA TERRESTRIAL",
"answ3":"ET",
"answ2":"E.T. the Extra-Terrestrial.",
},
{
"cat":"Mixed Bag",
"ques":"Name the Nicholas Spark movie that stars Shane West and Mandy Moore.",
"answ":"A WALK TO REMEMBER",
"answ2":"A Walk to Remember.",
},
{
"cat":"Mixed Bag",
"ques":"What movie based on a 1960's television series features a villainous Sean Connery in a teddy bear suit?",
"answ":"THE AVENGERS",
"answ2":"The Avengers.",
},
{
"cat":"Mixed Bag",
"ques":"What was the first Batman movie to feature a score by composer Elliot Goldenthal?",
"answ":"BATMAN FOREVER",
"answ2":"Batman Forever.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the character played by Johnny Depp in the Tim Burton film Sleepy Hollow?",
"answ":"ICHABOD CRANE",
"answ2":"Ichabod Crane.",
},
{
"cat":"Mixed Bag",
"ques":"In 1990's Home Alone, the McCallisters were traveling to what European city for Christmas?",
"answ":"PARIS",
"answ2":"Paris.",
},
{
"cat":"Mixed Bag",
"ques":"In what 80s comedy does Tom Hanks play Detective Scott Turner?",
"answ":"TURNER AND HOOCH",
"answ2":"Turner & Hooch.",
},
{
"cat":"Mixed Bag",
"ques":"Who played taxi-driving misfit Travis Bickle?",
"answ":"ROBERT DE NIRO",
"answ3":"ROBERT DENIRO",
"answ2":"Robert De Niro.",
},
{
"cat":"Mixed Bag",
"ques":"In Tangled, what is Rapunzel's weapon of choice?",
"answ":"FRYING PAN",
"answ3":"PAN",
"answ2":"Frying Pan.",
},
{
"cat":"Mixed Bag",
"ques":"Finish the quote: 'Soylent Green is ____'",
"answ":"MADE OUT OF PEOPLE",
"answ2":"Made out of people.",
},
{
"cat":"Mixed Bag",
"ques":"The Road Warrior is a sequel to what movie?",
"answ":"MAD MAX",
"answ2":"Mad Max.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the dragon voiced by Sean Connery in Dragonheart?",
"answ":"DRACO",
"answ2":"Draco.",
},
{
"cat":"Mixed Bag",
"ques":"What film's characters include Marvin Acme, Judge Doom and Eddie Valiant?",
"answ":"WHO FRAMED ROGER RABBIT",
"answ2":"Who Framed Roger Rabbit.",
},
{
"cat":"Mixed Bag",
"ques":"John Travolta and Nicolas Cage square off in what John Woo film?",
"answ":"FACE OFF",
"answ3":"FACE/OFF",
"answ2":"Face/Off.",
},
{
"cat":"Mixed Bag",
"ques":"What was the name of the 2015 boxing film and Rocky spinoff starring Michael B. Jordan?",
"answ":"CREED",
"answ2":"Creed.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the princess in Disney's Aladdin?",
"answ":"JASMINE",
"answ3":"JASMIN",
"answ2":"Jasmine.",
},
{
"cat":"Mixed Bag",
"ques":"What Lord of the Rings actor also narrates 2007's adventure film Stardust?",
"answ":"IAN MCKELLEN",
"answ3":"IAN MCKALLEN",
"answ2":"Ian McKellen.",
},
{
"cat":"Mixed Bag",
"ques":"Marty McFly says: 'Nobody calls me _____'",
"answ":"CHICKEN",
"answ2":"Chicken.",
},
{
"cat":"Mixed Bag",
"ques":"Peter MacNicol plays Dr. Janosz Poha in what movie?",
"answ":"GHOSTBUSTERS II",
"answ3":"GHOSTBUSTERS 2",
"answ2":"Ghostbusters II.",
},
{
"cat":"Mixed Bag",
"ques":"Chris Farley and David Spade star in what movie about auto parts salesmen?",
"answ":"TOMMY BOY",
"answ3":"TOMMYBOY",
"answ2":"Tommy Boy.",
},
{
"cat":"Mixed Bag",
"ques":"What 2006 documentary features Al Gore and the tagline 'By Far the Most Terrifying Film You've Ever Seen'?",
"answ":"AN INCONVENIENT TRUTH",
"answ3":"INCONVENIENT TRUTH",
"answ2":"An Inconvenient Truth.",
},
{
"cat":"Mixed Bag",
"ques":"What character was played by John Cleese in 1981, Kevin Costner in 1991 and Cary Elwes in 1993?",
"answ":"ROBIN HOOD",
"answ2":"Robin Hood.",
},
{
"cat":"Mixed Bag",
"ques":"This 1960s film became the first and only X-rated movie in history to win Best Picture.",
"answ":"MIDNIGHT COWBOY",
"answ2":"Midnight Cowboy.",
},
{
"cat":"Mixed Bag",
"ques":"What actress played Rabbit's mom Stephanie in 2002's 8 Mile?",
"answ":"KIM BASINGER",
"answ2":"Kim Basinger.",
},
{
"cat":"Mixed Bag",
"ques":"Who won an Oscar for their performance in the 2006 film Dreamgirls?",
"answ":"JENNIFER HUDSON",
"answ2":"Jennifer Hudson.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Thulsa Doom in the original Conan the Barbarian?",
"answ":"JAMES EARL JONES",
"answ2":"James Earl Jones.",
},
{
"cat":"Mixed Bag",
"ques":"In Apollo 13, which actor played the role of Jack Swigert, who replaced astronaut Ken Mattingly at the last minute?",
"answ":"KEVIN BACON",
"answ2":"Kevin Bacon.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the young astronomer Leo Biederman who co-discovered the commet headed towards Earth in Deep Impact?",
"answ":"ELIJAH WOOD",
"answ2":"Elijah Wood.",
},
{
"cat":"Mixed Bag",
"ques":"What is the profession of Simon Pegg and Nick Frost in Hot Fuzz?",
"answ":"POLICE OFFICER",
"answ3":"COP",
"answ2":"Police Officer.",
},
{
"cat":"Mixed Bag",
"ques":"What 1989 comedy stars John Travolta, Kirstie Alley and a baby with the voice of Bruce Willis?",
"answ":"LOOK WHO'S TALKING",
"answ2":"Look Who's Talking.",
},
{
"cat":"Mixed Bag",
"ques":"Who voiced the title character in Fantastic Mr. Fox?",
"answ":"GEORGE CLOONEY",
"answ2":"George Clooney.",
},
{
"cat":"Mixed Bag",
"ques":"Which movie was the feature film directorial debut of F. Gary Gray?",
"answ":"FRIDAY",
"answ2":"Friday.",
},
{
"cat":"Mixed Bag",
"ques":"In Independence Day, who plays Captain Steven Hiller's fighter pilot friend that gets killed in the first battle?",
"answ":"HARRY CONNICK JR",
"answ2":"Harry Connick Jr.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of Gru's twin brother in the Despicable Me franchise?",
"answ":"DRU",
"answ2":"Dru.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the iconic dance Chunk does at the beginning of The Goonies?",
"answ":"TRUFFLE SHUFFLE",
"answ3":"THE TRUFFLE SHUFFLE",
"answ2":"Truffle Shuffle.",
},
{
"cat":"Mixed Bag",
"ques":"In what Jack Black movie does he play the author of a popular kids book series?",
"answ":"GOOSEBUMPS",
"answ2":"Goosebumps.",
},
{
"cat":"Mixed Bag",
"ques":"What Batman comic book villain is played by Cillian Murphy in Batman Begins?",
"answ":"SCARECROW",
"answ2":"Scarecrow.",
},
{
"cat":"Mixed Bag",
"ques":"What actress provides the voice of Fiona in the Shrek movies?",
"answ":"CAMERON DIAZ",
"answ2":"Cameron Diaz.",
},
{
"cat":"Mixed Bag",
"ques":"How many Guardians of the Galaxy are there by the end of the first movie?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
},
{
"cat":"Mixed Bag",
"ques":"What character did Christian Bale play in 2009's Terminator Salvation?",
"answ":"JOHN CONNOR",
"answ2":"John Connor.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Adonis in the movie Creed?",
"answ":"MICHAEL B JORDAN",
"answ2":"Michael B. Jordan.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed 2013's Mama?",
"answ":"ANDY MUSCHIETTI",
"answ3":"ANDY MUSHIETTI",
"answ2":"Andy Muschietti.",
},
{
"cat":"Mixed Bag",
"ques":"What kind of animal does the T-Rex eat before breaking out of his cage in Jurassic Park?",
"answ":"GOAT",
"answ3":"A GOAT",
"answ2":"Goat.",
},
{
"cat":"Mixed Bag",
"ques":"In Stand By Me, Gordie, Chris, Teddy and Vern journey into the woods looking for a ____",
"answ":"DEAD BODY",
"answ3":"CORPSE",
"answ2":"Dead body.",
},
{
"cat":"Mixed Bag",
"ques":"Which character has the ability to 'shine' in 1980s The Shining?",
"answ":"DANNY",
"answ3":"DANNY TORRANCE",
"answ2":"Danny Torrance.",
},
{
"cat":"Mixed Bag",
"ques":"What villain do the Avengers fight at the beginning of the movie Captain America Civil War?",
"answ":"CROSSBONES",
"answ3":"BROCK RUMLOW",
"answ2":"Crossbones.",
},
{
"cat":"Mixed Bag",
"ques":"What 90s comedy features the quote: 'We got no food, we got no jobs, our pet's heads are falling off!'",
"answ":"DUMB AND DUMBER",
"answ2":"Dumb and Dumber.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Dr. Jonathan Crane aka The Scarecrow in Christopher Nolan's Batman films?",
"answ":"CILLIAN MURPHY",
"answ3":"KILLIAN MURPHY",
"answ2":"Cillian Murphy.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Le Chiffre in 2006's Casino Royale?",
"answ":"MADS MIKKELSEN",
"answ3":"MADS MIKELSEN",
"answ2":"Mads Mikkelsen.",
},
{
"cat":"Mixed Bag",
"ques":"In which city do the events of 1995's Bad Boys take place?",
"answ":"MIAMI",
"answ2":"Miami.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the little girl taken in by Ellen Ripley in 1986's Aliens?",
"answ":"NEWT",
"answ2":"Newt.",
},
{
"cat":"Mixed Bag",
"ques":"In The Departed, who plays Colin Sullivan, the criminal who infiltrates the Boston police?",
"answ":"MATT DAMON",
"answ2":"Matt Damon.",
},
{
"cat":"Mixed Bag",
"ques":"Sean Penn plays a stoner called Spicoli in what 80s comedy?",
"answ":"FAST TIMES AT RIDGEMONT HIGH",
"answ3":"FAST TIMES AT RIDGEMOND HIGH",
"answ2":"Fast Times at Ridgemont High.",
},
{
"cat":"Mixed Bag",
"ques":"Molly Ringwald's first starring role was as Samantha in what teen comedy?",
"answ":"SIXTEEN CANDLES",
"answ3":"16 CANDLES",
"answ2":"Sixteen Candles.",
},
{
"cat":"Mixed Bag",
"ques":"Forrest Gump goes into the shrimping business to honor what fallen comrade?",
"answ":"BUBBA",
"answ2":"Bubba.",
},
{
"cat":"Mixed Bag",
"ques":"Name an actress that plays one of the wives in the 2005 drama Brokeback Mountain.",
"answ":"MICHELLE WILLIAMS",
"answ3":"ANNE HATHAWAY",
"answ2":"Michelle Williams/Anne Hathaway.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the President of the United States in the film Deep Impact?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the fictional California town that Marty McFly is from?",
"answ":"HILL VALLEY",
"answ2":"Hill Valley.",
},
{
"cat":"Mixed Bag",
"ques":"Harry and Sally finally get together during what holiday?",
"answ":"NEW YEAR'S EVE",
"answ3":"NEW YEARS EVE",
"answ2":"New Year's Eve.",
},
{
"cat":"Mixed Bag",
"ques":"Angela Bassett plays Tina Turner in what biopic?",
"answ":"WHAT'S LOVE GOTTA DO WITH IT",
"answ3":"WHAT'S LOVE GOT TO DO WITH IT",
"answ2":"What's Love Got to Do with It.",
},
{
"cat":"Mixed Bag",
"ques":"In The Number 23, what actor is obsessed with a novel?",
"answ":"JIM CARREY",
"answ2":"Jim Carrey.",
},
{
"cat":"Mixed Bag",
"ques":"What was the name of the follow-up film to Pee Wee's Big Adventure?",
"answ":"BIG TOP PEE WEE",
"answ2":"Big Top Pee-wee.",
},
{
"cat":"Mixed Bag",
"ques":"Roddy McDowell plays Peter Vincent in what 1980's thrillfest?",
"answ":"FRIGHT NIGHT",
"answ2":"Fright Night.",
},
{
"cat":"Mixed Bag",
"ques":"In what movie does Gary Busey play a villain that teams with Tommy Lee Jones named Commander Krill?",
"answ":"UNDER SIEGE",
"answ2":"Under Siege.",
},
{
"cat":"Mixed Bag",
"ques":"Kate Winslet and Leonardo DiCaprio star as a young couple in a Connecticut suburb in what movie?",
"answ":"REVOLUTIONARY ROAD",
"answ2":"Revolutionary Road.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays forensic psychologist Alex Cross in 1997's Kiss the Girls?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Mixed Bag",
"ques":"Who voices the title character of Balto in the 1995 film Balto?",
"answ":"KEVIN BACON",
"answ2":"Kevin Bacon.",
},
{
"cat":"Mixed Bag",
"ques":"Cloverfield, Hellboy II The Golden Army and Gran Torino were all released in what year?",
"answ":"2008",
"answ2":"2008.",
},
{
"cat":"Mixed Bag",
"ques":"Jodie Foster loses her daughter on a plane in what movie?",
"answ":"FLIGHTPLAN",
"answ2":"Flightplan.",
},
{
"cat":"Mixed Bag",
"ques":"What actor played characters named Farmer Ted, Brian Johnson and Gary Wallace in 1980s teen comedies?",
"answ":"ANTHONY MICHAEL HALL",
"answ2":"Anthony Michael Hall.",
},
{
"cat":"Mixed Bag",
"ques":"Who composed the score for Vertigo, North by Northwest and Psycho?",
"answ":"BERNARD HERRMANN",
"answ3":"BERNARD HERMANN",
"answ2":"Bernard Herrmann.",
},
{
"cat":"Mixed Bag",
"ques":"In the movie The Great White Hope, James Earl Jones played what boxer?",
"answ":"JACK JOHNSON",
"answ2":"Jack Johnson.",
},
{
"cat":"Mixed Bag",
"ques":"Who played more than one role in the Stanley Kubrick classic Dr. Strangelove?",
"answ":"PETER SELLERS",
"answ2":"Peter Sellers.",
},
{
"cat":"Mixed Bag",
"ques":"The Maltese Falcon and Disney's Dumbo were both released in what decade?",
"answ":"1940S",
"answ3":"40S",
"answ2":"1940s.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the 2013 movie Elysium?",
"answ":"NEIL BLOMKAMP",
"answ3":"NEILL BLOMKAMP",
"answ2":"Neil Blomkamp.",
},
{
"cat":"Mixed Bag",
"ques":"What actress starred as a tough cop in Blue Steel?",
"answ":"JAMIE LEE CURTIS",
"answ2":"Jamie Lee Curtis.",
},
{
"cat":"Mixed Bag",
"ques":"In what comedy does a sexy foreign student named Nadia move to town?",
"answ":"AMERICAN PIE",
"answ2":"American Pie.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Paulie the father of Juno MacGuff's child in Juno?",
"answ":"MICHAEL CERA",
"answ2":"Michael Cera.",
},
{
"cat":"Mixed Bag",
"ques":"Wayne and Garth were not worthy of which musical artist after his concert in Milwaukee?",
"answ":"ALICE COOPER",
"answ2":"Alice Cooper.",
},
{
"cat":"Mixed Bag",
"ques":"What sport was Happy's first love in Happy Gilmore?",
"answ":"HOCKEY",
"answ3":"ICE HOCKEY",
"answ2":"Hockey.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the heroic wizard in The Lord of the Rings films?",
"answ":"GANDALF",
"answ2":"Gandalf.",
},
{
"cat":"Mixed Bag",
"ques":"What family film includes the characters: Jesse Hall, Guy, Averman, Adam Banks, Connie Moreau, Goldberg?",
"answ":"THE MIGHTY DUCKS",
"answ3":"MIGHTY DUCKS",
"answ2":"The Mighty Ducks.",
},
{
"cat":"Mixed Bag",
"ques":"What Ninja Turtle always wears orange bandanas?",
"answ":"MICHELANGELO",
"answ3":"MIKEY",
"answ2":"Michelangelo.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the green ghost in Ghostbusters?",
"answ":"SLIMER",
"answ2":"Slimer.",
},
{
"cat":"Mixed Bag",
"ques":"What movie revolves around a super family whose kids are named Violet, Dash and Jack Jack?",
"answ":"THE INCREDIBLES",
"answ3":"INCREDIBLES",
"answ2":"The Incredibles.",
},
{
"cat":"Mixed Bag",
"ques":"What city is Rocky from?",
"answ":"PHILADELPHIA",
"answ3":"PHILLY",
"answ2":"Philadelphia.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Lara Croft in 2001's Lara Croft Tomb Raider?",
"answ":"ANGELINA JOLIE",
"answ2":"Angelina Jolie.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the character played by Robert Shaw in Jaws?",
"answ":"QUINT",
"answ2":"Quint.",
},
{
"cat":"Mixed Bag",
"ques":"In what film will you find a news anchor named Veronica Corningstone?",
"answ":"ANCHORMAN",
"answ3":"ANCHORMAN THE LEGEND OF RON BURGUNDY",
"answ2":"Anchorman: The Legend of Ron Burgundy.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Pretty Woman?",
"answ":"GARY MARSHALL",
"answ3":"GARRY MARSHALL",
"answ2":"Garry Marshall.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Rachel Lapp, mother to the young Amish boy in Witness?",
"answ":"KELLY MCGILLIS",
"answ3":"KELLY MACGILLIS",
"answ2":"Kelly McGillis.",
},
{
"cat":"Mixed Bag",
"ques":"Luc Besson's The Messenger is about what historical figure?",
"answ":"JEANNE D'ARC",
"answ3":"JOAN OF ARC",
"answ2":"Joan of Arc.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the swashbuckling misfire Cutthroat Island?",
"answ":"RENNY HARLIN",
"answ2":"Renny Harlin.",
},
{
"cat":"Mixed Bag",
"ques":"Kate Hudson plays whom in Almost Famous?",
"answ":"PENNIE LANE",
"answ3":"PENNY LANE",
"answ2":"Pennie Lane.",
},
{
"cat":"Mixed Bag",
"ques":"Name the 4th film in the Die Hard franchise.",
"answ":"LIVE FREE OR DIE HARD",
"answ2":"Live Free or Die Hard.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Douglas Quaid in 2012's Total Recall?",
"answ":"COLIN FARRELL",
"answ3":"COLIN FARELL",
"answ2":"Colin Farrell.",
},
{
"cat":"Mixed Bag",
"ques":"What 90s film marked Whitney Houston's feature film debut?",
"answ":"THE BODYGUARD",
"answ3":"BODYGUARD",
"answ2":"The Bodyguard.",
},
{
"cat":"Mixed Bag",
"ques":"For what 2010 film did Jennifer Lawrence receive her first Oscar nomination?",
"answ":"WINTER'S BONE",
"answ3":"WINTERS BONE",
"answ2":"Winter's Bone.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the action heroine simply known as The Bride?",
"answ":"UMA THURMAN",
"answ2":"Uma Thurman.",
},
{
"cat":"Mixed Bag",
"ques":"In which 80s film will you find a coach named Norman Dale?",
"answ":"HOOSIERS",
"answ2":"Hoosiers.",
},
{
"cat":"Mixed Bag",
"ques":"In Red Dawn a group of high school students fight against invading Soviets. What do the students call themselves?",
"answ":"WOLVERINES",
"answ3":"THE WOLVERINES",
"answ2":"Wolverines.",
},
{
"cat":"Mixed Bag",
"ques":"Which U.S. state provides the setting for the film 50 First Dates?",
"answ":"HAWAII",
"answ2":"Hawaii.",
},
{
"cat":"Mixed Bag",
"ques":"Who composed the score for Tron Legacy?",
"answ":"DAFT PUNK",
"answ2":"Daft Punk.",
},
{
"cat":"Mixed Bag",
"ques":"What position did Geena Davis' character play in A League of Their Own?",
"answ":"CATCHER",
"answ2":"Catcher.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed the contemporary film noir classic Chinatown?",
"answ":"ROMAN POLANSKI",
"answ2":"Roman Polanski.",
},
{
"cat":"Mixed Bag",
"ques":"In Who Framed Roger Rabbit, what is the name of the all-animation city?",
"answ":"TOONTOWN",
"answ2":"Toontown.",
},
{
"cat":"Mixed Bag",
"ques":"The Green Mile is based on a story by whom?",
"answ":"STEPHEN KING",
"answ2":"Stephen King.",
},
{
"cat":"Mixed Bag",
"ques":"Who played James Bond in the film Thunderball?",
"answ":"SEAN CONNERY",
"answ2":"Sean Connery.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film with the following characters: Boon, Otter, Bluto, Pinto.",
"answ":"ANIMAL HOUSE",
"answ2":"Animal House.",
},
{
"cat":"Mixed Bag",
"ques":"What animated Disney film features the song 'Just Around The Riverbend'?",
"answ":"POCAHONTAS",
"answ2":"Pocahontas.",
},
{
"cat":"Mixed Bag",
"ques":"In which northeastern state is Shawshank State Prison located?",
"answ":"MAINE",
"answ2":"Maine.",
},
{
"cat":"Mixed Bag",
"ques":"Name the actress who stars in the following movies: The Crush, Excess Baggage, Clueless.",
"answ":"ALICIA SILVERSTONE",
"answ2":"Alicia Silverstone.",
},
{
"cat":"Mixed Bag",
"ques":"How many James Bond films starred Pierce Brosnan?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Wall Street: Money Never Sleeps?",
"answ":"OLIVER STONE",
"answ2":"Oliver Stone.",
},
{
"cat":"Mixed Bag",
"ques":"Which film features the following characters: Billy, Gale, Sidney, Dewey, Tatum, Cotton, Ghostface.",
"answ":"SCREAM",
"answ2":"Scream.",
},
{
"cat":"Mixed Bag",
"ques":"In The Fugitive, before being accused of killing his wife Richard Kimble is a prominent surgeon in what city?",
"answ":"CHICAGO",
"answ2":"Chicago.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film with the following characters: Tre, Ricky, Doughboy.",
"answ":"BOYS N THE HOOD",
"answ3":"BOYS IN THE HOOD",
"answ2":"Boyz n the Hood.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film with the following characters: Mitch Robbin, Phil Berquist, Curly Washburn.",
"answ":"CITY SLICKERS",
"answ2":"City Slickers.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the crab in The Little Mermaid?",
"answ":"SEBASTIAN",
"answ2":"Sebastian.",
},
{
"cat":"Mixed Bag",
"ques":"What is the subtitle of the second film in The Lord of the Rings trilogy?",
"answ":"THE TWO TOWERS",
"answ3":"TWO TOWERS",
"answ2":"The Two Towers.",
},
{
"cat":"Mixed Bag",
"ques":"Where did the Griswolds go in the fourth Vacation movie?",
"answ":"LAS VEGAS",
"answ2":"Las Vegas.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film with the characters: Fred, Go Go, Honey Lemon, Wasabi, Tadashi.",
"answ":"BIG HERO 6",
"answ3":"BIG HERO SIX",
"answ2":"Big Hero 6.",
},
{
"cat":"Mixed Bag",
"ques":"What classic sci-fi film has the line: 'Never give up, never surrender!'",
"answ":"GALAXY QUEST",
"answ2":"Galaxy Quest.",
},
{
"cat":"Mixed Bag",
"ques":"Rufus, the time-travelling character in Bill & Ted's Excellent Adventure was played by which comedian?",
"answ":"GEORGE CARLIN",
"answ2":"George Carlin.",
},
{
"cat":"Mixed Bag",
"ques":"Name the film starring the following actors: Bruce Willis, Samuel L. Jackson, Robin Wright.",
"answ":"UNBREAKABLE",
"answ2":"Unbreakable.",
},
{
"cat":"Mixed Bag",
"ques":"Which holiday movie features the following characters: Flick, Randy, Ralphie, Miss Shields, Santa Claus?",
"answ":"A CHRISTMAS STORY",
"answ2":"A Christmas Story.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Pink in Dazed and Confused?",
"answ":"JASON LONDON",
"answ2":"Jason London.",
},
{
"cat":"Mixed Bag",
"ques":"How many Mission Impossible films have been released?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
},
{
"cat":"Mixed Bag",
"ques":"Robert Altman directed this 1980 film starring Robin Williams and Shelley Duvall.",
"answ":"POPEYE",
"answ2":"Popeye.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Iron Man 2?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
},
{
"cat":"Mixed Bag",
"ques":"Who is the love interest of Michael Douglas in The American President?",
"answ":"ANNETTE BENING",
"answ3":"ANNETTE BENNING",
"answ2":"Annette Bening.",
},
{
"cat":"Mixed Bag",
"ques":"Kevin Kline played the US President in what Ivan Reitman comedy?",
"answ":"DAVE",
"answ2":"Dave.",
},
{
"cat":"Mixed Bag",
"ques":"Dustin Hoffman stars in what political comedy in which a war is fabricated to cover up a political sex scandal?",
"answ":"WAG THE DOG",
"answ2":"Wag the Dog.",
},
{
"cat":"Mixed Bag",
"ques":"For what movie did Philip Seymour Hoffman win his Best Actor Oscar?",
"answ":"CAPOTE",
"answ2":"Capote.",
},
{
"cat":"Mixed Bag",
"ques":"What 2007 thriller stars Robert Downey Jr, Mark Ruffalo and Jake Gyllenhaal?",
"answ":"ZODIAC",
"answ2":"Zodiac.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Bud Fox in Wall Street?",
"answ":"CHARLIE SHEEN",
"answ2":"Charlie Sheen.",
},
{
"cat":"Mixed Bag",
"ques":"George Clooney takes on a horde of vampires in what 1996 film?",
"answ":"FROM DUSK TILL DAWN",
"answ2":"From Dusk Till Dawn.",
},
{
"cat":"Mixed Bag",
"ques":"Who played the character of Jenny in 1994's Forrest Gump?",
"answ":"ROBIN WRIGHT",
"answ2":"Robin Wright.",
},
{
"cat":"Mixed Bag",
"ques":"What actress stars in the following films: Blow, Sahara, Vanilla Sky?",
"answ":"PENELOPE CRUZ",
"answ2":"Penélope Cruz.",
},
{
"cat":"Mixed Bag",
"ques":"In what year did They Live come out?",
"answ":"1988",
"answ2":"1988.",
},
{
"cat":"Mixed Bag",
"ques":"How many times has Sylvester Stallone played John Rambo in theatrical films?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
},
];
speedquestion001 = shuffle(speedquestion001);