var solo = [
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, Han grew up as an orphan on what planet?",
"answ":"CORELLIA",
"answ2":"Corellia.",
},
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, who voiced the serpent-like gang leader on Corellia, Lady Proxima?",
"answ":"LINDA HUNT",
"answ2":"Linda Hunt.",
},
{
"cat":"Solo",
"ques":"What is the only character mentioned by name in the film's opening title scroll?",
"answ":"LADY PROXIMA",
"answ2":"Lady Proxima.",
},
{
"cat":"Solo",
"ques":"When Han is thrown to 'the beast' in Solo, how many days has it been since the beast was last fed?",
"answ":"3",
"answ3":"3 DAYS",
"answ2":"3 days.",
},
{
"cat":"Solo",
"ques":"In Solo, Han says he's going to be what, the best in the galaxy?",
"answ":"A PILOT",
"answ3":"PILOT",
"answ2":"A pilot.",
},
{
"cat":"Solo",
"ques":"In Solo, Beckett tells Han that there's a big shot gangster putting together a team on what planet?",
"answ":"TATOOINE",
"answ2":"Tatooine.",
},
{
"cat":"Solo",
"ques":"In Solo, Qi'ra is worried that if they leave Corellia they can be sold to the Hutt Cartel or what other group?",
"answ":"CRIMSON DAWN",
"answ2":"Crimson Dawn.",
},
{
"cat":"Solo",
"ques":"On what planet does Solo: A Star Wars Story open?",
"answ":"CORELLIA",
"answ2":"Corellia.",
},
{
"cat":"Solo",
"ques":"Who are said to be competing for resources- food, medicine and hyperfuel according to the opening text of Solo?",
"answ":"CRIME SYNDICATES",
"answ2":"Crime syndicates.",
},
{
"cat":"Solo",
"ques":"Enfys Nest and the Cloud Riders make a final stand against Crimson Dawn on what planet?",
"answ":"SAVEREEN",
"answ2":"Savareen.",
},
{
"cat":"Solo",
"ques":"What creature first seen in The Phantom Menace is a tasty delicacy that Dryden Vos offers to his guests Beckett, Han and Chewie?",
"answ":"COLO CLAW FISH",
"answ3":"COLO CLAWFISH",
"answ2":"Colo claw fish.",
},
{
"cat":"Solo",
"ques":"What was the name of the criminal organization that Lady Proxima was the head of?",
"answ":"WHITE WORMS",
"answ3":"THE WHITE WORMS",
"answ2":"White Worms.",
},
{
"cat":"Solo",
"ques":"In Solo, during the heist on Vandor, who sacrifices themselves by blowing up the bridge?",
"answ":"VAL",
"answ2":"Val.",
},
{
"cat":"Solo",
"ques":"What is the name of the large worm leader of the gang Qi'ra and Han are trying to escape at the beginning of Solo?",
"answ":"LADY PROXIMA",
"answ2":"Lady Proxima.",
},
{
"cat":"Solo",
"ques":"What is Beckett hired to steal from Vandor-1 in Solo?",
"answ":"COAXIUM",
"answ2":"Coaxium.",
},
{
"cat":"Solo",
"ques":"In Solo, what is the name of the planet where they go to process the coaxium?",
"answ":"SAVAREEN",
"answ2":"Savareen.",
},
{
"cat":"Solo",
"ques":"On what planet do Han and Beckett have their final gunslinger duel, leading to Beckett's death?",
"answ":"SAVAREEN",
"answ2":"Savareen.",
},
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, Darth Maul tells Qi'ra to meet him on which planet?",
"answ":"DATHOMIR",
"answ3":"DATOMIR",
"answ2":"Dathomir.",
},
{
"cat":"Solo",
"ques":"After being expelled from the Flight Academy, we find Han is now a Mudtrooper caught in a battle on what planet?",
"answ":"MIMBAN",
"answ2":"Mimban.",
},
{
"cat":"Solo",
"ques":"In Solo's opening prologue, the final line of words reads: 'On these mean streats, a young man fights for survival, but yearns to ____'?",
"answ":"FLY AMONG THE STARS",
"answ2":"Fly among the stars.",
},
{
"cat":"Solo",
"ques":"We learn that Chewbacca is how old in Solo?",
"answ":"190",
"answ3":"190 YEARS",
"answ2":"190 years.",
},
{
"cat":"Solo",
"ques":"Who said: 'Assume everyone will betray you. And you will never be disappointed'?",
"answ":"TOBIAS BECKETT",
"answ3":"BECKETT",
"answ2":"Tobias Beckett.",
},
{
"cat":"Solo",
"ques":"Anthony Daniels has a cameo in Solo: A Star Wars Story, what is the name of his character?",
"answ":"TAK",
"answ2":"Tak.",
},
{
"cat":"Solo",
"ques":"Who stars as Enfys Nest in Solo: A Star Wars Story?",
"answ":"ERIN KELLYMAN",
"answ2":"Erin Kellyman.",
},
{
"cat":"Solo",
"ques":"Solo: A Star Wars Story was released in what year?",
"answ":"2018",
"answ2":"2018.",
},
{
"cat":"Solo",
"ques":"Who directed Solo: A Star Wars Story?",
"answ":"RON HOWARD",
"answ2":"Ron Howard.",
},
{
"cat":"Solo",
"ques":"Who composed the score for Solo: A Star Wars Story?",
"answ":"BRADFORD YOUNG",
"answ2":"Bradford Young.",
},
{
"cat":"Solo",
"ques":"Who stars as Han Solo in Solo: A Star Wars Story?",
"answ":"ALDEN EHRENREICH",
"answ2":"Alden Ehrenreich.",
},
{
"cat":"Solo",
"ques":"Who stars as Tobias Beckett in Solo: A Star Wars Story?",
"answ":"WOODY HARRELSON",
"answ2":"Woody Harrelson.",
},
{
"cat":"Solo",
"ques":"Who stars as Lando Calrissian in Solo: A Star Wars Story?",
"answ":"DONALD GLOVER",
"answ2":"Donald Glover.",
},
{
"cat":"Solo",
"ques":"In Solo, what is the name of Lando's droid companion and navigator?",
"answ":"L3-37",
"answ3":"L337",
"answ2":"L3-37.",
},
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, what is the name of Han's girlfriend played by Emilia Clarke?",
"answ":"QIRA",
"answ3":"QI'RA",
"answ2":"Qi'ra.",
},
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, who provided the voice of Darth Maul?",
"answ":"SAM WITWER",
"answ2":"Sam Witwer.",
},
{
"cat":"Solo",
"ques":"Who plays crime lord Dryden Voss in Solo?",
"answ":"PAUL BETTANY",
"answ2":"Paul Bettany.",
},
{
"cat":"Solo",
"ques":"Who plays Chewbacca in Solo?",
"answ":"JOONAS SUOTAMO",
"answ3":"JONAS SUOTAMO",
"answ2":"Joonas Suotamo.",
},
{
"cat":"Solo",
"ques":"What card game do Han and Lando play in Solo: A Star Wars Story?",
"answ":"SABACC",
"answ3":"SABAC",
"answ2":"Sabacc.",
},
{
"cat":"Solo",
"ques":"In Solo: A Star Wars Story, what did Han try and bribe the gate officer with?",
"answ":"COAXIUM",
"answ3":"HYPERFUEL",
"answ2":"Coaxium/hyperfuel.",
},
{
"cat":"Solo",
"ques":"In Solo, Enfys Nest leads a band of marauders with this group name.",
"answ":"CLOUD RIDERS",
"answ3":"CLOUDRIDERS",
"answ2":"Cloud-Riders.",
},
{
"cat":"Solo",
"ques":"In Solo, Han Solo meets Chewbacca on what muddy planet?",
"answ":"MIMBAN",
"answ2":"Mimban.",
},
{
"cat":"Solo",
"ques":"Who played Weazel, a pod race spectator in Phantom Menace that became a marauder in Solo: A Star Wars Story?",
"answ":"WARWICK DAVIS",
"answ2":"Warwick Davis.",
},
{
"cat":"Solo",
"ques":"In Solo, what type of stormtroopers protect the conveyex transport on the snowy planet of Vandor?",
"answ":"RANGE TROOPERS",
"answ3":"RANGE TROOPER",
"answ2":"Range troopers.",
},
];
var r2Q10 = [
{
"cat":"Solo",
"ques":"Who voiced Lando's droid and co-pilot in Solo: A Star Wars Story?",
"answ":"PHOEBE WALLER BRIDGE",
"answ2":"Phoebe Waller-Bridge.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Thandie Newton</button><button id=corop class=buttons003 onclick=qcor()>Phoebe Waller-Bridge</button><button id=incop3 class=buttons003 onclick=qinc()>Erin Kellyman</button><button id=incop4 class=buttons003 onclick=qinc()>Dee Tails</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, we learned from Lando that Beckett killed what bounty hunter?",
"answ":"AURRA SING",
"answ3":"AURA SING",
"answ2":"Aurra Sing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cad Bane</button><button id=corop class=buttons003 onclick=qcor()>Aurra Sing</button><button id=incop3 class=buttons003 onclick=qinc()>Galen Marek</button><button id=incop4 class=buttons003 onclick=qinc()>Savage Opress</button><br/>",
},
{
"cat":"Solo",
"ques":"What kind of ship was Beckett's crew looking to steal on Mimban?",
"answ":"AT HAULER",
"answ2":"AT-hauler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>CR90 corvette</button><button id=incop2 class=buttons003 onclick=qinc()>X-wing starfighter</button><button id=corop class=buttons003 onclick=qcor()>AT-hauler</button><button id=incop4 class=buttons003 onclick=qinc()>Heavy lifter</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of the Grindalid that brought Han and Qi'ra before Lady Proxima and later chased them in his landspeeder?",
"answ":"MOLOCH",
"answ2":"Moloch.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jabbat</button><button id=incop2 class=buttons003 onclick=qinc()>Rebolt</button><button id=corop class=buttons003 onclick=qcor()>Moloch</button><button id=incop4 class=buttons003 onclick=qinc()>Syke</button><br/>",
},
{
"cat":"Solo",
"ques":"Paul Bettany plays a high ranking crime boss of what crime syndicate?",
"answ":"CRIMSON DAWN",
"answ2":"Crimson Dawn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Black Sun</button><button id=incop2 class=buttons003 onclick=qinc()>Haxion Brood</button><button id=corop class=buttons003 onclick=qcor()>Crimson Dawn</button><button id=incop4 class=buttons003 onclick=qinc()>Pyke Syndicate</button><br/>",
},
{
"cat":"Solo",
"ques":"Using the same armor Lando later wears in Return of the Jedi, Tobias Beckett goes undercover on Kessel using what name?",
"answ":"TUUL",
"answ2":"Tuul.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Osak</button><button id=incop2 class=buttons003 onclick=qinc()>Fassio</button><button id=corop class=buttons003 onclick=qcor()>Tuul</button><button id=incop4 class=buttons003 onclick=qinc()>Aban</button><br/>",
},
{
"cat":"Solo",
"ques":"This style of combat, first made famous in a 1997 Star Wars video game, was used by Qi'ra on Kessel.",
"answ":"TERAS KASI",
"answ3":"TERÄS KÄSI",
"answ2":"Teräs Käsi.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Förräderi</button><button id=corop class=buttons003 onclick=qcor()>Teräs Käsi</button><button id=incop3 class=buttons003 onclick=qinc()>Nexu Grin</button><button id=incop4 class=buttons003 onclick=qinc()>Aryx Cerea</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of the Wookie slave that Chewie freed on Kessel and then in turn helped Chewie, Han and the gang to escape",
"answ":"SAGWA",
"answ2":"Sagwa.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gungi</button><button id=corop class=buttons003 onclick=qcor()>Sagwa</button><button id=incop3 class=buttons003 onclick=qinc()>Tarfful</button><button id=incop4 class=buttons003 onclick=qinc()>Arrworr</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, when we first meet Beckett, he's posing as an Imperial soldier, based on his uniform what is his rank, which Han points out to him?",
"answ":"CAPTAIN",
"answ2":"Captain.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>General</button><button id=corop class=buttons003 onclick=qcor()>Captain</button><button id=incop3 class=buttons003 onclick=qinc()>Sergeant</button><button id=incop4 class=buttons003 onclick=qinc()>Lieutenant</button><br/>",
},
{
"cat":"Solo",
"ques":"What actor makes a cameo appearance as Ralakili, a male human who ran droid fighting pits on Vandor?",
"answ":"CLINT HOWARD",
"answ2":"Clint Howard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Val Kilmer</button><button id=corop class=buttons003 onclick=qcor()>Clint Howard</button><button id=incop3 class=buttons003 onclick=qinc()>Tom Hulce</button><button id=incop4 class=buttons003 onclick=qinc()>Richard Dreyfuss</button><br/>",
},
{
"cat":"Solo",
"ques":"What member of the Cloud Riders goes on to join Saw Gerrera's Partisans?",
"answ":"BENTHIC",
"answ3":"TWO TUBES",
"answ2":"Benthic/Two Tubes.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Enfys Nest</button><button id=corop class=buttons003 onclick=qcor()>Benthic</button><button id=incop3 class=buttons003 onclick=qinc()>Weazel</button><button id=incop4 class=buttons003 onclick=qinc()>Chussido</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, what kind of speeder do Han and Qi'ra use to get away from Lady Proxima's syndicate?",
"answ":"MX 68",
"answ3":"MX68",
"answ2":"MX-68.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>YT-300</button><button id=corop class=buttons003 onclick=qcor()>MX-68</button><button id=incop3 class=buttons003 onclick=qinc()>AV-21</button><button id=incop4 class=buttons003 onclick=qinc()>VCX-100</button><br/>",
},
{
"cat":"Solo",
"ques":"Who voices Rio Durant the four-armed Ardennian pilot on Beckett's crew?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Taiki Waititi</button><button id=corop class=buttons003 onclick=qcor()>Jon Favreau</button><button id=incop3 class=buttons003 onclick=qinc()>Dave Filoni</button><button id=incop4 class=buttons003 onclick=qinc()>Paul Bettany</button><br/>",
},
{
"cat":"Solo",
"ques":"How many years did Han Solo serve in the Imperial Army before abandoning it to join Beckett's crew?",
"answ":"THREE",
"answ3":"3",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, what is the name of the leader of marauders that is always causing trouble for Han and crew throughout the film?",
"answ":"ENFYS NEST",
"answ3":"ENFIS NEST",
"answ2":"Enfys Nest.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Baroosh Pawk</button><button id=corop class=buttons003 onclick=qcor()>Enfys Nest</button><button id=incop3 class=buttons003 onclick=qinc()>Faddera Rabar</button><button id=incop4 class=buttons003 onclick=qinc()>Callixido Ryss</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of Rio Durrant's home planet?",
"answ":"ARDENNIA",
"answ2":"Ardennia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nubia</button><button id=corop class=buttons003 onclick=qcor()>Ardennia</button><button id=incop3 class=buttons003 onclick=qinc()>Jabiim</button><button id=incop4 class=buttons003 onclick=qinc()>Adoris</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of the character played by Thandie Newton?",
"answ":"VAL",
"answ2":"Val.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alis</button><button id=corop class=buttons003 onclick=qcor()>Val</button><button id=incop3 class=buttons003 onclick=qinc()>Kyrsta</button><button id=incop4 class=buttons003 onclick=qinc()>Andria</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, what rank of Imperial officer does Beckett impersonate when he first meets Han?",
"answ":"CAPTAIN",
"answ2":"Captain.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>General</button><button id=corop class=buttons003 onclick=qcor()>Captain</button><button id=incop3 class=buttons003 onclick=qinc()>Corporal</button><button id=incop4 class=buttons003 onclick=qinc()>Commander</button><br/>",
},
{
"cat":"Solo",
"ques":"Han boasted to Beckett and Val that he was boosting what kind of vehicle when he was 10 when trying to convince them to let him join their crew?",
"answ":"AV 21 LANDSPEEDER",
"answ3":"AV 21",
"answ2":"AV-21 landspeeder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>M-68 landspeeder</button><button id=corop class=buttons003 onclick=qcor()>AV-21 landspeeder</button><button id=incop3 class=buttons003 onclick=qinc()>X-34 landspeeder</button><button id=incop4 class=buttons003 onclick=qinc()>AB-1 landspeeder</button><br/>",
},
{
"cat":"Solo",
"ques":"During the train heist, Val used her vantage point to distract and fend off what?",
"answ":"VIPER DROIDS",
"answ2":"Viper Droids.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Viper Droids</button><button id=incop2 class=buttons003 onclick=qinc()>Stormtroopers</button><button id=incop3 class=buttons003 onclick=qinc()>TIE Fighters</button><button id=incop4 class=buttons003 onclick=qinc()>Cloud Riders</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of the precious hyperdrive fuel that Han continues trying to smuggle throughout the film?",
"answ":"COAXIUM",
"answ2":"Coaxium.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Coaxium</button><button id=incop2 class=buttons003 onclick=qinc()>Rhydonium</button><button id=incop3 class=buttons003 onclick=qinc()>Beryllium</button><button id=incop4 class=buttons003 onclick=qinc()>Deuterium</button><br/>",
},
{
"cat":"Solo",
"ques":"What does Han tell Lando his father did for a living?",
"answ":"HE WORKED IN A CEC PLANT",
"answ3":"WORKED IN A CEC PLANT",
"answ2":"He worked in a CEC plant.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Imperial officer</button><button id=incop2 class=buttons003 onclick=qinc()>Smuggler</button><button id=corop class=buttons003 onclick=qcor()>Worked in a CEC plant</button><button id=incop4 class=buttons003 onclick=qinc()>Navigator on a spice freighter</button><br/>",
},
{
"cat":"Solo",
"ques":"Who kills Dryden Vos at the end of the film?",
"answ":"QIRA",
"answ3":"QI'RA",
"answ2":"Qi'ra.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Han</button><button id=incop2 class=buttons003 onclick=qinc()>Beckett</button><button id=corop class=buttons003 onclick=qcor()>Qi'ra</button><button id=incop4 class=buttons003 onclick=qinc()>Chewie</button><br/>",
},
{
"cat":"Solo",
"ques":"Warwick Davis reprises his role as what character from The Phantom Menace in Solo?",
"answ":"WEAZEL",
"answ3":"WEASEL",
"answ2":"Weazel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dahar</button><button id=incop2 class=buttons003 onclick=qinc()>Eesmu</button><button id=corop class=buttons003 onclick=qcor()>Weazel</button><button id=incop4 class=buttons003 onclick=qinc()>Wanbo</button><br/>",
},
{
"cat":"Solo",
"ques":"On what planet do Han and crew attempt a Railcrawler conveyex transport robbery for coaxium?",
"answ":"VANDOR",
"answ2":"Vandor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Batuu</button><button id=incop2 class=buttons003 onclick=qinc()>Lothal</button><button id=corop class=buttons003 onclick=qcor()>Vandor</button><button id=incop4 class=buttons003 onclick=qinc()>Hirin</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, Qi'ra has a conversation with the hologram of what famous character?",
"answ":"DARTH MAUL",
"answ2":"Darth Maul.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Darth Vader</button><button id=incop2 class=buttons003 onclick=qinc()>Yoda</button><button id=corop class=buttons003 onclick=qcor()>Darth Maul</button><button id=incop4 class=buttons003 onclick=qinc()>Count Dooku</button><br/>",
},
{
"cat":"Solo",
"ques":"The two-tiered long train of armored cargo cars that Beckett's crew tries to hijack is called a what?",
"answ":"CONVEYEX",
"answ2":"Conveyex.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Railspeeder</button><button id=incop2 class=buttons003 onclick=qinc()>Bullet train</button><button id=corop class=buttons003 onclick=qcor()>Conveyex</button><button id=incop4 class=buttons003 onclick=qinc()>Construction crawler</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the name of the security attendant aboard Dryden Vos' yacht that confiscates guests' weapons as they board?",
"answ":"TOTH RA",
"answ3":"TODD RA",
"answ2":"Toht Ra.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chakobi Sanwright</button><button id=incop2 class=buttons003 onclick=qinc()>Regineer Teed</button><button id=corop class=buttons003 onclick=qcor()>Toht Ra</button><button id=incop4 class=buttons003 onclick=qinc()>Auromae Iselo</button><br/>",
},
{
"cat":"Solo",
"ques":"Who first leads Han and the Imperials in a ground assault on Mimban, before being killed in an explosion?",
"answ":"MAJOR STAZ",
"answ3":"STAZ",
"answ2":"Major Staz.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lieutenant Bolandin</button><button id=corop class=buttons003 onclick=qcor()>Major Staz</button><button id=incop3 class=buttons003 onclick=qinc()>Corporal Nodar</button><button id=incop4 class=buttons003 onclick=qinc()>Private Woslo</button><br/>",
},
{
"cat":"Solo",
"ques":"After 'A long time ago in a galaxy far, far away' what are the next 5 words to appear?",
"answ":"IT IS A LAWLESS TIME",
"answ2":"It is a lawless time.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Turmoil has engulfed the Republic</button><button id=corop class=buttons003 onclick=qcor()>It is a lawless time</button><button id=incop3 class=buttons003 onclick=qinc()>It is a dark time</button><button id=incop4 class=buttons003 onclick=qinc()>Crime syndicates compete for resources</button><br/>",
},
{
"cat":"Solo",
"ques":"What type of alien is Rio, the pilot for Beckett voiced by Jon Favreau in Solo?",
"answ":"ARDENNIAN",
"answ2":"Ardennian.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dug</button><button id=incop2 class=buttons003 onclick=qinc()>Mynock</button><button id=incop3 class=buttons003 onclick=qinc()>Clawdite</button><button id=corop class=buttons003 onclick=qcor()>Ardennian</button><br/>",
},
{
"cat":"Solo",
"ques":"What does Rio Durant say he wants to do when he retires?",
"answ":"OPEN A CANTINA",
"answ2":"Open a cantina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Move to Tatooine</button><button id=corop class=buttons003 onclick=qcor()>Open a cantina</button><button id=incop3 class=buttons003 onclick=qinc()>Start a family</button><button id=incop4 class=buttons003 onclick=qinc()>Open a casino</button><br/>",
},
{
"cat":"Solo",
"ques":"According to the opening text of Solo, what three things do Crime Syndicates fight for?",
"answ":"FOOD MEDICINE HYPERFUEL",
"answ3":"FOOD MEDICINE AND HYPERFUEL",
"answ2":"Food, medicine, hyperfuel.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guns, food, medicine</button><button id=corop class=buttons003 onclick=qcor()>Food, medicine, hyperfuel</button><button id=incop3 class=buttons003 onclick=qinc()>Money, food, honor</button><button id=incop4 class=buttons003 onclick=qinc()>Food, freedom, family</button><br/>",
},
{
"cat":"Solo",
"ques":"In Solo, Lando says he did a job for Dryden Voss involving which planet?",
"answ":"FELUCIA",
"answ2":"Felucia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mygeeto</button><button id=corop class=buttons003 onclick=qcor()>Felucia</button><button id=incop3 class=buttons003 onclick=qinc()>Polis Massa</button><button id=incop4 class=buttons003 onclick=qinc()>Cato Neimoidia</button><br/>",
},
{
"cat":"Solo",
"ques":"What is the nickname Dryden Voss uses to describe Han after learning that he, like Qi'ra, hails from Corellia?",
"answ":"FELLOW SCRUMRAT",
"answ3":"SCRUMRAT",
"answ2":"Scrumrat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Buckethead</button><button id=corop class=buttons003 onclick=qcor()>Scrumrat</button><button id=incop3 class=buttons003 onclick=qinc()>Leatherneck</button><button id=incop4 class=buttons003 onclick=qinc()>Dirtball</button><br/>",
},
];
r2Q10 = shuffle(r2Q10);
solo = shuffle(solo);