var vehiclesweapons = [
{
"cat":"Vehicles, weapons & tech",
"ques":"What does the acronym AT-ST stand for?",
"answ":"ALL TERRAIN SCOUT TRANSPORT",
"answ2":"All Terrain Scout Transport.",
},
{
"cat":"Vehicles, Weapons & tech",
"ques":"What is the color of the lightsaber used by Jedi Master Agen Kolar, during the Battle of Geonosis in Attack of the Clones?",
"answ":"GREEN",
"answ2":"Green.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"You'll see the SW-0608 Zeta-Class Heavy Cargo Shuttle in what film?",
"answ":"ROGUE ONE",
"answ2":"Rogue One.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In Rogue One, what type of TIE-fighters are used as modified troop transports at the Battle of Scarif?",
"answ":"TIE REAPER",
"answ3":"TIE REAPER ATTACK LANDER",
"answ2":"TIE Reaper.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In Attack of the Clones, what is the name of the speeder that Zam Wessell used to try and escape Obi-Wan and Anakin?",
"answ":"KORO 2 AIRSPEEDER",
"answ3":"KORO 2 ALL ENVIRONMENT EXODRIVE AIRSPEEDER",
"answ2":"Koro-2 all-environment exodrive airspeeder.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In The Phantom Menace, what is the class of battleship that was the Primary Capital ship for the Trade Federation's Trade Defense Force?",
"answ":"LUCREHULK CLASS",
"answ3":"LUCREHULK",
"answ2":"Lucrehulk class.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the melee weapon of choice of the Sand People?",
"answ":"GAFFI STICK",
"answ3":"GADERFFII",
"answ2":"Gaffi stick/Gaderffii.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the common name of the Rebel ship used to ram an Imperial Star Destroyer in Rogue One?",
"answ":"HAMMERHEAD CORVETTE",
"answ2":"Hammerhead corvette.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In The Clone Wars, what type of cables do the clones use to try and get up to the abandoned monastery on Teth?",
"answ":"ASCENSION CABLES",
"answ3":"ASCENSION",
"answ2":"Ascension cables.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What are the wings on an X-Wing also called?",
"answ":"S FOILS",
"answ2":"S-Foils.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In The Empire Strikes Back, what does C-3PO note has been damaged on the Falcon as they try and escape Hoth?",
"answ":"HYPERDRIVE MOTIVATOR",
"answ2":"Hyperdrive motivator.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the name of the shuttle that transported Han and crew to Endor?",
"answ":"TYDIRIUM",
"answ3":"TYDERIUM",
"answ2":"Tydirium.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What vehicle does Rey hope to use to escape the First Order on Jakku?",
"answ":"QUADJUMPER",
"answ3":"TUG B13",
"answ2":"Quadjumper/TUG-B13.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the center switch on a speeder bike used for?",
"answ":"JAMMING COMLINKS",
"answ3":"JAMMING COMMUNICATIONS",
"answ2":"Jamming comlinks.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"Who wields a thermal detonator in the original trilogy?",
"answ":"PRINCESS LEIA",
"answ3":"LEIA",
"answ2":"Princess Leia.",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In Revenge of the Sith, what is the specific name of the MagnaGuard combat droid used as General Grievous' bodyguards?",
"answ":"IG 100 MAGNAGUARD",
"answ3":"IG 100",
"answ2":"IG-100 MagnaGuard.",
},
];
var r2Q13 = [
{
"cat":"Vehicles, weapons & tech",
"ques":"What class of speed cruiser does Luke claim he used to bullseye womp rats in?",
"answ":"T 16 SKYHOPPER",
"answ3":"T 16",
"answ2":"T-16 skyhopper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>V-wing airspeeder</button><button id=incop2 class=buttons003 onclick=qinc()>T-23 skyhopper</button><button id=corop class=buttons003 onclick=qcor()>T-16 skyhopper</button><button id=incop4 class=buttons003 onclick=qinc()>MC75 cruiser</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"According to Obi-Wan, a lightsaber is 'Not as clumsy or ____ as a blaster.'",
"answ":"RANDOM",
"answ2":"Random.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ineffective</button><button id=incop2 class=buttons003 onclick=qinc()>Uncivilized</button><button id=corop class=buttons003 onclick=qcor()>Random</button><button id=incop4 class=buttons003 onclick=qinc()>Unconsidered</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the name of the first ship we see in Star Wars A New Hope?",
"answ":"CORELLIAN CORVETTE",
"answ3":"TANTIVE IV",
"answ2":"Tantive IV or Corellian corvette.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Millennium Falcon</button><button id=incop2 class=buttons003 onclick=qinc()>Devastator</button><button id=corop class=buttons003 onclick=qcor()>Tantive IV</button><button id=incop4 class=buttons003 onclick=qinc()>Endurance</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What word does Rey use to describe the dusty old Millennium Falcon in The Force Awakens?",
"answ":"GARBAGE",
"answ2":"Garbage.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Junk</button><button id=incop2 class=buttons003 onclick=qinc()>Trash</button><button id=incop3 class=buttons003 onclick=qinc()>Scrap Metal</button><button id=corop class=buttons003 onclick=qcor()>Garbage</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What was the callsign of Admiral Ackbar's ship?",
"answ":"HOME ONE",
"answ3":"HOME 1",
"answ2":"Home One.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Home One</button><button id=incop2 class=buttons003 onclick=qinc()>Home Three</button><button id=incop3 class=buttons003 onclick=qinc()>Home Six</button><button id=incop4 class=buttons003 onclick=qinc()>Home Two</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What color is the bolt of a stormtrooper's blaster, when it is set to stun?",
"answ":"BLUE",
"answ2":"Blue.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Red</button><button id=corop class=buttons003 onclick=qcor()>Blue</button><button id=incop3 class=buttons003 onclick=qinc()>Green</button><button id=incop4 class=buttons003 onclick=qinc()>Yellow</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What spacecraft delivers the fatal shot that blows up the second Death Star?",
"answ":"MILLENIUM FALCON",
"answ3":"MILLENIUM FALCON",
"answ2":"Millennium Falcon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Y-Wing Fighter</button><button id=incop2 class=buttons003 onclick=qinc()>B-Wing Fighter</button><button id=incop3 class=buttons003 onclick=qinc()>X-Wing Fighter</button><button id=corop class=buttons003 onclick=qcor()>Millennium Falcon</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"Various battle droids have a color that indicates their primary function. What color indicates a command battle droid?",
"answ":"YELLOW",
"answ2":"Yellow.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Yellow</button><button id=incop2 class=buttons003 onclick=qinc()>Red</button><button id=incop3 class=buttons003 onclick=qinc()>Blue</button><button id=incop4 class=buttons003 onclick=qinc()>Black</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What type of machines did Uncle Owen have installed on his farm's south ridge?",
"answ":"CONDENSERS",
"answ2":"Condensers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Condensers</button><button id=incop2 class=buttons003 onclick=qinc()>Moisture vaporators</button><button id=incop3 class=buttons003 onclick=qinc()>Regulators</button><button id=incop4 class=buttons003 onclick=qinc()>Air conditioners</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What vehicles are equipped with harpoons and tow cables?",
"answ":"SNOWSPEEDERS",
"answ3":"SNOWSPEEDER",
"answ2":"Snowspeeders.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Freerunners</button><button id=incop2 class=buttons003 onclick=qinc()>Landspeeders</button><button id=corop class=buttons003 onclick=qcor()>Snowspeeders</button><button id=incop4 class=buttons003 onclick=qinc()>Skyhoppers</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"The number 3263827 corresponds to what in Star Wars?",
"answ":"GARBAGE COMPACTOR",
"answ3":"TRASH COMPACTOR",
"answ2":"Garbage Compactor.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tractor Beam</button><button id=incop2 class=buttons003 onclick=qinc()>Skyhopper</button><button id=corop class=buttons003 onclick=qcor()>Garbage Compactor</button><button id=incop4 class=buttons003 onclick=qinc()>Starfighter</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In the classic trilogy, how many characters ignite a lightsaber?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What Star Destroyer was pursuing Han when the Falcon lost its main rear deflector shield in The Empire Strikes Back?",
"answ":"THE AVENGER",
"answ3":"AVENGER",
"answ2":"The Avenger.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Eviscerator</button><button id=incop2 class=buttons003 onclick=qinc()>The Finalizer</button><button id=corop class=buttons003 onclick=qcor()>The Avenger</button><button id=incop4 class=buttons003 onclick=qinc()>The Inflictor</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the name of the Nebulon-B escort frigate that Luke gets his wounds tended to on, following his fight with Vader, in Empire Strikes Back?",
"answ":"REDEMPTION",
"answ2":"Redemption.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Vengeance</button><button id=incop2 class=buttons003 onclick=qinc()>Leviathan</button><button id=incop3 class=buttons003 onclick=qinc()>Liquidator</button><button id=corop class=buttons003 onclick=qcor()>Redemption</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What is the name of Jango Fett's ship?",
"answ":"SLAVE ONE",
"answ3":"SLAVE I",
"answ2":"Slave I.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Retaliator</button><button id=incop2 class=buttons003 onclick=qinc()>Optima</button><button id=incop3 class=buttons003 onclick=qinc()>Home One</button><button id=corop class=buttons003 onclick=qcor()>Slave I</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"How many movies mention a Death Star in the opening crawl?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>0</button><button id=incop2 class=buttons003 onclick=qinc()>1</button><button id=incop3 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In The Last Jedi, the Resistance is forced to use what type of beat up ships to fight the approaching First Order?",
"answ":"SKI SPEEDERS",
"answ3":"SKI SPEEDER",
"answ2":"Ski Speeders.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dune Hoppers</button><button id=incop2 class=buttons003 onclick=qinc()>X-wings</button><button id=incop3 class=buttons003 onclick=qinc()>Land Speeders</button><button id=corop class=buttons003 onclick=qcor()>Ski Speeders</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"In The Last Jedi, what did Leia give to Rey so that she could find her way back to the Resistance?",
"answ":"CLOAKED BINARY BEACON",
"answ3":"S THREAD TRANSMITTER BRACELET",
"answ2":"Cloaked binary beacon/S-thread transmitter bracelet.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sith Wayfinder</button><button id=incop2 class=buttons003 onclick=qinc()>Transponder Ring</button><button id=incop3 class=buttons003 onclick=qinc()>Magnograsp transmitter</button><button id=corop class=buttons003 onclick=qcor()>Cloaked binary beacon</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"Which Rogue One character uses the MWC-35C Repeating Cannon as their signature weapon?",
"answ":"BAZE MALBUS",
"answ2":"Baze Malbus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jyn Erso</button><button id=incop2 class=buttons003 onclick=qinc()>Cassian Endor</button><button id=incop3 class=buttons003 onclick=qinc()>Chirrut Imwe</button><button id=corop class=buttons003 onclick=qcor()>Baze Malbus</button><br/>",
},
{
"cat":"Vehicles, weapons & tech",
"ques":"What substance can sustain a person in perfect hibernation?",
"answ":"CARBONITE",
"answ2":"Carbonite.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tyridium</button><button id=incop2 class=buttons003 onclick=qinc()>Potassium</button><button id=incop3 class=buttons003 onclick=qinc()>Hydrogen</button><button id=corop class=buttons003 onclick=qcor()>Carbonite</button><br/>",
},
];
r2Q13 = shuffle(r2Q13);
vehiclesweapons = shuffle(vehiclesweapons);