var fivepointer001 = [
{
"cat":"Droids",
"ques":"What hoop-wheeled robot missile launcher is employed against the Clone Army on Geonosis?",
"answ":"HAILFIRE DROID",
"answ2":"Hailfire droid.",
},
{
"cat":"Droids",
"ques":"What is the name of the droid that can be seen torturing a gonk droid in Return of the Jedi?",
"answ":"8D8",
"answ2":"8D8.",
},
{
"cat":"Droids",
"ques":"In The Phantom Menace, what protocol droid attends to Qui-Gon and Obi-Wan on the Trade Federation ship and speaks with a female voice?",
"answ":"TC14",
"answ3":"TC 14",
"answ2":"TC-14.",
},
{
"cat":"Mixed Bag",
"ques":"Who is the only actor to ever receive an Oscar nomination for a performance in a Star Wars film?",
"answ":"ALEC GUINNESS",
"answ2":"Alec Guinness.",
},
{
"cat":"Mixed Bag",
"ques":"The term 'nerf herder' was introduced in what Star Wars film?",
"answ":"THE EMPIRE STRIKES BACK",
"answ3":"EMPIRE STRIKES BACK",
"answ2":"The Empire Strikes Back.",
},
{
"cat":"Mixed Bag",
"ques":"How many towers does the Jedi Temple have on Coruscant?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
},
{
"cat":"Heroes & Villains",
"ques":"According to Yoda, what 'matters not'?",
"answ":"SIZE",
"answ2":"Size.",
},
{
"cat":"Heroes & Villains",
"ques":"Before becoming Darth Tyranus, Dooku left the Jedi Order and reclaimed his birthright of Count for which planet?",
"answ":"SERENNO",
"answ2":"Serenno.",
},
{
"cat":"Heroes & Villains",
"ques":"According to Yoda, what does a Jedi never use the Force for?",
"answ":"ATTACK",
"answ3":"ATTACKING",
"answ2":"Attack.",
},
{
"cat":"Heroes & Villains",
"ques":"Who was Darth Vader referring to when he said: 'Now his failure is complete'?",
"answ":"OBI WAN KENOBI",
"answ3":"OBI WAN",
"answ2":"Obi-Wan Kenobi.",
},
{
"cat":"Creatures & Aliens",
"ques":"Lo-Grey is which type of creature in Star Wars canon?",
"answ":"EWOK",
"answ2":"Ewok.",
},
{
"cat":"Clone Wars",
"ques":"Ziro's assassin droid failed his mission to where?",
"answ":"YOUT 12",
"answ3":"TWELFTH MOON OF YOUT",
"answ2":"Twelfth moon of Yout/Yout 12.",
},
{
"cat":"Clone Wars",
"ques":"Who was the general that led the droid army in the opening battle on Christophsis?",
"answ":"WHORM LOATHSOM",
"answ3":"GENERAL LOATHSOM",
"answ2":"Whorm Loathsom.",
},
{
"cat":"Clone Wars",
"ques":"In The Clone Wars, we learn that Ziro the Hutt is the Master of the Hutt Clan on how many systems?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
},
{
"cat":"Mixed Bag",
"ques":"Producer Robert Watts has a cameo as an Imperial in what film?",
"answ":"RETURN OF THE JEDI",
"answ3":"STAR WARS EPISODE VI RETURN OF THE JEDI",
"answ2":"Return of the Jedi.",
},
{
"cat":"Mixed Bag",
"ques":"Taun We and Lama Su are from what planet?",
"answ":"KAMINO",
"answ2":"Kamino.",
},
{
"cat":"A New Hope",
"ques":"According to Luke, what did Uncle Owen tell him that Anakin's profession was?",
"answ":"NAVIGATOR ON A SPICE FREIGHTER",
"answ3":"NAVIGATOR",
"answ2":"Navigator on a spice freighter.",
},
{
"cat":"A New Hope",
"ques":"In A New Hope, according to Gold Five's estimate, how many guns line the first Death Star's trench?",
"answ":"TWENTY",
"answ3":"20",
"answ2":"20.",
},
{
"cat":"A New Hope",
"ques":"What is the first line Luke says to Leia in A New Hope?",
"answ":"HUH OH THE UNIFORM",
"answ3":"HUH? OH THE UNIFORM",
"answ2":"Huh? Oh the uniform.",
},
{
"cat":"A New Hope",
"ques":"In A New Hope, Princess Leia is being held in detention block AA-23, on what level?",
"answ":"LEVEL 5",
"answ3":"5",
"answ2":"Level 5.",
},
{
"cat":"Revenge of the Sith",
"ques":"What Jedi was killed by Clone Troopers on Felucia?",
"answ":"AAYLA SECURA",
"answ3":"AYLA SECURA",
"answ2":"Aayla Secura.",
},
{
"cat":"Revenge of the Sith",
"ques":"In Revenge of the Sith, while Palpatine is watching the theatre performance, which Umbaran is sitting next to him that leaves when Anakin arrives?",
"answ":"SLY MOORE",
"answ2":"Sly Moore.",
},
{
"cat":"Attack of the Clones",
"ques":"What was the name of the decoy that was killed in the first assassination attempt we see on Senator Amidala?",
"answ":"CORDE",
"answ2":"Cordé.",
},
{
"cat":"Attack of the Clones",
"ques":"What kind of poisonous creatures were used to try and assassinate Padmé Amidala in Attack of the Clones?",
"answ":"KOHUNS",
"answ3":"KOUHUNS",
"answ2":"Kouhuns.",
},
{
"cat":"The Phantom Menace",
"ques":"Name the character Sofia Coppola found herself playing after she paid a visit to the set of Episode I?",
"answ":"SACHE",
"answ2":"Saché.",
},
{
"cat":"The Phantom Menace",
"ques":"What is the name of the Chargrian male politician that served under both Chancellor Valorum and Palpatine?",
"answ":"MAS AMEDDA",
"answ3":"MAS AMEDA",
"answ2":"Mas Amedda.",
},
{
"cat":"The Phantom Menace",
"ques":"What was the name of the droid control ship destroyed by Anakin Skywalker?",
"answ":"VUUTUN PALAA",
"answ3":"VUUTUN PALA",
"answ2":"Vuutun Palaa.",
},
{
"cat":"The Phantom Menace",
"ques":"Who is introduced as a two time winner of the Boonta Eve Classic before the race begins?",
"answ":"BOLES ROOR",
"answ2":"Boles Roor.",
},
{
"cat":"The Phantom Menace",
"ques":"What is the name of the Neimoidian captain of the Trade Federation Droid Control Ship? The one Sidious 'didn't want in his sight again.'",
"answ":"DAULTAY DOFINE",
"answ3":"DAULTEY DOFINE",
"answ2":"Daultay Dofine.",
},
{
"cat":"The Phantom Menace",
"ques":"From what world is the podracer Ben Quadinaros from?",
"answ":"TUND",
"answ2":"Tund.",
},
{
"cat":"Attack of the Clones",
"ques":"What is the name of the librarian in the Jedi Archives?",
"answ":"JOCASTA NU",
"answ2":"Jocasta Nu.",
},
{
"cat":"Filming Locations",
"ques":"In what Central American country were the exterior shots of Yavin's moon filmed?",
"answ":"GUATEMALA",
"answ2":"Guatemala.",
},
{
"cat":"Return of the Jedi",
"ques":"Deep Roy played a flute-playing member of the Max Rebo Band. What is his name?",
"answ":"DROOPY MCCOOL",
"answ2":"Droopy McCool.",
},
{
"cat":"Return of the Jedi",
"ques":"In Return of the Jedi, Admiral Ackbar tells Green group to stay close to what holding sector?",
"answ":"MV 7",
"answ3":"MV7",
"answ2":"MV-7.",
},
{
"cat":"Return of the Jedi",
"ques":"What class of ship is the Home One?",
"answ":"MC80 STAR CRUISER",
"answ3":"MC80A STAR CRUISER",
"answ2":"MC80 Star Cruiser.",
},
{
"cat":"Return of the Jedi",
"ques":"Where on Tatooine is the Sarlacc located?",
"answ":"PIT OF CARKOON",
"answ3":"PIT OF CARCOON",
"answ2":"Pit of Carkoon.",
},
{
"cat":"Revenge of the Sith",
"ques":"Name the Jedi killed while riding a speeder bike on the planet Saleucami in Revenge of the Sith.",
"answ":"STASS ALLIE",
"answ2":"Stass Allie.",
},
{
"cat":"Revenge of the Sith",
"ques":"In Revenge of the Sith, Obi-Wan tells Anakin that Jedi Master Quinlan Vos has just moved his Clone Troopers to where?",
"answ":"BOZ PITY",
"answ2":"Boz Pity.",
},
{
"cat":"Revenge of the Sith",
"ques":"What is the name of the clone commander in charge of the troops, under the leadership of the Jedi Knight Aayla Secura?",
"answ":"CC 5052",
"answ3":"BLY",
"answ2":"CC-5052/Bly.",
},
{
"cat":"Rogue One",
"ques":"Which planet featured in the film Rogue One is said to be 'a holy land for the Jedi'?",
"answ":"JEDHA",
"answ2":"Jedha.",
},
{
"cat":"The Empire Strikes Back",
"ques":"In the Battle of Hoth, the snowspeeders fly in what attack pattern?",
"answ":"DELTA",
"answ3":"ATTACK PATTERN DELTA",
"answ2":"Attack Pattern Delta.",
},
{
"cat":"The Empire Strikes Back",
"ques":"What type of blaster does Boba Fett use in the film?",
"answ":"EE 3 CARBINE RIFLE",
"answ3":"EE 3 BLASTER CARBINE",
"answ2":"EE-3 blaster carbine.",
},
{
"cat":"The Empire Strikes Back",
"ques":"What is the name of the character portrayed by John Ratzenberger in The Empire Strikes Back?",
"answ":"BREN DERLIN",
"answ3":"MAJOR BREN DERLIN",
"answ2":"Bren Derlin.",
},
{
"cat":"The Empire Strikes Back",
"ques":"In The Empire Strikes Back, who barked the order 'Shields up!' just before the Falcon buzzed the Star Destroyer's bridge?",
"answ":"CAPTAIN NEEDA",
"answ3":"LORTH NEEDA",
"answ2":"Captain Needa.",
},
{
"cat":"The Empire Strikes Back",
"ques":"In The Empire Strikes Back, when The Falcon grasps on to an Imperial Cruiser to avoid detection, what solor system are they all in?",
"answ":"ANOAT SYSTEM",
"answ3":"THE ANOAT SYSTEM",
"answ2":"Anoat system.",
},
{
"cat":"The Force Awakens",
"ques":"After escaping Jakku, where did Rey say that she would drop Finn and BB-8 off?",
"answ":"PONEMAH TERMINAL",
"answ3":"PONEMAH",
"answ2":"Ponemah Terminal.",
},
{
"cat":"The Force Awakens",
"ques":"Name the character played by actor Simon Pegg.",
"answ":"UNKAR PLUTT",
"answ3":"UNKAR PLUT",
"answ2":"Unkar Plutt.",
},
{
"cat":"The Force Awakens",
"ques":"After escaping Jakku, while Rey was fixing the Falcon, what was the tool that she asked for AFTER asking for the Harris wrench?",
"answ":"PILEX DRIVER",
"answ3":"PILEX BIT DRIVER",
"answ2":"Pilex driver.",
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the blue communications droid that shares control of the Resistance's command center droid operations with C-3PO?",
"answ":"PZ4CO",
"answ3":"PZ 4CO",
"answ2":"PZ-4CO.",
},
{
"cat":"Attack of the Clones",
"ques":"What is the name of Obi-Wan Kenobi's red astromech droid in Attack of the Clones?",
"answ":"R4 P17",
"answ3":"R4P17",
"answ2":"R4-P17.",
},
{
"cat":"Solo",
"ques":"What model of landspeeder did Han steal on Corellia that he used for his escape with Qi-ra?",
"answ":"M 68",
"answ3":"M68",
"answ2":"M-68.",
},
{
"cat":"Solo",
"ques":"In addition to Bossk, who did Val want to recruit for the train heist instead of Han and Chewie?",
"answ":"THE XAN SISTERS",
"answ3":"XAN SISTERS",
"answ2":"The Xan sisters.",
},
{
"cat":"Solo",
"ques":"What planet did Beckett always say he wanted to go back to in Solo: A Star Wars Story?",
"answ":"GLEE ANSELM",
"answ2":"Glee Anselm.",
},
{
"cat":"The Last Jedi",
"ques":"In The Last Jedi, Luke takes a big gulp of fresh green milk from what Ach-To island marine mammal?",
"answ":"THALA SIREN",
"answ3":"THALASIREN",
"answ2":"Thala-siren.",
},
{
"cat":"The Last Jedi",
"ques":"The Last Jedi opens with a massive space battle in which Resistance bombers try to take out what kind of massive First Order ship?",
"answ":"DREADNOUGHT",
"answ2":"Dreadnought.",
},
{
"cat":"The Last Jedi",
"ques":"Rose and Finn were arrested for a parking violation on Canto Bight. What code number did that violation pertain to?",
"answ":"27B/6",
"answ3":"27B 6",
"answ2":"27B/6.",
},
{
"cat":"The Last Jedi",
"ques":"In The Last Jedi, Poe says that Holdo was famous for what battle?",
"answ":"BATTLE OF CHYRON BELT",
"answ3":"BATTLE OF KYRON BELT",
"answ2":"Battle of Chyron Belt.",
},
{
"cat":"The Phantom Menace",
"ques":"In Episode I, what is the name of the Neimoidian Trade Federation Senator that denied Amidala's claim of invasion of Naboo at the senate hearing?",
"answ":"LOTT DOD",
"answ3":"LOT DOD",
"answ2":"Lott Dod.",
},
{
"cat":"Rise of Skywalker",
"ques":"In Rise of Skywalker, Lando tells Jannah he is from what system?",
"answ":"GOLD SYSTEM",
"answ3":"THE GOLD SYSTEM",
"answ2":"Gold system.",
},
{
"cat":"The Last Jedi",
"ques":"What was the last name of the First Order captain that was General Hux's right hand?",
"answ":"CAPTAIN PEAVEY",
"answ3":"PEAVEY",
"answ2":"Peavey.",
},
{
"cat":"Villains",
"ques":"What is the name of the Imperial general who informs Tarkin that there is a Rebel incursion on Scariff in Rogue One?",
"answ":"ROMODI",
"answ3":"GENERAL ROMODI",
"answ2":"General Romodi.",
},
{
"cat":"Who said it?",
"ques":"Two characters said the famous line 'I have a bad feeling about this' in Episode IV. Han Solo and ____",
"answ":"LUKE",
"answ3":"LUKE SKYWALKER",
"answ2":"Luke Skywalker.",
},
{
"cat":"Who said it?",
"ques":"In The Last Jedi, what are the two dying words of the captain of the Anodyne before The First Order destroys it?",
"answ":"GODSPEED REBELS",
"answ2":"Godspeed rebels.",
},
{
"cat":"Who said it?",
"ques":"In The Empire Strikes Back, who said: 'Get a shuttle ready. I shall assume full responsibility for losing them and apologize to Lord Vader'?",
"answ":"LORTH NEEDA",
"answ3":"CAPTAIN NEEDA",
"answ2":"Captain Needa.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'Greed can be a powerful ally.'?",
"answ":"QUI GON JINN",
"answ3":"QUI GON",
"answ2":"Qui-Gon Jinn.",
},
];
fivepointer001 = shuffle(fivepointer001);