var episodevii = [
{
"cat":"The Force Awakens",
"ques":"Which system that is home to the New Republic is destroyed by the Starkiller Base?",
"answ":"HOSNIAN",
"answ3":"HOSNIAN SYSTEM",
"answ2":"Hosnian system.",
},
{
"cat":"The Force Awakens",
"ques":"Name the character played by actor Simon Pegg in The Force Awakens.",
"answ":"UNKAR PLUTT",
"answ3":"UNKAR PLUT",
"answ2":"Unkar Plutt.",
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the Tasu Leech-led criminal organization seen confronting Han about debts he owes to them in Episode VII?",
"answ":"KANJIKLUB",
"answ2":"Kanjiklub.",
},
{
"cat":"The Force Awakens",
"ques":"Who gives FN-2187 the new name of Finn because he refused to use the First Order designation?",
"answ":"POE DAMERON",
"answ2":"Poe Dameron.",
},
{
"cat":"The Force Awakens",
"ques":"How many Oscars was The Force Awakens nominated for?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Harriet Walter portrays this doctor with the Resistance who notably attended both Chewbacca and Finn after they were wounded?",
"answ":"HARTER KALONIA",
"answ3":"DR KALONIA",
"answ2":"Dr. Kalonia.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Kylo Ren tells Hux that his soldiers are obviously skilled at committing 'what'?",
"answ":"HIGH TREASON",
"answ2":"High treason.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what is the proper name of the self-rising portion bread that Rey is seen eating?",
"answ":"POLYSTARCH",
"answ3":"POLYSTARCH PORTION BREAD",
"answ2":"Polystarch.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, after a TIE fighter blasts the cannon on the Millenium Falcon, Finn says that it's now stuck in what position?",
"answ":"FORWARD POSITION",
"answ3":"FORWARD",
"answ2":"Forward position.",
},
{
"cat":"The Force Awakens",
"ques":"The remnants of what type of vehicle does Rey live in while on Jakku?",
"answ":"AT AT",
"answ2":"AT-AT.",
},
{
"cat":"The Force Awakens",
"ques":"Which actress plays the resistance pilot Jess Pava?",
"answ":"JESSICA HENWICK",
"answ2":"Jessica Henwick.",
},
{
"cat":"The Force Awakens",
"ques":"Rey says: 'I didn't know there was this much green in the whole galaxy' after she arrives on what planet?",
"answ":"TAKODANA",
"answ2":"Takodana.",
},
{
"cat":"The Force Awakens",
"ques":"What type of staff do we first see Rey wielding on Jakku?",
"answ":"QUARTERSTAFF",
"answ3":"QUARTER STAFF",
"answ2":"Quarterstaff.",
},
{
"cat":"The Force Awakens",
"ques":"According to the opening crawl of The Force Awakens, The First Order will not rest until Skywalker, the last Jedi has been what?",
"answ":"DESTROYED",
"answ2":"Destroyed.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Han Solo tells Finn that women always figure out what?",
"answ":"THE TRUTH",
"answ3":"TRUTH",
"answ2":"The truth.",
},
{
"cat":"The Force Awakens",
"ques":"What does Supreme Leader Snoke warn will happen in the galaxy if Luke Skywalker returns?",
"answ":"NEW JEDI WILL RISE",
"answ3":"THE NEW JEDI WILL RISE",
"answ2":"New Jedi will rise.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, according to Finn stormtrooper masks filter out what?",
"answ":"SMOKE",
"answ3":"SMOKE NOT TOXINS",
"answ2":"Smoke.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what type of tape does Rey need while trying to repair the Falcon?",
"answ":"BONDING TAPE",
"answ3":"BONDING",
"answ2":"Bonding tape.",
},
{
"cat":"The Force Awakens",
"ques":"Performer Mike Quinn returned to the Star Wars franchise to portray which character in The Force Awakens?",
"answ":"NIEN NUNB",
"answ2":"Nien Nunb.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what insult does Han use when saying someone put a compressor on the ignition line?",
"answ":"MOOF MILKER",
"answ3":"SOME MOOF MILKER",
"answ2":"Moof-milker.",
},
{
"cat":"The Force Awakens",
"ques":"Which actor cameos as FN-1824, who Rey uses the Force on to get out of her restraints, while on Starkiller Base in The Force Awakens?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Lor San Tekka says to Poe that Leia is not a General to him, but she is what?",
"answ":"ROYALTY",
"answ2":"Royalty.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, when Rey meets BB-8 she tells him to stay away from what in the North?",
"answ":"THE SINKING FIELDS",
"answ3":"SINKING FIELDS",
"answ2":"The Sinking Fields.",
},
{
"cat":"The Force Awakens",
"ques":"While Finn is trying to put bandages on Chewbacca, he asks for help, calling Chewie a what to everyone listening?",
"answ":"GIANT HAIRY THING",
"answ2":"Giant hairy thing.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Lor San Tekka tells Kylo that he cannot deny the truth that is his what?",
"answ":"FAMILY",
"answ2":"Family.",
},
{
"cat":"The Force Awakens",
"ques":"Name the Resistance pilot that ran an off-screen reconnaissance mission over Starkiller Base in The Force Awakens.",
"answ":"TEMMIN WEXLEY",
"answ3":"SNAP WEXLEY",
"answ2":"Temmin Wexley/Snap Wexley.",
},
{
"cat":"The Force Awakens",
"ques":"Who says to Han: 'Your game is old. There's no one in the galaxy left for you to swindle.'?",
"answ":"BALA TIK",
"answ2":"Bala-Tik.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who first ignites Luke's lightsaber?",
"answ":"FINN",
"answ2":"Finn.",
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the junk trader on Jakku that Rey frequently does business with?",
"answ":"UNKAR PLUTT",
"answ3":"UNKAR PLUT",
"answ2":"Unkar Plutt.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what rank does Leia hold with the Resistance as we learn from the film's opening crawl?",
"answ":"GENERAL",
"answ2":"General.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, where was the tie fighter stolen by Finn and Poe projected to crash?",
"answ":"GOAZON BADLANDS",
"answ3":"GOAZON",
"answ2":"Goazon Badlands.",
},
{
"cat":"The Force Awakens",
"ques":"Who is the proprietor of the tavern that Han Solo, Rey and Finn visit in The Force Awakens?",
"answ":"MAZ KANATA",
"answ2":"Maz Kanata.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who says to Kyle Ren: 'I won't have you question my methods.'?",
"answ":"GENERAL HUX",
"answ3":"HUX",
"answ2":"General Hux.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who says: 'That's not how the Force works!'?",
"answ":"HAN SOLO",
"answ3":"SOLO",
"answ2":"Han Solo.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what character gives Poe Dameron the map to Luke Skywalker at the film's opening?",
"answ":"LOR SAN TEKKA",
"answ2":"Lor San Tekka.",
},
{
"cat":"The Force Awakens",
"ques":"Who convinces Supreme Leader Snoke that the Starkiller Base weapon should be used?",
"answ":"HUX",
"answ3":"GENERAL HUX",
"answ2":"General Hux.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who plays Resistance pilot Snap Wexley?",
"answ":"GREG GRUNBERG",
"answ2":"Greg Grunberg.",
},
{
"cat":"The Force Awakens",
"ques":"At the end of The Force Awakens, besides R2 who travels to Ach-To with Rey to find Luke?",
"answ":"CHEWIE",
"answ3":"CHEWBACCA",
"answ2":"Chewbacca.",
},
{
"cat":"The Force Awakens",
"ques":"Who plays senior officer of the Resistance, Admiral Statura, in The Force Awakens?",
"answ":"KEN LEUNG",
"answ2":"Ken Leung.",
},
{
"cat":"The Force Awakens",
"ques":"To whom does Poe Dameron say: 'The Resistance will not be intimidated by you!'?",
"answ":"KYLO REN",
"answ2":"Kylo Ren.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, this venerable actor plays Church of the Force member Lor San Tekka.",
"answ":"MAX VON SYDOW",
"answ2":"Max von Sydow.",
},
{
"cat":"The Force Awakens",
"ques":"How many characters are mentioned by name in the opening crawl of The Force Awakens?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, how many parsecs does Rey mistakenly think the Millennium Falcon made the Kessel Run in?",
"answ":"14",
"answ3":"14 PARSECS",
"answ2":"14 parsecs.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Maz Kanata says whose shadow is spreading across the galaxy?",
"answ":"THE FIRST ORDER",
"answ3":"FIRST ORDER",
"answ2":"The First Order.",
},
{
"cat":"The Force Awakens",
"ques":"Consisting of four words, what was the first sentence in the opening crawl for The Force Awakens?",
"answ":"LUKE SKYWALKER HAS VANISHED",
"answ2":"Luke Skywalker has vanished.",
},
{
"cat":"The Force Awakens",
"ques":"Who plays Supreme Leader Snoke?",
"answ":"ANDY SERKIS",
"answ2":"Andy Serkis.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who gave Finn Luke's old lightsaber?",
"answ":"MAZ KANATA",
"answ2":"Maz Kanata.",
},
{
"cat":"The Force Awakens",
"ques":"How many TIE fighters pursue Rey and Finn in the Millennium Falcon through the Graveyard of Giants on Jakku?",
"answ":"TWO",
"answ3":"2",
"answ2":"2.",
},
{
"cat":"The Force Awakens",
"ques":"Who played Rey in The Force Awakens?",
"answ":"DAISY RIDLEY",
"answ2":"Daisy Ridley.",
},
{
"cat":"The Force Awakens",
"ques":"What famous veteran of the Galactic Civil War came out of retirement to join General Leia's Resistance?",
"answ":"ACKBAR",
"answ3":"ADMIRAL ACKBAR",
"answ2":"Admiral Ackbar.",
},
{
"cat":"The Force Awakens",
"ques":"What was the first location that Rey saw in her vision after touching the lightsaber she found at Maz's castle?",
"answ":"CLOUD CITY",
"answ2":"Cloud City.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, which character physically disables the shields on Starkiller Base?",
"answ":"CAPTAIN PHASMA",
"answ2":"Captain Phasma.",
},
{
"cat":"The Force Awakens",
"ques":"How many years has Maz Kanata run her watering hole on the planet Takodana?",
"answ":"1 000",
"answ3":"1000",
"answ2":"1000.",
},
{
"cat":"The Force Awakens",
"ques":"According to Rey, how does BB-8 respond when she asked him where he came from?",
"answ":"THAT'S CLASSIFIED",
"answ2":"That's classified.",
},
{
"cat":"The Force Awakens",
"ques":"In Episode VII, who sets off the explosives in the oscillator in Starkiller base?",
"answ":"CHEWBACCA",
"answ3":"CHEWIE",
"answ2":"Chewbacca.",
},
{
"cat":"The Force Awakens",
"ques":"How does Kylo Ren refer to Darth Vader during his monologue about finishing what he started?",
"answ":"GRANDFATHER",
"answ3":"GRAND FATHER",
"answ2":"Grandfather.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, how much did Bala-Tik loan Han Solo for the Rathtar job?",
"answ":"50000 CREDITS",
"answ3":"50 000 CREDITS",
"answ2":"50,000 credits.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who accompanies Rey and Chewie to find Luke Skywalker?",
"answ":"R2D2",
"answ3":"R2 D2",
"answ2":"R2-D2.",
},
{
"cat":"The Force Awakens",
"ques":"What is Poe Dameron's call sign?",
"answ":"BLACK LEADER",
"answ2":"Black Leader.",
},
{
"cat":"The Force Awakens",
"ques":"In Episode VII, according to Finn what do First Order stormtrooper masks not filter out?",
"answ":"TOXINS",
"answ2":"Toxins.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, R2 put himself in what state ever since Luke went away?",
"answ":"LOW POWER",
"answ3":"LOW POWER MODE",
"answ2":"Low Power Mode.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who is the only character to say: 'May the Force be with you'?",
"answ":"GENERAL LEIA",
"answ3":"LEIA",
"answ2":"Leia.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Han Solo said that he used to think that the magical power of the Force was a bunch of what?",
"answ":"MUMBO JUMBO",
"answ2":"Mumbo-jumbo.",
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, how many times does Kylo Ren wound Finn with his three-bladed lightsaber?",
"answ":"TWO",
"answ3":"2",
"answ2":"2.",
},
];
var r2Q7 = [
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, who said the line: 'Tell that to Kanjiklub'?",
"answ":"BALA TIK",
"answ2":"Bala-Tik.",
"option":["Bala-Tik", "Razoo Quin-Fee", "Delphi Kloda", "Tasu Leech"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, in what system is the Resistance base located?",
"answ":"ILENIUM SYSTEM",
"answ3":"ILEENIUM SYSTEM",
"answ2":"Ileenium system.",
"option":["Ileenium system", "Yavin system", "Hosnian system", "Exegol system"],
},
{
"cat":"The Force Awakens",
"ques":"Kylo Ren's First Order Star Destroyer goes by what name?",
"answ":"THE FINALIZER",
"answ2":"The Finalizer.",
"option":["The Finalizer", "The Supremacy", "The Conqueror", "The Fulminatrix"],
},
{
"cat":"The Force Awakens",
"ques":"According to Han Solo, who stole the Millennium Falcon from him?",
"answ":"GANNIS DUCAIN",
"answ3":"DUCAIN",
"answ2":"Ducain.",
"option":["Ducain", "Magaloof", "Ballax", "Quella"],
},
{
"cat":"The Force Awakens",
"ques":"How many portions does Unkar Plutt initially offer for BB-8?",
"answ":"60 PORTIONS",
"answ3":"60",
"answ2":"60.",
"option":["60", "50", "30", "100"],
},
{
"cat":"The Force Awakens",
"ques":"What creature does Finn share a drink with in Jakku?",
"answ":"HAPPABORE",
"answ2":"Happabore.",
"option":["Happabore", "Bantha", "Blurrg", "Fathier"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what planet is the Resistance base located on?",
"answ":"D'QAR",
"answ3":"D QAR",
"answ2":"D'Qar.",
"option":["D'Qar", "Felucia", "Hoth", "Scarif"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, how does Maz Kanata refer to Chewbacca?",
"answ":"BOYFRIEND",
"answ3":"HER BOYFRIEND",
"answ2":"Her boyfriend.",
"option":["Her boyfriend", "Her old flame", "Her son", "Her furry friend"],
},
{
"cat":"The Force Awakens",
"ques":"Who were Han and Chewie delivering the 3 rathtars to?",
"answ":"PRANA",
"answ3":"KING PRANA",
"answ2":"King Prana.",
"option":["King Prana", "Jabba the Hutt", "Regent Solculvis", "Kanjiklub"],
},
{
"cat":"The Force Awakens",
"ques":"Not counting young Rey's screams, whose voice is the first heard in Rey's force vision after touching Luke's lightsaber?",
"answ":"YODA",
"answ2":"Yoda.",
"option":["Yoda", "Luke Skywalker", "Kylo Ren", "Princess Leia"],
},
{
"cat":"The Force Awakens",
"ques":"What job does Finn tell Han was one of his duties on Starkiller Base?",
"answ":"JANITOR",
"answ2":"Janitor.",
"option":["Janitor", "Cook", "Guard", "Engineer"],
},
{
"cat":"The Force Awakens",
"ques":"Where does Finn want to go after he visits Maz Kanata's castle?",
"answ":"OUTER RIM",
"answ3":"THE OUTER RIM",
"answ2":"Outer Rim.",
"option":["Outer Rim", "Western Reaches", "Wild Space", "Expansion Region"],
},
{
"cat":"The Force Awakens",
"ques":"What nickname does Han Solo call Finn by?",
"answ":"BIG DEAL",
"answ2":"Big deal.",
"option":["Big deal", "Tough guy", "Mr. Big time", "Rookie"],
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the outpost on Jakku that Rey regularly visits to turn in parts for supplies and food?",
"answ":"NIIMA OUTPOST",
"answ3":"NIMA OUTPOST",
"answ2":"Niima Outpost.",
"option":["Niima Outpost", "Black Spire Outpost", "Coronet Outpost", "Akkalo Outpost"],
},
{
"cat":"The Force Awakens",
"ques":"Which Indonesian actor played in The Raid series and played a character named Tassu Leech in The Force Awakens?",
"answ":"YAYAN RUHIAN",
"answ2":"Yayan Ruhian.",
"option":["Yayan Ruhian", "Joe Taslim", "Iko Uwais", "Donny Alamsyah"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what are Leia's final words to Han?",
"answ":"BRING HIM HOME",
"answ2":"Bring him home.",
"option":["Bring him home", "Save our son", "I love you", "Be careful"],
},
{
"cat":"The Force Awakens",
"ques":"In the beginning of The Force Awakens, what is the name of the ship that Han and Chewie are using in their smuggling operation?",
"answ":"ERAVANA",
"answ3":"ERVANA",
"answ2":"Eravana.",
"option":["Eravana", "Uhumele", "Mayjeln", "Millanti"],
},
{
"cat":"The Force Awakens",
"ques":"How/why do BB-8 and Rey first interact with Finn?",
"answ":"BB 8 RECOGNIZES HIS JACKET",
"answ3":"BB 8 RECOGNIZED HIS JACKET",
"answ2":"BB-8 recognizes his jacket.",
"option":["BB-8 recognizes his jacket", "Finn helps Rey in a fight", "Finn tries to steal BB-8", "Finn trips over BB-8"],
},
{
"cat":"The Force Awakens",
"ques":"Also known as the Crimson Corsair, Finn seeks a ride off Takodana with what red raider pirate?",
"answ":"SIDON ITHANO",
"answ2":"Sidon Ithano.",
"option":["Sidon Ithano", "Reeg Brosna", "Quiggold", "Pendewqell"],
},
{
"cat":"The Force Awakens",
"ques":"As BB-8 rolls across the sand dunes of Jakku before meeting Rey, what kind of creature is seen popping his head up out of the sand?",
"answ":"NIGHTWATCHER WORM",
"answ2":"Nightwatcher worm.",
"option":["Nightwatcher worm", "Happabore", "Sand urchin", "Bloggin"],
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the scavenger that nets BB-8 on Jakku?",
"answ":"TEEDO",
"answ2":"Teedo.",
"option":["Teedo", "Duros", "Kaleesh", "Falleen"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens what is the name of the First Order base?",
"answ":"STARKILLER BASE",
"answ3":"STARKILLER",
"answ2":"Starkiller Base.",
"option":["Starkiller Base", "Stardestroyer Base", "Suncrusher Base", "Darklighter Base"],
},
{
"cat":"The Force Awakens",
"ques":"This superfan director has a voice cameo as a Stormtrooper during the destruction of Maz's Castle in The Force Awakens.",
"answ":"KEVIN SMITH",
"answ2":"Kevin Smith.",
"option":["Kevin Smith", "JJ Abrams", "Jon Favreau", "Dave Filoni"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens what does Rey repair on BB-8 when they first meet?",
"answ":"ANTENNA",
"answ3":"HIS ANTENNA",
"answ2":"Antenna.",
"option":["Antenna", "Lens", "Battery", "Laser"],
},
{
"cat":"The Force Awakens",
"ques":"The chromium armor of this character was initially designed for Kylo Ren.",
"answ":"CAPTAIN PHASMA",
"answ2":"Captain Phasma.",
"option":["Captain Phasma", "Captain Rex", "Boba Fett", "Captain Antilles"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what is the name of the planet that is home to Maz Kanata's castle?",
"answ":"TAKODANA",
"answ2":"Takodana.",
"option":["Takodana", "Cardota", "Raysho", "Courtsilius"],
},
{
"cat":"The Force Awakens",
"ques":"Where does Finn want to go after he visits Maz Kenata's castle with Rey and Han Solo to escape The First Order?",
"answ":"THE OUTER RIM",
"answ3":"OUTER RIM",
"answ2":"The Outer Rim.",
"option":["The Outer Rim", "Tatooine", "Core Worlds", "Jakku"],
},
{
"cat":"The Force Awakens",
"ques":"Korr Sella and Chancellor Villecham perish on what planet?",
"answ":"HOSNIAN PRIME",
"answ2":"Hosnian Prime.",
"option":["Hosnian Prime", "Vardos", "Pillio", "Skako"],
},
{
"cat":"The Force Awakens",
"ques":"Despite only appearing in the Niima Outpost chase sequences for a few frames, this cult favorite law enforcing character has his own action figure.",
"answ":"CONSTABLE ZUVIO",
"answ3":"ZUVIO",
"answ2":"Constable Zuvio.",
"option":["Constable Zuvio", "Goss Toowers", "Tam Posla", "Tasu Leech"],
},
{
"cat":"The Force Awakens",
"ques":"What is the name of the Abednedo X-wing starfighter pilot who was shot down during the Battle of Starkiller Base?",
"answ":"ELLO ASTY",
"answ2":"Ello Asty.",
"option":["Ello Asty", "Bastian", "Niv Lek", "Yolo Ziff"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Han mentions that the Guavian Death Gang must have tracked them from where?",
"answ":"NANTOON",
"answ2":"Nantoon.",
"option":["Nantoon", "Jakku", "Teyr", "Loronar"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, Finn has a lightsaber and fights against a stormtrooper who is using what specific riot baton?",
"answ":"Z6 RIOT CONTROL BATON",
"answ3":"Z6 BATON",
"answ2":"Z6 riot control baton.",
"option":["Z6 riot control baton", "Z3 snap baton", "Z4 electrobaton", "Z2 stun baton"],
},
{
"cat":"The Force Awakens",
"ques":"When Han, Chewy and Finn first arrive on Illum, Hux gets a report from an officer that he says the super weapon will be charged in how long?",
"answ":"15 MINUTES",
"answ2":"15 minutes.",
"option":["15 minutes", "25 minutes", "10 minutes", "20 minutes"],
},
{
"cat":"The Force Awakens",
"ques":"What character reported Poe and Finn's escape from the Finalizer?",
"answ":"THANISSON",
"answ3":"LIEUTENANT THANISSON",
"answ2":"Thanisson.",
"option":["Thanisson", "Masir Trach", "Kaplan", "Hux"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, how much credits does Bala-Tik say they loaned Han Solo for the rathtar job?",
"answ":"50 000",
"answ3":"50000",
"answ2":"50,000.",
"option":["50,000", "30,000", "20,000", "15,000"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, from what bay number are Poe and Finn trying to escape the Finalizer from?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "7", "14", "39"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what species is Unkar Plutt?",
"answ":"CROLUTE",
"answ3":"KROLUTE",
"answ2":"Crolute.",
"option":["Crolute", "Zabrak", "Bothan", "Nautolan"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, excluding Bala-Tik how many representatives from the Guavian Death Gang intercept Han Solo?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":["5", "7", "9", "10"],
},
{
"cat":"The Force Awakens",
"ques":"According to the opening crawl, Leia has sent her most daring pilot on a secret mission to Jakku where an old 'what' has discovered a clue to Luke's whereabouts?",
"answ":"ALLY",
"answ2":"Ally.",
"option":["Ally", "Acquaintance", "Companion", "Friend"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, when discussing the First Order, Maz Kanata says their 'what' is spreading through the galaxy?",
"answ":"SHADOW",
"answ2":"Shadow.",
"option":["Shadow", "Darkness", "Reach", "Evil"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, the pirate Quiggold is from what planet?",
"answ":"GABDOR",
"answ2":"Gabdor.",
"option":["Gabdor", "Cardota", "Delphidan", "Ilum"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, when Rey meets BB-8 she tells him to stay off what Ridge?",
"answ":"KELVIN RIDGE",
"answ2":"Kelvin Ridge.",
"option":["Kelvin Ridge", "Goazon Ridge", "Meru Ridge", "Tuanul Ridge"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what is the first name of Admiral Statura?",
"answ":"USHOS",
"answ3":"OSHOS",
"answ2":"Ushos.",
"option":["Ushos", "Taslin", "Caluan", "Gial"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, what is the name of the servant droid that alerted the Resistance of BB-8's presence in Maz Kanata's castle?",
"answ":"GA97",
"answ3":"GA 97",
"answ2":"GA-97.",
"option":["GA-97", "EV-9D9", "PA-LT4", "A-3DO"],
},
{
"cat":"The Force Awakens",
"ques":"After capturing Han and Finn, a stormtrooper reports to his commander that they have the targets in custody, what is the name of the stormtrooper commander?",
"answ":"TK 338",
"answ2":"TK-338.",
"option":["TK-338", "TK-479", "TK-714", "TK-1138"],
},
{
"cat":"The Force Awakens",
"ques":"In The Force Awakens, a stormtrooper informs Kylo Ren that sensors have been triggered in what hangar as Rey tries to escape Starkiller Base?",
"answ":"718",
"answ3":"HANGAR 718",
"answ2":"Hangar 718.",
"option":["Hangar 718", "Hangar 539", "Hangar 647", "Hangar 491"],
},
];
r2Q7 = shuffle(r2Q7);
episodevii = shuffle(episodevii);