var rogueone = [
{
"cat":"Rogue One",
"ques":"In Rogue One, when Jyn says that she found a blaster, K-2SO says that he finds that answer unconvincing and ____?",
"answ":"VAGUE",
"answ2":"Vague.",
},
{
"cat":"Rogue One",
"ques":"What planet does Senator Tynnra Pamlo represent in the Imperial Senate?",
"answ":"TARIS",
"answ2":"Taris.",
},
{
"cat":"Rogue One",
"ques":"What Star Wars director cameoed in Rogue One as a Death Star trooper?",
"answ":"RIAN JOHNSON",
"answ2":"Rian Johnson.",
},
{
"cat":"Rogue One",
"ques":"What is the name of the Hammerhead corvette that rams two Star Destroyers together, destroying all three ships during the Battle of Scarif?",
"answ":"THE LIGHTMAKER",
"answ2":"The Lightmaker.",
},
{
"cat":"Rogue One",
"ques":"Warwick Davis plays what alien character that works for Saw's rebels on Jedha in Rogue One?",
"answ":"WEETEEF CYU BEE",
"answ2":"Weeteef Cyu-Bee.",
},
{
"cat":"Rogue One",
"ques":"Which actor plays Baze Malbus?",
"answ":"JIANG WEN",
"answ2":"Jiang Wen.",
},
{
"cat":"Rogue One",
"ques":"Who has the last line of dialogue in Rogue One?",
"answ":"LEIA",
"answ3":"PRINCESS LEIA",
"answ2":"Leia.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Admiral Raddus of the Rebel Alliance asks his squadron leaders to report in, which leader reports in first?",
"answ":"BLUE LEADER",
"answ2":"Blue Leader.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, after crashing into the Star Destroyer, Captain Oquoné tells his crew to move what kind of thrusters into full power?",
"answ":"SUBLIGHT",
"answ2":"Sublight.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what cell block is Jyn Erso held in while in the Imperial detention center and labor camp?",
"answ":"4227",
"answ3":"CELL BLOCK 4227",
"answ2":"4227.",
},
{
"cat":"Rogue One",
"ques":"Which actress plays young Jyn Erso in the film Rogue One?",
"answ":"BEAU GADSDON",
"answ2":"Beau Gadsdon.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Cassian left the crashed ship on Eadu, in what configuration was his weapon in?",
"answ":"SNIPER",
"answ3":"SNIPER CONFIGURATION",
"answ2":"Sniper configuration.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, Grand Moff Tarkin says that destroying an entire moon will not be necessary, because they need to make a statement, not a what?",
"answ":"MANIFESTO",
"answ2":"Manifesto.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Cassian first speaks to Jyn he asks when was the last time she was in contact with her father, what is her response?",
"answ":"15 YEARS",
"answ3":"15 YEARS AGO",
"answ2":"15 years ago.",
},
{
"cat":"Rogue One",
"ques":"'May the Force of others be with you' are the first lines spoken by which Rogue One character?",
"answ":"CHIRRUT IMWE",
"answ2":"Chirrut Îmwe.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, the Rebel Alliance Headquarters was located on a moon orbiting what planet?",
"answ":"YAVIN",
"answ2":"Yavin.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the tropical planet in which the final act takes place?",
"answ":"SCARIF",
"answ2":"Scarif.",
},
{
"cat":"Rogue One",
"ques":"What director has a cameo as the Rebel soldier that pulls the lever that releases the Tantive IV from the belly of Admiral Raddus' ship?",
"answ":"GARETH EDWARDS",
"answ2":"Gareth Edwards.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what are Saw Gererra's last words in the film?",
"answ":"SAVE THE REBELLION SAVE THE DREAM",
"answ3":"SAVE THE DREAM",
"answ2":"Save the rebellion, save the dream.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the first droid that is seen in the film?",
"answ":"SE 2 WORKER DROID",
"answ3":"SE 2",
"answ2":"SE-2 worker droid.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, K-2SO says that he'll be there for Jyn, because who said he had to be?",
"answ":"CASSIAN",
"answ3":"CASSIAN ENDOR",
"answ2":"Cassian.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, who takes away command of the Death Star from Director Krennic?",
"answ":"GRAND MOFF TARKIN",
"answ3":"TARKIN",
"answ2":"Grand Moff Tarkin.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, which character says the strongest stars have hearts of Kyber?",
"answ":"CHIRRUT IMWE",
"answ3":"CHIRRUT ÎMWE",
"answ2":"Chirrut Îmwe.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, who says: 'Its power to create problems has certainly been confirmed. A city destroyed... an Imperial facility openly attacked.'?",
"answ":"DARTH VADER",
"answ2":"Darth Vader.",
},
{
"cat":"Rogue One",
"ques":"What is the name of the yacht Dryden Vos travels in?",
"answ":"FIRST LIGHT",
"answ2":"First Light.",
},
{
"cat":"Rogue One",
"ques":"What is the name of the planet Saw Gerrera lives on where his city is destroyed by the Death Star?",
"answ":"JEDHA",
"answ2":"Jedha.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, which admiral leads the space assault on Imperial forces during the Battle of Scarif?",
"answ":"ADMIRAL RADDUS",
"answ3":"RADDUS",
"answ2":"Admiral Raddus.",
},
{
"cat":"Rogue One",
"ques":"Who was the first character in the Rogue One team to die in the film?",
"answ":"K 2SO",
"answ3":"K2SO",
"answ2":"K-2SO.",
},
{
"cat":"Rogue One",
"ques":"Who is K-2SO talking to when he says: 'Congratulations, you are being rescued. Please do not resist.'?",
"answ":"JYN ERSO",
"answ3":"JYN",
"answ2":"Jyn Erso.",
},
{
"cat":"Rogue One",
"ques":"On what planet is Jyn Erso held as a prisoner in an Imperial labor camp before being rescued by the Rebel alliance near the beginning of the film?",
"answ":"WOBANI",
"answ2":"Wobani.",
},
{
"cat":"Rogue One",
"ques":"By what title is Tarkin called by Krennic in Rogue One?",
"answ":"GOVERNOR",
"answ2":"Governor.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the informant Cassian meets on Kafrene?",
"answ":"TIVIK",
"answ2":"Tivik.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, Director Krennic is often seen flanked by what elite class of stormtrooper?",
"answ":"DEATH TROOPERS",
"answ3":"DEATHTROOPERS",
"answ2":"Death troopers.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what character says: 'The Force moves darkly near a creature that is about to kill.'?",
"answ":"CHIRRUT IMWE",
"answ3":"CHIRRUT ÎMWE",
"answ2":"Chirrut Îmwe.",
},
{
"cat":"Rogue One",
"ques":"What peaceful lifestyle does Galen Erso lead while living on Lah'mu?",
"answ":"FARMING",
"answ3":"FARMER",
"answ2":"Farming.",
},
{
"cat":"Rogue One",
"ques":"What nickname is given to Jyn Erso by her father?",
"answ":"STARDUST",
"answ2":"Stardust.",
},
{
"cat":"Rogue One",
"ques":"Who portrayed Mon Mothma in Rogue One?",
"answ":"GENEVIEVE O'REILLY",
"answ2":"Genevieve O'Reilly.",
},
{
"cat":"Rogue One",
"ques":"Rogue One: Star Wars Story was released in what year?",
"answ":"2016",
"answ2":"2016.",
},
{
"cat":"Rogue One",
"ques":"Who provided the voice for K-2SO in Rogue One?",
"answ":"ALAN TUDYK",
"answ3":"ALAN TUDIK",
"answ2":"Alan Tudyk.",
},
{
"cat":"Rogue One",
"ques":"Who composed the score for Rogue One?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what member of the Rebel team was previously an Imperial Cargo pilot?",
"answ":"BODHI ROOK",
"answ2":"Bodhi Rook.",
},
{
"cat":"Rogue One",
"ques":"What Rogue One cast member was played by Jiang Wen?",
"answ":"BAZE",
"answ3":"BAZE MALBUS",
"answ2":"Baze Malbus.",
},
{
"cat":"Rogue One",
"ques":"Who plays the character Chirrut Imwe in Rogue One?",
"answ":"DONNIE YEN",
"answ2":"Donnie Yen.",
},
{
"cat":"Rogue One",
"ques":"Who played Cassian Andor in Rogue One?",
"answ":"DIEGO LUNA",
"answ2":"Diego Luna.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the Talpini Partisan played by Warwick Davis?",
"answ":"WEETEEF CYUBEE",
"answ3":"WEETEEF CYU BEE",
"answ2":"Weeteef Cyu-Bee.",
},
{
"cat":"Rogue One",
"ques":"Who played Jyn Erso's father?",
"answ":"MADS MIKKELSEN",
"answ2":"Mads Mikkelsen.",
},
{
"cat":"Rogue One",
"ques":"Who played Jyn Erso in Rogue One?",
"answ":"FELICITY JONES",
"answ2":"Felicity Jones.",
},
{
"cat":"Rogue One",
"ques":"Who plays pilot Bodhi Rook in Rogue One?",
"answ":"RIZ AHMED",
"answ2":"Riz Ahmed.",
},
{
"cat":"Rogue One",
"ques":"What is the name of Ben Mendelsohn's character in Rogue One?",
"answ":"ORSON KRENNIC",
"answ3":"KRENNIC",
"answ2":"Orson Krennic.",
},
{
"cat":"Rogue One",
"ques":"What is the name of Forest Whitaker's character in Rogue One?",
"answ":"SAW GERERA",
"answ3":"SAW GERRERA",
"answ2":"Saw Gerrera.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the planet that the Empire is removing the kyber crystals from?",
"answ":"JEDHA",
"answ2":"Jedha.",
},
{
"cat":"Rogue One",
"ques":"According to Chirrut, the strongest stars have hearts of what?",
"answ":"KYBER",
"answ2":"Kyber.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, young Jyn had what kind of doll as a toy?",
"answ":"STORMTROOPER",
"answ2":"Stormtrooper.",
},
{
"cat":"Rogue One",
"ques":"On what planet does Galen Erso die?",
"answ":"EADU",
"answ3":"EDU",
"answ2":"Eadu.",
},
{
"cat":"Rogue One",
"ques":"Admiral Raddus commanded the Battle of Scarif from the deck of what Rebel capital ship?",
"answ":"THE PROFUNDITY",
"answ3":"PROFUNDITY",
"answ2":"Profundity.",
},
{
"cat":"Rogue One",
"ques":"What was Jyn Erso's mother's name?",
"answ":"LYRA",
"answ3":"LYRA ERSO",
"answ2":"Lyra.",
},
{
"cat":"Rogue One",
"ques":"What was Jyn Erso's father's name?",
"answ":"GALEN",
"answ3":"GALEN ERSO",
"answ2":"Galen.",
},
{
"cat":"Rogue One",
"ques":"When Krennic approached Galen at the beginning of Rogue One, Galen said that Krennic was confusing peace with what?",
"answ":"TERROR",
"answ2":"Terror.",
},
{
"cat":"Rogue One",
"ques":"Before entering Jedha City, Jyn told Cassian that they should leave K-2SO behind, except she referred to K2 as what?",
"answ":"TARGET PRACTICE",
"answ2":"Target practice.",
},
{
"cat":"Rogue One",
"ques":"Who directed Rogue One?",
"answ":"GARETH EDWARDS",
"answ2":"Gareth Edwards.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the General who orders Cassian to kill Galen Erso?",
"answ":"GENERAL DRAVEN",
"answ3":"DRAVEN",
"answ2":"General Draven.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, Cassian Andor exclaims that he has been in the Rebellion since he was how many years old?",
"answ":"SIX",
"answ3":"6",
"answ2":"6.",
},
{
"cat":"Rogue One",
"ques":"Who said: 'Your behavior, Jyn Erso, is continually unexpected'?",
"answ":"K2SO",
"answ3":"K 2SO",
"answ2":"K-2SO.",
},
{
"cat":"Rogue One",
"ques":"Who said: 'Save the Rebellion! Save the dream'?",
"answ":"SAW GERRERA",
"answ3":"SAW GERERA",
"answ2":"Saw Gerrera.",
},
{
"cat":"Rogue One",
"ques":"When General Draven is questioning Jyn Erso, name the fourth charge he lists on her rap sheet.",
"answ":"ESCAPING CUSTODY",
"answ2":"Escaping custody.",
},
{
"cat":"Rogue One",
"ques":"What is the first name of the male politician Vaspar, who represented the Taldot sector in the Imperial Senate?",
"answ":"VASP",
"answ2":"Vasp.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, Jyn Erso tells the Alliance that if they give way to this evil with this much power, they condemn the galaxy to an eternity of what?",
"answ":"SUBMISSION",
"answ2":"Submission.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, to distract the enemy to the wrong area, Bodhi pretends to see 40 Rebels on what pad number?",
"answ":"TWO",
"answ3":"2",
"answ2":"2.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what section number in the Ring of Kafrene does Cassian Andor meet with Tivik?",
"answ":"SECTION 9",
"answ3":"9",
"answ2":"9.",
},
{
"cat":"Rogue One",
"ques":"What type of fighter did Gold Leader fly in the Battle of Scarif?",
"answ":"Y WING",
"answ2":"Y-wing.",
},
{
"cat":"Rogue One",
"ques":"Which actor portrays General Hurst Romodi in the film?",
"answ":"ANDY DE LA TOUR",
"answ2":"Andy de la Tour.",
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the name of the character played by Riz Ahmed?",
"answ":"BODI ROOK",
"answ3":"BODHI ROOK",
"answ2":"Bodhi Rook.",
},
];
var r2Q9 = [
{
"cat":"Rogue One",
"ques":"Which Star Wars character attempts to say the classic 'I have a bad feeling about this' line in Rogue One?",
"answ":"K 2SO",
"answ3":"K2SO",
"answ2":"K-2SO.",
"option":["K-2SO", "Cassian Endor", "Jyn Erso", "Saw Gerrera"],
},
{
"cat":"Rogue One",
"ques":"Which actor plays Second Lieutenant Frobb of the Galactic Empire in the film?",
"answ":"GEOFF BELL",
"answ2":"Geoff Bell.",
"option":["Geoff Bell", "Michael Gould", "Michael Shaffer", "Rufus Wright"],
},
{
"cat":"Rogue One",
"ques":"Genevieve O'Reilly took over what iconic original trilogy role as leader of the Rebel Alliance in Rogue One?",
"answ":"MON MOTHMA",
"answ2":"Mon Mothma.",
"option":["Mon Mothma", "Chief Chirpa", "Yarna d'al' Gargan", "Greeata Jendowanian"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, according to Mon Mothma, Saw Gerrera's what has caused the Alliance a great many problems?",
"answ":"MILITANCY",
"answ2":"Militancy.",
"option":["Militancy", "Vengeance", "Aggressiveness", "Boldness"],
},
{
"cat":"Rogue One",
"ques":"What is the name of the popular gunner character affectionately dubbed the 'space monkey'?",
"answ":"BISTAN",
"answ2":"Bistan.",
"option":["Bistan", "Baze", "Malbus", "Libbark"],
},
{
"cat":"Rogue One",
"ques":"When General Draven is questioning Jyn Erso, what is the first charge he lists on her rap sheet?",
"answ":"POSSESSION OF UNSANCTIONED WEAPONS",
"answ2":"Possession of unsanctioned weapons.",
"option":["Possession of unsanctioned weapons", "Aggravated assault", "Escape from custody", "Forgery of Imperial documents"],
},
{
"cat":"Rogue One",
"ques":"What was the name of the rebel that Cassian killed so he could escape from the stormtroopers at the beginning of Rogue One?",
"answ":"TIVIK",
"answ2":"Tivik.",
"option":["Tivik", "Edrio", "Xosad", "Kaev"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, which starfighter squadron makes it through the Shield Gate to assist Rebels on the ground?",
"answ":"BLUE SQUADRON",
"answ3":"BLUE",
"answ2":"Blue Squadron.",
"option":["Blue Squadron", "Red Squadron", "Gold Squadron", "Green Squadron"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the official name of the insurgent group led by Saw Gerrera?",
"answ":"THE PARTISANS",
"answ3":"PARTISANS",
"answ2":"The Partisans.",
"option":["The Partisans", "The Rebel Alliance", "The New Order", "The Paramilitary"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, K-2SO gets upset that Jyn Erso is allowed to have what, but he is not?",
"answ":"BLASTER",
"answ3":"SPACE GUN",
"answ2":"Blaster.",
"option":["Blaster", "Lightsaber", "Sandwich", "Helmet"],
},
{
"cat":"Rogue One",
"ques":"Who plays Republic Informant Tivik in Rogue One?",
"answ":"DANIEL MAYS",
"answ2":"Daniel Mays.",
"option":["Daniel Mays", "Ben Daniels", "Nick Kellington", "Jordan Stephens"],
},
{
"cat":"Rogue One",
"ques":"What landing platform were the Rebels directed to land on at Scarif?",
"answ":"PLATFORM 9",
"answ3":"9",
"answ2":"Platform 9.",
"option":["Platform 9", "Platform 94", "Platform 14", "Platform 327"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, Blue Squadron is led by what Rebel General?",
"answ":"ANTOC MERRICK",
"answ3":"GENERAL MERRICK",
"answ2":"Antoc Merrick.",
"option":["Antoc Merrick", "Farns Monsbee", "Ten Numb", "Jaldine Gerams"],
},
{
"cat":"Rogue One",
"ques":"Galen designs a weakness in what area, or module, of the Death Star?",
"answ":"REACTOR MODULE",
"answ2":"Reactor module.",
"option":["Reactor module", "Igniter module", "Coolant module", "Hyperdrive module"],
},
{
"cat":"Rogue One",
"ques":"What is the name of the planet the Ersos are hiding on at the beginning of Rogue One?",
"answ":"LAHMU",
"answ3":"LAH'MU",
"answ2":"Lah'mu.",
"option":["Lah'mu", "Tython", "Byss", "Chandrila"],
},
{
"cat":"Rogue One",
"ques":"What is the codename for the Death Star plans?",
"answ":"STARDUST",
"answ2":"Stardust.",
"option":["Stardust", "Starlight", "Sunshine", "Stargaze"],
},
{
"cat":"Rogue One",
"ques":"Before being rescued by the Rebellion, Jyn Erso had been using what alias?",
"answ":"LIANA HALLIK",
"answ3":"LIANA HALIK",
"answ2":"Liana Hallik.",
"option":["Liana Hallik", "Aurra Sing", "Aayla Secura", "Mara Jade"],
},
{
"cat":"Rogue One",
"ques":"Cassian Endor is an officer in what division of the Rebel Alliance?",
"answ":"INTELLIGENCE",
"answ2":"Intelligence.",
"option":["Intelligence", "Reconnaissance", "Special Forces", "Black Ops"],
},
{
"cat":"Rogue One",
"ques":"At what location does Cassian meet his contact at the beginning of the film?",
"answ":"RING OF KAFRENE",
"answ3":"KAFRENE",
"answ2":"Ring of Kafrene.",
"option":["Ring of Kafrene", "Fort Anaxes", "Mek-Sha", "Ordo Eris"],
},
{
"cat":"Rogue One",
"ques":"The Rebel Alliance distanced themselves from Saw because he was _____",
"answ":"AN EXTREMIST",
"answ3":"EXTREMIST",
"answ2":"An extremist.",
"option":["An extremist", "A traitor", "Crazy", "Unreliable"],
},
{
"cat":"Rogue One",
"ques":"After K2 downloads the map to the data vault, he learns that the optimal route to the vault puts how many stormtroopers in their path?",
"answ":"89",
"answ2":"89.",
"option":["89", "57", "74", "33"],
},
{
"cat":"Rogue One",
"ques":"What is the name of the human male attendant that informs Darth Vader that Director Krennic has arrived on Mustafar?",
"answ":"VANEE",
"answ3":"VANEÉ",
"answ2":"Vaneé.",
"option":["Vaneé", "Tivik", "Pao", "Bistan"],
},
{
"cat":"Rogue One",
"ques":"Who says 'We call it the Death Star. There is no better name... and the day is coming soon when it will be unleashed'?",
"answ":"GALEN ERSO",
"answ2":"Galen Erso.",
"option":["Galen Erso", "Captain Pterro", "Darth Vader", "Governor Tarkin"],
},
{
"cat":"Rogue One",
"ques":"Darth Vader tells Krennic that the Senate was informed what caused the destruction of Jedha?",
"answ":"A MINING DISASTER",
"answ3":"MINING DISASTER",
"answ2":"A mining disaster.",
"option":["A mining disaster", "Meteor impact", "The Death Star", "Volcano eruption"],
},
{
"cat":"Rogue One",
"ques":"Tarkin cites a recent failure of Krennic's as a reason to justify his takeover of the Death Star and test its power. What was the reason?",
"answ":"SECURITY BREACH",
"answ3":"A SECURITY BREACH",
"answ2":"Security breach.",
"option":["A security breach", "Failure to blockade Jedha", "Let prisoners escape", "Hit an Imperial cruiser"],
},
{
"cat":"Rogue One",
"ques":"What was Bodhi Rook's final line in the film?",
"answ":"THIS IS FOR YOU GALEN",
"answ2":"This is for you Galen.",
"option":["This is for you Galen", "Don't disappoint me", "For the Republic", "See you on the other side"],
},
{
"cat":"Rogue One",
"ques":"What does K-2SO say is his speciality?",
"answ":"STRATEGIC ANALYSIS",
"answ2":"Strategic Analysis.",
"option":["Strategic Analysis", "Deception", "Risk Management", "Shooting"],
},
{
"cat":"Rogue One",
"ques":"How many credits are awarded if anyone has information about Bodhi Rook?",
"answ":"600 CREDITS",
"answ3":"600",
"answ2":"600.",
"option":["600", "1500", "800", "1000"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, while on Earth, Chirrut asks Baze if Cassian looks like a what?",
"answ":"KILLER",
"answ2":"Killer.",
"option":["Killer", "Friend", "Enemy", "Soldier"],
},
{
"cat":"Rogue One",
"ques":"Saw Gerrera gave Jyn a knife and what other item the last time he saw her, before telling her to hide in a bunker?",
"answ":"BLASTER",
"answ3":"LOADED BLASTER",
"answ2":"Blaster.",
"option":["Blaster", "Backpack", "Compass", "Necklace"],
},
{
"cat":"Rogue One",
"ques":"How old was Jyn when Saw left her behind on her own?",
"answ":"16",
"answ3":"16 YEARS",
"answ2":"16.",
"option":["16", "21", "18", "20"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Cassian Andor kills two stormtroopers in front of Tivik, what section of the Ring of Kafrene where they killed?",
"answ":"SECTION 9",
"answ3":"9",
"answ2":"Section 9.",
"option":["Section 9", "Section 7", "Section 12", "Section 5"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Chirrut Imwe is first introduced he asks Jyn if she would trade her necklace for what?",
"answ":"GLIMPSE INTO YOUR FUTURE",
"answ3":"GLIMPSE INTO HER FUTURE",
"answ2":"Glimpse into your future.",
"option":["Glimpse into her future", "12.000 credits", "Lightsaber", "A-300 blaster rifle"],
},
{
"cat":"Rogue One",
"ques":"Who said the line: 'Failure will find you explaining why to a far less patient audience'?",
"answ":"WILHUFF TARKIN",
"answ3":"GRAND MOFF TARKIN",
"answ2":"Grand Moff Tarkin/Wilhuff Tarkin.",
"option":["Grand Moff Tarkin", "Antoc Merrick", "Davits Draven", "Darth Vader"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when a Stormtrooper stops Cassian and Jyn, he tells K-2SO that he needs to check his what?",
"answ":"DIAGNOSTICS",
"answ2":"Diagnostics.",
"option":["Diagnostics", "Ammo", "Wiring", "Power engines"],
},
{
"cat":"Rogue One",
"ques":"At the end of the film, Darth Vader fights Rebel troopers as they try to escape with the Death Star plans. What is the name of the ship they're escaping from?",
"answ":"PROFUNDITY",
"answ3":"THE PROFUNDITY",
"answ2":"Profundity.",
"option":["Profundity", "Accordance", "Aspiration", "Temperance"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the first word spoken in the film?",
"answ":"MAMA",
"answ3":"MOMMA",
"answ2":"Mama.",
"option":["Mama", "Help", "Hello", "Sorry"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, when Cassian Endor and Tivik are having their meeting, stormtroopers find them and ask to see their what?",
"answ":"SCANDOCS",
"answ2":"Scandocs.",
"option":["Scandocs", "Identichip", "Chain code", "Comlink"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, according to Chirrut how does the force move when a creature is about to kill?",
"answ":"DARKLY",
"answ2":"Darkly.",
"option":["Darkly", "Dourly", "Smoothly", "Slowly"],
},
{
"cat":"Rogue One",
"ques":"Which Imperial walker appears in Rogue One?",
"answ":"AT ACT",
"answ3":"ATACT",
"answ2":"AT-ACT.",
"option":["AT-ACT", "AT-DT", "AT-AA", "AT-OT"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what were Lyra Erso's last words to her daughter?",
"answ":"TRUST THE FORCE",
"answ2":"Trust the Force.",
"option":["Trust the Force", "May the Force protect you", "Believe in the Force", "Be one with the Force"],
},
{
"cat":"Rogue One",
"ques":"What is the homeworld of the character Mon Mothma?",
"answ":"CHANDRILA",
"answ2":"Chandrila.",
"option":["Chandrila", "Fest", "Lexrul", "Jedha"],
},
{
"cat":"Rogue One",
"ques":"What was the name of the Imperial General in command of the base on Scarif in Rogue One?",
"answ":"GENERAL RAMDA",
"answ3":"SOTORUS RAMDA",
"answ2":"Sotorus Ramda.",
"option":["Sotorus Ramda", "Hurst Romodi", "Maximilian Veers", "Cassio Tagge"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, what is the specific name of the UT-60D U-wing shuttle that Jyn and Cassian take to Jeddha?",
"answ":"LMTR20",
"answ3":"LMTR 20",
"answ2":"LMTR-20.",
"option":["LMTR-20", "Bravo One", "Vanguard", "T-65B"],
},
{
"cat":"Rogue One",
"ques":"Which actor portrays Galactic Empire Captain Dunstig Pterro in the film Rogue One?",
"answ":"TONY PITTS",
"answ2":"Tony Pitts.",
"option":["Tony Pitts", "Duncan Pow", "Robin Pearce", "Martin Gordon"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, how many Death Star engineers are interrogated and executed by Krennic?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
"option":["6", "4", "5", "3"],
},
{
"cat":"Rogue One",
"ques":"In Rogue One, as the crew is trying to land on Eadu, K-2SO says what is the percent chance of failure?",
"answ":"26",
"answ3":"26 PERCENT",
"answ2":"26.",
"option":["26", "8", "15", "2"],
},
];
r2Q9 = shuffle(r2Q9);
rogueone = shuffle(rogueone);