var speedquestion001 = [
{
"cat":"Mixed Bag",
"ques":"Which bounty hunter watched the Boonta Eve Classic from Beggar's Canyon?",
"answ":"AURRA SING",
"answ3":"AURA SING",
"answ2":"Aurra Sing.",
},
{
"cat":"Mixed Bag",
"ques":"In The Clone Wars, how many star cruisers does Mace Windu need from Admiral Wurtz?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Mixed Bag",
"ques":"In Return of the Jedi, what is the language spoken by the Ewoks?",
"answ":"EWOKESE",
"answ2":"Ewokese.",
},
{
"cat":"Mixed Bag",
"ques":"In The Phantom Menace, what species is Mas Amedda?",
"answ":"CHAGRIAN",
"answ2":"Chagrian.",
},
{
"cat":"Mixed Bag",
"ques":"In Attack of the Clones, which character speaks the last line of the film?",
"answ":"YODA",
"answ2":"Yoda.",
},
{
"cat":"Mixed Bag",
"ques":"In Return of the Jedi, who plays Mon Mothma?",
"answ":"CAROLINE BLAKISTON",
"answ2":"Caroline Blakiston.",
},
{
"cat":"Mixed Bag",
"ques":"Which Jedi is shown executed on Cato Neimoidia?",
"answ":"PLO KOON",
"answ2":"Plo Koon.",
},
{
"cat":"Mixed Bag",
"ques":"R2-D2 has appeared in how many Star Wars films?",
"answ":"11",
"answ2":"11.",
},
{
"cat":"Mixed Bag",
"ques":"Who is the only actor to ever receive an Oscar nomination for a performance in a Star Wars film?",
"answ":"ALEC GUINNESS",
"answ2":"Alec Guinness.",
},
{
"cat":"Mixed Bag",
"ques":"The term 'nerf herder' was introduced in what Star Wars film?",
"answ":"THE EMPIRE STRIKES BACK",
"answ3":"EMPIRE STRIKES BACK",
"answ2":"The Empire Strikes Back.",
},
{
"cat":"Mixed Bag",
"ques":"Taun We and Lama Su are from what planet?",
"answ":"KAMINO",
"answ2":"Kamino.",
},
{
"cat":"Mixed Bag",
"ques":"What species is Watto?",
"answ":"TOYDARIAN",
"answ2":"Toydarian.",
},
{
"cat":"Mixed Bag",
"ques":"What is Owen Lars' occupation?",
"answ":"MOISTURE FARMER",
"answ2":"Moisture farmer.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Wedge Antilles?",
"answ":"DENIS LAWSON",
"answ2":"Denis Lawson.",
},
{
"cat":"Mixed Bag",
"ques":"Who says 'Twilight is upon me and soon night must fall'?",
"answ":"YODA",
"answ2":"Yoda.",
},
{
"cat":"Mixed Bag",
"ques":"Whose Force ghost does Luke see on Dagobah?",
"answ":"OBI WAN KENOBI",
"answ3":"OBI WAN",
"answ2":"Obi-Wan Kenobi.",
},
{
"cat":"Mixed Bag",
"ques":"Which character has their memory wiped in an attempt to find the location of the Emperor's wayfinder?",
"answ":"C 3PO",
"answ3":"C3PO",
"answ2":"C-3PO.",
},
{
"cat":"Mixed Bag",
"ques":"Which film features the following characters: Obi-Wan Kenobi, Palpatine, C-3PO, Commander Cody and Ahsoka Tano?",
"answ":"THE CLONE WARS",
"answ3":"CLONE WARS",
"answ2":"The Clone Wars.",
},
{
"cat":"Mixed Bag",
"ques":"In The Last Jedi, what character calls Supreme Leader Snoke's flagship 'Snokes boudoir'?",
"answ":"DJ",
"answ2":"DJ.",
},
{
"cat":"Mixed Bag",
"ques":"In The Phantom Menace, Anakin says that he thinks he has been on Tatooine since he was how old?",
"answ":"3",
"answ3":"3 YEARS",
"answ2":"3 years.",
},
{
"cat":"Mixed Bag",
"ques":"In Return of the Jedi who tells Luke Skywalker: 'I shall enjoy watching you die'?",
"answ":"JABBA THE HUTT",
"answ3":"JABBA",
"answ2":"Jabba the Hutt.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the Ocean Moon of Endor?",
"answ":"KEF BIR",
"answ2":"Kef Bir.",
},
{
"cat":"Mixed Bag",
"ques":"In A New Hope, C-3PO calls R2-D2 an overweight glob of what?",
"answ":"GREASE",
"answ2":"Grease.",
},
{
"cat":"Mixed Bag",
"ques":"Which Jedi says: 'The Force surrounds you Rey' during The Rise of Skywalker?",
"answ":"ANAKIN",
"answ3":"ANAKIN SKYWALKER",
"answ2":"Anakin Skywalker.",
},
{
"cat":"Mixed Bag",
"ques":"What were Shmi Skywalker's final two words before she died?",
"answ":"I LOVE",
"answ2":"I Love.",
},
{
"cat":"Mixed Bag",
"ques":"In The Phantom Menace, what is the last word in the opening crawl?",
"answ":"CONFLICT",
"answ2":"Conflict.",
},
{
"cat":"Mixed Bag",
"ques":"In The Empire Strikes Back, who had the callsign of Rogue Four?",
"answ":"DEREK KLIVIAN",
"answ3":"DEREK HOBBIE KLIVIAN",
"answ2":"Derek 'Hobbie' Klivian.",
},
{
"cat":"Mixed Bag",
"ques":"How many Star Wars films have won Academy Awards, not including Honorary Oscars?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"Mixed Bag",
"ques":"Chris Weitz co-wrote the screenplay for which Star Wars film?",
"answ":"ROGUE ONE",
"answ2":"Rogue One.",
},
{
"cat":"Mixed Bag",
"ques":"How many people have directed a live action Star Wars movie?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
},
{
"cat":"Mixed Bag",
"ques":"In how many films does Yaddle appear on the Jedi Council?",
"answ":"1",
"answ3":"ONE",
"answ2":"1.",
},
{
"cat":"Mixed Bag",
"ques":"Who flies as Red Five during the Battle of Endor?",
"answ":"GRIZZ FRIX",
"answ3":"GRIZ FRIX",
"answ2":"Grizz Frix.",
},
{
"cat":"Mixed Bag",
"ques":"Angus MacInnes plays which character in A New Hope?",
"answ":"GOLD LEADER",
"answ3":"JON VANDER",
"answ2":"Gold Leader/Jon Vander.",
},
{
"cat":"Mixed Bag",
"ques":"In how many films does the character Boba Fett appear?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"Mixed Bag",
"ques":"On what planet does Saw Gererra die?",
"answ":"JEDHA",
"answ2":"Jedha.",
},
{
"cat":"Mixed Bag",
"ques":"On what planet is Ki-Adi-Mundi murdered during Order 66?",
"answ":"MYGEETO",
"answ3":"MIGEETO",
"answ2":"Mygeeto.",
},
{
"cat":"Mixed Bag",
"ques":"In how many theatrically released films did Harrison Ford appear as Han Solo?",
"answ":"FIVE",
"answ3":"5",
"answ2":"5.",
},
{
"cat":"Mixed Bag",
"ques":"On what planet is Kit Fisto murdered in Revenge of the Sith?",
"answ":"CORUSCANT",
"answ2":"Coruscant.",
},
{
"cat":"Mixed Bag",
"ques":"How many actors have played Han Solo on the big screen?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"Mixed Bag",
"ques":"What character appears as Jabba's majordomo in Return of the Jedi?",
"answ":"BIB FORTUNA",
"answ2":"Bib Fortuna.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the star yacht that BB-8 and DJ steal in The Last Jedi?",
"answ":"THE LIBERTINE",
"answ3":"LIBERTINE",
"answ2":"The Libertine.",
},
{
"cat":"Mixed Bag",
"ques":"What is the final planet seen at the end of Revenge of the Sith?",
"answ":"TATOOINE",
"answ2":"Tatooine.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the Gand findsman seen in the Bounty Hunter line in Empire?",
"answ":"ZUCKUSS",
"answ3":"ZUCKUS",
"answ2":"Zuckuss.",
},
{
"cat":"Mixed Bag",
"ques":"Who flies as Red 5 during the Battle of Scarif?",
"answ":"PEDRIN GAUL",
"answ2":"Pedrin Gaul.",
},
{
"cat":"Mixed Bag",
"ques":"Who voices Admiral Ackbar in The Last Jedi?",
"answ":"TOM KANE",
"answ2":"Tom Kane.",
},
{
"cat":"Mixed Bag",
"ques":"In how many films does the character C-3PO appear?",
"answ":"11",
"answ3":"ELEVEN",
"answ2":"11.",
},
{
"cat":"Mixed Bag",
"ques":"You'll find the Boonta Eve Classic play out in which Star Wars film?",
"answ":"THE PHANTOM MENACE",
"answ3":"PHANTOM MENACE",
"answ2":"The Phantom Menace.",
},
{
"cat":"Mixed Bag",
"ques":"Who voices Mace Windu in the Clone Wars movie?",
"answ":"SAMUEL L JACKSON",
"answ2":"Samuel L. Jackson",
},
{
"cat":"Mixed Bag",
"ques":"Who plays C-3PO in the Star Wars franchise?",
"answ":"ANTHONY DANIELS",
"answ2":"Anthony Daniels.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of the planet destroyed by the Death Star in A New Hope?",
"answ":"ALDERAAN",
"answ2":"Alderaan.",
},
{
"cat":"Mixed Bag",
"ques":"At the beginning of Revenge of the Sith, who has been kidnapped by General Grievous?",
"answ":"CHANCELLOR PALPATINE",
"answ3":"PALPATINE",
"answ2":"Chancellor Palpatine.",
},
{
"cat":"Mixed Bag",
"ques":"In The Last Jedi, who plays the character of DJ?",
"answ":"BENICIO DEL TORO",
"answ2":"Benicio Del Toro.",
},
{
"cat":"Mixed Bag",
"ques":"In The Empire Strikes Back, what character is frozen in Carbonite in Cloud City?",
"answ":"HAN SOLO",
"answ3":"HAN",
"answ2":"Han Solo.",
},
{
"cat":"Mixed Bag",
"ques":"Who plays Queen Amidala in The Phantom Menace?",
"answ":"NATALIE PORTMAN",
"answ2":"Natalie Portman.",
},
{
"cat":"Mixed Bag",
"ques":"Whom is Leia referring to when she says: 'Why you stuck up, half-witted, scruffy-looking nerf herder'?",
"answ":"HAN SOLO",
"answ3":"HAN",
"answ2":"Han Solo.",
},
{
"cat":"Mixed Bag",
"ques":"In A New Hope, which actor provided the voice of Darth Vader?",
"answ":"JAMES EARL JONES",
"answ2":"James Earl Jones.",
},
{
"cat":"Mixed Bag",
"ques":"Who played Rose Tico in The Last Jedi?",
"answ":"KELLY MARIE TRAN",
"answ2":"Kelly Marie Tran.",
},
{
"cat":"Mixed Bag",
"ques":"According to Jedi Code, how many padawans can a Jedi master take on at one time?",
"answ":"1",
"answ3":"ONE",
"answ2":"1.",
},
{
"cat":"Mixed Bag",
"ques":"Before Count Dooku turned to the dark side of the Force, who was his Jedi Master?",
"answ":"YODA",
"answ2":"Yoda.",
},
{
"cat":"Mixed Bag",
"ques":"Who says: 'Help me Obi-Wan Kenobi, you're my only hope'?",
"answ":"LEIA",
"answ3":"PRINCESS LEIA",
"answ2":"Princess Leia.",
},
{
"cat":"Mixed Bag",
"ques":"Who is the Baron Administrator of Cloud City in The Empire Strikes Back?",
"answ":"LANDO CALRISSIAN",
"answ3":"LANDO",
"answ2":"Lando Calrissian.",
},
{
"cat":"Mixed Bag",
"ques":"What planet is ruled from its capital at Bestine?",
"answ":"TATOOINE",
"answ2":"Tatooine.",
},
{
"cat":"Mixed Bag",
"ques":"How many actors have played Obi-Wan Kenobi on the big screen?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Mixed Bag",
"ques":"Garrick Hagon plays which character in A New Hope?",
"answ":"BIGGS DARKLIGHTER",
"answ2":"Biggs Darklighter.",
},
{
"cat":"Mixed Bag",
"ques":"What is the name of Tarkin's Star Destroyer in Rogue One?",
"answ":"EXECUTRIX",
"answ3":"THE EXECUTRIX",
"answ2":"Executrix.",
},
{
"cat":"Mixed Bag",
"ques":"What is the final planet seen at the end of The Rise of Skywalker?",
"answ":"TATOOINE",
"answ2":"Tatooine.",
},
{
"cat":"Mixed Bag",
"ques":"What podracer is known for his record setting Pitdroid team?",
"answ":"ODY MANDRELL",
"answ2":"Ody Mandrell.",
},
{
"cat":"Mixed Bag",
"ques":"What color is Kit Fisto's lightsaber?",
"answ":"GREEN",
"answ2":"Green.",
},
{
"cat":"Mixed Bag",
"ques":"Who flew as Green Leader during the Battle of Endor?",
"answ":"ARVEL CRYNYD",
"answ3":"ARVEL KRINID",
"answ2":"Arvel Crynyd.",
},
{
"cat":"Mixed Bag",
"ques":"Who voices Yoda in The Empire Strikes Back?",
"answ":"FRANK OZ",
"answ2":"Frank Oz.",
},
{
"cat":"Mixed Bag",
"ques":"In how many films does the character Luke Skywalker appear?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
},
{
"cat":"Mixed Bag",
"ques":"Who votes in Padme's stead when she's in hiding after the assassination attempt on her life?",
"answ":"JAR JAR BINKS",
"answ3":"JAR JAR",
"answ2":"Jar Jar.",
},
{
"cat":"Mixed Bag",
"ques":"Who directed Star Wars Episode III: Revenge of the Sith?",
"answ":"GEORGE LUCAS",
"answ2":"George Lucas.",
},
{
"cat":"Mixed Bag",
"ques":"First introduced in The Force Awakens, who voices Maz Kanata?",
"answ":"LUPITA NYONGO",
"answ3":"LUPITA NYONG'O",
"answ2":"Lupita Nyong'o.",
},
{
"cat":"Mixed Bag",
"ques":"Who had the callsign Echo 7 in The Empire Strikes Back?",
"answ":"HAN SOLO",
"answ3":"HAN",
"answ2":"Han Solo.",
},
{
"cat":"Mixed Bag",
"ques":"In Return of the Jedi, what is the first name of the Ewok Leia befriends on Endor?",
"answ":"WICKET",
"answ2":"Wicket.",
},
{
"cat":"Mixed Bag",
"ques":"On what planet was Jabba's Palace located?",
"answ":"TATOOINE",
"answ2":"Tatooine.",
},
{
"cat":"Mixed Bag",
"ques":"Who tells Luke to go to the Dagobah system in The Empire Strikes Back?",
"answ":"OBI WAN KENOBI",
"answ3":"OBI WAN",
"answ2":"Obi-Wan Kenobi.",
},
{
"cat":"Mixed Bag",
"ques":"Who portrayed Ben Kenobi for the first time in A New Hope?",
"answ":"ALEC GUINNESS",
"answ3":"ALEC GUINESS",
"answ2":"Alec Guinness.",
},
{
"cat":"Mixed Bag",
"ques":"In The Phantom Menace, Gunga City is hidden in which lake?",
"answ":"LAKE PAONGA",
"answ2":"Lake Paonga.",
},
{
"cat":"Mixed Bag",
"ques":"In Rogue One, who says the line: 'Congratulations. You are being rescued. Please do not resist.'?",
"answ":"K2SO",
"answ3":"K 2SO",
"answ2":"K-2SO.",
},
{
"cat":"Mixed Bag",
"ques":"The Lanai of Ach-To are better known by what name?",
"answ":"CARETAKERS",
"answ3":"THE CARETAKERS",
"answ2":"Caretakers.",
},
{
"cat":"Mixed Bag",
"ques":"Lewis MacLeod voiced what character in The Phantom Menace?",
"answ":"SEBULBA",
"answ2":"Sebulba.",
},
{
"cat":"Mixed Bag",
"ques":"What villain said: 'Only your hatred can destroy me'?",
"answ":"DARTH VADER",
"answ3":"VADER",
"answ2":"Darth Vader.",
},
{
"cat":"Mixed Bag",
"ques":"In Episode I, Brian Blessed voiced what character?",
"answ":"RUGOR NASS",
"answ3":"BOSS NASS",
"answ2":"Rugor Nass.",
},
{
"cat":"Mixed Bag",
"ques":"Who hired Zam Wesell to try and assassinate Padmé in Attack of the Clones?",
"answ":"JANGO FETT",
"answ2":"Jango Fett.",
},
{
"cat":"Mixed Bag",
"ques":"In Rogue One, Lord Vader has built a fortress on what planet?",
"answ":"MUSTAFAR",
"answ2":"Mustafar.",
},
{
"cat":"Mixed Bag",
"ques":"In The Force Awakens, what is the name of Chewbacca's weapon that Han Solo uses and likes?",
"answ":"BOWCASTER",
"answ2":"Bowcaster.",
},
{
"cat":"Mixed Bag",
"ques":"In The Rise of Skywalker, while playing holochess at the beginning of the film, how old does Poe say Chewbacca is?",
"answ":"250",
"answ3":"250 YEARS",
"answ2":"250.",
},
{
"cat":"Mixed Bag",
"ques":"In The Rise of Skywalker, what character says the line: 'Always. In the shadows. From the very beginning.'?",
"answ":"LEIA",
"answ3":"GENERAL LEIA",
"answ2":"Leia.",
},
];
speedquestion001 = shuffle(speedquestion001);