var competitorlist = [
{
"id": "Schloth",
"lowercase": "Jessica Schloth",
"twitter": "@JessicaSchloth",
"record": "1-2",
"faction": "THE DEN",
"strength1" : "YA Adaptations",
"strength2" : "Romance",
"strength3" : "Sandra Bullock",
"strength4" : "Scarlett Johansson",
"strength5" : "Cameron Diaz",
"strength6" : "Julia Roberts",
"percentage": "60",
"percentage3": "55",
"percentage5": "55",
"strengthpercentage": "70",
"strengthpercentage3": "65",
"strengthpercentage5": "65",
},
{
"id": "Silvestrini",
"lowercase": "Rachel Silvestrini",
"twitter": "@RMSilvestrini",
"record": "0-4",
"faction": "THE DEN",
"strength1" : "Kevin Smith",
"strength2" : "Will Smith",
"strength3" : "Disney",
"strength4" : "Pixar",
"strength5" : "Holiday Movies",
"strength6" : "Adam Sandler",
"percentage": "62",
"percentage3": "57",
"percentage5": "57",
"strengthpercentage": "72",
"strengthpercentage3": "67",
"strengthpercentage5": "67",
},
{
"id": "Young",
"lowercase": "Britney Young",
"twitter": "@ItsBritneyYoung",
"record": "2-2",
"faction": "THE STARS",
"strength1" : "Dance Movies",
"strength2" : "Musicals",
"strength3" : "Disney",
"strength4" : "Pixar",
"strength5" : "Cameron Diaz",
"strength6" : "Meryl Streep",
"percentage": "63",
"percentage3": "58",
"percentage5": "58",
"strengthpercentage": "73",
"strengthpercentage3": "68",
"strengthpercentage5": "68",
},
{
"id": "Hauser",
"lowercase": "Paul Walter Hauser",
"twitter": "@PaulWHauser",
"record": "0-2",
"faction": "USUAL SUSPECTS",
"strength1" : "Sports",
"strength2" : "Christopher Nolan",
"strength3" : "Keanu Reeves",
"strength4" : "Bruce Willis",
"strength5" : "Adam Sandler",
"strength6" : "Comedies",
"percentage": "67",
"percentage3": "62",
"percentage5": "62",
"strengthpercentage": "77",
"strengthpercentage3": "72",
"strengthpercentage5": "72",
},
{
"id": "Gubbins",
"lowercase": "Peggy Gubbins",
"twitter": "@PeggyGubbins",
"record": "1-2",
"faction": "THE DEN",
"strength1" : "Julia Roberts",
"strength2" : "2010s",
"strength3" : "Rom-coms",
"strength4" : "Scarlett Johansson",
"strength5" : "Tom Hanks",
"strength6" : "Cate Blanchett",
"percentage": "65",
"percentage3": "60",
"percentage5": "60",
"strengthpercentage": "75",
"strengthpercentage3": "70",
"strengthpercentage5": "70",
},
{
"id": "White",
"lowercase": "James White",
"twitter": "@G4TOR24",
"record": "2-3",
"faction": "KORRUPTION",
"strength1" : "Disney",
"strength2" : "DreamWorks Animation",
"strength3" : "YA Adaptations",
"strength4" : "Video Game Movies",
"strength5" : "2010s",
"strength6" : "Matthew McConaughey",
"percentage": "68",
"percentage3": "63",
"percentage5": "63",
"strengthpercentage": "78",
"strengthpercentage3": "73",
"strengthpercentage5": "73",
},
{
"id": "Lomis",
"lowercase": "Brother Lomis",
"twitter": "@BrotherLomis",
"record": "1-1",
"faction": "EXCHANGE",
"strength1" : "Christopher Nolan",
"strength2" : "Sly & Arnie",
"strength3" : "Kurt Russell",
"strength4" : "Disaster Movies",
"strength5" : "Kevin Smith",
"strength6" : "2000s",
"percentage": "68",
"percentage3": "63",
"percentage5": "63",
"strengthpercentage": "78",
"strengthpercentage3": "73",
"strengthpercentage5": "73",
},
{
"id": "Kempe",
"lowercase": "Jen Kempe",
"twitter": "@JKMemeQueen",
"record": "1-2",
"faction": "S.W.A.G.",
"strength1" : "Disney",
"strength2" : "Comic Book Movies",
"strength3" : "Animated",
"strength4" : "YA Adaptations",
"strength5" : "Fantasy/Sci-fi",
"strength6" : "Romance",
"percentage": "75",
"percentage3": "70",
"percentage5": "70",
"strengthpercentage": "85",
"strengthpercentage3": "80",
"strengthpercentage5": "80",
},
{
"id": "Duralde",
"lowercase": "Alonso Duralde",
"twitter": "@ADuralde",
"record": "0-2",
"faction": "THE DEN",
"strength1" : "Holiday Movies",
"strength2" : "Classics",
"strength3" : "Cate Blanchett",
"strength4" : "Alfred Hitchcock",
"strength5" : "Festival Darlings",
"strength6" : "John Carpenter",
"percentage": "70",
"percentage3": "65",
"percentage5": "65",
"strengthpercentage": "80",
"strengthpercentage3": "75",
"strengthpercentage5": "75",
},
{
"id": "Harley",
"lowercase":"Nick Harley",
"twitter":"@Mick_Marley",
"record":"0-1",
"faction":"THE STARS",
"strength1":"Dreamworks Animation",
"strength2":"Animated",
"strength3":"YA Adaptations",
"strength4":"Stanley Kubrick",
"strength5":"Tom Hanks",
"strength6":"Martin Scorsese",
"percentage": "73",
"percentage3": "68",
"percentage5": "68",
"strengthpercentage": "83",
"strengthpercentage3": "78",
"strengthpercentage5": "78",
},
{
"id": "Blunden",
"lowercase":"Jacob Blunden",
"twitter": "@JacobBlunden",
"record": "0-2",
"faction": "KORRUPTION",
"strength1" : "YA Adaptations",
"strength2" : "Oscar Movies",
"strength3" : "2010s",
"strength4" : "Comic Book Movies",
"strength5" : "Spy Movies",
"strength6" : "Stanley Kubrick",
"percentage": "77",
"percentage3": "72",
"percentage5": "72",
"strengthpercentage": "87",
"strengthpercentage3": "82",
"strengthpercentage5": "82",
},
{
"id": "Mancuso",
"lowercase":"Vinnie Mancuso",
"twitter": "@VinnieMancuso1",
"record": "1-2",
"faction": "S.W.A.G.",
"strength1" : "YA Adaptations",
"strength2" : "Oscar Movies",
"strength3" : "Kurt Russell",
"strength4" : "Christopher Nolan",
"strength5" : "Spy Movies",
"strength6" : "Matthew McConaughey",
"percentage": "68",
"percentage3": "63",
"percentage5": "63",
"strengthpercentage": "78",
"strengthpercentage3": "73",
"strengthpercentage5": "73",
},
{
"id": "Nemiroff",
"lowercase":"Perri Nemiroff",
"twitter": "@PNemiroff",
"record": "1-3",
"faction": "QUIRKY MERCS",
"strength1" : "Horror",
"strength2" : "Monster Movies",
"strength3" : "Oscar Movies",
"strength4" : "Festival Darlings",
"strength5" : "John Carpenter",
"strength6" : "Thrillers",
"percentage": "75",
"percentage3": "70",
"percentage5": "70",
"strengthpercentage": "85",
"strengthpercentage3": "80",
"strengthpercentage5": "80",
},
{
"id": "Raddus",
"lowercase":"Rick Raddus",
"twitter":"@taylorlcleek",
"record":"3-0",
"faction":"EXCHANGE",
"strength1":"Horror",
"strength2":"Sly & Arnie",
"strength3":"Bruce Willis",
"strength4":"Keanu Reeves",
"strength5":"Kurt Russell",
"strength6":"Crime",
"percentage": "73",
"percentage3": "68",
"percentage5": "68",
"strengthpercentage": "83",
"strengthpercentage3": "78",
"strengthpercentage5": "78",
},
{
"id": "Del Rio",
"lowercase":"David Del Rio",
"twitter":"@David_DelRio",
"record":"4-4",
"faction":"DUNGEON",
"strength1":"Famous Actors and Actresses",
"strength2":"2010s",
"strength3":"Dramas",
"strength4":"Martin Scorsese",
"strength5":"Directors",
"strength6":"Matthew McConaughey",
"percentage": "77",
"percentage3": "72",
"percentage5": "72",
"strengthpercentage": "87",
"strengthpercentage3": "82",
"strengthpercentage5": "82",
},
{
"id": "Alvarez",
"lowercase":"Frankie Alvarez",
"twitter":"@FAlvarez8085",
"record":"2-1",
"faction":"USUAL SUSPECTS",
"strength1":"Alfred Hitchcock",
"strength2":"Classics",
"strength3":"Spy Movies",
"strength4":"Martin Scorsese",
"strength5":"John Carpenter",
"strength6":"Keanu Reeves",
"percentage": "75",
"percentage3": "70",
"percentage5": "70",
"strengthpercentage": "85",
"strengthpercentage3": "80",
"strengthpercentage5": "80",
},
{
"id": "Lieberman",
"lowercase":"Ty Lieberman",
"twitter":"@tyler_lieberman",
"record":"2-2",
"faction":"EXCHANGE",
"strength1":"Horror",
"strength2":"Famous Actors and Actresses",
"strength3":"Cate Blanchett",
"strength4":"Meryl Streep",
"strength5":"Comedies",
"strength6":"Dance Movies",
"percentage": "77",
"percentage3": "72",
"percentage5": "72",
"strengthpercentage": "87",
"strengthpercentage3": "82",
"strengthpercentage5": "82",
},
{
"id": "Frabetti",
"lowercase":"Paige Frabetti",
"twitter":"@frontpaigenews9",
"record":"3-2",
"faction":"USUAL SUSPECTS",
"strength1":"Quentin Tarantino",
"strength2":"2010s",
"strength3":"Romance",
"strength4":"Meryl Streep",
"strength5":"Julia Roberts",
"strength6":"Matthew McConaughey",
"percentage": "78",
"percentage3": "73",
"percentage5": "73",
"strengthpercentage": "88",
"strengthpercentage3": "83",
"strengthpercentage5": "83",
},
{
"id": "Tom",
"lowercase":"Tom",
"twitter":"@startthemachine",
"record":"2-1",
"faction":"THE DEN",
"strength1":"Eddie Murphy",
"strength2":"James Bond",
"strength3":"Monster Movies",
"strength4":"Spy Movies",
"strength5":"Julia Roberts",
"strength6":"John Carpenter",
"percentage": "80",
"percentage3": "75",
"percentage5": "75",
"strengthpercentage": "90",
"strengthpercentage3": "85",
"strengthpercentage5": "85",
},
{
"id": "Smith",
"lowercase":"Kevin Smith",
"twitter":"@ThatKevinSmith",
"record":"3-1",
"faction":"QUIRKY MERCS",
"strength1":"Kevin Smith",
"strength2":"Comedies",
"strength3":"Tom Cruise",
"strength4":"Adam Sandler",
"strength5":"Directors",
"strength6":"Comic Book Movies",
"percentage": "80",
"percentage3": "75",
"percentage5": "75",
"strengthpercentage": "90",
"strengthpercentage3": "85",
"strengthpercentage5": "85",
},
{
"id": "Kan",
"lowercase":"Jeffrey Kan",
"twitter":"@TheKingKan",
"record":"2-1",
"faction":"EXCHANGE",
"strength1":"Pixar",
"strength2":"Disney",
"strength3":"2010s",
"strength4":"YA Adaptations",
"strength5":"Comic Book Movies",
"strength6":"Fantasy/Sci-fi",
"percentage": "81",
"percentage3": "76",
"percentage5": "76",
"strengthpercentage": "91",
"strengthpercentage3": "86",
"strengthpercentage5": "86",
},
{
"id": "Horowitz",
"lowercase":"Josh Horowitz",
"twitter":"@joshuahorowitz",
"record":"3-1",
"faction":"QUIRKY MERCS",
"strength1":"Pixar",
"strength2":"Oscar Movies",
"strength3":"Festival Darlings",
"strength4":"Famous Actors and Actresses",
"strength5":"Dramas",
"strength6":"Audrey Hepburn",
"percentage": "81",
"percentage3": "76",
"percentage5": "76",
"strengthpercentage": "91",
"strengthpercentage3": "86",
"strengthpercentage5": "86",
},
{
"id": "Bancroft",
"lowercase":"Jacoby Bancroft",
"twitter":"@jbancroft815",
"record":"1-2",
"faction":"QUIRKY MERCS",
"strength1":"Pixar",
"strength2":"DreamWorks Animation",
"strength3":"Animated",
"strength4":"Quentin Tarantino",
"strength5":"Clint Eastwood",
"strength6":"2010s",
"percentage": "81",
"percentage3": "76",
"percentage5": "76",
"strengthpercentage": "91",
"strengthpercentage3": "86",
"strengthpercentage5": "86",
},
{
"id": "Bateman",
"lowercase": "Ben Bateman",
"twitter": "@benbatemanmedia",
"record": "14-9",
"faction": "DUNGEON",
"strength1" : "Movie Release Dates",
"strength2" : "Oscar Movies",
"strength3" : "Action/Adventure",
"strength4" : "Denzel Washington",
"strength5" : "Christopher Nolan",
"strength6" : "Julia Roberts",
"percentage": "82",
"percentage3": "77",
"percentage5": "77",
"strengthpercentage": "92",
"strengthpercentage3": "87",
"strengthpercentage5": "87",
},
{
"id": "Newman",
"lowercase": "Griffin Newman",
"twitter": "@GriffLightning",
"record": "7-1",
"faction": "EXCHANGE",
"strength1" : "Eddie Murphy",
"strength2" : "2000s",
"strength3" : "Directors",
"strength4" : "John Carpenter",
"strength5" : "Christopher Nolan",
"strength6" : "Denzel Washington",
"percentage": "83",
"percentage3": "78",
"percentage5": "78",
"strengthpercentage": "93",
"strengthpercentage3": "88",
"strengthpercentage5": "88",
},
{
"id": "McKee",
"lowercase": "Marisol McKee",
"twitter": "@Marisol_Miriah",
"record": "8-1",
"faction": "KORRUPTION",
"strength1" : "Black Cinema",
"strength2" : "Meryl Streep",
"strength3" : "Denzel Washington",
"strength4" : "Eddie Murphy",
"strength5" : "Audrey Hepburn",
"strength6" : "Musicals",
"percentage": "84",
"percentage3": "79",
"percentage5": "79",
"strengthpercentage": "94",
"strengthpercentage3": "89",
"strengthpercentage5": "89",
},
{
"id": "Murrell",
"lowercase": "Dan Murrell",
"twitter": "@MurrellDan",
"record": "20-8",
"faction": "DUNGEON",
"strength1" : "Steven Spielberg",
"strength2" : "Comic Book Movies",
"strength3" : "Oscar Movies",
"strength4" : "2010s",
"strength5" : "Tim Burton",
"strength6" : "Stanley Kubrick",
"percentage": "86",
"percentage3": "81",
"percentage5": "81",
"strengthpercentage": "96",
"strengthpercentage3": "91",
"strengthpercentage5": "91",
},
{
"id": "Erwin",
"lowercase": "Ethan Erwin",
"twitter": "@MrEthanErwin",
"record": "16-7",
"faction": "USUAL SUSPECTS",
"strength1" : "2000s",
"strength2" : "Directors",
"strength3" : "Tom Cruise",
"strength4" : "80s",
"strength5" : "Martin Scorsese",
"strength6" : "Kurt Russell",
"percentage": "85",
"percentage3": "80",
"percentage5": "80",
"strengthpercentage": "95",
"strengthpercentage3": "90",
"strengthpercentage5": "90",
},
];