var whosaidit = [
{
"cat":"Who said it?",
"ques":"Who said: 'Have you ever danced with the devil in the pale moonlight'?",
"answ":"THE JOKER",
"answ3":"JOKER",
"answ2":"The Joker.",
},
{
"cat":"Who said it?",
"ques":"Which MCU character says the line: 'I am taking a shower and you're gonna join me'?",
"answ":"PEPPER POTTS",
"answ2":"Pepper Potts.",
},
{
"cat":"Who said it?",
"ques":"Which Middle Earth character said: 'I know what I must do, it's just that I'm afraid to do it'?",
"answ":"FRODO",
"answ2":"Frodo.",
},
{
"cat":"Who said it?",
"ques":"Which Batman villain said: 'Ah the direct approach, I admire that in a man with a mask'?",
"answ":"THE PENGUIN",
"answ3":"OSWALD COBBLEPOT",
"answ2":"The Penguin.",
},
{
"cat":"Who said it?",
"ques":"What graphic novel adaptation begins with the line: 'I was cast into being in the winter of 1795'?",
"answ":"I FRANKENSTEIN",
"answ2":"I Frankenstein.",
},
{
"cat":"Who said it?",
"ques":"Which dystopian film features the line: 'Denial is the most predictable of human responses, but rest assured this will be the sixth time we have destroyed it, and we have become exceedingly efficient at it?'",
"answ":"THE MATRIX RELOADED",
"answ3":"MATRIX RELOADED",
"answ2":"The Matrix Reloaded.",
},
{
"cat":"Who said it?",
"ques":"In what film will you hear Lex Luthor say: 'I just want what Prometheus wanted'?",
"answ":"SUPERMAN RETURNS",
"answ2":"Superman Returns.",
},
{
"cat":"Who said it?",
"ques":"Which 2000s comic book film has the line: 'She will always be mine and I will always be hers. She owns me, body and soul. She is the love of my life. She's my city.'?",
"answ":"THE SPIRIT",
"answ2":"The Spirit.",
},
{
"cat":"Who said it?",
"ques":"In what 2000 film will you hear the words: 'Six weeks ago I was ordinary and pathetic. Just like you. Who am I now? Account manager? Assassin?'",
"answ":"WANTED",
"answ2":"Wanted.",
},
{
"cat":"Who said it?",
"ques":"Which Men in Black film features the quote: 'You've never been in love have you? I'm not making fun. I'm genuinely asking. You've never once abandoned logic for passion'?",
"answ":"MEN IN BLACK INTERNATIONAL",
"answ2":"Men in Black: International.",
},
{
"cat":"Who said it?",
"ques":"Which character says the line: 'What we some kinda...Suicide Squad'?",
"answ":"DEADSHOT",
"answ2":"Deadshot.",
},
{
"cat":"Who said it?",
"ques":"Which Star Trek hero said: 'The line must be drawn here! This far, no further! And I will make them pay for what they've done!",
"answ":"PICARD",
"answ3":"JEAN LUC PICARD",
"answ2":"Jean-Luc Picard.",
},
{
"cat":"Who said it?",
"ques":"What Middle Earth character said: 'Death is just another path, one that we all must take.'?",
"answ":"GANDALF",
"answ2":"Gandalf.",
},
{
"cat":"Who said it?",
"ques":"Which adventurous hero said the line: 'We do not follow maps to buried treasure, and 'X' never, ever marks the spot.'?",
"answ":"INDIANA JONES",
"answ2":"Indiana Jones.",
},
{
"cat":"Who said it?",
"ques":"What DC villain said: 'The only morality in a cruel world is chance.'?",
"answ":"HARVEY DENT",
"answ3":"TWO FACE",
"answ2":"Harvey Dent/Two-Face.",
},
{
"cat":"Who said it?",
"ques":"What DC villain said: 'We all have our little faults. Mine's in California.'?",
"answ":"LEX LUTHOR",
"answ2":"Lex Luthor.",
},
{
"cat":"Who said it?",
"ques":"Which Star Trek character said: 'Logic is the beginning of wisdom, not the end.'?",
"answ":"SPOCK",
"answ2":"Spock.",
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'I'm gonna die surrounded by the biggest idiots in the galaxy.'?",
"answ":"GAMORA",
"answ2":"Gamora.",
},
{
"cat":"Who said it?",
"ques":"What DC character said: 'One misses the days when one's biggest concern is exploding wind-up penguins'?",
"answ":"ALFRED PENNYWORTH",
"answ3":"ALFRED",
"answ2":"Alfred Pennyworth.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'That's my secret, Cap. I'm always angry.'?",
"answ":"BRUCE BANNER",
"answ3":"HULK",
"answ2":"Bruce Banner/Hulk.",
},
{
"cat":"Who said it?",
"ques":"Which hero said: 'Look, I'm here to help. But it has to be on my own terms.'?",
"answ":"SUPERMAN",
"answ2":"Superman.",
},
{
"cat":"Who said it?",
"ques":"What Star Wars character said: 'You're nothing. But not to me.'?",
"answ":"KYLO REN",
"answ2":"Kylo Ren.",
},
{
"cat":"Who said it?",
"ques":"What DCEU character said: 'I live underground. Y'all are just tourists.'?",
"answ":"KILLER CROC",
"answ2":"Killer Croc.",
},
{
"cat":"Who said it?",
"ques":"Which character says the following line: 'Spartans! Ready your breakfast and eat hearty... For tonight we dine in hell!'?",
"answ":"LEONIDAS",
"answ3":"KING LEONIDAS",
"answ2":"Leonidas.",
},
{
"cat":"Who said it?",
"ques":"Which DC villain said: 'Would you like to see my mask? I use it in my experiments.'?",
"answ":"SCARECROW",
"answ3":"JONATHAN CRANE",
"answ2":"Scarecrow.",
},
{
"cat":"Who said it?",
"ques":"What Marvel hero said: 'Nature made me a freak. Man made me a weapon. And God made it last too long.'",
"answ":"WOLVERINE",
"answ2":"Wolverine.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'Do not pity the dead, Harry. Pity the living, and, above all those who live without love.'?",
"answ":"ALBUS DUMBLEDORE",
"answ3":"DUMBLEDORE",
"answ2":"Albus Dumbledore.",
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'He may have been your father, boy, but he wasn’t your daddy'?",
"answ":"YONDU",
"answ3":"YONDU UDONTA",
"answ2":"Yondu.",
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Sir, I'm gonna have to ask you to exit the donut'?",
"answ":"FURY",
"answ3":"NICK FURY",
"answ2":"Nick Fury.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'You shouldn’t have killed my mom and squished my Walkman'?",
"answ":"PETER QUILL",
"answ3":"STAR LORD",
"answ2":"Star-Lord/Peter Quill.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'Please don't make the super-suit green... or animated!'?",
"answ":"DEADPOOL",
"answ2":"Deadpool.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'If you're nothing without the suit, then you shouldn't have it'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark/Iron Man.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'You either die a hero, or you live long enough to see yourself become the villain'?",
"answ":"HARVEY DENT",
"answ3":"TWO FACE",
"answ2":"Harvey Dent/Two-Face.",
},
{
"cat":"Who said it?",
"ques":"What character said 'Avengers Assemble!' in Avengers: Endgame?",
"answ":"CAPTAIN AMERICA",
"answ3":"STEVE ROGERS",
"answ2":"Captain America.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'I've mastered the ability of standing so incredibly still, that I become invisible to the eye. Watch.'?",
"answ":"DRAX THE DESTROYER",
"answ3":"DRAX",
"answ2":"Drax.",
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Piss off, ghost!'?",
"answ":"KORG",
"answ2":"Korg.",
},
{
"cat":"Who said it?",
"ques":"What famous character said: 'It's not the years, honey, it's the mileage.'?",
"answ":"INDIANA JONES",
"answ2":"Indiana Jones.",
},
{
"cat":"Who said it?",
"ques":"In The Fellowship of the Ring, what character says: 'They will find you. They will take the ring. And you will beg for death before the end!'?",
"answ":"BOROMIR",
"answ2":"Boromir.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'Mankind has always feared what it doesn't understand'?",
"answ":"MAGNETO",
"answ3":"ERIK LEHNSHERR",
"answ2":"Magneto.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'Do you know what happens to a toad when it's struck by lightning? The same thing that happens to everything else.'?",
"answ":"STORM",
"answ2":"Storm.",
},
{
"cat":"Who said it?",
"ques":"In Attack of the Clones, what character said 'This party's over.'?",
"answ":"MACE WINDU",
"answ2":"Mace Windu.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'We are the future, Charles. They no longer matter.'?",
"answ":"ERIK LEHNSHERR",
"answ3":"MAGNETO",
"answ2":"Magneto.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'From here you will witness the final destruction of the Alliance'?",
"answ":"EMPEROR PALPATINE",
"answ3":"PALPATINE",
"answ2":"Emperor Palpatine.",
},
{
"cat":"Who said it?",
"ques":"In Return of the Jedi, who says: 'The shield is down! Commence attack on the Death Star's main reactor'?",
"answ":"ADMIRAL ACKBAR",
"answ3":"ACKBAR",
"answ2":"Admiral Ackbar.",
},
{
"cat":"Who said it?",
"ques":"Who said: 'You know who I am. You don't know where I am. And you'll never see me coming.'?",
"answ":"THE MANDARIN",
"answ3":"MANDARIN",
"answ2":"The Mandarin.",
},
{
"cat":"Who said it?",
"ques":"In the MCU who said: 'I am not some starry-eyed waif here to succumb to your... your pelvic sorcery'?",
"answ":"GAMORA",
"answ2":"Gamora.",
},
];
var r2Q10 = [
{
"cat":"Who said it?",
"ques":"What DCEU character said: 'I can save today, you can save the world.'?",
"answ":"STEVE TREVOR",
"answ2":"Steve Trevor.",
"option":["Steve Trevor", "Batman", "Cyborg", "Mera"],
},
{
"cat":"Who said it?",
"ques":"What wizard said: 'true courage is about knowing not when to take a life, but when to spare one.'?",
"answ":"GANDALF",
"answ2":"Gandalf.",
"option":["Gandalf", "Dumbledore", "Saruman", "Minerva McGonagall"],
},
{
"cat":"Who said it?",
"ques":"In the Star Wars prequels, who tells Anakin: 'We'll watch your career with great interest.'?",
"answ":"PALPATINE",
"answ3":"CHANCELLOR PALPATINE",
"answ2":"Palpatine.",
"option":["Palpatine", "Qui-Gon Jinn", "Mace Windu", "Yoda"],
},
{
"cat":"Who said it?",
"ques":"What Star Wars character said: 'Well, if droids could think, there’d be none of us here, would there'?",
"answ":"OBI WAN",
"answ3":"OBI WAN KENOBI",
"answ2":"Obi-Wan Kenobi.",
"option":["Obi-Wan Kenobi", "Mace Windu", "Luke Skywalker", "Qui-Gon Jinn"],
},
{
"cat":"Who said it?",
"ques":"What villain said: 'I believe whatever doesn't kill you, simply makes you stranger.'?",
"answ":"JOKER",
"answ3":"THE JOKER",
"answ2":"The Joker.",
"option":["The Joker", "Penguin", "The Riddler", "Lex Luthor"],
},
{
"cat":"Who said it?",
"ques":"Who said the famous line: 'I have a bad feeling about this' in The Force Awakens?",
"answ":"HAN",
"answ3":"HAN SOLO",
"answ2":"Han Solo.",
"option":["Han Solo", "Rey", "Luke Skywalker", "Finn"],
},
{
"cat":"Who said it?",
"ques":"What Star Wars character said: 'Bounty hunters. We don't need their scum.'?",
"answ":"ADMIRAL PIETT",
"answ3":"ADMIRAL PIET",
"answ2":"Admiral Piett.",
"option":["Admiral Piett", "General Veers", "Emperor Palpatine", "General Motti"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'Do you know the Klingon proverb that tells us revenge is a a dish that is best served cold? It's very cold in space.'?",
"answ":"KHAN",
"answ2":"Khan.",
"option":["Khan", "Sybok", "Nero", "Kruge"],
},
{
"cat":"Who said it?",
"ques":"What hero comic book character said: 'My weakness. Small knives. Anything but knives!'?",
"answ":"SPIDER MAN",
"answ3":"SPIDERMAN",
"answ2":"Spider-Man.",
"option":["Spider-Man", "Hit-Girl", "Deadpool", "Iron Man"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'I can teach you how to bewitch the mind and ensnare the senses.'?",
"answ":"SEVERUS SNAPE",
"answ3":"SNAPE",
"answ2":"Severus Snape.",
"option":["Severus Snape", "Darth Sidious", "Voldemort", "Saruman"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'Citizens of Xandar, behold your guardians of the galaxy! What fruit have they wrought.'?",
"answ":"RONAN THE ACCUSER",
"answ3":"RONAN",
"answ2":"Ronan the Accuser.",
"option":["Ronan the Accuser", "Star-Lord", "Rocket Raccoon", "Yondu"],
},
{
"cat":"Who said it?",
"ques":"What villain said: 'You do not know pain. You do not know fear. You will taste man-flesh.'?",
"answ":"SARUMAN",
"answ2":"Saruman.",
"option":["Saruman", "Thanos", "Steppenwolf", "Dormammu"],
},
{
"cat":"Who said it?",
"ques":"What film begins with the narration: 'Who am I? You sure you want to know? The story of my life is not for the faint of heart.'?",
"answ":"SPIDER MAN",
"answ2":"Spider-Man.",
"option":["Spider-Man", "Deadpool", "The Wolverine", "Blade"],
},
{
"cat":"Who said it?",
"ques":"What villain said: 'You are here because the outside world rejects you. This is your family, I am your father.'?",
"answ":"THE SHREDDER",
"answ3":"SHREDDER",
"answ2":"The Shredder.",
"option":["The Shredder", "The Motherf*cker", "Saruman", "The Penguin"],
},
{
"cat":"Who said it?",
"ques":"In Rogue One, while on Eadu, Chirrut asks Baze if Cassian looks like a what'?",
"answ":"KILLER",
"answ2":"Killer.",
"option":["Killer", "Murderer", "Friend", "Coward"],
},
{
"cat":"Who said it?",
"ques":"What DC hero said: 'I'm no leader. I came because I had no choice. I came to save my home, and the people that I love.'?",
"answ":"AQUAMAN",
"answ2":"Aquaman.",
"option":["Aquaman", "The Flash", "Wonder Woman", "Superman"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'I am on nobody's side, because nobody is ony my side.'?",
"answ":"TREEBEARD",
"answ2":"Treebeard.",
"option":["Treebeard", "Steve Trevor", "Valkyrie", "M'Baku"],
},
{
"cat":"Who said it?",
"ques":"What hero said: 'If we can't accept limitations, we're no better than the bad guys.'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Captain America", "Dr. Manhattan", "Batman"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Well now I'm standing. Happy? We're all standing now. Bunch of jackasses, standing in a circle.'?",
"answ":"ROCKET",
"answ3":"ROCKET RACCOON",
"answ2":"Rocket.",
"option":["Rocket", "Star-Lord", "Ant-Man", "Iron Man"],
},
{
"cat":"Who said it?",
"ques":"What Harry Potter character said: 'We've all got both light and darkness inside us. What matters is the part we choose to act on. That's who we really are.'?",
"answ":"SIRIUS BLACK",
"answ2":"Sirius Black.",
"option":["Sirius Black", "Albus Dumbledore", "Remus Lupin", "Arthur Weasley"],
},
{
"cat":"Who said it?",
"ques":"What Lord of the Rings character said: 'Even the smallest person can change the course of the future.'?",
"answ":"GALADRIEL",
"answ2":"Galadriel.",
"option":["Galadriel", "Gandalf", "Boromir", "Legolas"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'I do anything and everything Mr. Stark requires. Including occasionally taking out the trash. Will that be all?'",
"answ":"PEPPER POTTS",
"answ3":"PEPPER POTS",
"answ2":"Pepper Potts.",
"option":["Pepper Potts", "Happy Hogan", "Vision", "Peter Parker"],
},
{
"cat":"Who said it?",
"ques":"In Rogue One, who said: 'There is more than one kind of prison, Captain. I sense that you carry yours wherever you go.'?",
"answ":"CHIRRUT",
"answ3":"CHIRUT",
"answ2":"Chirrut.",
"option":["Chirrut", "Baze", "Jyn", "General Dodonna"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'If we can't protect the Earth, you can be damn sure we'll avenge it.'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Steve Rogers", "Black Widow", "Hawkeye"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'Nothing goes over my head. My reflexes are too fast. I would catch it.'?",
"answ":"DRAX THE DESTROYER",
"answ3":"DRAX",
"answ2":"Drax.",
"option":["Drax", "Rocket Raccoon", "The Flash", "Superman"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'If you say one more word, I’ll feed you to my children! I’m kidding. We’re vegetarians.'?",
"answ":"MBAKU",
"answ3":"M'BAKU",
"answ2":"M'Baku.",
"option":["M'Baku", "Ego", "Talos", "The Grandmaster"],
},
{
"cat":"Who said it?",
"ques":"What hero said: 'I don't want to kill anyone. I don't like bullies. I don't care where they're from.'",
"answ":"STEVE ROGERS",
"answ3":"CAPTAIN AMERICA",
"answ2":"Steve Rogers.",
"option":["Steve Rogers", "Tony Stark", "Bruce Banner", "Peter Parker"],
},
{
"cat":"Who said it?",
"ques":"What DCEU character said: 'Normal is a setting on the dryer. People like us, we don't get normal!'?",
"answ":"HARLEY QUINN",
"answ2":"Harley Quinn.",
"option":["Harley Quinn", "Wonder Woman", "Mera", "Amanda Waller"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Dude, you’re embarrassing me in front of the wizards.'?",
"answ":"IRON MAN",
"answ3":"TONY STARK",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Thor", "Star-Lord", "Ant-Man"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'The hardest choices require the strongest wills.'?",
"answ":"THANOS",
"answ2":"Thanos.",
"option":["Thanos", "General Zod", "Lex Luthor", "Doctor Doom"],
},
{
"cat":"Who said it?",
"ques":"What LOTR character said: 'Nine companions. So be it. You shall be the fellowship of the ring.'?",
"answ":"ELROND",
"answ2":"Elrond.",
"option":["Elrond", "Gandalf", "Aragorn", "Legolas"],
},
{
"cat":"Who said it?",
"ques":"In The Hobbit: An Unexpected Journey, who said: 'Loyalty, honour, a willing heart... I can ask no more than that.'?",
"answ":"THORIN",
"answ2":"Thorin.",
"option":["Thorin", "Balin", "Gandalf", "Elrond"],
},
{
"cat":"Who said it?",
"ques":"What MCU villain said: 'You need't have com so far Asgardian. Death would have come to you soon enough.'?",
"answ":"MALEKITH",
"answ2":"Malekith.",
"option":["Malekith", "Surtur", "Thanos", "Laufey"],
},
{
"cat":"Who said it?",
"ques":"What MCU villain said: 'People think in terms of good and evil, but really, time is the true enemy of us all. Time kills everything.'?",
"answ":"KAECILIUS",
"answ2":"Kaecilius.",
"option":["Kaecilius", "Thanos", "Ronan the Accuser", "Dormammu"],
},
{
"cat":"Who said it?",
"ques":"What DCEU character said: 'Love your perfume. What is that? The stench of death?'",
"answ":"HARLEY QUINN",
"answ3":"HARLEY QUIN",
"answ2":"Harley Quinn.",
"option":["Harley Quinn", "Deadshot", "Captain Boomerang", "The Flash"],
},
{
"cat":"Who said it?",
"ques":"Which DC superhero said: 'Sorry I've been away so long. I won't let you down again.'?",
"answ":"SUPERMAN",
"answ2":"Superman.",
"option":["Superman", "Wonder Woman", "Batman", "Aquaman"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said 'We have a Hulk' in Infinity War?",
"answ":"LOKI",
"answ2":"Loki.",
"option":["Loki", "Black Widow", "Captain America", "Iron Man"],
},
{
"cat":"Who said it?",
"ques":"In what comic book film does the villain say: 'Now you ask me what I am. I am the bringer of the tide, I am the wave that will clean this unclean world'?",
"answ":"PRIEST",
"answ2":"Priest.",
"option":["Priest", "Bloodshot", "Polar", "Spawn"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Why would I put my finger on his throat'?",
"answ":"DRAX",
"answ3":"DRAX THE DESTROYER",
"answ2":"Drax.",
"option":["Drax", "Thor", "Rocket Raccoon", "Star-Lord"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'I know what it's like to lose. To feel so desperately that you're right, yet to fail nonetheless. It's frightening, turns the legs to jelly.'?",
"answ":"THANOS",
"answ2":"Thanos.",
"option":["Thanos", "Gandalf", "Batman", "Captain America"],
},
{
"cat":"Who said it?",
"ques":"What Marvel character said: 'Just because someone stumbles and loses their way doesn't mean that they're lost forever'?",
"answ":"PROFESSOR X",
"answ3":"CHARLES XAVIER",
"answ2":"Professor X/Charles Xavier.",
"option":["Professor X", "Rogue", "Spider-Man", "Storm"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'It's not who I am underneath, but what I do that defines me'?",
"answ":"BATMAN",
"answ3":"BRUCE WAYNE",
"answ2":"Batman.",
"option":["Batman", "Spider-Man", "Iron Man", "Black Panther"],
},
{
"cat":"Who said it?",
"ques":"What Lord of the Rings character said: 'I don't want to be in a battle, but waiting on the edge of one I can't escape is even worse.'?",
"answ":"PIPPIN",
"answ3":"PEREGRIN TOOK",
"answ2":"Pippin.",
"option":["Pippin", "Sam", "Frodo", "Merry"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'Even when you had two eyes, you'd see only half the picture.'?",
"answ":"ODIN",
"answ2":"Odin.",
"option":["Odin", "Thanos", "Hela", "Loki"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'You know all those dangerous mutants you hear about in the news? I'm the worst one.'?",
"answ":"PYRO",
"answ2":"Pyro.",
"option":["Pyro", "Sabretooth", "Magneto", "Juggernaut"],
},
{
"cat":"Who said it?",
"ques":"Who said: 'Fear leads to anger. Anger leads to hate. Hate leads to suffering.'?",
"answ":"YODA",
"answ2":"Yoda.",
"option":["Yoda", "Obi-Wan Kenobi", "Qui-Gon Jinn", "Mace Windu"],
},
{
"cat":"Who said it?",
"ques":"Which character is the first to say the line: 'I love you 3000' in Avengers Endgame?",
"answ":"MORGAN STARK",
"answ3":"MORGAN",
"answ2":"Morgan Stark.",
"option":["Morgan Stark", "Happy Hogan", "Tony Stark", "Pepper Potts"],
},
{
"cat":"Who said it?",
"ques":"What Star Wars character said: 'Don't call me a mindless philosopher, you overweight glob of grease.'",
"answ":"C3PO",
"answ3":"C 3PO",
"answ2":"C-3PO.",
"option":["C-3PO", "Luke Skywalker", "Lando Calrissian", "Han Solo"],
},
{
"cat":"Who said it?",
"ques":"What MCU character said: 'This isn't freedom, this is fear.'",
"answ":"CAPTAIN AMERICA",
"answ3":"STEVE ROGERS",
"answ2":"Captain America.",
"option":["Captain America", "Thor", "Hawkeye", "Black Widow"],
},
{
"cat":"Who said it?",
"ques":"What Star Wars character said: 'You can't stop change any more than you can stop the suns from setting'?",
"answ":"SHMI SKYWALKER",
"answ3":"SHMI",
"answ2":"Shmi Skywalker.",
"option":["Shmi Skywalker", "Luke Skywalker", "Obi-Wan Kenobi", "Mace Windu"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'This is the fight of our lives and we're going to win. Whatever it takes.'",
"answ":"CAPTAIN AMERICA",
"answ3":"STEVE ROGERS",
"answ2":"Captain America.",
"option":["Captain America", "Phil Coulson", "Tony Stark", "Nick Fury"],
},
{
"cat":"Who said it?",
"ques":"Which Marvel villain said the quote: 'And from the ashes of their world, we'll build a better one'",
"answ":"APOCALYPSE",
"answ3":"APOCALYPS",
"answ2":"Apocalypse.",
"option":["Apocalypse", "Thanos", "Ronan the Accuser", "Dormammu"],
},
{
"cat":"Who said it?",
"ques":"Which character said the line: 'The Desolation of Smaug' in the film The Desolation of Smaug?",
"answ":"BALIN",
"answ2":"Balin.",
"option":["Balin", "Bilbo", "Gandalf", "Thorin"],
},
{
"cat":"Who said it?",
"ques":"What DC villain said: 'The more fear you make, the more loot you take.'?",
"answ":"LEX LUTHOR",
"answ2":"Lex Luthor.",
"option":["Lex Luthor", "Scarecrow", "Two-Face", "Penguin"],
},
{
"cat":"Who said it?",
"ques":"What MCU villain said: 'You know who I am. You don't know where I am. And you'll never see me coming.'?",
"answ":"THE MANDARIN",
"answ3":"MANDARIN",
"answ2":"The Mandarin.",
"option":["The Mandarin", "Killmonger", "Mysterio", "Ultron"],
},
{
"cat":"Who said it?",
"ques":"What MCU villain said: 'I think you're confusing peace with quiet.'?",
"answ":"ULTRON",
"answ2":"Ultron.",
"option":["Ultron", "Thanos", "Ronan the Accuser", "Ebony Maw"],
},
{
"cat":"Who said it?",
"ques":"Which DCEU film has the line: 'A good death is its own reward'?",
"answ":"MAN OF STEEL",
"answ2":"Man of Steel.",
"option":["Man of Steel", "Suicide Squad", "Batman V Superman", "Birds of Prey"],
},
{
"cat":"Who said it?",
"ques":"What X-Men film begins with the line: 'Mutants, born with extraordinary abilities. And yet still they are children stumbling in the dark, searching for guidance.'?",
"answ":"X MEN APOCALYPSE",
"answ2":"X-Men: Apocalypse.",
"option":["X-Men: Apocalypse", "X-Men: Dark Phoenix", "X-Men: First Class", "X-Men: Days of Future Past"],
},
{
"cat":"Who said it?",
"ques":"Which MCU film begins with the line: 'Things are never going to be the same now. I mean look at this.'?",
"answ":"SPIDER MAN HOMECOMING",
"answ3":"SPIDERMAN HOMECOMING",
"answ2":"Spider-Man: Homecoming.",
"option":["Spider-Man: Homecoming", "Ant-Man & The Wasp", "Avengers: Infinity War", "Avengers: Endgame"],
},
{
"cat":"Who said it?",
"ques":"In Harry Potter and the Chamber of Secrets, a second message written in blood says: 'Her ___ will lie in the chamber forever.'",
"answ":"SKELETON",
"answ2":"Skeleton.",
"option":["Skeleton", "Remains", "Body", "Corpse"],
},
{
"cat":"Who said it?",
"ques":"What graphic novel film has the line: 'Remember us. As simple an order as a king can give. Remember why we died.'?",
"answ":"300",
"answ2":"300.",
"option":["300", "A History of Violence", "V for Vendetta", "Road to Perdition"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'Asleep for the danger, awake for the money, as per frickin' usual.'?",
"answ":"ROCKET RACCOON",
"answ3":"ROCKET",
"answ2":"Rocket Raccoon.",
"option":["Rocket Raccoon", "Tony Stark", "Ant-Man", "Star-Lord"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'You like that, Westworld? That's the thing about smart guys, we always cover our ass'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Hank Pym", "Bruce Banner", "Falcon"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'I told you, I don't want to join your super-secret boy band'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Ant-Man", "Hawkeye", "Star-Lord"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'One thing I've proven is that you can count on me to pleasure myself'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Thor", "Ant-Man", "Star-Lord"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'Genius. Billionaire. Playboy. Philanthropist.'?",
"answ":"TONY STARK",
"answ3":"IRON MAN",
"answ2":"Tony Stark.",
"option":["Tony Stark", "Hank Pym", "Aldrich Killian", "Doctor Strange"],
},
{
"cat":"Who said it?",
"ques":"Which MCU character said: 'Well, I was born yesterday'?",
"answ":"VISION",
"answ2":"Vision.",
"option":["Vision", "Thanos", "The Collector", "Captain America"],
},
];
whosaidit = shuffle(whosaidit);
r2Q10 = shuffle(r2Q10);