var jurassicpark = [
{
"cat":"Jurassic Park",
"ques":"Who plays paleontologist Dr. Alan Grant in the original Jurassic Park?",
"answ":"SAM NEILL",
"answ2":"Sam Neill.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, what Disneyland theme park attraction does Malcolm reference when he says 'if the ride breaks down the inhabitants inside won't eat the tourists'?",
"answ":"PIRATES OF THE CARIBBEAN",
"answ2":"Pirates of the Caribbean.",
},
{
"cat":"Jurassic Park",
"ques":"Which film in the Jurassic Park franchise features appearances from B.D. Wong, Jeff Goldblum and Toby Jones?",
"answ":"FALLEN KINGDOM",
"answ3":"JURASSIC WORLD FALLEN KINGDOM",
"answ2":"Jurassic World: Fallen Kingdom.",
},
{
"cat":"Jurassic Park",
"ques":"How many composers have contributed scores to the Jurassic Park franchise?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Jurassic Park",
"ques":"The characters of Nick Van Owen and Roland Tembo appear in which Jurassic Park film?",
"answ":"THE LOST WORLD JURASSIC PARK",
"answ3":"JURASSIC PARK THE LOST WORLD",
"answ2":"The Lost World: Jurassic Park.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, which character says: 'Gee, the lack of humility before nature that's being displayed here, uh... staggers me.'?",
"answ":"MALCOLM",
"answ3":"IAN MALCOLM",
"answ2":"Ian Malcolm.",
},
{
"cat":"Jurassic Park",
"ques":"Which Jurassic Park film ends with the line 'And if we could only step aside and trust in nature, life will find a way.'?",
"answ":"THE LOST WORLD JURASSIC PARK",
"answ3":"THE LOST WORLD",
"answ2":"The Lost World: Jurassic Park.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, when Dennis Nedry is first introduced he is in what capital city in Costa Rica?",
"answ":"SAN JOSE",
"answ2":"San José.",
},
{
"cat":"Jurassic Park",
"ques":"You'll find the characters of Nash and Cooper in what Jurassic Park film?",
"answ":"JURASSIC PARK III",
"answ3":"JURASSIC PARK 3",
"answ2":"Jurassic Park III.",
},
{
"cat":"Jurassic Park",
"ques":"Who played mercenary Ken Wheatly in Jurassic World: Fallen Kingdom?",
"answ":"TED LEVINE",
"answ2":"Ted Levine.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, who gets electrocuted by a fence while trying to climb over it?",
"answ":"TIM",
"answ3":"TIM MURPHY",
"answ2":"Tim.",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur kills Zara, Zach and Gray's babysitter in Jurassic World?",
"answ":"MOSASAURUS",
"answ2":"Mosasaurus.",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur kills Hoskins in Jurassic World?",
"answ":"VELOCIRAPTOR",
"answ3":"RAPTOR",
"answ2":"Velociraptor.",
},
{
"cat":"Jurassic Park",
"ques":"What year saw the release of Jurassic World: Fallen Kingdom?",
"answ":"2018",
"answ2":"2018.",
},
{
"cat":"Jurassic Park",
"ques":"Which leg does Malcolm injure in Jurassic Park?",
"answ":"LEFT",
"answ3":"LEFT LEG",
"answ2":"Left.",
},
{
"cat":"Jurassic Park",
"ques":"Which Jurassic Park film ends with the film: 'Probably stick together. For survival.'?",
"answ":"JURASSIC WORLD",
"answ2":"Jurassic World.",
},
{
"cat":"Jurassic Park",
"ques":"Who directed Jurassic World?",
"answ":"COLIN TREVORROW",
"answ3":"COLIN TREVOROW",
"answ2":"Colin Trevorrow.",
},
{
"cat":"Jurassic Park",
"ques":"Who directed Jurassic World: Fallen Kingdom?",
"answ":"JA BAYONA",
"answ3":"J A BAYONA",
"answ2":"J. A. Bayona.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic World, what is the name of the dinosaur that is a genetic hybrid?",
"answ":"INDOMINUS REX",
"answ2":"Indominus Rex.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, who plays park owner John Hammond?",
"answ":"RICHARD ATTENBOROUGH",
"answ2":"Richard Attenborough.",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park The Lost World, dr. Ian Malcom is joined on the adventure by dr. Sarah Harding played by whom?",
"answ":"JULIANNE MOORE",
"answ2":"Julianne Moore.",
},
{
"cat":"Jurassic Park",
"ques":"Who played Dr. Ellie Sattler in Jurassic Park?",
"answ":"LAURA DERN",
"answ2":"Laura Dern.",
},
{
"cat":"Jurassic Park",
"ques":"Who directed 1997's The Lost World: Jurassic Park?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"Jurassic Park",
"ques":"In which film in the Jurassic Park franchise are we introduced to the Indominus Rex?",
"answ":"JURASSIC WORLD",
"answ2":"Jurassic World.",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of the fictional island were the first Jurassic Park film is set?",
"answ":"ISLA NUBAR",
"answ2":"Isla Nubar.",
},
{
"cat":"Jurassic Park",
"ques":"In 1993's Jurassic Park, what is the name of the industrialist who creates Jurassic Park?",
"answ":"JOHN HAMMOND",
"answ2":"John Hammond.",
},
];
var r2Q11 = [
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, what three-word phrase does John Hammond repeatedly use when describing his park?",
"answ":"SPARED NO EXPENSE",
"answ2":"Spared no expense.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>A unique experience</button><button id=corop class=buttons003 onclick=qcor()>Spared no expense</button><button id=incop3 class=buttons003 onclick=qinc()>Never seen before</button><button id=incop4 class=buttons003 onclick=qinc()>My favorite part</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In the climax of The Lost World: Jurassic Park, a T-Rex manages to escape in what city?",
"answ":"SAN DIEGO",
"answ2":"San Diego.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago</button><button id=corop class=buttons003 onclick=qcor()>San Diego</button><button id=incop3 class=buttons003 onclick=qinc()>Los Angeles</button><button id=incop4 class=buttons003 onclick=qinc()>San Francisco</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who plays Roland Tembo in The Lost World: Jurassic Park, whose only goal was to hunt a male T-Rex?",
"answ":"PETE POSTLETHWAITE",
"answ3":"PETE POSTLETWAITE",
"answ2":"Pete Postlethwaite.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bill Paxton</button><button id=incop2 class=buttons003 onclick=qinc()>David Thewlis</button><button id=incop3 class=buttons003 onclick=qinc()>Djimon Hounsou</button><button id=corop class=buttons003 onclick=qcor()>Pete Postlethwaite</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, what animal's DNA do they use to fill in the gaps in the dino DNA?",
"answ":"FROG",
"answ2":"Frog.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Frog</button><button id=incop2 class=buttons003 onclick=qinc()>Crocodile</button><button id=incop3 class=buttons003 onclick=qinc()>Eagle</button><button id=incop4 class=buttons003 onclick=qinc()>Chicken</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur was sick in Jurassic Park?",
"answ":"TRICERATOPS",
"answ2":"Triceratops.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Velociraptor</button><button id=incop2 class=buttons003 onclick=qinc()>Dilophosaurus</button><button id=corop class=buttons003 onclick=qcor()>Triceratops</button><button id=incop4 class=buttons003 onclick=qinc()>Tyrannosaurus Rex</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, who is the only person capable of getting the park back online?",
"answ":"DENNIS NEDRY",
"answ2":"Dennis Nedry.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Henry Wu</button><button id=incop2 class=buttons003 onclick=qinc()>Ray Arnold</button><button id=incop3 class=buttons003 onclick=qinc()>Tim Murphy</button><button id=corop class=buttons003 onclick=qcor()>Dennis Nedry</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, John Hammond's park is on an island off the coast of what Central American country?",
"answ":"COSTA RICA",
"answ2":"Costa Rica.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Costa Rica</button><button id=incop2 class=buttons003 onclick=qinc()>Honduras</button><button id=incop3 class=buttons003 onclick=qinc()>Panama</button><button id=incop4 class=buttons003 onclick=qinc()>Nicaragua</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What brand of shaving cream did Dennis use to smuggle out dinosaur embryos in Jurassic Park?",
"answ":"BARBASOL",
"answ2":"Barbasol.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brut</button><button id=incop2 class=buttons003 onclick=qinc()>Magic Shave</button><button id=corop class=buttons003 onclick=qcor()>Barbasol</button><button id=incop4 class=buttons003 onclick=qinc()>Proraso</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of animal is used to lure the T-Rex out of the jungle in Jurassic Park?",
"answ":"GOAT",
"answ2":"Goat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cow</button><button id=incop2 class=buttons003 onclick=qinc()>Sheep</button><button id=corop class=buttons003 onclick=qcor()>Goat</button><button id=incop4 class=buttons003 onclick=qinc()>Pig</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the full name of Laura Dern's character in Jurassic Park?",
"answ":"ELLIE SATTLER",
"answ3":"ELLIE SADLER",
"answ2":"Ellie Sattler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sarah Harding</button><button id=incop2 class=buttons003 onclick=qinc()>Amanda Kirby</button><button id=corop class=buttons003 onclick=qcor()>Ellie Sattler</button><button id=incop4 class=buttons003 onclick=qinc()>Claire Dearing</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who is the only actor from Jurassic Park to return for Jurassic World?",
"answ":"BD WONG",
"answ3":"B D WONG",
"answ2":"B.D. Wong.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeff Goldblum</button><button id=incop2 class=buttons003 onclick=qinc()>Sam Neill</button><button id=corop class=buttons003 onclick=qcor()>BD Wong</button><button id=incop4 class=buttons003 onclick=qinc()>Bob Peck</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"How fast (in mph) did they clock the T-Rex in Jurassic Park?",
"answ":"32",
"answ3":"32 MPH",
"answ2":"32.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>27</button><button id=incop2 class=buttons003 onclick=qinc()>30</button><button id=corop class=buttons003 onclick=qcor()>32</button><button id=incop4 class=buttons003 onclick=qinc()>35</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In The Lost World, what is the name of Ian Malcom's daughter?",
"answ":"KELLY",
"answ2":"Kelly.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jane</button><button id=incop2 class=buttons003 onclick=qinc()>Susie</button><button id=corop class=buttons003 onclick=qcor()>Kelly</button><button id=incop4 class=buttons003 onclick=qinc()>Laura</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the first name of Dr. Grant's assistant in Jurassic Park 3?",
"answ":"BILLY",
"answ3":"BILLY BRENNAN",
"answ2":"Billy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sean</button><button id=incop2 class=buttons003 onclick=qinc()>Sam</button><button id=corop class=buttons003 onclick=qcor()>Billy</button><button id=incop4 class=buttons003 onclick=qinc()>Benjamin</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of Bryce Dallas Howard's character in Jurassic World?",
"answ":"CLAIRE DEARING",
"answ3":"CLAIRE",
"answ2":"Claire Dearing.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Karen Mitchell</button><button id=incop2 class=buttons003 onclick=qinc()>Vivian Cruthers</button><button id=corop class=buttons003 onclick=qcor()>Claire Dearing</button><button id=incop4 class=buttons003 onclick=qinc()>Iris Johnson</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"While on their way to the island in Jurassic Park 3, Dr. Grant has a bizarre dream with a raptor that speaks to him, what does the raptor say?",
"answ":"ALAN",
"answ2":"Alan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Behind You</button><button id=incop2 class=buttons003 onclick=qinc()>Wake Up</button><button id=corop class=buttons003 onclick=qcor()>Alan</button><button id=incop4 class=buttons003 onclick=qinc()>Why</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is Dr. Ellie Sattler's profession?",
"answ":"PALEOBOTANIST",
"answ2":"Paleobotanist.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Paleontologist</button><button id=incop2 class=buttons003 onclick=qinc()>Mathematician</button><button id=corop class=buttons003 onclick=qcor()>Paleobotanist</button><button id=incop4 class=buttons003 onclick=qinc()>Ethologist</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What year saw the release of Jurassic Park III?",
"answ":"2001",
"answ2":"2001.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1999</button><button id=incop2 class=buttons003 onclick=qinc()>2000</button><button id=corop class=buttons003 onclick=qcor()>2001</button><button id=incop4 class=buttons003 onclick=qinc()>2002</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of the island chain referenced at the start of The Lost World?",
"answ":"THE FIVE DEATHS",
"answ3":"LAS CINCO MUERTES",
"answ2":"The Five Deaths.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Bermuda Chain</button><button id=incop2 class=buttons003 onclick=qinc()>The Three Wonders</button><button id=corop class=buttons003 onclick=qcor()>The Five Deaths</button><button id=incop4 class=buttons003 onclick=qinc()>Galápagos Islands</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic World: Fallen Kingdom, what type of natural disaster is threatening to destroy the park?",
"answ":"VOLCANO",
"answ3":"VOLCANIC ERUPTION",
"answ2":"Volcanic eruption.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tornado</button><button id=incop2 class=buttons003 onclick=qinc()>Tsunami</button><button id=corop class=buttons003 onclick=qcor()>Volcanic eruption</button><button id=incop4 class=buttons003 onclick=qinc()>Earthquake</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park 3, what type of dinosaur startles Eric when he and Dr. Grant are hiding away in the abandoned InGen truck?",
"answ":"COMPIES",
"answ3":"COMPSOGNATHUS",
"answ2":"Compsognathus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Velociraptor</button><button id=incop2 class=buttons003 onclick=qinc()>Spinosaurus</button><button id=corop class=buttons003 onclick=qcor()>Compsognathus</button><button id=incop4 class=buttons003 onclick=qinc()>T-Rex</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What does Lex refer to herself as after her brother Tim makes fun of her in Jurassic Park?",
"answ":"HACKER",
"answ2":"Hacker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hacker</button><button id=incop2 class=buttons003 onclick=qinc()>Winner</button><button id=incop3 class=buttons003 onclick=qinc()>Genius</button><button id=incop4 class=buttons003 onclick=qinc()>Geek</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who plays Donald Gennaro, the 'blood sucking lawyer'?",
"answ":"MARTIN FERRERO",
"answ2":"Martin Ferrero.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Martin Ferrero</button><button id=incop2 class=buttons003 onclick=qinc()>Emilio Estevez</button><button id=incop3 class=buttons003 onclick=qinc()>Jim Caviezel</button><button id=incop4 class=buttons003 onclick=qinc()>Clive Owen</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Fallen Kingdom, Lockwood carries a cane to help him walk. What is on the head of the cane?",
"answ":"AMBER",
"answ3":"AMBER WITH MOSQUITO",
"answ2":"Amber.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Amber</button><button id=incop2 class=buttons003 onclick=qinc()>Skull</button><button id=incop3 class=buttons003 onclick=qinc()>Snake head</button><button id=incop4 class=buttons003 onclick=qinc()>T-Rex head</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who hits Dr. Grant just before landing on Isla Sorna in Jurassic Park III?",
"answ":"COOPER",
"answ2":"Cooper.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Cooper</button><button id=incop2 class=buttons003 onclick=qinc()>Nash</button><button id=incop3 class=buttons003 onclick=qinc()>Billy</button><button id=incop4 class=buttons003 onclick=qinc()>Malcolm</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"How many species of dinosaurs appear on screen in the first Jurassic Park?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":"<button id=corop class=buttons003 onclick=qcor()>7</button><button id=incop2 class=buttons003 onclick=qinc()>9</button><button id=incop3 class=buttons003 onclick=qinc()>10</button><button id=incop4 class=buttons003 onclick=qinc()>12</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who is the owner of Jurassic World in Jurassic World?",
"answ":"SIMON MASRANI",
"answ3":"MASRANI",
"answ2":"Simon Masrani.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Simon Masrani</button><button id=incop2 class=buttons003 onclick=qinc()>Benjamin Lockwood</button><button id=incop3 class=buttons003 onclick=qinc()>John Hammond</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Wu</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park 3, who was carrying the satellite phone just before getting eaten by the Spinosaurus?",
"answ":"NASH",
"answ3":"MB NASH",
"answ2":"Nash.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nash</button><button id=incop2 class=buttons003 onclick=qinc()>Paul Kirby</button><button id=incop3 class=buttons003 onclick=qinc()>Cooper</button><button id=incop4 class=buttons003 onclick=qinc()>Billy</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What kind of berries does Ellie think the Triceratops has been eating which could have led to its sickness?",
"answ":"WEST INDIAN LILAC",
"answ2":"West Indian Lilac.",
"option":"<button id=corop class=buttons003 onclick=qcor()>West Indian Lilac</button><button id=incop2 class=buttons003 onclick=qinc()>Acai</button><button id=incop3 class=buttons003 onclick=qinc()>Acerola Cherries</button><button id=incop4 class=buttons003 onclick=qinc()>Naranjilla</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What was the name given to the new genetically created dinosaur in Fallen Kingdom?",
"answ":"INDORAPTOR",
"answ2":"Indoraptor.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Indoraptor</button><button id=incop2 class=buttons003 onclick=qinc()>Indosaurus</button><button id=incop3 class=buttons003 onclick=qinc()>Indoceratops</button><button id=incop4 class=buttons003 onclick=qinc()>Indopteradon</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park 3, who says the line: 'This is how you play God'?",
"answ":"ALAN",
"answ3":"ALAN GRANT",
"answ2":"Alan Grant.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Ian Malcolm</button><button id=incop3 class=buttons003 onclick=qinc()>John Hammond</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Wu</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In The Lost World, what sport does Kelly participate in to which she claims she was cut from the team?",
"answ":"GYMNASTICS",
"answ2":"Gymnastics.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gymnastics</button><button id=incop2 class=buttons003 onclick=qinc()>Basketball</button><button id=incop3 class=buttons003 onclick=qinc()>Figure skating</button><button id=incop4 class=buttons003 onclick=qinc()>Soccer</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Only one movie in the Jurassic franchise has NOT shown a Stegosaurus. Name that movie.",
"answ":"JURASSIC PARK",
"answ2":"Jurassic Park.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jurassic World</button><button id=incop2 class=buttons003 onclick=qinc()>Jurassic Park 3</button><button id=incop3 class=buttons003 onclick=qinc()>The Lost World: Jurassic Park</button><button id=corop class=buttons003 onclick=qcor()>Jurassic Park</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur appears as a hologram that scares one of the velociraptors chasing the main characters in the final act of Jurassic World?",
"answ":"DILOPHOSAURUS",
"answ2":"Dilophosaurus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>T-Rex</button><button id=incop2 class=buttons003 onclick=qinc()>Spinosaurus</button><button id=incop3 class=buttons003 onclick=qinc()>Indominus Rex</button><button id=corop class=buttons003 onclick=qcor()>Dilophosaurus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What other theme park does Hammond mention that also had issues on its opening day?",
"answ":"DISNEYLAND",
"answ2":"Disneyland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Universal Studios</button><button id=incop2 class=buttons003 onclick=qinc()>SeaWorld</button><button id=incop3 class=buttons003 onclick=qinc()>Knott's Berry Farm</button><button id=corop class=buttons003 onclick=qcor()>Disneyland</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Paul Kirby claims his business is called 'Kirby Enterprises' but it is eventually revealed to be called what?",
"answ":"KIRBY PAINT AND TILE PLUS",
"answ2":"Kirby Paint and Tile Plus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kirby Painting and Decorating</button><button id=incop2 class=buttons003 onclick=qinc()>Kirby & Son Painting</button><button id=incop3 class=buttons003 onclick=qinc()>Kirby Corp</button><button id=corop class=buttons003 onclick=qcor()>Kirby Paint and Tile Plus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who scored Jurassic World?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Williams</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop3 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>Michael Giacchino</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of the boat carrying the T-Rex on its way to San Diego?",
"answ":"SS VENTURE",
"answ3":"VENTURE",
"answ2":"SS Venture.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>SS Agusta</button><button id=incop2 class=buttons003 onclick=qinc()>SS Cussler</button><button id=incop3 class=buttons003 onclick=qinc()>SS Minnow</button><button id=corop class=buttons003 onclick=qcor()>SS Venture</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park 3, what type of dinosaur is seen flying away at the end of the film?",
"answ":"PTERANODON",
"answ3":"PTERADON",
"answ2":"Pteranodon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Microraptor</button><button id=incop2 class=buttons003 onclick=qinc()>Archaeopteryx</button><button id=incop3 class=buttons003 onclick=qinc()>Ambopteryx</button><button id=corop class=buttons003 onclick=qcor()>Pteranodon</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is being cooked for the guests on Jurassic Park after they witness the Velociraptor paddock?",
"answ":"CHILEAN SEA BASS",
"answ3":"BASS",
"answ2":"Chilean Sea Bass.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ecuadorian Ceviche</button><button id=incop2 class=buttons003 onclick=qinc()>Carbonada</button><button id=incop3 class=buttons003 onclick=qinc()>Brazilian Chocolate Fudge Balls</button><button id=corop class=buttons003 onclick=qcor()>Chilean Sea Bass</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Fallen Kingdom, what is Lockwood's 'granddaughter's' first name?",
"answ":"MAISIE",
"answ2":"Maisie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sophia</button><button id=incop2 class=buttons003 onclick=qinc()>Wendy</button><button id=incop3 class=buttons003 onclick=qinc()>Natalie</button><button id=corop class=buttons003 onclick=qcor()>Maisie</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur uses its bowl-shaped head to attack one of the InGen soldiers in The Lost World?",
"answ":"PACHYCEPHALOSAURUS",
"answ2":"Pachycephalosaurus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Triceratops</button><button id=incop2 class=buttons003 onclick=qinc()>Dilophosaurus</button><button id=incop3 class=buttons003 onclick=qinc()>Compsognathus</button><button id=corop class=buttons003 onclick=qcor()>Pachycephalosaurus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of Hammond's greedy nephew and main antagonist in The Lost World?",
"answ":"PETER LUDLOW",
"answ3":"LUDLOW",
"answ2":"Peter Ludlow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miles Chadwick</button><button id=incop2 class=buttons003 onclick=qinc()>Scrap Davis</button><button id=incop3 class=buttons003 onclick=qinc()>Bill Steingarten</button><button id=corop class=buttons003 onclick=qcor()>Peter Ludlow</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"John Hammond tells Ellie Sattler that his first theme park attraction was what?",
"answ":"FLEA CIRCUS",
"answ2":"Flea circus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Carousel</button><button id=incop2 class=buttons003 onclick=qinc()>Bumper cars</button><button id=incop3 class=buttons003 onclick=qinc()>Haunted House</button><button id=corop class=buttons003 onclick=qcor()>Flea circus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who plays the young girl attacked by Compy's at the start of The Lost World?",
"answ":"CAMILLA BELLE",
"answ2":"Camilla Belle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ariana Richards</button><button id=incop2 class=buttons003 onclick=qinc()>Vanessa Lee Chester</button><button id=corop class=buttons003 onclick=qcor()>Camilla Belle</button><button id=incop4 class=buttons003 onclick=qinc()>Bethany Joy Lenz</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Jurassic Park's tagline was: An adventure ___ million years in the making.",
"answ":"65",
"answ2":"65.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>55</button><button id=incop2 class=buttons003 onclick=qinc()>60</button><button id=corop class=buttons003 onclick=qcor()>65</button><button id=incop4 class=buttons003 onclick=qinc()>70</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What year did The Lost World: Jurassic Park come out?",
"answ":"1997",
"answ2":"1997.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1995</button><button id=incop2 class=buttons003 onclick=qinc()>1996</button><button id=corop class=buttons003 onclick=qcor()>1997</button><button id=incop4 class=buttons003 onclick=qinc()>1998</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What original Jurassic Park character appears on the back of a book in Jurassic World?",
"answ":"IAN MALCOLM",
"answ3":"MALCOLM",
"answ2":"Ian Malcolm.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Henry Wu</button><button id=corop class=buttons003 onclick=qcor()>Ian Malcolm</button><button id=incop4 class=buttons003 onclick=qinc()>John Hammond</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who played Amanda Kirby in Jurassic Park 3?",
"answ":"TEA LEONI",
"answ2":"Tea Leoni.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kim Basinger</button><button id=incop2 class=buttons003 onclick=qinc()>Demi Moore</button><button id=corop class=buttons003 onclick=qcor()>Tea Leoni</button><button id=incop4 class=buttons003 onclick=qinc()>Kim Cattrall</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What did Billy steal and keep hidden from the other survivors in Jurassic Park 3?",
"answ":"RAPTOR EGGS",
"answ3":"DINOSAUR EGGS",
"answ2":"Raptor eggs.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gun</button><button id=incop2 class=buttons003 onclick=qinc()>Chocolate bars</button><button id=corop class=buttons003 onclick=qcor()>Raptor eggs</button><button id=incop4 class=buttons003 onclick=qinc()>Telephone</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who plays Dieter Stark, Roland's second-in-command who is eventually killed by the Compy's in The Lost World?",
"answ":"PETER STORMARE",
"answ2":"Peter Stormare.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Vince Vaughn</button><button id=incop2 class=buttons003 onclick=qinc()>Joe Manganiello</button><button id=corop class=buttons003 onclick=qcor()>Peter Stormare</button><button id=incop4 class=buttons003 onclick=qinc()>Richard Schiff</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, when Dodgson delivers money to Nedry, how many species of dinosaurs does he mention are on the island?",
"answ":"15",
"answ2":"15.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>10</button><button id=incop2 class=buttons003 onclick=qinc()>12</button><button id=corop class=buttons003 onclick=qcor()>15</button><button id=incop4 class=buttons003 onclick=qinc()>20</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who played Eddie Carr in The Lost World?",
"answ":"RICHARD SCHIFF",
"answ2":"Richard Schiff.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Vince Vaughn</button><button id=incop2 class=buttons003 onclick=qinc()>Frank Grillo</button><button id=corop class=buttons003 onclick=qcor()>Richard Schiff</button><button id=incop4 class=buttons003 onclick=qinc()>Pete Postlethwaite</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic Park, when Grant discovers that the dinosaurs have been breeding, what kind of frog does he claim changes sex in a single-sex environment?",
"answ":"WEST AFRICAN",
"answ3":"WEST AFRICAN FROG",
"answ2":"West African Frog.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>North American Frog</button><button id=incop2 class=buttons003 onclick=qinc()>South American Frog</button><button id=corop class=buttons003 onclick=qcor()>West African Frog</button><button id=incop4 class=buttons003 onclick=qinc()>South Asian Frog</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Ted Levine's mercenary Ken Wheatley collects what from dinosaurs as a trophy in Fallen Kingdom?",
"answ":"TEETH",
"answ2":"Teeth.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scales</button><button id=incop2 class=buttons003 onclick=qinc()>Bones</button><button id=corop class=buttons003 onclick=qcor()>Teeth</button><button id=incop4 class=buttons003 onclick=qinc()>Quills</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In Jurassic World, Jake Johnson's character Lowerey is wearing a vintage Jurassic Park shirt. Where did he say he bought it?",
"answ":"EBAY",
"answ2":"eBay.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Amazon</button><button id=incop2 class=buttons003 onclick=qinc()>Alibaba</button><button id=corop class=buttons003 onclick=qcor()>eBay</button><button id=incop4 class=buttons003 onclick=qinc()>Craigslist</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who composed the score for Jurassic Park 3?",
"answ":"DON DAVIS",
"answ3":"DONALD DAVIS",
"answ2":"Don Davis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Williams</button><button id=corop class=buttons003 onclick=qcor()>Don Davis</button><button id=incop3 class=buttons003 onclick=qinc()>James Horner</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Kamen</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Zach and Grey are traveling in what when they are attacked by the Indominus Rex?",
"answ":"GYROSPHERE",
"answ2":"Gyrosphere.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeep</button><button id=corop class=buttons003 onclick=qcor()>Gyrosphere</button><button id=incop3 class=buttons003 onclick=qinc()>Train</button><button id=incop4 class=buttons003 onclick=qinc()>Boat</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who played Hammond's silent partner Benjamin Lockwood in Fallen Kingdom?",
"answ":"JAMES CROMWELL",
"answ2":"James Cromwell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Arkin</button><button id=corop class=buttons003 onclick=qcor()>James Cromwell</button><button id=incop3 class=buttons003 onclick=qinc()>Christoper Plummer</button><button id=incop4 class=buttons003 onclick=qinc()>Donald Sutherland</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of fish does the Mosasaurus eat before a giant crowd in Jurassic World?",
"answ":"SHARK",
"answ2":"Shark.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sturgeon</button><button id=corop class=buttons003 onclick=qcor()>Shark</button><button id=incop3 class=buttons003 onclick=qinc()>Lampreys</button><button id=incop4 class=buttons003 onclick=qinc()>Tuna</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who played documentarian Nick Van Owen in The Lost World?",
"answ":"VINCE VAUGHN",
"answ2":"Vince Vaughn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Owen Wilson</button><button id=corop class=buttons003 onclick=qcor()>Vince Vaughn</button><button id=incop3 class=buttons003 onclick=qinc()>Ben Stiller</button><button id=incop4 class=buttons003 onclick=qinc()>Samuel L. Jackson</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Which original Jurassic Park lead character returns in Fallen Kingdom?",
"answ":"IAN MALCOLM",
"answ3":"DR IAN MALCOLM",
"answ2":"Ian Malcom.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Grant</button><button id=corop class=buttons003 onclick=qcor()>Ian Malcom</button><button id=incop3 class=buttons003 onclick=qinc()>Ellie Sattler</button><button id=incop4 class=buttons003 onclick=qinc()>John Hammond</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What type of dinosaur kills Cooper in Jurassic Park 3?",
"answ":"SPINOSAURUS",
"answ2":"Spinosaurus.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>T-Rex</button><button id=corop class=buttons003 onclick=qcor()>Spinosaurus</button><button id=incop3 class=buttons003 onclick=qinc()>Velociraptor</button><button id=incop4 class=buttons003 onclick=qinc()>Stegosaurus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What major wireless company sponsored the Indominus Rex?",
"answ":"VERIZON WIRELESS",
"answ3":"VERIZON",
"answ2":"Verizon Wireless.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cricket Wireless</button><button id=corop class=buttons003 onclick=qcor()>Verizon Wireless</button><button id=incop3 class=buttons003 onclick=qinc()>Liberty Wireless</button><button id=incop4 class=buttons003 onclick=qinc()>Access Wireless</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of the man who delivers money to Nedry in Jurassic Park?",
"answ":"LEWIS DODGSON",
"answ3":"DODGSON",
"answ2":"Lewis Dodgson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eddie Carr</button><button id=corop class=buttons003 onclick=qcor()>Lewis Dodgson</button><button id=incop3 class=buttons003 onclick=qinc()>John Roxton</button><button id=incop4 class=buttons003 onclick=qinc()>Martin Gutierrez</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In The Lost World, who said the line: 'Mommy's very angry.'?",
"answ":"MALCOLM",
"answ3":"IAN MALCOLM",
"answ2":"Ian Malcolm.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sarah Harding</button><button id=corop class=buttons003 onclick=qcor()>Ian Malcolm</button><button id=incop3 class=buttons003 onclick=qinc()>Roland Tembo</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Ludlow</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is the name of Vincent D'Onofrio's character in Jurassic World?",
"answ":"VIC HOSKINS",
"answ3":"HOSKINS",
"answ2":"Vic Hoskins.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Vic Hoskins</button><button id=incop2 class=buttons003 onclick=qinc()>Gray Mitchell</button><button id=incop3 class=buttons003 onclick=qinc()>Lowery Cruthers</button><button id=incop4 class=buttons003 onclick=qinc()>Simon Masrani</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What does the parachute say in Jurassic Park 3?",
"answ":"DINO SOAR",
"answ3":"DINOSOAR",
"answ2":"Dino-Soar.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dino-Soar</button><button id=incop2 class=buttons003 onclick=qinc()>InGen</button><button id=incop3 class=buttons003 onclick=qinc()>Biosyn</button><button id=incop4 class=buttons003 onclick=qinc()>Lucas Parachutes</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"How many volts of electricity are the electric fences in Jurassic Park?",
"answ":"10 000",
"answ3":"10000",
"answ2":"10,000.",
"option":"<button id=corop class=buttons003 onclick=qcor()>10,000</button><button id=incop2 class=buttons003 onclick=qinc()>15,000</button><button id=incop3 class=buttons003 onclick=qinc()>30,000</button><button id=incop4 class=buttons003 onclick=qinc()>40,000</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What is Owen doing when Claire arrives to see him the first time in Fallen Kingdom?",
"answ":"BUILDING A HOUSE",
"answ2":"Building a house.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Building a house</button><button id=incop2 class=buttons003 onclick=qinc()>Watching TV</button><button id=incop3 class=buttons003 onclick=qinc()>Mowing the lawn</button><button id=incop4 class=buttons003 onclick=qinc()>Cooking</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Which celebrity talk show host appears in Jurassic World?",
"answ":"JIMMY FALLON",
"answ2":"Jimmy Fallon.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jimmy Fallon</button><button id=incop2 class=buttons003 onclick=qinc()>Seth Meyers</button><button id=incop3 class=buttons003 onclick=qinc()>Jimmy Kimmel</button><button id=incop4 class=buttons003 onclick=qinc()>Stephen Colbert</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What island are the main characters stranded on in Jurassic Park 3?",
"answ":"ISLA SORNA",
"answ2":"Isla Sorna.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Isla Sorna</button><button id=incop2 class=buttons003 onclick=qinc()>Isla Nubar</button><button id=incop3 class=buttons003 onclick=qinc()>Isla Tacano</button><button id=incop4 class=buttons003 onclick=qinc()>Isla Matanceros</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Which dinosaur does the T-Rex attack in the open field after Dr. Grant and the kids flee from them?",
"answ":"GALLIMIMUS",
"answ2":"Gallimimus.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gallimimus</button><button id=incop2 class=buttons003 onclick=qinc()>Velociraptor</button><button id=incop3 class=buttons003 onclick=qinc()>Dilophosaurus</button><button id=incop4 class=buttons003 onclick=qinc()>Compsognathus</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who has a voice cameo as Mr. DNA in Jurassic World?",
"answ":"COLIN TREVORROW",
"answ2":"Colin Trevorrow.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Colin Trevorrow</button><button id=incop2 class=buttons003 onclick=qinc()>Steven Spielberg</button><button id=incop3 class=buttons003 onclick=qinc()>J. A. Bayona</button><button id=incop4 class=buttons003 onclick=qinc()>David Attenborough</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Which state are Dr. Grant and Dr. Sattler based out of?",
"answ":"MONTANA",
"answ2":"Montana.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Montana</button><button id=incop2 class=buttons003 onclick=qinc()>California</button><button id=incop3 class=buttons003 onclick=qinc()>Texas</button><button id=incop4 class=buttons003 onclick=qinc()>Florida</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who plays Eli Mills, Lockwood's ambitious assistant in Fallen Kingdom?",
"answ":"RAFE SPALL",
"answ2":"Rafe Spall.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rafe Spall</button><button id=incop2 class=buttons003 onclick=qinc()>Ted Levine</button><button id=incop3 class=buttons003 onclick=qinc()>Lieb Schreiber</button><button id=incop4 class=buttons003 onclick=qinc()>Toby Jones</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"What means of transportation does Malcolm and his crew take to get to Isla Sorna in The Lost World?",
"answ":"BOAT",
"answ3":"A BOAT",
"answ2":"Boat.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Boat</button><button id=incop2 class=buttons003 onclick=qinc()>Helicopter</button><button id=incop3 class=buttons003 onclick=qinc()>Airplane</button><button id=incop4 class=buttons003 onclick=qinc()>Water scooter</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Who said: 'I bet you'll never look at birds the same again' in Jurassic Park?",
"answ":"ALAN GRANT",
"answ3":"DR GRANT",
"answ2":"Alan Grant.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Ian Malcolm</button><button id=incop3 class=buttons003 onclick=qinc()>John Hammond</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Wu</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"How many films in the Jurassic Park franchise has John Williams done the music for?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=corop class=buttons003 onclick=qcor()>2</button><button id=incop3 class=buttons003 onclick=qinc()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"Which character in Jurassic Park said: 'T-Rex doesn't want to be fed. He wants to hunt. Can't just suppress 65 million years of gut instinct.'?",
"answ":"ALAN GRANT",
"answ3":"GRANT",
"answ2":"Alan Grant.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Grant</button><button id=incop2 class=buttons003 onclick=qinc()>Ian Malcolm</button><button id=incop3 class=buttons003 onclick=qinc()>John Hammond</button><button id=incop4 class=buttons003 onclick=qinc()>Ellie Sattler</button><br/>",
},
{
"cat":"Jurassic Park",
"ques":"In The Lost World, John Hammond says that he has worked to keep the dinosaurs on Isla Sorna safe for how many years?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop3 class=buttons003 onclick=qinc()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
];
jurassicpark = shuffle(jurassicpark);
r2Q11 = shuffle(r2Q11);