var transformers = [
{
"cat":"Transformers",
"ques":"Which film in the Transformers franchise was released in 2018?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"What actress plays Charlie Watson in Bumblebee?",
"answ":"HAILEE STEINFELD",
"answ2":"Hailee Steinfeld.",
},
{
"cat":"Transformers",
"ques":"In how many of the Transformers films does Shia LaBeouf appear as Sam Witwicky?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Transformers",
"ques":"In Transformers (2007), what is the name of the super secret government agency responsible for hiding the existence of Transformers?",
"answ":"SECTOR SEVEN",
"answ3":"SECTOR 7",
"answ2":"Sector Seven.",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played U.S. Secretary of Defense John Keller?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
},
{
"cat":"Transformers",
"ques":"Travis Knight directed which film in the Transformers franchise?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"In Transformers: The Movie, what is the name of the city the autobots have built on Earth?",
"answ":"AUTOBOT CITY",
"answ2":"Autobot City.",
},
{
"cat":"Transformers",
"ques":"Which Transformers film was released in 2014?",
"answ":"TRANSFORMERS AGE OF EXTINCTION",
"answ3":"AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
},
{
"cat":"Transformers",
"ques":"Who directed 2007's Transformers?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
},
{
"cat":"Transformers",
"ques":"In the Transformers franchise, which Autobot is a yellow Chevrolet Camaro?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"Which actor played the role of Sam Witwicky in the Transformers franchise?",
"answ":"SHIA LABEOUF",
"answ3":"SHIA LEBEOUF",
"answ2":"Shia LaBeouf.",
},
{
"cat":"Transformers",
"ques":"In the Transformers series, what is Shia LaBeouf's first name?",
"answ":"SAM",
"answ2":"Sam.",
},
{
"cat":"Transformers",
"ques":"What is the subtitle of the first sequel to Michael Bay's Transformers?",
"answ":"REVENGE OF THE FALLEN",
"answ2":"Revenge of the Fallen.",
},
{
"cat":"Transformers",
"ques":"Who plays Mikaela Barnes in the Transformers franchise?",
"answ":"MEGAN FOX",
"answ2":"Megan Fox.",
},
];
var r2Q12 = [
{
"cat":"Transformers",
"ques":"Who voiced Daytrader in Transformers: The Last Knight?",
"answ":"STEVE BUSCEMI",
"answ2":"Steve Buscemi.",
"option":["Steve Buscemi", "Alan Tudyk", "Mark Ryan", "Reno Wilson"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Sam Witwicky's father?",
"answ":"KEVIN DUNN",
"answ2":"Kevin Dunn.",
"option":["Kevin Dunn", "Dennis Quaid", "Jon Voight", "Denis Leary"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Sam Witwicky's mother?",
"answ":"JULIE WHITE",
"answ2":"Julie White.",
"option":["Julie White", "Laura Linney", "Marisa Tomei", "Helen Mirren"],
},
{
"cat":"Transformers",
"ques":"Who voiced The Fallen, in Transformers: Revenge of the Fallen?",
"answ":"TONY TODD",
"answ2":"Tony Todd.",
"option":["Tony Todd", "Samuel L. Jackson", "Forest Whitaker", "Laurence Fishburne"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Captain William Lennox?",
"answ":"JOSH DUHAMEL",
"answ3":"JOSH DUMEL",
"answ2":"Josh Duhamel.",
"option":["Josh Duhamel", "Kevin Bacon", "Ed Harris", "John Turturro"],
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, who played wealthy car collector Dylan Gould?",
"answ":"PATRICK DEMPSEY",
"answ2":"Patrick Dempsey.",
"option":["Patrick Dempsey", "Aaron Eckhart", "Nicholas Hoult", "James Marsden"],
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, who played Bruce Brazos, Sam's employer and boss at Accuretta Systems?",
"answ":"JOHN MALKOVICH",
"answ2":"John Malkovich.",
"option":["John Malkovich", "Jon Voight", "John Goodman", "Patrick Stewart"],
},
{
"cat":"Transformers",
"ques":"What Star Trek actor voiced Sentinel Prime in Transformers: Dark of the Moon?",
"answ":"LEONARD NIMOY",
"answ2":"Leonard Nimoy.",
"option":["Leonard Nimoy", "Chris Pine", "William Shatner", "Patrick Stewart"],
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, what comedian played paranoid software programmer Jerry 'Deep' Wang?",
"answ":"KEN JEONG",
"answ3":"KEN JONG",
"answ2":"Ken Jeong.",
"option":["Ken Jeong", "Dave Chappelle", "Chevy Chase", "Joel McHale"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, Sam says that Captain Witicky was one of the first to exlore what location?",
"answ":"ARCTIC CIRCLE",
"answ3":"THE ARCTIC CIRCLE",
"answ2":"The Arctic Circle.",
"option":["Arctic Circle", "Madagascar", "Alaska", "Iceland"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, what junk food was set before Rachel and Glen as they were being held in the interrogation room by Sector 7?",
"answ":"DONUTS",
"answ3":"DONUT",
"answ2":"Donuts.",
"option":["Donuts", "Cookies", "Cake", "Candy"],
},
{
"cat":"Transformers",
"ques":"You can find the quote: 'They literally call themselves Decepticons, that doesn't set off any red flags?' in what film in the Transformers franchise?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
"option":["Bumblebee", "Dark of the Moon", "The Last Knight", "Age of Extinction"],
},
{
"cat":"Transformers",
"ques":"Who played Agent Seymour Simmons in the Transformers franchise?",
"answ":"JOHN TURTURRO",
"answ3":"JOHN TURTURO",
"answ2":"John Turturro.",
"option":["John Turturro", "Cliff Curtis", "Antonio Banderas", "Samuel L. Jackson"],
},
{
"cat":"Transformers",
"ques":"Who played Merlin in Transformers: The Last Knight?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":["Stanley Tucci", "Tom Hardy", "Diego Luna", "B.D. Wong"],
},
{
"cat":"Transformers",
"ques":"What is the name the Transformers give to the Cube that creates Transformers in the 2000s film Transformers?",
"answ":"ALL SPARK",
"answ3":"ALLSPARK",
"answ2":"AllSpark.",
"option":["AllSpark", "Harvester", "Matrix", "Creator"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, what is the name of Sam Witwicky's pet chihuahua?",
"answ":"MOJO",
"answ2":"Mojo.",
"option":["Mojo", "Dexter", "Rex", "Billy"],
},
{
"cat":"Transformers",
"ques":"Who directed 1986's Transformers The Movie?",
"answ":"NELSON SHIN",
"answ2":"Nelson Shin.",
"option":["Nelson Shin", "Igor Kovalyov", "David Silverman", "Brian Levant"],
},
{
"cat":"Transformers",
"ques":"Who voiced Bumblebee in 2007's Transformers?",
"answ":"MARK RYAN",
"answ2":"Mark Ryan.",
"option":["Mark Ryan", "Hugo Weaving", "Robert Foxworth", "Jess Harnell"],
},
{
"cat":"Transformers",
"ques":"Who voices Megatron in 2007's Transformers?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
"option":["Hugo Weaving", "Charlie Adler", "Mark Ryan", "Reno Wilson"],
},
{
"cat":"Transformers",
"ques":"Who voices Optimus Prime in 2007's Transformers?",
"answ":"PETER CULLEN",
"answ2":"Peter Cullen.",
"option":["Peter Cullen", "Hugo Weaving", "Nick Nolte", "Darius McCrary"],
},
{
"cat":"Transformers",
"ques":"Which sci-fi legend was the voice of Galvatron in 1986's The Transformers?",
"answ":"LEONARD NIMOY",
"answ2":"Leonard Nimoy.",
"option":["Leonard Nimoy", "William Shatner", "Mark Hamill", "Patrick Stewart"],
},
{
"cat":"Transformers",
"ques":"Who voiced Hot Rod in 1986's The Transformers: The Movie?",
"answ":"JUDD NELSON",
"answ2":"Judd Nelson.",
"option":["Judd Nelson", "Scatman Crothers", "Corey Burton", "Peter Cullen"],
},
{
"cat":"Transformers",
"ques":"In which film of the franchise does character actor Mitch Pileggi appear as the TRF group leader?",
"answ":"THE LAST KNIGHT",
"answ3":"TRANSFORMERS THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":["The Last Knight", "Revenge of the Fallen", "Age of Extinction", "Dark of the Moon"],
},
{
"cat":"Transformers",
"ques":"In Transformers: Revenge of the Fallen, in Sam Witwicki's college dorm there is a vending machine of what soda?",
"answ":"MOUNTAIN DEW",
"answ2":"Mountain Dew.",
"option":["Mountain Dew", "Fanta", "Coca-Cola", "Sprite"],
},
{
"cat":"Transformers",
"ques":"Which Academy Award winning actress plays Charlotte Mearing, the Director of National Intelligence, in Transformers: Dark of the Moon?",
"answ":"FRANCES MCDORMAND",
"answ2":"Frances McDormand.",
"option":["Frances McDormand", "Marion Cotillard", "Cate Blanchett", "Olivia Colman"],
},
{
"cat":"Transformers",
"ques":"Which Transformers film ends with the quote: 'I am Optimus Prime and this message is to my creators: leave planet Earth alone, because I'm coming for you'?",
"answ":"TRANSFORMERS AGE OF EXTINCTION",
"answ3":"AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
"option":["Age of Extinction", "The Last Knight", "Revenge of the Fallen", "Dark of the Moon"],
},
{
"cat":"Transformers",
"ques":"In what year does the movie Transformers: The Movie take place?",
"answ":"2005",
"answ2":"2005.",
"option":["2005", "2025", "2015", "2000"],
},
{
"cat":"Transformers",
"ques":"Who plays Harold Attinger, a corrupt CIA operative and government official in Transformers: Age of Extinction?",
"answ":"KELSEY GRAMMER",
"answ2":"Kelsey Grammer.",
"option":["Kelsey Grammer", "Mark Strong", "Stanley Tucci", "Nick Nolte"],
},
{
"cat":"Transformers",
"ques":"In Transformers: Age of Extinction, who kills corrupt CIA operative Harold Attinger, played by Kelsey Grammar?",
"answ":"OPTIMUS PRIME",
"answ2":"Optimus Prime.",
"option":["Optimus Prime", "Cade Yeager", "Galvatron", "Crosshairs"],
},
{
"cat":"Transformers",
"ques":"What Oscar nominee plays billionaire Joshua Joyce in Transformers: Age of Extinction?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":["Stanley Tucci", "Mark Rylance", "Benicio del Toro", "Ben Kingsley"],
},
{
"cat":"Transformers",
"ques":"In Transformers: Dark of the Moon, Sam Witwicky and Carly live in what city?",
"answ":"WASHINGTON DC",
"answ3":"DC",
"answ2":"Washington DC.",
"option":["Washington DC", "Las Vegas", "Chicago", "Philadelphia"],
},
{
"cat":"Transformers",
"ques":"The characters Ultra Magnus, Arcee and Kranix appear in which film?",
"answ":"THE TRANSFORMERS THE MOVIE",
"answ3":"TRANSFORMERS THE MOVIE",
"answ2":"The Transformers: The Movie.",
"option":["The Transformers: The Movie", "Transformers (2007)", "Transformers: Dark of the Moon", "Transformers: Age of Extinction"],
},
{
"cat":"Transformers",
"ques":"In Transformers (2007), Sam Witwicky and Mikaela Barnes are in what grade?",
"answ":"11TH",
"answ3":"ELEVENTH",
"answ2":"11th.",
"option":["11th", "9th", "10th", "12th"],
},
{
"cat":"Transformers",
"ques":"In Transformers: The Last Knight, what is the name of Izabella's small robotic friend?",
"answ":"SQWEEKS",
"answ2":"Sqweeks.",
"option":["Sqweeks", "Pterry", "Scorn", "Slug"],
},
{
"cat":"Transformers",
"ques":"In what film will you hear the quote: 'I'm asking you to look at all the junk and see the treasure. You got to have faith, Prime, in who we can be'?",
"answ":"AGE OF EXTINCTION",
"answ3":"TRANSFORMERS AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
"option":["Age of Extinction", "Dark of the Moon", "The Last Knight", "Revenge of the Fallen"],
},
{
"cat":"Transformers",
"ques":"In what Transformers film will you find the wizard Merlin helping the Guardian Knights?",
"answ":"TRANSFORMERS THE LAST KNIGHT",
"answ3":"THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":["The Last Knight", "Revenge of the Fallen", "Dark of the Moon", "The Transformers: The Movie"],
},
{
"cat":"Transformers",
"ques":"Laura Haddock plays Viviane Wembly, a professor of English Literature at the University of Oxford, in which Transformers movie?",
"answ":"THE LAST KNIGHT",
"answ3":"TRANSFORMERS THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":["Transformers: The Last Knight", "Transformers: Revenge of the Fallen", "Transformers (2007)", "Transformers: Dark of the Moon"],
},
{
"cat":"Transformers",
"ques":"In Bumblebee, Charlie's neighbor and friend Guillermo Gutierrez goes by what nickname?",
"answ":"MEMO",
"answ2":"Memo.",
"option":["Memo", "Guti", "Mohawk", "Guille"],
},
{
"cat":"Transformers",
"ques":"Which Transformers film begins with a Spanish speaking soldier named Fig wanting to eat alligator meat?",
"answ":"TRANSFORMERS",
"answ3":"TRANSFORMERS 2007",
"answ2":"Transformers (2007).",
"option":["Transformers (2007)", "Transformers: Revenge of the Fallen", "Transformers: Age of Extinction", "Transformers: Dark of the Moon"],
},
{
"cat":"Transformers",
"ques":"Which Transformers film has the tagline: 'Beyond good, beyond evil, beyond your wildest imagination.'?",
"answ":"TRANSFORMERS THE MOVIE",
"answ3":"THE TRANSFORMERS THE MOVIE",
"answ2":"The Transformers: The Movie.",
"option":["The Transformers: The Movie", "Transformers: Revenge of the Fallen", "Transformers: Age of Extinction", "Transformers: Dark of the Moon"],
},
{
"cat":"Transformers",
"ques":"How many film in the Transformers franchise has John Turturro appeared as the character Seymour Simmons?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":["4", "2", "3", "1"],
},
{
"cat":"Transformers",
"ques":"In Transformers: Dark of the Moon, at what famous Washington D.C. location did Carly Spencer and Sam Witwicky meet?",
"answ":"THE WHITE HOUSE",
"answ3":"WHITE HOUSE",
"answ2":"The White House.",
"option":["The White House", "Lincoln Memorial", "Washington Monument", "Smithsonian Institution Building"],
},
{
"cat":"Transformers",
"ques":"In Bumblebee, what sport was Charlie highly proficient in that she stepped away from because of a family tragedy?",
"answ":"DIVING",
"answ2":"Diving.",
"option":["Diving", "Soccer", "Basketball", "Baseball"],
},
{
"cat":"Transformers",
"ques":"In how many films of the Transformers franchise does Megan Fox appear?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"Transformers",
"ques":"Who played single father and struggling inventor Cade Yeager in Age of Extinction?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
"option":["Mark Wahlberg", "Chris Pratt", "Ryan Gosling", "Andrew Garfield"],
},
{
"cat":"Transformers",
"ques":"Who voiced Hound in Age of Extinction?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
"option":["John Goodman", "Peter Cullen", "Ken Watanabe", "John DiMaggio"],
},
{
"cat":"Transformers",
"ques":"Who voiced Hot Rod in Transformers: The Last Knight?",
"answ":"OMAR SY",
"answ2":"Omar Sy.",
"option":["Omar Sy", "Frank Welker", "Mark Ryan", "Michael B. Jordan"],
},
{
"cat":"Transformers",
"ques":"Who played Sir Edmund Burton in Transformers: The Last Knight?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
"option":["Anthony Hopkins", "Ian McKellen", "Jack Nicholson", "Morgan Freeman"],
},
{
"cat":"Transformers",
"ques":"Who voiced Drift in Age of Extinction?",
"answ":"KEN WATANABE",
"answ2":"Ken Watanabe.",
"option":["Ken Watanabe", "Reno Wilson", "T.J. Miller", "Peter Cullen"],
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played U.S. Air Force Combat Controller Robert Epps?",
"answ":"TYRESE GIBSON",
"answ2":"Tyrese Gibson.",
"option":["Tyrese Gibson", "Omar Sy", "Jamie Foxx", "Anthony Mackie"],
},
];
transformers = shuffle(transformers);
r2Q12 = shuffle(r2Q12);