var transformers = [
{
"cat":"Transformers",
"ques":"Which film in the Transformers franchise was released in 2018?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"In Transformers (2007), what is the name of the super secret government agency responsible for hiding the existence of Transformers?",
"answ":"SECTOR SEVEN",
"answ3":"SECTOR 7",
"answ2":"Sector Seven.",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played U.S. Secretary of Defense John Keller?",
"answ":"JON VOIGHT",
"answ2":"Jon Voight.",
},
{
"cat":"Transformers",
"ques":"Travis Knight directed which film in the Transformers franchise?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"In Transformers: The Movie, what is the name of the city the autobots have built on Earth?",
"answ":"AUTOBOT CITY",
"answ2":"Autobot City.",
},
{
"cat":"Transformers",
"ques":"Which Transformers film was released in 2014?",
"answ":"TRANSFORMERS AGE OF EXTINCTION",
"answ3":"AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
},
{
"cat":"Transformers",
"ques":"Who directed 2007's Transformers?",
"answ":"MICHAEL BAY",
"answ2":"Michael Bay.",
},
{
"cat":"Transformers",
"ques":"In the Transformers franchise, which Autobot is a yellow Chevrolet Camaro?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
},
{
"cat":"Transformers",
"ques":"Which actor played the role of Sam Witwicky in the Transformers franchise?",
"answ":"SHIA LABEOUF",
"answ3":"SHIA LEBEOUF",
"answ2":"Shia LaBeouf.",
},
{
"cat":"Transformers",
"ques":"In the Transformers series, what is Shia LaBeouf's first name?",
"answ":"SAM",
"answ2":"Sam.",
},
{
"cat":"Transformers",
"ques":"What is the subtitle of the first sequel to Michael Bay's Transformers?",
"answ":"REVENGE OF THE FALLEN",
"answ2":"Revenge of the Fallen.",
},
{
"cat":"Transformers",
"ques":"Who plays Mikaela Barnes in the Transformers franchise?",
"answ":"MEGAN FOX",
"answ2":"Megan Fox.",
},
];
var r2Q12 = [
{
"cat":"Transformers",
"ques":"Who voiced Daytrader in Transformers: The Last Knight?",
"answ":"STEVE BUSCEMI",
"answ2":"Steve Buscemi.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Steve Buscemi</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Tudyk</button><button id=incop3 class=buttons003 onclick=qinc()>Mark Ryan</button><button id=incop4 class=buttons003 onclick=qinc()>Reno Wilson</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Sam Witwicky's father?",
"answ":"KEVIN DUNN",
"answ2":"Kevin Dunn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kevin Dunn</button><button id=incop2 class=buttons003 onclick=qinc()>Dennis Quaid</button><button id=incop3 class=buttons003 onclick=qinc()>Jon Voight</button><button id=incop4 class=buttons003 onclick=qinc()>Denis Leary</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Sam Witwicky's mother?",
"answ":"JULIE WHITE",
"answ2":"Julie White.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Julie White</button><button id=incop2 class=buttons003 onclick=qinc()>Laura Linney</button><button id=incop3 class=buttons003 onclick=qinc()>Marisa Tomei</button><button id=incop4 class=buttons003 onclick=qinc()>Helen Mirren</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced The Fallen, in Transformers: Revenge of the Fallen?",
"answ":"TONY TODD",
"answ2":"Tony Todd.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tony Todd</button><button id=incop2 class=buttons003 onclick=qinc()>Samuel L. Jackson</button><button id=incop3 class=buttons003 onclick=qinc()>Forest Whitaker</button><button id=incop4 class=buttons003 onclick=qinc()>Laurence Fishburne</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played Captain William Lennox?",
"answ":"JOSH DUHAMEL",
"answ3":"JOSH DUMEL",
"answ2":"Josh Duhamel.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Josh Duhamel</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Bacon</button><button id=incop3 class=buttons003 onclick=qinc()>Ed Harris</button><button id=incop4 class=buttons003 onclick=qinc()>John Turturro</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, who played wealthy car collector Dylan Gould?",
"answ":"PATRICK DEMPSEY",
"answ2":"Patrick Dempsey.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Patrick Dempsey</button><button id=incop2 class=buttons003 onclick=qinc()>Aaron Eckhart</button><button id=incop3 class=buttons003 onclick=qinc()>Nicholas Hoult</button><button id=incop4 class=buttons003 onclick=qinc()>James Marsden</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, who played Bruce Brazos, Sam's employer and boss at Accuretta Systems?",
"answ":"JOHN MALKOVICH",
"answ2":"John Malkovich.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jon Voight</button><button id=incop2 class=buttons003 onclick=qinc()>John Goodman</button><button id=corop class=buttons003 onclick=qcor()>John Malkovich</button><button id=incop4 class=buttons003 onclick=qinc()>Patrick Stewart</button><br/>",
},
{
"cat":"Transformers",
"ques":"What Star Trek actor voiced Sentinel Prime in Transformers: Dark of the Moon?",
"answ":"LEONARD NIMOY",
"answ2":"Leonard Nimoy.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Pine</button><button id=incop2 class=buttons003 onclick=qinc()>William Shatner</button><button id=corop class=buttons003 onclick=qcor()>Leonard Nimoy</button><button id=incop4 class=buttons003 onclick=qinc()>Patrick Stewart</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Dark of the Moon, what comedian played paranoid software programmer Jerry 'Deep' Wang?",
"answ":"KEN JEONG",
"answ3":"KEN JONG",
"answ2":"Ken Jeong.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dave Chappelle</button><button id=incop2 class=buttons003 onclick=qinc()>Chevy Chase</button><button id=corop class=buttons003 onclick=qcor()>Ken Jeong</button><button id=incop4 class=buttons003 onclick=qinc()>Joel McHale</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, Sam says that Captain Witicky was one of the first to exlore what location?",
"answ":"ARCTIC CIRCLE",
"answ3":"THE ARCTIC CIRCLE",
"answ2":"The Arctic Circle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Madagascar</button><button id=incop2 class=buttons003 onclick=qinc()>Alaska</button><button id=corop class=buttons003 onclick=qcor()>Arctic Circle</button><button id=incop4 class=buttons003 onclick=qinc()>Iceland</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, what junk food was set before Rachel and Glen as they were being held in the interrogation room by Sector 7?",
"answ":"DONUTS",
"answ3":"DONUT",
"answ2":"Donuts.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cookies</button><button id=incop2 class=buttons003 onclick=qinc()>Cake</button><button id=corop class=buttons003 onclick=qcor()>Donuts</button><button id=incop4 class=buttons003 onclick=qinc()>Candy</button><br/>",
},
{
"cat":"Transformers",
"ques":"You can find the quote: 'They literally call themselves Decepticons, that doesn't set off any red flags?' in what film in the Transformers franchise?",
"answ":"BUMBLEBEE",
"answ2":"Bumblebee.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><button id=incop2 class=buttons003 onclick=qinc()>Transformers: The Last Knight</button><button id=corop class=buttons003 onclick=qcor()>Bumblebee</button><button id=incop4 class=buttons003 onclick=qinc()>Transformers: Age of Extinction</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who played Agent Seymour Simmons in the Transformers franchise?",
"answ":"JOHN TURTURRO",
"answ3":"JOHN TURTURO",
"answ2":"John Turturro.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cliff Curtis</button><button id=incop2 class=buttons003 onclick=qinc()>Antonio Banderas</button><button id=corop class=buttons003 onclick=qcor()>John Turturro</button><button id=incop4 class=buttons003 onclick=qinc()>Samuel L. Jackson</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who played Merlin in Transformers: The Last Knight?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tom Hardy</button><button id=incop2 class=buttons003 onclick=qinc()>Diego Luna</button><button id=corop class=buttons003 onclick=qcor()>Stanley Tucci</button><button id=incop4 class=buttons003 onclick=qinc()>B.D. Wong</button><br/>",
},
{
"cat":"Transformers",
"ques":"What is the name the Transformers give to the Cube that creates Transformers in the 2000s film Transformers?",
"answ":"ALL SPARK",
"answ3":"ALLSPARK",
"answ2":"AllSpark.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harvester</button><button id=incop2 class=buttons003 onclick=qinc()>Matrix</button><button id=corop class=buttons003 onclick=qcor()>AllSpark</button><button id=incop4 class=buttons003 onclick=qinc()>Creator</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, what is the name of Sam Witwicky's pet chihuahua?",
"answ":"MOJO",
"answ2":"Mojo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dexter</button><button id=incop2 class=buttons003 onclick=qinc()>Rex</button><button id=corop class=buttons003 onclick=qcor()>Mojo</button><button id=incop4 class=buttons003 onclick=qinc()>Billy</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who directed 1986's Transformers The Movie?",
"answ":"NELSON SHIN",
"answ2":"Nelson Shin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Igor Kovalyov</button><button id=incop2 class=buttons003 onclick=qinc()>David Silverman</button><button id=corop class=buttons003 onclick=qcor()>Nelson Shin</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Levant</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced Bumblebee in 2007's Transformers?",
"answ":"MARK RYAN",
"answ2":"Mark Ryan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugo Weaving</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Foxworth</button><button id=corop class=buttons003 onclick=qcor()>Mark Ryan</button><button id=incop4 class=buttons003 onclick=qinc()>Jess Harnell</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voices Megatron in 2007's Transformers?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Hugo Weaving</button><button id=incop2 class=buttons003 onclick=qinc()>Charlie Adler</button><button id=incop3 class=buttons003 onclick=qinc()>Mark Ryan</button><button id=incop4 class=buttons003 onclick=qinc()>Reno Wilson</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voices Optimus Prime in 2007's Transformers?",
"answ":"PETER CULLEN",
"answ2":"Peter Cullen.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Peter Cullen</button><button id=incop2 class=buttons003 onclick=qinc()>Hugo Weaving</button><button id=incop3 class=buttons003 onclick=qinc()>Nick Nolte</button><button id=incop4 class=buttons003 onclick=qinc()>Darius McCrary</button><br/>",
},
{
"cat":"Transformers",
"ques":"Which sci-fi legend was the voice of Galvatron in 1986's The Transformers?",
"answ":"LEONARD NIMOY",
"answ2":"Leonard Nimoy.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Leonard Nimoy</button><button id=incop2 class=buttons003 onclick=qinc()>William Shatner</button><button id=incop3 class=buttons003 onclick=qinc()>Mark Hamill</button><button id=incop4 class=buttons003 onclick=qinc()>Patrick Stewart</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced Hot Rod in 1986's The Transformers: The Movie?",
"answ":"JUDD NELSON",
"answ2":"Judd Nelson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Judd Nelson</button><button id=incop2 class=buttons003 onclick=qinc()>Scatman Crothers</button><button id=incop3 class=buttons003 onclick=qinc()>Corey Burton</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Cullen</button><br/>",
},
{
"cat":"Transformers",
"ques":"In which film of the franchise does character actor Mitch Pileggi appear as the TRF group leader?",
"answ":"THE LAST KNIGHT",
"answ3":"TRANSFORMERS THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Revenge of the Fallen</button><button id=incop2 class=buttons003 onclick=qinc()>Age of Extinction</button><button id=incop3 class=buttons003 onclick=qinc()>Dark of the Moon</button><button id=corop class=buttons003 onclick=qcor()>The Last Knight</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers: Revenge of the Fallen, in Sam Witwicki's college dorm there is a vending machine of what soda?",
"answ":"MOUNTAIN DEW",
"answ2":"Mountain Dew.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fanta</button><button id=incop2 class=buttons003 onclick=qinc()>Coca-Cola</button><button id=incop3 class=buttons003 onclick=qinc()>Sprite</button><button id=corop class=buttons003 onclick=qcor()>Mountain Dew</button><br/>",
},
{
"cat":"Transformers",
"ques":"Which Academy Award winning actress plays Charlotte Mearing, the Director of National Intelligence, in Transformers: Dark of the Moon?",
"answ":"FRANCES MCDORMAND",
"answ2":"Frances McDormand.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Marion Cotillard</button><button id=incop2 class=buttons003 onclick=qinc()>Cate Blanchett</button><button id=incop3 class=buttons003 onclick=qinc()>Olivia Colman</button><button id=corop class=buttons003 onclick=qcor()>Frances McDormand</button><br/>",
},
{
"cat":"Transformers",
"ques":"Which Transformers film ends with the quote: 'I am Optimus Prime and this message is to my creators: leave planet Earth alone, because I'm coming for you'?",
"answ":"TRANSFORMERS AGE OF EXTINCTION",
"answ3":"AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Last Knight</button><button id=incop2 class=buttons003 onclick=qinc()>Revenge of the Fallen</button><button id=incop3 class=buttons003 onclick=qinc()>Dark of the Moon</button><button id=corop class=buttons003 onclick=qcor()>Age of Extinction</button><br/>",
},
{
"cat":"Transformers",
"ques":"In what year does the movie Transformers: The Movie take place?",
"answ":"2005",
"answ2":"2005.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2000</button><button id=incop2 class=buttons003 onclick=qinc()>2025</button><button id=incop3 class=buttons003 onclick=qinc()>2015</button><button id=corop class=buttons003 onclick=qcor()>2005</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who plays Harold Attinger, a corrupt CIA operative and government official in Transformers: Age of Extinction?",
"answ":"KELSEY GRAMMER",
"answ2":"Kelsey Grammer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mark Strong</button><button id=corop class=buttons003 onclick=qcor()>Kelsey Grammer</button><button id=incop3 class=buttons003 onclick=qinc()>Stanley Tucci</button><button id=incop4 class=buttons003 onclick=qinc()>Nick Nolte</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers: Age of Extinction, who kills corrupt CIA operative Harold Attinger, played by Kelsey Grammar?",
"answ":"OPTIMUS PRIME",
"answ2":"Optimus Prime.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cade Yeager</button><button id=corop class=buttons003 onclick=qcor()>Optimus Prime</button><button id=incop3 class=buttons003 onclick=qinc()>Galvatron</button><button id=incop4 class=buttons003 onclick=qinc()>Crosshairs</button><br/>",
},
{
"cat":"Transformers",
"ques":"What Oscar nominee plays billionaire Joshua Joyce in Transformers: Age of Extinction?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mark Rylance</button><button id=corop class=buttons003 onclick=qcor()>Stanley Tucci</button><button id=incop3 class=buttons003 onclick=qinc()>Benicio del Toro</button><button id=incop4 class=buttons003 onclick=qinc()>Ben Kingsley</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers: Dark of the Moon, Sam Witwicky and Carly live in what city?",
"answ":"WASHINGTON DC",
"answ3":"DC",
"answ2":"Washington DC.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Las Vegas</button><button id=corop class=buttons003 onclick=qcor()>Washington DC</button><button id=incop3 class=buttons003 onclick=qinc()>Chicago</button><button id=incop4 class=buttons003 onclick=qinc()>Philadelphia</button><br/>",
},
{
"cat":"Transformers",
"ques":"The characters Ultra Magnus, Arcee and Kranix appear in which film?",
"answ":"THE TRANSFORMERS THE MOVIE",
"answ3":"TRANSFORMERS THE MOVIE",
"answ2":"The Transformers: The Movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers (2007)</button><button id=corop class=buttons003 onclick=qcor()>The Transformers: The Movie</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><button id=incop4 class=buttons003 onclick=qinc()>Transformers: Age of Extinction</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers (2007), Sam Witwicky and Mikaela Barnes are in what grade?",
"answ":"11TH",
"answ3":"ELEVENTH",
"answ2":"11th.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>9th</button><button id=corop class=buttons003 onclick=qcor()>11th</button><button id=incop3 class=buttons003 onclick=qinc()>10th</button><button id=incop4 class=buttons003 onclick=qinc()>12th</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers: The Last Knight, what is the name of Izabella's small robotic friend?",
"answ":"SQWEEKS",
"answ2":"Sqweeks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Pterry</button><button id=corop class=buttons003 onclick=qcor()>Sqweeks</button><button id=incop3 class=buttons003 onclick=qinc()>Scorn</button><button id=incop4 class=buttons003 onclick=qinc()>Slug</button><br/>",
},
{
"cat":"Transformers",
"ques":"In what film will you hear the quote: 'I'm asking you to look at all the junk and see the treasure. You got to have faith, Prime, in who we can be'?",
"answ":"AGE OF EXTINCTION",
"answ3":"TRANSFORMERS AGE OF EXTINCTION",
"answ2":"Transformers: Age of Extinction.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><button id=corop class=buttons003 onclick=qcor()>Transformers: Age of Extinction</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers: The Last Knight</button><button id=incop4 class=buttons003 onclick=qinc()>Transformers: Revenge of the Fallen</button><br/>",
},
{
"cat":"Transformers",
"ques":"In what Transformers film will you find the wizard Merlin helping the Guardian Knights?",
"answ":"TRANSFORMERS THE LAST KNIGHT",
"answ3":"THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Revenge of the Fallen</button><button id=corop class=buttons003 onclick=qcor()>Transformers: The Last Knight</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><button id=incop4 class=buttons003 onclick=qinc()>The Transformers: The Movie</button><br/>",
},
{
"cat":"Transformers",
"ques":"Laura Haddock plays Viviane Wembly, a professor of English Literature at the University of Oxford, in which Transformers movie?",
"answ":"THE LAST KNIGHT",
"answ3":"TRANSFORMERS THE LAST KNIGHT",
"answ2":"Transformers: The Last Knight.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Revenge of the Fallen</button><button id=corop class=buttons003 onclick=qcor()>Transformers: The Last Knight</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers (2007)</button><button id=incop4 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Bumblebee, Charlie's neighbor and friend Guillermo Gutierrez goes by what nickname?",
"answ":"MEMO",
"answ2":"Memo.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Guti</button><button id=corop class=buttons003 onclick=qcor()>Memo</button><button id=incop3 class=buttons003 onclick=qinc()>Mohawk</button><button id=incop4 class=buttons003 onclick=qinc()>Guille</button><br/>",
},
{
"cat":"Transformers",
"ques":"Which Transformers film begins with a Spanish speaking soldier named Fig wanting to eat alligator meat?",
"answ":"TRANSFORMERS",
"answ3":"TRANSFORMERS 2007",
"answ2":"Transformers (2007).",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Revenge of the Fallen</button><button id=corop class=buttons003 onclick=qcor()>Transformers (2007)</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers: Age of Extinction</button><button id=incop4 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><br/>",
},
{
"cat":"Transformers",
"ques":"Which Transformers film has the tagline: 'Beyond good, beyond evil, beyond your wildest imagination.'?",
"answ":"TRANSFORMERS THE MOVIE",
"answ3":"THE TRANSFORMERS THE MOVIE",
"answ2":"The Transformers: The Movie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Transformers: Revenge of the Fallen</button><button id=incop2 class=buttons003 onclick=qinc()>Transformers: Age of Extinction</button><button id=incop3 class=buttons003 onclick=qinc()>Transformers: Dark of the Moon</button><button id=corop class=buttons003 onclick=qcor()>The Transformers: The Movie</button><br/>",
},
{
"cat":"Transformers",
"ques":"How many film in the Transformers franchise has John Turturro appeared as the character Seymour Simmons?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=incop3 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Transformers: Dark of the Moon, at what famous Washington D.C. location did Carly Spencer and Sam Witwicky meet?",
"answ":"THE WHITE HOUSE",
"answ3":"WHITE HOUSE",
"answ2":"The White House.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lincoln Memorial</button><button id=incop2 class=buttons003 onclick=qinc()>Washington Monument</button><button id=incop3 class=buttons003 onclick=qinc()>Smithsonian Institution Building</button><button id=corop class=buttons003 onclick=qcor()>The White House</button><br/>",
},
{
"cat":"Transformers",
"ques":"In Bumblebee, what sport was Charlie highly proficient in that she stepped away from because of a family tragedy?",
"answ":"DIVING",
"answ2":"Diving.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soccer</button><button id=incop2 class=buttons003 onclick=qinc()>Basketball</button><button id=incop3 class=buttons003 onclick=qinc()>Baseball</button><button id=corop class=buttons003 onclick=qcor()>Diving</button><br/>",
},
{
"cat":"Transformers",
"ques":"In how many films of the Transformers franchise does Megan Fox appear?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=corop class=buttons003 onclick=qcor()>2</button><button id=incop3 class=buttons003 onclick=qinc()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who played single father and struggling inventor Cade Yeager in Age of Extinction?",
"answ":"MARK WAHLBERG",
"answ2":"Mark Wahlberg.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Pratt</button><button id=incop2 class=buttons003 onclick=qinc()>Ryan Gosling</button><button id=incop3 class=buttons003 onclick=qinc()>Andrew Garfield</button><button id=corop class=buttons003 onclick=qcor()>Mark Wahlberg</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced Hound in Age of Extinction?",
"answ":"JOHN GOODMAN",
"answ2":"John Goodman.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John Goodman</button><button id=incop2 class=buttons003 onclick=qinc()>Peter Cullen</button><button id=incop3 class=buttons003 onclick=qinc()>Ken Watanabe</button><button id=incop4 class=buttons003 onclick=qinc()>John DiMaggio</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced Hot Rod in Transformers: The Last Knight?",
"answ":"OMAR SY",
"answ2":"Omar Sy.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Omar Sy</button><button id=incop2 class=buttons003 onclick=qinc()>Frank Welker</button><button id=incop3 class=buttons003 onclick=qinc()>Mark Ryan</button><button id=incop4 class=buttons003 onclick=qinc()>Michael B. Jordan</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who played Sir Edmund Burton in Transformers: The Last Knight?",
"answ":"ANTHONY HOPKINS",
"answ2":"Anthony Hopkins.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Anthony Hopkins</button><button id=incop2 class=buttons003 onclick=qinc()>Ian McKellen</button><button id=incop3 class=buttons003 onclick=qinc()>Jack Nicholson</button><button id=incop4 class=buttons003 onclick=qinc()>Morgan Freeman</button><br/>",
},
{
"cat":"Transformers",
"ques":"Who voiced Drift in Age of Extinction?",
"answ":"KEN WATANABE",
"answ2":"Ken Watanabe.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Ken Watanabe</button><button id=incop2 class=buttons003 onclick=qinc()>Reno Wilson</button><button id=incop3 class=buttons003 onclick=qinc()>T.J. Miller</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Cullen</button><br/>",
},
{
"cat":"Transformers",
"ques":"In 2007's Transformers, who played U.S. Air Force Combat Controller Robert Epps?",
"answ":"TYRESE GIBSON",
"answ2":"Tyrese Gibson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Tyrese Gibson</button><button id=incop2 class=buttons003 onclick=qinc()>Omar Sy</button><button id=incop3 class=buttons003 onclick=qinc()>Jamie Foxx</button><button id=incop4 class=buttons003 onclick=qinc()>Anthony Mackie</button><br/>",
},
];
transformers = shuffle(transformers);
r2Q12 = shuffle(r2Q12);