var animated = [
{
"cat":"Animated",
"ques":"What school subject does Mr. Incredible struggle to teach to Dash, saying they 'changed it' in Incredibles 2?",
"answ":"MATH",
"answ3":"MATHEMATICS",
"answ2":"Math.",
},
{
"cat":"Animated",
"ques":"Actor Spencer Fox voices which character in The Incredibles?",
"answ":"DASH PARR",
"answ3":"DASH",
"answ2":"Dash Parr.",
},
{
"cat":"Animated",
"ques":"In The Adventures of Tintin, what is the name of the 17th century man-of-war ship commanded by Sir Francis Haddock?",
"answ":"THE UNICORN",
"answ2":"The Unicorn.",
},
{
"cat":"Animated",
"ques":"Who voices Gwen Stacy in Spider-Man: Into the Spider-Verse?",
"answ":"HAILEE STEINFELD",
"answ2":"Hailee Steinfeld.",
},
{
"cat":"Animated",
"ques":"What year saw the release of Incredibles 2?",
"answ":"2018",
"answ2":"2018.",
},
{
"cat":"Animated",
"ques":"What is the name of the superhero-killing battle robots created by Syndrome in The Incredibles?",
"answ":"OMNIDROID",
"answ3":"OMNIDROIDS",
"answ2":"Omnidroids.",
},
{
"cat":"Animated",
"ques":"Who voices the villainous Syndrome in 2004's The Incredibles?",
"answ":"JASON LEE",
"answ2":"Jason Lee.",
},
{
"cat":"Animated",
"ques":"The characters King Kong, Sauron and the Kraken appear in which animated film?",
"answ":"THE LEGO BATMAN MOVIE",
"answ3":"LEGO BATMAN MOVIE",
"answ2":"The Lego Batman Movie.",
},
{
"cat":"Animated",
"ques":"What 2018 animated superhero film features the song 'My Superhero Movie'?",
"answ":"TEEN TITANS GO TO THE MOVIES",
"answ3":"TEEN TITANS GO  TO THE MOVIES",
"answ2":"Teen Titans Go! to the Movies.",
},
{
"cat":"Animated",
"ques":"Which animated film begins with the main character singing 'Can't Help Falling in Love With You'?",
"answ":"STRANGE MAGIC",
"answ2":"Strange Magic.",
},
{
"cat":"Animated",
"ques":"In The Incredibles, what does Mr. Incredible realize he still has on right before his wedding?",
"answ":"HIS MASK",
"answ3":"MASK",
"answ2":"His mask.",
},
{
"cat":"Animated",
"ques":"You'll find the International Superhero Accord officially legalizing superheroes in what animated film?",
"answ":"THE INCREDIBLES 2",
"answ3":"INCREDIBLES 2",
"answ2":"The Incredibles 2.",
},
{
"cat":"Animated",
"ques":"In what film will you hear the quote: 'To think, all it took was one day in the Sahara! Congratulations, Captain, you're sober!'?",
"answ":"THE ADVENTURES OF TINTIN",
"answ3":"ADVENTURES OF TINTIN",
"answ2":"The Adventures of Tintin.",
},
{
"cat":"Animated",
"ques":"Who voices Miles' mother, Rio, in Spider-Man: Into the Spider-Verse?",
"answ":"LUNA LAUREN VELEZ",
"answ2":"Luna Lauren Velez.",
},
{
"cat":"Animated",
"ques":"You will find a cat named Squeaker being saved by a superhero in what animated film?",
"answ":"THE INCREDIBLES",
"answ2":"The Incredibles.",
},
{
"cat":"Animated",
"ques":"Who has a subtle cameo as a janitor on the Warner Brothers film lot in Teen Titans Go! To the Movies?",
"answ":"STAN LEE",
"answ2":"Stan Lee.",
},
{
"cat":"Animated",
"ques":"Which actress voices Barbara Gordon in The Lego Batman Movie?",
"answ":"ROSARIO DAWSON",
"answ2":"Rosario Dawson.",
},
{
"cat":"Animated",
"ques":"Who voiced Peter B. Parker in Spider-Man: Into the Spider-Verse?",
"answ":"JAKE JOHNSON",
"answ2":"Jake Johnson.",
},
{
"cat":"Animated",
"ques":"Who is appointed as the new Police Commissioner in Jim Gordon's place in The Lego Batman Movie?",
"answ":"BARBARA GORDON",
"answ2":"Barbara Gordon.",
},
{
"cat":"Animated",
"ques":"In The Adventures of Tintin, what is the name of Tintin's pet dog?",
"answ":"SNOWY",
"answ2":"Snowy.",
},
{
"cat":"Animated",
"ques":"What silly villain is terrorizing the city at the beginning of Teen Titans Go! To the Movies?",
"answ":"BALLOON MAN",
"answ2":"Balloon Man.",
},
{
"cat":"Animated",
"ques":"Who directed 2011's The Adventures of Tintin?",
"answ":"STEVEN SPIELBERG",
"answ2":"Steven Spielberg.",
},
{
"cat":"Animated",
"ques":"What is the name of the anime-style version of Spider-Man in Spider-Man: Into the Spider-Verse?",
"answ":"PENI PARKER",
"answ3":"PENNY PARKER",
"answ2":"Peni Parker.",
},
{
"cat":"Animated",
"ques":"What is the name of the inflatable healthcare robot in Disney's Big Hero 6?",
"answ":"BAYMAX",
"answ2":"Baymax.",
},
{
"cat":"Animated",
"ques":"In The Incredibles who provides the voice of Mr. Incredible?",
"answ":"CRAIG T NELSON",
"answ2":"Craig T. Nelson.",
},
{
"cat":"Animated",
"ques":"Which animated film, based on a Marvel comic, has a villain named Robert Callaghan, portrayed by James Cromwell?",
"answ":"BIG HERO 6",
"answ3":"BIG HERO SIX",
"answ2":"Big Hero 6.",
},
{
"cat":"Animated",
"ques":"What is the first name of the speedster son in The Incredibles?",
"answ":"DASH",
"answ3":"DASHIELL",
"answ2":"Dash.",
},
{
"cat":"Animated",
"ques":"Who voices the character of The Underminer in The Incredibles and The Incredibles 2?",
"answ":"JOHN RATZENBERGER",
"answ2":"John Ratzenberger.",
},
{
"cat":"Animated",
"ques":"Who provided the voice of Edna Mode in The Incredibles?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
},
{
"cat":"Animated",
"ques":"What is the name of the supervillain in The Incredibles?",
"answ":"SYNDROME",
"answ2":"Syndrome.",
},
{
"cat":"Animated",
"ques":"In The Incredibles, to what superhero is Mr. Incredible married?",
"answ":"ELASTIGIRL",
"answ2":"Elastigirl.",
},
{
"cat":"Animated",
"ques":"In what animated film does the villain say the line 'Your Angel of Death awaits' to all of its victims when it first appears to them?",
"answ":"BATMAN MASK OF THE PHANTASM",
"answ2":"Batman: Mask of the Phantasm.",
},
{
"cat":"Animated",
"ques":"Who voices Harley Quinn in The Lego Batman Movie?",
"answ":"JENNY SLATE",
"answ2":"Jenny Slate.",
},
{
"cat":"Animated",
"ques":"Who voices Batman in The Lego Batman Movie?",
"answ":"WILL ARNETT",
"answ2":"Will Arnett.",
},
{
"cat":"Animated",
"ques":"What Star Wars actor voices Two-Face in The Lego Batman Movie?",
"answ":"BILLY DEE WILLIAMS",
"answ2":"Billy Dee Williams.",
},
];
var r2Q15 = [
{
"cat":"Animated",
"ques":"In Big Hero 6, who voices Alistair Krei, an entrepreneur and tech guru who is the target of the masked villain?",
"answ":"ALAN TUDYK",
"answ3":"ALAN TUDIK",
"answ2":"Alan Tudyk.",
"option":["Alan Tudyk", "Benedict Cumberbatch", "Andy Serkis", "Jason Lee"],
},
{
"cat":"Animated",
"ques":"What late night talk show host lent his voice to the Riddler in The Lego Batman Movie?",
"answ":"CONAN O'BRIEN",
"answ2":"Conan O'Brien.",
"option":["Conan O'Brien", "Jimmy Fallon", "Jimmy Kimmel", "Stephen Colbert"],
},
{
"cat":"Animated",
"ques":"What is the first name of Hiro's older brother in Big Hero 6?",
"answ":"TADASHI",
"answ2":"Tadashi.",
"option":["Tadashi", "Baymax", "Go Go", "Wasabi"],
},
{
"cat":"Animated",
"ques":"In Teen Titans Go! To the Movies, what DC villain do the Titans try to convince to be their archnemesis?",
"answ":"SLADE WILSON",
"answ3":"DEATHSTROKE",
"answ2":"Slade Wilson/Deathstroke.",
"option":["Deathstroke", "Joker", "Penguin", "Riddler"],
},
{
"cat":"Animated",
"ques":"What Oscar winning actor voices Miles' uncle Aaron Davis in Spider-Man: Into the Spider-Verse?",
"answ":"MAHERSHALA ALI",
"answ3":"MAHARSHALA ALI",
"answ2":"Mahershala Ali.",
"option":["Mahershala Ali", "Denzel Washington", "Jamie Foxx", "Forest Whitaker"],
},
{
"cat":"Animated",
"ques":"Who kills mob boss Salvatore Valestra in Batman: Mask of the Phantasm?",
"answ":"THE JOKER",
"answ3":"JOKER",
"answ2":"The Joker.",
"option":["The Joker", "The Phantasm", "The Riddler", "Bane"],
},
{
"cat":"Animated",
"ques":"Who voices Superman in The Lego Batman Movie?",
"answ":"CHANNING TATUM",
"answ2":"Channing Tatum.",
"option":["Channing Tatum", "Jonah Hill", "Tom Hardy", "Will Arnett"],
},
{
"cat":"Animated",
"ques":"Who voices The Flash in The Lego Batman Movie?",
"answ":"ADAM DEVINE",
"answ2":"Adam DeVine.",
"option":["Adam DeVine", "Jesse Eisenberg", "Ezra Miller", "Zach Braff"],
},
{
"cat":"Animated",
"ques":"Who voiced the lead character of Tintin in The Adventures of Tintin?",
"answ":"JAMIE BELL",
"answ2":"Jamie Bell.",
"option":["Jamie Bell", "Justin Long", "Jesse Eisenberg", "Zach Braff"],
},
{
"cat":"Animated",
"ques":"Who directed The Incredibles?",
"answ":"BRAD BIRD",
"answ2":"Brad Bird.",
"option":["Brad Bird", "Lee Unkrich", "John Lasseter", "Pete Docter"],
},
{
"cat":"Animated",
"ques":"In Spider-Man: Into the Spider-Verse, under what New York City neighborhood is Kingpin's collider located?",
"answ":"BROOKLYN",
"answ2":"Brooklyn.",
"option":["Brooklyn", "Staten Island", "Harlem", "Queens"],
},
{
"cat":"Animated",
"ques":"In Big Hero 6, what is the name of the invention Hiro presents at the science fair that becomes stolen and used for evil?",
"answ":"MICROBOTS",
"answ2":"Microbots.",
"option":["Microbots", "Weather Pods", "Durachrome", "Gravity Tube"],
},
{
"cat":"Animated",
"ques":"In Batman: Mask of the Phantasm, what is the first name of Bruce's old flame, voiced by Dana Delany?",
"answ":"ANDREA",
"answ2":"Andrea.",
"option":["Andrea", "Daisy", "Chelsea", "Brooke"],
},
{
"cat":"Animated",
"ques":"In The Incredibles 2, what kind of animal does Jack-Jack get into a backyard scuffle with?",
"answ":"RACCOON",
"answ2":"Raccoon.",
"option":["Raccoon", "Cat", "Fox", "Pigeon"],
},
{
"cat":"Animated",
"ques":"In Big Hero 6, what comedic actor provides the voice for uber comic book fan and professional slacker, Fred?",
"answ":"TJ MILLER",
"answ3":"T J MILLER",
"answ2":"T.J. Miller.",
"option":["T.J. Miller", "James Franco", "Seth Rogen", "Jason Segel"],
},
{
"cat":"Animated",
"ques":"In Teen Titans Go! To the Movies, what talk show host voices Batman?",
"answ":"JIMMY KIMMEL",
"answ2":"Jimmy Kimmel.",
"option":["Jimmy Kimmel", "Stephen Colbert", "Seth Meyers", "Jimmy Fallon"],
},
{
"cat":"Animated",
"ques":"In The Lego Batman Movie, what is the name of the location that Batman sends the Joker to, where he assembles a super team of villains?",
"answ":"THE PHANTOM ZONE",
"answ3":"PHANTOM ZONE",
"answ2":"The Phantom Zone.",
"option":["The Phantom Zone", "Arkham Asylum", "Blackgate Penitentiary", "Glacier point"],
},
{
"cat":"Animated",
"ques":"In The Incredibles, Mr. Incredibles hides behind the skeleton of what former superhero to avoid detection?",
"answ":"GAZERBEAM",
"answ2":"Gazerbeam.",
"option":["Gazerbeam", "Blazestone", "Downburst", "Appogee"],
},
{
"cat":"Animated",
"ques":"What is the name of the villain that uses TV's to hypnotize people in The Incredibles 2?",
"answ":"SCREENSLAVER",
"answ3":"THE SCREENSLAVER",
"answ2":"Screenslaver.",
"option":["Screenslaver", "The Underminder", "Syndrome", "Mezmerella"],
},
{
"cat":"Animated",
"ques":"What is the name of the daughter that can turn invisible in The Incredibles?",
"answ":"VIOLET",
"answ2":"Violet.",
"option":["Violet", "Samantha", "Amber", "Susan"],
},
{
"cat":"Animated",
"ques":"In The Incredibles, hero costume designer Edna Mode never includes what in her costume designs?",
"answ":"CAPE",
"answ3":"CAPES",
"answ2":"Capes.",
"option":["Capes", "Purple", "Buttons", "Zippers"],
},
{
"cat":"Animated",
"ques":"In Incredibles 2, who voices Winston Deavor, a superhero fan who wants to bring superheroes through revamping the public's perception?",
"answ":"BOB ODENKIRK",
"answ2":"Bob Odenkirk.",
"option":["Bob Odenkirk", "Will Arnett", "Dustin Hoffman", "Ed Helms"],
},
{
"cat":"Animated",
"ques":"In The Incredibles, after the public turns on superheroes, the government initiates which program to force heroes to permanently keep their secret identities?",
"answ":"SUPERHERO RELOCATION PROGRAM",
"answ3":"THE SUPERHERO RELOCATION PROGRAM",
"answ2":"Superhero Relocation Program.",
"option":["Superhero Relocation Program", "Identity Change Program", "Superhero Eraser Program", "Identity Permanence Program"],
},
{
"cat":"Animated",
"ques":"Which character in The Incredibles tell Mr. Incredible: 'My God, you've gotten fat'?",
"answ":"ETNA MODE",
"answ3":"EDNA MODE",
"answ2":"Edna Mode.",
"option":["Edna Mode", "Mirage", "Syndrome", "Frozone"],
},
{
"cat":"Animated",
"ques":"In The Incredibles, Bob Parr's boss mentions that a company is like an enormous what?",
"answ":"CLOCK",
"answ2":"Clock.",
"option":["Clock", "Assembly Line", "Engine", "Piano"],
},
{
"cat":"Animated",
"ques":"Which member of the Teen Titans is voiced by Hynden Walch in Teen Titans Go! To the Movies",
"answ":"STARFIRE",
"answ2":"Starfire.",
"option":["Starfire", "Beast Boy", "Cyborg", "Raven"],
},
{
"cat":"Animated",
"ques":"What Star Wars actor voiced Legolas in 1978's Lord of the Rings?",
"answ":"ANTHONY DANIELS",
"answ2":"Anthony Daniels.",
"option":["Anthony Daniels", "Mark Hamill", "Han Solo", "Billy Dee Williams"],
},
{
"cat":"Animated",
"ques":"Who voices Frodo in 1978's Lord of the Rings?",
"answ":"CHRISTOPHER GUARD",
"answ2":"Christopher Guard.",
"option":["Christopher Guard", "William Squire", "Michael Graham Fox", "David Buck"],
},
{
"cat":"Animated",
"ques":"Who voices Robin in The Lego Batman Movie?",
"answ":"MICHAEL CERA",
"answ2":"Michael Cera.",
"option":["Michael Cera", "Justin Long", "Jonah Hill", "Jesse Eisenberg"],
},	
{
"cat":"Animated",
"ques":"Who directed 2017's The Lego Batman Movie?",
"answ":"CHRIS MCKAY",
"answ2":"Chris McKay.",
"option":["Chris McKay", "Phil Lord", "Tim Story", "Charlie Bean"],
},
{
"cat":"Animated",
"ques":"Who voices Catwoman in The Lego Batman Movie?",
"answ":"ZOE KRAVITZ",
"answ2":"Zoë Kravitz.",
"option":["Zoë Kravitz", "Angelina Jolie", "Scarlett Johansson", "Olivia Munn"],
},
{
"cat":"Animated",
"ques":"Who provided the voice of Miguel O'hara, also known as Spider-Man 2099, in Spider-Man: Into the Spider-Verse?",
"answ":"OSCAR ISAAC",
"answ2":"Oscar Isaac.",
"option":["Oscar Isaac", "Armie Hammer", "James Marsden", "Nicolas Cage"],
},
{
"cat":"Animated",
"ques":"Who composed the score for The Incredibles?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "Howard Shore", "Brad Bird"],
},
{
"cat":"Animated",
"ques":"What is the name of the baby in The Incredibles?",
"answ":"JACK JACK",
"answ2":"Jack Jack.",
"option":["Jack Jack", "John John", "Jeff Jeff", "Joe Joe"],
},
{
"cat":"Animated",
"ques":"Which part of Robin's body is comically small in Teen Titans Go! To the Movies?",
"answ":"HANDS",
"answ3":"HAND",
"answ2":"Hands.",
"option":["Hands", "Feet", "Ears", "Nose"],
},
{
"cat":"Animated",
"ques":"What is Batman's password to get into the Batcave in The Lego Batman Movie?",
"answ":"IRON MAN SUCKS",
"answ2":"Iron Man Sucks.",
"option":["Iron Man Sucks", "Bruce Wayne For President", "Password", "No Bats No Fun"],
},
{
"cat":"Animated",
"ques":"Which villain released Joker and the others from the Phantom Zone in The LEGO Batman Movie?",
"answ":"HARLEY QUINN",
"answ2":"Harley Quinn.",
"option":["Harley Quinn", "Penguin", "Deathstroke", "Riddler"],
},
{
"cat":"Animated",
"ques":"Who voices Aragorn in 1978's Lord of the Rings?",
"answ":"JOHN HURT",
"answ2":"John Hurt.",
"option":["John Hurt", "Donald Sutherland", "Christopher Lee", "Dustin Hoffman"],
},
{
"cat":"Animated",
"ques":"Mikey Kelley voices which turtle in TMNT (2007)?",
"answ":"MICHELANGELO",
"answ2":"Michelangelo.",
"option":["Michelangelo", "Raphael", "Donatello", "Leonardo"],
},
{
"cat":"Animated",
"ques":"Which actor is the voice of Unicron in The Transformers: The Movie?",
"answ":"ORSON WELLES",
"answ2":"Orson Welles.",
"option":["Orson Welles", "Paul Newman", "Peter Cullen", "Judd Nelson"],
},
{
"cat":"Animated",
"ques":"In The Incredibles, which character wears special gloves that freeze his targets and remove their gravity?",
"answ":"SYNDROME",
"answ2":"Syndrome.",
"option":["Syndrome", "Bomb Voyage", "The Underminer", "Frozone"],
},
{
"cat":"Animated",
"ques":"In Big Hero 6, Hiro Hamada is mildly allergic to what?",
"answ":"PEANUTS",
"answ3":"PEANUT",
"answ2":"Peanuts.",
"option":["Peanuts", "Chocolate", "Gluten", "Shellfish"],
},
{
"cat":"Animated",
"ques":"Samuel L. Jackson, Anthony Daniels and what other actor reprise their roles from the live action Star Wars films in The Clone Wars movie?",
"answ":"CHRISTOPHER LEE",
"answ2":"Christopher Lee.",
"option":["Christopher Lee", "Ewan McGregor", "Temuera Morrison", "Hayden Christensen"],
},
{
"cat":"Animated",
"ques":"At the start of The Incredibles, Bob is late for what event because he was out fighting crime?",
"answ":"HIS WEDDING",
"answ3":"WEDDING",
"answ2":"His wedding.",
"option":["His wedding", "His daughter's play", "Funeral", "His birthday"],
},
{
"cat":"Animated",
"ques":"Actor William Squire voices which character in 1978's The Lord of the Rings?",
"answ":"GANDALF",
"answ2":"Gandalf.",
"option":["Gandalf", "Aragorn", "Frodo", "Merry"],
},
{
"cat":"Animated",
"ques":"In The Adventures of Tintin, how many total miniature models of the Unicorn exist?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "4", "5"],
},
{
"cat":"Animated",
"ques":"Who directed Strange Magic?",
"answ":"GARY RYDSTROM",
"answ3":"GARY RIDSTROM",
"answ2":"Gary Rydstrom.",
"option":["Gary Rydstrom", "Andrew Stanton", "Dave Filoni", "Peter Docter"],
},
{
"cat":"Animated",
"ques":"What X-Men actor voices the Bog King in Strange Magic?",
"answ":"ALAN CUMMING",
"answ2":"Alan Cumming.",
"option":["Alan Cumming", "Michael Fassbender", "James Marsden", "Hugh Jackman"],
},
{
"cat":"Animated",
"ques":"Who voices Andrea Beaumont, also known as the Phantasm, in Batman: Mask of the Phantasm?",
"answ":"DANA DELANY",
"answ2":"Dana Delany.",
"option":["Dana Delany", "Jennifer Hale", "Laura Bailey", "Jeanne Tripplehorn"],
},
{
"cat":"Animated",
"ques":"Jonah Hill voices which DC superhero in The Lego Batman Movie?",
"answ":"GREEN LANTERN",
"answ2":"Green Lantern.",
"option":["Green Lantern", "Spider-Man", "Batman", "Superman"],
},
{
"cat":"Animated",
"ques":"In Into the Spider-Verse, when the film begins, how many years has Peter Parker been Spider-Man?",
"answ":"10",
"answ3":"10 YEARS",
"answ2":"10.",
"option":["10", "8", "6", "5"],
},
{
"cat":"Animated",
"ques":"In Spider-Man: Into the Spider-Verse, what Charles Dickens book does Miles have to write a book report about, that inspires his graffiti art later in the film?",
"answ":"GREAT EXPECTATIONS",
"answ2":"Great Expectations.",
"option":["Great Expectations", "Oliver Twist", "A Tale of Two Cities", "David Copperfield"],
},
{
"cat":"Animated",
"ques":"What animated film featured the line: 'Just remember, there's a thin line between being a hero and being a memory.'?",
"answ":"THE TRANSFORMRS THE MOVIE",
"answ2":"The Transformers: The Movie.",
"option":["The Transformers: The Movie", "Spider-Man: Into the Spider-Verse", "Batman: Mask of the Phantasm", "Big Hero 6"],
},
];
animated = shuffle(animated);
r2Q15 = shuffle(r2Q15);