var graphicnovels = [
{
"cat":"Graphic Novels",
"ques":"In what film will you see characters playing a video game called 'Ninja Ninja Revolution'?",
"answ":"SCOTT PILGRIM VS THE WORLD",
"answ3":"SCOTT PILGRIM VERSUS THE WORLD",
"answ2":"Scott Pilgrim vs. the World.",
},
{
"cat":"Graphic Novels",
"ques":"Which actress plays a sex worker named Mary Kelly in the film From Hell?",
"answ":"HEATHER GRAHAM",
"answ2":"Heather Graham.",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Maggie Greer, the wife of Bruce Willis' character in Surrogates?",
"answ":"ROSAMUND PIKE",
"answ2":"Rosamund Pike.",
},
{
"cat":"Graphic Novels",
"ques":"Who directed Watchmen?",
"answ":"ZACK SNYDER",
"answ2":"Zack Snyder.",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, who was president in 1985 and is currently on their third term?",
"answ":"RICHARD NIXON",
"answ3":"NIXON",
"answ2":"Richard Nixon.",
},
{
"cat":"Graphic Novels",
"ques":"Which actor plays Adrien Viedt aka Ozymandias in Watchmen?",
"answ":"MATRHEW GOODE",
"answ2":"Matthew Goode.",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Ava Lord in Sin City: A Dame to Kill For?",
"answ":"EVA GREEN",
"answ2":"Eva Green.",
},
{
"cat":"Graphic Novels",
"ques":"In Cowboys & Aliens, who plays Jake Lonergan, the protagonist who has memory loss?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
},
{
"cat":"Graphic Novels",
"ques":"In 300, who plays Dilios, the narrator of the story and one of the 300 who fought alongside Leonidas?",
"answ":"DAVID WENHAM",
"answ2":"David Wenham.",
},
{
"cat":"Graphic Novels",
"ques":"In Road to Perdition, who plays Connor, the unstable son of mob boss John Rooney?",
"answ":"DANIEL CRAIG",
"answ2":"Daniel Craig.",
},
{
"cat":"Graphic Novels",
"ques":"Who directed Cowboys & Aliens?",
"answ":"JON FAVREAU",
"answ2":"Jon Favreau.",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, which actress plays Sally Jupiter aka Silk Spectre 1?",
"answ":"CARLA GUGINO",
"answ2":"Carla Gugino.",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Irish mob boss John Rooney in Road to Perdition?",
"answ":"PAUL NEWMAN",
"answ2":"Paul Newman.",
},
{
"cat":"Graphic Novels",
"ques":"In Snowpiercer, who plays Gilliam, the elderly leader of the tail section and mentor to Curtis?",
"answ":"JOHN HURT",
"answ2":"John Hurt.",
},
{
"cat":"Graphic Novels",
"ques":"In Road to Perdition, who plays Maguire, a psychopathic killer who photographs his victims?",
"answ":"JUDE LAW",
"answ2":"Jude Law.",
},
{
"cat":"Graphic Novels",
"ques":"In what graphic novel adaptation will you find the character of Lorraine Broughton taking ice baths?",
"answ":"ATOMIC BLONDE",
"answ2":"Atomic Blonde.",
},
{
"cat":"Graphic Novels",
"ques":"What building is the target of V's attack at the end of V for Vendetta?",
"answ":"PARLIAMENT",
"answ3":"HOUSES OF PARLIAMENT",
"answ2":"Houses of Parliament/Parliament.",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Frank Nitti, a crime boss working under Al Capone in Road to Perdition?",
"answ":"STANLEY TUCCI",
"answ2":"Stanley Tucci.",
},
{
"cat":"Graphic Novels",
"ques":"What empire do the Spartans war against in 300, which Xerxes rules over?",
"answ":"PERSIAN",
"answ3":"PERSIA",
"answ2":"Persia.",
},
{
"cat":"Graphic Novels",
"ques":"In what graphic novel based film does Bill Nighy play a demon prince named Naberius?",
"answ":"I FRANKENSTEIN",
"answ2":"I, Frankenstein.",
},
{
"cat":"Graphic Novels",
"ques":"What city-state is Leonidas king of in the film 300?",
"answ":"SPARTA",
"answ2":"Sparta.",
},
{
"cat":"Graphic Novels",
"ques":"Which graphic novel adaptation stars Mickey Rourke, Josh Brolin, Jessica Alba and Eva Green?",
"answ":"SIN CITY A DAME TO KILL FOR",
"answ2":"Sin City: A Dame to Kill For.",
},
{
"cat":"Graphic Novels",
"ques":"What was the profession of Gordon Deitrich in V for Vendetta?",
"answ":"TALK SHOW HOST",
"answ3":"TV HOST",
"answ2":"Talk show host.",
},
{
"cat":"Graphic Novels",
"ques":"What 2000s film has supporting performances by Jennifer Jason Leigh, Dylan Baker and Ciarán Hinds?",
"answ":"ROAD TO PERDITION",
"answ2":"Road to Perdition.",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs the World, what is the full name of Scott's girlfriend played by Mary Elizabeth Winstead?",
"answ":"RAMONA FLOWERS",
"answ2":"Ramona Flowers.",
},
{
"cat":"Graphic Novels",
"ques":"Who portrayed Rorschach in Watchmen?",
"answ":"JACKIE EARLE HALEY",
"answ3":"JACKIE EARL HALEY",
"answ2":"Jackie Earle Haley.",
},
{
"cat":"Graphic Novels",
"ques":"Who played The Comedian in Watchmen?",
"answ":"JEFFREY DEAN MORGAN",
"answ2":"Jeffrey Dean Morgan.",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, Dr. Manhattan exiles himself to what planet?",
"answ":"MARS",
"answ2":"Mars.",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, Rorschach is framed for the murder of what former supervillain?",
"answ":"MOLOCH",
"answ2":"Moloch.",
},
{
"cat":"Graphic Novels",
"ques":"Lena Headey plays Queen Gorgo in which graphic novel adaptation?",
"answ":"300",
"answ2":"300.",
},
{
"cat":"Graphic Novels",
"ques":"In 300: Rise of an Empire, what was the name of the 'God King' Xerxes's father?",
"answ":"DARIUS",
"answ2":"Darius.",
},
{
"cat":"Graphic Novels",
"ques":"What is the name of the King of the opposing Persian army in Zack Snyder's 300?",
"answ":"XERXES",
"answ2":"Xerxes.",
},
{
"cat":"Graphic Novels",
"ques":"What 2005 film based on a graphic novel has such characters as John Hartigan, Marv and the Yellow Basterd?",
"answ":"SIN CITY",
"answ2":"Sin City.",
},
{
"cat":"Graphic Novels",
"ques":"Gerard Butler, Lena Headey and Michael Fassbender star in what 2007 graphic novel adaptation?",
"answ":"300",
"answ2":"300.",
},
{
"cat":"Graphic Novels",
"ques":"Finish the quote from V for Vendetta: 'Remember, Remember the ____ of November.'",
"answ":"FIFTH",
"answ3":"5TH",
"answ2":"Fifth.",
},
{
"cat":"Graphic Novels",
"ques":"Who directed A History of Violence?",
"answ":"DAVID CRONENBERG",
"answ3":"DAVID KRONENBERG",
"answ2":"David Cronenberg.",
},
{
"cat":"Graphic Novels",
"ques":"Who composed the score for A History of Violence?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
},
{
"cat":"Graphic Novels",
"ques":"Who starred as small town man, Tom Stall, in A History of Violence?",
"answ":"VIGGO MORTENSEN",
"answ2":"Viggo Mortensen.",
},
{
"cat":"Graphic Novels",
"ques":"Who played Tom Hank's character's son in the movie Road to Perdition?",
"answ":"TYLER HOECHLIN",
"answ3":"TYLER HOCHLIN",
"answ2":"Tyler Hoechlin.",
},
{
"cat":"Graphic Novels",
"ques":"Who directed Road to Perdition?",
"answ":"SAM MENDES",
"answ2":"Sam Mendes.",
},
{
"cat":"Graphic Novels",
"ques":"Who played V in V for Vendetta?",
"answ":"HUGO WEAVING",
"answ2":"Hugo Weaving.",
},
{
"cat":"Graphic Novels",
"ques":"Who played the role of Evey in V for Vendetta?",
"answ":"NATALIE PORTMAN",
"answ2":"Natalie Portman.",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Lorraine Broughton, a top-level MI6 agent, in 2017's Atomic Blonde?",
"answ":"CHARLIZE THERON",
"answ2":"Charlize Theron.",
},
];
var r2Q18 = [
{
"cat":"Graphic Novels",
"ques":"In what year does the majority of 2009's Watchmen take place?",
"answ":"1985",
"answ2":"1985.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1981</button><button id=corop class=buttons003 onclick=qcor()>1985</button><button id=incop3 class=buttons003 onclick=qinc()>1986</button><button id=incop4 class=buttons003 onclick=qinc()>1989</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is the name of Scott's high school girlfriend in Scott Pilgrim vs. the World?",
"answ":"KNIVES",
"answ3":"KNIVES CHAU",
"answ2":"Knives.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Stacey</button><button id=corop class=buttons003 onclick=qcor()>Knives</button><button id=incop3 class=buttons003 onclick=qinc()>Ramona</button><button id=incop4 class=buttons003 onclick=qinc()>Natalie</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What instrument does Kim play in Scott's band in Scott Pilgrim vs the World?",
"answ":"DRUMS",
"answ2":"Drums.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Saxophone</button><button id=corop class=buttons003 onclick=qcor()>Drums</button><button id=incop3 class=buttons003 onclick=qinc()>Piano</button><button id=incop4 class=buttons003 onclick=qinc()>Guitar</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What city is the scarred gangster Carl Fogarty from in A History of Violence?",
"answ":"PHILADELPHIA",
"answ2":"Philadelphia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicago</button><button id=corop class=buttons003 onclick=qcor()>Philadelphia</button><button id=incop3 class=buttons003 onclick=qinc()>San Francisco</button><button id=incop4 class=buttons003 onclick=qinc()>Detroit</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Which actor plays a gangster named Carl Fogarty in A History of Violence?",
"answ":"ED HARRIS",
"answ2":"Ed Harris.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>William Hurt</button><button id=corop class=buttons003 onclick=qcor()>Ed Harris</button><button id=incop3 class=buttons003 onclick=qinc()>Stephen McHattie</button><button id=incop4 class=buttons003 onclick=qinc()>Ciaran Hinds</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs The World, Scott and his girlfriend Knives talk about what club that she belongs to at school?",
"answ":"YEARBOOK CLUB",
"answ3":"YEAR BOOK CLUB",
"answ2":"Yearbook Club.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Glee Club</button><button id=corop class=buttons003 onclick=qcor()>Yearbook Club</button><button id=incop3 class=buttons003 onclick=qinc()>Film Club</button><button id=incop4 class=buttons003 onclick=qinc()>Chess Club</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In what year was Watchmen released?",
"answ":"2009",
"answ2":"2009.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2007</button><button id=corop class=buttons003 onclick=qcor()>2009</button><button id=incop3 class=buttons003 onclick=qinc()>2010</button><button id=incop4 class=buttons003 onclick=qinc()>2006</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, the original Minutemen superhero team formed during what year?",
"answ":"1939",
"answ2":"1939.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1937</button><button id=corop class=buttons003 onclick=qcor()>1939</button><button id=incop3 class=buttons003 onclick=qinc()>1941</button><button id=incop4 class=buttons003 onclick=qinc()>1943</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, what is the name of Hollis Mason's (aka Nite Owl) autobiography?",
"answ":"UNDER THE HOOD",
"answ2":"Under the Hood.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Trust In The Law</button><button id=incop2 class=buttons003 onclick=qinc()>An American Hero Story</button><button id=incop3 class=buttons003 onclick=qinc()>The Man behind the Legend</button><button id=corop class=buttons003 onclick=qcor()>Under the Hood</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In 2009's Watchmen, what is the name of the newspaper to which Rorschach sends his journal?",
"answ":"NEW FRONTIERSMAN",
"answ2":"New Frontiersman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Daily News</button><button id=incop2 class=buttons003 onclick=qinc()>Mail Watch</button><button id=incop3 class=buttons003 onclick=qinc()>New Mail Today</button><button id=corop class=buttons003 onclick=qcor()>New Frontiersman</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, what is the name of Nite Owl II's ship?",
"answ":"ARCHIMEDES",
"answ2":"Archimedes.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Archimedes</button><button id=incop2 class=buttons003 onclick=qinc()>Merlin</button><button id=incop3 class=buttons003 onclick=qinc()>Euclid</button><button id=incop4 class=buttons003 onclick=qinc()>Plutarch</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who played Nite Owl II in Watchmen?",
"answ":"PATRICK WILSON",
"answ2":"Patrick Wilson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jeffrey Dean Morgan</button><button id=incop2 class=buttons003 onclick=qinc()>Tim Blake Nelson</button><button id=corop class=buttons003 onclick=qcor()>Patrick Wilson</button><button id=incop4 class=buttons003 onclick=qinc()>Matthew Goode</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is Tom Hanks character's job in Road to Perdition?",
"answ":"HITMAN",
"answ3":"ASSASSIN",
"answ2":"Hitman/Assassin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Weatherman</button><button id=incop2 class=buttons003 onclick=qinc()>Teacher</button><button id=incop3 class=buttons003 onclick=qinc()>Baker</button><button id=corop class=buttons003 onclick=qcor()>Hitman</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What Lord of the Rings star plays Dilio, a Spartan soldier and narrator of 300?",
"answ":"DAVID WENHAM",
"answ2":"David Wenham.",
"option":"<button id=corop class=buttons003 onclick=qcor()>David Wenham</button><button id=incop2 class=buttons003 onclick=qinc()>Sean Bean</button><button id=incop3 class=buttons003 onclick=qinc()>Viggo Mortensen</button><button id=incop4 class=buttons003 onclick=qinc()>John Rhys-Davies</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays the female love interest to Charlize Theron in Atomic Blonde?",
"answ":"SOFIA BOUTELLA",
"answ3":"SOPHIA BOUTELLA",
"answ2":"Sofia Boutella.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mackenzie Davis</button><button id=incop2 class=buttons003 onclick=qinc()>Michelle Rodriguez</button><button id=corop class=buttons003 onclick=qcor()>Sofia Boutella</button><button id=incop4 class=buttons003 onclick=qinc()>Margot Robbie</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What city do Michael Sullivan and his son flee to after their family is killed in Road to Perdition?",
"answ":"CHICAGO",
"answ2":"Chicago.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miami</button><button id=incop2 class=buttons003 onclick=qinc()>Boston</button><button id=corop class=buttons003 onclick=qcor()>Chicago</button><button id=incop4 class=buttons003 onclick=qinc()>Detroit</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What planet does Dr. Manhattan exile himself on in Watchmen?",
"answ":"MARS",
"answ2":"Mars.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mercury</button><button id=incop2 class=buttons003 onclick=qinc()>Jupiter</button><button id=corop class=buttons003 onclick=qcor()>Mars</button><button id=incop4 class=buttons003 onclick=qinc()>Neptune</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is the first name of Jamie Bell's character in Snowpiercer?",
"answ":"EDGAR",
"answ2":"Edgar.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gilliam</button><button id=incop2 class=buttons003 onclick=qinc()>Mason</button><button id=corop class=buttons003 onclick=qcor()>Edgar</button><button id=incop4 class=buttons003 onclick=qinc()>Curtis</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Atomic Blonde, what is the name of the micro-document that contains names of intelligence agents?",
"answ":"THE LIST",
"answ2":"The List.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Satchel</button><button id=incop2 class=buttons003 onclick=qinc()>The Spyglass</button><button id=corop class=buttons003 onclick=qcor()>The List</button><button id=incop4 class=buttons003 onclick=qinc()>The Watch</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs the World, how many total evil exes must Scott defeat?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>6</button><button id=incop2 class=buttons003 onclick=qinc()>5</button><button id=incop3 class=buttons003 onclick=qinc()>8</button><button id=corop class=buttons003 onclick=qcor()>7</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is the actual name of the city in Sin City?",
"answ":"BASIN CITY",
"answ2":"Basin City.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Los Angelinos</button><button id=incop2 class=buttons003 onclick=qinc()>Andreas</button><button id=corop class=buttons003 onclick=qcor()>Basin City</button><button id=incop4 class=buttons003 onclick=qinc()>Diggsville</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In what year was V for Vendetta released?",
"answ":"2005",
"answ2":"2005.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2003</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=corop class=buttons003 onclick=qcor()>2005</button><button id=incop4 class=buttons003 onclick=qinc()>2006</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Atomic Blonde, the film primarily takes place in what decade?",
"answ":"1980S",
"answ3":"80S",
"answ2":"1980s.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1960s</button><button id=incop2 class=buttons003 onclick=qinc()>1970s</button><button id=corop class=buttons003 onclick=qcor()>1980s</button><button id=incop4 class=buttons003 onclick=qinc()>1990s</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays the character Julie Powers in Scott Pilgrim vs The World?",
"answ":"AUBREY PLAZA",
"answ2":"Aubrey Plaza.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kirsten Dunst</button><button id=incop2 class=buttons003 onclick=qinc()>Brie Larson</button><button id=corop class=buttons003 onclick=qcor()>Aubrey Plaza</button><button id=incop4 class=buttons003 onclick=qinc()>Hilary Duff</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What company does Ramona work for in Scott Pilgrim vs. the World?",
"answ":"AMAZON",
"answ2":"Amazon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Postal Service</button><button id=incop2 class=buttons003 onclick=qinc()>FedEx</button><button id=corop class=buttons003 onclick=qcor()>Amazon</button><button id=incop4 class=buttons003 onclick=qinc()>UPS</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays police inspector Finch in V for Vendetta?",
"answ":"STEPHEN REA",
"answ2":"Stephen Rea.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugo Weaving</button><button id=incop2 class=buttons003 onclick=qinc()>John Hurt</button><button id=corop class=buttons003 onclick=qcor()>Stephen Rea</button><button id=incop4 class=buttons003 onclick=qinc()>Clive Owen</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In A History of Violence, Viggo Mortensen's character calls attention to himself by killing two armed robbers at what type of location?",
"answ":"DINER",
"answ3":"RESTAURANT",
"answ2":"Diner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Library</button><button id=incop2 class=buttons003 onclick=qinc()>Movie Theater</button><button id=corop class=buttons003 onclick=qcor()>Diner</button><button id=incop4 class=buttons003 onclick=qinc()>Police station</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Which graphic novel adaptation begins with the line: 'Earth before the war. New York before I was born. A place I've only seen pictures of.'?",
"answ":"OBLIVION",
"answ2":"Oblivion.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Watchmen</button><button id=incop2 class=buttons003 onclick=qinc()>Cowboys & Aliens</button><button id=corop class=buttons003 onclick=qcor()>Oblivion</button><button id=incop4 class=buttons003 onclick=qinc()>From Hell</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Oblivion, what is the name of the supposed alien species that invaded Earth and roams the planet?",
"answ":"SCAVENGERS",
"answ2":"Scavengers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ravagers</button><button id=incop2 class=buttons003 onclick=qinc()>Roamers</button><button id=incop3 class=buttons003 onclick=qinc()>Soarers</button><button id=corop class=buttons003 onclick=qcor()>Scavengers</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In V for Vendetta, V refers to his home by what name?",
"answ":"SHADOW GALLERY",
"answ2":"Shadow Gallery.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shadow Suite</button><button id=incop2 class=buttons003 onclick=qinc()>Monte Manor</button><button id=corop class=buttons003 onclick=qcor()>Shadow Gallery</button><button id=incop4 class=buttons003 onclick=qinc()>Cristo Manor</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In A History of Violence, what sport are the high school kids playing in gym class?",
"answ":"DODGEBALL",
"answ2":"Dodgeball.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Baseball</button><button id=incop2 class=buttons003 onclick=qinc()>Basketball</button><button id=incop3 class=buttons003 onclick=qinc()>Football</button><button id=incop4 class=buttons003 onclick=qinc()>Dodgeball</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs the World, Ramona's evil ex Lucas Lee is a rising actor who also used to be what kind of professional athlete?",
"answ":"SKATEBOARDER",
"answ2":"Skateboarder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sprinter</button><button id=incop2 class=buttons003 onclick=qinc()>Swimmer</button><button id=incop3 class=buttons003 onclick=qinc()>Surfer</button><button id=corop class=buttons003 onclick=qcor()>Skateboarder</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Watchmen, who is revealed to ultimately be behind the major villainous activitities throughout the film?",
"answ":"OZYMANDIAS",
"answ2":"Ozymandias.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nite Owl</button><button id=corop class=buttons003 onclick=qcor()>Ozymandias</button><button id=incop3 class=buttons003 onclick=qinc()>Dr. Manhattan</button><button id=incop4 class=buttons003 onclick=qinc()>Silk Spectre II</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs The World, who plays Gideon Graves, Ramona's 7th evil ex and the founder of The League?",
"answ":"JASON SCHWARTZMAN",
"answ2":"Jason Schwartzman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chris Evans</button><button id=incop2 class=buttons003 onclick=qinc()>Mark Webber</button><button id=incop3 class=buttons003 onclick=qinc()>Brandon Routh</button><button id=corop class=buttons003 onclick=qcor()>Jason Schwartzman</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays the silent psycho killer Kevin in Sin City?",
"answ":"ELIJAH WOOD",
"answ2":"Elijah Wood.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Elijah Wood</button><button id=incop2 class=buttons003 onclick=qinc()>Bruce Willis</button><button id=incop3 class=buttons003 onclick=qinc()>Rutger Hauer</button><button id=incop4 class=buttons003 onclick=qinc()>Benicio del Toro</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Theron, a corrupt Spartan politician in 300?",
"answ":"DOMINIC WEST",
"answ2":"Dominic West.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Dominic West</button><button id=incop2 class=buttons003 onclick=qinc()>Tom Wisdom</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Fassbender</button><button id=incop4 class=buttons003 onclick=qinc()>Peter Mensah</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs. The World, what is Scott Pilgrim's favorite food that he makes for Ramona and he says he could eat for every meal?",
"answ":"GARLIC BREAD",
"answ2":"Garlic Bread.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Garlic Bread</button><button id=incop2 class=buttons003 onclick=qinc()>Marshmallows</button><button id=incop3 class=buttons003 onclick=qinc()>Pancakes</button><button id=incop4 class=buttons003 onclick=qinc()>Scrambled Eggs</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What color does Knives dye her hair to try and compete with Ramona in Scott Pilgrim vs. the World?",
"answ":"BLUE",
"answ2":"Blue.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Blue</button><button id=incop2 class=buttons003 onclick=qinc()>Red</button><button id=incop3 class=buttons003 onclick=qinc()>Orange</button><button id=incop4 class=buttons003 onclick=qinc()>Green</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In 300, what are the only things that the god king Xerxes requires of Sparta, as said by his messenger?",
"answ":"EARTH AND WATER",
"answ3":"WATER AND EARTH",
"answ2":"Earth and Water.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blood and Armor</button><button id=corop class=buttons003 onclick=qcor()>Earth and Water</button><button id=incop3 class=buttons003 onclick=qinc()>Weapons and Armor</button><button id=incop4 class=buttons003 onclick=qinc()>Food and Water</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What was Brie Larson's character name before going by Envy in Scott Pilgrim vs. The World?",
"answ":"NATALIE",
"answ2":"Natalie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Maggie</button><button id=corop class=buttons003 onclick=qcor()>Natalie</button><button id=incop3 class=buttons003 onclick=qinc()>Caroline</button><button id=incop4 class=buttons003 onclick=qinc()>Rebecca</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Which actress plays Envy Adams in Scott Pilgrim vs The World?",
"answ":"BRIE LARSON",
"answ2":"Brie Larson.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Alba</button><button id=corop class=buttons003 onclick=qcor()>Brie Larson</button><button id=incop3 class=buttons003 onclick=qinc()>Jessica Simpson</button><button id=incop4 class=buttons003 onclick=qinc()>Megan Fox</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Richie Cusack, a mob boss working out of Philadelphia in A History of Violence?",
"answ":"WILLIAM HURT",
"answ2":"William Hurt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Peter Stomare</button><button id=corop class=buttons003 onclick=qcor()>William Hurt</button><button id=incop3 class=buttons003 onclick=qinc()>John Goodman</button><button id=incop4 class=buttons003 onclick=qinc()>Viggo Mortensen</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Dwight McCarthy in 2014's Sin City?",
"answ":"CLIVE OWEN",
"answ2":"Clive Owen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Eric Bana</button><button id=corop class=buttons003 onclick=qcor()>Clive Owen</button><button id=incop3 class=buttons003 onclick=qinc()>Frank Grillo</button><button id=incop4 class=buttons003 onclick=qinc()>Adam Driver</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is the nickname of Gideon Graves in Scott Pilgrim vs the World?",
"answ":"G MAN",
"answ2":"G-Man.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Grave-Digger</button><button id=corop class=buttons003 onclick=qcor()>G-Man</button><button id=incop3 class=buttons003 onclick=qinc()>Big G</button><button id=incop4 class=buttons003 onclick=qinc()>The OG</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What graphic novel based film features heroic performances by Miranda Otto and Jai Courtney opposing a villainous Bill Nighy?",
"answ":"I FRANKENSTEIN",
"answ2":"I Frankenstein.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>V for Vendetta</button><button id=corop class=buttons003 onclick=qcor()>I Frankenstein</button><button id=incop3 class=buttons003 onclick=qinc()>The Shadow</button><button id=incop4 class=buttons003 onclick=qinc()>From Hell</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who stars as Nancy, an exotic dancer appearing in multiple storylines in 2005's Sin City?",
"answ":"JESSICA ALBA",
"answ2":"Jessica Alba.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Salma Hayek</button><button id=corop class=buttons003 onclick=qcor()>Jessica Alba</button><button id=incop3 class=buttons003 onclick=qinc()>Amanda Seyfried</button><button id=incop4 class=buttons003 onclick=qinc()>Jennifer Lopez</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Scott Pilgrim's sister, Stacey, in the graphic novel-based Scott Pilgrim vs the World?",
"answ":"ANNA KENDRICK",
"answ2":"Anna Kendrick.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Miley Cyrus</button><button id=corop class=buttons003 onclick=qcor()>Anna Kendrick</button><button id=incop3 class=buttons003 onclick=qinc()>Hilary Duff</button><button id=incop4 class=buttons003 onclick=qinc()>Brie Larson</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In V for Vendetta, who played closeted homosexual and talk show host Gordon Deitrich?",
"answ":"STEPHEN FRY",
"answ2":"Stephen Fry.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hugh Laurie</button><button id=incop2 class=buttons003 onclick=qinc()>Woody Harrelson</button><button id=incop3 class=buttons003 onclick=qinc()>Mel Brooks</button><button id=corop class=buttons003 onclick=qcor()>Stephen Fry</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs the World, what type of police take away Todd Ingram's superhuman powers?",
"answ":"VEGAN POLICE",
"answ3":"VEGAN",
"answ2":"Vegan Police.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Fashion Police</button><button id=incop2 class=buttons003 onclick=qinc()>Superhuman Police</button><button id=incop3 class=buttons003 onclick=qinc()>Secret Police</button><button id=corop class=buttons003 onclick=qcor()>Vegan Police</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In Scott Pilgrim vs the World, what color is Ramona's hair when Scott first meets her?",
"answ":"PINK",
"answ2":"Pink.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Orange</button><button id=incop2 class=buttons003 onclick=qinc()>Green</button><button id=incop3 class=buttons003 onclick=qinc()>Blue</button><button id=corop class=buttons003 onclick=qcor()>Pink</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Ramona Flowers in Scott Pilgrim vs The World?",
"answ":"MARY ELIZABETH WINSTEAD",
"answ3":"MARY ELISABETH WINSTEAD",
"answ2":"Mary Elizabeth Winstead.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Megan Fox</button><button id=incop2 class=buttons003 onclick=qinc()>Amy Adams</button><button id=incop3 class=buttons003 onclick=qinc()>Aubrey Plaza</button><button id=corop class=buttons003 onclick=qcor()>Mary Elizabeth Winstead</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"What is the name of the explosive drug in Snowpiercer?",
"answ":"KRONOLE",
"answ3":"CRONOLE",
"answ2":"Kronole.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soma</button><button id=incop2 class=buttons003 onclick=qinc()>Ketracel White</button><button id=incop3 class=buttons003 onclick=qinc()>Melange</button><button id=corop class=buttons003 onclick=qcor()>Kronole</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who directed V for Vendetta?",
"answ":"JAMES MCTEIGUE",
"answ2":"James McTeigue.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dave Green</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Rodriguez</button><button id=incop3 class=buttons003 onclick=qinc()>Alex Garland</button><button id=corop class=buttons003 onclick=qcor()>James McTeigue</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"Who plays Bob, a cop who betrays Bruce Willis' character in Sin City?",
"answ":"MICHAEL MADSEN",
"answ2":"Michael Madsen.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Steve Buscemi</button><button id=incop2 class=buttons003 onclick=qinc()>Peter Stormare</button><button id=incop3 class=buttons003 onclick=qinc()>Clive Owen</button><button id=corop class=buttons003 onclick=qcor()>Michael Madsen</button><br/>",
},
{
"cat":"Graphic Novels",
"ques":"In I Frankenstein, what type of creatures are the characters played by Miranda Otto and Jai Courtney?",
"answ":"GARGOYLES",
"answ3":"GARGOYLE",
"answ2":"Gargoyles.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Werewolves</button><button id=incop2 class=buttons003 onclick=qinc()>Trolls</button><button id=incop3 class=buttons003 onclick=qinc()>Vampires</button><button id=corop class=buttons003 onclick=qcor()>Gargoyles</button><br/>",
},
];
graphicnovels = shuffle(graphicnovels);
r2Q18 = shuffle(r2Q18);