var dystopiantime = [
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part 3, Clara briefly gets on a train headed to what city, when she believes her relationship with Doc is over?",
"answ":"SAN FRANCISCO",
"answ2":"San Francisco.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Gloria Foster and Mary Alice both play what role in the Matrix trilogy?",
"answ":"THE ORACLE",
"answ2":"The Oracle.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who portrays Thomas Anderson's business partner named Smith in The Matrix Resurrections?",
"answ":"JONATHAN GROFF",
"answ2":"Jonathan Groff.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Harry Lennix portrays a commander in the Matrix trilogy. What is his name?",
"answ":"LOCK",
"answ2":"Lock.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Link, the operator on the Nebuchadnezzar who takes over for Tank, in The Matrix Reloaded and The Matrix Revolutions?",
"answ":"HAROLD PERRINEAU",
"answ2":"Harold Perrineau.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Barnes, John Connor's right-hand man, in Terminator Salvation?",
"answ":"COMMON",
"answ2":"Common.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What franchise character was killed off during the opening scene at a beach resort in Terminator: Dark Fate?",
"answ":"JOHN CONNOR",
"answ2":"John Connor.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays the role of Miles Dyson in Terminator Genisys?",
"answ":"COURTNEY B VANCE",
"answ2":"Courtney B. Vance.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What director played the role of Chad, Tiffany's husband inside the Matrix, in the film The Matrix Resurrections?",
"answ":"CHAD STAHELSKI",
"answ2":"Chad Stahelski.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays the role of O'Brien, a detective in San Francisco Police Department in the year 2017 who investigates time travelers in the film Terminator Genisys?",
"answ":"JK SIMMONS",
"answ2":"J. K. Simmons.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part III, to what year does Marty time travel to in the old west?",
"answ":"1885",
"answ2":"1885.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what is the name of the housing development where Marty's family lives in 2015?",
"answ":"HILLDALE",
"answ2":"Hilldale.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what is the name of Marty McFly's son, who is also played by Michael J. Fox?",
"answ":"MARTY MCFLY JR",
"answ2":"Marty McFly, Jr.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, when Marty first meets young Doc in 1955, Doc is wearing a device on his head that he built to enable him to do what?",
"answ":"READ SOMEONE ELSE'S THOUGHTS",
"answ3":"READ SOMEONE ELSE'S MIND",
"answ2":"Read someone else's thoughts.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Finish this line spoken by Buford Tannen in the third BTTF film: 'Eight o'clock Monday, runt. If you ain't here, I'll hunt you and shoot you down like a ____'?",
"answ":"DUCK",
"answ2":"Duck.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the Back to the Future series, who plays Seamus McFly?",
"answ":"MICHAEL J FOX",
"answ2":"Michael J. Fox.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, when 1955 Doc hears that Ronald Reagan is President in 1985, he jokingly asks if who is Vice President?",
"answ":"JERRY LEWIS",
"answ2":"Jerry Lewis.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Name the actress who played Jennifer in the first Back to the Future film.",
"answ":"CLAUDIA WELLS",
"answ2":"Claudia Wells.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who co-wrote the entire Back to the Future trilogy with Robert Zemeckis?",
"answ":"BOB GALE",
"answ2":"Bob Gale.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what does Marty call the nifty feature that Nike sneakers have in 2015?",
"answ":"POWER LACES",
"answ2":"Power laces.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Matrix trilogy, what is the name of the Prophet who assists Neo in his quest?",
"answ":"THE ORACLE",
"answ2":"The Oracle.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, who stars as Curtis Everett, the heroic leader of the revolution?",
"answ":"CHRIS EVANS",
"answ2":"Chris Evans.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who stars as Rev-9, an advanced Terminator that originated from Legion and was sent back in time to terminate Dani in Terminator: Dark Fate?",
"answ":"GABRIEL LUNA",
"answ2":"Gabriel Luna.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which dystopian film features performances from Michael Jeter, Jack Black and Jeanne Tripplehorn?",
"answ":"WATERWORLD",
"answ2":"Waterworld.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, old Marty is goaded into participating in an illegal scam by a co-worker, leading to his termination. What was the co-workers name?",
"answ":"DOUGLAS NEEDLES",
"answ3":"NEEDLES",
"answ2":"Douglas Needles.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, after being caught by Strickland, Marty McFly now has how many tardies in a row?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"The T-800 has begun living as a human and goes by what name in Terminator: Dark Fate?",
"answ":"CARL",
"answ2":"Carl.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part 2, which character has a face-to-face encounter with their future self in the year 2015, causing them to faint?",
"answ":"JENNIFER",
"answ3":"JENNIFER PARKER",
"answ2":"Jennifer.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Mary Alice plays the Oracle in what 2000s dystopian film?",
"answ":"THE MATRIX REVOLUTIONS",
"answ3":"MATRIX REVOLUTIONS",
"answ2":"The Matrix Revolutions.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, who does Marty tell he should run for mayor while he's traveled back to 1955?",
"answ":"GOLDIE WILSON",
"answ2":"Goldie Wilson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the town that Aunty Entity helps run, where the Thunderdome is located, in Mad Max Beyond Thunderdome?",
"answ":"BARTER TOWN",
"answ3":"BARTERTOWN",
"answ2":"Barter Town.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays the villainous character known as The Deacon in Waterworld?",
"answ":"DENNIS HOPPER",
"answ2":"Dennis Hopper.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In which Terminator film does John Connor say: 'You're nothing but a relic from a deleted timeline.'?",
"answ":"TERMINATOR GENISYS",
"answ2":"Terminator Genisys.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which Oscar nominee plays Pat Novak, host of The Novak Element and prominent supporter of mechanized crime control in the film RoboCop (2014)?",
"answ":"SAMUEL L JACKSON",
"answ2":"Samuel L. Jackson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Peter Hyams directed what 1994 film featuring Mia Sara?",
"answ":"TIMECOP",
"answ2":"Timecop.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which dystopian film begins with the line: 'My name is Max. My world is fire and blood.'?",
"answ":"MAD MAX FURY ROAD",
"answ2":"Mad Max: Fury Road.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Alex, an advanced T-5000 who embodies Skynet, in Terminator Genisys?",
"answ":"MATT SMITH",
"answ2":"Matt Smith.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Matrix franchise, who is said to be the father of the Matrix if the Oracle is the mother?",
"answ":"THE ARCHITECT",
"answ3":"ARCHITECT",
"answ2":"The Architect.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which actor played the character of Immortan Joe in Mad Max: Fury Road?",
"answ":"HUGH KEAYS BYRNE",
"answ3":"HUGH KEYS BYRNE",
"answ2":"Hugh Keays-Byrne.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, who plays Edgar, Curtis' friend and second-in-command?",
"answ":"JAMIE BELL",
"answ2":"Jamie Bell.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who directed Snowpiercer?",
"answ":"BONG JOON HO",
"answ2":"Bong Joon-ho.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Lord Humungus is the name of the main villain from which film in the Mad Max franchise?",
"answ":"MAD MAX 2",
"answ3":"THE ROAD WARRIOR",
"answ2":"Mad Max 2/The Road Warrior.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What singer plays Aunty Entity in Mad Max Beyond Thunderdome?",
"answ":"TINA TURNER",
"answ2":"Tina Turner.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the subtitle for the third Mad Max film?",
"answ":"BEYOND THUNDERDOME",
"answ2":"Beyond Thunderdome.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which actor plays the title character in the 1979 film Mad Max?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the only Mad Max film that George Miller did not direct on his own?",
"answ":"MAD MAX BEYOND THUNDERDOME",
"answ2":"Mad Max Beyond Thunderdome.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In which Terminator film is Arnold Schwarzenegger's character referred to as the Guardian?",
"answ":"TERMINATOR GENISYS",
"answ2":"Terminator Genisys.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which actor plays the title character in the 1979 film Mad Max?",
"answ":"MEL GIBSON",
"answ2":"Mel Gibson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Morpheus' team in The Matrix features two brothers, Tank and ____.",
"answ":"DOZER",
"answ2":"Dozer.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of Laurence Fishburne's character in The Matrix?",
"answ":"MORPHEUS",
"answ2":"Morpheus.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Agent Smith in The Matrix trilogy?",
"answ":"HUGO WEAVING",
"answ3":"HUGO WEEVING",
"answ2":"Hugo Weaving.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the being that Neo encounters in the room with all the tv monitors at the end of The Matrix Reloaded?",
"answ":"ARCHITECT",
"answ3":"THE ARCHITECT",
"answ2":"The Architect.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Trinity in The Matrix Trilogy?",
"answ":"CARRIE ANNE MOSS",
"answ2":"Carrie-Anne Moss.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was the name of the 2nd film in The Matrix Trilogy?",
"answ":"THE MATRIX RELOADED",
"answ3":"MATRIX RELOADED",
"answ2":"The Matrix Reloaded.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was Neo's last name before he was awoken in The Matrix?",
"answ":"ANDERSON",
"answ2":"Anderson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Minister Mason, Minister Wilford's right hand in Snowpiercer?",
"answ":"TILDA SWINTON",
"answ2":"Tilda Swinton.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, what type of vehicle is the Snowpiercer?",
"answ":"TRAIN",
"answ2":"Train.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played George McFly in Back to the Future?",
"answ":"CRISPIN GLOVER",
"answ2":"Crispin Glover.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Lorraine McFly in Back to the Future?",
"answ":"LEA THOMPSON",
"answ3":"LEA THOMSON",
"answ2":"Lea Thompson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What year saw the release of Back to the Future Part 2?",
"answ":"1989",
"answ2":"1989.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Biff in Back to the Future?",
"answ":"THOMAS F WILSON",
"answ3":"THOMAS WILSON",
"answ2":"Thomas F. Wilson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What name did Marty use as an alias in Back to the Future 3?",
"answ":"CLINT EASTWOOD",
"answ2":"Clint Eastwood.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the Back to the Future films, what is the name of the device that converts trash into fuel for the Delorean?",
"answ":"MR FUSION",
"answ3":"MISTER FUSION",
"answ2":"Mr. Fusion.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is Mary McFly's mother's first name in the Back to the Future series?",
"answ":"LORRAINE",
"answ3":"LORAINE",
"answ2":"Lorraine.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, when Biff has an accident in George's car early in the film, he spills what type of beverage on his jacket?",
"answ":"BEER",
"answ2":"Beer.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future 2, according to Doc Brown, what had been abolished in 2015?",
"answ":"LAWYERS",
"answ2":"Lawyers.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what is the name of Biff's grandson in 2015?",
"answ":"GRIFF",
"answ3":"GRIFF TANNEN",
"answ2":"Griff.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was the name of the school dance where Marty's parents fell for each other?",
"answ":"THE ENCHANTMENT UNDER THE SEA",
"answ3":"ENCHANTMENT UNDER THE SEA",
"answ2":"The Enchantment Under The Sea.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, Doc Brown came up with the idea for the flux capacitor after falling off of what?",
"answ":"TOILET",
"answ2":"Toilet.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What does Marty hate getting called in the Back to the Future series?",
"answ":"CHICKEN",
"answ2":"Chicken.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who directed the Back to the Future trilogy?",
"answ":"ROBERT ZEMECKIS",
"answ2":"Robert Zemeckis.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the first Back to the Future film, George McFly calls Lorraine his 'what' when he means to say destiny?",
"answ":"DENSITY",
"answ2":"Density.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What month of 1955 does Marty McFly travel to in Back to the Future 1?",
"answ":"NOVEMBER",
"answ2":"November.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays Marty's girlfriend (and future wife) Jennifer in Back to the Future Part II?",
"answ":"ELISABETH SHUE",
"answ3":"ELIZABETH SHUE",
"answ2":"Elisabeth Shue.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was the name of the man who took Marty in shortly after he arrived in the old west in Back to the Future 3?",
"answ":"SEAMUS MCFLY",
"answ3":"SEAMUS",
"answ2":"Seamus McFly.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the mall at the end of Back to the Future where Marty meets Doc Brown?",
"answ":"LONE PINE MALL",
"answ3":"LONE PINE",
"answ2":"Lone Pine Mall",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future 3, where does Doc take Marty to make the jump from 1955 to 1885?",
"answ":"DRIVE IN",
"answ3":"POHATCHEE DRIVE IN",
"answ2":"Pohatchee Drive-In.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Christian Bale plays John Connor in which Terminator film?",
"answ":"TERMINATOR SALVATION",
"answ3":"SALVATION",
"answ2":"Terminator Salvation.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Terminator Salvation, who played Marcus Wright, a human-terminator hybrid experiment?",
"answ":"SAM WORTHINGTON",
"answ2":"Sam Worthington.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Sarah Connor in Terminator Genisys?",
"answ":"EMILIA CLARKE",
"answ3":"EMILIA CLARK",
"answ2":"Emilia Clarke.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Terminator 2, which human is most directly responsible for the creation of Skynet?",
"answ":"MILES DYSON",
"answ2":"Miles Dyson.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What year saw the release of Terminator 3: Rise of the Machines?",
"answ":"2003",
"answ2":"2003.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the computer defense system that creates a nuclear holocaust to exterminate humanity in The Terminator franchise?",
"answ":"SKYNET",
"answ2":"Skynet.",
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the subtitle of the third film in The Terminator franchise?",
"answ":"RISE OF THE MACHINES",
"answ2":"Rise of the Machines.",
},
];
var r2Q19 = [
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the idyllic place that Furiosa is taking Immortan Joe's wives in Mad Max Fury Road?",
"answ":"THE GREEN PLACE",
"answ3":"GREEN PLACE",
"answ2":"The Green Place.",
"option":["The Green Place", "The Safe Zone", "The Oasis", "The Heavenly Mountains"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played the sick war boy named Nux in Mad Max Fury Road?",
"answ":"NICHOLAS HOULT",
"answ3":"NICHOLAS HOLT",
"answ2":"Nicholas Hoult.",
"option":["Nicholas Hoult", "Tom Hardy", "Michael Cera", "Paul Dano"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which actress plays Maggie McFly in Back to the Future 3?",
"answ":"LEA THOMPSON",
"answ2":"Lea Thompson.",
"option":["Lea Thompson", "Claudia Wells", "Darlene Vogel", "Elizabeth Shue"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In which Terminator film does Sarah Connor say: 'I'm wanted in a couple states. 50 actually.'?",
"answ":"TERMINATOR DARK FATE",
"answ2":"Terminator Dark Fate.",
"option":["Terminator Dark Fate", "Terminator Salvation", "Terminator 2: Judgment Day", "Terminator Genisys"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Mad Max: Fury Road, the convoy Furiosa is leading is supposed to go where, before she takes them off course?",
"answ":"GAS TOWN",
"answ2":"Gas Town.",
"option":["Gas Town", "Citadel", "Aqua Cola", "Bullet Farm"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays the character Persephone in The Matrix Reloaded?",
"answ":"MONICA BELLUCI",
"answ2":"Monica Belluci.",
"option":["Monica Belluci", "Jada Pinkett Smith", "Essie Davis", "Nona Gaye"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Mad Max: Fury Road, what is the name of Immortan Joe's followers who are chasing Furiosa and Max and that Nux was once a part of?",
"answ":"WARBOYS",
"answ3":"WAR BOYS",
"answ2":"War Boys.",
"option":["War Boys", "The Army", "The Wretched", "Repair Boys"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, Marty McFly travels back to what year?",
"answ":"1955",
"answ2":"1955.",
"option":["1955", "1952", "1950", "1956"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Back to the Future 2 takes us forward to 2015. What is the next year Marty visits in the film?",
"answ":"1985",
"answ2":"1985.",
"option":["1985", "1965", "1955", "1995"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In what year was The Terminator released?",
"answ":"1984",
"answ2":"1984.",
"option":["1984", "1982", "1980", "1986"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played John Connor in Terminator 2 Judgment Day?",
"answ":"EDWARD FURLONG",
"answ2":"Edward Furlong.",
"option":["Edward Furlong", "Haley Joel Osmont", "Jonathan Taylor Thomas", "Macaulay Culkin"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Finish the quote from Terminator 2: 'I need your clothes, your boots, and your ____'",
"answ":"MOTORCYCLE",
"answ2":"Motorcycle.",
"option":["Motorcycle", "Gun", "Car", "Wallet"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Terminator, what kind of pet did Sarah Connor have?",
"answ":"LIZARD",
"answ3":"IGUANA",
"answ2":"Iguana/Lizard.",
"option":["Iguana", "Parrot", "Dog", "Tortoise"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who was the composer for 1984's The Terminator?",
"answ":"BRAD FIEDEL",
"answ2":"Brad Fiedel.",
"option":["Brad Fiedel", "John Williams", "Alan Silvestri", "Jack Nitzsche"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Terminator, what is the name of Sarah's roommate?",
"answ":"GINGER",
"answ2":"Ginger.",
"option":["Ginger", "Gina", "Jennifer", "Jessica"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who directed 2009's Terminator Salvation?",
"answ":"MCG",
"answ2":"McG.",
"option":["McG", "Jonathan Mostow", "Alan Taylor", "Tim Miller"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Terminator, from what year did the Terminator travel back in time to kill Sarah Connor?",
"answ":"2029",
"answ2":"2029.",
"option":["2029", "2025", "2035", "2039"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Kyle Reese in 1984's The Terminator?",
"answ":"MICHAEL BIEHN",
"answ2":"Michael Biehn.",
"option":["Michael Biehn", "Lance Henriksen", "Bill Paxton", "Dennis Quaid"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the film The Terminator, what is the make and model of the cybernetic assassin sent to kill Sarah Connor?",
"answ":"T 800",
"answ3":"T800",
"answ2":"T-800.",
"option":["T-800", "T-700", "T-1000", "T-100"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who plays the villainous T-1000 in Terminator 2?",
"answ":"ROBERT PATRICK",
"answ2":"Robert Patrick.",
"option":["Robert Patrick", "Joe Morton", "Edward Furlong", "Earl Boen"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was the make and model number of the liquid metal Terminator sent to kill John Connor in T2: Judgement Day?",
"answ":"T 1000",
"answ3":"T1000",
"answ2":"T-1000.",
"option":["T-1000", "T-2000", "T-800", "T-9000"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Arnold Schwarzenegger and which other performer reprised their roles from the original Terminator in Terminator: Dark Fate?",
"answ":"LINDA HAMILTON",
"answ2":"Linda Hamilton.",
"option":["Linda Hamilton", "Lance Henriksen", "Michael Biehn", "Paul Winfield"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"How many gigawatts of electricity did Doc Brown need to power the DeLorean in Back to the Future?",
"answ":"121",
"answ3":"121 GIGAWATTS",
"answ2":"1.21 gigawatts.",
"option":["1.21", "2.33", "1.29", "3.26"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, when Marty joins his mother and her family for dinner, what classic TV show were they watching?",
"answ":"THE HONEYMOONERS",
"answ3":"HONEYMOONERS",
"answ2":"The Honeymooners.",
"option":["The Honeymooners", "I Love Lucy", "Mister Peepers", "My Little Margie"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What musician plays Needles in Back to the Future part II and III?",
"answ":"FLEA",
"answ2":"Flea.",
"option":["Flea", "Ringo Starr", "Slash", "Meat Loaf"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was the name of Marvin Berry's band that performed at the Enchantment Under the Sea dance in Back to the Future?",
"answ":"THE STARLIGHTERS",
"answ3":"STARLIGHTERS",
"answ2":"The Starlighters.",
"option":["The Starlighters", "The Penguins", "Lonely Heart", "Cavaliers"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of Marty's band in Back to the Future?",
"answ":"THE PINHEADS",
"answ3":"PINHEADS",
"answ2":"The Pinheads.",
"option":["The Pinheads", "The Rocking Oranges", "The Dudes", "The Rutles"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the future timeline in Back to the Future 2, what baseball team wins the World Series?",
"answ":"CHICAGO CUBS",
"answ3":"THE CHICAGO CUBS",
"answ2":"Chicago Cubs.",
"option":["Chicago Cubs", "Washington Nationals", "Minnesota Twins", "Los Angeles Dodgers"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what was the first thing that Marty tried to order to drink at the diner in 1955?",
"answ":"TAB",
"answ2":"Tab.",
"option":["Tab", "Pepsi Free", "Diet Coke", "Dr Pepper"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Doc Brown's love interest in Back to the Future Part III?",
"answ":"MARY STEENBURGEN",
"answ2":"Mary Steenburgen.",
"option":["Mary Steenburgen", "Lea Thompson", "Elisabeth Shue", "Demi Moore"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who composed the score for Back to the Future?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Danny Elfman", "John Williams", "James Horner"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who performed the song 'Back in Time' from Back to the Future?",
"answ":"HUEY LEWIS",
"answ3":"HUEY LEWIS AND THE NEWS",
"answ2":"Huey Lewis and the News.",
"option":["Huey Lewis and the News", "Eric Clapton", "Etta James", "Marvin Berry & The Starlighters"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In the Back to the Future films, who do we learn is Doc Brown's favorite author?",
"answ":"JULES VERNE",
"answ2":"Jules Verne.",
"option":["Jules Verne", "Arthur Conan Doyle", "H.G. Wells", "Robert Louis Stevenson"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what is in the truck that Biff and his friends crashed into during the skateboard chase?",
"answ":"MANURE",
"answ2":"Manure.",
"option":["Manure", "Milk", "Hay", "Corn"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What was Buford Tannen's nickname in Back to The Future 3?",
"answ":"MAD DOG",
"answ2":"Mad Dog.",
"option":["Mad Dog", "Crazy", "The Terrifying", "Butcher"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what item does Doc pack because he's not sure if it exists in the future?",
"answ":"COTTON UNDERWEAR",
"answ2":"Cotton underwear.",
"option":["Cotton underwear", "Paper", "Walkman", "Pepsi"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What color is the pill that Neo needs to take to get to the Matrix?",
"answ":"RED",
"answ2":"Red.",
"option":["Red", "Blue", "Green", "Yellow"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played Cypher in The Matrix?",
"answ":"JOE PANTOLIANO",
"answ2":"Joe Pantoliano.",
"option":["Joe Pantoliano", "Joe Manganiello", "John Leguizamo", "Marcus Chong"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who played the beautiful Persephone in The Matrix Reloaded and The Matrix Revolutions?",
"answ":"MONICA BELLUCI",
"answ2":"Monica Belluci.",
"option":["Monica Belluci", "Salma Hayek", "Halle Berry", "Jennifer Lopez"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the name of the last human city on Earth in The Matrix trilogy?",
"answ":"ZION",
"answ2":"Zion.",
"option":["Zion", "Dulopolis", "Palomar", "Kaldor"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"When Neo experiences déjà vu in The Matrix, what animal does he see twice?",
"answ":"CAT",
"answ3":"A CAT",
"answ2":"Cat.",
"option":["Cat", "Mouse", "Horse", "Dog"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Waterworld, what is the name of the pirate gang led by Dennis Hopper's character?",
"answ":"SMOKERS",
"answ3":"THE SMOKERS",
"answ2":"Smokers.",
"option":["Smokers", "Ravagers", "War Boys", "Marauders"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who directed Waterworld?",
"answ":"KEVIN REYNOLDS",
"answ2":"Kevin Reynolds.",
"option":["Kevin Reynolds", "Lawrence Kasdan", "Sam Raimi", "Ron Shelton"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Waterworld, what is Kevin Costner's character offered by the trader in exchange for sex with Helen?",
"answ":"PAPER",
"answ2":"Paper.",
"option":["Paper", "Food", "Clothes", "Seeds"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"George Miller's dystopian action classic Mad Max was released in what year?",
"answ":"1979",
"answ2":"1979.",
"option":["1979", "1978", "1976", "1981"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Who performed the tune 'We Don't Need Another Hero' in Mad Max Beyond Thunderdome?",
"answ":"TINA TURNER",
"answ2":"Tina Turner.",
"option":["Tina Turner", "Madonna", "Whitney Houston", "Alice Cooper"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is Doc Brown's first name in Back to the Future?",
"answ":"EMMETT",
"answ3":"EMMET",
"answ2":"Emmett.",
"option":["Emmett", "Eliott", "Adam", "John"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is the last name of the principal at Marty's school in Back to the Future?",
"answ":"STRICKLAND",
"answ3":"MR STRICKLAND",
"answ2":"Strickland.",
"option":["Strickland", "Howard", "Pelton", "Goodman"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future 3, what was the amount of money dispute between Doc and Buford that led to Doc being shot in the back?",
"answ":"80",
"answ3":"80 DOLLARS",
"answ2":"$80.",
"option":["$80", "$70", "$100", "$50"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"At what speed will the Delorean time travel in Back to the Future?",
"answ":"88 MPH",
"answ3":"88 MILES PER HOUR",
"answ2":"88 mph.",
"option":["88 mph", "80 mph", "120 mph", "90 mph"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Marty and Doc travel to what year in the future, featuring flying cars and no lawyers, in Back to the Future Part 2?",
"answ":"2015",
"answ2":"2015.",
"option":["2015", "2012", "2005", "2020"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What brand of underwear was Marty wearing in Back to the Future?",
"answ":"CALVIN KLEIN",
"answ2":"Calvin Klein.",
"option":["Calvin Klein", "Hugo Boss", "Armani", "Diesel"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Marty McFly and Doc Brown head to the wild west in Back to the Future Part III released in what year?",
"answ":"1990",
"answ2":"1990.",
"option":["1990", "1986", "1989", "1992"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future 3, what did the huge machine that Doc Brown built in his workshop successfully produce?",
"answ":"ICE CUBES",
"answ3":"ICE",
"answ2":"Ice cubes.",
"option":["Ice cubes", "Bread", "Muffins", "Gold"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, what title does Tilda Swinton's character have?",
"answ":"MINISTER",
"answ2":"Minister.",
"option":["Minister", "General", "Queen", "Major"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, what are the protein blocks revealed to be made out of?",
"answ":"BUGS",
"answ3":"INSECTS",
"answ2":"Bugs.",
"option":["Bugs", "Eggs", "Human remains", "Corn"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Snowpiercer, what animal do Yona and Timmy see outside of the train at the end of the movie?",
"answ":"POLAR BEAR",
"answ2":"Polar Bear.",
"option":["Polar Bear", "Giraffe", "Lion", "Eagle"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which Oscar winning actress plays the character Tanya in Snowpiercer?",
"answ":"OCTAVIA SPENCER",
"answ2":"Octavia Spencer.",
"option":["Octavia Spencer", "Meryl Streep", "Cate Blanchett", "Frances McDormand"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Waterworld, which actress plays the role of Helen, who is Enola's guardian?",
"answ":"JEANNE TRIPPLEHORN",
"answ2":"Jeanne Tripplehorn.",
"option":["Jeanne Tripplehorn", "Sarah Michelle Gellar", "Ashley Judd", "Sela Ward"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which Mad Max film takes place in a metropolis sector called Sun City?",
"answ":"MAD MAX",
"answ3":"MAD MAX 1979",
"answ2":"Mad Max.",
"option":["Mad Max", "Mad Max: Fury Road", "Mad Max Beyond Thunderdome", "Mad Max 2"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Which actress plays The Oracle in The Matrix Reloaded?",
"answ":"GLORIA FOSTER",
"answ2":"Gloria Foster.",
"option":["Gloria Foster", "Jada Pinkett Smith", "Monica Belluci", "Gina Torres"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future 2, the Chicago Cubs win the World Series in the future timeline that Marty and Doc visit. From what city was the team that they beat from?",
"answ":"MIAMI",
"answ2":"Miami.",
"option":["Miami", "Boston", "New York", "Detroit"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Terminator: Salvation, in what year does the film open?",
"answ":"2003",
"answ2":"2003.",
"option":["2003", "2005", "2004", "2007"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"What is Lorraine McFly's maiden name?",
"answ":"BAINES",
"answ2":"Baines.",
"option":["Baines", "Martin", "Hayes", "Johnson"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, in the alternate 1985 timeline, it is revealed that George had died in what year?",
"answ":"1973",
"answ2":"1973.",
"option":["1973", "1975", "1980", "1970"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what Clint Eastwood western is Biff watching on TV while in his hot tub?",
"answ":"A FISTFUL OF DOLLARS",
"answ2":"A Fistful of Dollars.",
"option":["A Fistful of Dollars", "The Good, the Bad and the Ugly", "Hang 'Em High", "High Plains Drifter"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Back to the Future I won an Oscar in what category?",
"answ":"BEST SOUND EFFECTS EDITING",
"answ3":"SOUND EFFECTS EDITING",
"answ2":"Best Sound Effects Editing.",
"option":["Best Sound Effects Editing", "Best Visuel Effects", "Best Editing", "Best Original Screenplay"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what brand of canine food is Einstein supposed to be eating in the beginning of the film?",
"answ":"KAL KAN",
"answ2":"Kal Kan.",
"option":["Kal Kan", "Purina", "Royal Canin", "Pedigree"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, Marty makes what comment after being assaulted by the 'Jaws 19' ad?",
"answ":"SHARK STILL LOOKS FAKE",
"answ2":"Shark still looks fake.",
"option":["Shark still looks fake", "Didn't scare me", "Graphics have improved", "What was that?"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what 2015 TV cable channel broadcasts 'beautiful views, 24 hours a day'?",
"answ":"THE SCENERY CHANNEL",
"answ2":"The Scenery Channel.",
"option":["The Scenery Channel", "The Life Channel", "The Quiet Channel", "The Nature Channel"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, what is the last name of Marty's boss who fires him?",
"answ":"FUJITSU",
"answ2":"Fujitsu.",
"option":["Fujitsu", "Mirakaya", "Hiroshi", "Fukuyama"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what is the name of the café that the teens frequent in 1955?",
"answ":"LOU'S CAFE",
"answ2":"Lou's Café.",
"option":["Lou's Café", "Mike's Café", "Dave's Café", "George's Café"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In BTTF Part II, Doc gets rejuvenated in the future. They took out some wrinkles, did hair repair, changed the blood, and added a good 30 to 40 years to his life. They also replaced his what?",
"answ":"COLON AND SPLEEN",
"answ3":"SPLEEN AND COLON",
"answ2":"Spleen and colon.",
"option":["Spleen and colon", "Stomach and kidneys", "Colon and bladder", "Spleen and liver"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future Part II, with his mass fortune, what company does Biff start that makes him even richer?",
"answ":"BIFFCO",
"answ2":"BiffCo.",
"option":["BiffCo", "Biff Industries", "Biff & Sons", "Biff Inc."],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, what is the name of the newspaper that documents the life of Doc Brown and the Clock Tower incident among other things in Hill Valley?",
"answ":"HILL VALLEY TELEGRAPH",
"answ3":"THE HILL VALLEY TELEGRAPH",
"answ2":"The Hill Valley Telegraph.",
"option":["The Hill Valley Telegraph", "The Hill Valley Mail", "The Hill Valley Post", "The Hill Valley Daily"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Matrix Reloaded, Neo and his friends find out that they have how many days until the machines attack Zion?",
"answ":"3",
"answ3":"3 DAYS",
"answ2":"3 days.",
"option":["3 days", "5 days", "4 days", "2 days"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, how old did Marty say he was when he accidentally set the living room rug on fire?",
"answ":"8",
"answ3":"8 YEARS OLD",
"answ2":"8.",
"option":["8", "10", "6", "12"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In Back to the Future, Doc Brown tells Marty to meet him at Twin Pines Mall at what precise time?",
"answ":"1:15 AM",
"answ3":"115 AM",
"answ2":"1:15 AM.",
"option":["1:15 AM", "2:30 AM", "4:10 AM", "5:00 AM"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"Actor Bruce Spence appears as a pilot in how many films in the Mad Max franchise?",
"answ":"2",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Matrix, the film begins with police attempting to capture Trinity. How many units were sent in to get her?",
"answ":"2 UNITS",
"answ3":"2",
"answ2":"2 units.",
"option":["2 units", "3 units", "4 units", "5 units"],
},
{
"cat":"Dystopian Future/Time Travel",
"ques":"In The Matrix Reloaded, according to Agent Smith, what binds us, connects us, and defines us?",
"answ":"PURPOSE",
"answ2":"Purpose.",
"option":["Purpose", "Fear", "Vanity", "Power"],
},
];
dystopiantime = shuffle(dystopiantime);
r2Q19 = shuffle(r2Q19);