var batman = [
{
"cat":"Batman",
"ques":"You'll find Ed Begley Jr. and Drew Barrymore in which Batman film?",
"answ":"BATMAN FOREVER",
"answ2":"Batman Forever.",
},
{
"cat":"Batman",
"ques":"In Batman Forever, what is the name of the device that Riddler invents to steal information from users minds?",
"answ":"THE BOX",
"answ3":"BOX",
"answ2":"The Box.",
},
{
"cat":"Batman",
"ques":"In The Dark Knight, what was the name of the Gotham City Police Commissioner that Gordon took over for after he was poisoned by Joker?",
"answ":"LOEB",
"answ2":"Loeb.",
},
{
"cat":"Batman",
"ques":"Michael Murphy plays the character credited as The Mayor in what Batman film?",
"answ":"BATMAN RETURNS",
"answ2":"Batman Returns.",
},
{
"cat":"Batman",
"ques":"Which actor has played Alfred Pennyworth the most, with 4 theatrical appearances?",
"answ":"MICHAEL GOUGH",
"answ2":"Michael Gough.",
},
{
"cat":"Batman",
"ques":"Tracy Walter plays a goon named Bob in which Batman film?",
"answ":"BATMAN 1989",
"answ3":"BATMAN",
"answ2":"Batman (1989).",
},
{
"cat":"Batman",
"ques":"In Batman: Mask of the Phantasm, Bruce Wayne is practicing what form of martial art that Andrea is a professional in as well?",
"answ":"JIU JITSU",
"answ3":"JIUJITSU",
"answ2":"Jiu-jitsu.",
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, Marion Cotillard plays Miranda Tate, who is revealed to actually be whom?",
"answ":"TALIA AL GHUL",
"answ2":"Talia al Ghul.",
},
{
"cat":"Batman",
"ques":"Who plays Commissioner Gordon in Batman Forever?",
"answ":"PAT HEALY",
"answ2":"Pat Healy.",
},
{
"cat":"Batman",
"ques":"You'll find the character of Mayor Borg in which Batman film?",
"answ":"BATMAN",
"answ3":"BATMAN 1989",
"answ2":"Batman (1989).",
},
{
"cat":"Batman",
"ques":"In Batman Returns, what is the name of Selina Kyle's black cat?",
"answ":"MISS KITTY",
"answ2":"Miss Kitty.",
},
{
"cat":"Batman",
"ques":"In which film does Batman say: 'It's not who I am underneath...but what I do that defines me'?",
"answ":"BATMAN BEGINS",
"answ2":"Batman Begins.",
},
{
"cat":"Batman",
"ques":"Actor Lee Wallace plays the mayor of Gotham city in which Batman film?",
"answ":"BATMAN 1989",
"answ3":"BATMAN",
"answ2":"Batman (1989).",
},
{
"cat":"Batman",
"ques":"Who played Batgirl in the ill fated and critically panned Batman & Robin?",
"answ":"ALICIA SILVERSTONE",
"answ2":"Alicia Silverstone.",
},
{
"cat":"Batman",
"ques":"In Batman Forever, Edward Nygma is a researcher working at what company, when first introduced in the film?",
"answ":"WAYNE ENTERPRISES",
"answ2":"Wayne Enterprises.",
},
{
"cat":"Batman",
"ques":"Which Batman film features the line: 'Why is there always someone who brings eggs and tomatoes to a speech'?",
"answ":"BATMAN RETURNS",
"answ2":"Batman Returns.",
},
{
"cat":"Batman",
"ques":"In what Batman film will you hear Alfred say: 'Broken wings mend in time. One day Robin will fly again. I promise.'?",
"answ":"BATMAN FOREVER",
"answ2":"Batman Forever.",
},
{
"cat":"Batman",
"ques":"In Batman & Robin, what is the name of Alfred's sister?",
"answ":"MARGARET",
"answ2":"Margaret.",
},
{
"cat":"Batman",
"ques":"In Batman Forever, the villains play a version of what board game in an attempt to stop Robin from getting to the island?",
"answ":"BATTLESHIP",
"answ2":"Battleship.",
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, what is the name of Bruce Wayne's corporate rival, for who Catwoman steals Wayne's fingerprints?",
"answ":"JOHN DAGGETT",
"answ3":"DAGGETT",
"answ2":"John Daggett.",
},
{
"cat":"Batman",
"ques":"In Batman Begins, who rescues Bruce from his burning mansion?",
"answ":"ALFRED",
"answ3":"ALFRED PENNYWORTH",
"answ2":"Alfred Pennyworth.",
},
{
"cat":"Batman",
"ques":"At the end of The Dark Knight Rises, there is a ceremony revealing a statue of whom?",
"answ":"BATMAN",
"answ2":"Batman.",
},
{
"cat":"Batman",
"ques":"Who played mob boss Carl Grissom in 1989's Batman?",
"answ":"JACK PALANCE",
"answ2":"Jack Palance.",
},
{
"cat":"Batman",
"ques":"What public office does Harvey Dent hold in The Dark Knight?",
"answ":"DISTRICT ATTORNEY",
"answ3":"DA",
"answ2":"District Attorney.",
},
{
"cat":"Batman",
"ques":"What villain wrote words in the sky with missiles in 1966's Batman?",
"answ":"THE RIDDLER",
"answ3":"RIDDLER",
"answ2":"The Riddler.",
},
{
"cat":"Batman",
"ques":"How many years after The Dark Knight does The Dark Knight Rises take place?",
"answ":"8",
"answ3":"EIGHT",
"answ2":"8.",
},
{
"cat":"Batman",
"ques":"Who played character Mr. Freeze in Batman & Robin?",
"answ":"ARNOLD SCHWARZENEGGER",
"answ2":"Arnold Schwarzenegger.",
},
{
"cat":"Batman",
"ques":"What public office does Oswald Cobblepot run for in Batman Returns?",
"answ":"MAYOR",
"answ3":"MAYOR OF GOTHAM",
"answ2":"Mayor.",
},
{
"cat":"Batman",
"ques":"What villain was Scarecrow working for in Batman Begins?",
"answ":"RA'S AL GHUL",
"answ2":"Ra's al Ghul.",
},
{
"cat":"Batman",
"ques":"What is the collective name for the circus acrobats that Bruce and Chase go to see in Batman Forever?",
"answ":"FLYING GRAYSONS",
"answ3":"THE FLYING GRAYSONS",
"answ2":"The Flying Graysons.",
},
{
"cat":"Batman",
"ques":"In Batman Begins, who said: 'You're not the devil. You're practice.'?",
"answ":"BRUCE WAYNE",
"answ3":"BATMAN",
"answ2":"Bruce Wayne.",
},
{
"cat":"Batman",
"ques":"In Batman Begins, who operates the Batmobile on the ground while Bruce is fighting Ra's al Ghul on the train?",
"answ":"JIM GORDON",
"answ3":"COMMISSIONER GORDON",
"answ2":"Jim Gordon.",
},
{
"cat":"Batman",
"ques":"In Batman Forever, Alfred and Dick get the name of Robin from what item of Dick's?",
"answ":"MOTORCYCLE",
"answ3":"HIS MOTORCYCLE",
"answ2":"Motorcycle.",
},
{
"cat":"Batman",
"ques":"What is the name Lucius gives to the large aircraft operated by Batman in The Dark Knight Rises?",
"answ":"THE BAT",
"answ3":"BAT",
"answ2":"The Bat.",
},
{
"cat":"Batman",
"ques":"Who saves the circus-goers by throwing Two-Face's bomb into the river in Batman Forever?",
"answ":"DICK GRAYSON",
"answ3":"ROBIN",
"answ2":"Dick Grayson/Robin.",
},
{
"cat":"Batman",
"ques":"Who do the villains plan to kidnap to lure Batman and Robin into their trap in Batman 1966?",
"answ":"BRUCE WAYNE",
"answ2":"Bruce Wayne.",
},
{
"cat":"Batman",
"ques":"In The Dark Knight, who operated the giant sonar machine to assist Batman in stopping SWAT teams from killing hostages?",
"answ":"LUCIUS FOX",
"answ3":"LUCIUS",
"answ2":"Lucius Fox.",
},
{
"cat":"Batman",
"ques":"What is the first film featuring the character of Batman to win an Oscar?",
"answ":"BATMAN",
"answ3":"BATMAN (1989)",
"answ2":"Batman (1989)",
},
{
"cat":"Batman",
"ques":"Finish the quote from The Dark Knight: ''Madness, as you know, is like gravity, all it takes is ____'",
"answ":"A LITTLE PUSH",
"answ2":"A little push.",
},
{
"cat":"Batman",
"ques":"What is the name Lucius gives to the large aircraft operated by Batman in The Dark Knight Rises?",
"answ":"THE BAT",
"answ3":"BAT",
"answ2":"The Bat.",
},
{
"cat":"Batman",
"ques":"Who directed the 1995 film Batman Forever?",
"answ":"JOEL SCHUMACHER",
"answ2":"Joel Schumacher.",
},
{
"cat":"Batman",
"ques":"In how many of Nolan's Batman films does Jonathan Crane/Scarecrow appear?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Batman",
"ques":"In Tim Burton's Batman, what is the name of Jack Nicholson's character before he becomes the Joker?",
"answ":"JACK NAPIER",
"answ3":"JACK",
"answ2":"Jack Napier.",
},
{
"cat":"Batman",
"ques":"What is the name of the mysterious group that Ra's al Ghul is the leader of in Batman Begins?",
"answ":"LEAGUE OF SHADOWS",
"answ3":"THE LEAGUE OF SHADOWS",
"answ2":"League of Shadows.",
},
{
"cat":"Batman",
"ques":"Who plays Dr. Chase Meridian in Batman Forever?",
"answ":"NICOLE KIDMAN",
"answ2":"Nicole Kidman.",
},
{
"cat":"Batman",
"ques":"Who played Lucius Fox in the Christopher Nolan Batman films?",
"answ":"MORGAN FREEMAN",
"answ2":"Morgan Freeman.",
},
{
"cat":"Batman",
"ques":"Who plays Alfred Pennyworth in the Christopher Nolan Batman films?",
"answ":"MICHAEL CAINE",
"answ3":"MICHAEL KANE",
"answ2":"Michael Caine.",
},
{
"cat":"Batman",
"ques":"What DC film introduced us to the infamous Bat credit-card?",
"answ":"BATMAN AND ROBIN",
"answ2":"Batman & Robin.",
},
{
"cat":"Batman",
"ques":"In Batman and Robin, what does Mr. Freeze modify into a freeze ray to cover all of Gotham in ice?",
"answ":"TELESCOPE",
"answ2":"Telescope.",
},
{
"cat":"Batman",
"ques":"In the Lego Batman Movie, where do Batman and Robin steal the Phantom Zone Projector from?",
"answ":"THE FORTRESS OF SOLITUDE",
"answ3":"FORTRESS OF SOLITUDE",
"answ2":"The Fortress of Solitude.",
},
{
"cat":"Batman",
"ques":"In Batman Forever, what modified board game do The Riddler and Two-Face play that attacks Batman & Robin as they attempt to infiltrate their lair?",
"answ":"BATTLESHIP",
"answ2":"Battleship.",
},
{
"cat":"Batman",
"ques":"Who played Harvey Dent in The Dark Knight?",
"answ":"AARON ECKHART",
"answ2":"Aaron Eckhart.",
},
{
"cat":"Batman",
"ques":"Who wrote the screenplay for Batman Begins with Christopher Nolan?",
"answ":"DAVID GOYER",
"answ3":"DAVID S GOYER",
"answ2":"David S. Goyer.",
},
{
"cat":"Batman",
"ques":"In Batman Returns, who plays the Penguin's father?",
"answ":"PAUL REUBENS",
"answ3":"PAUL RUBENS",
"answ2":"Paul Reubens.",
},
{
"cat":"Batman",
"ques":"In Batman Returns, The Penguin's main mode of transportation is shaped like what animal?",
"answ":"DUCK",
"answ2":"Duck.",
},
{
"cat":"Batman",
"ques":"What was the name of the original villain created for the 1993 animated Batman film?",
"answ":"THE PHANTASM",
"answ3":"PHANTASM",
"answ2":"The Phantasm.",
},
{
"cat":"Batman",
"ques":"Who played Poison Ivy in Batman & Robin?",
"answ":"UMA THURMAN",
"answ2":"Uma Thurman.",
},
{
"cat":"Batman",
"ques":"In Batman Begins, what did the homeless man stop Bruce Wayne from throwing into the fire barrel?",
"answ":"HIS COAT",
"answ3":"COAT",
"answ2":"His coat.",
},
{
"cat":"Batman",
"ques":"In which Batman film are Penguin and Catwoman the villains?",
"answ":"BATMAN RETURNS",
"answ2":"Batman Returns.",
},
{
"cat":"Batman",
"ques":"What is the name of the Joker's henchman that turns on the boombox in the museum in 1989's Batman?",
"answ":"LAWRENCE",
"answ3":"LAURENCE",
"answ2":"Lawrence.",
},
{
"cat":"Batman",
"ques":"In Batman Begins, what is the name of the mysterious group that trains Bruce Wayne?",
"answ":"LEAGUE OF SHADOWS",
"answ3":"THE LEAGUE OF SHADOWS",
"answ2":"League of Shadows.",
},
{
"cat":"Batman",
"ques":"What is the name of Christopher Walken's character in Batman Returns?",
"answ":"MAX SHRECK",
"answ2":"Max Shreck.",
},
];
var r2Q21 = [
{
"cat":"Batman",
"ques":"Who played reporter Alexander Knox in 1989's Batman?",
"answ":"ROBERT WUHL",
"answ2":"Robert Wuhl.",
"option":["Robert Wuhl", "Jack Palance", "Michael Gough", "Pat Hingle"],
},
{
"cat":"Batman",
"ques":"What is the name of the corrupt accountant who launders money for the mob in The Dark Knight?",
"answ":"LAU",
"answ3":"MR LAU",
"answ2":"Lau.",
"option":["Lau", "Lee", "Wang", "Zhang"],
},
{
"cat":"Batman",
"ques":"To prove his worth to the League of Shadows what must Bruce Wayne bring to the mountain top in Batman Begins?",
"answ":"FLOWER",
"answ3":"A FLOWER",
"answ2":"a flower.",
"option":["Flower", "Amulet", "Ring", "Necklace"],
},
{
"cat":"Batman",
"ques":"Who directed 1966's Batman: The Movie?",
"answ":"LESLIE H MARTINSON",
"answ3":"LESLIE MARTINSON",
"answ2":"Leslie H. Martinson.",
"option":["Leslie H. Martinson", "Neil Hamilton", "Nelson Riddle", "Adam West"],
},
{
"cat":"Batman",
"ques":"In Batman Begins how many years was Bruce Wayne away from Gotham City?",
"answ":"7",
"answ3":"SEVEN",
"answ2":"7.",
"option":["7", "5", "6", "3"],
},
{
"cat":"Batman",
"ques":"In Batman Begins, according to Alfred, how many generations of Waynes have lived at Wayne Manor?",
"answ":"6",
"answ3":"SIX",
"answ2":"6.",
"option":["6", "7", "5", "8"],
},
{
"cat":"Batman",
"ques":"What Batman villain pops up in each of Christopher Nolan's Dark Knight trilogy?",
"answ":"SCARECROW",
"answ2":"Scarecrow.",
"option":["Scarecrow", "Victor Zsasz", "Two-Face", "Deadshot"],
},
{
"cat":"Batman",
"ques":"In The Dark Night, what does Lucius say is the name of the evacuation technique Batman uses to escape China?",
"answ":"SKY HOOK",
"answ3":"SKYHOOK",
"answ2":"Skyhook.",
"option":["Skyhook", "Batscape", "S.T.E.A.L.T.H", "Whirlwind"],
},
{
"cat":"Batman",
"ques":"Who plays Peter Foley, the deputy police commissioner who takes over for Gordon in The Dark Knight Rises?",
"answ":"MATTHEW MODINE",
"answ2":"Matthew Modine.",
"option":["Matthew Modine", "Burn Gorman", "Paul Reiser", "Brett Cullen"],
},
{
"cat":"Batman",
"ques":"What is Penguin's human name in Batman Returns?",
"answ":"OSWALD COBBLEPOT",
"answ3":"OSWALD",
"answ2":"Oswald Cobblepot.",
"option":["Oswald Cobblepot", "Crispus Allen", "Elijah Van Dahl", "Aubrey James"],
},
{
"cat":"Batman",
"ques":"Which actress portrayed Catwoman in 1966's Batman?",
"answ":"LEE MERIWETHER",
"answ3":"LEE MERIWEATHER",
"answ2":"Lee Meriwether.",
"option":["Lee Meriwether", "Eartha Kitt", "Julie Newmar", "Jill St. John"],
},
{
"cat":"Batman",
"ques":"In Batman Begins, what item did Bruce and Rachel fight over as kids?",
"answ":"ARROWHEAD",
"answ3":"AN ARROWHEAD",
"answ2":"An arrowhead.",
"option":["An arrowhead", "A knife", "A diamond", "A ring"],
},
{
"cat":"Batman",
"ques":"What is the name of Batman's motorcycle in The Dark Knight?",
"answ":"BATPOD",
"answ2":"Batpod.",
"option":["Batpod", "Batcycle", "Batwheel", "Batbike"],
},
{
"cat":"Batman",
"ques":"Who provided the voice of Batman in Batman: Mask of the Phantasm?",
"answ":"KEVIN CONROY",
"answ2":"Kevin Conroy.",
"option":["Kevin Conroy", "Bruce Greenwood", "Adam West", "Jason O'Mara"],
},
{
"cat":"Batman",
"ques":"Who played the mobster Gambol, that put the hit out on the Joker in The Dark Knight?",
"answ":"MICHAEL JAI WHITE",
"answ3":"MICHAEL JAY WHITE",
"answ2":"Michael Jai White.",
"option":["Michael Jai White", "Vinnie Jones", "John David Washington", "Ice-T"],
},
{
"cat":"Batman",
"ques":"In 1989's Batman, how many millions of dollars does the Joker say he'll dump on the streets of Gotham City?",
"answ":"20",
"answ3":"20 MILLION",
"answ2":"20 million.",
"option":["20 million", "1 million", "50 million", "100 million"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, what is the false name that Marion Cotillard's character goes by?",
"answ":"MIRANDA TATE",
"answ2":"Miranda Tate.",
"option":["Miranda Tate", "Pamela Isley", "Nora Fries", "Jane Doe"],
},
{
"cat":"Batman",
"ques":"In Batman & Robin, Poison Ivy crashes the Save the Rainforest Charity Ball by dressing as what animal?",
"answ":"GORILLA",
"answ2":"Gorilla.",
"option":["Gorilla", "Jaguar", "Flamingo", "Alligator"],
},
{
"cat":"Batman",
"ques":"What former pro-wrestler cameos as an Arkham Asylum guard in Batman & Robin?",
"answ":"JESSE VENTURA",
"answ2":"Jesse Ventura.",
"option":["Jesse Ventura", "Kevin Nash", "Diamond Dallas Paige", "Roddy Piper"],
},
{
"cat":"Batman",
"ques":"What actress played Senator June Finch in Batman v. Superman Dawn of Justice?",
"answ":"HOLLY HUNTER",
"answ2":"Holly Hunter.",
"option":["Holly Hunter", "Diane Lane", "Nancy Grace", "Carla Gugino"],
},
{
"cat":"Batman",
"ques":"In Batman and Robin, how was Alicia Silverstone's Barbara related to Alfred? She was his ____",
"answ":"NIECE",
"answ2":"Niece.",
"option":["Niece", "Daughter", "Sister", "Granddaughter"],
},
{
"cat":"Batman",
"ques":"William Hootkins aka Porkins from Star Wars plays this character in 1989's Batman.",
"answ":"LIEUTENANT ECKHARDT",
"answ3":"LIEUTENANT ECKHART",
"answ2":"Lieutenant Eckhardt.",
"option":["Lieutenant Eckhardt", "Harvey Bullock", "Carl Grissom", "Thomas Wayne"],
},
{
"cat":"Batman",
"ques":"What is the name of the Joker's right hand goon in 1989's Batman?",
"answ":"BOB",
"answ2":"Bob.",
"option":["Bob", "Brendan", "Carl", "Frank"],
},
{
"cat":"Batman",
"ques":"What U.S agency is attacked by Bane and his men at the opening of The Dark Knight Rises?",
"answ":"CIA",
"answ2":"CIA.",
"option":["CIA", "FBI", "NSA", "DEA"],
},
{
"cat":"Batman",
"ques":"What does Bruce offer to give Dick Grayson if he decides to stay at Wayne Manor in Batman Forever?",
"answ":"MOTORCYCLE",
"answ3":"A MOTORCYCLE",
"answ2":"Motorcycle.",
"option":["Motorcycle", "Boat", "Helicopter", "Car"],
},
{
"cat":"Batman",
"ques":"In Batman and Robin, before she became ill, Mr. Freeze gave his wife a necklace shaped like what?",
"answ":"SNOWFLAKE",
"answ2":"Snowflake.",
"option":["Snowflake", "Heart", "Star", "Angel"],
},
{
"cat":"Batman",
"ques":"In Batman Forever, Two-Face and The Riddler gain access to Wayne Manor by disguising themselves as what?",
"answ":"TRICK OR TREATERS",
"answ2":"Trick-or-treaters.",
"option":["Trick-or-treaters", "Gardeners", "Painters", "Lawyers"],
},
{
"cat":"Batman",
"ques":"What color was Penguin's top hat in 1966's Batman The Movie?",
"answ":"PURPLE",
"answ2":"Purple.",
"option":["Purple", "Blue", "Black", "White"],
},
{
"cat":"Batman",
"ques":"Which actor plays Edward Nygma's boss Fred Stickley, who is thrown out of a window to his death in Batman Forever?",
"answ":"ED BEGLEY JR",
"answ3":"ED BEGLEY JUNIOR",
"answ2":"Ed Begley Jr.",
"option":["Ed Begley Jr", "Rene Auberjonois", "John Glover", "Paul Gleason"],
},
{
"cat":"Batman",
"ques":"In Batman Forever, Bruce Wayne has two motorcycles, of the same kind, that impress Dick Grayson. By what name do they go by?",
"answ":"VINCENT BLACK KNIGHT",
"answ2":"Vincent Black Knight.",
"option":["Vincent Black Knight", "Triumph Bonneville", "Kawasaki Ninja", "Harley Davidson EL"],
},
{
"cat":"Batman",
"ques":"At the end of Batman Begins, Jim Gordon holds what rank in the GCPD?",
"answ":"LIEUTENANT",
"answ2":"Lieutenant.",
"option":["Lieutenant", "Captain", "Detective", "Commissioner"],
},
{
"cat":"Batman",
"ques":"What is Wayne Manor to be used for in accordance to Wayne's will in The Dark Knight Rises?",
"answ":"ORPHANAGE",
"answ2":"Orphanage.",
"option":["Orphanage", "Museum", "Homeless Shelter", "Hospital"],
},
{
"cat":"Batman",
"ques":"What is the name of the district of Gotham City where Batman aids the police in fighting the escaped Arkham Asylum convicts in Batman Begins?",
"answ":"THE NARROWS",
"answ3":"NARROWS",
"answ2":"The Narrows.",
"option":["The Narrows", "The Straights", "The Projects", "The Limits"],
},
{
"cat":"Batman",
"ques":"What theatre were Bruce's parents killed outside of in Batman 1989?",
"answ":"THE MONARCH THEATRE",
"answ3":"MONARCH THEATRE",
"answ2":"The Monarch Theatre.",
"option":["Monarch Theatre", "Royal Theatre", "Arkham Theatre", "Gotham Theatre"],
},
{
"cat":"Batman",
"ques":"What is the name of the mob boss who is killed by Joker by a lethal handshake in Batman 1989?",
"answ":"ANTOINE ROTELLI",
"answ3":"ROTELLI",
"answ2":"Antoine Rotelli.",
"option":["Antoine Rotelli", "Rafael Santini", "Pino Maroni", "Carmine Falcone"],
},
{
"cat":"Batman",
"ques":"In Batman 1989 what does Mob Boss Grissom remind Jack Napier to bring with him?",
"answ":"LUCKY DECK OF CARDS",
"answ3":"HIS LUCKY DECK OF CARDS",
"answ2":"His lucky deck of cards.",
"option":["His lucky deck of cards", "His smile", "His lucky hat", "His gun"],
},
{
"cat":"Batman",
"ques":"The Lego Batman Movie opens with a quote from what musician that Batman takes credit for?",
"answ":"MICHAEL JACKSON",
"answ2":"Michael Jackson.",
"option":["Michael Jackson", "David Bowie", "Elvis Presley", "Bob Dylan"],
},
{
"cat":"Batman",
"ques":"What is the name of the man who killed Bruce Wayne's parents in Batman Begins?",
"answ":"JOE CHILL",
"answ3":"JOE",
"answ2":"Joe Chill.",
"option":["Joe Chill", "Rupert Thorne", "Tony Zucco", "Lew Moxon"],
},
{
"cat":"Batman",
"ques":"What was the last name of the corrupt judge that was working for Carmine Falcone in Batman Begins?",
"answ":"FADEN",
"answ3":"PHADEN",
"answ2":"Faden.",
"option":["Faden", "Donovan", "Johnson", "Bowden"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, once Bane takes control of Gotham City, Commissioner Gordon has a sentencing trial. Which Dark Knight trilogy villain serves as judge of this trial?",
"answ":"SCARECROW",
"answ3":"JONATHAN CRANE",
"answ2":"Scarecrow.",
"option":["Scarecrow", "Ra's al Ghul", "Penguin", "Two-Face"],
},
{
"cat":"Batman",
"ques":"Vivica A. Fox appears as Ms. B. Haven in what Batman film?",
"answ":"BATMAN AND ROBIN",
"answ2":"Batman & Robin.",
"option":["Batman & Robin", "Batman", "Batman Returns", "Batman Forever"],
},
{
"cat":"Batman",
"ques":"Billy Dee Williams has portrayed Harvey Dent/Two Face how many times in both live action and animation?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":["2", "1", "3", "4"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight, the Joker says he prefers to use a knife on his victims because with guns 'you can't savor all the little' what?",
"answ":"EMOTIONS",
"answ2":"Emotions.",
"option":["Emotions", "Sensations", "Feelings", "Reactions"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight, what is the name of the paranoid schizophrenic that Harvey Dent confronts at gunpoint after the assassination attempt on Gotham's mayor?",
"answ":"THOMAS SCHIFF",
"answ2":"Thomas Schiff.",
"option":["Thomas Schiff", "Frank Boles", "Andrew Carter", "Willy Deever"],
},
{
"cat":"Batman",
"ques":"Who plays the character introduced as Miranda Tate in The Dark Knight Rises?",
"answ":"MARION COTILARD",
"answ3":"MARION COTILLARD",
"answ2":"Marion Cotillard.",
"option":["Marion Cotillard", "Anne Hathaway", "Juno Temple", "Mélanie Laurent"],
},
{
"cat":"Batman",
"ques":"What year saw the release of Batman Returns?",
"answ":"1992",
"answ2":"1992.",
"option":["1992", "1991", "1990", "1993"],
},
{
"cat":"Batman",
"ques":"Which year saw the release of Batman: Mask of the Phantasm?",
"answ":"1993",
"answ2":"1993.",
"option":["1993", "1995", "1997", "1990"],
},
{
"cat":"Batman",
"ques":"Batmvan V Superman: Dawn of Justice was released in what year?",
"answ":"2016",
"answ2":"2016.",
"option":["2016", "2015", "2017", "2018"],
},
{
"cat":"Batman",
"ques":"In Batman v. Superman, where was the tracker found in Jimmy Olsen's gear? In his ____",
"answ":"CAMERA",
"answ3":"CAMERA FILM",
"answ2":"Camera.",
"option":["Camera", "Helmet", "Gun", "Water bottle"],
},
{
"cat":"Batman",
"ques":"In Batman V Superman, what real-world talk show host did we see interviewing Holly Hunter's character about Superman?",
"answ":"CHARLIE ROSE",
"answ2":"Charlie Rose.",
"option":["Charlie Rose", "David Letterman", "Conan O'Brien", "Jimmy Kimmel"],
},
{
"cat":"Batman",
"ques":"In Batman V Superman, what do Bruce and Diana look at when they run into each other at the museum?",
"answ":"A SWORD",
"answ3":"SWORD",
"answ2":"A sword.",
"option":["A sword", "A tablet", "A necklace", "A helmet"],
},
{
"cat":"Batman",
"ques":"In Batman v. Superman, what is the name of the theory that Lex Luthor has for enhancing people on Earth?",
"answ":"THE METAHUMAN THEORY",
"answ3":"METAHUMAN THEORY",
"answ2":"The Metahuman Theory.",
"option":["The Metahuman Theory", "The Providence Theory", "The Inhuman Theory", "The Ultimates Theory"],
},
{
"cat":"Batman",
"ques":"In Batman v Superman, Jimmy Olsen is an undercover operative from what government organization?",
"answ":"CIA",
"answ2":"CIA.",
"option":["CIA", "FBI", "NSA", "MI6"],
},
{
"cat":"Batman",
"ques":"Who plays Martha Wayne in Batman v. Superman?",
"answ":"LAUREN COHEN",
"answ3":"LAUREN COHAN",
"answ2":"Lauren Cohan.",
"option":["Lauren Cohan", "Kate Bosworth", "Erica Durance", "Jennifer Morrison"],
},
{
"cat":"Batman",
"ques":"How many years has Bruce Wayne been operating as Batman according to Batman v. Superman?",
"answ":"20 YEARS",
"answ3":"20",
"answ2":"20 years.",
"option":["20 years", "15 years", "18 years", "22 years"],
},
{
"cat":"Batman",
"ques":"Who portrayed Wallace Keefe, the victim who lost his legs in the Metropolis incident in Batman V Superman?",
"answ":"SCOOT MCNAIRY",
"answ3":"SCOOT MACNAIRY",
"answ2":"Scoot McNairy.",
"option":["Scoot McNairy", "Ray Fisher", "Jeffrey Dean Morgan", "Callan Mulvey"],
},
{
"cat":"Batman",
"ques":"What is the name of the LexCorp cargo ship that Bruce is looking for in Batman v. Superman?",
"answ":"WHITE PORTUGUESE",
"answ3":"WHITE PORTUGESE",
"answ2":"White Portuguese.",
"option":["White Portuguese", "Apollo", "Black Legion", "Nightshade"],
},
{
"cat":"Batman",
"ques":"In Batman v. Superman, what weapon was Lex Luthor going to use to get Martha Kent killed?",
"answ":"FLAME THROWER",
"answ3":"FLAMETHROWER",
"answ2":"Flame Thrower.",
"option":["Flame Thrower", "Bomb", "Knife", "Shotgun"],
},
{
"cat":"Batman",
"ques":"Who plays Jimmy Olsen in Batman v. Superman?",
"answ":"MICHAEL CASSIDY",
"answ2":"Michael Cassidy.",
"option":["Michael Cassidy", "Scoot McNairy", "Mark Edward Taylor", "Callan Mulvey"],
},
{
"cat":"Batman",
"ques":"In 1989's Batman, what is the first name of Grissom's mistress, who is secretly sleeping with Jack?",
"answ":"ALICIA",
"answ2":"Alicia.",
"option":["Alicia", "Rachel", "Samantha", "Karen"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, after Jim is put in the hospital he promotes Blake to what position?",
"answ":"DETECTIVE",
"answ2":"Detective.",
"option":["Detective", "Lieutenant", "Captain", "Commissioner"],
},
{
"cat":"Batman",
"ques":"Which Batman villain said: 'A lot of tape and a little patience make all the difference.'?",
"answ":"THE PENGUIN",
"answ3":"PENGUIN",
"answ2":"The Penguin.",
"option":["The Penguin", "Scarecrow", "Joker", "The Riddler"],
},
{
"cat":"Batman",
"ques":"Pat Hingle plays what character in Batman 1989?",
"answ":"COMMISSIONER GORDON",
"answ3":"JAMES GORDON",
"answ2":"Commissioner Gordon.",
"option":["Commissioner Gordon", "Thomas Wayne", "Carl Grissom", "Harvey Dent"],
},
{
"cat":"Batman",
"ques":"Rutger Hauer, Cillian Murphy and Tom Wilkinson appear in what Batman film?",
"answ":"BATMAN BEGINS",
"answ2":"Batman Begins.",
"option":["Batman Begins", "Batman (1989)", "Batman Returns", "The Dark Knight"],
},
{
"cat":"Batman",
"ques":"In how many Batman films has Morgan Freeman appeared in?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "1", "4"],
},
{
"cat":"Batman",
"ques":"What mode does Batman's aircraft go into when Alfred takes control in Batman V. Superman?",
"answ":"DRONE MODE",
"answ3":"DRONE",
"answ2":"Drone Mode.",
"option":["Drone Mode", "Stealth Mode", "Sniper Mode", "War Mode"],
},
{
"cat":"Batman",
"ques":"Who voices Mob boss Salvatore Valestra in Batman: Mask of the Phantasm?",
"answ":"ABE VIGODA",
"answ2":"Abe Vigoda.",
"option":["Abe Vigoda", "Hart Bochner", "Stacy Keach", "Eric Roberts"],
},
{
"cat":"Batman",
"ques":"In Batman Forever, the film's first lines from Alfred have him suggesting to get Bruce Wayne a what?",
"answ":"SANDWICH",
"answ2":"Sandwich.",
"option":["Sandwich", "New suit", "Oil change", "Mojito"],
},
{
"cat":"Batman",
"ques":"While at the museum in 1989's Batman, what item is delivered to Vicki before Joker comes in?",
"answ":"MASK",
"answ3":"GAS MASK",
"answ2":"Gas mask.",
"option":["Gas mask", "Camera", "Tape recorder", "Flower"],
},
{
"cat":"Batman",
"ques":"In The Dark Knight Rises, what function of Batman's large aircraft is said by Lucius to be broken?",
"answ":"AUTOPILOT",
"answ3":"AUTO PILOT",
"answ2":"Auto-pilot.",
"option":["Auto-pilot", "Air conditioning", "Engine", "Landing gear"],
},
{
"cat":"Batman",
"ques":"How many films has Ben Affleck appeared in as Batman/Bruce Wayne?",
"answ":"3",
"answ3":"THREE",
"answ2":"3 (Batman v Superman/Suicide Squad/Justice League).",
"option":["3", "2", "4", "5"],
},
{
"cat":"Batman",
"ques":"Frank Gorshin plays what role in 1966's Batman: The Movie?",
"answ":"RIDDLER",
"answ3":"THE RIDDLER",
"answ2":"The Riddler.",
"option":["The Riddler", "Robin", "Penguin", "Two-Face"],
},
{
"cat":"Batman",
"ques":"Who plays the gangster Sal Maroni in The Dark Knight?",
"answ":"ERIC ROBERTS",
"answ2":"Eric Roberts.",
"option":["Eric Roberts", "Gary Cole", "Tom Wilkinson", "Joe Pesci"],
},
{
"cat":"Batman",
"ques":"In Batman V. Superman, the destruction of Metropolis the film opens with, takes place how many months before the rest of the film is set?",
"answ":"18",
"answ3":"18 YEARS",
"answ2":"18.",
"option":["18", "20", "15", "13"],
},
];
batman = shuffle(batman);
r2Q21 = shuffle(r2Q21);