var xmen = [
{
"cat":"X-Men",
"ques":"In X-Men First Class what real event do the X-Men try to prevent from happening in the 1960s?",
"answ":"CUBAN MISSILE CRISIS",
"answ3":"THE CUBAN MISSILE CRISIS",
"answ2":"The Cuban Missile Crisis.",
},
{
"cat":"X-men",
"ques":"In Deadpool 2, what is the name of Bill Skarsgard's acid spitting character?",
"answ":"ZEITGEIST",
"answ2":"Zeitgeist.",
},
{
"cat":"X-Men",
"ques":"The characters of William Stryker, Victor Creed, Agent Zero and Gambit appear in what X-Men universe film?",
"answ":"X MEN ORIGINS WOLVERINE",
"answ2":"X-Men Origins: Wolverine.",
},
{
"cat":"X-Men",
"ques":"Richard E. Grant plays Dr. Zander Rice in what 2010s Marvel comic based film?",
"answ":"LOGAN",
"answ2":"Logan.",
},
{
"cat":"X-Men",
"ques":"In X-Men: The Last Stand, at the end of the film Magneto slightly moves what object with his powers?",
"answ":"CHESS PIECE",
"answ2":"Chess piece.",
},
{
"cat":"X-Men",
"ques":"'All is revealed' are the last words of what X-Men villain?",
"answ":"APOCALYPSE",
"answ2":"Apocalypse.",
},
{
"cat":"X-Men",
"ques":"What mutant has the real name John Allerdyce?",
"answ":"PYRO",
"answ2":"Pyro.",
},
{
"cat":"X-Men",
"ques":"X-Men: The Last Stand opens with Charles and Erik visiting what young mutant?",
"answ":"JEAN GREY",
"answ2":"Jean Grey.",
},
{
"cat":"X-Men",
"ques":"In X-Men: Apocalypse, what movie do the students go out to see before they come back to see the mansion destroyed?",
"answ":"RETURN OF THE JEDI",
"answ2":"Return of the Jedi.",
},
{
"cat":"X-Men",
"ques":"In X-Men Origins: Wolverine, who kills Will.i.am's character John Wraith?",
"answ":"SABRETOOTH",
"answ3":"VICTOR CREED",
"answ2":"Sabretooth.",
},
{
"cat":"X-Men",
"ques":"In Deadpool, Wade proposes to Vanessa during which holiday?",
"answ":"CHRISTMAS",
"answ2":"Christmas.",
},
{
"cat":"X-Men",
"ques":"What mutant rescues Nightcrawler from a cage fighting arena in X-Men: Apocalypse?",
"answ":"MYSTIQUE",
"answ3":"RAVEN",
"answ2":"Mystique.",
},
{
"cat":"X-Men",
"ques":"How many actresses have played Jean Grey in the X-Men films?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4 (Famke Janssen/Sophie Turner/Haley Ramm/Summer Fontana).",
},
{
"cat":"X-Men",
"ques":"What supervillain name does Russell give himself in Deadpool 2?",
"answ":"FIREFIST",
"answ2":"Firefist.",
},
{
"cat":"X-Men",
"ques":"What is the name of the bartender played by TJ Miller in Deadpool?",
"answ":"WEASEL",
"answ2":"Weasel.",
},
{
"cat":"X-Men",
"ques":"What X-Men villain's real name is En Sabah Nur?",
"answ":"APOCALYPSE",
"answ3":"APOCALYPS",
"answ2":"Apocalypse.",
},
{
"cat":"X-Men",
"ques":"What is the name of Wade's roommate, played by Leslie Uggams, in Deadpool?",
"answ":"BLIND AL",
"answ3":"AL",
"answ2":"Blind Al.",
},
{
"cat":"X-Men",
"ques":"Name one of the two actors who cameo as rednecks in Deadpool 2.",
"answ":"MATT DAMON",
"answ3":"ALAN TUDYK",
"answ2":"Matt Damon/Alan Tudyk.",
},
{
"cat":"X-Men",
"ques":"What profession does Logan have before Sabretooth finds him and Silverfox in X-Men Origins: Wolverine?",
"answ":"LOGGER",
"answ3":"LUMBERJACK",
"answ2":"Logger/Lumberjack.",
},
{
"cat":"X-Men",
"ques":"How many live action X-Men movies did Bryan Singer direct?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"X-Men",
"ques":"In X-Men: Days of Future Past, Erik reveals that which US President was a mutant?",
"answ":"JOHN KENNEDY",
"answ3":"JFK",
"answ2":"John F. Kennedy.",
},
{
"cat":"X-Men",
"ques":"In X-Men: The Last Stand, which mutant reveals that they took the mutant cure voluntarily?",
"answ":"ROGUE",
"answ2":"Rogue.",
},
{
"cat":"X-Men",
"ques":"What X-Men film marks the first appearance of Moira MacTaggert?",
"answ":"X MEN THE LAST STAND",
"answ3":"THE LAST STAND",
"answ2":"X-Men: The Last Stand.",
},
{
"cat":"X-Men",
"ques":"Which X-Man was Logan substitute teaching for at the beginning of X-Men: The Last Stand?",
"answ":"SCOTT SUMMERS",
"answ3":"CYCLOPS",
"answ2":"Scott Summers/Cyclops.",
},
{
"cat":"X-Men",
"ques":"In how many X-Men films did Jennifer Lawrence appear as Raven/Mystique?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"X-Men",
"ques":"In how many X-Men films has Halle Berry appeared in?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
},
{
"cat":"X-Men",
"ques":"You'll find the characters of Angel, Nightcrawler, Jubilee and Moira MacTaggert in what X-Men film?",
"answ":"X MEN APOCALYPSE",
"answ3":"APOCALYPSE",
"answ2":"X-Men: Apocalypse.",
},
{
"cat":"X-Men",
"ques":"What is the first name of the mustached normal man, who is a member of the X-Force in Deadpool 2?",
"answ":"PETER",
"answ2":"Peter.",
},
{
"cat":"X-Men",
"ques":"Who plays Hank McCoy in X-Men: First Class?",
"answ":"NICHOLAS HOULT",
"answ2":"Nicholas Hoult.",
},
{
"cat":"X-Men",
"ques":"In X-Men, which mutant does Logan accidentally stab after they try to wake him up from nightmares?",
"answ":"ROGUE",
"answ2":"Rogue.",
},
{
"cat":"X-Men",
"ques":"What game do Charles and Erik play in Paris at the end of Dark Phoenix?",
"answ":"CHESS",
"answ2":"Chess.",
},
{
"cat":"X-Men",
"ques":"Who does Jean accidentally kill while outside her father's home in Dark Phoenix?",
"answ":"RAVEN",
"answ3":"MYSTIQUE",
"answ2":"Raven/Mystique.",
},
{
"cat":"X-Men",
"ques":"Which mutant infiltrates and sabotages Cerebro in X-Men?",
"answ":"MYSTIQUE",
"answ2":"Mystique.",
},
{
"cat":"X-Men",
"ques":"In X-Men: First Class, who saves Erik from drowning as he tries to stop Shaw from escaping in a submarine?",
"answ":"CHARLES XAVIER",
"answ3":"PROFESSOR X",
"answ2":"Charles Xavier.",
},
{
"cat":"X-Men",
"ques":"What is the ful real name of the villain Sabretooth in X-Men Origins: Wolverine",
"answ":"VICTOR CREED",
"answ2":"Victor Creed.",
},
{
"cat":"X-Men",
"ques":"Who directed The New Mutants?",
"answ":"JOSH BOONE",
"answ2":"Josh Boone.",
},
{
"cat":"X-Men",
"ques":"In X-Men: Days of Future Past, Erik breaks into the Pentagon to steal what item?",
"answ":"HIS HELMET",
"answ3":"HELMET",
"answ2":"His helmet.",
},
{
"cat":"X-Men",
"ques":"Who directed X-Men: The Last Stand?",
"answ":"BRETT RATNER",
"answ2":"Brett Ratner.",
},
{
"cat":"X-Men",
"ques":"Who plays the villainous Dr. Zander Rice in Logan?",
"answ":"RICHARD E GRANT",
"answ3":"RICHARD GRANT",
"answ2":"Richard E. Grant.",
},
{
"cat":"X-Men",
"ques":"X-Men Days of Future Past was nominated for which Oscar?",
"answ":"BEST VISUAL EFFECTS",
"answ3":"VISUAL EFFECTS",
"answ2":"Best Visual Effects.",
},
{
"cat":"X-Men",
"ques":"In what year was The Wolverine released?",
"answ":"2013",
"answ2":"2013.",
},
{
"cat":"X-Men",
"ques":"Why is Deadpool's suit red?",
"answ":"TO HIDE THE BLOOD",
"answ3":"IT HIDES THE BLOOD",
"answ2":"To hide the blood.",
},
{
"cat":"X-Men",
"ques":"Who played Apocalypse in X-Men: Apocalypse?",
"answ":"OSCAR ISAAC",
"answ2":"Oscar Isaac.",
},
{
"cat":"X-Men",
"ques":"What Game of Thrones star plays Jean Grey in X-Men Apocalypse?",
"answ":"SOPHIE TURNER",
"answ2":"Sophie Turner.",
},
{
"cat":"X-Men",
"ques":"Who played Mystique in 2000's X-Men?",
"answ":"REBECCA ROMIJN",
"answ2":"Rebecca Romijn.",
},
{
"cat":"X-Men",
"ques":"In X-Men First Class, what is the name of the mutant working with Sebastian Shaw who can produce tornadoes at will?",
"answ":"RIPTIDE",
"answ2":"Riptide.",
},
{
"cat":"X-Men",
"ques":"In 2000's X-Men, what mutant is presenting in front of a congressional hearing about mutants at the beginning of the film?",
"answ":"JEAN GREY",
"answ2":"Jean Grey.",
},
{
"cat":"X-Men",
"ques":"Who plays Kitty Pryde aka Shadowcat in X-Men: The Last Stand and Days of Future Past?",
"answ":"ELLEN PAGE",
"answ3":"ELLIOT PAGE",
"answ2":"Elliot Page.",
},
{
"cat":"X-Men",
"ques":"Who plays Colonel William Stryker in X2?",
"answ":"BRIAN COX",
"answ3":"BRYAN COX",
"answ2":"Brian Cox.",
},
{
"cat":"X-Men",
"ques":"X-Men: The Last Stand opens with a flashback of Xavier and Magneto attempting to recruit which mutant as a child?",
"answ":"JEAN GREY",
"answ2":"Jean Grey.",
},
{
"cat":"X-Men",
"ques":"Which actor plays Cable in Deadpool 2?",
"answ":"JOSH BROLIN",
"answ2":"Josh Brolin.",
},
{
"cat":"X-Men",
"ques":"Who played Cyclops in 2000's X-Men?",
"answ":"JAMES MARSDEN",
"answ2":"James Marsden.",
},
{
"cat":"X-Men",
"ques":"Who plays Laura in 2017's Logan?",
"answ":"DAFNE KEEN",
"answ3":"DAPHNE KEEN",
"answ2":"Dafne Keen.",
},
{
"cat":"X-Men",
"ques":"In Deadpool 2, who plays the hero Bedlam?",
"answ":"TERRY CREWS",
"answ2":"Terry Crews.",
},
{
"cat":"X-Men",
"ques":"What is the name of the robotic warrior that Wolverine fights at the end of The Wolverine?",
"answ":"SILVER SAMURAI",
"answ2":"Silver Samurai.",
},
{
"cat":"X-Men",
"ques":"In X2, what is the nickname of the young mutant that has the ability to control fire?",
"answ":"PYRO",
"answ2":"Pyro.",
},
{
"cat":"X-Men",
"ques":"Who voices Juggernaut in Deadpool 2?",
"answ":"RYAN REYNOLDS",
"answ2":"Ryan Reynolds.",
},
{
"cat":"X-Men",
"ques":"What is the alphanumeric codename of the feral clone of Wolverine in 2017's Logan?",
"answ":"X 24",
"answ3":"X24",
"answ2":"X-24.",
},
{
"cat":"X-Men",
"ques":"The character of Mortimer Toynbee appeared in the first X-Men film and X-Men Days of Future Past. He is better known by what mutant name?",
"answ":"TOAD",
"answ2":"Toad.",
},
{
"cat":"X-Men",
"ques":"In Logan, what is the name of the boat that Logan wants to get for Charles that he's been saving up for?",
"answ":"SUNSEEKER",
"answ3":"THE SUNSEEKER",
"answ2":"Sunseeker.",
},
{
"cat":"X-Men",
"ques":"Early in the 2000 film X-Men, who attacks Rogue and Logan when they're on the road?",
"answ":"SABRETOOTH",
"answ2":"Sabretooth.",
},
{
"cat":"X-Men",
"ques":"What famous actor made a cameo as Vanisher in Deadpool 2?",
"answ":"BRAD PITT",
"answ2":"Brad Pitt.",
},
{
"cat":"X-Men",
"ques":"Who played Bedlam in Deadpool 2?",
"answ":"TERRY CREWS",
"answ2":"Terry Crews.",
},
{
"cat":"X-Men",
"ques":"Who played Zeitgeist in Deadpool 2?",
"answ":"BILL SKARSGARD",
"answ3":"BILL SKARSGÂRD",
"answ2":"Bill Skarsgârd.",
},
{
"cat":"X-Men",
"ques":"Who played Peter in Deadpool 2?",
"answ":"ROB DELANEY",
"answ2":"Rob Delaney.",
},
{
"cat":"X-Men",
"ques":"Who directed 2016's Deadpool?",
"answ":"TIM MILLER",
"answ2":"Tim Miller.",
},
{
"cat":"X-Men",
"ques":"Who directed Deadpool 2?",
"answ":"DAVID LEITCH",
"answ2":"David Leitch.",
},
{
"cat":"X-Men",
"ques":"Who played Caliban in 2017's Logan?",
"answ":"STEPHEN MERCHANT",
"answ2":"Stephen Merchant.",
},
{
"cat":"X-Men",
"ques":"What famous singer played John Wraith in X-Men Origins: Wolverine?",
"answ":"WILLIAM",
"answ3":"WILL I AM",
"answ2":"Will.i.am.",
},
{
"cat":"X-Men",
"ques":"Who played Fred Dukes/Blob in X-Men Origins: Wolverine?",
"answ":"KEVIN DURAND",
"answ2":"Kevin Durand.",
},
{
"cat":"X-Men",
"ques":"Who directed X-Men Origins: Wolverine?",
"answ":"GAVIN HOOD",
"answ2":"Gavin Hood.",
},
{
"cat":"X-Men",
"ques":"What is the real name of the mutant known as Angel?",
"answ":"WARREN WORTHINGTON III",
"answ3":"WARREN WORTHINGTON 3",
"answ2":"Warren Worthington III.",
},
{
"cat":"X-Men",
"ques":"Who played Toad in the first X-Men film?",
"answ":"RAY PARK",
"answ2":"Ray Park.",
},
{
"cat":"X-Men",
"ques":"What is the name of the character that tracks down Logan in The Wolverine, to take him to Japan?",
"answ":"YUKIO",
"answ2":"Yukio.",
},
{
"cat":"X-Men",
"ques":"What was the name of the PG-13 version of Deadpool 2 that had new scenes featuring Fred Savage?",
"answ":"ONCE UPON A DEADPOOL",
"answ2":"Once Upon A Deadpool.",
},
{
"cat":"X-Men",
"ques":"What is the name of the shape-shifting aliens in X-Men: Dark Phoenix?",
"answ":"D'BARI",
"answ3":"DEBARI",
"answ2":"D'Bari.",
},
{
"cat":"X-Men",
"ques":"Name one of the two members of the X-Men that Lady Deathstrike kidnapped in X2.",
"answ":"CYCLOPS",
"answ3":"PROFESSOR X",
"answ2":"Cyclops/Professor X.",
},
{
"cat":"X-Men",
"ques":"In what X-Men movie will you hear the quote: 'I'm the Juggernaut, bitch!'?",
"answ":"X MEN THE LAST STAND",
"answ3":"THE LAST STAND",
"answ2":"X-Men The Last Stand.",
},
{
"cat":"X-Men",
"ques":"Who was the first mutant that Apocalypse recruited in X-Men: Apocalypse?",
"answ":"STORM",
"answ3":"ORORO MUNROE",
"answ2":"Storm.",
},
{
"cat":"X-Men",
"ques":"Which X-Men film involves a shape-shifting race of aliens called the D'Bari?",
"answ":"X MEN DARK PHOENIX",
"answ3":"DARK PHOENIX",
"answ2":"X-Men: Dark Phoenix.",
},
{
"cat":"X-Men",
"ques":"What is the name of the teleporting mutant in X-Men First Class?",
"answ":"AZAZEL",
"answ2":"Azazel.",
},
{
"cat":"X-Men",
"ques":"What building does Nightcrawler infiltrate at the beginning of X2?",
"answ":"THE WHITE HOUSE",
"answ3":"WHITE HOUSE",
"answ2":"The White House.",
},
{
"cat":"X-Men",
"ques":"Who said 'Two years I rotted in that hellhole and I ain't ever going back.' in X-Men Origins Wolverine?",
"answ":"GAMBIT",
"answ3":"REMY LEBEAU",
"answ2":"Gambit/Remy LeBeau.",
},
{
"cat":"X-Men",
"ques":"In X-Men: Apocalypse, who was Angel's opponent in the cage match before he fights Nightcrawler?",
"answ":"BLOB",
"answ3":"THE BLOB",
"answ2":"Blob.",
},
{
"cat":"X-Men",
"ques":"Name one of the two actors that played the mutant Angel in the X-Men franchise.",
"answ":"BEN FOSTER",
"answ3":"BEN HARDY",
"answ2":"Ben Foster/Ben Hardy.",
},
{
"cat":"X-Men",
"ques":"In Dark Phoenix, Jean Grey's parents were killed in what type of accident?",
"answ":"CAR ACCIDENT",
"answ3":"CAR CRASH",
"answ2":"Car crash.",
},
{
"cat":"X-Men",
"ques":"Who directed X-Men First Class?",
"answ":"MATTHEW VAUGHN",
"answ2":"Matthew Vaughn.",
},
];
var r2Q22 = [
{
"cat":"X-Men",
"ques":"In X-Men Days of Future Past, in the future timeline who does Logan injure with his claws?",
"answ":"KITTY PRYDE",
"answ2":"Kitty Pryde.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kitty Pryde</button><button id=incop2 class=buttons003 onclick=qinc()>Rogue</button><button id=incop3 class=buttons003 onclick=qinc()>Cyclops</button><button id=incop4 class=buttons003 onclick=qinc()>Jean Grey</button><br/>",
},
{
"cat":"X-Men",
"ques":"Where is Magneto imprisoned in X-Men Days of Future Past?",
"answ":"THE PENTAGON",
"answ3":"PENTAGON",
"answ2":"The Pentagon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alcatraz</button><button id=corop class=buttons003 onclick=qcor()>The Pentagon</button><button id=incop3 class=buttons003 onclick=qinc()>The Raft</button><button id=incop4 class=buttons003 onclick=qinc()>Guantanamo Bay</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men First Class, Charles Xavier graduates from which university?",
"answ":"OXFORD",
"answ3":"OXFORD UNIVERSITY",
"answ2":"Oxford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harvard</button><button id=corop class=buttons003 onclick=qcor()>Oxford</button><button id=incop3 class=buttons003 onclick=qinc()>Cambridge</button><button id=incop4 class=buttons003 onclick=qinc()>Princeton</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men First Class, what did Magneto kill Sebastian Shaw with?",
"answ":"A COIN",
"answ3":"COIN",
"answ2":"A coin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A coin</button><button id=incop2 class=buttons003 onclick=qinc()>A hammer</button><button id=incop3 class=buttons003 onclick=qinc()>A gun</button><button id=incop4 class=buttons003 onclick=qinc()>A nail</button><br/>",
},
{
"cat":"X-Men",
"ques":"While ranting to Colossus, what does Deadpool refer to the X-Mansion as?",
"answ":"NEVERLAND MANSION",
"answ2":"Neverland Mansion.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Neverland Mansion</button><button id=incop2 class=buttons003 onclick=qinc()>Boy Band HQ</button><button id=incop3 class=buttons003 onclick=qinc()>Pervert Manor</button><button id=incop4 class=buttons003 onclick=qinc()>XXX Men Mansion</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Logan, what is the name of the group of mutant hunters led by Donald Pierce?",
"answ":"REAVERS",
"answ3":"THE REAVERS",
"answ2":"Reavers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Reavers</button><button id=incop2 class=buttons003 onclick=qinc()>Ravagers</button><button id=incop3 class=buttons003 onclick=qinc()>Scavengers</button><button id=incop4 class=buttons003 onclick=qinc()>X-Force</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Logan, what animal does Charles compare Laura to?",
"answ":"LIONESS",
"answ3":"LION",
"answ2":"Lioness.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hawk</button><button id=corop class=buttons003 onclick=qcor()>Lioness</button><button id=incop3 class=buttons003 onclick=qinc()>Raptor</button><button id=incop4 class=buttons003 onclick=qinc()>Bobcat</button><br/>",
},
{
"cat":"X-Men",
"ques":"In which Eastern European country was Magneto hiding at the beginning of X-Men Apocalypse?",
"answ":"POLAND",
"answ2":"Poland.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>East Germany</button><button id=incop2 class=buttons003 onclick=qinc()>Czech Republic</button><button id=corop class=buttons003 onclick=qcor()>Poland</button><button id=incop4 class=buttons003 onclick=qinc()>Romania</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X2: X-Men United, the jet plane has trouble lifting off because the what are offline?",
"answ":"VERTICAL THRUSTERS",
"answ3":"THE VERTICAL THRUSTERS",
"answ2":"Vertical Thrusters.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Engine Boosters</button><button id=incop2 class=buttons003 onclick=qinc()>Jet Propulsions</button><button id=corop class=buttons003 onclick=qcor()>Vertical Thrusters</button><button id=incop4 class=buttons003 onclick=qinc()>Alignment Gears</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Logan, what is the full name of the nurse who hires Logan?",
"answ":"GABRIELA LOPEZ",
"answ3":"GABRIELA LÓPEZ",
"answ2":"Gabriela López.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Esperanza Martinez</button><button id=incop2 class=buttons003 onclick=qinc()>Laura Chavez</button><button id=corop class=buttons003 onclick=qcor()>Gabriela López</button><button id=incop4 class=buttons003 onclick=qinc()>Maria Fernandez</button><br/>",
},
{
"cat":"X-Men",
"ques":"What does Deadpool say is the 'old-fashioned way' of doing this?",
"answ":"WITH 2 SWORDS AND MAXIMUM EFFORT",
"answ3":"WITH TWO SWORDS AND MAXIMUM EFFORT",
"answ2":"With two swords and maximum effort.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>With two fists and a music beat to punch to</button><button id=incop2 class=buttons003 onclick=qinc()>With two guns and plenty of ammo</button><button id=corop class=buttons003 onclick=qcor()>With two swords and maximum effort</button><button id=incop4 class=buttons003 onclick=qinc()>With two brass knuckles and a woman to go home to</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men First Class, what is the name of Sebastian Shaw's secret society?",
"answ":"THE HELLFIRE CLUB",
"answ3":"HELLFIRE CLUB",
"answ2":"The Hellfire Club.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Mutant Alliance</button><button id=incop2 class=buttons003 onclick=qinc()>The Inner Circle</button><button id=corop class=buttons003 onclick=qcor()>The Hellfire Club</button><button id=incop4 class=buttons003 onclick=qinc()>Mutant Liberation Front</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Logan, what is the name of the place that Laura is trying to get to?",
"answ":"EDEN",
"answ2":"Eden.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Haven</button><button id=incop2 class=buttons003 onclick=qinc()>The Beyond</button><button id=incop3 class=buttons003 onclick=qinc()>Aurora</button><button id=corop class=buttons003 onclick=qcor()>Eden</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Bobby Drake aka Iceman in X-Men, X2 and The Last Stand?",
"answ":"SHAWN ASHMORE",
"answ2":"Shawn Ashmore.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Marsden</button><button id=incop2 class=buttons003 onclick=qinc()>Alexander Burton</button><button id=incop3 class=buttons003 onclick=qinc()>Tyler Mane</button><button id=corop class=buttons003 onclick=qcor()>Shawn Ashmore</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Logan, how much money is Logan paid to take Laura to North Dakota?",
"answ":"20000",
"answ3":"20 000",
"answ2":"$20,000.",
"option":"<button id=corop class=buttons003 onclick=qcor()>$20,000</button><button id=incop2 class=buttons003 onclick=qinc()>$60,000</button><button id=incop3 class=buttons003 onclick=qinc()>$80,000</button><button id=incop4 class=buttons003 onclick=qinc()>$100,000</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Ajax's right hand woman Angel Dust in Deadpool?",
"answ":"GINA CARANO",
"answ2":"Gina Carano.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gina Carano</button><button id=incop2 class=buttons003 onclick=qinc()>Morena Baccarin</button><button id=incop3 class=buttons003 onclick=qinc()>Brianna Hildebrand</button><button id=incop4 class=buttons003 onclick=qinc()>Zazie Beetz</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men First Class, in what Southern American country does Erik find the two Nazi's he's been searching for?",
"answ":"ARGENTINA",
"answ2":"Argentina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brazil</button><button id=corop class=buttons003 onclick=qcor()>Argentina</button><button id=incop3 class=buttons003 onclick=qinc()>Chile</button><button id=incop4 class=buttons003 onclick=qinc()>Bolivia</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played the mutant Psylocke in X-Men Apocalypse?",
"answ":"OLIVIA MUNN",
"answ2":"Olivia Munn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sophie Turner</button><button id=incop2 class=buttons003 onclick=qinc()>Olivia Wilde</button><button id=incop3 class=buttons003 onclick=qinc()>Michelle Yeoh</button><button id=corop class=buttons003 onclick=qcor()>Olivia Munn</button><br/>",
},
{
"cat":"X-Men",
"ques":"What is Cyclops' full real name in the X-Men franchise?",
"answ":"SCOTT SUMMERS",
"answ2":"Scott Summers.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Bobby Drake</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Kelly</button><button id=incop3 class=buttons003 onclick=qinc()>John Allerdyce</button><button id=corop class=buttons003 onclick=qcor()>Scott Summers</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Deadpool, during the battle on the highway, Deadpool says he has how many bullets left in his guns?",
"answ":"12",
"answ3":"TWELVE",
"answ2":"12.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=incop3 class=buttons003 onclick=qinc()>10</button><button id=corop class=buttons003 onclick=qcor()>12</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who plays Will Munson, the farmer who Logan helps, in Logan?",
"answ":"ERIQ LA SALLE",
"answ3":"ERIC LA SALLE",
"answ2":"Eriq La Salle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Boyd Holbrook</button><button id=incop2 class=buttons003 onclick=qinc()>Ruben Blades</button><button id=incop3 class=buttons003 onclick=qinc()>Richard E. Grant</button><button id=corop class=buttons003 onclick=qcor()>Eriq La Salle</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men Days of Future Past, what mutant in the future timeline is able to sense when Sentinels are approaching?",
"answ":"WARPATH",
"answ2":"Warpath.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Sunspot</button><button id=incop2 class=buttons003 onclick=qinc()>Colossus</button><button id=incop3 class=buttons003 onclick=qinc()>Blink</button><button id=corop class=buttons003 onclick=qcor()>Warpath</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X2, Mystique helps Magneto escape from prison by injecting what kind of metal into the security guard's blood?",
"answ":"IRON",
"answ2":"Iron.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Iron</button><button id=incop2 class=buttons003 onclick=qinc()>Adamantium</button><button id=incop3 class=buttons003 onclick=qinc()>Bronze</button><button id=incop4 class=buttons003 onclick=qinc()>Copper</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men: First Class, what is Sebastian Shaw's yacht called?",
"answ":"CASPARTINA",
"answ2":"Caspartina.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Albatross</button><button id=incop2 class=buttons003 onclick=qinc()>Red Tide</button><button id=incop3 class=buttons003 onclick=qinc()>Saracen</button><button id=corop class=buttons003 onclick=qcor()>Caspartina</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Deadpool, what kind of pizza does Wade have delivered in order to threaten the pizza delivery guy into stop stalking a girl?",
"answ":"PINEAPPLE AND OLIVE",
"answ3":"PINEAPPLE OLIVE",
"answ2":"Pineapple and olive.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Banana pepper and pineapple</button><button id=incop2 class=buttons003 onclick=qinc()>Pepperoni and marshmallow</button><button id=corop class=buttons003 onclick=qcor()>Pineapple and olive</button><button id=incop4 class=buttons003 onclick=qinc()>Ham and anchovies</button><br/>",
},
{
"cat":"X-Men",
"ques":"In 2000's X-Men, what is Rogue's real first name?",
"answ":"MARIE",
"answ2":"Marie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Julia</button><button id=corop class=buttons003 onclick=qcor()>Marie</button><button id=incop3 class=buttons003 onclick=qinc()>Jean</button><button id=incop4 class=buttons003 onclick=qinc()>Rose</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X2, after escaping Stryker's raid on the mansion, what song plays loudly when Pyro turns on the radio in Cyclops' car?",
"answ":"BYE BYE BYE",
"answ2":"Bye Bye Bye.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Bye Bye Bye</button><button id=incop2 class=buttons003 onclick=qinc()>Wannabe</button><button id=incop3 class=buttons003 onclick=qinc()>Everybody (Backtreet's Back)</button><button id=incop4 class=buttons003 onclick=qinc()>Baby One More Time</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Deadpool 2, what is the name of the X-Force member played by Lewis Tan?",
"answ":"SHATTERSTAR",
"answ2":"Shatterstar.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Shatterstar</button><button id=incop2 class=buttons003 onclick=qinc()>Zeitgeist</button><button id=incop3 class=buttons003 onclick=qinc()>Vanisher</button><button id=incop4 class=buttons003 onclick=qinc()>Bedlam</button><br/>",
},
{
"cat":"X-Men",
"ques":"In 2013's The Wolverine, mutant villain Dr. Green also went by what name?",
"answ":"VIPER",
"answ2":"Viper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Copperhead</button><button id=corop class=buttons003 onclick=qcor()>Viper</button><button id=incop3 class=buttons003 onclick=qinc()>Cobra</button><button id=incop4 class=buttons003 onclick=qinc()>Rattler</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men Apocalypse, what song plays during the Quicksilver X-Mansion rescue scene?",
"answ":"SWEET DREAMS",
"answ3":"SWEET DREAMS ARE MADE OF THIS",
"answ2":"Sweet Dreams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>We Are The Champions</button><button id=corop class=buttons003 onclick=qcor()>Sweet Dreams</button><button id=incop3 class=buttons003 onclick=qinc()>Eye of the Tiger</button><button id=incop4 class=buttons003 onclick=qinc()>Good Vibrations</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X2: X-Men United, what subject does Wolverine tell Bobby Drake's parents he teaches at the Xavier Institute?",
"answ":"ART",
"answ2":"Art.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Poetry</button><button id=incop2 class=buttons003 onclick=qinc()>Music</button><button id=incop3 class=buttons003 onclick=qinc()>Gym</button><button id=corop class=buttons003 onclick=qcor()>Art</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men: Days of Future Past, who plays Bolivar Trask, a military scientist whom Mystique assassinated in the original 1973?",
"answ":"PETER DINKLAGE",
"answ2":"Peter Dinklage.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brian Cox</button><button id=incop2 class=buttons003 onclick=qinc()>Laurence Fishburne</button><button id=incop3 class=buttons003 onclick=qinc()>John Hurt</button><button id=corop class=buttons003 onclick=qcor()>Peter Dinklage</button><br/>",
},
{
"cat":"X-Men",
"ques":"What Chinese New Year animal does Vanessa say it is during the sex montage in Deadpool?",
"answ":"DOG",
"answ2":"Dog.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Chicken</button><button id=incop2 class=buttons003 onclick=qinc()>Cow</button><button id=incop3 class=buttons003 onclick=qinc()>Rat</button><button id=corop class=buttons003 onclick=qcor()>Dog</button><br/>",
},
{
"cat":"X-Men",
"ques":"What was the first X-Men movie to be nominated for Best Adapted Screenplay?",
"answ":"LOGAN",
"answ2":"Logan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>X-Men: Days of Future Past</button><button id=incop2 class=buttons003 onclick=qinc()>X-Men: First Class</button><button id=incop3 class=buttons003 onclick=qinc()>X-Men</button><button id=corop class=buttons003 onclick=qcor()>Logan</button><br/>",
},
{
"cat":"X-Men",
"ques":"In Deadpool, what is the name of the taxi driver that gives a ride to Deadpool multiple times in the film?",
"answ":"DOPINDER",
"answ2":"Dopinder.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Raj</button><button id=incop2 class=buttons003 onclick=qinc()>Raviv</button><button id=incop3 class=buttons003 onclick=qinc()>Ahmed</button><button id=corop class=buttons003 onclick=qcor()>Dopinder</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men Days of Future Past, what government building does Magneto surround with a baseball stadium?",
"answ":"WHITE HOUSE",
"answ3":"THE WHITE HOUSE",
"answ2":"The White House.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Pentagon</button><button id=incop2 class=buttons003 onclick=qinc()>The Capitol</button><button id=incop3 class=buttons003 onclick=qinc()>Eisenhower Executive Office Building</button><button id=corop class=buttons003 onclick=qcor()>The White House</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who plays Moira McTaggert in X-Men First Class and X-Men Apocalypse?",
"answ":"ROSE BYRNE",
"answ2":"Rose Byrne.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Amy Adams</button><button id=incop2 class=buttons003 onclick=qinc()>The Coby Smulders</button><button id=incop3 class=buttons003 onclick=qinc()>Hilary Swank</button><button id=corop class=buttons003 onclick=qcor()>Rose Byrne</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men: First Class, Sebastian Shaw worked for the Nazi's under what name?",
"answ":"KLAUS SCHMIDT",
"answ3":"DR KLAUS SCHMIDT",
"answ2":"Klaus Schmidt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Karl Müller</button><button id=incop2 class=buttons003 onclick=qinc()>Günter Schulz</button><button id=incop3 class=buttons003 onclick=qinc()>Hans Meier</button><button id=corop class=buttons003 onclick=qcor()>Klaus Schmidt</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Gambit in X-Men Origins: Wolverine?",
"answ":"TAYLOR KITCH",
"answ2":"Taylor Kitch.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alexander Skarsgard</button><button id=incop2 class=buttons003 onclick=qinc()>Dylan O'Brien</button><button id=incop3 class=buttons003 onclick=qinc()>Logan Lerman</button><button id=corop class=buttons003 onclick=qcor()>Taylor Kitch</button><br/>",
},
{
"cat":"X-Men",
"ques":"What did Iceman create out of ice for Rogue on her desk in X-Men?",
"answ":"ROSE",
"answ3":"FLOWER",
"answ2":"Rose.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rose</button><button id=incop2 class=buttons003 onclick=qinc()>Compass</button><button id=incop3 class=buttons003 onclick=qinc()>Cat</button><button id=incop4 class=buttons003 onclick=qinc()>Clock</button><br/>",
},
{
"cat":"X-Men",
"ques":"Which mutant's DNA is essential to the evolution of the Sentinels in X-Men Days of Future Past?",
"answ":"MYSTIQUE",
"answ3":"RAVEN",
"answ2":"Mystique.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mystique</button><button id=incop2 class=buttons003 onclick=qinc()>Rogue</button><button id=incop3 class=buttons003 onclick=qinc()>Jean Grey</button><button id=incop4 class=buttons003 onclick=qinc()>Professor X</button><br/>",
},
{
"cat":"X-Men",
"ques":"Alan Cumming played which mutant in X2?",
"answ":"NIGHTCRAWLER",
"answ2":"Nightcrawler.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nightcrawler</button><button id=incop2 class=buttons003 onclick=qinc()>Cyclops</button><button id=incop3 class=buttons003 onclick=qinc()>Iceman</button><button id=incop4 class=buttons003 onclick=qinc()>Pyro</button><br/>",
},
{
"cat":"X-Men",
"ques":"What is Magneto's prison cell made of in X2: X-Men United?",
"answ":"PLASTIC",
"answ2":"Plastic.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Plastic</button><button id=incop2 class=buttons003 onclick=qinc()>Glass</button><button id=incop3 class=buttons003 onclick=qinc()>Adamantium</button><button id=incop4 class=buttons003 onclick=qinc()>Wood</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X2: X-Men United, who stops Pyro's rampage against police officers?",
"answ":"ROGUE",
"answ2":"Rogue.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rogue</button><button id=incop2 class=buttons003 onclick=qinc()>Jean Grey</button><button id=incop3 class=buttons003 onclick=qinc()>Wolverine</button><button id=incop4 class=buttons003 onclick=qinc()>Professor X</button><br/>",
},
{
"cat":"X-Men",
"ques":"How many times did Hugh Jackman play Wolverine on screen?",
"answ":"NINE",
"answ3":"9",
"answ2":"9.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>5</button><button id=incop2 class=buttons003 onclick=qinc()>6</button><button id=incop3 class=buttons003 onclick=qinc()>7</button><button id=corop class=buttons003 onclick=qcor()>9</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who directed 2013's The Wolverine?",
"answ":"JAMES MANGOLD",
"answ2":"James Mangold.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gavin Hood</button><button id=incop2 class=buttons003 onclick=qinc()>Brett Ratner</button><button id=incop3 class=buttons003 onclick=qinc()>Bryan Singer</button><button id=corop class=buttons003 onclick=qcor()>James Mangold</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Victor Creed in X-Men Origins: Wolverine?",
"answ":"LIEV SCHREIBER",
"answ3":"LIEB SCHREIBER",
"answ2":"Liev Schreiber.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Clive Owen</button><button id=incop2 class=buttons003 onclick=qinc()>Kevin Durand</button><button id=incop3 class=buttons003 onclick=qinc()>Daniel Henney</button><button id=corop class=buttons003 onclick=qcor()>Liev Schreiber</button><br/>",
},
{
"cat":"X-Men",
"ques":"How many X-Men movies did Anna Paquin appear in?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"X-Men",
"ques":"What classic western do Professor X and Laura watch in Logan?",
"answ":"SHANE",
"answ2":"Shane.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Silver Lode</button><button id=incop2 class=buttons003 onclick=qinc()>Giant</button><button id=incop3 class=buttons003 onclick=qinc()>Rio Bravo</button><button id=corop class=buttons003 onclick=qcor()>Shane</button><br/>",
},
{
"cat":"X-Men",
"ques":"What is Ajax's actual first name in Deadpool?",
"answ":"FRANCIS",
"answ2":"Francis.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Kim</button><button id=incop2 class=buttons003 onclick=qinc()>Jean</button><button id=incop3 class=buttons003 onclick=qinc()>Jordan</button><button id=corop class=buttons003 onclick=qcor()>Francis</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who plays Beast in X-Men: The Last Stand?",
"answ":"KELSEY GRAMMER",
"answ3":"KELSEY GRAMMAR",
"answ2":"Kelsey Grammer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nicholas Hoult</button><button id=incop2 class=buttons003 onclick=qinc()>Hank Azaria</button><button id=incop3 class=buttons003 onclick=qinc()>James Marsden</button><button id=corop class=buttons003 onclick=qcor()>Kelsey Grammer</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Colossus in X2 and X-Men: The Last Stand?",
"answ":"DANIEL CUDMORE",
"answ2":"Daniel Cudmore.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Donald Mackinnon</button><button id=incop2 class=buttons003 onclick=qinc()>Stefan Kapičić</button><button id=corop class=buttons003 onclick=qcor()>Daniel Cudmore</button><button id=incop4 class=buttons003 onclick=qinc()>T.J. Storm</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who played Pyro in X2 and X-Men: The Last Stand?",
"answ":"AARON STANFORD",
"answ2":"Aaron Stanford.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ben Foster</button><button id=incop2 class=buttons003 onclick=qinc()>James Marsden</button><button id=corop class=buttons003 onclick=qcor()>Aaron Stanford</button><button id=incop4 class=buttons003 onclick=qinc()>Shawn Ashmore</button><br/>",
},
{
"cat":"X-Men",
"ques":"In what year was X-Men: Days of Future Past released?",
"answ":"2014",
"answ2":"2014.",
"option":"<button id=corop class=buttons003 onclick=qcor()>2014</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=incop3 class=buttons003 onclick=qinc()>2012</button><button id=incop4 class=buttons003 onclick=qinc()>2011</button><br/>",
},
{
"cat":"X-Men",
"ques":"In what year was X-Men: First Class released?",
"answ":"2011",
"answ2":"2011.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2010</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=incop3 class=buttons003 onclick=qinc()>2012</button><button id=corop class=buttons003 onclick=qcor()>2011</button><br/>",
},
{
"cat":"X-Men",
"ques":"In what year was X-Men: Apocalypse released?",
"answ":"2016",
"answ2":"2016.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2012</button><button id=incop2 class=buttons003 onclick=qinc()>2013</button><button id=incop3 class=buttons003 onclick=qinc()>2015</button><button id=corop class=buttons003 onclick=qcor()>2016</button><br/>",
},
{
"cat":"X-Men",
"ques":"In what year was X-Men: Dark Phoenix released?",
"answ":"2019",
"answ2":"2019.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2020</button><button id=incop2 class=buttons003 onclick=qinc()>2017</button><button id=incop3 class=buttons003 onclick=qinc()>2018</button><button id=corop class=buttons003 onclick=qcor()>2019</button><br/>",
},
{
"cat":"X-Men",
"ques":"What year saw the release of X-Men The Last Stand?",
"answ":"2006",
"answ2":"2006.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2007</button><button id=incop2 class=buttons003 onclick=qinc()>2004</button><button id=incop3 class=buttons003 onclick=qinc()>2005</button><button id=corop class=buttons003 onclick=qcor()>2006</button><br/>",
},
{
"cat":"X-Men",
"ques":"Rose Byrne played the role of Moira MacTaggert in how many X-Men films?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=corop class=buttons003 onclick=qcor()>2</button><button id=incop3 class=buttons003 onclick=qinc()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"X-Men",
"ques":"Who plays Rahne Sinclair, also known as Wolfsbane, in New Mutants?",
"answ":"MAISIE WILLIAMS",
"answ2":"Maisie Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brianna Hildebrand</button><button id=corop class=buttons003 onclick=qcor()>Maisie Williams</button><button id=incop3 class=buttons003 onclick=qinc()>Anya Taylor-Joy</button><button id=incop4 class=buttons003 onclick=qinc()>Blu Hunt</button><br/>",
},
{
"cat":"X-Men",
"ques":"In X-Men (2000), which mutants kills Sabretooth?",
"answ":"CYCLOPS",
"answ2":"Cyclops.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jean Grey</button><button id=corop class=buttons003 onclick=qcor()>Cyclops</button><button id=incop3 class=buttons003 onclick=qinc()>Storm</button><button id=incop4 class=buttons003 onclick=qinc()>Wolverine</button><br/>",
},
{
"cat":"X-Men",
"ques":"You'll find Rogue in Meridian, Missisippi, where she accidentally harms her boyfriend at the beginning of which X-Men film?",
"answ":"X MEN",
"answ3":"X MEN 2000",
"answ2":"X-Men (2000).",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>X-Men: The Last Stand</button><button id=corop class=buttons003 onclick=qcor()>X-Men</button><button id=incop3 class=buttons003 onclick=qinc()>X-Men: Days of Future Past</button><button id=incop4 class=buttons003 onclick=qinc()>X2</button><br/>",
},
{
"cat":"X-Men",
"ques":"In which X-Men film does Charles Xavier say: 'Just because someone stumbles and loses their path, doesn't mean they're lost forever.'?",
"answ":"X MEN DAYS OF FUTURE PAST",
"answ3":"DAYS OF FUTURE PAST",
"answ2":"X-Men: Days of Future Past.",
"option":"<button id=corop class=buttons003 onclick=qcor()>X-Men: Days of Future Past</button><button id=incop2 class=buttons003 onclick=qinc()>X2</button><button id=incop3 class=buttons003 onclick=qinc()>X-Men: Apocalypse</button><button id=incop4 class=buttons003 onclick=qinc()>Logan</button><br/>",
},
{
"cat":"X-men",
"ques":"Who played Warren Worthington II, the head of Worthington Labs in X-Men: The Last Stand?",
"answ":"MICHAEL MURPHY",
"answ2":"Michael Murphy.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael Murphy</button><button id=incop2 class=buttons003 onclick=qinc()>Daniel Cudmore</button><button id=incop3 class=buttons003 onclick=qinc()>Josef Sommer</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Duke</button><br/>",
},
{
"cat":"X-men",
"ques":"In X-Men: Days of Future Past, William Stryker says that his son Jason is coming up on how many years old?",
"answ":"8",
"answ3":"EIGHT",
"answ2":"8.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>4</button><button id=incop2 class=buttons003 onclick=qinc()>6</button><button id=corop class=buttons003 onclick=qcor()>8</button><button id=incop4 class=buttons003 onclick=qinc()>10</button><br/>",
},
{
"cat":"X-men",
"ques":"In X-Men First Class, Klaus Schmidt says to young Erik that his gift is unlocked with anger and what?",
"answ":"PAIN",
"answ2":"Pain.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pain</button><button id=incop2 class=buttons003 onclick=qinc()>Rage</button><button id=incop3 class=buttons003 onclick=qinc()>Despair</button><button id=incop4 class=buttons003 onclick=qinc()>Stress</button><br/>",
},
];
xmen = shuffle(xmen);
r2Q22 = shuffle(r2Q22);