var spiderman = [
{
"cat":"Spider-Man",
"ques":"Besides Stan Lee, who cameos as a different character in each of Sam Raimi's Spider-Man films?",
"answ":"BRUCE CAMPBELL",
"answ3":"BRUCE CAMBELL",
"answ2":"Bruce Campbell.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Robbie Robertson in the Sam Raimi Spider-Man films?",
"answ":"BILL NUNN",
"answ2":"Bill Nunn.",
},
{
"cat":"Spider-Man",
"ques":"Dr. Curt Connors says the line: 'I want to create a world without weakness' in which Spider-Man film?",
"answ":"THE AMAZING SPIDER MAN",
"answ3":"AMAZING SPIDER MAN",
"answ2":"The Amazing Spider-Man.",
},
{
"cat":"Spider-Man",
"ques":"This actor had seperate roles as a ring announcer, a snooty usher and a French maître d' in the Sam Raimi Spider-Man films.",
"answ":"BRUCE CAMPBELL",
"answ2":"Bruce Campbell.",
},
{
"cat":"Spider-Man",
"ques":"In what Spider-Man film will you find Delmar's grocery deli?",
"answ":"SPIDER MAN HOMECOMING",
"answ3":"SPIDERMAN HOMECOMING",
"answ2":"Spider-Man: Homecoming.",
},
{
"cat":"Spider-Man",
"ques":"In which Spider-Man film does a man find Spider-Man's suit in the garbage and then give it to J. Jonah Jameson?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDER MAN II",
"answ2":"Spider-Man 2.",
},
{
"cat":"Spider-Man",
"ques":"Kenneth Choi plays High School Principal Morita in which Spider-Man film?",
"answ":"SPIDER MAN HOMECOMING",
"answ3":"SPIDERMAN HOMECOMING",
"answ2":"Spider-Man: Homecoming.",
},
{
"cat":"Spider-Man",
"ques":"Which Spider-Man film features cameo performances from the actors Joel McHale and Emily Deschanel?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDER MAN II",
"answ2":"Spider-Man 2.",
},
{
"cat":"Spider-Man",
"ques":"In what Spider-Man film will you find electrical engineer Max Dillon working for Oscorp?",
"answ":"THE AMAZING SPIDER MAN 2",
"answ3":"AMAZING SPIDER MAN 2",
"answ2":"The Amazing Spider-Man 2.",
},
{
"cat":"Spider-Man",
"ques":"What company did Peter's father work at in The Amazing Spider-Man?",
"answ":"OSCORP",
"answ3":"OSCORP INDUSTRIES",
"answ2":"Oscorp.",
},
{
"cat":"Spider-Man",
"ques":"What is the human name of the character played by Thomas Haden Church in Spider-Man 3?",
"answ":"FLINT MARKO",
"answ3":"FLINT",
"answ2":"Flint Marko.",
},
{
"cat":"Spider-Man",
"ques":"In the post-credits scene of Spider-Man Homecoming, Captain America talks about what valuable trait for soldiers and students?",
"answ":"PATIENCE",
"answ2":"Patience.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Homecoming, Peter reviews embarrassing footage of himself doing an impression of what Avenger?",
"answ":"THOR",
"answ2":"Thor.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Into the Spider-Verse, Peter Miles and Gwen visits whose home to create a new override key?",
"answ":"AUNT MAY",
"answ3":"MAY PARKER",
"answ2":"Aunt May.",
},
{
"cat":"Spider-Man",
"ques":"Who is the DJ at Liz's party in Spider-Man: Homecoming?",
"answ":"FLASH",
"answ3":"FLASH THOMPSON",
"answ2":"Flash Thompson.",
},
{
"cat":"Spider-Man",
"ques":"What job does Peter get fired from at the start of Spider-Man 2?",
"answ":"PIZZA DELIVERY",
"answ3":"PIZZA DELIVERY MAN",
"answ2":"Pizza delivery.",
},
{
"cat":"Spider-Man",
"ques":"What is the first name of Peter's best friend in Spider-Man: Homecoming?",
"answ":"NED",
"answ2":"Ned.",
},
{
"cat":"Spider-Man",
"ques":"What New York City borough is Peter Park from?",
"answ":"QUEENS",
"answ2":"Queens.",
},
{
"cat":"Spider-Man",
"ques":"What newspaper does Peter work for as a freelance photographer in Spider-Man?",
"answ":"THE DAILY BUGLE",
"answ3":"DAILY BUGLE",
"answ2":"The Daily Bugle.",
},
{
"cat":"Spider-Man",
"ques":"What was the final answer of the Academic Decathlon in Spider-Man: Homecoming?",
"answ":"0",
"answ3":"ZERO",
"answ2":"Zero.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 2, J. Jonah Jameson acquires Spider-Man's suit from someone with what profession?",
"answ":"GARBAGE MAN",
"answ3":"GARBAGEMAN",
"answ2":"Garbage man.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, who pilots the aircraft that drops Peter off at the finale in London?",
"answ":"HAPPY HOGAN",
"answ3":"HAPPY",
"answ2":"Happy Hogan.",
},
{
"cat":"Spider-Man",
"ques":"Who does Doc Ock kidnap and carry up a building after attempting a bank robbery in Spider-Man 2?",
"answ":"AUNT MAY",
"answ3":"MAY PARKER",
"answ2":"Aunt May.",
},
{
"cat":"Spider-Man",
"ques":"Whose funeral do MJ and Peter attend at the end of Spider-Man 3?",
"answ":"HARRY OSBORN",
"answ2":"Harry Osborn.",
},
{
"cat":"Spider-Man",
"ques":"What alias does Mysterio go by in Spider-Man: Far From Home?",
"answ":"QUENTIN BECK",
"answ2":"Quentin Beck.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Homecoming, Peter stops a bank robbery where the thieves are wearing masks of whom?",
"answ":"THE AVENGERS",
"answ3":"AVENGERS",
"answ2":"The Avengers.",
},
{
"cat":"Spider-Man",
"ques":"Who voiced Doctor Octopus in Spider-Man: Into the Spider-Verse?",
"answ":"KATHRYN HAHN",
"answ2":"Kathryn Hahn.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, where does the class go instead of the festival while in Prague?",
"answ":"OPERA",
"answ2":"Opera.",
},
{
"cat":"Spider-Man",
"ques":"In what year was Spider-Man Homecoming released?",
"answ":"2017",
"answ2":"2017.",
},
{
"cat":"Spider-Man",
"ques":"In what year was Spider-Man Far From Home released?",
"answ":"2019",
"answ2":"2019.",
},
{
"cat":"Spider-Man",
"ques":"Who directed Spider-Man Far From Home?",
"answ":"JON WATTS",
"answ2":"Jon Watts.",
},
{
"cat":"Spider-Man",
"ques":"Who directed Spider-Man Homecoming?",
"answ":"JON WATTS",
"answ2":"Jon Watts.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Homecoming, Ned says he wants to assist Peter with his missions by being his 'what'?",
"answ":"GUY IN THE CHAIR",
"answ2":"Guy in the chair.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Homecoming, Ned asks Peter to build what LEGO object with him?",
"answ":"DEATH STAR",
"answ2":"Death Star.",
},
{
"cat":"Spider-Man",
"ques":"Which Community actor plays Aaron Davis, the man who buys weapons from Adrian Toombs in Spider-Man: Homecoming?",
"answ":"DONALD GLOVER",
"answ2":"Donald Glover.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 3, Peter uses the loud sound of what to remove the symbiote from himself before it passes to Eddie Brock?",
"answ":"BELL",
"answ3":"CHURCH BELL",
"answ2":"Church bell.",
},
{
"cat":"Spider-Man",
"ques":"Name one of the two actors who played Curt Connors in the live-action Spider-Man films.",
"answ":"DYLAN BAKER",
"answ3":"RHYS IFANS",
"answ2":"Dylan Baker/Rhys Ifans.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Felicia Hardy in The Amazing Spider-Man 2?",
"answ":"FELICITY JONES",
"answ2":"Felicity Jones.",
},
{
"cat":"Spider-Man",
"ques":"Who directed The Amazing Spider-Man 2?",
"answ":"MARC WEBB",
"answ2":"Marc Webb.",
},
{
"cat":"Spider-Man",
"ques":"Who played Electro in The Amazing Spider-Man 2?",
"answ":"JAMIE FOXX",
"answ2":"Jamie Foxx.",
},
{
"cat":"Spider-Man",
"ques":"Who played Aunt May in The Amazing Spider-Man?",
"answ":"SALLY FIELD",
"answ2":"Sally Field.",
},
{
"cat":"Spider-Man",
"ques":"Who played Uncle Ben in The Amazing Spider-Man?",
"answ":"MARTIN SHEEN",
"answ2":"Martin Sheen.",
},
{
"cat":"Spider-Man",
"ques":"Who played Peter's father in The Amazing Spider-Man?",
"answ":"CAMPBELL SCOTT",
"answ2":"Campbell Scott.",
},
{
"cat":"Spider-Man",
"ques":"Which legendary comic and actress voices Aunt May in Spider-Man Into the Spider-Verse?",
"answ":"LILY TOMLIN",
"answ3":"LILLY TOMLIN",
"answ2":"Lily Tomlin.",
},
{
"cat":"Spider-Man",
"ques":"Who voices Spider-Man Noir in Spider-Man: Into The Spider-Verse?",
"answ":"NICHOLAS CAGE",
"answ3":"NICOLAS CAGE",
"answ2":"Nicolas Cage.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Gwen Stacy in Spider-Man 3?",
"answ":"BRYCE DALLAS HOWARD",
"answ2":"Bryce Dallas Howard.",
},
{
"cat":"Spider-Man",
"ques":"Who plays J. Jonah Jameson in the Sam Raimi Spider-Man films?",
"answ":"JK SIMMONS",
"answ3":"J K SIMMONS",
"answ2":"J.K. Simmons",
},
{
"cat":"Spider-Man",
"ques":"Who played the theater usher in Spider-Man 2?",
"answ":"BRUCE CAMPBELL",
"answ3":"BRUCE CAMBELL",
"answ2":"Bruce Campbell.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Harry Osborn in Sam Raimi's Spider-Man films?",
"answ":"JAMES FRANCO",
"answ2":"James Franco.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Eddie Brock in Spider-Man 3?",
"answ":"TOPHER GRACE",
"answ2":"Topher Grace.",
},
{
"cat":"Spider-Man",
"ques":"Who plays Captain George Stacy, Gwen's father in The Amazing Spider-Man?",
"answ":"DENIS LEARY",
"answ3":"DENNIS LEARY",
"answ2":"Denis Leary.",
},
{
"cat":"Spider-Man",
"ques":"In 2004's Spider-Man 2, what is the profession of John Jameson, son to J. Jonah Jameson?",
"answ":"ASTRONAUT",
"answ2":"Astronaut.",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 2, what does Harry Osborn want in exchange for giving Doc Ock tritium?",
"answ":"SPIDER MAN",
"answ3":"SPIDER MAN BROUGHT TO HIM",
"answ2":"Spider-Man brought to him.",
},
{
"cat":"Spider-Man",
"ques":"What did Peter Parker originally want to be called at the wrestling match in 2002's Spider-Man?",
"answ":"HUMAN SPIDER",
"answ3":"THE HUMAN SPIDER",
"answ2":"The Human Spider.",
},
{
"cat":"Spider-Man",
"ques":"In the Raimi Spider-Man films, what is the name of the newspaper editor that Peter Parker worked for as a photographer?",
"answ":"J JONAH JAMESON",
"answ2":"J. Jonah Jameson.",
},
{
"cat":"Spider-Man",
"ques":"What does Peter Parker want to buy from the prize money from the wrestling competition in Spider-Man?",
"answ":"CAR",
"answ3":"A CAR",
"answ2":"A car.",
},
];
var r2Q23 = [
{
"cat":"Spider-Man",
"ques":"Which actor played Flash Thompson in Sam Raimi's Spider-Man?",
"answ":"JOE MANGANIELLO",
"answ2":"Joe Manganiello.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Cliff Curtis</button><button id=corop class=buttons003 onclick=qcor()>Joe Manganiello</button><button id=incop3 class=buttons003 onclick=qinc()>Tony Revolori</button><button id=incop4 class=buttons003 onclick=qinc()>Adrien Brody</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 2, Dr. Otto Octavius is an expert in what field?",
"answ":"FUSION",
"answ2":"Fusion.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Nanotechnology</button><button id=corop class=buttons003 onclick=qcor()>Fusion</button><button id=incop3 class=buttons003 onclick=qinc()>Gene splicing</button><button id=incop4 class=buttons003 onclick=qinc()>Neurology</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played Captain Stacy in Spider-Man 3?",
"answ":"JAMES CROMWELL",
"answ2":"James Cromwell.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Denis Leary</button><button id=incop2 class=buttons003 onclick=qinc()>John Lithgow</button><button id=corop class=buttons003 onclick=qcor()>James Cromwell</button><button id=incop4 class=buttons003 onclick=qinc()>Thomas Hayden Church</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What actress was cast as Mary Jane Watson in The Amazing Spider-Man 2 but was ultimately cut from the film?",
"answ":"SHAILENE WOODLEY",
"answ2":"Shailene Woodley.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jessica Chastain</button><button id=incop2 class=buttons003 onclick=qinc()>Zoë Kravitz</button><button id=incop3 class=buttons003 onclick=qinc()>Kirsten Dunst</button><button id=corop class=buttons003 onclick=qcor()>Shailene Woodley</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In 2004's Spider-Man 2, what job does Peter get fired from because he's always late?",
"answ":"PIZZA DELIVERY MAN",
"answ3":"PIZZA DELIVERY",
"answ2":"Pizza Delivery.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pizza Delivery</button><button id=incop2 class=buttons003 onclick=qinc()>Librarian</button><button id=incop3 class=buttons003 onclick=qinc()>Ice Cream Vendor</button><button id=incop4 class=buttons003 onclick=qinc()>Waiter</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Sam Raimi's Spider-Man, which famous singer is performing during the parade scene?",
"answ":"MACY GRAY",
"answ2":"Macy Gray.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jennifer Hudson</button><button id=incop2 class=buttons003 onclick=qinc()>Beyoncé</button><button id=corop class=buttons003 onclick=qcor()>Macy Gray</button><button id=incop4 class=buttons003 onclick=qinc()>Kenny Rogers</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played Flint Marko aka Sandman in Spider-Man 3?",
"answ":"THOMAS HADEN CHURCH",
"answ3":"THOMAS HAYDEN CHURCH",
"answ2":"Thomas Haden Church.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Thomas Haden Church</button><button id=incop2 class=buttons003 onclick=qinc()>Topher Grace</button><button id=incop3 class=buttons003 onclick=qinc()>Alfred Molina</button><button id=incop4 class=buttons003 onclick=qinc()>Denis Leary</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played J. Jonah Jameson's receptionist, Miss Betty Brant, in Sam Raimi's Spider-Man films?",
"answ":"ELIZABETH BANKS",
"answ3":"ELISABETH BANKS",
"answ2":"Elizabeth Banks.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charlize Theron</button><button id=incop2 class=buttons003 onclick=qinc()>Emily Blunt</button><button id=corop class=buttons003 onclick=qcor()>Elizabeth Banks</button><button id=incop4 class=buttons003 onclick=qinc()>Jessica Chastain</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played scientist Alistair Smythe in The Amazing Spider-Man 2?",
"answ":"BJ NOVAK",
"answ2":"B.J. Novak.",
"option":"<button id=corop class=buttons003 onclick=qcor()>B.J. Novak</button><button id=incop2 class=buttons003 onclick=qinc()>Joseph Gordon-Levitt</button><button id=incop3 class=buttons003 onclick=qinc()>John Krasinski</button><button id=incop4 class=buttons003 onclick=qinc()>Dan Stevens</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played Doctor Curt Conners aka The Lizard in The Amazing Spider-Man?",
"answ":"RHYS IFANS",
"answ3":"RHYS EFANS",
"answ2":"Rhys Ifans.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jonathan Rhys Meyers</button><button id=corop class=buttons003 onclick=qcor()>Rhys Ifans</button><button id=incop3 class=buttons003 onclick=qinc()>Tim Roth</button><button id=incop4 class=buttons003 onclick=qinc()>Denis Leary</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played the Rhino in The Amazing Spider-Man 2?",
"answ":"PAUL GIAMATTI",
"answ2":"Paul Giamatti.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Leguizamo</button><button id=incop2 class=buttons003 onclick=qinc()>Vinnie Jones</button><button id=corop class=buttons003 onclick=qcor()>Paul Giamatti</button><button id=incop4 class=buttons003 onclick=qinc()>Jason Statham</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In the Sam Raimi Spider-Man film, what character became the Green Goblin?",
"answ":"NORMAN OSBORN",
"answ2":"Norman Osborn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Harry Osborn</button><button id=incop2 class=buttons003 onclick=qinc()>Bart Hamilton</button><button id=corop class=buttons003 onclick=qcor()>Norman Osborn</button><button id=incop4 class=buttons003 onclick=qinc()>Phil Urich</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played Aunt May in the Sam Raimi Spider-Man films?",
"answ":"ROSEMARY HARRIS",
"answ2":"Rosemary Harris.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Helen Mirren</button><button id=incop2 class=buttons003 onclick=qinc()>Marisa Tomei</button><button id=corop class=buttons003 onclick=qcor()>Rosemary Harris</button><button id=incop4 class=buttons003 onclick=qinc()>Geraldine James</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What University does Peter Parker attend in Spider-Man 2?",
"answ":"COLUMBIA UNIVERSITY",
"answ3":"COLUMBIA",
"answ2":"Columbia University.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>New York University</button><button id=incop2 class=buttons003 onclick=qinc()>Manhattan College</button><button id=corop class=buttons003 onclick=qcor()>Columbia University</button><button id=incop4 class=buttons003 onclick=qinc()>Rutgers University</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In The Amazing Spider-Man 2, what is the full real name of the man who becomes the supervillain Electro?",
"answ":"MAX DILLON",
"answ3":"MAXWELL DILLON",
"answ2":"Max Dillon.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Francis Frye</button><button id=incop2 class=buttons003 onclick=qinc()>Quentin Beck</button><button id=corop class=buttons003 onclick=qcor()>Max Dillon</button><button id=incop4 class=buttons003 onclick=qinc()>Mac Gargan</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In 2002's Spider-Man, what is the name of J. Jonah Jameson's secretary?",
"answ":"BETTY BRANT",
"answ3":"BETTY BRAND",
"answ2":"Betty Brant.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Liz Allan</button><button id=corop class=buttons003 onclick=qcor()>Betty Brant</button><button id=incop3 class=buttons003 onclick=qinc()>Jean DeWolff</button><button id=incop4 class=buttons003 onclick=qinc()>Sally Avril</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What was the name of the girl that Peter had a crush on in Spider-Man Homecoming?",
"answ":"LIZ",
"answ3":"LIZ TOOMES",
"answ2":"Liz.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Laura</button><button id=incop2 class=buttons003 onclick=qinc()>Emily</button><button id=corop class=buttons003 onclick=qcor()>Liz</button><button id=incop4 class=buttons003 onclick=qinc()>Amy</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What is the name of the man that owns the deli that Peter is regular at in Spider-Man Homecoming?",
"answ":"MR DELMAR",
"answ3":"DELMAR",
"answ2":"Mr Delmar.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mr Delmar</button><button id=incop2 class=buttons003 onclick=qinc()>Mr Harrington</button><button id=incop3 class=buttons003 onclick=qinc()>Mr Mason</button><button id=incop4 class=buttons003 onclick=qinc()>Mr Wilson</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What is Adrian's nickname for his daughter Liz in Spider-Man: Homecoming?",
"answ":"GUMDROP",
"answ3":"GUM DROP",
"answ2":"Gumdrop.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Gumdrop</button><button id=incop2 class=buttons003 onclick=qinc()>Kit Kat</button><button id=incop3 class=buttons003 onclick=qinc()>Jelly Bean</button><button id=incop4 class=buttons003 onclick=qinc()>Skittle</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Homecoming, the thug that was thrown off the ferry has a tattoo of what on his neck?",
"answ":"SCORPION",
"answ2":"Scorpion.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lizard</button><button id=incop2 class=buttons003 onclick=qinc()>Octopus</button><button id=corop class=buttons003 onclick=qcor()>Scorpion</button><button id=incop4 class=buttons003 onclick=qinc()>Lion</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who plays Dr. Ratha, a man at Oscorp trying to get Dr. Conners to save Norman Osborn, in The Amazing Spider-Man?",
"answ":"IRRFAN KHAN",
"answ3":"IRFAN KHAN",
"answ2":"Irrfan Khan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Erick Avari</button><button id=incop2 class=buttons003 onclick=qinc()>Ravi Patel</button><button id=corop class=buttons003 onclick=qcor()>Irrfan Khan</button><button id=incop4 class=buttons003 onclick=qinc()>Rishi Kapoor</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spiderman Homecoming, Ned discovers that Tony has placed a block on Peter's suit, limiting its capabilities. What is the name of the protocol?",
"answ":"TRAINING WHEELS PROTOCOL",
"answ2":"Training Wheels Protocol.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Baby Monitor Protocol</button><button id=corop class=buttons003 onclick=qcor()>Training Wheels Protocol</button><button id=incop3 class=buttons003 onclick=qinc()>Guardian Angel Protocol</button><button id=incop4 class=buttons003 onclick=qinc()>Big Brother Protocol</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Homecoming, what is the group that takes over the salvage and clean up of superhero battles and puts Toomes out of work?",
"answ":"DEPARTMENT OF DAMAGE CONTROL",
"answ2":"Department of Damage Control.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Department of Damage Recovery</button><button id=incop2 class=buttons003 onclick=qinc()>Department of Wreckage Control</button><button id=corop class=buttons003 onclick=qcor()>Department of Damage Control</button><button id=incop4 class=buttons003 onclick=qinc()>Department of Alien Control</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What was the first name of Otto Octavius' wife in Spider-Man 2?",
"answ":"ROSALIE",
"answ2":"Rosalie.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jane</button><button id=incop2 class=buttons003 onclick=qinc()>Sarah</button><button id=corop class=buttons003 onclick=qcor()>Rosalie</button><button id=incop4 class=buttons003 onclick=qinc()>Helen</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who plays the criminal Mac Gargan in Spider-Man: Homecoming?",
"answ":"MICHAEL MANDO",
"answ2":"Michael Mando.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Keaton</button><button id=corop class=buttons003 onclick=qcor()>Michael Mando</button><button id=incop3 class=buttons003 onclick=qinc()>Logan Marshall-Green</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Chernus</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Far From Home, what is the password to Happy's cellphone?",
"answ":"PASSWORD",
"answ2":"Password.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Happy</button><button id=incop2 class=buttons003 onclick=qinc()>Tony</button><button id=incop3 class=buttons003 onclick=qinc()>Cellphone</button><button id=corop class=buttons003 onclick=qcor()>Password</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Homecoming, when the Chitauri grenade explodes what famous DC landmark does Peter have to save his friends from?",
"answ":"WASHINGTON MONUMENT",
"answ3":"THE WASHINGTON MONUMENT",
"answ2":"Washington Monument.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Lincoln Memorial</button><button id=corop class=buttons003 onclick=qcor()>Washington Monument</button><button id=incop3 class=buttons003 onclick=qinc()>White House</button><button id=incop4 class=buttons003 onclick=qinc()>Union Station</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played the Green Goblin in The Amazing Spider-Man 2?",
"answ":"DANE DEHAAN",
"answ2":"Dane DeHaan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Marsden</button><button id=incop2 class=buttons003 onclick=qinc()>James Franco</button><button id=corop class=buttons003 onclick=qcor()>Dane DeHaan</button><button id=incop4 class=buttons003 onclick=qinc()>Willem Dafoe</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 3, what is the first name of Sandman's daughter?",
"answ":"PENNY",
"answ2":"Penny.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alison</button><button id=incop2 class=buttons003 onclick=qinc()>Susan</button><button id=corop class=buttons003 onclick=qcor()>Penny</button><button id=incop4 class=buttons003 onclick=qinc()>Jane</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What element was the power source for Doc Ock's machine in Spider-Man 2?",
"answ":"TRITIUM",
"answ2":"Tritium.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Plutonium</button><button id=incop2 class=buttons003 onclick=qinc()>Helium</button><button id=corop class=buttons003 onclick=qcor()>Tritium</button><button id=incop4 class=buttons003 onclick=qinc()>Radium</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who played Uncle Ben in the Sam Raimi Spider-Man films?",
"answ":"CLIFF ROBERTSON",
"answ2":"Cliff Robertson.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Cliff Robertson</button><button id=incop2 class=buttons003 onclick=qinc()>John Slattery</button><button id=incop3 class=buttons003 onclick=qinc()>Donald Sutherland</button><button id=incop4 class=buttons003 onclick=qinc()>Martin Sheen</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, after Mysterio tricked Spider-Man into stepping in front of a train, Peter woke up in a prison cell in what country?",
"answ":"THE NETHERLANDS",
"answ3":"HOLLAND",
"answ2":"The Netherlands/Holland.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Netherlands</button><button id=incop2 class=buttons003 onclick=qinc()>Belgium</button><button id=incop3 class=buttons003 onclick=qinc()>Germany</button><button id=incop4 class=buttons003 onclick=qinc()>France</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, what city does the Fire Elemental attack in?",
"answ":"PRAGUE",
"answ2":"Prague.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Prague</button><button id=incop2 class=buttons003 onclick=qinc()>Berlin</button><button id=incop3 class=buttons003 onclick=qinc()>Amsterdam</button><button id=incop4 class=buttons003 onclick=qinc()>Paris</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man Homecoming, what name does Peter give to the computerized voice in his upgraded suit?",
"answ":"KAREN",
"answ2":"Karen.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Karen</button><button id=incop2 class=buttons003 onclick=qinc()>Kate</button><button id=incop3 class=buttons003 onclick=qinc()>Linda</button><button id=incop4 class=buttons003 onclick=qinc()>Carrie</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Which actress plays the role of Peter Parker's mother Mary Parker in The Amazing Spider-Man?",
"answ":"EMBETH DAVIDTZ",
"answ3":"EMBETH DAVIDZ",
"answ2":"Embeth Davidtz.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Embeth Davidtz</button><button id=incop2 class=buttons003 onclick=qinc()>Kelsey Asbille</button><button id=incop3 class=buttons003 onclick=qinc()>Kari Coleman</button><button id=incop4 class=buttons003 onclick=qinc()>Hannah Marks</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Lucy Lawless, Sara Ramirez and Octavia Spencer have cameos in which Spider-Man film?",
"answ":"SPIDER MAN",
"answ2":"Spider-Man.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Spider-Man</button><button id=incop2 class=buttons003 onclick=qinc()>Spider-Man 2</button><button id=incop3 class=buttons003 onclick=qinc()>Spider-Man 3</button><button id=incop4 class=buttons003 onclick=qinc()>The Amazing Spider-Man</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Which Spider-Man villain said the following line: 'Join me! Imagine what we could accomplish together... what we could create. Or we could destroy.'?",
"answ":"GREEN GOBLIN",
"answ3":"THE GREEN GOBLIN",
"answ2":"The Green Goblin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Green Goblin</button><button id=incop2 class=buttons003 onclick=qinc()>Sandman</button><button id=incop3 class=buttons003 onclick=qinc()>Doctor Octopus</button><button id=incop4 class=buttons003 onclick=qinc()>Vulture</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Which film features the line: 'That person who helps others simply because it should or must be done, and because it is the right thing to do, is indeed without a doubt, a real supehero'?",
"answ":"SPIDER MAN INTO THE SPIDER VERSE",
"answ2":"Spider-Man: Into the Spider-Verse.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Spider-Man: Into the Spider-Verse</button><button id=incop2 class=buttons003 onclick=qinc()>Spider-Man</button><button id=incop3 class=buttons003 onclick=qinc()>Spider-Man Homecoming</button><button id=incop4 class=buttons003 onclick=qinc()>Spider-Man 3</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"At the end of Spiderman 2, MJ runs away from what event to go see Peter?",
"answ":"WEDDING",
"answ3":"HER WEDDING",
"answ2":"Her wedding.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Her wedding</button><button id=incop2 class=buttons003 onclick=qinc()>Concert</button><button id=incop3 class=buttons003 onclick=qinc()>Her birthday</button><button id=incop4 class=buttons003 onclick=qinc()>Football match</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, Ned tries to get Betty to switch seats with Peter on the plane by saying Peter is allergic to what?",
"answ":"PERFUME",
"answ2":"Perfume.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Perfume</button><button id=incop2 class=buttons003 onclick=qinc()>Nuts</button><button id=incop3 class=buttons003 onclick=qinc()>Baby powder</button><button id=incop4 class=buttons003 onclick=qinc()>Cheese</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Homecoming, Peter tells Happy about how he helped a lady that day. What food item did the lady buy Peter in return?",
"answ":"CHURRO",
"answ2":"Churro.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Churro</button><button id=incop2 class=buttons003 onclick=qinc()>Donut</button><button id=incop3 class=buttons003 onclick=qinc()>Bagel</button><button id=incop4 class=buttons003 onclick=qinc()>Hotdog</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In 2002's Spider-Man, what DC superhero's name does Peter say while testing out his webs on the rooftop?",
"answ":"SHAZAM",
"answ2":"Shazam.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Shazam</button><button id=incop2 class=buttons003 onclick=qinc()>Superman</button><button id=incop3 class=buttons003 onclick=qinc()>Batman</button><button id=incop4 class=buttons003 onclick=qinc()>Cyborg</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What profession does MJ's new boyfriend John Jameson have in Spider-Man 2?",
"answ":"ASTRONAUT",
"answ2":"Astronaut.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Astronaut</button><button id=incop2 class=buttons003 onclick=qinc()>Model</button><button id=incop3 class=buttons003 onclick=qinc()>Doctor</button><button id=incop4 class=buttons003 onclick=qinc()>Firefighter</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In The Amazing Spider-Man, after getting his powers, Peter taunts Flash while he's participating in what sport?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Basketball</button><button id=incop2 class=buttons003 onclick=qinc()>Baseball</button><button id=incop3 class=buttons003 onclick=qinc()>Football</button><button id=incop4 class=buttons003 onclick=qinc()>Ice hockey</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Homecoming, where does Peter tell Tony he is, when he is actually on the Staten Island Ferry?",
"answ":"BAND PRACTICE",
"answ3":"AT BAND PRACTICE",
"answ2":"Band practice.",
"option":"<button id=corop class=buttons003 onclick=qcor()>At band practice</button><button id=incop2 class=buttons003 onclick=qinc()>At home</button><button id=incop3 class=buttons003 onclick=qinc()>At Ned's house</button><button id=incop4 class=buttons003 onclick=qinc()>In the supermarket</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What does Aunt May call the Spider-Sense in Spider-Man: Far From Home?",
"answ":"PETER TINGLE",
"answ2":"Peter Tingle.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Peter Tingle</button><button id=incop2 class=buttons003 onclick=qinc()>Spider Smell</button><button id=incop3 class=buttons003 onclick=qinc()>Special Feeling</button><button id=incop4 class=buttons003 onclick=qinc()>Super Sense</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who voiced Wilson Fisk in Spider-Man: Into the Spider-Verse?",
"answ":"LIEV SCHREIBER",
"answ2":"Liev Schreiber.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Liev Schreiber</button><button id=incop2 class=buttons003 onclick=qinc()>Hugh Jackman</button><button id=incop3 class=buttons003 onclick=qinc()>Hugo Weaving</button><button id=incop4 class=buttons003 onclick=qinc()>James Woods</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who voiced Mary Jane Watson in Spider-Man: Into the Spider-Verse?",
"answ":"ZOE KRAVITZ",
"answ2":"Zoe Kravitz.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Zoe Kravitz</button><button id=incop2 class=buttons003 onclick=qinc()>Amy Adams</button><button id=incop3 class=buttons003 onclick=qinc()>Alison Brie</button><button id=incop4 class=buttons003 onclick=qinc()>Emma Stone</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Stan Lee has a cameo in which Spider-Man film, in which he tells Peter Parker that one person CAN make a difference?",
"answ":"SPIDER MAN 3",
"answ3":"SPIDER MAN III",
"answ2":"Spider-Man 3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Spider-Man</button><button id=incop2 class=buttons003 onclick=qinc()>Spider-Man 2</button><button id=corop class=buttons003 onclick=qcor()>Spider-Man 3</button><button id=incop4 class=buttons003 onclick=qinc()>The Amazing Spider-Man</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man, how much is the payout if you survive 3 minutes in the wrestling ring?",
"answ":"3000",
"answ3":"3 000",
"answ2":"$3,000.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>$1,000</button><button id=incop2 class=buttons003 onclick=qinc()>$2,000</button><button id=corop class=buttons003 onclick=qcor()>$3,000</button><button id=incop4 class=buttons003 onclick=qinc()>$4,000</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, what is the name of the classmate who tries to compete with Peter for MJ's affection?",
"answ":"BRAD",
"answ3":"BRAD DAVIS",
"answ2":"Brad.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Flash</button><button id=incop2 class=buttons003 onclick=qinc()>Sean</button><button id=corop class=buttons003 onclick=qcor()>Brad</button><button id=incop4 class=buttons003 onclick=qinc()>Ryan</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In 2002's Spider-Man, what food item was Peter supposed to bring to Thanksgiving?",
"answ":"CRANBERRIES",
"answ2":"Cranberries.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Soup</button><button id=incop2 class=buttons003 onclick=qinc()>Muffins</button><button id=corop class=buttons003 onclick=qcor()>Cranberries</button><button id=incop4 class=buttons003 onclick=qinc()>Potatoes</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In 2002's Spider-Man, what does Norman bring as a gift for Thanksgiving?",
"answ":"FRUITCAKE",
"answ2":"Fruitcake.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Turkey</button><button id=incop2 class=buttons003 onclick=qinc()>Cranberry sauce</button><button id=corop class=buttons003 onclick=qcor()>Fruitcake</button><button id=incop4 class=buttons003 onclick=qinc()>Stuffing</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Which Spider-Man film features supporting performances from Theresa Russell, James Cromwell and Becky Ann Baker?",
"answ":"SPIDER MAN 3",
"answ3":"SPIDER MAN III",
"answ2":"Spider-Man 3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Amazing Spider-Man</button><button id=incop2 class=buttons003 onclick=qinc()>The Amazing Spider-Man 2</button><button id=corop class=buttons003 onclick=qcor()>Spider-Man 3</button><button id=incop4 class=buttons003 onclick=qinc()>Spider-Man 2</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 3, once Harry comes home after his accident, what present does Peter give Harry as a homecoming gift?",
"answ":"BASKETBALL",
"answ2":"Basketball.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scooter</button><button id=incop2 class=buttons003 onclick=qinc()>Helmet</button><button id=corop class=buttons003 onclick=qcor()>Basketball</button><button id=incop4 class=buttons003 onclick=qinc()>Camera</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Who plays Liz in Spider-Man: Homecoming?",
"answ":"LAURA HARRIER",
"answ2":"Laura Harrier.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Tiffany Espensen</button><button id=incop2 class=buttons003 onclick=qinc()>Zendaya</button><button id=corop class=buttons003 onclick=qcor()>Laura Harrier</button><button id=incop4 class=buttons003 onclick=qinc()>Angourie Rice</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man 3, J. Jonah Jameson has to take pills and try and keep himself calm due to what?",
"answ":"HIGH BLOOD PRESSURE",
"answ3":"HYPERTENSION",
"answ2":"High blood pressure.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Anxiety attacks</button><button id=incop2 class=buttons003 onclick=qinc()>Cholesterol</button><button id=corop class=buttons003 onclick=qcor()>High blood pressure</button><button id=incop4 class=buttons003 onclick=qinc()>Anger Management</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What newspaper does Peter Porker say he works for in his narration of Spider-Man Into the Spider-Verse?",
"answ":"THE DAILY BEAGLE",
"answ3":"DAILY BEAGLE",
"answ2":"Daily Beagle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Daily Big</button><button id=incop2 class=buttons003 onclick=qinc()>Daily Bugle</button><button id=corop class=buttons003 onclick=qcor()>Daily Beagle</button><button id=incop4 class=buttons003 onclick=qinc()>Daily Ham</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"What radioactive material was stolen from OsCorp at the beginning of The Amazing Spider-Man 2?",
"answ":"PLUTONIUM",
"answ2":"Plutonium.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Uranium</button><button id=incop2 class=buttons003 onclick=qinc()>Radium</button><button id=corop class=buttons003 onclick=qcor()>Plutonium</button><button id=incop4 class=buttons003 onclick=qinc()>Astatine</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Into the Spider-Verse, what is the name of the lab where Olivia Octavius is head scientist?",
"answ":"ALCHEMAX",
"answ2":"Alchemax.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Oscorp</button><button id=incop2 class=buttons003 onclick=qinc()>Roxxon</button><button id=corop class=buttons003 onclick=qcor()>Alchemax</button><button id=incop4 class=buttons003 onclick=qinc()>AccuTech</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In The Amazing Spider-Man 2, Norman Osborn sent his son off to boarding school at what age?",
"answ":"11",
"answ3":"ELEVEN",
"answ2":"11.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>13</button><button id=incop2 class=buttons003 onclick=qinc()>10</button><button id=corop class=buttons003 onclick=qcor()>11</button><button id=incop4 class=buttons003 onclick=qinc()>9</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In Spider-Man: Far From Home, Peter wants to buy MJ what type of necklace?",
"answ":"BLACK DAHLIA",
"answ2":"Black Dahlia.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blue Orchid</button><button id=incop2 class=buttons003 onclick=qinc()>Red Daisy</button><button id=corop class=buttons003 onclick=qcor()>Black Dahlia</button><button id=incop4 class=buttons003 onclick=qinc()>Green Lilly</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"In which film does Peter Parker say: 'Sometimes to do what's right, we must be steady, and give up the things we desire the most...even our dreams'?",
"answ":"SPIDER MAN II",
"answ3":"SPIDER MAN 2",
"answ2":"Spider-Man 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Amazing Spider-Man 2</button><button id=incop2 class=buttons003 onclick=qinc()>Spider-Man</button><button id=corop class=buttons003 onclick=qcor()>Spider-Man 2</button><button id=incop4 class=buttons003 onclick=qinc()>Spider-Man 3</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"To date, how many times has J.K. Simmons played the role of J. Jonah Jameson on the big screen?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=incop2 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Spider-Man",
"ques":"Which Spider-Man film villain says the line: 'I'm not a bad person. Just had bad luck.'?",
"answ":"SANDMAN",
"answ3":"THE SANDMAN",
"answ2":"Sandman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Norman Osborn</button><button id=incop2 class=buttons003 onclick=qinc()>Elektro</button><button id=corop class=buttons003 onclick=qcor()>Sandman</button><button id=incop4 class=buttons003 onclick=qinc()>Doctor Octopus</button><br/>",
},
];
spiderman = shuffle(spiderman);
r2Q23 = shuffle(r2Q23);