var heroesvillains = [
{
"cat":"Heroes & Villains",
"ques":"Which villain from a swashbuckling franchise says the line: 'Life is cruel. Why should the afterlife be any different'?",
"answ":"DAVY JONES",
"answ2":"Davy Jones.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Narcissa Malfoy in the Harry Potter franchise?",
"answ":"HELEN MCCRORY",
"answ2":"Helen McCrory.",
},
{
"cat":"Heroes & Villains",
"ques":"In R.I.P.D. the Deados can be easily discovered because of their strong hate of what type of food?",
"answ":"INDIAN",
"answ3":"INDIAN FOOD",
"answ2":"Indian food.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Captain Amazing in the 90s action comedy Mystery Men?",
"answ":"GREG KINNEAR",
"answ2":"Greg Kinnear.",
},
{
"cat":"Heroes & Villains",
"ques":"In The Lord of The Rings, at the entrance to Moria, who realized the answer to the riddle was in Elvish?",
"answ":"FRODO",
"answ2":"Frodo.",
},
{
"cat":"Heroes & Villains",
"ques":"What comic book movie features the villain Neville Sinclair, a Hollywood movie star who is secretly a Nazi agent?",
"answ":"THE ROCKETEER",
"answ2":"The Rocketeer.",
},
{
"cat":"Heroes & Villains",
"ques":"What was the first Marvel comics superhero that Chris Evans portrayed?",
"answ":"JOHNNY STORM",
"answ3":"HUMAN TORCH",
"answ2":"Johnny Storm/Human Torch.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the role of Madmartigan, a boastful immured mercenary swordsman who helps Willow on his quest, in Willow?",
"answ":"VAL KILMER",
"answ2":"Val Kilmer.",
},
{
"cat":"Heroes & Villains",
"ques":"What superhero has his base of operations on the island of Bangalla?",
"answ":"THE PHANTOM",
"answ2":"The Phantom.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the villainous navy captain Artemisia, in 300: Rise of an Empire?",
"answ":"EVA GREEN",
"answ2":"Eva Green.",
},
{
"cat":"Heroes & Villains",
"ques":"Which villain disguises himself as Commodore Schmidlapp to infiltrate the Batcave in Batman '66?",
"answ":"THE PENGUIN",
"answ3":"PENGUIN",
"answ2":"The Penguin.",
},
{
"cat":"Heroes & Villains",
"ques":"What is Loki the God of in the MCU?",
"answ":"MISCHIEF",
"answ3":"GOD OF MISCHIEF",
"answ2":"Mischief.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the young and villainous Chris D'Amico in the Kick-Ass films?",
"answ":"CHRISTOPHER MINTZ PLASSE",
"answ3":"CHRISTOPHER MINTS PLASSE",
"answ2":"Christopher Mintz-Plasse.",
},
{
"cat":"Heroes & Villains",
"ques":"Which DC villain does a magic trick where he makes a pencil disappear?",
"answ":"THE JOKER",
"answ3":"JOKER",
"answ2":"The Joker.",
},
{
"cat":"Heroes & Villains",
"ques":"What is Hela the goddess of in Thor: Ragnarok?",
"answ":"DEATH",
"answ2":"Death.",
},
{
"cat":"Heroes & Villains",
"ques":"In RED, who plays William Cooper, a CIA agent tasked with hunting down and killing Frank Moses?",
"answ":"KARL URBAN",
"answ2":"Karl Urban.",
},
{
"cat":"Heroes & Villains",
"ques":"What hero identity has been taken up by characters named Don Diego De La Vega and Alejandro Murrieta?",
"answ":"ZORRO",
"answ2":"Zorro.",
},
{
"cat":"Heroes & Villains",
"ques":"Who voices the evil Parallax in Green Lantern?",
"answ":"CLANCY BROWN",
"answ2":"Clancy Brown .",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Maria Rambeau in Captain Marvel?",
"answ":"LASHANA LYNCH",
"answ2":"Lashana Lynch.",
},
{
"cat":"Heroes & Villains",
"ques":"What film has villains named Balthazar, Mammon, Gabriel and Lucifer?",
"answ":"CONSTANTINE",
"answ2":"Constantine.",
},
{
"cat":"Heroes & Villains",
"ques":"William Fichtner plays a villain named Eric Sacks in what 2014 comic book movie?",
"answ":"TEENAGE MUTANT NINJA TURTLES",
"answ2":"Teenage Mutant Ninja Turtles.",
},
{
"cat":"Heroes & Villains",
"ques":"What heroic character has been played by Danny Woodburn, Tony Shalhoub and Kevin Clash across numerous comic book movies?",
"answ":"SPLINTER",
"answ3":"MASTER SPLINTER",
"answ2":"Splinter.",
},
{
"cat":"Heroes & Villains",
"ques":"What kind of weapon does Steel mainly use in Steel?",
"answ":"HAMMER",
"answ3":"SLEDGE HAMMER",
"answ2":"Hammer.",
},
{
"cat":"Heroes & Villains",
"ques":"What is the weapon of choice of William H. Macy's character in Mystery Men?",
"answ":"SHOVEL",
"answ2":"Shovel.",
},
{
"cat":"Heroes & Villains",
"ques":"In Mystery Men, who plays the villain Casanova Frankenstein?",
"answ":"GEOFFREY RUSH",
"answ2":"Geoffrey Rush.",
},
{
"cat":"Heroes & Villains",
"ques":"What is the real name of the man who becomes The Crow in The Crow?",
"answ":"ERIC DRAVEN",
"answ2":"Eric Draven.",
},
{
"cat":"Heroes & Villains",
"ques":"What movies features the heroic characters named King Balor, Princess Nuala and Trevor Bruttenholm?",
"answ":"HELLBOY II THE GOLDEN ARMY",
"answ3":"HELLBOY 2 THE GOLDEN ARMY",
"answ2":"Hellboy II: The Golden Army.",
},
{
"cat":"Heroes & Villains",
"ques":"In Guardians of the Galaxy Vol. 2, Yondu refers to Rocket Raccoon as what other type of animal?",
"answ":"RAT",
"answ2":"Rat.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Selena, in 1984's Supergirl?",
"answ":"FAYE DUNAWAY",
"answ2":"Faye Dunaway.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played corrupt police officer Bobby Hayes in R.I.P.D.?",
"answ":"KEVIN BACON",
"answ2":"Kevin Bacon.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Dr. Walter Jenning in Howard the Duck?",
"answ":"JEFFREY JONES",
"answ2":"Jeffrey Jones.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Kesslee in Tank Girl?",
"answ":"MALCOLM MCDOWELL",
"answ2":"Malcolm McDowell.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Jet Girl in 1995's Tank Girl?",
"answ":"NAOMI WATTS",
"answ2":"Naomi Watts.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Judge Dredd in 2012's Dredd?",
"answ":"KARL URBAN",
"answ3":"CARL URBAN",
"answ2":"Karl Urban.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Judge Dredd in 1995's Judge Dredd?",
"answ":"SYLVESTER STALLONE",
"answ2":"Sylvester Stallone.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the titular character in The Spirit?",
"answ":"GABRIEL MACHT",
"answ2":"Gabriel Macht.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Richmond Valentine in Kingsman: The Secret Service?",
"answ":"SAMUEL L JACKSON",
"answ3":"SAM JACKSON",
"answ2":"Samuel L. Jackson.",
},
{
"cat":"Heroes & Villains",
"ques":"By what legendary name did Mark Strong's character go by in Kingsman The Secret Service?",
"answ":"MERLIN",
"answ2":"Merlin.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Poppy in Kingsman: The Golden Circle?",
"answ":"JULIANNE MOORE",
"answ2":"Julianne Moore.",
},
{
"cat":"Heroes & Villains",
"ques":"In Kingsman: The Golden Circle, who plays the head of the Statesman, Champagne a.k.a. Champ?",
"answ":"JEFF BRIDGES",
"answ2":"Jeff Bridges.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Merlin in Kingsman: The Secret Service?",
"answ":"MARK STRONG",
"answ2":"Mark Strong.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the titular character in The Rocketeer?",
"answ":"BILLY CAMPBELL",
"answ3":"BILLY CAMBELL",
"answ2":"Billy Campbell.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Hit-Girl in the Kick-Ass films?",
"answ":"CHLOE GRACE MORETZ",
"answ2":"Chloë Grace Moretz.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Big Daddy in 2010's Kick-Ass?",
"answ":"NICOLAS CAGE",
"answ3":"NICHOLAS CAGE",
"answ2":"Nicolas Cage.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the lead character, Themistokles, in 300: Rise of an Empire?",
"answ":"SULLIVAN STAPLETON",
"answ2":"Sullivan Stapleton.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Queen Gorgo, in 300: Rise of an Empire?",
"answ":"LENA HEADEY",
"answ2":"Lena Headey.",
},
{
"cat":"Heroes & Villains",
"ques":"Who voiced Frozone in The Incredibles?",
"answ":"SAMUEL L JACKSON",
"answ2":"Samuel L. Jackson.",
},
{
"cat":"Heroes & Villains",
"ques":"Who voiced Elastigirl in The Incredibles?",
"answ":"HOLLY HUNTER",
"answ2":"Holly Hunter.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Emperor Ming the Merciless in 1980's Flash Gordon?",
"answ":"MAX VON SYDOW",
"answ2":"Max von Sydow.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Flash Gordon in 1980's Flash Gordon?",
"answ":"SAM J JONES",
"answ3":"SAM JONES",
"answ2":"Sam J. Jones.",
},
{
"cat":"Heroes & Villains",
"ques":"In Flash Gordon, what football team does Flash play for?",
"answ":"NEW YORK JETS",
"answ3":"JETS",
"answ2":"New York Jets.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays David Dunn in Unbreakable?",
"answ":"BRUCE WILLIS",
"answ2":"Bruce Willis.",
},
{
"cat":"Heroes & Villains",
"ques":"Samuel L. Jackson goes by the name of Mr. Glass in 2000's Unbreakable. What is his real name?",
"answ":"ELIJAH PRICE",
"answ2":"Elijah Price.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Peyton Westlake, a brilliant scientist who was left for dead and burned alive in 1990's Darkman?",
"answ":"LIAM NEESON",
"answ2":"Liam Neeson.",
},
{
"cat":"Heroes & Villains",
"ques":"What 1991 film features the hero saying the line: 'What's it like working for a Nazi, Eddie? Does he pay you in dollars or Deutschmarks'?",
"answ":"THE ROCKETEER",
"answ2":"The Rocketeer.",
},
{
"cat":"Heroes & Villains",
"ques":"Which DC villain says: 'Prison is a creepy place, Kitty, and one needs to make creepy friends in order to survive.'?",
"answ":"LEX LUTHOR",
"answ2":"Lex Luthor.",
},
{
"cat":"Heroes & Villains",
"ques":"What Marvel character can be heard saying: 'This is not vengeance. Revenge is not a valid motive, it's an emotional response.'?",
"answ":"THE PUNISHER",
"answ3":"PUNISHER",
"answ2":"The Punisher.",
},
{
"cat":"Heroes & Villains",
"ques":"You'll find the villainous Prince Nuada Silverlance in what 2008 comic book film?",
"answ":"HELLBOY II THE GOLDEN ARMY",
"answ3":"HELLBOY 2 THE GOLDEN ARMY",
"answ2":"Hellboy II: The Golden Army.",
},
{
"cat":"Heroes & Villains",
"ques":"Who stars as Lamont Cranston, also known as The Shadow, in 1994's The Shadow?",
"answ":"ALEC BALDWIN",
"answ2":"Alec Baldwin.",
},
{
"cat":"Heroes & Villains",
"ques":"In how many films in the X-Men franchise did Michael Fassbender appear as Magneto?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4. (First Class/Days of Future Past/Apocalypse/Dark Phoenix)",
},
{
"cat":"Heroes & Villains",
"ques":"What film has superhero characters named Go-Go, Wasabi and Honey Lemon?",
"answ":"BIG HERO 6",
"answ3":"BIG HERO SIX",
"answ2":"Big Hero 6.",
},
{
"cat":"Heroes & Villains",
"ques":"You'll find the characters of Allan Quatermain, Tom Sawyer and Dorian Gray in what 2003 comic film?",
"answ":"THE LEAGUE OF EXTRAORDINARY GENTLEMEN",
"answ3":"LEAGUE OF EXTRAORDINARY GENTLEMEN",
"answ2":"The League of Extraordinary Gentlemen.",
},
{
"cat":"Heroes & Villains",
"ques":"How many actors have portrayed Lex Luthor in live action on the silver screen since 1978?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
},
{
"cat":"Heroes & Villains",
"ques":"In the comic based Bulletproof Monk, who plays the nameless monk?",
"answ":"CHOW YUN FAT",
"answ2":"Chow Yun-fat.",
},
{
"cat":"Heroes & Villains",
"ques":"Which Marvel film features the villains Tombstone and The Prowler?",
"answ":"SPIDER MAN INTO THE SPIDER VERSE",
"answ2":"Spider-Man: Into the Spider-Verse.",
},
{
"cat":"Heroes & Villains",
"ques":"In 2005's Constantine, Djimon Hounsou plays what character?",
"answ":"PAPA MIDNITE",
"answ3":"PAPA MIDNIGHT",
"answ2":"Papa Midnite.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Colonel Stars & Stripes in Kick-Ass 2?",
"answ":"JIM CARREY",
"answ2":"Jim Carrey.",
},
{
"cat":"Heroes & Villains",
"ques":"In what 2014 comic book film does Joseph Gordon Levitt play a gambler named Johnny?",
"answ":"SIN CITY A DAME TO KILL FOR",
"answ2":"Sin City: A Dame to Kill For.",
},
{
"cat":"Heroes & Villains",
"ques":"What is the real first name of Sabretooth in the X-Men series?",
"answ":"VICTOR",
"answ3":"VIKTOR",
"answ2":"Victor.",
},
{
"cat":"Heroes & Villains",
"ques":"In 2019's Hellboy, who plays Hellboys's adoptive father and founder of the BPRD, Trevor Bruttenholm?",
"answ":"IAN MCSHANE",
"answ2":"Ian McShane.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Hellboy in 2019's Hellboy?",
"answ":"DAVID HARBOUR",
"answ2":"David Harbour.",
},
{
"cat":"Heroes & Villains",
"ques":"What U.S. city was Erik Killmonger from?",
"answ":"OAKLAND",
"answ2":"Oakland.",
},
{
"cat":"Heroes & Villains",
"ques":"What branch of the military does James 'Rhodey' Rhodes serve in the MCU?",
"answ":"AIR FORCE",
"answ3":"UNITED STATES AIR FORCE",
"answ2":"Air Force.",
},
{
"cat":"Heroes & Villains",
"ques":"Who does Doc steal the plutonium from in Back to the Future?",
"answ":"LIBYANS",
"answ3":"THE LIBYANS",
"answ2":"The Libyans.",
},
{
"cat":"Heroes & Villains",
"ques":"Name the MCU villain played by Lee Pace.",
"answ":"RONAN",
"answ3":"RONAN THE ACCUSER",
"answ2":"Ronan the Accuser.",
},
{
"cat":"Heroes & Villains",
"ques":"In Watchmen, which member of the Watchmen team has the real name Jon Osterman?",
"answ":"DR MANHATTAN",
"answ3":"DOCTOR MANHATTAN",
"answ2":"Dr. Manhattan.",
},
{
"cat":"Heroes & Villains",
"ques":"True of False: Anne Hathaway is never identified as Catwoman in The Dark Knight Rises?",
"answ":"TRUE",
"answ2":"True.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays former wetwork agent Victoria Winslow in 2010's RED?",
"answ":"HELEN MIRREN",
"answ2":"Helen Mirren.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays former CIA agent Frank Moses in 2010's RED?",
"answ":"BRUCE WILLIS",
"answ2":"Bruce Willis.",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of the aquatic empath from the Ron Perlman Hellboy films?",
"answ":"ABE SAPIEN",
"answ3":"ABRAHAM SAPIEN",
"answ2":"Abe Sapien.",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of the monstrous creature that Hulk fights at the end of the Incredible Hulk?",
"answ":"ABOMINATION",
"answ3":"THE ABOMINATION",
"answ2":"Abomination.",
},
{
"cat":"Heroes & Villains",
"ques":"In Kingsman: The Secret Service, Eggsy names his pet training pug after what fictional character from TV?",
"answ":"JACK BAUER",
"answ2":"Jack Bauer.",
},
{
"cat":"Heroes & Villains",
"ques":"In The Dark Knight Rises, what does Selina Kyle steal from Bruce upon their first meeting?",
"answ":"PEARL NECKLACE",
"answ3":"MOTHER'S PEARLS",
"answ2":"Pearl necklace.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Red Sonja in 1985's Red Sonja?",
"answ":"BRIGITTE NIELSEN",
"answ3":"BIRGITTE NIELSEN",
"answ2":"Brigitte Nielsen.",
},
{
"cat":"Heroes & Villains",
"ques":"Who stars as Eric Draven in 1994's The Crow?",
"answ":"BRANDON LEE",
"answ2":"Brandon Lee.",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays ruthless mob boss Frank D'Amico, in Kick-Ass?",
"answ":"MARK STRONG",
"answ2":"Mark Strong.",
},
{
"cat":"Heroes & Villains",
"ques":"In which film does Indiana Jones say: 'Nazis. I hate these guys.'?",
"answ":"INDIANA JONES AND THE LAST CRUSADE",
"answ3":"THE LAST CRUSADE",
"answ2":"Indiana Jones and the Last Crusade.",
},
{
"cat":"Heroes & Villains",
"ques":"Who played Spawn in 1997's Spawn?",
"answ":"MICHAEL JAI WHITE",
"answ3":"MICHAEL JAY WHITE",
"answ2":"Michael Jai White.",
},
{
"cat":"Heroes & Villains",
"ques":"In how many MCU films does Loki make an appearance?",
"answ":"6",
"answ3":"SIX",
"answ2":"6. (Thor/The Avengers/Thor: The Dark World/Thor Ragnarok/Infinity War/Endgame)",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays mercenary and bounty Barb Wire in the film Barb Wire?",
"answ":"PAMELA ANDERSON",
"answ2":"Pamela Anderson.",
},
{
"cat":"Heroes & Villains",
"ques":"What Star Wars actor played Axel in the film Barb Wire?",
"answ":"TEMUERA MORRISON",
"answ2":"Temuera Morrison.",
},
];
var r2Q8 = [
{
"cat":"Heroes & Villains",
"ques":"In the Star Wars movie timeline, who was the first Jedi to learn how to return from death as a force ghost?",
"answ":"QUI GON JINN",
"answ3":"QUI GON",
"answ2":"Qui-Gon Jinn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mace Windu</button><button id=incop2 class=buttons003 onclick=qinc()>Yoda</button><button id=incop3 class=buttons003 onclick=qinc()>Obi-Wan Kenobi</button><button id=corop class=buttons003 onclick=qcor()>Qui-Gon Jinn</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Return of the King, what character kills the Witch-king of Angmar by stabbing him in the head?",
"answ":"EOWYN",
"answ2":"Éowyn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Merry</button><button id=incop2 class=buttons003 onclick=qinc()>Faramir</button><button id=incop3 class=buttons003 onclick=qinc()>Aragorn</button><button id=corop class=buttons003 onclick=qcor()>Éowyn</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who killed Frigga, Thor's mother in Thor The Dark World?",
"answ":"ALGRIM",
"answ2":"Algrim.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Algrim</button><button id=incop2 class=buttons003 onclick=qinc()>Jane Foster</button><button id=incop3 class=buttons003 onclick=qinc()>Loki</button><button id=incop4 class=buttons003 onclick=qinc()>Malekith</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Indiana Jones and The Last Crusade, what is Indy's reply when his father remarks: 'I didn't know you could fly a plane'?",
"answ":"FLY YES LAND NO",
"answ2":"Fly yes. Land no.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Depends what you mean by fly</button><button id=incop2 class=buttons003 onclick=qinc()>Me neither</button><button id=incop3 class=buttons003 onclick=qinc()>It's never too late to learn</button><button id=corop class=buttons003 onclick=qcor()>Fly yes. Land no.</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What birthday was Bilbo celebrating in Fellowship of the Ring?",
"answ":"111TH",
"answ3":"111TH BIRTHDAY",
"answ2":"111th birthday.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>100th</button><button id=incop2 class=buttons003 onclick=qinc()>107th</button><button id=corop class=buttons003 onclick=qcor()>111th</button><button id=incop4 class=buttons003 onclick=qinc()>120th</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of the place that Ant-Man enters when he goes subatomic?",
"answ":"QUANTUM REALM",
"answ2":"Quantum realm.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Micro cosmos</button><button id=incop2 class=buttons003 onclick=qinc()>Micro realm</button><button id=corop class=buttons003 onclick=qcor()>Quantum realm</button><button id=incop4 class=buttons003 onclick=qinc()>Atom dimension</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Star Trek II The Wrath of Khan, what word does Spock communicate during his mind meld with McCoy?",
"answ":"REMEMBER",
"answ2":"Remember.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Thanks</button><button id=incop2 class=buttons003 onclick=qinc()>Forget</button><button id=corop class=buttons003 onclick=qcor()>Remember</button><button id=incop4 class=buttons003 onclick=qinc()>Forgive</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who is the first of the Fellowship to offer to accompany Frodo to Mordor, after Gandalf?",
"answ":"ARAGORN",
"answ2":"Aragorn.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Samwise</button><button id=incop2 class=buttons003 onclick=qinc()>Gimli</button><button id=corop class=buttons003 onclick=qcor()>Aragorn</button><button id=incop4 class=buttons003 onclick=qinc()>Boromir</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What does Han Solo say right after shooting the radio on the Death Star's detention level in A New Hope?",
"answ":"BORING CONVERSATION ANYWAY",
"answ2":"Boring conversation anyway.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Boring conversation anyway</button><button id=incop2 class=buttons003 onclick=qinc()>Couldn't understand him anyway</button><button id=incop3 class=buttons003 onclick=qinc()>It's gonna get worse anyway</button><button id=incop4 class=buttons003 onclick=qinc()>Yes, I bet you have</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Return of the King, which character cannot resist the temptation to look into the Palantir?",
"answ":"PIPPIN",
"answ2":"Pippin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Pippin</button><button id=incop2 class=buttons003 onclick=qinc()>Sam</button><button id=incop3 class=buttons003 onclick=qinc()>Frodo</button><button id=incop4 class=buttons003 onclick=qinc()>Gimli</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In The Phantom Menace, who warns Queen Amidala 'I can only protect you... I can't fight a war for you.'?",
"answ":"QUI GON",
"answ3":"QUI GON JINN",
"answ2":"Qui-Gon Jinn.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Qui-Gon Jinn</button><button id=incop2 class=buttons003 onclick=qinc()>Obi-Wan Kenobi</button><button id=incop3 class=buttons003 onclick=qinc()>Anakin Skywalker</button><button id=incop4 class=buttons003 onclick=qinc()>Mace Windu</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What was the name of the Death Eater that was appointed to the post of Head of Magical Law Enforcement under Voldemort's regime?",
"answ":"YAXLEY",
"answ3":"JAXLEY",
"answ2":"Yaxley.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Yaxley</button><button id=incop2 class=buttons003 onclick=qinc()>Runcorn</button><button id=incop3 class=buttons003 onclick=qinc()>Thicknesse</button><button id=incop4 class=buttons003 onclick=qinc()>Carrow</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who served as Viceroy to the Trade Federation in The Phantom Menace?",
"answ":"NUTE GUNREY",
"answ3":"NUTE GUNRAY",
"answ2":"Nute Gunray.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nute Gunray</button><button id=incop2 class=buttons003 onclick=qinc()>Sib Canay</button><button id=incop3 class=buttons003 onclick=qinc()>Lufa Danak</button><button id=incop4 class=buttons003 onclick=qinc()>Rune Haako</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What character said: 'Do you want to know why I use a knife? Guns are too quick. You can't savor all the... little emotions'?",
"answ":"JOKER",
"answ3":"THE JOKER",
"answ2":"The Joker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>The Joker</button><button id=incop2 class=buttons003 onclick=qinc()>Ra's al Ghul</button><button id=incop3 class=buttons003 onclick=qinc()>Lex Luthor</button><button id=incop4 class=buttons003 onclick=qinc()>Doctor Doom</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What actor provided the motion capture and voice of the White Orc Azog in the Hobbit films?",
"answ":"MANU BENNETT",
"answ2":"Manu Bennett.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Dominic Purcell</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Jai White</button><button id=incop3 class=buttons003 onclick=qinc()>Vinnie Jones</button><button id=corop class=buttons003 onclick=qcor()>Manu Bennett</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In the Harry Potter films, which Weasley married Fleur Delacour?",
"answ":"BILL",
"answ3":"BILL WEASLEY",
"answ2":"Bill.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Charlie</button><button id=incop2 class=buttons003 onclick=qinc()>Fred</button><button id=incop3 class=buttons003 onclick=qinc()>George</button><button id=corop class=buttons003 onclick=qcor()>Bill</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of the character played by both Walter Koenig and Anton Yelchin in the Star Trek films?",
"answ":"CHEKOV",
"answ3":"PAVEL CHEKOV",
"answ2":"Chekov.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>McCoy</button><button id=incop2 class=buttons003 onclick=qinc()>Sulu</button><button id=incop3 class=buttons003 onclick=qinc()>Scotty</button><button id=corop class=buttons003 onclick=qcor()>Chekov</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the main villain that simply goes by 'Max' in the Vertigo comics based film, The Losers?",
"answ":"JASON PATRIC",
"answ3":"JASON PATRICK",
"answ2":"Jason Patric.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jason Patric</button><button id=incop2 class=buttons003 onclick=qinc()>Jeffrey Dean Morgan</button><button id=incop3 class=buttons003 onclick=qinc()>Idris Elba</button><button id=incop4 class=buttons003 onclick=qinc()>Eric Bana</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What does Steve say when Peggy ask how he feels after the Super Soldier procedure in Captain America: The First Avenger?",
"answ":"TALLER",
"answ2":"Taller.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Stronger</button><button id=incop2 class=buttons003 onclick=qinc()>Tired</button><button id=incop3 class=buttons003 onclick=qinc()>Hungry</button><button id=corop class=buttons003 onclick=qcor()>Taller</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Indiana Jones and the Last Crusade, how did Dr. Jones Sr. claim to find out Elsa was a Nazi?",
"answ":"SHE TALKS IN HER SLEEP",
"answ3":"TALKS IN HER SLEEP",
"answ2":"She talks in her sleep.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>He intercepted a letter</button><button id=incop2 class=buttons003 onclick=qinc()>He overheard a phone call</button><button id=incop3 class=buttons003 onclick=qinc()>Her accent</button><button id=corop class=buttons003 onclick=qcor()>She talks in her sleep</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"During the graveyard scene in Harry Potter and The Goblet of Fire, Peter Pettigrew killed Cedric Diggory with what spell?",
"answ":"KILLING CURSE",
"answ3":"AVADA KEDAVRA",
"answ2":"Avada Kedavra.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Crucio</button><button id=incop2 class=buttons003 onclick=qinc()>Valar morghulis</button><button id=incop3 class=buttons003 onclick=qinc()>Imperio</button><button id=corop class=buttons003 onclick=qcor()>Avada Kedavra</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"The Ringwraiths or Black Riders were also referred to as what in the Lord of the Rings trilogy?",
"answ":"NAZGUL",
"answ3":"NAZGÛL",
"answ2":"Nazgûl.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ungoliant</button><button id=incop2 class=buttons003 onclick=qinc()>Gothmog</button><button id=incop3 class=buttons003 onclick=qinc()>Balrogs</button><button id=corop class=buttons003 onclick=qcor()>Nazgûl</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In The Avengers, what 'Mark' number of the Iron Man suit did Tony use in the Battle of New York?",
"answ":"MARK 7",
"answ3":"7",
"answ2":"Mark 7.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mark 5</button><button id=corop class=buttons003 onclick=qcor()>Mark 7</button><button id=incop3 class=buttons003 onclick=qinc()>Mark 12</button><button id=incop4 class=buttons003 onclick=qinc()>Mark 42</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In The Rocketeer, the final battle between Cliff and Neville Sinclair occurs on what mode of transportation?",
"answ":"ZEPPELIN",
"answ2":"Zeppelin.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Biplane</button><button id=incop2 class=buttons003 onclick=qinc()>Aircraft carrier</button><button id=corop class=buttons003 onclick=qcor()>Zeppelin</button><button id=incop4 class=buttons003 onclick=qinc()>Train</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Whose base do The Avengers lead an assault against in the opening scene of Avengers: Age of Ultron?",
"answ":"BARON VON STRUCKER",
"answ3":"BARON STRUCKER",
"answ2":"Baron von Strucker.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Arnim Zola</button><button id=incop2 class=buttons003 onclick=qinc()>Johann Schmidt</button><button id=corop class=buttons003 onclick=qcor()>Baron von Strucker</button><button id=incop4 class=buttons003 onclick=qinc()>Alexander Pierce</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of the process that a Padawan must go through to become a Jedi Knight?",
"answ":"JEDI TRIALS",
"answ3":"THE JEDI TRIALS",
"answ2":"Jedi Trials.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Concordance of Fealty</button><button id=incop2 class=buttons003 onclick=qinc()>Day of Demand</button><button id=corop class=buttons003 onclick=qcor()>Jedi Trials</button><button id=incop4 class=buttons003 onclick=qinc()>Exultation</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of Nero's Romulan ship in 2009's Star Trek?",
"answ":"NARADA",
"answ2":"Narada.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Scimitar</button><button id=incop2 class=buttons003 onclick=qinc()>Talvath</button><button id=corop class=buttons003 onclick=qcor()>Narada</button><button id=incop4 class=buttons003 onclick=qinc()>Devoras</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Dave Lizewski creates a page for people to contact his alter-ego, Kick-Ass, for help on what social media platform?",
"answ":"MYSPACE",
"answ2":"Myspace.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Craigslist</button><button id=incop2 class=buttons003 onclick=qinc()>eBay</button><button id=corop class=buttons003 onclick=qcor()>Myspace</button><button id=incop4 class=buttons003 onclick=qinc()>Facebook</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What Scottish actor plays Charlie, a marksman suffering from PTSD in Wonder Woman?",
"answ":"EWEN BREMNER",
"answ3":"EWAN BREMNER",
"answ2":"Ewen Bremner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jonny Lee Miller</button><button id=incop2 class=buttons003 onclick=qinc()>Josh Hartnett</button><button id=corop class=buttons003 onclick=qcor()>Ewen Bremner</button><button id=incop4 class=buttons003 onclick=qinc()>Robert Carlyle</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who is the voice of Sauron in Fellowship of the Ring?",
"answ":"ALAN HOWARD",
"answ2":"Alan Howard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christopher Lee</button><button id=incop2 class=buttons003 onclick=qinc()>John Rhys-Davies</button><button id=corop class=buttons003 onclick=qcor()>Alan Howard</button><button id=incop4 class=buttons003 onclick=qinc()>Andy Serkis</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Dredd (2012), what is the name of the clan that has taken over the entire building where the film takes place?",
"answ":"MA MA CLAN",
"answ3":"MAMA CLAN",
"answ2":"Ma-ma Clan.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Blood Brothers</button><button id=incop2 class=buttons003 onclick=qinc()>Red Dragons</button><button id=corop class=buttons003 onclick=qcor()>Ma-ma Clan</button><button id=incop4 class=buttons003 onclick=qinc()>Slo-mo Clan</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the ruthless cattle baron Woodrow Dolarhyde in Cowboys & Aliens?",
"answ":"HARRISON FORD",
"answ2":"Harrison Ford.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Harrison Ford</button><button id=incop2 class=buttons003 onclick=qinc()>Clancy Brown</button><button id=incop3 class=buttons003 onclick=qinc()>Daniel Craig</button><button id=incop4 class=buttons003 onclick=qinc()>Josh Brolin</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What was the name of the main villain in 2004's Hellboy?",
"answ":"RASPUTIN",
"answ3":"GRIGORI RASPUTIN",
"answ2":"Rasputin.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rasputin</button><button id=incop2 class=buttons003 onclick=qinc()>King Balor</button><button id=incop3 class=buttons003 onclick=qinc()>Sadu-Hem</button><button id=incop4 class=buttons003 onclick=qinc()>Hecate</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Kingsman The Secret Service, what TV action hero does Eggsy name his dog after?",
"answ":"JACK BAUER",
"answ2":"Jack Bauer.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Knight</button><button id=corop class=buttons003 onclick=qcor()>Jack Bauer</button><button id=incop3 class=buttons003 onclick=qinc()>B. A. Baracus</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Austin</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of Sam Rockwell's character in Iron Man 2?",
"answ":"JUSTIN HAMMER",
"answ2":"Justin Hammer.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Justin Hammer</button><button id=incop2 class=buttons003 onclick=qinc()>Ivan Vanko</button><button id=incop3 class=buttons003 onclick=qinc()>Howard Stark</button><button id=incop4 class=buttons003 onclick=qinc()>Jeremy Hamburger</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Dr. Arnim Zola in the MCU?",
"answ":"TOBY JONES",
"answ2":"Toby Jones.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Toby Jones</button><button id=incop2 class=buttons003 onclick=qinc()>Robert Redford</button><button id=incop3 class=buttons003 onclick=qinc()>Hugo Weaving</button><button id=incop4 class=buttons003 onclick=qinc()>Stanley Tucci</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who provided the voice of the aquatic empath Abe Sapien in Hellboy II: The Golden Army?",
"answ":"DOUG JONES",
"answ2":"Doug Jones.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Seth MacFarlane</button><button id=corop class=buttons003 onclick=qcor()>Doug Jones</button><button id=incop3 class=buttons003 onclick=qinc()>David Hyde Pierce</button><button id=incop4 class=buttons003 onclick=qinc()>David Tennant</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays the drug lord simply known as Ma-Ma in Dredd?",
"answ":"LENA HEADEY",
"answ2":"Lena Headey.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Lena Headey</button><button id=incop2 class=buttons003 onclick=qinc()>Olivia Thirlby</button><button id=incop3 class=buttons003 onclick=qinc()>Nicole Kidman</button><button id=incop4 class=buttons003 onclick=qinc()>Anne Hathaway</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Cowboys & Aliens, what actor who also played a MCU villain, plays Doc?",
"answ":"SAM ROCKWELL",
"answ2":"Sam Rockwell.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Sam Rockwell</button><button id=incop2 class=buttons003 onclick=qinc()>Viggo Mortensen</button><button id=incop3 class=buttons003 onclick=qinc()>Mickey Rourke</button><button id=incop4 class=buttons003 onclick=qinc()>Guy Pearce</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What race is Ronan the Accuser?",
"answ":"KREE",
"answ2":"Kree.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Kree</button><button id=incop2 class=buttons003 onclick=qinc()>Skrull</button><button id=incop3 class=buttons003 onclick=qinc()>Sakaaran</button><button id=incop4 class=buttons003 onclick=qinc()>D'Rillian</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In what 1990's comic book movie do the criminals Funboy, T-Bird, Skank and Tin-Tin appear?",
"answ":"THE CROW",
"answ2":"The Crow.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Mystery Men</button><button id=incop2 class=buttons003 onclick=qinc()>Spawn</button><button id=corop class=buttons003 onclick=qcor()>The Crow</button><button id=incop4 class=buttons003 onclick=qinc()>Howard the Duck</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the nefarious Neville Sinclair in the 1991 comic book film The Rocketeer?",
"answ":"TIMOTHY DALTON",
"answ2":"Timothy Dalton.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Roger Moore</button><button id=incop2 class=buttons003 onclick=qinc()>Pierce Brosnan</button><button id=incop3 class=buttons003 onclick=qinc()>George Lazenby</button><button id=corop class=buttons003 onclick=qcor()>Timothy Dalton</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"The League of Extraordinary Gentlemen stars Sean Connery as which iconic literary adventurer?",
"answ":"ALLAN QUATERMAIN",
"answ2":"Allan Quatermain.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Allan Quatermain</button><button id=incop2 class=buttons003 onclick=qinc()>Jim Hawkins</button><button id=incop3 class=buttons003 onclick=qinc()>Robinson Crusoe</button><button id=incop4 class=buttons003 onclick=qinc()>Charles Marlow</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What superhero was the subject of a 90s movie and has the alter ego Kit Walker?",
"answ":"PHANTOM",
"answ3":"THE PHANTOM",
"answ2":"The Phantom.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Shadow</button><button id=incop2 class=buttons003 onclick=qinc()>Steel</button><button id=incop3 class=buttons003 onclick=qinc()>The Rocketeer</button><button id=corop class=buttons003 onclick=qcor()>The Phantom</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Red 2, who played Sarah Ross, love interest to Bruce Willis' character?",
"answ":"MARY LOUISE PARKER",
"answ3":"MARY LUISE PARKER",
"answ2":"Mary-Louise Parker.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mary-Louise Parker</button><button id=incop2 class=buttons003 onclick=qinc()>Kate Beckinsale</button><button id=incop3 class=buttons003 onclick=qinc()>Marisa Tomei</button><button id=incop4 class=buttons003 onclick=qinc()>Robin Wright</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Natalie Portman's assistant Darcy in Thor and Thor: The Dark World?",
"answ":"KAT DENNINGS",
"answ3":"CAT DENNINGS",
"answ2":"Kat Dennings.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jaimie Alexander</button><button id=incop2 class=buttons003 onclick=qinc()>Alexis Dziena</button><button id=incop3 class=buttons003 onclick=qinc()>Ari Graynor</button><button id=corop class=buttons003 onclick=qcor()>Kat Dennings</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays pickpocket Kar and co-lead to Chow Yun-fat in Bulletproof Monk?",
"answ":"SEAN WILLIAM SCOTT",
"answ2":"Sean William Scott.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Joseph Gordon-Levitt</button><button id=corop class=buttons003 onclick=qcor()>Sean William Scott</button><button id=incop3 class=buttons003 onclick=qinc()>Jason Biggs</button><button id=incop4 class=buttons003 onclick=qinc()>Jonathan Rhys Meyers</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Ben Daimio in 2019's Hellboy?",
"answ":"DANIEL DAE KIM",
"answ2":"Daniel Dae Kim.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Daniel Dae Kim</button><button id=incop2 class=buttons003 onclick=qinc()>David Harbour</button><button id=incop3 class=buttons003 onclick=qinc()>Ian McShane</button><button id=incop4 class=buttons003 onclick=qinc()>Henry Golding</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In The Mask, what is the first balloon figure Stanley Ipkiss makes for the group of thugs?",
"answ":"GIRAFFE",
"answ2":"Giraffe.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Giraffe</button><button id=incop2 class=buttons003 onclick=qinc()>Dog</button><button id=incop3 class=buttons003 onclick=qinc()>Tommy Gun</button><button id=incop4 class=buttons003 onclick=qinc()>Lion</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Son of the Mask, which mythological god is the primary antagonist?",
"answ":"LOKI",
"answ2":"Loki.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Loki</button><button id=incop2 class=buttons003 onclick=qinc()>Mars</button><button id=incop3 class=buttons003 onclick=qinc()>Hades</button><button id=incop4 class=buttons003 onclick=qinc()>Ra</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who plays Clown, also known as Violator, in Spawn?",
"answ":"JOHN LEGUIZAMO",
"answ2":"John Leguizamo.",
"option":"<button id=corop class=buttons003 onclick=qcor()>John Leguizamo</button><button id=incop2 class=buttons003 onclick=qinc()>Martin Sheen</button><button id=incop3 class=buttons003 onclick=qinc()>Stephen Dorff</button><button id=incop4 class=buttons003 onclick=qinc()>Harvey Keitel</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Tank Girl, what is the name of the mutant inhuman renegades that attack W&P?",
"answ":"RIPPERS",
"answ2":"Rippers.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Rippers</button><button id=incop2 class=buttons003 onclick=qinc()>Scavengers</button><button id=incop3 class=buttons003 onclick=qinc()>Wild Riders</button><button id=incop4 class=buttons003 onclick=qinc()>Ravagers</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What type of animal does Hellboy have an affinity for in 2004's Hellboy?",
"answ":"CAT",
"answ3":"CATS",
"answ2":"Cat.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Cat</button><button id=incop2 class=buttons003 onclick=qinc()>Dog</button><button id=incop3 class=buttons003 onclick=qinc()>Tortoise</button><button id=incop4 class=buttons003 onclick=qinc()>Owl</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"Who played the villainous Jason Wynn in Spawn?",
"answ":"MARTIN SHEEN",
"answ2":"Martin Sheen.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Martin Sheen</button><button id=incop2 class=buttons003 onclick=qinc()>John Leguizamo</button><button id=incop3 class=buttons003 onclick=qinc()>Tim Curry</button><button id=incop4 class=buttons003 onclick=qinc()>Armand Assante</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What country is Elektra's family from in Daredevil?",
"answ":"GREECE",
"answ2":"Greece.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Greece</button><button id=incop2 class=buttons003 onclick=qinc()>Turkey</button><button id=incop3 class=buttons003 onclick=qinc()>Mexico</button><button id=incop4 class=buttons003 onclick=qinc()>Columbia</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the first name of Elektra's father?",
"answ":"NIKOLAS",
"answ3":"NICHOLAS",
"answ2":"Nikolas.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Nikolas</button><button id=incop2 class=buttons003 onclick=qinc()>Adrian</button><button id=incop3 class=buttons003 onclick=qinc()>Titus</button><button id=incop4 class=buttons003 onclick=qinc()>Marco</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"What is the name of Thanos' father?",
"answ":"A'LARS",
"answ3":"ALARS",
"answ2":"A'Lars.",
"option":"<button id=corop class=buttons003 onclick=qcor()>A'Lars</button><button id=incop2 class=buttons003 onclick=qinc()>Kronos</button><button id=incop3 class=buttons003 onclick=qinc()>Ikaris</button><button id=incop4 class=buttons003 onclick=qinc()>Ajak</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In Kingsman: The Golden Circle, what is the name of the diner that Poppy serves hamburgers and also dies in?",
"answ":"POPPY'S DINER",
"answ2":"Poppy's Diner.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Poppy's Diner</button><button id=incop2 class=buttons003 onclick=qinc()>Your Song Diner</button><button id=incop3 class=buttons003 onclick=qinc()>1950's Mash Up Diner</button><button id=incop4 class=buttons003 onclick=qinc()>Elton's Place</button><br/>",
},
{
"cat":"Heroes & Villains",
"ques":"In X-Men Origins: Wolverine, what class is Scott Summers in when he is first introduced and given detention?",
"answ":"SPANISH",
"answ2":"Spanish.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Spanish</button><button id=incop2 class=buttons003 onclick=qinc()>History</button><button id=incop3 class=buttons003 onclick=qinc()>Algebra</button><button id=incop4 class=buttons003 onclick=qinc()>Economics</button><br/>",
},
];
heroesvillains = shuffle(heroesvillains);
r2Q8 = shuffle(r2Q8);