var scoressoundtracks = [
{
"cat":"Scores & Soundtracks",
"ques":"How many Wizarding World films have been composed by Nicholas Hooper?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Juice Newton's Angel of the Morning is the intro music for what comic book film?",
"answ":"DEADPOOL",
"answ2":"Deadpool.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What MCU soundtrack features the songs Highway to Hell, Back in Black and War Machine?",
"answ":"IRON MAN 2",
"answ2":"Iron Man 2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The songs 'House of the Rising Son' and 'Sympathy for the Devil' appear in what 2016 comic book film?",
"answ":"SUICIDE SQUAD",
"answ2":"Suicide Squad.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays at the end of Suicide Squad as the team is shown back in prison?",
"answ":"BOHEMIAN RHAPSODY",
"answ2":"Bohemian Rhapsody.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for Dick Tracy and Wanted?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool 2, what song plays as Deadpool kills the henchmen in Hong Kong towards the beginning of the movie?",
"answ":"9 TO 5",
"answ3":"NINE TO FIVE",
"answ2":"9 to 5.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Road to Perdition?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2014's Teenage Mutant Ninja Turtles?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which American heavy metal band has a composing credit on Jonah Hex?",
"answ":"MASTODON",
"answ2":"Mastodon.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What AC/DC song plays as the X-Force jumps out of their plane in Deadpool 2?",
"answ":"THUNDERSTRUCK",
"answ2":"Thunderstruck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What is the name of the song Quisilver is listening to in the slow-motion scene in Days of Future Past?",
"answ":"TIME IN A BOTTLE",
"answ2":"Time in a Bottle.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ang Lee's Hulk?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which DC film was composed by Hildur Guðnadóttir?",
"answ":"JOKER",
"answ2":"Joker.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for both Zorro films?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2005's Fantastic Four?",
"answ":"JOHN OTTMAN",
"answ2":"John Ottman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool, what song is Deadpool listening to at the beginning of the freeway fight scene?",
"answ":"SHOOP",
"answ2":"Shoop.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Batman 1989 features two songs within the movie performed by what pop legend?",
"answ":"PRINCE",
"answ2":"Prince.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Dark Knight Rises?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Darkman?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for X-Men: Dark Phoenix?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Batman Returns?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Prisoner of Azkaban?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Fantastic Beasts and Where to Find Them?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Avengers Endgame?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Guardians of the Galaxy?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Guardians of the Galaxy 2?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ant-Man?",
"answ":"CHRISTOPHE BECK",
"answ3":"CHRISTOPH BECK",
"answ2":"Christophe Beck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ant-Man and the Wasp?",
"answ":"CHRISTOPHE BECK",
"answ2":"Christophe Beck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Doctor Strange?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spider-Man Homecoming?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spider-Man Far From Home?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain Marvel?",
"answ":"PINAR TOPRAK",
"answ2":"Pinar Toprak.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Black Panther?",
"answ":"LUDWIG GÖRANSSON",
"answ3":"LUDWIG GORANSSON",
"answ2":"Ludwig Göransson.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor Ragnarok?",
"answ":"MARK MOTHERSBAUGH",
"answ2":"Mark Mothersbaugh.",
},
];
var r2Q9 = [
{
"cat":"Scores & Soundtracks",
"ques":"Who has composed a score for a Men in Black film, a Spider-Man film and an Avengers film?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ludwig Göransson</button><button id=corop class=buttons003 onclick=qcor()>Danny Elfman</button><button id=incop3 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop4 class=buttons003 onclick=qinc()>Michael Giacchino</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool, what song did Wade and Vanessa do it to during the sex montage?",
"answ":"CALENDAR GIRL",
"answ2":"Calendar Girl.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Let's Get It On</button><button id=corop class=buttons003 onclick=qcor()>Calendar Girl</button><button id=incop3 class=buttons003 onclick=qinc()>Careless Whisper</button><button id=incop4 class=buttons003 onclick=qinc()>Angel of the Morning</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Lord of the Rings films?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Williams</button><button id=corop class=buttons003 onclick=qcor()>Howard Shore</button><button id=incop3 class=buttons003 onclick=qinc()>Hans Zimmer</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America The Winter Soldier?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shelly Johnson</button><button id=corop class=buttons003 onclick=qcor()>Henry Jackman</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop4 class=buttons003 onclick=qinc()>Tyler Bates</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America Civil War?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Shelly Johnson</button><button id=corop class=buttons003 onclick=qcor()>Henry Jackman</button><button id=incop3 class=buttons003 onclick=qinc()>Brian Tyler</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song does Baby Groot dance to during the mid-credits scene of Guardians of the Galaxy?",
"answ":"I WANT YOU BACK",
"answ2":"I Want You Back.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ain't No Mountain High Enough</button><button id=incop2 class=buttons003 onclick=qinc()>ABC</button><button id=corop class=buttons003 onclick=qcor()>I Want You Back</button><button id=incop4 class=buttons003 onclick=qinc()>Ain't Too Proud To Beg</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score of X-Men First Class?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Henry Jackman</button><button id=incop2 class=buttons003 onclick=qinc()>John Ottman</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Kamen</button><button id=incop4 class=buttons003 onclick=qinc()>John Powell</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song does Kirk and crew use to jam and disorient the swarm ships in Star Trek Beyond?",
"answ":"SABOTAGE",
"answ2":"Sabotage.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Gratitude</button><button id=incop2 class=buttons003 onclick=qinc()>Novacane</button><button id=incop3 class=buttons003 onclick=qinc()>Stranglehold</button><button id=corop class=buttons003 onclick=qcor()>Sabotage</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Watchmen?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Christophe Beck</button><button id=incop2 class=buttons003 onclick=qinc()>Craig Armstrong</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=corop class=buttons003 onclick=qcor()>Tyler Bates</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What Prince song played while Joker danced around the museum in 1989's Batman?",
"answ":"PARTYMAN",
"answ2":"Partyman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Batdance</button><button id=incop2 class=buttons003 onclick=qinc()>The Arms of Orion</button><button id=incop3 class=buttons003 onclick=qinc()>Feel U Up</button><button id=corop class=buttons003 onclick=qcor()>Partyman</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Fantastic Beasts: The Crimes of Grindelwald?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Howard Shore</button><button id=incop2 class=buttons003 onclick=qinc()>Thomas Newman</button><button id=incop3 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>James Newton Howard</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Sorcerer's Stone?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brad Fiedel</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop3 class=buttons003 onclick=qinc()>Jerry Goldsmith</button><button id=corop class=buttons003 onclick=qcor()>John Williams</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Goblet of Fire?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Thomas Newman</button><button id=corop class=buttons003 onclick=qcor()>Patrick Doyle</button><button id=incop4 class=buttons003 onclick=qinc()>John Williams</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Order of the Phoenix?",
"answ":"NICHOLAS HOOPER",
"answ2":"Nicholas Hooper.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>John Williams</button><button id=incop2 class=buttons003 onclick=qinc()>Thomas Newman</button><button id=corop class=buttons003 onclick=qcor()>Nicholas Hooper</button><button id=incop4 class=buttons003 onclick=qinc()>Howard Shore</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Deathly Hallows Part 1?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Horner</button><button id=incop2 class=buttons003 onclick=qinc()>Hans Zimmer</button><button id=corop class=buttons003 onclick=qcor()>Alexandre Desplat</button><button id=incop4 class=buttons003 onclick=qinc()>Bill Conti</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Suicide Squad?",
"answ":"STEVEN PRICE",
"answ2":"Steven Price.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hans Zimmer</button><button id=corop class=buttons003 onclick=qcor()>Steven Price</button><button id=incop3 class=buttons003 onclick=qinc()>Howard Shore</button><button id=incop4 class=buttons003 onclick=qinc()>Jerry Goldsmith</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Justice League?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Hans Zimmer</button><button id=corop class=buttons003 onclick=qcor()>Danny Elfman</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performed the song Venom for Venom?",
"answ":"EMINEM",
"answ2":"Eminem.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Drake</button><button id=corop class=buttons003 onclick=qcor()>Eminem</button><button id=incop3 class=buttons003 onclick=qinc()>Pitbull</button><button id=incop4 class=buttons003 onclick=qinc()>Kendrick Lamar</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Iron Man 2?",
"answ":"JOHN DEBNEY",
"answ2":"John Debney.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brian Tyler</button><button id=corop class=buttons003 onclick=qcor()>John Debney</button><button id=incop3 class=buttons003 onclick=qinc()>Craig Armstrong</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Iron Man 3?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Brian Tyler</button><button id=incop2 class=buttons003 onclick=qinc()>Danny Elfman</button><button id=incop3 class=buttons003 onclick=qinc()>Patrick Doyle</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Incredible Hulk?",
"answ":"CRAIG ARMSTRONG",
"answ2":"Craig Armstrong.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Craig Armstrong</button><button id=incop2 class=buttons003 onclick=qinc()>Howard Shore</button><button id=incop3 class=buttons003 onclick=qinc()>Patrick Doyle</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"In 2009's Watchmen, what song is played during the funeral of the Comedian?",
"answ":"THE SOUND OF SILENCE",
"answ3":"SOUND OF SILENCE",
"answ2":"The Sound of Silence.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Man on the Moon</button><button id=incop2 class=buttons003 onclick=qinc()>Hallelujah</button><button id=corop class=buttons003 onclick=qcor()>The Sound of Silence</button><button id=incop4 class=buttons003 onclick=qinc()>What Dreams May Come</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brian Tyler</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=corop class=buttons003 onclick=qcor()>Patrick Doyle</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor The Dark World?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Brian Tyler</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop3 class=buttons003 onclick=qinc()>Patrick Doyle</button><button id=incop4 class=buttons003 onclick=qinc()>Danny Elfman</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2012's The Avengers?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America The First Avenger?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Hans Zimmer</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Avengers Infinity War?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Patrick Doyle</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Rogue One: A Star Wars Story?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Michael Giacchino</button><button id=incop2 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1989's Batman?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Danny Elfman</button><button id=incop2 class=buttons003 onclick=qinc()>John Barry</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Batman Forever and Batman & Robin?",
"answ":"ELLIOT GOLDENTHAL",
"answ3":"ELLIOT GOLDENTAL",
"answ2":"Elliot Goldenthal.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Elliot Goldenthal</button><button id=incop2 class=buttons003 onclick=qinc()>Danny Elfman</button><button id=incop3 class=buttons003 onclick=qinc()>John Williams</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Blade?",
"answ":"MARK ISHAM",
"answ2":"Mark Isham.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Mark Isham</button><button id=incop2 class=buttons003 onclick=qinc()>RZA</button><button id=incop3 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Elektra?",
"answ":"CHRISTOPHE BECK",
"answ3":"CHRISTOPH BECK",
"answ2":"Christophe Beck.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Christophe Beck</button><button id=incop2 class=buttons003 onclick=qinc()>Graeme Revell</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop4 class=buttons003 onclick=qinc()>James Horner</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Logan and The Wolverine?",
"answ":"MARCO BELTRAMI",
"answ2":"Marco Beltrami.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Marco Beltrami</button><button id=incop2 class=buttons003 onclick=qinc()>Junkie XL</button><button id=incop3 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays while Quill is exploring Morag at the start of Guardians of the Galaxy?",
"answ":"COME AND GET YOUR LOVE",
"answ2":"Come and get your love.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Come and get your love</button><button id=incop2 class=buttons003 onclick=qinc()>Hooked on a Feeling</button><button id=incop3 class=buttons003 onclick=qinc()>Cherry Bomb</button><button id=incop4 class=buttons003 onclick=qinc()>Moonage Daydream</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek: The Motion Picture?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jerry Goldsmith</button><button id=incop2 class=buttons003 onclick=qinc()>James Horner</button><button id=incop3 class=buttons003 onclick=qinc()>Cliff Eidelman</button><button id=incop4 class=buttons003 onclick=qinc()>Leonard Rosenman</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek: Nemesis?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":"<button id=corop class=buttons003 onclick=qcor()>Jerry Goldsmith</button><button id=incop2 class=buttons003 onclick=qinc()>James Horner</button><button id=incop3 class=buttons003 onclick=qinc()>Cliff Eidelman</button><button id=incop4 class=buttons003 onclick=qinc()>Leonard Rosenman</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek VI: The Undiscovered Country?",
"answ":"CLIFF EIDELMAN",
"answ2":"Cliff Eidelman.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jerry Goldsmith</button><button id=incop2 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>Cliff Eidelman</button><button id=incop4 class=buttons003 onclick=qinc()>Leonard Rosenman</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek (2009) and Star Trek Into Darkness?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>Michael Giacchino</button><button id=incop4 class=buttons003 onclick=qinc()>Hans Zimmer</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Dennis McCarthy composed the score for which Star Trek movie?",
"answ":"STAR TREK GENERATIONS",
"answ3":"GENERATIONS",
"answ2":"Star Trek Generations.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Star Trek: First Contact</button><button id=incop2 class=buttons003 onclick=qinc()>Star Trek: Nemesis</button><button id=corop class=buttons003 onclick=qcor()>Star Trek Generations</button><button id=incop4 class=buttons003 onclick=qinc()>Star Trek Into Darkness</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Jerry Goldsmith composed the scores for how many Star Trek films?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=incop2 class=buttons003 onclick=qinc()>4</button><button id=corop class=buttons003 onclick=qcor()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Michael Giacchino composed the scores for how many Star Trek films?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>1</button><button id=incop2 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop4 class=buttons003 onclick=qinc()>4</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Amazing Spider-Man?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=incop2 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=corop class=buttons003 onclick=qcor()>James Horner</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Deadpool 2?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Junkie XL</button><button id=incop2 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>Tyler Bates</button><button id=incop4 class=buttons003 onclick=qinc()>Brian Tyler</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Green Lantern?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Michael Giacchino</button><button id=corop class=buttons003 onclick=qcor()>James Newton Howard</button><button id=incop3 class=buttons003 onclick=qinc()>Tyler Bates</button><button id=incop4 class=buttons003 onclick=qinc()>Alan Silvestri</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1978's Superman?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Jerry Goldsmith</button><button id=corop class=buttons003 onclick=qcor()>John Williams</button><button id=incop3 class=buttons003 onclick=qinc()>James Horner</button><button id=incop4 class=buttons003 onclick=qinc()>Ennio Morricone</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays while Nite Owl and Silk Spectre make love in 2009's Watchmen?",
"answ":"HALLELUJAH",
"answ3":"HALLELUJA",
"answ2":"Hallelujah.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>The Times They Are a-Changin</button><button id=corop class=buttons003 onclick=qcor()>Hallelujah</button><button id=incop3 class=buttons003 onclick=qinc()>You're My Thrill</button><button id=incop4 class=buttons003 onclick=qinc()>What's Going On</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Kingsman: The Golden Circle, what song does Elton John play when Eggsy and Harry attack Poppy Land?",
"answ":"SATURDAY NIGHT'S ALRIGHT FOR FIGHTING",
"answ3":"SATURDAY NIGHT'S ALRIGHT",
"answ2":"Saturday Night's Alright for Fighting.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>I'm Still Standing</button><button id=corop class=buttons003 onclick=qcor()>Saturday Night's Alright for Fighting</button><button id=incop3 class=buttons003 onclick=qinc()>Tiny Dancer</button><button id=incop4 class=buttons003 onclick=qinc()>Sacrifice</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Hans Zimmer shared credit for the score of Batman Begins with which composer?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>James Horner</button><button id=corop class=buttons003 onclick=qcor()>James Newton Howard</button><button id=incop3 class=buttons003 onclick=qinc()>John Powell</button><button id=incop4 class=buttons003 onclick=qinc()>Klaus Badelt</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Danny Elfman and which other composer are credited for the score of Age of Ultron?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Alan Silvestri</button><button id=corop class=buttons003 onclick=qcor()>Brian Tyler</button><button id=incop3 class=buttons003 onclick=qinc()>Henry Jackman</button><button id=incop4 class=buttons003 onclick=qinc()>Tyler Bates</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"The song Vindicated by Dashboard Confessional appears in the end credits of what Marvel movie?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDERMAN 2",
"answ2":"Spider-Man 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>X-Men</button><button id=corop class=buttons003 onclick=qcor()>Spider-Man 2</button><button id=incop3 class=buttons003 onclick=qinc()>Hulk</button><button id=incop4 class=buttons003 onclick=qinc()>Blade II</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"The songs 'Come on, Come in', 'Noots' and 'Everything Burns' were part of the soundtrack of what Marvel film?",
"answ":"FANTASTIC FOUR",
"answ3":"FANTASTIC FOUR (2005)",
"answ2":"Fantastic Four (2005).",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Ghost Rider</button><button id=corop class=buttons003 onclick=qcor()>Fantastic Four (2005)</button><button id=incop3 class=buttons003 onclick=qinc()>Ghost Rider: Spirit of Vengeance</button><button id=incop4 class=buttons003 onclick=qinc()>Daredevil</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Alan Silvestri composed full scores for how many MCU films?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>3</button><button id=corop class=buttons003 onclick=qcor()>4</button><button id=incop3 class=buttons003 onclick=qinc()>5</button><button id=incop4 class=buttons003 onclick=qinc()>6</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who has composing credits on Catwoman, Constantine and 2007's TMNT?",
"answ":"KLAUS BADELT",
"answ3":"CLAUS BADELT",
"answ2":"Klaus Badelt.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Brian Tyler</button><button id=corop class=buttons003 onclick=qcor()>Klaus Badelt</button><button id=incop3 class=buttons003 onclick=qinc()>John Du Prez</button><button id=incop4 class=buttons003 onclick=qinc()>Steve Jablonsky</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"John Williams composed the scores for how many Harry Potter films?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>2</button><button id=corop class=buttons003 onclick=qcor()>3</button><button id=incop3 class=buttons003 onclick=qinc()>4</button><button id=incop4 class=buttons003 onclick=qinc()>5</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"What late 90s pop song plays during the opening logos of Iron Man 3?",
"answ":"BLUE",
"answ3":"BLUE (DA BA DEE)",
"answ2":"Blue.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Livin' La Vida Loca</button><button id=corop class=buttons003 onclick=qcor()>Blue</button><button id=incop3 class=buttons003 onclick=qinc()>Barbie Girl</button><button id=incop4 class=buttons003 onclick=qinc()>I'll Be There For You</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Dashboard Confessional performed the credits song 'Vindicated' for what 2004 Marvel film?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDERMAN 2",
"answ2":"Spider-Man 2.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Daredevil</button><button id=corop class=buttons003 onclick=qcor()>Spider-Man 2</button><button id=incop3 class=buttons003 onclick=qinc()>Hulk</button><button id=incop4 class=buttons003 onclick=qinc()>X2</button><br/>",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performs the end-credit song 'Into the West' for The Lord of the Rings: The Return of the King?",
"answ":"ANNIE LENNOX",
"answ2":"Annie Lennox.",
"option":"<button id=incop1 class=buttons003 onclick=qinc()>Emilíana Torrini</button><button id=corop class=buttons003 onclick=qcor()>Annie Lennox</button><button id=incop3 class=buttons003 onclick=qinc()>Sheila Chandra</button><button id=incop4 class=buttons003 onclick=qinc()>Enya</button><br/>",
},
];
scoressoundtracks = shuffle(scoressoundtracks);
r2Q9 = shuffle(r2Q9);