var scoressoundtracks = [
{
"cat":"Scores & Soundtracks",
"ques":"How many Wizarding World films have been composed by Nicholas Hooper?",
"answ":"2",
"answ3":"TWO",
"answ2":"2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Iron Man 2, a remixed version of what Queen song plays with It Takes Two, while Tony and Rhodey fight at Tony's birthday party?",
"answ":"ANOTHER ONE BITES THE DUST",
"answ2":"Another One Bites the Dust.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In what Harry Potter film will you find the songs 'Do the Hippogriff' and 'Magic Works' performed by the band Weird Sisters?",
"answ":"HARRY POTTER AND THE GOBLET OF FIRE",
"answ3":"GOBLET OF FIRE",
"answ2":"Harry Potter and the Goblet of Fire.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the films R.I.P.D. and Red?",
"answ":"CHRISTOPHE BECK",
"answ2":"Christophe Beck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for both Fantastic Four and Fantastic Four: Rise of the Silver Surfer?",
"answ":"JOHN OTTMAN",
"answ2":"John Ottman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"'Zordon Awakes', 'Birth of a Legend' and 'Megazord' are featured tracks in the score to what fantasy/sci-fi film?",
"answ":"POWER RANGERS",
"answ2":"Power Rangers.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Hellboy II: The Golden Army?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which Star Trek composer also wrote the music for 1987's Superman IV: the Quest for Peace?",
"answ":"ALEXANDER COURAGE",
"answ2":"Alexander Courage.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Juice Newton's Angel of the Morning is the intro music for what comic book film?",
"answ":"DEADPOOL",
"answ2":"Deadpool.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What MCU soundtrack features the songs Highway to Hell, Back in Black and War Machine?",
"answ":"IRON MAN 2",
"answ2":"Iron Man 2.",
},
{
"cat":"Scores & Soundtracks",
"ques":"The songs 'House of the Rising Son' and 'Sympathy for the Devil' appear in what 2016 comic book film?",
"answ":"SUICIDE SQUAD",
"answ2":"Suicide Squad.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays at the end of Suicide Squad as the team is shown back in prison?",
"answ":"BOHEMIAN RHAPSODY",
"answ2":"Bohemian Rhapsody.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the scores for Dick Tracy and Wanted?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool 2, what song plays as Deadpool kills the henchmen in Hong Kong towards the beginning of the movie?",
"answ":"9 TO 5",
"answ3":"NINE TO FIVE",
"answ2":"9 to 5.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Road to Perdition?",
"answ":"THOMAS NEWMAN",
"answ2":"Thomas Newman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2014's Teenage Mutant Ninja Turtles?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which American heavy metal band has a composing credit on Jonah Hex?",
"answ":"MASTODON",
"answ2":"Mastodon.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What AC/DC song plays as the X-Force jumps out of their plane in Deadpool 2?",
"answ":"THUNDERSTRUCK",
"answ2":"Thunderstruck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"What is the name of the song Quisilver is listening to in the slow-motion scene in Days of Future Past?",
"answ":"TIME IN A BOTTLE",
"answ2":"Time in a Bottle.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ang Lee's Hulk?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Which DC film was composed by Hildur Guðnadóttir?",
"answ":"JOKER",
"answ2":"Joker.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for both Zorro films?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool, what song is Deadpool listening to at the beginning of the freeway fight scene?",
"answ":"SHOOP",
"answ2":"Shoop.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Batman 1989 features two songs within the movie performed by what pop legend?",
"answ":"PRINCE",
"answ2":"Prince.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Dark Knight Rises?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Darkman?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for X-Men: Dark Phoenix?",
"answ":"HANS ZIMMER",
"answ2":"Hans Zimmer.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Batman Returns?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Prisoner of Azkaban?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Fantastic Beasts and Where to Find Them?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Avengers Endgame?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Guardians of the Galaxy?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Guardians of the Galaxy 2?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ant-Man?",
"answ":"CHRISTOPHE BECK",
"answ3":"CHRISTOPH BECK",
"answ2":"Christophe Beck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Ant-Man and the Wasp?",
"answ":"CHRISTOPHE BECK",
"answ2":"Christophe Beck.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Doctor Strange?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spider-Man Homecoming?",
"answ":"MICHAEL GIACCHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Spider-Man Far From Home?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain Marvel?",
"answ":"PINAR TOPRAK",
"answ2":"Pinar Toprak.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Black Panther?",
"answ":"LUDWIG GÖRANSSON",
"answ3":"LUDWIG GORANSSON",
"answ2":"Ludwig Göransson.",
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor Ragnarok?",
"answ":"MARK MOTHERSBAUGH",
"answ2":"Mark Mothersbaugh.",
},
];
var r2Q9 = [
{
"cat":"Scores & Soundtracks",
"ques":"In 2004's The Punisher, country music star Mark Collie's character Harry Heck plays what song on his guitar to Frank Castle inside the diner?",
"answ":"IN TIME",
"answ2":"In Time.",
"option":["In Time", "The End Has Come", "Hurt", "Still Running"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who recorded the song 'Ashes' for Deadpool 2?",
"answ":"CELINE DION",
"answ2":"Celine Dion.",
"option":["Celine Dion", "Ariana Grande", "Adele", "Lady Gaga"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The songs 'Burn', 'Golgotha Tenement Blues' and 'Color Me Once' are on the soundtrack for what 1990s comic book film?",
"answ":"THE CROW",
"answ2":"The Crow.",
"option":["The Crow", "Spawn", "The Phantom", "Mystery Men"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who has composed a score for a Men in Black film, a Spider-Man film and an Avengers film?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Ludwig Göransson", "Alan Silvestri", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Deadpool, what song did Wade and Vanessa do it to during the sex montage?",
"answ":"CALENDAR GIRL",
"answ2":"Calendar Girl.",
"option":["Calendar Girl", "Let's Get It On", "Careless Whisper", "Angel of the Morning"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for the Lord of the Rings films?",
"answ":"HOWARD SHORE",
"answ2":"Howard Shore.",
"option":["Howard Shore", "John Williams", "Hans Zimmer", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America The Winter Soldier?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":["Henry Jackman", "Shelly Johnson", "Michael Giacchino", "Tyler Bates"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America Civil War?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":["Henry Jackman", "Shelly Johnson", "Brian Tyler", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song does Baby Groot dance to during the mid-credits scene of Guardians of the Galaxy?",
"answ":"I WANT YOU BACK",
"answ2":"I Want You Back.",
"option":["I Want You Back", "Ain't No Mountain High Enough", "ABC", "Ain't Too Proud To Beg"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score of X-Men First Class?",
"answ":"HENRY JACKMAN",
"answ2":"Henry Jackman.",
"option":["Henry Jackman", "John Ottman", "Michael Kamen", "John Powell"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song does Kirk and crew use to jam and disorient the swarm ships in Star Trek Beyond?",
"answ":"SABOTAGE",
"answ2":"Sabotage.",
"option":["Sabotage", "Gratitude", "Novacane", "Stranglehold"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Watchmen?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
"option":["Tyler Bates", "Christophe Beck", "Craig Armstrong", "Michael Giacchino"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What Prince song played while Joker danced around the museum in 1989's Batman?",
"answ":"PARTYMAN",
"answ2":"Partyman.",
"option":["Partyman", "Batdance", "The Arms of Orion", "Feel U Up"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Fantastic Beasts: The Crimes of Grindelwald?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":["James Newton Howard", "Howard Shore", "Thomas Newman", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Sorcerer's Stone?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Brad Fiedel", "Michael Giacchino", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Goblet of Fire?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":["Patrick Doyle", "Alan Silvestri", "Thomas Newman", "John Williams"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Order of the Phoenix?",
"answ":"NICHOLAS HOOPER",
"answ2":"Nicholas Hooper.",
"option":["Nicholas Hooper", "John Williams", "Thomas Newman", "Howard Shore"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Harry Potter and the Deathly Hallows Part 1?",
"answ":"ALEXANDRE DESPLAT",
"answ3":"ALEXANDER DESPLAT",
"answ2":"Alexandre Desplat.",
"option":["Alexandre Desplat", "James Horner", "Hans Zimmer", "Bill Conti"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Suicide Squad?",
"answ":"STEVEN PRICE",
"answ2":"Steven Price.",
"option":["Steven Price", "Hans Zimmer", "Howard Shore", "Jerry Goldsmith"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Justice League?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "Hans Zimmer", "John Williams", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performed the closing credits song 'May It Be' from Lord of the Rings: The Fellowship of the Ring?",
"answ":"ENYA",
"answ2":"Enya.",
"option":["Enya", "Annie Lennox", "Liv Tyler", "Celine Dion"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performed the song Venom for Venom?",
"answ":"EMINEM",
"answ2":"Eminem.",
"option":["Eminem", "Drake", "Pitbull", "Kendrick Lamar"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Iron Man 2?",
"answ":"JOHN DEBNEY",
"answ2":"John Debney.",
"option":["John Debney", "Brian Tyler", "Craig Armstrong", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Iron Man 3?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":["Brian Tyler", "Danny Elfman", "Patrick Doyle", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Incredible Hulk?",
"answ":"CRAIG ARMSTRONG",
"answ2":"Craig Armstrong.",
"option":["Craig Armstrong", "Howard Shore", "Patrick Doyle", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In 2009's Watchmen, what song is played during the funeral of the Comedian?",
"answ":"THE SOUND OF SILENCE",
"answ3":"SOUND OF SILENCE",
"answ2":"The Sound of Silence.",
"option":["The Sound of Silence", "Man on the Moon", "Hallelujah", "What Dreams May Come"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor?",
"answ":"PATRICK DOYLE",
"answ2":"Patrick Doyle.",
"option":["Patrick Doyle", "Brian Tyler", "Alan Silvestri", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Thor The Dark World?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":["Brian Tyler", "Michael Giacchino", "Patrick Doyle", "Danny Elfman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 2012's The Avengers?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Michael Giacchino", "John Williams", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Captain America The First Avenger?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Hans Zimmer", "John Williams", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Avengers Infinity War?",
"answ":"ALAN SILVESTRI",
"answ2":"Alan Silvestri.",
"option":["Alan Silvestri", "Patrick Doyle", "John Williams", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Rogue One: A Star Wars Story?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "John Williams", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1989's Batman?",
"answ":"DANNY ELFMAN",
"answ2":"Danny Elfman.",
"option":["Danny Elfman", "John Barry", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Batman Forever and Batman & Robin?",
"answ":"ELLIOT GOLDENTHAL",
"answ3":"ELLIOT GOLDENTAL",
"answ2":"Elliot Goldenthal.",
"option":["Elliot Goldenthal", "Danny Elfman", "John Williams", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Blade?",
"answ":"MARK ISHAM",
"answ2":"Mark Isham.",
"option":["Mark Isham", "RZA", "Alan Silvestri", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Elektra?",
"answ":"CHRISTOPHE BECK",
"answ3":"CHRISTOPH BECK",
"answ2":"Christophe Beck.",
"option":["Christophe Beck", "Graeme Revell", "Michael Giacchino", "James Horner"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Logan and The Wolverine?",
"answ":"MARCO BELTRAMI",
"answ2":"Marco Beltrami.",
"option":["Marco Beltrami", "Junkie XL", "Michael Giacchino", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays while Quill is exploring Morag at the start of Guardians of the Galaxy?",
"answ":"COME AND GET YOUR LOVE",
"answ2":"Come and get your love.",
"option":["Come and get your love", "Hooked on a Feeling", "Cherry Bomb", "Moonage Daydream"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek: The Motion Picture?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "James Horner", "Cliff Eidelman", "Leonard Rosenman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek: Nemesis?",
"answ":"JERRY GOLDSMITH",
"answ2":"Jerry Goldsmith.",
"option":["Jerry Goldsmith", "James Horner", "Cliff Eidelman", "Leonard Rosenman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek VI: The Undiscovered Country?",
"answ":"CLIFF EIDELMAN",
"answ2":"Cliff Eidelman.",
"option":["Cliff Eidelman", "Jerry Goldsmith", "James Horner", "Leonard Rosenman"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Star Trek (2009) and Star Trek Into Darkness?",
"answ":"MICHAEL GIACCHINO",
"answ3":"MICHAEL GIACHINO",
"answ2":"Michael Giacchino.",
"option":["Michael Giacchino", "Alan Silvestri", "James Horner", "Hans Zimmer"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Dennis McCarthy composed the score for which Star Trek movie?",
"answ":"STAR TREK GENERATIONS",
"answ3":"GENERATIONS",
"answ2":"Star Trek Generations.",
"option":["Star Trek Generations", "Star Trek: First Contact", "Star Trek: Nemesis", "Star Trek Into Darkness"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Jerry Goldsmith composed the scores for how many Star Trek films?",
"answ":"5",
"answ3":"FIVE",
"answ2":"5.",
"option":["5", "4", "3", "6"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Michael Giacchino composed the scores for how many Star Trek films?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "1", "4"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for The Amazing Spider-Man?",
"answ":"JAMES HORNER",
"answ2":"James Horner.",
"option":["James Horner", "Alan Silvestri", "Michael Giacchino", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Deadpool 2?",
"answ":"TYLER BATES",
"answ2":"Tyler Bates.",
"option":["Tyler Bates", "Junkie XL", "James Horner", "Brian Tyler"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for Green Lantern?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":["James Newton Howard", "Michael Giacchino", "Tyler Bates", "Alan Silvestri"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who composed the score for 1978's Superman?",
"answ":"JOHN WILLIAMS",
"answ2":"John Williams.",
"option":["John Williams", "Jerry Goldsmith", "James Horner", "Ennio Morricone"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What song plays while Nite Owl and Silk Spectre make love in 2009's Watchmen?",
"answ":"HALLELUJAH",
"answ3":"HALLELUJA",
"answ2":"Hallelujah.",
"option":["Hallelujah", "The Times They Are a-Changin", "You're My Thrill", "What's Going On"],
},
{
"cat":"Scores & Soundtracks",
"ques":"In Kingsman: The Golden Circle, what song does Elton John play when Eggsy and Harry attack Poppy Land?",
"answ":"SATURDAY NIGHT'S ALRIGHT FOR FIGHTING",
"answ3":"SATURDAY NIGHT'S ALRIGHT",
"answ2":"Saturday Night's Alright for Fighting.",
"option":["Saturday Night's Alright for Fighting", "I'm Still Standing", "Tiny Dancer", "Sacrifice"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Hans Zimmer shared credit for the score of Batman Begins with which composer?",
"answ":"JAMES NEWTON HOWARD",
"answ2":"James Newton Howard.",
"option":["James Newton Howard", "James Horner", "John Powell", "Klaus Badelt"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Danny Elfman and which other composer are credited for the score of Age of Ultron?",
"answ":"BRIAN TYLER",
"answ3":"BRYAN TYLER",
"answ2":"Brian Tyler.",
"option":["Brian Tyler", "Alan Silvestri", "Henry Jackman", "Tyler Bates"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The song Vindicated by Dashboard Confessional appears in the end credits of what Marvel movie?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDERMAN 2",
"answ2":"Spider-Man 2.",
"option":["Spider-Man 2", "X-Men", "Hulk", "Blade II"],
},
{
"cat":"Scores & Soundtracks",
"ques":"The songs 'Come on, Come in', 'Noots' and 'Everything Burns' were part of the soundtrack of what Marvel film?",
"answ":"FANTASTIC FOUR",
"answ3":"FANTASTIC FOUR (2005)",
"answ2":"Fantastic Four (2005).",
"option":["Fantastic Four (2005)", "Ghost Rider", "Ghost Rider: Spirit of Vengeance", "Daredevil"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Alan Silvestri composed full scores for how many MCU films?",
"answ":"4",
"answ3":"FOUR",
"answ2":"4.",
"option":["4", "3", "5", "6"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who has composing credits on Catwoman, Constantine and 2007's TMNT?",
"answ":"KLAUS BADELT",
"answ3":"CLAUS BADELT",
"answ2":"Klaus Badelt.",
"option":["Klaus Badelt", "Brian Tyler", "John Du Prez", "Steve Jablonsky"],
},
{
"cat":"Scores & Soundtracks",
"ques":"John Williams composed the scores for how many Harry Potter films?",
"answ":"3",
"answ3":"THREE",
"answ2":"3.",
"option":["3", "2", "4", "5"],
},
{
"cat":"Scores & Soundtracks",
"ques":"What late 90s pop song plays during the opening logos of Iron Man 3?",
"answ":"BLUE",
"answ3":"BLUE (DA BA DEE)",
"answ2":"Blue.",
"option":["Blue", "Livin' La Vida Loca", "Barbie Girl", "I'll Be There For You"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Dashboard Confessional performed the credits song 'Vindicated' for what 2004 Marvel film?",
"answ":"SPIDER MAN 2",
"answ3":"SPIDERMAN 2",
"answ2":"Spider-Man 2.",
"option":["Spider-Man 2", "Daredevil", "Hulk", "X2"],
},
{
"cat":"Scores & Soundtracks",
"ques":"Who performs the end-credit song 'Into the West' for The Lord of the Rings: The Return of the King?",
"answ":"ANNIE LENNOX",
"answ2":"Annie Lennox.",
"option":["Annie Lennox", "Emilíana Torrini", "Sheila Chandra", "Enya"],
},
];
scoressoundtracks = shuffle(scoressoundtracks);
r2Q9 = shuffle(r2Q9);